OpenAPITools/openapi-generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java
Add model caching in Perl client generator to speed up code gen process. Useful when the spec is huge.
```
``` 
cc @wing328 (2017/07)  @yue9944882 (2019/06)
=> Add model caching in Perl client generator

samples/client/petstore/php/OpenAPIClient-php/tests/ObjectSerializerTest.php
PR #12849 fixed a small bug in ObjectSerializer::deserialize(). As requested [here](https://github.com/OpenAPITools/openapi-generator/pull/12849#issuecomment-1186130098) by @wing328, this PR adds tests for it.
There are two commits here: the first one does some code cleanup to the test class, while the second one adds the new tests.
```
```  …
=> [PHP] ObjectSerializerTest: add tests for ObjectSerializer::deserialize() associative arrays bugfix

modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache, samples/client/petstore/java/webclient-nulable-arrays/src/main/java/org/openapitools/client/api/DefaultApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/DefaultApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/UserApi.java
Fix for https://github.com/OpenAPITools/openapi-generator/issues/12809
This PR gives ability to manually control handling of response. Additional method with `WithResponseSpec` suffix is introduced. This method gives ability to control how different HTTP status is handled. Examples can be checked here - https://github.com/spring-projects/spring-framework/issues/20280
```
```  …
=> [Java][WebClient] return ResponseSpec to manually control response handling

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java, modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache, modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchModelTest.java
The typescript-fetch use `Date` typed properties for date and date-time fields.
The generated interface and factory function looks like this:
```typescript
export interface TheModel {
/**
* 
* @type {Date}
* @memberof TheModel
*/
mandatoryDate: Date;
/**
* 
* @type {Date}
* @memberof TheModel
*/
optionalDate?: Date;
}
export function TheModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TheModel {
if ((json === undefined) || (json === null)) {
return json;
}
return {
'mandatoryDate': (new Date(json['updateDateTime'])),
'optionalDate': !exists(json, 'publicationDateTime') ? undefined : (new Date(json['publicationDateTime'])),
};
}
```
When changing the type mapping with `--type-mappings=date=string,DateTime=string` only the interface changes:
```typescript
export interface …
```
=> [typescript-fetch] date=string type mapping

modules/openapi-generator/src/main/resources/cpp-restbed-server/api-header.mustache, modules/openapi-generator/src/main/resources/cpp-restbed-server/api-source.mustache
If you send a request with a body and a header greater than 255 characters long there will be an exception.
The session->fetch will not return the body in the synchronous way expected.
These changes are relevant to cpp-restbed-server only. @ravinikam @stkrwork @etherealjoy @martindelille @muttleyxd
=> [RestBed] Fix crash in extractBodyContent when using large headers

modules/openapi-generator/src/main/resources/Java/libraries/resteasy/pom.mustache, modules/openapi-generator/src/main/resources/Java/model.mustache, modules/openapi-generator/src/main/resources/Java/pojo.mustache
Commit solves the problem, described here - https://github.com/OpenAPITools/openapi-generator/issues/8134
=> [Java] fix bug that dateLibrary java8 does works now with xml

modules/openapi-generator/src/main/resources/php/api.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
This PR fixes a small bug on api.mustache, where a recent change used double curly braces instead of triple ones. As one can see in the only affected generated sample, the content of  'dataType' should never be HTML-escaped... :wink:
```
``` 
@jebentier, …
=> [PHP] double curly braces bugfix

bin/configs/r-client.yaml, docs/generators/r.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java, modules/openapi-generator/src/main/resources/r/api.mustache
Add option `operationIdNaming` to customize operationId in R client
Naming: PascalCase, camelCase or snake_case
```
``` 
=> Add option to customize operationId in R client

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
Add model caching to PHP generators
```
``` 
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)
=> Add model caching to PHP generators

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/TypeScriptClientCodegenTest.java
resolves #12973
This PR enables `typescript generator` to generate code without throwing any exceptions when `additionalProperty` is explicitly set to `true`, as in the following example.
```yaml
openapi: 3.0.3
components:
schemas:
foo:
properties:
bar:
additionalProperties: true
description: baz
type: object
type: object
info:
title: Repro
version: 1.0.0
paths:
"/":
get:
description: Foo
operationId: getFoo
responses:
'200':
content:
schema:
properties:
foo:
description: Foo.
type: string
required:
- foo
type: object
description: Foo
summary: Foo
tags:
- metadata
```
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD …
=> [typescript] Don't throw exception when `additionalProperties` is set to `true`

modules/openapi-generator/src/main/resources/r/NAMESPACE.mustache, modules/openapi-generator/src/main/resources/r/api.mustache, modules/openapi-generator/src/main/resources/r/api_client.mustache, modules/openapi-generator/src/main/resources/r/description.mustache, samples/client/petstore/R/DESCRIPTION, samples/client/petstore/R/NAMESPACE, samples/client/petstore/R/R/api_client.R, samples/client/petstore/R/R/fake_api.R, samples/client/petstore/R/R/pet_api.R, samples/client/petstore/R/R/store_api.R, samples/client/petstore/R/R/user_api.R, samples/client/petstore/R/build_and_test.bash
Add support for accept, content-type headers in R client
```
``` 
=> Add support for accept, content-type headers in R client

modules/openapi-generator/src/main/resources/r/api.mustache, samples/client/petstore/R/R/fake_api.R, samples/client/petstore/R/R/pet_api.R, samples/client/petstore/R/R/store_api.R, samples/client/petstore/R/R/user_api.R
Prefix local variables in API functions to avoid naming collisions with function parameters.
```
``` 
=> [R] Prefix local variables in API functions to avoid naming collisions

modules/openapi-generator/src/main/resources/r/api.mustache, samples/client/petstore/R/R/pet_api.R, samples/client/petstore/R/tests/testthat/test_petstore.R
Throw exception if username, password is not set in endpoints that require HTTP auth
```
``` 
=> [R] Throw exception if username, password is not set in HTTP auth

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache, samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
We've run into this issue when setting `config.debugging = true`:
```rb
require 'petstore'
api_instance = Petstore::FakeApi.new
Petstore.configure do |config|
config.debugging = true
end
result = api_instance.fake_health_get
```
> D, [2022-07-28T13:52:50.321834 #25054] DEBUG -- : Calling API: FakeApi.fake_health_get ...
> openapi-generator/samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb:115:in `build_request': undefined method `verbose=' for #<Faraday::RequestOptions timeout=60> (NoMethodError)
> 
>       request.options.verbose        = config.debugging      if config.debugging
>                      ^^^^^^^^^^^^^^^^^
Looks like the `verbose` option [comes from typhoeus](https://github.com/OpenAPITools/openapi-generator/blob/79c5091de49a387a65bc87088b45e2be8aa8e484/modules …
=> [Ruby] Remove configuring verbose option from Faraday template

modules/openapi-generator/src/main/resources/typescript-axios/tsconfig.mustache
Fix #12728
typescript-axios generated project does not compile with the supportsES6 option unless "moduleResolution": "node" is added in tsconfig.json
This simple patch add the missing line to tsconfig.json only when supportsES6 is true
@nicokoenig you are listed as the technical committee member for typescript-axios so I'm mentioning you to review this patch as suggested by the guidelines.
```
```  …
=> [BUG] [typescript-axios] Generated project does not compile with the supportsES6 option

modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache, modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml, samples/client/petstore/R-httr2/R/api_client.R, samples/client/petstore/R-httr2/R/pet_api.R, samples/client/petstore/R-httr2/README.md, samples/client/petstore/R-httr2/docs/PetApi.md, samples/client/petstore/R-httr2/tests/testthat/test_petstore.R, samples/client/petstore/R/R/pet_api.R, samples/client/petstore/R/README.md, samples/client/petstore/R/docs/PetApi.md, samples/client/petstore/R/tests/testthat/test_petstore.R
- fix HTTP header (due to a bug in using the variable name as the HTTP header name instead of using the value of the variable)
- add tests
```
``` 
=> [R][httr2] fix HTTP header

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonExperimentalClientTest.java, modules/openapi-generator/src/test/resources/3_0/issue_13043_recursive_model.yaml, modules/openapi-generator/src/test/resources/3_0/issue_13043_recursive_model_expected_value.txt
In PythonExperimentalClientCodegen:
* Added a function to isolate the addition of schemas to the included schema list.  This function will throw an exception if a schema is added twice (an error condition).
* add composed schemas to the included shemas list (thanks @spacether)
* terminate recursion for anyType if a cycle is found (thanks @spacether )
* moved a call to addSchemasToIncludedSchemaList outside of the for loop in 'exampleForObjectModel'
* added unit test with spec to reproduce this bug
```
```  …
=> Issue 13043: [python-experimental] Fixed stackoverflow error in toExampleValueRecursive 

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java
Converted an exception to a warning when doubly adding schemas to the includedSchemas list.  Rather than crashing, the code will issue a warning and proceed.
```
``` 
@spacether
=> Issue 13043: converted an exception to a warning

modules/openapi-generator/src/main/resources/r/api.mustache, modules/openapi-generator/src/main/resources/r/api_client.mustache, modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache, samples/client/petstore/R-httr2/R/api_client.R, samples/client/petstore/R-httr2/R/fake_api.R, samples/client/petstore/R-httr2/R/pet_api.R, samples/client/petstore/R-httr2/R/store_api.R, samples/client/petstore/R-httr2/R/user_api.R, samples/client/petstore/R-httr2/tests/testthat/test_petstore.R, samples/client/petstore/R/R/api_client.R, samples/client/petstore/R/R/fake_api.R, samples/client/petstore/R/R/pet_api.R, samples/client/petstore/R/R/store_api.R, samples/client/petstore/R/R/user_api.R, samples/client/petstore/R/tests/testthat/test_petstore.R
- Fix form parameter support
- add tests
```
``` 
=> [R][httr2] Fix form parameter support

modules/openapi-generator/src/main/resources/rust/Cargo.mustache, samples/client/petstore/rust/reqwest/petstore-awsv4signature/Cargo.toml
When supportAsync and withAWSV4Signature are both enabled, the generate `Cargo.toml` will contain the following code:
```
[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde"] }
[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]
aws-sigv4 = "0.3.0"
http = "0.2.5"
secrecy = "0.8.0"
```
The last 3 lines become children of `[dependencies.reqwest]` which can cause compile errors.
```
``` 
You may …
=> [rust] fix incorrect Cargo.toml generated when supportAsync & withAWSV4Signature are both enabled.

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
apache-httpclient serialize support custom contentType
```
public MultipartEntityBuilder addTextBody(
final String name, final String text) {
return addTextBody(name, text, ContentType.DEFAULT_TEXT);
}
```
**org.apache.http.entity.mime.MultipartEntityBuilder#addTextBody(java.lang.String, java.lang.String)**  addTextBody with 
ContentType.DEFAULT_TEXT ;
```
public static final ContentType TEXT_PLAIN = create(
"text/plain", Consts.ISO_8859_1);
public static final ContentType DEFAULT_TEXT = TEXT_PLAIN;
``` 
charset of "ISO-8859-1" can not handle with  chinese characters, so it is nessary to support custom contentType.
same to  UrlEncodedFormEntity
```
``` 
This is important, as CI …
=> [Java] apache-httpclient serialize support custom contentType

modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache
Small fix to `modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache` (PHP Symfony generator) to fix variable typo in validation annotations
=> Update php-symfony/model_variables.mustache to fix template bug (#13060)

modules/openapi-generator/src/main/resources/python-experimental/schemas.handlebars, samples/openapi3/client/3_0_3_unit_test/python-experimental/unit_test_api/schemas.py, samples/openapi3/client/petstore/python-experimental/petstore_api/schemas.py
There is a print statement which should be removed
```
``` 
=> [python-experimental] removes print

modules/openapi-generator/src/main/resources/r/api.mustache, samples/client/petstore/R-httr2/R/fake_api.R, samples/client/petstore/R-httr2/R/pet_api.R, samples/client/petstore/R-httr2/R/store_api.R, samples/client/petstore/R-httr2/R/user_api.R, samples/client/petstore/R/R/fake_api.R, samples/client/petstore/R/R/pet_api.R, samples/client/petstore/R/R/store_api.R, samples/client/petstore/R/R/user_api.R
- Better validation for R client parameters
```
``` 
FYI @Ramanth (2019/07) @saigiridhar21 (2019/07)
=> Better validation for R client parameters

modules/openapi-generator/src/main/resources/csharp-netcore/ClientUtils.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache, samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Api/MultipartApi.cs, samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ClientUtils.cs
In the current csharp-netcore generator objects passed as multipart form-data are treated as primitive type and converted to string. With this changes it will also be possible to pass non-primitive objects that will be serialized as JSON, similar to how it is done in the `csharp` generator: https://github.com/OpenAPITools/openapi-generator/blob/eeb1711f9f073a90b62e4d0fa2ecf81b51a13281/modules/openapi-generator/src/main/resources/csharp/api.mustache#L272
Example specification supported now with the changes:
```yaml
...
paths:
/upload:
post:
requestBody:
content:
schema:
$ref: '#/components/schemas/UploadsRequest'
components:
schemas:
UploadsRequest:
type: object
properties:
config:
$ref: '#/components/schemas/UploadConfig'
file:
type: string
format: binary …
```
=> [csharp-netcore] Form data serialize non-primitive objects

docs/generators/kotlin-server.md, docs/generators/kotlin-spring.md, docs/generators/kotlin-vertx.md, docs/generators/kotlin.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
resolves #13010
Kotlin generators generate code that cannot be compiled if the enum value `contract` is present, as in the example below. So, I added `contract` to reserved words.
- Example
```yml
openapi: "3.0.3"
info:
title: "Kotlin"
version: "1"
paths:
/users:
get:
responses:
'200':
description: test
content:
schema:
$ref: '#/components/schemas/Response'
components:
schemas:
Response:
type: object
properties:
id:
type: string
value:
type: string
enum:
- contract
- var
- val
```
```
```  …
=> [Kotlin] Add reserved word `contract`

modules/openapi-generator/src/main/resources/r/api.mustache, modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache, samples/client/petstore/R-httr2/R/api_client.R, samples/client/petstore/R-httr2/R/pet_api.R, samples/client/petstore/R/R/pet_api.R
Skip client id, secret validation to allow multiple auth schemas
```
``` 
=> [R] Skip client id, secret validation to allow multiple auth schemas

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonExperimentalClientTest.java, modules/openapi-generator/src/test/resources/3_0/issue_13043_geometry_collection_expected_value.txt, modules/openapi-generator/src/test/resources/3_0/issue_13043_recursive_model.yaml
Converted Exception to a warning when a Schema is doubly added to the includedSchemas list
Broke recursion in a more reasonable place when generating example values
```
``` 
=> Issue 13043: Improved handling of recursive schemas

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
Moving this logic so that a generator option that is processed in an overriden processOpts which is called in configureGeneratorProperties() can influence the useInlineModelResolver.
Should this logic be inside the configureGeneratorProperties method after processing opts but before pre processing the api?
Or should it be in the generate method but after calling configureGeneratorProperties and configureOpenAPIInfo?
Merely opening this PR to have a discussion about this and which location for this logic would be preferable.
@spacether The only reason it "works" in the Python generator is because the default is false
@wing328 
```
``` 
This is important, as CI jobs will verify …
=> Allow useInlineModelResolver to be influenced by generator options

modules/openapi-generator/src/main/resources/typescript-axios/common.mustache, samples/client/petstore/typescript-axios/builds/composed-schemas/common.ts, samples/client/petstore/typescript-axios/builds/default/common.ts, samples/client/petstore/typescript-axios/builds/es6-target/common.ts, samples/client/petstore/typescript-axios/builds/test-petstore/common.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/common.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/common.ts, samples/client/petstore/typescript-axios/builds/with-interfaces/common.ts, samples/client/petstore/typescript-axios/builds/with-node-imports/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version/common.ts, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/common.ts, samples/client/petstore/typescript-axios/builds/with-string-enums/common.ts
Fixes https://github.com/OpenAPITools/openapi-generator/issues/12887
```typescript
setSearchParams( url, {pageable: {size:10, page: 2}})
```
would result in 
```
/cool/api/?pageable=%5Bobject+Object%5D
```
```typescript
setSearchParams( url, {pageable: {size:10, page: 2}})
```
would result in 
```
/cool/api/?pageable.size=10&pageable.page=2
```
@mkusaka @davidgamero kindly review the changes if they are at the right place. Thanks!
```
```  …
=> [#12887] typescript-axios: nested object as query parameter

modules/openapi-generator/src/main/resources/typescript-axios/common.mustache, samples/client/petstore/typescript-axios/builds/composed-schemas/common.ts, samples/client/petstore/typescript-axios/builds/default/common.ts, samples/client/petstore/typescript-axios/builds/es6-target/common.ts, samples/client/petstore/typescript-axios/builds/test-petstore/common.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/common.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/common.ts, samples/client/petstore/typescript-axios/builds/with-interfaces/common.ts, samples/client/petstore/typescript-axios/builds/with-node-imports/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version/common.ts, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/common.ts, samples/client/petstore/typescript-axios/builds/with-string-enums/common.ts
Referring to a recently merged PR - https://github.com/OpenAPITools/openapi-generator/pull/13051
@macjohnny The current output with the above merge is little buggy:
`cool/api?.pageable.page=10&.pageable.size=20`
There is a "." before every parameter. The fix for "." prefix before every query parameter is added.
```
``` 
For Windows …
=> [Typescript-axios] Dot prefix on every query parameter

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java, modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache, modules/openapi-generator/src/main/resources/rust-server/client-operation.mustache, modules/openapi-generator/src/main/resources/rust-server/lib.mustache
Cleaned up cargo clippy warnings rather than explicitly allowing them.
@frol
@farcaller
@richardwhiuk
@paladinzh
```
``` 
=> Cleaned up cargo clippy warnings

modules/openapi-generator/src/main/resources/typescript/api/api.mustache, samples/client/others/typescript/builds/with-unique-items/apis/DefaultApi.ts, samples/openapi3/client/petstore/typescript/builds/browser/apis/PetApi.ts, samples/openapi3/client/petstore/typescript/builds/browser/apis/StoreApi.ts, samples/openapi3/client/petstore/typescript/builds/browser/apis/UserApi.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/apis/DefaultApi.ts, samples/openapi3/client/petstore/typescript/builds/default/apis/PetApi.ts, samples/openapi3/client/petstore/typescript/builds/default/apis/StoreApi.ts, samples/openapi3/client/petstore/typescript/builds/default/apis/UserApi.ts, samples/openapi3/client/petstore/typescript/builds/deno/apis/PetApi.ts, samples/openapi3/client/petstore/typescript/builds/deno/apis/StoreApi.ts, samples/openapi3/client/petstore/typescript/builds/deno/apis/UserApi.ts, samples/openapi3/client/petstore/typescript/builds/inversify/apis/PetApi.ts, samples/openapi3/client/petstore/typescript/builds/inversify/apis/StoreApi.ts, samples/openapi3/client/petstore/typescript/builds/inversify/apis/UserApi.ts, samples/openapi3/client/petstore/typescript/builds/jquery/apis/PetApi.ts, samples/openapi3/client/petstore/typescript/builds/jquery/apis/StoreApi.ts, samples/openapi3/client/petstore/typescript/builds/jquery/apis/UserApi.ts, samples/openapi3/client/petstore/typescript/builds/object_params/apis/PetApi.ts, samples/openapi3/client/petstore/typescript/builds/object_params/apis/StoreApi.ts, samples/openapi3/client/petstore/typescript/builds/object_params/apis/UserApi.ts
This fixes OpenAPITools/openapi-generator#11288.
```
``` 
=> Fix missing import in `api.mustache` for Typescript generator

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache, samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
Faraday 0.16.0 added Faraday::FilePart as an alias to Faraday::UploadIO and deprecated Faraday::UploadIO. In Faraday 2.0 the deprecated UploadIO was removed.
Fixes: e12100b033c13b835fc3b3f1de159dc7f4634fc0
cc @cliffano @zlx @autopp
```
``` 
=> Replace use of deprecated Faraday::UploadIO

modules/openapi-generator/src/main/resources/rust/model.mustache
Fix the case where a model is nullable (unwrap Option before Boxing it).
```
``` 
@frol, @farcaller, @richardwhiuk,  @paladinzh ^
Cheers!
=> Fix template for nullable models in rust new() fns

modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache, samples/client/petstore/R-httr2/R/api_client.R, samples/client/petstore/R-httr2/tests/testthat/test_petstore.R
- allow oauth scopes customization
- remove unused import
```
``` 
=> [R] allow oauth scopes customization, remove unused import

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java, modules/openapi-generator/src/test/resources/3_0/issues_13069.yaml, samples/client/petstore/python/docs/FakeApi.md, samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/docs/FakeApi.md, samples/openapi3/client/petstore/python/docs/FakeApi.md
The previous regular expression was too open, including any last character in the second group. This commit fixes that, making sure we only remove leading forward slashes, trailing forward slashes or trailing `\i`.
Added a UT that failed prior to this change and edited an existing UT to cover the case where the regex field is not a first class citizen but instead a property inside an object (or Schema).
You can see the original issue for more details.
This commit closes [13069](https://github.com/OpenAPITools/openapi-generator/issues/13069).
**Weird things for reviewers to pay attention to:**
1.  In the testRegexObjects there is an assert that the `property1.pattern` was appended with the leading and trailing slashes (this is done in DefaultCodegen#toRegularExpression). However, if we …
=> Fixed regular expression in python client codegen that was removing any trailing chars instead of only expected ones

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue13146_file_abstraction_response.yaml
…in operation response for rest template
Implements feature https://github.com/OpenAPITools/openapi-generator/issues/13146
```
``` 
=> feat: [JAVA] [resttemplate] [#13146] added support for abstract file

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java, modules/openapi-generator/src/main/resources/scala-sttp/model.mustache
This PR fixed [the issue 10055](https://github.com/OpenAPITools/openapi-generator/issues/10055) 
Here is the openapi spec to reproduce the issue and verify the fix.
```
openapi: 3.0.3
info:
title: array item is enum
version: '1.0'
paths:
/state:
get:
operationId: getUserReport
responses:
'200':
description: get Users
content:
schema:
$ref: '#/components/schemas/Users'
components:
schemas:
Users:
properties:
emails:
items:
type: string
type: array
search:
enum:
- first_name
- last_name
- email
- full_name
type: string
sort_by:
items:
enum:
- first_name
- last_name
- email
type: string
type: array
type: object
```
```
```  …
=> [scala][sttp]fix enum generation for inline-enum of array

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
=> [csharp-netcore] Use type names as the keys of the enum reference map

docs/generators/cpp-pistache-server.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
Add support for AnyType objects to fix a compile-time error when generating code for an arbitrary typed object:
```
arrayOfSomething:
type: array
items: {}
```
Replace `AnyType` with `nlohmann::json` so that the correct type can be manually unpacked later. This JSON library is already used in the [cpp-pistache-server templates](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/cpp-pistache-server)
- Related:
- #12641
- #12642
- #10266
- #7458
- #6332
- #7617
```
``` 
These must match the expectations made …
=> [cpp-pistache-server]: Add support for AnyType objects

modules/openapi-generator/src/main/resources/python/model_templates/methods_shared.mustache, samples/client/petstore/python/petstore_api/model_utils.py, samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/model_utils.py, samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/model_utils.py, samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/model_utils.py, samples/openapi3/client/petstore/python/petstore_api/model_utils.py, samples/openapi3/client/petstore/python/tests_manual/test_copy.py
This PR solve the issue describe in https://github.com/OpenAPITools/openapi-generator/issues/13129.
The deepcopy function throws a ApiValueError (`Cannot deserialize input data due to missing discriminator. The discriminator property 'className' is missing at path: ()`) for some models with AllOf in schema e.g.,  `from petstore_api.model.dog import Dog`.
```
```  …
=> fix deepcopy for allOf schemas

modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-header.mustache, modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-source.mustache
Add support generating code for an enum when use "--additional-properties=useStructModel=true"
```
TestEnum:
type: string
enum: 
- Value1
- Value2
```
Command: `openapi-generator-cli.jar generate -g cpp-pistache-server --additional-properties=useStructModel=true`
```
```  …
=> [cpp-pistache-server] Fix enum generation for mode useStructModel=true

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
Issue [#13139](https://github.com/OpenAPITools/openapi-generator/issues/13139)
```
``` 
=> Allow override CodegenConfigurator in GenerateTask

modules/openapi-generator/src/main/resources/csharp-netcore/modelAnyOf.mustache
* fixes issue [#13170 ](https://github.com/OpenAPITools/openapi-generator/issues/13170) : fixed null-coalescing operator incorrectly used for primitive types with the same changes than @jafin made in https://github.com/OpenAPITools/openapi-generator/pull/11427
```
``` 
**"nothing to commit", it appears there is no change in either petstore sample or docs.**
_I am not really used to github, feel free to advise if I should change something for the PR._
=> fix: [csharp-netcore]: anyOf fixes for Primitive types

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
Fixes #13201 see bug report for details about the issue
To validate the work run the OpenApi spec provided in the bug report.
Then check that `/output-folder/model/foo.ts` have the correctly path to import the `Model1st` interface. It should be `from './model1st';`
```
```  …
=> fix: [typescript-angular] incorrect import when model starts with number

modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache, modules/openapi-generator/src/test/resources/integrationtests/typescript/petstore-expected/api/pet.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api/pet.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api/pet.service.ts, samples/client/petstore/typescript-angular-v14-provided-in-root/builds/default/api/pet.service.ts
Fixes #11782 see bug report for details about the issue
To validate the work run
```bash
-i https://raw.githubusercontent.com/snebjorn/openapi-gen-bug/master/join-bug.json \
-g typescript-angular \
-o output-master/join-bug
```
and check that all `.join` calls in a service (`api/default.service.ts`) are valid typescript. Meaning that it no longer calls `.join` directly on a `Set`.
```
```  …
=> fix: [typescript-angular] `.join` does not exist on type `Set`

modules/openapi-generator/src/main/resources/r/api.mustache
Fix return in R when response message is empty (returnExceptionOnFailure not enabled)
```
``` 
=> Fix return in R when response message is empty

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java, samples/config/petstore/protobuf-schema/models/other_test.proto
- Fix protobuf variable name to avoid turning `_` into `Underscore`
- Minor code format enhancement
- To fix https://github.com/OpenAPITools/openapi-generator/issues/9544
```
``` 
=> Fix protobuf variable name

modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache
The javascript in the index.mustache file from the html2 module had a syntax error where the closure and forEach method were not closed properly which led to javascript errors in the generated html.
```
``` 
=> Fix for issue #13272 - Syntax error in generated html

modules/openapi-generator/src/main/resources/r/api.mustache, samples/client/petstore/R-httr2-wrapper/R/pet_api.R, samples/client/petstore/R-httr2/R/pet_api.R, samples/client/petstore/R/R/pet_api.R, samples/client/petstore/R/tests/testthat/test_petstore.R
Fix http basic auth in R client by not throwing error when username/password is not provided to support endpoints with multi-auth schemas defined.
To close https://github.com/OpenAPITools/openapi-generator/issues/13328
```
``` 
cc @Ramanth (2019/07) …
=> Fix http basic auth in R client

modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache, samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiClient.java
Fixes #13327 
Ensure Resteasy JAX-RS Response object closed by using try-with-resources block.
```
``` 
cc: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608
=> fix: ensure Resteasy JAX-RS Response object closed

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
In case the lifecycle phase is `generate-test-sources` the default output directory is:
`"${project.build.directory}/generated-test-sources/openapi"`
In case of any other lifecycle phase the default output directory is:
`"${project.build.directory}/generated-sources/openapi"`
Also use the `src/main/java` as the only default source folder in the output path for both
cases when `addCompileSourceRoot == true` and when `addTestCompileSourceRoot == true`.
In case you really need `src/test/java` it still can be set in the configOptions manually:
```xml
<configOptions>
<sourceFolder>src/test/java</sourceFolder>
</configOptions>
```
This PR fixes #13152
=> [maven] Use one of two default paths of output directory according to the lifecycle phase

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
Update allVars to handle empty string, include R doc type extension.
Previously these enhancements were made to `vars` only.
```
``` 
=> [R] update allVars to handle empty string, include R doc type extension

modules/openapi-generator/src/main/resources/r/modelGeneric.mustache, modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml, samples/client/petstore/R-httr2-wrapper/R/date.R, samples/client/petstore/R-httr2-wrapper/docs/Date.md, samples/client/petstore/R-httr2/R/date.R, samples/client/petstore/R-httr2/docs/Date.md, samples/client/petstore/R/R/date.R, samples/client/petstore/R/docs/Date.md
- Escape % in description in R model @field to address rdoc warning.
- Add a test
```
``` 
=> Escape % in description in R model @field

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache, modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache, samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts, samples/client/petstore/typescript-fetch/builds/default/runtime.ts, samples/client/petstore/typescript-fetch/builds/enum/runtime.ts, samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts, samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts, samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts, samples/client/petstore/typescript-rxjs/builds/default/runtime.ts, samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts, samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts, samples/client/petstore/typescript-rxjs/builds/with-progress-subscriber/runtime.ts
Fixes #12948
```
``` 
FYI as instructed @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo  @amakhrov @davidgamero @mkusaka
=> Mark overrides in typescript-fetch and typescript-rxjs

modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
Hi @wing328 @zhemant @michelealbano
When a field of a JSON map is null, e.g. in below example, `annotations` of  `metadata` is null
```json
{
"apiVersion": "v1",
"kind": "ServiceAccount",
"metadata": {
"name": "test-sa",
"namespace": "smoking-test",
"annotations": null
}
}
```
`*_parseFromJSON` will treat `annotations` as invalid/error, and free the total memory of `metadata` 
The detail is at https://github.com/kubernetes-client/c/issues/138
This PR treats "null" as a valid value for a field of a JSON map.
```
```  …
=> [C][Client] Treat "null" as a valid value for a field of a JSON map

modules/openapi-generator/src/main/resources/Java/libraries/feign/auth/OAuth.mustache, samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/auth/OAuth.java, samples/client/petstore/java/feign/src/main/java/org/openapitools/client/auth/OAuth.java
Hi @wing328 @bbdouglas @sreeshas, @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608,
this is my proposed fix for https://github.com/OpenAPITools/openapi-generator/issues/13339
The Java OAuth RequestInterceptor implementation for Feign currently verifies if a previously obtained access token needs to be renewed by checking if `System.currentTimeMillis()` is greater than `expirationTimeSeconds`. This causes a new access token to be requested for each interaction. Converting `expirationTimeSeconds` to milliseconds should fix this. 
```
```  …
=> [Java][Feign] convert expirationTimeSeconds to milliseconds

pom.xml
Update jackson-databind to newer version 2.13.4
To fix https://github.com/OpenAPITools/openapi-generator/issues/13388
```
``` 
FYI. @OpenAPITools/generator-core-team
=> Update jackson-databind to newer version

docs/generators/php-dt.md, docs/generators/php-laravel.md, docs/generators/php-lumen.md, docs/generators/php-mezzio-ph.md, docs/generators/php-slim-deprecated.md, docs/generators/php-slim4.md, docs/generators/php-symfony.md, docs/generators/php.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpDataTransferClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpLaravelServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpMezzioPathHandlerServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSilexServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java, samples/client/petstore/php/OpenAPIClient-php/docs/Api/FakeApi.md, samples/client/petstore/php/OpenAPIClient-php/docs/Model/EnumTest.md, samples/client/petstore/php/OpenAPIClient-php/docs/Model/FormatTest.md, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Model/EnumTest.php, samples/client/petstore/php/OpenAPIClient-php/lib/Model/FormatTest.php, samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php, samples/server/petstore/php-laravel/lib/app/Models/EnumTest.php, samples/server/petstore/php-laravel/lib/app/Models/FormatTest.php
Fixes #13335 
Fixes inconsistent treating of double as a native type in php. Removes type from native primitives and consistently fixes the map in the AbstractPhpCodegen class 
References:
https://docs.phpdoc.org/3.0/guide/guides/types.html#primitives
http://php.net/manual/en/language.types.intro.php
https://www.php.net/manual/en/language.types.float.php
@jebentier  @dkarlovi @mandrean @jfastnacht @ybelenko @renepardon 
```
```  …
=> Fix php generators treating double as a native type

modules/openapi-generator/src/main/resources/r/api.mustache, modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml, samples/client/petstore/R-httr2-wrapper/R/fake_api.R, samples/client/petstore/R-httr2-wrapper/README.md, samples/client/petstore/R-httr2-wrapper/docs/FakeApi.md, samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R, samples/client/petstore/R-httr2/R/fake_api.R, samples/client/petstore/R-httr2/README.md, samples/client/petstore/R-httr2/docs/FakeApi.md, samples/client/petstore/R/R/fake_api.R, samples/client/petstore/R/README.md, samples/client/petstore/R/docs/FakeApi.md
- Support set in R client parameters (query)
- Add tests
```
``` 
=> Support set in R client parameters

modules/openapi-generator/src/main/resources/r/modelGeneric.mustache, modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml, samples/client/petstore/R-httr2-wrapper/R/special.R, samples/client/petstore/R-httr2-wrapper/docs/Special.md, samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R, samples/client/petstore/R-httr2/R/special.R, samples/client/petstore/R-httr2/docs/Special.md, samples/client/petstore/R/R/special.R, samples/client/petstore/R/docs/Special.md
- Add set support to model properties in R client
- minor refactoring in the template
- add tests
```
``` 
=> Add set support to model properties in R client

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
https://github.com/OpenAPITools/openapi-generator/pull/11911 broke file upload with form data.
This PR fixes it.
```
``` 
@jimschubert (2017/09) [❤️](https://www.patreon.com/jimschubert), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) …
=> [kotlin][client] fix file upload with okhttp

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java
Fixes #9386
When using generators `python-flask`and `python-aiohttp`, the generated test body boolean values reads now as follows ("True" or "False"):
```python
body = {
"boolean_property": True
}
```
Previous buggy generated code:
```python
body = {
"boolean_property": true
}
```
Most of the code is copy-paste from generator `python-fastapi`(PythonFastAPIServerCodegen.java)
Steps to see the new generated code:
```console
-i modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
-g python-flask \
-o /var/tmp/python-flask
cat /var/tmp/python-flask/openapi_server/test/test_store_controller.py
-i …
```
=> [fix][python-flask][python-aiohttp]: incorrect boolean literal in unit tests

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pojo.mustache, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/model/FileSchemaTestClass.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/model/Pet.java, samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/model/Pet.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/model/FileSchemaTestClass.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/model/Pet.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ArrayOfInlineAllOf.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Drawing.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/FileSchemaTestClass.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Pet.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/PetWithRequiredTags.java
```
``` 
- Fix for https://github.com/OpenAPITools/openapi-generator/issues/13446
- applicable for next patch release (6.1.1?)
=> [JAVA] fix ClassCastException validating an optional JsonArray with null

modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache, modules/openapi-generator/src/test/resources/integrationtests/typescript/additional-properties-expected/api/user.service.ts, modules/openapi-generator/src/test/resources/integrationtests/typescript/array-and-object-expected/api/project.service.ts, modules/openapi-generator/src/test/resources/integrationtests/typescript/custom-path-params-expected/api/matrixParams.service.ts, modules/openapi-generator/src/test/resources/integrationtests/typescript/petstore-expected/api/pet.service.ts, modules/openapi-generator/src/test/resources/integrationtests/typescript/petstore-expected/api/store.service.ts, modules/openapi-generator/src/test/resources/integrationtests/typescript/petstore-expected/api/user.service.ts, samples/client/petstore/typescript-angular-v12-oneOf/builds/default/api/default.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api/store.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api/user.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api/store.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api/user.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api/pet.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api/store.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api/user.service.ts, samples/client/petstore/typescript-angular-v13-oneOf/builds/default/api/default.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api/store.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api/user.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api/store.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api/user.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api/pet.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api/store.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api/user.service.ts, samples/client/petstore/typescript-angular-v14-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-angular-v14-provided-in-root/builds/default/api/store.service.ts, samples/client/petstore/typescript-angular-v14-provided-in-root/builds/default/api/user.service.ts
Fixes https://github.com/OpenAPITools/openapi-generator/issues/13380
This has somewhat long history:
- Earlier bug reports back in 2020: https://github.com/OpenAPITools/openapi-generator/issues/7557
- An attempt to fix the `isBodyAllowed` populated by the Java code: https://github.com/OpenAPITools/openapi-generator/pull/10751 .
- That PR resulted in broken generated TypeScript code (https://github.com/OpenAPITools/openapi-generator/issues/10975, https://github.com/OpenAPITools/openapi-generator/issues/10864) and was later reverted. This was unfortunate, because in its core, that PR did the right thing
The approach implemented in this PR only affects typescript-angular generator. Generated code uses [`HttpClient#request`](https://angular.io/api/common/http/HttpClient#request) directly …
=> [typescript-angular] Support body for DELETE requests

modules/openapi-generator/src/main/resources/dart2/serialization/native/native_enum.mustache, modules/openapi-generator/src/main/resources/dart2/serialization/native/native_enum_inline.mustache, samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/model/order.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/model/pet.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/enum_arrays.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/enum_class.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/enum_test.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/map_test.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/order.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_enum.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_enum_default_value.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_enum_integer.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_enum_integer_default_value.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/pet.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/single_ref_type.dart
Fixes #12167
The template files for enum TypeTransformers included a `data.toString()` function that wasn't valid for non-string enums. The result was syntactically incorrect Dart files that wouldn't compile.
This PR removes the method call.
The following specfile can be used to confirm:
<details>
<summary>specfile</summary>
```yaml
openapi: 3.0.3
info:
version: "1.1"
title: Dart Uint8list Demo
servers:
- url: "localhost"
variables:
host:
default: localhost
paths:
/item:
get:
operationId: GetItem
description: "Should return an Item"
responses:
"200":
description: items
content:
schema:
$ref: "#components/schemas/item"
components:
schemas:
Item:
type: object
description: "Some json thing"
required:
- strChoice
- intChoice
properties:
strChoice:
$ref: …
```
=> [Dart] Remove toString() call in enum TypeTransformers

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
Support for international letters like øæå in enums and variablenames. Before they was santized with a "_" letter.
```
``` 
=> [Kotlin] Support for international letters like øæå.

modules/openapi-generator/src/main/resources/php/api.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
The current version of the PHP generator does not support ranged status codes since they are treated as `int` in the switch case statements. Hence I did get some `PHP Parse error:  syntax error, unexpected 'XX' (T_STRING) in` errors. This PR removes ranged status codes from the switch-case statements
```
``` 
For Windows users, please …
=> PHP: fix ranged status codes

.travis.yml
Fix travis docker push during version release
Will confirm this fix as part of the v6.2.0 release.
```
``` 
=> Fix travis docker push during version release

modules/openapi-generator/src/main/resources/elixir/api.mustache, samples/client/petstore/elixir/lib/openapi_petstore/api/fake.ex, samples/client/petstore/elixir/lib/openapi_petstore/api/pet.ex
@mrmstn
While working with the Magento 2.4 API definition to generate an Elixir client, there were several issues found. The easiest to resolve is a documentation naming issue. (The others will be raised for discussion.)
This is known to be an issue with query parameters, but may not be limited to *just* query parameters.
In the event that a parameter is a mix of arrays and objects, the template in the documentation for the API function was expanding out the parameter name such that `foo[0]` would be turned into `:foo_left_square_bracket0_right_square_bracket`, but the actual parameter name was being left as `:foo[0]`, which meant that the documentation did not reflect the actual parameter.
> Note: there are issues with the way that query parameters are put
> together in this sense, which …
=> Elixir: Improve generated API options docs

modules/openapi-generator/src/main/resources/swift5/Configuration.mustache, modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache, samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift, samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Configuration.swift
This is a solution for the problem described in #11629 
Adds ability for injection of custom ResponseSerializers into Alamofire library version of the generator. This is useful for many use cases like adjusting the empty response codes which default to [204, 205] otherwise. 
If Configuration remains unchanged, behavior of the generated code is the same as before. 
Because we can't make use of Swift 5.7 language feature [`any`](https://www.donnywals.com/what-is-the-any-keyword-in-swift/), unfortunately we have to use type erasure in order to use `ResponseSerializer` as a type in the `Configuration`
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of …
=> [swift5] [alamofire] adds ability to inject custom response serializers

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java, modules/openapi-generator/src/main/resources/typescript-axios/package.mustache, modules/openapi-generator/src/main/resources/typescript-axios/tsconfig.esm.mustache, modules/openapi-generator/src/main/resources/typescript-axios/tsconfig.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/axios/TypeScriptAxiosClientCodegenTest.java, samples/client/petstore/typescript-axios/builds/es6-target/.openapi-generator/FILES, samples/client/petstore/typescript-axios/builds/es6-target/package.json, samples/client/petstore/typescript-axios/builds/es6-target/tsconfig.esm.json, samples/client/petstore/typescript-axios/builds/es6-target/tsconfig.json, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/package.json, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/tsconfig.json, samples/client/petstore/typescript-axios/builds/with-npm-version/package.json, samples/client/petstore/typescript-axios/builds/with-npm-version/tsconfig.json
fix https://github.com/OpenAPITools/openapi-generator/issues/12828
An additional tsconfig.esm.json is added to every generated typescript-axios code having supportsES6 and npmName.
That will create an additional ECMAScript Module (ESM) to the npm build.
I used similar PR for `typescript-fetch` client as reference https://github.com/OpenAPITools/openapi-generator/pull/11720
```
```  …
=> [typescript-axios] / #12828: Add ESM support to typescript-axios client

modules/openapi-generator/src/main/resources/swift5/api.mustache, modules/openapi-generator/src/test/resources/2_0/swift/petstore-with-fake-endpoints-models-for-testing.yaml, samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/alamofireLibrary/docs/PetAPI.md, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/docs/PetAPI.md, samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/combineLibrary/docs/PetAPI.md, samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/frozenEnums/docs/PetAPI.md, samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/nonPublicApi/docs/PetAPI.md, samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/objcCompatible/docs/PetAPI.md, samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/promisekitLibrary/docs/PetAPI.md, samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/readonlyProperties/docs/PetAPI.md, samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/resultLibrary/docs/PetAPI.md, samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/rxswiftLibrary/docs/PetAPI.md, samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/APIs/PetAPI.swift, samples/client/petstore/swift5/urlsessionLibrary/docs/PetAPI.md, samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/x-swift-hashable/docs/PetAPI.md
This PR fixes #13613:
- Uses the correct mustache variable to check for the need for authentication of an endpoint
- updated samples to have one endpoint where multiple security schemes are being used  
Verification of the fix can be done either manually via provided swagger from bug report or via updated sample spec. Without the fix `truetrue` is being generated, with the fix just `true` as expected
Updated mustache file from this PR can be provided via the generator cli option `-t` to have it working for 6.2.0 for now
```
```  …
=> [swift5] fix generation of multiple security definitions

modules/openapi-generator/src/main/resources/swift5/Models.mustache, modules/openapi-generator/src/main/resources/swift5/api.mustache, samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/AnotherFakeAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeClassnameTags123API.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/StoreAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/UserAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Models.swift, samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/Models.swift, samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/Models.swift
Fixes Xcode 14 warning: `Capture of with non-sendable type in a `@Sendable` closure withTaskCancellationHandler`
```
``` 
=> [swift][client] fix xcode warning

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Don't pass `Content-Type: application/json` when passing a `null` body for `POST`/etc request in Kotlin.
```
``` 
=> [kotlin] Fix empty body with POST/etc in OkHttp client

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerDeprecatedCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
A first try to reduce code smells. I've take a reduce scope with only kotlin generators.
@jimschubert (2017/09) heart, @dr4ke616 (2018/08) @karismann (2019/03) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)
```
``` 
=> [Kotlin]Reducing code smells

docs/generators/typescript.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
Resolves #13724 
```
``` 
@mkusaka
@davidgamero
@amakhrov
@petejohansonxo
@akehir
@topce
@macjohnny
@Vrolijkx
@kenisteward
@sebastianhaas
@taxpon
@TiFu
=> [#13724][BUG][Typescript] Add 'constructor' to reserved words for Typescript Client

modules/openapi-generator/src/main/resources/python-flask/model.mustache, samples/server/petstore/python-flask/openapi_server/models/api_response.py, samples/server/petstore/python-flask/openapi_server/models/category.py, samples/server/petstore/python-flask/openapi_server/models/order.py, samples/server/petstore/python-flask/openapi_server/models/pet.py, samples/server/petstore/python-flask/openapi_server/models/tag.py, samples/server/petstore/python-flask/openapi_server/models/user.py
Reverts OpenAPITools/openapi-generator#6911
Because the source PR broke from_dict functionality
https://github.com/OpenAPITools/openapi-generator/pull/6911#issuecomment-667245941
=> Revert "Fix #6899 - python-flask now uses the pre-existing getter/setter validators"

modules/openapi-generator/src/main/resources/python/model_templates/schema_composed_or_anytype.handlebars
[python] fixes required prop in composed schemas, prop not in properties, addProps unset
Note: this fix came from https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/55 and
https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/54
```
```  …
=> [python] fixes required prop in composed schema, prop not in properties, addProps unset

modules/openapi-generator/src/main/resources/php/HeaderSelector.mustache, modules/openapi-generator/src/main/resources/php/api.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/HeaderSelector.php, samples/client/petstore/php/OpenAPIClient-php/tests/HeaderSelectorTest.php
The current HeaderSelector class is handling Content-Type incorrectly:
1. When there are multiple Content types in the OpenAPI Definition and none are of type application/json, it is concatenating them. This is explicitly described as incorrect in IETF RFC9110, section 8.3, last paragraph:
> Although Content-Type is defined as a singleton field, it is sometimes incorrectly generated multiple times, resulting in a combined field value that appears to be a list. Recipients often attempt to handle this error by using the last syntactically valid member of the list, leading to potential interoperability and security issues if different implementations have different error handling behaviors.
2. If any of the multiple content types contains "application/json", then it will always set the …
=> [PHP] Allow selecting Content-Type

modules/openapi-generator/src/main/resources/rust/Cargo.mustache, samples/client/petstore/rust/hyper/petstore/Cargo.toml
This crate version has a security vuln
https://rustsec.org/advisories/RUSTSEC-2018-0005
ping @frol @farcaller @richardwhiuk @paladinzh @jacob-pro
```
``` 
=> Rust: Remove unused serde_yaml

modules/openapi-generator/src/main/resources/rust/Cargo.mustache, samples/client/petstore/rust/hyper/petstore/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-async/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-awsv4signature/Cargo.toml, samples/client/petstore/rust/reqwest/petstore/Cargo.toml
This crate version has an indirect security vuln,
as tokio-core 0.1.18 (latest) is two years old,
and uses tokio 0.1.5.
https://rustsec.org/advisories/RUSTSEC-2021-0124
ping @frol @farcaller @richardwhiuk @paladinzh @jacob-pro
```
``` 
=> Rust: Remove unused tokio in rust hyper client

modules/openapi-generator/src/main/resources/elm/Api.mustache, samples/openapi3/client/elm/src/Api.elm
This is a backwards compatible change. It adds the additional function `sendWithCustomExpect` to the provided helper functions in `Api.elm` to make requests.
It can be used to implement a more fine grained error handling as described [here](https://package.elm-lang.org/packages/elm/http/latest/Http#expectStringResponse). Before it was e.g. not possible to access the response body if the server responded with an error like 404.
@eriktim
```
```  …
=> [elm] add function to allow more fine grained error handling

docs/generators/java-helidon-client.md, docs/generators/java-helidon-server.md
CI is failing due to a missing property in the Java Helidon documentation. 
See: https://github.com/OpenAPITools/openapi-generator/actions/runs/3351771721/jobs/5553475799
```
``` 
=> Add missing property to Java Helidon docs

.gitignore, pom.xml
Fixes a vulnerability in Apache Commons Text with CVE score 9.8 (CRITICAL).
Resolves #13851
=> CVE-2022-42889: Upgraded commons-text to version 1.10.0.

modules/openapi-generator/src/main/resources/php/HeaderSelector.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/HeaderSelector.php, samples/client/petstore/php/OpenAPIClient-php/tests/HeaderSelectorTest.php
This fixes #12926 and addresses #728 for the specific PHP client.
When handling Accept headers, the current behavior of the php OpenAPIGenerator is:
- If there is none in the api description, don't send one.
- If one of them matches a "json-like" RE, send only "application/json" and ignore the others
- otherwise, concatenate all them and send it.
The first and third behaviors are fine, but the second one has some issues:
1. if the API description includes parameters for the "json-like" Accept header, they will be simply disregarded. This can be a problem if those parameters are mandatory for that API.
2. scenarios like the one described in #12926 cannot be solved without using a middleware in the http client, to change the Accept header just before sending the request. This is not a good …
=> [PHP] handle properly multiple accept headers

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey2/auth/OAuth.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/auth/OAuth.mustache, samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/auth/OAuth.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/OAuth.java, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/auth/OAuth.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/OAuth.java
Java jersey OAuth2 add support for public client by a new method ApiClient.setOauthCredentialsForPublicClient(String clientId), which does not require the clientSecret as described in issue #13827 
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) …
=> Java jersey OAuth2 add support for public client

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/exploded-query-param-array.yaml
=> [JAVA] [NATIVE] Fix exploded query parameters with array property

modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php, samples/client/petstore/php/OpenAPIClient-php/tests/ObjectSerializerTest.php
Fixes #13635, by correcting a regression added by #11225 and extending #12120 adjustments.
ObjectSerializer::toQueryValue() filters out parameters whose values are "empty" (using the `empty()` method from php), but it disregards the value's _type_ when doing so. A single exception is added for the **false** value, if the OpenApi type is boolean. 
This PR add checks for numeric fields, since the value "0" (both integer and float) should not be filtered out. New tests are added, covering 100% of the added lines.
```
```  …
=> [PHP] Accept 0 as value for query parameters

modules/openapi-generator/src/main/resources/elixir/deserializer.ex.mustache, samples/client/petstore/elixir/lib/openapi_petstore/deserializer.ex
Currently, there is an issue with the deserializations of maps, which are null.
As an example, the given payload is the following
```json
{
"ID": "2b892741-1853-3ddd-382f-fc12e93b5174",
"CreateTime": 1666707394061348343,
"ModifyTime": 1666707394064897549
}
```
the schema definitions looks something like this
```yaml
components:
schemas:
Evaluation:
properties:
CreateTime:
format: int64
type: integer
FailedTGAllocs:
$ref: '#/components/schemas/AllocationMetric'
type: object
ID:
type: string
ModifyTime:
format: int64
type: integer
type: object
AllocationMetric:
properties:
AllocationTime:
format: int64
type: integer
type: object
```
As you can see, `FailedTGAllocs` is a simple dictionary with the value type of `AllocationMetric`. The generator will produce something …
=> [Elixir] Fixes issue with maps/dictionary not present in payload

modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache, samples/client/petstore/c/model/order.c
Sometimes, the value of `date-time` data type in the JSON/YAML string is `null`
e.g.
```yaml
- apiVersion: v1
count: 1
eventTime: null  <----- here !
firstTimestamp: "2022-11-02T09:18:07Z"
kind: Event
lastTimestamp: "2022-11-02T09:18:07Z"
...
```
Currently openapi-generator/c-libcurl cannot handle this case when parsing JSON strings into cJSON objects. 
e.g. https://github.com/kubernetes-client/c/issues/144
```
```  …
=> [C][Client] Check cJSON_IsNull when the data type is datetime

modules/openapi-generator/src/main/resources/r/modelAnyOf.mustache, modules/openapi-generator/src/main/resources/r/modelOneOf.mustache, samples/client/petstore/R-httr2-wrapper/R/any_of_pig.R, samples/client/petstore/R-httr2-wrapper/R/any_of_primitive_type_test.R, samples/client/petstore/R-httr2-wrapper/R/mammal.R, samples/client/petstore/R-httr2-wrapper/R/one_of_primitive_type_test.R, samples/client/petstore/R-httr2-wrapper/R/pig.R, samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R, samples/client/petstore/R-httr2/R/any_of_pig.R, samples/client/petstore/R-httr2/R/any_of_primitive_type_test.R, samples/client/petstore/R-httr2/R/mammal.R, samples/client/petstore/R-httr2/R/one_of_primitive_type_test.R, samples/client/petstore/R-httr2/R/pig.R, samples/client/petstore/R-httr2/tests/testthat/test_petstore.R, samples/client/petstore/R/R/any_of_pig.R, samples/client/petstore/R/R/any_of_primitive_type_test.R, samples/client/petstore/R/R/mammal.R, samples/client/petstore/R/R/one_of_primitive_type_test.R, samples/client/petstore/R/R/pig.R, samples/client/petstore/R/tests/testthat/test_petstore.R
- Better error check if discriminator value is null in r client
- Better error messages (e.g. Error! The value of discriminator property `className` is null  instead of EXPR must be a length 1 vector.)
- updated tests.
```
``` 
cc @Ramanth (2019/07) …
=> Better error check if discriminator value is null in r client

modules/openapi-generator/src/main/resources/python-legacy/api_client.mustache, samples/client/petstore/python-asyncio/petstore_api/api_client.py, samples/client/petstore/python-legacy/petstore_api/api_client.py, samples/client/petstore/python-tornado/petstore_api/api_client.py, samples/openapi3/client/petstore/python-legacy/petstore_api/api_client.py
The if not passed the models create a new configuration object which configures logging and determines cpu count every time. This causes extreme performance issues when deserializing larger sets of items.
See also
https://github.com/kubernetes-client/python/issues/1921
```
```  …
=> [Python] pass api_client configuration to model deserialize

modules/openapi-generator/src/main/resources/go/api_test.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
Fix the issue reported in https://github.com/OpenAPITools/openapi-generator/pull/13560#issuecomment-1299322387
The import in the test file has been corrected
```
``` 
=> Correct import, add test

modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt, modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
=> #13726 Introduce new remoteInputSpec parameter

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache, samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
fix #13943
```
```
cc @cliffano, @zlx, @autopp
=> [BUG][RUBY] Fix ruby faraday HTTP 0 issue without libcurl 

docs/customization.md, modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java, modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml
Add option to skip reusing inline schemas by providing `SKIP_SCHEMA_REUSE=true` to inline scheme naming default option, e.g. `--inline-schema-name-defaults SKIP_SCHEMA_REUSE=true`
This allow users to map each schemas that are previously automatically mapped to the same inline schema due to identical definition.
Added tests and updated doc.
```
```  …
=> Add option to skip reusing inline schemas

modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache, modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache, samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift, samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
This PR closes #13978 
Details of this issue can be read in the linked issue. By not checking for equality but for a prefix we do no longer fall through to fatalError if a provided content-type has been appended with a charset 
```
``` 
The program was …
=> [swift5] support content types with charsets

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/enumClass.mustache, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/model/Order.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/model/Pet.java
When using jaxrs-cxf-cdi, contrary to the other cxf generators, the enums are not setup with the json serializer so that the value in the openapi is the one that gets serialized.
It looks like there is simply a missing jackson annotation on the enum, that will make it work.
An alternative option is to configure the jackson serializer in the application, to use SerializationFeature.WRITE_ENUMS_USING_TO_STRING and DeserializationFeature READ_ENUMS_USING_TO_STRING
But this approach:
- requires a special configuration of the mapper
- is inconsistent with other generators
- imposes a configuration that has effects for the other usages of jackson in a application
- [x ] Pull …
=> [jaxrs-cxf-cdi] use jackson for enum serialization

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java
[python] fixes bug where v2 specs generate clients when they should not
```
``` 
=> [python] fixes bug where v2 specs generate clients when they should not

.github/workflows/samples-rust.yaml, pom.xml, samples/client/petstore/rust/reqwest/petstore-async-middleware/pom.xml, samples/client/petstore/rust/reqwest/petstore-async-middleware/src/apis/configuration.rs
Add tests for rust reqwest middleware client
```
``` 
cc @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10)
=> Add tests for rust reqwest middleware client

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java
Fix #13648
Change from `packagePath()` to `packageName` when generating the Python `import` statement.
@spacether 
**Test command:**
```shell
$ java -jar ./modules/openapi-generator-cli/target/openapi-generator-cli.jar \
generate \
-i ./modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
-g python \
--additional-properties packageName='my.openapi' \
-o /tmp/issue-13648
```
**Before:**
```shell
$ tail -n2 /tmp/issue-13648/my/openapi/model/pet.py
from my/openapi.model.category import Category
from my/openapi.model.tag import Tag
```
**After:**
```shell
$ tail -n2 /tmp/issue-13648/my/openapi/model/pet.py
from my.openapi.model.category import Category
from my.openapi.model.tag import Tag
```
``` …
```
=> Fix invalid Python import for qualified package name

modules/openapi-generator/src/main/resources/typescript-axios/baseApi.mustache, samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/base.ts, samples/client/petstore/typescript-axios/builds/composed-schemas/base.ts, samples/client/petstore/typescript-axios/builds/default/base.ts, samples/client/petstore/typescript-axios/builds/es6-target/base.ts, samples/client/petstore/typescript-axios/builds/test-petstore/base.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/base.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/base.ts, samples/client/petstore/typescript-axios/builds/with-interfaces/base.ts, samples/client/petstore/typescript-axios/builds/with-node-imports/base.ts, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/base.ts, samples/client/petstore/typescript-axios/builds/with-npm-version/base.ts, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/base.ts, samples/client/petstore/typescript-axios/builds/with-string-enums/base.ts
As part of PR #13964, a change was introduced that causes Typescript to fail to compile because of unused local variables.  This appears to have been a known issue.  Moving the ts-ignore comment to fix the issue
```
``` 
=> Make sure ts-ignore is ignoring right line

modules/openapi-generator/src/main/resources/python-prior/api_client.mustache, samples/client/petstore/python-prior/petstore_api/api_client.py, samples/client/petstore/python-prior_disallowAdditionalPropertiesIfNotPresent/petstore_api/api_client.py, samples/openapi3/client/extensions/x-auth-id-alias/python-prior/x_auth_id_alias/api_client.py, samples/openapi3/client/petstore/python-prior/petstore_api/api_client.py, samples/openapi3/client/petstore/python-prior/tests_manual/test_fake_api.py
Tweak the python-prior API bindings, so that they no longer cast lists to tuples when making a POST request with a multipart/form-data content-type. This fixes an interaction with
`urllib3.request_encode_body`, whose `fields` parameter expects tuples, not lists.
cc @spacether
See: https://urllib3.readthedocs.io/en/stable/reference/urllib3.request.html
Fix: https://github.com/OpenAPITools/openapi-generator/issues/14012
=> Don't cast list to tuple in python-prior binding

modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/api.mustache, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/UserApi.java
When generating a client that requires a set, the interface is not including the import of java.util.Set.
The proposal is to include it in the same group as the rest of the collections.
Related issue: https://github.com/OpenAPITools/openapi-generator/issues/14047
```
```  …
=> [JAVA][RETROFIT2] Include java.util.Set in fullJavaUtil imports

samples/openapi3/client/petstore/python-prior/tests_manual/test_api_validation.py, samples/openapi3/client/petstore/python-prior/tests_manual/test_deserialization.py, samples/openapi3/client/petstore/python-prior/tests_manual/test_fake_api.py, samples/openapi3/client/petstore/python-prior/tests_manual/test_http_signature.py
This change has no functional impact. In my view, `pathlib` has a more pleasant API than `os.path`.  Incidentally, this slightly reduces line count.
cc @spacether
=> Migrate python-prior/tests_manual/ to pathlib

modules/openapi-generator/src/main/resources/go/client.mustache, samples/client/petstore/go/go-petstore/client.go, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go, samples/openapi3/client/petstore/go/go-petstore/client.go
A trailing whitespace gets included if the error is not a RFC7807 model. Not a huge issue but still nice to have cleaner error message
This was introduced with https://github.com/OpenAPITools/openapi-generator/pull/13680
```
``` 
@antihax @grokify …
=> [Go] Trim Client Error Message White Space

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt, modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
=> Cleanup outputDir before openApiGenerate

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/api.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/apachehttpclient/ApacheHttpClientCodegenTest.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/UserApi.java
Porting https://github.com/OpenAPITools/openapi-generator/pull/11682 and https://github.com/OpenAPITools/openapi-generator/pull/13656 to the apache client.
```
``` 
=> [JAVA][APACHE] Fix apache http client query parameters

modules/openapi-generator/src/main/resources/go/api_test.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/go/petstore-with-no-response-body.yaml
Closes #14079 
Currently, the Go client generator produces tests that are incorrect when an API endpoint response does not include a response body.  This updates the `api_test` template to remove the expectation for a response body if the API endpoint under test does not produce a response body.  A unit test is also added to the Go generator to validate that the `api_test` file is generated correctly for those API endpoints.
```
```  …
=> [Go] Fix generated client tests when there is no response body

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java
[python] fixes addProps sometime breaks
Verification test added for model and property
This happened because schema baseNames were colliding when an items schema and an additionalProperties schema had identical schemas. When that happened, one (earlier processed) codegenProperty was returned from a cache.
I added the methods getAdditionalPropertiesName and getItemsName to provide these names and prevent collisions
Synonym PR for https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/93
```
```  …
=> [python] fixes addProps sometimes breaks

modules/openapi-generator/src/main/resources/typescript-axios/package.mustache, samples/client/petstore/typescript-axios/builds/es6-target/package.json, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/package.json, samples/client/petstore/typescript-axios/builds/with-npm-version/package.json
Axios 0.27.2 is a version that is around us for about 6 months and until now is the last one with major version 0, the next version is Axios 1.* so openapi-generator should have this version upgraded to the latest axios 0.27.2
Some improvements
*  Automatic object serialization to a FormData object if the request `Content-Type` header is set to `multipart/form-data`.
* Better FormData integrationn
* AxiosError refactoring
* 
```
```  …
=> Upgrade typescript-axios from 0.26.1 to 0.27.2

modules/openapi-generator/src/main/resources/JavaSpring/model.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
fix #13885
issue arises from incomplete implementation and tests in #13365 
```
``` 
mention JavaSpring community:
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) …
=> put back missing import for NotNull annotation in #13365 fix #13885

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/php/AbstractPhpCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypeScriptNodeClientCodegenTest.java
The initialialization of the typeAlias field happens "on demand" in fromModel(...) but it's be better to do it in setOpenApi(...). This is because there are other methods such as fromOperation(...), which also depend on that initialization. Also, all the information that's necessary for typeAliases, is known in setOpenAPI.
This PR was requested as part of the review of https://github.com/OpenAPITools/openapi-generator/pull/13805#issuecomment-1318664950.
```
```  …
=> Initialize typeAliases in setOpenAPI

modules/openapi-generator/src/main/resources/typescript-angular/configuration.mustache, modules/openapi-generator/src/test/resources/integrationtests/typescript/additional-properties-expected/configuration.ts, modules/openapi-generator/src/test/resources/integrationtests/typescript/array-and-object-expected/configuration.ts, modules/openapi-generator/src/test/resources/integrationtests/typescript/custom-path-params-expected/configuration.ts, modules/openapi-generator/src/test/resources/integrationtests/typescript/petstore-expected/configuration.ts, samples/client/petstore/typescript-angular-v12-oneOf/builds/default/configuration.ts, samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/configuration.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/configuration.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/configuration.ts, samples/client/petstore/typescript-angular-v13-oneOf/builds/default/configuration.ts, samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/configuration.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/configuration.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/configuration.ts, samples/client/petstore/typescript-angular-v14-provided-in-root/builds/default/configuration.ts, samples/client/petstore/typescript-angular-v14-query-param-object-format/configuration.ts
In https://github.com/OpenAPITools/openapi-generator/pull/13132 `defaultEncodeParam` method has been introduced. This method is used in every API client call to encode the path variables. By default openapi-generator uses `string` type for date-time params, but this encoder misses the type check and tries to call `toISOString()` on it.
```
```  …
=> typescript-angular: Fixed path parameter encoding for date-time dataFormat

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
Fix build warning in Java Apache client
```
> Task :javadoc
/Users/williamcheng/Code/openapi-generator3/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java:210: warning: no @param for objectMapper
public ApiClient setObjectMapper(ObjectMapper objectMapper) {
^
/Users/williamcheng/Code/openapi-generator3/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java:222: warning: no @param for httpClient
public ApiClient setHttpClient(CloseableHttpClient httpClient) {
^
/Users/williamcheng/Code/openapi-generator3/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java:234: warning: no @param for basePath
public ApiClient setBasePath(String basePath) {
^ …
```
=> Fix build warning in Java Apache client

modules/openapi-generator/src/main/resources/python-legacy/common_README.mustache, samples/client/petstore/python-asyncio/README.md
Fix https://github.com/OpenAPITools/openapi-generator/issues/13247
Added the missing `async` and `await` keywords. The generated example is now executable.
```
``` 
@spacether
=> [Python] Fix client legacy generator asyncio README code example

bin/configs/c.yaml, modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache, modules/openapi-generator/src/test/resources/2_0/c/petstore.yaml, samples/client/petstore/c/README.md, samples/client/petstore/c/api/UserAPI.c, samples/client/petstore/c/api/UserAPI.h, samples/client/petstore/c/docs/UserAPI.md
When the query parameters in a API request is type of "integer" or "boolean",  if its value is `0` or `false`, the current code does not send the query parameter to the API server. 
e.g.
```c
if (gracePeriodSeconds)    <--- if gracePeriodSeconds == 0, the below code will be ignored.
{
keyQuery_gracePeriodSeconds = strdup("gracePeriodSeconds");
valueQuery_gracePeriodSeconds = calloc(1,MAX_NUMBER_LENGTH);
snprintf(valueQuery_gracePeriodSeconds, MAX_NUMBER_LENGTH, "%d", gracePeriodSeconds);
keyPairQuery_gracePeriodSeconds = keyValuePair_create(keyQuery_gracePeriodSeconds, valueQuery_gracePeriodSeconds);
list_addElement(localVarQueryParameters,keyPairQuery_gracePeriodSeconds);
}
```
This PR changes the code to:
```c
if (1) // Always send integer parameters to …
```
=> [C][Client] Always send integer or boolean query parameters to the API server 

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/user.service.ts
This pull request updates the typescript-nest client generator to use `URLSearchParams` instead of an empty object when storing and referencing query parameters. This fixes a bug where the generator would build invalid typescript. 
Using the examples described in [this issue](https://github.com/OpenAPITools/openapi-generator/issues/14134), the following typescript would be generated:
```
let queryParameters = {};
if (brandOrganizationId) {
brandOrganizationId.forEach((element) => {
queryParameters.append('brandOrganizationId', <any>element);
})
}
```
The `queryParameters` object is a plain object and doesn't have the `append` method available. This change updates `queryParameters` to always be an instance of `URLSearchParams` where `append` is an available method. 
Axios (the http client …
=> [typescript-nest] fixes query parameter append bug

modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpNetCoreClientDeepObjectTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientDeepObjectTest.java, modules/openapi-generator/src/test/resources/3_0/deepobject.yaml
Add tests to cover base name (deep object) bug
A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/13662
```
``` 
=> Add tests to cover base name (deep object)  bug

modules/openapi-generator/src/main/resources/python/configuration.handlebars, modules/openapi-generator/src/main/resources/python/doc_auth_partial.handlebars, samples/openapi3/client/3_0_3_unit_test/python/unit_test_api/configuration.py, samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/configuration.py, samples/openapi3/client/petstore/python/docs/apis/tags/PetApi.md, samples/openapi3/client/petstore/python/petstore_api/configuration.py
[python] Fixes Configuration w/ access_token at initialization
```
``` 
=> [python] Fixes Configuration w/ access_token at initialization

docs/generators/typescript-axios.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
describe withSeparateModelsAndApi, modelPackage, apiPackage as mentioned in #5008
```
``` 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) …
=> [tyescript-axios] fix description for config options: withSeparateModelsAndAp, modelPackage, apiPackage

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache, samples/client/petstore/typescript-fetch/builds/allOf-readonly/runtime.ts, samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts, samples/client/petstore/typescript-fetch/builds/default/runtime.ts, samples/client/petstore/typescript-fetch/builds/enum/runtime.ts, samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts, samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts, samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
Current generated code produces a `response` variable set to undefined, and TS does not like you changing the type of the variable later. Therefore, set the type of the variable to be `Response` or `undefined`
Solves OpenAPITools/openapi-generator#12007
_Very_ small change, simply fixing the type of the response variable so Typescript doesn't complain
```
```  …
=> [typescript-fetch] Fix response type to be Response or undefined

modules/openapi-generator/src/main/resources/Java/apiException.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/apiException.mustache, samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiException.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiException.java, samples/client/petstore/java/jersey1/src/main/java/org/openapitools/client/ApiException.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiException.java, samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiException.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiException.java, samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiException.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiException.java, samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiException.java
Improves the implementation of Java ApiException for okhttp3 and top level in cases where there is a status code and a response body, but there is no message passed to the exception constructor.
See: https://github.com/kubernetes-client/java/issues/2066
cc @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 
```
```  …
=> Modify Java ApiException to have a more informative message.

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/TypeScriptClientCodegenTest.java
This PR fixes an issue with the Typescript client code generator when compiling a regular expression pattern:
```
Exception: Unbalanced '{' - missing '}' at 
'[A-Z]{3'
^
Caused by: com.github.curiousoddman.rgxgen.parsing.dflt.RgxGenParseException: Unbalanced '{' - missing '}' at 
'[A-Z]{3'
^
```
This PR supersedes #13655, as its author seems inactive. It also implements a suggestion made in this previous PR, of removing the non-standard support for leading/trailing slashes when parsing regular expressions (see https://github.com/OpenAPITools/openapi-generator/pull/13655#discussion_r992232977)
Fixes #13390
Mentioning the Typescript technical commitee: @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka 
```
./mvnw …
```
=> Fixed typescript codegen pattern compiler

samples/server/petstore/python-fastapi/requirements.txt
There are 1 security vulnerabilities found in urllib3 1.26.4
- [CVE-2021-33503](https://www.oscs1024.com/hd/CVE-2021-33503)
Upgrade urllib3 from 1.26.4 to  for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade urllib3 to 

modules/openapi-generator/src/main/resources/typescript-axios/common.mustache, samples/client/petstore/typescript-axios/builds/composed-schemas/common.ts, samples/client/petstore/typescript-axios/builds/default/common.ts, samples/client/petstore/typescript-axios/builds/es6-target/common.ts, samples/client/petstore/typescript-axios/builds/test-petstore/common.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/common.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/common.ts, samples/client/petstore/typescript-axios/builds/with-interfaces/common.ts, samples/client/petstore/typescript-axios/builds/with-node-imports/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version/common.ts, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/common.ts, samples/client/petstore/typescript-axios/builds/with-string-enums/common.ts
Resolved Type Error - `TypeError: Cannot convert undefined or null to object`
With `typescript-axios` template, function `setFlattenedQueryParams` which stringifies url search parameters raises TypeError when value of parameter is null (like `cursor: null`) or undefined (like `obj: { key: undefined }` in recursive execution).
It seems to be same issue with [#5174](https://github.com/OpenAPITools/openapi-generator/issues/5174) issue and [#5197](https://github.com/OpenAPITools/openapi-generator/pull/5197) PR for `typescript-angular`.
@mkusaka 
```
``` 
These must …
=> [typescript-axios] Add temination condition for flattening url parameters

modules/openapi-generator/src/main/resources/typescript-axios/baseApi.mustache, samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/base.ts, samples/client/petstore/typescript-axios/builds/composed-schemas/base.ts, samples/client/petstore/typescript-axios/builds/default/base.ts, samples/client/petstore/typescript-axios/builds/es6-target/base.ts, samples/client/petstore/typescript-axios/builds/test-petstore/base.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/base.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/base.ts, samples/client/petstore/typescript-axios/builds/with-interfaces/base.ts, samples/client/petstore/typescript-axios/builds/with-node-imports/base.ts, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/base.ts, samples/client/petstore/typescript-axios/builds/with-npm-version/base.ts, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/base.ts, samples/client/petstore/typescript-axios/builds/with-string-enums/base.ts
- Sets the  `name` property inside class constructor
- Updated samples
The setting `noImplicitOverride` leads to a more robust codebase. However, setting this option resulted in an error since the class was overriding the `name` property without marking it as override.
- [TS Documentation noImplicitOverride](https://www.typescriptlang.org/tsconfig#noImplicitOverride)
- https://github.com/OpenAPITools/openapi-generator/pull/14225 (First attempt to solve this issue)
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx  @macjohnny  @topce @akehir  @petejohansonxo @amakhrov  @davidgamero  @mkusaka 
```
```  …
=> feat(typescript-axios): set `name` in constructor

modules/openapi-generator/src/main/resources/ruby-client/api_error.mustache, samples/client/petstore/ruby-autoload/lib/petstore/api_error.rb, samples/client/petstore/ruby-faraday/lib/petstore/api_error.rb, samples/client/petstore/ruby/lib/petstore/api_error.rb, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_error.rb, samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_error.rb, samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_error.rb
When generating message-only errors (e.g. `ApiError.new('Connection failed')`), the `@message` instance variable is not set so the `message` method returns the default message: 
https://github.com/OpenAPITools/openapi-generator/blob/d90c9a6f3bdabec92019e7a78837400c575c5735/modules/openapi-generator/src/main/resources/ruby-client/api_error.mustache#L36-L37
With this PR (setting the `@message` instance variable), the `message` method returns the expected message:
```
```  …
=> [ruby] Fix api_error.mustache to initialize message-only errors properly

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
This PR is to support servers variables in okhttp-json, this is an addon of #4998 because it was missing the okhttp-gson.
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) …
=> [Java][Client] Generate servers for okhttp-gson

docs/generators/fsharp-functions.md, docs/generators/fsharp-giraffe-server.md, docs/generators/java-inflector.md, docs/generators/jaxrs-cxf-client.md, docs/generators/swift5.md, modules/openapi-generator/src/main/resources/Java/libraries/feign/api.mustache, samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/feign/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/feign/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/feign/src/main/java/org/openapitools/client/api/UserApi.java
Hi, I just saw, that the generated Map Class is never used outside of tests, but it would be the perfect fit for the changed mehods, as its use-case is exactly the same.
Also a useful change to prevent problems with Collection types and their generics parameters (f.e. Map<x, y>). See: https://stackoverflow.com/questions/62823341/openapi-generator-maven-plugin-breaks-old-feign-with-querymap
Mentions:
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608
=> Update Java/Feign api.mustache to accept its own convinience Map Class

modules/openapi-generator/src/main/resources/ruby-client/README.mustache, modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache, samples/client/petstore/ruby-autoload/lib/petstore/configuration.rb, samples/client/petstore/ruby-faraday/lib/petstore/configuration.rb, samples/client/petstore/ruby/lib/petstore/configuration.rb, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/configuration.rb, samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/configuration.rb, samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/configuration.rb
- The client can now be optionally configured with an access token getter proc
- The proc overrides the the static access token if it is set
See: https://github.com/OpenAPITools/openapi-generator/issues/14068
ruby technical committee: @cliffano @zlx @autopp @wing328 
```
```  …
=> Enable access token refresh

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/store.service.ts, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/user.service.ts
When sending a request with a client generated by typescript-nestjs, the default headers are modified. This occurs when headers such as "Accept" are appended by the client.
The root of the issue is that a reference to the default headers is stored instead of a clone.
Previously the code would have been generated like this:
```
public deletePet(petId: number, apiKey?: string, ): Observable<any> {
/* ... */
let headers = this.defaultHeaders;$
if (apiKey !== undefined && apiKey !== null) {$
headers['api_key'] = String(apiKey);$
}
```
This adds the `api_key` to the default headers, which then leaks to all following requests, until another request might change the `api_key` header.
This PR changes the generated code to:
```
public deletePet(petId: number, apiKey?: string, ): Observable<any> { …
```
=> typescript-nestjs / Ensure default headers remain unmodified

modules/openapi-generator/src/main/resources/swift5/Extensions.mustache, samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift, samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/Extensions.swift, samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/Extensions.swift
fixes https://github.com/OpenAPITools/openapi-generator/issues/14306
```
``` 
=> [BUG][Swift] fix decimal encoding referencing not existing extension method "encodeToJSON" 

.travis.yml
Fix Travis build error by pinning the gem bunlder version
```
``` 
=> Fix gem bundler version in Travis build

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, samples/client/echo_api/java/feign-gson/.openapi-generator/FILES
Just a simple change to not include the DefaultApi20Impl class if the hasOAuthMethods flag is disabled
```
``` 
=> Java Feign - DefaultApi20Impl is only needed if OAuth is enabled

modules/openapi-generator/src/main/resources/php/api.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
- perf: \GuzzleHttp\json_encode is deprecated, use \GuzzleHttp\Utils::jsonEncode instead
```
``` 
=> [PHP] \GuzzleHttp\json_encode is deprecated, use \GuzzleHttp\Utils::jsonEncode instead

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
The import mapping for LocalTime still pointed to org.joda.time.*. This one line made the jodatime dependency required.
I've added it where @cbornet had already placed the code for LocalDate.
Without this change I've had to resort to this workaround in my build:
```
<plugin>
<artifactId>maven-antrun-plugin</artifactId>
<version>3.1.0</version>
<executions>
<execution>
<phase>generate-sources</phase>
<goals>
<goal>run</goal>
</goals>
<configuration>
<target>
<replace
dir="${project.build.directory}/generated-sources/openapi/src/main/java"
includes="**/*.java"
token="import org.joda.time.*;"
value="/* do not import jodatime */"/>
</target>
</configuration>
</execution>
</executions>
</plugin>
```
```
``` …
=> [Java] fix LocalTime import for dateLibrary java8

modules/openapi-generator/src/main/resources/php-symfony/model.mustache, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/ApiResponse.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Category.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/EnumStringModel.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Order.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Pet.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Tag.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/User.php
Currently, the `model generic` template is used to generate all DTO classes including enums.
This results in empty classes for enums.
This PR just make use of the existing `model enum` template to generate enum DTOs.
```
```  …
=> Fix enum generation for php-symfony generator

modules/openapi-generator/src/main/resources/dart2/serialization/native/native_class.mustache, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/array_of_array_of_number_only.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/array_test.dart
Fixes #13460
This PR adds better support for array-of-arrays such that non-nullable/required properties will no longer generate invalid dart code.
This just required changes to the native_class.mustache file
```
``` 
@jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela
=> [Dart] Fix array of array nullable and non-nullable value generation

modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache, samples/client/petstore/c/model/api_response.c, samples/client/petstore/c/model/category.c, samples/client/petstore/c/model/tag.c, samples/client/petstore/c/model/user.c
Hi @wing328 @zhemant @michelealbano
This PR is similar to https://github.com/OpenAPITools/openapi-generator/pull/13884
Sometimes, the value of `string` data type in the JSON/YAML string is null
e.g.
```yaml
{
"kind": "NodeList",
"apiVersion": "v1",
"metadata": {
"continue": ""
},
"items": [
{
"kind": "Node",
...
"status": {
...
"phase": null  <---- Here !
}
}
]
}
```
Currently `openapi-generator/c-libcurl` doesn't allow this case, so parsing JSON strings into cJSON objects will fail.
```
``` 
You may …
=> [C][Client] Allow cJSON_IsNull() for a string if it is not mandatory

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
Small fix to address this comment https://github.com/OpenAPITools/openapi-generator/pull/14310#discussion_r1059522238
```
``` 
=> [Java][Jersey2] revert configurable javax package for javax.net

.github/workflows/samples-dotnet-standard.yaml
The other pipeline to build dotnet samples was ignoring standard. It looks like to include standard we need to use another dotnet-version property.
```
``` 
@mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti …
=> [csharp-netcore] Added new pipeline to build standard

modules/openapi-generator/src/main/resources/go/model_simple.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/property-readonly.yaml, samples/client/petstore/go/go-petstore/model_has_only_read_only.go, samples/client/petstore/go/go-petstore/model_name.go, samples/client/petstore/go/go-petstore/model_read_only_first.go, samples/openapi3/client/petstore/go/go-petstore/model_has_only_read_only.go, samples/openapi3/client/petstore/go/go-petstore/model_name.go, samples/openapi3/client/petstore/go/go-petstore/model_read_only_first.go, samples/openapi3/client/petstore/go/go-petstore/model_read_only_with_default.go
Fix #12551
Readonly fields to be ignored during `toSerialize`
```
``` 
=> 12551 [Go] Skipping marshalling of readonly fields

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
`typescript-axios` generator uses an option `useSingleRequestParameter ` as mentioned in https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-axios.md
However, this option is used only in generated classes. This PR reuse the same logic in api factories.
```
``` 
For Windows users, please run the script …
=> [typescript-axios] single request param in factory

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/JavaFileAssert.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/issue_14252.yaml
fix for https://github.com/OpenAPITools/openapi-generator/issues/14252
```
``` 
=> [Java] fix bigDecimalAsString config option

modules/openapi-generator/src/main/resources/typescript/http/http.mustache, samples/client/others/typescript/builds/with-unique-items/http/http.ts, samples/openapi3/client/petstore/typescript/builds/browser/http/http.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/http/http.ts, samples/openapi3/client/petstore/typescript/builds/default/http/http.ts, samples/openapi3/client/petstore/typescript/builds/deno/http/http.ts, samples/openapi3/client/petstore/typescript/builds/inversify/http/http.ts, samples/openapi3/client/petstore/typescript/builds/jquery/http/http.ts, samples/openapi3/client/petstore/typescript/builds/object_params/http/http.ts
Start moving away from the url-parse package in favor of the [WHATWG url api](https://nodejs.org/api/url.html#the-whatwg-url-api)
This follows convention and will make future implementations towards the fetch api smoother
from url-parse [npm page](https://www.npmjs.com/package/url-parse):
> url-parse was created in 2014 when the WHATWG URL API was not available in Node.js and the URL interface was supported only in some browsers. Today this is no longer true. The URL interface is available in all supported Node.js release lines and basically all browsers. Consider using it for better security and accuracy.
```
```  …
=> [typescript] migrate url-parse to URL WHATGW in https.ts

modules/openapi-generator/src/main/resources/csharp-netcore-functions/modelGeneric.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/validatable.mustache, modules/openapi-generator/src/main/resources/csharp/modelGeneric.mustache
Adding `.ToString()` when the type is Guid. Fixes #12442
```
``` 
@mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti
=> [csharp] Add .ToString() if is Uuid/Guid is validated with regex fixes: #12442

modules/openapi-generator/src/main/resources/JavaSpring/api.mustache, samples/openapi3/client/petstore/spring-cloud-3/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/client/petstore/spring-cloud-async/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/client/petstore/spring-cloud-spring-pageable/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/client/petstore/spring-cloud/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/client/petstore/spring-stubs-skip-default-interface/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/client/petstore/spring-stubs/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/server/petstore/spring-boot-springdoc/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/server/petstore/springboot-beanvalidation-no-nullable/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/server/petstore/springboot-delegate/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/server/petstore/springboot-useoptional/src/main/java/org/openapitools/api/UserApi.java, samples/openapi3/server/petstore/springboot/src/main/java/org/openapitools/api/UserApi.java, samples/server/petstore/spring-boot-defaultInterface-unhandledException/src/main/java/org/openapitools/api/UserApi.java, samples/server/petstore/springboot-virtualan/src/main/java/org/openapitools/virtualan/api/UserApi.java
fix for https://github.com/OpenAPITools/openapi-generator/issues/14394
```
``` 
=> [Java][Spring] fix default response code

modules/openapi-generator/src/main/resources/swift5/api.mustache, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/AnotherFakeAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeClassnameTags123API.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/StoreAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/UserAPI.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/.gitignore, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient.xcodeproj/project.pbxproj, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient.xcodeproj/xcshareddata/xcschemes/SwaggerClient.xcscheme, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient.xcworkspace/contents.xcworkspacedata, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient.xcworkspace/xcshareddata/swiftpm/Package.resolved, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient/AppDelegate.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient/Assets.xcassets/AppIcon.appiconset/Contents.json, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient/Base.lproj/LaunchScreen.storyboard, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient/Base.lproj/Main.storyboard, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient/Info.plist, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClient/ViewController.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClientTests/APIHelperTests.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClientTests/FileUtils.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClientTests/Info.plist, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClientTests/PetAPITests.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClientTests/StoreAPITests.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClientTests/UIImage+Extras.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClientTests/UserAPITests.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/pom.xml, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift5/swift5_test_all.sh
Since https://github.com/OpenAPITools/openapi-generator/pull/14416 got merged, we can now simplify the async/await implementation.
```
``` 
=> [swift5][client] - simplify async await

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java
For crystal lang, there's no need to require any file for primitive types.
This PR makes the model import for a primitive type return null.
@wing328 Please review.
```
``` 
=> [Crystal] Skip primitive types from ModelImportMap

docs/generators/java-camel.md, docs/generators/spring.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
Applying @borsch's suggestion in #14362.
```
``` 
Java | @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)
-- | --
=> [Java][Spring] Fix #14362 when useSpringBoot3=true, then useJakartaEe

samples/client/petstore/swift5/alamofireLibrary/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/SwaggerClientTests/APIHelperTests.swift, samples/client/petstore/swift5/asyncAwaitLibrary/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift5/combineLibrary/SwaggerClientTests/SwaggerClientTests/APIHelperTests.swift, samples/client/petstore/swift5/combineLibrary/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift5/default/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift5/promisekitLibrary/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift5/rxswiftLibrary/SwaggerClientTests/SwaggerClientTests/APIHelperTests.swift, samples/client/petstore/swift5/rxswiftLibrary/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift5/urlsessionLibrary/SwaggerClientTests/run_xcodebuild.sh
This PR, enables the unit tests in the Swift sample projects.
```
``` 
=> [swift5][client] - enable swift unit tests

modules/openapi-generator/src/main/resources/go/client.mustache, samples/client/petstore/go/go-petstore/client.go, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go, samples/openapi3/client/petstore/go/go-petstore/client.go
Query params were incorrectly being exploded all the time, regardless of the setting in the spec.
This was introduced with https://github.com/OpenAPITools/openapi-generator/pull/13909/files and addresses https://github.com/OpenAPITools/openapi-generator/issues/14089
I think there are a lot of different ways to fix this issue, but this was a minimal way to get a slice of query params to be comma separated.
```
```  …
=> [Go] [Client] Don't Explode Query Params

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
Fix for https://github.com/OpenAPITools/openapi-generator/issues/14077
```
``` 
=> [Java][Spring] fix ParameterObject import for Spring Boot 3

modules/openapi-generator/src/main/resources/elixir/request_builder.ex.mustache, samples/client/petstore/elixir/lib/openapi_petstore/request_builder.ex
Currently, whenever someone passes a header parameter to the request, the request will fail since the `Tesla.put_header/3` will be called with the wrong parameter.
```
The following arguments were given to Tesla.put_header/3:
%{method: :get, url: "/jobs"}
:index
123
Attempted function clauses (showing 1 out of 1):
def put_header(%Tesla.Env{} = env, key, value) when is_binary(key) and is_binary(value)
```
This PR will fixes this issue by removing the `Tesla.put_header/3` call and replacing it with a simple `get value from list an pass it to the map` logic.
I noticed this bug during the review of https://github.com/OpenAPITools/openapi-generator/pull/14071#discussion_r1033703313
@halostatue or @wing328, Would you mind giving me a review on this one?
``` …
```
=> [elixir] Fixes issue with setting Header parameters

docs/generators/elixir.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java, samples/client/petstore/elixir/lib/openapi_petstore/model/all_of_with_single_ref.ex
Fixes #14070
This PR will handle `AnyType` as primitives to prevent the generator from generating specific classes, since in elixir structs cannot have any extra undefined files. This will also result in `AnyType` parameters not be serialized in any other way than Poison interprets it.
Since the Pet Store doesn't have some good examples to see the results of this change, here's a Dummy Spec:
```yaml
openapi: 3.0.3
info:
title: Dummy Spec
version: 1.0.11
servers:
- url: https://dummy.example.com/api
paths:
/quotas:
get:
operationId: GetQuotas
responses:
"200":
$ref: '#/components/responses/GetQuotasResponse'
tags:
- Enterprise
/dummy:
get:
operationId: GetQuotas
responses:
"200":
$ref: '#/components/responses/GetJobScaleStatusResponse'
tags:
- Enterprise
components:
schemas:
ConsulGateway: …
```
=> [elixir] Properly map AnyType

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/issue_12524.json
Conditional based implementation of https://github.com/OpenAPITools/openapi-generator/pull/12524
The main issue here is that generated model `public class API01ListOfStuff extends ArrayList<API01AbstractStuff>` doesn't have any properties that's why `AbstractJavaCodegen#postProcessModelProperty` doesn't invoked for this model. Since import of `JsonTypeName` is only model dependent  and not model's property dependent, I've moved that import to `fromModel` method
**Note:** seems like there are few more imports which are only model dependent but are present in postProcessModelProperty. I'll clean-up them separately 
```
```  …
=> [Java] fix JsonTypeName import

modules/openapi-generator/src/main/resources/python-nextgen/api_doc_example.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonNextgenClientCodegenTest.java, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/AnotherFakeApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/DefaultApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/StoreApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/UserApi.md, samples/openapi3/client/petstore/python-nextgen/docs/AnotherFakeApi.md, samples/openapi3/client/petstore/python-nextgen/docs/DefaultApi.md, samples/openapi3/client/petstore/python-nextgen/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen/docs/StoreApi.md, samples/openapi3/client/petstore/python-nextgen/docs/UserApi.md
This PR fixes the issue #14538
as described in the above issue, this PR makes auto generated API example doc runnable in success even when OpenAPI spec has no auth methods.
```
``` 
@spacether @wing328
=> [python-nextgen] fix issue on API example doc autogeneration

modules/openapi-generator-maven-plugin/README.md
Add samples to the documentation of the maven plugin to better show that type mappings are an easy way to customize the generator output.
After [asking on StackOverflow](https://stackoverflow.com/q/74940796), I first implemented a custom generator. It seemed too much effort for such a small change, but I was happy that it worked. I opened #14527 to add a configuration option to the jaxrs-spec generator to make this easier for others. Only then I found out about the much simpler configuration option (thank you to @borsch)
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608
=> [docs][maven-plugin] Add section on type and import mappings with samples

.github/PULL_REQUEST_TEMPLATE.md
The current list of items to be run in the PR template is incomplete. Looking at the `Docs up-to-date` workflow, an additional bin script is run which was making the PR fail in my case. I added it to the template
https://github.com/OpenAPITools/openapi-generator/actions/runs/3975110788/workflow
```
```  …
=> Update PR template to contain all scripts to run

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
There are 1 security vulnerabilities found in websockets 8.1
- [CVE-2021-33880](https://www.oscs1024.com/hd/CVE-2021-33880)
Upgrade websockets from 8.1 to 10.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade websockets to 10.0

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultGeneratorTest.java
```
``` 
closes https://github.com/OpenAPITools/openapi-generator/issues/2737
=> fix #2737 creates (empty) directories if contained files are ignored

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache, modules/openapi-generator/src/main/resources/ruby-client/api_client_spec.mustache, samples/client/petstore/ruby-autoload/spec/api_client_spec.rb, samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb, samples/client/petstore/ruby-faraday/spec/api_client_spec.rb, samples/client/petstore/ruby/spec/api_client_spec.rb, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/spec/api_client_spec.rb, samples/openapi3/client/features/dynamic-servers/ruby/spec/api_client_spec.rb, samples/openapi3/client/features/generate-alias-as-model/ruby-client/spec/api_client_spec.rb
This PR relates to the bug reported in #14596 and configures the proxy for the Ruby Faraday client if a proxy is configured. It also adds a spec to ensure the proxy is set properly.
@cliffano @zlx @autopp 
```
``` 
```
``` …
=> Set proxy in ruby faraday client if configured

modules/openapi-generator/src/main/resources/go/api_doc.mustache, samples/client/petstore/go/go-petstore/docs/AnotherFakeApi.md, samples/client/petstore/go/go-petstore/docs/FakeApi.md, samples/client/petstore/go/go-petstore/docs/FakeClassnameTags123Api.md, samples/client/petstore/go/go-petstore/docs/PetApi.md, samples/client/petstore/go/go-petstore/docs/StoreApi.md, samples/client/petstore/go/go-petstore/docs/UserApi.md, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/docs/UsageApi.md, samples/openapi3/client/petstore/go/go-petstore/docs/AnotherFakeApi.md, samples/openapi3/client/petstore/go/go-petstore/docs/DefaultApi.md, samples/openapi3/client/petstore/go/go-petstore/docs/FakeApi.md, samples/openapi3/client/petstore/go/go-petstore/docs/FakeClassnameTags123Api.md, samples/openapi3/client/petstore/go/go-petstore/docs/PetApi.md, samples/openapi3/client/petstore/go/go-petstore/docs/StoreApi.md, samples/openapi3/client/petstore/go/go-petstore/docs/UserApi.md
This PR addressed https://github.com/OpenAPITools/openapi-generator/issues/14610
- fix the examples in golang client documents
- correct import
- regenerate go client samples
```
``` 
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) …
=> Fix the examples and import path in golang client documents

modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoModelTest.java
`GoModelTest` uses deprecated code (`Schema.addProperties()`): this PR refactors the test code to use instead `Schema.addProperty()`
```
``` 
```
``` 
@antihax (2017/11) @grokify (2018/07) …
=> [Go] GoModelTest: remove deprecated code

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/resources/3_0/csharp/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/docs/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/docs/apis/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/docs/apis/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/docs/apis/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/docs/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/docs/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/docs/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/README.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/DefaultApi.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/DefaultApi.cs
Fixes https://github.com/OpenAPITools/openapi-generator/issues/14163
I tried writing a test instead of editing the samples such as below. The test succeeded with or without the change, which is strange because I can see the change is working as intended. `openAPI.toString()` returns the same thing before and after the change. 
CSharpModelTest.java
```java
@Test
public void assertAllOfIsRequired() {
final OpenAPI openAPI = TestUtils.parseFlattenSpec("src/test/resources/3_0/csharp-netcore/issue_14163.yaml");
CSharpNetCoreClientCodegen codegen = new CSharpNetCoreClientCodegen();
codegen.setOpenAPI(openAPI);
PathItem pathItem = openAPI.getPaths().get("/country");
Operation operation = pathItem.getPost();
String requiredParameter = (String) …
```
=> Inline allOf parameters are always not required

new.sh
This PR fix issues #14557
```
``` 
=> Change access level of LOGGER in new.sh to fix testLoggersAreNotPublicFinalAndNotStatic 

modules/openapi-generator/src/main/resources/Java/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
Restores previous behavior broken between v6.2.1 and v6.3.0.
Addresses https://github.com/OpenAPITools/openapi-generator/issues/14598 using the same approach taken in https://github.com/OpenAPITools/openapi-generator/pull/11277. When calling `APIClient.setBasePath`, null out the `serverIndex` so that the base path configuration is actually used.
@bbdouglas @sreeshas @jfiala @lukoyanov  @jeff9finger  @karismann @Zomzog @lwlee2608 
```
```  …
=> [Java] Fix APIClient basePath Configuration

modules/openapi-generator/src/main/resources/Java/libraries/native/oneof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/native/pojo.mustache, modules/openapi-generator/src/main/resources/Java/pojo.mustache
To close https://github.com/OpenAPITools/openapi-generator/issues/14647
```
``` 
```
``` 
=> [Java][native]Fixed StringJoiner add method parameter error

modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/handlebars/StringHelpers.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/handlebars/StringHelpersTest.java
This PR adds a `.handlebars` helper `endsWith` (a mirror version of the existing `startsWith` helper).
Closes: #14633
```
``` 
```
``` 
=> Add 'endsWith' handlebars helper function

modules/openapi-generator/src/main/resources/dart/libraries/dio/analysis_options.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/class_header.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/class_members.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/enum.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/enum_inline.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/class.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/enum.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/enum_inline.mustache, samples/openapi3/client/petstore/dart-dio/oneof/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/oneof_primitive/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/model/deprecated_object.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/model/deprecated_object.dart
Closes #13818
```
``` 
```
``` 
CC @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)
=> [dart][dart-dio] Add deprecations on models and fields

modules/openapi-generator/src/main/resources/r/modelAnyOf.mustache, modules/openapi-generator/src/main/resources/r/modelGeneric.mustache, modules/openapi-generator/src/main/resources/r/modelOneOf.mustache, samples/client/petstore/R-httr2-wrapper/R/any_of_pig.R, samples/client/petstore/R-httr2-wrapper/R/any_of_primitive_type_test.R, samples/client/petstore/R-httr2-wrapper/R/mammal.R, samples/client/petstore/R-httr2-wrapper/R/nested_one_of.R, samples/client/petstore/R-httr2-wrapper/R/one_of_primitive_type_test.R, samples/client/petstore/R-httr2-wrapper/R/pet.R, samples/client/petstore/R-httr2-wrapper/R/pig.R, samples/client/petstore/R-httr2-wrapper/R/update_pet_request.R, samples/client/petstore/R-httr2/R/any_of_pig.R, samples/client/petstore/R-httr2/R/any_of_primitive_type_test.R, samples/client/petstore/R-httr2/R/mammal.R, samples/client/petstore/R-httr2/R/nested_one_of.R, samples/client/petstore/R-httr2/R/one_of_primitive_type_test.R, samples/client/petstore/R-httr2/R/pet.R, samples/client/petstore/R-httr2/R/pig.R, samples/client/petstore/R-httr2/R/update_pet_request.R, samples/client/petstore/R/R/any_of_pig.R, samples/client/petstore/R/R/any_of_primitive_type_test.R, samples/client/petstore/R/R/mammal.R, samples/client/petstore/R/R/nested_one_of.R, samples/client/petstore/R/R/one_of_primitive_type_test.R, samples/client/petstore/R/R/pet.R, samples/client/petstore/R/R/pig.R, samples/client/petstore/R/R/update_pet_request.R
[This spec](https://github.com/OpenAPITools/openapi-generator/files/10546957/openapi.zip) generates failing code (error during `R CMD check`) because some fields have an underscore prefix.
This PR adds some backticks where necessary.
@Ramanth  @saigiridhar21 
```
```  …
=> [R] Fix escaping in templates

modules/openapi-generator/src/main/resources/rust/request.rs, samples/client/petstore/rust/hyper/petstore/src/apis/request.rs
=> [rust] Fix content-type in templates

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
Attempt to fix #14690 
```
``` 
```
``` 
=> [Fix] take numeric types into account for array defaults (fixes issue #14690

modules/openapi-generator-cli/src/test/java/org/openapitools/codegen/cmd/utils/OptionUtilsTest.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/OptionUtils.java
This PR improves the management of CommaSeparatedTuples to be able to support strings that include commas:
```
a,b,c,"1,2,3" -> [a][b][c][1,2,3]
```
When the value (ie "1,2,3") is quoted the commas are ignored and the (sub)list is considered a single value
```
```  …
=> Support CommaSeparatedTuples including commas

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/config/MergedSpecBuilder.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/config/MergedSpecBuilderTest.java, modules/openapi-generator/src/test/resources/bugs/mergerTest/spec1.json, modules/openapi-generator/src/test/resources/bugs/mergerTest/spec1.yaml, modules/openapi-generator/src/test/resources/bugs/mergerTest/spec2.json, modules/openapi-generator/src/test/resources/bugs/mergerTest/spec2.yaml
Implementation for https://github.com/OpenAPITools/openapi-generator/issues/3981
```
``` 
=> Generate merge spec

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-ktor/api.mustache, samples/client/petstore/kotlin-jvm-ktor-gson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt, samples/client/petstore/kotlin-jvm-ktor-jackson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
ktor-client doesn't support building form request from arbitrary parameters: it will happily consume values of predefined types such as `String`, `Number` etc but will fail in runtime (!) at a given line in case of say `List<T>` or `Instant`.
https://github.com/ktorio/ktor/blob/fb161cd7d268f2c0f62982d82d9264ca920173ad/ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/formDsl.kt#L63
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as an argument …
=> ktor-client add toString() for generic params

docs/usage.md
Docs-only change. Hopefully self-explanatory between the change and the issue.
Fixes #14722
- N/A Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
``` 
- N/A In case …
=> Make usage of !include more clear

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
Fixes #14688 
```
``` 
```
``` 
=> fix: Inline model schema's name is wrong

modules/openapi-generator/src/main/resources/go-server/routers.mustache, samples/server/petstore/go-api-server/go/routers.go, samples/server/petstore/go-chi-server/go/routers.go, samples/server/petstore/go-server-required/go/routers.go
```
``` 
This PR fix the issue [13927](https://github.com/OpenAPITools/openapi-generator/issues/13927).
The changes affects directly to go-server generator (chi and mux). The ```routers.go``` mustache template has been modified including a new clause that …
=> [BUG][Go] Remove "null" body value when body is empty #13927

modules/openapi-generator/src/main/resources/go-server/routers.mustache, samples/server/petstore/go-api-server/go/routers.go, samples/server/petstore/go-chi-server/go/routers.go, samples/server/petstore/go-server-required/go/routers.go
go server - use tabs instead of spaces
```
``` 
```
``` 
=> go server - use tabs instead of spaces

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
Fixes #14665 See this issue for reproducer information.  This fix does resolve the mentioned issue, but I'm not certain if it is the correct approach.
```
``` 
```
``` 
=> [Bug][Go] consider allOf schemas for rendering string default vaules

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java, modules/openapi-generator/src/main/resources/typescript/model/model.mustache, samples/openapi3/client/petstore/typescript/builds/browser/models/Order.ts, samples/openapi3/client/petstore/typescript/builds/browser/models/Pet.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/Dog.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/DogAllOf.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/PetByType.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/PetsFilteredPatchRequest.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/PetsPatchRequest.ts, samples/openapi3/client/petstore/typescript/builds/default/models/Order.ts, samples/openapi3/client/petstore/typescript/builds/default/models/Pet.ts, samples/openapi3/client/petstore/typescript/builds/deno/models/Order.ts, samples/openapi3/client/petstore/typescript/builds/deno/models/Pet.ts, samples/openapi3/client/petstore/typescript/builds/inversify/models/Order.ts, samples/openapi3/client/petstore/typescript/builds/inversify/models/Pet.ts, samples/openapi3/client/petstore/typescript/builds/jquery/models/Order.ts, samples/openapi3/client/petstore/typescript/builds/jquery/models/Pet.ts, samples/openapi3/client/petstore/typescript/builds/object_params/models/Order.ts, samples/openapi3/client/petstore/typescript/builds/object_params/models/Pet.ts, samples/openapi3/client/petstore/typescript/tests/browser/test/PetApi.test.ts, samples/openapi3/client/petstore/typescript/tests/default/test/api/PetApi.test.ts, samples/openapi3/client/petstore/typescript/tests/default/test/models/ObjectSerializer.test.ts, samples/openapi3/client/petstore/typescript/tests/deno/test/api/PetApi_test.ts, samples/openapi3/client/petstore/typescript/tests/jquery/test/api/PetApi.test.ts, samples/openapi3/client/petstore/typescript/tests/object_params/test/api/PetApi.test.ts
https://github.com/OpenAPITools/openapi-generator/issues/14569
###Related PR
https://github.com/OpenAPITools/openapi-generator/pull/14579
```
``` 
```
``` 
=> [Typescript] Enums generation (7.0.0)

modules/openapi-generator-online/pom.xml
Revert spring boot back to 2.5.14
To fix https://github.com/OpenAPITools/openapi-generator/issues/14589
```
``` 
```
``` 
=> [openapi-generator-online] Revert spring boot back to 2.5.14

modules/openapi-generator/src/main/resources/rust-server/client-operation.mustache, modules/openapi-generator/src/main/resources/rust-server/lib.mustache, modules/openapi-generator/src/main/resources/rust-server/models.mustache, modules/openapi-generator/src/main/resources/rust-server/server-operation.mustache, samples/server/petstore/rust-server/output/multipart-v3/src/lib.rs, samples/server/petstore/rust-server/output/no-example-v3/src/lib.rs, samples/server/petstore/rust-server/output/no-example-v3/src/server/mod.rs, samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs, samples/server/petstore/rust-server/output/openapi-v3/src/models.rs, samples/server/petstore/rust-server/output/openapi-v3/src/server/callbacks.rs, samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs, samples/server/petstore/rust-server/output/ops-v3/src/lib.rs, samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs, samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs, samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs, samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs, samples/server/petstore/rust-server/output/ping-bearer-auth/src/lib.rs, samples/server/petstore/rust-server/output/rust-server-test/src/lib.rs, samples/server/petstore/rust-server/output/rust-server-test/src/server/mod.rs
This pull request fixes these clippy warnings:
- clippy::disallowed_names (renamed from clippy::blacklisted_name)
- clippy::single_match (dismissed because it occurs in some cases)
- clippy::explicit_auto_deref
- clippy::needless_borrow
- clippy::suspicious_to_owned
```
```  …
=> [rust-server] Fix clippy warnings

docs/customization.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/simplifyBooleanEnum_test.yaml
Add rule (SIMPLIFY_BOOLEAN_ENUM) to simplify boolean enum so that boolean enum becomes just enum
```
``` 
```
``` 
=> Add rule to simplify boolean enum

docs/customization.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/simplifyOneOfAnyOf_test.yaml
Add rule (SIMPLIFY_ONEOF_ANYOF) to simplify oneOf/anyOf
- remove null (sub-schema) and set `nullable` to `true` instead
- simplify oneOf/anyOf with a single sub-schema to just the sub-schema itself
```
``` 
``` …
```
=> Add rule to simplify oneOf/anyOf

modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache, samples/client/petstore/ruby-autoload/lib/petstore/configuration.rb, samples/client/petstore/ruby-faraday/lib/petstore/configuration.rb, samples/client/petstore/ruby/lib/petstore/configuration.rb, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/configuration.rb, samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/configuration.rb, samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/configuration.rb
An `attr_accessor` has been added for the `return_binary_data` attribute in the Configuration object. This fixes the bug mentioned in #14771
@cliffano @zlx @autopp
```
``` 
```
``` 
=> [Ruby] fix `return_binary_data` with `attr_accessor`

modules/openapi-generator/src/main/resources/python-nextgen/model_anyof.mustache, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/any_of_color.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/any_of_pig.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/any_of_color.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/any_of_pig.py, samples/openapi3/client/petstore/python-nextgen/tests/test_model.py
based on https://github.com/OpenAPITools/openapi-generator/pull/14779 with updated samples and added tests.
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet …
=> Add from_dict in model anyOf in python-nextgen

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/resources/3_0/echo_api.yaml, samples/client/echo_api/java/apache-httpclient/api/openapi.yaml, samples/client/echo_api/java/apache-httpclient/docs/DefaultValue.md, samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/model/DefaultValue.java, samples/client/echo_api/java/apache-httpclient/src/test/java/org/openapitools/client/CustomTest.java, samples/client/echo_api/java/feign-gson/api/openapi.yaml, samples/client/echo_api/java/feign-gson/src/main/java/org/openapitools/client/model/DefaultValue.java, samples/client/echo_api/java/native/api/openapi.yaml, samples/client/echo_api/java/native/docs/DefaultValue.md, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/model/DefaultValue.java, samples/client/echo_api/java/native/src/test/java/org/openapitools/client/CustomTest.java, samples/client/echo_api/java/okhttp-gson/api/openapi.yaml, samples/client/echo_api/java/okhttp-gson/docs/DefaultValue.md, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/model/DefaultValue.java, samples/client/echo_api/python-nextgen/docs/DefaultValue.md, samples/client/echo_api/python-nextgen/openapi_client/models/default_value.py
set `isNulalble` accordingly if x-nullable is set
```
``` 
```
``` 
=> Better handling of x-nullable in codegen property

docs/customization.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
add a new rule to set tags for all operations
```
``` 
```
``` 
=> [openapi-normalizer] add a new rule to set tags for all operations

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/auth/HttpBasicAuth.mustache, modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/auth/HttpBearerAuth.mustache, modules/openapi-generator/src/main/resources/Java/libraries/webclient/auth/HttpBasicAuth.mustache, modules/openapi-generator/src/main/resources/Java/libraries/webclient/auth/HttpBearerAuth.mustache, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/webclient-jakarta/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/webclient-jakarta/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/webclient-nullable-arrays/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/webclient-nullable-arrays/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java
This utility class has been marked as deprecated for future removal since Spring 6.0.5. All Java generators, except WebClient and RestTemplate, are already using Base64 directly.
```
``` 
```
``` 
=> [Java] [WebClient] [RestTemplate] Stop using org.springframework.util.Base64Utils in Java generators

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache, samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
Java Jersey glassfish fix renewing OAuth-Accesstoken as described in issue #14734
```
``` 
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet …
=> Java Jersey glassfish fix renewing OAuth-Accesstoken #14734

modules/openapi-generator/src/main/resources/rust/Cargo.mustache, samples/client/petstore/rust/reqwest/petstore-async-middleware/Cargo.toml
Simply bump `reqwest-middleware` to its latest version: `0.2.0`
```
``` 
```
``` 
=> [RUST] Upgrade reqwest-middleware

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/api-source.mustache, samples/client/petstore/cpp-restsdk/client/src/api/PetApi.cpp, samples/client/petstore/cpp-restsdk/client/src/api/StoreApi.cpp, samples/client/petstore/cpp-restsdk/client/src/api/UserApi.cpp
This will enable parameters to contain white spaces, as this sometimes occurs when the parameters are not contained in the request body.
```
``` 
```
``` 
=> [Bug][C++-cpprest] Encode request parameters to enable whitespace characters

modules/openapi-generator/src/main/resources/cpp-pistache-server/api-impl-header.mustache, modules/openapi-generator/src/main/resources/cpp-pistache-server/model-header.mustache, modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-header.mustache, samples/server/petstore/cpp-pistache/impl/PetApiImpl.h, samples/server/petstore/cpp-pistache/impl/StoreApiImpl.h, samples/server/petstore/cpp-pistache/impl/UserApiImpl.h, samples/server/petstore/cpp-pistache/model/ApiResponse.h, samples/server/petstore/cpp-pistache/model/Category.h, samples/server/petstore/cpp-pistache/model/Order.h, samples/server/petstore/cpp-pistache/model/Pet.h, samples/server/petstore/cpp-pistache/model/Tag.h, samples/server/petstore/cpp-pistache/model/User.h
The `{{declspec}}` annotations were not consistently applied and were missing on some classes and free functions.
Side note: the `declspec` and `defaultInclude` config options are not officially documented for the cpp-pistache-server generator, but they work correctly (aside the missing annotations). Not sure if something needs to be done on that front.
My use case is that I'm building my server and APIs in a shared library and while trying to use the model classes in my tests couldn't link to it since some of the model symbols (`to_json` and `from_json` in my case) were not exported (I'm using `declspec` and `defaultInclude` for the classical use case of exporting symbols).
```
```  …
=> [C++][Pistache] Add some missing {{declspec}} on classes and functions

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java, samples/client/echo_api/python-nextgen/openapi_client/api/query_api.py
- switch union order to have StrictStr first when the allowStringInDateTimeParameters option is enabled.
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet …
=> [python-nextgen] switch union order to have StrictStr first

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
Fix for #14753
```
``` 
```
``` 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) …
=> [typescript] Fix Invalid path separator for imports on Windows

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/K6ClientCodegen.java, modules/openapi-generator/src/main/resources/k6/script.mustache, samples/client/petstore/k6/script.js
- Add the operationId to the request to make it accessible in template in K6ClientGenerator.java
- Add example in comment in script.mustache
```
``` 
```
``` 
Visiblity @mostafa
=> [K6] Enhancement: Make operationId accessible inside requests

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java, modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/EnumTest.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/enum_test.py, samples/openapi3/client/petstore/python-nextgen/docs/EnumTest.md, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/enum_test.py, samples/openapi3/client/petstore/python-nextgen/tests/test_model.py
To fix https://github.com/OpenAPITools/openapi-generator/issues/14581
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) …
=> [python-nextgen] fix enum default value

modules/openapi-generator/src/main/java/org/openapitools/codegen/config/MergedSpecBuilder.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/TypeScriptClientCodegenTest.java
Fix for https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=OpenAPITools_openapi-generator&open=AYZdW1bp7xWj06WbygBl
```
``` 
```
``` 
=> [Core] Close Stream<Path> on spec merger

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
This change removes the `modelNamePrefix` from the API import filename to be consistent with the processing in the rest of the class.
To test: run `openapi-generator-cli generate -i api.yml -g typescript-angular -o gen/api --additional-properties=modelNamePrefix=I`
In the original code you'll see:
```typescript
// model.ts
// <header>
import { IOtherModel } from './other-model';
...
```
```typescript
// service.ts
// <header>
// <external-imports>
// @ts-ignore                                                                  
import { IModel } from '../model/i-model'; /** There is no file with name "i-model.ts" */
...
```
with the changes the first file will remain the same but the second will be:
```typescript
// service.ts
// <header>
// <external-imports>
// @ts-ignore …
```
=> fix(typescript-angular): fix model filename including `modelNamePrefix`

modules/openapi-generator/src/test/java/org/openapitools/codegen/TemplateManagerTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypescriptAngularAdditionalPropertiesIntegrationTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypescriptAngularArrayAndObjectIntegrationTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypescriptAngularParamsStrategyCustomIntegrationTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypescriptAngularPetstoreIntegrationTest.java
disabled the following unit tests to stop the build in master from failing
- typescript tests (already disable in abstract generator before, re-emerge last few days likely due to change in dep/OS/build images)
- template tests related to skipping non mustache/handler (which are likely already covered in petstore tests)
```
``` 
For …
=> Disable unit tests to prevent build from failing

modules/openapi-generator/src/main/resources/python-nextgen/api.mustache, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/fake_classname_tags123_api.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/user_api.py
This PR adds overloads for the API call methods so that python tooling can properly infer whether you are calling an asynchronous method or not. The whole thing is unfortunately a little counter-intuitive, as `async_req=True` means that the request will not be using async-await, but will run in a threadpool.
```
```  …
=> [python-nextgen] Add @overload for api methods to handle async requests

modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift, samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
Since https://github.com/OpenAPITools/openapi-generator/pull/7527 got merged, the global headers always override the local headers. This means that if there is a local header that you want to customise in some requests, and you also have a global request, the global request will always prevail.
This is somehow limiting, so with this PR, the local headers set in the request override the global headers. 
@lightman73 @FranzMarini does this looks good to you?
```
```  …
=> [swift5][client] improve headers order

modules/openapi-generator/src/main/resources/csharp-netcore/model_test.mustache
related: fix https://github.com/OpenAPITools/openapi-generator/issues/14350
tested locally to confirm the fix.
(no change in samples as test files won't be overwritten)
```
``` 
```
``` 
cc …
=> Remove API import from model tests in csharp-netcore client

docs/customization.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/addUnsignedToIntegerWithInvalidMaxValue_test.yaml
To close https://github.com/OpenAPITools/openapi-generator/issues/14481
Add new openapi-normalizer rule: ADD_UNSIGNED_TO_INTEGER_WITH_INVALID_MAX_VALUE
when set to true, auto fix integer with maximum value 4294967295 (2^32-1) or long with 18446744073709551615 (2^64-1) by adding x-unsigned to the schema
```
```  …
=> Add new openapi-normalizer rule: ADD_UNSIGNED_TO_INTEGER_WITH_INVALID_MAX_VALUE

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java, modules/openapi-generator/src/test/resources/3_0/simplifyBooleanEnum_test.yaml
- minor refactoring
- fix bug in composed schema with proper processing of properties
- tested locally 
- added a test
- fix a bug in `ModelUtils.hasCommonAttributesDefined`
```
``` 
```
``` 
FYI …
=> Minor bug fix in openapi normalizer

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSCXFCDIServerCodegen.java, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/api.mustache, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/PetApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/PetApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/org/openapitools/api/impl/PetApiServiceImpl.java
Use a  single "InputStream" instead of "File" for requestBody that is binary string.
This allows the generated code to build in case of a definition like:
```
requestBody:
content:
text/plain:
schema:
type: string
format: binary
```
This fixes #9372 : without it, the generated code for that sample simply do not build.
```
``` 
For …
=> [jaxrs][cxf-cdi] use InputStream for binary body

modules/openapi-generator/src/main/resources/erlang-client/api.mustache
This change is attempting (draft currently) to fix a regression in URL Paths in the erlang-client. The current pet_store sample erlang-client does not work against the real `petstore.swagger.io` because of a regression in the Path introduced in https://github.com/OpenAPITools/openapi-generator/commit/cdc00769aadb46d4617fbec35daee643e95b7926.
Currently if one makes a request for pet id `10` the api client will make a request for `%0a` instead.
```
```  …
=> [erlang-client] Fix url path generation being passed to hackney_url

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
Fixes https://github.com/OpenAPITools/openapi-generator/issues/14745
```
``` 
```
``` 
=> [Bug][Rust] fix: removes replacement which makes x-tag-name incompatible with spec

docs/generators/kotlin-spring.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java, modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/spring/KotlinSpringServerCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/kotlin/skip-default-interface.yaml
skipDefaultInterface option to the Kotlin-Spring generator. This config option is e.g. in the [(java-)spring generator](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/spring.md) available
=> [Kotlin-Spring] add skip-default-interface option

modules/openapi-generator/src/main/resources/csharp-netcore/auth/OAuthAuthenticator.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs
For the csharp-netcore generator, some `ConfigureAwait(false)` statements were missing in the async methods. This could cause a deadlock, mainly in .NET Framework UI code. The general guidance is to use ConfigureAwait(false) if you’re writing a general-purpose library.
```
```  …
=> [csharp-netcore] Add missing ConfigureAwaits for csharp-netcore generator

modules/openapi-generator/src/main/resources/php-symfony/api_input_validation.mustache, modules/openapi-generator/src/main/resources/php-symfony/serialization/JmsSerializer.mustache, samples/server/petstore/php-symfony/SymfonyBundle-php/Service/JmsSerializer.php
This fixes the issues described on #14930 , ie: it fixes the parsing of date-time parameter, as well as non-required date-time parameters.
All the details are either on the bug report and on commit messages.
This PR can be tested by setting up a Symfony app with autogenerated code using the openapi file described on #14930 and performing the queries:
```
curl -i http://localhost:8000/my-route  # with this PR it leads to a 200 response (instead of 400 with current master)
curl -i http://localhost:8000/my-route?myparam=2017-07-21T12:34:56Z # this also returns 200 with this PR instead of a 400
```
(since this is PHP I guess I should ping @jebentier, @dkarlovi , @mandrean, @jfastnacht , @ybelenko  @renepardon (sorry in advance for the noise if I misunderstood that guideline))
```
./mvnw clean …
```
=> [PHP-Symfony] Fixes #14930

bin/configs/spring-cloud-oas3-fakeapi.yaml, bin/configs/spring-http-interface.yaml, docs/generators/java-camel.md, docs/generators/spring.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java, modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/AnimalDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/BigCatDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/CatDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/CategoryDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/DogDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/EnumTestDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/FormatTestDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/NameDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/PetDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/TypeHolderDefaultDto.java, samples/client/petstore/spring-http-interface/src/main/java/org/openapitools/model/TypeHolderExampleDto.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/Animal.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/BigCat.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/Cat.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/Category.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/Dog.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/EnumTest.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/FormatTest.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/Name.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/Pet.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/TypeHolderDefault.java, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/src/main/java/org/openapitools/model/TypeHolderExample.java
Fix for https://github.com/OpenAPITools/openapi-generator/issues/14934
```
``` 
```
``` 
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) …
=> [Java][Spring] option whether to generate required args constructor

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Using default locale for non-user visible text transformations is not safe and can result in bugs, in particular with Turkish locale.
More details in
https://mattryall.net/blog/the-infamous-turkish-locale-bug
=> [Kotlin][client] Do not use default locale in kotlin generated code

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache, modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache, samples/client/petstore/typescript-fetch/builds/allOf-nullable/runtime.ts, samples/client/petstore/typescript-fetch/builds/allOf-readonly/runtime.ts, samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/FakeApi.ts, samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts, samples/client/petstore/typescript-fetch/builds/default/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/default/runtime.ts, samples/client/petstore/typescript-fetch/builds/enum/runtime.ts, samples/client/petstore/typescript-fetch/builds/es6-target/src/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts, samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/src/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts, samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/apis/UserApi.ts, samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
See #9364
See #2870
```
``` 
```
``` 
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka
=> [BUG][typescript-fetch] wrong response for simple types

modules/openapi-generator/src/main/resources/python-nextgen/model_generic.mustache, samples/client/echo_api/python-nextgen/openapi_client/models/default_value.py, samples/client/echo_api/python-nextgen/openapi_client/models/pet.py, samples/client/echo_api/python-nextgen/openapi_client/models/query.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/enum_arrays.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/enum_test.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/map_test.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/order.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/pet.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/special_name.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/tests/test_model.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/enum_arrays.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/enum_test.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/map_test.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/order.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/pet.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/special_name.py, samples/openapi3/client/petstore/python-nextgen/tests/test_model.py
@wing328 @spacether @krjakbrjak 
This PR fixes validation of lists of enums in python-nextgen, fixes #14785 
```
``` 
=> [python-nextgen] Fix validation of list of enums

samples/openapi3/client/petstore/typescript/tests/jquery/test-runner.ts
Fix TS jQuery tests by increasing timeout
```
``` 
```
``` 
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce …
=> Fix TS jQuery tests by increasing timeout

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java, modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml, samples/client/echo_api/python-nextgen/openapi_client/api/query_api.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/README.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python-nextgen/README.md, samples/openapi3/client/petstore/python-nextgen/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen/petstore_api/api/fake_api.py
To close https://github.com/OpenAPITools/openapi-generator/issues/14912
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) …
=> [python-nextgen] use Any instead of StrictStr in any type

modules/openapi-generator/src/main/resources/python-nextgen/model_generic.mustache, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/mixed_properties_and_additional_properties_class.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/parent_with_optional_dict.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/mixed_properties_and_additional_properties_class.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/parent_with_optional_dict.py, samples/openapi3/client/petstore/python-nextgen/tests/test_model.py
- fix optional dict of object
- add test
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla …
=> [python-nextgen] fix optional dict of object

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-default-values-jvm-retrofit2/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-retrofit2-rx3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-retrofit2/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/Configuration.swift, samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
The existing `converterFactory` property worked fine, but was not available in certain cases.
I think there are these problems.
1. You can add only one `converterFactory`.
2. `converterFactory` can only be added at the very end.
In my case, I had to add my custom Converter.Factory first, because JsonParser doesn't handle empty strings and throws an exception. (#14982)
At first, I planned to add a `preConverterFactory` property, but changed `converterFactory` to an array to make it more customizable.
For backwards compatibility, `converterFactory` has not been removed from the code, it has been left using the @Deprecated annotation.
I think this PR of mine will help you meet more requirements.
```
``` …
=> Added converterFactories property to ApiClient in jvm-retrofit2.

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/issue_14907.yaml
Fix for https://github.com/OpenAPITools/openapi-generator/issues/14907
```
``` 
```
``` 
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) …
=> [Java][Spring] fix reactive method with only implicit headers (fix #14907)

modules/openapi-generator/src/main/resources/Javascript/libraries/apollo/api.mustache, modules/openapi-generator/src/main/resources/Javascript/libraries/javascript/api.mustache, samples/client/petstore/javascript-apollo/src/api/FakeApi.js, samples/client/petstore/javascript-apollo/src/api/PetApi.js, samples/client/petstore/javascript-es6/src/api/FakeApi.js, samples/client/petstore/javascript-es6/src/api/PetApi.js, samples/client/petstore/javascript-promise-es6/src/api/FakeApi.js, samples/client/petstore/javascript-promise-es6/src/api/PetApi.js
Update optional parameters in jsdoc
To close https://github.com/OpenAPITools/openapi-generator/issues/15014
```
``` 
```
``` 
=> [JS] Update optional parameters in jsdoc

modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
https://github.com/OpenAPITools/openapi-generator/issues/14928
```
``` 
```
``` 
[@wing328](https://github.com/wing328) (2015/07) [❤️](https://www.patreon.com/wing328) …
=> [Java] maven plugin to clean-up output before generation

bin/configs/python-nextgen-echo-api.yaml, docs/generators/python-nextgen.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java, samples/client/echo_api/python-nextgen/openapi_client/api/query_api.py, samples/client/echo_api/python-nextgen/test/test_manual.py
remove allowStringInDateTimeParameters option as confirmed with the user that it's no longer needed.
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) …
=> [python-nextgen] remove allowStringInDateTimeParameters option

docs/customization.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/allOf_extension_parent.yaml
Add new openapi-normalizer rule REFACTOR_ALLOF_WITH_PROPERTIES_ONLY.
When set to true, refactor schema with allOf and properties in the same level to a schema with allOf only and, the allOf contains a new schema containing the properties in the top level.
```
```  …
=> Add new openapi-normalizer rule REFACTOR_ALLOF_WITH_PROPERTIES_ONLY

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue-5676-enums.yaml, samples/client/petstore/elixir/lib/openapi_petstore/model/all_of_with_single_ref.ex, samples/client/petstore/java-helidon-client/mp/docs/AllOfWithSingleRef.md, samples/client/petstore/java-helidon-client/se/docs/AllOfWithSingleRef.md, samples/client/petstore/java/apache-httpclient/docs/AllOfWithSingleRef.md, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/model/AllOfWithSingleRef.java, samples/client/petstore/java/webclient-jakarta/docs/AllOfWithSingleRef.md, samples/client/petstore/java/webclient/docs/AllOfWithSingleRef.md, samples/client/petstore/php/OpenAPIClient-php/docs/Model/AllOfWithSingleRef.md, samples/client/petstore/php/OpenAPIClient-php/lib/Model/AllOfWithSingleRef.php, samples/client/petstore/ruby-autoload/lib/petstore/models/all_of_with_single_ref.rb, samples/client/petstore/ruby-faraday/lib/petstore/models/all_of_with_single_ref.rb, samples/client/petstore/ruby/lib/petstore/models/all_of_with_single_ref.rb, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/model/all_of_with_single_ref.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/model/all_of_with_single_ref.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/all_of_with_single_ref.dart, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/all_of_with_single_ref.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/all_of_with_single_ref.py, samples/server/petstore/cpp-restbed/generated/3_0/model/AllOfWithSingleRef.cpp, samples/server/petstore/cpp-restbed/generated/3_0/model/AllOfWithSingleRef.h, samples/server/petstore/java-helidon-server/mp/src/main/java/org/openapitools/server/model/AllOfWithSingleRef.java, samples/server/petstore/java-helidon-server/se/src/main/java/org/openapitools/server/model/AllOfWithSingleRef.java, samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/model/AllOfWithSingleRef.java, samples/server/petstore/php-laravel/lib/app/Models/AllOfWithSingleRef.php
Better allOf handling in fromProperty for allOf with a single schema (no top level attributes such as default, readOnly)
To fix https://github.com/OpenAPITools/openapi-generator/issues/14524
```
``` 
```
``` 
Commit all …
=> Better allOf handling in fromProperty

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/FormApi.java, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
Skip null form values, so no empty fields are sent. Before this change, null values were not an option (that would cause an NPE). The best could be an empty string.
```
``` 
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog …
=> [JAVA][NATIVE] Fix NPE for form values request builder

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java, modules/openapi-generator/src/main/resources/php-nextgen/.phplint.mustache, modules/openapi-generator/src/main/resources/php-nextgen/composer.mustache, modules/openapi-generator/src/main/resources/php-nextgen/gitignore, samples/client/petstore/php-nextgen/OpenAPIClient-php/.gitignore, samples/client/petstore/php-nextgen/OpenAPIClient-php/.openapi-generator/FILES, samples/client/petstore/php-nextgen/OpenAPIClient-php/.phplint.dist.yml, samples/client/petstore/php-nextgen/OpenAPIClient-php/.phplint.yml, samples/client/petstore/php-nextgen/OpenAPIClient-php/composer.json, samples/client/petstore/php-nextgen/OpenAPIClient-php/pom.xml
* Add basic config for `overtrue/phplint` package
* Change `phplint` version to 9.x since it supports PHP 8.x
* Add `phplint` run to repo CI(`pom.xml`)
Tested locally:
```console
$  composer test
> phplint
phplint 9.0.4 by overtrue and contributors.
Runtime       : PHP 8.1.6
Configuration : /Users/ybelenko/Sites/openapi-generator/samples/client/petstore/php-nextgen/OpenAPIClient-php/.phplint.yml
................................................................................................ 97 / 115 ( 84%)
...................
Time: 2 secs, Memory: 6.0 MiB, Cache: 0 hit, 115 misses
[OK] 115 files 
```
cc @Articus @jebentier @dkarlovi @mandrean @jfastnacht @renepardon
```
```  …
=> [php] Add phplint package

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java, modules/openapi-generator/src/main/resources/python-nextgen/model_generic.mustache, modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/FormatTest.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/format_test.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/tests/test_model.py, samples/openapi3/client/petstore/python-nextgen/docs/FormatTest.md, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/format_test.py
- fix pattern with double quote
- add tests
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla …
=> [python-nextgen] fix pattern with double quote

modules/openapi-generator/src/main/resources/python-nextgen/model_generic.mustache, samples/client/echo_api/python-nextgen/openapi_client/models/default_value.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/enum_test.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/health_check_result.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/nullable_class.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/outer_object_with_enum_property.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/tests/test_model.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/enum_test.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/health_check_result.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/nullable_class.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/outer_object_with_enum_property.py, samples/openapi3/client/petstore/python-nextgen/tests/test_model.py
- use `__fields_set__` to determine if the nullable field is needed (set explicitly to None) in to_dict
- add tests
- to fix https://github.com/OpenAPITools/openapi-generator/issues/15056
```
``` 
```
``` 
Commit all …
=> [python-nextgen] use __fields_set__ to determine if the field is needed in to_dict

modules/openapi-generator/src/main/resources/cpp-ue4/Build.cs.mustache, modules/openapi-generator/src/main/resources/cpp-ue4/api-operations-source.mustache, modules/openapi-generator/src/main/resources/cpp-ue4/helpers-header.mustache
Hello,
After recently updating openapi-generator  for our project I noticed some regressions in past pull requests as well as missing features. 
Additions are detailed in the commits but:
- Fixed compilation warnings
- Fixed compilation error on APIs using files in http forms, which was a big breaking change and honestly i'm surprised nobody reported it before
- Added support for enums as url parameters
- Cosmetic improvements to the generated code
```
``` 
You may regenerate an individual generator …
=> [cpp-ue4] Series of fixes for cpp-ue4

modules/openapi-generator/src/main/resources/php-nextgen/gitignore, samples/client/petstore/php-nextgen/OpenAPIClient-php/.gitignore
Since client generator is library and not a project it makes sense to exclude composer.lock from codebase by default.
Ref: http://getcomposer.org/doc/02-libraries.md#lock-file
cc @Articus @jebentier @dkarlovi @mandrean @jfastnacht @renepardon
```
``` 
``` …
```
=> [php-nextgen] Exclude composer.lock from codebase

modules/openapi-generator/src/main/resources/Java/libraries/native/pojo.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/model/DataQuery.java, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/Cat.java, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/Dog.java, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/ParentPet.java, samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/Cat.java, samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/Dog.java, samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/ParentPet.java
add @override to POJO
```
``` 
``` …
```
=> [java][native] add @override to POJO

docs/generators/python-nextgen.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java, samples/client/echo_api/python-nextgen/docs/BodyApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/FormatTest.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/PetApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/format_test.py, samples/openapi3/client/petstore/python-nextgen/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen/docs/FormatTest.md, samples/openapi3/client/petstore/python-nextgen/docs/PetApi.md, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/format_test.py
Add bytearray, none_type as primitive type. Otherwise, bytearray, none_type will be treated as model.
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) …
=> [python-nextgen] Add bytearray, none_type as primitive type

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/resources/3_0/simplifyAnyOfStringAndEnumString_test.yaml, modules/openapi-generator/src/test/resources/3_0/simplifyOneOfAnyOf_test.yaml
Fix NPE in simplifyOneOfAnyOf as getNullable can return null instead of true/false
```
``` 
```
``` 
=> [openapi-normalizer] Fix NPE in simplifyOneOfAnyOf

modules/openapi-generator/src/main/resources/python-nextgen/pyproject.mustache, samples/client/echo_api/python-nextgen/pyproject.toml, samples/openapi3/client/petstore/python-nextgen-aiohttp/pyproject.toml, samples/openapi3/client/petstore/python-nextgen/pyproject.toml
Fixes #15169, setting the authors field like `Author <author@domain.tld>`
```
``` 
```
``` 
=> fix(python-nextgen): Use spec format for authors in pyproject

modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache
Added useSwashBuckle condition to Swashbuckle attributes in models. This is to prevent uncompilable models if the useSwashBuckle property is set to false when invoking the generator.
This fixes issue #15156 
- [] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
```  …
=> Added useSwashBuckle condition to discriminator model attributes

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache, modules/openapi-generator/src/main/resources/go-server/impl.mustache, modules/openapi-generator/src/main/resources/go-server/routers.mustache, modules/openapi-generator/src/main/resources/go-server/service.mustache, samples/server/petstore/go-api-server/go/api_pet.go, samples/server/petstore/go-api-server/go/api_pet_service.go, samples/server/petstore/go-api-server/go/api_store.go, samples/server/petstore/go-api-server/go/api_store_service.go, samples/server/petstore/go-api-server/go/api_user.go, samples/server/petstore/go-api-server/go/api_user_service.go, samples/server/petstore/go-api-server/go/impl.go, samples/server/petstore/go-api-server/go/routers.go, samples/server/petstore/go-chi-server/go/api_pet.go, samples/server/petstore/go-chi-server/go/api_pet_service.go, samples/server/petstore/go-chi-server/go/api_store.go, samples/server/petstore/go-chi-server/go/api_store_service.go, samples/server/petstore/go-chi-server/go/api_user.go, samples/server/petstore/go-chi-server/go/api_user_service.go, samples/server/petstore/go-chi-server/go/impl.go, samples/server/petstore/go-chi-server/go/routers.go, samples/server/petstore/go-server-required/go/api_pet.go, samples/server/petstore/go-server-required/go/api_pet_service.go, samples/server/petstore/go-server-required/go/api_store.go, samples/server/petstore/go-server-required/go/api_store_service.go, samples/server/petstore/go-server-required/go/api_user.go, samples/server/petstore/go-server-required/go/api_user_service.go, samples/server/petstore/go-server-required/go/impl.go, samples/server/petstore/go-server-required/go/routers.go
Change merge branch for PR #10140
Since the operation ID should be unique for each API group, it is more rightly for the routes to be `map[string]Route` instead of the name being a field of Route.
Also, this allows for easy embedding compared to using []Route.
For example, if you wish to embed the controller and "override" a `DeleteOrder` you would have to "override" the whole `Routes()` method like so...
```
// Routes returns all of the api route for the StoreApiController
func (c *StoreApiController) Routes() Routes {
return Routes{
"DeleteOrder": Route{
strings.ToUpper("Delete"),
"/v2/store/order/{orderId}",
c.DeleteOrder,
},
"GetInventory": Route{
strings.ToUpper("Get"),
"/v2/store/inventory",
c.GetInventory,
},
"GetOrderById": Route{
strings.ToUpper("Get"), …
```
=> [go-server] Change Routes type from `[]Route` to `map[string]Route`

modules/openapi-generator/src/main/resources/Java/libraries/vertx/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/vertx/pom.mustache, samples/client/petstore/java/vertx-no-nullable/build.gradle, samples/client/petstore/java/vertx-no-nullable/pom.xml, samples/client/petstore/java/vertx/build.gradle, samples/client/petstore/java/vertx/pom.xml
Update vertx to newer version 3.5.2
To fix https://github.com/OpenAPITools/openapi-generator/issues/15195
```
``` 
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov …
=> [java] Update vertx to newer version 3.5.2

README.md
Add blog that explains how to customise Mustache templates during code generation
```
``` 
```
``` 
=> Add blog Mustache templates with OpenAPI generator

modules/openapi-generator/src/main/resources/go-server/go.mod.mustache, modules/openapi-generator/src/main/resources/go-server/helpers.mustache, modules/openapi-generator/src/main/resources/go-server/model.mustache, samples/server/petstore/go-api-server/go.mod, samples/server/petstore/go-api-server/go/helpers.go, samples/server/petstore/go-api-server/go/model_api_response.go, samples/server/petstore/go-api-server/go/model_category.go, samples/server/petstore/go-api-server/go/model_order.go, samples/server/petstore/go-api-server/go/model_pet.go, samples/server/petstore/go-api-server/go/model_tag.go, samples/server/petstore/go-api-server/go/model_user.go, samples/server/petstore/go-chi-server/go.mod, samples/server/petstore/go-chi-server/go/helpers.go, samples/server/petstore/go-chi-server/go/model_api_response.go, samples/server/petstore/go-chi-server/go/model_category.go, samples/server/petstore/go-chi-server/go/model_order.go, samples/server/petstore/go-chi-server/go/model_pet.go, samples/server/petstore/go-chi-server/go/model_tag.go, samples/server/petstore/go-chi-server/go/model_user.go, samples/server/petstore/go-server-required/go.mod, samples/server/petstore/go-server-required/go/helpers.go, samples/server/petstore/go-server-required/go/model_an_object.go, samples/server/petstore/go-server-required/go/model_api_response.go, samples/server/petstore/go-server-required/go/model_category.go, samples/server/petstore/go-server-required/go/model_order.go, samples/server/petstore/go-server-required/go/model_order_info.go, samples/server/petstore/go-server-required/go/model_pet.go, samples/server/petstore/go-server-required/go/model_special_info.go, samples/server/petstore/go-server-required/go/model_tag.go, samples/server/petstore/go-server-required/go/model_user.go
The required Go version in go.mod is 1.13. Since Chi requires 1.14, this is not suitable.
Since Go versions <1.18 has been long end-of-life, and >=1.18 is required for generics 1.18 is used.
Other updates include
- bump Chi and Mux dependencies
- Change recurse to use generics
```
```  …
=> [go-server] Update dependencies and use generics

.github/workflows/samples-go.yaml, samples/server/petstore/go-api-server/README.md
Improve Go Github workflow by installing missing dependencies.
```
``` 
```
``` 
FYI @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 …
=> Improve Go Github workflow

docs/generators/groovy.md, docs/generators/java-camel.md, docs/generators/java-helidon-client.md, docs/generators/java-helidon-server.md, docs/generators/java-inflector.md, docs/generators/java-micronaut-client.md, docs/generators/java-micronaut-server.md, docs/generators/java-msf4j.md, docs/generators/java-pkmst.md, docs/generators/java-play-framework.md, docs/generators/java-undertow-server.md, docs/generators/java-vertx-web.md, docs/generators/java-vertx.md, docs/generators/java.md, docs/generators/jaxrs-cxf-cdi.md, docs/generators/jaxrs-cxf-client.md, docs/generators/jaxrs-cxf-extended.md, docs/generators/jaxrs-cxf.md, docs/generators/jaxrs-jersey.md, docs/generators/jaxrs-resteasy-eap.md, docs/generators/jaxrs-resteasy.md, docs/generators/jaxrs-spec.md, docs/generators/spring.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
Another PR to fix #13484 and other related issues, as other PR's are either closed or change default behavior.
allow to specify the useOneOfInterfaces option for java as was once possible in 4.3.1 and below.
Note that this PR does not change default behavior, nor does it introduce any new behavior as the useOneOfInterfaces is an existing option but was no longer exposed.
```
```  …
=> allow to specify the useOneOfInterfaces option for java

modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api.mustache
In order to properly use jakarta packages instead of javax packages when beanValidation is turned on in addition to useJakartaEE being set to true. 
Settings from the configOptions. 
useBeanValidation: "true",
microprofileRestClientVersion: "3.0",
useJakartaEE: "true",
```
``` 
FYI @bbdouglas @sreeshas @jfiala  @lukoyanov  @cbornet  @jeff9finger  @karismann  @Zomzog @lwlee2608
=> [java] For microprofile generator use rootJavaEEPackage instead of javaxPackage for specifiying JavaEE Base package

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
[ModelUtils] Remove deprecated warning (which is scheduled to be removed in 6.x)
Users should use `REF_AS_PARENT_IN_ALLOF` in openapi normalizer instead if they want inheritance without using `discriminator.propertyName`
```
```  …
=> [ModelUtils] Remove deprecated warning

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
Better null check in processUseAllOfRefAsParent (openapi normalizer) 
FYI  @OpenAPITools/generator-core-team 
```
``` 
```
``` 
=> Better null check in processUseAllOfRefAsParent (openapi normalizer)

modules/openapi-generator/src/main/resources/python-nextgen/model_generic.mustache, samples/client/echo_api/python-nextgen/openapi_client/models/default_value.py, samples/client/echo_api/python-nextgen/openapi_client/models/pet.py, samples/client/echo_api/python-nextgen/openapi_client/models/query.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/enum_arrays.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/enum_test.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/format_test.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/map_test.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/order.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/pet.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/special_name.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/enum_arrays.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/enum_test.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/format_test.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/map_test.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/order.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/pet.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/special_name.py, samples/openapi3/client/petstore/python-nextgen/tests/test_model.py
To fix https://github.com/OpenAPITools/openapi-generator/issues/15134
Add null check when the optional/nullable type is defined with regular expression
```
``` 
```
``` 
FYI @taxpon (2017/07) …
=> [python-nextgen] Better null check for regular expression validator

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java
Fix printing empty notes since an empty string is truthy
```
``` 
```
``` 
@eriktim
=> [Elm] Fix printing empty notes

modules/openapi-generator/src/main/resources/cpp-ue4/api-operations-source.mustache
Hello, I made another pull request that addresses different issue. Query parameter generation works very well except "multi" collection format. `CollectionToUrlString_multi` generates "key=value1&key=value2&..." like string and if used with query string, duplicated key string is appended like:
`key=key=value1&key=value2`
This commit separates "multi" type collection query string generation from other types.
@Kahncode 
```
```  …
=> [cpp-ue4] Fix multi collection format has duplicated prefix

modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache, samples/client/petstore/ruby-autoload/lib/petstore/configuration.rb, samples/client/petstore/ruby-faraday/lib/petstore/configuration.rb, samples/client/petstore/ruby/lib/petstore/configuration.rb, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/configuration.rb, samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/configuration.rb, samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/configuration.rb
@cliffano, @zlx, @autopp
As discussed in https://github.com/OpenAPITools/openapi-generator/pull/7415#discussion_r1113274416, it seems unlikely the code was correct.
server_operation_index is a hash table. In Ruby, `hash[key]` will return the value associated with `key`. If key is absent, `nil` is returned. Because that is sometimes undesirable, there is also `hash.fetch(key)`, which raises an error if the key is absent. It also allows you to specify a default to fall back on: `hash.fetch(key, default)` will return `default` if the key is absent.
So, since not all users will specify a 'server per operation' (or at least: I'm not), the old code would usually set `index` to the `server_index`, which is initialized to 0. The subsequent `if index == nil` will usually return false (`0 != nil` …
=> [Ruby] Client: fix base_url when no server_operation_index is defined

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/resources/3_0/simplifyOneOfAnyOf_test.yaml
- Fix nullable boolean check in oneOf schema as getNulalble can return null
- add tests
```
``` 
```
``` 
=> [openapi-normalizer] Fix nullable boolean check in oneOf schema

modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/config/MergedSpecBuilder.java
Adding documentation for maven options and gradle options which are already present, but not documented yet.
--------------
```
``` 
=> add missing documentation for maven and gradle options

modules/openapi-generator/pom.xml, pom.xml
Update git-commit-id maven plugin to newer version and skip git build time to improve build caching.
```
``` 
```
``` 
=> Update git-commit-id maven plugin to newer version

modules/openapi-generator/src/main/resources/python-nextgen/model_anyof.mustache, modules/openapi-generator/src/main/resources/python-nextgen/model_oneof.mustache, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/any_of_color.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/any_of_pig.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/color.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/models/pig.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/any_of_color.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/any_of_pig.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/color.py, samples/openapi3/client/petstore/python-nextgen/petstore_api/models/pig.py, samples/openapi3/client/petstore/python-nextgen/tests/test_model.py
- fix to_json, to_dict in handling primitive types (e.g. [1, 23, 456]
- add tests
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco …
=> [python-nextgen] fix to_json, to_dict in handling primitive types

docs/generators.md, docs/generators/python-nextgen.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java
Mark python-nextgen client generator as stable
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) …
=> Mark python-nextgen client generator as stable

modules/openapi-generator/src/main/resources/dart/libraries/dio/api.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/class_members.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/class.mustache, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/pet_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/model/deprecated_object.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/model/object_with_deprecated_fields.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/pet_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/model/deprecated_object.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/model/object_with_deprecated_fields.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/pet_api_test.dart
Addresses problems in #13818
```
``` 
```
``` 
CC @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)
=> [dart][dart-dio] Fix property deprecation and add parameter deprecation

modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom_3.0.mustache, samples/client/petstore/java/microprofile-rest-client-3.0/pom.xml, samples/client/petstore/java/microprofile-rest-client-3.0/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/microprofile-rest-client-3.0/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/microprofile-rest-client-3.0/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/microprofile-rest-client/pom.xml, samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/UserApi.java
Follow-up for #6680.
Using the microprofile library requires an additional (unnecessary) dependency in a project. If one uses a different implementation than CXF, e.g. Jersey, the CXF dependency has to be pulled in additionally. But Jersey has an own implementation for multipart handling.
The dependency and the corresponding import aren't used at the moment. Thus, they can be safely deleted.
```
```  …
=> [Java] [Microprofile] Remove unused CXF dependency

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/api-source.mustache, samples/client/petstore/cpp-restsdk/client/src/api/PetApi.cpp, samples/client/petstore/cpp-restsdk/client/src/api/StoreApi.cpp, samples/client/petstore/cpp-restsdk/client/src/api/UserApi.cpp
This pull request is a follow up to #14797 where I missed the actual encoding call not beeing encode but encode_uri
```
``` 
```
``` 
@muttleyxd @MartinDelille @etherealjoy @stkrwork @ravinikam
=> Fix request parameter encode call

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pojo.mustache
It's clear that these imports are missing in the mustache file for the okhttp-gson pojo.
Description of the problem can be found under #14599
=>  [BUG] [JAVA] Missing imports in okhttp-gson client #14599 

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoGinServerCodegen.java, modules/openapi-generator/src/main/resources/go-gin-server/go.mod.mustache, modules/openapi-generator/src/main/resources/go-gin-server/main.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/goginserver/GoGinServerCodegenTest.java, samples/server/petstore/go-gin-api-server/.openapi-generator/FILES, samples/server/petstore/go-gin-api-server/go.mod, samples/server/petstore/go-gin-api-server/main.go
Add `go.mod` in Go Gin Server generator as it is a required directive (the same approach is taken for the Go client) and it conveniently declares the `gin-gonic` dependency.
```
``` 
```
```  …
=> [GO] Add go.mod in go-gin-server generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java, modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python-nextgen/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen/petstore_api/api/fake_api.py
For bytes with validations returned structure:
`Union[conbytes, consts](%s)`
raises exception _Cannot instantiate typing.Union_.
This PR fixes it by adding parameters to types separately.
Thanks for reviewing and merging.
```
``` 
``` …
```
=> [python-nextgen] fix typing for bytes with validations

modules/openapi-generator/src/main/resources/dart/libraries/dio/api.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/api/deserialize.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/api/deserialize.mustache, samples/openapi3/client/petstore/dart-dio/oneof/lib/src/api/default_api.dart, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/lib/src/api/bar_api.dart, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/lib/src/api/foo_api.dart, samples/openapi3/client/petstore/dart-dio/oneof_primitive/lib/src/api/default_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/another_fake_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/default_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/fake_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/fake_classname_tags123_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/pet_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/store_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/api/user_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/another_fake_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/default_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/fake_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/fake_classname_tags123_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/pet_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/store_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/user_api.dart
Modify mustache files to handle cases where the response data is null (e.g. status code 204) instead of throwing an exception
fixes https://github.com/OpenAPITools/openapi-generator/issues/15426
```
``` 
```
``` 
Commit …
=> [dart-dio] fix endpoints returning null

docs/generators/apex.md, docs/generators/cpp-tiny.md, docs/generators/cpp-ue4.md, docs/generators/fsharp-giraffe-server.md, docs/generators/javascript-apollo-deprecated.md, docs/generators/javascript-closure-angular.md, docs/generators/javascript.md, docs/generators/jetbrains-http-client.md, docs/generators/julia-client.md, docs/generators/julia-server.md, docs/generators/k6.md, docs/generators/markdown.md, docs/generators/plantuml.md, docs/generators/python-fastapi.md, docs/generators/python-flask.md, docs/generators/swift5.md, docs/generators/wsdl-schema.md, docs/generators/xojo-client.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ProcessUtils.java
Adds initial support for OpenID Connect security.
See #425 
```
``` 
```
``` 
=> Initial OIDC support

modules/openapi-generator/src/main/resources/typescript/package.mustache, samples/client/others/typescript/builds/with-unique-items/package.json, samples/openapi3/client/petstore/typescript/builds/browser/package-lock.json, samples/openapi3/client/petstore/typescript/builds/browser/package.json, samples/openapi3/client/petstore/typescript/builds/composed-schemas/package.json, samples/openapi3/client/petstore/typescript/builds/default/package-lock.json, samples/openapi3/client/petstore/typescript/builds/default/package.json, samples/openapi3/client/petstore/typescript/builds/inversify/package-lock.json, samples/openapi3/client/petstore/typescript/builds/inversify/package.json, samples/openapi3/client/petstore/typescript/builds/jquery/package-lock.json, samples/openapi3/client/petstore/typescript/builds/jquery/package.json, samples/openapi3/client/petstore/typescript/builds/object_params/package-lock.json, samples/openapi3/client/petstore/typescript/builds/object_params/package.json, samples/openapi3/client/petstore/typescript/tests/browser/package-lock.json, samples/openapi3/client/petstore/typescript/tests/default/package-lock.json, samples/openapi3/client/petstore/typescript/tests/inversify/package-lock.json, samples/openapi3/client/petstore/typescript/tests/jquery/package-lock.json, samples/openapi3/client/petstore/typescript/tests/object_params/package-lock.json
- Add types to exports in package.json
- Regenerate and build petstore samples
These types exports are necessary for the module resolution in typescript 5.
```
``` 
```
``` 
Cf. @TiFu (2017/07) …
=> [typescript] Add missing types field to export declaration

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/BodyApi.java, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/FormApi.java, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/HeaderApi.java, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/PathApi.java, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/QueryApi.java
fix https://github.com/OpenAPITools/openapi-generator/issues/15310
fix https://github.com/OpenAPITools/openapi-generator/issues/12616
Reported problem occurs because the checks for "text/plain" Content Type did not account for the possibility that the Content Type _additionally_ specifies the charset. i.e. "text/plain;charset=UTF-8" was not properly recognized as "text/plain" case.
According to the [Media Type specification](https://www.rfc-editor.org/rfc/rfc9110.html#media.type), we can ignore everything after the first ";", so that's what my fix does.
------------
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge …
=> [JAVA] fix "text/plain" with charset specification

modules/openapi-generator/src/main/resources/dart2/api.mustache, modules/openapi-generator/src/main/resources/dart2/serialization/native/native_class.mustache, samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api/pet_api.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/model/pet.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/pet_api.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/array_of_number_only.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/array_test.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/object_with_deprecated_fields.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/pet.dart
A couple of weeks ago, I created a pr to support unique items in an array (effectively, producing a `Set` instead of a `List`). The pr in question has been approved and merged: https://github.com/OpenAPITools/openapi-generator/pull/15027
With that being said, and as @ahmednfwela tried to explain in the comments in that pr, Dart is unable to encode a `Set` properly and would throw instead. This pr fixes that issue and ensures that a `Set` is encoded as a JSON `List`.
```
```  …
=> Encode a `Set` in `toJson()` properly

.github/PULL_REQUEST_TEMPLATE.md
The PULL_REQUEST_TEMPLATE is updated to use the correct script name
```
``` 
```
``` 
=> Correct name of script in PULL_REQUEST_TEMPLATE.md

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/JsonConverter.mustache
The anyOf and oneOf where out of order. Just matching what is in the constructor.
```
``` 
```
``` 
=> [csharp-netcore][generichost] Fixed the order to match the constructor

samples/client/petstore/go/auth_test.go, samples/client/petstore/go/fake_api_test.go, samples/client/petstore/go/pet_api_test.go, samples/client/petstore/go/store_api_test.go, samples/client/petstore/go/user_api_test.go
=> Fix Go client tests

modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/pom-sb3.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/pom.mustache
As interfaceOnly=true not generates main class the repackage goal for the artifact fails.
This change applies the same template as used in JavaSpring or in kotlin-spring spring-cloud library.
You can reproduce this using a minimal sample demonstrated in this repository https://github.com/zaenk/kotlin-spring-interface-only
- this repo generate the code using `npx @openapitools/openapi-generator-cli generate -i openapi.yaml -g kotlin-spring --additional-properties=interfaceOnly=true` command
- you can observe the faulty behaviour running `mvn repackge` after the code is generated. For reference here are the relevant logs:
```
------------------------------------------------------------------------
[INFO] Total time:  7.281 s
[INFO] Finished at: 2023-05-12T17:50:06+02:00
[INFO] …
```
=> [kotlin-spring] interfaceOnly=true flag skips spring-boot plugin repackage goal

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/XojoClientCodegen.java
rename private method to avoid confusion as default codegen also has a method named `getPropertyDefaultValue`
cc @Topheee
```
``` 
```
``` 
=> [xojo] rename private method to avoid confusion

.github/workflows/samples-dotnet.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java, modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache, samples/server/petstore/aspnetcore-6.0-project4Models/.openapi-generator/FILES, samples/server/petstore/aspnetcore-6.0-useNewtonsoft/src/Org.OpenAPITools/Controllers/PetApi.cs, samples/server/petstore/aspnetcore-6.0-useNewtonsoft/src/Org.OpenAPITools/Controllers/StoreApi.cs, samples/server/petstore/aspnetcore-6.0-useNewtonsoft/src/Org.OpenAPITools/Controllers/UserApi.cs, samples/server/petstore/aspnetcore-6.0-useNewtonsoft/src/Org.OpenAPITools/Models/Animal.cs
a follow PR to https://github.com/OpenAPITools/openapi-generator/pull/15515
```
``` 
```
``` 
Technical committee: @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) …
=> Minor enhancements to the aspnetcore server generator

modules/openapi-generator/src/main/resources/Javascript-Apollo/README.mustache, modules/openapi-generator/src/main/resources/Javascript-Flowtyped/api.mustache, modules/openapi-generator/src/main/resources/Javascript/README.mustache, samples/client/petstore/javascript-apollo/README.md, samples/client/petstore/javascript-es6/README.md, samples/client/petstore/javascript-promise-es6/README.md
Follow-up of #15220 but for other generators
```
``` 
=> [javascript] fix use of isBasicBasic and isBasicBearer conditions

modules/openapi-generator/src/main/resources/cpp-pistache-server/model-source.mustache, modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-source.mustache, samples/server/petstore/cpp-pistache/model/ApiResponse.cpp, samples/server/petstore/cpp-pistache/model/Category.cpp, samples/server/petstore/cpp-pistache/model/Order.cpp, samples/server/petstore/cpp-pistache/model/Pet.cpp, samples/server/petstore/cpp-pistache/model/Tag.cpp, samples/server/petstore/cpp-pistache/model/User.cpp
The `to_json` utilities produce a `null` JSON value instead of an empty `{}` object when all the object properties are optional and not provided. The json object is default constructed (null value). In case there is at least one property affecting it will turn the null/default json into an object, which is not the case with no properties.
* I found it with and use the class model but I think the issue is the same for the struct model, so I fixed that too.
* I don't really understand all the data modes, but I think the enum case should be correct as the value of `j` will be completely overwritten. However I don't know how the `vendorExtensions.x-is-string-enum-container` case work, hopefully this is also correct?
``` …
```
=> [C++][Pistache] Generate empty JSON object instead of a null value

modules/openapi-generator/src/main/resources/cpp-pistache-server/api-header.mustache, samples/server/petstore/cpp-pistache/api/PetApi.h, samples/server/petstore/cpp-pistache/api/StoreApi.h, samples/server/petstore/cpp-pistache/api/UserApi.h
This is following #15279
Marking those methods 'override' should avoid producing `-Winconsistent-missing-override` warnings or similar.
```
``` 
```
``` 
=> [C++][Pistache] Add missing 'override' on virtual methods

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/clientConfiguration.mustache
Follow-up of #15220 but for Java-Spring
```
``` 
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) …
=> [Spring] fix use of isBasic condition

modules/openapi-generator/src/main/resources/aspnetcore/3.0/Formatters/InputFormatterStream.mustache, samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs, samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs, samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs, samples/server/petstore/aspnetcore-6.0-pocoModels/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs, samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs, samples/server/petstore/aspnetcore-6.0-useNewtonsoft/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs, samples/server/petstore/aspnetcore-6.0-useSwashBuckle/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs, samples/server/petstore/aspnetcore-6.0/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs
Simply add documentation. Without this, it creates warning when building the code.
```
``` 
```
``` 
Commit all …
=> Fix warning when building because of the missing documentation

docs/new-generator.md
OpenIdConnect and HTTP Bearer and HTTP signature  are missing from the template for new generator README.md
```
``` 
=> add missing security schemes to new generator README template

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
To close https://github.com/OpenAPITools/openapi-generator/issues/14119
=> Fix the bug that the property generateApis always true

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
fix https://github.com/OpenAPITools/openapi-generator/issues/15483
```
``` 
```
``` 
=> [Gradle] add `inputSpecRootDirectory` for generate task

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/api.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/UserApi.cs
Adds an OrDefault operation. If the request is not critical, the user can call this method and just ignore any errors. The error will still get logged by the none default operation.
```
``` 
```
``` 
=> [csharp-netcore][generichost] Added OrDefault method

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
typo in https://github.com/OpenAPITools/openapi-generator/pull/15185 introduces this build error if you use bool params in your spec:
```
*hidden*: cannot use parseBool (value of type func(param string) (bool, error)) as type ParseString[float32] in argument to WithParse[float32]
``` 
This PR fixes typo
```
``` 
For Windows users, please …
=> fix incorrect generic type in go-server codegen template

modules/openapi-generator/src/main/resources/lua/README.mustache, modules/openapi-generator/src/main/resources/lua/api.mustache
Follow-up of #15220 but for other generators
```
``` 
@daurnimator (2017/08)
=> [lua] fix use of isBasic condition

modules/openapi-generator/src/main/resources/xojo-client/README.mustache, modules/openapi-generator/src/main/resources/xojo-client/api.mustache, modules/openapi-generator/src/main/resources/xojo-client/api_mock.mustache
Follow-up of #15220 but for xojo
```
``` 
@Topheee (2023/04)
=> [xojo] fix use of isBasic condition

modules/openapi-generator/src/main/resources/Eiffel/README.mustache, modules/openapi-generator/src/main/resources/Eiffel/api_client.mustache
Follow-up of #15220 but for Eiffel
```
``` 
@jvelilla (2017/09)
=> [eiffel] fix use of isBasic condition

modules/openapi-generator/src/main/resources/android/README.mustache, modules/openapi-generator/src/main/resources/android/libraries/volley/apiInvoker.mustache
Follow-up of #15220 but for android
```
``` 
@jaz-ah (2017/09)
=> [android] fix use of isBasic condition

modules/openapi-generator/src/main/resources/powershell/README.mustache, modules/openapi-generator/src/main/resources/powershell/api_doc.mustache, samples/client/petstore/powershell/README.md, samples/client/petstore/powershell/docs/PSFakeApi.md, samples/client/petstore/powershell/docs/PSPetApi.md
Follow-up of #15220 but for powershell
```
``` 
@wing328 (2020/05)
=> [powershell] fix use of isBasic condition

modules/openapi-generator/src/main/resources/php-slim-server/README.mustache, modules/openapi-generator/src/main/resources/php-slim4-server/README.mustache, modules/openapi-generator/src/main/resources/php-symfony/README.mustache, modules/openapi-generator/src/main/resources/php-symfony/api_controller.mustache, modules/openapi-generator/src/main/resources/php/README.mustache, samples/client/petstore/php/OpenAPIClient-php/README.md
Follow-up of #15220 but for PHP
**isBasic is true for HTTP bearer auth method and HTTP signature method, not only HTTP basic auth method; it should not be used when we want to apply code changes in the context of HTTP basic auth only!**
```
``` 
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), …
=> [PHP] fix use of isBasic condition

modules/openapi-generator/src/main/resources/perl/README.mustache, modules/openapi-generator/src/main/resources/perl/api_doc.mustache, samples/client/petstore/perl/README.md, samples/client/petstore/perl/docs/FakeApi.md
Follow-up of #15220 but for Perl
```
``` 
@wing328 (2017/07) [❤️](https://www.patreon.com/wing328) @yue9944882 (2019/06)
=> [perl] fix use of isBasic condition

modules/openapi-generator/src/main/resources/bash/Dockerfile.mustache, modules/openapi-generator/src/main/resources/bash/README.mustache, modules/openapi-generator/src/main/resources/bash/client.mustache, samples/client/petstore/bash/README.md
Follow-up of #15220 but for bash
```
``` 
@frol (2017/07) @bkryza (2017/08) @kenjones-cisco (2017/09)
=> [bash] fix use of isBasic condition

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaPlayFrameworkCodegen.java
Add missing attributes to CodeGen copies + refactor to simplify code and reduce risk of such mistakes happening again
```
``` 
Ada: @stcarrez (2018/02) @michelealbano (2018/02)
Java: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov …
=> [Ada] [Java] fix Codegen copies

modules/openapi-generator/src/main/resources/cpp-qt-client/README.mustache, modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/api-source.mustache
Follow-up of #15220 but for C++
```
``` 
@ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) …
=> [cpp C++] fix use of isBasic condition

.github/workflows/check-supported-versions.yaml, pom.xml
- update pom.xml with new plugin, setting
- revise workflow (check supported version)
```
``` 
```
``` 
=> Update pom.xml with new plugin, setting

modules/openapi-generator/src/main/resources/dart/libraries/dio/README.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/api_doc.mustache, modules/openapi-generator/src/main/resources/dart2/README.mustache, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/README.md, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/doc/FakeApi.md, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/README.md, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/doc/FakeApi.md, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/README.md
Follow-up of #15220 but for dart
```
``` 
@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) …
=> [dart] fix use of isBasic condition

modules/openapi-generator/src/main/resources/swift5/README.mustache, modules/openapi-generator/src/main/resources/swift5/api.mustache
Follow-up of #15220 but for Swift
```
``` 
@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu …
=> [swift5] fix use of isBasic condition

modules/openapi-generator/src/main/resources/rust-server/README.mustache, modules/openapi-generator/src/main/resources/rust/hyper/api.mustache
Follow-up of #15220 but for other generators
```
``` 
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh …
=> [rust] fix use of isBasic condition

docs/generators/groovy.md, modules/openapi-generator/src/main/resources/Groovy/ApiUtils.mustache, modules/openapi-generator/src/main/resources/Groovy/model.mustache, modules/openapi-generator/src/main/resources/Groovy/modelClass.mustache, modules/openapi-generator/src/main/resources/Groovy/modelEnum.mustache, samples/client/petstore/groovy/src/main/groovy/org/openapitools/api/ApiUtils.groovy, samples/client/petstore/groovy/src/main/groovy/org/openapitools/model/Order.groovy, samples/client/petstore/groovy/src/main/groovy/org/openapitools/model/Pet.groovy
Adds enum generation instead of empty classes in groovy client. This problem could be fixed using new template with `-t` params, but I found an issue #14420  and decided to open this PR. 
Changes:
* model: added generation of enums in separate classes and nested enums
* ApiUtils: added custom request encoder. JsonGenerator in groovy allows  by default usage of Enum.name() instead of value field. groovyx.net.http.HttpBuilder does not support customizing of JsonGenerator, but it supports overriding of encoder.
```
```  …
=> [groovy] support enum generation in groovy client

docs/generators/kotlin-server.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerCodegen.java, modules/openapi-generator/src/main/resources/kotlin-server/libraries/jaxrs-spec/api.mustache, modules/openapi-generator/src/main/resources/kotlin-server/libraries/jaxrs-spec/build.gradle.mustache, modules/openapi-generator/src/main/resources/kotlin-server/libraries/jaxrs-spec/generatedAnnotation.mustache, modules/openapi-generator/src/main/resources/kotlin-server/libraries/jaxrs-spec/model.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinServerCodegenTest.java, samples/server/petstore/kotlin-server/jaxrs-spec/build.gradle
Support the `jakarta.*` namespace for the kotlin-server generator. This was already implemented in the jaxrs-spec and kotlin-spring generators.
```
``` 
```
``` 
cc @jimschubert (2017/09) …
=> [kotlin-server] add support for jakarta ee namespace

modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache, samples/client/petstore/rust/reqwest/petstore-async-middleware/src/apis/pet_api.rs, samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs, samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/apis/pet_api.rs, samples/client/petstore/rust/reqwest/petstore/src/apis/pet_api.rs
based on https://github.com/OpenAPITools/openapi-generator/pull/15314 with updated samples.
cc @gkobeaga 
```
``` 
```
``` 
cc @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh …
=> [rust-client]: fix for collectionFormat=multi

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
Fix go server string comparison using StringUtils.isNotEmpty
```
``` 
```
``` 
=> [go-server] fix string comparison

modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache, samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-unityWebRequest/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Configuration.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/Configuration.cs
Related to the issue [15576](https://github.com/OpenAPITools/openapi-generator/issues/15576)
- For some API definitions(i.e.: Yapily openapi definition https://api.yapily.com/docs/v3/openapi.json), the `Operation` and `OperationIndex` properties are not defined for each endpoint(i.e.: AddUserUsingPOSTWithHttpInfoAsync in Yapily) and because of that, the method GetOperationServerUrl in the class Configuration raise an `ArgumentNullException`
- This PR adds a null check to avoid this exception
```
```  …
=> Adds operation null check avoid null exception

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java, modules/openapi-generator/src/test/resources/3_0/issue_11772.yml
Fix for https://github.com/OpenAPITools/openapi-generator/issues/15408
Related PR https://github.com/OpenAPITools/openapi-generator/pull/14882
```
``` 
```
``` 
=> Fix extensions handling for allOf with single schema

modules/openapi-generator/src/main/resources/typescript-inversify/api.service.mustache, modules/openapi-generator/src/main/resources/typescript-jquery/api.mustache, modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache, modules/openapi-generator/src/main/resources/typescript-rxjs/apis.mustache
Follow-up of #15220 but for typescript
```
``` 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) …
=> [typescript] fix use of isBasic condition

docs/templating.md
While trying to customize templates I struggled to find a reference list of the variables available to me. A link to the source would have helped a lot, so I hope it helps the next person.
```
``` 
```
```  …
=> docs (templating): add link to find more template variables

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java, modules/openapi-generator/src/main/resources/python-fastapi/api.mustache, modules/openapi-generator/src/main/resources/python-fastapi/base_api.mustache, modules/openapi-generator/src/main/resources/python-fastapi/impl_argument.mustache, modules/openapi-generator/src/main/resources/python-fastapi/impl_argument_definition.mustache, samples/server/petstore/python-fastapi/.openapi-generator/FILES, samples/server/petstore/python-fastapi/src/openapi_server/apis/pet_api.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/pet_api_base.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/store_api.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/store_api_base.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api_base.py
It is very difficult to "merge" the changes, made by code generation, and the changes, made by developers. It would be very useful to separate the generated code and the code written by developers. In addition this would remove the necessity to track the generated code. Pyhton (since 3.6) has a hook, __init_subclasses__, that could be used to solve exactly this problem.
The classes from *_base.py should be implemented in an ns package that is specified by the additional parameter ("-p fastapiImplementationPackage=example_name").
Signed-off-by: Nikita Vakula <programmistov.programmist@gmail.com>
```
```  …
=> [python-fastapi] Added a base class for the actual implementation

run-in-docker.sh
OpenAPI Generator 7 requires JDK 11+, but the `run-in-docker.sh` had not been updated and was still using JDK 8.
Related to #15333.
Before this fix:
```console
$ ./run-in-docker.sh mvn clean install -U
…
13616 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.3.0:enforce (enforce-maven) on project openapi-generator-project:
13616 [ERROR] Rule 0: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
13616 [ERROR] Detected JDK version 1.8.0-342 (JAVA_HOME=/usr/local/openjdk-8/jre) is not in the allowed range [1.11.0,).
```
After this fix, the compile continues to completion.
=> Fix run-in-docker.sh for OpenAPI Generator 7+ by using JDK 11+

modules/openapi-generator/src/main/java/org/openapitools/codegen/CliOption.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
Clean up the clioption configuration of `KotlinServerCodegen` to use methods from `DefaultCodegen`. Also added a new variant of `addOption` to `DefaultCodegen` to support enum values.
```
``` 
```
```  …
=> [kotlin-server] cleanup KotlinServerCodegen configuration

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/issue_13052.yaml
_Edit on 05/25/2023: filled PR template_
Spring Pageable is imported whenever we have an API with a Pageable Json schema, even if x-spring-paginated is not set.
This was breaking existing open Api which where using a Pageable (non-Spring)  component.
This commit imports Spring Pageable only if x-spring-paginated is set to true.
To achieve that, I need to wait until operation processing (fromOperation method) to alter the importMapping setting.
This fixes https://github.com/OpenAPITools/openapi-generator/issues/13052
```
```  …
=> spring: fix spring pageable used without any config

modules/openapi-generator/src/main/resources/python/api.mustache, samples/client/echo_api/python/openapi_client/api/query_api.py
To fix https://github.com/OpenAPITools/openapi-generator/issues/15554
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus …
=> [python] Fix date isinstance check in query parameter

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/api.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/UserApi.cs
Created a partial method that enables developers to format arguments before sending to the server. This was achievable before using inheritance, but that feels a bit awkward to use in this  context. Partial methods are better suited for this task.
```
```  …
=> [csharp-netcore][generichost] Created partial method to format arguments

bin/configs/spring-http-interface-reactive.yaml, bin/configs/spring-http-interface.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
fix https://github.com/OpenAPITools/openapi-generator/issues/15631
Bean validation is disabled, documentation provider & annotation provides are also disabled. All there features don't make any sense for client library
```
``` 
``` …
```
=> [Spring] Defaulting for Spring HTTP Interface library

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
This is a fix for #15577.
The three affected methods now return a sane default value in case `items` is `null`. These methods normally don't have to handle `null` because they are only called when an actual item is present.
But the serialization logic doesn't care for that.
```
```  …
=> [BUG][typescript-fetch] fix npe when debuggingModels (#15577)

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache, samples/client/petstore/typescript-fetch/builds/allOf-nullable/runtime.ts, samples/client/petstore/typescript-fetch/builds/allOf-readonly/runtime.ts, samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts, samples/client/petstore/typescript-fetch/builds/default/runtime.ts, samples/client/petstore/typescript-fetch/builds/enum/runtime.ts, samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts, samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts, samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
Fix for #13456: JSON serialization is used as a default. I changed to have `toString()` as a default and JSON only in case of requested by mime-type.
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka: Please review 😃 .
```
```  …
=> Do JSON serialization only if requested by mime-type (#13456)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
Fix property name comparison in C#
```
``` 
```
``` 
=> Fix property name comparison in C#

modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt, modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
to fix #15729
```
``` 
```
``` 
=> Add support for dry-run flag to Maven and Gradle plugins

bin/configs/go-echo-server-petstore-new.yaml, modules/openapi-generator/src/main/resources/go-echo-server/api.mustache, modules/openapi-generator/src/main/resources/go-echo-server/go-mod.mustache, modules/openapi-generator/src/main/resources/go-echo-server/main.mustache, samples/server/petstore/go-echo-server/go.mod, samples/server/petstore/go-echo-server/handlers/api_pet.go, samples/server/petstore/go-echo-server/handlers/api_store.go, samples/server/petstore/go-echo-server/handlers/api_user.go, samples/server/petstore/go-echo-server/main.go
Hi!
As discussed in #15636, this PR changes the template files of go-echo-server in order to respect the `--git-host` argument. The changes have been tested by running the `./bin/generate-samples.sh ./bin/configs/go-echo-server-petstore-new.yaml` and by hand using the generated `openapi-generator-cli.jar`.
```
```  …
=> [Go] Update go-echo-server generator to respect the --git-host argument

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/JsonConverter.mustache
Name cannot be used here because enumVars also has a name property. datatypeWithEnum was used a workaround, but that does not work if the class contains mulitple properties of that type. So use nameInCamelCase instead.
```
``` 
``` …
```
=> [csharp-netcore][generichose] Use correct name for enum while serializing

modules/openapi-generator/src/main/resources/xojo-client/api.mustache
Follow-up of the other "fix use of isBasic" PR series, but for code from new Xojo generator developed in parallel
```
``` 
For …
=> [xojo] fix use of isBasic from #15194

modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-cloud/clientConfiguration.mustache
Follow-up of the other "fix use of isBasic" PR series, but for code from new kotlin-spring generator developed in parallel
```
```  …
=> [Kotlin-Spring] fix use of isBasic from #15048

modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/pojo.mustache, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/Category.java, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/ModelApiResponse.java, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/Order.java, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/Pet.java, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/Tag.java, samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/User.java, samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/Category.java, samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/ModelApiResponse.java, samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/Order.java, samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/Pet.java, samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/Tag.java, samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/User.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/Category.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/ModelApiResponse.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/Order.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/Pet.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/Tag.java, samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/User.java
closes #1698
This PR is based on @tnmtechnologies' work in #2039. On top of their changes I made some whitespace changes, to address the remaining comments in #2039.
```
``` 
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog …
=> [Java][Jaxrs][Resteasy] add @Valid to getter methods, updated

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/resources/Java/jackson_annotations.mustache, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/AdditionalPropertiesClass.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/ArrayOfArrayOfNumberOnly.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/ArrayOfNumberOnly.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/ArrayTest.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/EnumArrays.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/FileSchemaTestClass.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/MapTest.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/MixedPropertiesAndAdditionalPropertiesClass.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/Pet.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/TypeHolderDefault.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/TypeHolderExample.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/XmlItem.java, samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Pet.java
This PR is based on @jzrebiec's commits in #5371. I mainly rebased those to the current master.
The changes can be tested e.g. with [this input file](https://gist.github.com/martin-mfg/7f427836adb64bea947cea0cc3629aad), and the [java-resttemplate-withXml.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/configs/java-resttemplate-withXml.yaml) config.
```
```  …
=> always use @JacksonXmlElementWrapper and read xml data from referenced schema, updated

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt, modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskConfigurationCacheTest.kt
- Use `FileSystemOperations` to delete output folder if Gradle Version >= 6
- Add `GenerateTaskConfigurationCacheTest` test class
Fixes https://github.com/OpenAPITools/openapi-generator/issues/15692
Please note that the [FileSystemOperations](https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileSystemOperations.html) has been introduced with Gradle 6.0 and this is the reason why we need to condition its usage.
```
```  …
=> Allow configuration cache compatibility

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
Fixes #15541
Default Value: Backslash value needs an escaped backslash in generated python code.
Single quotes needs escapng on multilines as well (at least if there were three in a row)
Added a small unit test.
- [~] In case you are adding a new generator, run the following additional script : 
@spacether @krjakbrjak
=> [Python] default values escaping more appropriate

modules/openapi-generator/src/main/resources/python/exceptions.mustache, modules/openapi-generator/src/main/resources/python/rest.mustache, samples/client/echo_api/python/openapi_client/exceptions.py, samples/client/echo_api/python/openapi_client/rest.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/exceptions.py, samples/openapi3/client/petstore/python/petstore_api/exceptions.py, samples/openapi3/client/petstore/python/petstore_api/rest.py
Added BadRequestException as a subclass in python exceptions in order to validate the exceptions precisely
@spacether  @krjakbrjak 
```
``` 
```
``` 
=> [Python] Added BadRequestException as a subclass in python exceptions

modules/openapi-generator/src/main/resources/go/model_simple.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java, samples/client/petstore/go/go-petstore/model_has_only_read_only.go, samples/client/petstore/go/go-petstore/model_name.go, samples/client/petstore/go/go-petstore/model_read_only_first.go, samples/openapi3/client/petstore/go/go-petstore/model_has_only_read_only.go, samples/openapi3/client/petstore/go/go-petstore/model_name.go, samples/openapi3/client/petstore/go/go-petstore/model_read_only_first.go, samples/openapi3/client/petstore/go/go-petstore/model_read_only_with_default.go, samples/openapi3/client/petstore/go/model_test.go
PR #14335 has mistakenly removed the readOnly fields during the JSON serialization, resulting in models with missing fields.
This PR reverts those changes.
```
``` 
```
``` 
=> [Go] Serialize readonly fields

modules/openapi-generator/src/main/resources/postman-collection/postman.mustache
Follow-up of the other "fix use of isBasic" PR series, but for code from new postman generator developed in parallel
```
``` 
For …
=> [Postman] fix use of isBasic from #15294

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java, modules/openapi-generator/src/main/resources/python/pyproject.mustache, modules/openapi-generator/src/main/resources/python/setup.mustache, samples/client/echo_api/python/.openapi-generator/FILES, samples/client/echo_api/python/pyproject.toml, samples/client/echo_api/python/setup.py, samples/openapi3/client/petstore/python-aiohttp/.openapi-generator/FILES, samples/openapi3/client/petstore/python-aiohttp/pyproject.toml, samples/openapi3/client/petstore/python-aiohttp/setup.py, samples/openapi3/client/petstore/python/.openapi-generator/FILES, samples/openapi3/client/petstore/python/pyproject.toml, samples/openapi3/client/petstore/python/setup.py
Add py.typed
To close https://github.com/OpenAPITools/openapi-generator/issues/15097
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco …
=> [python] Add py.typed

modules/openapi-generator/src/main/resources/python/requirements.mustache, modules/openapi-generator/src/main/resources/python/setup.mustache, samples/client/echo_api/python/requirements.txt, samples/client/echo_api/python/setup.py, samples/openapi3/client/petstore/python-aiohttp/requirements.txt, samples/openapi3/client/petstore/python-aiohttp/setup.py, samples/openapi3/client/petstore/python/requirements.txt, samples/openapi3/client/petstore/python/setup.py
Install urllib3 < 2.1.0, which contains breaking changes
https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) …
=> [python] install urllib3 < 2.1.0 only

README.md
Add Revved Up by Gradle Enterprise badge with a link to https://ge.openapi-generator.tech/scans
See rendering in the original branch:
https://github.com/jprinet/openapi-generator/tree/chore/add-revved-up-badge
=> Add Revved up by Gradle Enterprise badge

.github/dependabot.yml, pom.xml
This PR configures Dependabot to monitor Gradle extensions.
Please note that I had to fix a couple of Maven module paths which were wrong and failed the Dependabot update.
=> Enable Dependabot on Maven extensions

modules/openapi-generator/src/main/resources/dart/libraries/dio/analysis_options.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/api/imports.mustache
The dart-dio generator had a couple of hard-coded `/src/` paths which meant the resulting code didn't work if you used a the custom `sourceFolder` property as it was importing from a directory that didn't exist.
This change results in no differences in the generated code since the default source directory is already `src` (although a new line got added when I ran the scripts in the instructions so I've committed that) so should be non-breaking.
```
```  …
=> [dart-dio] Use sourceFolder property instead of src

modules/openapi-generator/src/main/resources/Java/libraries/webclient/build.gradle.mustache, samples/client/petstore/java/webclient-swagger2/build.gradle
Just fixes a misplaced insert for the swagger2 annotation library dependency.
```
``` 
=> FIX: Typo on swagger2 dependency

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache, modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/pom-sb3.mustache, modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/pom.mustache
This fixes https://github.com/OpenAPITools/openapi-generator/issues/15828
There was additional char before version number which cause dependency not found error
@cachescrubber @welshm @MelleD
=> [spring] Fix invalid swagger2 annotation library version in pom.xml

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/issue_constructor-required-values-with-multiple-inheritance.yaml
PR fixes Issue https://github.com/OpenAPITools/openapi-generator/issues/15825
```
``` 
```
``` 
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) …
=> [BUG] [Java-Spring] Required-Fields-Constructor has wrong super call when using multiple inheritance layers

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/java-codegen-empty-array-as-default-value/baseType.yaml, modules/openapi-generator/src/test/resources/bugs/java-codegen-empty-array-as-default-value/defaultValuesType.yaml, modules/openapi-generator/src/test/resources/bugs/java-codegen-empty-array-as-default-value/issue_wrong-default.yaml, modules/openapi-generator/src/test/resources/bugs/java-codegen-empty-array-as-default-value/objectType.yaml
PR fixes Issue https://github.com/OpenAPITools/openapi-generator/issues/15835
```
``` 
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) …
=> [BUG][JAVA] Handling default values leads to wrong defaults or not compilable code fixed

modules/openapi-generator/src/main/resources/typescript/http/http.mustache
- x ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
```
``` 
``` …
```
=> [BUG][typescript] add missing importFileExtension support

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java, modules/openapi-generator/src/main/resources/dart/libraries/dio/api.mustache, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/pet_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/store_api.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api/user_api.dart
If the value of a parameter in the path is something that was camelized (enum values containing dashes for example), `toString()` will just return the string representation of the camelized value, not the original, which will fail validation on the server. Thus path parameters need to be properly serialized as well, this will map camelized values back to their original value as per OAS.
Attn: @jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela 
```
```  …
=> [dart-dio] Correctly serialize path parameters

modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache, samples/client/others/typescript/builds/with-unique-items/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/browser/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/default/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/deno/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/inversify/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/jquery/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/object_params/models/ObjectSerializer.ts
as `mediaTypes` is an array of strings and an required argument it will never be undefined when we can rely on the typesystem. However, it can be zero length(`[]`) and in this case we would throw.
* Closes #15011
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx  @macjohnny @topce  @akehir @petejohansonxo @amakhrov  @davidgamero  @mkusaka 
```
```  …
=> [Bug] fix: use length to check for default return media type

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue15859.json
To fix the following exception:
```
Exception in thread \"main\" java.lang.RuntimeException: Could not process model 'ResourceMonitor'.Please make sure that your schema is correct!
at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:535)
at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:956)
at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
at org.openapitools.codegen.DefaultCodegen.mergeProperties(DefaultCodegen.java:2828)
at org.openapitools.codegen.DefaultCodegen.updateModelForComposedSchema(DefaultCodegen. …
```
=> fix: NullPointerException in DefaultCodegen.mergeProperties when processing models

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellHttpClientCodegen.java, modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/pom.mustache, samples/server/petstore/jaxrs-spec-microprofile-openapi-annotations/pom.xml
I used [this simple OpenApi file](https://raw.githubusercontent.com/martin-mfg/openapi-generator/2cf82152edd2b31e8d525a4b8b953560f7e7fa38/modules/openapi-generator/src/test/resources/experiments.yaml) as input for all generators. This uncovered problems in several generators.  Some threw an Exception while processing the input, while others generated code that doesn't compile. Most generators couldn't handle the empty strings in this input.
I upgraded quarkus because with the old version, compilation failed with 
> [error]: Build step io.quarkus.resteasy.deployment.ResteasyServletProcessor#jaxrsConfig threw an exception: java.lang.IllegalArgumentException: Path must start with /
This is because there is no `servers` section in the input file, and thus no base path. The new version doesn't …
=> [Java][Haskell][Python] fix errors with empty strings, missing basePath

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Allow better default value in parameters using codegen property 
```
``` 
```
``` 
=> Allow better default value in parameters using codegen property

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/java/explode-query-parameter.yaml, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/UserApi.java
=> Fix issue #907 by ensuring the parameters is properly "exploded"

.github/workflows/samples-c-libcurl-client.yaml
This PR adds a GitHub Action to test c client sample build to address https://github.com/OpenAPITools/openapi-generator/pull/15782#issuecomment-1581832821
@wing328 @zhemant (2018/11) @ityuhui (2019/12) @michelealbano (2020/03)
```
``` 
``` …
```
=> [C][Client] Add GitHub Action to test c client sample build

.github/workflows/windows.yaml, modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/AuthorTemplate.java
fix https://github.com/OpenAPITools/openapi-generator/issues/9528
On Windows, some generators use `\` in the template directory path. But for the author cli command, this is not interpreted as file separator.
run `java -jar .\openapi-generator-cli.jar author template --verbose  -g jaxrs-spec --library quarkus` on Windows to verify.
```
```  …
=> author command: replace \ by /, fix #9528

.github/workflows/docker.yaml, modules/openapi-generator-online/Dockerfile
Update openapi-generator-online Dockerfile to use openjdk11 image
```
``` 
```
``` 
=> Update openapi-generator-online Dockerfile to use openjdk11 image

modules/openapi-generator/src/main/resources/dart2/api_helper.mustache, modules/openapi-generator/src/main/resources/dart2/apilib.mustache, modules/openapi-generator/src/main/resources/dart2/serialization/native/native_class.mustache, samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api_helper.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/model/order.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api_helper.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/fake_big_decimal_map200_response.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/format_test.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/mixed_properties_and_additional_properties_class.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/nullable_class.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/number_only.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/object_with_deprecated_fields.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/order.dart, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_composite.dart
During generation of a new code, I uncovered 2 bugs in the Dart template:
1. Deserializing a date-time field when `pattern: epoch` fails because the generated code outputs `/epoch/` instead of `epoch`, as it used to be before.
2. Having a non-nullable field of type `integer` without a default value produces code with syntax errors (assigning `null` to property).
This pr addresses both of these bugs.
```
```  …
=> Fix epoch deserialization and parsing numbers

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRustCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/rust/AbstractRustCodegenTest.java
Consider a model like the below:
```json
{
"type": "object",
"properties": {
"type": {
"type": "string",
"description": "An enum.",
"enum": [
"VARIANT",
"MORE_VARIANT"
]
},
}
```
Currently, the `type` property will be represented in Rust by the name `RHashType`, because the generator tries to sanitize the name first as a variable name (`type` → `r#type`) and then again as a type name (`r#type` → `RHashType`). This PR ensures that the sanitizing happens only once (`type` → `Type`).
This is a breaking change to the generator's output.
```
```  …
=> [Rust] Sanitize enum names correctly

modules/openapi-generator-online/Dockerfile
Use openjdk official docker image in openapi-generator-online as travis failed with adoptjdk in publishing docker images
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/15947/
```
docker build modules/openapi-generator-online/ -t test3
[+] Building 6.8s (9/9) FINISHED                                                                                                                                                                                                            
=> [internal] load build definition from Dockerfile                                                                                                                                                                                   0.1s
=> => transferring dockerfile: 539B …
```
=> Use openjdk official docker image in openapi-generator-online

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache, samples/client/petstore/typescript-axios/builds/test-petstore/api.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
Adds `isEnumRef` to the condition because it does not match the `isPrimitiveType` condition if the enum definition is separated
Fixes #9897
```
``` 
```
``` 
@TiFu (2017/07) @taxpon (2017/07) …
=> Fixed `typescript-axios` not setting enum ref correctly for `multipart/form-data`

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpFunctionsServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpReducedClientCodegen.java
The property getNullableTypes should no longer be used, but it was still being called by the abstract. Fixed this in a way that the derived classes can continue using the legacy getNullableTypes for now.
```
``` 
```
``` …
=> [csharp] Enabled overriding parameter patching

modules/openapi-generator/src/main/resources/php-symfony/Bundle.mustache, samples/server/petstore/php-symfony/SymfonyBundle-php/OpenAPIServerBundle.php
This fixes the issue described on #15959 ; it: it fixes the Symfony warning:
`User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "OpenAPI\Server\OpenAPIServerBundle" now to avoid errors or add an explicit @return annotation to suppress this message`
I tested this PR by setting up a Symfony app with the bundle autogenerated with this patch, and observing that the warning goes away, and that the queries made against the symfony app are correctly handled.
It's PHP, so here is a ping: @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ybelenko, @renepardon 
```
```  …
=> [PHP-Symfony] Fix Symfony warning on OpenAPIServerBundle

modules/openapi-generator/src/main/resources/php-symfony/README.mustache, samples/server/petstore/php-symfony/SymfonyBundle-php/README.md
This fixes the issue described in on #15961. Ie: with this PR, the generated README suggests to implement the `class DefaultApi` in a file named DefaultApi.php instead of DefaultApiInterface.php
(I've tested this PR by running the php-symfony generator on an arbitrary openapi file and checking the content of the generated README)
It's PHP, so here is a ping: @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ybelenko, @renepardon
```
```  …
=> [PHP-Symfony] fix name mismatch in generated README (#15961)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java, modules/openapi-generator/src/main/resources/postman-collection/item.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/postman-collection/SampleProject.yaml, samples/schema/postman-collection/postman.json
PR to keep the original name of the header (`baseName`) in the generated Postman collection
Fix #15904 
```
``` 
```
``` 
@gcatanese @wing328
=> [Postman Collections] Keep original header name

modules/openapi-generator/src/main/java/org/openapitools/codegen/DryRunTemplateManager.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DryRunTemplateManagerTest.java
Currently the dry-run status output only shows metadata files. This PR fixes that and also adds tests for the `DryRunTemplateManager` class.
Fixes #15730.
```
``` 
```
``` 
=> Fix dry-run output and add tests

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenDiscriminator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenEncoding.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenMediaType.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenServer.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenServerVariable.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Per the OAS spec, discriminators, encodings, media types, servers, and server variables are supposed to support vendor extensions. This PR adds that.
```
``` 
```
``` 
=> Support vendor extensions on more objects as per the OAS spec

modules/openapi-generator/src/main/resources/go/api.mustache, samples/client/petstore/go/go-petstore/api_fake.go, samples/openapi3/client/petstore/go/fake_api_test.go, samples/openapi3/client/petstore/go/go-petstore/api_fake.go
This is to fix the client generation problem related to #14798 where url value ends up being `reflect.Value+value` instead of their real value.
@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5
```
``` 
```
``` 
Commit …
=> [GO] Fix value formatting in url with slices

modules/openapi-generator/src/main/resources/asciidoc-documentation/index.mustache
The case sensitivity for the heading for the response codes was incorrect and has been corrected for the generation of Asciidoc.
```
``` 
```
``` 
=> Spelling fixes of a table caption for generated Asciidoc files

modules/openapi-generator/src/main/resources/JavaPlayFramework/newApiController.mustache, samples/server/petstore/java-play-framework-api-package-override/app/com/puppies/store/apis/PetApiController.java, samples/server/petstore/java-play-framework-async/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework-controller-only/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework-fake-endpoints/app/controllers/FakeApiController.java, samples/server/petstore/java-play-framework-fake-endpoints/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework-no-bean-validation/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework-no-exception-handling/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework-no-interface/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework-no-nullable/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework-no-swagger-ui/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework-no-wrap-calls/app/controllers/PetApiController.java, samples/server/petstore/java-play-framework/app/controllers/PetApiController.java
This PR aims ot fix the bug listed here : https://github.com/OpenAPITools/openapi-generator/issues/15982
- Use 'orElse' instead of 'get' to avoid Exception for non required headers
- Update samples
- [ X ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ X ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
``` 
Commit all …
=> Bugfix #15982 :  Use 'orElse' instead of 'get' toi avoir problem with optional header

modules/openapi-generator/src/main/resources/Javascript-Flowtyped/api.mustache
According to the Swagger Documentation, string/date should be a `full-date notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), for example, 2017-07-21`:
https://swagger.io/docs/specification/data-models/data-types/#string
Right now, the JavaScript-Flowtyped generator handles string/date like string/date-time. This fix removes the unnecessary parts of the isoString.
```
```  …
=> fixed date converter for javascript-flowtyped

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/UserApi.cs
Possible fix for the samples being wrong due to parameter sorting being inconsistent.
```
``` 
```
``` 
=> [csharp] Collect operation parameters to a list instead of set

modules/openapi-generator/src/main/resources/typescript/http/http.mustache, samples/client/others/typescript/builds/with-unique-items/http/http.ts, samples/openapi3/client/petstore/typescript/builds/browser/http/http.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/http/http.ts, samples/openapi3/client/petstore/typescript/builds/default/http/http.ts, samples/openapi3/client/petstore/typescript/builds/deno/http/http.ts, samples/openapi3/client/petstore/typescript/builds/inversify/http/http.ts, samples/openapi3/client/petstore/typescript/builds/jquery/http/http.ts, samples/openapi3/client/petstore/typescript/builds/object_params/http/http.ts, samples/openapi3/client/petstore/typescript/tests/browser/test/ServerConfiguration.test.ts, samples/openapi3/client/petstore/typescript/tests/browser/web-test-runner.config.js, samples/openapi3/client/petstore/typescript/tests/inversify/test/services.test.ts
In the previous PR #14319 the code was changed to use the standard `URL` constructor instead of url-parse. In principal I am always in favour of getting rid of extra dependencies. This constructor however does not allow relative URLs. So that use case was broken since 6.3.0.
This PR prefixes the URL with `window.location.origin`, when there is no protocol. I hope this is close enough to the original behaviour to work for everybody.
Test output without the change:
>  ❌ ServerConfiguration > supports relative URLs
>       TypeError: Failed to construct 'URL': Invalid URL
>         at new RequestContext (dist/ServerConfiguration.test.js:2176:18)
>         at ServerConfiguration.makeRequestContext (dist/ServerConfiguration.test.js:2477:14)
>         at dist/ServerConfiguration.test.js:2494:16 …
=> [typescript] Fix support for relative URLs

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/K6ClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
minor refactoring: remove openapi parameter from method as openapi is available to all methods in default codegen
```
``` 
```
``` 
=> [default codegen] remove openapi parameter from method

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java, modules/openapi-generator/src/main/resources/postman-collection/postman.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/postman-collection/SampleProject.yaml, samples/schema/postman-collection/postman.json
This PR changes the value set for  the generated Postman variables:
- before this PR: the `example` would be used to define the value of the variable
- after this PR: the `defaultValue` is used to define the value of the variable
When there is no default value set for a OpenAPI parameter then the corresponding Postman variable will be generated without setting the initial value.
```
```  …
=> [POSTMAN] Use parameter default value

modules/openapi-generator/src/main/resources/postman-collection/item.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, samples/schema/postman-collection/postman.json
This PR marks the Postman request header as disabled when it does not have a value.
The header is still created and included in the generated collection, but it will not be sent (by default) with the request.
```
``` 
```
``` …
=> [POSTMAN] Mark request header as disabled

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJuliaCodegen.java, modules/openapi-generator/src/main/resources/julia-client/partial_model_single.mustache, modules/openapi-generator/src/main/resources/julia-server/partial_model_single.mustache
Fixed issues in default value and enum generation for non-string types.
```
``` 
```
``` 
@wing328
=> [Julia] Fix error in default value and enum gen

modules/openapi-generator/src/main/resources/python/model_generic.mustache
=> [BUG][Python] Fix syntax error in from_dict call

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/resources/csharp/libraries/generichost/JsonConverter.mustache, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Model/PolymorphicProperty.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
The mustache change is just a little simpler, no change in logic. The change in abstract removes the warning.
```
``` 
```
``` 
=> [csharp] Removed a warning when deserializing json

modules/openapi-generator/src/main/resources/kotlin-spring/generatedAnnotation.mustache, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/SpringDocConfiguration.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApiController.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApiDelegate.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApiController.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApiDelegate.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApiController.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApiDelegate.kt, samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/SpringDocConfiguration.kt, samples/server/petstore/kotlin-springboot-springfox/src/main/kotlin/org/openapitools/SpringFoxConfiguration.kt
Generator: kotlin-spring
Library: spring-boot
Parameters Required to reproduce:
```
useSpringBoot3=false
```
Without this, it generates a jakarta annotation in the controllers of a spring boot 2 project which causes the generated code to fail compilation. 
Just uses the same parameter as the other annotation templating. Fixes things for me locally on a spring boot 2.7 project. 
@jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier 
```
```  …
=> [BUGFIX][kotlin-spring] Fix generatedAnnotation to use the javaxPackage variable instead of jakarta to fix spring boot 2 codegen

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java, modules/openapi-generator/src/main/resources/php/composer.mustache
This is my first PR. It's a WIP PR I think but it mainly to get some insights on it.
Fix #14645
```
``` 
```
``` 
=> PHP - Permit to customize more composer.json parts

modules/openapi-generator/src/main/resources/julia-server/model.mustache, modules/openapi-generator/src/main/resources/julia-server/partial_model_alias.mustache, modules/openapi-generator/src/main/resources/julia-server/partial_model_anyof.mustache, modules/openapi-generator/src/main/resources/julia-server/partial_model_oneof.mustache, modules/openapi-generator/src/main/resources/julia-server/partial_model_single.mustache, samples/server/petstore/julia/src/models/model_ApiResponse.jl, samples/server/petstore/julia/src/models/model_Category.jl, samples/server/petstore/julia/src/models/model_Order.jl, samples/server/petstore/julia/src/models/model_Pet.jl, samples/server/petstore/julia/src/models/model_Tag.jl, samples/server/petstore/julia/src/models/model_User.jl
Fixed issue in enum generation for julia-server code. An empty struct was generated, where it should have generated a type alias.
```
``` 
```
``` 
cc: @wing328
=> [Julia] Fix error in server enum generation

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/HttpSigningConfiguration.mustache, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
Used net60OrLater instead of hard coding the framework types. 
```
``` 
```
``` 
=> [csharp][generichost] Fixed bug in http signing config

modules/openapi-generator/src/main/resources/cpp-pistache-server/model-source.mustache, modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-source.mustache
In OpenAPI it is possible to define an enum schema containing integers only.
Similar to the following JSON snippet:
```
...
"components": {
"schemas": {
"size": {
"type": "integer",
"description": "Container size",
"enum": [
10000,
20000,
100000,
200000,
300000,
1000000,
1200000,
2500000,
5000000,
10000000
]
}
}
}
...
```
To correctly serialize this we need to convert to JSON integers. We can achieve this by feeding nlohmann JSON objects directly with integers instead of strings.
For the C++ pistache server adapt the enum models to serialize integer values if possible.
C++ committee:  @ravinikam, @stkrwork, @etherealjoy, @martindelille, @muttleyxd
```
``` 
This is important, as …
=> [C++][Pistache] Serialize integer enums if possible

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
The three attributes are not set correctly:
`public boolean isEnum; // true if the enum is defined inline`
`public boolean isInnerEnum; // Enums declared inline will be located inside the generic model, changing how the enum is referenced in some cases.`
`private boolean isEnumRef; // true if it's a reference to an enum`
I changed the code so that the return value from ModelUtils.getReferencedSchema is compared against its original parameter to see if a ref is actually resolved.
To close #15476
```
```  …
=> Fixed problem with non-ref-enums which were handled like ref-enums

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/docs/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/docs/apis/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/docs/apis/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/docs/apis/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient-httpclient/docs/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient-net47/docs/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient-net48/docs/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient-net5.0/docs/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient-unityWebRequest/docs/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient/docs/FakeApi.md, samples/client/petstore/csharp/OpenAPIClientCore/docs/FakeApi.md
- escape reserved words directly in `toParamName`
- remove code block to add `x-is-json` (not in used anywhere)
```
``` 
```
```  …
=> [C#] minor refactoring

modules/openapi-generator/src/main/resources/cpp-qt-client/helpers-body.mustache, modules/openapi-generator/src/main/resources/cpp-qt-client/model-body.mustache, modules/openapi-generator/src/main/resources/cpp-qt-client/model-header.mustache, modules/openapi-generator/src/main/resources/cpp-qt-client/object.mustache, samples/client/petstore/cpp-qt/CMakeLists.txt, samples/client/petstore/cpp-qt/client/PFXApiResponse.cpp, samples/client/petstore/cpp-qt/client/PFXApiResponse.h, samples/client/petstore/cpp-qt/client/PFXCategory.cpp, samples/client/petstore/cpp-qt/client/PFXCategory.h, samples/client/petstore/cpp-qt/client/PFXHelpers.cpp, samples/client/petstore/cpp-qt/client/PFXObject.h, samples/client/petstore/cpp-qt/client/PFXOrder.cpp, samples/client/petstore/cpp-qt/client/PFXOrder.h, samples/client/petstore/cpp-qt/client/PFXPet.cpp, samples/client/petstore/cpp-qt/client/PFXPet.h, samples/client/petstore/cpp-qt/client/PFXTag.cpp, samples/client/petstore/cpp-qt/client/PFXTag.h, samples/client/petstore/cpp-qt/client/PFXTestAnyType.cpp, samples/client/petstore/cpp-qt/client/PFXTestAnyType.h, samples/client/petstore/cpp-qt/client/PFXUser.cpp, samples/client/petstore/cpp-qt/client/PFXUser.h
I added CMake compile option to fail on all warnings. Let's see how the CI reacts.
EDIT: I realized that I was still using an older version of openapi-generator when writing this warning fix that I already did here: f40433d28fc0 
Although having the following in the test project:
```
add_compile_options(-Wall -Werror)
```
```
``` 
For …
=> [cpp-qt-client] Fix warning

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFServerCodegen.java
Code clean up for go server, jaxrs-cxf generators as model no longer have isMap set to true in default codegen
```
``` 
```
``` 
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) …
=> Code clean up for go server, jaxrs-cxf generators

modules/openapi-generator/src/main/resources/julia-client/api.mustache, modules/openapi-generator/src/main/resources/julia-server/api.mustache, samples/client/petstore/julia/src/apis/api_PetApi.jl, samples/server/petstore/julia/src/apis/api_PetApi.jl
- detect multipart and urlencoded post data formats correctly on the server side
- generate data types correctly for binary file uploads
- re-generated samples
```
``` 
```
``` 
cc: @wing328
=> [Julia] correct handling of POST data encodings

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache, modules/openapi-generator/src/main/resources/csharp/auth/OAuthAuthenticator.mustache, modules/openapi-generator/src/main/resources/csharp/netcore_project.mustache, modules/openapi-generator/src/main/resources/csharp/nuspec.mustache, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs, samples/client/petstore/csharp/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Org.OpenAPITools.csproj
Bumped RestSharp to the latest stable version (110.2.0), + changes in ApiClient.cs to fix a couple errors caused by breaking changes in RestSharp.
- `string` ContentType(s) to `RestSharp.ContentType` ContentType(s).
- `new RestClient([..]).UseSerializer()` moved into the `configureSerialization` delegate constructor parameter.
- Moved the `new RestResponse<T>` Request initializer into the constructor as a RestRequest is now required.
```
```  …
=> [csharp] Update RestSharp to 110.2.0

docs/generators/python.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
Add oneOf lookup option (doc) in python client generator
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) …
=> Add oneOf lookup option (doc) in python client generator

modules/openapi-generator/src/main/resources/typescript-axios/common.mustache, samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/common.ts, samples/client/petstore/typescript-axios/builds/composed-schemas/common.ts, samples/client/petstore/typescript-axios/builds/default/common.ts, samples/client/petstore/typescript-axios/builds/es6-target/common.ts, samples/client/petstore/typescript-axios/builds/test-petstore/common.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/common.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/common.ts, samples/client/petstore/typescript-axios/builds/with-interfaces/common.ts, samples/client/petstore/typescript-axios/builds/with-node-imports/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version/common.ts, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/common.ts, samples/client/petstore/typescript-axios/builds/with-string-enums/common.ts
Closes #11799 
This PR is a minor change affecting `typescript-axios`.
I tried to pass a custom axios instance but it wouldn't take into account its baseURL:
```typescript
import axios from "axios";
const customAxios = axios.create({
baseURL: "http://localhost:3000",
});
DefaultApiFactory(undefined, undefined, customAxios)
.authIsEmailAvailablePost(email)
.then((response: boolean) => {
console.log(response);
})
.catch((e) => {
console.error(e);
});
```
I checked in the generated code, the customAxios does have the baseURL and is properly loaded, but instead of `http://localhost:3000/auth/isEmailAvailable`, the URL called was `http://localhost/auth/isEmailAvailable`, because `BASE_PATH` is loaded, which is `http://localhost`, and `customAxios.baseURL` is never read whatsover: …
=> fix(typescript-axios): use baseURL of (custom) axios instance

modules/openapi-generator/src/main/resources/typescript-nestjs/README.mustache, modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache, modules/openapi-generator/src/main/resources/typescript-nestjs/configuration.mustache, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/README.md, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api.module.ts, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/configuration.ts, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/README.md, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api.module.ts, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/configuration.ts
Allow the configuration of the nestjs module with different providers via `forRootAsync`. This will RESOLVE #15269. 
```
``` 
```
``` 
=> [typescript-nestjs] allow configuration with forRootAsync (#15269)

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Translated words are not prefixed with quotation marks (`'`).
resolves #16161.
```
``` 
```
``` 
=> Fix DefaultCodegen.specialCharReplacements's comment to match the current behavior

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
Support `nameMapping` in abstract typescript codegen: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#name-mapping
Did a test by mapping `options` with `otherOptions` with a modified petstore spec using ts angular generator and the diff looks good:
```diff
--- a/samples/client/petstore/typescript-angular-v16-provided-in-root/builds/default/api/pet.service.ts
+++ b/samples/client/petstore/typescript-angular-v16-provided-in-root/builds/default/api/pet.service.ts
@@ -406,16 +406,20 @@ export class PetService {
* Find pet by ID
* Returns a single pet
* @param petId ID of pet to return
+     * @param otherOptions ID of pet to return
* @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the …
```
=> Support nameMapping in abstract typescript codegen

modules/openapi-generator/src/main/resources/php-symfony/Controller.mustache, samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/Controller.php
This fixes #15043
The issue is that browsers like "text/html,...,*/*;q=0.8" (see for instance https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values )
Without this commit we end up with an array of accepted type like `("text/html", "*/*;q=0.8)` so when we then check if the array contains `*/*` the check fails, and we return a 406 even though the client is able to get the response.
This commit fixes it by removing the `;q=0.8` part.
(Ideally we should not just discard that part, we should extract that
value, and order by it. See
https://developer.mozilla.org/en-US/docs/Glossary/Quality_values for
more info about that. However this could be done in a subsequent PR:
this already fixes the 406 error, which is pretty blocking)
To test this patch I: …
=> Fix parsing of Accept header like '*/*;q=0.8'

bin/configs/java-okhttp-gson.yaml, docs/customization.md, modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java, modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java, modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt, modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfiguratorUtils.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml, samples/client/petstore/java/okhttp-gson/README.md, samples/client/petstore/java/okhttp-gson/api/openapi.yaml, samples/client/petstore/java/okhttp-gson/docs/FakeApi.md, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java
- Add parameter name mappings option to allow users map parameter name to whatever they want. (parameter naming can be different than the property naming so that's why we need another option)
- Add tests
- update doc
- update abstract java codegen to use the new option.
```
```  …
=> Add parameter name mappings option

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache, modules/openapi-generator/src/test/resources/3_0/echo_api.yaml, samples/client/echo_api/java/apache-httpclient/README.md, samples/client/echo_api/java/apache-httpclient/api/openapi.yaml, samples/client/echo_api/java/apache-httpclient/docs/BodyApi.md, samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/api/BodyApi.java, samples/client/echo_api/java/feign-gson/api/openapi.yaml, samples/client/echo_api/java/feign-gson/src/main/java/org/openapitools/client/api/BodyApi.java, samples/client/echo_api/java/native/README.md, samples/client/echo_api/java/native/api/openapi.yaml, samples/client/echo_api/java/native/docs/BodyApi.md, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/BodyApi.java, samples/client/echo_api/java/native/src/test/java/org/openapitools/client/CustomTest.java, samples/client/echo_api/java/okhttp-gson/README.md, samples/client/echo_api/java/okhttp-gson/api/openapi.yaml, samples/client/echo_api/java/okhttp-gson/docs/BodyApi.md, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/api/BodyApi.java, samples/client/echo_api/python/README.md, samples/client/echo_api/python/docs/BodyApi.md, samples/client/echo_api/python/openapi_client/api/body_api.py
[Java][Native] Fix multipart builder when API accepts files array. Fix #16055 
```
``` 
```
``` 
=> [Java][Native] Fix multipart builder files array (#16055)

.circleci/config.yml, modules/openapi-generator/src/main/resources/ruby-client/partial_anyof_module.mustache, modules/openapi-generator/src/test/resources/3_0/ruby/petstore-with-fake-endpoints-models-for-testing.yaml, pom.xml, samples/client/petstore/ruby/lib/petstore/configuration.rb, samples/client/petstore/ruby/lib/petstore/models/mammal_anyof.rb, samples/client/petstore/ruby/spec/custom/configuration_spec.rb, samples/client/petstore/ruby/spec/custom/pet_spec.rb
- Add tests to operation servers in ruby client
- remove `valid?` (deprecated) from anyof model template
```
``` 
```
``` 
=> [ruby] Add tests to operation servers in ruby client

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
I spotted a mention of `github.com/antihax/optional` in AbstractGoCodegen. I was curious and investigated. However, it turns out that this code is an obsolete remnant of the go-deprecated generator removed before 6.0.0, so is now just a false lead. This PR cleans it up so no-one else has to go down the same investigative pathway.
To confirm this is sensible, observe that the removed code is setting a vendor extension `x-optional-data-type` but there is no mention of this anywhere in the templates.
```
``` 
_No changes to commit._
```
``` 
_Not applicable._
_There are no versioned branches right now._
Go technical committee: @antihax (2017/11) @grokify (2018/07) @kemokemo …
=> Purge obsolete Go codegen code re `github.com/antihax/optional`

modules/openapi-generator/src/main/resources/go/client.mustache, samples/client/petstore/go/go-petstore/client.go, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go, samples/openapi3/client/petstore/go/go-petstore/client.go
=> fix(golang): make sure xml.Encoder is closed

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellYesodServerCodegen.java, modules/openapi-generator/src/main/resources/haskell-servant/Types.mustache, modules/openapi-generator/src/main/resources/haskell-yesod/src/API/Types.mustache, samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/Types.hs, samples/server/petstore/haskell-yesod/src/OpenAPIPetstore/Types.hs
Special character replacements in the `haskell` and the `haskell-yesod` generators are not working correctly, and this PR fixes the issue and some related issues. 
The main problem is that those generators generate code that assumes the quotation mark prefixes, but the generated field names do not have the quotation mark prefixes. It seems that those generators try to use`fixOperatorChars` to perform special character replacements with quotation marks, but special characters have already been replaced in `DefaultCodegen.fromModel()` which does not insert quotation marks (c.f. #16161).
For example, the following spec resulted in the code that does not work properly.
```yaml
openapi: 3.0.0
info:
title: Test
description: Test API
version: 1.0.0
servers:
- url: https://api.example.com/ …
```
=> [haskell][haskell-yesod] Fix special char replacements

bin/configs/ada.yaml, bin/configs/unmaintained/ada.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java, modules/openapi-generator/src/test/resources/3_0/ada/petstore.yaml, samples/client/petstore/ada/src/client/samples-petstore-clients.adb, samples/client/petstore/ada/src/client/samples-petstore-clients.ads, samples/client/petstore/ada/src/model/samples-petstore-models.adb, samples/client/petstore/ada/src/model/samples-petstore-models.ads
- Add mapping option to Ada client/server codegen
- add tests (new 3.0 petstore spec for ada)
```
``` 
```
``` 
FYI @stcarrez (2018/02) @michelealbano (2018/02)
=> Add mapping option to Ada client/server codegen

modules/openapi-generator/src/main/resources/python/model_anyof.mustache, modules/openapi-generator/src/main/resources/python/model_oneof.mustache, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/any_of_color.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/any_of_pig.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/color.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/int_or_string.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/one_of_enum_string.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/pig.py, samples/openapi3/client/petstore/python/petstore_api/models/any_of_color.py, samples/openapi3/client/petstore/python/petstore_api/models/any_of_pig.py, samples/openapi3/client/petstore/python/petstore_api/models/color.py, samples/openapi3/client/petstore/python/petstore_api/models/int_or_string.py, samples/openapi3/client/petstore/python/petstore_api/models/one_of_enum_string.py, samples/openapi3/client/petstore/python/petstore_api/models/pig.py
```
``` 
```
``` 
This is a small update.
Add type hints.
=> [python-nextgen] Add type to actual instance

.circleci/config.yml, CI/circle_parallel.sh
=> Fix circleci node 4 failure

bin/configs/javascript-es6.yaml, docs/customization.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java, samples/client/petstore/javascript-es6/.openapi-generator/FILES, samples/client/petstore/javascript-es6/README.md, samples/client/petstore/javascript-es6/docs/FakeApi.md, samples/client/petstore/javascript-es6/docs/HealthCheckStatus.md, samples/client/petstore/javascript-es6/src/api/FakeApi.js, samples/client/petstore/javascript-es6/src/index.js, samples/client/petstore/javascript-es6/src/model/HealthCheckStatus.js, samples/client/petstore/javascript-es6/test/model/HealthCheckStatus.spec.js
Add name mappings (parameter, property, model) support to JS client
e.g.
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g javascript -i modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml  -o /tmp/javascript2/ --name-mappings _type=underscoreType,type_=typeWithUnderscore --parameter-name-mappings _type=paramType,type_=typeParam --model-mappings Tag=MyTag
```
```
```  …
=> Add name mappings support to JS client

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellYesodServerCodegen.java, modules/openapi-generator/src/main/resources/haskell-servant/Types.mustache, modules/openapi-generator/src/main/resources/haskell-yesod/src/API/Types.mustache, samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/Types.hs, samples/server/petstore/haskell-yesod/src/OpenAPIPetstore/Types.hs
I noticed that `haskell` (haskell-servant) and `haskell-yesod` generators cannot handle field names starting with upper case characters. For example, the following spec contains the `Message` field, and the generated   `ToJSON`/`FromJSON`  instances of `HelloResponse` do not work.
```yaml
openapi: 3.0.0
info:
title: Test
description: Test API
version: 1.0.0
servers:
- url: https://api.example.com/
description: the server
paths:
/hello:
get:
operationId: hello
summary: "summary"
description: "description."
responses:
"200":
description: foo
content:
schema:
$ref: '#/components/schemas/HelloResponse'
components:
schemas:
HelloResponse:
type: object
properties:
id:
type: string
description: id
Message:
type: string
description: text
required:
- id
- Message
description: …
```
=> [haskell-servant][haskell-yesod] Use table-based conversion for field name conversion 

modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache, samples/client/petstore/c/src/apiClient.c
libcurl API curl_easy_setopt requires the third parameter has to be passed with correct type depending on specific option.
For CURLOPT_POSTFIELDSIZE_LARGE option, it has to be type curl_off_t which is expected to be 64bit whether on 32bit or 64bit platform.
```
```  …
=> support 32bit in postdata

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinClientCodegenModelTest.java
based on https://github.com/OpenAPITools/openapi-generator/pull/9689 (resolved merge conflicts)
credits: @Tmeneau
To fallback, one can use name mapping options: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#name-mapping
cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)
```
```  …
=> [bug][kotlin] sanitize model names according to convention

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
```
``` 
```
``` 
Fix for incorrect links in Windows-generated markdown.
I have conducted my own tests on Windows and have confirmed that only markdown files are affected.
```
$ git diff --name-only …
```
=> [Dart/CSharp/Python] replace File.separator with slash

docs/generators/csharp.md, docs/generators/java.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
=> Add additional reserved words for java and csharp

modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache, samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/models/PetEnum.kt
When creating an enum where a valid value is `String`, the override of toString() will be the wrong type and compilation fails with:
```
Return type of 'toString' is not a subtype of the return type of the overridden member 'public open fun toString(): kotlin.String defined in kotlin.Enum'
```
Using `kotlin.String` instead of just `String` as the return value will allow using `String` as a value in an enum.
@jimschubert
```
```  …
=> Ensure enum classes toString() returns kotlin.String

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellYesodServerCodegen.java
`HaskellServantCodegen` and `HaskellYesodServerCodegen` modify `specialCharReplacements` by replacing its keys: backslash (`\`) with `\\` and `"` with `\"`.
It seems that those replacements were for using the keys in string literals in the `specialChars` table in the generated code. 
I.e. we want to have `("\\", "Back_Slash")` instead of `("\", "Back_Slash")` and `("\"", "Double_Quote")` instead of `(""", "Double_Quote")` in the table below.
https://github.com/OpenAPITools/openapi-generator/blob/81c398e5304f411eb57814349841827c13b2a54e/samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/Types.hs#L158-L196
However, modifying the keys causes the substitution of those characters in field names not to work, making generated code syntactically invalid. Suppose we have the following …
=> [haskell-servant][haskell-yesod] Fix specialCharReplacements

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pojo.mustache, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/model/DefaultValue.java, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/model/Query.java, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/model/TestQueryStyleFormExplodeTrueArrayStringQueryObjectParameter.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/model/ArrayOfArrayOfNumberOnly.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/model/ArrayOfNumberOnly.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/model/ArrayTest.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/model/EnumArrays.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/model/XmlItem.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/model/ArrayOfArrayOfNumberOnly.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/model/ArrayOfNumberOnly.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/model/ArrayTest.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/model/EnumArrays.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/model/XmlItem.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ArrayDefault.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ArrayOfArrayOfNumberOnly.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ArrayOfNumberOnly.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ArrayTest.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/EnumArrays.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/NullableClass.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ObjectWithDeprecatedFields.java
When the server responds with a ```null``` in JSON for an optional array, the GSON client refuses to accept it. Since the element is optional, it should simply continue.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/16212
```
```  …
=> Fix Java GSON client not accepting optional null arrays

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-webclient/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-jvm-spring-2-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Generated kotlin client with library set to `jvm-spring-webclient` does not return proper result for endpoints returning list of objects. Instead of list with properly mapped objects, the list of LinkedHashMaps is returned. This produces runtime errors since the classes don't match. Using ParameterizedTypeReference instead of class reference fixes the issue.
Fixes the reported issue: https://github.com/OpenAPITools/openapi-generator/issues/16292
Stack overflow thread that mentioned this issue: https://stackoverflow.com/questions/63685164/jackson-returning-linkedhashmap-from-api-generated-with-openapi-codegen
```
```  …
=> [Kotlin client][jvm-spring-webclient] Improve type reference declaration in ApiClient for request in order to fix invalid response of type List<T>. 

modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache, modules/openapi-generator/src/main/resources/htmlDocs2/sample_dart.mustache, samples/documentation/html2/index.html
Add dart code sample while generating documentation using `html2` generator 
For eg: `java  -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i ./samples/yaml/pet.yml -g html2` will now generate html file which includes dart code samples
=> Feature suppoert  dart  sample code in html2 generator

modules/openapi-generator/src/main/resources/typescript-rxjs/servers.mustache
add hasOwnProperty checking; use const instead of var
```
``` 
=> [typescript-rxjs] Update servers.mustache

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/cmake-lists.mustache, samples/client/petstore/cpp-restsdk/client/CMakeLists.txt
Hi,
This fixes the generated CMakeLists.txt when used with [cpprestsdk](https://github.com/microsoft/cpprestsdk) framework (see the details below).
---------
The generated CMakeFiles.txt contains the following issues (tested with the latest cpprestsdk version available: `2.10.18`):
1. The public dependency on CppRestSDK is not matching the one from the generated CMake config files on Unix, but is correct for Windows.
Name mismatch: `cpprest` instead of `cpprestsdk::cpprest`.
2. The library links against the whole Boost libraries (usage of `Boost_LIBRARIES`) whereas it only needs `boost/algorithm/*.hpp` and `boost/uuid/*.hpp` which are headers-only. Boost CMake finder provides different targets (see more details in https://cmake.org/cmake/help/latest/module/FindBoost.html). The one for the …
=> [cpp-restsdk] Update CMake to fix cpprest linking for UNIX and few enhancements

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/modelGeneric.mustache
Fixed class definition bug that occurs with validatable disabled, no inheritance, and none of the properties are readonly.
```
``` 
```
``` 
=> [csharp][generichost] Fixed class definition

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache, samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/PetApi.kt
https://github.com/OpenAPITools/openapi-generator/pull/13404
The above PullRequest now outputs normal code when an enum exists in the query parameter.
However, it was not supported by the kotlin-client multiplatform library.
With my PR, the kotlin-client multiplatform library now outputs correct code with query parameters with enums as well.
```
```  …
=> [kotlin-client][multiplatform] Added support enum query parameter

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache, samples/client/petstore/kotlin-default-values-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/DefaultApi.kt
=> [kotlin-multiplatform] Fixed build error when setting formdata in array

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSSpecServerCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/ping-array-default.yaml
Likely since 6.3.0 and introduction of default value for arrays in Java. https://github.com/OpenAPITools/openapi-generator/pull/14130 
In Java codegen a default value for the container type `array` will use `java.util.Arrays` to set the default value, however the required import is not added automatically. 
Issue reproduced at least with jaxrs-spec, jaxrs-jersey and spring generators.
https://github.com/OpenAPITools/openapi-generator/blob/dbb80de3cbd9b72da97d90be25c360f025f59567/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L1028-L1032
This PR contains:
- Test reproducing the issue.
- ⚠️ Possible fix by importing required class whenever array container type is found. With this approach the import could be superfluous when the array …
=> [Java] Array default value requires import of java.util.Arrays

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java, modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache, samples/client/others/kotlin-jvm-okhttp-parameter-tests/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-name-parameter-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Implements `application/octet-stream` with binary data in Kotlin client code generator.
OkHttp already supports binary input/output, so only adding content type and delegating to OkHttp is necessary here.
cc @jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier
```
```  …
=> [Kotlin Client] Implement octet-stream/binary

modules/openapi-generator/src/main/resources/go-gin-server/controller-api.mustache, modules/openapi-generator/src/main/resources/go-gin-server/main.mustache, modules/openapi-generator/src/main/resources/go-gin-server/routers.mustache, samples/server/petstore/go-gin-api-server/go/api_pet.go, samples/server/petstore/go-gin-api-server/go/api_store.go, samples/server/petstore/go-gin-api-server/go/api_user.go, samples/server/petstore/go-gin-api-server/go/routers.go, samples/server/petstore/go-gin-api-server/main.go
Before this change, the user would be required to make changes in the
generated code. This makes it really hard to update the API and the
documentation at the same time. With this change, the generated code can
be imported as is and used. The user just needs to set the handler
functions for each endpoint.
Endpoints which haven't had a handler function set will give a 501 (not yet implemented) error.
Testing this can be done with the following commands:
```
-i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
-g go-gin-server \
-o /tmp/gin
```
I'm still working on the documentation for it and making …
=> Update go-gin-server templates to return a configurable library

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp-restsharp-name-parameter-mappings/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ApiClient.cs
Remove memory leak with RestClient in ApiClient for **csharp-netcore**.
This fix issue #13961
@mandrean (2017/08) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)
```
``` 
```
``` 
Commit …
=> [BUG] [csharp-netcore] Resolve Memory leak in ApiClient

bin/configs/c.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java, modules/openapi-generator/src/test/resources/2_0/c/petstore.yaml, samples/client/petstore/c/.openapi-generator/FILES, samples/client/petstore/c/README.md, samples/client/petstore/c/docs/MappedModel.md, samples/client/petstore/c/model/mapped_model.c, samples/client/petstore/c/model/mapped_model.h, samples/client/petstore/c/unit-test/test_mapped_model.c
Add mapping features (property, parameter model names) to C client generator (we've added these features to many other generators)
Added a simple test
```
``` 
```
``` 
cc @zhemant (2018/11) @ityuhui …
=> Add mapping features to C client generator

.gitignore, modules/openapi-generator/src/main/resources/python-flask/__init__model.mustache, modules/openapi-generator/src/main/resources/python-flask/base_model.mustache, modules/openapi-generator/src/main/resources/python-flask/controller.mustache, modules/openapi-generator/src/main/resources/python-flask/controller_test.mustache, modules/openapi-generator/src/main/resources/python-flask/encoder.mustache, modules/openapi-generator/src/main/resources/python-flask/model.mustache, modules/openapi-generator/src/main/resources/python-flask/setup.mustache, modules/openapi-generator/src/main/resources/python-flask/typing_utils.mustache, modules/openapi-generator/src/main/resources/python-flask/util.mustache, samples/server/petstore/python-flask/openapi_server/controllers/pet_controller.py, samples/server/petstore/python-flask/openapi_server/controllers/store_controller.py, samples/server/petstore/python-flask/openapi_server/controllers/user_controller.py, samples/server/petstore/python-flask/openapi_server/encoder.py, samples/server/petstore/python-flask/openapi_server/models/__init__.py, samples/server/petstore/python-flask/openapi_server/models/api_response.py, samples/server/petstore/python-flask/openapi_server/models/base_model.py, samples/server/petstore/python-flask/openapi_server/models/category.py, samples/server/petstore/python-flask/openapi_server/models/order.py, samples/server/petstore/python-flask/openapi_server/models/pet.py, samples/server/petstore/python-flask/openapi_server/models/tag.py, samples/server/petstore/python-flask/openapi_server/models/user.py, samples/server/petstore/python-flask/openapi_server/test/test_pet_controller.py, samples/server/petstore/python-flask/openapi_server/test/test_store_controller.py, samples/server/petstore/python-flask/openapi_server/test/test_user_controller.py, samples/server/petstore/python-flask/openapi_server/typing_utils.py, samples/server/petstore/python-flask/openapi_server/util.py, samples/server/petstore/python-flask/setup.py
removing some residual python2 code, since it is not supported anymore, like:
- no need for `six` anymore
- no need for encoding utf8 in top file
- remove `object` inheritance in base model
- remove absolute import `__future__`
resolve #16377
```
``` 
``` …
```
=> [python-flask] adopt python3.5+ syntax

modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache, samples/server/petstore/kotlin-spring-default/src/main/kotlin/org/openapitools/api/PetApiController.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApi.kt, samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/PetApiController.kt, samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/PetApiController.kt, samples/server/petstore/kotlin-springboot-source-swagger2/src/main/kotlin/org/openapitools/api/PetApiController.kt
To fix https://github.com/OpenAPITools/openapi-generator/issues/16295
=> [Kotlin-Spring] fix arrays response api after generation

modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache, samples/client/others/typescript/builds/with-unique-items/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/browser/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/default/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/deno/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/inversify/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/jquery/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/object_params/models/ObjectSerializer.ts
https://github.com/kubernetes-client/javascript/issues/893
Adds additional `supportedMediaTypes` to the `ObjectSerializer.mustache` template. The 1.0.0 release of https://github.com/kubernetes-client/javascript is needs this change so that API calls to `patch` resources can succeed. Currently, they fail because the media types needed for patch operations are not listed in the template.
```
```  …
=> Add supportedMediaTypes needed for kubernetes client

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
Since it is looking at the payload before the transformation it should use the "original name" and not the "generated name" for the property when evaluating the discriminator.
```
``` 
```
``` 
=> Use propertyBaseName instead of propertyName for discriminator (typescript-fetch)

modules/openapi-generator/src/main/resources/python-flask/model.mustache, samples/server/petstore/python-flask/openapi_server/models/api_response.py, samples/server/petstore/python-flask/openapi_server/models/category.py, samples/server/petstore/python-flask/openapi_server/models/order.py, samples/server/petstore/python-flask/openapi_server/models/pet.py, samples/server/petstore/python-flask/openapi_server/models/tag.py, samples/server/petstore/python-flask/openapi_server/models/user.py
Adding types to python model generated using the python-flask generator
Linked issue: https://github.com/OpenAPITools/openapi-generator/issues/13806
The goal is to have types on the properties of the generated models to help python devs
```
``` 
``` …
```
=> Adding model type hints for Python Flask

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalatraServerCodegen.java
Using the **scalatra** generator on Windows crashes OpenAPI Generator with `java.lang.IllegalArgumentException: character to be escaped is missing`. This PR fixes that.
`File.separator` returns a single backslash on Windows, which is not a valid value for `replaceAll`.
To guard against similar problems, I could add a unit test that simply invokes each existing generator on a small input spec. Just to ensure the generator runs without crashes. This would then automatically be checked by the [windows workflow](https://github.com/OpenAPITools/openapi-generator/blob/master/.github/workflows/windows.yaml) (and others as well).
Let me know if that would be helpful.
@clasnake (2017/07), @jimschubert (2017/09) [❤️](https://www.patreon.com/jimschubert), @shijinkui (2018/01), @ramzimaalej …
=> Fix scalatra on Windows

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
Fix miscast types. At compile time, it says it can't find toISOString because the parameter is of type string, because <any> modifies the whole thing.
```
``` 
- Typescript: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) …
=> Incorrect type cast of date-time in NestJs generator prevented ts from compiling

modules/openapi-generator/src/main/resources/go/api.mustache, samples/client/petstore/go/go-petstore/api_fake.go, samples/openapi3/client/petstore/go/go-petstore/api_fake.go
Adding support for parameters default values in the Golang Generator.
All optional parameters with `default` value will have value assigned.
This solves inconsistency with the default value support in request body (already present)
Issue: #15126
```
```  …
=> issue15126: restore "default" value support for golang generator

modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
Sorry for the nits PR.
There is a 4 space indentation point and I wanted to fix the template as the generated code was pointed out to Rubocop.
https://github.com/rubocop/ruby-style-guide#spaces-indentation
```
``` 
```
``` …
=> [Ruby] align indentation

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java, modules/openapi-generator/src/main/resources/ruby-client/api.mustache, samples/client/petstore/ruby-autoload/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby-autoload/lib/petstore/api/pet_api.rb, samples/client/petstore/ruby-faraday/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby-faraday/lib/petstore/api/pet_api.rb, samples/client/petstore/ruby/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
Faraday replaces the underscore ("_") character with hyphen ("-") if a header param key is symbol:
https://github.com/lostisland/faraday/blob/v2.7.10/lib/faraday/utils/headers.rb#L44-L46
e.g. `user_uuid` => `User-Uuid`
I understand that the underscore ("_") character can be problematic (https://httpwg.org/specs/rfc9110.html#rfc.section.16.3.2.1) but still I think there are some cases we want to use the underscore ("_") character in header param keys.
```
``` 
You may regenerate an individual generator …
=> [ruby] Not symbolize header param keys to allow the usage of underscore ("_") character

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml, samples/openapi3/client/petstore/python-aiohttp/README.md, samples/openapi3/client/petstore/python-aiohttp/docs/FakeApi.md, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python/README.md, samples/openapi3/client/petstore/python/docs/FakeApi.md, samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
To fix https://github.com/OpenAPITools/openapi-generator/issues/16429
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus …
=> Fix uuid example cast exception in python generators

modules/openapi-generator/src/test/java/org/openapitools/codegen/AllGeneratorsTest.java
as discussed in https://github.com/OpenAPITools/openapi-generator/pull/16395#issuecomment-1692622328
Adding a unit test that simply invokes each existing generator on the petstore input spec. Just to ensure all generators run without crashes.
```
``` 
=> add test to invoke each generator and catch simple crashes

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellHttpClientCodegen.java
- Fix cast exception in uuid default value (haskell-http-client)
- tested locally to confirm the fix
```
``` 
```
``` 
=> Fix cast exception in uuid default value (haskell-http-client)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ObjcClientCodegen.java
- Fix cast exception in default value of UUID
- tested locally to confirm the fix
```
``` 
```
``` 
=> [ObjC] Fix cast exception in default value of UUID

samples/client/petstore/go/go.mod, samples/client/petstore/go/go.sum
There are 1 security vulnerabilities found in golang.org/x/net v0.2.0
- [CVE-2022-41723](https://www.oscs1024.com/hd/CVE-2022-41723)
Upgrade golang.org/x/net from v0.2.0 to 0.7.0 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade golang.org/x/net to 0.7.0

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java, modules/openapi-generator/src/test/resources/2_0/issue_8289.json
- Fix model name being a type in TS abstract codegen by using modelNameMappings option
- to fix https://github.com/OpenAPITools/openapi-generator/issues/9289
- tested locally to confirm the fix
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g typescript-fetch -i /tmp/a.json -o /tmp/ts2/ --model-name-mappings File=SystemFile
```
will add a test later
```
```  …
=> Fix model name being a type in TS abstract codegen

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractApexCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractFSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SwiftCombineClientCodegen.java
- Fix cast exception when handling example/default of UUID/Long type
- tested impacted generator to confirm all the fix
```
``` 
```
``` 
=> Fix cast exception when handling example/default of UUID/Long type

modules/openapi-generator/src/main/resources/python/api_client.mustache, samples/client/echo_api/python/openapi_client/api_client.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py, samples/openapi3/client/petstore/python/petstore_api/api_client.py
fix: python client generator didn't respect range response specificationin (e.g. "1XX", "2XX", etx.).  Return values tended to become None as a result
The python mustache template now, if an exact response code is not found first, looks up '<N>XX' as the presumed response code in the map of response definitions.
OpenAPI allows response codes to be specified as "1XX", "2XX", etc (c.f. https://swagger.io/specification/#responses-object), to avoid having to duplicate a lot of similarly handled responses.  The python generator did only lookup the exact response in the API definition and would return raw data or None (depending on the request method) since no definition was found.
The fix simply looks up for a range response if the exact response wasn't found.
Fixes: #14090
Attention: …
=> fix: python client generator didn't respect range response specification

modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/BackSlashLambda.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/ForwardSlashLambda.java, modules/openapi-generator/src/main/resources/php-slim4-server/README.mustache, modules/openapi-generator/src/main/resources/php-slim4-server/phpunit.xml.mustache, modules/openapi-generator/src/main/resources/php-symfony/testing/phpunit.xml.mustache, modules/openapi-generator/src/main/resources/php/phpunit.xml.mustache
Fix slash in php generator's doc & config
Without this fix, using the generator in Windows will generate
```diff
--- a/samples/client/petstore/php/OpenAPIClient-php/phpunit.xml.dist
+++ b/samples/client/petstore/php/OpenAPIClient-php/phpunit.xml.dist
@@ -2,8 +2,8 @@
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" bootstrap="./vendor/autoload.php" colors="true" convertErrorsToExceptions="true" convertNoticesToExceptions="true" convertWarningsToExceptions="tr
ue" stopOnFailure="false" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd">
<coverage processUncoveredFiles="true">
<include>
-      <directory suffix=".php">./lib/Api</directory>
-      <directory suffix=".php">./lib/Model</directory>
+      <directory suffix=".php">./lib\/Api</directory>
+ …
```
=> Fix slash in php generator's doc & config

modules/openapi-generator/src/main/resources/python-aiohttp/conftest.mustache, modules/openapi-generator/src/main/resources/python-aiohttp/setup.mustache, modules/openapi-generator/src/main/resources/python-aiohttp/tox.mustache, samples/server/petstore/python-aiohttp-srclayout/setup.py
Fix slash in python aiohttp files.
Before the fix when generating the samples on Windows,
```diff
$ git diff
diff --git a/samples/server/petstore/python-aiohttp-srclayout/setup.py b/samples/server/petstore/python-aiohttp-srclayout/setup.py
index 5cfff33cdbe..abc1aeb12a0 100644
--- a/samples/server/petstore/python-aiohttp-srclayout/setup.py
+++ b/samples/server/petstore/python-aiohttp-srclayout/setup.py
@@ -27,9 +27,9 @@ setup(
url="",
keywords=["OpenAPI", "OpenAPI Petstore"],
install_requires=REQUIRES,
-    packages=find_packages("src/"),
-    package_dir={"": "src/"},
-    package_data={'': ['src//openapi/openapi.yaml']},
+    packages=find_packages("src\"),
+    package_dir={"": "src\"},
+    package_data={'': ['src\/openapi/openapi.yaml']},
include_package_data=True,
entry_points={ …
```
=> Fix slash in python aiohttp files

docs/global-properties.md
As described in #8388, the separator was changed to colon, however the documentation still specifies comma separated string, which could lead to confusion.
=> Fix global property separator in docs

modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/IndentedLambda.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/mustache/IndentedLambdaTest.java
Fix indent lambda using \n as line break as that's what the templates use
```
``` 
```
``` 
=> Fix indent lambda using \n as line break

modules/openapi-generator/src/test/resources/3_0/echo_api.yaml, samples/client/echo_api/csharp-restsharp/README.md, samples/client/echo_api/csharp-restsharp/api/openapi.yaml, samples/client/echo_api/csharp-restsharp/docs/FormApi.md, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Api/FormApi.cs, samples/client/echo_api/java/apache-httpclient/README.md, samples/client/echo_api/java/apache-httpclient/api/openapi.yaml, samples/client/echo_api/java/apache-httpclient/docs/FormApi.md, samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/api/FormApi.java, samples/client/echo_api/java/feign-gson/api/openapi.yaml, samples/client/echo_api/java/feign-gson/src/main/java/org/openapitools/client/api/FormApi.java, samples/client/echo_api/java/native/README.md, samples/client/echo_api/java/native/api/openapi.yaml, samples/client/echo_api/java/native/docs/FormApi.md, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/FormApi.java, samples/client/echo_api/java/native/src/test/java/org/openapitools/client/CustomTest.java, samples/client/echo_api/java/okhttp-gson/README.md, samples/client/echo_api/java/okhttp-gson/api/openapi.yaml, samples/client/echo_api/java/okhttp-gson/docs/FormApi.md, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/api/FormApi.java, samples/client/echo_api/python/README.md, samples/client/echo_api/python/docs/FormApi.md, samples/client/echo_api/python/openapi_client/api/form_api.py
add tests for oneOf form parameters in Java native client
```
``` 
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) …
=> [java][native] Add tests for oneOf form parameters

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
Moving logic from C# to default codegen to ensure the enum entry name is unique in every generator.
https://github.com/OpenAPITools/openapi-generator/pull/16316#issuecomment-1701978976
```
``` 
```
```  …
=> Ensured enum entry name is unique

modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pojo.mustache, samples/client/petstore/java/microprofile-rest-client-3.0-jackson-with-xml/src/main/java/org/openapitools/client/model/Pet.java, samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Pet.java, samples/client/petstore/java/microprofile-rest-client-3.0/src/main/java/org/openapitools/client/model/Pet.java, samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/model/Pet.java
Apply what has be done for optional array property's default value for microprofile ( #14961 did it for java , native and jersey, but not for microprofile)
```
``` 
```
``` 
@bbdouglas (2017/07) …
=> [java] Microprofile - fix optional array property's default value

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/RubyClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue_1517.yaml
Ruby regexs are always generated as match patterns enclosed in slash characters (i.e. using the `/pattern/` syntax). Regular expressions defined in the OpenAPI declaration via the `pattern` attribute follow [ECMA 262](https://262.ecma-international.org/5.1/#sec-15.10.1) which means they already include the correct escaping of forward slashes as far as Ruby is concerned.
The current Ruby codegen is incorrectly escaping all forward slashes, which ultimately causes the generated code to include additional incorrect escape sequences which cause the generated file to have an invalid syntax.
This commit ports the same fix introduced in https://github.com/OpenAPITools/openapi-generator/pull/1539 for the Python codegen, as both Ruby and Python use perl-flavored regular expressions so they behave …
=> [Ruby] Fix incorrect escaping of Ruby forward slashes

modules/openapi-generator/src/main/resources/python/api_client.mustache, samples/client/echo_api/python/openapi_client/api_client.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py, samples/openapi3/client/petstore/python/petstore_api/api_client.py
Use of `isinstance` is preferred (and validated by common linters).
=> python: use isinstance instead of type()

modules/openapi-generator/src/main/resources/elixir/connection.ex.mustache, samples/client/petstore/elixir/lib/openapi_petstore/connection.ex
Correctly types the arguments for the Tesla.Middleware.Headers module on the token authorization. As you can see in [the example here](https://hexdocs.pm/tesla/Tesla.html#client/2) the Headers middleware options are a list of key-value pairs. 
This looks to be a regression introduced in https://github.com/OpenAPITools/openapi-generator/pull/12775 as a typo, as the stringdoc shows the correct structure.
Relevant issue https://github.com/ory/sdk/issues/285
```
```  …
=> Elixir: fix broken connection token authorization middleware

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/AWS4Auth.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache, samples/client/petstore/java/okhttp-gson-awsv4signature/pom.xml, samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/auth/AWS4Auth.java
Bug fix AWS4Auth to support query parameters and updated to use AWS SDK V2 from V1
To fix #16268 
The ./modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/AWS4Auth.mustache does not follow the AWS Sigv4 specification when it comes to Query parameters as per https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html. The causes all requests that have a query parameter to receive a 403 forbidden response.
I also updated the implementation to use the AWS SDK v2 instead of previous v1. 
```
```  …
=> Bug fix AWS4Auth to support query parameters and updated to use AWS SDK V2 from V1

modules/openapi-generator/src/main/resources/python/model_generic.mustache, samples/client/echo_api/python/openapi_client/models/default_value.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/class_model.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/file.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/health_check_result.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/model200_response.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/model_return.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/name.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/object_to_test_additional_properties.py, samples/openapi3/client/petstore/python/petstore_api/models/class_model.py, samples/openapi3/client/petstore/python/petstore_api/models/file.py, samples/openapi3/client/petstore/python/petstore_api/models/health_check_result.py, samples/openapi3/client/petstore/python/petstore_api/models/model200_response.py, samples/openapi3/client/petstore/python/petstore_api/models/model_return.py, samples/openapi3/client/petstore/python/petstore_api/models/name.py, samples/openapi3/client/petstore/python/petstore_api/models/object_to_test_additional_properties.py
Descriptions can easily exceed line-length limits because they are often extracted from doc/comments strings, which may use unexpected formatting.
Python doc strings, in particular, are likely to use newlines, which mustache does not preserve, causing descriptions to be condensed to a single line.
=> python: ignore long lines for model descriptions

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java, modules/openapi-generator/src/test/resources/2_0/nestedFormParameter.yaml
fix #12036, fix #14461, fix #14681, fix #10254, which all report the same problem. Possibly there are more such issues.
For `application/x-www-form-urlencoded` and `multipart/form-data` parameters, the model class of the form parameter is not needed and thus (correctly) not generated. But if the form parameter has any property with a non-primitive type, a model class for this property *is* needed and should be generated. But it is currently not generated.
The filtering of form model classes happens in `ModelUtils.getSchemasUsedOnlyInFormParam`. This method uses `visitOpenAPI` to iterate through all models. It then skips generation of all models for which the associated mime-type `t` is always `application/x-www-form-urlencoded` or `multipart/form-data`.
So to fix the described problem, I …
=> Fix selection of unnecessary form parameter models

modules/openapi-generator/src/main/resources/php/model_generic.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/Model/FormatTest.php, samples/client/petstore/php/psr-18/lib/Model/FormatTest.php
Properties like
```
lastModifiedDateTime:
pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?([Zz]|[+-][0-9][0-9]:[0-9][0-9])$'
type: string
description: Date and time the item was last modified. Read-only.
format: date-time
readOnly: true
```
generate this kind of code:
```
/**
* Sets last_modified_date_time
*
* @param \DateTime|null $last_modified_date_time Date and time the item was last modified. Read-only.
*
* @return self
*/
public function setLastModifiedDateTime($last_modified_date_time)
{
if (is_null($last_modified_date_time)) {
throw new \InvalidArgumentException('non-nullable last_modified_date_time cannot be null');
}
if ((!preg_match("/^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3] …
```
=> [PHP] convert data to string before giving it to preg_match

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/swift5/Swift5ClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue_15511.yaml
- Mark oneOf/anyOf form parameters as optional so that users can choose which properties from sub-schemas to include in the form parameters
- Add tests
Related issue: https://github.com/OpenAPITools/openapi-generator/issues/15511
```
```  …
=> Mark oneOf/anyOf form parameters as optional

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache, samples/client/petstore/java/resttemplate-jakarta/build.gradle, samples/client/petstore/java/resttemplate-jakarta/pom.xml, samples/client/petstore/java/resttemplate-swagger1/build.gradle, samples/client/petstore/java/resttemplate-swagger1/pom.xml, samples/client/petstore/java/resttemplate-swagger2/build.gradle, samples/client/petstore/java/resttemplate-swagger2/pom.xml, samples/client/petstore/java/resttemplate-withXml/build.gradle, samples/client/petstore/java/resttemplate-withXml/pom.xml, samples/client/petstore/java/resttemplate/build.gradle, samples/client/petstore/java/resttemplate/pom.xml
Update Java(resttemplate) dependencies to newer versions
```
``` 
```
``` 
FYI @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger …
=> Update Java(resttemplate) dependencies to newer versions

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
I was getting the following error
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'AvatarizationBatchParameters'.Please make sure that your schema is correct!
at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:529)
at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:950)
at org.openapitools.codegen.cmd.Generate.execute(Generate.java:511)
at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class io.swagger.v3.oas.models.media.Schema (java.lang.Boolean is in module java.base of loader 'bootstrap'; …
```
=> [typescript] fix: allow 'additionalProperties: true' at top level

modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache, samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiClient.java
This patch fixes two issues with the Resteasy generated client code. The first is the usage of a deprecated method, `getFormData`.  The fix for this issue was originally conceived by @peter-seitz.
The second issue was a problem in how the Content-Disposition header was being constructed.  If we had a file named `test.txt` and were uploading it to a field named `myFile`, the Content-Disposition header should look
like
```http
Content-Disposition: form-data; name="myFile"
```
Instead, the code was using the file's name (rather than the field name) in the name directive and the header looked like
```http
Content-Disposition: form-data; name="test.txt"
```
The Content-Disposition header can take an optional directive, filename, but I have not included that here as that directive is mostly …
=> [java-client][resteasy] fix multipart requests

docs/generators/kotlin-server.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerCodegen.java, modules/openapi-generator/src/main/resources/kotlin-server/libraries/jaxrs-spec/build.gradle.mustache, modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/build.gradle.mustache, samples/server/petstore/kotlin-server/ktor/build.gradle
The added option removes the wrapper part of build.gradle, enabling the generated project to be used as a sub project. The same option from kotlin client was used as reference for this change.
```
``` 
```
``` 
Commit all …
=> Add omitGradleWrapper option to kotlin-server code generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java, modules/openapi-generator/src/main/resources/php-nextgen/ObjectSerializer.mustache, modules/openapi-generator/src/main/resources/php-nextgen/model_enum.mustache, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/EnumClass.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/OuterEnum.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/OuterEnumDefaultValue.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/OuterEnumInteger.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/OuterEnumIntegerDefaultValue.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/SingleRefType.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ObjectSerializer.php
In the PHP generator, enums are implemented by creating a class that stores the enum values in static properties.
This results in weird type hints where these enums are used since the PHPDoc type specifies the class, but the actual values are the values of these properties.
PHP 8.1 adds backed enums which allow us to implement this correctly with less confusing type hints and better developer ergonomics.
Since backed enums need to declare the backing type, I introduced the vendor extension x-php-enum-type.
This follows the same principle as how a similar problem was solved [in the python generator](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java#L995).
```
./mvnw clean …
```
=> [php-nextgen] Use PHP 8.1 backed enums

modules/openapi-generator/src/main/resources/php-nextgen/ObjectSerializer.mustache, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ObjectSerializer.php
In #16556 I updated the ObjectSerializer to work with the new PHP enums. Unfortunately I got a little confused and performed an instanceof check on the class string.
This PR fixes this by using [`is_subclass_of`](https://www.php.net/manual/en/function.is-subclass-of.php)
```
```  …
=> [php-nextgen] Fix parent class check in ObjectSerializer

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
Better null check for schema types
(there's already a test in generate-samples)
```
``` 
```
``` 
=> [openapi-normalizer] Better null check for schema types

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/oauth2ClientProperties.mustache, samples/client/petstore/spring-cloud-feign-without-url/src/main/resources/oauth2-client.properties, samples/client/petstore/spring-cloud/src/main/resources/oauth2-client.properties, samples/openapi3/client/petstore/spring-cloud-3-with-optional/src/main/resources/oauth2-client.properties, samples/openapi3/client/petstore/spring-cloud-3/src/main/resources/oauth2-client.properties, samples/openapi3/client/petstore/spring-cloud-async/src/main/resources/oauth2-client.properties, samples/openapi3/client/petstore/spring-cloud-spring-pageable/src/main/resources/oauth2-client.properties
The scopes property is incorrect and is not read when starting.
This PR fixes the wrong property
```
``` 
```
``` 
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) …
=> Fix spring scope property

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
=> [maven-generator] Do not cleanup output if spec file is unchanged and skipIfSpecIsUnchanged=true (Fixes #16490)

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/resources/python/github-workflow.mustache, modules/openapi-generator/src/main/resources/python/gitlab-ci.mustache, modules/openapi-generator/src/main/resources/python/requirements.mustache, modules/openapi-generator/src/main/resources/python/test-requirements.mustache, samples/client/echo_api/python/.github/workflows/python.yml, samples/client/echo_api/python/.gitlab-ci.yml, samples/openapi3/client/petstore/python-aiohttp/.github/workflows/python.yml, samples/openapi3/client/petstore/python-aiohttp/.gitlab-ci.yml, samples/openapi3/client/petstore/python-aiohttp/requirements.txt, samples/openapi3/client/petstore/python-aiohttp/test-requirements.txt, samples/openapi3/client/petstore/python/.github/workflows/python.yml, samples/openapi3/client/petstore/python/.gitlab-ci.yml, samples/openapi3/client/petstore/python/requirements.txt, samples/openapi3/client/petstore/python/test-requirements.txt
-  Update github workflow, use debug instead of warning
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) …
=> [python] Update github workflow, use debug instead of warning

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
Fixed a bug in postProcessAllModels, changing an anyOf to a oneOf.
=> Fix oneOf processing in AbstractCSharpCodegen.java

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorValidateExtension.kt, modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/ValidateTask.kt, modules/openapi-generator-gradle-plugin/src/test/kotlin/ValidateTaskDslTest.kt, modules/openapi-generator-gradle-plugin/src/test/resources/specs/petstore-v3.0-recommend.yaml
close #6371 
Added test code to reproduce #6371 and fix it.
```
``` 
```
``` 
=> Fix ValidateTask failure if recommend is not assigned

modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache, samples/client/petstore/swift5/anycodableLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift, samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
…h @available on version 7.0.0
```
``` 
```
``` 
Fixing issue: [issue link](https://github.com/OpenAPITools/openapi-generator/issues/16479)
=> [swift] remove unavailable property to fix Xcode 15 compiler error

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
Better null check to avoid NPE in DefaultCodegen, DefaultGenerator, ModelUtils
```
``` 
```
``` 
=> Better null check to avoid NPE

docs/generators/groovy.md, docs/generators/java-camel.md, docs/generators/java-helidon-client.md, docs/generators/java-helidon-server.md, docs/generators/java-inflector.md, docs/generators/java-micronaut-client.md, docs/generators/java-micronaut-server.md, docs/generators/java-msf4j.md, docs/generators/java-pkmst.md, docs/generators/java-play-framework.md, docs/generators/java-undertow-server.md, docs/generators/java-vertx-web.md, docs/generators/java-vertx.md, docs/generators/java.md, docs/generators/jaxrs-cxf-cdi.md, docs/generators/jaxrs-cxf-client.md, docs/generators/jaxrs-cxf-extended.md, docs/generators/jaxrs-cxf.md, docs/generators/jaxrs-jersey.md, docs/generators/jaxrs-resteasy-eap.md, docs/generators/jaxrs-resteasy.md, docs/generators/jaxrs-spec.md, docs/generators/spring.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/java/autoset_constant.yaml
Partial implementation of #16547
Created a new property ``autosetConstants`` and added implementation for Java (OkHttp) client.
If ``autosetConstants``  is set to True, the generated code will hardcode values for any Header / Query / Cookie Param which is marked as required and can only have a single valid enum value.
The constant params will be removed from the method signature of the API.
A testcase has also been added to validate Header value is hardcoded if above is true.
I've run ``./bin/generate-samples.sh`` and there is no change in existing code generation if the new ``autosetConstants`` property is not set, Therefore there should not be any risk in getting this change merged.
=> Autoset constants (Required fields having single valid enum value) Java (OkHttp) Implementation of #16547

.github/workflows/samples-java-server-jdk8.yaml, bin/configs/java-undertow-server.yaml, modules/openapi-generator/src/main/resources/java-undertow-server/pom.mustache, pom.xml, samples/server/petstore/java-undertow/dependency-reduced-pom.xml, samples/server/petstore/java-undertow/pom.xml, samples/server/petstore/java-undertow/src/main/java/org/openapitools/handler/PathHandlerInterface.java, samples/server/petstore/java-undertow/src/main/resources/config/openapi.json
Update java undertow to newer version
To close https://github.com/OpenAPITools/openapi-generator/pull/16598
```
``` 
```
``` 
=> Update java undertow to newer version

modules/openapi-generator/src/main/resources/python/api.mustache, modules/openapi-generator/src/main/resources/python/api_client.mustache, samples/client/echo_api/python/openapi_client/api_client.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_classname_tags123_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/user_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py, samples/openapi3/client/petstore/python-aiohttp/tests/test_api_client.py, samples/openapi3/client/petstore/python-aiohttp/tests/util.py, samples/openapi3/client/petstore/python/petstore_api/api_client.py
This removes all the non-async code from the aiohttp generator:
* all the methods that should be asynchronous are marked as `async`
* the `async_req` parameter is gone; calls are directly awaitables now
* the async calls into a thread pool are gone and the thread pool is gone too (now useless)
Closes: #15824
Closes: #5539
Related: #763
Related: #3696
The code is extracted from https://github.com/OpenAPITools/openapi-generator/pull/15878, readjusted to remove the typing changes and fixed for the aiohttp client tests to pass.
@krjakbrjak @wing328 
```
``` 
These …
=> python: remove non-async code path from the aiohttp generator

docs/generators/kotlin-server.md, docs/generators/kotlin-spring.md, docs/generators/kotlin-vertx.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/jvm_volley/KotlinJvmVolleyModelCodegenTest.java
Remove `serializationLibrary` option from Kotlin server generators
```
``` 
FYI @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) …
=> Remove `serializationLibrary` option from Kotlin server generators

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, samples/schema/postman-collection/postman.json
Path parameters are often modified by developers using the collection (ie to test different scenarios), therefore creating those path parameters as Postman (global) variables does not make much sense.
This PR changes the default value of the configuration `pathParamsAsVariables` to skip (by default) the path parameters. Developers can still decide to enable this behavior setting the property to true.
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as an argument …
=> Change default value of 'pathParamsAsVariables' config option

.github/workflows/samples-python-nextgen-client-echo-api.yaml, .github/workflows/samples-python-petstore.yaml, samples/openapi3/client/petstore/python/tests/test_api_client.py, samples/openapi3/client/petstore/python/tests/test_pet_api.py
This runs more Python tests through GitHub Actions, with multiple code base and multiple Python versions.
I used this a lot to test my change in https://github.com/OpenAPITools/openapi-generator/pull/16624, which is difficult to fully assess if nothing exercises the generated Python code.
@krjakbrjak as Python tech-comittee
@wing328 as the previous editor on the `echo_client` sample + GitHub Action workflow
See: https://github.com/OpenAPITools/openapi-generator/pull/16643
```
```  …
=> python: run the Python samples tests with GitHub Actions

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java, modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache
Removes duplicate imports of okhttp3.ResponseBody.
Instead of adding the import for every operation, this sets a "global" variable _isResponseFile_ as already expected by api.mustache.
Adding the import for every operation (that has isResponseFile set to true) was introduced in #9239 and lead to non-compiling generated Apis as multiple imports are not allowed.
This fixes #9682.
@jimschubert can you review this?
```
```  …
=> fix(#9682): API class has multiple imports of 'okhttp3.ResponseBody'

.github/workflows/samples-python-nextgen-client-echo-api.yaml, .github/workflows/samples-python-petstore.yaml, samples/openapi3/client/petstore/python-aiohttp/tests/test_pet_api.py
Follow-up to https://github.com/OpenAPITools/openapi-generator/pull/16643, but with Python 3.11 enabled.
In Python 3.11, [`asyncio.wait()` can't be used on coroutines alone](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait):
@krjakbrjak as Python tech-comittee
@wing328 as the merger for the parent PR #16643
```
```  …
=> python: runs GitHub Actions with Python 3.11

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetServerCodegen.java
Following the changes in #15967, this fixes the DateTimeOffset option in the ASP.NET Core server stub template. Notably, the `setTypeMapping` method overload no longer does anything that the base method doesn't already set up. But the existing overload overrides and breaks the DateTimeOffset mapping, forcing it always to DateTime. I compiled locally and ran the generator, confirming that this indeed produces a DateTimeOffset in a generated server stub.
```
``` 
You may regenerate …
=> [BUG][aspnetcore] Fix ASP.NET Core server DateTimeOffset type mapping

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java, samples/client/petstore/php-nextgen/OpenAPIClient-php/docs/Api/FakeApi.md, samples/client/petstore/php-nextgen/OpenAPIClient-php/docs/Api/PetApi.md, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeApi.php
- Fix form parameter default value
- A follow-up PR to fix php-nextgen parameter default value (array): https://github.com/OpenAPITools/openapi-generator/pull/16572
A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/16572
```
```  …
=> [php-nextgen] Fix default value for array of items

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ApiClient.cs
Given a csharp client is generated for an API that is secured using OAuth2 
When the client is used to call any secured operation 
Then an exception occurs as follows;
```
Unhandled Exception: System.NotImplementedException: Set the RestClientOptions.Authenticator property instead
at RestSharp.RestClientExtensions.UseAuthenticator(RestClient client, IAuthenticator authenticator)
at MyProj.OAuthService.Client.ApiClient.Exec[T](RestRequest request, RequestOptions options, IReadableConfiguration configuration) in C:\Source\OAuthSolution\src\MyProj.OAuthService\Client\ApiClient.cs:line 466
at MyProj.OAuthService.Client.ApiClient.Get[T](String path, RequestOptions options, IReadableConfiguration configuration) in C:\Source\OAuthSolution\src\MyProj.OAuthService\Client\ApiClient.cs:line 773
at …
```
=> [csharp] Fix Issue #16660 System.NotImplementedException in ApiClient.cs with OAuth2

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache
Fix for the issue - https://github.com/OpenAPITools/openapi-generator/issues/16678#issuecomment-1737324656
Fixes wrong headers annotation for kotlin's retrofit2 api template.
```
``` 
=> fix: Fixes headers annotation for kotlin retrofit2 api template (16678)

modules/openapi-generator/src/main/resources/python/api.mustache, samples/client/echo_api/python/openapi_client/api/auth_api.py, samples/client/echo_api/python/openapi_client/api/body_api.py, samples/client/echo_api/python/openapi_client/api/form_api.py, samples/client/echo_api/python/openapi_client/api/header_api.py, samples/client/echo_api/python/openapi_client/api/path_api.py, samples/client/echo_api/python/openapi_client/api/query_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_classname_tags123_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/user_api.py, samples/openapi3/client/petstore/python/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_classname_tags123_api.py, samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
* In samples/openapi3/client/petstore/python, this reduces the mypy errors from 435 to 178 errors
* In samples/openapi3/client/petstore/python-aiohttp, this reduces the mypy errors from 381 to 124 errors
* In samples/client/echo_api/python, this reduces the mypy errors from 131 to 25 errors
@wing328
@krjakbrjak
@fa0311
```
```  …
=> python: type API client internal structures

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java, modules/openapi-generator/src/main/resources/php-symfony/model_generic.mustache, modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/ApiResponse.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Category.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Order.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Pet.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Tag.php, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/User.php
After PR https://github.com/OpenAPITools/openapi-generator/pull/12532 in php-symfony model does not exist default values from OpenApi specification. This commit add support for default scalar value of properties in php-symfony model. Default values now returns in getter-functions, and return type in getter function changed to not nullable/
=> [php-symfony] Support for default scalar value of properties in model

docs/generators/go.md, modules/openapi-generator/src/main/resources/go/api.mustache, modules/openapi-generator/src/main/resources/go/client.mustache, modules/openapi-generator/src/main/resources/go/configuration.mustache
Add optional response middleware to go template.
Adds a second request middleware which can return an error (did not modify the existing request middleware to avoid any breaking changes).
Fixes #16471 
```
``` 
=> [Go] Adding response middleware

modules/openapi-generator/src/main/resources/ruby-client/model_test.mustache
Update ruby rspec model test (comment out instance test)
To fix https://github.com/OpenAPITools/openapi-generator/issues/16629
```
``` 
=> Update Ruby rspec model test

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/apiInterface.mustache
{{>cookieParams}} was introduced to generated classes but not for the only interface use case in #8117
```
``` 
=> Added {{>cookieParams}} to interface

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
Use the existing toModelName method to normalize the discriminator
I stumbled upon the issue #16391 when I was trying to use an Enum as a discriminator which was added in #13846
```
``` 
=> fix: Add prefix and suffix to discriminator

modules/openapi-generator/src/main/resources/php-nextgen/ObjectSerializer.mustache, samples/client/echo_api/php-nextgen/src/ObjectSerializer.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ObjectSerializer.php
Generated PHP-Code is invalid because the function was named wrong.
```
``` 
=> fix invalid function is_subclass call for php-nextgen

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java, modules/openapi-generator/src/test/resources/2_0/c/petstore.yaml, samples/client/petstore/c/.openapi-generator/FILES, samples/client/petstore/c/README.md, samples/client/petstore/c/docs/model_with_set_propertes.md, samples/client/petstore/c/model/model_with_set_propertes.c, samples/client/petstore/c/model/model_with_set_propertes.h, samples/client/petstore/c/unit-test/test_model_with_set_propertes.c
map set to list so that the output compiles before someone has time to map `set` to a proper set data structure in C.
to close https://github.com/OpenAPITools/openapi-generator/issues/16611
```
``` 
@zhemant (2018/11) @ityuhui …
=> [C] map set to list, add tests

modules/openapi-generator/src/main/resources/php-nextgen/ObjectSerializer.mustache, samples/client/echo_api/php-nextgen/src/ObjectSerializer.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ObjectSerializer.php
I am unsure if the whole check could be removed because in the setter method of the model there is a phpdoc typehint which states that only an enum is allowed. But as long as there are no native type hints it could not be ensured that the value is always an enum. 
`$data` in this case should never be overwritten because it contains the OpenApi information. 
In my opinion serialization of the value should always be a scalar value because otherwise receiving clients must understand PHP enums serialization. 
Offtopic: there are some more issues with enums, i.e. in query parameters. But I will fix them with separate pull requests so they are clean and simple. 
```
```  …
=> [php-next-gen] fix handling with enums in object serializer

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java, modules/openapi-generator/src/main/resources/php-nextgen/ObjectSerializer.mustache, modules/openapi-generator/src/main/resources/php-nextgen/model_generic.mustache, samples/client/echo_api/php-nextgen/src/ObjectSerializer.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ObjectSerializer.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/test/AuthTest.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/test/NullableTest.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/test/PetApiTest.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/test/ServerVariablesInOperationTest.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/test/StoreApiTest.php
- fix type in object serializer, model setter and getter
- update tests
```
``` 
FYI @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)
=> [php-nextgen] Fix type, update tests

modules/openapi-generator/src/main/resources/ruby-client/api_client_httpx_partial.mustache, samples/client/echo_api/ruby-httpx/lib/openapi_client/api_client.rb, samples/client/petstore/ruby-httpx/lib/petstore/api_client.rb, samples/client/petstore/ruby-httpx/spec/custom/pet_spec.rb
=> Fix ruby httpx test

modules/openapi-generator/src/main/resources/zapier/model.mustache, modules/openapi-generator/src/main/resources/zapier/utils.mustache, samples/client/petstore/zapier/models/Pet.js, samples/client/petstore/zapier/utils/utils.js
=> [Zapier] Fixed zapier objects arrays mapping

modules/openapi-generator/src/main/resources/python/api.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api/auth_api.py, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api/body_api.py, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api/form_api.py, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api/header_api.py, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api/path_api.py, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api/query_api.py, samples/client/echo_api/python/openapi_client/api/auth_api.py, samples/client/echo_api/python/openapi_client/api/body_api.py, samples/client/echo_api/python/openapi_client/api/form_api.py, samples/client/echo_api/python/openapi_client/api/header_api.py, samples/client/echo_api/python/openapi_client/api/path_api.py, samples/client/echo_api/python/openapi_client/api/query_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_classname_tags123_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/user_api.py, samples/openapi3/client/petstore/python/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_classname_tags123_api.py, samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
[refactor: Use newlines in _with_http_info call](https://github.com/OpenAPITools/openapi-generator/commit/1e5f48eb3e55caa8af536ac17a7a983e6cf749a8)
[fix: Do not pydantic-validate function args twice](https://github.com/OpenAPITools/openapi-generator/commit/e312d4260c07e295748df14579c75f3fcd73628b)
Closes #15757
```
```  …
=> [python] Do not pydantic-validate function args twice

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
Currently the generation of `go-server` code for an array of files is broken. It generates the following:
```go
fileParam, err := ReadFormFilesToTempFiles(r, "file")	if err != nil {
c.errorHandler(w, r, &ParsingError{Err: err}, nil)
return
}
```
Which should be:
```go
fileParam, err := ReadFormFilesToTempFiles(r, "file")
if err != nil {
c.errorHandler(w, r, &ParsingError{Err: err}, nil)
return
}
```
```
```  …
=> Fix missing newline for file array in go-server/controller-api.mustache

modules/openapi-generator/src/main/resources/go-server/routers.mustache, samples/openapi3/server/petstore/go/go-petstore/go/routers.go, samples/server/petstore/go-api-server/go/routers.go, samples/server/petstore/go-chi-server/go/routers.go
Generated Go code , routers.go, imports io/ioutil package which has been deprecated, the same functionality is now provided by package io or package os.
Routers mustache template will now use io and os accordingly. Uses os.CreateTemp to create temp directory.  Uses io.Copy to avoid reading file into memory.
```
```  …
=> [Go-Server] Don't import io/ioutil package that has been deprecated as of Go 1.16

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, samples/schema/postman-collection/postman.json
Use Postman syntax when creating path parameters to make sure that `{{baseUrl}}/users/{id}` is converted to `{{baseUrl}}/users/:id`
Fix #16826 
```
``` 
@gcatanese @wing328
=> [Postman Collection] Fix path parameter syntax

modules/openapi-generator/src/main/resources/go/README.mustache, samples/client/echo_api/go/README.md, samples/client/petstore/go/go-petstore/README.md, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/README.md, samples/openapi3/client/petstore/go/go-petstore/README.md
A few years ago the examples in the README template for the Go client were [updated](https://github.com/OpenAPITools/openapi-generator/commit/93488f41959b00a7ceb011b05430208d7216e825#diff-8dbc27f20275ea67d48781556602ad1dd99a94c3edeb4919aa356efb78b178bcR32-R34) to use the `{{packageName}}` provided to the generator instead of using `sw` as the hard-coded package name. However, not every reference to `sw` was replaced which caused me a good deal of confusion when trying to understand how to use the generated client. This PR updates the references to `sw` that were missed previously.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of …
=> [BUG][GO] Replace references to sw package with {{packageName}} in README template

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/resources/python/api.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
Partial implementation of https://github.com/OpenAPITools/openapi-generator/issues/16547
If ``autosetConstants`` is set to True, the generated code by Python generator will hardcode values for any Header / Query Param which is marked as required and can only have a single valid enum value.
The single valued required enum i.e. The constant param will be removed from the method signature.
Also, Sight refactoring of the code pushed in https://github.com/OpenAPITools/openapi-generator/pull/16550
The Code to handle constants can be shared by all the generators.
A test case has been added that asserts that if ``autosetConstants`` is set to true then the constant key/value pair is being set in the generated code.
I've run ``./bin/generate-samples.sh`` and there is no change in existing code …
=> Autoset constants (Required fields having single valid enum value)

modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache, samples/client/others/java/webclient-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/webclient-jakarta/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/webclient-nullable-arrays/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/webclient-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
This will remove unused imports on apache commons-logging from the java webclient generator, which allows consumers a bit more freedom over logging libraries in their applications (e.g. in our organization we generally only allow _libraries_ to expose slf4j).  
```
```  …
=> chore: remove unused commons logging imports from java webclient

docs/generators/ruby.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java, modules/openapi-generator/src/main/resources/ruby-client/gemspec.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/options/RubyClientOptionsProvider.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/RubyClientOptionsTest.java, samples/client/echo_api/ruby-httpx/openapi_client.gemspec, samples/client/petstore/ruby-autoload/petstore.gemspec, samples/client/petstore/ruby-faraday/petstore.gemspec, samples/client/petstore/ruby-httpx/petstore.gemspec, samples/client/petstore/ruby/petstore.gemspec, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/x_auth_id_alias.gemspec, samples/openapi3/client/features/dynamic-servers/ruby/dynamic_servers.gemspec, samples/openapi3/client/features/generate-alias-as-model/ruby-client/petstore.gemspec
Currently there is no easy way to specify a gem's metadata. [Metadata](https://guides.rubygems.org/specification-reference/#metadata) is often used to reference related links for a given gem, but is otherwise a generic key/value dictionary that can be looked up by consumers of the gem. For example, can be used to specify if multi factor authentication is required when publishing on rubygems ([rails example](https://github.com/rails/rails/blob/main/rails.gemspec#L29)).
This pull request adds support for populating a gem's metadata by introducing an additional property (`gemMetadata`). This can be any arbitrary object, even though it should follow the rubygems [specs](https://guides.rubygems.org/specification-reference/#metadata).
I briefly considered using a list of entries instead where …
=> [Ruby] Add support for populating a gem metadata

.envrc
Right now, if a developer uses `direnv` but does not use `nix`, an error
is reported whenever changing into the OpenAPI generator directory:
```console
$ cd ~/oss/forks/openapi-generator
direnv: loading ~/oss/forks/openapi-generator/.envrc
direnv: using flake
environment:1270: nix: command not found
```
This uses the `has()` function to check for `nix` to *conditionally* run
the `use_flake` function.
=> Prevent direnv errors when not using nix

modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Order.php
Previously a DateTime properties was generated like that:
```php
/**
* @var \DateTime|null
* @SerializedName("shipDate")
* @Assert\DateTime()
* @Type("DateTime")
*/
protected ?\DateTime $shipDate = null;
```
But when in our server base code, if we want to valid our object with Symfony\Component\Validator\Validator\ValidatorInterface (see [Symfony doc](https://symfony.com/doc/current/validation.html)), we have this error : `This value should be of type `
When we read [this documentation](https://symfony.com/doc/current/reference/constraints/DateTime.html) we understand why : our parameter is a DateTime type, not a string like in their example.
So we need to change this assert `@Assert\DateTime()` by `@Assert\Type("\DateTime"))`
All of this is similar with Date type.
```
./mvnw clean …
```
=> [PHP-SYMFONY] Debug Date and DateTime Assert

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
To fix https://github.com/OpenAPITools/openapi-generator/issues/16907
```
``` 
=> fixed flaky test JavaClientCodegenTest#testMicroprofileRestClientIncorrectVersion

modules/openapi-generator/src/main/resources/rust-server/example-server-operation.mustache, samples/server/petstore/rust-server/output/multipart-v3/examples/server/server.rs, samples/server/petstore/rust-server/output/no-example-v3/examples/server/server.rs, samples/server/petstore/rust-server/output/openapi-v3/examples/client/server.rs, samples/server/petstore/rust-server/output/openapi-v3/examples/server/server.rs, samples/server/petstore/rust-server/output/ops-v3/examples/server/server.rs, samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/server/server.rs, samples/server/petstore/rust-server/output/ping-bearer-auth/examples/server/server.rs, samples/server/petstore/rust-server/output/rust-server-test/examples/server/server.rs
The generated example code would clone the context. However as context is a generic type and is not declared to implement Clone, a clone of a reference is just a copy of the reference and therefore unnecessary. This change removes the redundant call and therefore avoids the `cargo clippy` warning.
```
``` 
For …
=> fix(rust-server): remove redundant clone

modules/openapi-generator/src/main/resources/rust/Cargo.mustache, modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache, modules/openapi-generator/src/main/resources/rust/reqwest/configuration.mustache, samples/client/others/rust/reqwest-regression-16119/Cargo.toml, samples/client/others/rust/reqwest-regression-16119/src/apis/configuration.rs, samples/client/petstore/rust/reqwest/name-mapping/Cargo.toml, samples/client/petstore/rust/reqwest/name-mapping/src/apis/configuration.rs, samples/client/petstore/rust/reqwest/petstore-awsv4signature/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/apis/configuration.rs, samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/apis/pet_api.rs, samples/client/petstore/rust/reqwest/petstore/Cargo.toml, samples/client/petstore/rust/reqwest/petstore/src/apis/configuration.rs, samples/client/petstore/rust/reqwest/petstore/src/apis/pet_api.rs
Requires reqwest 0.11 even if code was generated in blocking mode.
close #15549
```
``` 
- cc @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10)
=> chore(deps,rust): requires reqwest 0.11 in blocking generated code

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp-restsharp-name-parameter-mappings/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ApiClient.cs
added missing line in config mapping, closes #14608 
```
```  …
=> [csharp] RemoteCertificateValidationCallback was not called on async methods; resolves #14608

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java, samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Pet.php
This commit fix type hinting of model array items in PHPDoc comments.
=> [php-symfony] Fix type hint for array in comments.

modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache, modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache, modules/openapi-generator/src/main/resources/ruby-client/api_client_httpx_partial.mustache, modules/openapi-generator/src/main/resources/ruby-client/api_client_typhoeus_partial.mustache, samples/client/echo_api/ruby-httpx/lib/openapi_client/api_client.rb, samples/client/petstore/ruby-autoload/lib/petstore/api_client.rb, samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb, samples/client/petstore/ruby-httpx/lib/petstore/api_client.rb, samples/client/petstore/ruby/lib/petstore/api_client.rb, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_client.rb, samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_client.rb, samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb
https://github.com/OpenAPITools/openapi-generator/issues/16796
This makes the ApiClient threadsafe in ruby. I definitely need help testing this and following the process.
```
``` 
=> [ruby] Make File Downloads Threadsafe

modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/IndentedLambda.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/mustache/IndentedLambdaTest.java, samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Capitalization.ts, samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/Capitalization.ts, samples/server/petstore/cpp-restbed/generated/3_0/api/AnotherFakeApi.cpp, samples/server/petstore/cpp-restbed/generated/3_0/api/DefaultApi.cpp, samples/server/petstore/cpp-restbed/generated/3_0/api/FakeApi.cpp, samples/server/petstore/cpp-restbed/generated/3_0/api/FakeClassnameTags123Api.cpp, samples/server/petstore/cpp-restbed/generated/3_0/api/PetApi.cpp, samples/server/petstore/cpp-restbed/generated/3_0/api/StoreApi.cpp, samples/server/petstore/cpp-restbed/generated/3_0/api/UserApi.cpp, samples/server/petstore/kotlin-server-modelMutable/src/main/kotlin/org/openapitools/server/apis/PetApi.kt, samples/server/petstore/kotlin-server-modelMutable/src/main/kotlin/org/openapitools/server/apis/StoreApi.kt, samples/server/petstore/kotlin-server-modelMutable/src/main/kotlin/org/openapitools/server/apis/UserApi.kt, samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/apis/PetApi.kt, samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/apis/StoreApi.kt, samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/apis/UserApi.kt
The split command will strip trailing line breaks, thus mutating the string, when all we really want the indent lambda to do is indent.
```
``` 
=> Fixed indent lambda to not strip line breaks

modules/openapi-generator/src/main/resources/php/api.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php, samples/client/petstore/php/OpenAPIClient-php/tests/AuthTest.php, samples/client/petstore/php/OpenAPIClient-php/tests/HeadersTest.php, samples/client/petstore/php/OpenAPIClient-php/tests/ResponseTypesTest.php
In the case the server returns a non JSON response  `json_decode` and respectively the whole function would return `null`. This is not desirable because the consumer of the library would have to check for exceptions AND for `null` as return value.
This PR changes the behavior, so that an `ApiException` is thrown if the data cannot be decoded.
~~P.S. there is an other `json_decode` further down the code, I haven't fixed that one, because I think that is anyway dead code and should be deleted~~
Should fix https://github.com/owncloud/libre-graph-api-php/issues/4
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as …
=> [PHP] check if json_decode was able to decode response

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/allof_primitive.yaml
To close https://github.com/OpenAPITools/openapi-generator/issues/16857
Better `isAlias` detection for allOf with a single item.
```
``` 
=> Better isAlias detection

modules/openapi-generator/src/main/resources/python-pydantic-v1/api_client.mustache, modules/openapi-generator/src/main/resources/python/api_client.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api_client.py, samples/client/echo_api/python-pydantic-v1/openapi_client/api_client.py, samples/client/echo_api/python-pydantic-v1/test/test_manual.py, samples/client/echo_api/python/openapi_client/api_client.py, samples/client/echo_api/python/test/test_manual.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py, samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/api_client.py, samples/openapi3/client/petstore/python-pydantic-v1/petstore_api/api_client.py, samples/openapi3/client/petstore/python-pydantic-v1/tests/test_api_client.py, samples/openapi3/client/petstore/python/petstore_api/api_client.py, samples/openapi3/client/petstore/python/tests/test_api_client.py
=> fix parameters_to_url_query returns booleans with upper letter

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonPydanticV1Codegen.java
The postponed model imports are wrong when the mapping name is not equal to the model name.
See [Issue](https://github.com/OpenAPITools/openapi-generator/issues/16848) for example schema and further description.
I changed the method used in the python pydantic generators to use the model name for the postponed imports instead of the mapping name of the discriminator mapping. 
```
```  …
=> [python] Fix postponed model imports

modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache
Required for some compilation modes of TS, specifically for use with SvelteKit.
The error I'm getting when using the generated code on SvelteKit is:
```
TS1444:  XXX  is a type and must be imported using a type-only import when  preserveValueImports  and  isolatedModules  are both enabled.
```
Those options are deliberate and mandatory according to SvelteKit's doc.
As such I've made a change to the way types are imported, which actually already seems to be present in `modelGeneric`. This change is conclusive on my end and makes the generated code work in my project.
Now, to be perfectly transparent, I am extremely not used to the tooling of this project and I have no idea if did everything right. Specifically, I think I managed to run some tests but it stays pretty elusive to me, so let …
=> Type import for oneOf models in ts-fetch template

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache, samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/default/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/es6-target/src/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/src/apis/PetApi.ts, samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/apis/PetApi.ts
PR https://github.com/OpenAPITools/openapi-generator/pull/11523 changed the typescript-fetch generator so that marking an API or property as deprecated would result in a @deprecated comment being added above the relevant generated API or property. However, this was only enabled for interfaces and only raw methods.
This PR adds @deprecated comments for all deprecated APIs and properties, in classes and interfaces. This is important so that developers can easily tell when they're using a deprecated API, and so that other tooling (linters, etc) can be used to forbid using deprecated APIs.
```
```  …
=> [typescript-fetch] Generate @deprecated comments for all deprecated APIs

docs/generators/go.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java, modules/openapi-generator/src/main/resources/go/model_simple.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientOptionsTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/options/GoClientOptionsProvider.java
I added generateMarshalJSON (boolean) as a setting for additional-properties.
By default, it is set to true. However, if explicitly set to false, it will not implement the MarshalJSON using ToMap.
This PR is related to #16948.
I kindly ask for your review.
```
```  …
=> [Go] add generateMarshalJSON key for additional-properties settings

modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java, modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/config/GlobalSettings.java
In the maven plugin, add logging of `GlobalSettings`.
This adresses the suggestion in https://github.com/OpenAPITools/openapi-generator/issues/4506 to have complete logging of all relevant inputs in the maven plugin.
```
``` 
=> maven plugin: log global settings

modules/openapi-generator/src/main/resources/python/model_anyof.mustache, modules/openapi-generator/src/main/resources/python/model_generic.mustache, modules/openapi-generator/src/main/resources/python/model_oneof.mustache, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/animal.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/circular_reference_model.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/dummy_model.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/first_ref.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/second_ref.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/self_reference_model.py, samples/openapi3/client/petstore/python/petstore_api/models/animal.py, samples/openapi3/client/petstore/python/petstore_api/models/circular_reference_model.py, samples/openapi3/client/petstore/python/petstore_api/models/dummy_model.py, samples/openapi3/client/petstore/python/petstore_api/models/first_ref.py, samples/openapi3/client/petstore/python/petstore_api/models/second_ref.py, samples/openapi3/client/petstore/python/petstore_api/models/self_reference_model.py, samples/openapi3/client/petstore/python/tests/test_model.py
```
``` 
---
Pydantic v2 has made significant changes to the specifications regarding the reconstruction of models required for circular references.
This requires the construction of a very complex referencing algorithm to resolve.
I …
=> [python] add circular reference import 

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonPydanticV1ClientCodegen.java
Fix pydantic v1 default template folder (python => python-pydantic-v1)
```
``` 
=> Fix pydantic v1 default template folder

modules/openapi-generator/src/main/resources/python/api_client.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api_client.py, samples/client/echo_api/python/openapi_client/api_client.py, samples/openapi3/client/petstore/python/petstore_api/api_client.py
Probably [this commit](https://github.com/fa0311/openapi-generator/commit/4d3d312aee20229aa3cbf7406ec722843d8d6f8a#diff-c1d7ea3a1de60effaa5908cee1be9a7e2fd420bdb75a2e2a28a6c3290380192dL106-L111) cleaned up a little too much so when I do [this](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/client/echo_api/python#getting-started):
```python
with openapi_client.ApiClient(configuration) as api_client:
api_instance = openapi_client.AuthApi(api_client)
```
I'm seeing this error: 
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: __enter__
```
Probably we don't need them anymore but I think it doesn't hurt to keep the `__enter__` and `__exit__` methods to get along with the sample code 🙂.
``` …
```
=> [python] Add back `__enter__` and `__exit__` methods for non asyncio

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, samples/schema/postman-collection/postman.json
The generated Postman collection presents the requests in a random order.
This PR fixes the generator to sort the requests by path to make sure Postman displays all requests for a given endpoint together.
Fixes #16982 
```
```  …
=> [POSTMAN] [BUG] Correct order of the Postman requests

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/anyof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey2/oneof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/anyof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/oneof_model.mustache
=> corrected gneration of java jersey code with oneof and anyof

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java, modules/openapi-generator/src/main/resources/go/model_simple.mustache, samples/client/echo_api/go/model_pet.go, samples/client/petstore/go/go-petstore/model_animal.go, samples/client/petstore/go/go-petstore/model_big_cat.go, samples/client/petstore/go/go-petstore/model_cat.go, samples/client/petstore/go/go-petstore/model_category.go, samples/client/petstore/go/go-petstore/model_dog.go, samples/client/petstore/go/go-petstore/model_enum_test_.go, samples/client/petstore/go/go-petstore/model_format_test_.go, samples/client/petstore/go/go-petstore/model_name.go, samples/client/petstore/go/go-petstore/model_pet.go, samples/client/petstore/go/go-petstore/model_type_holder_default.go, samples/client/petstore/go/go-petstore/model_type_holder_example.go, samples/openapi3/client/petstore/go/go-petstore/model_animal.go, samples/openapi3/client/petstore/go/go-petstore/model_apple_req.go, samples/openapi3/client/petstore/go/go-petstore/model_banana_req.go, samples/openapi3/client/petstore/go/go-petstore/model_cat.go, samples/openapi3/client/petstore/go/go-petstore/model_category.go, samples/openapi3/client/petstore/go/go-petstore/model_dog.go, samples/openapi3/client/petstore/go/go-petstore/model_duplicated_prop_parent.go, samples/openapi3/client/petstore/go/go-petstore/model_enum_test_.go, samples/openapi3/client/petstore/go/go-petstore/model_format_test_.go, samples/openapi3/client/petstore/go/go-petstore/model_name.go, samples/openapi3/client/petstore/go/go-petstore/model_pet.go, samples/openapi3/client/petstore/go/go-petstore/model_whale.go, samples/openapi3/client/petstore/go/go-petstore/model_zebra.go, samples/openapi3/client/petstore/go/model_test.go
Relates to #12201
Code generated by the Go client generator does not validate `required` fields, which is especially problematic in `oneOf` schemas where the sub-schemas are differentiated by required fields.
For example, consider the following schema:
```yaml
components:
schemas:
Thing:
oneOf:
- $ref: '#/components/schemas/ThingWithFoo'
- $ref: '#/components/schemas/ThingWithBar'
ThingWithFoo:
type: object
properties:
foo:
type: string
id:
type: string
required:
- foo
ThingWithBar:
type: object
properties:
bar:
type: string
id:
type: string
required:
- bar
```
Assume that the API itself only returns an object that has `foo` or an object that has `bar`; it will not return an object with both properties.  Existing versions of `openapi-generator` Go client generator will generate models …
=> [Go] validate required fields when unmarshalling JSON

modules/openapi-generator/src/main/resources/python/api_client.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/api_client.py, samples/client/echo_api/python/openapi_client/api_client.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py, samples/openapi3/client/petstore/python/petstore_api/api_client.py
If the schema defines a response type for error responses, the client does not raise exceptions since https://github.com/OpenAPITools/openapi-generator/pull/16802.
This PR raises exceptions on all status codes outside [200,299].
In a follow-up, it would be nice to deserialize error responses if a type is documented, and add the deserialized model class to the exception object.
```
``` 
You may …
=> [python][fix] Raise exceptions on non-2xx responses

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpModelEnumTest.java
This pull request introduces the `enumPropertyNaming` option to the C# generator. This option, which is currently supported by the Kotlin and TypeScript generators, allows you to control the naming style of enum names.
In our projects, we consistently use `UPPER_SNAKE_CASE` for constants in our OpenAPI definitions, and we prefer to maintain this naming style in our C# code. However, the current C# generator changes the enum names by removing the underscores, resulting in enum names like `UPPERSNAKECASE`.
While searching for a solution to this problem, I came across the `enumPropertyNaming` option available in the Kotlin and TypeScript generators. To resolve this discrepancy and ensure that our enum naming style remains consistent with `UPPER_SNAKE_CASE`, I ported this option to the C# …
=> [csharp] Introducing the `enumPropertyNaming` option to the C# Generator

docs/generators/aspnetcore.md, docs/generators/csharp-functions.md, docs/generators/csharp.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/resources/csharp/netcore_project.mustache, modules/openapi-generator/src/main/resources/csharp/netcore_testproject.mustache, modules/openapi-generator/src/main/resources/csharp/nuspec.mustache, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-restsharp-name-parameter-mappings/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-restsharp-name-parameter-mappings/src/Org.OpenAPITools/Model/Env.cs, samples/client/petstore/csharp-restsharp-name-parameter-mappings/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt-useSourceGeneration/src/UseSourceGeneration.Test/UseSourceGeneration.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-httpclient/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Org.OpenAPITools.csproj
Update c# dependencies to newer versions, update reserved word list
cc @mandrean (2017/08) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)
```
```  …
=> Update C# dependencies to newer versions, update reserved word list

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, pom.xml
fix #16710
The problem was that in `mergeProperties`, instances of `Schema` were copied by reference. So later changes to a sub-schema of one of the models affected other models as well.
I had to upgrade swagger-parser so that I could use `AnnotationsUtils.clone`. The new swagger-parser version included a newer jackson-related dependency, so I further had to upgrade some other dependencies so that the transitive jackson-related dependencies were again compatible with each other.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit …
=> fix oneOf merging, upgrade dependencies

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
Using the following spec:
```yaml
openapi: 3.0.0
info:
title: Sample API
description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
version: 0.1.9
servers:
- url: http://api.example.com/v1
description: Optional server description, e.g. Main (production) server
paths:
/users:
post:
summary: Creates a user.
requestBody:
required: true
content:
schema:
type: object
properties:
dataSchema:
type: string
format: uri
default: https://example.com/v1/schema.json
enum:
- https://example.com/v1/schema.json
- https://example.com/v2/schema.json
responses: 
'201':
description: Created
```
The generated DataSchemaEnum is:
```java
public enum DataSchemaEnum {
COM_V1_SCHEMA_JSON("https://example.com/v1/schema.json"), …
```
=> fix(java): generate correct enum constructor when string format is uri

modules/openapi-generator/src/main/resources/typescript-axios/baseApi.mustache, samples/client/echo_api/typescript-axios/build/base.ts, samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/base.ts, samples/client/petstore/typescript-axios/builds/composed-schemas/base.ts, samples/client/petstore/typescript-axios/builds/default/base.ts, samples/client/petstore/typescript-axios/builds/es6-target/base.ts, samples/client/petstore/typescript-axios/builds/test-petstore/base.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/base.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/base.ts, samples/client/petstore/typescript-axios/builds/with-interfaces/base.ts, samples/client/petstore/typescript-axios/builds/with-node-imports/base.ts, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/base.ts, samples/client/petstore/typescript-axios/builds/with-npm-version/base.ts, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/base.ts, samples/client/petstore/typescript-axios/builds/with-string-enums/base.ts
When the base path is an empty string, the current domain is expected to be used
=> [ts][axios] fix bugs in base.ts

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache, modules/openapi-generator/src/test/resources/3_0/go-server/petstore.yaml, samples/server/petstore/go-api-server/api/openapi.yaml, samples/server/petstore/go-api-server/go/api.go, samples/server/petstore/go-api-server/go/api_pet.go, samples/server/petstore/go-api-server/go/api_pet_service.go, samples/server/petstore/go-chi-server/api/openapi.yaml, samples/server/petstore/go-chi-server/go/api.go, samples/server/petstore/go-chi-server/go/api_pet.go, samples/server/petstore/go-chi-server/go/api_pet_service.go
If a form param is an array and isn't caught in the previous checks, treat it as a slice of strings.
Previously it would generate code that would not compile as a `string` would get passed into a function signature that was expecting a slice of strings.
```
```  …
=> [Go][Server] FormParams - Generic Array Type Handling

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-ktor/infrastructure/ApiClient.kt.mustache, modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-array-simple-string-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-ktor-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-ktor-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-ktor-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
#12966 introduced a bug (#14044) where ktor does not perform json serializing at all in requests.
The Content-Type header is simply not set so content negotiation does not step in.
#14045 might also be a solution for this, but it seems to be stalled for some reason (too many changes?), so i created this minimal PR to fix the issue.
This commit fixes the issue for kotlin (ktor) multiplatform and ktor-jvm. Tested with multiplatform.
@jimschubert: Could you review? CI should work, just some download timeouts...
```
```  …
=> [Kotlin] fix(#14044): ktor JSON serialization handling

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoModelTest.java
Add's model name mapping support for go.
Added a new test that tests both the model name creation and model filename.
Because of the way the filenames are generated this took me a few tries to get right, but I think I ended up with the most simple implementation
@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5
```
```  …
=> [GO] Add support for model name mapping for go

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java, modules/openapi-generator/src/main/resources/postman-collection/item.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, samples/schema/postman-collection/postman.json
In the case of generating the Postman collection with the setting `pathParamsAsVariables=true` (where path parameters are defined as environment variables) the generation would change the operation path
```
'/users/{userId}':
```
to
```
'/users/{{userId}}':
```
Although this works, this is not the correct approach: the path parameter value should be set by applying the Postman notation.
This PR fixes this inconsistency creating the correct configuration: set the value of the parameter using the environment variable without affecting the URL.
```
...
"url": {
"raw": "{{baseUrl}}/users/:userId",
"host": [ "{{baseUrl}}" ],
"path": [ "users", ":userId" ],
"variable": [
{
"key": "userId",
"value": "{{userId}}",
"description": "The unique identifier of the user."
}
],
...
```
```
./mvnw clean …
```
=> Use postman notation

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java
After addressing #17028 the method  `doubleCurlyBraces` has become no longer used.
This PR removes the method and its tests.
```
```  …
=> [POSTMAN] Remove unused method doubleCurlyBraces

modules/openapi-generator/src/main/resources/powershell/api.mustache
This fixes #17005 where the `id = APIKeyHeader` was used instead if the apikey `name = X-ApiKey` for apikey in header and query.
```yaml
securityDefinitions:
APIKeyHeader:       # This was wrongly used in the header
type: apiKey
name: X-ApiKey    # This is now used in the header instead
in: header
```
The docs are already correct so they don't need to be updated. Did not add any tests but tested it manually by adding my yaml from the issue and running it with the `./bin/generate-samples.sh ./bin/configs/powershell*` command.
@wing328 could you have a look at this apikey header fix in the powershell generator please.
```
```  …
=> fix(powershell): use apikey name in header instead of securityDefinition spec id

modules/openapi-generator/src/main/resources/powershell/Build.ps1.mustache, modules/openapi-generator/src/main/resources/powershell/Org.OpenAPITools.psm1.mustache, samples/client/petstore/powershell/Build.ps1, samples/client/petstore/powershell/src/PSPetstore/PSPetstore.psm1
This PR fixes #17024 which says that Build.ps1 and *.psm1 fails to run when your openapi spec doesn't have any Models because there is no Model folder then.
@wing328 Could you have a look at this PR please.
```
``` 
IMPORTANT: Do …
=> Fix powershell client Build.ps1 and *.psm1 error when there is a missing Model folder

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache, samples/openapi3/server/petstore/go/go-petstore/go/api_store.go, samples/openapi3/server/petstore/go/go-petstore/go/api_user.go, samples/server/petstore/go-api-server/go/api_store.go, samples/server/petstore/go-api-server/go/api_user.go, samples/server/petstore/go-chi-server/go/api_store.go, samples/server/petstore/go-chi-server/go/api_user.go
If a Path parameter is not a Number or Model it was not being checked if it was provided. Path Parameters are required and should be checked to ensure they were provided.
I verified by attempting to Generate a Go Client with an OpenAPI spec where a Path Param was not provided and the generation failed with the correct message stating the Path Param needed to be marked `required`
```
``` 
You may …
=> [Go][Server] Verify Path Params are provided

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml, samples/client/petstore/java/okhttp-gson/README.md, samples/client/petstore/java/okhttp-gson/api/openapi.yaml, samples/client/petstore/java/okhttp-gson/docs/AnotherFakeApi.md, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
Fix NPE in request body due to null schema
To fix https://github.com/OpenAPITools/openapi-generator/issues/17037
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)
```
```  …
=> Fix NPE in request body

modules/openapi-generator/src/main/resources/python/rest.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent-true/openapi_client/rest.py, samples/client/echo_api/python/openapi_client/rest.py, samples/openapi3/client/petstore/python/petstore_api/rest.py
I added handling of boolean types in text/plain request bodies.
Example YAML:
```yaml
openapi: 3.0.0
info:
title: Test Boolean
version: 1.0.0
servers:
- url: /
paths:
/test:
get:
operationId: test
requestBody:
content:
text/plain:
schema:
type: boolean
required: true
responses:
"200":
description: Success
default:
description: Unexpected Error
```
Before adding the section in the rest.py the request could not be created.
```
```  …
=> [python] added handling for boolean content type

.github/workflows/docker.yaml, .hub.cli.dockerfile, .hub.online.dockerfile, Dockerfile, docker-entrypoint.sh, run-in-docker.sh
Fixes #17000 
```
``` 
Remarks for reviewers:
=> Update base image of Dockerfile

modules/openapi-generator-cli/Dockerfile, modules/openapi-generator-online/Dockerfile
Use [amazoncorretto:17.0.8-alpine3.18](https://hub.docker.com/layers/library/amazoncorretto/17.0.8-alpine3.18/images/sha256-6e6f780411eae55e8dcb59391aa09dd778f0fa2c896f9c218961fdb7da52f485?context=explore) which has 0 vulnerabilities.
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/17007
```
``` 
You may regenerate an individual generator by passing the relevant config(s) …
=> Use JDK17 images in Dockerfile

modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/pom.mustache, samples/client/petstore/java/rest-assured-jackson/build.gradle, samples/client/petstore/java/rest-assured-jackson/pom.xml, samples/client/petstore/java/rest-assured/build.gradle, samples/client/petstore/java/rest-assured/pom.xml
update rest-assured dependencies to newer versions
```
``` 
@bbdouglas (2017/07) @sreeshas …
=> [java] update rest-assured dependencies to newer versions

modules/openapi-generator/src/main/resources/php-nextgen/api.mustache, samples/client/echo_api/php-nextgen/src/Api/AuthApi.php, samples/client/echo_api/php-nextgen/src/Api/BodyApi.php, samples/client/echo_api/php-nextgen/src/Api/FormApi.php, samples/client/echo_api/php-nextgen/src/Api/HeaderApi.php, samples/client/echo_api/php-nextgen/src/Api/PathApi.php, samples/client/echo_api/php-nextgen/src/Api/QueryApi.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/AnotherFakeApi.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/DefaultApi.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeApi.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeClassnameTags123Api.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/PetApi.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/StoreApi.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/UserApi.php
same as #16879 for php-nextgen
```
``` 
=> [PHP-NG] check if json_decode was able to decode response

.github/workflows/samples-python-server.yaml, modules/openapi-generator/src/main/resources/python-aiohttp/controller_test.mustache, modules/openapi-generator/src/main/resources/python-aiohttp/requirements.mustache, modules/openapi-generator/src/main/resources/python-aiohttp/tox.mustache, samples/server/petstore/python-aiohttp-srclayout/requirements.txt, samples/server/petstore/python-aiohttp-srclayout/test_python3.sh, samples/server/petstore/python-aiohttp-srclayout/tests/test_pet_controller.py, samples/server/petstore/python-aiohttp-srclayout/tests/test_store_controller.py, samples/server/petstore/python-aiohttp-srclayout/tests/test_user_controller.py, samples/server/petstore/python-aiohttp-srclayout/tox.ini
```
``` 
ping @cbornet @tomplus @krjakbrjak @fa0311 @multani
- The workflow was basically not …
=> Python-server workflow fixes + pytest

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java
If the type is not specified, then its set as `mixed`, but the nullifying it with a `?` is illegal in PHP, as mixed already includes `null`
```
```  …
=> [PHP-NG] don't nullify mixed types

modules/openapi-generator/src/main/resources/php-nextgen/model_generic.mustache, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/FormatTest.php
same as #16513 but for php-nextgen
```
``` 
=> [PHP-NG] convert data to string before giving it to preg_match

samples/client/petstore/rust/reqwest/petstore/tests/type_testing.rs
Fix rust client test by properly  creating the object.
tests passed locally:
```
running 1 test
test test_types ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Doc-tests petstore-reqwest
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
```
```  …
=> Fix rust client test

modules/openapi-generator/src/main/resources/php-nextgen/ObjectSerializer.mustache, samples/client/echo_api/php-nextgen/src/ObjectSerializer.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ObjectSerializer.php
We have this definition in the specs file:
```
innererror:
type: object
description: The structure of this object is service-specific
```
see https://github.com/owncloud/libre-graph-api/blob/main/api/openapi-spec/v1.0.yaml#L4197C1-L4199C72
In an error case the server replies with:
```
{"error":{"code":"notAllowed","innererror":{"date":"2023-11-17T14:46:21Z","request-id":"789f1afa4e75/f0JanGCTzg-015800"},"message":"insufficient permissions to create a space."}}
```
note that the `innererror` is an object.
But the PHP code would fail with `OpenAPI\Client\Model\OdataErrorMain::setInnererror(): Argument #1 ($innererror) must be of type ?object, array given, called in /home/artur/www/libre-graph-api/out/php-nextgen/src/ObjectSerializer.php on line 537`
Maybe there is a reason, I cannot see, …
=> [PHP-NG] allow 'object' type in serializer

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/inner_dict_with_property.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/nullable_class.py, samples/openapi3/client/petstore/python/petstore_api/models/inner_dict_with_property.py, samples/openapi3/client/petstore/python/petstore_api/models/nullable_class.py, samples/openapi3/client/petstore/python/tests/test_model.py
Model properties annotated only with `type: object` are currently turned into `Union[str, Any]` in Python. This is wrong, since they must be dictionaries. They cannot be strings.
```
```  …
=> [python] fix: Annotate free-form object as dict in Python

modules/openapi-generator/src/main/resources/csharp/libraries/httpclient/ApiClient.mustache, samples/client/petstore/csharp/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
```
``` 
```
``` 
The C Sharp Client will not handle the headers in the `Deserialize` function.
Should use the `ClientUtils.ParameterToString` to handle the header value.
Reference: …
=> fix[csharp]: The Deserialize should use the ClientUtils to handle the headers

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/clientConfiguration.mustache
In #16011, the `@ConditionalOnProperty` import was moved to only the under the `hasOAuthMethods` section of the template. From looking at the mustache template for generating the client config, `@ConditionalOnProperty` import is required for all authentication methods and not just the OAuth. This PR moves the import to the `hasAuthMethods` section so the import is generated for all the types of authentication.
This bug has been raised in #16625.
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg (2023/08) can you guys take a look at this small change? Please let me know if I have missed anything as this is my first change to the project. Thank you!
``` …
```
=> Fix JavaSpring clientConfiguration's @ConditionalOnProperty import

modules/openapi-generator/src/main/resources/python/api_doc.mustache, modules/openapi-generator/src/main/resources/python/api_doc_example.mustache, modules/openapi-generator/src/main/resources/python/model_doc.mustache
Adding some whitespace to better handle markdown render by [jekyll](https://jekyllrb.com/)
=> python docs templates minor fixes for jekyll

README.md
According to information posted at the old url https://github.com/takari/maven-wrapper (most recent commit 2b2c15adc38acfcf17533f5d7aff220ba87256ba as of this writing),
the new official project url of maven wrapper now is https://maven.apache.org/wrapper/
=> README: update url for maven-wrapper

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache, samples/client/petstore/kotlin-array-simple-string-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-default-values-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-multiplatform/build.gradle.kts
=> [kotlin-client][multiplatform] fix iosSimulatorArm64 source sets

modules/openapi-generator/src/main/resources/typescript-fetch/modelGenericInterfaces.mustache
The typescript-fetch templates for models currently don't support nullable enums. This PR copies the `nullable` segment for non-enum properties to fix that.
<details>
<summary>Example OpenAPI spec</summary>
```json
{
"openapi": "3.0.0",
"paths": {
"/": {
"get": {
"operationId": "GetRoot",
"summary": "GET /",
"description": "foo",
"parameters": [],
"responses": {
"200": {
"description": "",
"content": { "application/json": { "schema": { "$ref": "#/components/schemas/PaymentCard" } } }
}
}
}
}
},
"info": {
"title": "API",
"description": "Some API with a nullable enum",
"version": "v1",
"contact": {}
},
"tags": [],
"servers": [],
"components": {
"schemas": {
"PaymentCard": {
"type": "object",
"properties": {
"cardIssuer": { "nullable": true, "enum": ["visa", "mastercard"], "type": "string" } …
```
=> Fix typescript-fetch to support nullable enum properties

.github/workflows/docker.yaml, modules/openapi-generator-cli/Dockerfile, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-online/Dockerfile
Update Dockerfile (cli, online) to use eclipse-temurin:17.0.3_7-jre-focal
Add tests for openapi-generator-cli Dockerfile
```
```  …
=> Update Dockerfile (cli, online) to use eclipse-temurin:17.0.3_7-jre-focal

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
- Add openapi-normalizer rule to set tags to operationId
- add tests
- to close https://github.com/OpenAPITools/openapi-generator/issues/17145
e.g.
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g spring -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml  -o  /tmp/spring5 --openapi-normalizer SET_TAGS_TO_OPERATIONID=true --additional-properties useTags=true
```
```
```  …
=> Add openapi-normalizer rule to set tags to operationId

modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/URLPathUtilsTest.java
Fix build errors in JDK 21
```
``` 
=> Fix build errors in JDK 21

bin/configs/php-nextgen.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/Order.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/OuterEnum.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/OuterEnumDefaultValue.php
- Add enum name mapping support to PHP generators
- add tests
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)
```
```  …
=> Add enum name mapping support to PHP generators

modules/openapi-generator/src/main/resources/rust-server/models.mustache
The JSON Schema Array validation keywords `minItems` and `maxItems` were missing in the template for `model.rs`. 
Fixes #17136
=> include {min|max}Items validation in rust-server models

modules/openapi-generator/src/main/resources/Java/libraries/jersey3/pojo.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/ObjectWithDeprecatedFields.java
During the Jersey3 generation, a deprecated property only generates a deprecated getter, while the model attribute, the setter method and the builder method are not deprecated
This PR adds the @Deprecated annotation where it is applicable
A similar issue was fixed for OkHttp-GSON (#15287)
```
```  …
=> [JAVA] Jersey3 deprecated field only deprecates getter method

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java, modules/openapi-generator/src/test/resources/3_1/common-parameters.yaml
The `OpenAPINormalizer` normalizes the operation parameters but it ignores the common parameters, that are shared by several operations.
This PR fixes this to normalize both sets of parameters. `OpenAPINormalizer.normalizeParameters()` has been refactored to be used for both sets of parameters.
This PR supersedes #17188
```
```  …
=> [BUG] OpenAPI normalizer ignoring common parameters

modules/openapi-generator/src/main/resources/Java/libraries/jersey3/pojo.mustache, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/ObjectWithDeprecatedFields.java
This PR completes #17221 to deprecate also the private attribute (when the field is deprecated in the OpenAPI spec).
@wing328 Sorry, I have missed earlier the deprecation of the attribute.
```
```  …
=> [JAVA] Jersey3 deprecate class attribute

modules/openapi-generator/src/main/resources/postman-collection/item.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, samples/schema/postman-collection/postman.json
This PR makes sure that the required query parameters are enabled on Postman: being mandatory the user is supposed to set a value and always include them in the request
```
```  …
=> [POSTMAN] Enabling required query parameters

bin/configs/go-petstore.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java, samples/openapi3/client/petstore/go/go-petstore/docs/OuterEnum.md, samples/openapi3/client/petstore/go/go-petstore/docs/OuterEnumDefaultValue.md, samples/openapi3/client/petstore/go/go-petstore/model_outer_enum.go, samples/openapi3/client/petstore/go/go-petstore/model_outer_enum_default_value.go
- Add enum name mapping support to Go generators
- add tests
```
``` 
cc 
@antihax (2017/11) …
=> Add enum name mapping support to Go generators

bin/configs/rust-reqwest-petstore.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRustCodegen.java, samples/client/petstore/rust/reqwest/petstore/src/models/order.rs
- Add enum name mapping feature to the Rust generators
- add tests
```
``` 
cc @frol (2017/07) …
=> Add enum name mapping feature to the Rust generators

modules/openapi-generator/src/main/resources/postman-collection/item.mustache
The description of path parameters is escaped, and thus not correctly displayed in Postman, unlike headers and query parameters.
This PR makes sure that the path parameter description is rendered as-is.
```
```  …
=> [POSTMAN] Skip escaping path parameter description

modules/openapi-generator/src/main/resources/php/Configuration.mustache
Discovered by @phpstan
```
``` 
@renepardon
=> Fix parameter names in Configuration

modules/openapi-generator/src/main/resources/php-nextgen/api.mustache, modules/openapi-generator/src/main/resources/php-symfony/serialization/SerializerInterface.mustache, modules/openapi-generator/src/main/resources/php-symfony/testing/model_test.mustache, modules/openapi-generator/src/main/resources/php/api.mustache
While generating PHP code I've noticed few lines are indented with 3 spaces not 4.
Command used: `grep -E '^(    )+ [^* ]'`
```
```  …
=> Fix non-four indents in PHP templates

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/ApiTestsBase.mustache, modules/openapi-generator/src/main/resources/csharp/libraries/generichost/DependencyInjectionTests.mustache, modules/openapi-generator/src/main/resources/csharp/libraries/generichost/README.client.mustache, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt-useSourceGeneration/src/UseSourceGeneration/README.md, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/README.md, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/README.md, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/README.md
Minor mistake went unnoticed due to name and keyParamName being the same.
```
``` 
=> [csharp][generichost] Use keyParamName instead of name

modules/openapi-generator/src/main/resources/php/api.mustache
The indentation was totally missing from the first line of the docblock.
```
``` 
=> Fix PHP constructor docblock

modules/openapi-generator/src/main/resources/powershell/api_client.mustache, samples/client/echo_api/powershell/src/PSOpenAPITools/Private/ApiClient.ps1, samples/client/petstore/powershell/src/PSPetstore/Private/PSApiClient.ps1
Powershell client should use $Response.Content for deserializing response. Converting $Response to string as is replaces non-ascii characters with `?`
fix #17340 
```
```  …
=> Use $Response.Content for deserializing response

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache, samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
In MR #16876, a bug was introduced that causes file downloading to fail for the Faraday adapter.
@meganemura @dkliban
This commit fixes the obvious missing parameter for the method call to `download_file()` and the missing variable `request` for saving the response value of the call to `build_request()`.
Tested so far only locally, but would like to add an appropriate test case for binary data download but need some feedback, how to integrate this kind of tests into this MR.
There is an appropriate test scenario for the Python client that could be used as reference:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/echo_api/python/test/test_manual.py#L110
``` …
```
=> Ruby Client for Faraday: fix file downloading

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
fix: #17085 
To [Java technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee): @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)
```
```  …
=> [JavaSpring] Enable scopes for all security scheme types

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/model/WebhooksMap.java, modules/openapi-generator/src/main/resources/go-gin-server/routers.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/goginserver/GoGinServerCodegenTest.java, modules/openapi-generator/src/test/resources/3_1/webhooks.yaml, samples/server/petstore/go-gin-api-server/go/routers.go
Add support for webhooks introducing the webhooks root element, without affecting the existing apis.
Provided a test case for the Go Gin Server to prove the generator makes webhooks available to the mustache templates.
Webhook generation can be skipped if needed (same as models and apis).
```
```  …
=> OpenAPI 3.1.0 Add webhooks support

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/api.mustache, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt-useSourceGeneration/src/UseSourceGeneration/Api/PetApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs
Hey, I would like `generichost` library to support basic method/param deprecation like this: https://github.com/OpenAPITools/openapi-generator/pull/10084 in the past.  
I've added conditional `[Obsolete]` attribute on `I{{Controller}}Api` methods along with `(deprecated)` in param descriptions, pretty much the same as mentioned PR.   
We just need _anything_ to show our clients that stuff is deprecated, most of them don't care about `<remarks>...</remarks>` but having build warning gets their attention.
Let me know if I need to make an issue for this or change/fix something, but it's a fairly simple addition.
Tagging @devhl-labs because as far as I've seen you mostly maintain this library :)
=> [csharp][generichost] Handle obsolete params and methods

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumClass.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumOuterClass.mustache, modules/openapi-generator/src/main/resources/Java/libraries/native/modelEnum.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/modelEnum.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/modelInnerEnum.mustache, modules/openapi-generator/src/main/resources/Java/modelEnum.mustache, modules/openapi-generator/src/main/resources/Java/modelInnerEnum.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/enum-and-inner-enum-uri.yaml
This is a followup to #16929 to fix the compilation errors with the java ok-http-gson. I also tested compilation against all java libraries.
The modelEnum template needed an additional update to CodegenModel to check if the format is set as a URI as the isUri check was returning false. I followed the same code as isUuid, but noticed a comment in DefaultCodeGen about UUID being a rare use case and may be removed in future [DefaultCodegen.java#L3031](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L3031), so I don't know if this change is the best approach.
```
``` 
(For Windows users, …
=> Fix issue with URI type in the enum

modules/openapi-generator/src/main/resources/scala-akka-client/apiRequest.mustache, modules/openapi-generator/src/main/resources/scala-akka-client/paramCreation.mustache, samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/api/PetApi.scala, samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/core/ApiRequest.scala, samples/client/petstore/scala-akka/src/test/scala/PetApiTest.scala
based on #8610
manual tests passed in #8610 
better tests is to use the echo api spec and we'll see if anyone from the community has time to make the contributions.
```
```  …
=> [scala-akka-client] Scala Akka client does not support arbitrary query string parameters 

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache, samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
This PR is a fix proposal for Java client with Apache HTTP library generator.
By default, this generator creates code that doesn't support JSON payloads containing UTF-8 characters.
The fix here is to set JSON `StringEntity` default charset to UTF-8.
Related issue: https://github.com/OpenAPITools/openapi-generator/issues/12797
```
```  …
=> fix: java apache httpclient should support UTF-8 by default

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/resources/3_1/java/petstore.yaml, samples/client/petstore/java/okhttp-gson-3.1/README.md, samples/client/petstore/java/okhttp-gson-3.1/api/openapi.yaml, samples/client/petstore/java/okhttp-gson-3.1/docs/FakeApi.md, samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/api/FakeApi.java
- dereference parameters in OpenAPI 3.1 spec
- add tests
to fix https://github.com/OpenAPITools/openapi-generator/issues/17160
```
```  …
=> Dereference parameters in OpenAPI 3.1 spec

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
The modelNameMappings were introduced with PRs #16209, #16234 and are now also used in the ruby client generator.
The previously implemented lookup in schemaMappings (PR #12962) still takes precedence.
```
```  …
=> [Ruby] Add model name mapping support to ruby client generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/allOf_extension_parent.yaml
to fix https://github.com/OpenAPITools/openapi-generator/issues/17425
```
``` 
FYI …
=> To fix infinite loop for allOf with single element in normalizer

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/resources/3_1/java/petstore.yaml, samples/client/petstore/java/okhttp-gson-3.1/api/openapi.yaml, samples/client/petstore/java/okhttp-gson-3.1/docs/AnyTypeTest.md, samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/model/AnyTypeTest.java
Fix missing array description in 3.1 spec
to fix https://github.com/OpenAPITools/openapi-generator/issues/17423
```
```  …
=> Fix missing array description in 3.1 spec

modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache, samples/client/others/typescript/builds/with-unique-items/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/browser/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/default/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/deno/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/inversify/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/jquery/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/builds/object_params/models/ObjectSerializer.ts, samples/openapi3/client/petstore/typescript/tests/default/test/models/ObjectSerializer.test.ts
Address https://github.com/OpenAPITools/openapi-generator/issues/17282
```
``` 
---
@TiFu …
=> Generalized mime type support

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java, samples/client/petstore/typescript-axios/builds/test-petstore/api.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts, samples/client/petstore/typescript-fetch/builds/default-v3.0/models/NullableClass.ts, samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/NullableClass.ts
Models generated from `additionalProperties` schema with `nullable: true` are missing `null` from the type declaration.
Applies https://github.com/OpenAPITools/openapi-generator/pull/15026 to the base typescript codegen to fix other TS-based generators.
```
```  …
=> fix(typescript-*): nullable additionalProperty values

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
fix #17196
In typescript-axios `useSingleRequestParameter` an `AxiosRequestConfig` is used without import.
Fixed by changing to `RawAxiosRequestConfig` with reference to #14518 .
```
```  …
=> [typescript-axios] Fix Missing AxiosRequestConfig

modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, samples/client/petstore/java/webclient-jakarta/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/webclient-jakarta/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/webclient-jakarta/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/webclient-swagger2/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/webclient-swagger2/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/webclient-swagger2/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/UserApi.java
Webclient explode query parameters support
Related issues:
https://github.com/OpenAPITools/openapi-generator/issues/907
https://github.com/OpenAPITools/openapi-generator/issues/14691
https://github.com/OpenAPITools/openapi-generator/issues/4808
Similar to https://github.com/OpenAPITools/openapi-generator/pull/14825 (RestTemplate fix)
```
```  …
=> webclient explode query parameters support

modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java
Remove tests that are now replaced with Python sample testing
@wing328 Sorry, forgot to push those changes
```
```  …
=> [POSTMAN] Remove tests replaced with Python sample testing

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache, samples/client/others/kotlin-jvm-okhttp-parameter-tests/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-name-parameter-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
With recent versions of `okhttp3`, the variable `EMPTY_REQUEST` (defined in package `okhttp3.internal`) is changed to be, well, `internal`. This caused the generated Kotlin code in `ApiClient.kt` to be faulty.
This pr defines the same variable as a local one.
```
```  …
=> Stop using internal variable from okhttp3

modules/openapi-generator/src/main/resources/kotlin-spring/apiController.mustache, modules/openapi-generator/src/main/resources/kotlin-vertx-server/apiProxy.mustache, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApiController.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApiController.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApiController.kt, samples/server/petstore/kotlin-vertx-modelMutable/src/main/kotlin/org/openapitools/server/api/verticle/PetApiVertxProxyHandler.kt, samples/server/petstore/kotlin-vertx-modelMutable/src/main/kotlin/org/openapitools/server/api/verticle/StoreApiVertxProxyHandler.kt, samples/server/petstore/kotlin-vertx-modelMutable/src/main/kotlin/org/openapitools/server/api/verticle/UserApiVertxProxyHandler.kt, samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/verticle/PetApiVertxProxyHandler.kt, samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/verticle/StoreApiVertxProxyHandler.kt, samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/verticle/UserApiVertxProxyHandler.kt
See https://github.com/OpenAPITools/openapi-generator/issues/17465
```
``` 
@jimschubert …
=> Fix Kotlin templates to be compatible with Kotlin K2 compiler

modules/openapi-generator/src/main/resources/swift5/OpenAPIDateWithoutTime.mustache, samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/OpenAPIDateWithoutTime.swift, samples/client/petstore/swift5/alamofireLibrary/SwaggerClientTests/SwaggerClientTests/DateFormatTests.swift
Fix decoding OpenAPIDateWithoutTime which in previous implementation only worked when used with CodableHelper, because it encoded to String, but tried to decode from Date afterwards
```
```  …
=> Fix decoding OpenAPIDateWithoutTime

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
Not throwing exception when ignore file exists on windows.
```
``` 
=> Not throwing exception when ignore file exists

.github/CODEOWNERS
Adding the technical committee manually each time is boring. Adding the technical committee to the .github/CODEOWNERS
allow automatic notification.
Maybe someone could create on these file without pinging me to check it works well on this repo (this is the case on another repo I contribute to: https://github.com/conan-io/conan-center-index/)
```
```  …
=> [cpp-qt-client] Add cpp-qt-client technical committee to CODEOWNERS

modules/openapi-generator/src/main/resources/cpp-qt-client/CMakeLists.txt.mustache, samples/client/petstore/cpp-qt/client/CMakeLists.txt
CMake 3.27.7 complains with low minimum version:
CMake Deprecation Warning at youdub/client/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of CMake.
```
```  …
=> [cpp-qt-client] Update minimum cmake version to 3.5

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache, samples/client/echo_api/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/resttemplate-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
in rest template, when the retry limits exceeded
rethrow the original exception
also add 429 (Too many requests) status code to the retry logic
fix #17478
```
```  …
=> [resttemplate] rethrow original exception when retry limits exceeded

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/api.mustache
Remove optional path parameter in C# generichost template
cc @devhl-labs 
```
``` 
=> Remove optional path parameter in C# generichost template

bin/configs/ruby.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java, samples/client/petstore/ruby/lib/petstore/models/outer_enum.rb, samples/client/petstore/ruby/lib/petstore/models/outer_enum_default_value.rb
Add enum name mapping support to Ruby generators
To close https://github.com/OpenAPITools/openapi-generator/issues/11350
```
```  …
=> Add enum name mapping support to Ruby generators

bin/configs/spring-boot-3.yaml, modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, samples/openapi3/server/petstore/springboot-3/pom.xml, samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/Category.java, samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/ModelApiResponse.java, samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/Order.java, samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/Pet.java, samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/Tag.java, samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/User.java, samples/openapi3/server/petstore/springboot-3/src/test/java/org/openapitools/JacksonTest.java, samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Category.java, samples/server/petstore/java-camel/src/main/java/org/openapitools/model/ModelApiResponse.java, samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Order.java, samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Pet.java, samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Tag.java, samples/server/petstore/java-camel/src/main/java/org/openapitools/model/User.java
Fixes https://github.com/OpenAPITools/openapi-generator/issues/16915 by changing the spring-pojo template to correctly place the JacksonXmlProperty annotations.
* Modify the test added for https://github.com/OpenAPITools/openapi-generator/issues/5705 so that it checks the corrected template.
* add test to the openapi3/server/petstore/springboot-3 sample
```
```  …
=> Fix spring generator dto annotations for xml support

modules/openapi-generator/src/main/resources/go-server/routers.mustache, samples/openapi3/server/petstore/go/go-petstore/go/routers.go, samples/server/petstore/go-api-server/go/routers.go, samples/server/petstore/go-chi-server/go/routers.go
Currently for the go-server, we're taking uploaded files (multipart/form-data), reading them and creating tmp files for them. There was some unexpected behaviour there, one of which was that this function returns an already closed file, so consumers will really only use the filename to manually open it from disk again, but also since it uses the default tmpfile creation with a random value suffixed, it's "impossible" to go back to the original filename (unless assuming the suffix is always fixed length, but meh).
My preferred approach would be something along these lines, but that actually changes behaviour (not putting the files on disk at all), so that could be a breaking change (especially as existing users will be taking the filename, and reopening it from disk, which won't work with …
=> fix(go-server): ensure original filename can be deduced from tmp file

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java, modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml, samples/client/petstore/java/apache-httpclient/api/openapi.yaml, samples/client/petstore/java/feign/api/openapi.yaml, samples/client/petstore/java/okhttp-gson/api/openapi.yaml, samples/client/petstore/java/resteasy/api/openapi.yaml, samples/client/petstore/java/resttemplate-withXml/api/openapi.yaml, samples/client/petstore/java/resttemplate/api/openapi.yaml, samples/client/petstore/java/vertx/api/openapi.yaml, samples/client/petstore/java/webclient-jakarta/api/openapi.yaml, samples/client/petstore/java/webclient-swagger2/api/openapi.yaml, samples/client/petstore/java/webclient/api/openapi.yaml, samples/openapi3/client/petstore/java/jersey2-java8-special-characters/api/openapi.yaml, samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/api/BarApi.java, samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/api/FooApi.java, samples/openapi3/server/petstore/spring-boot-oneof/src/main/resources/openapi.yaml, samples/openapi3/server/petstore/springboot-delegate/src/main/resources/openapi.yaml, samples/openapi3/server/petstore/springboot-implicitHeaders/src/main/resources/openapi.yaml, samples/server/petstore/java-helidon-server/mp/src/main/resources/META-INF/openapi.yml, samples/server/petstore/java-helidon-server/se/src/main/resources/META-INF/openapi.yml, samples/server/petstore/springboot-beanvalidation-no-nullable/src/main/resources/openapi.yaml, samples/server/petstore/springboot-beanvalidation/src/main/resources/openapi.yaml, samples/server/petstore/springboot-delegate-j8/src/main/resources/openapi.yaml, samples/server/petstore/springboot-delegate/src/main/resources/openapi.yaml, samples/server/petstore/springboot-implicitHeaders/src/main/resources/openapi.yaml, samples/server/petstore/springboot-reactive-noResponseEntity/src/main/resources/openapi.yaml, samples/server/petstore/springboot-reactive/src/main/resources/openapi.yaml, samples/server/petstore/springboot-useoptional/src/main/resources/openapi.yaml, samples/server/petstore/springboot-virtualan/src/main/resources/openapi.yaml
Changes the previous behavior of generating `null` examples for composed schemas.
Fixes #17497
```
```  …
=> fix: ExampleGenerator correctly generates allOf composed schemas

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java, modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml
When an example was specified for a property with the `date` format, it's example would be generated to something like `2024-01-01T00:00:00.000+00:00` or `Sat Jan 30 01:00:00 CET 2021`.
It's because the resolved type for a Date example is a DateSchema, and a DateSchema uses `java.util.Date` to represents the Date. Which gets printed using .toString() not in the YYYY-MM-dd format.
Fixes #17494 #15342
```
```  …
=> fix: ExampleGenerator correctly produces YYYY-MM-dd format for `date` with examples

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-restclient/api.mustache, modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-webclient/api.mustache, samples/client/petstore/kotlin-jvm-spring-2-webclient/src/main/kotlin/org/openapitools/client/apis/PetApi.kt, samples/client/petstore/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/apis/PetApi.kt, samples/client/petstore/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
While with  #12255   the handling of default values for different kotlin clients was unified, the new clients added with #15568 and #17366 do handle default values differently. This change tries to bring the new clients jvm-spring-webclient and jvm-spring-restclient in line with other kotlin clients.
@stefankoppier as the creator of jvm-spring-webclient / jvm-spring-webclient
Kotlin technical committee: @jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it …
=> [BUG][Kotlin] Add default values to optional parameters for jvm-spring-webclient and jvm-spring-restclient

modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/RFC3339DateFormat.java, modules/openapi-generator/src/main/resources/Java/JSON.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache, modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/pom.mustache, modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON.mustache, modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/pom.mustache, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/JSON.java, samples/client/others/java/okhttp-gson-oneOf/src/main/java/org/openapitools/client/JSON.java, samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/okhttp-gson/pom.xml, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/rest-assured-jackson/pom.xml, samples/client/petstore/java/rest-assured/pom.xml, samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/retrofit2-play26/pom.xml, samples/client/petstore/java/retrofit2/pom.xml, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/retrofit2rx2/pom.xml, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/retrofit2rx3/pom.xml, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/JSON.java
This PR removes the last dependency to com.google.gson.internal.* packages by copying ISO8601Utils.java to this project's source code. The file itself was already copied to gson from the Jackson databind library (see https://github.com/google/gson/blob/main/gson/src/main/java/com/google/gson/internal/bind/util/ISO8601Utils.java). I have used the latest version to date: https://github.com/FasterXML/jackson-databind/blob/2.16/src/main/java/com/fasterxml/jackson/databind/util/ISO8601Utils.java
This change is needed as the internal gson packages (where ISO8601Utils has been copied to) have been excluded from the exposed packages in osgi environments since gson version 2.8.6 (see this related issue for more information: https://github.com/OpenAPITools/openapi-generator/issues/13169 in which …
=> remove internal ISO8601Utils dependency
