modules/openapi-generator/src/main/resources/typescript/auth/auth.mustache, modules/openapi-generator/src/main/resources/typescript/package.mustache, samples/openapi3/client/petstore/typescript/builds/default/auth/auth.ts, samples/openapi3/client/petstore/typescript/builds/default/package.json, samples/openapi3/client/petstore/typescript/builds/inversify/auth/auth.ts, samples/openapi3/client/petstore/typescript/builds/inversify/package.json, samples/openapi3/client/petstore/typescript/builds/object_params/auth/auth.ts, samples/openapi3/client/petstore/typescript/builds/object_params/package.json
https://github.com/OpenAPITools/openapi-generator/issues/14257
```
``` 
=> [Typescript] Change btoa to native code

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/pom-sb3.mustache, modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/pom.mustache, samples/client/petstore/spring-cloud-async/pom.xml, samples/client/petstore/spring-cloud-date-time/pom.xml, samples/client/petstore/spring-cloud-feign-without-url/pom.xml, samples/client/petstore/spring-cloud-spring-pageable/pom.xml, samples/client/petstore/spring-cloud/pom.xml, samples/openapi3/client/petstore/spring-cloud-3/pom.xml, samples/openapi3/client/petstore/spring-cloud-async/pom.xml, samples/openapi3/client/petstore/spring-cloud-date-time/pom.xml, samples/openapi3/client/petstore/spring-cloud-oas3-fakeapi/pom.xml, samples/openapi3/client/petstore/spring-cloud-spring-pageable/pom.xml, samples/openapi3/client/petstore/spring-cloud/pom.xml
- Upgrade Spring Boot to 2.7.6/3.0.0
- Upgrade Spring Cloud to 2021.0.5/2022.0.0
```
```  …
=> [Java][Spring] Upgrade Spring Cloud dependencies

modules/openapi-generator/src/main/resources/python/api_client.handlebars, modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml, samples/openapi3/client/3_0_3_unit_test/python/unit_test_api/api_client.py, samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api_client.py, samples/openapi3/client/petstore/python/docs/apis/tags/FakeApi.md, samples/openapi3/client/petstore/python/petstore_api/api_client.py, samples/openapi3/client/petstore/python/petstore_api/paths/fake_delete_coffee_id/delete.py, samples/openapi3/client/petstore/python/petstore_api/paths/fake_delete_coffee_id/delete.pyi
Synonym PR for https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/106
```
``` 
=> [python] Fixes Response TypeError

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java, modules/openapi-generator/src/main/resources/python/endpoint.handlebars
=> Add JsonIgnore annotation to avoid debugSupportingFiles creating heap space issues

.github/workflows/check-supported-versions.yaml
Add a test for debugSupportingFiles
```
``` 
=> Add a test for debugSupportingFiles

modules/openapi-generator/pom.xml, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonLegacyClientCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonNextgenClientCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonPriorClientTest.java, modules/openapi-generator/src/test/resources/3_0/v1beta3.yaml, pom.xml
Update opeanpi-generator dependencies
```
``` 
=> Update opeanpi-generator dependencies

modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache
Fix for: https://github.com/OpenAPITools/openapi-generator/issues/14337
```
```  …
=> Fix problem when uploading file using form-data in jersey3 client

modules/openapi-generator-cli/pom.xml
Update CLI module dependencies
```
``` 
FYI  @OpenAPITools/generator-core-team
=> Update CLI module dependencies

.travis.yml, pom.xml
- move python-fastapi test to another node in circleci
- comment some tests in Travis (test locally for the time being)
```
``` 
=> Fix circleci build failure (node1) and Travis build failure

.travis.yml
Fix `mvn deploy` in Travis CI
```
``` 
=> Fix `mvn deploy` in Travis CI

docs/generators/java.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
Update useRuntimeException description in java client generator
```
```  …
=> [java] Update useRuntimeException description

.github/workflows/samples-dotnet-standard.yaml, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/README.md
Trying to fix pipeline to enable a release.
```
``` 
=> [csharp-netcore] Pipeline fix

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, modules/openapi-generator/src/main/resources/Java/libraries/native/oneof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/native/pojo.mustache, modules/openapi-generator/src/main/resources/Java/pojo.mustache
based on #14493 with a fix to NPE
```
``` 
cc 
=> [java] Fix template logic related to supportUrlQuery 

modules/openapi-generator/src/main/resources/typescript-koa-server/package.mustache, samples/server/petstore/typescript-koa-server/package.json, samples/server/petstore/typescript-koa-server/yarn.lock
=> Fix version of ts-node-dev for ts-koa2-server

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
This PR fixes the issue [#14545](https://github.com/OpenAPITools/openapi-generator/issues/14545)
Here is the openapi spec that can be used to reproduce the issue and verify the fix. 
```yaml
openapi: 3.0.3
info:
title: parameter type is enum
version: '1.0'
paths:
/state:
get:
operationId: getBooks
parameters:
- explode: true
in: query
name: language
required: false
schema:
$ref: '#/components/schemas/LanguageCode'
responses:
'200':
description: get Books
content:
schema:
$ref: '#/components/schemas/Books'
components:
schemas:
Books:
properties:
title:
type: string
language:
$ref: '#/components/schemas/LanguageCode'
author:
type: string
type: object
LanguageCode:
enum:
- eng
- jpn
title: language_code
type: string
```
``` …
```
=> [scala-sttp]Update import for enum in API class  

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenMediaType.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/content-data.yaml
Fix #14169
This PR makes sure the examples defined in Response Content are made available to the Mustache templates
```
``` 
- [] If your PR is targeting a particular programming language, @mention the [technical …
=> Support examples in Response Content

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache, modules/openapi-generator/src/main/resources/go-server/routers.mustache, samples/server/petstore/go-api-server/go/routers.go, samples/server/petstore/go-chi-server/go/routers.go, samples/server/petstore/go-server-required/go/routers.go
This fixes issue #10787
```
``` 
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04)
=> [Go] Updates bool parameter parsing to handle optional params

.github/workflows/samples-cpp-qt-client.yaml
=> Add action for qt client

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache, samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
Send empty body instead of `null` when the http request body is not provided.
```
```  …
=> Fix empty body in java apache client

CI/circle_parallel.sh
Update CI to install v1.18
```
``` 
```
``` 
=> Update CI to install v1.18

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
=> [java]  better code format

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey2/JSON.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/JSON.mustache, samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/JSON.java, samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java, samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/JSON.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/JSON.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java
Some minor cleanups and a bug fix for the Java Jersey2 & 3 client generators.
Fix a bug introduced in 8551b0af492286a431c95ce3a37d7edf1ef4870a where `ALLOW_COERCION_OF_SCALARS` wasn't set properly on the `ObjectMapper`.
@wing328
```
```  …
=> [java][jersey] Fix ALLOW_COERCION_OF_SCALARS

modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/spring/KotlinSpringServerCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/kotlin/issue4111-multiline-operation-description.yaml, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApi.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApi.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApi.kt, samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/PetApiController.kt, samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/StoreApiController.kt, samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/UserApiController.kt, samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/PetApiController.kt, samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/StoreApiController.kt, samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/UserApiController.kt, samples/server/petstore/kotlin-springboot-source-swagger2/src/main/kotlin/org/openapitools/api/PetApiController.kt, samples/server/petstore/kotlin-springboot-source-swagger2/src/main/kotlin/org/openapitools/api/StoreApiController.kt, samples/server/petstore/kotlin-springboot-source-swagger2/src/main/kotlin/org/openapitools/api/UserApiController.kt
This adds support for multiline descriptions for operations in the Kotlin-Spring generator for both regular API generation (i.e. Controller) and interface-only API generation.
Multiline descriptions allow us to use rich text representations, e.g. with Markdown. Note that Markdown-formatted descriptions are rendered nicely in Swagger-UI. I imagine that most openapi consumers will be able (or want to) support Markdown (at some point).
The solution for Kotlin-Spring is rather simple, using Raw Strings to contain the `unescapedNotes`.
I've added a test case for both the regular API and the interface-only API. The Samples were ~left unchanged~ updated after running the steps below.
This pull request resolves this issue in Kotlin-Spring only:
- #4111
``` …
```
=> [Kotlin-Spring] Support multiline descriptions

modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/class_serializer.mustache
Fixes #14519
This commit makes use of [one_of_serializer](https://pub.dev/packages/one_of_serializer).
Attn: @jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela
```
``` 
=> [dart-dio] Fix anyOf serialization

modules/openapi-generator/src/main/resources/typescript/README.mustache
Very minor change. Backstory: Looks like a large, sweeping change trimmed off a few backticks in the `README` template. Without them the rest of `typescript` generator readme is rubbish. 
Edits: I added three backticks in order to format the `README` as intended.
```
```  …
=> Updated typescript generator readme template

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
- update starlette to newer version
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla …
=> [python-fastapi] update starlette to newer version

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/api.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/UserApi.cs
Fixes https://github.com/OpenAPITools/openapi-generator/issues/14682
```
``` 
```
``` 
=> [csharp-netcore] Use scheme from base address

samples/client/petstore/R/build_and_test.bash
Install lifecycle as part of R tests
```
``` 
```
``` 
=> Install lifecycle as part of R tests

.travis.yml, website/docusaurus.config.js
- Enable onBrokenLinks (set to `ignore`)
- stop auto publish in CI as it failed
```
``` 
```
``` 
=> [website] Enable onBrokenLinks

samples/client/echo_api/python-nextgen/test/test_manual.py
=> [python-nextgen] better datetime test

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-ktor/api.mustache
Sadly there is a bug introduced by @Rattenkrieg in #14717 🙈 who seems to have forgotten that array iteration has different syntax in kotlin and java.
I believe we can add additional cases in tests to cover such behavior, however I'm not sure which spec to patch so I any guidance here would be appreciated.
```
```  …
=> ktor-client fix array generation

.github/workflows/samples-erlang.yaml, samples/client/petstore/erlang-client/pom.xml
Setup Github works for Erlang projects
```
``` 
```
``` 
@tsloughter @jfacorro @robertoaloi
=> Setup Github works for Erlang projects

bitrise.yml, samples/client/petstore/swift5/alamofireLibrary/pom.xml, samples/client/petstore/swift5/swift5_test_all.sh
(based on https://github.com/OpenAPITools/openapi-generator/pull/14834 and included commits to skip builds of openapi-generator, which takes a long time)
Try to fix bitrise warning `This workflow is using a deprecated stack. Change your build stack, or your builds will not work after Mar 13`
```
```  …
=> [CI] try to fix bitrise deprecation warning #14834

docs/generators/typescript-axios.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
Adds options to the typescript-axios generator's reserved words, so clients with "options" parameters generate valid typescript code.
Fixes #14649
Before:
```
async v1SamplePost(options?: object, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1SamplePost200Response>> {
const localVarAxiosArgs = await localVarAxiosParamCreator.v1SamplePost(options, options);
return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
},
```
After:
```
async v1SamplePost(_options?: object, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1SamplePost200Response>> {
const localVarAxiosArgs = await localVarAxiosParamCreator.v1SamplePost(_options, options);
return …
```
=> [Typescript-Axios] Add options to TypescriptAxios reserved words

README.md
add dmTECH GmbH as company using openApiGenerator
```
``` 
```
``` 
=> add dmTECH GmbH as company using openApiGenerator

modules/openapi-generator/src/main/resources/typescript-angular/api.module.mustache, samples/client/petstore/typescript-angular-v12-oneOf/builds/default/api.module.ts, samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api.module.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api.module.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api.module.ts, samples/client/petstore/typescript-angular-v13-oneOf/builds/default/api.module.ts, samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api.module.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api.module.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api.module.ts, samples/client/petstore/typescript-angular-v14-provided-in-root/builds/default/api.module.ts, samples/client/petstore/typescript-angular-v14-query-param-object-format/api.module.ts, samples/client/petstore/typescript-angular-v15-provided-in-root/builds/default/api.module.ts
```
``` 
```
``` 
@macjohnny I found another issue, will look at the other PR and figuring out if some of the steps ^^^ are part of the problem
=> fix(typescript-angular): only import services if providing them

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/api.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/UserApi.cs
Fixes https://github.com/OpenAPITools/openapi-generator/issues/14874
```
``` 
```
``` 
=> [csharp-netcore] Removed double encoding

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue-5676-enums.yaml, samples/client/petstore/typescript-fetch/builds/enum/apis/DefaultApi.ts, samples/client/petstore/typescript-fetch/builds/with-string-enums/apis/DefaultApi.ts
Better support of allOf with 1 sub-schema (supporting nullable, readOnly, writeOnly, default to start with)
to close https://github.com/OpenAPITools/openapi-generator/issues/14689
```
``` 
``` …
```
=> Better support of allOf with 1 sub-schema

modules/openapi-generator/src/main/resources/csharp-netcore/TestProject.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/netcore_project.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/netcore_testproject.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/nuspec.mustache, samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Org.OpenAPITools.csproj
Update C# client dependencies
<br class="Apple-interchange-newline">
```
``` 
```
```  …
=> Update C# client dependencies

docs/generators/csharp-netcore.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
Update option description
A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/14894
```
``` 
```
``` 
=> [csharp-netcore] Update option description

bin/configs/jaxrs-cxf-cdi.yaml, modules/openapi-generator/src/test/resources/3_0/jaxrs/petstore.yaml, samples/server/petstore/jaxrs-cxf-cdi/.openapi-generator/FILES, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/PetApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/PetApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/StoreApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/TestApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/TestApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/UserApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/UserApiService.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/model/Category.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/org/openapitools/api/impl/PetApiServiceImpl.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/org/openapitools/api/impl/StoreApiServiceImpl.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/org/openapitools/api/impl/TestApiServiceImpl.java, samples/server/petstore/jaxrs-cxf-cdi/src/main/java/org/openapitools/api/impl/UserApiServiceImpl.java
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/14439
```
``` 
```
``` 
FYI @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet …
=> [jaxrs-cxf-cdi] add tests for binary body

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/JsonConverter.mustache, modules/openapi-generator/src/test/resources/3_0/csharp/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/docs/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/docs/models/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/docs/models/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/docs/models/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/docs/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/docs/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/docs/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-unityWebRequest/docs/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient-unityWebRequest/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/FormatTest.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/FormatTest.cs
Adding unsigned numbers to the samples.
```
``` 
```
``` 
=> [csharp-netcore] Added samples for unsigned

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/DateTimeJsonConverter.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/DateTimeNullableJsonConverter.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Client/DateTimeJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Client/DateTimeNullableJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Client/DateTimeJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Client/DateTimeNullableJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Client/DateTimeJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Client/DateTimeNullableJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Client/DateTimeJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Client/DateTimeNullableJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Client/DateTimeJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Client/DateTimeNullableJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Client/DateTimeJsonConverter.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Client/DateTimeNullableJsonConverter.cs
Use the DateTime format in two more places.
```
``` 
```
``` 
=> [csharp-netcore] Used the date format

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelTest.java
Expose `isPassword` codegen property. This property can be used in the mustache templates to handle specific generation use case. _e.g._:
* hiding the string value of password fields in generated toString() methods
* use more specific types like `char[]` instead of `String` in [Java](https://stackoverflow.com/a/8881376)
Closes https://github.com/OpenAPITools/openapi-generator/issues/9124
```
```  …
=> feat(password): add `isPassword` codegen property

.travis.yml, samples/server/petstore/jaxrs-spec-required-and-readonly-property/src/gen/java/org/openapitools/api/RestResourceRoot.java
Reduce log level to avoid Travis CI build failure
```
``` 
```
``` 
=> Reduce log level to avoid Travis CI build failure

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/OperationOrDefault.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/api.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/UserApi.cs
Fixes https://github.com/OpenAPITools/openapi-generator/issues/14950
```
``` 
```
``` 
=> [csharp-netcore] Suffixed variables with LocalVar to avoid conflicts

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
=> [GO] [REQ] Enable bearer security schema for Go client

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java, modules/openapi-generator/src/main/resources/typescript/model/model.mustache
https://github.com/OpenAPITools/openapi-generator/issues/10593
`"nullable": true` for Typescript generator
```
``` 
```
``` 
=> [Typescript] Nullable

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
The ModelUtils class contains many helpful methods and some methods behave in very similar ways.
However their source code looked different even though they got the same basic logic.
To improve the code readability harmonize the method code and simplify some logic. 
Example:
```
public bool function()
{
if (a) {
return true;
} else {
return false;
}
}
```
can be simplified to
```
public bool function()
{
return a;
}
```
It seems like a rather lengthy PR on a very core class, however, each commit is quite short and distinct, and the commit messages might help as well.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge …
=> Refactor ModelUtils methods without logic changes

modules/openapi-generator/src/main/resources/python-nextgen/api_client.mustache
=> Fix typo in api_client.mustache "configuraiton -> configuration"

modules/openapi-generator/src/main/resources/python-nextgen/github-workflow.mustache, samples/client/echo_api/python-nextgen/.github/workflows/python.yml, samples/openapi3/client/petstore/python-nextgen-aiohttp/.github/workflows/python.yml, samples/openapi3/client/petstore/python-nextgen/.github/workflows/python.yml
Fix typos in github workflow
To fix https://github.com/OpenAPITools/openapi-generator/issues/15090
tested in https://github.com/wing328/python-ci-test/actions and all tests passed
```
``` 
```
```  …
=> [python-nextgen] Fix github workflow 

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
improve SIMPLIFY_ANYOF_STRING_AND_ENUM_STRING by simplifying enum of string & string to just enum of string instead.
```
``` 
```
``` 
=> [openapi-normalizer] improve SIMPLIFY_ANYOF_STRING_AND_ENUM_STRING

README.md
Fix link to TravisCI, add links to posts
```
``` 
```
``` 
=> Fix link to TravisCI, add links to posts

modules/openapi-generator/src/main/resources/python-nextgen/pyproject.mustache, samples/client/echo_api/python-nextgen/pyproject.toml, samples/openapi3/client/petstore/python-nextgen-aiohttp/pyproject.toml, samples/openapi3/client/petstore/python-nextgen/pyproject.toml
Downgrade tox and flake8. Alternatively, we can increase the minimum python version to 3.8.1. Related issue #15166 
```
``` 
```
``` 
/cc @spacether
=> fix(python-nextgen): dependency incompatibility

docs/customization.md
In documentation, clarify which OpenAPI Generator version exactly introduced [Set skipFormModel to true by default](https://github.com/OpenAPITools/openapi-generator/pull/8125).
- [ x Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as an argument …
=> Update customization.md: clarify `skipFormModel` version

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
Using `--reserved-words-mappings` argument does not work they are not marked to be escaped 
```
``` 
```
``` 
Fixes
- fixes #4833
- fixes #15002
Partially addresses #14956
=> [go] Fix: reservedWordsMappings not checked for reserved word

modules/openapi-generator/src/main/resources/python-nextgen/pyproject.mustache, modules/openapi-generator/src/main/resources/python-nextgen/requirements.mustache, modules/openapi-generator/src/main/resources/python-nextgen/setup.mustache, samples/client/echo_api/python-nextgen/pyproject.toml, samples/client/echo_api/python-nextgen/requirements.txt, samples/client/echo_api/python-nextgen/setup.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/pyproject.toml, samples/openapi3/client/petstore/python-nextgen-aiohttp/requirements.txt, samples/openapi3/client/petstore/python-nextgen-aiohttp/setup.py, samples/openapi3/client/petstore/python-nextgen/pyproject.toml, samples/openapi3/client/petstore/python-nextgen/requirements.txt, samples/openapi3/client/petstore/python-nextgen/setup.py
Align the lower limits between pyproject.toml and setup.py.
Set a common upper limit of <2, because version 2 brings breaking changes.
```
``` 
```
``` 
@spacether @krjakbrjak @wing328
=> [python-nextgen] Limit allowed pydantic version range

docs/plugins.md
@wing328 As promised in issue #15095, a PR to improve the documentation for Gradle 7+. 
```
``` 
```
``` 
=> Issue #15095: Improve gradle task documentation for gradle 7+

README.md
Add @lwj5 to go technical committee
```
``` 
```
``` 
=> Add @lwj5 to go technical committee

.github/workflows/samples-go.yaml, modules/openapi-generator/src/main/resources/go-server/routers.mustache, samples/server/petstore/go-chi-server/go/routers.go, samples/server/petstore/go-server-required/go/routers.go
=> [go-server] Fix: name declared and not used

modules/openapi-generator/src/main/resources/java-undertow-server/pom.mustache, samples/server/petstore/java-undertow/dependency-reduced-pom.xml, samples/server/petstore/java-undertow/pom.xml
Update undertow to newer version from 2.2.19.Final to 2.2.24.Final
```
``` 
```
``` 
FYI @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) …
=> [java] Update undertow to newer version

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java, modules/openapi-generator/src/test/resources/3_0/simplifyOneOfAnyOf_test.yaml
- Update schema in properties when it's refactored
- fix `nullable in processSimplifyOneOf, processSimplifyAnyOf
To fix https://github.com/matt7aylor#issuecomment-1503072363
```
``` 
``` …
```
=> Minor bug fixes in openapi normalizer

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/api.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/api.mustache
Fixes #15114.
No changes to samples because they don't use UUID, but I tested it locally by tweaking the sample spec.
```
``` 
```
``` 
ping @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala …
=> [java][jersey] Fix UUID path parameters (#15114)

modules/openapi-generator/src/main/resources/Java/libraries/native/anyof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/native/oneof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/native/pojo.mustache, modules/openapi-generator/src/main/resources/Java/pojo.mustache
@wing328 I think this fixes #15210, but I haven't verified.
Triple braces is needed to avoid escaping `<` and `>` for generic types.
```
``` 
```
``` 
ping @bbdouglas (2017/07) @sreeshas (2017/08) …
=> [java] Fix anyof generics (#15210)

.github/workflows/gradle-enterprise.yaml, .mvn/extensions.xml, .mvn/gradle-enterprise.xml
Add workflow for gradle enterprise
```
``` 
```
``` 
=> Add workflow for gradle enterprise

modules/openapi-generator/src/main/resources/python-legacy/configuration.mustache, modules/openapi-generator/src/main/resources/python-nextgen/configuration.mustache, modules/openapi-generator/src/main/resources/python/configuration.handlebars
=> rename hasBearerMethods to hasHttpBearerMethods

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java, modules/openapi-generator/src/main/resources/python-nextgen/__init__package.mustache, modules/openapi-generator/src/main/resources/python-nextgen/api_doc.mustache, modules/openapi-generator/src/main/resources/python-nextgen/api_doc_example.mustache, modules/openapi-generator/src/main/resources/python-nextgen/configuration.mustache, modules/openapi-generator/src/main/resources/python-nextgen/python_doc_auth_partial.mustache, samples/client/echo_api/python-nextgen/docs/BodyApi.md, samples/client/echo_api/python-nextgen/docs/FormApi.md, samples/client/echo_api/python-nextgen/docs/HeaderApi.md, samples/client/echo_api/python-nextgen/docs/PathApi.md, samples/client/echo_api/python-nextgen/docs/QueryApi.md, samples/client/echo_api/python-nextgen/openapi_client/__init__.py, samples/client/echo_api/python-nextgen/test/test_manual.py, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/AnotherFakeApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/DefaultApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/FakeClassnameTags123Api.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/PetApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/StoreApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/docs/UserApi.md, samples/openapi3/client/petstore/python-nextgen-aiohttp/petstore_api/__init__.py, samples/openapi3/client/petstore/python-nextgen/docs/AnotherFakeApi.md, samples/openapi3/client/petstore/python-nextgen/docs/DefaultApi.md, samples/openapi3/client/petstore/python-nextgen/docs/FakeApi.md, samples/openapi3/client/petstore/python-nextgen/docs/FakeClassnameTags123Api.md, samples/openapi3/client/petstore/python-nextgen/docs/PetApi.md, samples/openapi3/client/petstore/python-nextgen/docs/StoreApi.md, samples/openapi3/client/petstore/python-nextgen/docs/UserApi.md, samples/openapi3/client/petstore/python-nextgen/petstore_api/__init__.py
- import models
- remove blank lines
- fix http signing code sample
- fix signing import
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) …
=> [python-nextgen] better sample code

.mvn/extensions.xml, .mvn/gradle-enterprise.xml
- Update Gradle enterprise extension to 1.17
- update config (obfuscation, buildCache)
```
``` 
```
``` 
=> Update Gradle enterprise extension to 1.17, update config

modules/openapi-generator/src/main/resources/swift5/README.mustache, samples/client/petstore/swift5/alamofireLibrary/README.md, samples/client/petstore/swift5/anycodable/README.md, samples/client/petstore/swift5/asyncAwaitLibrary/README.md, samples/client/petstore/swift5/combineLibrary/README.md, samples/client/petstore/swift5/default/README.md, samples/client/petstore/swift5/deprecated/README.md, samples/client/petstore/swift5/frozenEnums/README.md, samples/client/petstore/swift5/nonPublicApi/README.md, samples/client/petstore/swift5/objcCompatible/README.md, samples/client/petstore/swift5/oneOf/README.md, samples/client/petstore/swift5/promisekitLibrary/README.md, samples/client/petstore/swift5/readonlyProperties/README.md, samples/client/petstore/swift5/resultLibrary/README.md, samples/client/petstore/swift5/rxswiftLibrary/README.md, samples/client/petstore/swift5/urlsessionLibrary/README.md, samples/client/petstore/swift5/validation/README.md, samples/client/petstore/swift5/vaporLibrary/README.md, samples/client/petstore/swift5/x-swift-hashable/README.md
* fix anchor tag because [its name attribute is now obsolete](https://www.w3.org/wiki/Elements/a#HTML_Attributes)
* add internal links
```
``` 
@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) …
=> [swift5] cleanup documentation

modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom_3.0.mustache, samples/client/petstore/java/microprofile-rest-client-3.0/pom.xml, samples/client/petstore/java/microprofile-rest-client-3.0/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/microprofile-rest-client-3.0/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/microprofile-rest-client-3.0/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/microprofile-rest-client/pom.xml, samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/UserApi.java
Reverts OpenAPITools/openapi-generator#15364
=> Revert "[Java] [Microprofile] Remove unused CXF dependency"

modules/openapi-generator/src/main/resources/python-nextgen/api.mustache, samples/client/echo_api/python-nextgen/openapi_client/api/query_api.py
=> [python-nextgen]: Fix date query params typo

pom.xml
Update surefire setting rerun tests (twice)
```
``` 
```
``` 
=> Update surefire setting rerun tests (twice)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/XojoClientCodegen.java
[xojo] Add copyright, remove unused import
```
``` 
```
``` 
cc @Topheee
=> [xojo] Add copyright, remove unused import

.github/workflows/samples-elm.yaml, samples/openapi3/client/elm/pom.xml, samples/openapi3/client/elm/src/Api.elm
- Update elm workflow to cover `samples/openapi3/client/elm`
- trigger a build failure to confirm the workflow is working as expected
```
``` 
```
``` 
FYI @eriktim, @Qluxzz
=> Update elm workflow to cover more tests

docs/generators/java.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/15416
```
``` 
```
``` 
=> [java][resttemplate] add option `generateClientAsBean`

modules/openapi-generator/src/main/resources/python-nextgen/github-workflow.mustache, samples/client/echo_api/python-nextgen/.github/workflows/python.yml, samples/openapi3/client/petstore/python-nextgen/.github/workflows/python.yml
```
``` 
```
``` 
cc @spacether @krjakbrjak
=> Add Python 3.11 to github-workflow.mustache

modules/openapi-generator/src/main/resources/dart/libraries/dio/README.mustache, modules/openapi-generator/src/main/resources/dart2/README.mustache, samples/openapi3/client/petstore/dart-dio/oneof/README.md, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/README.md, samples/openapi3/client/petstore/dart-dio/oneof_primitive/README.md, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/README.md, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/README.md, samples/openapi3/client/petstore/dart2/petstore_client_lib/README.md, samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/README.md
=> [dart] cleanup documentation

modules/openapi-generator/src/main/resources/python-nextgen/pyproject.mustache, samples/client/echo_api/python-nextgen/pyproject.toml, samples/openapi3/client/petstore/python-nextgen-aiohttp/pyproject.toml, samples/openapi3/client/petstore/python-nextgen/pyproject.toml
The url had the repo id & user id in the wrong order
```
``` 
```
``` 
cc @spacether @krjakbrjak @wing328
=> Fix repository url in pyproject.toml

bin/utils/test_file_list.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/Api/PetApiTests.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/FormatTest.cs
- fix back slash in regex
```
``` 
```
``` 
=> [csharp-netcore] fix back slash in regex

modules/openapi-generator/src/main/resources/r/README.mustache, samples/client/petstore/R-httr2-wrapper/README.md, samples/client/petstore/R-httr2/README.md, samples/client/petstore/R/README.md
=> [R] cleanup documentation

modules/openapi-generator/src/main/resources/C-libcurl/README.md.mustache, samples/client/petstore/c/README.md
```
``` 
@zhemant (2018/11) @ityuhui (2019/12) @michelealbano (2020/03)
=> [C] cleanup documentation

modules/openapi-generator/src/main/resources/apex/README_ant.mustache, modules/openapi-generator/src/main/resources/apex/README_sfdx.mustache, samples/client/petstore/apex/README.md
=> [apex] cleanup documentation

modules/openapi-generator/src/main/resources/ruby-client/README.mustache, samples/client/petstore/ruby-autoload/README.md, samples/client/petstore/ruby-faraday/README.md, samples/client/petstore/ruby/README.md, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/README.md, samples/openapi3/client/features/dynamic-servers/ruby/README.md, samples/openapi3/client/features/generate-alias-as-model/ruby-client/README.md
=> [Ruby] cleanup documentation

modules/openapi-generator/src/main/resources/Javascript-Apollo/README.mustache, modules/openapi-generator/src/main/resources/Javascript/README.mustache, samples/client/petstore/javascript-apollo/README.md, samples/client/petstore/javascript-es6/README.md, samples/client/petstore/javascript-promise-es6/README.md
=> [Javascript] cleanup documentation

modules/openapi-generator/src/main/resources/objc/README.mustache, samples/client/petstore/objc/core-data/README.md, samples/client/petstore/objc/default/README.md
=> [Objective-C objc] cleanup documentation

modules/openapi-generator/src/main/resources/go/README.mustache, samples/client/petstore/go/go-petstore/README.md, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/README.md, samples/openapi3/client/petstore/go/go-petstore/README.md
```
``` 
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)
=> [Go] cleanup documentation

modules/openapi-generator/src/main/resources/php-symfony/README.mustache, modules/openapi-generator/src/main/resources/php/README.mustache, samples/client/petstore/php/OpenAPIClient-php/README.md, samples/server/petstore/php-symfony/SymfonyBundle-php/README.md
=> [php] cleanup documentation

modules/openapi-generator/src/main/resources/perl/README.mustache, samples/client/petstore/perl/README.md
```
``` 
@wing328 (2017/07) [❤️](https://www.patreon.com/wing328) @yue9944882 (2019/06)
=> [Perl] cleanup documentation

modules/openapi-generator/src/main/resources/scala-akka-client/README.mustache, modules/openapi-generator/src/main/resources/scala-httpclient/README.mustache, modules/openapi-generator/src/main/resources/scala-sttp/README.mustache, samples/client/petstore/scala-akka/README.md, samples/client/petstore/scala-sttp/README.md
* fix anchor tag because [its name attribute is now obsolete](https://www.w3.org/wiki/Elements/a#HTML_Attributes)
* add internal links
```
``` 
@clasnake (2017/07), @jimschubert (2017/09) …
=> [Scala] cleanup documentation

modules/openapi-generator/src/main/resources/rust-server/README.mustache, samples/server/petstore/rust-server/output/multipart-v3/README.md, samples/server/petstore/rust-server/output/no-example-v3/README.md, samples/server/petstore/rust-server/output/openapi-v3/README.md, samples/server/petstore/rust-server/output/ops-v3/README.md, samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/README.md, samples/server/petstore/rust-server/output/ping-bearer-auth/README.md, samples/server/petstore/rust-server/output/rust-server-test/README.md
* add internal links
```
``` 
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10)
=> [Rust] cleanup documentation

modules/openapi-generator/src/main/resources/scala-sttp/build.sbt.mustache, samples/client/petstore/scala-sttp/build.sbt
Update scala versions to 2.13.10 and 2.12.17
```
``` 
```
``` 
=> Update scala versions to 2.13.10 and 2.12.17

modules/openapi-generator/src/main/resources/julia-client/README.mustache, samples/client/petstore/julia/README.md
* fix anchor tag because [its name attribute is now obsolete](https://www.w3.org/wiki/Elements/a#HTML_Attributes)
* add internal links
```
``` 
@mention @tanmaykm
=> [Julia] Cleanup README docs

modules/openapi-generator/src/main/resources/asciidoc-documentation/index.mustache
set toc level to 4 (accordingly to generated layout)
=> [asciidoc] Set toc level to 4 

modules/openapi-generator/src/main/resources/csharp-netcore/netcore_project.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/netcore_testproject.mustache, samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net48/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Org.OpenAPITools.csproj
=> [csharp-netcore] Updated package versions

docs/generators/dart-dio.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/dio/DartDioClientCodegenTest.java
Dart-Dio resets the metadata features in what I think is a typo.
```
``` 
=> [dart][dio] fix features of dart-dio generator

.github/workflows/windows.yaml
Add workflow to test builds and gradle plugin on Windows
```
``` 
```
``` 
=> Add workflow to test builds and Gradle plugin on Windows

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinClientCodegenModelTest.java
Fix for [issue 15583](https://github.com/OpenAPITools/openapi-generator/issues/15583)
=> [Kotlin] Fixed additional property omitGradleWrapper for kotlin generator

appveyor.yml
- use docker instead of mvn to run petstore
- remove project build and gradle test (now done in github workflow instead)
- remove installation of mvn, gradle (no longer needed)
- reduce build time by 50%
```
``` 
```
``` …
=> Improve Appveyor tests

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
Reverts OpenAPITools/openapi-generator#14126
=> Revert "Fix the bug that the property generateApis always true"

.github/workflows/linux.yaml, .github/workflows/windows.yaml
=> Set maven to 3.9 in Github workflow

modules/openapi-generator/src/main/resources/python/model_generic.mustache
Fixes #15622. This is a tiny fix, so I didn't update the sample spec files to cover this but tested locally. If you consider it's worth updating the spec, I can do that.
```
``` 
```
``` 
@spacether …
=> [python] Fix incorrect variable name for nullable fields with regex contraints

.github/workflows/samples-dotnet6-client.yaml, .github/workflows/samples-dotnet6-server.yaml, samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools.Test/Api/PetApiTests.cs, samples/server/petstore/aspnetcore-6.0/.openapi-generator-ignore
=> Add workflow to tests C# projects with .net 6

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Org.OpenAPITools.csproj
PR to add multiple `examples` to CogenenParameter which are, at the moment, not available during the code generation.
Fix #15645
```
``` 
```
``` 
=> Add multiple parameter examples to CodegenParameter

modules/openapi-generator/src/main/resources/go-server/Dockerfile.mustache, samples/server/petstore/go-api-server/Dockerfile, samples/server/petstore/go-chi-server/Dockerfile, samples/server/petstore/go-server-required/Dockerfile
Update Dockerfile go version to 1.19
Tested locally:
```sh
➜  go-api-server git:(go-docker) ✗ docker build . -t go-server
[+] Building 62.5s (14/14) FINISHED                                                                                                                                                                               
=> [internal] load build definition from Dockerfile                                                                                                                                                         0.0s
=> => transferring dockerfile: 344B                                                                                                                                                                         0.0s
=> [internal] load .dockerignore …
```
=> [go-server] Update Dockerfile go version to 1.19

.github/workflows/docker.yaml, run-in-docker.sh
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/15655
```
``` 
```
``` 
=> Add tests for Dockerfile, run-in-docker.sh

modules/openapi-generator/src/main/resources/csharp-netcore/netcore_project.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Org.OpenAPITools.csproj
Fixes this warning
No way to resolve conflict between "System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Web". Choosing "System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.
```
```  …
=> [csharp-netcore] Remove unneeded item groups from csproj

.github/actions/run-samples/action.yaml, .github/workflows/samples-dart.yaml, samples/openapi3/client/petstore/dart-dio/oneof/pom.xml
Update dart workflow java version to 11
```
``` 
```
``` 
cc @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela …
=> Update dart workflow java version to 11

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
fix minor bugs in string comparison
```
``` 
```
``` 
=> Fix bugs (string comparison) in csharp generators

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
Update python-fastapi server dependencies to newer version
cc @krjakbrjak
```
``` 
```
``` 
=> Update python-fastapi server dependencies

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
This change ensures that all CodegenProperty collections receive the same treatment. This does not change anything except make all the property collections the same.
```
``` 
```
``` 
=> [abstract-csharp] Patch all property collections

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
Removes a hotfix that is no longer needed.
```
``` 
```
``` 
=> [abstract-csharp] Removed hotfix

modules/openapi-generator/src/main/resources/go/README.mustache
closes #15704
```
``` 
```
``` 
=> Add go API key example in README.md

docs/new-generator.md
* fix anchor tag because [its name attribute is now obsolete](https://www.w3.org/wiki/Elements/a#HTML_Attributes)
* add missing authentication schemes from README of new generators
```
``` 
Core Team [@wing328](https://github.com/wing328) (2015/07) …
=> cleanup new generator documentation

.mvn/wrapper/maven-wrapper.properties
Set maven wrapper to v3.8.8 to make it consistent with the CI builds
```
``` 
```
``` 
=> Set maven wrapper to v3.8.8

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
Removing hotfixes that are no longer needed.
```
``` 
```
``` 
=> [csharp-netcore] Removed more hotfixes

docs/generators/powershell.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
Add BearerToken and SignatureAuth to Powershell client
Remove OAuth2_Implicit from Powershell client
See:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/powershell/api.mustache#L207-L212
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/powershell/http_signature_auth.mustache
- no occurrence of `{{#isOAuth}}` or `oauth` in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/powershell/ outside of api_doc.mustache and README.mustache
```
```  …
=> [Powershell] fix security features listed in documentation

docs/generators/r.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
Add BearerToken to R
See: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/r/api.mustache#L565-L570
```
``` 
=> [R] fix security features listed in documentation

.github/workflows/linux.yaml
Do not skip jacoco report in Linux workflow
```
``` 
```
``` 
=> Do not skip jacoco report in Linux workflow

README.md
=> [readme] minor fix

docs/generators/go.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
Add SignatureAuth to go
See: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/signing.mustache
```
``` 
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d …
=> [Go] fix security features listed in documentation

docs/generators/javascript-flowtyped.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptFlowtypedClientCodegen.java
Add BasicAuth, ApiKey, OAuth2_Implicit to javascript-flowtyped
See:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Javascript-Flowtyped/api.mustache#L102
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Javascript-Flowtyped/api.mustache#L120
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Javascript-Flowtyped/api.mustache#L126-L128
```
```  …
=> [JavaScript][javascript-flowtyped] fix security features listed in documentation

docs/generators/rust.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
Add BearerToken to Rust client
See:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache#L232-L236
```
``` 
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) …
=> [Rust] fix security features listed in documentation

docs/generators/kotlin-server.md, docs/generators/kotlin-spring.md, docs/generators/kotlin-vertx.md, docs/generators/kotlin.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
=> Add missing quote

bin/configs/python-fastapi.yaml, modules/openapi-generator/src/test/resources/3_0/python-fastapi/petstore.yaml, samples/server/petstore/python-fastapi/.openapi-generator/FILES, samples/server/petstore/python-fastapi/openapi.yaml, samples/server/petstore/python-fastapi/src/openapi_server/apis/fake_api.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/fake_api_base.py, samples/server/petstore/python-fastapi/src/openapi_server/main.py, samples/server/petstore/python-fastapi/tests/test_fake_api.py
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/15686
```
``` 
```
``` 
=> Add a test case for python-fastapi query parameter default value

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/api.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/DefaultApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/UserApi.cs
Uses the new lambda to improve spacing.
```
``` 
```
``` 
=> [csharp-netcore][generichost] Improved spacing

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/TrimTrailingWhiteSpaceLambda.java, modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/ApiTestsBase.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/IServiceCollectionExtensions.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/netcore_project.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools.Test/Api/ApiTestsBase.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Extensions/IServiceCollectionExtensions.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools.Test/Api/ApiTestsBase.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Extensions/IServiceCollectionExtensions.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools.Test/Api/ApiTestsBase.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Extensions/IServiceCollectionExtensions.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools.Test/Api/ApiTestsBase.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Extensions/IServiceCollectionExtensions.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools.Test/Api/ApiTestsBase.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Extensions/IServiceCollectionExtensions.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools.Test/Api/ApiTestsBase.cs, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Org.OpenAPITools.csproj
Adds new lambda to strip trailing whitespace. Removes multiple warnings. My .netstandard tests don't need System.Web so I reverted a recent change by changing ^net60OrLater to ^useGenericHost. That puts it back into other libraries, but it was only recently removed.
```
```  …
=> [csharp-netcore][generichost] Fixed more warnings and spacing issues

docs/generators/php-dt.md, docs/generators/php-slim-deprecated.md, docs/generators/php-slim4.md, docs/generators/php-symfony.md, docs/generators/php.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpDataTransferClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlim4ServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlimServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
Add BasicAuth, BearerAuth, OAuthImplicit, ApiKey to PHP, PHP-DT, PHP-DT-MODERN, PHP-SLIM, PHP-SLIM4
Add BasicAuth,  OAuthImplicit, ApiKey to PHP-SYMFONY
See:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php/api.mustache#L710-L737
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/php-dt/README.md?plain=1#L110-L119
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/php-dt-modern/README.md?plain=1#L110-L119
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-slim-server/SlimRouter.mustache#L72-L118
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/ …
=> [PHP] fix security features listed in documentation

docs/generators/csharp-netcore.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreReducedClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CsharpNetcoreFunctionsServerCodegen.java
Add BearerToken and SignatureAuth to csharp-netcore and BearerToken to csharp
See:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp/api.mustache#L309-L315
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp-dotnet2/ApiClient.mustache#L276-L278
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/BearerToken.mustache
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/HttpSigningToken.mustache
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-genera …
=> [C#] [csharp] [chsarp-netcore] fix security features listed in documentation

docs/generators/kotlin-spring.md, docs/generators/kotlin.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
For kotlin-client: set ApiKey, BasicAuth, BearerAuth, OAuthImplicit, OAuthAccessCode (retrofit2 only)
Kotlin-Spring supports all OAuth flows
See:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/infrastructure/ApiClient.kt.mustache#L41-L45
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/auth/OAuthFlow.kt.mustache
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-cloud/clientConfiguration.mustache#L23-L39
```
``` 
Commit …
=> [Kotlin] fix security features listed in documentation

docs/generators/python-fastapi.md, docs/generators/python-flask.md, docs/generators/python.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java
Remove OpenIDConnect from Python generator documentation
Remove OAuthApplication from python-fastapi
Remove all OAuth except OAuthImplicit from python-flask
See:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/configuration.mustache#L475-L529
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python-fastapi/security_api.mustache#L23-L58
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python-flask/security_controller_.mustache
```
```  …
=> [Python] fix security features listed in documentation

docs/generators/java-helidon-client.md, docs/generators/java-helidon-server.md, docs/generators/java-inflector.md, docs/generators/java-msf4j.md, docs/generators/java-pkmst.md, docs/generators/java-play-framework.md, docs/generators/java-undertow-server.md, docs/generators/java-vertx-web.md, docs/generators/java-vertx.md, docs/generators/java.md, docs/generators/jaxrs-cxf-cdi.md, docs/generators/jaxrs-cxf-client.md, docs/generators/jaxrs-cxf-extended.md, docs/generators/jaxrs-cxf.md, docs/generators/jaxrs-jersey.md, docs/generators/jaxrs-resteasy-eap.md, docs/generators/jaxrs-resteasy.md, docs/generators/jaxrs-spec.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
Remove OpenIDConnect from Java generators documentation, except for java-JAX-RS server (because library quarkus supports it (is there a way to document that it does not apply to other libraries?)).
Document that java-JAX-RS (for quarkus library) and java-client supports all OAuth flows
Add HttpSignatureAuth to java-client because libraries jersey2 and jersey3 support it (is there a way to document that it does not apply to other libraries?)
and also add a test confirming that there is http signature auth for Jersey Client.
See:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/auth/OAuthFlow.mustache java-client
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/li …
=> [Java] fix security features listed in documentation

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
as suggested in https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=OpenAPITools_openapi-generator&open=AYdncXE4x42g5MqgsWDo
FYI  @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)
```
```  …
=> [TS] Rename function to avoid confusion of function in parent class

pom.xml
Update rewrite to newer version
Fyi @OpenAPITools/generator-core-team 
```
``` 
```
``` 
=> Update maven-rewrite to newer version

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Minor refactoring on default codegen
```
``` 
```
``` 
=> Minor refactoring on default codegen

docs/generators/apex.md, docs/generators/cpp-tiny.md, docs/generators/cpp-ue4.md, docs/generators/fsharp-giraffe-server.md, docs/generators/javascript-apollo-deprecated.md, docs/generators/javascript-closure-angular.md, docs/generators/javascript.md, docs/generators/jetbrains-http-client.md, docs/generators/julia-client.md, docs/generators/julia-server.md, docs/generators/k6.md, docs/generators/markdown.md, docs/generators/n4js.md, docs/generators/plantuml.md, docs/generators/postman-collection.md, docs/generators/postman.md, docs/generators/swift5.md, docs/generators/wsdl-schema.md, docs/generators/xojo-client.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJuliaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AndroidClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
Only a handful of generators support OpenID Connect, and they list it explicitly in their feature set. Therefore these remain unchanged by the current PR.
```
``` 
=> fix security features listed in documentation - remove openID Connect included by default

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
Better null check in isExtensionParent
https://sonarcloud.io/project/issues?open=AYipbvke6EdZMb2-ww1a&id=OpenAPITools_openapi-generator`
```
``` 
```
``` 
=> Better null check in isExtensionParent method

.github/workflows/gradle-test.yaml, samples/client/petstore/java/webclient-swagger2/.openapi-generator-ignore
=> Add java-webclient gradle test

docs/generators/scala-sttp.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
Changed stability of Scala sttp client from beta to stable
```
``` 
```
``` 
=> Scala sttp stability change

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/dict_query_parameter.yaml
=> Add containerType to codegen parameter

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaHelidonCommonCodegen.java
Better way to initialise HashMap
to fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=OpenAPITools_openapi-generator&open=AYPgB9igBgR8ZyOmYIQk
```
``` 
```
``` 
=> [Java][Helidon] Better way to initialise HashMap

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenMediaType.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/content-data.yaml
Supersedes PR #15580 
This PR makes the (single) request example available during the code generation. Currently only examples are fetched and available.
```
``` 
```
``` 
=> Fetch request inline (single) example (bis)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
Fixes https://github.com/OpenAPITools/openapi-generator/issues/13709
```
``` 
```
``` 
=> [abstract-csharp] Removed circular composed schemas hotfix

modules/openapi-generator/src/main/resources/dart2/pubspec.mustache
updated intl package to v0.18.0 for dart 3.0 compatibility
=> updated intl package to v0.18.0 for dart 3.0 compatibility

README.md
Added Aleri Solutions to list of companies
=> Added Aleri Solutions to list of companies using the generator; see #4

.circleci/config.yml, .github/actions/run-samples/action.yaml, .github/workflows/docker.yaml, .github/workflows/gradle-plugin-tests.yaml, .github/workflows/linux.yaml, .github/workflows/maven-plugin-tests.yaml, .github/workflows/openapi-generator.yaml, .github/workflows/sonar.yml, .github/workflows/windows.yaml, .travis.yml, CI/circle_parallel.sh
=> use mvnw instead of mvn in workflow

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/FirstLambda.java, modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/README.client.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/netcore_project.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/README.md
Fixes https://github.com/OpenAPITools/openapi-generator/issues/15887
```
``` 
```
``` 
=> [csharp][generichost] Fixed wrong packages with .net6

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/auth/HttpBasicAuth.mustache, modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/auth/HttpBearerAuth.mustache, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java
These imports are unused; this PR removes them to provide less warnings in generated code.
```
``` 
```
``` 
=> Remove unused import in Java resttemplate auth templates

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
To fix https://github.com/OpenAPITools/openapi-generator/issues/15915
FYI @Ramanth (2019/07) @saigiridhar21 (2019/07)
<br class="Apple-interchange-newline">
```
``` 
```
``` 
=> Fix NPE in R construct example code

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/StringUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/markdown/MarkdownSampleGeneratorTest.java, modules/openapi-generator/src/test/resources/3_0/issue_15923.yaml
To fix https://github.com/OpenAPITools/openapi-generator/issues/15923
```
``` 
```
``` 
=> Fix NPE in StringUtils.camelize

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Remove addSchemaImportsFromV3SpecLocations as it's no longer used.
```
``` 
```
``` 
=> Remove addSchemaImportsFromV3SpecLocations

docs/generators/java.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
Add supportUrlQuery as an option
```
``` 
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) …
=> [java] Add supportUrlQuery as an option

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
Fixes https://github.com/OpenAPITools/openapi-generator/issues/15886
```
``` 
```
``` 
=> [csharp] Fixed support for DateTimeOffset

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
Fixes #15600
```
``` 
```
``` 
@lwj5 I would appreciate your review as member of the technical committee for Go. Thanks!
=> [go] fix StringIndexOutOfBoundsException while processing recursive model

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Remove getPropertyDefaultValue to simply the code and avoid any confusion
```
``` 
```
``` 
=> [default codegen] Remove getPropertyDefaultValue

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue_12929.yaml
To fix https://github.com/OpenAPITools/openapi-generator/issues/12929#issuecomment-1612907658
```
``` 
```
``` 
=> Add logic to avoid stackoverflow

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> 7.0.0-beta release

modules/openapi-generator-gradle-plugin/build.gradle, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle
Minor fix to gradle test, pom.xml, build.gradle
```
``` 
```
``` 
=> Minor fix to gradle test, pom.xml, build.gradle

.github/workflows/samples-spring-jdk17.yaml, .github/workflows/samples-spring.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java, samples/openapi3/client/petstore/spring-cloud-3-with-optional/.openapi-generator-ignore, samples/server/petstore/springboot/.openapi-generator-ignore
Fix Spring CI sample folder by removing `.yaml` from the path
(minor code format change in csharp client generator)
```
``` 
```
``` 
cc @cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) …
=> Fix Spring CI sample folder

modules/openapi-generator/src/main/resources/csharp/netcore_project.mustache, modules/openapi-generator/src/main/resources/csharp/netcore_testproject.mustache, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Org.OpenAPITools.csproj, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools.Test/Org.OpenAPITools.Test.csproj
=> [csharp][generichost] Version bump

.github/workflows/samples-dart.yaml, samples/openapi3/client/petstore/dart-dio/oneof/pom.xml, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/pom.xml, samples/openapi3/client/petstore/dart-dio/oneof_primitive/pom.xml, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/pom.xml, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/pom.xml
* cache maven dependencies
* use newest exec plugin
* execute pub via dart subcommand
```
``` 
```
``` 
=> [Dart] Update CI

docs/customization.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java, modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml
Add support for inline enum refactoring, which means inline enum schemas will be refactored separately and use $ref to reference them instead.
To close https://github.com/OpenAPITools/openapi-generator/issues/15972
To enable it, add `--inline-schema-name-defaults RESOLVE_INLINE_ENUMS=true` to CLI for example.
```
```  …
=> [inline model resolver] Add support for inline enum refactoring

modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/javascript/JavascriptClientCodegenTest.java, samples/client/echo_api/java/apache-httpclient/docs/QueryApi.md, samples/client/echo_api/java/native/docs/QueryApi.md, samples/client/echo_api/java/okhttp-gson/docs/QueryApi.md, samples/client/echo_api/python/docs/QueryApi.md, samples/client/echo_api/python/openapi_client/api/query_api.py, samples/openapi3/client/petstore/go/go-petstore/docs/FakeAPI.md
- Fix isMap for models.
- Update docs and tests
Will file another PR later to support free form object
```
``` 
```
``` 
=> [default codegen] Fix isMap

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-webclient/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-jvm-spring-2-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
```
``` 
```
``` 
@jimschubert (2017/09) [❤️](https://www.patreon.com/jimschubert), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m …
=> [kotlin][spring-webclient] Add parseDateToQueryString

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/HttpSigningConfiguration.mustache, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
Removed more warnings. Removed the regions also because they are generally frowned upon.
```
``` 
```
``` 
=> [csharp][generichost] Removed warnings in HTTP signing config

.github/workflows/samples-julia.yaml, bin/configs/julia-client-petstore-new.yaml, bin/configs/julia-server-petstore-new.yaml, samples/client/petstore/julia/src/PetStoreClient.jl, samples/server/petstore/julia/src/PetStoreServer.jl
Added Julia client and server tests to GitHub workflow
```
``` 
```
``` 
cc: @wing328
=> [Julia] add Julia tests to GitHub workflow

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCamelServerCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/javascript/JavascriptClientCodegenTest.java, samples/server/petstore/java-undertow/src/main/java/org/openapitools/handler/PathHandlerInterface.java
- Add isJson, isXml to consumes, produces
- add test
- refactor JavaCamel server generator (code cleanup)
```
``` 
```
``` 
=> Add isJson, isXml to consumes, produces

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, samples/client/others/csharp-complex-files/docs/MultipartApi.md, samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Api/MultipartApi.cs
This should give a speed increase to large specs.
```
``` 
```
``` 
=> [csharp] Faster logic to patch parameters

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJuliaCodegen.java
Minor code enhancement in Abstract Julia Codegen based on https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=OpenAPITools_openapi-generator&open=AYkxX6jmKEGI2CLjaePx&tab=why
```
``` 
```
```  …
=> Minor code enhancement in Abstract Julia Codegen

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/any_type.yaml
- Add support for isFreeFormObject flag
- Add tests
```
``` 
```
``` 
=> Add support for isFreeFormObject flag 

modules/openapi-generator/src/main/resources/csharp/HttpSigningConfiguration.mustache, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-unityWebRequest/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
based on https://github.com/OpenAPITools/openapi-generator/pull/16039 but for restsharp instead
```
``` 
```
``` …
=> [C#][restsharp] Removed warnings in HTTP signing config

modules/openapi-generator/src/main/resources/csharp/HttpSigningConfiguration.mustache, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-unityWebRequest/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
based on https://github.com/OpenAPITools/openapi-generator/pull/16040 but for C# restsharp
```
``` 
```
``` …
=> [C#][restsharp] Fixed bug in http signing config

modules/openapi-generator/src/main/resources/haskell-servant/README.mustache, samples/server/petstore/haskell-servant/README.md
Since `create{{title}}Client` is not a monadic action, e.g.
https://github.com/OpenAPITools/openapi-generator/blob/ddc2b3e56048ce3518d84e06fdd0198283c3b215/samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/API.hs#L238-L261
it's not possible to use `<-` like:
```haskell
OpenAPIPetstoreBackend{..} <- API.createOpenAPIPetstoreClient
```
We need to use `let` instead like:
```haskell
let OpenAPIPetstoreBackend{..} = API.createOpenAPIPetstoreClient
```
```
```  …
=> [haskell] fix exampe code in generated README.md

modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
The `+` should be encoded to `%2B`
Ref: https://stackoverflow.com/questions/5450190/how-to-encode-the-plus-symbol-in-a-url
Fix https://github.com/OpenAPITools/openapi-generator/issues/15538
```
``` 
```
``` 
Commit all …
=> fix(java): plus url encoding

modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
Reverts OpenAPITools/openapi-generator#15539
=> Revert "fix(java): plus url encoding"

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java, pom.xml
- remove static from logger
FYI @stcarrez (2018/02) @michelealbano (2018/02)
```
``` 
```
``` 
=> [Ada] remove static from logger

README.md, docs/customization.md
- Update README
-  customization.md
```
``` 
```
``` 
=> Update README, customization.md

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java
- to fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=OpenAPITools_openapi-generator&open=AYmNB_eSyVxu6ULEhfC2
```
``` 
```
``` 
cc @stcarrez (2018/02) @michelealbano (2018/02)
=> [Ada] Add null check to catch potential NPE

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
Previously, it was only checked for an exact equal string, which failed when there were additional options such as charset.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/16210
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala …
=> Support for multipart/form-data; charset="utf-8" in Java GSON Generator

samples/openapi3/client/petstore/python/tests/test_model.py
Add tests for circular refs issue in python client
A follow-up PR for #16199 
```
``` 
```
``` 
=> Add tests for circular refs issue in python client

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ZapierClientCodegen.java
Fix two bugs reported on [SonarCloud](https://sonarcloud.io/summary/new_code?id=OpenAPITools_openapi-generator&branch=master). Hopefully, with these fixes, the build status of the master branch will be green again.
```
``` 
=> fix 2 Sonar-reported bugs

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
According to the issue #12646 the values in enum that has a `name` field cannot be compiled, as a workaround for this, you can use the `enumPropertyNaming` property with a value of `PascalCase` to make it work, but the values in enums are not getting used if `PascalCase` or `UPPERCASE` gets configured for enums. Instead, the toString() of the enum is used which can bring wrong values.
@jimschubert, @dr4ke616, @karismann, @Zomzog, @andrewemery, @4brunu, @yutaka0m, @stefankoppier
```
``` 
You may …
=> Fix enum headers values while using Kotlin jvm-okhttp

.github/workflows/samples-haskell.yaml, bin/configs/haskell-servant.yaml, bin/configs/haskell-yesod.yaml, modules/openapi-generator/src/test/resources/3_0/haskell/petstore.yaml, samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/API.hs, samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/Types.hs, samples/server/petstore/haskell-yesod/src/OpenAPIPetstore/Types.hs
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/16289
```
``` 
```
``` 
=> Add tests, workflow for haskell samples

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java, modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml, samples/openapi3/client/petstore/python-aiohttp/README.md, samples/openapi3/client/petstore/python-aiohttp/docs/FakeApi.md, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python/README.md, samples/openapi3/client/petstore/python/docs/FakeApi.md, samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
fix data type
To fix https://github.com/OpenAPITools/openapi-generator/issues/16239
```
``` 
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco …
=> [python] Fix data type

samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/JSONTest.java
Add tests for array of number in Java okhttp-gson client
A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/16213
```
``` 
```
``` 
=> Add tests for array of number in Java okhttp-gson client

modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache, samples/client/petstore/swift5/anycodableLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift, samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift, samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
based on https://github.com/OpenAPITools/openapi-generator/pull/15140
credits: @aniruddhJo 
```
``` 
``` …
```
=> [swift] to support application/octet-stream for file upload

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpClientCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/protobuf/ProtobufSchemaCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/dollar-in-names-pull14359.yaml
based on https://github.com/OpenAPITools/openapi-generator/pull/14359
credits: @Joshix-1 
```
``` 
```
``` 
=> Fix removing dollar sign for name sanitization

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java, modules/openapi-generator/src/main/resources/typescript-rxjs/servers.mustache, samples/client/others/typescript-rxjs/allOf-composition/servers.ts, samples/client/petstore/typescript-rxjs/builds/default/servers.ts, samples/client/petstore/typescript-rxjs/builds/es6-target/servers.ts, samples/client/petstore/typescript-rxjs/builds/with-npm-version/servers.ts, samples/client/petstore/typescript-rxjs/builds/with-progress-subscriber/servers.ts
Minor enhancements to tyescript-rxjs client generator
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/9449/
```
``` 
```
``` 
=> Minor enhancements to tyescript-rxjs client generator

modules/openapi-generator/src/main/resources/go/client.mustache, samples/client/petstore/go/go-petstore/client.go, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go, samples/openapi3/client/petstore/go/go-petstore/client.go
based on https://github.com/OpenAPITools/openapi-generator/pull/15139/files
credits @aniruddhJo
to close #15131
```
``` 
```
``` 
=> [go] fix issue that tempfile is not deleted

modules/openapi-generator/src/main/resources/zapier/model.mustache, modules/openapi-generator/src/main/resources/zapier/utils.mustache, samples/client/petstore/zapier/models/Pet.js, samples/client/petstore/zapier/utils/utils.js
=> Zapier request fields fix

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpReducedClientCodegen.java
Moving the regex processing to the abstract. 
@mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)
```
``` 
```
``` 
=> [csharp] Moved regex processing to abstract

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/14239
```
``` 
```
``` 
=> Fix missing comma in Kotlin ApiClient

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache, modules/openapi-generator/src/test/resources/2_0/templates/Java/libraries/jersey2/ApiClient.mustache, samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
At the moment generators for jersey2 and 3 create an ApiClient which calls customizeClientBuilder before initializing the clientConfig with a default config, which result in overwriting the customization. 
If needed I'm happy to provide a poc to verify the code.
This resolves #16353 
Technical committee members for java: 
```
```  …
=> [BUG] [java][jersey2/3] clientBuilder gets overwritten after call to customizeClientBuilder

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/infrastructure/Bytes.kt.mustache, samples/client/petstore/kotlin-array-simple-string-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt, samples/client/petstore/kotlin-array-simple-string-multiplatform/src/main/kotlin/org/openapitools/client/infrastructure/Bytes.kt, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/src/main/kotlin/org/openapitools/client/infrastructure/Bytes.kt, samples/client/petstore/kotlin-default-values-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt, samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt
Fix implementation of `String.decodeBase64Bytes` extension function (issue #16366)
```
``` 
=> [BUG][kotlin-client][multiplatform] Write data to packet

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java
Add mapping features (property, parameter model names) to C++ generators (we've added these features to many other generators)
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)
```
``` 
``` …
```
=> Add mapping features to Abstract C++ Codegen

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaIsMatrixParameterTest.java, modules/openapi-generator/src/test/resources/3_1/matrix-path-params-spec.json
Fixes #16330 by adding a boolean variable  `isMatrix` to mustache parameter context. This allows custom template code like:
{{#isPathParam}}{{#isMatrix}}@MatrixParam{{/isMatrix}}{{^isMatrix}}@PathParam{{/isMatrix}}
```
``` 
``` …
```
=> allow check for path parameters in matrix style

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/IHttpClientBuilderExtensions.mustache, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Extensions/IHttpClientBuilderExtensions.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Extensions/IHttpClientBuilderExtensions.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-allOf/src/Org.OpenAPITools/Extensions/IHttpClientBuilderExtensions.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-anyOf/src/Org.OpenAPITools/Extensions/IHttpClientBuilderExtensions.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netcore-latest-oneOf/src/Org.OpenAPITools/Extensions/IHttpClientBuilderExtensions.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Extensions/IHttpClientBuilderExtensions.cs
Fixed a minor spelling issue with "circiut" (should be circuit). These changes only affect the XML comments.
```
``` 
```
``` 
=> Fixing spelling of circiut => circuit

bin/configs/julia-client-petstore-new.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJuliaCodegen.java, samples/client/petstore/julia/.openapi-generator/FILES, samples/client/petstore/julia/docs/MappedModel.md, samples/client/petstore/julia/src/models/model_MappedModel.jl
=> additional changes required for mapped names

README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> Prepare v7.0.0 release

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
resolve #16363
When a OpenAPI spec which uses a request parameter apikey, Kotlin client generator generates uncopilable code.
This PR fixes template in order to generate compilable code. 
```yaml
openapi: 3.0.1
info:
title: Apply Default Global SecurityScheme in springdoc-openapi
version: 1.0.0
servers:
- url: http://localhost:8080
description: Generated server url
security:
- apikey: [ ]
paths:
"/mailboxes":
get:
tags:
- mailbox-controller
operationId: listAll
responses:
'200':
description: OK
content:
"*/*":
schema:
type: object
properties:
objectId:
type: string
from:
type: string
subject:
type: string
components:
securitySchemes:
apikey:
type: apiKey
name: apikey
in: query
```
```
``` 
Commit all …
=> [Kotlin] Fix Kotlin client template

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java
Better handling of null pointer in CodegenSecurity
```
``` 
```
``` 
=> Better handling of null pointer in CodegenSecurity

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml, samples/client/petstore/java/okhttp-gson/README.md, samples/client/petstore/java/okhttp-gson/api/openapi.yaml, samples/client/petstore/java/okhttp-gson/docs/AnotherFakeApi.md, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- Fix cast exception in array default value (number)
To fix https://github.com/OpenAPITools/openapi-generator/issues/16426
```
``` 
```
``` 
FYI @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala …
=> [java] Fix cast exception in array default value (number)

docs/generators/java.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
Enumeration comparison in Java using equalsIgnoreCase when String
fix https://github.com/OpenAPITools/openapi-generator/issues/16385
Pretty much a duplicate of https://github.com/OpenAPITools/openapi-generator/pull/15273, except for Java generator
```
```  …
=> Fix Issue 16385

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java, modules/openapi-generator/src/test/resources/2_0/c/petstore.yaml, samples/client/petstore/c/docs/MappedModel.md, samples/client/petstore/c/model/mapped_model.c, samples/client/petstore/c/model/mapped_model.h
- Fix cast exception with UUID default value
- add tests
cc @zhemant (2018/11) @ityuhui (2019/12) @michelealbano (2020/03)
```
``` 
```
``` 
=> [C] Fix cast exception with UUID default value

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
Better null check in array default value
To fix https://github.com/OpenAPITools/openapi-generator/issues/9474
```
``` 
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov …
=> [java] Better null check in array default value

bin/configs/lua.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/LuaClientCodegen.java, samples/client/petstore/lua/petstore/model/user.lua
- https://github.com/OpenAPITools/openapi-generator/pull/new/lua-mapping-feature
- add tests
```
``` 
```
``` 
FYI @daurnimator (2017/08)
=> Add name mapping features to Lua client generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
- minor refactoring in the client generator
```
``` 
```
``` 
=> [Go] minor refactoring in the client generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/resources/python/api.mustache, samples/client/echo_api/python/openapi_client/api/auth_api.py, samples/client/echo_api/python/openapi_client/api/body_api.py, samples/client/echo_api/python/openapi_client/api/form_api.py, samples/client/echo_api/python/openapi_client/api/header_api.py, samples/client/echo_api/python/openapi_client/api/path_api.py, samples/client/echo_api/python/openapi_client/api/query_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_classname_tags123_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/user_api.py, samples/openapi3/client/petstore/python/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_classname_tags123_api.py, samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
import Annotated if needed
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @krjakbrjak (2023/02)
```
``` 
```
``` 
Commit all …
=> [python] import Annotated if needed

pom.xml
Update dependency `jackson-threetenbp` from `2.12.5` to `2.14.3`.
```
``` 
```
``` 
=> Update dependency "jackson-threetenbp" from "2.12.5" to "2.14.3"

docs/generators/groovy.md, docs/generators/java-camel.md, docs/generators/java-helidon-client.md, docs/generators/java-helidon-server.md, docs/generators/java-inflector.md, docs/generators/java-micronaut-client.md, docs/generators/java-micronaut-server.md, docs/generators/java-msf4j.md, docs/generators/java-pkmst.md, docs/generators/java-play-framework.md, docs/generators/java-undertow-server.md, docs/generators/java-vertx-web.md, docs/generators/java-vertx.md, docs/generators/java.md, docs/generators/jaxrs-cxf-cdi.md, docs/generators/jaxrs-cxf-client.md, docs/generators/jaxrs-cxf-extended.md, docs/generators/jaxrs-cxf.md, docs/generators/jaxrs-jersey.md, docs/generators/jaxrs-resteasy-eap.md, docs/generators/jaxrs-resteasy.md, docs/generators/jaxrs-spec.md, docs/generators/spring.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/16550
```
``` 
```
``` 
=> [java] remove option, update doc

modules/openapi-generator/src/main/resources/go-gin-server/go.mod.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/goginserver/GoGinServerCodegenTest.java, samples/server/petstore/go-gin-api-server/go.mod
to close https://github.com/OpenAPITools/openapi-generator/pull/16515
```
``` 
```
```  …
=> Update go gin to newer version

.github/PULL_REQUEST_TEMPLATE.md, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> 7.0.1 release

appveyor.yml
- add `-SkipPublisherCheck` in Appveyor CI to fix the build failure
```
``` 
=> [PowerShell] add -SkipPublisherCheck

.github/workflows/samples-dotnet6-client-echo-api.yaml, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools.Test/CustomTest.cs
=> Run tests for C# Echo API client in CI

modules/openapi-generator/src/main/resources/python/api.mustache, samples/client/echo_api/python/openapi_client/api/body_api.py, samples/client/echo_api/python/openapi_client/api/form_api.py, samples/client/echo_api/python/openapi_client/api/header_api.py, samples/client/echo_api/python/openapi_client/api/path_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/user_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
To fix https://github.com/OpenAPITools/openapi-generator/issues/16621
```
``` 
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @krjakbrjak …
=> [python] Fix required parameter check

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
```
``` 
```
``` 
Since the original issue(#15633) and PR(#15641)  don't seem to be progressing, I'm trying to work again to resolve the issue.
=> [typescript-axios]: handle explode query

docs/generators/jaxrs-jersey.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFExtServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJerseyServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaPKMSTServerCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSCXFExtServerCodegenTest.java
code clean up: remove supportJava6 option from code
```
``` 
FYI @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) …
=> [java] remove supportJava6 option from code

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/model/cat.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/model/dog.dart
**[Feature]** add the ability to generate apis and models in the specified folder from config.yaml
Closing [#14658](https://github.com/OpenAPITools/openapi-generator/issues/14658#issue-1578799075) 
```
``` 
```
``` 
Commit …
=> [Feature] add the ability to generate apis and models in the specified folder from config.yaml

modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/spring.xml
based on https://github.com/OpenAPITools/openapi-generator/pull/16719
to close https://github.com/OpenAPITools/openapi-generator/issues/16701
```
``` 
=> Update tests for maven plugins

.github/workflows/samples-java-client-jdk11.yaml, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/AWS4Auth.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache, samples/client/echo_api/java/okhttp-gson/pom.xml, samples/client/others/java/okhttp-gson-streaming/pom.xml, samples/client/petstore/java/okhttp-gson-3.1/pom.xml, samples/client/petstore/java/okhttp-gson-awsv4signature/build.gradle, samples/client/petstore/java/okhttp-gson-awsv4signature/build.sbt, samples/client/petstore/java/okhttp-gson-awsv4signature/pom.xml, samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/auth/AWS4Auth.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/pom.xml, samples/client/petstore/java/okhttp-gson-group-parameter/pom.xml, samples/client/petstore/java/okhttp-gson-nullable-required/pom.xml, samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml, samples/client/petstore/java/okhttp-gson-swagger1/pom.xml, samples/client/petstore/java/okhttp-gson-swagger2/pom.xml, samples/client/petstore/java/okhttp-gson/pom.xml
- fix AWS auth issue
- update aws auth JAR to latest stable release
```
```  …
=> [Java][okhttp-gson] fix AWS auth issue

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SwiftCombineClientCodegen.java
Bug fixes based on report: https://sonarcloud.io/summary/new_code?id=OpenAPITools_openapi-generator
```
``` 
=> Bug fixes based on report

.gitignore, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java, modules/openapi-generator/src/main/resources/php-nextgen/api.mustache, samples/client/petstore/php-nextgen/OpenAPIClient-php/phplint.dist.yml, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/PetApi.php, samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/StoreApi.php
- minor fix to return type (array): https://stackoverflow.com/a/40693938/677735
- add phplint yml config file
```
``` 
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), …
=> [php-nextgen] minor fix to return type

modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
The current log statement prints "%s", updating to properly include the parameter
```
``` 
=> Fix log statement

modules/openapi-generator/src/main/resources/csharp/HttpSigningConfiguration.mustache, samples/client/petstore/csharp/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net47/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net48/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient-unityWebRequest/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
The current method ```ecdsa.SignHash()``` used for signing using ECDSA key,  it returns the signature in ANS1 format and we have helper function ```ConvertToECDSAANS1Format()``` which convert ANS1 format to Der format.
We have observed that the function ```ConvertToECDSAANS1Format()``` returns invalid signature if we run it for more than 100 times.
To overcome this issue .NET5 has provided a method which can be used to generate signature for ecdsa key with DER format.
``` ecdsa.SignHash(dataToSign, DSASignatureFormat.Rfc3279DerSequence);```
I have tested with new method it works as expected without any failure.
This method gives valid signature always and authentication happens without any fail.  
``` …
```
=> [csharp] fix ecdsa signing issue.

samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/unnamed_dict_with_additional_model_list_properties.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/unnamed_dict_with_additional_string_list_properties.py, samples/openapi3/client/petstore/python/petstore_api/models/unnamed_dict_with_additional_model_list_properties.py, samples/openapi3/client/petstore/python/petstore_api/models/unnamed_dict_with_additional_string_list_properties.py
=> fix: Merge conflict from #16779 and #16777

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ZapierClientCodegen.java
- we already add these options to many other generator to allow users customize the property/parameter/model name
- minor code format enhancement
```
``` 
cc @emajo
=> Add mapping options to zapier client generator

samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools.Test/.editorconfig
Add rule to skip xUnit1031
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/16657 
```
``` 
=> [csharp] Add rule to skip xUnit1031

modules/openapi-generator/src/main/resources/python/api.mustache
=> [python] chore: Simplify async/non-async api method templates

modules/openapi-generator/src/main/resources/php-symfony/serialization/JmsSerializer.mustache, samples/server/petstore/php-symfony/SymfonyBundle-php/Service/JmsSerializer.php
```
``` 
Fixes #15950
Pinging PHP technical committee members - @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ybelenko, @renepardon
=> [PHP-Symfony] fix #15950: Add float to deserialize

modules/openapi-generator/src/main/resources/zapier/package.mustache, modules/openapi-generator/src/main/resources/zapier/utils.mustache, samples/client/petstore/zapier/package.json, samples/client/petstore/zapier/utils/utils.js
=> [zapier] Zapier generator minor fix

modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api.module.ts
=> fix(nestjs) fix import in api module template (16670)

modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache, modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache, samples/client/petstore/kotlin-array-simple-string-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-default-values-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-jvm-ktor-gson/build.gradle, samples/client/petstore/kotlin-jvm-ktor-jackson/build.gradle, samples/client/petstore/kotlin-jvm-ktor-kotlinx_serialization/build.gradle, samples/client/petstore/kotlin-multiplatform/build.gradle.kts
Update ktor-client lib from 2.1.3 to 2.2.3
Issue - https://github.com/OpenAPITools/openapi-generator/issues/16867
```
``` 
=> Update ktor client version  for custom plugin support

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-jvm-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-retrofit2-rx3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-retrofit2/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
=> [kotlin][client] Fix compilation error when all auth method is mapped to null

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ProcessUtils.java, modules/openapi-generator/src/main/resources/csharp/libraries/generichost/api.mustache
Fixes https://github.com/OpenAPITools/openapi-generator/issues/16825
```
``` 
=> Make security scheme comparison case insensitive

.github/workflows/samples-go-client-echo-api.yaml, modules/openapi-generator/src/main/resources/go/api.mustache, samples/client/echo_api/go/api_body.go, samples/client/petstore/go/go-petstore/api_fake.go, samples/client/petstore/go/go-petstore/api_pet.go, samples/openapi3/client/petstore/go/go-petstore/api_fake.go, samples/openapi3/client/petstore/go/go-petstore/api_pet.go
- Add Go Echo api client github workflow
- Add multiple file upload support (no compilation errors)
```
``` 
=> [Go] Add multiple file upload support

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
Better code format: default codegen, test, model utils
```
``` 
=> [Core] Better code format

modules/openapi-generator/src/main/resources/go/api.mustache, modules/openapi-generator/src/main/resources/go/model_simple.mustache
Use unescaped baseName to avoid any potential issue (no report of issue so far)
```
``` 
=> [go] Use unescaped baseName

modules/openapi-generator/src/main/resources/typescript-nestjs/package.mustache, samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/package.json, samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/package.json
Fixes #15492 
```
``` 
```
``` 
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx  @macjohnny  @topce  @akehir  @petejohansonxo @amakhrov  @davidgamero  @mkusaka
=> fix(typescript-nodejs): update package json dependencies

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/16986, no change in samples (expected)
```
```  …
=> openapi normalizer: minor refactoring in responses

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
Better null check in getSchemaFromResponse
A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/16986
```
```  …
=> Better null check in getSchemaFromResponse

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> 7.1.0 release

pom.xml
Update lombok dep to newer version v1.18.30
```
``` 
=> Update lombok dependency to newer version v1.18.30

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue-5676-enums.yaml
To fix https://github.com/OpenAPITools/openapi-generator/issues/17048
```
```  …
=> Retain deprecated in allOf schema handling

website/docusaurus.config.js
=> Update algoria settings in the website

modules/openapi-generator-cli/Dockerfile, modules/openapi-generator-online/Dockerfile
Reverts OpenAPITools/openapi-generator#17076
=> Revert "Use JDK17 images in Dockerfile"

.github/workflows/samples-jdk17.yaml, modules/openapi-generator/src/main/resources/Java/libraries/webclient/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache, samples/client/others/java/webclient-useAbstractionForFiles/build.gradle, samples/client/others/java/webclient-useAbstractionForFiles/pom.xml, samples/client/petstore/java/webclient-jakarta/build.gradle, samples/client/petstore/java/webclient-jakarta/pom.xml, samples/client/petstore/java/webclient-nullable-arrays/build.gradle, samples/client/petstore/java/webclient-nullable-arrays/pom.xml, samples/client/petstore/java/webclient-swagger2/build.gradle, samples/client/petstore/java/webclient-swagger2/pom.xml, samples/client/petstore/java/webclient/build.gradle, samples/client/petstore/java/webclient/pom.xml
Update webclient dep to newer version, add tests
```
``` 
@bbdouglas (2017/07) @sreeshas …
=> [java] Update webclient dependencies to newer version, add tests

modules/openapi-generator/src/main/resources/zapier/model.mustache, samples/client/petstore/zapier/models/Pet.js
to fix https://github.com/OpenAPITools/openapi-generator/issues/17093
```
``` 
=> [ZAPIER] added required fields to zapier models generation

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache, samples/client/petstore/kotlin-array-simple-string-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-default-values-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-multiplatform/build.gradle.kts
=> [kotlin-client][multiplatform] add iosSimulatorArm64 target

modules/openapi-generator/src/main/resources/dart/libraries/dio/analysis_options.mustache, samples/openapi3/client/petstore/dart-dio/oneof/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/oneof_primitive/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/analysis_options.yaml, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/analysis_options.yaml
Solves https://github.com/OpenAPITools/openapi-generator/issues/15908
@jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela
```
```  …
=> [BUG] [dart-dio] Support for Analyzer configuration options changes in Dart 3

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/17116
```
``` 
=> [php-nextgen] Fix comparison using equals

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
Trying to generate Kotlin code for cookieAuth will result in a malformed ApiClient.kt for function updateAuthParams. In this case the code block has too many closing brackets. This commit fixes this by adding the same tags around the closing brackets as for the opening ones.
```
```  …
=> [Kotlin] fix: ApiClient match tags of closing brackets with opening ones (#12976)

bin/configs/csharp-restsharp-net7.0.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/Order.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/OuterEnum.cs, samples/client/petstore/csharp/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/OuterEnumDefaultValue.cs
- add enum name mapping feature to c# client, server generators
- add a test
cc @mandrean (2017/08) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)
```
```  …
=> Add enum name mapping feature to C# generators

modules/openapi-generator/src/main/resources/rust-server/models.mustache, modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml, samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml, samples/server/petstore/rust-server/output/openapi-v3/docs/NullableTest.md, samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
Add tests for max,min items in array (rust-server)
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/17201
```
```  …
=> Add tests for max,min items in array (rust-server)

modules/openapi-generator/src/main/resources/Java/libraries/feign/pom.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom_3.0.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/server/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/libraries/jersey3/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/pom.mustache, modules/openapi-generator/src/main/resources/java-pkmst/pom.mustache, modules/openapi-generator/src/main/resources/java-undertow-server/pom.mustache, samples/client/echo_api/java/feign-gson/pom.xml, samples/client/petstore/java/feign-no-nullable/pom.xml, samples/client/petstore/java/feign/pom.xml, samples/client/petstore/java/microprofile-rest-client-3.0-jackson-with-xml/pom.xml, samples/client/petstore/java/microprofile-rest-client-3.0-jackson/pom.xml, samples/client/petstore/java/microprofile-rest-client-3.0/pom.xml, samples/client/petstore/java/microprofile-rest-client-with-useSingleRequestParameter/pom.xml, samples/client/petstore/java/microprofile-rest-client/pom.xml, samples/server/petstore/java-undertow/pom.xml, samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml, samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml, samples/server/petstore/jaxrs-cxf/pom.xml, samples/server/petstore/jaxrs-datelib-j8/pom.xml, samples/server/petstore/jaxrs-jersey/pom.xml, samples/server/petstore/jaxrs/jersey2-useTags/pom.xml, samples/server/petstore/jaxrs/jersey2/pom.xml, samples/server/petstore/jaxrs/jersey3/pom.xml
Update logback to newer versions 1.4.13
```
```  …
=> [java] Update logback to newer versions

modules/openapi-generator/src/main/resources/postman-collection/item.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, samples/schema/postman-collection/postman.json
The description of the headers is not displayed in Postman. This PR makes sure that the header description is included in the generated `postman.json`.
```
```  …
=> [POSTMAN] Include header description

bin/configs/dart-petstore-client-lib.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java, samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/model/order.dart
- Add enum mapping option
- Add tests
```
``` 
cc 
@jaumard (2018/09) @josh-burton (2019/12) …
=> [Dart] Add enum mapping option

bin/configs/ada.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java, modules/openapi-generator/src/test/resources/3_0/ada/petstore.yaml, samples/client/petstore/ada/src/model/samples-petstore-models.adb, samples/client/petstore/ada/src/model/samples-petstore-models.ads
- Add enum name mapping to Ada codegen
- Add tests
```
``` 
cc @stcarrez (2018/02) …
=> Add enum name mapping to Ada codegen

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
Check boolean value returned by createNewFile and throw errors if needed.
```
``` 
=> Check boolean value returned by createNewFile

modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/server/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/libraries/jersey3/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/pom.mustache, samples/client/petstore/java/microprofile-rest-client/pom.xml, samples/client/petstore/jaxrs-cxf-client-jackson/pom.xml, samples/client/petstore/jaxrs-cxf-client/pom.xml, samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml, samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml, samples/server/petstore/jaxrs-cxf/pom.xml, samples/server/petstore/jaxrs-datelib-j8/pom.xml, samples/server/petstore/jaxrs-jersey/pom.xml, samples/server/petstore/jaxrs/jersey2-useTags/pom.xml, samples/server/petstore/jaxrs/jersey2/pom.xml, samples/server/petstore/jaxrs/jersey3/pom.xml
=> Update logback core to newer version 1.4.14

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache, samples/client/petstore/kotlin-array-simple-string-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-default-values-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-multiplatform-kotlinx-datetime/build.gradle.kts, samples/client/petstore/kotlin-multiplatform/build.gradle.kts
=> [kotlin-client][multiplatform] use shortcut to access jsMain as well

samples/openapi3/client/petstore/python/tests/test_model.py
=> Add a test for SecretStr in the python client

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue_17376.json
to fix https://github.com/OpenAPITools/openapi-generator/issues/17376
```
``` 
FYI …
=> Fix NPE in codegen security

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache, samples/client/echo_api/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/resttemplate-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
=> Fix for handling error in resttemplate

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache, samples/client/echo_api/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/resttemplate-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
=> [java][resttemplate] replace deprecated response code function

.github/workflows/samples-postman.yaml, samples/schema/postman-collection/python/requirements.txt, samples/schema/postman-collection/python/setup.cfg, samples/schema/postman-collection/python/test-requirements.txt, samples/schema/postman-collection/python/test/test_info.py, samples/schema/postman-collection/python/test/test_parameters.py
Create GitHub workflow to verify the correctness of the generated Postman samples
```
```  …
=> [POSTMAN] Add Samples GitHub workflow

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
to close https://github.com/OpenAPITools/openapi-generator/issues/17433
```
``` 
=> Update wording in exception message (python abstract)

modules/openapi-generator-cli/pom.xml, modules/openapi-generator/pom.xml, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, pom.xml
update dependencies (logback, parser) to newer versions
```
``` 
=> Update dependencies to newer versions

modules/openapi-generator/src/main/resources/zapier/package.mustache, samples/client/petstore/zapier/package.json
=> [Zapier] Updated some dependencies

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java, modules/openapi-generator/src/main/resources/go-gin-server/controller-api.mustache, modules/openapi-generator/src/main/resources/go-gin-server/routers.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/goginserver/GoGinServerCodegenTest.java, samples/server/petstore/go-gin-api-server/go/api_pet.go, samples/server/petstore/go-gin-api-server/go/api_store.go, samples/server/petstore/go-gin-api-server/go/api_user.go
PR to add the missing web handlers when generating from an OpenAPI file that includes webhooks.
```
```  …
=> [GO Gin Server] Webhooks support: add missing webhook handlers

.mvn/extensions.xml, .mvn/gradle-enterprise.xml
- Updated remote build cache config to only push when authenticated -> if an unauthenticated push is attempted remote build cache will get turned off for the rest of the build. This can happen (does) on forked PR builds which run in an unsecure environment.
- Updated Gradle Enterprise (Develocity) plugins to get better integration with the Develocity server.
```
```  …
=> Update gradle enterprise setup

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.2.0 release

README.md
Just a super tiny fix to make GitHub render the :star: correctly
```
``` 
=> fix rendering of stars in README

README.md
Added Christopher Queen Consulting to list of companies using the generator
```
``` 
=> Added Christopher Queen Consulting to list of companies using the generator

modules/openapi-generator/src/main/resources/php/Configuration.mustache
BUG: in getHostString() : typo in variable usage : $hostsSettings instead of $hostSettings.
Generated PHP class had compilation errors.
=> BUG - PHP template - Configuration.mustache

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
=> fix typo in javadoc in RestTemplate/ApiClient

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
to fix https://github.com/OpenAPITools/openapi-generator/issues/17545
tested locally to confirm the fix.
```
```  …
=> Fix description in allOf with single item

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustAxumServerCodegen.java, modules/openapi-generator/src/main/resources/rust-axum/response.mustache, samples/server/petstore/rust-axum/output/multipart-v3/src/lib.rs, samples/server/petstore/rust-axum/output/multipart-v3/src/server/mod.rs, samples/server/petstore/rust-axum/output/openapi-v3/src/lib.rs, samples/server/petstore/rust-axum/output/openapi-v3/src/server/mod.rs, samples/server/petstore/rust-axum/output/ops-v3/src/lib.rs, samples/server/petstore/rust-axum/output/ops-v3/src/server/mod.rs, samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs, samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs, samples/server/petstore/rust-axum/output/petstore/src/lib.rs, samples/server/petstore/rust-axum/output/petstore/src/server/mod.rs, samples/server/petstore/rust-axum/output/ping-bearer-auth/src/lib.rs, samples/server/petstore/rust-axum/output/ping-bearer-auth/src/server/mod.rs, samples/server/petstore/rust-axum/output/rust-axum-test/src/lib.rs, samples/server/petstore/rust-axum/output/rust-axum-test/src/server/mod.rs
This PR remove redundant code in `rust-axum` generator. Also refactor `response` model to include status code.
Kindly ping @wing328 for quick review.
```
```  …
=> [Rust] [Axum] Remove redundant code in rust-axum generator

modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApi.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApi.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApi.kt
Only add tags fr Kotlin
@jimschubert (2017/09) [❤️](https://www.patreon.com/jimschubert), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)
=> Add tags on operation for template kotlin-spring

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustAxumServerCodegen.java, samples/server/petstore/rust-axum/output/multipart-v3/src/header.rs, samples/server/petstore/rust-axum/output/multipart-v3/src/lib.rs, samples/server/petstore/rust-axum/output/multipart-v3/src/models.rs, samples/server/petstore/rust-axum/output/multipart-v3/src/server/mod.rs, samples/server/petstore/rust-axum/output/openapi-v3/src/header.rs, samples/server/petstore/rust-axum/output/openapi-v3/src/lib.rs, samples/server/petstore/rust-axum/output/openapi-v3/src/models.rs, samples/server/petstore/rust-axum/output/openapi-v3/src/server/mod.rs, samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/header.rs, samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs, samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs, samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs, samples/server/petstore/rust-axum/output/petstore/src/header.rs, samples/server/petstore/rust-axum/output/petstore/src/lib.rs, samples/server/petstore/rust-axum/output/petstore/src/models.rs, samples/server/petstore/rust-axum/output/petstore/src/server/mod.rs, samples/server/petstore/rust-axum/output/ping-bearer-auth/src/header.rs, samples/server/petstore/rust-axum/output/ping-bearer-auth/src/lib.rs, samples/server/petstore/rust-axum/output/ping-bearer-auth/src/models.rs, samples/server/petstore/rust-axum/output/ping-bearer-auth/src/server/mod.rs, samples/server/petstore/rust-axum/output/rust-axum-test/src/header.rs, samples/server/petstore/rust-axum/output/rust-axum-test/src/lib.rs, samples/server/petstore/rust-axum/output/rust-axum-test/src/models.rs, samples/server/petstore/rust-axum/output/rust-axum-test/src/server/mod.rs
Since Rust Axum generator bases on `rust-server`, many code logic/blocks are duplicated. This PR tries to cleanup those duplicated codes.
```
```  …
=> [Rust] [Axum] Deduplicate code from rust-axum generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
Fix for https://github.com/OpenAPITools/openapi-generator/issues/17578
```
``` 
=> Fix flattenPath() in InlineModelResolver: use List instead of Map

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustAxumServerCodegen.java
=> Add copyright note to rust axum server codegen

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
Without this the generated code contains `{}` in the field name which is invalid.
Fixes #13166
Previously generated code:
```go
// IncidentData - struct for IncidentData
type IncidentData struct {
ArrayOfMapmapOfStringinterface{} *[]map[string]interface{}
MapmapOfStringinterface{} *map[string]interface{}
}
```
After
```go
// IncidentData - struct for IncidentData
type IncidentData struct {
ArrayOfMapmapOfStringAny *[]map[string]interface{}
MapmapOfStringAny *map[string]interface{}
}
```
Example input spec:
```json
{
"components": {
"schemas": {
"IncidentData": {
"oneOf": [
{
"items": {
"type": "object"
},
"type": "array"
},
{
"type": "object"
},
{
"type": "null"
}
],
"title": "Incident Data"
}
}
},
"info": {
"title": "Test",
"version": "0.1.0"
},
"openapi": "3.0.2",
"paths": {
"/": { …
```
=> Fix Go generation of `type: object` inside anyOf

modules/openapi-generator/pom.xml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java, modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/requesObject.mustache, samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/PetApi.kt, samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/StoreApi.kt, samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/UserApi.kt
Fix CI issue in PR `#17158`
```
``` 
@wing328
=> Able to generate within parameter #17158

modules/openapi-generator/src/main/resources/rust-axum/models.mustache, samples/server/petstore/rust-axum/output/openapi-v3/src/models.rs
This PR fixes clippy warning when comparing RawValue.
```
``` 
=> [Rust] [Axum] Fix clippy warning

modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/class.mustache
=> [dart-dio] includeIfNull: truefalse bugfix

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java, samples/client/petstore/perl/docs/FakeApi.md, samples/client/petstore/perl/lib/WWW/OpenAPIClient/FakeApi.pm, samples/client/petstore/perl/lib/WWW/OpenAPIClient/Object/TestInlineFreeformAdditionalPropertiesRequest.pm
to fix https://github.com/OpenAPITools/openapi-generator/issues/17650
@wing328 (2017/07) ❤️ @yue9944882 (2019/06)
```
```  …
=> Add any type support in Perl client generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Remove isAnyTypeSchema in default codegen as it's not used any where
```
```  …
=> Remove isAnyTypeSchema in default codegen

CI/circle_parallel.sh, samples/client/petstore/perl/pom.xml, samples/client/petstore/perl/test.bash
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/17668
```
``` 
=> Test perl petstore client in CircleCI

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
=> Fix typo in KotlinClientCodegen.java user-visible error message

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaHttp4sServerCodegen.java, pom.xml
various improvements, fix dockerfile build issue
```
``` 
FYI @clasnake (2017/07), @jimschubert …
=> Improvements on scala http4s server generator

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/enumOuterClass.mustache
When generating an enum class, the JsonProperty import appear to be missing with the latest openapi-generator code.
In that case, the generated code does not build.
```
``` 
```
``` 
@bbdouglas …
=> [jaxrs][cxf-cdi] make sure the imports are present for enum, if using jackson

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java, modules/openapi-generator/src/test/resources/3_0/schema.yaml, modules/openapi-generator/src/test/resources/3_0/simplifyOneOfAnyOf_test.yaml
to close https://github.com/OpenAPITools/openapi-generator/issues/17523
```
```  …
=> Fix null schema check for array of string in 3.1 spec

modules/openapi-generator/src/main/resources/Javascript/partial_model_generic.mustache
References #17767
If value was falsey, the validateJSON method was not working correctly.
=> [BUG][Javascript] - validateJSON not working on value 0

modules/openapi-generator/src/main/resources/cpp-qt-client/CMakeLists.txt.mustache, samples/client/petstore/cpp-qt/client/CMakeLists.txt
I put back find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core Network Gui) although I'm not sure it is needed.
```
```  …
=> [cpp-qt-client] Fix CMakeLists.txt.mustache and CMakeLists.txt for Qt5 (fix #17712)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQtAbstractCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQtClientCodegen.java
- signals (builtin Qt macro)
- slots (builtin Qt macro)
- NULL
- valid (generated classes has an isValid method)
- set (generated classes has an isSet method)
Fixes #17487
```
```  …
=> [cpp-qt-client] Extend the reserved keywords for Qt projects with the following words:

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> prepare 7.3.0-release

modules/openapi-generator/src/main/resources/php/libraries/psr-18/api.mustache, samples/client/petstore/php/psr-18/lib/Api/AnotherFakeApi.php, samples/client/petstore/php/psr-18/lib/Api/DefaultApi.php, samples/client/petstore/php/psr-18/lib/Api/FakeApi.php, samples/client/petstore/php/psr-18/lib/Api/FakeClassnameTags123Api.php, samples/client/petstore/php/psr-18/lib/Api/PetApi.php, samples/client/petstore/php/psr-18/lib/Api/StoreApi.php, samples/client/petstore/php/psr-18/lib/Api/UserApi.php
- `selectHeadersForMultipart()` does not exist,
- therefore we have to call `selectHeaders()`
This is signature of `public function selectHeaders(array $accept, string $contentType, bool $isMultipart): array;`
We have to pass `$multipart` as 3rd parameter.
The second parameter is content type as string, not in array.
```
```  …
=> fix(php): call selectHeaders correctly in psr-18 implementation

modules/openapi-generator/src/main/resources/python-fastapi/README.mustache
Adresses https://github.com/OpenAPITools/openapi-generator/issues/17819
```
```
=> Run the server using PYTHONPATH and correct module

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Add support for extension in request body to name body parameter using `x-codegen-request-body-name`
(so the same extension in both request body and operations work)
to close https://github.com/OpenAPITools/openapi-generator/issues/16647
test locally to confirm the fix
```diff
--- a/lib/Api/UsersApi.php
+++ b/lib/Api/UsersApi.php
@@ -125,32 +125,32 @@ class UsersApi
/**
* Operation createUser
*
-     * @param  \OpenAPI\Client\Model\CreateUserCommand $create_user_command create_user_command (required)
+     * @param  \OpenAPI\Client\Model\CreateUserCommand $command command (required)
* @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createUser'] to see the possible values for this operation
*
* @throws \OpenAPI\Client\ApiException on non-2xx …
```
=> Add support for extension in request body to name body parameter

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
Update python-fastapi dependencies to newer versions
```
``` 
@cbornet (2017/09) @tomplus …
=> Update python-fastapi dependencies to newer versions

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache, modules/openapi-generator/src/test/resources/3_0/java/native/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml, samples/client/petstore/java/native-async/README.md, samples/client/petstore/java/native-async/api/openapi.yaml, samples/client/petstore/java/native-async/docs/FakeApi.md, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/native/README.md, samples/client/petstore/java/native/api/openapi.yaml, samples/client/petstore/java/native/docs/FakeApi.md, samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
to close https://github.com/OpenAPITools/openapi-generator/issues/17864
```
``` 
=> Use unescaped media type in java native client

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml, samples/client/petstore/java/okhttp-gson/api/openapi.yaml, samples/client/petstore/java/okhttp-gson/docs/PetUsingAllOf.md, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/PetUsingAllOf.java
to fix https://github.com/OpenAPITools/openapi-generator/issues/17825
```
```  …
=> Fix multi line description in allOf

.mvn/gradle-enterprise.xml
Enable Develocity Local Build cache
```
``` 
=> Enable local build cache

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OperationWrapper.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/ParameterWrapper.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/SchemaWrapper.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/SecuritySchemeWrapper.java, modules/openapi-generator/src/test/resources/3_0/echo_api.yaml, modules/openapi-generator/src/test/resources/3_0/kotlin/echo_api.yaml, samples/client/petstore/csharp/OpenAPIClient-generichost-manual-tests/ManualTests.Latest.UseSourceGeneration/UnitTest1.cs, samples/client/petstore/csharp/OpenAPIClient-generichost-manual-tests/OpenAPIClient-generichost-manual-tests/UnitTest1.cs
=> Fix typos 'the the'.

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaHttp4sServerCodegen.java
=> Remove postprocess printing

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/KebabCaseLambda.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/mustache/KebabCaseLambdaTest.java
This PR introduces a new mustache lambda function "kebabcase". The lambda will accept any input and convert it to kebab case, the function will remove any special characters along the way.
I am working on generating docs with proper markdown links and needed kebab case for the links to work properly.
```
```  …
=> Add additional mustache lambda for kebab case

modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/Animal.cs, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/ApiResponse.cs, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/Cat.cs, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/Category.cs, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/Dog.cs, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/Order.cs, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/Pet.cs, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/Tag.cs, samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Models/User.cs
The already existing `nullableReferenceType`  added support for nullable parameters, but not for the fields inside of the models which was problematic.
With this simple change, the fields are now nullable as they should be.
```
```  …
=> [AspDotNet] Add nullable to model fields

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache, samples/client/echo_api/java/resttemplate/build.gradle, samples/client/echo_api/java/resttemplate/pom.xml, samples/client/others/java/resttemplate-useAbstractionForFiles/build.gradle, samples/client/others/java/resttemplate-useAbstractionForFiles/pom.xml, samples/client/petstore/java/resttemplate-jakarta/build.gradle, samples/client/petstore/java/resttemplate-jakarta/pom.xml, samples/client/petstore/java/resttemplate-swagger1/build.gradle, samples/client/petstore/java/resttemplate-swagger1/pom.xml, samples/client/petstore/java/resttemplate-swagger2/build.gradle, samples/client/petstore/java/resttemplate-swagger2/pom.xml, samples/client/petstore/java/resttemplate-withXml/build.gradle, samples/client/petstore/java/resttemplate-withXml/pom.xml, samples/client/petstore/java/resttemplate/build.gradle, samples/client/petstore/java/resttemplate/pom.xml
update spring-related dependencies to newer version.
cc 
```
```  …
=> [resttemplate] Update springweb to newer version

modules/openapi-generator/src/main/resources/Java/api.mustache, modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/api.mustache, modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache, modules/openapi-generator/src/main/resources/java-helidon/client/libraries/se/api.mustache, modules/openapi-generator/src/main/resources/java-helidon/client/libraries/se/api_impl.mustache, samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/api/QueryApi.java, samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/QueryApi.java, samples/client/petstore/java-helidon-client/se/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java-helidon-client/se/src/main/java/org/openapitools/client/api/FakeApiImpl.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
This PR resolves https://github.com/OpenAPITools/openapi-generator/issues/17960.
```
``` 
=> Update Java templates to correctly close parenthesis

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
Update orjson to newer version 
```
``` 
=> [python-fastapi] Update orjson to newer version

bin/configs/typescript-angular-v16-provided-in-root.yaml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java, samples/client/petstore/typescript-angular-v16-provided-in-root/builds/default/model/order.ts
add enum name mapping feature to the typescript client
add a test
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as …
=> Add enum name mapping feature to typescript generators 

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> prepare 7.4.0 release

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java, samples/schema/postman-collection/postman.json, samples/schema/postman-collection/python/test/test_endpoints.py
The Postman Generator generates Postman requests from examples defined as Components (using `href`).
This PR updates the generator to use inline examples (defined within the `requestBody`) when applicable.
```
``` 
IMPORTANT: Do …
=> [POSTMAN] Genarate Postman requests from inline examples

modules/openapi-generator/src/main/resources/dart/libraries/dio/auth/basic_auth.mustache, modules/openapi-generator/src/main/resources/dart/libraries/dio/auth/bearer_auth.mustache, samples/openapi3/client/petstore/dart-dio/oneof/lib/src/auth/basic_auth.dart, samples/openapi3/client/petstore/dart-dio/oneof/lib/src/auth/bearer_auth.dart, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/lib/src/auth/basic_auth.dart, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/lib/src/auth/bearer_auth.dart, samples/openapi3/client/petstore/dart-dio/oneof_primitive/lib/src/auth/basic_auth.dart, samples/openapi3/client/petstore/dart-dio/oneof_primitive/lib/src/auth/bearer_auth.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/auth/basic_auth.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/auth/bearer_auth.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/auth/basic_auth.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/auth/bearer_auth.dart
Solves https://github.com/OpenAPITools/openapi-generator/issues/17073
@agilob @jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela 
```
```  …
=> [dart] fix: Bearer and Basic auth interceptors case-insensitive scheme comparison (17073)

modules/openapi-generator/src/main/resources/go-gin-server/go.mod.mustache, samples/server/petstore/go-gin-api-server-interface-only/go.mod, samples/server/petstore/go-gin-api-server/go.mod
=> Update protobuf to newer version (go gin)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SwiftCombineClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/model/ModelMap.java
- create a static function to build map of codegen model 
- minor refactoring in C# abstract codegen to use map of codegen model instead of going through list of model maps every time.
```
```  …
=> [Refactor] create a static function to build map of codegen model

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/clientPropertiesConfiguration.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/issue_18090.yaml
based on https://github.com/OpenAPITools/openapi-generator/pull/18091 with a fix to the test
to fix #18090
```
```  …
=> Insert missing quote in clientPropertiesConfiguration.mustache for the Spring generator 

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
=> Skip check for possible model type in Abstract C#

modules/openapi-generator/src/main/resources/scala-sttp4/jsonSupport.mustache, samples/client/petstore/scala-sttp4/src/main/scala/org/openapitools/client/core/JsonSupport.scala
=> scala-sttp4: fix for missing EnumNameSerializer for inner enum definitions

README.md, docs/integration.md
=> update links to blog posts

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
=> Allow generatorVersion to be overwritten in additional properties

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGraphQLCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ClojureClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GraphQLNodeJSExpressServerCodegen.java
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/18201
```
``` 
=> Better type check for additional properties before casting

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache, samples/client/echo_api/java/okhttp-gson/build.gradle, samples/client/echo_api/java/okhttp-gson/build.sbt, samples/client/others/java/okhttp-gson-oneOf/build.gradle, samples/client/others/java/okhttp-gson-oneOf/build.sbt, samples/client/others/java/okhttp-gson-streaming/build.gradle, samples/client/others/java/okhttp-gson-streaming/build.sbt, samples/client/petstore/java/okhttp-gson-3.1/build.gradle, samples/client/petstore/java/okhttp-gson-3.1/build.sbt, samples/client/petstore/java/okhttp-gson-awsv4signature/build.gradle, samples/client/petstore/java/okhttp-gson-awsv4signature/build.sbt, samples/client/petstore/java/okhttp-gson-dynamicOperations/build.gradle, samples/client/petstore/java/okhttp-gson-dynamicOperations/build.sbt, samples/client/petstore/java/okhttp-gson-group-parameter/build.gradle, samples/client/petstore/java/okhttp-gson-group-parameter/build.sbt, samples/client/petstore/java/okhttp-gson-nullable-required/build.gradle, samples/client/petstore/java/okhttp-gson-nullable-required/build.sbt, samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle, samples/client/petstore/java/okhttp-gson-parcelableModel/build.sbt, samples/client/petstore/java/okhttp-gson-swagger1/build.gradle, samples/client/petstore/java/okhttp-gson-swagger1/build.sbt, samples/client/petstore/java/okhttp-gson-swagger2/build.gradle, samples/client/petstore/java/okhttp-gson-swagger2/build.sbt, samples/client/petstore/java/okhttp-gson/build.gradle, samples/client/petstore/java/okhttp-gson/build.sbt
=> [Java] Update okhttp3 from 4.10.0 to 4.12.0 to fix CVE-2023-3635

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache, samples/client/echo_api/java/resttemplate/build.gradle, samples/client/echo_api/java/resttemplate/pom.xml, samples/client/others/java/resttemplate-useAbstractionForFiles/build.gradle, samples/client/others/java/resttemplate-useAbstractionForFiles/pom.xml, samples/client/petstore/java/resttemplate-jakarta/build.gradle, samples/client/petstore/java/resttemplate-jakarta/pom.xml, samples/client/petstore/java/resttemplate-swagger1/build.gradle, samples/client/petstore/java/resttemplate-swagger1/pom.xml, samples/client/petstore/java/resttemplate-swagger2/build.gradle, samples/client/petstore/java/resttemplate-swagger2/pom.xml, samples/client/petstore/java/resttemplate-withXml/build.gradle, samples/client/petstore/java/resttemplate-withXml/pom.xml, samples/client/petstore/java/resttemplate/build.gradle, samples/client/petstore/java/resttemplate/pom.xml
Update spring-context and spring-web to newer version 
```
``` 
@bbdouglas (2017/07) @sreeshas …
=> Update spring-context and spring-web to newer version

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/ClientUtils.mustache, modules/openapi-generator/src/main/resources/csharp/libraries/generichost/api.mustache, samples/client/petstore/csharp/generichost/net8/AllOf/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/AnyOf/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/AnyOfNoCompare/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/FormModels/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp/generichost/net8/FormModels/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/generichost/net8/FormModels/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/OneOf/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/Petstore/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp/generichost/net8/Petstore/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/generichost/net8/Petstore/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/UseDateTimeForDate/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/standard2.0/Petstore/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp/generichost/standard2.0/Petstore/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp/generichost/standard2.0/Petstore/src/Org.OpenAPITools/Api/UserApi.cs
We can't just ToString a parameter. If it is an enum, the json value might be different than what ToString can return. 
closes https://github.com/OpenAPITools/openapi-generator/pull/15974
```
```  …
=> [csharp][generichost] Fixed operation parameter handling

modules/openapi-generator/src/test/resources/3_0/postman-collection/SampleProject.yaml, samples/schema/postman-collection/postman.json, samples/schema/postman-collection/python/test/test_endpoints.py
PR to add a test for the CI pipeline to cover PR #18294
```
``` 
@wing328
=> [POSTMAN] Add test for CI suite

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java, modules/openapi-generator/src/test/resources/3_1/schema.yaml
- Fix object and complex composed schema check
- Add tests
```
```  …
=> Fix object and complex composed schema check

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
to close https://github.com/OpenAPITools/openapi-generator/pull/18368
```
``` 
=> Update idna to newer version (fastapi)

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
to close https://github.com/OpenAPITools/openapi-generator/pull/18374
```
``` 
=> Update dnspython to a newer version

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.5.0 release

README.md
Hi! I recently gave a presentation at a tech conference on how to effectively use OpenAPI Generator with Laravel.
The talk was delivered in Japanese and lasted about 40 minutes, where I shared detailed insights and practical examples. I believe this content could be a valuable resource for the community. Would it be alright to add a link to this talk's video and related materials in the repository's documentation section?
```
```  …
=> README: Add a link to the tech conference talk

modules/openapi-generator/src/main/resources/go-gin-server/go.mod.mustache, samples/server/petstore/go-gin-api-server-interface-only/go.mod, samples/server/petstore/go-gin-api-server/go.mod
to close https://github.com/OpenAPITools/openapi-generator/pull/18435
```
``` 
=> Update x/net to newer version in Go generators

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/resources/csharp/libraries/generichost/JsonConverter.mustache, samples/client/petstore/csharp/generichost/net8/FormModels/src/Org.OpenAPITools/Model/PolymorphicProperty.cs, samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/Model/PolymorphicProperty.cs, samples/client/petstore/csharp/generichost/net8/Petstore/src/Org.OpenAPITools/Model/PolymorphicProperty.cs, samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/Model/PolymorphicProperty.cs, samples/client/petstore/csharp/generichost/standard2.0/Petstore/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
=> [csharp] Fixed nullability of composed schemas

docs/generators/kotlin.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java, modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache
Fixes #18439.
- Fix the template to use `modelPackage`
- Fix a typo in the template
To verify:
```bash
rm -rf example \
&& java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g kotlin \
-i https://docs.gradle.com/enterprise/api-manual/ref/develocity-2024.1-api.yaml \
-p library=jvm-retrofit2 \
-p packageName=com.example \
-p modelPackage=com.example.model \
-o example \
&& sh example/gradlew -p example compileKotlin
```
- After changes: `BUILD SUCCESSFUL` ✅ 
- Before changes: `BUILD FAILED` ❌ 
```
e: file:///Users/gabrielfeo2/projects/openapi-generator/example/src/main/kotlin/com/example/apis/BuildsApi.kt:25:20 Unresolved reference: models
...
```
``` …
```
=> [kotlin] Fix model imports when using exploded query params

modules/openapi-generator/src/main/resources/typescript-axios/common.mustache, samples/client/echo_api/typescript-axios/build/common.ts, samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/common.ts, samples/client/petstore/typescript-axios/builds/composed-schemas/common.ts, samples/client/petstore/typescript-axios/builds/default/common.ts, samples/client/petstore/typescript-axios/builds/es6-target/common.ts, samples/client/petstore/typescript-axios/builds/test-petstore/common.ts, samples/client/petstore/typescript-axios/builds/with-complex-headers/common.ts, samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/common.ts, samples/client/petstore/typescript-axios/builds/with-interfaces/common.ts, samples/client/petstore/typescript-axios/builds/with-node-imports/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/common.ts, samples/client/petstore/typescript-axios/builds/with-npm-version/common.ts, samples/client/petstore/typescript-axios/builds/with-single-request-parameters/common.ts, samples/client/petstore/typescript-axios/builds/with-string-enums/common.ts
Reverts OpenAPITools/openapi-generator#17790
=> Revert "Fix: Always serialise Map and Set to object and array in typescript-axios"

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java, modules/openapi-generator/src/main/resources/rust/Cargo.mustache, modules/openapi-generator/src/main/resources/rust/model.mustache, modules/openapi-generator/src/test/resources/3_0/rust/petstore.yaml, samples/client/petstore/rust/hyper/petstore/Cargo.toml, samples/client/petstore/rust/hyper/petstore/docs/TypeTesting.md, samples/client/petstore/rust/hyper/petstore/src/models/type_testing.rs, samples/client/petstore/rust/reqwest/petstore-async-middleware/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-async-middleware/docs/TypeTesting.md, samples/client/petstore/rust/reqwest/petstore-async-middleware/src/models/type_testing.rs, samples/client/petstore/rust/reqwest/petstore-async/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-async/docs/TypeTesting.md, samples/client/petstore/rust/reqwest/petstore-async/src/models/type_testing.rs, samples/client/petstore/rust/reqwest/petstore-avoid-box/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-avoid-box/docs/TypeTesting.md, samples/client/petstore/rust/reqwest/petstore-avoid-box/src/models/type_testing.rs, samples/client/petstore/rust/reqwest/petstore-awsv4signature/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-awsv4signature/docs/TypeTesting.md, samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/models/type_testing.rs, samples/client/petstore/rust/reqwest/petstore/Cargo.toml, samples/client/petstore/rust/reqwest/petstore/docs/TypeTesting.md, samples/client/petstore/rust/reqwest/petstore/src/models/type_testing.rs
This PR adds support for base64-encoded binary data (type:string, format: byte) for Rust.
```
```  …
=> [Rust] Add support for base64-encoded byte arrays

docs/generators/java.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
=> (java client) minor code enhancements

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
fixes https://github.com/OpenAPITools/openapi-generator/issues/10718
The file type passed to `postProcessFile` by DefaultCodegen used to be `supporting-mustache` and `supporting-common` earlier. This has been changed to `supporting-file` in https://github.com/OpenAPITools/openapi-generator/pull/6357 and https://github.com/OpenAPITools/openapi-generator/pull/7366.
AbstractGoCodegen was never updated to match this change, and accepts only `supporting-mustache`. This PR changes it to accept `supporting-file` instead. 
```
```  …
=> [GO] fix post process file type

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/18519
```
``` 
=> Clean up supporting-mustache

bin/configs/java-jersey2-special-characters.yaml, docs/generators/php.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpClientCodegen.java, samples/documentation/html2/index.html
=> [PHP] Update php.md - marked Multiserver as true 

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
to close https://github.com/OpenAPITools/openapi-generator/pull/18583
```
``` 
=> Update python-fastapi dependencies

modules/openapi-generator-gradle-plugin/build.gradle
=> [gradle plug-in] update jvm target

modules/openapi-generator-gradle-plugin/build.gradle
=> Update java version in build.gradle

modules/openapi-generator-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
=> downgrade gradle to 7.6.4

modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache, modules/openapi-generator/src/main/resources/htmlDocs2/js_jsonschemaview.mustache
fix #13313
The oneOf was not supported because of typo.
Also, I added the null check for schema.properties because oneOf doesn't have properties.
Use minimal reproducable spec of https://github.com/OpenAPITools/openapi-generator/issues/13313 ([here](https://gist.github.com/pbarnes-tibco/fc6320658db878262a1adc3696ea06ec))
```
```  …
=> [html2] Add oneOf support.

modules/openapi-generator/src/test/resources/3_0/jaxrs-spec/petstore-with-fake-endpoints-models-for-testing.yaml, samples/server/petstore/jaxrs-spec/.openapi-generator/FILES, samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/FakeApi.java, samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/FakeTestsDefaultsDefaultResponse.java, samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/IntegerEnum.java, samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/StringEnum.java, samples/server/petstore/jaxrs-spec/src/main/openapi/openapi.yaml
a follow up PR to https://github.com/OpenAPITools/openapi-generator/issues/18451
```
``` 
=> Add tests for @Valid (enum)

modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache, samples/client/echo_api/ruby-faraday/lib/openapi_client/api_client.rb, samples/client/echo_api/ruby-httpx/lib/openapi_client/api_client.rb, samples/client/echo_api/ruby-typhoeus/lib/openapi_client/api_client.rb, samples/client/petstore/ruby-autoload/lib/petstore/api_client.rb, samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb, samples/client/petstore/ruby-httpx/lib/petstore/api_client.rb, samples/client/petstore/ruby/lib/petstore/api_client.rb, samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_client.rb, samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_client.rb, samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb
```
``` 
@cliffano @zlx @autopp
[issue …
=> Ruby: Fixed CodeQL polynomial regexp

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> 7.6.0 release

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
to close https://github.com/OpenAPITools/openapi-generator/pull/18721
```
``` 
=> update requests in python-fastapi to newer version

.github/PULL_REQUEST_TEMPLATE.md
=> Update PR template with latest minor version reference

modules/openapi-generator/src/main/resources/csharp/netcore_project.mustache
https://github.com/dotnet/sdk/issues/40445
```
``` 
=> Fix build issue when using dotnet 8.0.300

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
=> tiny simplification of typescript-nestjs api.service.mustache

.github/workflows/samples-kotlin-server-jdk17.yaml, modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradle-sb3-Kts.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradleKts.mustache, samples/server/petstore/kotlin-springboot-request-cookie/build.gradle.kts, samples/server/petstore/kotlin-springboot-request/build.gradle.kts
=> [kotlin-spring] Fix gradle build failure when generated with interfaceOnly=true 

CI/circle_parallel.sh
=> Add tests for Cpprestsdk client in CircleCI

.github/workflows/samples-dotnet-fx.yaml
=> [csharp] Fixed .net framework workflow

modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradle-sb3-Kts.mustache, samples/server/petstore/kotlin-springboot-request-cookie/build.gradle.kts, samples/server/petstore/kotlin-springboot-request/build.gradle.kts
Closes #14949
Currently the CI jobs for all my other PRs are failing b/c i activated testing of the kotlin-springboot-request-cookie as part of #18809 (one would assume that should teach me to stay strictly in scope in my PRs :see_no_evil:).
I'm a bit concerned why that did not come up in that PRs CI runs… we should investigate. However, on the positive side it made me get around to fix #14949.
```
```  …
=> [kotlin-spring] Generated code using Schema with discriminator mapping will not compile

docs/generators/python-fastapi.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/AllGeneratorsTest.java
=> [python-fastapi] Fix CLI crash when calling `config-help` & update docs

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ClojureClientCodegen.java
=> [clojure] Apply model/param/var name mappings (#18665)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ErlangClientCodegen.java
Fixes #18662
@tsloughter @jfacorro @robertoaloi
=> [erlang-client] Apply var/param name mappings (#18662)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
Fixes #18663
@sbu-WBT @kuhnroyal @agilob @ahmednfwela
=> [dart] Apply var/param/model name mappings, handle single _ (#18663)

modules/openapi-generator/pom.xml
Avoid leaking `slf4j-simple` as a dependency to openapi-generator consumers.
Fixes: #14113
```
```  …
=> build: use runtime scope for slf4j-simple log sink

website/src/dynamic/sponsors.yml, website/src/dynamic/users.yml
I would like to suggest using the deeplink at https://opensource.muenchen.de/software/openapi-generator.html.
```
```  …
=> muenchen deeplink

modules/openapi-generator/src/main/resources/csharp/modelAnyOf.mustache, samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Model/GmFruit.cs, samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Model/MixedAnyOfContent.cs, samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Model/GmFruit.cs, samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Model/MixedAnyOfContent.cs, samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Model/GmFruit.cs, samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Model/MixedAnyOfContent.cs, samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/GmFruit.cs, samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/MixedAnyOfContent.cs, samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/GmFruit.cs, samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/MixedAnyOfContent.cs, samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Model/GmFruit.cs, samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Model/MixedAnyOfContent.cs, samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Model/GmFruit.cs, samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Model/MixedAnyOfContent.cs, samples/client/petstore/csharp/unityWebRequest/standard2.0/Petstore/src/Org.OpenAPITools/Model/GmFruit.cs, samples/client/petstore/csharp/unityWebRequest/standard2.0/Petstore/src/Org.OpenAPITools/Model/MixedAnyOfContent.cs
Refactor anyOf model template by removing "this."
Note:
As requested by @wing328 
```
```  …
=> [csharp] Refactor anyOf model template

modules/openapi-generator/src/main/resources/zapier/api.mustache, modules/openapi-generator/src/main/resources/zapier/utils.mustache, samples/client/petstore/zapier/apis/PetApi.js, samples/client/petstore/zapier/apis/StoreApi.js, samples/client/petstore/zapier/apis/UserApi.js, samples/client/petstore/zapier/utils/utils.js
based on https://github.com/OpenAPITools/openapi-generator/pull/18848 with updated samples
```
```  …
=> Marketplace software zapier request middleware

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/enumClass.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/spec/enumOuterClass.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSSpecServerCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/issue_13444.yaml
Fix #13444
based on https://github.com/OpenAPITools/openapi-generator/pull/13592
```
``` 
=> [Java][jaxrs-spec] enumUnknownDefaultCase true now returns correctly in fromValue

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpClientDeepObjectTest.java, samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/net6/ParameterMappings/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/net7/UseDateTimeForDate/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs, samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
Improved apiclient.mustache to keep it dry, sharing a single exec with Action<> delegate.
```
```  …
=> [csharp] Improved apiclient.mustache 

samples/server/petstore/rust-axum/output/openapi-v3/src/server/mod.rs, samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs, samples/server/petstore/rust-axum/output/petstore/src/server/mod.rs, samples/server/petstore/rust-axum/pom.xml
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/18895
```
``` 
=> update rust axum samples, add cargo fmt

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
[python-fastapi] Update urllib3 to newer version
To close https://github.com/OpenAPITools/openapi-generator/pull/18955
```
```  …
=> [python-fastapi] Update urllib3 to newer version

modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache, samples/openapi3/client/petstore/python-aiohttp/petstore_api/rest.py
based on https://github.com/OpenAPITools/openapi-generator/pull/18973
```
``` 
cc 
@cbornet …
=> Allow to pass a str to the Python aiohttp client

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
=> revert lost testMicroprofileGenerateCorrectJacksonGenerator_issue18336

README.md, website/src/dynamic/sponsors.yml
=> update kong URL

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache, modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-restclient/api.mustache, modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-webclient/api.mustache, modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-vertx/api.mustache
Fixes #18982
@jimschubert (2017/09) [❤️](https://www.patreon.com/jimschubert), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)
=> [kotlin-client] Generate safe ?. access for optional enums (#18982)

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.7.0 release

README.md
Related pull requests: 
- https://github.com/OpenAPITools/openapi-generator/pull/17495
- https://github.com/OpenAPITools/openapi-generator/pull/17499
- https://github.com/OpenAPITools/openapi-generator/pull/17603
- https://github.com/OpenAPITools/openapi-generator/pull/17614
Also added a YouTube link for the Java WireMock stub server presentation I have :)
=> Add Alexis Couvreur as author of Java WireMock stub server

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
Update certifi to newer version
```
``` 
=> [python-fastapi] Update certifi to newer version

.github/workflows/samples-python-petstore.yaml
=> Remove 3.7 tests in github python workflow

modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/api.mustache, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/UserApi.java
This reverts commit 9c4664a12c4622de57945214b9759a3f60cc6cec.
```
``` 
=> Revert "[java-retrofit2] Support payload for DELETE method (#19056)"

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/MysqlSchemaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlim4ServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/TemplateManagerOptions.java
=> Fix javadoc in various java files

modules/openapi-generator/src/main/resources/dart/libraries/dio/lib.mustache, samples/openapi3/client/petstore/dart-dio/oneof/lib/openapi.dart, samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/lib/openapi.dart, samples/openapi3/client/petstore/dart-dio/oneof_primitive/lib/openapi.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/openapi.dart, samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/openapi.dart
The `BearerAuthInterceptor` is missing from the generated library exports.
The other interceptors are included, so If we are exporting them, then it should be all or none
```
```  …
=> Add `BearerAuthInterceptor` to `dart-dio` library exports

README.md
=> docs: add act coding to users

modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java
=> Get rid of a bunch of Javadoc errors in Jersey 3 generated API client

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
setSortParamsByRequiredFlag is true in the default, so we don't have to set it again. The setSortModelPropertiesByRequiredFlag call does not matter because the generichost library has custom sorting logic anyway.
```
``` 
IMPORTANT: …
=> [csharp] Remove unnecessary code

.github/workflows/samples-java-client-echo-api-jdk17.yaml
This change was missing in the #19145 PR
```
``` 
@martin-mfg @wing328
=> test (JAVA SPRING RESTCLIENT) 18522: Add more JDK 17echo api tests & fix triggers

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, samples/client/others/java/jersey2-oneOf-Mixed/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/jersey2-oneOf-duplicates/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
=> [jersey2] Get rid of a bunch of Javadoc errors

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/server/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/server/pom.mustache, samples/client/petstore/jaxrs-cxf-client-jackson/pom.xml, samples/client/petstore/jaxrs-cxf-client/pom.xml, samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml, samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml, samples/server/petstore/jaxrs-cxf/pom.xml
=> Update CXF to newer version

.github/workflows/samples-python-pydantic-v1-petstore.yaml
Remove unsupported Python 3.7 tests that give error:
```
Run pipx install --python '/opt/hostedtoolcache/Python/3.7.17/x64/bin/python' poetry
creating virtual environment...
installing poetry...
Fatal error from pip prevented installation. Full pip output in file:
/opt/pipx/logs/cmd_2024-07-24_06.53.27_pip_errors.log
Some possibly relevant errors from pip install:
TypeError: Expected maxsize to be an integer or None
Error installing poetry.
```
```
```  …
=> Remove 3.7 tests in github python-pydantic-v1 workflow

.mvn/extensions.xml
=> revert gradle extension version

modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradle-sb3-Kts.mustache
based on https://github.com/OpenAPITools/openapi-generator/pull/19381
credit: @erikvanderwerf
```
```  …
=> Fix Reactive Spring build.gradle.kts

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.8.0 release

modules/openapi-generator/src/main/resources/python/pyproject.mustache
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/19404
```
``` 
=> Use gitHost in python pyproject template

README.md
Follow-up from https://github.com/OpenAPITools/openapi-generator/pull/19497 since https://github.com/OpenAPITools/openapi-generator-cli/pull/794 has been merged.
as promised in https://github.com/OpenAPITools/openapi-generator/pull/19497#issuecomment-2324036998
```
```
=> docs: link to existing documentation for snapshot builds and locally built JARs

modules/openapi-generator/src/main/resources/kotlin-spring/exceptions.mustache, samples/server/petstore/kotlin-spring-default/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-3/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-bigdecimal-default/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-delegate-nodefaults/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-integer-enum/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-multipart-request-model/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-source-swagger1/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-source-swagger2/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot-springfox/src/main/kotlin/org/openapitools/api/Exceptions.kt, samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/Exceptions.kt
I generated two folders with two different specs, which caused a conflict with the autowiring of the DefaultExceptionHandler class. To resolve this, I set different configuration names.
`Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [xdc.core.api.XdcCoreApiApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'defaultExceptionHandler' for bean class [xdc.external.apis.DefaultExceptionHandler] conflicts with existing, non-compatible bean definition of same name and class [xdc.tools.apis.DefaultExceptionHandler]`
@dr4ke616 @karismann @Zomzog @andrewemery @4brunu  @yutaka0m …
=> [kotlin-spring][server] fix spring boot configuration conflict

README.md, modules/openapi-generator/src/main/resources/erlang-server/handler.mustache, modules/openapi-generator/src/main/resources/erlang-server/logic_handler.mustache, samples/server/echo_api/erlang-server/src/openapi_auth_handler.erl, samples/server/echo_api/erlang-server/src/openapi_body_handler.erl, samples/server/echo_api/erlang-server/src/openapi_form_handler.erl, samples/server/echo_api/erlang-server/src/openapi_header_handler.erl, samples/server/echo_api/erlang-server/src/openapi_logic_handler.erl, samples/server/echo_api/erlang-server/src/openapi_path_handler.erl, samples/server/echo_api/erlang-server/src/openapi_query_handler.erl, samples/server/petstore/erlang-server/src/openapi_logic_handler.erl, samples/server/petstore/erlang-server/src/openapi_pet_handler.erl, samples/server/petstore/erlang-server/src/openapi_store_handler.erl, samples/server/petstore/erlang-server/src/openapi_user_handler.erl
```
``` 
Not sure if mentioning, as they unfortunately haven't been fully active 🥲  However, …
=> Erlang Server – cowboy return types improvements

modules/openapi-generator/src/test/java/org/openapitools/codegen/goginserver/GoGinServerCodegenTest.java
This PR is a minor fix in the test `GoGinServerCodegenTest`: the test should use a valid Go package name (so the generated output is valid and it can be run without changes).
@wing328 
```
```  …
=> [GO] GoGinServer - Correct package name in test

modules/openapi-generator/src/main/resources/python-pydantic-v1/requirements.mustache, modules/openapi-generator/src/main/resources/python-pydantic-v1/setup.mustache, modules/openapi-generator/src/main/resources/python/requirements.mustache, modules/openapi-generator/src/main/resources/python/setup.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/requirements.txt, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/setup.py, samples/client/echo_api/python-pydantic-v1/requirements.txt, samples/client/echo_api/python-pydantic-v1/setup.py, samples/client/echo_api/python/requirements.txt, samples/client/echo_api/python/setup.py, samples/openapi3/client/petstore/python-aiohttp/requirements.txt, samples/openapi3/client/petstore/python-aiohttp/setup.py, samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/requirements.txt, samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/setup.py, samples/openapi3/client/petstore/python-pydantic-v1/requirements.txt, samples/openapi3/client/petstore/python-pydantic-v1/setup.py, samples/openapi3/client/petstore/python/requirements.txt, samples/openapi3/client/petstore/python/setup.py
Improve the SemVer flexibility of the `urllib3` dependency.
Addresses https://github.com/OpenAPITools/openapi-generator/issues/18993.
I have not personally validated this change but believe this is all that should be required. Happy to follow any suggested validation paths. 
```
```  …
=> [python] Improve urllib3 semver flexibility

.github/PULL_REQUEST_TEMPLATE.md
=> chore: pull request template mentions an old current version

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradle-sb3-Kts.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-cloud/buildGradle-sb3-Kts.mustache, samples/server/petstore/kotlin-springboot-request-cookie/build.gradle.kts
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/19579
also update normalizer to pre-populate `info` if it's not defined to avoid NPE
```
```  …
=> update org.springdoc:springdoc-openapi-webmvc-api, ui to 2.6.0

modules/openapi-generator/src/test/java/org/openapitools/codegen/goginserver/GoGinServerCodegenTest.java
Uncomment `File::deleteOnExit` in webhooks test 
```
``` 
- [] If your PR is targeting a …
=> [GO] [GoGinServer] GoGinServerCodegenTest uncomment File::deleteOnExit

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache, samples/client/echo_api/java/resttemplate/build.gradle, samples/client/others/java/resttemplate-list-schema-validation/build.gradle, samples/client/others/java/resttemplate-useAbstractionForFiles/build.gradle, samples/client/petstore/java/resttemplate-jakarta/pom.xml, samples/client/petstore/java/resttemplate-swagger1/build.gradle, samples/client/petstore/java/resttemplate-swagger2/build.gradle, samples/client/petstore/java/resttemplate-withXml/build.gradle, samples/client/petstore/java/resttemplate/build.gradle
to close #19669, #19668
```
``` 
=> Update spring web in Java resttemplate client to 6.1.13

modules/openapi-generator/src/main/resources/typescript/services/ObjectParamAPI.mustache, samples/openapi3/client/petstore/typescript/builds/inversify/services/ObjectParamAPI.ts
=> style(typescript): add missing semi

modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumClass.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumOuterClass.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/microprofile/JavaMicroprofileServerCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/issue_19674.yaml
Fix https://github.com/OpenAPITools/openapi-generator/issues/19674
```
``` 
=> [Java][microprofile] enumUnknownDefaultCase true now returns correctly

modules/openapi-generator/src/main/resources/typescript-fetch/modelEnumInterfaces.mustache
refs OpenAPITools#1693
`x-enum-descriptions` was not supported in typescript-axios but not in typescript-fetch.
Similar pull requests:
- https://github.com/OpenAPITools/openapi-generator/pull/7477
- https://github.com/OpenAPITools/openapi-generator/pull/14123
```
```  …
=> [typescript-fetch] support "x-enum-descriptions"

README.md
Add @joscha to TS technical committee
cc
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)
```
```  …
=> Add @joscha to TS technical committee

modules/openapi-generator/src/main/resources/zapier/api.mustache, modules/openapi-generator/src/main/resources/zapier/utils.mustache, samples/client/petstore/zapier/apis/PetApi.js, samples/client/petstore/zapier/apis/StoreApi.js, samples/client/petstore/zapier/apis/UserApi.js, samples/client/petstore/zapier/utils/utils.js
=> [zapier] add response middleware

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/ClientUtils.mustache, samples/client/petstore/csharp/generichost/net8/AllOf/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/AnyOf/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/AnyOfNoCompare/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/FormModels/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/OneOf/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/Petstore/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/Client/ClientUtils.cs, samples/client/petstore/csharp/generichost/net8/UseDateTimeForDate/src/Org.OpenAPITools/Client/ClientUtils.cs
=> [csharp][generichost] Support formatting date only

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> Prepare 7.9.0 release

docs/generators/c.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
By default, gcc has a predefined macro “linux”
```bash
$ gcc -dM -E - < /dev/null | grep linux
#define __linux 1
#define __gnu_linux__ 1
#define linux 1                    <---------------------- here !
#define __linux__ 1
```
So if the source code contains "linux", the compilation will fail.
e.g.
```bash
/home/runner/work/c/c/kubernetes/model/v1_container_user.h:23:39: error: expected identifier or ‘(’ before numeric constant
23 |     struct v1_linux_container_user_t *linux; //model
|                                       ^~~~~
```
This PR adds "linux" to the reserved keywords to escape "linux" to "_linux" to avoid compilation failure.
```
``` 
(For …
=> [C][Client] Add gcc predefined macros to reserved keywords

modules/openapi-generator/src/main/resources/zapier/actions.mustache, modules/openapi-generator/src/main/resources/zapier/utils.mustache, samples/client/others/typescript/builds/enum-single-value/index.ts, samples/client/petstore/zapier/operations/actions.js, samples/client/petstore/zapier/utils/utils.js
=> feat: add middleware for create actions

.travis.yml
=> Uncomment workflow to update webpages

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-webclient/infrastructure/ApiClient.kt.mustache, samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-spring-2-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Fixes #19799
Should fix the following error that was appearing when generating a API for multipart/form-data requests with kotlin jvm-spring-webclient: 
> Content type 'multipart/form-data' not supported for bodyType=java.util.Collections$SingletonMap<?, ?>
Technical comitee: @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier
```
```  …
=> [kotlin-client][jvm-spring-webclient] Extract data from PartConfig for multipart/form-data requests in ApiClient

modules/openapi-generator/src/main/resources/python-flask/model.mustache, samples/server/petstore/python-flask/openapi_server/models/category.py
This pull request fix the issue #19487.
```
```  …
=> [python-flask] Fix #19487 SyntaxWarning

.travis.yml, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java, modules/openapi-generator/src/main/resources/python-fastapi/param_type.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonFastAPIServerCodegenTest.java, modules/openapi-generator/src/test/resources/bugs/pr_18691.json, samples/server/petstore/python-fastapi/src/openapi_server/apis/fake_api.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/fake_api_base.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/pet_api.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/pet_api_base.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/store_api.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/store_api_base.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api.py, samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api_base.py
=> Fix python-fastapi signature of parameters for method

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java, modules/openapi-generator/src/test/resources/3_0/null_schema_test.yaml
- Refactor isNullSchema check
- add more tests
```
``` 
=> Refactor isNullTypeSchema check

docs/faq-generators.md
=> Update generator FAQ

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
to close https://github.com/OpenAPITools/openapi-generator/pull/19878
```
``` 
=> [python-fastapi] Update fastapi, starlette to newer versions

modules/openapi-generator/src/test/resources/3_0/cpp-qt/petstore.yaml, samples/client/petstore/cpp-qt-addDownloadProgress/client/PFXPetApi.cpp, samples/client/petstore/cpp-qt-addDownloadProgress/client/PFXPrimitivesApi.cpp, samples/client/petstore/cpp-qt-addDownloadProgress/client/PFXStoreApi.cpp, samples/client/petstore/cpp-qt-addDownloadProgress/client/PFXUserApi.cpp, samples/client/petstore/cpp-qt/client/PFXPetApi.cpp, samples/client/petstore/cpp-qt/client/PFXPrimitivesApi.cpp, samples/client/petstore/cpp-qt/client/PFXStoreApi.cpp, samples/client/petstore/cpp-qt/client/PFXUserApi.cpp
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/19859
```
``` 
=> [cpp-qt] add tests for servers

modules/openapi-generator/src/main/resources/swift5/APIs.mustache, samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIs.swift, samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/APIs.swift, samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/APIs.swift
[swift5] add credentials by default
```
``` 
@jgavris (2017/07) @ehyche (2017/08) @Edubits …
=> [swift5] add credentials by default

bin/configs/java-helidon-client-mp_3.yaml, bin/configs/java-helidon-client-mp_4.yaml, bin/configs/java-helidon-client-se_3.yaml, bin/configs/java-helidon-client-se_4.yaml, bin/configs/java-micronaut-client.yaml, bin/configs/java-micronaut-server.yaml
Update configs with templateDir
```
``` 
=> Update configs with templateDir

modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/api.mustache, modules/openapi-generator/src/main/resources/JavaSpring/api.mustache, modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-http-interface/api.mustache, modules/openapi-generator/src/main/resources/java-micronaut/server/test/controller_test.groovy.mustache, modules/openapi-generator/src/main/resources/java-micronaut/server/test/controller_test.mustache, modules/openapi-generator/src/main/resources/java-pkmst/api.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache, modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/19912
```
``` 
=> Fix accepts, contentType with unescaped values

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache, samples/client/petstore/java/resttemplate-jakarta/pom.xml
update resttemplate dependency to newer version
to close https://github.com/OpenAPITools/openapi-generator/pull/19911
```
```  …
=> [java] update resttemplate dependency to newer version

.github/workflows/gradle-test.yaml, modules/openapi-generator/src/main/resources/Java/libraries/native/build.gradle.mustache, samples/client/echo_api/java/native/build.gradle, samples/client/petstore/java/native-async/build.gradle, samples/client/petstore/java/native-jakarta/build.gradle, samples/client/petstore/java/native/.openapi-generator-ignore, samples/client/petstore/java/native/build.gradle
- test build.gradle in CI
- sync pom.xml & build.gradle
```
``` 
=> Test build.gradle for java native petstore samples, sync pom.xml & build.gradle

README.md
Updated the README company list by adding CERN, which is currently experimenting with OpenApi Generator to streamline API calls in a newly developed business application.
```
```  …
=> Added Company to README.md

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache, samples/client/others/java/jersey2-oneOf-Mixed/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/jersey2-oneOf-duplicates/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey3-oneOf/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
Fixes #19965
```
``` 
Mentions: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger …
=> [Bug] [Java] Fix raw type compilation warning in ApiClient for jersey2 and jersey3

docs/generators/javascript.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java, samples/client/petstore/javascript-es6/src/ApiClient.js, samples/client/petstore/javascript-promise-es6/src/ApiClient.js
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/19949
```
``` 
=> [JS] set option to true by default, update samples

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJuliaCodegen.java, modules/openapi-generator/src/main/resources/julia-client/partial_model_single.mustache, modules/openapi-generator/src/main/resources/julia-server/partial_model_single.mustache, samples/client/petstore/julia/src/models/model_ApiResponse.jl, samples/client/petstore/julia/src/models/model_Category.jl, samples/client/petstore/julia/src/models/model_MappedModel.jl, samples/client/petstore/julia/src/models/model_Order.jl, samples/client/petstore/julia/src/models/model_Pet.jl, samples/client/petstore/julia/src/models/model_Tag.jl, samples/client/petstore/julia/src/models/model_User.jl, samples/server/petstore/julia/src/models/model_AnotherModel.jl, samples/server/petstore/julia/src/models/model_ApiResponse.jl, samples/server/petstore/julia/src/models/model_Category.jl, samples/server/petstore/julia/src/models/model_Order.jl, samples/server/petstore/julia/src/models/model_Pet.jl, samples/server/petstore/julia/src/models/model_Tag.jl, samples/server/petstore/julia/src/models/model_User.jl
Improved enum support. Added an override for `postProcessModels` method in julia code generator to do enum post processing. Added an override for `toEnumValue` method in julia code generator to generate enum values correctly based on julia types. Updated templates to use `#enumVars` for generating enum values.
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as …
=> [julia] improve enum support

modules/openapi-generator/src/main/resources/python/configuration.mustache, modules/openapi-generator/src/main/resources/python/pyproject.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/configuration.py, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/pyproject.toml, samples/client/echo_api/python/openapi_client/configuration.py, samples/client/echo_api/python/poetry.lock, samples/client/echo_api/python/pyproject.toml, samples/openapi3/client/petstore/python-aiohttp/petstore_api/configuration.py, samples/openapi3/client/petstore/python-aiohttp/pyproject.toml, samples/openapi3/client/petstore/python/petstore_api/configuration.py, samples/openapi3/client/petstore/python/pyproject.toml
Enhance typing for the Python modules, one module at a time.
Follow-up for:
* #17511 
* #17556
This provides typing information for the "configuration" module to enforce strong typing for all the methods and attributes.
cc @cbornet (2017/09) @tomplus (2018/10) @krjakbrjak (2023/02) @fa0311 (2023/10) @multani (2023/10) + @robertschweizer (who expressed interest around more typing)
```
``` 
You may …
=> python: stronger typing for the "configuration" module

docs/generators/csharp.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java, modules/openapi-generator/src/main/resources/csharp/ApiClient.v790.mustache, modules/openapi-generator/src/main/resources/csharp/Configuration.v790.mustache, modules/openapi-generator/src/main/resources/csharp/IReadableConfiguration.v790.mustache
a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/19875
```
``` 
=> [csharp] Add option to fallback to int for Timeout

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/duplicated_operationid.yaml
add a test https://github.com/OpenAPITools/openapi-generator/pull/20070/files#diff-73bab52f5d7424b5d166fb81aa39bfe47a4019ad4b9eb207b05a01c449d0c9b5R3157 for duplicated operationId
```
```  …
=> Add tests for duplicated operationId

modules/openapi-generator/src/main/resources/erlang-server/handler.mustache, modules/openapi-generator/src/main/resources/erlang-server/logic_handler.mustache, samples/server/echo_api/erlang-server/src/openapi_auth_handler.erl, samples/server/echo_api/erlang-server/src/openapi_body_handler.erl, samples/server/echo_api/erlang-server/src/openapi_form_handler.erl, samples/server/echo_api/erlang-server/src/openapi_header_handler.erl, samples/server/echo_api/erlang-server/src/openapi_logic_handler.erl, samples/server/echo_api/erlang-server/src/openapi_path_handler.erl, samples/server/echo_api/erlang-server/src/openapi_query_handler.erl, samples/server/petstore/erlang-server/src/openapi_logic_handler.erl, samples/server/petstore/erlang-server/src/openapi_pet_handler.erl, samples/server/petstore/erlang-server/src/openapi_store_handler.erl, samples/server/petstore/erlang-server/src/openapi_user_handler.erl
Allow for `ProvidedCallback` to return stop if manual handling was desired, as the `AcceptCallback` already does.
```
```  …
=> Erlang server

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> Prepare 7.10.0 release

.github/workflows/samples-php8.yaml
```
``` 
https://github.com/OpenAPITools/openapi-generator/pull/20162#dis …
=> add PHP8.4 CI

samples/client/echo_api/r/build_and_test.bash, samples/client/petstore/R-httr2-wrapper/build_and_test.bash, samples/client/petstore/R-httr2/build_and_test.bash, samples/client/petstore/R/build_and_test.bash
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/20132
```
```  …
=> Update r petstore client test script

docs/generators/kotlin.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
Update kotlin option description to clarify the support based on user feedback in https://github.com/OpenAPITools/openapi-generator/issues/20199
```
```  …
=> Update kotlin option description to clarify the support

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
=> Update python multipart dep to 0.0.18

bin/configs/elixir.yaml, modules/openapi-generator/src/test/resources/3_0/elixir/petstore-with-fake-endpoints-models-for-testing.yaml
Use a separate fake petstore spec for elixir for testing
fyi @mrmstn
```
```  …
=> [elixir] Use separate fake petstore spec for testing

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_1/issue_20239.yaml
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/20240 to ensure the path parameter won't be skipped
```
```  …
=> Add a test for generateParameterId

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache, samples/client/others/kotlin-jvm-okhttp-parameter-tests/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-explicit/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-name-parameter-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Reverts OpenAPITools/openapi-generator#20232
=> Revert "[Kotlin] fix #20231,  OkHttp client can handle a field with a list of files"

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
Fixes https://github.com/OpenAPITools/openapi-generator/issues/20248
```
```  …
=> [typescript-fetch] fix API signature return type for empty 20x responses

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache, samples/client/petstore/kotlin-array-simple-string-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-default-values-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-multiplatform-kotlinx-datetime/build.gradle.kts, samples/client/petstore/kotlin-multiplatform/build.gradle.kts
Bump Ktor to 3.0.2 for Kotlin client.
```
``` 
=> Bump Ktor to 3.0.2 for Kotlin client.

modules/openapi-generator/src/main/resources/go-gin-server/go.mod.mustache, samples/server/petstore/go-gin-api-server-interface-only/go.mod, samples/server/petstore/go-gin-api-server/go.mod
=> Update crypto dependencies to newer versions in go-gin-server

docs/installation.md
Added CLI installation via PyPI to `docs/installation.md`.
PyPI package page: 
https://pypi.org/project/openapi-generator-cli/
Repo: 
https://github.com/OpenAPITools/openapi-generator-pip
<details>
```
```  …
=> Add PyPI installation to docs

README.md
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/20350
```
```  …
=> Update readme with pip installation procedure

README.md, docs/3.0.0-release-note.md, docs/customization.md, modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJuliaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonPydanticV1Codegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- fix typos in doc
- fix typos in default codegen
- fix variable naming
- fix `parameter-name-mappings` check in maven plugin
based on https://github.com/OpenAPITools/openapi-generator/pull/19470
credits: @NathanBaulch
```
```  …
=> Various enhancements, bug fixes to default codegen and maven plugin

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache, samples/client/petstore/kotlin-array-simple-string-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-bigdecimal-default-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-default-values-multiplatform/build.gradle.kts, samples/client/petstore/kotlin-multiplatform-kotlinx-datetime/build.gradle.kts, samples/client/petstore/kotlin-multiplatform/build.gradle.kts
=> Bump Ktor to 3.0.3 for Kotlin client.

.github/workflows/samples-scala.yaml, samples/client/petstore/scalaz/.openapi-generator-ignore
sbt is no longer pre-installed so we need to install it manually
```
```  …
=> Fix sbt setup in workflow

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml, samples/client/petstore/java/okhttp-gson/api/openapi.yaml, samples/client/petstore/java/okhttp-gson/docs/NewPet.md, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/NewPet.java
Reverts OpenAPITools/openapi-generator#19986
=> Revert "Fix $ref to allOf in properties"

.github/ISSUE_TEMPLATE/bug_report.md
=> Update bug_report.md with up-to-date URL for online validator

docs/faq.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
=> Update openapi spec 3.1 support message

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.11.0 release

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
=> allow PHP generator to accept modelNameMapping

modules/openapi-generator/src/main/resources/rust/Cargo.mustache, samples/client/petstore/rust/reqwest/petstore-async-middleware/Cargo.toml
```
``` 
cc: @frol @farcaller @richardwhiuk @paladinzh @jacob-pro
=> [RUST] chore: Bumped Rust `reqwest-middleware` crate to 0.4

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
close #17863
Please see https://github.com/OpenAPITools/openapi-generator/issues/17863#issuecomment-2646268539 for an explanation.
```
```  …
=> remove false error message "Required var <property> not in properties"

modules/openapi-generator/src/main/resources/csharp/Solution.mustache
Enabled the use of the sourceFolder command line parameter to correctly reference folders in the solution file for the csharp language
=> Solution.mustache file modified (csharp generator)

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.12.0 release

modules/openapi-generator-maven-plugin/pom.xml
Hi,
Due to stricter security policies, we've been unable to download the openapi-generator-maven-plugin as it uses a compromised version of the `plexus-utils` library, that comes with the `org.sonatype.plexus:plexus-build-api:0.0.7` dependency. The `plexus-utils` library has had [CVE-2017-1000487](https://nvd.nist.gov/vuln/detail/CVE-2017-1000487) reported for it since 2017.
This has been mentioned already in issue https://github.com/OpenAPITools/openapi-generator/issues/19087 and https://github.com/OpenAPITools/openapi-generator/issues/11968, hence it should fix https://github.com/OpenAPITools/openapi-generator/issues/19087 and fix https://github.com/OpenAPITools/openapi-generator/issues/11968
Since most of our builds are broken now, I thought I might as well at least offer a PR to …
=> Upgrade plexus-build-api to mitigate CVE-2017-1000487

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache, samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
This is a follow-up to https://github.com/OpenAPITools/openapi-generator/pull/20515 to fix a missing [this-escape] warning  that popped up with 7.12.0 (`setUserAgent` method invokes `addDefaultHeader`, so that has to be final as well)
```
```  …
=> [JAVA] Finalize [this-escape] warnings fixes in apache-httpclient

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumClass.mustache, modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumOuterClass.mustache, modules/openapi-generator/src/main/resources/Java/libraries/native/modelEnum.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/modelEnum.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/modelInnerEnum.mustache, modules/openapi-generator/src/main/resources/Java/modelEnum.mustache, modules/openapi-generator/src/main/resources/Java/modelInnerEnum.mustache, modules/openapi-generator/src/main/resources/JavaSpring/enumClass.mustache, modules/openapi-generator/src/main/resources/JavaSpring/enumOuterClass.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/enum-implements.yaml
to fix https://github.com/OpenAPITools/openapi-generator/issues/20649
Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/bl
#20649
```
```  …
=> Fix #20649 Handling of x-implements for enumeration in java and spring generators

docs/customization.md
=> Improve documentation for RESOLVE_INLINE_ENUMS 

modules/openapi-generator/src/main/resources/typescript-angular/api.base.service.mustache, modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/typescript-angular/issue_20760.yaml, samples/client/others/typescript-angular/builds/composed-schemas-tagged-unions/api.base.service.ts, samples/client/others/typescript-angular/builds/composed-schemas/api.base.service.ts, samples/client/petstore/typescript-angular-v12-oneOf/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api.base.service.ts, samples/client/petstore/typescript-angular-v13-oneOf/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api.base.service.ts, samples/client/petstore/typescript-angular-v14-provided-in-root/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v14-query-param-object-format/api.base.service.ts, samples/client/petstore/typescript-angular-v15-provided-in-root/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v16-provided-in-root/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v17-provided-in-root/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v18-provided-in-root/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v19-with-angular-dependency-params/builds/default/api.base.service.ts, samples/client/petstore/typescript-angular-v19/builds/default/api.base.service.ts
This fixes #20760 (and was introduced in #20681).
The basePath was not correctly initialized.
@TiFu  @taxpon @sebastianhaas  @kenisteward @Vrolijkx  @macjohnny  @topce @akehir  @petejohansonxo @amakhrov @davidgamero  @mkusaka @joscha please review and/or give feedback :)
```
```  …
=> [typescript-angular] fix: update basePath initialization 

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/enum-implements.yaml
making the change suggested [here](https://github.com/OpenAPITools/openapi-generator/pull/20778#discussion_r1981906425)
```
```  …
=> change test spec to generate compilable output

bin/configs/nim.yaml, modules/openapi-generator/src/test/resources/3_0/nim/petstore.yaml
=> Migrate to nim own petstore test spec

modules/openapi-generator/src/main/resources/php/libraries/psr-18/composer.mustache, samples/client/petstore/php/psr-18/composer.json
=> [PHP] Bring PSR-18 composer.json inline with main

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
small cleanup for #20901
Since `convertPropertyToBooleanAndWriteBack(USE_SPRING_BUILT_IN_VALIDATION, this::setUseSpringBuiltInValidation);` is called, there's no need to manually set do `additionalProperties.put(USE_SPRING_BUILT_IN_VALIDATION, ...);`.
The green tests confirm this. :-)
```
```  …
=> [spring] small cleanup

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-webclient/infrastructure/ApiClient.kt.mustache, samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-spring-2-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
=> [BUG][Kotlin][WebClient] ApiClient is not compatible with spring-web 6 Observation API

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache, samples/server/petstore/python-fastapi/requirements.txt
to close https://github.com/OpenAPITools/openapi-generator/pull/21141
```
```  …
=> [python-fastapi] update h11, httpx to newer versions

samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml
fix:
```sh
$ cd samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests
$ dart pub get
Resolving dependencies... 
Because every version of openapi from path depends on dio ^5.7.0 and petstore_client_lib_fake_tests depends on dio 5.2.1, openapi from path is forbidden.
So, because petstore_client_lib_fake_tests depends on openapi from path, version solving failed.
You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on dio: dart pub add dev:dio:^5.7.0
```
```
``` 
This is important, as CI …
=> [dart-dio] Fix the version of the sample dependencies

pom.xml
=> Update maven plugin dependencies to newer versions

docs/faq-generators.md
[swift][client] update migration docs
```
``` 
@jgavris (2017/07) …
=> [swift][client] update migration docs

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.13.0 release

docs/installation.md
Replace version "7.9.0" by "7.12.0" in installation.md.
"7.9.0" is not mentioned in other places anymore.
```
```  …
=> fix documentation versions

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java, samples/client/petstore/elixir/mix.exs
Update [Tesla](https://hex.pm/packages/tesla), [ExDoc](https://hex.pm/packages/ex_doc) and [Dialyxir](https://hex.pm/packages/dialyxir) to their latest stable versions.
- Tesla [1.7..1.14](https://github.com/elixir-tesla/tesla/compare/v1.7.0...v1.14.1) (142 commits)
- ExDoc [0.30..0.37.3](https://github.com/elixir-lang/ex_doc/compare/v0.30.0...v0.37.3) (573 commits)
- Dialyxir [1.3..1.4.5](https://github.com/jeremyjh/dialyxir/compare/1.3.0...1.4.5) (61 commits)
The impact of this change is minimal since we are using "~>" in `mix.exs`. Thus, newly generated clients are likely to be using the latest available versions for these dependencies. Still, it's probably a good idea to update these versions in `mix.exs`. If nothing else, for documentation purposes.
Curious to hear your thoughts …
=> [chore][elixir] update dependencies

modules/openapi-generator/src/main/resources/csharp-functions/HttpSigningConfiguration.mustache, modules/openapi-generator/src/main/resources/csharp/HttpSigningConfiguration.mustache, samples/client/petstore/csharp/httpclient/net9/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/restsharp/net8/EnumMappings/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/restsharp/net8/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/restsharp/net9/EnumMappings/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/unityWebRequest/net9/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs, samples/client/petstore/csharp/unityWebRequest/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
Fixes https://github.com/OpenAPITools/openapi-generator/issues/20654
```
```  …
=> [csharp] fixed encoding

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
=> Update PR tempalte, issue template, link to validator

docs/templating.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Update user documentation about mustache lambdas.
```
```  …
=> update documentation about lambdas

modules/openapi-generator/src/main/resources/powershell/model_simple.mustache, modules/openapi-generator/src/main/resources/ruby-client/api.mustache, modules/openapi-generator/src/main/resources/ruby-client/partial_model_generic.mustache, samples/client/petstore/powershell/src/PSPetstore/Model/FormatTest.ps1, samples/client/petstore/ruby-autoload/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby-autoload/lib/petstore/models/format_test.rb, samples/client/petstore/ruby-faraday/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby-faraday/lib/petstore/models/format_test.rb, samples/client/petstore/ruby-httpx/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby-httpx/lib/petstore/models/format_test.rb, samples/client/petstore/ruby-httpx/lib/petstore/models/inline_object3.rb, samples/client/petstore/ruby/lib/petstore/api/fake_api.rb, samples/client/petstore/ruby/lib/petstore/models/format_test.rb, samples/client/petstore/ruby/lib/petstore/models/inline_object3.rb
`length must be great than or equal to ...` →`length must be greater than or equal to ...`
```
```  …
=> Fix spelling mistake in validations

pom.xml
=> update snakeyaml version to 2.4

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache, samples/client/echo_api/java/okhttp-gson-user-defined-templates/src/main/java/org/openapitools/client/ApiClient.java, samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/okhttp-gson-oneOf-array/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/okhttp-gson-oneOf/src/main/java/org/openapitools/client/ApiClient.java, samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-3.1-duplicated-operationid/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ApiClient.java
closes #21024
As explained in the linked issue, the regular expression can be optimized.
```
```  …
=> [JAVA][OKHTTP-GSON][VERTX] optimize regular expression

.mvn/extensions.xml
=> Update develocity to newer versions

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache, samples/client/echo_api/java/resttemplate/build.gradle, samples/client/others/java/resttemplate-list-schema-validation/build.gradle, samples/client/others/java/resttemplate-useAbstractionForFiles/build.gradle, samples/client/petstore/java/resttemplate-jakarta/pom.xml, samples/client/petstore/java/resttemplate-swagger1/build.gradle, samples/client/petstore/java/resttemplate-swagger2/build.gradle, samples/client/petstore/java/resttemplate-withXml/build.gradle, samples/client/petstore/java/resttemplate/build.gradle
to close https://github.com/OpenAPITools/openapi-generator/pull/21362
```
```  …
=> Update java restemplate dependencies to newer versions

.mvn/extensions.xml
to address the warnings during build
```
``` 
=> Update common custom user data maven extensions to 2.x

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache, samples/client/echo_api/java/resttemplate/build.gradle, samples/client/others/java/resttemplate-list-schema-validation/build.gradle, samples/client/others/java/resttemplate-useAbstractionForFiles/build.gradle, samples/client/petstore/java/resttemplate-jakarta/pom.xml, samples/client/petstore/java/resttemplate-swagger1/build.gradle, samples/client/petstore/java/resttemplate-swagger2/build.gradle, samples/client/petstore/java/resttemplate-withXml/build.gradle, samples/client/petstore/java/resttemplate/build.gradle
to close https://github.com/OpenAPITools/openapi-generator/pull/21413
=> Update spring web version in resttemplate

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.14.0 release

modules/openapi-generator/src/main/resources/python/pyproject.mustache, samples/client/others/java/restclient-enum-in-multipart/src/main/java/org/openapitools/client/JavaTimeFormatter.java, samples/client/petstore/java/restclient-useSingleRequestParameter-static/src/main/java/org/openapitools/client/JavaTimeFormatter.java, samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/JavaTimeFormatter.java, samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/Pair.java
Related: https://github.com/OpenAPITools/openapi-generator/issues/21468, https://github.com/OpenAPITools/openapi-generator/issues/21335
For a few years, the `pyproject.toml` `license` field was set to `NoLicense` when the spec did not provide another license. This value is not a valid SPDX identifier, however - as far as I can tell, there isn't any valid SPDX identifier for unlicensed code. (the Unlicense is NOT the same thing as UNLICENSED, [ref](https://opensource.stackexchange.com/a/12412)).
When this field was under the `[tool.poetry]` table, this was fine - Poetry doesn't seem to validate that field, or at least it allows `NoLicense`. [Poetry docs on `license`](https://python-poetry.org/docs/pyproject/#license)
However, this field was moved under the `[project]` table in …
=> fix(python): skip license if not provided

pom.xml
=> Update swagger parser to newer version

bin/configs/scala-http4s-server.yaml, modules/openapi-generator/src/test/resources/3_0/scala-http4s-server/petstore.yaml, samples/server/petstore/scala-http4s-server/.openapi-generator/FILES, samples/server/petstore/scala-http4s-server/src/main/scala/org/openapitools/api.scala, samples/server/petstore/scala-http4s-server/src/main/scala/org/openapitools/apis/FakeApi.scala
Add tests for scala http4s server with reserved words
a follow up pr to https://github.com/OpenAPITools/openapi-generator/pull/21490
```
```  …
=> Add tests for scala http4s server:

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
Just a small typo I noticed while looking through the CLI config options.
```
```  …
=> Fix typo in CLI command

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java
Fix for https://github.com/OpenAPITools/openapi-generator/pull/21555
```
```  …
=> [Protobuf] Fix nullpointer for allOf with additionalProperties=false (#21555)

modules/openapi-generator/src/main/resources/cpp-oatpp-server/model-header.mustache, samples/server/petstore/cpp-oatpp/model/ApiResponse.hpp, samples/server/petstore/cpp-oatpp/model/Category.hpp, samples/server/petstore/cpp-oatpp/model/Order.hpp, samples/server/petstore/cpp-oatpp/model/Pet.hpp, samples/server/petstore/cpp-oatpp/model/Tag.hpp, samples/server/petstore/cpp-oatpp/model/User.hpp
When testing https://github.com/OpenAPITools/openapi-generator/pull/21547 ran into a few issues that didn't make the API compliant:
- Model Fields were the wrong case
- Enum Fields weren't properly supported.
I've fixed both of those inconsistencies. It did not register to me that petstore does not make use of enums.
```
```  …
=> [C++] [Client] Fixes to cpp-oatpp-server generator.

.github/workflows/samples-dotnet-fx.yaml
2019 is deprecated, pr gates are not running. Fixes https://github.com/OpenAPITools/openapi-generator/issues/21650
```
```  …
=> [csharp] Use windows-latest

modules/openapi-generator/src/main/resources/csharp/libraries/unityWebRequest/ApiClient.mustache
Added handling for `application/octet-stream` into template csharp unityWebRequest ApiClient.
Resolves #21703
Unfortunately I was not able to build because of error:
```powerShell
Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:
invoke (default) on project openapi-generator-gradle-plugin-mvn-wrapper: 
org.gradle.tooling.BuildException: Could not execute build using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.6.4-bin.zip'.
```
Solution from [here](https://openapi-generator.tech/docs/contribute-building/#troubleshooting) does not yield positive result.
@mandrean @shibayan @Blackclaws @lucamazzanti @iBicha
```
./bin/utils/export_docs_generators.sh || …
```
=> [REQ] [CSHARP] [UNITYWEBREQUEST] Support Stream for unityWebRequest library

.github/workflows/linux.yaml
for https://github.com/OpenAPITools/openapi-generator/pull/21720#issuecomment-3186841733
```
```  …
=> Fix github workflow (linux.yaml)

modules/openapi-generator/src/main/resources/typescript/package.mustache, samples/client/echo_api/typescript/build/package.json, samples/client/others/typescript/encode-decode/build/package.json, samples/openapi3/client/petstore/typescript/builds/default/package.json, samples/openapi3/client/petstore/typescript/builds/explode-query/package.json, samples/openapi3/client/petstore/typescript/builds/inversify/package.json, samples/openapi3/client/petstore/typescript/builds/object_params/package.json
https://github.com/OpenAPITools/openapi-generator/issues/21745
```
```  …
=> [Typescript] Updated `form-data` to the latest version

.github/workflows/windows.yaml
windows equivalent of #21720
the workflow is using gradle 9 as of yesterday, breaking tests with the same -b flag deprecation
```
```  …
=> specify windows gradle version

modules/openapi-generator/src/main/resources/python/api_client.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api_client.py, samples/client/echo_api/python/openapi_client/api_client.py, samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py, samples/openapi3/client/petstore/python/petstore_api/api_client.py, samples/openapi3/client/petstore/python/tests/test_deserialization.py
Also tested against https://www.iana.org/assignments/media-types/media-types.xhtml to ensure that it accepts the same content types as before.
```
```  …
=> Fix overly permissive regular expression.

README.md, docs/installation.md, docs/plugins.md, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-maven-plugin/README.md, website/src/pages/index.js
=> update doc to reference 7.15.0

pom.xml
=> Update swagger parser to 2.1.32

modules/openapi-generator/src/main/resources/python-aiohttp/gitignore.mustache, modules/openapi-generator/src/main/resources/python-blueplanet/app/dockerignore.mustache, modules/openapi-generator/src/main/resources/python-blueplanet/app/gitignore.mustache, modules/openapi-generator/src/main/resources/python-flask/dockerignore.mustache, modules/openapi-generator/src/main/resources/python-flask/gitignore.mustache, modules/openapi-generator/src/main/resources/python-pydantic-v1/gitignore.mustache, modules/openapi-generator/src/main/resources/python/gitignore.mustache, samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/.gitignore, samples/client/echo_api/python-pydantic-v1/.gitignore, samples/client/echo_api/python/.gitignore, samples/openapi3/client/petstore/python-aiohttp/.gitignore, samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/.gitignore, samples/openapi3/client/petstore/python-pydantic-v1/.gitignore, samples/openapi3/client/petstore/python/.gitignore, samples/server/petstore/python-aiohttp-srclayout/.gitignore, samples/server/petstore/python-blueplanet/app/.dockerignore, samples/server/petstore/python-blueplanet/app/.gitignore, samples/server/petstore/python-flask/.dockerignore, samples/server/petstore/python-flask/.gitignore
Just adding a space before the comment text in .gitignore for readability.
No functional changes.
```diff
-#Ipython Notebook
+# Ipython Notebook
```
```
```  …
=> [python] style: add a space before comment text in .gitignore

modules/openapi-generator/src/main/resources/rust/Cargo.mustache, samples/client/others/rust/Cargo.lock, samples/client/others/rust/reqwest-regression-16119/Cargo.toml, samples/client/others/rust/reqwest/api-with-ref-param/Cargo.toml, samples/client/others/rust/reqwest/composed-oneof/Cargo.toml, samples/client/others/rust/reqwest/emptyObject/Cargo.toml, samples/client/others/rust/reqwest/oneOf-array-map/Cargo.toml, samples/client/others/rust/reqwest/oneOf-reuseRef/Cargo.toml, samples/client/others/rust/reqwest/oneOf/Cargo.toml, samples/client/petstore/rust/reqwest-trait/petstore/Cargo.toml, samples/client/petstore/rust/reqwest/name-mapping/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-async-middleware/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-async-tokensource/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-async/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-avoid-box/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-awsv4signature/Cargo.toml, samples/client/petstore/rust/reqwest/petstore-model-name-prefix/Cargo.toml, samples/client/petstore/rust/reqwest/petstore/Cargo.toml, samples/client/petstore/rust/reqwest/test-duplicates/Cargo.toml
Implements https://github.com/OpenAPITools/openapi-generator/issues/21924
```
```  …
=> [Rust] Add support for native-tls and rustls-tls Cargo features for the reqwest library

.github/workflows/samples-java-sbt.yaml, .github/workflows/samples-scala.yaml
=> Separate workflow to test Java samples with sbt

pom.xml
=> Update commons related dependencies to newer versions

.github/workflows/samples-java-client-jdk11.yaml, .github/workflows/samples-java-petsore-client-jdk11.yaml, CI/circle_parallel.sh, samples/client/petstore/java/jersey2-java8/.openapi-generator-ignore
Test Java clients with Petstore server in Github workflow
(migration from CircleCI)
```
```  …
=> Test Java clients with Petstore server in Github workflow

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
a follow up pr to #22002 
```
``` 
=> kotlin client: add docstring to new function

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/examples/spring.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml
=> v7.16.0 release

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/api.mustache, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/PetApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/StoreApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/TestApi.java, samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/UserApi.java
@Api(description=...) is deprecated in swagger-annotations-1.5.0 and the following.
Remove its usage: it is not used by swagger-ui, and generates warnings at build.
```
``` 
IMPORTANT: Do …
=> [java-cxf-cdi] @Api description is deprecated in swagger-annotations
