modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/examples.yaml

The DefaultCodegen now iterates through all api operations.
This allows to access different examples based on the response per status code and content type.
```
```  …

fix: DefaultCodegen now generates an exemple for each status codes

---

modules/openapi-generator/src/main/resources/python-flask/requirements.mustache

Because the requirements file does not limit connexion version to below 3.0, with release of connexion 3.0 the openapi server startup sequence runs into a module not found issue.
This contraint is preventing that.
```
``` 
IMPORTANT: …

bug fix: breaking dependency of flask server gen

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
samples/client/echo_api/typescript-axios/build/api.ts
samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-node-imports/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
samples/client/petstore/typescript-axios/builds/with-string-enums/api.ts

fix #17068
PR https://github.com/OpenAPITools/openapi-generator/pull/16782 introduced some local variables which does not follow the naming convetion for local var (prefix with `localVar`). This causes error when the API has a query parameter which conflict name with local variable.
For example. A parameter called 'index' will cause an error, which is quite a common name.
Add the conventional  `localVar` prefix to work around it.
```
``` 
These must match …

fix(typescript-axios): fix error if a parameter called 'index' exists

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ErlangClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/optionalResponse.yaml

Added missing copied properties from CodegenOperation in TypeScriptFetchClientCodegen and ErlangClientCodegen to resolve issue #15457. The codegen mustache templates had these values available, but always set to the default values, regardless of the actual OpenAPI spec it was used for.
```
```  …

Added missing copied properties from CodegenOperation

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml
samples/client/petstore/java/okhttp-gson/README.md
samples/client/petstore/java/okhttp-gson/api/openapi.yaml
samples/client/petstore/java/okhttp-gson/docs/ValuesApi.md
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/ValuesApi.java

add code to skip operations, models with x-internal set to true
```
```  …

Support x-internal in models and operations

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java
modules/openapi-generator/src/main/resources/perl/cpanfile.mustache
samples/client/petstore/perl/.openapi-generator/FILES
samples/client/petstore/perl/cpanfile

- add auto-generated cpanfiile in perl client
- cpanfile tested in github workflow
@wing328 (2017/07) ❤️ @yue9944882 (2019/06)
```
```  …

Add auto-generated cpanfile in Perl client

---

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/RestApplication.mustache

Fixes #17642 
When an OpenAPI specification contains a block info > contact > url, this url is not added to the generated OpenAPIDefinition, which is added to the RestApplication class. This pull request fixes that.
```
```  …

[jaxrs-spec] Addinfo contact url to the generated OpenAPIDefinition

---

modules/openapi-generator/src/main/resources/perl/Configuration.mustache
samples/client/petstore/perl/lib/WWW/OpenAPIClient/Configuration.pm

This is to address feature/issue #14297
IMHO, this is a somewhat trivial issue/PR. Yes, the version string is [hard-coded](https://github.com/OpenAPITools/openapi-generator/blob/3dcef8249b09f92fceba57e34b9c0cdaf7e7a758/modules/openapi-generator/src/main/resources/perl/Configuration.mustache#L85) into the http_user_agent default, but that hard-coded string is dynamically generated. Anyway, since the issue was accepted, here is a PR to resolve it.
Testing steps:
```
$ sudo apt install default-jdk maven
$ perlbrew use perl-5.36.0
$ perlbrew clean
$ perlbrew upgrade-perl
$ perl -E'say $]'
5.036003
$ ./mvnw clean package
$ ./bin/generate-samples.sh ./bin/configs/perl.yaml
$   ./bin/utils/export_docs_generators.sh
$ cd samples/client/petstore/perl
$ cpanm --installdeps .
$ prove -l
[... etc …
```

feat(perl): Update agent to use version constant

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin-jvm-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-retrofit2-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

This commit fixes an issue where the object mapper is not passed to the JacksonConverterFactory. The issue causing the serialization to fail when passing to the ApiClient a pre-configured mapper object (e.g. the primary bean of SpringBoot).
With this fix, the bean would be correctly passed to the factory, and the serialization would work "out of the box" for the pre-configured bean.
```
``` 
You …

Pass ObjectMapper to JacksonConverterFactory

---

modules/openapi-generator/src/main/resources/r/ApiResponse.mustache
modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/api_client.mustache
modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache
samples/client/petstore/R-httr2-wrapper/R/api_client.R
samples/client/petstore/R-httr2-wrapper/R/api_response.R
samples/client/petstore/R-httr2-wrapper/R/fake_api.R
samples/client/petstore/R-httr2-wrapper/R/pet_api.R
samples/client/petstore/R-httr2-wrapper/R/store_api.R
samples/client/petstore/R-httr2-wrapper/R/user_api.R
samples/client/petstore/R-httr2/R/api_client.R
samples/client/petstore/R-httr2/R/api_response.R
samples/client/petstore/R-httr2/R/fake_api.R
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R-httr2/R/store_api.R
samples/client/petstore/R-httr2/R/user_api.R
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/R/api_response.R
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R

@Ramanth  & @saigiridhar21 
There is currently no support in the generated R client for endpoints that return binary data which cannot be coerced to text. In the `self$Execute` method we have:
```r
resp <- req %>% req_error(is_error = function(resp) FALSE) %>% 
req_perform()
api_response <- ApiResponse$new()
api_response$status_code <- resp %>% resp_status()
api_response$status_code_desc <- resp %>% resp_status_desc()
api_response$response <- resp %>% resp_body_string()         ##### here
api_response$headers <- resp %>% resp_headers()
api_response
```
The `httr` implementation is similar. Both assume that the response content can be converted to a string. There are cases where the response is, for example, accepting `application/gzip` and returns a byte stream with content for a `tar.gz` …

support binary response for R api client

---

modules/openapi-generator/src/main/resources/python-pydantic-v1/api_client.mustache
modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api_client.py
samples/client/echo_api/python-pydantic-v1/openapi_client/api_client.py
samples/client/echo_api/python/openapi_client/api_client.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/api_client.py
samples/openapi3/client/petstore/python-pydantic-v1/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py

Fixed an issue the parameters_to_url_query method would throw an error if the input was of type List[int] #15788(https://github.com/OpenAPITools/openapi-generator/issues/15788)
because the join operation expects string types, but it is being applied to integers.
- [〇] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [〇] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [〇] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
``` …
```

fix an issue the parameters_to_url_query method would throw an error if the input was of type List[int] BUG#15788

---

modules/openapi-generator/src/main/resources/Javascript/libraries/javascript/ApiClient.mustache
samples/client/petstore/javascript-es6/src/ApiClient.js
samples/client/petstore/javascript-promise-es6/src/ApiClient.js

This pull request introduces a crucial enhancement to the regex used for parsing path parameters. Specifically, a hashtag (#) has been included in the regex to support Mojolicious Relaxed placeholders. These placeholders utilize a hash prefix and match all characters except '/', akin to the regular expression ([^/]+).
https://docs.mojolicious.org/Mojolicious/Guides/Routing#Relaxed-placeholders

Include support to Mojolicious relaxed placeholders parsing path parameters

---

samples/client/echo_api/ruby-faraday/spec/manual_spec.rb

Fix missing import in ruby faraday test

---

modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache

This PR fixes the issue #16975 by adding a `<model>.to_string()` call when appropriate.
Mentioning technical committee per PR checklist: @jacob-pro
```
```  …

[Rust][client] Fix issue #16975 - generated type not being converted to string

---

modules/openapi-generator/src/main/resources/cpp-ue4/helpers-header.mustache
samples/client/petstore/cpp-ue4/Public/OpenAPIHelpers.h

Currently if the `"uniqueItems": true,` is present in the schema for array items, the generated code does not compile due to lack of support for TSet container
```cpp
0>GenericApiOperations.cpp(151): Error C2672 : 'CollectionToUrlString_multi': no matching overloaded function found
0>Helpers.h(203): Reference  : could be 'FString ::CollectionToUrlString_multi(const TArray<T,FDefaultAllocator> &,const TCHAR *)'
0>GenericApiOperations.cpp(151): Reference  : 'FString ::CollectionToUrlString_multi(const TArray<T,FDefaultAllocator> &,const TCHAR *)': could not deduce template argument for 'const TArray<T,FDefaultAllocator> &' from 'const TSet<FString,DefaultKeyFuncs<InElementType,false>,FDefaultSetAllocator>'
0>        with
0>        [
0>            InElementType=FString
0>        ]
```
This …

[cpp-ue4] Fix generated code not compiling when using unique array items

---

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/api.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/spec/apiInterface.mustache
samples/server/petstore/jaxrs-spec-interface-response/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-spec-interface-response/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-spec-interface-response/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-spec-interface-response/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-spec-interface-response/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-spec-interface-response/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs-spec-jakarta/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-spec-jakarta/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-spec-jakarta/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-spec-jakarta/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-spec-jakarta/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-spec-jakarta/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs-spec-required-and-readonly-property/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/UserApi.java

This PR adds some fairly informative JavaDoc to the api methods for the jaxrs spec  generator.
The class level doc comment is copied from the `charp` equivalent.
Fixes issue ##17704
```
```  …

Add JavaDoc to api and apiInterface templates for the JavaJaxRS spec generator

---

modules/openapi-generator/src/main/resources/JavaSpring/enumClass.mustache
modules/openapi-generator/src/main/resources/JavaSpring/enumOuterClass.mustache

With #1693, the extension `x-enum-descriptions` was added. The changes made here introduce support for the Spring templates as well. Generation successfully tested locally for inner and outer enum classes.
```
``` 
@cachescrubber @welshm @MelleD @atextor …

[JavaSpring] Add Javadoc to enum (x-enum-descriptions)

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache
modules/openapi-generator/src/main/resources/Java/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pom.mustache
modules/openapi-generator/src/main/resources/java-msf4j-server/pom.mustache
samples/client/petstore/java/resttemplate-jakarta/pom.xml
samples/server/petstore/java-msf4j/pom.xml
samples/server/petstore/jaxrs-spec-jakarta/pom.xml

Closes #17590 
Use dependency com.fasterxml.jackson.jaxrs:jackson-jakarta-rs-json-provider instead of com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider in pom when useJakartaEe is true for Java projects.
Tagging the Java technical committee: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)
```
```  …

[java] fix Use jackson-jakarta-rs-json-provider when useJakartaEe is true

---

pom.xml

This addresses #17554 by downgrading `swagger-parser` to the version that was used in the 7.1.0 release of `openapi-generator`.
```
```  …

revert swagger-parser upgrade

---

modules/openapi-generator/src/main/resources/scala-sttp/jsonSupport.mustache
samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/core/JsonSupport.scala

If an enum is specified directly in a field of another object, then the `EnumNameSerializer` is not created as part of `def enumSerializers` in `JsonSupport`
As a result these enumerations are not parsed correctly in the generated client.

[scala-sttp]: fix for missing EnumNameSerializer for inner enum definitions

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java

```
``` 
<hr/>
I have the feeling this PR template is outdated:
1. I ran the tho sh files and …

fix require var logging, don't matchGenerated if allOf skipped

---

bin/configs/java-okhttp-gson.yaml
docs/customization.md
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfiguratorUtils.java
samples/client/petstore/java/okhttp-gson/README.md
samples/client/petstore/java/okhttp-gson/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/api/FakeApiTest.java

- provide an option (e.g. --operation-id-name-mappings) to map operationId to another value provided by the user (bypassing any normalization)
- add tests
```
```  …

Add operationId name mapping option

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache

Closes: #10114
Allows using bearer auth with typescript-nestjs
`modules/openapi-generator/src/test/resources/3_0/petstore.yaml` doesn't use bearer auth, but if it were
```
// authentication (bearer) required
if (typeof this.configuration.accessToken === 'function') {
headers['Authorization'] = `Bearer ${this.configuration.accessToken()}`;
} else if (this.configuration.accessToken) {
headers['Authorization'] = `Bearer ${this.configuration.accessToken}`;
}
```
would be appended to each service call.
I opted to not add bearer auth in the api spec because it's used by many generators. If you want I can add a typescript-nestjs directory and copy over the yaml file adding bearer auth
``` …
```

Allow using bearer auth in typescript-nestjs

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/user.service.ts

Closes: #17706
Typesafe access to `Configuration.apiKeys`
```
``` 
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov …

fix typescript-nestjs services when using api_key authentication

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-axios/modelGeneric.mustache
samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts

Fix #16494 
```
``` 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward …

[typescript-axios] Add any to index type when additionalPropertiesIsAnyType is true (#16494)

---

modules/openapi-generator/src/main/resources/typescript-aurelia/README.md
modules/openapi-generator/src/main/resources/typescript-axios/README.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/README.mustache
modules/openapi-generator/src/main/resources/typescript-jquery/README.mustache
modules/openapi-generator/src/main/resources/typescript-redux-query/README.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/README.mustache

The previous link no longer worked, so I've updated it to the latest version of the TypeScript handbook.
```
```  …

fix: update dead link to TypeScript docs

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/issue_16223.yaml
modules/openapi-generator/src/test/resources/3_0/issue_16223_enum_with_default.yaml
modules/openapi-generator/src/test/resources/3_0/issue_16223_enum_with_default_empty.yaml

fix: #16223
If a parameter is referencing an array-type schema in an external file using `$ref`, its default value will be rendered with unneeded square braces like `[foo, bar]`. This PR removes them.
To [Java technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee): @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)
```
```  …

[Java] Fix default values of array-type parameters in a referenced file

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

name in codegen model may have been escaped so we add schemaName to store the original schema name for parent lookup.
log a warning instead of throwing exception in case parent schema cannot be looked up using the codegen model name.
```
```  …

Fix parent schema look up using schema name

---

.github/workflows/samples-typescript-axios-echo-api.yaml
samples/client/echo_api/typescript-axios/build/.openapi-generator-ignore

Fix TS Axios client github workflow by using an old version of the http echo server
```
``` 

Fix TS Axios echo client github workflow

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java

Fixes #17752 
I've added in the pom.xml file for Java client with Resttemplate library the jakarta-validation-api dependency when setting the property userBeanValidation to true and the hibernate-validator dependecy when setting the property performBeanValidation to true. 
Versions are identical to other pom.xml files with the same dependencies. 
@cachescrubber @welshm @MelleD @atextor @manedev79 @javisst @borsch @banlevente @Zomzog @martin-mfg
```
```  …

[JAVA][bugfix] Add dependency for jakarta-validation-api and hibernate-validator to pom.xml for Java Resttemplate client

---

modules/openapi-generator/src/main/resources/go/utils.mustache
samples/client/echo_api/go/utils.go
samples/client/petstore/go/go-petstore/utils.go
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/utils.go
samples/openapi3/client/petstore/go-petstore-generateMarshalJSON-false/utils.go
samples/openapi3/client/petstore/go/go-petstore/utils.go

If a NullableTime is set explicitly to nil and attempted to be serialized, then `v.value` will be nil, resulting in a runtime panic.
```
```  …

[Go] Fix panic from marshalling Nil NullableTime

---

modules/openapi-generator/src/main/resources/java-camel-server/restConfiguration.mustache

Include API info in RestConfiguration for java-camel-server mustache template to prevent warning on startup as OpenAPI information can't be created otherwise.
Use java-camel-server generator to build the server and run it using the spring-boot-starter as described here: https://camel.apache.org/components/4.0.x/rest-component.html#_spring_boot_auto_configuration
@carnevalegiacomo
@martin-mfg
@lwlee2608
```
```  …

include API information in RestConfiguration Template

---

modules/openapi-generator/src/main/resources/go-gin-server/routers.mustache
samples/server/petstore/go-gin-api-server/go/routers.go

Currently, the GIN engine is directly created in the `NewRouter` function. so it is not possible to set middleware before the registration of routers.
I added a new function in the router so we can use the existing Gin Engine object.
```
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
...
}
```
FYI: @antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5
```
```  …

[go-gin-server]  add a new function to the router to pass the gin context

---

modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/psr-18/lib/ObjectSerializer.php

If it's not datetime nor bool, it's string
```
``` 

fix(php): do not cast to string something that's already string

---

modules/openapi-generator/src/main/resources/php-nextgen/Configuration.mustache
samples/client/echo_api/php-nextgen/src/Configuration.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Configuration.php

`hostSettings` is used everywhere else so I consider `hostsSettings` a typo
```
``` 

refactor(php): unify $hostSettings variable name

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinServerCodegenTest.java
modules/openapi-generator/src/test/resources/3_1/issue_17726.yaml

to fix https://github.com/OpenAPITools/openapi-generator/issues/17726
```
```  …

Fix attributes in allOf and $ref 

---

modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/BarRef.java

Fix for https://github.com/OpenAPITools/openapi-generator/issues/17486
```
``` 
@cachescrubber …

Fix java-spring equals generation

---

modules/openapi-generator/src/main/resources/dart2/pubspec.mustache
samples/openapi3/client/petstore/dart2/petstore_client_lib/pubspec.yaml
samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/pubspec.yaml

The hard reuirement of `intl: '^0.18.0'` limits current and future update behavior.
It is recommended by the flutter team to depend on `intl: any` instead.
```
```  …

[Dart] Make dependency on intl package less strict

---

docs/customization.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_0/enableKeepOnlyFirstTagInOperation_test.yaml

to close https://github.com/OpenAPITools/openapi-generator/issues/17653
e.g. 
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/java-okhttp/ --openapi-normalizer FILTER="operationId:addPet|getPetById"
```
```
```  …

Add FILTER to openapi normalizer

---

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_1/issue-17485.yaml

Fixes #17485 which was a regression in 7.2.0 after #17165 was merged. That change did not add the necessary imports to the generated API when bean validation was enabled and the schema contained an array that had item level validation.
```
```  …

[java][native] Fix missing imports when using list validation

---

modules/openapi-generator/src/main/resources/go/model_simple.mustache
samples/client/echo_api/go-external-refs/model_default_value.go
samples/client/echo_api/go/model_default_value.go
samples/openapi3/client/petstore/go/go-petstore/model_nullable_class.go
samples/openapi3/client/petstore/go/go-petstore/model_user.go

based on https://github.com/OpenAPITools/openapi-generator/pull/17840 with update samples
to close #17835 
```
```  …

[Go] fix isNil check

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/property-title.yaml

Even though `title` is technically for the title of the API itself, it's possible to set it for properties as well.
Right now, the `title` property is available in templates for regular properties, but for ref-properties it gets lost right here.
This seemed rather surprising to me, so I think it's better to fix.
```
``` 
You may regenerate an individual generator by passing the relevant config(s) …

make `title` available to templates for ref properties

---

.mvn/extensions.xml
.mvn/gradle-enterprise.xml

Simplify Develocity configuration by using the [Develocity build cache connector](https://docs.gradle.com/enterprise/maven-extension/#configuring_the_remote_cache).
Cache URL and credentials are not required anymore, the permissions will be checked on the access key provided in the environment
This contributes to fixing the Develocity remote build cache entries not being stored:
https://ge.openapi-generator.tech/scans/performance?performance.metric=avoidanceSavings,avoidanceSavingsRemoteBuildCache&performance.offset=2692&performance.pageSize=256&search.relativeStartTime=P90D&search.timeZoneId=Europe%2FParis
```
```  …

Migrate to Develocity Build Cache connector

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_1/composed-schema.yaml

A `ClassCastException` can happen on OpenAPI 3.1 schemas when they declare both `properties` and `oneOf`, for example:
```yaml
components:
schemas:
Payment:
type: object
properties:
label:
type: string
otherLabel:
type: string
amount:
type: number
oneOf:
- required:
- label
- amount
- required:
- otherLabel
- amount
```
This raises the following exception:
```
java.lang.ClassCastException: class io.swagger.v3.oas.models.media.JsonSchema cannot be cast to class io.swagger.v3.oas.models.media.ComposedSchema (io.swagger.v3.oas.models.media.JsonSchema and io.swagger.v3.oas.models.media.ComposedSchema are in unnamed module of loader 'app')
at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:461)
at org.openapitools.codegen.OpenAPINormalizer.normalizeComponentsSc …
```

Fix `ClassCastException` in `OpenAPINormalizer` on composed schemas

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java

I came across schemas containing NULL as enum item resulting un-compile-able code.
Dependant on #17802 
```
```  …

Add NULL as reserved keyword cpp

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java

(Will be necessary for adding NULL as a reserved keyword)
C++ keywords are case sensitive, I have no idea why were the keywords lowercased
- [ X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD …

[cpp]Do not lowercase the reserved keywords for C++

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

The enum item names were not sanitized against reserved keywords.
I originally faced with this issue with C++ code generation, although (based on the other languages I know) I think it is wise to adopt this sanitization generally for all generated languages.
```
```  …

Prevent enum item names being reserved keywords

---

modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
samples/server/petstore/rust-server/output/multipart-v3/Cargo.toml
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml

This PR grants the rust-server server feature `swagger/multipart_form`.
Currently, if you generate the rust-server, and then include it in another cargo project and only enable the `server` feature (as I was doing for a server specific workload), you will get the following error:
```sh
error[E0433]: failed to resolve: could not find `form` in `multipart`
--> lib/__omit__/src/server/mod.rs:917:58
|
917 |                 let boundary = match swagger::multipart::form::boundary(&headers) {
|                                                          ^^^^ could not find `form` in `multipart`
```
 
this is because with default features turned on, the server dependencies are able to piggy-back off of the client enabling `swagger/multipart_form`. Resolving this by enabled it for the server as well. …

Provide rust-server `swagger/multipart_form`

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ErlangProperCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java

This PR adds the `hasReadOnly` property to CodegenModel when it has at least one read-only property.
I ran into the same problem as #4190 with typescript-fetch generator. One solution can be using `Omit` to exclude read-only properties.
Given the following the OpenAPI schema and operation definition.
```yaml
title: Task
type: object
properties:
id:
type: integer
readOnly: true
title:
type: string
```
```yaml
post:
operationId: createTask
requestBody:
required: true
content:
schema:
$ref: Task.yml
...
```
typescript-fetch generator generates the following code, which always requires an `id` property on request. But we don't need an `id` when creating a resource.
```ts
export interface CreateTaskRequest {
task: Task;
}
```
With `hasReadOnly` property, we can rewrite the …

Add hasReadOnly property to CodegenModel

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml
samples/client/petstore/java/okhttp-gson/api/openapi.yaml

Better handling of allOf in requests/responses 
```
``` 

Better handling of allOf in requests/responses

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache
samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/JSON.java
samples/client/others/java/okhttp-gson-oneOf/src/main/java/org/openapitools/client/JSON.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/JSON.java

Make initializer block for GSON builder static, see #16860
* Fixes #16860
* I tested the changes locally with an openapi file from our project and it works as expected. The static is called and e.g. `JSON.deserialize` can be used without having to call `new JSON()`
```
``` 
- @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

[okhttp-gson] Make initializer block for GSON builder static #16860

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/auth/ApiErrorDecoder.mustache
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/auth/ApiErrorDecoder.java
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/auth/ApiErrorDecoder.java

fix(java):  resolve feign ambiguity in ApiErrorDecoder fix(#17842)

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/pom.mustache
samples/client/echo_api/java/feign-gson/pom.xml
samples/client/petstore/java/feign-no-nullable/pom.xml
samples/client/petstore/java/feign/pom.xml

update feign to `13.2.1`
```
``` 
cc
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) …

[java] Update feign to newer version: 13.2.1

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_1/composed-schemas-with-and-without-type.yaml

Composed schema request bodies (using `oneOf`, `anyOf`, `allOf`) with `type:object` currently fall within an edge case which causes generation to fail and in place where we should be generating `ParamName` or `Type ParamName` we instead get `UNKNOWN_PARAM_NAME`. 
Example of bad generation
```
/*
* @param UNKNOWN_PARAM_NAME  (optional)
* @throws ApiException if fails to make API call
*/
public void petsPatch( UNKNOWN_PARAM_NAME) throws ApiException {
Object localVarPostBody = UNKNOWN_PARAM_NAME;
```
The additional check for composed schema's catches this edge case and ensures that the generation is correct
```
/*
* @param petsPatchRequest  (optional)
* @throws ApiException if fails to make API call
*/
public void petsPatch(PetsPatchRequest petsPatchRequest) throws ApiException {
Object …
```

[JAVA] Fix 3.1 generation for composed schema's with object type

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java

Fixes #16818 
``EntityUtils#toString`` automatically selects the correct encoding based on the received request.
``Scanner`` currently uses the JVM default encoding, which doesn't always work.
```
```  …

[Java][apache-httpclient] Use ``EntityUtils#toString`` instead of ``Scanner`` for deserialization

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinServerCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java

- use correct `@Test` import - from TestNG instead of JUnit - in `KotlinServerCodegenTest` and `PostmanCollectionCodegenTest`
Previously, tests in these two classes were not run by TestNG.
- add missing slash to file path in `KotlinServerCodegenTest`
- use "\n" line endings in `PostmanCollectionCodegen`, regardless of operating system
```
``` 
You may regenerate an individual generator by passing …

fix KotlinServerCodegenTest and PostmanCollectionCodegenTest

---

docs/customization.md

Fix a typo in the docs.
```
``` 

fix: typo in docs

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java

Since the `AbstractJavaCodegen` does not call super in `toModelName`, this PR copies the `modelNameMappings` lookup
from `DefaultCodegen` to the start of that function. With this change, the `modelNameMappings` configuration key 
starts working, including recommendations to use it for anonymous internal schemas.
fixes #17189
```
```  …

[java] Use modelNameMappings if provided

---

docs/generators/go.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java

The Go generator docs are a bit out-of-date and don't reflect the current capabilities of the generator.  This updates the docs to mark certain features as supported; there may be other differences between the docs and real generator support, but what I've updated here reflects the features I have personally observed as working.
cc/ @wing328 
```
```  …

[Go] Update generator docs to reflect supported features

---

modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
samples/client/petstore/c/model/order.c
samples/client/petstore/c/model/pet.c

fix #17513 
This changes the template for enums to use their NULL value as a default. I have also regenerated the sample code.
This is potentially more breaking than my previous change but without the fix the code doesn't work.
@zhemant
@ityuhui
@michelealbano
```
```  …

[C][Client] Fix default enum value being -1

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
modules/openapi-generator/src/main/resources/csharp/api.mustache
modules/openapi-generator/src/main/resources/csharp/libraries/generichost/api.mustache
modules/openapi-generator/src/main/resources/csharp/libraries/httpclient/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpClientCodegenTest.java

Partial implementation of https://github.com/OpenAPITools/openapi-generator/issues/16547
If ``autosetConstants`` is set to True, the generated code by C# generator will hardcode values for any Header / Query Param which is marked as required and can only have a single valid enum value.
The single valued required enum i.e. The constant param will be removed from the method signature.
A test case has been added that asserts that if ``autosetConstants`` is set to true then the constant key/value pair is being set in the generated code.
I've run ``./bin/generate-samples.sh`` and there is no change in existing code generation if the new ``autosetConstants`` property is not set, Therefore there should not be any risk in getting this change merged.

Autoset constants (Required fields having single valid enum value) C# Implementation of #16547

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator-maven-plugin/src/test/java/org/openapitools/codegen/plugin/CodeGenMojoTest.java

Fix #16955 : inputSpec should not be mandatory if inputSpecRootDirectory is set
(@borsch @wing328 )
```
```  …

inputSpec should not be mandatory when inputSpecRootDirectory is set

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api.module.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api.module.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/user.service.ts

Addresses fix #17671 
A quick pass over the nullability issues reported by the tsc `strict` flag. Does not solve all issues - for example, the `queryParameters` still have one branch where they are accessed by index rather than with `.append`
@macjohnny hope you don't mind being pinged here

[typescript-nestjs] Compatability with tsc 'strict' flag

---

website/blog/2018-12-24-new-website.md

https://docusaurus.io/en returns 404, removing `/en` fixes it.

Update 2018 Blog Post broken link

---

pom.xml

The build has some cache misses when run twice without any change (on a fresh clone). The cost here is 10s of wall clock time:
The problem is that the file `modules/openapi-generator-maven-plugin/src/test/resources/default/_merged_spec.yaml` generated by the `maven-plugin` module tests is located in the `src/test/resources` folder which is used as goal input by `compiler:testCompile` and `surefire:test` from the `maven-plugin` module.
This means that the cache key is different, therefore the cache misses.
Clone the project in a new location
```
git clone git@github.com:OpenAPITools/openapi-generator.git /tmp/openapi-generator
cd /tmp/openapi-generator
```
The best solution would be to generate the `_merged_spec.yaml` in the `target` directory, …

Ignore _merged_spec.yaml when computing build cache key

---

docs/templating.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/UncamelizeLambda.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/mustache/UncamelizeLambdaTest.java

New `uncamelize` lambda that converts the input string from camelCase/PascalCase to a string of whitespace separated words. For example `inputText` to `Input Text`.
```
```  …

Add new uncamelize lambda (#18097)

---

modules/openapi-generator/src/main/resources/python-pydantic-v1/model_generic.mustache
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/models/map_of_array_of_model.py
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/models/unnamed_dict_with_additional_model_list_properties.py
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/models/unnamed_dict_with_additional_string_list_properties.py
samples/openapi3/client/petstore/python-pydantic-v1/petstore_api/models/map_of_array_of_model.py
samples/openapi3/client/petstore/python-pydantic-v1/petstore_api/models/unnamed_dict_with_additional_model_list_properties.py
samples/openapi3/client/petstore/python-pydantic-v1/petstore_api/models/unnamed_dict_with_additional_string_list_properties.py
samples/openapi3/client/petstore/python-pydantic-v1/tests/test_model.py

This PR applies the changes made by #16779 to pydantic-v1.
It fixes #18096, but with a different approach than #18110.
```
```  …

[python-pydantic-v1] Fix unnamed dicts with additional properties

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache

Whenever providing a boolean field in a form-data file upload, generated library is not doing any conversion causing the following error being raised: _TypeError: data should be a string, Buffer or Uint8Array_
Expected:
```typescript
localVarFormParams.append('validate_image_quality', String(validateImageQuality) as any);
```
Received:
```typescript
localVarFormParams.append('validate_image_quality', validateImageQuality as any);
```
```
``` 
These must …

fix(typescript-axios): Serialize boolean to string in form-data file upload (#18083)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
samples/client/petstore/typescript-fetch/builds/allOf-readonly/models/Club.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/HasOnlyReadOnly.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Name.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/ReadOnlyFirst.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/HasOnlyReadOnly.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/Name.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/ReadOnlyFirst.ts

Related to:  #4190  
This PR omits readOnly properties from request models. Given the following OpenAPI schema and operation.
```yaml
title: Task
type: object
properties:
id:
type: integer
readOnly: true
title:
type: string
```
```yaml
post:
operationId: createTask
requestBody:
required: true
content:
schema:
$ref: Task.yml
...
```
The current generated request models require the unneeded `id` property.
```js
export interface CreateTaskRequest {
task: Task;
}
```
This PR changes them to:
```js
export interface CreateTaskRequest {
task: Omit<Task, 'id'>;
}
```
To technical committee: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) …

[typescript-fetch] Omit readOnly properties from request models

---

docs/customization.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_0/setContainerToNullable_test.yaml

Add rule to set container (array, set, map) to true
```
```  …

Add rule to set container (array, set, map) to true

---

.github/workflows/samples-postman.yaml
README.md

Trigger workflow when there's a change to postman.json
cc @gcatanese
```
``` 

Trigger workflow when there's a change to postman.json

---

modules/openapi-generator/src/main/resources/r/ApiResponse.mustache
samples/client/echo_api/r/R/api_response.R
samples/client/petstore/R-httr2-wrapper/R/api_response.R
samples/client/petstore/R-httr2/R/api_response.R
samples/client/petstore/R/R/api_response.R

```
``` 
Breaking up PR https://github.com/OpenAPITools/openapi-generator/pull/18108 into …

[R][Client] Allow API response to be NULL

---

modules/openapi-generator/src/main/resources/typescript-axios/common.mustache
samples/client/echo_api/typescript-axios/build/common.ts
samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/common.ts
samples/client/petstore/typescript-axios/builds/composed-schemas/common.ts
samples/client/petstore/typescript-axios/builds/default/common.ts
samples/client/petstore/typescript-axios/builds/es6-target/common.ts
samples/client/petstore/typescript-axios/builds/test-petstore/common.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/common.ts
samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/common.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/common.ts
samples/client/petstore/typescript-axios/builds/with-node-imports/common.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/common.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/common.ts
samples/client/petstore/typescript-axios/builds/with-single-request-parameters/common.ts
samples/client/petstore/typescript-axios/builds/with-string-enums/common.ts

This produces type definitions that aren't compatible with the typescript-axios client:
```openapi
someField:
uniqueItems: true
type: array
items:
type: string
```
My fix serialises of `Set`s into arrays and `Map`s into objects, since otherwise they are not serialized with JSON.stringify, see https://stackoverflow.com/questions/31190885/json-stringify-a-set
```
```  …

Fix: Always serialise Map and Set to object and array in typescript-axios

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/postman-collection/SampleProject.yaml
samples/schema/postman-collection/postman.json
samples/schema/postman-collection/python/test/test_endpoints.py

Process request examples that include `array`  to create a valid Postman request that sends a list of values.
```
```  …

[POSTMAN] Process request with array of string

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelEnum.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/EnumClass.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnum.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumInteger.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumIntegerDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/SingleRefType.ts
samples/client/petstore/typescript-fetch/builds/enum/models/NumberEnum.ts
samples/client/petstore/typescript-fetch/builds/enum/models/StringEnum.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/BehaviorType.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/DeploymentRequestStatus.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/ErrorCode.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/PetPartType.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/WarningCode.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/EnumClass.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnum.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumInteger.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumIntegerDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/SingleRefType.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/NumberEnum.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/StringEnum.ts

I'm using Django REST Framework + DRF Spectacular to automatically generate OpenAPI 3 schemas for my APIs.
When defining nullable enums, the API generator `typescript-fetch` creates code that doesn't compile properly with two errors: 
* Spread types may only be created from object types (on `FromJSONTyped` functions).
* Module '"./BlankEnum"' has no exported member 'instanceOfBlankEnum' (enum templaces don't export function used by other API client files).
There's a problem generating `typescript-fetch` API clients using schemas containing `oneOf` and Enums.
Some parts of the API client seem to rely on the `instaceOf{{classname}}`, not provided for enum models.
Also, the code tries to create spread types from function types, leading to a TS compilation error.
_I'm not sure this is the …

fix: Fix schema generation for `oneOf` when using TS-FETCH client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

Fixes #18095 | [REQ][JAVA] - [QA] How not to generate "pattern" and "size" for UUID
Prevent generating "pattern" and "size" to special formats of string type:
- bytes[]    (added earlier)
- File         (added earlier)
- UUID      (new)
- URI         (new)
To be precise, it prevents to generate any kind of annotation on these types using the generator. It is still possible to put annotations onto them with mustache templates.
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg (2023/08)
```
```  …

#18095 | Prevent generating "pattern" and "size" to special formats of string type

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java

For consistency across generators we should allow specifying the value of the useJavaEE in the same way as for instance in the jaxrs-spec (Java)
```
```  …

[Kotlin] Should parse boolean value for useJavaEE as this is done elsewhere

---

modules/openapi-generator/src/main/resources/r/modelEnum.mustache
samples/client/echo_api/r/R/string_enum_ref.R

```
``` 
`modelEnum.mustache` currently produces classes that do not allow initialization as …

[R][Client] allow to initialize enum classes without parameters

---

modules/openapi-generator/src/main/resources/Java/maven.yml.mustache
modules/openapi-generator/src/main/resources/java-helidon/client/libraries/se/maven.yml.mustache
modules/openapi-generator/src/main/resources/r/r-client.mustache

```
``` 
Hi
I have updated the github mustache template for maven.yml and r-client for use the …

Upgrade github actions

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api/auth_api.py
samples/client/echo_api/python/openapi_client/api/auth_api.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/store_api.py
samples/openapi3/client/petstore/python/petstore_api/api/store_api.py

Fix for issue https://github.com/OpenAPITools/openapi-generator/issues/18088
In [AbstractPythonCodegen.java](https://github.com/OpenAPITools/openapi-generator/compare/master...zishunwei:fix_issue18088?expand=1#diff-33d3885e6c425e1c0c91281031bfdfe3d0b7d016d92c44a4c962c4fef5f900d3) , if we `new PythonImports();` in the method `getPydanticType`, the module imports can not be updated and stored in external variable `moduleImports` defined in `postProcessOperationsWithModels`. 
So it is a bug causing all typing imports for operation return type are not updated as we expected. 
It is supposed to pass the variable `moduleImports` into the method  `getPydanticType` directly, then we can see the imports for operation return type are generated well in the python binding by my testing.
```
./mvnw …
```

Fix issue 18088: Missing the important statement for Datetime in Python binding generation

---

modules/openapi-generator/src/main/resources/r/api.mustache
samples/client/petstore/R-httr2-wrapper/R/pet_api.R
samples/client/petstore/R-httr2/R/pet_api.R

```
``` 
Breaking up PR https://github.com/OpenAPITools/openapi-generator/pull/18108 into …

[R][Client] fix brackets for httr2 file_params

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Previously the extending of models when instantionTypte('map') was not set for language looked like this: `class ProductData extends null<String, ProductDataBase>`, this is not correct, it should look like this? `class ProductData extends ProductDataBase`. This PR fixes that.
```
```  …

Fix: in typescript fixes additionalProperties handling when extending models

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache

A misplaced parenthesis let to a syntax error when generating the code for a nullable set in the FromJSONTyped function. By moving the parenthesis to the correct place the syntax error was resolved in my case, I did not test for all combinations though. 
```
```  …

typescript-fetch: Move parenthesis to correct place

---

modules/openapi-generator/src/main/resources/kotlin-server/data_class.mustache

Ran into the issue https://github.com/OpenAPITools/openapi-generator/issues/14710 as well. The kotlin-spring template is very similar but [includes a conditional](https://github.com/OpenAPITools/openapi-generator/blob/84b3cd9962c033bfb9ce0f4832ac006f26f39b75/modules/openapi-generator/src/main/resources/kotlin-spring/dataClass.mustache#L8) using `#hasVars` which controls whether a regular or a data class is generated.
AFAICT that variable comes in somewhere via the `CodegenModel` since the `KotlinSpringServerCodegen` doesn't specify it explicitly.
Comittee members: @jimschubert, @dr4ke616, @karismann, @Zomzog, @andrewemery, @4brunu, @yutaka0m, @stefankoppier

fix[kotlin]: only use data class when it has constructor vars

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_1/issue_18184.yaml

- Fix #18184
- Add a test
```
``` 

Check nullable to detect null type in 3.1 spec

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ClojureClientCodegen.java

Fixes #18199.
- [] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
```
```  …

[Clojure] Handle both types of additional properties when getting type declaration

---

modules/openapi-generator/src/main/resources/php-slim4-server/README.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/abstract_authenticator.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/index.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/register_routes.mustache
samples/server/petstore/php-slim4/README.md
samples/server/petstore/php-slim4/lib/App/RegisterRoutes.php
samples/server/petstore/php-slim4/lib/Auth/AbstractAuthenticator.php
samples/server/petstore/php-slim4/public/index.php

In php-slim4 - The authorization types are picked, just they are not added to routes middlewares, this PR fixes that.
fix: added middleware adding for authorization methods, added unauthorized handler to authorization abstract, fixes #18031
Tested with real application, working.
```
```  …

#18031 Fix: added middleware adding for authorization methods [php-slim4]

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml
samples/client/petstore/java/okhttp-gson/README.md
samples/client/petstore/java/okhttp-gson/api/openapi.yaml
samples/client/petstore/java/okhttp-gson/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java

- properly dereference requestbodies when handling form payload
- add tests
```
```  …

Fix reference to request bodies in form content type

---

modules/openapi-generator/src/main/resources/Java/libraries/native/anyof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/oneof_model.mustache

fix #17895
oneOf and anyOf models generated for `native` library contain invalid code if they implement interfaces.
To fix this I copied the equivalent line from the `okhttp-gson` library template.
```
```  …

[JAVA][NATIVE] fix `implements` in oneOf/anyOf #17895

---

CI/circle_parallel.sh
modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache
modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
modules/openapi-generator/src/main/resources/ruby-client/gemspec.mustache
samples/client/echo_api/ruby-faraday/lib/openapi_client/api_client.rb
samples/client/echo_api/ruby-faraday/openapi_client.gemspec
samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
samples/client/petstore/ruby-faraday/petstore.gemspec

The fix made in #17853 introduced requiring a native gem, [ruby-filemagic](https://rubygems.org/gems/ruby-filemagic).  
Installing FileMagic library just to detect content-type is not a pleasant approach and I think [marcel](https://rubygems.org/gems/marcel) is the way we should go in 2024.
```
```  …

[ruby] Use Marcel to detect content-type in form-data file upload using faraday

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/inner_enum.yaml

fix #17999
If there are (only) inline enums and `RESOLVE_INLINE_ENUMS` is set, no EnumConverterConfiguration.java is generated. This PR fixes this.
The problem was that we checked for the existence of non-inline enums before `RESOLVE_INLINE_ENUMS` took effect. So I moved the check for those enums to a later point.
```
```  …

[SPRING BOOT] generate EnumConverterConfiguration for resolved inline enums

---

docs/customization.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_0/setPrimitiveTypesToNullable_test.yaml

Add rule to set primitive types to nullable
e.g.
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/java-okhttp/ --openapi-normalizer SET_PRIMITIVE_TYPES_TO_NULLABLE="integer|number"
```
```
```  …

Add rule to set primitive types to nullable

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_0/simplifyOneOfAnyOf_test.yaml

add logic to simplify any type represented with oneof/anyof
add tests
```
```  …

Add logic to simplify any type represented with oneof/anyof

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pojo.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/oneof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/pojo.mustache
samples/client/others/java/jersey2-oneOf-Mixed/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/jersey2-oneOf-duplicates/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/Fruit.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/FruitReq.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/Mammal.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/NullableShape.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/Pig.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/Quadrilateral.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/Shape.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/ShapeOrNull.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/Triangle.java
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/model/Pet.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/model/Pet.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/ObjectWithDeprecatedFields.java

a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/18042
```
``` 

[Java] Sync jersey2 jersey3 template

---

modules/openapi-generator/src/main/resources/swift5/APIHelper.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/anycodableLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/APIHelper.swift
samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/APIHelper.swift

Currently query items in a request have random ordering that can change with every request.
For example we see
`/geolocations?latitude=52.519&longitude=13.408`
and
`/geolocations?longitude=13.408&latitude=52.519`
To allow caching based on same URLs this PR takes care of ordering the query items alphabetically.
This should not have any impact on backward compatibility, because no installation will require a random ordering.
@dydus0x14
```
``` 
These must …

SWIFT5: sort query items alphabetically to allow better server side caching of requests with same URL

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JetbrainsHttpClientClientCodegen.java

- skip warnings by overriding escapeUnsafeCharacters, escapeQuotationMark
cc @jlengrand 
```
```  …

Skip warning, better code format for jetbrain http client generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java

Stop escaping string enum values in the kotlin generator (#18107)
These values are arbitrary strings and shouldn't be manipulated, but currently get run through the same escape logic as the generated names for such values. I've updated the tests here to assert that the generate name is still appropriately escaped safely while leaving the values raw as intended.
See also #18107 for reproduction YAML.
```
```  …

Kotlin: Do not escape/sanitize quoted enum values

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java

PR to process boolean fields
```
``` 
@wing328

[POSTMAN] Deal with boolean fields

---

docs/generators/groovy.md
docs/generators/java-camel.md
docs/generators/java-helidon-client.md
docs/generators/java-helidon-server.md
docs/generators/java-inflector.md
docs/generators/java-micronaut-client.md
docs/generators/java-micronaut-server.md
docs/generators/java-msf4j.md
docs/generators/java-pkmst.md
docs/generators/java-play-framework.md
docs/generators/java-undertow-server.md
docs/generators/java-vertx-web.md
docs/generators/java-vertx.md
docs/generators/java-wiremock.md
docs/generators/java.md
docs/generators/jaxrs-cxf-cdi.md
docs/generators/jaxrs-cxf-client.md
docs/generators/jaxrs-cxf-extended.md
docs/generators/jaxrs-cxf.md
docs/generators/jaxrs-jersey.md
docs/generators/jaxrs-resteasy-eap.md
docs/generators/jaxrs-resteasy.md
docs/generators/jaxrs-spec.md
docs/generators/spring.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

"==" enum value generates "_" in Java which is invalid since Java 9 
to fixes https://github.com/OpenAPITools/openapi-generator/issues/17276
based on https://github.com/OpenAPITools/openapi-generator/pull/17278
```
``` 
IMPORTANT: Do …

"==" enum value generates "_" in Java which is invalid since Java 9

---

modules/openapi-generator/src/main/resources/kotlin-spring/dataClass.mustache

Added the missing additionalModelTypeAnnotations for the Kotlin data class generator
```
``` 

[kotliln-spring] Update dataClass.mustache

---

modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
samples/client/petstore/swift5/anycodableLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
samples/client/petstore/swift5/validation/Package.resolved
samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift

UTTypeCopyPreferredTagWithClass is deprecated with iOS 15, so apps targeting iOS 15+ were getting this warning on any auto-generated code. This solution will solve that warning and works both iOS 15 and below.
- URLSessionImplementations.swift:563:22 'UTTypeCreatePreferredIdentifierForTag' was deprecated in iOS 15.0: Use the UTType class instead.
- URLSessionImplementations.swift:563:60 'kUTTagClassFilenameExtension' was deprecated in iOS 15.0: Use UTTagClassFilenameExtension instead.
- URLSessionImplementations.swift:564:32 'UTTypeCopyPreferredTagWithClass' was deprecated in iOS 15.0: Use the UTType class instead.
- URLSessionImplementations.swift:564:69 'kUTTagClassMIMEType' was deprecated in iOS 15.0: Use UTTagClassMIMEType instead.
``` …
```

[swift] Added solution for deprecated "UTTypeCopyPreferredTagWithClass"

---

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/AuthApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/BodyApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/FormApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/HeaderApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/PathApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/QueryApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/DefaultApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/DefaultApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java

to fix https://github.com/OpenAPITools/openapi-generator/pull/17736 due to the use of GenericType
```
```  …

[java][native] use type reference instead to fix compilation issue in JDK11

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptApolloClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java

And prefer example over default
This is #2669 but for JavaScript.
@CodeNinjai @frol @cliffano
```
```  …

[javascript] fix docs example quoting, fixes #6324

---

modules/openapi-generator/src/main/resources/typescript-node/package.mustache
samples/client/petstore/typescript-node/npm/package.json

Use latest versions for `bluebird` and `request` and remove `rewire`. `rewire` has high security alerts in Github security alerts as it depends on `json5` (https://nvd.nist.gov/vuln/detail/CVE-2022-46175) and shouldn't have been added to the generated clients as its used in tests. It was introduced here https://github.com/OpenAPITools/openapi-generator/commit/960412a9b4b60c597ebab5b11871b5848f5c97cb#diff-1df884eca4890fc2cff7eec6f61ac2157b1b9e72fe4cc13c782e300125fb0da3R20 although the same commit shows that it used to work without it https://github.com/OpenAPITools/openapi-generator/commit/960412a9b4b60c597ebab5b11871b5848f5c97cb#diff-d2785da28187b6d6ef1e0bdab42139309e443906fb5d9d365fce5e2a01673ef5R52-R56
Typescript technical committee: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas …

Update versions for typescript-node and remove vulnerable test package

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/AWS4Auth.mustache
samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-oneOf/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/auth/AWS4Auth.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

Adds support for AWS Temporary credentials (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html).
Involves adding to AWS4Auth.mustache
public void setCredentials(String accessKey, String secretKey, String sessionToken)
and
ApiClient.mustache
public void setAWS4Configuration(String accessKey, String secretKey, String sessionToken, String region, String service)
- [ X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ X] Run the following to [build the …

#18252 - [REQ] add sessionToken support to AWS4Auth

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_1/simplifyOneOfAnyOf_test.yaml

- Fix null check in 3.1 spec
- add getType method in modeltuils to support both 3.0 and 3.1 spec
```
```  …

Fix null check in 3.1 spec

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaCaskServerCodegen.java

This small change fixes an issue with the recently added scala-cask generator for cases where there are a single route.
In this case, the route annotation would be elided, e.g.:
```
("")
def createContract(request: cask.Request) = ...
```
``` …
```

scala cask fix for missing annotations on simple routes

---

modules/openapi-generator/src/main/resources/scala-cask/apiRoutes.mustache
samples/server/petstore/scala-cask/src/main/scala/sample/cask/api/PetRoutes.scala
samples/server/petstore/scala-cask/src/main/scala/sample/cask/api/StoreRoutes.scala
samples/server/petstore/scala-cask/src/main/scala/sample/cask/api/UserRoutes.scala

Fix for scala cask service responses to handle where there are zero or more defined response types
```
``` 
Commit all …

cask fix for response encoding

---

modules/openapi-generator/src/main/resources/php-symfony/Controller.mustache
modules/openapi-generator/src/main/resources/php-symfony/api_controller.mustache
modules/openapi-generator/src/main/resources/php-symfony/composer.mustache
modules/openapi-generator/src/main/resources/php-symfony/serialization/JmsSerializer.mustache
modules/openapi-generator/src/main/resources/php-symfony/testing/ControllerTest.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/Controller.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/PetController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/StoreController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/UserController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Service/JmsSerializer.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Tests/Controller/ControllerTest.php
samples/server/petstore/php-symfony/SymfonyBundle-php/composer.json

- add Symfony 7 support
- remove support php < 8.2 (EOL)
- remove symfony < 6.4 support
Bug Fix
- add missing $security{{name}} variable when using Bearer Auth (https://github.com/Catrobat/Catroweb-API/pull/143/files#r1561127625)
Misc
- The getContentType method is deprecated; use getContentTypeFormat instead. (Since: symfony/http-foundation', '6.2' deprecated // https://github.com/symfony/symfony/blob/7.1/UPGRADE-7.0.md)
- use match instead of a switch for simple assignments
- remove default depth param from json_encode call (`function json_encode(mixed $value, int $flags = 0, int $depth = 512): string|false {}`)
- make data provider static  - PHPUnit (https://github.com/sebastianbergmann/phpunit/commit/9caafe2d49b33a21f87db248a8ad6ca7c7bdac09)
``` …
```

[php-symfony] Allow Symfony 7 / Remove EOL PHP / Bearer Fix

---

modules/openapi-generator/src/main/resources/go/model_simple.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/go/allof_multiple_ref_and_discriminator.yaml

Currently, when the "FinalItem" is a composite schema the parent is not added. 
It seems this is done to handle the "additionalProperties".
My proposal is for this to work for "isMap" schemas and use the parentModel.name which for the items with additionalProperties would be null anyway. 
@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5 
To close https://github.com/OpenAPITools/openapi-generator/issues/18385

Go generate all of with multiple ref and discriminator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
samples/client/petstore/csharp/generichost/net8/FormModels/src/Org.OpenAPITools/Model/OneOfString.cs
samples/client/petstore/csharp/generichost/net8/FormModels/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/Model/OneOfString.cs
samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
samples/client/petstore/csharp/generichost/net8/Petstore/src/Org.OpenAPITools/Model/OneOfString.cs
samples/client/petstore/csharp/generichost/net8/Petstore/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/Model/OneOfString.cs
samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
samples/client/petstore/csharp/generichost/standard2.0/Petstore/src/Org.OpenAPITools/Model/OneOfString.cs
samples/client/petstore/csharp/generichost/standard2.0/Petstore/src/Org.OpenAPITools/Model/PolymorphicProperty.cs

This is the first step towards adding support for primitive types in composed schemas for generichost library. The problem being fixed is that properties that are composed properties have a different naming convention than the other model properties, which created a downstream issue when improving composed schema support.
```
```  …

[csharp] Fixed property naming convention for composed types

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java

Fix string comparison in haskell servant generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_1/reusable-components-without-paths.yaml

@mkusaka Can I get a review for this bug fix, 🙏  please?
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/18207
If you use an OpenAPI 3.1.0 schema without `paths`, the `typescript-fetch` generator produces a broken package. The root index file `index.ts` is:
```ts
/* tslint:disable */
/* eslint-disable */
export * from './runtime';
export * from './models/index';
```
but there isn't any `./models/index`.
Therefore Typescript gives this error:
> Cannot find module './models/index' or its corresponding type declarations. ts(2307)
`./models/index` is generated in the `TypeScriptFetchClientCodegen.postProcessOperationsWithModels` method ([ref](https://github.com/OpenAPITools/openapi-generator/blob/34ebc1c644f2072b4eb9caaabbb8f96c374249d1/modules/openapi-generator/src/main/java/o …

[TS-FETCH] Generate `models/index.ts` in `postProcessModels`

---

CONTRIBUTING.md

This adds instructions for building the binary to the Contributing guide without needing to run all the tests. The information is useful for new contributors who are not necessarily familiar with the Java ecosystem.
```
```  …

docs: add instruction for building the binary

---

modules/openapi-generator/src/main/resources/scala-cask/build.sbt.mustache
samples/server/petstore/scala-cask/build.sbt

This change fixes the published artefact names for both JS and JVM artefacts, where previously the 'ThisBuild / name' apparently didn't get read, leaving the published artefacts to be 'app'.
```
``` 
(For …

fix for the artefact names in scala cask

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache

This commit fixes an issue where enums are used as a value in either path or query params due to relying on string casting.
With this change, enum values are requested by using `.value` instead.
Solves #18236
```
``` 
IMPORTANT: Do …

[kotlin-multiplatform] Fix enum value issues in path or query

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java

Closes: https://github.com/OpenAPITools/openapi-generator/issues/17597
@jimschubert, @dr4ke616, @karismann, @Zomzog, @andrewemery, @4brunu, @yutaka0m, @stefankoppier
```
```  …

[BUG][Kotlin] Fix wrong type- and importMapping for kotlinx.date (#17597)

---

modules/openapi-generator/src/main/resources/csharp/HttpSigningConfiguration.mustache
samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/unityWebRequest/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs

HttpSigningConfiguration class provides the HttpSigned header which is used for httpSIgning Authentication. the function GetHttpSignedHeader of the class HttpSigningConfiguration was declared with access specifier internal which restrict user to get the signed header outside the assembly. to make the developer life easy and use the HttpSigningConfiguration class as utlity for httpSigning I have made the function to public so that it can be accessed outside assembly.
to close https://github.com/OpenAPITools/openapi-generator/pull/18481
```
```  …

[C#] made the HttpSigning method public to get the signed header.

---

.devcontainer/devcontainer.json

Inside a new devcontainer, I got a `/usr/local/sdkman/candidates/java/11.0.23-ms/` path, but the settings in devcontainer.json referred to ...11.0.16.1-ms, causing errors in VSCode. This updates the path to a more stable one. 
```
```  …

Use the current Java version in devcontainer.json.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_0/simplifyOneOfAnyOf_test.yaml

to fix https://github.com/OpenAPITools/openapi-generator/issues/18497
```
``` 
fyi …

Fix null type check when simplifying any type

---

bin/utils/dart-keywords/README.md
bin/utils/dart-keywords/dart-version.txt
bin/utils/dart-keywords/pubspec.lock
bin/utils/dart-keywords/pubspec.yaml
bin/utils/dart-keywords/save-dart-keywords.dart
bin/utils/dart-keywords/save_dart_keywords.sh
docs/generators/dart-dio.md
docs/generators/dart.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
modules/openapi-generator/src/main/resources/dart/dart-keywords.txt
modules/openapi-generator/src/main/resources/dart/libraries/dio/pubspec.mustache
modules/openapi-generator/src/main/resources/dart2/pubspec.mustache
samples/openapi3/client/petstore/dart-dio/oneof/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/oneof_primitive/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml
samples/openapi3/client/petstore/dart2/petstore_client_lib/pubspec.yaml
samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/pubspec.yaml

Support Dart3 SDK.
cc tech:
```
```  …

[dart] [dart-dio] Support Dart3

---

modules/openapi-generator/src/main/resources/php-flight/register_routes.mustache
modules/openapi-generator/src/main/resources/php-flight/register_routes_test.mustache
samples/server/petstore/php-flight/RegisterRoutes.php
samples/server/petstore/php-flight/Test/RegisterRoutesTest.php

For the php-flight server generator, there was a bug when parsing models - should have tested more thoroughly in the first place - sorry for that!
@jebentier , @dkarlovi , @mandrean , @jfastnacht , @ybelenko , @renepardon 
```
```  …

[php-flight] fix: parsing class/enum models

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java
modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml
samples/client/petstore/csharp/generichost/net8/FormModels/api/openapi.yaml
samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/api/openapi.yaml
samples/client/petstore/csharp/generichost/net8/Petstore/api/openapi.yaml
samples/client/petstore/csharp/generichost/net8/SourceGeneration/api/openapi.yaml
samples/client/petstore/csharp/generichost/standard2.0/Petstore/api/openapi.yaml
samples/client/petstore/csharp/httpclient/standard2.0/Petstore/api/openapi.yaml
samples/client/petstore/csharp/restsharp/net4.7/Petstore/api/openapi.yaml
samples/client/petstore/csharp/restsharp/net4.8/Petstore/api/openapi.yaml
samples/client/petstore/csharp/restsharp/net7/EnumMappings/api/openapi.yaml
samples/client/petstore/csharp/restsharp/net7/Petstore/api/openapi.yaml
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/api/openapi.yaml
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/api/openapi.yaml
samples/client/petstore/csharp/unityWebRequest/standard2.0/Petstore/api/openapi.yaml

Fixes example generator when using composed child schemas on `allOf` as well as `array` type schemas.
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/18443
```
```  …

fix: ExampleGenerator for composed child schemas and array schemas

---

modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache
modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift
samples/client/petstore/swift5/anycodableLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift

This PR add's support for `application/json` content type variants like:
- `application/vnd.api+json`
- `application/ld+json`
- `application/*+json`
```
```  …

[swift] support content type application json variants

---

modules/openapi-generator/src/main/resources/php-nextgen/ObjectSerializer.mustache
modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
modules/openapi-generator/src/main/resources/php/libraries/psr-18/api.mustache
samples/client/echo_api/php-nextgen/src/ObjectSerializer.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/lib/ObjectSerializer.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ObjectSerializer.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/test/ObjectSerializerTest.php
samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/OpenAPIClient-php/tests/ObjectSerializerTest.php
samples/client/petstore/php/psr-18/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/psr-18/lib/Api/DefaultApi.php
samples/client/petstore/php/psr-18/lib/Api/FakeApi.php
samples/client/petstore/php/psr-18/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/psr-18/lib/Api/PetApi.php
samples/client/petstore/php/psr-18/lib/Api/StoreApi.php
samples/client/petstore/php/psr-18/lib/Api/UserApi.php
samples/client/petstore/php/psr-18/lib/ObjectSerializer.php

This allows users to use APIs that require booleans in query params not to be cast to int, e.g. `&foo=true`. Currently, `true` is cast to `1` so it's passed as `&foo=1`. That might not be supported by the target API.
The fix contains copy-pasted function from guzzlehttp/psr7 `Query::build()` with minor tweaks.
https://github.com/guzzle/psr7/blob/540ec79fb2f2e96591febb0de464bc16ac2ea341/src/Query.php#L73
Related to https://github.com/OpenAPITools/openapi-generator/issues/2204
There's a proposal by me to include the functionality in guzzlehttp/psr7 https://github.com/guzzle/psr7/pull/603
```
```  …

feat(php): allow to pass raw boolean to api

---

modules/openapi-generator/src/main/resources/scala-sttp4/api.mustache
samples/client/petstore/scala-sttp4/src/main/scala/org/openapitools/client/api/PetApi.scala
samples/client/petstore/scala-sttp4/src/main/scala/org/openapitools/client/api/StoreApi.scala
samples/client/petstore/scala-sttp4/src/main/scala/org/openapitools/client/api/UserApi.scala

```
``` 
This PR solves #15785 for the scala-sttp4 generator.
Rationale for the changes:
- the problem that was tackled in #11949 was not really about default values.
- asUnit[Unit] leads to an error, anyways, so not only with default responses, this is the wrong encoding.
- using asEither(asString, ignore) works, but turns the structured error in Left into a String, shedding information in the process. The "asString.mapWithMetadata(..."-construct allows for empty or garbage response bodies while keeping the Left() information intact.
- asJsonAlwaysUnsafe is gone from sttp for a LONG time. This needed replacement, anyways.

scala-sttp4: fix for issue 15785 api returns unit.

---

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
modules/openapi-generator/src/main/resources/go-server/error.mustache
modules/openapi-generator/src/main/resources/go-server/model.mustache
samples/openapi3/server/petstore/go/go-petstore/go/api_pet.go
samples/openapi3/server/petstore/go/go-petstore/go/api_store.go
samples/openapi3/server/petstore/go/go-petstore/go/api_user.go
samples/openapi3/server/petstore/go/go-petstore/go/error.go
samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_store.go
samples/server/petstore/go-api-server/go/api_user.go
samples/server/petstore/go-api-server/go/error.go
samples/server/petstore/go-chi-server/go/api_pet.go
samples/server/petstore/go-chi-server/go/api_store.go
samples/server/petstore/go-chi-server/go/api_user.go
samples/server/petstore/go-chi-server/go/error.go

Currently when a min/max value for a number field is not respected, the api only returns a generic error message without providing any useful information to fix the request. This commit add the field name to the error message to help the user of the API.

[go-server] add field name in parsing error messages

---

bin/configs/kotlin-jvm-spring-3-webclient-echo-api.yaml
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-restclient/api.mustache
samples/client/echo_api/kotlin-jvm-spring-3-webclient/build.gradle
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/apis/AuthApi.kt
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/apis/BodyApi.kt
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/apis/FormApi.kt
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/apis/HeaderApi.kt
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/apis/PathApi.kt
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/apis/QueryApi.kt
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
samples/client/petstore/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/apis/UserApi.kt

Fixed a warning in kotlin-jvm-spring-restclient. I also noted that a sample was using the incorrect library.
```
```  …

[kotlin][client] fix warning

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Animal.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/ParentWithNullable.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/Animal.ts

This is very similar to https://github.com/OpenAPITools/openapi-generator/issues/6140 and came up in https://github.com/GoogleChrome/chromium-dashboard/pull/3819. I haven't reduced a test case from that PR, but I can if the maintainers here want. I did check that this change removes the circular dependency from https://github.com/GoogleChrome/chromium-dashboard/pull/3819, although getting rid of the cycle requires writing the schema in a way that removes the inheritance from the common base class.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of …

[typescript-fetch] Remove a cycle in the discriminator dependency graph.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java

Using archive.org snapshots in case the URLs change again, like they apparently have in the past.
Also fixing formal JavaDoc error, which does not allow bare URLs. This will become a bit less convoluted in Java 23 – however until then proper anchor tags are required.
```
```  …

Update broken JSON schema links

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelEnum.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/EnumClass.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnum.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumInteger.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumIntegerDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/SingleRefType.ts
samples/client/petstore/typescript-fetch/builds/enum/models/NumberEnum.ts
samples/client/petstore/typescript-fetch/builds/enum/models/StringEnum.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/BehaviorType.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/DeploymentRequestStatus.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/ErrorCode.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/PetPartType.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/WarningCode.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/EnumClass.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnum.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumInteger.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumIntegerDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/SingleRefType.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/NumberEnum.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/StringEnum.ts
samples/documentation/html2/index.html

The `instanceOf{{classname}}` function introduced in 93b76dde371b1e3e111040541ef568a329b62be6 makes use of the [Object.values](https://262.ecma-international.org/8.0/#sec-object.values) function introduced in [ECMAScript 2017](https://262.ecma-international.org/8.0), thus breaking compatibility with prior versions such as ES2016 and ES2015.
This PR suggests an alternate implementation for the `instanceOf{{classname}}` function in the `modelEnum.mustache` template that restores backward-compatibility.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs …

[typescript-fetch] Restore pre-es2017 compatibility in modelEnum template

---

modules/openapi-generator/src/main/resources/rust-server/server-make-service.mustache
modules/openapi-generator/src/main/resources/rust-server/server-operation.mustache
samples/server/petstore/rust-server/output/multipart-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/no-example-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/openapi-v3/src/client/callbacks.rs
samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/ops-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
samples/server/petstore/rust-server/output/ping-bearer-auth/src/server/mod.rs
samples/server/petstore/rust-server/output/rust-server-test/src/server/mod.rs

See #18572.
```
``` 
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh …

Fix #18572 rust server: Silence clippy lints by refactoring

---

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
modules/openapi-generator/src/test/resources/3_0/go-server/petstore.yaml
samples/server/petstore/go-api-server/api/openapi.yaml
samples/server/petstore/go-api-server/go/api.go
samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_pet_service.go
samples/server/petstore/go-api-server/go/api_user.go
samples/server/petstore/go-api-server/go/api_user_service.go
samples/server/petstore/go-chi-server/api/openapi.yaml
samples/server/petstore/go-chi-server/go/api.go
samples/server/petstore/go-chi-server/go/api_pet.go
samples/server/petstore/go-chi-server/go/api_pet_service.go
samples/server/petstore/go-chi-server/go/api_user.go
samples/server/petstore/go-chi-server/go/api_user_service.go

Default values for strings are missing double quotes in the golang server code
Fixes
- fixes #18472
```
```  …

[go-server] Fix: missing quotes for string default value

---

samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_user.go
samples/server/petstore/go-chi-server/go/api_pet.go
samples/server/petstore/go-chi-server/go/api_user.go

The PR for issue #18546 did not seem to include all the required sample changes to pass the `Verify git status` check.
All open PRs seem to be failing with that commit.
```
```  …

[go-server] Fix: missing sample changes from previous commit (#18546)

---

modules/openapi-generator/src/main/resources/rust-axum/lib.mustache
modules/openapi-generator/src/main/resources/rust-server/lib.mustache
modules/openapi-generator/src/main/resources/rust/lib.mustache
samples/client/others/rust/hyper/api-with-ref-param/src/lib.rs
samples/client/others/rust/hyper/composed-oneof/src/lib.rs
samples/client/others/rust/hyper/emptyObject/src/lib.rs
samples/client/others/rust/hyper/oneOf-array-map/src/lib.rs
samples/client/others/rust/hyper/oneOf-reuseRef/src/lib.rs
samples/client/others/rust/hyper/oneOf/src/lib.rs
samples/client/others/rust/reqwest-regression-16119/src/lib.rs
samples/client/others/rust/reqwest/api-with-ref-param/src/lib.rs
samples/client/others/rust/reqwest/composed-oneof/src/lib.rs
samples/client/others/rust/reqwest/emptyObject/src/lib.rs
samples/client/others/rust/reqwest/oneOf-array-map/src/lib.rs
samples/client/others/rust/reqwest/oneOf-reuseRef/src/lib.rs
samples/client/others/rust/reqwest/oneOf/src/lib.rs
samples/client/petstore/rust/hyper/petstore/src/lib.rs
samples/client/petstore/rust/reqwest/name-mapping/src/lib.rs
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/lib.rs
samples/client/petstore/rust/reqwest/petstore-async/src/lib.rs
samples/client/petstore/rust/reqwest/petstore-avoid-box/src/lib.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/lib.rs
samples/client/petstore/rust/reqwest/petstore/src/lib.rs
samples/server/petstore/rust-server/output/multipart-v3/src/lib.rs
samples/server/petstore/rust-server/output/no-example-v3/src/lib.rs
samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
samples/server/petstore/rust-server/output/ops-v3/src/lib.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
samples/server/petstore/rust-server/output/ping-bearer-auth/src/lib.rs
samples/server/petstore/rust-server/output/rust-server-test/src/lib.rs

Addresses issue: https://github.com/OpenAPITools/openapi-generator/issues/18600
```
``` 

Disable clippy::too_many_arguments in generated Rust client code.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpFlightServerCodegen.java
modules/openapi-generator/src/main/resources/php-flight/api.mustache
modules/openapi-generator/src/main/resources/php-flight/register_routes.mustache
samples/server/petstore/php-flight/Api/AbstractPetApi.php
samples/server/petstore/php-flight/Api/AbstractStoreApi.php
samples/server/petstore/php-flight/Api/AbstractUserApi.php
samples/server/petstore/php-flight/RegisterRoutes.php

…and use http status from spec
This additionally adds streaming stubs for all methods (rather err on the side of too much stubs).
@jebentier, @dkarlovi, @mandrean, @jfastnacht, @ybelenko, @renepardon
```
```  …

[php-flight] fix: always set http status in streaming response

---

modules/openapi-generator-gradle-plugin/README.adoc

When updating the `build.gradle` file, `configOptions.set([])` is no longer a valid command, and will cause a compilation error in the `build.gradle` file. Instead, we must use the `put` method instead. I updated the `README.md` file to reflect this. 
```
```  …

Updating Documentation for Gradle Setup 

---

modules/openapi-generator-maven-plugin/examples/multi-module/pom.xml
modules/openapi-generator-maven-plugin/pom.xml
modules/openapi-generator-maven-plugin/src/test/java/org/openapitools/codegen/plugin/CodeGenMojoTest.java
modules/openapi-generator-online/pom.xml
modules/openapi-generator-online/src/test/java/org/openapitools/codegen/online/api/GenApiControllerTest.java
modules/openapi-generator/pom.xml
modules/openapi-generator/src/main/resources/codegen/generatorClassTest.mustache
modules/openapi-generator/src/main/resources/codegen/pom.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/ArchUnitRulesTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpClientDeepObjectTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/helidon/JavaHelidonCommonCodegenPackagePrefixTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/helidon/JavaHelidonCommonCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/jetbrains/http/client/JetbrainsHttpClientClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/n4js/N4jsClientCodegenOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/mustache/IndentedLambdaTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java
pom.xml
samples/meta-codegen/lib/src/test/java/com/my/company/codegen/MyclientcodegenGeneratorTest.java

PR for openapi poms and codegen tests of #18470

upgrade openapi poms and codegen tests to junit5

---

modules/openapi-generator-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
modules/openapi-generator-gradle-plugin/pom.xml
modules/openapi-generator-gradle-plugin/samples/local-spec/gradle/wrapper/gradle-wrapper.properties
modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskConfigurationCacheTest.kt
modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskFromCacheTest.kt
modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskUpToDateTest.kt
modules/openapi-generator-gradle-plugin/src/test/kotlin/ValidateTaskDslTest.kt
pom.xml

This upgrades swagger-parser to the latest release.  In manual testing, this upgrade restored the generator's ability to resolve external references in OpenAPI specs.
Fixes #18429 
```
```  …

upgrade swagger-parser to latest version

---

modules/openapi-generator-gradle-plugin/build.gradle

a follow-up PR: https://github.com/OpenAPITools/openapi-generator/pull/18436 to fix the travis build failure.
```
```  …

update kotlin version to 1.9.0

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/AbstractIntegrationTest.java
pom.xml

A testNG upgrade to fix a critical CVE.
```
```

fix: Upgrade testng to avoid CVE-2022-4065

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml
samples/openapi3/client/petstore/python-aiohttp/docs/EnumTest.md
samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/enum_test.py
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/docs/EnumTest.md
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/models/enum_test.py
samples/openapi3/client/petstore/python-pydantic-v1/docs/EnumTest.md
samples/openapi3/client/petstore/python-pydantic-v1/petstore_api/models/enum_test.py
samples/openapi3/client/petstore/python/docs/EnumTest.md
samples/openapi3/client/petstore/python/petstore_api/models/enum_test.py

This fixes the issue described in #16560 of a problem with the Python family of converters that when processing enums, none of them substitutes the enum var extensions.
When processing the following schema:
```yaml
openapi: 3.0.0
info:
version: 1.0.0
title: Weather API
paths: {}
components:
schemas:
WeatherType:
type: integer
format: int32
enum:
- 42
- 18
- 56
x-enum-descriptions:
- 'Blue sky'
- 'Slightly overcast'
- 'Take an umbrella with you'
x-enum-varnames:
- Sunny
- Cloudy
- Rainy
```
The generator would yield:
```Python
from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401
from openapi_server.models.base_model import Model
from openapi_server import util
class WeatherType(Model):
"""NOTE: This class is auto generated by OpenAPI Generator …
```

[Python] Fix the post processing of enums

---

modules/openapi-generator/src/main/resources/rust/model.mustache
samples/client/others/rust/hyper/api-with-ref-param/src/models/color.rs
samples/client/others/rust/hyper/oneOf/src/models/fruit_type.rs
samples/client/others/rust/reqwest/api-with-ref-param/src/models/color.rs
samples/client/others/rust/reqwest/oneOf/src/models/fruit_type.rs
samples/client/petstore/rust/hyper/petstore/src/models/baz.rs
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/models/baz.rs
samples/client/petstore/rust/reqwest/petstore-async/src/models/baz.rs
samples/client/petstore/rust/reqwest/petstore-avoid-box/src/models/baz.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/models/baz.rs
samples/client/petstore/rust/reqwest/petstore/src/models/baz.rs

With the latest 1.78 release of Rust, Clippy has introduced a lint warning against the direct implementation of `ToString`, recommending instead to implement `Display`: https://rust-lang.github.io/rust-clippy/master/index.html#/to_string_trait_impl
This PR changes the uses of `impl ToString` in the Rust generator template for `impl Display`. It also updates the Rust samples. Note that because `Display` has a blanket implementation of `ToString`, the resulting enums will still implement `ToString`, so this doesn't break anything.
Tagging `openapi-generator` Rust committee, like the checklist mentions: @frol @farcaller @richardwhiuk @paladinzh @jacob-pro
```
``` 
(For Windows users, …

Use Display instead of ToString in Rust generators

---

modules/openapi-generator/src/main/resources/Java/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/api_test.mustache
modules/openapi-generator/src/test/resources/2_0/templates/Java/ApiClient.mustache
samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java

This PR aims to fix a compiler issue I ran into when generating `java` code from an API spec.
The generated code imports `com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider` in `ApiClient.java`, which is the javax package, while my project uses jakarta and requires `com.fasterxml.jackson.jakarta.rs.json.JacksonJsonProvider`. Upon searching, this seems to be a long-standing issue in this specific configuration, I was able to find at least one issue directly referencing it: #15875.
Upon digging deeper, it seems the generated `ApiClient.java` file in my particular configuration (using the `apache-httpclient` library) doesn't even use the imported class, so in this specialized template it can even be omitted, as is the case in a secondary issue reported as #18289.
The PR does not add any …

Fixes incorrect Jackson imports in Java templates used in ApiClient.java when useJakartaEe=true

---

modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/ping-with-hyphen-separated-security-scheme.yaml
samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ApiClient.java

resolves #18629 
Add lambda call to `camelcase` to correctly handle hyphen separated security schemes when generating the `AuthInfo` class in Java vertx client.
Steps to validate this branch:
1. Checkout to this branch locally and build the JAR: `./mvnw clean package`
2. Run the following command:
```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar \
generate \
-g java \
--library vertx \
-o /var/tmp/java-vertx-client-test \
-i https://gist.githubusercontent.com/rohitsanj/bd1f1f6747c41299bf4ce714ec2cda80/raw/6d46a2cfe8cf2dc173099e2b041af4dccb29c54a/openapi.yaml
```
3. After generating the project with the steps above, navigate to `src/main/java/org/openapitools/client/ApiClient.java` and verify that there are no syntax errors in the `AuthInfo` class.
I've also …

[Java] [VertX] Handle hyphen-separated security schemes in input spec

---

modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/build.gradle
samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

Requirement #18593 
**What has changed:** 
Switched out the **retrofit converter factory** used for **kotlinx_serialization** in the **kotlin** generator with the _new_ first party converter.
* Dependency changed `com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter `-> `com.squareup.retrofit2:converter-kotlinx-serialization` in modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
* Import changed `com.jakewharton.retrofit2.converter.kotlinx.serialization.asConverterFactory` -> `retrofit2.converter.kotlinx.serialization.asConverterFactory` in modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache
**Why was it changed:**
Given that no further development is to be expected on the …

[KOTLIN] Kotlinx serialization, use first party retrofit converter factory

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

Closes: #18477
```
``` 
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor …

[BUG][JAVA] Prevent generating "pattern" and "size" to ENUM

---

modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/Generator.java

Skip setting output folder in online service to avoid users providing output folder with `../../` for example to access other folders.
```
```  …

Skip setting output folder in online service

---

modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache

Follow up task from #18630, see this [comment](https://github.com/OpenAPITools/openapi-generator/pull/18630#discussion_r1598109709).
Existing unit test in `JavaClientCodeGenTest` covers the change in this PR.
https://github.com/OpenAPITools/openapi-generator/blob/926a07fe4dccf654d6f012b432c4a89cc2cb4bd7/modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java#L1002-L1033
```
``` 
These must match the expectations made …

[Java] [Vertx] Use pascalcase instead of double lambda

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
modules/openapi-generator/src/main/resources/typescript-axios/model.mustache
samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/model/abstract-user-dto.ts
samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/model/flat-stock-pick-order-dto.ts
samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/model/internal-authenticated-user-dto.ts
samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/model/remote-authenticated-user-dto.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/pet.ts

Fixes #17461.
Similar to #12195 but there does not seem to be solved type import issued for `withSeparateModelsAndApi` and as far as i saw, all the changes have already been addressed by #13964, therefore that PR can be closed.
```
```  …

typescript-axios: withSeparateModelsAndApi - fix missing import type

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache

Previously, generated code from the `oneOf` schema without a discriminator might cause runtime errors.
schema:
```yaml
openapi: 3.0.0
info:
version: 1.0.0
title: Test
description: Test
paths:
/foo:
get:
responses:
200:
description: foo
content:
schema:
$ref: '#/components/schemas/Foo'
components:
schemas:
Foo:
oneOf:
- $ref: '#/components/schemas/Bar'
- $ref: '#/components/schemas/Buzz'
Bar:
type: object
required:
- abc
properties:
abc:
type: array
items:
type: object
properties:
xyz:
type: number
Buzz:
type: object
required:
- def
properties:
def:
type: number
```
generated model code (partial):
```ts
// models/Foo.ts
// ...
export function FooFromJSON(json: any): Foo {
return FooFromJSONTyped(json, false);
}
export function FooFromJSONTyped(json: any, …
```

[typescript-fetch] Improve code generation for `oneOf` cases without discriminator

---

modules/openapi-generator/src/main/resources/go/client.mustache
samples/client/echo_api/go-external-refs/client.go
samples/client/echo_api/go/client.go
samples/client/others/go/allof_multiple_ref_and_discriminator/client.go
samples/client/others/go/oneof-anyof-required/client.go
samples/client/petstore/go/go-petstore/client.go
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go
samples/openapi3/client/petstore/go-petstore-generateMarshalJSON-false/client.go
samples/openapi3/client/petstore/go/go-petstore/client.go

Generated Go Client code now uses time.RFC3339Nano instead of time.RFC3339, so we do not loose the millisecond resolution.
Addresses https://github.com/OpenAPITools/openapi-generator/issues/18672
```
```  …

[GO][Client] Generated GO Client Time Query Param Millisecond Resolution Fix

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaCaskServerCodegen.java

This changes fixes routes which have freeform types. Previously they were just represented as "Object", and didn't have any default value.
The freeform schemas now are of type usjon.Value, with ujson.Null, to coincide with our cask ecosystem.
``` …
```

Added support for freeform types

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java

fix https://github.com/OpenAPITools/openapi-generator/issues/18730
```
``` 

convert all text/* content types to strings in the apache http java client

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
modules/openapi-generator/src/main/resources/typescript-nestjs/configuration.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/configuration.ts

```
``` 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) …

[typescript/nestjs] remove unused imports and allow async configuration

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/user.service.ts

Fixes mustach template from https://github.com/OpenAPITools/openapi-generator/pull/18476
- Comment block was improperly closed
- Also removes empty param destructuring when there are no params
Before (unterminated comment block)
```ts
/**
* 
* 
public metadataControllerGetMetadata(): Observable<AxiosResponse<GetDto>>;
public metadataControllerGetMetadata(): Observable<any> {
const {
} = requestParameters;
let headers = {...this.defaultHeaders};
```
After
```ts
/**
* 
* 
*/
public metadataControllerGetMetadata(): Observable<AxiosResponse<GetDto>>;
public metadataControllerGetMetadata(): Observable<any> {
let headers = {...this.defaultHeaders};
```
```
``` 
(For Windows users, please …

[typescript-nestjs] Fix template for useSingleRequestParameter

---

modules/openapi-generator-online/src/test/java/org/openapitools/codegen/online/api/GenApiControllerTest.java

Depending on test exec environment, this test could linger around for ~8 minutes, b/c pinging test.com will not resolve and run into several timeouts.
Brings down CI time for Linux Suite from >10m to ~4m. 
Connections in this test time out with 
```log
java.net.ConnectException: Connection timed out: connect
```
Connection fails immediately with
```
java.net.ConnectException: Connection refused: connect
```
```
```  …

Fix long running test

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenExampleValuesTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

Fix tests for parsing of additional type annotations & refactor test code

---

modules/openapi-generator/src/main/resources/crystal/shard.mustache
samples/client/petstore/crystal/shard.yml

This is an extremely straightforward change that bumps the version of [Kemal](https://github.com/kemalcr/kemal) and [Crest](https://github.com/mamantoha/crest) in order to fix a build error after a `shards update`. The issue experienced is a failure for the generated client library to run due to an error in the dependent library [http_proxy](https://github.com/mamantoha/http_proxy). This library is in a unusable state in version 0.8.1 due to a function prototype mismatch with its provided argument types. For review @wing328.
An OpenAPI-Generator user using the Crystal Language generator will experience a backtrace like this when using the current generator:
```
$ crystal build src/cli.cr --error-trace 
In src/cli.cr:50:6
50 | main.execute ARGV
^------
Error: instantiating …
```

[crystal-lang] Update dependencies to remedy build failure

---

modules/openapi-generator/src/main/resources/crystal/api_error.mustache
samples/client/petstore/crystal/src/petstore/api_error.cr

Displaying a rescue'd ApiError causes a compile-time error using crystal-lang v1.12.1. The `@message` instance variable is defined as `String | Nil`; however, even with a `.nil?` check, the variable causes a compile-time error when a further `.empty?` call is made. 
The offending line uses the`||` (logical OR) operator to ensure `@message` is not `Nil`. Although this should logically ensure that further operations on `@message` were only applied to `@message` when it is of type `String`, this is not what is seen during a compilation. It is unintuitive that this is necessary as crystal-lang's logical OR operator [uses left-hand associativity](https://crystal-lang.org/reference/1.12/syntax_and_semantics/operators.html).
This PR uses `.try` to make the `.empty?` call. Since Nil defines …

[crystal-lang] Resolve type check compile error in ApiError

---

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientDeepObjectTest.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/QueryApi.java

Implements proposed solution from #18736. Empty Strings are no longer added to the string builder in order to avoid creating invalid request querys.
```
```  …

[Java][native] Fix: empty deepObject can produce invalid query [fix #18736]

---

modules/openapi-generator/src/main/resources/JavaJaxRS/api.mustache
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/FooApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/FakeClassnameTags123Api.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/UserApi.java

Small fix for java JaxRS template. newInstance() method is deprecated in Class class since JDK9.

Fix javaJaxRS template: remove deprecated in JDK9 method usage

---

bin/configs/java-microprofile-rest-client-3.0-jackson-with-xml.yaml
docs/global-properties.md
modules/openapi-generator-gradle-plugin/README.adoc
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
modules/openapi-generator-maven-plugin/README.md
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/resources/csharp/libraries/generichost/README.client.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
samples/client/petstore/csharp/generichost/net8/AllOf/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/net8/AnyOf/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/net8/AnyOfNoCompare/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/net8/FormModels/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/net8/NullReferenceTypes/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/net8/OneOf/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/net8/Petstore/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/net8/SourceGeneration/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/net8/UseDateTimeForDate/src/Org.OpenAPITools/README.md
samples/client/petstore/csharp/generichost/standard2.0/Petstore/src/Org.OpenAPITools/README.md

Users of the plugins can just delete it (b/c the setting never transpired through to the actual generator), or move it into `configOptions` (given the generator supports XML, you can enable it this way) should they choose so.
---
Closes #3839
Closes #5764 
Closes #8902
Likely closes #11578
The basic issue is that `withXml` is documented as a global property [on the main web site](https://openapi-generator.tech/docs/globals/) as well as the maven plugin. However, no matter what value is provided, Spring or Java generators won't generate XML-related annotations (only when supplying it as a `configOption`), rendering it effectively useless.
~~This PR applies the global property to the CodeGen's additionalProperties – if (and only if) it not already defined via  `--additionalProperties` …

[General] Remove defunct global property `withXml` from generator, docs, maven & gradle plugin

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache

Moshi supports `nonPublicApi` flag but `jvm-retrofit2` doesn't. This make that the generated code doesn't compile because the public Retrofit interfaces point to the internal data classes from moshi.
This PR makes `jvm-retrofir2` to honor `nonPublicApi` so when added the retrofit interface will be `internal` and everything will compile again.
```
```  …

Support nonPublicApi on jvm-retrofit2

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java

This adds model name mapping to the swift 5 client generator
```
```  …

[Swift5] Add model name mapping

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelEnum.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/EnumClass.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnum.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumInteger.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumIntegerDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/SingleRefType.ts
samples/client/petstore/typescript-fetch/builds/enum/models/NumberEnum.ts
samples/client/petstore/typescript-fetch/builds/enum/models/StringEnum.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/BehaviorType.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/DeploymentRequestStatus.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/ErrorCode.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/PetPartType.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/WarningCode.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/EnumClass.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnum.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumInteger.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumIntegerDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/SingleRefType.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/NumberEnum.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/StringEnum.ts

Fixes a typescipt bug that was introduced in #18418 , details are explained in #18746 
@mkusaka 
```
```  …

Fix TS7053 errors in generated instanceOf* methods

---

modules/openapi-generator-cli/pom.xml
modules/openapi-generator-core/pom.xml
modules/openapi-generator-gradle-plugin/pom.xml
modules/openapi-generator-maven-plugin/pom.xml
modules/openapi-generator-online/pom.xml
modules/openapi-generator/pom.xml
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtilsTest.java
pom.xml

This PR:
- removes dependency `org.reflections`  
…is not used anywhere
- remove unused code and some minor optimizations for `TestUtils`
- covers `TestUtils.validatePomXmlFiles(List)` with tests  
Yo, dawg, i heard you like tests, so i wrote some tests for your test helpers :wink: (well really it was to make sure the following step produced runtime behavior)
- Reimplemented the method with Jackson XML mapper  
Although the `RawPom.parse` method implements tight checks by databinding to its own sophisticated pom POJO, it is really only the five assertions in `TestUtils.validatePomXmlFiles(List)` that we're after. `rewrite-maven` imports a whopping 73 MB onto the classpath with dozens of transitive dependencies having to be gulped by our IDEs – a little overkill just for a single test …

Remove unused test dependencies `org.reflections` & `maven-rewrite`

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/2_0/java/issue-6496.yaml

Closes #6496
See linked issue and implemented regression tests for details.
```
``` 

[JAVA] Fix jackson (de)serializer annotation breaking libs using gson when `bigDecimalAsString=true`

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpLaravelServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/AllGeneratorsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpLaravelServerCodegenTest.java
samples/server/petstore/php-laravel/.openapi-generator/FILES

[php-laravel] Fix file database/migrations/2019_08_19_000000 being written twice

---

docs/generators.md
docs/generators/javascript-closure-angular.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClosureAngularClientCodegen.java

It says on https://openapi-generator.tech/docs/generators/javascript-closure-angular in the helpTxt that this generator is `(beta)`, however the stability is shown as `STABLE`.
It also suggests that XML is supported, while the templates clearly show it isn't.
This PR amends that.
```
```  …

[javascript-closure-angular] Change metadata to reflect beta status and non-existing xml capability in docs

---

docs/generators/typescript-angular.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAngularClientOptionsProvider.java

If first declared the issue there => #18489 
```
``` 
Please review my PR : 
@TiFu @taxpon …

fixes #18489: provide support of array attributes in multipart/form-data request for angular typescript client

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator-maven-plugin/src/test/java/org/openapitools/codegen/plugin/CodeGenMojoTest.java
modules/openapi-generator-maven-plugin/src/test/resources/issue-16489/petstore.yaml
modules/openapi-generator-maven-plugin/src/test/resources/issue-16489/pom.xml
modules/openapi-generator-maven-plugin/src/test/resources/issue-16489/schemas/Pet.yaml

Otherwise regeneration will not happen when skipIfSpecIsUnchanged is enabled, although formally the spec content has changed.
Closes #4512
Closes #16489 
```
```  …

[maven-plugin] Generate hash from actual resolved spec rather than inputSpec file

---

modules/openapi-generator/src/main/resources/php-slim4-server/register_routes.mustache

Fixed a PHP Syntax Error (mssing semicolon) in the php-slim4-server templates.
```
```  …

[php-slim4-server] fix php syntax error in RegisterRoutes class (missing semicolon)

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api_client.py
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/tests/test_manual.py
samples/client/echo_api/python/openapi_client/api_client.py
samples/client/echo_api/python/tests/test_manual.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/tests/test_api.py
samples/openapi3/client/petstore/python/tests/test_deserialization.py
samples/openapi3/client/petstore/python/tests/test_fake_api.py

fix #18774
This PR is another approach to what I changed in #18069.
```
``` 
@cbornet (2017/09) …

[python] fix deserialize on basic str fails 

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache

fix #18876
```
``` 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward …

[typescript-fetch] fix Type error in oneOf when legacyDiscriminatorBehavior is false

---

docs/generators/elixir.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
samples/client/petstore/elixir/lib/openapi_petstore/api/fake.ex
samples/client/petstore/elixir/lib/openapi_petstore/api/pet.ex
samples/client/petstore/elixir/lib/openapi_petstore/api/user.ex

This PR improves Elixir code generation by resolving several issues observed when generating using the Procore API spec:
1. Previous reserved words list was incomplete. Updated to use the reserved words list from the Elixir language documentation.
2. Reserved words were being prefixed with an underscore. In Elixir this indicates that the variable is not being used and when it is used it will emit a warning. This updates the renaming function to use a suffix to avoid these warnings.
3. In rare cases, Typespecs were generating invalid types with a double "t" (e.g. ".t().t"). This change normalizes the names to improve reliability of the typespec generation.
@mrmstn
```
``` 
(For …

[Elixir] Fix generation issues and compilation warnings in Elixir generator

---

modules/openapi-generator/src/main/resources/kotlin-client/anyof_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/oneof_class.mustache
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiAnyOfUserOrPetOrArrayString.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiUserOrPetOrArrayString.kt

to close https://github.com/OpenAPITools/openapi-generator/issues/18890
remove java code in kotlin client template
```
```  …

Fix list in kotlin client templates

---

modules/openapi-generator/src/main/resources/JavaSpring/beanValidationCore.mustache
modules/openapi-generator/src/test/resources/3_0/spring/petstore-with-fake-endpoints-models-for-testing.yaml
samples/openapi3/server/petstore/springboot-delegate/src/main/resources/openapi.yaml
samples/openapi3/server/petstore/springboot-implicitHeaders/src/main/resources/openapi.yaml
samples/server/petstore/springboot-beanvalidation-no-nullable/src/main/resources/openapi.yaml
samples/server/petstore/springboot-beanvalidation/src/main/resources/openapi.yaml
samples/server/petstore/springboot-delegate-j8/src/main/resources/openapi.yaml
samples/server/petstore/springboot-delegate/src/main/resources/openapi.yaml
samples/server/petstore/springboot-implicitHeaders/src/main/resources/openapi.yaml
samples/server/petstore/springboot-reactive-noResponseEntity/src/main/resources/openapi.yaml
samples/server/petstore/springboot-reactive/src/main/resources/openapi.yaml
samples/server/petstore/springboot-useoptional/src/main/resources/openapi.yaml
samples/server/petstore/springboot-virtualan/src/main/resources/openapi.yaml
samples/server/petstore/springboot/src/main/resources/openapi.yaml

Remove bean validation for uuid, because it's not necessary and breaks the java code
#18095
```
```  …

Remove bean validation for uuid

---

docs/generators/typescript-axios.md
docs/generators/typescript-fetch.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptFetchClientOptionsProvider.java
samples/client/echo_api/typescript-axios/build/api.ts

```
``` 
Please review my PR :
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny …

fixes #18853: provide support of array attributes in multipart/form-data request for axios and fetch typescript clients

---

modules/openapi-generator-gradle-plugin/README.adoc
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt

Enhance the Gradle plugin to support loading templates from the classpath. This is already a feature of the Maven plugin, and this PR uses the same approach.

[Enhancement] [Gradle Plugin] Allow templates from classpath

---

modules/openapi-generator/src/main/resources/rust-axum/server-operation.mustache

This PR adds support for response ranges in rust-axum server, as defined in section 4.8.16.2 of the spec.
```
```  …

[rust-axum] Support for response status code ranges

---

.github/workflows/samples-python-client-echo-api.yaml
bin/configs/python-echo-api-disallowAdditionalPropertiesIfNotPresent-true.yaml
bin/configs/python.yaml
docs/generators/python.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
modules/openapi-generator/src/main/resources/python/rest.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/rest.py

Add an option to add ensure_ascii=False to json.dumps
based on https://github.com/OpenAPITools/openapi-generator/pull/18787
cc 
```
```  …

[python] Add an option to add ensure_ascii=False to json.dumps

---

.github/workflows/samples-java-client-echo-api-jdk11.yaml
.github/workflows/samples-java-client-echo-api-jdk17.yaml
.github/workflows/samples-java-client-echo-api-jdk8.yaml
.github/workflows/samples-java-client-jdk11.yaml
.github/workflows/samples-java-client-jdk17.yaml
.github/workflows/samples-java-helidon-v3.yaml
.github/workflows/samples-java-helidon-v4.yaml
.github/workflows/samples-java-play-framework.yaml
.github/workflows/samples-java-server-jdk8.yaml
.github/workflows/samples-java-wiremock.yaml
.github/workflows/samples-jaxrs-jdk11.yaml
.github/workflows/samples-jaxrs.yaml
.github/workflows/samples-jdk17.yaml
.github/workflows/samples-jdk21.yaml
.github/workflows/samples-spring-jdk17.yaml
.github/workflows/samples-spring.yaml
modules/openapi-generator/src/main/resources/JavaSpring/javaBuilder.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/Pet.java
samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/Pet.java

Closes #12804 
… as the regression test builds upon the features introduced into the test stack there, namely inner class assertions.
```
```  …

[JAVA-SPRING] Avoid broken code due to duplicate rendering of `@Deprecated` annotation with `generateBuilders=true`

---

bin/configs/kotlin-spring-boot-3.yaml
bin/configs/kotlin-spring-boot-delegate.yaml
bin/configs/kotlin-spring-boot.yaml
docs/generators/kotlin-spring.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/apiController.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/spring/KotlinSpringServerCodegenTest.java
samples/server/petstore/kotlin-springboot-3/src/main/kotlin/org/openapitools/api/PetApiController.kt
samples/server/petstore/kotlin-springboot-3/src/main/kotlin/org/openapitools/api/StoreApiController.kt
samples/server/petstore/kotlin-springboot-3/src/main/kotlin/org/openapitools/api/UserApiController.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApiController.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApiController.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApiController.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/FakeApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/FakeClassnameTestApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/FooApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/UserApi.kt
samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/UserApi.kt

RequestMappingMode: Explicit configuration to control the location of the generated class level RequestMapping annotation-
Based on #13838 but for the kotlin-spring generator.
Fixes #18884
```
```  …

Kotlin-Spring request mapping mode

---

modules/openapi-generator/src/main/resources/Java/libraries/native/modelEnum.mustache

`useEnumCaseInsensitive` option does not work in Java Enum Classes for native library. It is implemented implemented in the default template but not in the native template. This PR copies the conditional `equalsIgnoreCase` call from default template to `native`.
Seems like this change was forgotten in this PR: https://github.com/OpenAPITools/openapi-generator/pull/15273
More details are shared in this issue: https://github.com/OpenAPITools/openapi-generator/issues/18761
Java Committee Members:
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @martin-mfg
```
```  …

[Java][native] Fix: useEnumCaseInsensitive option fixed in Java Native Model Enum

---

modules/openapi-generator-gradle-plugin/README.adoc

#14909 added a new option `templateResourcePath`. However, the `README` was missing a default value for the AsciiDoc table, which caused all the properties after to be rendered wrongly (see the [`README.adoc`](https://github.com/OpenAPITools/openapi-generator/blob/819083b1ba2dfcd732abd3d9ed2ccd96e2e63992/modules/openapi-generator-gradle-plugin/README.adoc) and check the properties after `templateResourcePath` in the rendered Markdown).
This PR adds the `None` default (to match the existing properties).
```
```  …

Fix README by adding default entry for new `templateResourcePath` option in AsciiDoc

---

modules/openapi-generator/src/main/resources/swift-combine/api.mustache
samples/client/petstore/swift-combine/client/PetstoreOpenAPI/Sources/APIs/PetAPI.swift
samples/client/petstore/swift-combine/client/PetstoreOpenAPI/Sources/APIs/StoreAPI.swift
samples/client/petstore/swift-combine/client/PetstoreOpenAPI/Sources/APIs/UserAPI.swift

Fixes [Issue 18940](https://github.com/OpenAPITools/openapi-generator/issues/18940)
This renames the `url` & `path` variables to `localVarURL` and `localVarPath` to reduce the likelihood of collisions with parameters in the API request 
@dydus0x14
```
```  …

[swift] Rename url & path variables to avoid collision

---

modules/openapi-generator/src/main/resources/csharp/modelGeneric.mustache
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/DateOnlyClass.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/FormatTest.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/NullableClass.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/RequiredClass.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/DateOnlyClass.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/FormatTest.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/NullableClass.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/RequiredClass.cs

If supportsDateOnly is true the OpenAPIDateConverter doesn't get applied to DateOnly properties.
This prevents following client ApiException at runtime "Unable to cast object of type 'System.DateTime' to type 'System.DateOnly'".
I used the 'Steps to reproduce' from #18541 to test the change.
fix #18541 
```
```  …

[csharp] Don't apply OpenAPIDateConverter json converter attribute for DateOnly properties

---

modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache
samples/client/echo_api/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-default-values-jvm-retrofit2/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiPet.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/test/kotlin/org/openapitools/client/models/UserOrPetTest.kt
samples/client/petstore/kotlin-retrofit2-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-retrofit2-rx3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-retrofit2/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

- update ApiClient to register all adapters for GsonBuilder when constructing a new instance of ApiClient
- add tests
- also fix invalid json array variable name (to close https://github.com/OpenAPITools/openapi-generator/issues/18908)
```
```  …

[Kotlin] update ApiClient to register all adapters for GsonBuilder

---

modules/openapi-generator/src/main/resources/rust-server/lib.mustache
samples/server/petstore/rust-server/output/multipart-v3/src/lib.rs
samples/server/petstore/rust-server/output/no-example-v3/src/lib.rs
samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
samples/server/petstore/rust-server/output/ops-v3/src/lib.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
samples/server/petstore/rust-server/output/ping-bearer-auth/src/lib.rs
samples/server/petstore/rust-server/output/rust-server-test/src/lib.rs

New versions of rust clippy reports errors with duplicate allow directives. This change fixes the duplicate directives in generated rust code.
```
```  …

fix(rust-server): remove duplicate allow(unused_imports) directive

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
samples/client/others/kotlin-jvm-okhttp-parameter-tests/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-name-parameter-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

This should address https://github.com/OpenAPITools/openapi-generator/issues/18996.
We tracked down a memory leak from the generated api client in kotlin.
The `okhttp3.Response` is closeable and isn't closed. [This commit](https://github.com/airbytehq/airbyte-platform/commit/94e5fa35aca662bedb2877fa98f8a8c03f79deb7) shows the fix we did on in Airbyte that addressed the leak.
The fix I am proposing here is to wrap the usage of the `okhttp3.Response` in a `.use {}` block.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it …

[kotlin] Fix a leak in the ApiClient

---

modules/openapi-generator/src/main/resources/dart2/pubspec.mustache
samples/openapi3/client/petstore/dart2/petstore_client_lib/pubspec.yaml
samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/pubspec.yaml

The hard reuirements of 
- `http: '>=0.13.0 <0.14.0'`
- `collection: '^1.17.0'`
- `meta: '^1.1.8'`
limit current and future update behavior.
Previous discussions with @aviadkam have been done in https://github.com/OpenAPITools/openapi-generator/pull/17862
```
```  …

[Dart] Make dependency on http, collection and meta packages less strict

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/auth/OAuth.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/java/oauth.yaml
samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/auth/OAuth.java

Fixes #19000
Add support for a bearer token supplier to OAuth based RestTemplate clients
```
```  …

[java] [resttemplate] Add support for a bearer token supplier to OAuth based RestTemplate clients

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/resources/3_1/java/petstore.yaml
samples/client/petstore/java/okhttp-gson-3.1/README.md
samples/client/petstore/java/okhttp-gson-3.1/api/openapi.yaml
samples/client/petstore/java/okhttp-gson-3.1/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/api/FakeApi.java

To close https://github.com/OpenAPITools/openapi-generator/issues/19012
To close https://github.com/OpenAPITools/openapi-generator/issues/18655
- add tests
- fix NPE in ModelUtils.getType
```
```  …

Fix NPE in ModelUtils getType

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
modules/openapi-generator/src/main/resources/python/configuration.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api_client.py
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/configuration.py
samples/client/echo_api/python/openapi_client/api_client.py
samples/client/echo_api/python/openapi_client/configuration.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/configuration.py
samples/openapi3/client/petstore/python-aiohttp/tests/test_api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/configuration.py
samples/openapi3/client/petstore/python/tests/test_api_client.py
samples/openapi3/client/petstore/python/tests/test_configuration.py

Similar to #18934.
This change adds a flag to the configuration object to allow for ignoring operation servers. Currently, if operation level server objects are defined, there is no way to ignore these or use a different base path at the SDK level, which many other languages support. The new ignore_operation_servers flag allows the user to ignore any operation servers defined and instead use the currently defined `host`. This will default to the top level base path defined in the OpenAPI file, but can be configured to be any url by setting the `host` for the configuration object.
```
``` 
Commit all …

[Python] Add Flag to Allow Ignoring Operation Servers

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/anyof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/anyof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/anyof_model.mustache
modules/openapi-generator/src/test/resources/bugs/issue_18975.yaml

Changes how an `StdDeserializer<A>` of a specific type `A` deserializes into an `A`. We noticed the static block filling the `mappings` passed to the `JSON.registerDiscriminator(A.class, "type", mappings)` was only called _after_ the first call to the deserializer, causing the first result to have an `setActualInstance` call of the wrong subtype of `A`. This is because the static block is part of `A`, while the `StdDeserializer<A>` is a static subclass of `A`. Changing the reference to `A.class` into an actual instance of `A` by the `new A().getClass()` causes the static block to be called on time.
```
```  …

Tries to fix #18975 by changing how the deserializer interacts with its parent class

---

modules/openapi-generator/src/main/resources/android/libraries/volley/build.mustache
samples/client/petstore/android/volley/build.gradle

Causes failures like:
Configuration `:debugUnitTestRuntimeClasspath` contains AndroidX dependencies, but the `android.useAndroidX` property is not enabled, which may cause runtime issues.

[android][volley] Remove unused robolectric test dependency

---

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/FakeApi.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/apis/FakeApi.ts

As mentioned in #13841, date-time parameters in request bodies are not ISO formatted, which breaks with certain webservers. This commit invokes `toISOString()` for date-time body parameters like it is done for queryParameters.
Fixes #13841.
```
```  …

Fix x-www-form-urlencoded date-time string parameters

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
samples/client/echo_api/typescript-axios/build/api.ts
samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-node-imports/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
samples/client/petstore/typescript-axios/builds/with-string-enums/api.ts

Fixes #15985, for some reason all the versions of `options` have the correct type (`RawAxiosRequestConfig`) except "factory interface" versions of the functions. 
For example, the changed line is from `any` (in the original):
https://github.com/OpenAPITools/openapi-generator/blob/640ef9d9448a4a008af90eca9cc84c8a78ec87ec/samples/client/petstore/typescript-axios/builds/default/api.ts#L739
To `RawAxiosRequestConfig` (in this pull request):
https://github.com/OpenAPITools/openapi-generator/blob/d5d4c058af17b5321000eac057403980c6f56fb3/samples/client/petstore/typescript-axios/builds/default/api.ts#L739 
As you can see it calls this method in the next line, where the type is correctly present:
https://github.com/OpenAPITools/openapi-generator/blob/d5d4c058af17b5321000eac057403980c6f56fb3/samples …

#15985 Change options from any to RawAxiosRequestConfig in typescript-axios

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/AllOfWithSingleRef.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterObjectWithEnumProperty.ts
samples/client/petstore/typescript-fetch/builds/enum/models/EnumPatternObject.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/GetBehaviorTypeResponse.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/GetPetPartTypeResponse.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/AllOfWithSingleRef.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterObjectWithEnumProperty.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/EnumPatternObject.ts

Adds isEnumRef to the condition because it does not match the isPrimitiveType condition if the enum definition is separated.
isEnumRef was also added to the typescript-fetch specific ExtendedCodegenParameter and ExtendedCodegenProperty so that it can be used in templates.
Fixes #11613 
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka 
```
``` 
These must match the expectations made …

[typescript-fetch] Fix API-generation of referenced enums for multipart/form-data

---

modules/openapi-generator/src/main/resources/typescript/package.mustache
samples/client/others/typescript/builds/with-unique-items/package.json
samples/openapi3/client/petstore/typescript/builds/browser/package.json
samples/openapi3/client/petstore/typescript/builds/composed-schemas/package.json
samples/openapi3/client/petstore/typescript/builds/default/package.json
samples/openapi3/client/petstore/typescript/builds/inversify/package.json
samples/openapi3/client/petstore/typescript/builds/jquery/package.json
samples/openapi3/client/petstore/typescript/builds/object_params/package.json

Addresses issue #19003 by modifying the `package.mustache` file in the typescript generator.
```
```  …

[Typescript] Fix Issue Directly Publishing Package

---

modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/api.mustache
samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/api/UserApi.java

[java-retrofit2] Support payload for DELETE method

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
samples/client/others/kotlin-jvm-okhttp-parameter-tests/src/main/kotlin/org/openapitools/client/apis/DefaultApi.kt
samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt

When using the JVM implementation of OkHttp with a Kotlin client, you may encounter issues with the toString() method of enum parameters. By default, the toString() method of an enum returns the name of the enum value, not its value. So currently for 
```yaml
paths
/some/path:
get:
parameters:
- in: query
name: someEnum
schema:
type: array
items:
type: string
enum: ["first.value", "second.value"]
example: "first.value"
```
will generate a such enum for OkHttp Client (Moshi library just for an example)
```Kotlin
/**
* enum for parameter
*/
enum class SomeEnum(val value: kotlin.String) {
@Json(name = "first.value") firstPeriodValue("first.value"),
@Json(name = "second.value") secondPeriodValue("second.value"),
}
```
later in the client there is a mapping by (`ApiAbstractions.kt`)
```Kotlin …
```

[Kotlin-Client][JVM-OkHttp] Override parameter enum's toString()

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelEnum.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/EnumClass.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnum.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumInteger.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/OuterEnumIntegerDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/SingleRefType.ts
samples/client/petstore/typescript-fetch/builds/enum/models/NumberEnum.ts
samples/client/petstore/typescript-fetch/builds/enum/models/StringEnum.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/BehaviorType.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/DeploymentRequestStatus.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/ErrorCode.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/PetPartType.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/WarningCode.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/EnumClass.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnum.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumInteger.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/OuterEnumIntegerDefaultValue.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/SingleRefType.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/NumberEnum.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/models/StringEnum.ts

This is a follow-up to [OpenAPITools/openapi-generator#18770](https://github.com/OpenAPITools/openapi-generator/pull/18770) which partially fixed [OpenAPITools/openapi-generator#18746](https://github.com/OpenAPITools/openapi-generator/issues/18746) but still showed issues with number-based enums. This new approach was confirmed to be working with both number- and string-based enums.
```
``` 
You …

Fix casts for typescript-fetch enum keys not working on number-based enums

---

.github/workflows/samples-java-server-jdk8.yaml
.github/workflows/samples-jdk17.yaml

Enable checks for java-camel samples.
This is a follow-up to https://github.com/OpenAPITools/openapi-generator/pull/18690#issuecomment-2208338374, where a compilation error in java-camel samples wasn't caught by the current pipeline setup.
While testing my changes, I discovered that https://github.com/OpenAPITools/openapi-generator/pull/18870 recently broke the java-camel samples.
I also had to move the java-camel checks to JDK 17, because these samples now use an option that's not available in Java 8.
```
```  …

enable java-camel sample checks

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/spring/KotlinSpringServerCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/array-nullable-items.yaml

Allow array items to be nullable in Kotlin. 
https://github.com/OpenAPITools/openapi-generator/issues/19070
```
```  …

Allow array items in Kotlin to be nullable

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

`convertPropertyToStringAndWriteBack` and `convertPropertyToTypeAndWriteBack` both don't write a `boolean`, but a `String` and respectively a generic type `T`. Therefore, adjusted the javadocs and one method parameter.

Fix docs for two convertProperty methods in DefaultCodegen

---

modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/pojo.mustache
samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/Category.java
samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/ModelApiResponse.java
samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/Order.java
samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/Pet.java
samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/Tag.java
samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/model/User.java
samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/Category.java
samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/ModelApiResponse.java
samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/Order.java
samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/Pet.java
samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/Tag.java
samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/model/User.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/Category.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/ModelApiResponse.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/Order.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/Pet.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/Tag.java
samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/model/User.java

Fixes https://github.com/OpenAPITools/openapi-generator/issues/17069
The resteasy generator generates
> import javax.validation.Valid;
twice when useBeanValidation is enabled.
It is already added here https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/model.mustache#L12
```
```  …

Fix duplicate import javax.valid.Valid in resteasy generator

---

samples/openapi3/client/petstore/python/tests/test_model.py

`TestCase.assertEquals()` does not exist.

Fix call to TestCase.assertEqual()

---

docs/generators/typescript-axios.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-axios/package.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/axios/TypeScriptAxiosClientCodegenTest.java

Fixes #16642 
Creates a new configuration parameter for specifying axios version. This seems like a suitable "special case" to avoid a fully custom template just to bump the axios version, which is a common use case as security updates are made to the axios lib.
This has been end-to-end tested locally (generating a test client and validating that the axios version is changed as expected). I've also added unit tests.
cc: @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka
```
``` 
This is important, as …

[typescript-axios] add config parameter to specify custom axios version

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/echo_api/java/okhttp-gson-user-defined-templates/pom.xml
samples/client/echo_api/java/okhttp-gson/pom.xml
samples/client/others/java/okhttp-gson-oneOf/pom.xml
samples/client/others/java/okhttp-gson-streaming/pom.xml
samples/client/petstore/java/okhttp-gson-3.1/pom.xml
samples/client/petstore/java/okhttp-gson-awsv4signature/pom.xml
samples/client/petstore/java/okhttp-gson-dynamicOperations/pom.xml
samples/client/petstore/java/okhttp-gson-group-parameter/pom.xml
samples/client/petstore/java/okhttp-gson-nullable-required/pom.xml
samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
samples/client/petstore/java/okhttp-gson-swagger1/pom.xml
samples/client/petstore/java/okhttp-gson-swagger2/pom.xml

This PR is a follow up to #18235, that did not update okhttp in pom.xml files (was still 4.11.0).
This is a proper fix for CVE-2023-3635.
```
```  …

Update okhttp3 to 4.12.0 for Maven projects

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

The double equal '==' is a common operator in a few contexts. I am using it for [haystack operators](https://project-haystack.org/doc/docHaystack/Filters), but there is also Python, Javascript, etc.
Currently if `==` appears in an enum its name gets sanitized to empty and generates invalid syntax. This problem is very similar to the one fixed in #12801 , so I am suggesting the same fix here.
```
```  …

codegen: add == -> 'Double_Equal' to specialCharReplacements

---

modules/openapi-generator/src/main/resources/powershell/api.mustache
samples/client/petstore/powershell/src/PSPetstore/Api/PSFakeClassnameTags123Api.ps1
samples/client/petstore/powershell/src/PSPetstore/Api/PSPetApi.ps1
samples/client/petstore/powershell/src/PSPetstore/Api/PSStoreApi.ps1

This PR contains a small change to support ApiKeyPrefix, i.e. an extra string that may be required in the `Authorization:` header (or in the URL parameter) before the ApiKey. ApiKeyPrefix is already supported in the Configuration, but never used in the API code. Likely, when required the prefix was added to the key as a workaround.
The prefix string is directly concatenated to the ApiKey. Any space separators that may be required must be added to the ApiKeyPrefix.
The change has been tested on a client API requiring such a prefix in the header.
```
``` 
This is important, …

[PowerShell] Support ApiKeyPrefix

---

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
samples/client/echo_api/ruby-faraday/lib/openapi_client/api_client.rb
samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb

Based on my findings attempting to download PDFs with a downstream gem, I discovered that binary transferred data is never being unpacked into it's native format. This renders the results malformed. https://github.com/mxenabled/mx-platform-ruby/issues/90
This PR adds a patch that simplifies the flow control of the `deserialize` method, while updating it to properly deserialize content from binary transfer encoding.
I have a patch of this running downstream in production.
Ruby Committee: @cliffano @zlx @autopp
```
```  …

[Ruby] Fix Content-Transfer-Encoding binary unpacking

---

samples/client/echo_api/python/tests/test_manual.py

`TestCase.assertDictContainsSubset()` was deprecated in Python 3.2,
which went EOL in 2016. Rewrite the assertion to target Python 3.8+.
See: https://docs.python.org/3.2/library/unittest.html#unittest.TestCase.assertDictContainsSubset
See: https://devguide.python.org/versions/

Update call to assertDictContainsSubset()

---

docs/generators/elixir.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
modules/openapi-generator/src/main/resources/elixir/README.md.mustache
modules/openapi-generator/src/main/resources/elixir/connection.ex.mustache
modules/openapi-generator/src/main/resources/elixir/mix.exs.mustache

Fix package version handling: remove unused hardcoded `apiVersion`, add `packageVersion` and use it everywhere.
@mrmstn

[Elixir] allow custom packageVersion

---

modules/openapi-generator/src/main/resources/swift5/APIHelper.mustache
modules/openapi-generator/src/main/resources/swift5/OpenAPIDateWithoutTime.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/OpenAPIDateWithoutTime.swift
samples/client/petstore/swift5/anycodableLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/APIHelper.swift
samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/APIHelper.swift

This fixes #18074, OpenAPIDateWithoutTime handling when a date is part of the uri path (parameter).
There are several options to fix the issue, this is just one suggestion.
```
```  …

[Swift] fix(#18074): correctly map OpenAPIDateWithoutTime to string in path

---

modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache
samples/server/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/api/UserApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/FakeApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/FakeClassnameTestApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/FooApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot-request-cookie/src/main/kotlin/org/openapitools/api/UserApi.kt
samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot-request/src/main/kotlin/org/openapitools/api/UserApi.kt

fix #19156 @RestController annotation at Kotlin-Spring API interface
```
``` 
@jimschubert, …

[Kotlin][Spring] When using interfaceOnly, Spring Boot 3 needs @RestController annotation at api interface

---

modules/openapi-generator/src/main/resources/cpp-qt-client/HttpFileElement.cpp.mustache
modules/openapi-generator/src/main/resources/cpp-qt-client/HttpRequest.cpp.mustache
modules/openapi-generator/src/main/resources/cpp-qt-client/HttpRequest.h.mustache
modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache
samples/client/petstore/cpp-qt/client/PFXHttpFileElement.cpp
samples/client/petstore/cpp-qt/client/PFXHttpRequest.cpp
samples/client/petstore/cpp-qt/client/PFXHttpRequest.h
samples/client/petstore/cpp-qt/client/PFXPetApi.cpp
samples/client/petstore/cpp-qt/client/PFXPrimitivesApi.cpp
samples/client/petstore/cpp-qt/client/PFXStoreApi.cpp
samples/client/petstore/cpp-qt/client/PFXUserApi.cpp

There is some Qt version check in the generated code. I propose to drop pre Qt 5.15.2 to make the maintenance easier.
Ping @ravinikam @stkrwork @etherealjoy @muttleyxd
```
``` …

[qt-cpp] Remove Qt support before Qt 5.15.2

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/api.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/api.mustache
samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/api/UserApi.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/api/StoreApi.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/api/UserApi.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/api/StoreApi.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/api/UserApi.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/api/StoreApi.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/api/UserApi.java

This PR fixes the case of a parameter with format URI in the path as seen in #19129. 
The `.toString()` casting were added only in two cases: `isUuid` or `^isString`. However this is not sufficient to catch the case of URI. Instead of adding another exception, I changed the code to always call `.toString()`, similarly to what is done for `okhttp-gson` template.
```
```  …

Close #19129: java jersey2 and jersey3: Always cast path parameters to string similarly to okhttp-gson

---

.github/workflows/samples-python-client-echo-api.yaml

The unit tests in the following directories are written to unittest, not pytest:
* `samples/client/echo_api/python/`
* `samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/`
If pytest is told to execute these tests, it will log warnings about being unable to collect certain tests.

Run unittest tests with unittest

---

.github/workflows/samples-python-client-echo-api.yaml

Python 3.7 is EOL, and Python 3.12 has been released.
See: https://devguide.python.org/versions/

Update Python versions used for unit tests

---

modules/openapi-generator/src/main/resources/python-fastapi/api.mustache
modules/openapi-generator/src/main/resources/python-fastapi/base_api.mustache
samples/server/petstore/python-fastapi/src/openapi_server/apis/fake_api.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/fake_api_base.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/pet_api.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/pet_api_base.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/store_api.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/store_api_base.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api_base.py

```
``` 
cc: @cbornet (2017/09) @tomplus (2018/10) @krjakbrjak (2023/02) @fa0311 (2023/10) …

[python-fastapi] Fix api endpoint template

---

docs/generators/kotlin-spring.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
modules/openapi-generator/src/main/resources/kotlin-spring/beanValidationModel.mustache

…rator as known in java spring generator
Coming from [this issue](https://github.com/OpenAPITools/openapi-generator/issues/16958) I created a solution which works for me. I'd appreciate proper review, as I am not too experienced in this repository.
```
```  …

adds support for x-pattern-message in kotlin-spring generator

---

modules/openapi-generator/src/main/resources/python-fastapi/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonFastapiCodegenTest.java
modules/openapi-generator/src/test/resources/3_1/nodesc.yaml
samples/server/petstore/python-fastapi/src/openapi_server/apis/fake_api.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/pet_api.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/store_api.py
samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api.py

- return 500 if not implemented
- added some unittests
```
``` 
cc: @cbornet (2017/09) @tomplus …

[python-fastapi] return 500 if not implemented, added some unittests

---

bin/configs/kotlin-spring-boot-delegate.yaml
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
modules/openapi-generator/src/main/resources/kotlin-spring/apiDelegate.mustache
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApiDelegate.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApiDelegate.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApiDelegate.kt

fix #18555 kotlin-spring generator flag appendRequestToHandler generates broken code when used with flag delegatePattern
```
```  …

[Kotlin][Spring] fix flag appendRequestToHandler with delegatePattern

---

modules/openapi-generator/src/main/resources/php-nextgen/ApiException.mustache
modules/openapi-generator/src/main/resources/php/ApiException.mustache
modules/openapi-generator/src/main/resources/php/libraries/psr-18/ApiException.mustache
samples/client/echo_api/php-nextgen/src/ApiException.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/lib/ApiException.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ApiException.php
samples/client/petstore/php/OpenAPIClient-php/lib/ApiException.php
samples/client/petstore/php/psr-18/lib/ApiException.php

This PR fixes some incorrect type docs in the ApiException class for the PHP generators.
Mainly that the type of the headers array is actually `string[][]`, not `string[]` as documented in [PSR-7](https://www.php-fig.org/psr/psr-7/#3-interfaces).
I also specified the type of the response body in the constructor parameter from mixed to stdClass|string|null.
This type was already used for the property the value is stored in, and passing any other value therefore already caused fatal PHP errors.
```
```  …

php: Fix typedoc comment for headers in ApiException

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java

This commit updates the access modifier of the ExtendedCodegenModel class from its default (package-private) to public, allowing it to be accessible from outside its package.
```
```  …

Fix ExtendedCodegenModel class access modifier to public (#10342)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java

Our project using angular 18.1.X ran into some issues in combination with the generated openapi specs. The issue is that the generated definition files contain a line like `/// <reference path="xxxx.ngtypecheck.d.ts" />`
Also seen here: https://github.com/angular/angular/issues/56945
Upgrading typescript and ng-packagr seem to solve the issue.
I mostly looked at https://github.com/OpenAPITools/openapi-generator/pull/18916 to see what needed to be changed, hope I didn't miss anything :)
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)
``` …
```

feat(typescript-angular): add support for Angular V18.1

---

modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/Serializer.kt.mustache
samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt

Currently kotlinx serialization doesn't encode properties that have the default value, which is a bit strange and can lead to errors.
Here you can find more information about it.
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded-by-default
```
@Serializable
data class Project(val name: String, val language: String = "Kotlin")
fun main() {
val data = Project("kotlinx.serialization")
println(Json.encodeToString(data))
}
```
This code will have the following output
```
{"name":"kotlinx.serialization"}
```
Which will lead to errors if the server is not expecting this behaviour.
```
``` 
(For Windows users, please run the …

[Kotlin][Client] Encode default values with kotlinx serialization

---

modules/openapi-generator/src/main/resources/java-camel-server/pojo.mustache
samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Category.java
samples/server/petstore/java-camel/src/main/java/org/openapitools/model/ModelApiResponse.java
samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Order.java
samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Pet.java
samples/server/petstore/java-camel/src/main/java/org/openapitools/model/Tag.java
samples/server/petstore/java-camel/src/main/java/org/openapitools/model/User.java

#18870 broke the java-camel samples. see https://github.com/OpenAPITools/openapi-generator/pull/18870#issuecomment-2208661491 . In this PR I revert the problematic change.
java-camel re-uses the pojo.mustache file from JavaSpring. Since the mentioned change only breaks the java-camel sample but not the JavaSpring sample, I copied pojo.mustache from JavaSpring to java-camel and reverted the relevant change only there; not for JavaSpring.
```
``` 
These must …

[JAVA-CAMEL] revert broken xml change

---

modules/openapi-generator/src/main/resources/go/model_simple.mustache
samples/client/echo_api/go-external-refs/model_pet.go
samples/client/echo_api/go/model_pet.go
samples/client/others/go/allof_multiple_ref_and_discriminator/model_additional_data.go
samples/client/others/go/allof_multiple_ref_and_discriminator/model_base_item.go
samples/client/others/go/allof_multiple_ref_and_discriminator/model_final_item.go
samples/client/others/go/oneof-anyof-required/model_nested_object1.go
samples/client/others/go/oneof-anyof-required/model_nested_object2.go
samples/client/petstore/go/go-petstore/model_animal.go
samples/client/petstore/go/go-petstore/model_category.go
samples/client/petstore/go/go-petstore/model_enum_test_.go
samples/client/petstore/go/go-petstore/model_format_test_.go
samples/client/petstore/go/go-petstore/model_name.go
samples/client/petstore/go/go-petstore/model_pet.go
samples/client/petstore/go/go-petstore/model_type_holder_default.go
samples/client/petstore/go/go-petstore/model_type_holder_example.go
samples/openapi3/client/petstore/go-petstore-generateMarshalJSON-false/model_pet.go
samples/openapi3/client/petstore/go/go-petstore/model_category.go
samples/openapi3/client/petstore/go/go-petstore/model_foo.go

a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/19232
```
``` 

update docstring in go client, better code format

---

modules/openapi-generator/src/main/resources/powershell/api.mustache
samples/client/echo_api/powershell/src/PSOpenAPITools/Api/BodyApi.ps1
samples/client/petstore/powershell/src/PSPetstore/Api/PSFakeApi.ps1
samples/client/petstore/powershell/src/PSPetstore/Api/PSPetApi.ps1

When the path of an object of type `System.IO.FileInfo` is relative, the full path is calculated using as directory the value returned by `[System.IO.Directory]::GetCurrentDirectory()`, which is a constant rather than the value returned by `Get-Location`. See [Issue #18428](https://github.com/OpenAPITools/openapi-generator/issues/18428)
This fix uses the method [GetUnresolvedProviderPathFromPSPath](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.pathintrinsics.getunresolvedproviderpathfrompspath?view=powershellsdk-1.1.0) to resolve a path relative to the current directory. Only form parameters of type `System.IO.FileInfo` are affected.
```
``` 
(For Windows …

[PowerShell][Bug] Fix issue #18428 - [System.IO.FileInfo] object used in multipart/form-data submission does not support relative paths 

---

modules/openapi-generator/src/main/resources/python/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/java/autoset_constant.yaml

https://github.com/OpenAPITools/openapi-generator/pull/16761 introduced Python code to set default header or query string value when OpenAPI parameter is  required and has one enum value (have to use `--additional-properties autosetConstants=true` to activate functionality).
The Python mustache template tries to add parameter to `_query_params` dict, but `query_params` is a list:
```
_query_params: List[Tuple[str, str]] = []
...
_query_params['{{baseName}}'] = {{#_enum}}'{{{.}}}'{{/_enum}} # wrong
```
https://github.com/prashant-pant/openapi-generator/blob/21ee1101f5fb310904ae904018cee93d249b796d/modules/openapi-generator/src/main/resources/python/api.mustache#L196-L228
This PR updates mustache template to append query string tuple to `_query_string` list.
- [ x] Read the [contribution …

[BUG] [Python] Fix autoset constants Python code for default query string value

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

This PR removes the loop, but not the early return, when a model name appears in `schemaMappings`, because it doesn't do what it looks like it's doing and that causes issues for mapping to generic classes in Java on windows, and potentially more generators.
That method relied on the faulty assumption that toModelFilename does not consider mappings, which is not the case.
Fixes #19167 (and the duplicate #19174), and tested with the reproducer from that ticket.
My understanding is that this doesn't regress any observable behavior, because the early return is kept around so the model doesn't get generated in the first place and the file paths that should be skipped are never actually reached.
``` …
```

Don't explicity skip templates for not-imported, mapped models/schemas

---

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net6/ParameterMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/UseDateTimeForDate/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs

- async should never be blocked on the ApiClient To fix we invert the logic and use Task as base and keep consistency, we expect and wait result only on synchronous calls.
- Fixes #19176 
```
```  …

[csharp] #19176 fix Task.Result directly blocks thread

---

modules/openapi-generator-core/src/test/java/org/openapitools/codegen/config/WorkflowSettingsTest.java

Refactored certain identifiers to more appropriate names according to the identifier's usages. This is to improve code clarity.
```
```  …

Refactored Identifiers

---

modules/openapi-generator/src/main/resources/php-nextgen/ObjectSerializer.mustache
modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
samples/client/echo_api/php-nextgen/src/ObjectSerializer.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/ObjectSerializer.php
samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/OpenAPIClient-php/tests/ObjectSerializerTest.php
samples/client/petstore/php/psr-18/lib/ObjectSerializer.php

Fix for https://github.com/OpenAPITools/openapi-generator/issues/19233

[BUG] PHP Client - ObjectSerializer::buildQuery flattens array params resulting invalid URL params (param=a&param=b vs param[]=a&param[]=b) #19233

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaHelidonCommonCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/languages/HelidonCommonCodegenTest.java

The Helidon generators permit users to specify which Helidon version to refer to in the generated code. The code which processes the Helidon version validates the user-specified version against known Helidon releases if possible.
This small enhancement (to the Helidon generators only) allows users to refer to unpublished releases (such as a snapshot release).
The PR includes an additional unit test for this use case.
```
```  …

Minor change to Helidon version handling allowing snapshot versions

---

modules/openapi-generator/src/main/resources/powershell/api_client.mustache
samples/client/echo_api/powershell/src/PSOpenAPITools/Private/ApiClient.ps1
samples/client/petstore/powershell/src/PSPetstore/Private/PSApiClient.ps1

This PR fixes an issue when the received response is of type `application/octet-stream` rather than `application/json`. 
`DeserializeResponse` in `api_client.mustache` expects a parameter of type `string`. Since the associated type of a binary content type is `Byte[]` and no intrinsic conversion exists, an exception is thrown.
The commit modifies the type of the parameter `$Response` to `Object`, so the function can handle both text and binary response bodies (if it is binary and the Content-Type of the response is correct, the parameter is returned as-is).
```
``` 
This is …

[PowerShell] Fix response type on deserialization

---

modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/model/GeneratorInput.java
modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/Generator.java
modules/openapi-generator-online/src/test/java/org/openapitools/codegen/online/api/GenApiControllerTest.java

Added support for openapi-normalizer in the online version with a minimal test. 
To fix #18677.
The changes done are the following:
- Added an openapiNormalizer List<String> argument to the api (if this is not a desired change i can just put it in the options object and just parse the list of strings).
- Wrote the feature in a similar manner as in the generator-cli code.
- Wrote a minimal test that checks that the normalized version code is less (or equal) in size to the not normalized version.
```
``` 
Commit all changed files. [In my case it did not create any changes] …

Added support for openapi-normalizer in the online version.

---

modules/openapi-generator/src/main/resources/dart2/gitignore.mustache

gitignore only supports line comments, not in-line comments

fix invalid syntax in gitignore

---

modules/openapi-generator/src/main/resources/powershell/api_client.mustache
samples/client/echo_api/powershell/src/PSOpenAPITools/Private/ApiClient.ps1
samples/client/petstore/powershell/src/PSPetstore/Private/PSApiClient.ps1

This fix covers the case  of a 204 “No content” response with no `Content-Type:` header.
In the code of `DeserializeResponse` there is a check for the parameter `$ContentTypes` being `$null` , but `[AllowNull()]` is missing in the parameter declaration, so the function throws an exception when called.
```
```  …

[PowerShell] Fix missing Content-Type header on a 204 response

---

modules/openapi-generator/src/main/resources/cpp-pistache-server/api-header.mustache
modules/openapi-generator/src/main/resources/cpp-pistache-server/api-source.mustache
samples/server/petstore/cpp-pistache-everything/api/PetApi.cpp
samples/server/petstore/cpp-pistache-everything/api/PetApi.h
samples/server/petstore/cpp-pistache-everything/api/StoreApi.cpp
samples/server/petstore/cpp-pistache-everything/api/StoreApi.h
samples/server/petstore/cpp-pistache-everything/api/UserApi.cpp
samples/server/petstore/cpp-pistache-everything/api/UserApi.h
samples/server/petstore/cpp-pistache-nested-schema-refs/api/StoreApi.cpp
samples/server/petstore/cpp-pistache-nested-schema-refs/api/StoreApi.h
samples/server/petstore/cpp-pistache/api/PetApi.cpp
samples/server/petstore/cpp-pistache/api/PetApi.h
samples/server/petstore/cpp-pistache/api/StoreApi.cpp
samples/server/petstore/cpp-pistache/api/StoreApi.h
samples/server/petstore/cpp-pistache/api/UserApi.cpp
samples/server/petstore/cpp-pistache/api/UserApi.h

This allows overriders to have full access to the response object and more finely control the error handling behavior.
For example, this enables the specification of a proper `Content-Type` header in case of custom format responses (application/json, application/problem+json,...)
This should be backward compatible, providing a second overloaded version with full response access to chose from if needed. The new version taking priority if both overloads are overridden.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would …

[C++][Pistache] Add error handlers overload taking the response object

---

modules/openapi-generator/src/main/resources/cpp-pistache-server/helpers-header.mustache
samples/server/petstore/cpp-pistache-everything/model/Helpers.h
samples/server/petstore/cpp-pistache-nested-schema-refs/model/Helpers.h
samples/server/petstore/cpp-pistache/model/Helpers.h

[C++][Pistache] Fix 'unused-parameter' warning on Helpers.h file

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/echo_api/java/okhttp-gson-user-defined-templates/src/main/java/org/openapitools/client/ApiClient.java
samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-oneOf/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

fix #16362
This is based on the PR by @spraot: #18808
> Build URL again after applying auths so that any necessary query params are added there.
>
> Potentially still issues if there is an auth that changes the query parameters and an auth that hashes the query params and those are run in the wrong order. But those cases are unlikely (two types of auths?) and broken anyways with existing code.
I made another fix on top of his PR so that it actually works now. Before, `allQueryParams` was updated, but never used.
```
```  …

[JAVA] use query parameter apikey if present 

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml

Minor core code refactor spotted while doing other development.
Currently we split Operation ID generation across two functions: `getOrGenerateOperationId` and `fromOperation`
This refactor moves all of the code into `getOrGenerateOperationId`
This has a knock-on effect, which means that callback operation IDs now get correctly created with a camel case name - I think this is an improvement.
```
```  …

[Core] Consolidate Operation ID generation

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml
samples/client/echo_api/java/okhttp-gson-user-defined-templates/src/main/java/org/openapitools/client/ApiClient.java
samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-oneOf/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/README.md
samples/client/petstore/java/okhttp-gson/api/openapi.yaml
samples/client/petstore/java/okhttp-gson/docs/DefaultApi.md
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/DefaultApi.java

Fix issue https://github.com/OpenAPITools/openapi-generator/issues/19225

[Java][OkHttp-Gson] fix: free form query parameters for okhttp-gson

---

modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
modules/openapi-generator/src/main/resources/rust-server/client-imports.mustache
modules/openapi-generator/src/main/resources/rust-server/generate-multipart-related.mustache
modules/openapi-generator/src/main/resources/rust-server/server-request-body-multipart-related.mustache
samples/server/petstore/rust-server/output/multipart-v3/Cargo.toml
samples/server/petstore/rust-server/output/multipart-v3/src/client/mod.rs
samples/server/petstore/rust-server/output/multipart-v3/src/server/mod.rs

Use functions from the https://github.com/Metaswitch/swagger-rs crate for multipart/related helper functions, rather than including the logic in every generated crate.
This updates the generated code to use functions from the swagger-rs crate, rather than having hand rolled code in each crate. Code in the support crate is easier to test, update and bug fix, rather than generated code which requires each generated crate to be updated.
Support was added in 5.0 - the generated code already uses the swagger-rs 6
```
```  …

[Rust Server] Use swagger/multipart_related support

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
modules/openapi-generator/src/main/resources/go/model_simple.mustache
modules/openapi-generator/src/test/resources/3_0/go/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
samples/openapi3/client/petstore/go/go-petstore/api/openapi.yaml
samples/openapi3/client/petstore/go/go-petstore/docs/FormatTest.md
samples/openapi3/client/petstore/go/go-petstore/model_format_test_.go

to close https://github.com/OpenAPITools/openapi-generator/issues/19102
```
``` 
cc 
@antihax …

Better handling of backtick in pattern

---

docker-entrypoint.sh

```
``` 
---
Hi! This is nothing serious. The file was changed to have the same indent style (4 spaces). Also the do start of the loop was in a separate line when the rest of the file followed more popular convention with ifs
```
if ...; then
code
```
instead of
```
if ...
then
code
```
EDIT: Grammar

docker-entrypoint.sh fix mixed indent + move do to same line as start of loop 

---

modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache

This fixes a missing quote in `Cargo.toml`, which causes validation errors
```
error: failed to parse manifest at `api/rust/Cargo.toml`
Caused by:
could not parse input as TOML
Caused by:
newline in string found at line 11 column 49
```
```
```  …

[Rust Server] Fix homepage URL in Cargo.toml

---

.github/workflows/samples-rust.yaml
modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
samples/server/petstore/rust-server/output/multipart-v3/Cargo.toml
samples/server/petstore/rust-server/output/no-example-v3/Cargo.toml
samples/server/petstore/rust-server/output/openapi-v3/Cargo.toml
samples/server/petstore/rust-server/output/ops-v3/Cargo.toml
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml
samples/server/petstore/rust-server/output/ping-bearer-auth/Cargo.toml
samples/server/petstore/rust-server/output/rust-server-test/Cargo.toml

- Enforce that all features build as part of CI, by passing `--all-features` to the build.
- Upgrade `frunk` to `0.4`. This is required to bring in https://github.com/lloydmeta/frunk/pull/186 which is required to fix the following compile error:
```
error[E0412]: cannot find type `_uc` in module `frunk_core::labelled::chars`
--> output/petstore-with-fake-endpoints-models-for-testing/src/models.rs:565:43
|
565 | #[cfg_attr(feature = "conversion", derive(frunk::LabelledGeneric))]
|                                           ^^^^^^^^^^^^^^^^^^^^^^ not found in `frunk_core::labelled::chars`
|
= note: this error originates in the derive macro `frunk::LabelledGeneric` (in Nightly builds, run with -Z macro-backtrace for more info)
```
This is caused by sanitised identifiers like `r#type` which …

[Rust] Ensure all features build as part of CI / Upgrade to Frunk 0.4

---

modules/openapi-generator/src/main/resources/rust-server/README.mustache
samples/server/petstore/rust-server/output/multipart-v3/README.md
samples/server/petstore/rust-server/output/no-example-v3/README.md
samples/server/petstore/rust-server/output/openapi-v3/README.md
samples/server/petstore/rust-server/output/ops-v3/README.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/README.md
samples/server/petstore/rust-server/output/ping-bearer-auth/README.md
samples/server/petstore/rust-server/output/rust-server-test/README.md

The generated README says
```
You can use the example server and client as a basis for your own code.
See below for [more detail on implementing a server](#writing-a-server).
```
but the `Writing a server section` was removed in https://github.com/OpenAPITools/openapi-generator/pull/3552, and replaced by a briefer note under `Using the generated library`.
This fixes the link to point to a section that exists.
This fix was contributed by @kw217
```
``` 
These …

[Rust Server] Fix server-writing docs for rust-server

---

modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache
samples/client/echo_api/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/models/StringEnumRef.kt
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/models/StringEnumRef.kt

Support for unknown default enum values was added in #17404, but this works for only inner enums in data classes.
This PR fixes to work for top-level enums as well.
```
```  …

[kotlin-client][jackson] Add missing @JsonEnumDefaultValue annotation to top-level enums

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
samples/server/petstore/rust-server/output/openapi-v3/README.md
samples/server/petstore/rust-server/output/openapi-v3/docs/default_api.md
samples/server/petstore/rust-server/output/openapi-v3/examples/client/main.rs
samples/server/petstore/rust-server/output/openapi-v3/examples/server/server.rs
samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/README.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/fake_api.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/pet_api.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/store_api.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/user_api.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/client/main.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/server/server.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs

In the generated Rust Server code, the order of the operations list determines the order of cases in a match statement.
This meant that if we had two operations (say, `/foo/bar/` and `/foo/{something}`) where a given path (`/foo/bar`) could match both, it matched the operation whose `operationId` was alphabetically first, rather than following https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#pathsObject which says:
> When matching URLs, concrete (non-templated) paths would be matched before their templated counterparts.
This sorts the operations so that the ones with fewest path parameters come first, which does meet that requirement.
This fix was contributed by @rkd-msw
``` …
```

[Rust Server] Sort operations so that the ones with fewest params come first

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/feign/build.sbt.mustache
pom.xml
samples/client/echo_api/java/feign-gson/build.gradle
samples/client/echo_api/java/feign-gson/build.sbt
samples/client/petstore/java/feign-no-nullable/build.gradle
samples/client/petstore/java/feign-no-nullable/build.sbt
samples/client/petstore/java/feign/build.gradle
samples/client/petstore/java/feign/build.sbt

Upgrade commons-io dependency to latest 2.16.1.
Currently the main pom.xml has [commons-io 2.11.0 released 2021](https://github.com/apache/commons-io/releases/tag/rel%2Fcommons-io-2.11.0).
Currently the modules and samples have [commons-io 2.8.0 released 2020](https://github.com/apache/commons-io/releases/tag/rel%2Fcommons-io-2.8.0).
```
``` 
You may regenerate an individual generator by passing …

Upgrade commons-io dependency to latest 2.16.1

---

modules/openapi-generator/src/main/resources/go/model_simple.mustache

[Go] fix regex validation breakage in unmarshaljson function

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/oneof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/oneof_model.mustache

The code generation template for the Jersey Java client had an extra bracket for Boolean deserialization, that made the code not compile.
```
```  …

[Java] Remove extra bracket to fix compilation of Jersey clients (trivial)

---

modules/openapi-generator/src/main/resources/typescript/types/ObservableAPI.mustache
samples/client/others/typescript/builds/with-unique-items/types/ObservableAPI.ts
samples/openapi3/client/petstore/typescript/builds/browser/types/ObservableAPI.ts
samples/openapi3/client/petstore/typescript/builds/composed-schemas/types/ObservableAPI.ts
samples/openapi3/client/petstore/typescript/builds/default/types/ObservableAPI.ts
samples/openapi3/client/petstore/typescript/builds/deno/types/ObservableAPI.ts
samples/openapi3/client/petstore/typescript/builds/inversify/types/ObservableAPI.ts
samples/openapi3/client/petstore/typescript/builds/jquery/types/ObservableAPI.ts
samples/openapi3/client/petstore/typescript/builds/object_params/types/ObservableAPI.ts

- **style: use const for `middleware`** (c285a63ab1dcc9d1d4a8d23b9cefa5d30f4418ec is the only meaningful change, rest of pull request is generated code)
- **chore: update generated code samples**
```
```

[typescript] use `const` for `middleware` symbol

---

README.md

This adds documentation on how to use a locally built JAR and/or a snapshot version with the npm-based generator package.
@macjohnny as promised 🎉 
```
``` 

docs: add hints about how to use snapshot version of `generator-cli`

---

modules/openapi-generator/src/main/resources/go/README.mustache
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/README.md

Generates a working example of api key auth in README.md.
cc @antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5
closes #19490
```
```  …

bugfix: use the correct key when generating auth example in readme

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/validation-attributes/models/Pet.ts

Resolves https://github.com/OpenAPITools/openapi-generator/issues/19520 
This PR aims to fix the above bug, by ensuring that set properties from API responses are correctly initialized as sets instead of being passed directly as arrays. 
`isPrimitiveType` appears to be true for arrays which contain primitives, not just for primitives themselves. Because of the template conditions, this means that arrays of primitives were being passed verbatim from the API response. 
This logic is fine for regular arrays, but for sets this causes a problem, as the values aren't being converted to a `Set` after being retrieved from the API. This leads to issues where the client thinks the property is a `Set`, but it's actually an array. The outcome of this is that accessing `Set` members such as `size` …

[typescript-fetch] Fixed issue where unique arrays (sets) of primitive values aren't initialized properly 

---

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom-sb3.mustache
samples/openapi3/server/petstore/springboot-3/pom.xml
samples/server/petstore/springboot-file-delegate-optional/pom.xml
samples/server/petstore/springboot-lombok-tostring/pom.xml

```
``` 
@cachescrubber @welshm @MelleD @atextor @manedev79 @javisst @borsch @banlevente …

[Java][Spring]Update dependencies to remove vulnerability in org.springframework:spring-webmvc

---

modules/openapi-generator/src/main/resources/swift5/Extensions.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/anycodableLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/Extensions.swift
samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/vaporLibrary/Sources/PetstoreClient/Extensions.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/Extensions.swift

This PR aims to address https://github.com/OpenAPITools/openapi-generator/issues/19459 with the solution provided by @borsosbe.
Mentioning swift tech commitee: @dydus0x14 @4brunu @jgavris @ehyche @Edubits @jaz-ah for visibility into the issue.
```
```  …

[swift5] Fix Xcode 16 compilation crash with Extensions.swift generation

---

modules/openapi-generator/src/main/resources/typescript-axios/modelEnum.mustache
samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts

fix: https://github.com/OpenAPITools/openapi-generator/issues/19570
```
``` 

[typescript-axios] fix: enum datatype jsdoc (#19570)

---

docs/debugging.md

This adds a hint on how to attach the VSCode debugger to the suspended process
```
``` 

docs: add hint about how to attach VSCode to the suspended Java process

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/goserver/GoServerCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/go-server/route-order.yaml
samples/openapi3/server/petstore/go/go-petstore/go/api.go
samples/openapi3/server/petstore/go/go-petstore/go/api_pet.go
samples/openapi3/server/petstore/go/go-petstore/go/api_pet_service.go
samples/openapi3/server/petstore/go/go-petstore/go/api_store.go
samples/openapi3/server/petstore/go/go-petstore/go/api_store_service.go
samples/openapi3/server/petstore/go/go-petstore/go/api_user.go
samples/openapi3/server/petstore/go/go-petstore/go/api_user_service.go
samples/server/petstore/go-api-server/go/api.go
samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_pet_service.go
samples/server/petstore/go-api-server/go/api_store.go
samples/server/petstore/go-api-server/go/api_store_service.go
samples/server/petstore/go-api-server/go/api_user.go
samples/server/petstore/go-api-server/go/api_user_service.go
samples/server/petstore/go-chi-server/go/api.go
samples/server/petstore/go-chi-server/go/api_pet.go
samples/server/petstore/go-chi-server/go/api_pet_service.go
samples/server/petstore/go-chi-server/go/api_store.go
samples/server/petstore/go-chi-server/go/api_store_service.go
samples/server/petstore/go-chi-server/go/api_user.go
samples/server/petstore/go-chi-server/go/api_user_service.go

This PR adds a configuration property (`skipSortingOperations`) to skip sorting the operations alphabetically. Sorting the operations, which is the default behaviour, is fine for most generators but it is an issue for the Go Server generator (where the order of the routes matters).
Fix #19445 
```
```  …

[GO] Go Server: preserve order of the routes as defined in the OpenAPI file

---

modules/openapi-generator/src/main/resources/php-symfony/model_generic.mustache

This PR fixes #19562. I did run the scripts to regenerate the samples, but it appears there is no symfony sample that triggers this code path.
I decided to use `!is_null(...)` instead of the suggested `is_string(...)` because that would break all integer enums.
Both `is_null` and `is_string` would cause a PHP warning if the variable was not set, but I think we can ignore that since it is always set to the default value or null (if no default value exists) in the template.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it …

[php-symfony] Fix enum not serialized with value like '0'

---

docs/generators/kotlin.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/Serializer.kt.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinClientCodegenModelTest.java
samples/client/echo_api/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-jvm-jackson/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-jvm-spring-2-webclient/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-jvm-vertx-jackson-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-jvm-vertx-jackson/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-retrofit2-jackson/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt

This PR intents to fix #19408 and to have the same default behavior as the Java clients' i.e. being able to configure the Jackson's ObjectMapper FAIL_ON_UNKNOWN_PROPERTIES. 
```
```  …

[Kotlin] Add a new additional property to configure Jackson's `failOnUnknownProperties`

---

samples/client/petstore/php/OpenAPIClient-php/tests/EnumTestTest.php

This is a follow-up to https://github.com/OpenAPITools/openapi-generator/pull/19555 that updates the failing enum tests. All test cases in the EnumTestTest class are now passing.
For some reason, other tests that try to use the addPet endpoint are failing with a `405 Method Not Allowed`  error.
I am not sure what the issue is there, but these tests are failing in master, event before the changes from #19555.
```
```  …

[PHP] Update enum tests

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/LocalDateAdapter.kt.mustache
modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/LocalDateTimeAdapter.kt.mustache
modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/LocalTimeAdapter.kt.mustache
modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/Serializer.kt.mustache
samples/client/petstore/kotlin-kotlinx-datetime/.openapi-generator/FILES
samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/LocalDateTimeAdapter.kt
samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/LocalTimeAdapter.kt
samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt

```
``` 
@dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier

[kotlin-client][multiplatform] add support for kotlinx.datetime.LocalTime

---

modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/deserialize.mustache
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/deserialize.dart

To fix #19495, to allow deserialization of dictionary/map response types.
```
``` 

[dart-dio] Fix dictionary/map deserialization, fixes #19495

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/api.mustache
samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/api/PathApi.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/UserApi.java

With collections, calling toString will result in the value becoming [a,b] instead of just a,b.
Using the existing apiClient::parameterToString method ensures it gets parsed correctly if it is a collection
---
Currently apache-httpclient does not comply with OAS 3.0 regarding parameter serialization of path variables:
https://swagger.io/docs/specification/serialization/
With an apache-httpclient calling a generated client for an endpoint `/users/3,4,5` will cause it to call `/users/[3,4,5]` because of the toString() being called on the collection.
This PR will fix that.
Using the current apache-httpclient template causes the following code to be generated:
Obviously it will never end well, calling toString() on a collection. So, instead, I changed the template to call …

[Java] [apache-httpclient] Fix issue with toString causing wrong value with collections

---

modules/openapi-generator/src/main/resources/rust-server/client-operation.mustache
samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
samples/server/petstore/rust-server/output/ping-bearer-auth/src/client/mod.rs

The comment about auth types supported by the generator shouldn't be
included in the generated code as it's confusing when the API doesn't
support the same auth types.
As such, we convert it from a Rust comment to a Mustache comment
```
```  …

[Rust Server] Convert Rust comment to Mustache

---

modules/openapi-generator/src/main/resources/rust-server/models.mustache
samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs

Add derive of Hash to enums. This is always valid, as they don't contain data
This change was contributed by @CastleQuirm
```
```  …

[Rust Server] Add derive of Hash to enums

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/resources/rust-server/models.mustache
modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
samples/server/petstore/rust-server/output/multipart-v3/src/models.rs
samples/server/petstore/rust-server/output/no-example-v3/src/models.rs
samples/server/petstore/rust-server/output/openapi-v3/.openapi-generator/FILES
samples/server/petstore/rust-server/output/openapi-v3/README.md
samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
samples/server/petstore/rust-server/output/openapi-v3/docs/AdditionalPropertiesWithNullable.md
samples/server/petstore/rust-server/output/openapi-v3/docs/NullableObject.md
samples/server/petstore/rust-server/output/openapi-v3/docs/NullableTest.md
samples/server/petstore/rust-server/output/openapi-v3/docs/ObjectUntypedProps.md
samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs
samples/server/petstore/rust-server/output/rust-server-test/src/models.rs

With:
```
sampleObject:
type: object
$ref: '#/components/schemas/SampleData'
minProperties: 1
description: Map of Charging data policy decisions.
```
and
```
SampleData:
type: object
...
nullable: true
```
We currently generate: `HashMap<String, SampleData>`, which doesn't allow null sample data entries. This MR changes this to be `HashMap<String, swagger::Nullable<SampleData>>`, which thus will allow null sample data entries.
We do this by moving null-handling to the Java code - primarily `getTypeDeclaration()`.
Note, to some extent this is wrong. In this MR (and previously) we are treating `nullable: true` as an extrinsic property (like required), whereas it should be an intrinsic property (and thus `HashMap<String, SampleData>` is correct, but `SampleData` absorbs …

[Rust Server] Handle additional properties being nullable

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/README.mustache

Fixes #19431, I think. I didn't have to commit any snapshot changes, though, which leads me to think that maybe I'm doing it wrong?
Per below instructions, tagging Java members: @martin-mfg @lwlee2608 
```
```  …

fix: make generated java readme use correct package

---

modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradle-sb3-Kts.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-cloud/buildGradle-sb3-Kts.mustache

When I generate with `"useSwaggerUI": "false"`, It generates bellow dependency.
```
implementation("org.springdoc:springdoc-openapi-webmvc-core:2.2.0-M5")
```
But it is incorrect dependency(this version is not exists.), so I'm getting the following error.
```
Could not find org.springdoc:springdoc-openapi-webmvc-core:2.2.0-M5.
```
I fixed it to use version springdoc v2.
ref: https://springdoc.org/#migrating-from-springdoc-v1
```
```  …

[kotlin-spring] fix springdoc dependencies 

---

modules/openapi-generator/src/main/resources/aspnetcore/3.0/Startup.mustache
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-6.0-NewtonsoftFalse/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-6.0-pocoModels/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-6.0/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-8.0-NewtonsoftFalse/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-8.0-nullableReferenceTypes/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-8.0-pocoModels/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-8.0-project4Models/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-8.0/src/Org.OpenAPITools/Startup.cs

This fixes issue #19592. Tested by building and applying the fix to the example given in the issue and verified working.
Steps ran from the failure state in the issue (present in sibling directory, hence  `../`):
```
java -jar ../openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g aspnetcore -i openapi.yaml
dotnet test src/Org.OpenAPITools.Tests
```
```
```  …

[aspnetcore] Fix issue #19592 regarding swagger xml comments

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpReducedClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestSdkClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaCaskServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/lib/src/deserialize.dart
samples/server/petstore/rust-server/output/openapi-v3/.openapi-generator/FILES
samples/server/petstore/rust-server/output/openapi-v3/README.md
samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
samples/server/petstore/rust-server/output/openapi-v3/docs/AdditionalPropertiesReferencedAnyOfObject.md
samples/server/petstore/rust-server/output/openapi-v3/src/models.rs

Handle references in additionalProperties correctly when determining free-form status.
This requires ModelUtils to take a reference to the OpenAPI document, to allow it to resolve the reference.
```
```  …

[Core/Rust Server] Check references in additionalProperties correctly when checking freeForm status

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/resources/rust-server/client-request-body-instance.mustache
modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
samples/server/petstore/rust-server/output/openapi-v3/Cargo.toml
samples/server/petstore/rust-server/output/openapi-v3/README.md
samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
samples/server/petstore/rust-server/output/openapi-v3/bin/cli.rs
samples/server/petstore/rust-server/output/openapi-v3/docs/default_api.md
samples/server/petstore/rust-server/output/openapi-v3/examples/client/main.rs
samples/server/petstore/rust-server/output/openapi-v3/examples/server/server.rs
samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs

Add support for arrays in forms (application/x-www-url-form-urlencoded) with the style properties `style=form,explode=true`.
```
```  …

[Rust Server] Handle arrays in forms

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

to close https://github.com/OpenAPITools/openapi-generator/issues/7319
```
```  …

Use debug instead of warn, error to show less log

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
modules/openapi-generator/src/test/resources/3_0/php-nextgen/petstore-with-fake-endpoints-models-for-testing.yaml
modules/openapi-generator/src/test/resources/3_0/php/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/echo_api/php-nextgen-streaming/docs/Api/HeaderApi.md
samples/client/echo_api/php-nextgen-streaming/docs/Api/PathApi.md
samples/client/echo_api/php-nextgen-streaming/docs/Api/QueryApi.md
samples/client/echo_api/php-nextgen-streaming/src/Api/HeaderApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/PathApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/QueryApi.php
samples/client/echo_api/php-nextgen/docs/Api/HeaderApi.md
samples/client/echo_api/php-nextgen/docs/Api/PathApi.md
samples/client/echo_api/php-nextgen/docs/Api/QueryApi.md
samples/client/echo_api/php-nextgen/src/Api/HeaderApi.php
samples/client/echo_api/php-nextgen/src/Api/PathApi.php
samples/client/echo_api/php-nextgen/src/Api/QueryApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/README.md
samples/client/petstore/php-nextgen/OpenAPIClient-php/docs/Api/FakeApi.md
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeApi.php
samples/client/petstore/php/OpenAPIClient-php/README.md
samples/client/petstore/php/OpenAPIClient-php/docs/Api/FakeApi.md
samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/psr-18/README.md
samples/client/petstore/php/psr-18/docs/Api/FakeApi.md
samples/client/petstore/php/psr-18/lib/Api/FakeApi.php

If you have an endpoint that takes a single instance of an enum as a parameter, its Qualifier (e.g. \OpenAPI\Client\Model) is missing in both the PHPDoc and the function parameter types. This PR fixes that. (See [this method in the echo_api](https://github.com/OpenAPITools/openapi-generator/compare/master...JulianVennen:php-nextgen-imports?expand=1#diff-923b9e098e2ef9b0ceac697463aea0ed6daabf653afcd7bb76fd910009d2df68) for an example).
This PR fixes that by adding an override for getParameterDataType in the AbstractPHPGenerator.
For [some documentation files](https://github.com/OpenAPITools/openapi-generator/compare/master...JulianVennen:php-nextgen-imports?expand=1#diff-767f5a48a015abb767a1fad9e304a3dd2e840a0314da23f451111be94ae11657R514) this causes a duplicated qualifier, but I am …

[PHP] Add missing qualifier for enum parameters

---

modules/openapi-generator/src/main/resources/rust/model.mustache
samples/client/petstore/rust/hyper/petstore/src/models/numeric_enum_testing.rs
samples/client/petstore/rust/hyper0x/petstore/src/models/numeric_enum_testing.rs
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/models/numeric_enum_testing.rs
samples/client/petstore/rust/reqwest/petstore-async/src/models/numeric_enum_testing.rs
samples/client/petstore/rust/reqwest/petstore-avoid-box/src/models/numeric_enum_testing.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/models/numeric_enum_testing.rs
samples/client/petstore/rust/reqwest/petstore/src/models/numeric_enum_testing.rs

Rust docs for `ToString` explicitly recommend implementing `Display`:
> This trait is automatically implemented for any type which implements the Display trait. As such, ToString shouldn’t be implemented directly: Display should be implemented instead, and you get the ToString implementation for free.
See: https://doc.rust-lang.org/std/string/trait.ToString.html
See: https://github.com/Nitrokey/nethsm-sdk-rs/pull/33
Since this is about Rust, CC'ing @frol @farcaller @richardwhiuk @paladinzh @jacob-pro
```
``` 
This is important, as CI jobs will verify _all_ generator outputs …

rust: Implement `Display` instead of `ToString` for enums

---

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache
samples/server/petstore/python-fastapi/requirements.txt

Update the requirements.txt template for the python-fastapi generator to use updated dependency versions:
- Change PyYAML==5.4.1 to PyYAML>=5.4.1,<6.1.0
- Change httptools>=0.1.2 to httptools>=0.3.0,<0.7.0
This should resolve the compatibility issues with Python 3.12 and allow successful installation of the dependencies.
See issue [19665](https://github.com/OpenAPITools/openapi-generator/issues/19665)
Thank you!
```
```  …

[BUG][python-fastapi] Updated pyyaml and httptools in requirements template to resolve compatibility issues with Python 3.12

---

modules/openapi-generator/src/main/resources/Javascript/partial_model_generic.mustache
samples/client/petstore/javascript-apollo/src/model/Animal.js
samples/client/petstore/javascript-apollo/src/model/Foo.js
samples/client/petstore/javascript-apollo/src/model/Order.js
samples/client/petstore/javascript-es6/src/model/Animal.js
samples/client/petstore/javascript-es6/src/model/Foo.js
samples/client/petstore/javascript-es6/src/model/Order.js
samples/client/petstore/javascript-promise-es6/src/model/Animal.js
samples/client/petstore/javascript-promise-es6/src/model/Foo.js
samples/client/petstore/javascript-promise-es6/src/model/Order.js

Add initialization of default vars to constructor in model template.
```
``` 
Related issue: …

[Javascript] Add initialization of default vars to constructor

---

modules/openapi-generator/src/main/resources/typescript/http/http.mustache
samples/client/others/typescript/builds/array-of-lists/http/http.ts
samples/client/others/typescript/builds/with-unique-items/http/http.ts
samples/client/others/typescript/encode-decode/build/http/http.ts
samples/openapi3/client/petstore/typescript/builds/browser/http/http.ts
samples/openapi3/client/petstore/typescript/builds/composed-schemas/http/http.ts
samples/openapi3/client/petstore/typescript/builds/default/http/http.ts
samples/openapi3/client/petstore/typescript/builds/deno/http/http.ts
samples/openapi3/client/petstore/typescript/builds/deno_object_params/http/http.ts
samples/openapi3/client/petstore/typescript/builds/explode-query/http/http.ts
samples/openapi3/client/petstore/typescript/builds/inversify/http/http.ts
samples/openapi3/client/petstore/typescript/builds/jquery/http/http.ts
samples/openapi3/client/petstore/typescript/builds/nullable-enum/http/http.ts
samples/openapi3/client/petstore/typescript/builds/object_params/http/http.ts

Replaces all inline occurrences of `{ [key:string]: string }` with a convenience type.
```
``` 

style(typescript): use `Headers` type

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
samples/client/others/typescript/builds/null-types-simple/.gitattributes
samples/client/others/typescript/builds/null-types-simple/.openapi-generator/FILES
samples/client/others/typescript/builds/null-types-simple/http/http.ts

test(OpenAPINormalizer): nullability normalization for 3.1 specs

---

modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache

[kotlin] enforce fields in data classes

---

modules/openapi-generator/src/main/resources/zapier/actions.mustache
modules/openapi-generator/src/main/resources/zapier/api.mustache
modules/openapi-generator/src/main/resources/zapier/utils.mustache
samples/client/petstore/zapier/apis/PetApi.js
samples/client/petstore/zapier/apis/StoreApi.js
samples/client/petstore/zapier/apis/UserApi.js
samples/client/petstore/zapier/operations/actions.js
samples/client/petstore/zapier/utils/utils.js

closes https://github.com/OpenAPITools/openapi-generator/issues/19636
```
``` 

zapier: create a search action predicate

---

modules/openapi-generator/src/main/resources/cpp-pistache-server/helpers-header.mustache
samples/server/petstore/cpp-pistache-everything/model/Helpers.h
samples/server/petstore/cpp-pistache-nested-schema-refs/model/Helpers.h
samples/server/petstore/cpp-pistache/model/Helpers.h

This PR fixes #19683 
```
``` 
@ravinikam @stkrwork  @etherealjoy @martindelille  @muttleyxd

Fix #19683 : Generated code fails to build with  x86_64-linux-gnu-g++-13

---

modules/openapi-generator/src/main/resources/erlang-server/api.mustache
modules/openapi-generator/src/main/resources/erlang-server/handler.mustache
modules/openapi-generator/src/main/resources/erlang-server/router.mustache
modules/openapi-generator/src/main/resources/erlang-server/server.mustache
samples/server/echo_api/erlang-server/src/openapi_api.erl
samples/server/echo_api/erlang-server/src/openapi_auth_handler.erl
samples/server/echo_api/erlang-server/src/openapi_body_handler.erl
samples/server/echo_api/erlang-server/src/openapi_form_handler.erl
samples/server/echo_api/erlang-server/src/openapi_header_handler.erl
samples/server/echo_api/erlang-server/src/openapi_path_handler.erl
samples/server/echo_api/erlang-server/src/openapi_query_handler.erl
samples/server/echo_api/erlang-server/src/openapi_router.erl
samples/server/echo_api/erlang-server/src/openapi_server.erl
samples/server/petstore/erlang-server/src/openapi_api.erl
samples/server/petstore/erlang-server/src/openapi_pet_handler.erl
samples/server/petstore/erlang-server/src/openapi_router.erl
samples/server/petstore/erlang-server/src/openapi_server.erl
samples/server/petstore/erlang-server/src/openapi_store_handler.erl
samples/server/petstore/erlang-server/src/openapi_user_handler.erl

If inner path definitions support specialised servers, then add them to the cowboy routes, as previously they'd all be ignored.
```
```  …

Erlang server

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_1/issue_18291.yaml
samples/client/petstore/java/okhttp-gson-3.1/api/openapi.yaml
samples/client/petstore/java/okhttp-gson-3.1/docs/AnyTypeTest.md
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/model/AnyTypeTest.java
samples/client/petstore/rust/reqwest/petstore-async-tokensource/src/models/numeric_enum_testing.rs

- Avoid NPE when handling prefixItems0
- add tests
```
```  …

[OpenAPI 3.1] Avoid NPE when handling prefixItems

---

modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/configuration.rb

```
``` 
Hello, 
As mentionned in this issue : #19737 , in the SecurityScheme generated, the …

[Ruby-client] Use secuirtyScheme Key for api_key

---

modules/openapi-generator/src/main/resources/ruby-client/README.mustache
modules/openapi-generator/src/main/resources/ruby-client/api_doc.mustache
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/README.md
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/docs/UsageApi.md

```
``` 
Hi,
After PR #19740, I forgot to update the documentation generated as the code is …

[Ruby]fix_ruby_documentation_apikey_name

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

This adds the content of the `info.summary` property to the `additionalProperties` in case it is non-empty.
```
```  …

feat(core): add `info.summary` to `additionalProperties` for `3.1` specs

---

docs/generators/swift5.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
modules/openapi-generator/src/main/resources/swift5/modelOneOf.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/Swift5OptionsProvider.java

Hi, thanks for your tool, it's amazing!
After using it for a while I found out that I need a flag for generating additional default unknown case in OneOf (for client 
backward compatibility to avoid decoding fail in earlier client version)
So this is my vision of how it can be done
```
```  …

add oneOf-default-case option for swift5

---

docs/generators/swift6.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift6ClientCodegen.java
modules/openapi-generator/src/main/resources/swift6/modelOneOf.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/Swift6ClientCodegenOptionsProvider.java

This PR brings the changes of those two PR to swift 6.
https://github.com/OpenAPITools/openapi-generator/pull/19094
https://github.com/OpenAPITools/openapi-generator/pull/19753
```
```  …

[swift6] oneOf-default-case

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_1/issue_18291.yaml
samples/client/petstore/java/okhttp-gson-3.1/api/openapi.yaml

- fix normalization for anyOf, oneOf sub schemas (not being updated before this fix)
- better handling of 3.1 spec in getSchemaItems (model utils class)
- add tests
```
``` 
IMPORTANT: Do …

Fix anyOf/oneOf normalization for 3.1 spec

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

Fixes https://github.com/OpenAPITools/openapi-generator/pull/19616#discussion_r1781264186
The problem is that in the code previously, sorting was done on the platform-specific paths with the platform-specific separator. `\` and `/` sort in different places, hence the order changes.
This pull request does not sort on the file objects, but on the relative, platform-independent path. I wasn't able to use `org.apache.commons.io.comparator.PathFileComparator` directly, as it expects a `File` object, but thankfully the implementation is trivial and we have lambdas :)
Tested on Windows here: https://github.com/OpenAPITools/openapi-generator/pull/19616#issuecomment-2385536683
```
``` 
(For …

fix(core): system-independent relative path sorting for `FILES` output

---

modules/openapi-generator/src/main/resources/erlang-server/api.mustache
samples/server/echo_api/erlang-server/src/openapi_api.erl
samples/server/petstore/erlang-server/src/openapi_api.erl

Three things:
- First of all, fix a bug where `exclusiveMinimum` and `exclusiveMaximum` were considered integers, when they are in fact booleans.
- Add support for validating that strings of format `byte` are indeed `base64` encoded and return them parsed.
- Likewise for strings of format `date-time`.
Other changes are related to general performance optimisations and code quality.
Question, @wing328, I'm not sure to understand how documentation for the capabilities of the generators work, and I'm afraid they might be falling behind with all the recent changes, can you share with me some directions on this? I'd work on that on a follow-up PR though, just to keep this one focused.
``` …
```

Erlang server validation bugfixes and capability extensions

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/HandlebarsEngineAdapter.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/handlebars/AccessAwareFieldValueResolver.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/HandlebarsEngineAdapterTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/handlebars/StringHelpersTest.java

The old MY_FIELD_VALUE_RESOLVER.INSTANCE is equivalent to FieldValueResolver.INSTANCE, which is assigned `new FieldValueResolver();` so our custom class was never used.
This should improve https://github.com/OpenAPITools/openapi-generator/issues/510 somewhat, and finally properly applies the suggestion from https://github.com/jknack/handlebars.java/issues/940#issuecomment-1083817905
```
``` 
You …

[BUG] HandlebarsEngineAdapter.java failed to use custom FieldValueResolver causing IllegalAccessException for maps 

---

modules/openapi-generator/src/main/resources/powershell/api.mustache
samples/client/petstore/powershell/src/PSPetstore/Api/PSUserApi.ps1

This PR aims to correct [Issue #18427 ](https://github.com/OpenAPITools/openapi-generator/issues/18427). The fix submitted by @condorcorde in [PR #19262 ](https://github.com/OpenAPITools/openapi-generator/pull/19262) seems to give a different behavior than the one expected.
When using `$LocalVarBodyParameter = ,$User | ConvertTo-Json  -Depth 100`, `$User` being a 1-element array, the output will look something like this :
`{ "Value" : _content of $User_, "Length" : 1 }`
Which is different from the expected behavior, that is to only get the array itself. This PR fixes this by forcing the cast of $User to an array using the `@()` syntax before converting it to Json.
```
``` 
(For …

[POWERSHELL] fix: keep array context when converting to json

---

modules/openapi-generator/src/main/resources/rust-axum/types.mustache

Fixes the Rust doc tests generated by rust-axum. The doc tests used an invalid `should_panic` attribute, probably a typo.
For reference, this is how a doc test that is expected to panic should look like: https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#attributes
Sorry for not providing a minimal OpenAPI spec to reproduce the issue but I think the problem is obvious and the fix is trivial enough.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as …

Fix rust axum doc tests (#19538)

---

.ddev/web-build/Dockerfile.maven
modules/openapi-generator/src/main/resources/php/HeaderSelector.mustache
modules/openapi-generator/src/main/resources/php/libraries/psr-18/api.mustache
samples/client/petstore/php/OpenAPIClient-php/lib/HeaderSelector.php
samples/client/petstore/php/psr-18/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/psr-18/lib/Api/DefaultApi.php
samples/client/petstore/php/psr-18/lib/Api/FakeApi.php
samples/client/petstore/php/psr-18/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/psr-18/lib/Api/PetApi.php
samples/client/petstore/php/psr-18/lib/Api/StoreApi.php
samples/client/petstore/php/psr-18/lib/Api/UserApi.php
samples/client/petstore/php/psr-18/lib/HeaderSelector.php

Some APIs offer a PATCH-Request method for Entities and use "application/merge-patch+json" as Content-Type. This was not detected as json_encode and ObjectSerializer target and thus resultet in an Exception,
```
Nyholm\Psr7\Request::withBody(): Argument #1 ($body) must be of type Psr\Http\Message\StreamInterface, _XXX__ given, called in XXX
```
This PR fixes this.
```
```  …

[PHP-Client] Allow Content-Type merge-match+json for encoding

---

modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypeScriptNodeClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/typescript-node/SampleProject.yaml
samples/client/petstore/typescript-node/3_0/api/defaultApi.ts
samples/client/petstore/typescript-node/default/api/petApi.ts
samples/client/petstore/typescript-node/npm/api/petApi.ts

Add @deprecated tag when processing deprecated operations in the OpenAPI file
@wing328 I have added a helper method (`assertFileContains(Path path, String line, int lineNumber)`) to verify a specific line (more effective than searching for the string in the file anywhere), let me know if this is ok or you see some drawbacks. Thanks.
```
``` 
You may regenerate an individual generator by passing …

[Typescript-Node] Mark deprecated endpoints

---

modules/openapi-generator/src/main/resources/python/github-workflow.mustache
modules/openapi-generator/src/main/resources/python/pyproject.mustache
modules/openapi-generator/src/main/resources/python/test-requirements.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/.github/workflows/python.yml
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/pyproject.toml
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/test-requirements.txt
samples/client/echo_api/python/.github/workflows/python.yml
samples/client/echo_api/python/pyproject.toml
samples/client/echo_api/python/test-requirements.txt
samples/openapi3/client/petstore/python-aiohttp/.github/workflows/python.yml
samples/openapi3/client/petstore/python-aiohttp/pyproject.toml
samples/openapi3/client/petstore/python-aiohttp/test-requirements.txt
samples/openapi3/client/petstore/python/.github/workflows/python.yml
samples/openapi3/client/petstore/python/pyproject.toml
samples/openapi3/client/petstore/python/test-requirements.txt

Restores the python client dev dependency `pytest-cov` which is required in the generated workflows.
Fixes https://github.com/OpenAPITools/openapi-generator/pull/19694#issuecomment-2391646845.
```
```  …

[Python] Restore required dev dependency + Adjust generated Github workflow

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AvroSchemaCodegen.java
modules/openapi-generator/src/test/resources/3_0/avro-schema/valid-enums.yaml
samples/openapi3/schema/valid-enums/avro-schema-enum/Sample.avsc

Fixes:
```
Download 7.9.0-20241003.092246-97 ...
Downloaded 7.9.0-20241003.092246-97
[[avro-schema] spec.json] [main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[[avro-schema] spec.json] [main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: avro-schema (schema)
[[avro-schema] spec.json] [main] INFO  o.o.codegen.DefaultGenerator - Generator 'avro-schema' is considered beta.
[[avro-schema] spec.json] Exception in thread "main" java.lang.RuntimeException: Could not process model 'Field'.Please make sure that your schema is correct!
[[avro-schema] spec.json] 	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:528)
[[avro-schema] spec.json] 	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:453) …
```

fix(avro-schema): fix NPE for `null` enum values

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_1/simplifyOneOfAnyOf_test.yaml

- Fix issue when schema is a $ref in isNullTypeSchema
- Better handling of primitive type with oneOf
- Add tests
```
```  …

[normalizer] bug fixes (isNullTypeSchema, handling of primitive types with oneOf)

---

modules/openapi-generator/src/main/resources/php-nextgen/api.mustache
modules/openapi-generator/src/main/resources/php/api.mustache
samples/client/echo_api/php-nextgen-streaming/src/Api/AuthApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/BodyApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/FormApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/HeaderApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/PathApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/QueryApi.php
samples/client/echo_api/php-nextgen/src/Api/AuthApi.php
samples/client/echo_api/php-nextgen/src/Api/BodyApi.php
samples/client/echo_api/php-nextgen/src/Api/FormApi.php
samples/client/echo_api/php-nextgen/src/Api/HeaderApi.php
samples/client/echo_api/php-nextgen/src/Api/PathApi.php
samples/client/echo_api/php-nextgen/src/Api/QueryApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/AnotherFakeApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/DefaultApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeClassnameTags123Api.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/PetApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/StoreApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/UserApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php

For **PHP**.
By default should use static Configuration class instance, otherwise new instance is created every time you make an API call.
Before this PR every time you create new API object and do not pass Configuration object as 2nd argument to API class constructor it creates new Configuration instance. This is wrong, because Configuration class is meant to be Singleton - so `Configuration::getDefaultConfiguration()` should be used instead.
Please review: @jebentier @dkarlovi @mandrean @jfastnacht @ybelenko @renepardon

[PHP] By default should use static Configuration class instance

---

README.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaHttp4sClientCodegen.java

a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/19658
```
``` 

Minor improvemetns to new scala client generator

---

modules/openapi-generator/src/main/resources/csharp/ClientUtils.mustache
samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Client/ClientUtils.cs
samples/client/petstore/csharp/restsharp/net6/ParameterMappings/src/Org.OpenAPITools/Client/ClientUtils.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Client/ClientUtils.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Client/ClientUtils.cs
samples/client/petstore/csharp/restsharp/net7/UseDateTimeForDate/src/Org.OpenAPITools/Client/ClientUtils.cs

The DateOnly object was previously unhandled when being converted to a string in `ParameterToString`. This PR adds handling for DateOnly in the same way the other date objects are handled and outputs it in the correct default format. This conditional is only added if we are net60 or later.
For issue #19728 
```
```  …

[csharp] Output DateOnly paramater in the correct default format (#19728)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java

PR to fix #18017. I'm curious if I could add string to this same set? I noticed it also does not obey the "nullable: true" property. It does work in the AspNetCore codegen however.
```
```  …

[csharp] Make DateOnly nullable in the CSharpClientCodegen

---

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/modelbase-header.mustache
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/ModelBase.h

Fix #19566 implemented missing definitions of declared methods inside [modelbase-header.mustache](modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/modelbase-header.mustache) for the cpp-rest-sdk-client
I have also added two missing body of methods definitions
```
```  …

Implemented missing definitions of declared methods inside modelbase-header.mustache, added two missing body of methods definitions

---

modules/openapi-generator/src/main/resources/erlang-server/api.mustache
modules/openapi-generator/src/main/resources/erlang-server/handler.mustache
modules/openapi-generator/src/main/resources/erlang-server/logic_handler.mustache
modules/openapi-generator/src/main/resources/erlang-server/router.mustache
samples/server/echo_api/erlang-server/src/openapi_api.erl
samples/server/echo_api/erlang-server/src/openapi_auth_handler.erl
samples/server/echo_api/erlang-server/src/openapi_body_handler.erl
samples/server/echo_api/erlang-server/src/openapi_form_handler.erl
samples/server/echo_api/erlang-server/src/openapi_header_handler.erl
samples/server/echo_api/erlang-server/src/openapi_logic_handler.erl
samples/server/echo_api/erlang-server/src/openapi_path_handler.erl
samples/server/echo_api/erlang-server/src/openapi_query_handler.erl
samples/server/echo_api/erlang-server/src/openapi_router.erl
samples/server/petstore/erlang-server/src/openapi_api.erl
samples/server/petstore/erlang-server/src/openapi_logic_handler.erl
samples/server/petstore/erlang-server/src/openapi_pet_handler.erl
samples/server/petstore/erlang-server/src/openapi_router.erl
samples/server/petstore/erlang-server/src/openapi_store_handler.erl
samples/server/petstore/erlang-server/src/openapi_user_handler.erl

1. There was a risk of mixing identifiers in PascalCase and camelCase, which could make some rules not match when they should have.
2. Schemas would always be json-verified even when the mime-type defined was not in json. Enforce this correctly.
3. Also added more type information to help a type checker with ensuring we're handling the right cases.
4. Added a bit more erlang internal documentation to help with exploring a generated file.
```
``` 
These must …

[Erlang Server] Add more type information and fix minor bugs

---

modules/openapi-generator/src/main/resources/swift6/APIs.mustache
modules/openapi-generator/src/main/resources/swift6/libraries/alamofire/AlamofireImplementations.mustache
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/APIs.swift
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/AlamofireImplementations.swift
samples/client/petstore/swift6/alamofireLibrary/SwaggerClientTests/SwaggerClient.xcodeproj/project.pbxproj
samples/client/petstore/swift6/alamofireLibrary/SwaggerClientTests/SwaggerClient/AppDelegate.swift
samples/client/petstore/swift6/alamofireLibrary/SwaggerClientTests/SwaggerClient/BearerTokenHandler.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/APIs.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/AlamofireImplementations.swift

With this change, in swift6, while using alamofire, it's possible to intercept the request without make any subclass of the open api generated code.
```
```  …

[swift6] alamofire interceptor

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
modules/openapi-generator/src/main/resources/python/rest.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api_client.py
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/rest.py
samples/client/echo_api/python/openapi_client/api_client.py
samples/client/echo_api/python/openapi_client/rest.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/rest.py
samples/openapi3/client/petstore/python/tests/test_deserialization.py

This PR updates the Python client to handle content types with the `text/` prefix, ensuring they are parsed as regular strings.
Issue: https://github.com/OpenAPITools/openapi-generator/issues/19190
Cc. @cbornet @tomplus @krjakbrjak @fa0311 @multani
```
```  …

[Python][Client] Allow all content-types with `text/` prefix

---

modules/openapi-generator/src/main/resources/Java/libraries/restclient/ApiClient.mustache
samples/client/echo_api/java/restclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/restclient-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/typescript/builds/enum-single-value/index.ts
samples/client/petstore/java/restclient-nullable-arrays/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-useSingleRequestParameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient/src/main/java/org/openapitools/client/ApiClient.java

**Description:**
The changes fix the ApiClient mustache template for java RestClient generator. Some of the constructors didn't properly pass the ObjectMapper parameter on, leading to creating default mapper even if the consumer passed custom instance.
Additionally, PR refactors the ApiClient constructors in order to move the creation logic to the one, most specific, constructor.
The pr fixes #19667
Technical committee Java:
@martin-mfg, @lwlee2608, @Zomzog, @karismann, @jeff9finger, @cbornet, @lukoyanov, @jfiala, @sreeshas, @bbdouglas
```
```  …

Fix java rest client ApiClient template to properly assign ObjectMapper

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/K6ClientCodegen.java

This PR removes the `calculateRequestOrder` function. The previous function was deemed unnecessary due to its redundant logic and lack of unique functionality.
- Removed function
- Removed call to `calculateRequestOrder` function, which calculated the order of requests based on `operationGroupingOrder` and `requestsSize`.
- Updated request creation logic:
- Changed request creation logic to use `requests.size()` as the key in `requests.putIfAbsent()`, ensuring that each new request is added with a unique identifier based on the current size of the request map.
- The original implementation included unnecessary complexity that generated a bug that only generated 2 operations if they were on the same path.
- All existing tests have been run to ensure that no functionality has been affected …

Remove calculateRequestOrder Function and fix bug

---

modules/openapi-generator/src/main/resources/python/model_generic.mustache
samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/map_test.py
samples/openapi3/client/petstore/python/petstore_api/models/map_test.py

```
``` 
This PR solves issue #19274 by checking the input type on enum validators. The current …

[python] Check if the given input is a container (Array or Map) when validating enum values

---

modules/openapi-generator/src/main/resources/JavaSpring/javaBuilder.mustache
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/Bar.java
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/BarCreate.java
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/BarRef.java
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/Foo.java
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/FooRef.java
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/Pasta.java
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/Pizza.java
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/model/PizzaSpeziale.java
samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/BigCat.java
samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/Cat.java
samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/ChildWithNullable.java
samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/Dog.java

Related issue: #19425 
contains example OpenAPI file and describes the problem 
```
```  …

[Java Spring] Fix copyOf inheritance using empty object instead of passed value

---

modules/openapi-generator/src/main/resources/swift6/libraries/urlsession/URLSessionImplementations.mustache
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift

This PR simplifies the authentication process in the swift generator.
When I introduced the URLSession integration, I made it over configurable, and a bit complex.
This is a step into making it simpler.
Also I suspect that no one is using this advanced configuration.
In the future, if someone need this, we can make this available again and simpler to use.
```
```  …

[swift6] simplify authentication

---

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net6/ParameterMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/UseDateTimeForDate/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs

See issue #19525 
- Non-async overload of `Deserialize` is obsolete, RestSharp suggests using async overload of `Deserialize` instead.
```
```  …

[csharp] Address obsolete build warnings in ApiClient

---

modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache
samples/server/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/api/UserApi.kt

The @RestController annotation is not suitable if the spring-cloud library with the feign client is used.
See discussion at https://github.com/OpenAPITools/openapi-generator/issues/19156#issuecomment-2414193210 
```
``` 
IMPORTANT: …

[kotlin-spring] fix Api Interface for kotlin-spring with spring-cloud library

---

modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache

Previously, if an operation had a 'servers' block, the template would emit code requiring a `serverConf` local variable. Unfortunately, the template would not emit this variable, because it was looking for a `servers` variable in the wrong context.
This change makes the template emit an anonymous block containing a unique server configuration for each operation.
I did not test this change beyond a simple code inspection, there are other problems with the code generator which prevent it from running on my API definition.
To reproduce the original issue, install QT build dependencies, then:
* go to https://lichess.org/api, click the "Download" link, save `openapi.json` somewhere
* `java -jar target/openapi-generator-cli.jar  generate -i /path/to/openapi.json -o /tmp/Lichess -g …

Fix missing serverConf variable

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
modules/openapi-generator/src/main/resources/typescript-nestjs/configuration.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/configuration.ts

Closes #19741 
```
``` 
TypeScript committee members: @TiFu (2017/07) @taxpon (2017/07) …

Add httpClient config to typescript-nestjs generator

---

modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift

Type change in Alamofire 5.10 caused unintended recursive call.
This change adds a type cast to force the correct function call signature.
- [x ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
```
``` 
- [x ] File the PR against the [correct …

[swift5] fix compile error from Alamofire 5.10 - cast Parameter type to avoid recursion

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/issue_19895.yaml

Pr aims to fix an issue in the java feign generator in which the Content-type and Accept header values were incorrectly generated since it escaped some of the characters, i.e. equal sign.
It causes the specific media types (i.e. `application/json;charset=utf-8`) to be converted into the escaped version of that media type, leading to the incorrect headers being provided in the generated API.
fixes #19895 
Technical committee Java:
@martin-mfg, @lwlee2608, @Zomzog, @karismann, @jeff9finger, @cbornet, @lukoyanov, @jfiala, @sreeshas, @bbdouglas
```
``` 
This is important, as CI …

[BUG][java] Fix java feign client to use unescaped media type (#19895)

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/auth/OAuth.mustache
samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/auth/OAuth.java

Fix javadoc issue (incorrect parameter name) in resttemplate OAuth class
```
``` 

[java] Fix javadoc in resttemplate OAuth class

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-ktor/api.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-restclient/api.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-webclient/api.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-vertx/api.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinClientCodegenApiTest.java
modules/openapi-generator/src/test/resources/3_0/kotlin/issue19930-path-escaping.json

Pr aims to fix an issue when path variable was incorrectly escaped during generation of kotlin client apis. It led to the situation where single quotes were escaped, resulting in invalid code being generated.
Fixes #19930 
Technical Kotlin Committee:
@dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier @e5l
```
```  …

[BUG][KOTLIN] Fix the path variable escaping in kotlin client generators 

---

docs/generators/kotlin.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_opt_var.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_req_var.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinClientCodegenModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinModelCodegenTest.java
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiAnnotation.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiApiResponse.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiCategory.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiOrder.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiPet.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiTag.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiUser.kt

As requested in issue https://github.com/OpenAPITools/openapi-generator/issues/17544 added support for `x-field-extra-annotation` to the Kotlin generator. To be consistent also added support for `x-class-extra-annotation` annotation.
Resolves https://github.com/OpenAPITools/openapi-generator/issues/17544
```
```  …

[REQ] resolve #17544 Add x-field-extra-annotation and x-class-extra-annotation for kotlin generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java

This fixes generation of a Rust library for OpenAPI specifications where `info.version` was a single-digit number. This happened to for [this](https://github.com/motis-project/motis/blob/db005f2e55812b8231e2e2dbac4d3abf711a8610/openapi.yaml#L10) specification. The fix for this issue is similar to the one in !17440.
The error of Rust generates for this is:
```
error: unexpected end of input while parsing major version number
--> Cargo.toml:3:11
|
3 | version = "1"
|           ^^^
|
```
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD …

Fix Rust generation for versions without minor or patch parts

---

modules/openapi-generator/src/main/resources/Java/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/build.gradle.mustache
samples/client/echo_api/java/native/build.gradle
samples/client/petstore/java/native-async/build.gradle
samples/client/petstore/java/native-jakarta/build.gradle
samples/client/petstore/java/native/build.gradle

If i generate a client for java with the library native, i get the following error when i try to build the client via `./gradlew assemble`.
```
/build.gradle' line: 53
Could not set unknown property 'classifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.
```
This error can also be reproduced if you use the native Java echo_api client sample.
According to the gradle documentation, the `classifier` property was removed with the update to Gradle 8.x
See: https://docs.gradle.org/current/userguide/upgrading_version_7.html#abstractarchivetask_api_cleanup
@bbdouglas @Zomzog @lwlee2608 @martin-mfg
```
```  …

[JAVA]: Fix unknown property error for gradle build

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_1/unsupported_schema_test.yaml

- Better handling of allOf with unsupported schemas such as if, then, etc
- Add tests
```
```  …

Better handling of allOf with unsupported schemas

---

modules/openapi-generator/src/main/resources/Java/pojo.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/apachehttpclient/ApacheHttpClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/unique-items-string-enum.yaml

Fixes #19957
See the mentioned issue for more details on issue reproduction/validation. I changed the pojo.mustache file to use {{datatypeWithEnum}} instead of {{dataType}} and added a test.
```
```  …

[java] Fix generation of POJOs with sets of enums

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java

Fixes https://github.com/OpenAPITools/openapi-generator/issues/19924
@joscha Pinging author of these tests for awareness
Here are the logs produced by ./mvnw clean package
[ERROR] Failures:
[ERROR] org.openapitools.codegen.DefaultCodegenTest.testExecutePostProcessor
[ERROR]   Run 1: DefaultCodegenTest.testExecutePostProcessor:755 expected [true] but found [false]
[ERROR]   Run 2: DefaultCodegenTest.testExecutePostProcessor:755 expected [true] but found [false]
[ERROR]   Run 3: DefaultCodegenTest.testExecutePostProcessor:755 expected [true] but found [false]
[INFO]
[INFO]
[ERROR] Tests run: 3214, Failures: 1, Errors: 0, Skipped: 4
```
``` 
(For Windows users, please run the script in …

Fix test on Windows

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml
samples/client/petstore/java/okhttp-gson/api/openapi.yaml
samples/client/petstore/java/okhttp-gson/docs/NewPet.md
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/NewPet.java

To fix https://github.com/OpenAPITools/openapi-generator/issues/17534, https://github.com/OpenAPITools/openapi-generator/issues/19900
Add tests
```
```  …

Fix $ref to allOf in properties

---

modules/openapi-generator/src/main/resources/kotlin-client/anyof_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/oneof_class.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/ClientLibrary.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinClientCodegenApiTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinClientCodegenModelTest.java
modules/openapi-generator/src/test/resources/3_0/issue_19942.json
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiAnyOfUserOrPet.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiAnyOfUserOrPetOrArrayString.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiUserOrPet.kt
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiUserOrPetOrArrayString.kt

Pr introduces sanitizing of the adapter... names in the oneOf and anyOf model templates in order to avoid incorrect names being generated. 
The root cause of this issue comes from the fact that Kotlin generator uses canonical names for type mappings and thus {{dataType}} variable is a canonical name with dots. It is then used for variable names generation.
Sanitizing of the names will be enough to fix #19942 but the type mappings problem should also be addressed imo. 
It seems that other generators (i.e. java) are not having this issue.
During the preparation of this fix, I also realized that `validateJsonElement` methods are also missing in oneOf and anyOf classes, which would also cause the compilation errors. I fixed this issue as well in the scope of this pr.
Technical Kotlin …

[BUG][KOTLIN] Sanitize names of the adapter variables in anyOf and oneOf model template to avoid compilation errors

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml
modules/openapi-generator/src/test/resources/3_1/common-parameters.yaml

- Update inline model resolver to flatten responses
- Add tests
- Fix https://github.com/OpenAPITools/openapi-generator/issues/19982
```
```  …

Update inline model resolver to flatten responses

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java

The api.mustache template only uses the reflect package if there is a query parameter which `isCollectionFormatMulti`. The import for the reflect package is however added if _any_ parameter is `isCollectionFormatMulti`.
If the parameter which `isCollectionFormatMulti` e.g. is in the body instead of the query, this leads to the import being part of the generated code but not used and the code does not compile.
This updates reworks the import handling for the `reflect` package so that it is only added if there is a query parameter which `isCollectionFormatMulti`.
```
./mvnw clean package && \
./bin/generate-samples.sh ./bin/configs/*.yaml && \
```  …

[BUG][GO] only import `reflect` when using it

---

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
samples/client/echo_api/csharp-restsharp/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net6/ParameterMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net7/UseDateTimeForDate/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs

The generated code of Csharp get a fully quallify namespace for PATH
using Path = global::System.IO.Path;
```
```  …

[csharp] Mustache fully qualify namespace for Path

---

docs/faq-generators.md
modules/openapi-generator/src/main/resources/swift6/libraries/urlsession/URLSessionImplementations.mustache
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/urlsessionLibrary/SwaggerClientTests/SwaggerClient/BearerTokenHandler.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift

Swift 6 improve retry interceptor to fix https://github.com/OpenAPITools/openapi-generator/issues/19939
```
```  …

[swift6] improve retry interceptor

---

modules/openapi-generator/src/main/resources/Java/libraries/restclient/auth/OAuth.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
samples/client/petstore/java/restclient-swagger2/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/restclient-useSingleRequestParameter/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/restclient/src/main/java/org/openapitools/client/auth/OAuth.java

Fixes OpenAPITools#19943
Add support for a token supplier to OAuth based RestClient clients
```
```  …

[java] [restclient] Add support for a token supplier to OAuth based RestClient clients

---

docs/generators/javascript.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java
modules/openapi-generator/src/main/resources/Javascript/libraries/javascript/ApiClient.mustache

Fixes #19947 
- Added a new parameter 'useURLSearchParams' to the JavaScript Client Codegen
- If set to true, the deprecated npm ['querystring'](https://www.npmjs.com/package/querystring) is not generated anymore in the javascript code. Instead we use [UrlSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), which is a built-in function of javascript.
- If set to false, the old behavior is still generated.
- Default value is 'false'
Additional tests:
- manual testing with openapi-generator-cli additional properties and configuration file
```
```  …

[#19947] add parameter 'useURLSearchParams' to use JS build-in UrlSearchParams, instead of deprecated npm lib 'querystring'

---

modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache
samples/client/petstore/cpp-qt-addDownloadProgress/client/PFXUserApi.cpp
samples/client/petstore/cpp-qt/client/PFXUserApi.cpp

QUrl::toPercentEncoding accepts only QString type, but we pass any primitive type to him
It's fix for [issue 20001](https://github.com/OpenAPITools/openapi-generator/issues/20001)
1. mark non string property as required in openapi file
2. generate client
3. try build it
4. build must pass without any error messages
```
```  …

feat cpp-qt-client: fix cast primitive to string

---

modules/openapi-generator/src/main/resources/swift6/api.mustache
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/APIs/FakeAPI.swift
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/APIs/PetAPI.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/APIs/FakeAPI.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/APIs/PetAPI.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/APIs/FakeAPI.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/APIs/PetAPI.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/APIs/FakeAPI.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/APIs/PetAPI.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/APIs/FakeAPI.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/APIs/PetAPI.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/APIs/FakeAPI.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/APIs/PetAPI.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/APIs/FakeAPI.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/APIs/PetAPI.swift
samples/client/petstore/swift6/vaporLibrary/Sources/PetstoreClient/APIs/FakeAPI.swift
samples/client/petstore/swift6/vaporLibrary/Sources/PetstoreClient/APIs/PetAPI.swift

Continuation of #20013. I missed a place where enums are generated which can always conform to `Sendable`.
```
```  …

[swift6] Add Sendable conformance to request parameter enums

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/CopyLambda.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/PasteLambda.java
modules/openapi-generator/src/main/resources/csharp/libraries/generichost/JsonConverter.mustache
modules/openapi-generator/src/main/resources/csharp/libraries/generichost/RateLimitProvider`1.mustache
modules/openapi-generator/src/main/resources/csharp/libraries/generichost/ValidateRegex.mustache
modules/openapi-generator/src/main/resources/csharp/libraries/generichost/WritePropertyHelper.mustache
modules/openapi-generator/src/main/resources/csharp/libraries/generichost/modelGeneric.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/mustache/CopyPasteLambdaTest.java

The copy lambda had a hard coded command that mutated the cached value. That was giving me an issue in another PR I'm working on. I removed that, and I also moved the white space handling from paste to copy. The reason for that change is that the way we handle white space will depend on how the copy is written. For example, these two will produce different results. Therefore, we should handle the white space correctly in the copy lambda where it occurs, not later in the paste.
```
{{#lambda.copy}}foo{{/lambda.copy}}
{{#lambda.copy}}
foo
{{/lambda.copy}}
```
```
``` 
This is …

Refactor copy lambda

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java

Fixes #20030 
Copied implementation from PythonClientCodegen.escapeReservedWord() to handle fields with reserved words in pydantic models.
I'm unsure whether to target master or a minor release branch even if this results in field renaming. Decided to go with master since affected models were inherently broken, and since python-fastapi is currently in beta. Please comment if you decide otherwise.
```
```  …

[BUG][python-fastapi] Copy escapeReservedWord implementation from python generator

---

bin/configs/typescript-consolidated-inversify.yaml
samples/openapi3/client/petstore/typescript/builds/inversify/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/inversify/apis/StoreApi.ts
samples/openapi3/client/petstore/typescript/builds/inversify/apis/UserApi.ts
samples/openapi3/client/petstore/typescript/builds/inversify/http/http.ts
samples/openapi3/client/petstore/typescript/builds/inversify/package.json
samples/openapi3/client/petstore/typescript/builds/inversify/tsconfig.json

On the current `master` branch, the "TypeScript clients type checks" check is failing with:
```
➤ samples/openapi3/client/petstore/typescript/builds/inversify
added 26 packages in 2s
Error: node_modules/@inversifyjs/common/lib/cjs/services/models/LazyServiceIdentifier.d.ts(4,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
Error: node_modules/@inversifyjs/core/lib/cjs/legacyTarget/models/LegacyTargetImpl.d.ts(10,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
Error: Process completed with exit code 2.
```
Let's enable `supportsES6` in the sample testing to get rid of the error.
There is https://github.com/OpenAPITools/openapi-generator/pull/16187 which will enable es6 across the board …

[typescript] fix Inversify type checks on CI

---

.github/workflows/samples-kotlin-server-jdk17.yaml
.github/workflows/samples-kotlin-server-jdk21.yaml
.github/workflows/samples-kotlin-server.yaml
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin5/build.gradle.kts.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/build.gradle.kts.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradle-sb3-Kts.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradleKts.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-cloud/buildGradle-sb3-Kts.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-cloud/buildGradleKts.mustache
samples/server/petstore/kotlin-server/javalin-6/build.gradle.kts
samples/server/petstore/kotlin-server/javalin/build.gradle.kts
samples/server/petstore/kotlin-spring-cloud/build.gradle.kts
samples/server/petstore/kotlin-spring-default/build.gradle.kts
samples/server/petstore/kotlin-springboot-3/build.gradle.kts
samples/server/petstore/kotlin-springboot-bigdecimal-default/build.gradle.kts
samples/server/petstore/kotlin-springboot-delegate-nodefaults/build.gradle.kts
samples/server/petstore/kotlin-springboot-delegate/build.gradle.kts
samples/server/petstore/kotlin-springboot-integer-enum/build.gradle.kts
samples/server/petstore/kotlin-springboot-modelMutable/build.gradle.kts
samples/server/petstore/kotlin-springboot-multipart-request-model/build.gradle.kts
samples/server/petstore/kotlin-springboot-reactive/build.gradle.kts
samples/server/petstore/kotlin-springboot-request-cookie/build.gradle.kts
samples/server/petstore/kotlin-springboot-source-swagger1/build.gradle.kts
samples/server/petstore/kotlin-springboot-source-swagger2/build.gradle.kts
samples/server/petstore/kotlin-springboot-springfox/build.gradle.kts
samples/server/petstore/kotlin-springboot/build.gradle.kts

In https://github.com/OpenAPITools/openapi-generator/commit/3240c5baf0ba11d4a0408fb742d218ad4d694632, @wing328 bumped the version of `org.springdoc:springdoc-openapi-starter-webmvc-ui` to `2.6.0` for the `kotlin-springboot-request-cookie` sample.
In [this PR](https://github.com/OpenAPITools/openapi-generator/pull/20054), the tests for said sample are now failing with:
```
e: /home/runner/.gradle/caches/modules-2/files-2.1/org.springdoc/springdoc-openapi-starter-common/2.6.0/c8cf5fbd1f9e4c410d67f1de27dfc3529de13620/springdoc-openapi-starter-common-2.6.0.jar!/META-INF/springdoc-openapi-starter-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
```
Let's bump the Kotlin versions in the …

[kotlin-server] Bump Kotlin/Gradle versions and improve CI triggers/config

---

modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache
modules/openapi-generator/src/main/resources/csharp-functions/modelGeneric.mustache
modules/openapi-generator/src/main/resources/csharp/modelGeneric.mustache
samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Model/Cat.cs
samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Model/ChildCat.cs
samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Model/Dog.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Model/Cat.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Model/ChildCat.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Model/Dog.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Model/Cat.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Model/ChildCat.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Model/Dog.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/Cat.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/ChildCat.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Model/Dog.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/Cat.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/ChildCat.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Model/Dog.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Model/Cat.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Model/ChildCat.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Model/Dog.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Model/Cat.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Model/ChildCat.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Model/Dog.cs

This fixes the issue mentioned in https://github.com/OpenAPITools/openapi-generator/issues/17990.
The change was tested and applied using template overrides in the modelGeneric scenario. I updated all other references to this attribute as it should be causing the same issue.
```
```  …

fix(csharp): Fixed JsonConverter for discriminators only appearing on base classes

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/DartClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/php/AbstractPhpCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
samples/client/echo_api/php-nextgen-streaming/docs/Api/BodyApi.md
samples/client/echo_api/php-nextgen-streaming/docs/Api/QueryApi.md
samples/client/echo_api/php-nextgen/docs/Api/BodyApi.md
samples/client/echo_api/php-nextgen/docs/Api/QueryApi.md
samples/client/petstore/php-nextgen/OpenAPIClient-php/docs/Api/FakeApi.md
samples/client/petstore/php-nextgen/OpenAPIClient-php/docs/Api/PetApi.md
samples/client/petstore/php/OpenAPIClient-php/docs/Api/FakeApi.md
samples/client/petstore/php/OpenAPIClient-php/docs/Api/PetApi.md
samples/client/petstore/php/psr-18/docs/Api/FakeApi.md
samples/client/petstore/php/psr-18/docs/Api/PetApi.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/PetController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/EnumStringModel.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Order.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Pet.php

This PR fixes #17582 by correctly escaping strings inside the single quotes for the PHP, Dart and Python generators.
For the PHP generator, double quotes escaped by the default generator are unescaped because PHP treats `'\"'` as a string containing a backslash and a double quote.
I have verified that python and dart treat `'\"'` as a string containing just a double quote character.
```
``` 
You …

[PHP/Dart/Python] Correctly escape strings in single quotes (Fixes #17582)

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/echo_api/java/okhttp-gson-user-defined-templates/src/main/java/org/openapitools/client/ApiClient.java
samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-oneOf-array/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-oneOf/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

a follow-up PR to #19226
```
``` 

Suppress the cast warning in java okhttp-gson client

---

modules/openapi-generator/src/main/resources/dart2/api_helper.mustache
samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api_helper.dart
samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api_helper.dart

fix #15393 
This PR is part of the effort to split PR #17548 
Adds a special case for handling deserialization of non-explicit doubles.
e.g, given the definition:
```yaml
double_obj:
properties:
dfield:
type: number
format: double      
```
Then sending `{dfield: 2.4}` will deserialize correctly, but `{dfield: 2}` will be cast as an int an fail the object parse.

 [dart2] [client] Added better double handling to 'mapValueOfType<T>'

---

modules/openapi-generator/src/main/resources/erlang-server/logic_handler.mustache
samples/server/echo_api/erlang-server/src/openapi_logic_handler.erl
samples/server/petstore/erlang-server/src/openapi_logic_handler.erl

I'm afraid I forgot in the previous https://github.com/OpenAPITools/openapi-generator/pull/20087 to export the newly created type. It should all be correct now 🥲 
```
```  …

erlang-server: Extend provided return and make the type available

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/allOf_extension_parent.yaml

Fix allOf with properties for the REF_AS_PARENT_IN_ALLOF rule

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustAxumServerCodegen.java
modules/openapi-generator/src/main/resources/rust-axum/Cargo.mustache
modules/openapi-generator/src/main/resources/rust-axum/apis-mod.mustache
modules/openapi-generator/src/main/resources/rust-axum/apis.mustache
modules/openapi-generator/src/main/resources/rust-axum/server-operation.mustache
modules/openapi-generator/src/main/resources/rust-axum/server-route.mustache
samples/server/petstore/rust-axum/output/apikey-auths/Cargo.toml
samples/server/petstore/rust-axum/output/apikey-auths/src/apis/mod.rs
samples/server/petstore/rust-axum/output/apikey-auths/src/apis/payments.rs
samples/server/petstore/rust-axum/output/apikey-auths/src/server/mod.rs
samples/server/petstore/rust-axum/output/multipart-v3/Cargo.toml
samples/server/petstore/rust-axum/output/openapi-v3/Cargo.toml
samples/server/petstore/rust-axum/output/ops-v3/Cargo.toml
samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml
samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/apis/mod.rs
samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/apis/pet.rs
samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/apis/store.rs
samples/server/petstore/rust-axum/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
samples/server/petstore/rust-axum/output/petstore/Cargo.toml
samples/server/petstore/rust-axum/output/petstore/src/apis/mod.rs
samples/server/petstore/rust-axum/output/petstore/src/apis/pet.rs
samples/server/petstore/rust-axum/output/petstore/src/apis/store.rs
samples/server/petstore/rust-axum/output/petstore/src/apis/user.rs
samples/server/petstore/rust-axum/output/petstore/src/server/mod.rs
samples/server/petstore/rust-axum/output/ping-bearer-auth/Cargo.toml
samples/server/petstore/rust-axum/output/rust-axum-header-uuid/Cargo.toml
samples/server/petstore/rust-axum/output/rust-axum-test/Cargo.toml
samples/server/petstore/rust-axum/output/rust-axum-validation-test/Cargo.toml

This PR helps handling Authentication via [API key](https://swagger.io/docs/specification/authentication/api-keys/) (in Header and in Cookie). Extracted Claims are now sent to all Operations
Integration tests passed:
```bash
mvn clean && ./bin/generate-samples.sh bin/configs/manual/rust-axum-* && mvn integration-test -f samples/server/petstore/rust-axum/pom.xml
```
```
```  …

[Rust-Axum][Breaking Changes] Extracting Claims in Cookie/Header

---

modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/Order.kt
samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/Pet.kt

This PR fixes two issues for explicit generation of KSerializer for enums (with auto unknown case):
- KSerializer's name - the referencing side was ok, but the referenced side was using the wrong variable (output shows the change)
- When the enum was a part of the container, the KSerializer was generated incorrectly (non-compiling). I copied the pattern from line 123 and it works flawlessly now. I am unable to show it in the generated code without changing pets schema.
@e5l
THIS IS FOLLOW UP FOR #20092
Example of the second issue:
Before:
```kotlin
@Serializable
data class CreatorFanclubPutRequestBodyDto (
@SerialName(value = "creator_fanclub_types")
val creatorFanclubTypes: kotlin.collections.List<CreatorFanclubPutRequestBodyDto.CreatorFanclubTypes>
) {
@Serializable(with = …
```

Fix explicit KSerializer's name & generation when used in container

---

modules/openapi-generator/src/main/resources/erlang-server/app.src.mustache
modules/openapi-generator/src/main/resources/erlang-server/rebar.config.mustache
samples/server/echo_api/erlang-server/rebar.config
samples/server/echo_api/erlang-server/src/openapi.app.src
samples/server/petstore/erlang-server/rebar.config
samples/server/petstore/erlang-server/src/openapi.app.src

Adding jesse to the release app.up specs. This should have popped up in a more barebones project but I'd previously tested this in much bigger projects where someone else was already using jesse as a dependency and therefore code passed correctly. Now going on with something smaller: https://github.com/esl/amoc-arsenal/pull/5 :)
```
```  …

erlang-server: add jesse to app.up release

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/JSON.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/JSON.mustache
samples/client/others/java/jersey2-oneOf-Mixed/src/main/java/org/openapitools/client/JSON.java
samples/client/others/java/jersey2-oneOf-duplicates/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/jersey3-oneOf/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/JSON.java
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/JSON.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/JSON.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/JSON.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java

Fixes #20125
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala …

[#20125] Remove unnecessary model package import to avoid ambiguous class references

---

modules/openapi-generator/src/main/resources/Java/libraries/restclient/ApiClient.mustache
samples/client/echo_api/java/restclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/restclient-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-nullable-arrays/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-useSingleRequestParameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient/src/main/java/org/openapitools/client/ApiClient.java

Insert custom converter at the beginning of the `RestClientBuilder` converter list so as not to use default `MappingJackson2HttpMessageConverter`
See #20111

fixes(java/restclient) Force usage of custom converter

---

modules/openapi-generator/src/main/resources/swift6/Models.mustache
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/Models.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift

NullEncodable currently assumes that all usages conform to Hashable. This could lead to compilation errors in the generated code.
```
``` 
IMPORTANT: Do …

[swift6] Add conditional Hashable conformance to NullEncodable

---

modules/openapi-generator/src/main/resources/swift6/Validation.mustache
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/Validation.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/vaporLibrary/Sources/PetstoreClient/Infrastructure/Validation.swift

This is a slight correctness improvement, by replacing `@unchecked Sendable` with compiler-checked `Sendable`.
```
```  …

[swift6] Add checked Sendable conformance to Validation structs

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiResponse.kt.mustache
samples/client/others/kotlin-jvm-okhttp-parameter-tests/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-explicit/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-name-parameter-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiResponse.kt

See: https://github.com/OpenAPITools/openapi-generator/issues/20160
```
```  …

Added default headers to `ServerError<T>` for Kotlin OkHTTP generator

---

modules/openapi-generator/src/main/resources/elm/operation.mustache
samples/client/petstore/elm/src/Api/Request/Pet.elm
samples/client/petstore/elm/src/Api/Request/Store.elm
samples/client/petstore/elm/src/Api/Request/User.elm
samples/openapi3/client/elm/src/Api/Request/Default.elm
samples/openapi3/client/elm/src/Api/Request/Primitive.elm

We currently only print the notes in a doc comment if they exist. This PR fixes so both the summary and notes are printed as expected.
```
```  …

[Elm] Add missing operation summary

---

.github/workflows/samples-php8.yaml
modules/openapi-generator/src/main/resources/php-symfony/Controller.mustache
modules/openapi-generator/src/main/resources/php-symfony/model_generic.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/Controller.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/ApiResponse.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Category.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Order.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Pet.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Tag.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Model/User.php

```
``` 
add PHP 8.4 support
https://www.php.net/releases/8.4/en.php
In …

PHP8.4 comptible, php-symfony resources

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/issue_19393_map_of_inner_enum.yaml

[Java] Fix compilation error for a Map<String, Set<InnerEnum>> due to incompatible types

---

modules/openapi-generator/src/main/resources/swift6/Models.mustache
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/Models.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/Models.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/Models.swift

This PR changes the Response open class to a struct. This is a breaking change, but I think there's a lot of benefits to not allowing Response to be overridden. The primary benefit is conformance to Sendable, which is important for Swift 6 specifically.
```
```  …

[swift6] Change Response to struct

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api_client.py
samples/client/echo_api/python/openapi_client/api_client.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/tests/test_api_client.py
samples/openapi3/client/petstore/python/tests/test_api_validation.py

[python] Encode list query params

---

.github/workflows/samples-elm.yaml

The find command that tries to find all elm files didn't have quotes around the pattern, which meant that it only found the .elm files in the current folder and only tried to compile that.
```
``` 
IMPORTANT: …

[Elm] Fix not compiling all elm files in test suite

---

modules/openapi-generator/src/main/resources/erlang-server/api.mustache
modules/openapi-generator/src/main/resources/erlang-server/app.src.mustache
modules/openapi-generator/src/main/resources/erlang-server/logic_handler.mustache
modules/openapi-generator/src/main/resources/erlang-server/rebar.config.mustache
samples/server/echo_api/erlang-server/rebar.config
samples/server/echo_api/erlang-server/src/openapi.app.src
samples/server/echo_api/erlang-server/src/openapi_api.erl
samples/server/echo_api/erlang-server/src/openapi_logic_handler.erl
samples/server/petstore/erlang-server/rebar.config
samples/server/petstore/erlang-server/src/openapi.app.src
samples/server/petstore/erlang-server/src/openapi_api.erl
samples/server/petstore/erlang-server/src/openapi_logic_handler.erl

Just generating the right link for the doc generator and the type checker.
```
```  …

Erlang server – minor fix to return type and generated doc

---

modules/openapi-generator/src/test/resources/2_0/c/petstore.yaml
samples/client/others/go/oneof-anyof-required/model_object2.go
samples/client/petstore/c-useJsonUnformatted/.openapi-generator/FILES
samples/client/petstore/c-useJsonUnformatted/CMakeLists.txt
samples/client/petstore/c-useJsonUnformatted/README.md
samples/client/petstore/c-useJsonUnformatted/api/PetAPI.c
samples/client/petstore/c-useJsonUnformatted/api/PetAPI.h
samples/client/petstore/c-useJsonUnformatted/docs/PetAPI.md
samples/client/petstore/c-useJsonUnformatted/docs/preference.md
samples/client/petstore/c-useJsonUnformatted/docs/user.md
samples/client/petstore/c-useJsonUnformatted/model/preference.c
samples/client/petstore/c-useJsonUnformatted/model/preference.h
samples/client/petstore/c-useJsonUnformatted/model/user.c
samples/client/petstore/c-useJsonUnformatted/model/user.h
samples/client/petstore/c-useJsonUnformatted/unit-test/test_preference.c
samples/client/petstore/c/.openapi-generator/FILES
samples/client/petstore/c/README.md
samples/client/petstore/c/api/PetAPI.c
samples/client/petstore/c/api/PetAPI.h
samples/client/petstore/c/docs/PetAPI.md
samples/client/petstore/c/docs/preference.md
samples/client/petstore/c/docs/user.md
samples/client/petstore/c/model/preference.c
samples/client/petstore/c/model/preference.h
samples/client/petstore/c/model/user.c
samples/client/petstore/c/model/user.h
samples/client/petstore/c/unit-test/test_preference.c
samples/openapi3/client/elm/src/Api/Request/Default.elm

These are the updated test schemas for the recently merged C generator patches. As requested by @wing328 here:
https://github.com/OpenAPITools/openapi-generator/pull/14434#issuecomment-2497497110

Tests for recent C fixes

---

modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache
samples/client/others/typescript/builds/array-of-lists/models/ObjectSerializer.ts
samples/client/others/typescript/builds/enum-single-value/models/ObjectSerializer.ts
samples/client/others/typescript/builds/null-types-simple/models/ObjectSerializer.ts
samples/client/others/typescript/builds/with-unique-items/models/ObjectSerializer.ts
samples/client/others/typescript/encode-decode/build/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/browser/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/default/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/deno/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/deno_object_params/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/explode-query/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/inversify/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/jquery/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/nullable-enum/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/object_params/models/ObjectSerializer.ts

accessing `normalizeMediaType` should be done static in `ObjectSerializer`, as described in https://github.com/OpenAPITools/openapi-generator/issues/20201.
fix applies only to the `typescript` generator.
closes #20201 if accepted as solution by maintainers.
```
```  …

static access to normalizeMediaType in typescript object serializer

---

modules/openapi-generator/src/main/resources/rust/Cargo.mustache

This closes the quotes properly in the generated Cargo.toml manifest for the rust generator
```
```  …

fix: close quotes in cargo manifest

---

modules/openapi-generator/src/main/resources/python-flask/controller.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonFlaskConnexionServerCodegenTest.java
modules/openapi-generator/src/test/resources/bugs/issue_1666.yaml
samples/server/petstore/python-flask/openapi_server/controllers/pet_controller.py
samples/server/petstore/python-flask/openapi_server/controllers/store_controller.py
samples/server/petstore/python-flask/openapi_server/controllers/user_controller.py

fix #1666
Since Connexion defaults to using 'body' as the argument name for the requestBody, the controller's argument name is adjusted accordingly.
```
```  …

[python-flask] Change requestBody argument name to 'body' in controllers

---

modules/openapi-generator/src/main/resources/typescript/http/http.mustache
samples/client/others/typescript/encode-decode/build/http/http.ts
samples/openapi3/client/petstore/typescript/builds/default/http/http.ts
samples/openapi3/client/petstore/typescript/builds/explode-query/http/http.ts
samples/openapi3/client/petstore/typescript/builds/inversify/http/http.ts
samples/openapi3/client/petstore/typescript/builds/object_params/http/http.ts

url, http, and https are Node.js core modules, and form-data should be loaded using a bare specifier. This commit removes the file extensions from these imports.
```
```  …

fix(typescript): remove incorrect file extensions

---

modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/Serializer.kt.mustache
samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt

fix: register gson CustomTypeAdapterFactory in kotlin-client if generateOneOfAnyOfWrappers enabled

---

modules/openapi-generator/src/main/resources/elixir/request_builder.ex.mustache
samples/client/petstore/elixir/lib/openapi_petstore/request_builder.ex

The spec for `RequestBuilder.evaluate_response/2` does not allow for lists of structs to be returned. This is incorrect as `Deserializer.to_struct/2` can return a list of structs that gets passed up through to the generated api functions.
This PR updates the `RequestBuilder.evaluate_response/2` spec to correctly reflect the behavior of the function return values.
```
```  …

[elixir] Update dialyzer spec

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
samples/client/others/kotlin-jvm-okhttp-parameter-tests/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-explicit/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-name-parameter-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

[kotlin][client] support text/plain in okhttp

---

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/model-header.mustache
modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/model-source.mustache
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/ApiResponse.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Category.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Order.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Pet.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/SchemaWithSet.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/SchemaWithSet_vaccinationBook.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Tag.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/User.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Vaccine.h
samples/client/petstore/cpp-restsdk/client/src/model/ApiResponse.cpp
samples/client/petstore/cpp-restsdk/client/src/model/Category.cpp
samples/client/petstore/cpp-restsdk/client/src/model/CreateUserOrPet_request.cpp
samples/client/petstore/cpp-restsdk/client/src/model/Order.cpp
samples/client/petstore/cpp-restsdk/client/src/model/Pet.cpp
samples/client/petstore/cpp-restsdk/client/src/model/SchemaWithSet.cpp
samples/client/petstore/cpp-restsdk/client/src/model/SchemaWithSet_vaccinationBook.cpp
samples/client/petstore/cpp-restsdk/client/src/model/Tag.cpp
samples/client/petstore/cpp-restsdk/client/src/model/User.cpp
samples/client/petstore/cpp-restsdk/client/src/model/Vaccine.cpp

A follow-up PR to #19919
code looks more readable after the change, e.g.
- https://github.com/OpenAPITools/openapi-generator/blob/3c9e27555621eba797394c9a4aaf01768ab4d641/samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Pet.h
- https://github.com/OpenAPITools/openapi-generator/blob/3c9e27555621eba797394c9a4aaf01768ab4d641/samples/client/petstore/cpp-restsdk/client/src/model/Pet.cpp
```
``` 
These must …

[cpprestsdk] Better code format

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

Fix proposal for https://github.com/OpenAPITools/openapi-generator/issues/20239
Use `ref` field when filled in place of missing `name`:`in` to avoid collision onto generated id (when $ref is present, it generate systemically `null:null` ID)
So, with fix, in place of generating a missing parameter onto function prototype:
```java
public void get(Integer queryParameter) throws ApiException {
```
It now generated the correct list:
```java
public void get(String pathParameter, Integer queryParameter) throws ApiException {
```
```
./mvnw clean install
```

fix (DefaultGenerator): Handle "$ref" parameter reference to identify parameter ID (#20239)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java

This fixes an issue introduced in version 7.6.0. When using the ModelNamePrefix option with typescript-fetch, the given prefix is duplicated in import statements leading to compilation failure (see issue for how to reproduce). 
The root case is that the method `toModelFilename` that is adding prefix and suffix is called twice when generating the variables used to create import statements. 
Fixes https://github.com/OpenAPITools/openapi-generator/issues/19039
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit …

[typescript-fetch] [BUG] Fix duplication of ModelNamePrefix in import statements

---

docs/generators/kotlin.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/Java/libraries/feign/README.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
modules/openapi-generator/src/test/resources/3_0/tags.yaml
samples/client/echo_api/java/feign-gson/README.md
samples/client/others/kotlin-jvm-okhttp-parameter-tests/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/java/feign-no-nullable/README.md
samples/client/petstore/java/feign/README.md
samples/client/petstore/kotlin-allOff-discriminator/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-explicit/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-kotlinx-datetime/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-name-parameter-mappings/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

Fixes a typo in:
* a Kotlin generator constant
* docs, comments and strings in the Kotlin generator and other modules.
Attn Kotlin team: @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier @e5l
```
```  …

Fix typo "bellow"

---

modules/openapi-generator/src/main/resources/csharp/auth/OAuthAuthenticator.mustache
modules/openapi-generator/src/main/resources/csharp/auth/TokenResponse.mustache
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/Auth/TokenResponse.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/Auth/TokenResponse.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/Auth/TokenResponse.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs
samples/client/petstore/csharp/restsharp/net7/EnumMappings/src/Org.OpenAPITools/Client/Auth/TokenResponse.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs
samples/client/petstore/csharp/restsharp/net7/Petstore/src/Org.OpenAPITools/Client/Auth/TokenResponse.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/Auth/TokenResponse.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/Auth/OAuthAuthenticator.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/Auth/TokenResponse.cs

This adds a simple change to the AuthToken and TokenResponse code to allow for automatic refreshes. (I didn't test the refresh_token since I don't have one of those super handy).
Split off from #20233.
```
```  …

Add auth token refresh to csharp

---

docs/generators/scala-akka-http-server.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaHttpServerCodegen.java
modules/openapi-generator/src/main/resources/scala-akka-http-server/build.sbt.mustache
samples/server/petstore/scala-pekko-http-server/build.sbt

This change is a fix for Issue 20225 - Improve handling of pekko versions
https://github.com/OpenAPITools/openapi-generator/issues/20275
This change adds a new parameter for the `scala-akka-http-server` generator. The parameter is called `pekkoHttpVersion` and lets a user control the version of the `pekko-http` package in the same way you do for `akka-http` versions.
The change also increases the version of `pekko-stream` to `1.0.3`.
To validate the work in this PR, run the `scala-akka-http-generator`:
* Not using the `usePekkoHttp` flag should have the same bahavior as before
* `usePekkoHttp=true` should add pekko packages instead of akka packages just as before, but the `pekko-stream` package should now have version `1.0.3`. The version of `pekko-http` should still be `1.0.0` as long as …

Improve handling of pekko versions in scala-akka-http-server generator

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache
samples/client/petstore/java/resttemplate-jakarta/build.gradle

In the build.gradle template for the Java generator's resttemplate library, changed dependency to com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider instead of com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider when useJarkartaEe is enabled. This makes it consistent with the pom template file.
Related to #13124
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @martin-mfg
```
```  …

Depend on jackson-jakarta-rs-json-provider when useJakartaEe is true in build.gradle for Java resttemplate generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java

This PR normalizes path parameters by converting `-` to `_` to avoid compiler failures. 
See #20295 for more info.
Given a path with kebab cased path params `/pet/{pet-id}`
```rs
let local_var_uri_str = format!("{}/pet/{pet-id}", local_var_configuration.base_path, pet-id=pet_id);
// This does not compile
```
```rs
let local_var_uri_str = format!("{}/pet/{pet_id}", local_var_configuration.base_path, pet_id=pet_id);
```
```
``` 
These …

[Rust] Added path param normalization for kebab case path params

---

modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
samples/client/others/c/bearerAuth/src/apiClient.c
samples/client/petstore/c-useJsonUnformatted/src/apiClient.c
samples/client/petstore/c/src/apiClient.c

One more patch from the original pull request at https://github.com/OpenAPITools/openapi-generator/pull/14379. I'm sending this one on its own because it was controversial the last time (@ityuhui). At my company we need the C api to verify ssl certificates by default. We already apply this patch ourselves, but I think a safer default like this should be better for everyone. Of course I'll appreciate any feedback on the matter.
@wing328 @ityuhui @zhemant @michelealbano

Fix a few issues with the C generator (part 5)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaHelidonCommonCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/languages/HelidonCommonCodegenTest.java

Resolves #20298 
The Helidon generator contains code to calculate the longest common prefix among paths to help optimize the grouping of operations into services.
As described in the bug, the original implementation essentially compared character-by-character which led to problems if paths agreed partway through a segment. For example, given the paths "/a/part-one" and "/a/part-two" the code would incorrectly yield a common prefix of "a/part-" when it should have been "/a".
The PR revises the calculation so it examines corresponding _segments_ rather than corresponding _characters_ of the paths. 
The PR includes additional tests to more thoroughly check the implementation.
(Also, the PR updates the hard-coded current latest releases of Helidon used by the generator if the user does not …

Fix bug in common path prefix calculation in Helidon generators

---

modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache
samples/openapi3/client/petstore/python-aiohttp/petstore_api/rest.py
samples/openapi3/client/petstore/python-aiohttp/tests/test_api_client.py

aiohttp's `ClientSession` & `TCPConnector` used to obtain an event loop in __init__ (via `asyncio.get_event_loop`). However, as of https://github.com/aio-libs/aiohttp/pull/8512 both classes now obtain the running event loop and won't potentially create one. This makes it impossible to create `ClientSession` and `TCPConnector` objects outside of coroutines, as `get_running_loop` must be called from a coroutine.
Thus we defer the creation of a `ClientSession` into the actual request and cache it for later usage. Thereby we pay only a very small price on the first request, but subsequent requests will not be any more expensive.
This PR should fix a long standing issue in py-gitea-opensuse-org: https://github.com/dcermak/py-gitea-opensuse-org/actions/runs/12208693521/job/34062321907?pr=48 …

[python,aiohttp] Don't create persistent aiohttp.ClientSession in __init__

---

README.md
docs/faq.md
modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/java/native/issue13968.yaml
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/BodyApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/DefaultApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
website/src/pages/index.js

[java][native] fix empty response body

---

modules/openapi-generator/src/main/resources/php-nextgen/api.mustache
samples/client/echo_api/php-nextgen-streaming/src/Api/HeaderApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/PathApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/QueryApi.php
samples/client/echo_api/php-nextgen/src/Api/HeaderApi.php
samples/client/echo_api/php-nextgen/src/Api/PathApi.php
samples/client/echo_api/php-nextgen/src/Api/QueryApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeApi.php

Using enums in path, header or query parameters with the php-nextgen generator currently causes type errors like the following:
```
PHP Fatal error:  Uncaught TypeError: OpenAPI\Client\ObjectSerializer::toPathValue(): Argument #1 ($value) must be of type string, OpenAPI\Client\Model\IntEnum given, called in /tmp/openapi-tests/src/Api/DefaultApi.php on line 1183 and defined in /tmp/openapi-tests/src/ObjectSerializer.php:165
Stack trace:
#0 /tmp/openapi-tests/src/Api/DefaultApi.php(1183): OpenAPI\Client\ObjectSerializer::toPathValue()
#1 /tmp/openapi-tests/src/Api/DefaultApi.php(1051): OpenAPI\Client\Api\DefaultApi->pathIntPGetRequest()
#2 /tmp/openapi-tests/src/Api/DefaultApi.php(1033): OpenAPI\Client\Api\DefaultApi->pathIntPGetWithHttpInfo()
#3 /tmp/openapi-tests/dev.php(11): …
```

[PHP][php-nextgen] Fix usage of enums in parameters (Fix #20086)

---

modules/openapi-generator/src/main/resources/typescript/package.mustache
samples/client/others/typescript/builds/array-of-lists/package.json
samples/client/others/typescript/builds/enum-single-value/package.json
samples/client/others/typescript/builds/null-types-simple/package.json
samples/client/others/typescript/builds/with-unique-items/package.json
samples/client/others/typescript/encode-decode/build/package.json
samples/openapi3/client/petstore/typescript/builds/browser/package.json
samples/openapi3/client/petstore/typescript/builds/composed-schemas/package.json
samples/openapi3/client/petstore/typescript/builds/default/package.json
samples/openapi3/client/petstore/typescript/builds/explode-query/package.json
samples/openapi3/client/petstore/typescript/builds/inversify/package.json
samples/openapi3/client/petstore/typescript/builds/jquery/package.json
samples/openapi3/client/petstore/typescript/builds/nullable-enum/package.json
samples/openapi3/client/petstore/typescript/builds/object_params/package.json

close the loop on #14319 and remove the now unused dependency on url-parse.
```
```  …

[typescript] remove unused url-parse package to complete WHATWG migration

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java
modules/openapi-generator/src/main/resources/php-nextgen/api.mustache

API Endpoints sometimes return different datatypes with different status codes. In the php-nextgen generator on the first such type was used as the return type which would cause fatal errors if any other type was returned.
This PR fixes that by returning an intersection type with all possible return types.
For a [minimal spec example](https://gist.github.com/JulianVennen/71e28763cee1329d93645fb19d29d319) the change looks like this.
Before:
```php
/**
* ...
* @return \OpenAPI\Client\Model\A|\OpenAPI\Client\Model\B|\OpenAPI\Client\Model\C
*/
public function testGet(
string $contentType = self::contentTypes['testGet'][0]
): \OpenAPI\Client\Model\A
```
After:
```php
/**
* ...
* @return \OpenAPI\Client\Model\A|\OpenAPI\Client\Model\B|\OpenAPI\Client\Model\C
*/
public function testGet(
string …
```

[PHP][php-nextgen] List all possible return types (fix #17113)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpNextgenClientCodegen.java
modules/openapi-generator/src/main/resources/php-nextgen/api.mustache
samples/client/echo_api/php-nextgen-streaming/src/Api/BodyApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/FormApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/HeaderApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/PathApi.php
samples/client/echo_api/php-nextgen-streaming/src/Api/QueryApi.php
samples/client/echo_api/php-nextgen/src/Api/BodyApi.php
samples/client/echo_api/php-nextgen/src/Api/FormApi.php
samples/client/echo_api/php-nextgen/src/Api/HeaderApi.php
samples/client/echo_api/php-nextgen/src/Api/PathApi.php
samples/client/echo_api/php-nextgen/src/Api/QueryApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/AnotherFakeApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeClassnameTags123Api.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/PetApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/StoreApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/UserApi.php

This PR addresses the following issues:
- If a parameter does not have a type specified and is not required, the invalid type declaration `?mixed` is generated (fix #20335)
- If a parameter is required but nullable, the generated type does not allow null values
- The methods `{operationId}Request` and `{operationId}AsyncWithHttpInfo` have no parameter types
```
``` 
You may …

[PHP][php-nextgen] Improve method parameter typing

---

modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache
modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
samples/client/others/c/bearerAuth/CMakeLists.txt
samples/client/others/c/bearerAuth/src/apiClient.c
samples/client/petstore/c-useJsonUnformatted/CMakeLists.txt
samples/client/petstore/c-useJsonUnformatted/model/order.c
samples/client/petstore/c-useJsonUnformatted/model/pet.c
samples/client/petstore/c-useJsonUnformatted/src/apiClient.c
samples/client/petstore/c/model/order.c
samples/client/petstore/c/model/pet.c
samples/client/petstore/c/src/apiClient.c

Before completing the pull request at https://github.com/OpenAPITools/openapi-generator/pull/14379, I want to draw attention to a newer issue I've recently noticed. Building the petstore sample results in the following warnings:
```
/home/runner/work/openapi-generator/openapi-generator/samples/client/petstore/c/model/order.c: In function ‘order_convertToJSON’:
/home/runner/work/openapi-generator/openapi-generator/samples/client/petstore/c/model/order.c:97:48: warning: implicit declaration of function ‘statusorder_ToString’ [-Wimplicit-function-declaration]
97 |     if(cJSON_AddStringToObject(item, "status", statusorder_ToString(order->status)) == NULL)
|                                                ^~~~~~~~~~~~~~~~~~~~
/home/runner/work/openapi-generator/openapi-generator/samples/client/ …
```

Fix a few issues with the C generator (part 6)

---

modules/openapi-generator/src/main/resources/Java/JSON.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON.mustache

This change adds some missing guards in Mustache templates to avoid having imports of conflicting date/time classes when using the Joda library. These guards were on the methods that used the differing date/time classes, but were not on the corresponding imports. Of the various Java library templates, only those for okhttp-gson and retrofit2 had these date/time class import patterns. It looks like these guards were once there but got accidentally removed as part of #11547.
I used the following command line to reproduce the issue on master using the Petstore API spec:
```
~/work/openapi-generator [master] $ java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
-g java \
--library okhttp-gson \
--additional-properties=dateLibrary=joda \
-i …
```

[Java][okhttp-gson][retrofit2] Avoid ambiguous references for date and time classes (#18416)

---

modules/openapi-generator/src/main/resources/php-nextgen/model_generic.mustache
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/Animal.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/ParentWithNullable.php

- To validate please read and use the specifications provided in the linked [issue](https://github.com/OpenAPITools/openapi-generator/issues/20343)
```
```  …

[FIX][PHP-NEXTGEN] Missing tagged union discriminator literal (#20343)

---

modules/openapi-generator/src/main/resources/python-fastapi/README.mustache

fix #19480 
Just using templated package name in the README template instead of hardcoded default package name.
To verify, simply run the FastAPI server generator with the command given in the issue, and see that the package name is filled in using the template.
```
```  …

Fix package name in FastAPI README template

---

modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache
modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
modules/openapi-generator/src/test/resources/2_0/c/petstore.yaml
samples/client/others/c/bearerAuth/CMakeLists.txt
samples/client/petstore/c-useJsonUnformatted/CMakeLists.txt
samples/client/petstore/c-useJsonUnformatted/README.md
samples/client/petstore/c-useJsonUnformatted/api/StoreAPI.c
samples/client/petstore/c-useJsonUnformatted/api/StoreAPI.h
samples/client/petstore/c-useJsonUnformatted/docs/StoreAPI.md
samples/client/petstore/c/README.md
samples/client/petstore/c/api/StoreAPI.c
samples/client/petstore/c/api/StoreAPI.h
samples/client/petstore/c/docs/StoreAPI.md

Another new warning I've noticed when building our api with the latest version:
```
/root/avh-api/c/api/api/ArmAPI.c: In function ‘ArmAPI_v1CreateImage’:
/root/avh-api/c/api/api/ArmAPI.c:1346:32: error: assignment to ‘int’ from ‘void *’ makes integer from pointer without a cast [-Werror=int-conversion]
1346 |         valueForm_encapsulated = calloc(1,MAX_NUMBER_LENGTH);
|                                ^
/root/avh-api/c/api/api/ArmAPI.c:1347:18: error: passing argument 1 of ‘snprintf’ makes pointer from integer without a cast [-Werror=int-conversion]
1347 |         snprintf(valueForm_encapsulated, MAX_NUMBER_LENGTH, "%d", *encapsulated);
|                  ^~~~~~~~~~~~~~~~~~~~~~
|                  |
|                  int
In file included from /root/avh-api/c/api/api/ArmAPI.c:2: …
```

Fix a few issues with the C generator (part 7)

---

modules/openapi-generator/src/main/resources/swift5/modelObject.mustache
modules/openapi-generator/src/main/resources/swift6/modelObject.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/Models/Banana.swift
samples/client/petstore/swift5/vaporLibrary/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift5/vaporLibrary/Sources/PetstoreClient/Models/Pet.swift
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Models/FormatTest.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Models/Pet.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Models/FormatTest.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Models/Banana.swift
samples/client/petstore/swift6/vaporLibrary/Sources/PetstoreClient/Models/FormatTest.swift
samples/client/petstore/swift6/vaporLibrary/Sources/PetstoreClient/Models/Pet.swift

Related https://github.com/OpenAPITools/openapi-generator/pull/14218
I added access control to make the validation rules of the generated model accessible from external modules.
```
```  …

Add access control to the properties of validation rules

---

modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
modules/openapi-generator/src/main/resources/swift6/libraries/urlsession/URLSessionImplementations.mustache
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
samples/client/petstore/swift5/validation/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/URLSessionImplementations.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/URLSessionImplementations.swift

For the URLSession templates, application/x-www-form-urlencoded request bodies are currently not percent-encoded. This is different in Alamofire template where those request bodies are percent-encoded. 
This fixes #20357.
```
```  …

[swift] fix: URLSession template correctly percent-encodes http body for application/x-www-form-urlencoded

---

modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
samples/client/others/c/bearerAuth/api/DefaultAPI.c
samples/client/petstore/c-useJsonUnformatted/api/PetAPI.c
samples/client/petstore/c-useJsonUnformatted/api/StoreAPI.c
samples/client/petstore/c-useJsonUnformatted/api/UserAPI.c
samples/client/petstore/c/api/PetAPI.c
samples/client/petstore/c/api/StoreAPI.c
samples/client/petstore/c/api/UserAPI.c

Note: this does not fix anything else; for example all numerical types, including float and double, are still incorrectly cast to to long int before string conversion.

[C][Client] Remove broken intToStr() macro, update samples

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java

Fixes https://github.com/OpenAPITools/openapi-generator/issues/20390
Some new tests have been added to verify that ':' is converted to '_'.
Some codegen (JavaModel and CrystalClient) have been modified to manage this new 'colon' sanitize.
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04) @joscha (2024/10)
```
``` 
This is important, as CI jobs will verify …

#20390 : On enum name sanitize, convert colon to underscore

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetServerCodegen.java
samples/server/petstore/aspnetcore-6.0-NewtonsoftFalse/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-6.0-nullableReferenceTypes/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-6.0-pocoModels/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-6.0-useSwashBuckle/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-6.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-8.0-NewtonsoftFalse/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-8.0-nullableReferenceTypes/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-8.0-pocoModels/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-8.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-8.0-useSwashBuckle/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-8.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj

[ASPNETCORE] Add support for central package version management #20192

---

modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
modules/openapi-generator/src/main/resources/C-libcurl/list.c.mustache
modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
samples/client/others/c/bearerAuth/api/DefaultAPI.c
samples/client/others/c/bearerAuth/src/apiClient.c
samples/client/others/c/bearerAuth/src/list.c
samples/client/petstore/c-useJsonUnformatted/api/PetAPI.c
samples/client/petstore/c-useJsonUnformatted/api/StoreAPI.c
samples/client/petstore/c-useJsonUnformatted/api/UserAPI.c
samples/client/petstore/c-useJsonUnformatted/model/model_with_set_propertes.c
samples/client/petstore/c-useJsonUnformatted/model/pet.c
samples/client/petstore/c-useJsonUnformatted/model/user.c
samples/client/petstore/c-useJsonUnformatted/src/apiClient.c
samples/client/petstore/c-useJsonUnformatted/src/list.c
samples/client/petstore/c/api/PetAPI.c
samples/client/petstore/c/api/StoreAPI.c
samples/client/petstore/c/api/UserAPI.c
samples/client/petstore/c/model/model_with_set_propertes.c
samples/client/petstore/c/model/pet.c
samples/client/petstore/c/model/user.c
samples/client/petstore/c/src/apiClient.c
samples/client/petstore/c/src/list.c

Cut down on redundant `strlen()` churn and similar somewhat. Functionality does not change, just runtime cost.
Request: when merging would it be possible to _not_ squash the three commits but instead just rebase? Mashing even a moderately small changeset like this into a monolithic single diff makes reading the git log significantly more taxing cognitively. You can always do `git diff HEAD~3 HEAD` to see a combined diff, but you can't recover the lost information after squashing.

C overhead fixes

---

modules/openapi-generator/src/main/resources/php-nextgen/api.mustache
samples/client/echo_api/php-nextgen-streaming/src/Api/QueryApi.php
samples/client/echo_api/php-nextgen/src/Api/QueryApi.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/FakeApi.php

Query parameters in the php-nextgen generator are passed to the ObjectSerializer::toQueryValue method. For enum refs (which use native PHP enums) the value property, which contains the backing string or number, is passed instead. This causes a PHP warning when the parameter is null. To prevent that, I added a `?` which causes the resulting value to be null if the parameter itself is null.
This is not required for header or path parameters, as these are already inside a null check.
```
```  …

[php-nextgen] Use conditional access for enumref query params

---

.github/workflows/samples-dotnet-standard.yaml
modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
samples/client/echo_api/csharp/restsharp/net8/EchoApi/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/EnumMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/ParameterMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/UseDateTimeForDate/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs

based on https://github.com/OpenAPITools/openapi-generator/pull/20290
> First, when both the default configuration and the request options added the same header (like Authorization), the header was duplicated. Now, the request options override the default headers so that the header only appears once.
credit: @maciejcymanski132 
```
```  …

[C#] avoid duplicated header in csharp client (restsharp)

---

modules/openapi-generator/src/main/resources/julia-client/api.mustache
modules/openapi-generator/src/main/resources/julia-client/api_doc.mustache
modules/openapi-generator/src/main/resources/julia-server/api_doc.mustache
modules/openapi-generator/src/main/resources/julia-server/server.mustache
samples/client/petstore/julia/docs/FakeApi.md
samples/client/petstore/julia/docs/PetApi.md
samples/client/petstore/julia/docs/StoreApi.md
samples/client/petstore/julia/docs/UserApi.md
samples/client/petstore/julia/src/apis/api_PetApi.jl
samples/server/petstore/julia/docs/FakeApi.md
samples/server/petstore/julia/docs/PetApi.md
samples/server/petstore/julia/docs/StoreApi.md
samples/server/petstore/julia/docs/UserApi.md

It seems there is a small issue with generated julia function signature, when handling
```yaml
application/octet-stream:
schema:
type: string
format: binary
```
To better reproduce this, I set up a MWE here
https://github.com/qiaojunfeng/test-julia-OpenAPI/tree/main
Since this is a julia-specific issue, I will ping technical committee member @tanmaykm. Thanks!
```
``` 
You …

Fix Julia template for binary string

---

bin/configs/java-okhttp-gson.yaml
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
samples/client/petstore/java/okhttp-gson-3.1/docs/CodesEnum.md
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/model/CodesEnum.java
samples/client/petstore/rust/hyper/petstore/src/models/unique_item_array_testing.rs
samples/client/petstore/rust/hyper0x/petstore/src/models/unique_item_array_testing.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/models/unique_item_array_testing.rs
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/models/unique_item_array_testing.rs
samples/client/petstore/rust/reqwest/petstore-async-tokensource/src/models/unique_item_array_testing.rs
samples/client/petstore/rust/reqwest/petstore-async/src/models/unique_item_array_testing.rs
samples/client/petstore/rust/reqwest/petstore-avoid-box/src/models/unique_item_array_testing.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/models/unique_item_array_testing.rs
samples/client/petstore/rust/reqwest/petstore-model-name-prefix/src/models/foo_unique_item_array_testing.rs
samples/client/petstore/rust/reqwest/petstore/src/models/unique_item_array_testing.rs
samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts

To fallback, simply set the option to true
e.g. `--additional-properties removeEnumValuePrefix=true`
```
```  …

Set removeEnumValuePrefix to false by default

---

modules/openapi-generator/src/main/resources/python/pyproject.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/pyproject.toml
samples/client/echo_api/python/pyproject.toml
samples/openapi3/client/petstore/python-aiohttp/pyproject.toml
samples/openapi3/client/petstore/python/pyproject.toml

The current syntax is compatible with Poetry. However, it seems to cause issues with some other tools (https://github.com/OpenAPITools/openapi-generator/pull/19694#discussion_r1913162884) and does not comply with the corresponding PEP (https://peps.python.org/pep-0508/#complete-grammar).
```
```

[Python] adjust multi-constraint dependency syntax to comply with PEP 508

---

modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache
samples/client/others/c/bearerAuth/CMakeLists.txt
samples/client/petstore/c-useJsonUnformatted/CMakeLists.txt
samples/client/petstore/c/.openapi-generator-ignore
samples/client/petstore/c/.openapi-generator/FILES
samples/client/petstore/c/CMakeLists.txt

Fixes `CMakeFiles.txt` so that the usual way to define custom C compile flags works. After the change users can set the initial value of `CMAKE_C_FLAGS` on the command line. Project-defined flags no longer replace the entire variable content but are appended instead. (Project flags still take priority if they need to override custom flags.)
For example to build a local version with architecture-specific CPU flags:
```sh
cmake -B /tmp/build -S /usr/src/whatever -DCMAKE_C_FLAGS='.march=znver3 -mtune=znver3'
```
The first commit enables `CMakeLists.txt` to be (re-)generated for one of the three C clients. It's been disabled for quite a long time, and it doesn't look like there is an actual reason for it. But please let me know if there's breakage.

[C][Client] Make custom CMAKE_C_FLAGS work

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_0/null_schema_test.yaml
samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/PetsPatchRequest.ts

to close https://github.com/OpenAPITools/openapi-generator/issues/20459
```
```  …

[normalizer] Better handling of schema with just description (any type)

---

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
samples/openapi3/server/petstore/go/go-petstore/go/api_pet.go
samples/openapi3/server/petstore/go/go-petstore/go/api_store.go
samples/openapi3/server/petstore/go/go-petstore/go/api_user.go
samples/server/others/go-server/no-body-path-params/go/api_body.go
samples/server/others/go-server/no-body-path-params/go/api_both.go
samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_store.go
samples/server/petstore/go-api-server/go/api_user.go
samples/server/petstore/go-chi-server/go/api_pet.go
samples/server/petstore/go-chi-server/go/api_store.go
samples/server/petstore/go-chi-server/go/api_user.go

The patch does an alternative initialization of a Go-lang variable, such that a custom pre-check and multiple alternative `:=` initialization would be needed in the mustache template. This fixes #17373 which would generate invalid code like:
```
nameParam := string{} // error: "invalid composite literal type string"
```
```
```  …

ISSUE: #17373 [BUG] [Go-server] invalid composite literal type string

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java

This work resolves the following issue - https://github.com/OpenAPITools/openapi-generator/issues/18384
Integration tests have been executed manually according to the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
```
```  …

[JAVA] Address [rawtypes] and [this-escape] warnings in generated API clients

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pojo.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/enum_discriminator_inheritance.yaml
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/EnumStringDiscriminator.java

When you define a schema with an enum discriminator and you use allOf to include the parent schema in the child schema the current generated code fails to compile due to the generator thinking the discriminator is of type string instead of enum.
This is mentioned in some issues I could find which this PR should fix:
#12412 #16073 #16672 #19194 #19261
These PRs attempt to solve it, but they have some flaws.
#10959 #16394
This was tested with `java` and `csharp` generators which both have issues. Other generators might also have issues with this if they implement custom logic of handling default values of enums like the `csharp` generator currently does.
The issue in the code lied in the fact that when checking whether or not the discriminator is an enum it only checks the properties of the …

[csharp][java] Fix enum discriminator default value

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java

This is a follow-up to the [following PR](https://github.com/OpenAPITools/openapi-generator/pull/20466) and addresses more warnings that popped up with 7.11.0. 
```
```  …

[JAVA] Additional [this-escape] warnings fixes

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJuliaCodegen.java
modules/openapi-generator/src/main/resources/julia-client/api.mustache
modules/openapi-generator/src/main/resources/julia-server/api.mustache
samples/client/petstore/julia/src/apis/api_UserApi.jl
samples/server/petstore/julia/src/apis/api_UserApi.jl

- Fix enum default value generation. Default values were falling back to the default code generator and were being generated improperly for Julia.
- Add more validations to client and server API call handlers. These validations were already being generated for models, but were missed out for API calls.
cc: @wing328 
```
```  …

[julia] fix enum default vals, add api validations

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/user.service.ts
samples/client/petstore/typescript-nestjs/builds/reservedParamNames/api/default.service.ts

Closes #20221 
```
``` 
TypeScript committee members: @TiFu (2017/07) …

Add optional AxiosRequestConfig parameter to typescript-nestjs service functions

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift6ClientCodegen.java
modules/openapi-generator/src/main/resources/swift6/modelOneOf.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/swift6/Swift6ClientCodegenTest.java
modules/openapi-generator/src/test/resources/bugs/issue_20560.yaml

Fixes incorrect generation of enum cases with associated values. #20560
```swift
master                                this PR
case typeString(String)               case typeString(String)
case type[Int]([Int])                 case typeArrayOfInt([Int])
case type[String]([String])   --->    case typeArrayOfString([String])
case type[[Int]]([[Int]])             case typeArrayOfArrayOfInt([[Int]])
```
Enum cases previously generated as `case type[Int]([Int])` become `case typeArrayOfInt([Int])`
```
```  …

[swift][bug] Fix generation of cases with associated values (#20560)

---

bin/configs/typescript-axios-echo-api.yaml
modules/openapi-generator/src/main/resources/typescript-axios/configuration.mustache
samples/client/echo_api/typescript-axios/build/configuration.ts
samples/client/others/typescript-axios/with-separate-models-and-api-inheritance/configuration.ts
samples/client/petstore/typescript-axios/builds/composed-schemas/configuration.ts
samples/client/petstore/typescript-axios/builds/default/configuration.ts
samples/client/petstore/typescript-axios/builds/es6-target/configuration.ts
samples/client/petstore/typescript-axios/builds/test-petstore/configuration.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/configuration.ts
samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/configuration.ts
samples/client/petstore/typescript-axios/builds/with-interfaces-and-with-single-request-param/configuration.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/configuration.ts
samples/client/petstore/typescript-axios/builds/with-node-imports/configuration.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/configuration.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/configuration.ts
samples/client/petstore/typescript-axios/builds/with-single-request-parameters/configuration.ts
samples/client/petstore/typescript-axios/builds/with-string-enums/configuration.ts

The change in #20067 has caused some issues with clients which run in a Browser. This commit replaces that change, leaving the default User-Agent for axios unmodified, and only sets the User-Agent if the `http-user-agent` parameter is provided during generation time.
```
```  …

[typescript-axios] Conditionally set user-agent

---

modules/openapi-generator/src/main/resources/elixir/deserializer.ex.mustache
samples/client/petstore/elixir/lib/openapi_petstore/deserializer.ex
samples/client/petstore/elixir/test/outer_enum_test.exs

This fixes a bug where an outer enum isn't properly deserialized in the generated Elixir client. See this issue. https://github.com/OpenAPITools/openapi-generator/issues/16412
I added one test to exercise the failure case, which I got from this PR https://github.com/OpenAPITools/openapi-generator/pull/19435 as I was searching to see if anyone else had been having the same problem I ran into. 
@tobbbles I grabbed your failing test from #19435 and included it here to speed things up. Thank you for your prior work on this. It pointed me in the right direction.
Real team effort here!
```
```  …

fix #16412 elixir outer enum bug

---

modules/openapi-generator/src/main/resources/rust/reqwest-trait/api.mustache
modules/openapi-generator/src/test/resources/3_0/rust/petstore.yaml
samples/client/petstore/rust/hyper/petstore/docs/PetApi.md
samples/client/petstore/rust/hyper0x/petstore/docs/PetApi.md
samples/client/petstore/rust/reqwest-trait/petstore/docs/PetApi.md
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/fake_api.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/store_api.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/testing_api.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/user_api.rs
samples/client/petstore/rust/reqwest/petstore-async-middleware/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-async-tokensource/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-async-tokensource/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-async/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-avoid-box/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-avoid-box/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-model-name-prefix/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-model-name-prefix/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore/src/apis/pet_api.rs

This PR is a small QoL improvement to add doc comments to functions based on the endpoint method/path and the operation description.
The format is:
```rs
/// {METHOD} {PATH}
/// 
/// {NOTES} 
```
example:
```rs
/// POST /v1/foo
///
/// This creates a foo in the database.
```
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as an argument …

feat: Added doc comments to Rust reqwest-trait template

---

modules/openapi-generator/src/main/resources/elixir/deserializer.ex.mustache
samples/client/petstore/elixir/lib/openapi_petstore/deserializer.ex
samples/client/petstore/elixir/test/outer_enum_test.exs

This is a more complete fix for a bug where an outer enum isn't properly deserialized in the generated Elixir client. See this issue. https://github.com/OpenAPITools/openapi-generator/issues/16412
My previous PR (https://github.com/OpenAPITools/openapi-generator/pull/20587) addressed the outer enum string bug. This follow-up PR fixes the issue more generally and updates the relevant test to ensure other outer enum types work as expected.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge …

fix outer enum number bug elixir generator

---

docs/generators/jaxrs-spec.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSCXFCDIServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pojo.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSSpecServerCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/required-properties.yaml

Fixes #20569.
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala …

[JAVA][JAXRS-SPEC] Add config option to disable generation of @JsonCreator constructor

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-restclient/infrastructure/ApiClient.kt.mustache
samples/client/echo_api/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

Should fix the following error that was appearing when generating a API for multipart/form-data requests with kotlin jvm-spring-restclient: Fixes https://github.com/OpenAPITools/openapi-generator/issues/20597
Content type 'multipart/form-data' not supported for bodyType=java.util.Collections$SingletonMap
Technical comitee: @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier
```
```  …

[kotlin-client][jvm-spring-restclient] Extract data from PartConfig for multipart/form-data requests in ApiClient

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

SortModelPropertiesByRequiredFlag - simplified comparison to order boolean false first
```
```  …

[DefaultCodegen] simplified comparison for required flag

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java

CSharpClientCodegen.cs
- use final keyword for getLibrary() within a method
- include unity in error message when unsupported library is provided by converting of/else to a map
- convert if/else to switch
- replace hard coded strings with variable usage
- postProcessModels -> simplify to avoid redundant checks
- `Boolean.FALSE.equals()` explicitly checks for false, but noneMatch() already returns true when no match is found. This avoids unnecessary boxing/unboxing of Boolean values.
- removed the `!cm.getComposedSchemas().getOneOf().isEmpty()` check because `removeIf()` inherently handles an empty list safely.
```
``` 
(For Windows users, please run the script …

[csharp] unity error message and code cleanup

---

modules/openapi-generator/src/main/resources/php-nextgen/model_generic.mustache
modules/openapi-generator/src/main/resources/php/model_generic.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpNextgenClientCodegenTest.java
modules/openapi-generator/src/test/resources/bugs/issue_20593.yaml

Fix https://github.com/OpenAPITools/openapi-generator/issues/20593
```
```  …

[php][php-nextgen] enumUnknownDefaultCase true now return the correct value for unknown values

---

modules/openapi-generator/src/test/resources/2_0/templates/Java/libraries/jersey2/build.gradle.mustache
modules/openapi-generator/src/test/resources/2_0/templates/Java/libraries/jersey2/build.sbt.mustache
modules/openapi-generator/src/test/resources/2_0/templates/Java/libraries/jersey2/pom.mustache
pom.xml

update jackson-threeten to 2.18.2

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

When an example was specified for a property with the date format, its example would be generated to something like `Sat Jan 30 01:00:00 CET 2021`.
It's because the resolved type for a date example is a `DateSchema` which uses `java.util.Date` to represents the date causing `toString()` to not conform to the `yyyy-mm-dd` format.
This is somewhat analogous to example generation in #17495.
```
```

fix: CodeGen correctly produces yyyy-mm-dd format for date with examples

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
modules/openapi-generator/src/main/resources/rust/Cargo.mustache
samples/client/others/rust/hyper/api-with-ref-param/Cargo.toml
samples/client/others/rust/hyper/composed-oneof/Cargo.toml
samples/client/others/rust/hyper/emptyObject/Cargo.toml
samples/client/others/rust/hyper/oneOf-array-map/Cargo.toml
samples/client/others/rust/hyper/oneOf-reuseRef/Cargo.toml
samples/client/others/rust/hyper/oneOf/Cargo.toml
samples/client/others/rust/reqwest-regression-16119/Cargo.toml
samples/client/others/rust/reqwest/api-with-ref-param/Cargo.toml
samples/client/others/rust/reqwest/composed-oneof/Cargo.toml
samples/client/others/rust/reqwest/emptyObject/Cargo.toml
samples/client/others/rust/reqwest/oneOf-array-map/Cargo.toml
samples/client/others/rust/reqwest/oneOf-reuseRef/Cargo.toml
samples/client/others/rust/reqwest/oneOf/Cargo.toml
samples/client/petstore/rust/reqwest/name-mapping/Cargo.toml

This PR adds logic to check if an API has at least one UUID type property and only add the uuid crate to the `Cargo.toml` if a UUID is found.
The motivation for this is to reduce un-needed dependencies and improve compile times.
```
```  …

feat: [rust] Dynamically add `uuid` crate only if used

---

modules/openapi-generator/src/main/resources/dart/libraries/dio/pubspec.mustache
samples/openapi3/client/petstore/dart-dio/oneof/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/oneof_primitive/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/pubspec.yaml

This commit fixes compatibility problems between the generated dart-dio code, json_serializable 6.9.0+, and Dart SDK 3.5 or later.
Changes:
- Updated `pubspec.mustache`:
- Set the minimum SDK constraint for the generated package to `>=3.5.0 <4.0.0`, reflecting the language version used in the generated code.
- Bump `json_annotation` dependency to `^4.9.0`.
- Bump `json_serializable` dependency to `^6.9.0`.
These changes ensure that the generated code:
- Is compatible with `json_serializable` 6.9.0+ and Dart SDK 3.5+.
- Avoids Dart 3.5+ specific syntax that causes errors on older SDKs.
- Maintains existing functionality and type safety.
PS: This …

Fix: Resolve Dart 3.5+ and json_serializable 6.9.0+ compatibility issues in generated dart-dio clients

---

bin/utils/test_file_list.yaml
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/main/resources/Java/libraries/feign/pojo.mustache
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/model/NullableClass.java
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/model/TestInlineFreeformAdditionalPropertiesRequest.java
samples/client/petstore/java/feign/src/test/java/org/openapitools/client/JacksonTest.java

When `additionalProperties` is set to `true`, use an `additionalProperties` attribute and `@JsonAnySetter` and `@JsonAnyGetter` annotations instead of extending `HashMap`.
This fixes the issue https://github.com/OpenAPITools/openapi-generator/issues/17361 only for the `feign` library.
I also created the following pull requests to fix the same issue for other libraries:
- https://github.com/OpenAPITools/openapi-generator/pull/19706 for the `resttemplate` library.
- https://github.com/OpenAPITools/openapi-generator/pull/19711 for the `webclient` library.
```
``` 
This is …

[java][feign] Fix model combining properties and additional properties

---

modules/openapi-generator/src/main/resources/csharp/HttpSigningConfiguration.mustache
samples/client/petstore/csharp/httpclient/net9/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net8/EnumMappings/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net8/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/net9/EnumMappings/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/unityWebRequest/net9/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp/unityWebRequest/standard2.0/Petstore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs

```
``` 
In .net9 SDK URL Encoding is done as part of …

[csharp] Handle query param encoding issues in .net9

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustAxumServerCodegen.java

This PR re-orders the list of `supportingFiles` in `RustAxumServerCodegen.java` so that they are in dependency order. This prevents the following error from `rustfmt` when post-processing is enabled due to `lib.rs` being formatted before referenced modules are created:
```
[main] INFO  o.o.codegen.TemplateManager - writing file /home/tanadeau/openapi/output/server-rust-axum/Cargo.toml
[main] INFO  o.o.codegen.TemplateManager - writing file /home/tanadeau/openapi/output/server-rust-axum/.gitignore
[main] INFO  o.o.codegen.TemplateManager - writing file /home/tanadeau/openapi/output/server-rust-axum/src/lib.rs
[main] ERROR o.o.codegen.DefaultCodegen - Error running the command (rustfmt --edition 2021 /home/tanadeau/openapi/output/server-rust-axum/src/lib.rs). Exit value: 1, Error output: …
```

[Rust-Axum] Fix rustfmt error due to ordering

---

modules/openapi-generator/src/main/resources/ruby-client/api_client_typhoeus_partial.mustache
samples/client/echo_api/ruby-typhoeus/lib/openapi_client/api_client.rb
samples/client/petstore/ruby-autoload/lib/petstore/api_client.rb
samples/client/petstore/ruby/lib/petstore/api_client.rb
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_client.rb
samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_client.rb
samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb

```
``` 
Hi @cliffano @zlx @autopp,
When downloading File type with …

Ruby fix typhoeus api client multiple call with file return type

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AsciidocDocumentationCodegen.java

The Asciidoc generator writes for not defined example values of e.g. model attributes the string value "null" instead of leaving it empty. 
Furthermore, override the `toRegularExpression` method to avoid additional escapes of e.g. `\` ->` \\`, ` ` -> `\` in regular expressions by skipping calling the submethod `escapeText`.
Note: We don't need additonal escapes in regular expressions for the asciidoc generator since we want to print the plain regular expression as it is in a doc file.
This PR closes Issue https://github.com/OpenAPITools/openapi-generator/issues/17149.
```
```  …

[BUG] [ASCIIDOC] Asciidoc generator sets not defined example values as string value "null"

---

modules/openapi-generator/src/main/resources/python-pydantic-v1/api_client.mustache
samples/client/echo_api/python-pydantic-v1/openapi_client/api_client.py
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/api_client.py

I'd like to apply the same solution as PR #20148 for the Python Pydantic v1 generator and have not been able to do a successful build.
```
```  …

[python] Encode list query parameters for python pydantic v1 client

---

modules/openapi-generator/src/main/resources/rust/model.mustache
modules/openapi-generator/src/main/resources/rust/reqwest-trait/api.mustache
modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache

This PR is an attempt to make the templates for the Rust client a bit more maintainable.
Currently, we have all of the function signature is a single line making it very difficult to reason about/update.
The approach here is to use mustache comments (ie. `{{! my comment }}` ) to annotate parts of the template and break things into multiple lines.
There are no changes when running the `./bin/generate-samples.sh ./bin/configs/*.yaml` script so the changes should not affect the generated clients.
<details><summary>PR checklist</summary>
```
``` 
This is …

[RUST] chore: Clean up Rust reqwest and model templates

---

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt

I have split my API spec YAML files across multiple files, and use the Gradle task to generate Kotlin server interfaces. The Gradle task incorrectly thinks it is UP-TO-DATE if only `inputSpec` is given because Gradle only checks that one file for changes, even though the generator is able to process the entire structure correctly. The `inputSpecRootDirectory` property is available which will tell Gradle to look at the entire directory, but _for some reason_ (I don't know) the generator is unable to process the merged file. So I've just cut out the middle step, and allowed for the best of both worlds.
Introduced a new property `inputSpecRootDirectorySkipMerge` to conditionally skip the merging step of the specification files. I chose it to be similar to `inputSpecRootDirectory` so that it …

[Kotlin] Add Option to Skip Merging Spec Files

---

modules/openapi-generator/src/main/resources/typescript-angular/modelEnum.mustache
modules/openapi-generator/src/test/resources/3_0/typescript-angular/composed-schemas.yaml
samples/client/others/typescript-angular/builds/composed-schemas-tagged-unions/model/dogBreed.ts
samples/client/others/typescript-angular/builds/composed-schemas/model/dogBreed.ts

Fixes #20692.
Adapted `typescript-angular/modelEnum.mustache` to respect `x-enum-descriptions` / `enumDescription`.
```
```  …

Fix #20692 [typescript-angular] Support enumDescription / x-enum-descriptions

---

modules/openapi-generator/src/main/resources/python/github-workflow.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/.github/workflows/python.yml
samples/client/echo_api/python/.github/workflows/python.yml
samples/openapi3/client/petstore/python-aiohttp/.github/workflows/python.yml
samples/openapi3/client/petstore/python/.github/workflows/python.yml

This fixes the github workflow file template for the Python client.
In order to use the `{{ }}` Github syntax more easily the mustache markers are changed to `<% %>` at the beginning of the file, so we have to use those instead.
```
```  …

[Python] Fix mustache tag syntax in github worklow

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
modules/openapi-generator/src/test/resources/3_0/rust/petstore.yaml
samples/client/petstore/rust/hyper/petstore/docs/TypeTesting.md
samples/client/petstore/rust/hyper/petstore/src/models/type_testing.rs
samples/client/petstore/rust/hyper0x/petstore/docs/TypeTesting.md
samples/client/petstore/rust/hyper0x/petstore/src/models/type_testing.rs
samples/client/petstore/rust/reqwest-trait/petstore/docs/TypeTesting.md
samples/client/petstore/rust/reqwest-trait/petstore/src/models/type_testing.rs
samples/client/petstore/rust/reqwest/petstore-async-middleware/docs/TypeTesting.md
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/models/type_testing.rs
samples/client/petstore/rust/reqwest/petstore-async-tokensource/docs/TypeTesting.md
samples/client/petstore/rust/reqwest/petstore-async-tokensource/src/models/type_testing.rs
samples/client/petstore/rust/reqwest/petstore-async/docs/TypeTesting.md
samples/client/petstore/rust/reqwest/petstore-async/src/models/type_testing.rs
samples/client/petstore/rust/reqwest/petstore-avoid-box/docs/TypeTesting.md
samples/client/petstore/rust/reqwest/petstore-avoid-box/src/models/type_testing.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/docs/TypeTesting.md
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/models/type_testing.rs
samples/client/petstore/rust/reqwest/petstore-model-name-prefix/docs/FooTypeTesting.md
samples/client/petstore/rust/reqwest/petstore-model-name-prefix/src/models/foo_type_testing.rs
samples/client/petstore/rust/reqwest/petstore/docs/TypeTesting.md
samples/client/petstore/rust/reqwest/petstore/src/models/type_testing.rs
samples/client/petstore/rust/reqwest/petstore/tests/type_testing.rs

Fixed compiler errors for `type: string, format: number` (aka decimal) types.
See https://github.com/OpenAPITools/openapi-generator/issues/20626 for more details
In the issue I mentioned some potential libraries for to represent decimal types.
However after some thought, I think defaulting to `String` makes sense. 
The user can simply parse the string into their desired BigDecimal datatype and we can add a config flag for a specific library in the future if there is demand for it.
<details><summary>PR checklist</summary>
```
``` 
This is important, as …

[rust] Fixed compiler errors for decimal types

---

modules/openapi-generator/src/main/resources/nodejs-express-server/package.mustache

Remove `axios` from `package.mustache` as it's not used in the starter build. This eliminates potential security vulnerabilities (ReDos & SSRF) from the dependency tree without affecting functionality.
fix #10427
```
```  …

fix(nodejs-express-server): remove unused axios dependency

---

modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/apiDelegate.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/service.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/serviceImpl.mustache
samples/server/petstore/kotlin-springboot-reactive-without-flow/src/main/kotlin/org/openapitools/api/PetApiController.kt
samples/server/petstore/kotlin-springboot-reactive-without-flow/src/main/kotlin/org/openapitools/api/PetApiService.kt
samples/server/petstore/kotlin-springboot-reactive-without-flow/src/main/kotlin/org/openapitools/api/PetApiServiceImpl.kt

Issue https://github.com/OpenAPITools/openapi-generator/issues/16130
In [previous PR 20409](https://github.com/OpenAPITools/openapi-generator/pull/20409) I added new `useFlowForArrayReturnType` param, but unfortunately it was added with mistake. The thing is that `List` endpoints generated with `useFlowForArrayReturnType = false` must have `suspend` modifier; otherwise I have no possibility to call `suspend` service-layer (and other) functions from my controller (with `useFlowForArrayReturnType = true` I can call them when actually building `Flow`). This PR fixes that thing.
@dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier @e5l
```
``` …

[kotlin-spring] Adds 'suspend' modifier for reactive List endpoint with useFlowForArrayReturnType = false (#16130)

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
samples/client/echo_api/kotlin-jvm-okhttp/src/main/kotlin/org/openapitools/client/apis/QueryApi.kt

It's not possible to use request objects in the API (e.g. `findItems(SearchRequest(name, status, fromDate, ...))`). One more example is a pagination parameter, something like `Page(size,offset)`. I'd like to use a model in the API but it's not possible at the moment.
Kotlin Client generator is not exploding a query object properly. It uses the object `toString()` method, so API request doesn't work. See [OpenAPI Parameter Serialization](https://swagger.io/docs/specification/v3_0/serialization/#query-parameters).
Used `isModel`, `isDeepObject`, `vars` template variables to fill `localVariableQuery` with the fields of the query object.
It should work fine for objects with primitive, enum, date props. The behavior for nested objects and arrays is undefined (And it is mentioned in [the …

[kotlin][client] Explode query param properly

---

modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache
modules/openapi-generator/src/main/resources/python/configuration.mustache
modules/openapi-generator/src/main/resources/python/rest.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/configuration.py
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/rest.py
samples/client/echo_api/python/openapi_client/configuration.py
samples/client/echo_api/python/openapi_client/rest.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/configuration.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/rest.py
samples/openapi3/client/petstore/python/petstore_api/configuration.py
samples/openapi3/client/petstore/python/petstore_api/rest.py

The `ca_cert_data` parameter lets a client validate a server's CA certificate chain using a variable/constant containing PEM (`str`) or DER (`bytes`) data, rather than needing to reference a file on disk.
Naming is based on what `urllib3` calls this parameter.
I've applied a similar patch to some locally generated bindings for `asyncio` and `urllib3`, and it's working there.
```
```  …

[Python] Add `ca_cert_data` parameter

---

docs/customization.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_0/enableSetTagsToVendorExtension_test.yaml

- Add openapi-normalizer rule to set tags to vendor extension
- add tests
- to close https://github.com/OpenAPITools/openapi-generator/issues/20709
e.g.
`java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i modules/openapi-generator/src/test/resources/3_0/enableSetTagsToVendorExtension_test.yaml -o /tmp/java-okhttp/ --openapi-normalizer SET_TAGS_TO_VENDOR_EXTENSION=x-tags`
```
``` 
These must …

Add openapi-normalizer rule to set tags to vendor extension

---

modules/openapi-generator/src/main/resources/erlang-server/api.mustache
modules/openapi-generator/src/main/resources/erlang-server/handler.mustache
modules/openapi-generator/src/main/resources/erlang-server/server.mustache
samples/server/echo_api/erlang-server/src/openapi_api.erl
samples/server/echo_api/erlang-server/src/openapi_auth_handler.erl
samples/server/echo_api/erlang-server/src/openapi_body_handler.erl
samples/server/echo_api/erlang-server/src/openapi_form_handler.erl
samples/server/echo_api/erlang-server/src/openapi_header_handler.erl
samples/server/echo_api/erlang-server/src/openapi_path_handler.erl
samples/server/echo_api/erlang-server/src/openapi_query_handler.erl
samples/server/echo_api/erlang-server/src/openapi_server.erl
samples/server/petstore/erlang-server/src/openapi_api.erl
samples/server/petstore/erlang-server/src/openapi_pet_handler.erl
samples/server/petstore/erlang-server/src/openapi_server.erl
samples/server/petstore/erlang-server/src/openapi_store_handler.erl
samples/server/petstore/erlang-server/src/openapi_user_handler.erl

Current erlang-server generates code with errors which will always crash on key authorisation.  This PR fix them and also has minor performance improvements for map updates.
@tsloughter
```
``` 
IMPORTANT: Do …

[erlang] erlang-server generator fixes

---

modules/openapi-generator/src/main/resources/erlang-server/handler.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/erlang/ErlangServerCodegenTest.java

When content type or accept in header contain character part (i.e. ContentType: application/json;charset=utf-8), server crash when tries to process request.
```
```  …

[Erlang] Fix crash on escaped type in erlang-server handler

---

modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api.mustache
modules/openapi-generator/src/main/resources/Java/libraries/microprofile/beanValidationCookieParams.mustache
modules/openapi-generator/src/main/resources/Java/libraries/microprofile/cookieParams.mustache
modules/openapi-generator/src/main/resources/Java/libraries/microprofile/cookieParamsImpl.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/microprofile/JavaMicroprofileServerCodegenTest.java
modules/openapi-generator/src/test/resources/bugs/microprofile_cookie.yaml

The Java MicroProfile generator was missing support for cookie parameters and would generate invalid code.
Example:
````yaml
info:
version: 2.0.0
title: test
paths:
/pets:
get:
summary: bla
operationId: getCustomer
parameters:
- name: first
in: header
schema:
type: string
- name: cookieParameter
in: cookie
schema:
type: string
responses:
'200':
description: OK
````            
would generate 
````java
@RegisterRestClient()
@RegisterProvider(ApiExceptionMapper.class)
@Path("/pets")
public interface CustomerApiApi  {
/**
* get information of the current customer
*
*/
@GET
@Produces({ "application/vnd.advisory-v1+json", "application/problem+json" })
GetCustomer200Response getPets(@HeaderParam("x-refnr")  String xRefnr, ) throws ApiException, ProcessingException;
}
````
Note …

Added support for Cookie parameters

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustAxumServerCodegen.java
modules/openapi-generator/src/test/resources/3_0/rust-axum/rust-axum-oneof.yaml
samples/server/petstore/rust-axum/output/rust-axum-oneof/src/models.rs

Found out that `oneOf`'s enum variant names were not correctly generated and datatypes like `Vec<foo::bar::Baz>` would end up as `Baz` instead of `VecOfBaz` generating duplicates in cases like the test included.
```
```  …

[Rust] Fix enum variant name generation

---

README.md
modules/openapi-generator/src/main/resources/Java/libraries/restclient/ApiClient.mustache
samples/client/echo_api/java/restclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/restclient-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-nullable-arrays/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-useSingleRequestParameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient/src/main/java/org/openapitools/client/ApiClient.java

Similar to other Java Client libs (e.g. RestTemplate [PullRequest](https://github.com/OpenAPITools/openapi-generator/pull/16485)), RestClient should also allow setting a bearerToken supplier instead of just a static string. 
I used the given RestTemplate PR as a template for this PR.
```
```  …

[Java][RestClient] Enable access token refresh

---

bin/configs/spring-cloud-3-with-optional.yaml
docs/generators/java-camel.md
docs/generators/spring.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java

a follow-up PR to #20406 
```
``` 

[java][spring] Add option `optionalAcceptNullable` to accept null values

---

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Validate.java
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

This PR adds authentication headers (if any) when fetching the OpenAPI definitions remotely. 
Changes have been made on:
- `validate` command of openapi-generator-cli
- `calculateInputSpecHash` method in CodeGenMojo.java
- `createCollapsedSpec` method in CodeGenMojo.java
Resolves #19308, resolves #19108
```
```  …

Authentication headers in Mojo and CLI 'validate' command

---

modules/openapi-generator/src/main/resources/nim-client/api.mustache
samples/client/petstore/nim/petstore/apis/api_pet.nim
samples/client/petstore/nim/petstore/apis/api_user.nim

Same parameter name declared multiple time in the same scope. => nim generated code does not compile.
```
```  …

[nim] Fix nim code generation in case of an endpoint for which schema defines both query parameters and multipart/form-data

---

modules/openapi-generator-maven-plugin/examples/java-client.xml
modules/openapi-generator-maven-plugin/examples/multi-module/pom.xml

fix failing pipeline "Maven plugin tests"
The problem is that the maven tests still include jackson 2.15.2 dependencies while the generated code is intended for jackson 2.17.1.
```
```  …

fix Maven plugin tests

---

modules/openapi-generator/src/main/resources/ocaml/model.mustache
samples/client/petstore/ocaml/src/models/api_response.ml
samples/client/petstore/ocaml/src/models/category.ml
samples/client/petstore/ocaml/src/models/order.ml
samples/client/petstore/ocaml/src/models/pet.ml
samples/client/petstore/ocaml/src/models/tag.ml
samples/client/petstore/ocaml/src/models/user.ml

Add a default value for non-required lists.
Also, indent the model template to make it easier to read and maintain.
I have kept 2 commits to easily review the cleanup vs the actual fix, and its impact on the sample petstore.
Closes https://github.com/OpenAPITools/openapi-generator/issues/20777
@cgensoul
```
```  …

[OCaml] Fix default optional list

---

modules/openapi-generator/src/main/resources/Javascript/libraries/javascript/ApiClient.mustache
samples/client/petstore/javascript-es6/src/ApiClient.js

Prior to this commit, a JS client generated with skipDefaultUserAgent enabled results in a src/ApiClient.js file that doesn't define this.defaultHeaders. This breaks because this.defaultHeaders is later directly passed to a superagent request which expects an object and not undefined.
Fixes #20791.
```
```  …

[JavaScript] Avoid undefined headers with skipDefaultUserAgent enabled

---

docs/customization.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java

Expanding on the work of https://github.com/OpenAPITools/openapi-generator/pull/17859 to add additional filters for Tags and Methods.
We personally needed the ability to generate only GET endpoints.
I also noticed the feature request for filtering by tags https://github.com/OpenAPITools/openapi-generator/issues/17653#issuecomment-2210539589 and added it with this change set.
I've added tests for the new filters and everything passes, I would love for a maintainer to review what I've written and give feedback.
```
```  …

Add tag and method filters during generation

---

modules/openapi-generator/src/main/resources/php-nextgen/model_generic.mustache
samples/client/echo_api/php-nextgen-streaming/src/Model/DefaultValue.php
samples/client/echo_api/php-nextgen-streaming/src/Model/Pet.php
samples/client/echo_api/php-nextgen-streaming/src/Model/Query.php
samples/client/echo_api/php-nextgen/src/Model/DefaultValue.php
samples/client/echo_api/php-nextgen/src/Model/Pet.php
samples/client/echo_api/php-nextgen/src/Model/Query.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/EnumArrays.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/EnumTest.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/MapTest.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/Order.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/ParentWithNullable.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/Pet.php

```
``` 
@jebentier, @dkarlovi, @mandrean, @jfastnacht, @ybelenko, …

[PHP-NEXTGEN] make allowable values enum getter static

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
modules/openapi-generator/src/main/resources/csharp/libraries/httpclient/ApiClient.mustache

When using C# OpenAPI clients with HttpClient or RestSharp from a browser via WASM (such as in Blazor WASM) it can be necessary to customize the HttpClient or RestRequest before sending it. In my case I need to invoke `httpRequestMessage.SetBrowserRequestCredentials(BrowserRequestCredentials.Include)` on the underlying HTTP request so that the browser's secure cookies are included with the request.
To achieve this in a backwards-compatible way I've introduced the `useVirtualForHooks` option for C#, which alters the definition of the `InterceptRequest` and `InterceptResponse` hooks to become `public virtual` methods, allowing the end-user to define custom HTTP request hooks. Technically I only need the `InterceptRequest` hook, but I've included `InterceptResponse` for consistency and …

[csharp] Add useVirtualForHooks option

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default/api/pet.service.ts

The current template assigns query parameters using:  
```mustache
queryParameters['{{baseName}}'] = {{paramName}}.join(COLLECTION_FORMATS['{{collectionFormat}}']);
```
However, this does not work with `URLSearchParams`, as it does not allow direct property assignment. Instead, it requires `.set()` or `.append()` to properly modify query parameters.
Replace the assignment with:  
```mustache
queryParameters.append('{{baseName}}', {{paramName}}.join(COLLECTION_FORMATS['{{collectionFormat}}']));
```
This ensures that query parameters are correctly added and serialized in the request URL.

fix(typescript-nestjs): handle query params serialization properly

---

modules/openapi-generator/src/main/resources/typescript-angular/api.base.service.mustache
samples/client/others/typescript-angular/builds/composed-schemas-tagged-unions/api.base.service.ts
samples/client/others/typescript-angular/builds/composed-schemas/api.base.service.ts
samples/client/petstore/typescript-angular-v12-oneOf/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api.base.service.ts
samples/client/petstore/typescript-angular-v13-oneOf/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api.base.service.ts
samples/client/petstore/typescript-angular-v14-provided-in-root/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v14-query-param-object-format/api.base.service.ts
samples/client/petstore/typescript-angular-v15-provided-in-root/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v16-provided-in-root/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v17-provided-in-root/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v18-provided-in-root/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v19-with-angular-dependency-params/builds/default/api.base.service.ts
samples/client/petstore/typescript-angular-v19/builds/default/api.base.service.ts

fixes #20799  (was introduced with https://github.com/OpenAPITools/openapi-generator/pull/20681)
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka @joscha please review :)
```
```  …

[typescript-angular] fix: correctly serialize query params objects

---

modules/openapi-generator/src/main/resources/csharp/RetryConfiguration.mustache
samples/client/echo_api/csharp/restsharp/net8/EchoApi/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/httpclient/net9/Petstore/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/net8/EnumMappings/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/net8/ParameterMappings/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/net8/Petstore/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/net8/UseDateTimeForDate/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/net9/EnumMappings/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/RetryConfiguration.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/RetryConfiguration.cs

This enables use of `Polly.ResiliencePipelineBuilder` where the built `Polly.ResiliencePipeline` returns an interface when using properties `AsSyncPolicy` or `AsAsyncPolicy`.
@mandrean @shibayan @Blackclaws @lucamazzanti @iBicha
```
```  …

Use interfaces for Polly retry policies in C#

---

modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
samples/server/petstore/rust-server/output/multipart-v3/Cargo.toml
samples/server/petstore/rust-server/output/no-example-v3/Cargo.toml
samples/server/petstore/rust-server/output/openapi-v3/Cargo.toml
samples/server/petstore/rust-server/output/ops-v3/Cargo.toml
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml
samples/server/petstore/rust-server/output/ping-bearer-auth/Cargo.toml
samples/server/petstore/rust-server/output/rust-server-test/Cargo.toml

Bump up env_logger dependency for Rust Server to 0.11.
```
``` 
@frol …

[Rust Server] Bump up env_logger to 0.11

---

modules/openapi-generator/src/main/resources/go-server/helpers.mustache
modules/openapi-generator/src/main/resources/go-server/routers.mustache
samples/openapi3/server/petstore/go/go-petstore/go/helpers.go
samples/openapi3/server/petstore/go/go-petstore/go/routers.go
samples/server/others/go-server/no-body-path-params/go/helpers.go
samples/server/others/go-server/no-body-path-params/go/routers.go
samples/server/petstore/go-api-server/go/helpers.go
samples/server/petstore/go-api-server/go/routers.go
samples/server/petstore/go-chi-server/go/helpers.go
samples/server/petstore/go-chi-server/go/routers.go

Related to https://github.com/OpenAPITools/openapi-generator/issues/20817
Missed moving the errMsgs from the router to the helper file in this MR: https://github.com/OpenAPITools/openapi-generator/pull/20823
Apologies about that! This MR is to complete the move so everything helper is together and router is standalone
```
```  …

[go-server] move errMsg helpers to helpers file

---

modules/openapi-generator/src/main/resources/Java/libraries/restclient/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
samples/client/echo_api/java/restclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/echo_api/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/restclient-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/resttemplate-list-schema-validation/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/resttemplate-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/webclient-useAbstractionForFiles/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-nullable-arrays/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-useSingleRequestParameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient-jakarta/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient-nullable-arrays/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient-useSingleRequestParameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java

Replace all UriComponentsBuilder.fromHttpUrl() with UriComponentsBuilder.fromUriString() because UriComponentsBuilder.fromHttpUrl will be removed in the near future.

#20868 - [REQ] [JAVA] [restClient] replace Deprecated code

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/config/GlobalSettings.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/config/GlobalSettingsTest.java

This pull request aims to fix an issue I've noticed when adding a non-string value or key as a system property.
The issue surfaces during the invocation of [CodeMojo#execute](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java#L962).
In such cases, [GlobalSettings#log](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/config/GlobalSettings.java#L71) throws a `ClassCastException` as expected/partially documented  [here](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/Properties.java#L1240).
```
./bin/generate-samples.sh ./bin/configs/*.yaml || …
```

fix(openapi-generator): fixes GlobalSettings

---

modules/openapi-generator/src/main/resources/python/README_onlypackage.mustache
modules/openapi-generator/src/main/resources/python/pyproject.mustache
modules/openapi-generator/src/main/resources/python/requirements.mustache
modules/openapi-generator/src/main/resources/python/setup.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/pyproject.toml
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/requirements.txt
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/setup.py
samples/client/echo_api/python/pyproject.toml
samples/client/echo_api/python/requirements.txt
samples/client/echo_api/python/setup.py
samples/openapi3/client/petstore/python-aiohttp/pyproject.toml
samples/openapi3/client/petstore/python-aiohttp/requirements.txt
samples/openapi3/client/petstore/python-aiohttp/setup.py
samples/openapi3/client/petstore/python/pyproject.toml
samples/openapi3/client/petstore/python/requirements.txt
samples/openapi3/client/petstore/python/setup.py
samples/openapi3/client/petstore/python/tests/test_api_exception.py

This PR updates urllib3's requirement for the Python generator. As described in #20826, older versions of the library were incompatible with the new `ca_cert_data` parameter added in PR #20697.
Fixes #20826.
---
```
```  …

fix: #20826 Update urllib3 requirement for Python generator

---

modules/openapi-generator/src/main/resources/swift6/Validation.mustache
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/Validation.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/Validation.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/Validation.swift
samples/client/petstore/swift6/vaporLibrary/Sources/PetstoreClient/Infrastructure/Validation.swift

Swift 6 allows for the `throws` keyword to specify the type of error being thrown. In the case of Validation, this will save one unboxing/casting operation and make the result easier to use.
```
``` 
IMPORTANT: …

[swift6] Add typed throws to Validation functions

---

modules/openapi-generator/src/main/resources/swift6/APIs.mustache
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/APIs.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/APIs.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/APIs.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIs.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/APIs.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/APIs.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/APIs.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIs.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIs.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIs.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIs.swift
samples/client/petstore/swift6/swift6_test_all.sh
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/APIs.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIs.swift

Currently there is no way to identify a request between retries, which it a bit limiting.
This PR adds an identifier to a request that keeps the same between retries.
```
```  …

[Swift][client] add identifier to each request

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/config/GlobalSettingsTest.java

a follow-up PR to #20744
```
``` 

Update global setting tests

---

modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/serializers.mustache
samples/openapi3/client/petstore/dart-dio/oneof/lib/src/serializers.dart
samples/openapi3/client/petstore/dart-dio/oneof_polymorphism_and_inheritance/lib/src/serializers.dart
samples/openapi3/client/petstore/dart-dio/oneof_primitive/lib/src/serializers.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/serializers.dart

Using dart-dio with `timemachine` leads to syntax error in `lib/src/serializers.dart` -> `Expected to find ')'`
It seems the bug was introduced here https://github.com/OpenAPITools/openapi-generator/pull/9180 ([see file](https://github.com/OpenAPITools/openapi-generator/pull/9180/files#diff-ed34f92642117843559fafdc7629de7660700f11ba8b2294a2003c22b25d7185)), where there's a closing bracket for `{{#useDateLibCore}} ....... {{/useDateLibCore}}`  but not for `{{#useDateLibTimeMachine}} ....... {{/useDateLibTimeMachine}}`. 
Adding the bracket just before the `.build` to ensure it is always closed, independent of what's defined in previous lines...
---
```
``` 
(For …

[dart-dio][timemachine] Bugfix: Ensure closing bracket when adding serializers

---

modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache

Closes #20904
Fixed the order, now it does not generate annotation only if there is a description.
```
```  …

Fix src/main/resources/JavaSpring/pojo.mustache to generate Deprecated unrelated to description

---

modules/openapi-generator/src/main/resources/swift6/APIHelper.mustache
modules/openapi-generator/src/main/resources/swift6/Extensions.mustache
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/alamofireLibrary/Sources/PetstoreClient/Infrastructure/Extensions.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/apiNonStaticMethod/Sources/PetstoreClient/Infrastructure/Extensions.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/asyncAwaitLibrary/Sources/PetstoreClient/Infrastructure/Extensions.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/combineDeferredLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Extensions.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/combineLibrary/Sources/CombineLibrary/Infrastructure/Extensions.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/default/Sources/PetstoreClient/Infrastructure/Extensions.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/objcCompatible/Sources/PetstoreClient/Infrastructure/Extensions.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/oneOf/PetstoreClient/Classes/OpenAPIs/Infrastructure/Extensions.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Extensions.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/resultLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Extensions.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Infrastructure/Extensions.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/urlsessionLibrary/Sources/PetstoreClient/Infrastructure/Extensions.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/APIHelper.swift
samples/client/petstore/swift6/validation/PetstoreClient/Classes/OpenAPIs/Infrastructure/Extensions.swift

https://github.com/OpenAPITools/openapi-generator/pull/20906 introduced two issues related to the parameters encoding.
The first problem is the following.
The default overload is disfavored and this is correct, this overload should be the last option to execute, if no other overload is compatible.
https://github.com/OpenAPITools/openapi-generator/blob/6e3b1996ed2f8a9cfb2fee1f60138b2ed4d77341/modules/openapi-generator/src/main/resources/swift6/Extensions.mustache#L25-L28
Those protocol conformance should execute the previous default implementation, but actually those are codable, so it will execute the overload of the codable. 
https://github.com/OpenAPITools/openapi-generator/blob/6e3b1996ed2f8a9cfb2fee1f60138b2ed4d77341/modules/openapi-generator/src/main/resources/swift6/Extensions.mustac …

[Swift][client] fix parameters encoding

---

bin/configs/protobuf-schema-config.yaml
bin/configs/protobuf-schema.yaml
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java
modules/openapi-generator/src/main/resources/protobuf-schema/api.mustache
modules/openapi-generator/src/main/resources/protobuf-schema/model.mustache
modules/openapi-generator/src/test/resources/3_0/protobuf/petstore.yaml
samples/config/petstore/protobuf-schema-config/models/order.proto
samples/config/petstore/protobuf-schema/models/order.proto

This PR fixes the issue by removing the "model/" prefix from imports that are explicitly mapped through importMapping. The generator now correctly handles standard protobuf types and ensures generated files compile successfully.
Example of Incorrect Import:
`import "model/google/protobuf/struct.proto"; 
`
Now:
`import "google/protobuf/struct.proto";
`
```
``` 
You may …

[protobuf-schema] Remove 'model/' prefix from Protobuf imports for mapped custom packages

---

modules/openapi-generator/src/main/resources/scala-akka-http-server/multipartDirectives.mustache
samples/server/petstore/scala-akka-http-server/src/main/scala/org/openapitools/server/MultipartDirectives.scala
samples/server/petstore/scala-pekko-http-server/src/main/scala/org/openapitools/server/MultipartDirectives.scala

Scala 3.x or latest Scala 2.13.x with migrate option( `-Xsource:3-cross` ) require parentheses in lambda params. 
```
Welcome to Scala 3.6.4 (11.0.26, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
scala> { (x: Int) => x }
val res0: Int => Int = Lambda$1505/0x00000008007f0040@389008d1
scala> { x: Int => x }
-- Error: ----------------------------------------------------------------------
1 |{ x: Int => x }
|         ^
|         parentheses are required around the parameter of a lambda
```
```
$ scala -Xsource:3-cross
Welcome to Scala 2.13.16 -Xsource:3.0.0 (OpenJDK 64-Bit Server VM, Java 11.0.26).
Type in expressions for evaluation. Or try :help.
scala> { (x: Int) => x }
val res0: Int => Int = $Lambda$1088/0x00000008006b0840@591a4f8e
scala> { x: Int => x …
```

update scala-akka-http-server generator

---

docs/customization.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java

Putting this up to help clarify my feature request in https://github.com/OpenAPITools/openapi-generator/issues/20842. I wanted to see if something like this would be considered. If so, I will proceed and add unit tests and documentation to get the PR ready for review. If not, I'll go the direction of putting this into a user defined template instead.
The openapi 2.0 spec did not support bearer authentication but it was added in openapi 3.0. In order to support client generation that includes support for bearerAuth, this change adds a new feature to the OpenapiNormalizer so that it can be configured to look for a specific securityDefinition name and convert it to bearerAuth.
Example:
openapi-generator-cli config file includes:
```
openapiNormalizer:
DETECT_BEARER_AUTH_FROM_NAME: bearerAuth …
```

Add support for normalizing bearerAuth

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java

```
``` 
The action name is escaped from `ActionName` to ``ActionNameOperation`. The enum is also exported escaped as `ActionNameOperationEnum`.
But currently, enums are then referenced via unescaped name as `ActionNameEnum`.

fix: escape operationIds before outputting them

---

modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/Serializer.kt.mustache
samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt

Currently the kotlinx serializer and adapter are not configurable from the outside.
This PR fixes that and also changes the level of some old deprecation warning to error.
```
```  …

[kotlin][client] make kotlinx serialization configurable

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache
samples/client/others/typescript-fetch/self-import-issue/models/AbstractUserDto.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Animal.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/ParentWithNullable.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/models/Animal.ts

Closes https://github.com/OpenAPITools/openapi-generator/issues/20982
```
```  …

fix: support backwards compatible changes in discriminators

---

modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin5/beanValidation.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin5/beanValidationModel.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin5/data_class_opt_var.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin5/data_class_req_var.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin5/paramDefault.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin5/pathParams.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin5/queryParams.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/beanValidation.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/beanValidationModel.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/data_class_opt_var.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/data_class_req_var.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/headerParams.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/paramDefault.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/pathParams.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/javalin6/queryParams.mustache
samples/server/petstore/kotlin-server-required-and-nullable-properties/src/main/kotlin/org/openapitools/server/models/Pet.kt
samples/server/petstore/kotlin-server/javalin-6/src/main/kotlin/org/openapitools/server/models/Category.kt
samples/server/petstore/kotlin-server/javalin-6/src/main/kotlin/org/openapitools/server/models/ModelApiResponse.kt
samples/server/petstore/kotlin-server/javalin-6/src/main/kotlin/org/openapitools/server/models/Order.kt
samples/server/petstore/kotlin-server/javalin-6/src/main/kotlin/org/openapitools/server/models/Pet.kt
samples/server/petstore/kotlin-server/javalin-6/src/main/kotlin/org/openapitools/server/models/Tag.kt
samples/server/petstore/kotlin-server/javalin-6/src/main/kotlin/org/openapitools/server/models/User.kt
samples/server/petstore/kotlin-server/javalin/src/main/kotlin/org/openapitools/server/models/Category.kt
samples/server/petstore/kotlin-server/javalin/src/main/kotlin/org/openapitools/server/models/ModelApiResponse.kt
samples/server/petstore/kotlin-server/javalin/src/main/kotlin/org/openapitools/server/models/Order.kt
samples/server/petstore/kotlin-server/javalin/src/main/kotlin/org/openapitools/server/models/Pet.kt
samples/server/petstore/kotlin-server/javalin/src/main/kotlin/org/openapitools/server/models/Tag.kt
samples/server/petstore/kotlin-server/javalin/src/main/kotlin/org/openapitools/server/models/User.kt

Several smaller fixes and additions to the javalin5 and javalin6 generators
- Bugfix for having a nullable property with a default value. It is assumed the interface can have a non-nullable field as an implementation for this. However, it is required to then set the default value.
- Adding validations to the beans (largely copied from the jaxrs implementation)
- Adding explicit basenames in the ObjectMapper Property annotations so that we do not have to rely on ObjectMappers' property name translations
@dr4ke616, @karismann, @Zomzog, @andrewemery, @4brunu, @yutaka0m, @stefankoppier, @e5l

Javalin fixes and validation

---

modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/psr-18/lib/ObjectSerializer.php

[PHP] - Removes trailing comma from ::flattenArray()

---

modules/openapi-generator/src/main/resources/JavaSpring/converter.mustache
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/openapi3/server/petstore/springboot-delegate/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/openapi3/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-beanvalidation-no-nullable/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-beanvalidation/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-delegate/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-reactive-noResponseEntity/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-spring-pageable-delegatePattern/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-spring-pageable-without-j8/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-spring-pageable/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-virtualan/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java

Add package to bean name in converter.mustache for EnumConverterConfiguration.java to resolve issue #17737 
```
```  …

#11737 Add package to bean name in converter.mustache for EnumConverterConfiguration.java

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJuliaCodegen.java

Fixed escaping of regex patterns on julialang server codegen.
cc: @wing328 
```
```  …

[julia] fix regex escape on server codegen

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java

In order to avoid a warning when the `supportsES6` additional property is not explicitly set, we check if is present before trying to set it inside `processOpts()` method of `AbstractTypeScriptClientCodegen` class:
```java
if (additionalProperties.containsKey(CodegenConstants.SUPPORTS_ES6)) {
setSupportsES6(convertPropertyToBooleanAndWriteBack(CodegenConstants.SUPPORTS_ES6));
}
```
Resolves #20485
```
```  …

[TypeScript] Avoid warning in TypeScript client generator due to SUPPORTS_ES6

---

modules/openapi-generator/src/main/resources/rust/Cargo.mustache
samples/client/others/rust/reqwest-regression-16119/Cargo.toml
samples/client/others/rust/reqwest/api-with-ref-param/Cargo.toml
samples/client/others/rust/reqwest/composed-oneof/Cargo.toml
samples/client/others/rust/reqwest/emptyObject/Cargo.toml
samples/client/others/rust/reqwest/oneOf-array-map/Cargo.toml
samples/client/others/rust/reqwest/oneOf-reuseRef/Cargo.toml
samples/client/others/rust/reqwest/oneOf/Cargo.toml
samples/client/petstore/rust/reqwest-trait/petstore/Cargo.toml
samples/client/petstore/rust/reqwest/name-mapping/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-async-middleware/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-async-tokensource/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-async/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-avoid-box/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-awsv4signature/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-model-name-prefix/Cargo.toml
samples/client/petstore/rust/reqwest/petstore/Cargo.toml

Generated Rust crates will allow configuring reqwest to use rustls via passthrough features.
fix: #19853
```
```  …

feat: [Rust][client] Add option to use rustls for reqwest instead of openssl

---

modules/openapi-generator/src/main/resources/php-laravel/api_controller.mustache
samples/server/petstore/php-laravel/Http/Controllers/AnotherFakeController.php
samples/server/petstore/php-laravel/Http/Controllers/DefaultController.php
samples/server/petstore/php-laravel/Http/Controllers/FakeClassnameTags123Controller.php
samples/server/petstore/php-laravel/Http/Controllers/FakeController.php
samples/server/petstore/php-laravel/Http/Controllers/PetController.php
samples/server/petstore/php-laravel/Http/Controllers/StoreController.php
samples/server/petstore/php-laravel/Http/Controllers/UserController.php

When handling exceptions thrown in the concrete instance of the API interface we currently do not report them. This would be problematic in production environments. Adding the `report` fixes this issue by using [Laravel error reporting](https://laravel.com/docs/12.x/errors#reporting-exceptions).
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as …

Add error reporting when handling exception in PHP Laravel

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/others/typescript-fetch/self-import-issue/runtime.ts
samples/client/petstore/typescript-fetch/builds/allOf-nullable/runtime.ts
samples/client/petstore/typescript-fetch/builds/allOf-readonly/runtime.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
samples/client/petstore/typescript-fetch/builds/oneOf/runtime.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/snakecase-discriminator/runtime.ts
samples/client/petstore/typescript-fetch/builds/validation-attributes/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts

This fixes the O(n^2) runtime of mapValues by replacing the spread operator reduce with a simple loop doing direct assignment. 
fixes #21046 
```
```  …

Fixes mapValues runtime inefficiency in typescript-fetch

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java

Currently, the implementation of the code generator for Python can generate invalid Python code if single quotes are used within an OpenAPI specification, e.g. for default values. Please see also this [issue](https://github.com/OpenAPITools/openapi-generator/issues/21022) that I have created.
This stems from invalid single quote escaping within the generator. It's kind of hard to spot, but in Java the strings "'" and "\'" are identical, so the implementation and its test were broken identically. 
This seems to have happened already quite a few years ago during refactoring, since the test seems might have been created as a result of this [issue](https://github.com/OpenAPITools/openapi-generator/issues/5981).
The minimal example from there is still valid:
```yaml
openapi: 3.0.0
info:
title: …
```

Fix single quote escaping for python code generator (and its test)

---

modules/openapi-generator/src/main/resources/crystal/api.mustache
modules/openapi-generator/src/main/resources/crystal/api_client.mustache
modules/openapi-generator/src/main/resources/crystal/model.mustache
modules/openapi-generator/src/main/resources/crystal/partial_model_generic.mustache
samples/client/petstore/crystal/spec/api_client_spec.cr
samples/client/petstore/crystal/src/petstore/api/fake_api.cr
samples/client/petstore/crystal/src/petstore/api/pet_api.cr
samples/client/petstore/crystal/src/petstore/api/store_api.cr
samples/client/petstore/crystal/src/petstore/api/user_api.cr
samples/client/petstore/crystal/src/petstore/api_client.cr
samples/client/petstore/crystal/src/petstore/models/another_property_name_mapping.cr
samples/client/petstore/crystal/src/petstore/models/api_response.cr
samples/client/petstore/crystal/src/petstore/models/category.cr
samples/client/petstore/crystal/src/petstore/models/format_test.cr
samples/client/petstore/crystal/src/petstore/models/order.cr
samples/client/petstore/crystal/src/petstore/models/pet.cr
samples/client/petstore/crystal/src/petstore/models/tag.cr
samples/client/petstore/crystal/src/petstore/models/user.cr

* fix(crystal): implement cookie Auth
* fix(crystal): don't send query parameters when parameter is nil
* fix(crystal): make optional parameters truly optional
* fix(crystal): bump to Crest 1.5.1
* fix(crystal): allow users to YAML.dump(model) to ease debug
```
```  …

 [crystal-lang] Various fixes for Crystal client

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache

When using enums in multipart/form-data requests, the generated code is missing the ".value" when appending the form data:
`enumprop?.apply { append("enumprop", enumprop) }`
should be, for enums and enum references:
`enumprop?.apply { append("enumprop", enumprop.value) }`
This fixes the template to include the ".value".
Sample spec:
```yaml
openapi: 3.0.1
info:
title: Test API
version: '1'
paths:
/some/path/method/{path_enum}:
put:
parameters:
- name: path_enum
in: path
description: 'Path enum'
schema:
$ref: "#/components/schemas/enumreftype"
required: true
requestBody:
content:
schema:
type: object
properties:
enumprop:
enum:
- 'value A'
- 'value B'
enumrefprop:
$ref: "#/components/schemas/enumreftype"
responses:
204:
description: 'Processed.'
components:
schemas: …
```

[kotlin-multiplatform] fix: kotlin multiplatform form-data enum params

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
samples/server/petstore/spring-boot-defaultInterface-unhandledException/.openapi-generator/FILES
samples/server/petstore/spring-boot-defaultInterface-unhandledException/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java

```
``` 
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) …

[Java][Spring] Ensure EnumConverterConfiguration.java is generated when interfaceOnly=true in Spring Generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PostmanCollectionCodegen.java
modules/openapi-generator/src/main/resources/postman-collection/item.mustache
modules/openapi-generator/src/main/resources/postman-collection/request.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/postman/PostmanCollectionCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/postman-collection/SampleProject.yaml
samples/schema/postman-collection/postman.json
samples/schema/postman-collection/python/test/test_endpoints.py

PR to include the response examples in the generated Postman collection JSON file.
@wing328 
```
```  …

[POSTMAN] Include response examples

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java
modules/openapi-generator/src/test/resources/3_0/protobuf/petstore-complex.yaml
samples/config/petstore/protobuf-schema-config-complex/.openapi-generator/FILES
samples/config/petstore/protobuf-schema-config-complex/models/pet.proto
samples/config/petstore/protobuf-schema-config-complex/models/tag_map.proto

This PR addresses a corner case where a map defined within an composed schema is being ignored during Protobuf generation. 
Previously, the pet map (the field defined via additionalProperties) was not being handled properly, resulting in its omission from the generated proto file. the schema like the following:
```
schemas:
Dog:
allOf:
- $ref: '#/components/schemas/DogBase'
- type: object
title: pet
$ref: '#/components/schemas/Pet'
minProperties: 1
Pet:
type: string
DogBase:
type: object
properties:
bark:
type: boolean
breed:
type: string
enum: [ Dingo, Husky, Retriever, Shepherd ]
```
With this PR, the generator now correctly detects and processes the pet map, ensuring that it is included in the generated Protobuf message.
``` …
```

[Protobuf Schema] Map Field Handling in Composed Schemas

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache
samples/client/petstore/java/feign-hc5/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java

Fixing performance issues due to Hardcoded HTTP client
1. Breaking change was introduced [here](https://github.com/OpenAPITools/openapi-generator/commit/a7a59378137cb1ce70d785f422251928df009846#diff-86e0b144aa0784ea6cccf92ec027a7b82407ee0cd823044b82396f7ffe08db92R55). (Somehow, the PR got merged despite a review comment suggested to revert the same in 2023 for a different reason)
2. This is causing performance issues as new tcp connection is created for each new request which is caught in performance tests.
3. Lot of TCP connections are created which in turn results in exceeded CPU utilisation and eventually timeout errors as all the resources are exhausted. For example, below image shows the number of TCP connections opened by my application which is using feign client to be 64. For 64 …

[JAVA][FEIGN] Removing hardcoded HTTP Client which is causing performance issues

---

modules/openapi-generator/src/main/resources/elixir/connection.ex.mustache
samples/client/petstore/elixir/lib/openapi_petstore/connection.ex

Generated documentation in the `Connection` module includes hard-coded references to the sample `OpenAPIPetstore` application.
This `PR` includes a fix to replace these hard-coded references by dynamic references to the generated module.
@mrmstn, @wing328 - This should be an easy one. As usual, curious to hear your thoughts 😊
```
```  …

[doc][elixir] remove hard-coded refs to openapipetstore

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache
samples/client/others/java/jersey2-oneOf-Mixed/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/jersey2-oneOf-duplicates/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey3-oneOf/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java

#8756 fixed issue #8755, where enabling debug settings in the ApiClient had no effect since the HTTP client was not reinitialized. The fix was to always reinitialize the HTTP client. This fix causes another issue, however, since the HTTP client is always reinitialized from the default settings, ignoring previously set options via `apiClient#setClientConfig(ClientConfig)` (e.g. proxy settings). 
This PR fixes both issues by applying debug settings to the existing ClientConfig instead of always reinitializing from default settings.
```
``` 
This is …

Jersey2: Do not reinitialize ClientConfig with default values when building HTTP Client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonFastapiCodegenTest.java

```
``` 
This fixes an error when the user supplys custom values for …

fix(fastapi): use correct impl & package vars on custom user values

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache
samples/client/others/java/jersey2-oneOf-Mixed/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/jersey2-oneOf-duplicates/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey3-oneOf/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java

A bug in [ApiClient.musache](modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache) causes API-keys to  be ignored when generating from an OpenAPI-specification file with an ApiKey securityScheme: 
```
{
"openapi" : "3.0.0",
"security" : [ {
"ApiKey" : [ ]
} ],
[...]
"components" : {
"securitySchemes" : {
"ApiKey" : {
"type" : "apiKey",
"description" : "Description",
"name" : "apiKey",
"in" : "query"
}
}
}
}
```
The generated code applies the query parameters to the WebTarget at [ApiClient.mustache:1235](https://github.com/OpenAPITools/openapi-generator/blob/9374dbd0308598a56b11746c364a71fceaa82c2b/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache#L1235), but the query parameters do not yet contain the API-key …

Jersey2: Move setting of authentication parameters before generating target URL to consider API keys in URL parameters

---

modules/openapi-generator/src/main/resources/csharp/Configuration.mustache
samples/client/echo_api/csharp/restsharp/net8/EchoApi/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/httpclient/net9/Petstore/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/httpclient/standard2.0/Petstore/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net8/EnumMappings/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net8/ParameterMappings/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net8/Petstore/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net8/UseDateTimeForDate/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net8/useVirtualForHooks/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/net9/EnumMappings/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/unityWebRequest/net9/Petstore/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp/unityWebRequest/standard2.0/Petstore/src/Org.OpenAPITools/Client/Configuration.cs

If no enum_values are given for in a serverUrl, the check should be ignored. Currently the serverVariable must contain "enum_values" otherwise the function throws an exception that serverVariables does not contain "enum_values"
@mandrean (2017/08) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)
```
```  …

Check if enum_values exists in the serverUrl [csharp]

---

docs/generators/elixir.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
modules/openapi-generator/src/test/resources/3_0/elixir/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/petstore/elixir/lib/openapi_petstore/api/fake.ex
samples/client/petstore/elixir/lib/openapi_petstore/api/store.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/array_of_array_of_number_only.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/array_of_number_only.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/fake_big_decimal_map_200_response.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/format_test.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/mixed_properties_and_additional_properties_class.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/nullable_class.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/number_only.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/object_with_deprecated_fields.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/order.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/outer_composite.ex

This PR addresses the issue reported in #21135 - ie. an issue with the generated typespecs that would prevent some generated clients from compiling; but it also introduces the following changes:
- Remove dead code
- More idiomatic type mappings and language-specific types
- Refactor type detection and typespecs generation to improve code re-usability and mantainability
All in all, this should contribute to make the Elixir generator easier to extend and more maintainable.
As usual, curious to hear your thoughts @mrmstn, @wing328 🙂
```
``` 
This is …

[fix][elixir] wrong typespec generation for all-of with single ref

---

docs/generators/elixir.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
modules/openapi-generator/src/main/resources/elixir/connection.ex.mustache
samples/client/petstore/elixir/lib/openapi_petstore/connection.ex

This `PR` adds support for [Bearer Authentication ](https://swagger.io/docs/specification/v3_0/authentication/bearer-authentication/)to the Elixir generator.
Bearer Authentication is implemented using [Tesla's BearerAuth middleware](https://hexdocs.pm/tesla/Tesla.Middleware.BearerAuth.html).
@mrmstn, @wing328 - Curious to hear your thoughts on this one too! 🙂
```
``` 
You …

[feat][elixir] support bearer authentication

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-ktor/api.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache
samples/client/petstore/kotlin-default-values-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/DefaultApi.kt
samples/client/petstore/kotlin-jvm-ktor-gson/docs/PetApi.md
samples/client/petstore/kotlin-jvm-ktor-gson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-jvm-ktor-jackson/docs/PetApi.md
samples/client/petstore/kotlin-jvm-ktor-jackson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-jvm-ktor-kotlinx_serialization/docs/PetApi.md
samples/client/petstore/kotlin-jvm-ktor-kotlinx_serialization/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-multiplatform-kotlinx-datetime/docs/PetApi.md
samples/client/petstore/kotlin-multiplatform-kotlinx-datetime/src/commonMain/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-multiplatform/docs/PetApi.md
samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/PetApi.kt

The currently generated code for multipart/form-data does not compile for binary parameters.
See  #9423, #19644 and #18094. It also fails when there's a list of files to be uploaded.
This PR includes 2 changes:
1. KotlinClientCodegen was changed to respect container types (to fix lists of files).
2. KotlinClientCodegen will now set the dataType to Ktor's FormPart instead of InputProvider
3. The api.mustache was changed accordingly.
No. 2 has some implications:
- The parameter name must be passed by the caller (When creating a FormPart like `FormPart("document", inputProvider)`
- The headers are still not set correctly, e.g. mime type and filename have to be set by the caller.
This may not be the most convenient solution to upload files, but it should suit every application as it leaves …

[kotlin] [multiplatform] [jvm-ktor] Fix formdata file upload

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/MergedSpecBuilder.java

Allow MergedSpecBuilder title, version and description to be configured to fix [#20822](https://github.com/OpenAPITools/openapi-generator/issues/20822)
I have made small changes to MErgedSpecBuilder and CodeGenMojo to allow users of the openapi-generator-maven-plugin to add a custom info header in merged open api files.
Before making this change, the fields in the info header were hard-coded as `title="merged spec"`, `description="merged spec"` and `version=1.0.0`
Now, through the use of 3 maven plugin tags, the setting of these fields by the user of the plugin is now possible. An example is provided below. With these changes, one can easily verify that the new plugin configuration is being adopted. The new info header values will appear in the open api file and any generated …

Enhancement: Allow MergedSpecBuilder title, version and description to be configured to fix [#20822]

---

modules/openapi-generator/src/main/resources/go/api_test.mustache

This is a PR to address #21106.
FYI @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)
```
```  …

fix: Support PathParams not of primitive types for Go in generated tests

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-webclient/infrastructure/ApiClient.kt.mustache
samples/client/echo_api/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-spring-2-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-spring-3-webclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

Fixes #16923
Spring configures the uriTemplate attribute and not generated openapi code. It also leverages Spring's uriBuilderFactory to correctly set the template.
Also, the commit removes a compile warning.
Kotlin technical committee:
@dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06) @e5l (2024/10)
```
```  …

[kotlin-client][jvm-spring-webclient] Fix metrics URI templating for WebClient

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-spring-restclient/infrastructure/ApiClient.kt.mustache
samples/client/echo_api/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-jvm-spring-3-restclient/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

Similar fix as #21148 but for RestClient
Spring configures uriTemplate attribute
Kotlin technical committee:
@dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06) @e5l (2024/10)
```
```  …

[kotlin-client][jvm-spring-restclient] Fix metrics URI templating for RestClient

---

modules/openapi-generator/src/main/resources/csharp/libraries/generichost/JsonConverter.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/anyOfDiscriminatorSimple.yaml

Using an anyOf with a discriminator creates uncompilable code with cshapr generichost. The issue is that the generated code tries to call a constructor with only one parameter, but the constructor will have multiple parameters.
Steps to reproduce:
```sh
cat << 'EOF' > modules/openapi-generator/src/test/resources/3_0/anyOfDiscriminatorSimple.yaml
openapi: 3.0.1
info:
title: fruity
version: 0.0.1
paths:
/:
get:
responses:
'200':
description: desc
content:
schema:
$ref: '#/components/schemas/FruitAnyOfDisc'
components:
schemas:
FruitAnyOfDisc:
anyOf:
- $ref: '#/components/schemas/AppleAnyOfDisc'
- $ref: '#/components/schemas/BananaAnyOfDisc'
discriminator:
propertyName: fruitType
AppleAnyOfDisc:
type: object
required:
- fruitType
properties:
fruitType:
type: string …
```

fix: [csharp] JsonConverter anyOf creates uncompilable code

---

modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
modules/openapi-generator/src/main/resources/JavaSpring/methodBody.mustache

Enable `returnSuccessCode` via maven plugin. Generate Spring Boot app (`<generatorName>spring</generatorName>`) via maven plugin.
```xml
<returnSuccessCode>true</returnSuccessCode>
```
Open API Generator version: 7.8.0
Please find the issue details in the issue: https://github.com/OpenAPITools/openapi-generator/issues/19446
```
```  …

Add HTTP status code in the setExampleResponse

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java

Properly parse the new `supportVertxFuture` option as boolean. Without this fix, setting "supportVertxFuture=false" enables the setting, because `"false"` is a non-empty value and thus evaluates to `true`.
This is a follow-up to https://github.com/OpenAPITools/openapi-generator/pull/21083. cc @RickyRister
```
```  …

[Java][Vertx] fix vertxFuture parsing

---

modules/openapi-generator/src/main/resources/php-nextgen/model_generic.mustache
samples/client/echo_api/php-nextgen-streaming/src/Model/DefaultValue.php
samples/client/echo_api/php-nextgen-streaming/src/Model/Pet.php
samples/client/echo_api/php-nextgen-streaming/src/Model/Query.php
samples/client/echo_api/php-nextgen/src/Model/DefaultValue.php
samples/client/echo_api/php-nextgen/src/Model/Pet.php
samples/client/echo_api/php-nextgen/src/Model/Query.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/EnumArrays.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/EnumTest.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/MapTest.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/Order.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/ParentWithNullable.php
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Model/Pet.php

fix(php-nextgen): do not call static methods dynamically

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/TemplateManagerOptions.java

Minor fixes to javadoc

---

docs/generators/scala-akka-http-server.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaHttpServerCodegen.java
modules/openapi-generator/src/main/resources/scala-akka-http-server/build.sbt.mustache
modules/openapi-generator/src/main/resources/scala-akka-http-server/controller.mustache
modules/openapi-generator/src/main/resources/scala-akka-http-server/stringDirectives.mustache
samples/server/petstore/scala-akka-http-server/build.sbt
samples/server/petstore/scala-akka-http-server/src/main/scala/org/openapitools/server/Controller.scala
samples/server/petstore/scala-akka-http-server/src/main/scala/org/openapitools/server/StringDirectives.scala
samples/server/petstore/scala-pekko-http-server/build.sbt
samples/server/petstore/scala-pekko-http-server/src/main/scala/org/openapitools/server/Controller.scala
samples/server/petstore/scala-pekko-http-server/src/main/scala/org/openapitools/server/StringDirectives.scala

fix some warnings and update akka, pekko and scala versions.
```
``` 

update akka-http and pekko-http server generator and example

---

modules/openapi-generator/src/main/resources/elixir/connection.ex.mustache
samples/client/petstore/elixir/lib/openapi_petstore/connection.ex

This PR simplifies the generated `Connection` module according to the discussion [here](https://github.com/OpenAPITools/openapi-generator/pull/21110#issuecomment-2816781119). The new approach is more idiomatic and improves the maintainability of the generator.
Additionally, it resolves the issue reported in #20562 by removing the problematic function specification from the generated code. The issue can be reproduced using Stripe's OpenAPI specification, available [here](https://raw.githubusercontent.com/stripe/openapi/refs/tags/v1719/openapi/spec3.json).
```
== Compilation error in file lib/connection.ex ==
** (MismatchedDelimiterError) mismatched delimiter found on lib/connection.ex:92:45:
error: unexpected token: )
│
4 │ defmodule Stripe.Connection do
│                             └ …
```

[fix][elixir] simplify connection module

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ErlangClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ErlangProperCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java

fix https://github.com/OpenAPITools/openapi-generator/issues/21172
Turn `hasParams` from a field into a getter to ensure the value is always up to date.
The problem reported in #21172 was caused by not updating `hasParams` after removing some parameters. With the new design, such problems are not possible anymore for `hasParams`. We probably should apply the same change to other fields like e.g. `hasRequiredParams` as well.
```
```  …

ensure correct value for hasParams

---

.devcontainer/devcontainer.json
modules/openapi-generator/src/main/resources/python-fastapi/README.mustache
samples/server/petstore/python-fastapi/README.md

The dev container fails to build because of the outdated docker-in-docker feature. This updates the docker-in-docker and fixes the build. I also updated the docker compose references in the docs.
```
```  …

fix: fix dev container failing to build

---

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
samples/client/echo_api/csharp/restsharp/net8/EchoApi/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/MultipleFrameworks/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.7/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net4.8/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/EnumMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/ParameterMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/UseDateTimeForDate/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net8/useVirtualForHooks/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/net9/EnumMappings/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp/restsharp/standard2.0/Petstore/src/Org.OpenAPITools/Client/ApiClient.cs

For the csharp generator, ConfigureAwait(false) was missing from a few awaited tasks in asynchronous ApiClient methods. This results in a deadlock when they are called synchronously in a WinForms application with a UI synchronization context (ask me how I know).
```
```  …

[csharp] Add missing ConfigureAwait(false) for csharp generator

---

modules/openapi-generator/src/main/resources/php-flight/register_routes_test.mustache
samples/server/petstore/php-flight/Test/RegisterRoutesTest.php

Hi
Static analysis tools such as PHPStan report errors when dynamic calls are used for static methods.
```
ERROR Dynamic call to static method PHPUnit\Framework\Assert::assertEquals().
```
According to the source code of PHPUnit
(https://github.com/sebastianbergmann/phpunit/blob/9.5.0/src/Framework/Assert.php) the function is indeed static.
```php
public static function assertTrue($condition, string $message = ''): void
```
This change updates to PHP Flight test template `register_routes_test.mustache` to use static calls for PHPUnit assertions.
@jebentier, @dkarlovi, @mandrean, @jfastnacht, @ybelenko, @renepardon: Thanks for having a look at this PR. Please inform me if there's anything I'd have to improve to get this merged.
``` …
```

[php-flight] fix: use static PHPUnit assertions

---

modules/openapi-generator/src/main/resources/php-laravel/api_controller.mustache
samples/server/petstore/php-laravel/Http/Controllers/FakeController.php

Update the api_controller.mustach
$request->bool is not a laravel function ,
should be $request->boolean()
```
```  …

[php-laravel generator] update $request->bool to $request->boolean

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
modules/openapi-generator/src/main/resources/php-symfony/Controller.mustache
modules/openapi-generator/src/main/resources/php-symfony/serialization/JmsSerializer.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/Controller.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Service/JmsSerializer.php

_(This is the update of #21258 that I pushed too soon the other day. This time I took more time to thoroughly think it before opening this PR)_
```
```  …

[php-symfony] fix handling of endpoints with "text/plain" or "image/png" response type

---

modules/openapi-generator/src/test/resources/3_0/php-symfony/petstore.yaml
samples/server/petstore/php-symfony/SymfonyBundle-php/Api/PetApiInterface.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/PetController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/README.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/config/routing.yaml
samples/server/petstore/php-symfony/SymfonyBundle-php/docs/Api/PetApiInterface.md

```
``` 
PR #21261 added support for endpoints …

[Php-Symfony] add text/plain and image/png endpoint in petstore.yaml

---

bin/configs/kotlin-misk-config.yaml
docs/generators/kotlin-misk.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinMiskServerCodegen.java
modules/openapi-generator/src/main/resources/kotlin-misk/apiAction.mustache
modules/openapi-generator/src/main/resources/kotlin-misk/apiImpl.mustache
modules/openapi-generator/src/main/resources/kotlin-misk/apiInterface.mustache
modules/openapi-generator/src/main/resources/kotlin-misk/api_test.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/misk/KotlinMiskServerCodegenOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/KotlinMiskServerCodegenOptionsProvider.java
samples/server/petstore/kotlin-misk-config/docs/PetApi.md
samples/server/petstore/kotlin-misk-config/docs/StoreApi.md
samples/server/petstore/kotlin-misk-config/docs/UserApi.md
samples/server/petstore/kotlin-misk-config/src/main/kotlin/org/openapitools/server/api/api/PetApiAction.kt
samples/server/petstore/kotlin-misk-config/src/main/kotlin/org/openapitools/server/api/api/StoreApiAction.kt
samples/server/petstore/kotlin-misk-config/src/main/kotlin/org/openapitools/server/api/api/UserApiAction.kt
samples/server/petstore/kotlin-misk-config/src/test/kotlin/org/openapitools/server/api/api/PetApiTest.kt
samples/server/petstore/kotlin-misk-config/src/test/kotlin/org/openapitools/server/api/api/StoreApiTest.kt
samples/server/petstore/kotlin-misk-config/src/test/kotlin/org/openapitools/server/api/api/UserApiTest.kt
samples/server/petstore/kotlin-misk/.openapi-generator/FILES
samples/server/petstore/kotlin-misk/docs/PetApi.md
samples/server/petstore/kotlin-misk/docs/StoreApi.md
samples/server/petstore/kotlin-misk/docs/UserApi.md
samples/server/petstore/kotlin-misk/src/main/kotlin/org/openapitools/server/api/api/PetApiAction.kt
samples/server/petstore/kotlin-misk/src/main/kotlin/org/openapitools/server/api/api/StoreApiAction.kt
samples/server/petstore/kotlin-misk/src/main/kotlin/org/openapitools/server/api/api/UserApiAction.kt
samples/server/petstore/kotlin-misk/src/test/kotlin/org/openapitools/server/api/api/PetApiTest.kt
samples/server/petstore/kotlin-misk/src/test/kotlin/org/openapitools/server/api/api/StoreApiTest.kt
samples/server/petstore/kotlin-misk/src/test/kotlin/org/openapitools/server/api/api/UserApiTest.kt

Kotlin Misk Add Extra Parameters

---

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache
samples/server/petstore/python-fastapi/requirements.txt

Currently, installing dependencies fails for FastAPI projects when using Python 3.13. This bumps up `typing-extensions` and `uvloop` to the latest versions to include 3.13 support. Using these new dependency versions with previous Python versions does not appear to cause any new problems when running `pip install`.
@krjakbrjak @fa0311 @multani 
Fixes #20058 
```
```  …

[python-fastapi] Upgrade dependencies to support Python 3.13

---

modules/openapi-generator/src/main/resources/php-symfony/Controller.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/Controller.php

[PHP-Symfony] revamp the computation of the contentType

---

modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache

Following [this issue](https://github.com/OpenAPITools/openapi-generator/issues/21204), when using integer enums with the kotlin-client generator, the generated enum will look like this:
```kotlin
@Serializable
enum class SomeCode(val value: kotlin.Int) {
@SerialName(value = "0")
_0(0)
}
```
You can see the values of the enum members are not integers, they are strings (`value = "0"`).  
Using integer enums, it's should look like this:
```kotlin
@Serializable
enum class SomeCode(val value: kotlin.Int) {
@SerialName(value = 0)
_0(0),
}
```
1. Create a `test.yml` file with the following content:
```yml
openapi: 3.0.3
info:
title: Demo
version: v1
components:
schemas:
Code:
type: integer
enum:
- 0
- 1
StringCode:
type: string
enum:
- hello
- world
paths:
/do:
get:
summary: Do something …
```

[kotlin-client] Add support for integer enums in serialization step

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

Fix broken build on Windows OS if the schema contains references to other schema files. The same project configuration works under Linux without issues.
This is because the `${project.basedir}` maven variable contains `\` in the string representation and this causes the resolve of referenced schema files.
```
[INFO] --- openapi-generator:7.13.0:generate (default) @ ****-****-**** ---
[ERROR] Error resolving schema ./bidibnode.json#/$defs/node
java.net.URISyntaxException: Illegal character in opaque part at index 2: D:\sample\demo/src/main/resources/json-api/bidib.json
at java.net.URI$Parser.fail (URI.java:2995)
at java.net.URI$Parser.checkChars (URI.java:3166)
at java.net.URI$Parser.parse (URI.java:3202)
at java.net.URI.<init> (URI.java:645)
at …
```

Fix broken build on Windows OS if the schema contains references to other schema files

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NimClientCodegen.java

This is a fix for bug https://github.com/OpenAPITools/openapi-generator/issues/20779
In case of a schema with an enum constraint, nim code generation creates a nim objtect type enum with the enum values of this schema enum.
It must be valid identifier otherwise the code can not compile.
The fix is to 
1/ detect if it is a valid nim identifier, job done with the isValidIdentifier private function, using a pattern based on the definition of a nim valid identifier (see https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords)
2/ If it is not a valid identifier, we surround the identifier with backticks.
- [X ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ X] Pull Request title clearly describes …

[Nim] Fix compilation in case of schema with enum constraint with an enum value being not a valid nim identifier

---

.github/workflows/samples-python-pydantic-v1-petstore.yaml
modules/openapi-generator/src/main/resources/python-pydantic-v1/__init__package.mustache
modules/openapi-generator/src/main/resources/python/__init__package.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonPydanticV1ClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/__init__.py
samples/client/echo_api/python-pydantic-v1/openapi_client/__init__.py
samples/client/echo_api/python/openapi_client/__init__.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/__init__.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/user_api.py
samples/openapi3/client/petstore/python-aiohttp/tests/test_api_client.py
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/__init__.py
samples/openapi3/client/petstore/python-pydantic-v1-aiohttp/petstore_api/api/user_api.py
samples/openapi3/client/petstore/python-pydantic-v1/petstore_api/__init__.py
samples/openapi3/client/petstore/python-pydantic-v1/petstore_api/api/user_api.py
samples/openapi3/client/petstore/python/petstore_api/__init__.py
samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
samples/openapi3/client/petstore/python/tests/test_api_client.py

to fix #20878
based on #20887
```
``` 

Provide " as member" where needed 

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api_client.py
samples/client/echo_api/python/openapi_client/api_client.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py

The method did not consider the objects created for oneOf schemata. If one of the cases was a list, to_dict would return it instead of something that has an items() method.
This should be reviewed by members of the python technical committee:
@cbornet @tomplus @krjakbrjak @fa0311 @multani
```
```  …

[Python] Correct sanitize_for_serialization in python generator for list in oneOf schema elements, fixes #18106

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestSdkClientCodegen.java

```
``` 
@ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille …

[cpp-restsdk] Fix invalid code if type is referenced in schema

---

modules/openapi-generator/src/main/resources/python/github-workflow.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/.github/workflows/python.yml
samples/client/echo_api/python/.github/workflows/python.yml
samples/openapi3/client/petstore/python-aiohttp/.github/workflows/python.yml
samples/openapi3/client/petstore/python/.github/workflows/python.yml

Info from CodeQL on repos containing a generated python client:
"Actions job or workflow does not limit the permissions of the GITHUB_TOKEN. Consider setting an explicit permissions block, using the following as a minimal starting point: {contents: read}"
"If a GitHub Actions job or workflow has no explicit permissions set, then the repository permissions are used. Repositories created under organizations inherit the organization permissions. The organizations or repositories created before February 2023 have the default permissions set to read-write. Often these permissions do not adhere to the principle of least privilege and can be reduced to read-only, leaving the write permission only to a specific types as issues: write or pull-requests: write."
``` …
```

[python] Explicitly define github workflow permissions

---

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
modules/openapi-generator/src/main/resources/go-server/routers.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/goserver/GoServerCodegenTest.java
samples/openapi3/server/petstore/go/go-petstore/go/api_pet.go
samples/openapi3/server/petstore/go/go-petstore/go/api_store.go
samples/openapi3/server/petstore/go/go-petstore/go/api_user.go
samples/openapi3/server/petstore/go/go-petstore/go/routers.go
samples/server/others/go-server/no-body-path-params/go/api_body.go
samples/server/others/go-server/no-body-path-params/go/api_both.go
samples/server/others/go-server/no-body-path-params/go/api_none.go
samples/server/others/go-server/no-body-path-params/go/api_path.go
samples/server/others/go-server/no-body-path-params/go/routers.go
samples/server/petstore/go-api-server/go/api_fake.go
samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_store.go
samples/server/petstore/go-api-server/go/api_user.go
samples/server/petstore/go-api-server/go/routers.go
samples/server/petstore/go-api-server/samples_tests/api_pet_test.go
samples/server/petstore/go-api-server/samples_tests/routers_test.go
samples/server/petstore/go-chi-server/go/api_fake.go
samples/server/petstore/go-chi-server/go/api_pet.go
samples/server/petstore/go-chi-server/go/api_store.go
samples/server/petstore/go-chi-server/go/api_user.go
samples/server/petstore/go-chi-server/go/routers.go

Go maps are never deterministically ordered, according to the [Go map documentation](https://pkg.go.dev/maps#All). 
> The iteration order is not specified and is not guaranteed to be the same from one call to the next
In the past, I think it was close enough to not be a problem, but since Go 1.24's refactor of how Go maps work (they are using swiss tables now) the orders are nearly random. This results in the returned `Routes`map being in a different iteration order each time, which is not ideal for cases where router-order matters (#19445 for instance)
To solve this, I have added a new function called `OrderedRoutes`which returns routes in an order-deterministic slice instead. I left the old `Routes()`getter for the time being for backwards compat.
``` …
```

[GO] Go Server: Adds ordered routes to go-server router

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_1/issue_21051.yaml

[JAVA] Correct generation of schema default values of type object (issue #21051)

---

docs/generators/python.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
modules/openapi-generator/src/main/resources/python/pyproject.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/pyproject.toml
samples/client/echo_api/python/pyproject.toml
samples/openapi3/client/petstore/python-aiohttp/pyproject.toml
samples/openapi3/client/petstore/python/pyproject.toml

Since the release of Poetry 2.0.0 the format of `pyproject.toml` that it is expecting changed.
See also: https://python-poetry.org/blog/announcing-poetry-2.0.0
This PR aims to update the pyproject.toml file to a format that does not use (now) deprecated features introduced by Poetry 1.
```
```  …

[python] Fix poetry deprecation warnings

---

bin/configs/python-aiohttp.yaml
samples/openapi3/client/petstore/python-aiohttp/pyproject.toml

Test poetry 1.x in python aiohttp client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/resources/3_0/allof_with_metadata_only_schemas.yaml
samples/client/petstore/rust/hyper/petstore/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/hyper/petstore/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/hyper0x/petstore/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/hyper0x/petstore/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/reqwest-trait/petstore/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/reqwest-trait/petstore/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/reqwest/petstore-async-middleware/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/reqwest/petstore-async-tokensource/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/reqwest/petstore-async-tokensource/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/reqwest/petstore-async/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/reqwest/petstore-async/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/reqwest/petstore-avoid-box/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/reqwest/petstore-avoid-box/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/reqwest/petstore-model-name-prefix/docs/FooTestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/reqwest/petstore-model-name-prefix/src/models/foo_test_all_of_with_multi_metadata_only.rs
samples/client/petstore/rust/reqwest/petstore/docs/TestAllOfWithMultiMetadataOnly.md
samples/client/petstore/rust/reqwest/petstore/src/models/test_all_of_with_multi_metadata_only.rs
samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
samples/client/petstore/typescript-axios/builds/composed-schemas/docs/Dog.md
samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/Dog.ts

- better handling of metadata in allOf by normalization/refactoring in normalizer
- add tests
```
```  …

Better handling of metadata in allOf

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/infrastructure/Bytes.kt.mustache
samples/client/petstore/kotlin-array-simple-string-multiplatform/build.gradle.kts
samples/client/petstore/kotlin-array-simple-string-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt
samples/client/petstore/kotlin-bigdecimal-default-multiplatform/build.gradle.kts
samples/client/petstore/kotlin-bigdecimal-default-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt
samples/client/petstore/kotlin-default-values-multiplatform/build.gradle.kts
samples/client/petstore/kotlin-default-values-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt
samples/client/petstore/kotlin-multiplatform-kotlinx-datetime/build.gradle.kts
samples/client/petstore/kotlin-multiplatform-kotlinx-datetime/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt
samples/client/petstore/kotlin-multiplatform/build.gradle.kts
samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/Bytes.kt

@dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier @e5l

[kotlin-client][multiplatform] update Kotlin and libraries versions

---

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/FormApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java

Fixes #21329 
```
``` 
@bbdouglas (2017/07) …

fix: #21329 Java Native, Provide Null Check before toString on param variables

---

modules/openapi-generator/src/main/resources/ruby-client/partial_anyof_module.mustache
modules/openapi-generator/src/main/resources/ruby-client/partial_oneof_module.mustache
samples/client/petstore/ruby-httpx/lib/petstore/models/mammal_anyof.rb
samples/client/petstore/ruby-httpx/lib/petstore/models/mammal_without_discriminator.rb
samples/client/petstore/ruby/lib/petstore/models/mammal_anyof.rb
samples/client/petstore/ruby/lib/petstore/models/mammal_without_discriminator.rb

Changes Date.parse to Date.iso8601 to fix incorrect type coercion in OneOf contexts. Previously, arbitrary strings matching Date.parse's lenient pattern (e.g., "ABC1") were incorrectly coerced to dates (2025-06-01), when they should have remained as strings.
For example:
- "ABC1" was parsed as Date(2025-06-01) instead of remaining "ABC1"
- This occurred because Date.parse treats the first char as month ('A'=1) and remaining digits as day
The fix ensures only ISO8601 formatted strings (e.g. "2025-06-02") are parsed as dates, improving type safety and preventing unexpected coercion of string values.
```
``` 
(For Windows users, please run the script in …

fix(ruby-client): fix incorrect Date parsing in OneOf

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java
modules/openapi-generator/src/main/resources/python-fastapi/api.mustache
samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api.py

Currently the default code of the Python FastAPI would be 200 when in reality it would be more suitable to keep it empty (or 0), as stated in #12481.
Here is the OpenAPI.yaml that was used as input:
https://github.com/OAI/OpenAPI-Specification/blob/aa91a19c43f8a12c02efa42d64794e396473f3b1/examples/v3.0/petstore-expanded.yaml#L51
Here is what it currently produces: 
```
responses={
200: {"model": Pet, "description": "pet response"},
200: {"model": Error, "description": "unexpected error"},
},
```
this is what it now produces:
```
responses={
200: {"model": Pet, "description": "pet response"},
"default": {"model": Error, "description": "unexpected error"},
},
```
```
./bin/utils/export_docs_generators.sh || …
```

fix(python-fastapi): remove 200 fallback code and use default (#12481)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
modules/openapi-generator/src/test/resources/3_0/enum_float.yaml

This is relevant for enums whose values are floats since without this step the enum is syntactically invalid.
See: https://github.com/OpenAPITools/openapi-generator/issues/21322
Sample output:
```py
class Type(int, Enum):
"""
Type
"""
"""
allowed enum values
"""
NUMBER_2_DOT_0 = 2.0
NUMBER_1_DOT_0 = 1.0
NUMBER_0_DOT_5 = 0.5
NUMBER_0_DOT_25 = 0.25
```
- Check out this branch
- Run `./mvnw package` to rebuild
- Then run this command to test against a spec that would've previously resulted in a syntax error:
```
-i modules/openapi-generator/src/test/resources/3_0/enum_float.yaml \
-g python \
-o /tmp/out/python
```
- Then:
```
python -m py_compile /tmp/out/python/openapi_client/models/type.py
```
- Ensure …

Replace periods with '_DOT_' in Python enum member names

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestSdkClientCodegen.java
modules/openapi-generator/src/test/resources/3_0/cpp-restsdk/petstore.yaml
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/CreateUserOrPet_request.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Pet.h
samples/client/petstore/cpp-restsdk/client/src/model/Pet.cpp

This fixes serialization and usage of Objects by wrapping it in shared_ptr. These methods all rely on the shared_ptr, and without it methods like `toJson`, `fromString`, etc. will fail to compile.
```
```  …

[cpp-restsdk] store Object as a shared pointer

---

modules/openapi-generator/src/main/resources/Java/libraries/vertx/apiImpl.mustache
samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/api/AnotherFakeApiImpl.java
samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/api/FakeApiImpl.java
samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/api/FakeClassnameTags123ApiImpl.java
samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/api/PetApiImpl.java
samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/api/StoreApiImpl.java
samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/api/UserApiImpl.java
samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/api/AnotherFakeApiImpl.java
samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/api/DefaultApiImpl.java
samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/api/FakeApiImpl.java
samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/api/FakeClassnameTags123ApiImpl.java
samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/api/PetApiImpl.java
samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/api/StoreApiImpl.java
samples/client/petstore/java/vertx-supportVertxFuture/src/main/java/org/openapitools/client/api/UserApiImpl.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/api/AnotherFakeApiImpl.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/api/DefaultApiImpl.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/api/FakeApiImpl.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/api/FakeClassnameTags123ApiImpl.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/api/PetApiImpl.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/api/StoreApiImpl.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/api/UserApiImpl.java

Fixes #21401 Java vertx path parameter white space encoding
```
```  …

[Java][vertx] fix path param encoding

---

modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache

This PR solves the problem described in #18660.
I made this fix locally and on my openapi the issue was fixed and no new issues were found.
For testing you can use the code from the Issue or use this:
```Json
{
"openapi": "3.1.0",
"info": {
"title": "Simple",
"version": "0.0.1"
},
"paths": {},
"components": {
"schemas": {
"TestEnum": {
"type": "string",
"enum": [
"",
"1",
"2"
],
"title": "TestEnum"
},
"TestItem": {
"properties": {
"test": {
"type": "integer",
"title": "test"
},
"testEmum": {
"$ref": "#/components/schemas/TestEnum",
"default": ""
}
},
"type": "object",
"required": [
"test"
],
"title": "TestItem"
}
}
},
"tags": []
}
```
@dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06) @e5l …

[kotlin] Fix compile error in enum properties with "" values(#18660)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustAxumServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/rust/RustAxumServerCodegenTest.java
modules/openapi-generator/src/test/resources/3_1/issue_21144.yaml

If tags are defined for an operation, the router path will be duplicated per tag. If a security schema is defined as well, the code will no longer compile because there will be duplicate operations with and without a claims parameter. Since there doesn't appear to be a benefit to specifying the same operation multiple times, this skips adding an operation if it already exists.
Fixes #21144 
```
``` 
These must …

[rust-axum] Prevent multiple declarations of the same operation

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaHttp4sServerCodegen.java
modules/openapi-generator/src/main/resources/scala-http4s-server/types.mustache

There is an example of correct openAPI specification:
```openapi: 3.0.0
info:
title: TestApi
version: latest
components:
schemas:
EnumType:
type: string
enum:
- Fix
- Max
paths:
/test/method:
post:
responses:
'200':
description: "success answer"
content:
schema:
type: object
required:
- constraint
properties:
constraint:
$ref: '#/components/schemas/EnumType'
```
For given OpenAPI specification generated not valid type for enum EnumType - empty case class:
```case class EnumType()```
I added enum handling for scala-http4s-server.
Trying to fix  https://github.com/OpenAPITools/openapi-generator/issues/9987 for scala-http4s-server.

[Scala] Add enums to scala-http4s-server

---

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/model-header.mustache
modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/model-source.mustache
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Color.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Order.h
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Pet.h
samples/client/petstore/cpp-restsdk/client/src/model/Color.cpp
samples/client/petstore/cpp-restsdk/client/src/model/Order.cpp
samples/client/petstore/cpp-restsdk/client/src/model/Pet.cpp

This fixes the issue with enum values being used instead of enum names. This is problematic when the values contain symbols that can't be a C++ variable. 
This also fixes compilation of enums on Windows for the string literals. 
It also simplifies the enum variables by removing the unnecessary prefix for scoped enum classes.
```
```  …

[cpp-rest-sdk] fix enum values being used instead of names

---

.github/workflows/samples-python-client-echo-api.yaml
.github/workflows/samples-python-petstore.yaml
modules/openapi-generator/src/main/resources/python/pyproject.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/pyproject.toml
samples/client/echo_api/python/pyproject.toml
samples/openapi3/client/petstore/python/pyproject.toml

Fixes: https://github.com/OpenAPITools/openapi-generator/issues/21335
```
```  …

[python] Validate pyproject.toml and fix the pyproject.toml version constraint format

---

bin/configs/typescript-echo-api.yaml
modules/openapi-generator/src/main/resources/typescript/api/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/TypeScriptClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/typescript/deprecated-operation.yaml
modules/openapi-generator/src/test/resources/3_0/typescript/deprecated-parameter.yaml
modules/openapi-generator/src/test/resources/3_0/typescript/echo_api.yaml
samples/client/echo_api/typescript/build/QueryApi.md
samples/client/echo_api/typescript/build/apis/QueryApi.ts
samples/client/echo_api/typescript/build/types/ObjectParamAPI.ts
samples/client/echo_api/typescript/build/types/ObservableAPI.ts
samples/client/echo_api/typescript/build/types/PromiseAPI.ts
samples/openapi3/client/petstore/typescript/builds/browser/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/default/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/deno/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/deno_object_params/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/explode-query/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/inversify/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/jquery/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/object_params/apis/PetApi.ts

PR to add `@deprecation` tags when endpoints or parameters are deprecated
```
```  …

[Typescript]: add deprecated tags

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRustCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/rust/AbstractRustCodegenTest.java
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/.openapi-generator/FILES
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/README.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/DollarSpecialLeftSquareBracketModelNameRightSquareBracket.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs

Fix issue where period-delimited model names (e.g. microsoft.graph.fido2AuthenticationMethod) were being converted to unwieldy names with "Period" substitutions. Now periods are replaced with underscores like hyphens, resulting in cleaner and more idiomatic Rust identifiers.
Fixes #15254 
```
``` 
You …

Replace periods with underscores in Rust model names

---

modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache

This reverts this PR https://github.com/OpenAPITools/openapi-generator/pull/21248 
```
```  …

Revert "[kotlin-client] Add support for integer enums in serialization for kotlin-client (#21248)"

---

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/AuthApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/BodyApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/FormApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/HeaderApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/PathApi.java
samples/client/echo_api/java/native/src/main/java/org/openapitools/client/api/QueryApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/DefaultApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native-jakarta/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/DefaultApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java

Fixes #21345 #19491
Include direct file download and byte array direct. This is self contained and semi based off Jersey3 version.
Filename from the response header is used if available else a random temp file is created instead.  Best effort is given for cleanup but the person getting the file should clean up first.
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache#L1129
This is tested on my override's for my work here:  https://github.com/qld-gov-au/kiteworks-integration/commit/d9a17209fa55c4a9bb743402e2a008441e0cc844 
```
``` 
(For Windows users, please run the …

fix: #21345 #19491 Java Native Client, handle Byte[] and File response types correctly

---

modules/openapi-generator/src/main/resources/rust/reqwest-trait/api.mustache
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/fake_api.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/store_api.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/testing_api.rs
samples/client/petstore/rust/reqwest-trait/petstore/src/apis/user_api.rs

The doc links for parameter and error structs in the `reqwest-trait` template were copied over from the `reqwest` template, but they are not valid as-is, as these functions are now part of a trait and not standalone functions. This means for them to work correctly in IDEs and docs you need to qualify them with the trait name.
For example, VSCode, shows the link with a different color and displays a preview of the function, plus clicking on the name would navigate to the function.
With this change:
Without this change:
I've also removed the trailing whitespace from the template file, let me know if you prefer that to be reverted and split into a separate PR.
Tagging openapi-generator Rust committee, like the checklist mentions: @frol @farcaller @richardwhiuk @paladinzh @jacob-pro
``` …
```

Qualify rust trait template comments

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
samples/openapi3/server/petstore/spring-boot-oneof-sealed/src/main/java/org/openapitools/model/Fruit.java

Changes so that the DefaultCodegenTest uses one test engine rather than each test using one of the two present in the project (junit and testng). This removes most warnings in the file that are not tied to a `Raw use of parameterized class Schema` warning.
These are fixes that I have done as part of an investigation into how to best extend `useOneOfInterfaces` to generated sealed interfaces. But since that might take a while I thought I might as well merge fixes that can be separated from that functionality.
Includes fix for samples that were not updated with [this change](https://github.com/OpenAPITools/openapi-generator/commit/3ef45f1b4d505c9479e40db87a59e9b8a458714b).
``` …
```

DefaultCodegenTest use same test engine for all tests

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppOatppServerCodegen.java

a follow up pr to https://github.com/OpenAPITools/openapi-generator/pull/21547/
```
```  …

[cpp-oatpp-server generator] update copyright, minor code formatting change

---

docs/generators/java-microprofile.md
docs/generators/java.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api.mustache
modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api_exception_mapper.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/microprofile/JavaMicroprofileServerCodegenTest.java

This PR fixes issue https://github.com/OpenAPITools/openapi-generator/issues/20751 made by @Munken 
It is made configurable whether generated Microprofile API clients should RegisterProvider ApiExceptionMapper.
It is also made configurable whether ApiExceptionMapper should be annotated with @Provider, making it a global exception mapper.
Both properties default to true in order to make this a non-breaking change.
```
``` 
These must …

[java][Microprofile] add config options to disable usage of ApiExceptionMapper

---

modules/openapi-generator/src/main/resources/JavaSpring/apiDelegate.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
modules/openapi-generator/src/test/resources/3_1/issue_21156.yaml

Added import, because also delegate can contain method implementation that uses AtomicInteger. This is fix for #21566 
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @martin-mfg
```
```  …

Conditional import of AtomicInteger added to delegate template

---

modules/openapi-generator/src/main/resources/JavaSpring/converter.mustache
samples/openapi3/server/petstore/spring-boot-oneof-sealed/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/openapi3/server/petstore/springboot-delegate/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/openapi3/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/spring-boot-defaultInterface-unhandledException/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-beanvalidation-no-nullable/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-beanvalidation/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-builtin-validation/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-delegate/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-reactive-noResponseEntity/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-spring-pageable-delegatePattern/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-spring-pageable-without-j8/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-spring-pageable/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot-virtualan/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java
samples/server/petstore/springboot/src/main/java/org/openapitools/configuration/EnumConverterConfiguration.java

This PR updates the mustache file used to create the EnumConverterConfiguration class for the Java Spring server generator, which is used when an OpenAPI spec contains an enum class.
The PR is a follow-up from code review feedback on [a similar PR](https://github.com/OpenAPITools/openapi-generator/pull/21579#discussion_r2217756798) in the Kotlin Spring server generator.
```
```  …

[Java-Spring] add comment to EnumConverterConfiguration mustache file

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java

Converts existing code into recursive code to better handle nested maps. First of a few PRs to fix issues pointed out by https://github.com/OpenAPITools/openapi-generator/issues/21585 I don't think sample changes are necessary since its only making existing code recursive.
```
```  …

[csharp] Handle nested maps recursively

---

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorValidateExtension.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/ValidateTask.kt
modules/openapi-generator-gradle-plugin/src/test/kotlin/ValidateTaskDslTest.kt

This PR adds a new treatWarningsAsErrors setting to the validation task.
If set to true, the task will fail when warnings are found—helpful for keeping specs clean and catching issues early.
By default, it's off to keep things backward-compatible :)

[gradle-plugin] add treatWarningsAsErrors option to openApiValidate in gradle plugin

---

modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator-maven-plugin/src/test/java/org/openapitools/codegen/plugin/CodeGenMojoTest.java
modules/openapi-generator-maven-plugin/src/test/resources/default/pom.xml

Fixes #19724 
[BUG] openapi-generator-maven-plugin 7.7.0 or 7.8.0 on Windows
The issue was originally introduced in PR #18576
Due to the changed If statement in [CodeGenMojo.java](https://github.com/OpenAPITools/openapi-generator/compare/master...Hobbesgoblin:openapi-generator:bugfix-for-remote-specs-with-params?expand=1#diff-233dcd5306a0a0c4760a7b5bd4b2e58ef35d90b2cb370f1bb8ce1c6b0c723687) the code in the block would never be entered for remote URLs, resulting in any parameters being part of the hashFileName.
The result of this was that the special characters would make the code generation fail on Windows (as the hashfile would never be saved, resulting in a `FileNotFoundException`) as well as leaking potentially sensitve inrformation, like parameter submitted access tokens, in the log …

Bugfix for remote specs with params

---

.github/workflows/samples-php-client.yaml
modules/openapi-generator/src/test/resources/3_0/php-nextgen/petstore-with-fake-endpoints-models-for-testing.yaml
modules/openapi-generator/src/test/resources/3_0/php/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/petstore/php-nextgen/OpenAPIClient-php/docs/Api/PetApi.md
samples/client/petstore/php-nextgen/OpenAPIClient-php/src/Api/PetApi.php
samples/client/petstore/php/OpenAPIClient-php/docs/Api/PetApi.md
samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
samples/client/petstore/php/OpenAPIClient-php/tests/AsyncTest.php
samples/client/petstore/php/OpenAPIClient-php/tests/DebugTest.php
samples/client/petstore/php/OpenAPIClient-php/tests/PetApiTest.php
samples/client/petstore/php/OpenAPIClient-php/tests/ServerVariablesInOperationTest.php
samples/client/petstore/php/psr-18/lib/Api/PetApi.php

- added php client tests in Github workflows
- tested with build failure
- updated tests
cc 
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon 
```
```  …

Test PHP clients in Github workflow

---

modules/openapi-generator/src/main/resources/php/libraries/psr-18/api.mustache
samples/client/petstore/php/psr-18/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/psr-18/lib/Api/DefaultApi.php
samples/client/petstore/php/psr-18/lib/Api/FakeApi.php
samples/client/petstore/php/psr-18/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/psr-18/lib/Api/PetApi.php
samples/client/petstore/php/psr-18/lib/Api/StoreApi.php
samples/client/petstore/php/psr-18/lib/Api/UserApi.php

The PSR-18 version of the `api.mustache` template uses the wrong constructor for `ApiException` in two places. It uses the constructor of the normal PHP generated (non-PSR18).
```
```  …

fix: Use correct constructor for ApiException in PSR-18 PHP library

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/typescript-fetch/issue_21587.yaml
modules/openapi-generator/src/test/resources/bugs/issue_21259.yaml

Closes #21587
The typescript-fetch client generator has a bug when generating model code where the list of imports will be missing items if the OAS spec includes a schema a `oneOf` section and the `oneOf` schema has `additionalProperties: true`. 
An example OAS would be 
```yaml
openapi: 3.0.1
info:
title: Example API
version: 1.0.0
paths:
/api/endpoint:
get:
operationId: GetEndpoint
responses:
'200':
description: Successful Response
content:
schema:
type: object
title: OneOfResponse
oneOf:
- $ref: '#/components/schemas/OptionOne'
- $ref: '#/components/schemas/OptionTwo'
components:
schemas:
OptionOne:
type: object
title: OptionOne
properties:
propOne:
type: number
additionalProperties: true
OptionTwo:
type: object
title: OptionTwo
properties:
propTwo:
type: string
``` …

[Bug][typescript-fetch] Typescript fetch one of addtl props imports

---

modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache
samples/client/others/c/bearerAuth/include/apiClient.h
samples/client/others/c/bearerAuth/src/apiClient.c
samples/client/petstore/c-useJsonUnformatted/include/apiClient.h
samples/client/petstore/c-useJsonUnformatted/src/apiClient.c
samples/client/petstore/c/include/apiClient.h
samples/client/petstore/c/src/apiClient.c
samples/client/petstore/c/unit-tests/manual-PetAPI.c

Hello,
As proposed in my previous PR (https://github.com/OpenAPITools/openapi-generator/pull/21613#issuecomment-3113483836), I've implemented a callback just before the `curl_easy_perform(handle)`.
In this way programmers have a way to modify the curl handler as they want without limits.
I've tested it using `manual-PetAPI.c` unit-test.
Best,
hirish
C Committee: @zhemant (2018/11) @ityuhui (2019/12) @michelealbano (2020/03) @eafer (2024/12)
Also @wing328 
```
``` 
This is important, as CI jobs will verify _all_ generator outputs …

add curl handler pre-invoke-callback to c-libcurl

---

modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache
samples/client/others/c/bearerAuth/CMakeLists.txt
samples/client/petstore/c-useJsonUnformatted/CMakeLists.txt
samples/client/petstore/c/CMakeLists.txt

feature: Add control flag for static compile

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache
samples/client/petstore/typescript-fetch/builds/oneOf/models/TestDiscriminatorResponse.ts

Closes #21668 
@ThorinEk reported a problem in [the discussion of Issue 21587](https://github.com/OpenAPITools/openapi-generator/issues/21587#issuecomment-3110136876) that relates to the default case in the switch statement generated for a oneOf model when the model has a discriminator.
```typescript
export function ExecuteCommandPostRequestToJSONTyped(value?: ExecuteCommandPostRequest | null, ignoreDiscriminator: boolean = false): any {
if (value == null) {
return value;
}
switch (value['command']) {
...  // removed
default:
// this should be return value since the variable json is undefined.
return json;
}
}
```
It looks like this bug was introduced in the PR for #20983
I did not implement a unit test for this bug because the typescript unit tests are asserting on the failure to match …

[BUG][typescript-fetch] Default case for oneOf serialization method returning undefined variable.

---

modules/openapi-generator/src/main/resources/php-laravel/api_controller.mustache

@ybelenko Mentioning you here as I needed to mention the relevant tech committee. as per the PR description template
I have removed the try/catch block from the controller logic in the php-laravel server generator. The reason for that is because the try/catch block is not extendable and returns a nonstandard and non-customizable response.
By removing the try/catch block we allow Laravel to pick up and handle the error. We also allow users of the generator to add their custom generator logic.
This should fix #21109 . Got no response so am now trying this route.
```
``` 
(For Windows users, please run the script in …

Removed try/catch to enable framework error handling to pick up error

---

modules/openapi-generator/src/main/resources/scala-sttp/paramCreation.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/scala/SttpCodegenTest.java
modules/openapi-generator/src/test/resources/bugs/issue_21602.yaml
samples/client/petstore/scala-sttp-circe/src/main/scala/org/openapitools/client/api/PetApi.scala
samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/PetApi.scala

fixes #21602
Marked as a draft while attempting to find a proper solution for how to handle required header parameters that are complex (i.e., the header contains a `ref` rather than a `string`).
```
paths:
/ping:
get:
summary: Ping with required header
operationId: getPing
parameters:
- name: X-Required-Schema-Header
in: header
required: true
schema:
$ref: '#/components/schemas/UUID'
components:
schemas:
UUID:
type: object
properties:
uuid:
type: string
```
```
```  …

[Scala sttp] Fix header serialization for Optional values

---

modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache
samples/client/echo_api/java/restclient/src/main/java/org/openapitools/client/api/QueryApi.java
samples/client/echo_api/typescript/build/models/ObjectSerializer.ts
samples/client/others/typescript/builds/array-of-lists/models/ObjectSerializer.ts
samples/client/others/typescript/builds/enum-single-value/models/ObjectSerializer.ts
samples/client/others/typescript/builds/null-types-simple/models/ObjectSerializer.ts
samples/client/others/typescript/builds/with-unique-items/models/ObjectSerializer.ts
samples/client/others/typescript/encode-decode/build/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/browser/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/default/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/deno/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/deno_object_params/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/explode-query/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/inversify/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/jquery/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/nullable-enum/models/ObjectSerializer.ts
samples/openapi3/client/petstore/typescript/builds/object_params/models/ObjectSerializer.ts

fixes https://github.com/kubernetes-client/javascript/issues/2189
-  Similar to PR #17514, which fixed the same issue in the typescript-node generator.
-  This PR targets the typescript/typescript-fetch generators instead. Projects like kubernetes-client/javascript use typescript-fetch, not typescript-node, so they are still affected.
```
``` 
You may …

fix(typescript): add Date instance check before date formatting

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/anyof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/oneof_model.mustache

relates to OpenAPITools/openapi-generator#16868
---
I found out that the same thing described in #16868 also happens for one of schemas. Here's an example with both, one of and any of.
```yaml
openapi: 3.1.0
info:
version: 0.1.0
title: ''
description: ''
paths:
/foo/:
post:
operationId: foo
requestBody:
content:
schema:
$ref: '#/components/schemas/OneOfExample'
required: true
responses:
'200':
content:
schema:
type: string
description: ''
/bar/:
post:
operationId: bar
requestBody:
content:
schema:
$ref: '#/components/schemas/AnyOfExample'
required: true
responses:
'200':
content:
schema:
type: string
description: ''
components:
schemas:
OneOfExample:
oneOf:
- type: string
format: uuid
- type: string
enum:
- delete …
```

fix(java): validation of UUIDs in oneOf and anyOf schemas

---

modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml
samples/client/petstore/java/okhttp-gson/api/openapi.yaml
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Scalar.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ScalarAnyOf.java

a follow up pr to https://github.com/OpenAPITools/openapi-generator/pull/21747
```
```  …

Add tests for uuid in oneOf/anyOf (java okhttp-gson)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java

Utilizes the Codegen parsing introduced in https://github.com/OpenAPITools/openapi-generator/pull/18935 to get rid of warnings for incorrectly set `additionalProperties` when they are not set rather than incorrectly set.
I.e., the client was getting `The value (generator's option) must be either boolean or string. Default to "false".` for `useRxJS` when generating a client, even though they had not even stated a value for it.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it …

[Typescript] Fix warning logs for additional properties that have not been set

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent/openapi_client/api_client.py
samples/client/echo_api/python/openapi_client/api_client.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api/fake_api.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/api_client.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/format_test.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/mixed_properties_and_additional_properties_class.py
samples/openapi3/client/petstore/python-aiohttp/petstore_api/models/task.py
samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/models/format_test.py
samples/openapi3/client/petstore/python/petstore_api/models/mixed_properties_and_additional_properties_class.py
samples/openapi3/client/petstore/python/petstore_api/models/task.py

This PR will change the Python type hint for uuid fields from `StrictStr` to `uuid.UUID`.
Solves #19485. 
I essentially just copied the changes suggested by @to-bee in this comment: https://github.com/OpenAPITools/openapi-generator/issues/19485#issuecomment-2569940124 .
Since this will be a breaking change, should it be hidden behind some flag or option? I opened the pull request against the 8.0.x branch, please change this if it is wrong.
@cbornet @tomplus @krjakbrjak @fa0311 @multani
```
```  …

Use Python uuid.UUID instead of StrictStr

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_0/simplifyOneOfAnyOf_test.yaml

Fixes #21732.
I have added so that it keeps ReadOnly and WriteOnly, but it might be that one should even run [copyMetadata](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java#L2362)?
```
```  …

Fix so that the normalizer retains the read/write only attribute

---

modules/openapi-generator/src/main/resources/typescript-axios/modelGeneric.mustache
samples/client/echo_api/typescript-axios/build/api.ts
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces-and-with-single-request-param/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-node-imports/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/order.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/pet.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/user.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
samples/client/petstore/typescript-axios/builds/with-string-enums/api.ts

followup to #21776, where i've accidently removed whitespace in the PR. this change now properly aligns whitespace, and also simplifies mustache template for `@deprecated`.
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka @joscha
```
```  …

[typescript-axios]: align jsdoc for `@deprecated`

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java

Fixes #21729 - memory leak in Apache HttpClient when the result (status code and headers) were stored under the thread id. In a setup when virtual thread executor is used, each execution uses a different thread, and so the map grows without limit.
The fix replaces ConcurrentHashMap with ThreadLocal, which should assure that once the Thread ends, the result is deallocated. It solution should be as thread-safe as before.
@wing328 - you reviewed the PR adding the memory leak, would you care to take a look at this fix?
```
``` 
This …

[Java][HttpClient] Fix memory leak with virtual threads (#21729)

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/MergedSpecBuilder.java

`MergedSpecBuilder` never passed the `auth` configuration parameter to the underlying `RemoteUrl` unlike the `inputSpec`.
This PR fixes the issue.
No tests were effected.
I testet it manually since I need this feature 😊
```
```  …

Fix MergedSpecBuilder not passing auth

---

modules/openapi-generator/src/main/resources/Java/libraries/restclient/ApiClient.mustache
samples/client/petstore/java/restclient-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-useSingleRequestParameter-static/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient-useSingleRequestParameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/restclient/src/main/java/org/openapitools/client/ApiClient.java

This fixes #20370 by adding a method that allows client to specify a supplier of access tokens to the ApiClient generated by the RestClient library for Spring. Very similar to a previous PR https://github.com/OpenAPITools/openapi-generator/pull/19002 
@cachescrubber (2022/02) 
@welshm (2022/02) 
@MelleD (2022/02) 
@atextor (2022/02) 
@manedev79 (2022/02) 
@javisst (2022/02) 
@borsch (2022/02) 
@banlevente (2022/02) 
@Zomzog (2022/09) 
@martin-mfg (2023/08)
```
``` 
This is important, as CI jobs will verify _all_ generator outputs …

[REQ] [Java] [Spring] Fix #20370 by adding an OAuth access token supplier

---

docs/generators/dart-dio.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/resources/dart/libraries/dio/pubspec.mustache
modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/class.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/DartDioClientOptionsProvider.java

to close https://github.com/OpenAPITools/openapi-generator/issues/21815
related: 
https://github.com/OpenAPITools/openapi-generator/pull/21667
https://github.com/OpenAPITools/openapi-generator/issues/21665
tested locally to confirm the fix
will add more tests as part of the work later to revamp testing for dart generators
cc 
```
```  …

Add skipCopyWith option for dart-dio

---

modules/openapi-generator/src/main/resources/scala-http4s/baseClient.mustache
samples/client/petstore/scala-http4s/src/main/scala/org/openapitools/client/apis/BaseClient.scala

The code for setting the form body parameters were wrong,
e.g. the key value pair (id, 12345) would be encoded as id=%28id%2C12345%29
This commit adds a fix to the base client to correctly setting formBody values the previous pair will now be encoded as
id=12345
@clasnake (2017/07), @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04) @fish86 (2023/06)
```
``` 
These must match …

[BUGFIX] scala-http4s fix bad encoding of form-urlencoded body in baseClient.mustache

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
samples/client/petstore/rust/reqwest/petstore-async-middleware/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-async-tokensource/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-async-tokensource/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-async/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-avoid-box/Cargo.toml
samples/client/petstore/rust/reqwest/petstore-avoid-box/src/apis/pet_api.rs

In a previous PR ([[Rust ]Add async file stream support for reqwest client](https://github.com/OpenAPITools/openapi-generator/pull/21771)): the `useAsyncFileStream` and `vendorExtensions.useAsyncFileStream` template variables are used in case there's at least one file uploaded in the body, but they are set as long as `supportAsync` is set and **any** parameter is a file (including if the file is in a form). So these variables are set more often than they should, introducing unused dependencies on `tokio`.
This explains why on `master`, these tests have the `tokio` dependency even though they don't use it:
- [samples/client/petstore/rust/reqwest/petstore-async-tokensource/Cargo.toml](https://github.com/OpenAPITools/openapi-generator/blob/bd0b81d26dcbbf104186e2c7630abe4ebc429c7e/samples/clie …

[rust] set useAsyncFileStream only for files in the body

---

docs/faq-generators.md
docs/generators.md
docs/generators/swift6.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift6ClientCodegen.java

Make Swift 6 generator stable
```
``` 
@jgavris …

[Swift6][client]Make Swift 6 generator stable

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/anyof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey3/anyof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/anyof_model.mustache
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/GmFruit.java
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/model/MammalAnyof.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/GmFruit.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/GmFruit.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/GmFruit.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/MammalAnyof.java

The generators for Java clients `jersey2`, `jersey3`, and `native` are unnecessarily using a `String.format()` call when throwing an `IOException`.
```
```  …

[Java] Remove unnecessary String.format from jersey2, jersey3, native

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/main/resources/rust-server/models.mustache
modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
samples/server/petstore/rust-server-deprecated/output/openapi-v3/api/openapi.yaml
samples/server/petstore/rust-server-deprecated/output/openapi-v3/docs/ObjectParam.md
samples/server/petstore/rust-server-deprecated/output/openapi-v3/src/models.rs
samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
samples/server/petstore/rust-server/output/openapi-v3/docs/ObjectParam.md
samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs

fixes #21805 
rust-server compilation failed with large maximums. Resolved by handling minimum and maximum using BigInt instead of longValue.
Tested by updating and regenerating samples and validating that the updated example compiles. 
```
```  …

Resolve large int overflow, issue21805 

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java

We encountered occassional build failures with the logic introduced in https://github.com/OpenAPITools/openapi-generator/pull/21531 due to discriminator properties still being generated in rare cases.
Not sure why it didn't happen consistently, may be related to Gradle caching or parallel builds or whatever.
Since patching these string comparisons, this has no longer occurred.
```
```  …

[kotlin-client] Fix string comparison in discriminator post-processing

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache
samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/apis/PetApi.kt

This adds the missing `@Serializable` annotation when using the `kotlin` generator with `serializationLibrary=kotlinx_serialization` and `library=jvm-retrofit2`.
Currently, the generated enum classes add `@SerialName` to each child of the enum, but these annotations do not work because `@Serializable` is missing from the enum class. This can be seen in [the docs here](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#serial-names-of-enum-entries). As a result, currently a setup like this to control ascending/descending sort order
```
enum class SortOrder(val value: String) {
@SerialName(value = "-name") _NAME("-name"),
@SerialName(value = "name") NAME("name"),
}
```
is serialized as `"_NAME"` and `"NAME"`, rather than the expected `"-name"` and `"name"`. …

Fix missing `@Serializable` on enums for kotlin/jvm-retrofit2

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
modules/openapi-generator/src/main/resources/rust/model.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/rust/RustClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/rust/rust-anyof-test.yaml

Fixes #21894 - Add support for `anyOf` schemas in the Rust client generator by treating them similarly to `oneOf` schemas when no discriminator is present.
- Modified `RustClientCodegen.java` to process `anyOf` schemas similar to `oneOf`
- Fixed template closing tag issue in `model.mustache` that prevented anyOf schemas from generating enums
- Added comprehensive test case `testAnyOfSupport()` to verify the fix
- Maintained multi-line formatting for `#[serde(untagged)]` attribute (separate line from `pub enum`)
- Updated test assertions to use two separate checks for better consistency with codebase patterns
- Ensures generated Rust code maintains consistent formatting with existing samples
The Rust generator already converts `anyOf` to `oneOf` internally for processing, but the template …

fix(rust): Add anyOf support to Rust client generator

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/echo_api/java/okhttp-gson-user-defined-templates/src/main/java/org/openapitools/client/ApiClient.java
samples/client/echo_api/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-oneOf-array/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-oneOf/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-3.1-duplicated-operationid/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-3.1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-awsv4signature/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-nullable-required/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-swagger2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @martin-mfg
```
```  …

java-client: fix some javadoc comments

---

modules/openapi-generator-gradle-plugin/build.gradle
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GeneratorsTask.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/ValidateTask.kt

Gradle's task input and output annotations should be applied to the accessors instead of the properties. Not adhering to this can cause funky behavior in the generated stubs. Examples of this can be found in the docs: https://docs.gradle.org/current/userguide/implementing_custom_tasks.html
Also adds missing annotations so that stricter validation passes.
```
```  …

Correctly annotate Gradle task in- & outputs and enable stricter plugin validation

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java

- [V] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [V] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [V] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
``` 
This is important, as CI jobs will verify …

[BUG][JAVA] RestTemplate uses hardcoded User-Agent Java-SDK #21972

---

.github/workflows/samples-powershell.yaml
appveyor.yml
modules/openapi-generator/src/test/resources/3_0/powershell/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
samples/client/petstore/powershell/.openapi-generator-ignore
samples/client/petstore/powershell/README.md
samples/client/petstore/powershell/docs/PSAnotherFakeApi.md
samples/client/petstore/powershell/docs/PSDefaultApi.md
samples/client/petstore/powershell/docs/PSFakeApi.md
samples/client/petstore/powershell/docs/PSFakeClassnameTags123Api.md
samples/client/petstore/powershell/docs/PSPetApi.md
samples/client/petstore/powershell/docs/PSStoreApi.md
samples/client/petstore/powershell/docs/PSUserApi.md
samples/client/petstore/powershell/src/PSPetstore/Client/PSConfiguration.ps1
samples/client/petstore/powershell/tests/Petstore.Tests.ps1

- add github workflow to test powershell petstore client
- remove powershell tests in appveyor
```
```  …

Add workflow for PowerShell clients

---

modules/openapi-generator/src/main/resources/Java/oneof_interface.mustache
modules/openapi-generator/src/main/resources/JavaSpring/oneof_interface.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/java/oneOf-with-annotations.yaml

Fix #20110
Allow annotations on interfaces generated for oneOfs
Main goal is to customize the serialization/deserialization.
For example with jackson:
```
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(...)
interface Animal {
}
```
```
```  …

[JAVA] Add vendorExtensions.x-class-extra-annotation to oneOf interfaces

---

modules/openapi-generator/src/main/resources/typescript-fetch/package.mustache
samples/client/petstore/typescript-fetch/builds/es6-target/package.json
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/package.json
samples/client/petstore/typescript-fetch/builds/sagas-and-records/package.json
samples/client/petstore/typescript-fetch/builds/with-npm-version/package.json
samples/client/petstore/typescript-fetch/builds/without-runtime-checks/package.json

Replaces deprecated `"typings"` field with `"types"` in `package.json`.
Without this fix, some IDEs (e.g., VS Code) fail to resolve type definitions correctly when using this package, due to `"typings"` being ignored in favor of the standard `"types"` field.

replace deprecated 'typings' field with standard 'types' in package.json

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
modules/openapi-generator/src/main/resources/go-server/controller-api.mustache

Previous mustache template was using #isBodyParam outside of #operation
context, so it was not effective.
Even if we'd add the proper context, we'd then risk generating duplicate
imports for multiple matching parameters.
For this reason, this patch implements detection of an optional body
parameter in code, making sure the corresponding import is added just
once.
Fixes #19237
```
```  …

go: Fix missing imports for optional body params.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/OpenAPINormalizerTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_1/null_schema_test.yaml
modules/openapi-generator/src/test/resources/3_1/simplifyOneOfAnyOf_test.yaml

- Fix additional properties handling in 3.1 spec preventing a schema with additional properties set to false from processing correctly in the normalizer
- Add tests
```
``` 
IMPORTANT: Do …

Fix additional properties handling in 3.1 spec
