OpenAPITools/openapi-generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Replacing it with `camelize` and will completely remove it in 4.x release

Deprecated initialCaps

---

modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache

Adding support for generating code related to authentication methods (basic, oauth and api-key).
Added error printing in case of the server is not available(curl perform failed).
Make apiClient object reusable(url, authentication are not freed and have to be freed manually)  (dataReceived in apiclient will still be freed. As it is not necessay outside the API function).

[C] Support for authentication methods

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java

- replace forward slash with underscore (e.g. /me/videos_privacy => _me_video_privacy) to fix the class name (e.g. MeVideosPrivacy vs MevideosPrivacy)
- minor fix to model prefix/suffix in Java models

Fix inline resolver in handling forward slash

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java

- Better support for composed schema (allOf)
- Fix discriminator's name with `toModelName`
- whitelist "object" as a special word in Java generators

Better support for composed schema (allOf)

---

modules/openapi-generator/src/main/resources/dart/api.mustache
modules/openapi-generator/src/main/resources/dart/api_helper.mustache
modules/openapi-generator/src/main/resources/dart2/api.mustache
modules/openapi-generator/src/main/resources/dart2/api_helper.mustache

- dart is not exists.
- @ircecho, @swipesight, @jaumard
The original processing is using `response.body` to deserialize as json in `api.mustache`.
However, this is decoded by latin1 if the header contains only `application/json` instead of `application/json; charset=utf-8`.
Because of this behavior, if the response body is encoded UTF-8 but the headers doesn't contain charset, the body will garbling.
cf: https://github.com/dart-lang/http/issues/175
Since playframework 2.6 returns `Content-Type: application/json` without `charset=utf-8`, I changed this parsing algolithm.

fix: force to decode as utf-8 when header contains application/json to avoid text garbling.

---

modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirequest.cpp.mustache

Fix typo reported here 
https://github.com/OpenAPITools/openapi-generator/issues/1708#issuecomment-452095269
> Found a typo in one of the cpp-qt5-qhttpengine-server .mustache files. Specifically, the file 'apirequest.cpp.mustache', line 80 -- there is an extra '(' after the '::fromStringValue' (i.e. line should be ... ::fromStringValue(QString ... ). You want me to create a separate issue?
Thanks to @dtucker61 for reporting.
@stkrwork @fvarose @MartinDelille @ravinikam

[C++] [Qt5] Fix typo in Qt5 Server template

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/resources/Java/modelEnum.mustache
modules/openapi-generator/src/main/resources/Java/modelInnerEnum.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java

See #1693, support added for java-client and jersey server.

[core] Support for "x-enum-descriptions" 

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/OAuthOkHttpClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/RetryingOAuth.mustache

@wing328 (author of #1838).
Java tech committee @bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
Follow up from of PR #1838:
The `org.apache.oltu.oauth2:org.apache.oltu.oauth2.client` is now only included if `hasOAuthMethods` is true. See:
This means that when a spec do not use OAuth, the generated code should not use any of the classes provided by the dependency. Otherwise maven build for the generated lib looks like this:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] <java-okhttp-gson project>/src/main/java/...../okhttpgson/auth/RetryingOAuth.java:[10,37] package …
```

[java-client][okhttp-gson] no oauth2 usage when hasOAuthMethods is false

---

modules/openapi-generator-gradle-plugin/README.adoc
modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt

Adds missing options supported by codegenConfigurator for consistency with maven plugin (see #1845)
Also includes documentation for a workaround found to address #1818.

[gradle] Add 4 boolean properties supported by codegenConfigurator

---

modules/openapi-generator/src/main/resources/python/api_doc_example.mustache
modules/openapi-generator/src/main/resources/python/common_README.mustache

- [-] Ran the shell script under `./bin/` to update Petstore sample ... _only a doc change_
Python technical committee: @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10)
APIs may have more than one auth method (for example both an app key and basic auth).
This changes the example to only initialize the config option once instead of once per auth method.

Python: Update api_doc_example for multiple auth

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java

`RubyClientCodegen` and `CLibcurlClientCodegen` are overriding [DefaultCodegen.shouldOverwrite()](https://github.com/OpenAPITools/openapi-generator/blob/470fc2065dd5ab3392b1a4d317af3f33cb26cd75/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L3705-L3707) but these implementations are same as the parent one. 👀

Minor fixes: remove unnecessary override

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java
modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml

Thanks @shiyumi-sarashino , who suggests this enhancement. ✨

Add primitive types support to ExampleGenerator

---

docs/migration-from-swagger-codegen.md

This is a fix for a small spelling error in a document. Hope it helps.

Fixed a small typo

---

modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
samples/client/petstore-security-test/typescript-node/api/fakeApi.ts
samples/client/petstore/typescript-node/default/api/petApi.ts
samples/client/petstore/typescript-node/default/api/storeApi.ts
samples/client/petstore/typescript-node/default/api/userApi.ts
samples/client/petstore/typescript-node/npm/api/petApi.ts
samples/client/petstore/typescript-node/npm/api/storeApi.ts
samples/client/petstore/typescript-node/npm/api/userApi.ts

This approach is inspired by the typescript-fetch implementation in swagger-codegen.
Fixes #1867

[TypeScript-Node] support setting the content-type header per-call

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java

[TS][Angular] fixing wrong model file suffix when identical with model suffix

---

modules/openapi-generator/src/main/resources/Java/libraries/resteasy/pom.mustache
samples/client/petstore/java/resteasy/pom.xml

- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
Now the sections scm, license and developer are not ignored when using the generator java and the library restesy.

SCM and license parameters are now also for resteasy clients available.

---

modules/openapi-generator/src/main/resources/JavaJaxRS/enumClass.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/enumOuterClass.mustache

@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
Generate javadoc for enum (based on `x-enum-descriptions`) for JaxRS, see #1693 for more details.
Tested with:
```yaml
weather:
type: object
properties:
type:
type: integer
format: int32
enum:
- 1
- 2
- 3
x-enum-descriptions:
- 'Blue sky'
- 'Slightly overcast'
- 'Take an umbrella with you'
x-enum-varnames:
- Sunny
- Cloudy
- Rainy
```
Produces:
```diff
--- a/Weather.java
+++ b/Weather.java
@@ -31,10 +31,19 @@
* Gets or Sets type
*/
public enum TypeEnum {
+    /**
+     * Blue sky
+     */
Sunny(1),
+    /**
+     * Slightly overcast
+     */
Cloudy(2),
+    /**
+     * Take an umbrella with you
+     */
Rainy(3);
private Integer value;
```

[java-jaxrs] Add Javadoc to enum (x-enum-descriptions)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java

Attempts to fix issue https://github.com/OpenAPITools/openapi-generator/issues/1944
After these changes the code generator adds the `N` prefix to the enum names as expected.
@cliffano @zlx

Fix Ruby invalid enum generation for numeric enums

---

docs/migration-from-swagger-codegen.md

Add migration note about the change in basePath from `https://localhost` to `http://locallhost` (http without s)
cc @tomplus

Add migration note about change in basePath

---

modules/openapi-generator/src/main/resources/php/Configuration.mustache
samples/client/petstore/php/OpenAPIClient-php/lib/Configuration.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Configuration.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/tests/ConfigurationTest.php

- allows the PHP API client to retrieve all server URLs defined in the spec
Ref: https://github.com/OpenAPITools/openapi-generator/pull/1280 for Ruby client
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) , @ybelenko (2018/07), @renepardon (2018/12)

Add multiple servers support to PHP client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/okhttp-gson/pom.xml

Use customized source folder in build config when provided.

Fix customized source folder in Java client

---

modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
samples/client/petstore/ruby/lib/petstore/configuration.rb
samples/openapi3/client/petstore/ruby/lib/petstore/configuration.rb
samples/openapi3/client/petstore/ruby/spec/configuration_spec.rb

- fixed index check for multiple server settings in Ruby client
- added a test case to cover the issue moving forward
cc @cliffano (2017/07) @zlx (2017/09)

Fix index check in Ruby client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ProcessUtils.java
modules/openapi-generator/src/main/resources/Java/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/retrofit/src/main/java/org/openapitools/client/ApiClient.java

Generate OAuth related files only if OAuth security schema is used

[Java] Generate OAuth related files only if OAuth security schema is used

---

docs/templating.md

Document 'x-enum-descriptions' and 'x-enum-varnames'

---

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/apiclient-header.mustache
samples/client/petstore/cpp-restsdk/ApiClient.h

Fixes #561
Before this change, the following OpenAPI path would cause a compilation failure in the generated C++ code. Specifically, the `format: "uuid"` was problematic, as it cause the underlying implementation to wrap the string in a `std::shared_ptr<>`.
```yaml
paths:
"/foo/{id}":
get:
summary: "Get a specific Fooby ID"
operationId: "getFoo"
parameters:
- name: "id"
in: "path"
description: "The UUID of the referenced object"
required: true
type: "string"
format: "uuid"
```
Yields:
```cpp
FooApi.cpp: In member function 'virtual pplx::task<std::shared_ptr<Foo> > FooApi::getFoo(std::shared_ptr<std::basic_string<char> >)':
FooApi.cpp:330:184: error: no matching function for call to 'ApiClient::parameterToString(std::shared_ptr<std::basic_string<char> >&)'
boost::replace_all(path, …
```

[C++][Client][C++ Rest SDK] Fix path parameters with format

---

scripts/openapi-generator-cli-completion.bash

Homebrew installs openapi-generator-cli as openapi-generator.  This will make bash completion work with either.
- (n/a) Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- (n/a) Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
Making the bash completion script work with Homebrew.

Making completion work with openapi-generator-cli or openapi-generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Add methods to let generators override and customize the naming of allOf, anyOf, oneOf schemes

Add methods to name interfaces (allOf, anyOf, oneOf)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java

To fix https://github.com/OpenAPITools/openapi-generator/issues/2037
- Fixed isFreeFormObject check for allOf, oneOf, anyOf
- Tested locally and the result is good

Fix isFreeFormObject check for allOf, oneOf, anyOf

---

.gitattributes

- n/a Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- n/a Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
This has the effect of making GitHub attribute the language of the project correctly (e.g. as Java). This is useful for sites which list projects by assigned language.

Add .gitattributes file to 'vendor' mustache templates

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java

The `generateSourceCodeOnly` was implicitly always true, regardless of its actual value. This has been fixed.
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess

[python] [bug]Use actual value of generateSourceCodeOnly

---

.github/PULL_REQUEST_TEMPLATE.md

Fix #2070. 
This PR updates PR template to ensure that `./bin/openapi3/**/.sh` is executed before sumitting new PR.

Request to run `./bin/openapi3/**/*.sh` before submitting new PR.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypescriptAngularApiVersionTest.java

@topce 
@macjohnny  
@nicokoenig 
Uses, if specified in OpenAPI file and not received as additional property, version from OpenAPI specification instead of using "1.0.0" as default one.

[TypescriptAngular] gets package npm version from API specification

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java

JS client should default to ES6 instead of ES5. This PR fixes a bug to make sure the default is ES6

[JavaScript] fix JS default ot ES6

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/package.json
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/package.json

The Angular Compiler 6 requires TypeScript >=2.7.2 and <2.10.0  #2096
changed the TypeScript  version for Angular 6
also changed tsickle and ngPackagr version for compatibility with this new TS Version

[angular-typescript] Wrong Typescript Version for Angular 6 with Npm

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAiohttpConnexionServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFlaskConnexionServerCodegen.java

Previously, if you used a packageName of the form "foo.bar.baz", half of the
generated files of the python generator went into a subdirectory
"foo/bar/baz" (correct), the other half went into a subdirectory
"foo.bar.baz" (incorrect).
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess

[python-flask] [python-aiohttp] [bug] Fixed handling of dotted module names

---

modules/openapi-generator/src/main/resources/python/model.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/issue_1997.yaml
samples/client/petstore/python-asyncio/README.md
samples/client/petstore/python-asyncio/docs/AnotherFakeApi.md
samples/client/petstore/python-asyncio/docs/FakeApi.md
samples/client/petstore/python-asyncio/docs/FakeClassnameTags123Api.md
samples/client/petstore/python-asyncio/docs/PetApi.md
samples/client/petstore/python-asyncio/docs/StoreApi.md
samples/client/petstore/python-asyncio/docs/UserApi.md
samples/client/petstore/python-asyncio/petstore_api/configuration.py
samples/client/petstore/python-tornado/README.md
samples/client/petstore/python-tornado/docs/AnotherFakeApi.md
samples/client/petstore/python-tornado/docs/FakeApi.md
samples/client/petstore/python-tornado/docs/FakeClassnameTags123Api.md
samples/client/petstore/python-tornado/docs/PetApi.md
samples/client/petstore/python-tornado/docs/StoreApi.md
samples/client/petstore/python-tornado/docs/UserApi.md
samples/client/petstore/python-tornado/petstore_api/configuration.py

@wing328 @taxpon @frol @mbohlool @cbornet @kenjones-cisco
I think this fixes #1997, if a parameter is nullable, then `None` should be an allowed value.
I ran `./bin/saples/python-petstore-all.sh' it created a bunch of changes that don't seem related, not sure why.

[Python] handle nullable parameters with None added to allowed_values

---

modules/openapi-generator/src/main/resources/php-symfony/services.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/config/services.yml

Add `controller.service_arguments` tag to controllers to make them public

---

modules/openapi-generator/src/main/resources/php/api.mustache
modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php

An example of the change can be found in https://github.com/OpenAPITools/openapi-generator/pull/2072/commits/64bf0d48c0b51de9e4e5a2efde49332d8f8bb60e#diff-15582b49a62d7a5ecac56414cfe6407fR332
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

Add "servers" support to the operation, path in PHP API client

---

docs/generators/php.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpClientCodegen.java
modules/openapi-generator/src/main/resources/lumen/composer.mustache
modules/openapi-generator/src/main/resources/php-laravel/composer.mustache
modules/openapi-generator/src/main/resources/php-symfony/README.mustache
modules/openapi-generator/src/main/resources/php-symfony/composer.mustache
modules/openapi-generator/src/main/resources/php/README.mustache
modules/openapi-generator/src/main/resources/php/composer.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/PhpClientOptionsProvider.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpClientOptionsTest.java
samples/client/petstore/php/OpenAPIClient-php/composer.json
samples/openapi3/client/petstore/php/OpenAPIClient-php/composer.json
samples/server/petstore/php-symfony/SymfonyBundle-php/README.md
samples/server/petstore/php-symfony/SymfonyBundle-php/composer.json

[PHP] remove deprecated options: composerVendorName, composerProjectName
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

[PHP] remove deprecated options

---

README.md

Added @autopp to Ruby technical committee. 🎉 

Add @autopp to Ruby technical committee

---

modules/openapi-generator/src/main/resources/php-symfony/api_controller.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/PetController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/StoreController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/UserController.php

Since we use `StrictJsonDeserializationVisitor` which can throw an exception on type mismatch we should catch this exception and consider it as validation error and return "Bad request" response.

[PHP-Symfony] Catch serializer exception

---

modules/openapi-generator/src/main/resources/typescript-angular/encoder.mustache
samples/client/petstore/typescript-angular-v2/default/encoder.ts
samples/client/petstore/typescript-angular-v2/with-interfaces/encoder.ts
samples/client/petstore/typescript-angular-v4.3/npm/encoder.ts
samples/client/petstore/typescript-angular-v4/npm/encoder.ts
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/default/encoder.ts
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/encoder.ts
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/encoder.ts
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/encoder.ts
samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/default/encoder.ts
samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/encoder.ts
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/default/encoder.ts
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/encoder.ts

rails' default naming for arrays in query parameters is name[]=...&name[]=...
It doesn't recognize the escaped forms %5B + %5D but fails silently
Adapting the solution [here](https://stackoverflow.com/a/48307962) to prevent HttpParameterCodec from encoding '[' and ']' in query param keys.
This is important for using Rails as a backend as the square brackets are added to the parameter names as per default.
I suppose this change doesn't interfere with most people's APIs as square brackets are not common suffixes other to arrays. Encoding them on the other hand is not necessary for URIs and users could still do this if required for their specific project.
However, if this still considered to be a breaking change, I suppose introducing an additional parameter such as …

Don't escape [ and ] in query param keys

---

modules/openapi-generator/src/main/resources/php-symfony/composer.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/composer.json

Fixes #1996
Current version of code is not compatible with JSMSerializerBundle:>=3.0

[PHP-Symfony] Fix JMSSerializerBundle version

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
modules/openapi-generator/src/main/resources/ruby-client/api.mustache
modules/openapi-generator/src/main/resources/ruby-client/model_test.mustache
modules/openapi-generator/src/main/resources/ruby-client/partial_model_enum_class.mustache
modules/openapi-generator/src/main/resources/ruby-client/partial_model_generic.mustache
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/models/enum_arrays.rb
samples/client/petstore/ruby/lib/petstore/models/enum_class.rb
samples/client/petstore/ruby/lib/petstore/models/enum_test.rb
samples/client/petstore/ruby/lib/petstore/models/order.rb
samples/client/petstore/ruby/lib/petstore/models/outer_enum.rb
samples/client/petstore/ruby/lib/petstore/models/pet.rb
samples/client/petstore/ruby/spec/models/enum_test_spec.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/models/enum_arrays.rb
samples/openapi3/client/petstore/ruby/lib/petstore/models/enum_class.rb
samples/openapi3/client/petstore/ruby/lib/petstore/models/enum_test.rb
samples/openapi3/client/petstore/ruby/lib/petstore/models/order.rb
samples/openapi3/client/petstore/ruby/lib/petstore/models/outer_enum.rb
samples/openapi3/client/petstore/ruby/lib/petstore/models/pet.rb
samples/openapi3/client/petstore/ruby/spec/models/enum_test_spec.rb

Fix #2081.
- To correctly escape, `toEnumValue` now returns double-quote string.
- To correctly expand allowable values, `{{#values}}` in `{{#allowableValues}}` changed to `{{#enumVars}}`.

[Ruby] Fix enum expansion in Ruby client (#2081)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientOptionsTest.java

Previously, if you used a packageName of the form `foo.bar.baz`, half of the
generated files of the python generator went into a subdirectory
`foo/bar/baz` (correct), the other half went into a subdirectory
`foo.bar.baz` (incorrect).
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess

[python] [bug] Fixed handling of dotted module names

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/AbstractIntegrationTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/bash/BashTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/DartModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/html/StaticHtmlGeneratorTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJerseyServerCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/javascript/JavascriptClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/objc/ObjcModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/perl/PerlClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/RubyClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/swift3/Swift3CodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/swift4/Swift4CodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypescriptAngularApiVersionTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java

In a lot of places in the Unit Tests, we parse an existing JSON or YAML specification.
This PR just ensure that this parsing is done with the same method call everywhere.
This is part of the effort I am doing for #2111, but the PR can be merged independently.

[clean-up] Centralize Swagger-Parser call in the unit tests

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java

#2004 
@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon

[PHP] Replace File.seperator with slashes in PHP projects #2004

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularModelTest.java

fix #2120
append _ at the beginning, as reserved keyword
add 2 tests case to check codegen parser for operationId and property starting with decimal

[typescript-angular] Incorrect OperationId Generated (starting with number)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java

Fix a null pointer reported in https://github.com/OpenAPITools/openapi-generator/issues/855#issuecomment-462730420

[core] Fix NullPointer when schema is not set in header

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_0/unusedSchemas.yaml

Introduced with #74 and updated with #1232, the `ModelUtils.getUnusedSchemas(OpenAPI)` returns all schemas that are not used in an OpenAPI specification.
This PR fixes the case where a Schema is referenced in an Header.
Original issue: #50

[core] consider schema in headers when computing unused schemas

---

modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
samples/client/petstore/typescript-angular-v2/npm/encoder.ts
samples/client/petstore/typescript-angular-v4.3/npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/api/pet.service.ts
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/api/pet.service.ts

#2147: fix compiler error in angular typescript codegen

---

modules/openapi-generator/src/main/resources/php-symfony/api_input_validation.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/PetController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/StoreController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/UserController.php

Input object is not validated at the moment. This PR fixes it.

[PHP-Symfony] Validate input objects

---

modules/openapi-generator/src/main/resources/php-symfony/services.mustache
modules/openapi-generator/src/main/resources/php-symfony/validation/SymfonyValidator.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/config/services.yml
samples/server/petstore/php-symfony/SymfonyBundle-php/Service/SymfonyValidator.php

Inject Symfony Validator service instead of creating own one.

[PHP-Symfony] Use Symfony Validator service

---

modules/openapi-generator/src/main/resources/php-symfony/api_controller.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/PetController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/StoreController.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/UserController.php

If method return empty response the return format is always null and the method returns 406 response before processing.

[PHP-Symfony] Don't try to detect response format if method return nothing

---

bin/utils/openapi-generator-cli.sh

`bin/utils/openapi-generator-cli.sh` is missing a single quote in line 32

openapi-generator-cli.sh: Fix missing single quote

---

modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
samples/server/petstore/rust-server/output/rust-server-test/src/client/mod.rs

Based on this [issue](https://github.com/servo/rust-url/issues/416) the `utf8_percent_encode` doesn't percent encode `+` instead treats it as a space which is may cause a problem if the query parameters contain one. For example if we wanted to use a DateTime range in query parameters:
`{base_path}{path}?start=2019-02-12T00:00:00+00:00&end=2019-02-13T15:00:00+00:00`
These parameters may be decoded as:
```
start = 2019-02-12T00:00:00 00:00
end = 2019-02-13T15:00:00 00:00
```
To solve this I changed query parameters to be form-urlencoded using `url::form_urlencoded` based on what's done in [`rust` client generator](https://github.com/OpenAPITools/openapi-generator/blob/ea08106c809c17a660c9180210e12ae02c2d5914/modules/openapi-generator/src/main/resources/rust/request.rs#L106).

[rust-server] Changed query parameters to be url encoded

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/api_client.mustache
modules/openapi-generator/src/main/resources/r/api_doc.mustache
modules/openapi-generator/src/main/resources/r/api_test.mustache
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/docs/Order.md
samples/client/petstore/R/docs/Pet.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/docs/StoreApi.md
samples/client/petstore/R/docs/User.md
samples/client/petstore/R/docs/UserApi.md

- use optional parameters
- fix header parameters
- rename callAPI to CallAPI to conform to the style guide
- fix API key authentication

[R] various improvements and bug fixes

---

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
modules/openapi-generator-maven-plugin/README.md

fix issue #2131 :
add missing General Configuration parameters in Maven Plugin README
fix word typo in generate description option

[plugin][maven] add missing General Configuration parameters in README

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5AbstractCodegen.java
modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirouter.h.mustache
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIApiRouter.h

- Fix failing build due to deprecation of `initialCaps`, filenames were wrongly named and not found during compilation
- Include `<functional>` for failing build in debian
`CC:` @stkrwork @fvarose @MartinDelille @ravinikam

[C++][Qt5] Fix import for models with underscore

---

docs/generators/typescript-angular.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java

update the default Angular version from 4.3 to 6.0 for generate client with npm libraries
issue #2116
useful link : https://angular.io/guide/releases#support-policy-and-schedule

[typescript-angular] Update default Angular version from 4.3 to 7.0

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelTest.java

fix the getter/setter when the second letter of the field name is already uppercase (following the JavaBeans API specification)
[Java] Getter/Setter naming convention not followed in generated models #2085
fix the getter/setter when the second letter of the field name is already uppercase (following the JavaBeans API specification)
Details : 
Override `getterAndSetterCapitalize` class in the `AbstractJavaCodeGen` class
Change Java test `convert a model with a 2nd char upper-case property names` (getter and setter expected results)
useful links : 
- https://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf?AuthParam= …

[Java] Getter/Setter naming convention not followed in generated models

---

modules/openapi-generator/src/main/resources/ruby-client/api.mustache
modules/openapi-generator/src/main/resources/ruby-client/partial_model_generic.mustache
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/models/format_test.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/models/format_test.rb

Fix #2069.
- To correctly embedding the regualr expression into error message, it's changed to string interpolation.
- Unnecessary invocation of `Regexp.new` is deleted. (`Regexp.new(/.../)` -> `/.../`)

[Ruby] Fix regualr expression in error message (#2069)

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

Addresses #2125 for `-g java -Dlibrary=okhttp-gson` only.
I committed the result of running `bin/java-petstore-okhttp-gson.sh`. But I didn't commit the result of running `bin/security/java-petstore-okhttp-gson.sh`, because there were tons of changes there that I didn't introduce. I'm not sure what I'm supposed to do with them.

okhttp-gson: allow array parameters in path using collectionFormat

---

modules/openapi-generator/src/main/resources/go/api.mustache

This fix the issue #1600 .
This allow us to compile the client, and we are using this way to maintain the cookie:
```go
jar, _ := cookiejar.New(&cookiejar.Options{PublicSuffixList: publicsuffix.List})
cfg.HTTPClient = &http.Client{nil, nil, jar, 0}
client := openapi.NewAPIClient(cfg)
```
We get authenticated sending an `apiToken` to the autentication endpoint.

Remove API Key Authentication code for go when cookie is used.

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/UserApi.java

Addresses issue #2125 for java resttemplate
Similar to PR https://github.com/OpenAPITools/openapi-generator/pull/2137
Remake of https://github.com/OpenAPITools/openapi-generator/pull/2176

rest-template: allow array parameters in path using collectionFormat

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java

Fixes #2127
Follow up of PR #1981
When you have a default value defined, in the outer enum case (where a seperated enum file is created) the default value was only working for the string type.
This PR address the issue.
---
Tested with a spec having this outer enum cases:
```yaml
components:
schemas:
IntEnum:
type: integer
format: int32
default: 2
enum:
- 1
- 2
- 3
LongEnum:
type: integer
format: int64
default: 30
enum:
- 20
- 30
- 40
StringEnum:
type: string
default: "b"
enum:
- "c"
- "b"
- "a"
EnumWithCustomName:
type: integer
format: int32
default: 2
enum:
- 1
- 2
x-enum-varnames:
- FOO
- BAR
```
And following schema:
```yaml
ObjWithEnumProperties:
type: object
properties:
iprop:
$ref: "#/components/schemas/IntEnum"
lprop:
$ref: "#/components/schemas/LongEnum"
sprop:
$ref: …
```

[core] fix referenced enum case

---

modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java

Enable error handling in Java WebClient library, fixes #1243.
Also now the generated Exception class `ApiException` is used.
Custom error handling behaviour can be defined in an overwriting class e.g.:
```java
public class MyApiClient extends ApiClient {
@Override
protected <T> Mono<T> handleUnsuccessfulResponse(ClientResponse response) {
return super.<T>handleUnsuccessfulResponse(response)
.onErrorMap(errorcode(404), x -> new MyNotFoundException("Not found"));
}
private static Predicate<Throwable> errorcode(int errorCode) {
return x -> x instanceof ApiException && ((ApiException) x).getCode() == errorCode;
}
}
```
@bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger

Enable error handling in Java WebClient library, fixes #1243

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java
modules/openapi-generator/src/test/resources/3_0/examples.yaml
modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml

This PR closes https://github.com/OpenAPITools/openapi-generator/issues/2119

Fix missing nullable

---

modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
modules/openapi-generator/src/main/resources/rust/reqwest/configuration.mustache

Use `req_builder.bearer_auth` instead of `basic_auth` when `BearerAuth` security schema is specified.
@frol, @farcaller, @bjgill

Use oauth token for basic bearer auth in Rust.

---

modules/openapi-generator/src/main/resources/haskell-servant/Types.mustache
samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/Types.hs

Implemented fix for https://github.com/OpenAPITools/openapi-generator/issues/1849

Something in the dependencies changed. This switch is no longer needed.

---

.travis.yml

The installation is no longer needed

[CI] skip "bats" installation in Travis CI

---

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt

This allows easier creation of custom `GenerateTask`. Specifically, this makes:
- generateModelTests
- generateModelDocumentation
- generateApiTests
- generateApiDocumentation
- withXml
optional, following the same pattern as other properties in GenerateTask.
Without this change, we get `java.lang.IllegalStateException: No value has been specified for this provider.` until these properties are specified for the task, when attempting to define a custom generate task (such as one to generate API docs).
Note I left a couple of items in PR checklist unmarked as they don't seem relevant to this change. Please let me know if this should be handled differently.

Gradle - make GenerateTask properties optional

---

.travis.yml
samples/openapi3/client/petstore/ruby/press_anykey_to_continue.sh
samples/openapi3/client/petstore/ruby/spec/custom/api_error_spec.rb
samples/openapi3/client/petstore/ruby/spec/custom/base_object_spec.rb
samples/openapi3/client/petstore/ruby/spec/custom/pet_spec.rb
samples/openapi3/client/petstore/ruby/spec/custom/store_spec.rb
samples/openapi3/client/petstore/ruby/spec/petstore_helper.rb

Add petstore integration tests to Ruby OAS3 client

---

bin/utils/openapi-generator-cli.sh

Fix version detection

---

.travis.yml
CI/circle_parallel.sh
circle.yml
pom.xml
samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/API.hs
samples/server/petstore/haskell-servant/pom.xml

Test haskell-servant petstore sample in ~~Travis~~ Shippable CI.

Add Haskell Servant build to Shippable CI

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
samples/client/petstore/R/NAMESPACE
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/Pet.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/docs/StoreApi.md
samples/client/petstore/R/docs/UserApi.md

Fix NPE issue due to default value using example value

[R] Fix NPE issue due to default value using example value

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

Better info message about using generateAliasAsModel as discussed in the chat room (https://gitter.im/OpenAPITools/openapi-generator)
FYI @jimschubert

Better info message about using generateAliasAsModel

---

bin/openapi3/ruby-client-petstore.sh
samples/openapi3/client/petstore/ruby/spec/api/another_fake_api_spec.rb
samples/openapi3/client/petstore/ruby/spec/api/default_api_spec.rb
samples/openapi3/client/petstore/ruby/spec/api/fake_api_spec.rb
samples/openapi3/client/petstore/ruby/spec/api/fake_classname_tags123_api_spec.rb
samples/openapi3/client/petstore/ruby/spec/api/pet_api_spec.rb
samples/openapi3/client/petstore/ruby/spec/api/store_api_spec.rb
samples/openapi3/client/petstore/ruby/spec/api/user_api_spec.rb
samples/openapi3/client/petstore/ruby/spec/models/enum_test_spec.rb

In order to guarantee update of test files in sample for Ruby's OAS3 client (`samples/openapi3/client/petstore/ruby/spec`), `bin/openapi3/ruby-client-petstore.sh` will also purge the test file.
See: https://github.com/OpenAPITools/openapi-generator/pull/2211#issuecomment-467802105

[Ruby] Auto recreate specs in OAS3 Ruby sample

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-rxjs/modelGeneric.mustache
samples/client/petstore/typescript-rxjs/builds/default/models/Order.ts
samples/client/petstore/typescript-rxjs/builds/default/models/Pet.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/models/Order.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/models/Pet.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/models/Order.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/models/Pet.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/models/Order.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/models/Pet.ts

Based on the discussion of #1947 and copied from #2123 this solves the issue of identical enums exported within barrels by prefixing them with the name of the interface. The namespace issue mentioned in the ticket / pr wasn't an issue for `typescript-rxjs` but it looks like enums weren't properly generated in the past as the diff of the petstore samples shows.

[typescript-rxjs] fix enums

---

CI/circle_parallel.sh

Now we've to manually comment/uncomment the line before/after the release.
Ideally the script "ensure-up-to-date.sh" should only run for SNAPSHOT version only.
fix #284

Run "bin/ensure-up-to-date.sh" for SNAPSHOT version only

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/AbstractRubyCodegenTest.java
samples/client/petstore-security-test/ruby/docs/ModelReturn.md
samples/client/petstore-security-test/ruby/lib/petstore/api_error.rb
samples/client/petstore-security-test/ruby/lib/petstore/models/model_return.rb
samples/client/petstore-security-test/ruby/spec/api/fake_api_spec.rb
samples/client/petstore/ruby/spec/api/another_fake_api_spec.rb
samples/client/petstore/ruby/spec/api/fake_api_spec.rb
samples/client/petstore/ruby/spec/api/fake_classname_tags123_api_spec.rb
samples/client/petstore/ruby/spec/api/pet_api_spec.rb
samples/client/petstore/ruby/spec/api/store_api_spec.rb
samples/client/petstore/ruby/spec/api/user_api_spec.rb

Fix #2261.
This PR has been modified to escape string interpolations in `enum` when generating Ruby client.
- To escape `#{`, modified `AbstractRubyCodegen::escapeUnsafeCharactors`
- Added test class for `AbstractRubyCodegen`
- For this the visibility of `AbstractRubyCodegen` and its constructor ware changed to public.
E.g.
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate --skip-validate-spec -g ruby -o /tmp/gem -i 'https://gist.githubusercontent.com/autopp/48160b45f1c17c950ba72feb971786c3/raw/974579f49d9a0eebff0455e54efce842eee64c9b/example.yml'
```
`lib/openapi_client/api/default_api.rb` generated by the above command no longer includes string interpolation.
```
def foo_get_with_http_info(opts = {})
if @api_client.config.debugging …
```

[Ruby] Escape string interpolation notation of Ruby (#2261)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/ClientOpts.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/SupportingFile.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java

I'm now revisiting openapi-generator with a bit more Java expertise than I had a few months ago. There are a few things in the Rust generator that seem worthy of refactoring.
Also, I've recently discovered `Objects.equals` and `Objects.hash` - see https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html. These helpers, introduced in Java 7, vastly reduce the amount of boilerplate required to implement the `equals` and `hashcode` methods. If this PR gets accepted, I'll have a go at giving the same treatment to a bunch of other classes with similar/worse quantities of boilerplate.

Refactor and use some Java 7 features

---

modules/openapi-generator/pom.xml
pom.xml

fix pom warnings : 
- uncorrect configuration parameters on maven-javadoc-plugin
- invalid path on some profile

[Maven] Minor fix on pom

---

modules/openapi-generator/src/main/resources/haskell-http-client/haskell-http-client.cabal.mustache
samples/client/petstore/haskell-http-client/openapi-petstore.cabal

katip-0.8.0.0 is needed due to the interface change in `mkHandleScribe`

 haskell-http-client: update katip version bound

---

modules/openapi-generator/src/main/resources/haskell-http-client/haskell-http-client.cabal.mustache
samples/client/petstore/haskell-http-client/openapi-petstore.cabal

The indentation of `category` in the .cabal file is off.

haskell-http-client: fix indentation in .cabal file

---

bin/utils/ensure-up-to-date

Add R and JavaScript in ensure-up-to-date sample scripts

ensure-up-to-date - add r and javascript

---

modules/openapi-generator/src/main/resources/Java/beanValidationCore.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/beanValidationCore.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/beanValidationCore.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/beanValidationCore.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/beanValidationCore.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/spec/beanValidationCore.mustache
modules/openapi-generator/src/main/resources/JavaSpring/beanValidationCore.mustache

@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
the exclusiveMinimum openApi properties is not mapped in bean validation annotation template
#2082

[Java] Bean Validation for decimalmin/max incorrect when exclusive set

---

samples/client/petstore/R/NAMESPACE
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/docs/StoreApi.md
samples/client/petstore/R/docs/UserApi.md

[R sample] fix CircleCI error of outdated sample  after #2227 merging on master

[R sample] fix CircleCI error of outdated sample

---

modules/openapi-generator/src/main/resources/JavaSpring/api.mustache

fixes #2191
The distinction between the following cases was leading to compile errors in the generated code
adressing request body as single file:
```yaml
requestBody:
content:
application/octet-stream:
schema:
type: string
format: binary
```
and files in multipart/form-data requests:
```yaml
requestBody:
content: 
schema:
type: object
properties:
id:  
type: string
format: uuid
profileImage:  
type: string
format: binary
```
(as described [here](https://swagger.io/docs/specification/describing-request-body/file-upload/)
I found out, that internally multipart parameters are handled in formParams, where the "raw" body is handled in bodyParams.
In the template for formParams is a special case for files in multipart, that was also used for rendering the delegate methods …

[Spring] fix datatype for non-multipart file request body

---

pom.xml

[Maven] fix Spaces in Windows user path breaks build on test goal

---

samples/client/petstore-security-test/ruby/.travis.yml
samples/client/petstore-security-test/ruby/Gemfile.lock

When we run `./bin/security/ruby-client-petstore.sh`, we got changes.
I think someone fogot to commit it.

Add .travis.yml and Gemfile.lock to ruby security test folder

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
samples/client/petstore/typescript-fetch/builds/default/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/es6-target/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/models/Pet.ts

Fixes #2323 
Apply the same guard against `undefined` as is already used for `Date` (just above).
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce

[typescript-fetch] Guard array mapping against undefined on optional array model properties

---

modules/openapi-generator/src/main/resources/typescript-rxjs/apis.mustache
samples/client/petstore/typescript-rxjs/builds/default/apis/PetApi.ts
samples/client/petstore/typescript-rxjs/builds/default/apis/StoreApi.ts
samples/client/petstore/typescript-rxjs/builds/default/apis/UserApi.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/apis/PetApi.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/apis/StoreApi.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/apis/UserApi.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/apis/PetApi.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/apis/StoreApi.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/apis/UserApi.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/apis/PetApi.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/apis/StoreApi.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/apis/UserApi.ts

This PR removes unneeded wrapping functions within api controllers.

[typescript-rxjs] drop unneeded function wrapping 

---

modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirequest.cpp.mustache

- Add  handling of free form object in the API request
- No changes in the generated sample code
`cc:`
@stkrwork @MartinDelille @ravinikam @fvarose

[C++] [Qt5 Server] Add support for free form object in requests

---

bin/scala-httpclient-petstore.sh
bin/windows/scala-httpclient-petstore.bat
docs/generators.md
docs/generators/scala-httpclient-deprecated.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaHttpClientCodegen.java

Renamed `scala-httpclient` to `scala-httpclient-deprecated`. Users should switch to `scala-akka` instead.
cc @clasnake , @jimschubert @shijinkui, @ramzimaalej

[scala-httpclient] mark the generator as deprecated

---

README.md

Fixes:
Error: invalid option: --HEAD
See also:
- https://github.com/Homebrew/brew/issues/4793

[README] Update instructions for reinstalling master with brew

---

modules/openapi-generator-maven-plugin/README.md

additional PR to fix #2131 : 
- add missing `groupId`, `artifactId` and `artifactVersion` global parameters
- fix default value of `output` parameter

[Maven doc] fix/add General Configuration parameters

---

CI/samples.ci/client/petstore/java/test-manual/okhttp-gson/api/PetApiTest.java
samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/api/PetApiTest.java

Additional tests provided by @ngaya-ll 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

Add more tests to the Java client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java

@jimschubert (2017/09) , @dr4ke616 (2018/08)
fix #1885
add some missing testcase on toModelName function in abstract Kotlin CodeGen package

[Kotlin] Add ability to use modelNamePrefix/modelNameSuffix

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore-security-test/typescript-fetch/runtime.ts
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/runtime.ts

Fixes #2233.
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce 
Add support for nested objects in query parameters.
Object type query parameters can currently not be properly serialized (see related issue above).  
This PR allows nested object parameters in the `HTTPQuery` type and extends the `querystring` function of the API runtime library to recursively serialize objects with the `deepObject` style as defined in [OpenAPI 3.0](https://swagger.io/docs/specification/serialization/#query).
This method does *not* support arrays of objects, as this would cause an ambiguous serialization due to the use of the `explode` format for arrays.  
E.g. a query string `person[name]=Alice&person[name]=Bob` could be interpreted as an array of person objects with one name …

[typescript-fetch] Support deepObject serialization in query parameters

---

modules/openapi-generator/src/main/resources/ruby-client/api.mustache
samples/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/client/petstore/ruby/lib/petstore/api/user_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/user_api.rb

YARD supports parameter type tag.
https://www.rubydoc.info/gems/yard/file/docs/Tags.md#param
We can use `dataType` as parameter type.
So it's very useful to output `dataType`.

Outputs dataType to YARD tag 

---

modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache

- when package name is set the generated code fails to compile
- fix small typo `ConentType`
`e.g.`
```bash
-i ~/api-specs/swagger.yaml  -o ~/genclient -g csharp-netcore \
--additional-properties packageName=MyPackage \
--additional-properties netCoreProjectFile=true \
--additional-properties targetFramework=netcoreapp2.0
```
`cc:`
@wing328 @jimschubert

[C#][netcore] Fix package name in the localVar types

---

samples/client/petstore/R/test_petstore.bash

- skip error when directory already exists in the test script

[R] skip error when directory already exists in the test script

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellHttpClientCodegen.java
modules/openapi-generator/src/main/resources/haskell-http-client/ImportMappings.mustache
modules/openapi-generator/src/main/resources/haskell-http-client/Model.mustache
modules/openapi-generator/src/main/resources/haskell-http-client/TopLevel.mustache
modules/openapi-generator/src/main/resources/haskell-http-client/haskell-http-client.cabal.mustache

import mappings take the form of:
```
--import-mappings %DATATYPE%=%MODULE%
```
full example (with --type-mappings):
```
--type-mappings intstr.IntOrString=IntOrString
--import-mappings IntOrString=Kubernetes.CustomTypes
```
The import-mapped module will be an exposed module of the generated library.
The import mappings will be re-exported from ImportMappings, which itself is re-xported from Models.
Model.hs
```
module Kubernetes.Model (module Kubernetes.Model, module Kubernetes.ImportMappings) where
import Kubernetes.ImportMappings
```
ImportMappings.hs:
```
module Kubernetes.ImportMappings (module ImportMappings) where
import Kubernetes.CustomTypes as ImportMappings (IntOrString(..))
```

[haskell-http-client] add support for import-mappings

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
modules/openapi-generator/src/main/resources/python/configuration.mustache
modules/openapi-generator/src/test/resources/3_0/petstore.yaml
samples/client/petstore-security-test/python/petstore_api/api_client.py
samples/client/petstore/python-asyncio/petstore_api/api_client.py
samples/client/petstore/python-tornado/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py
samples/server/openapi3/petstore/python-flask-python2/openapi_server/controllers/security_controller_.py
samples/server/openapi3/petstore/python-flask-python2/openapi_server/openapi/openapi.yaml
samples/server/openapi3/petstore/python-flask-python2/openapi_server/test/test_user_controller.py
samples/server/openapi3/petstore/python-flask/openapi_server/controllers/security_controller_.py
samples/server/openapi3/petstore/python-flask/openapi_server/openapi/openapi.yaml
samples/server/openapi3/petstore/python-flask/openapi_server/test/test_user_controller.py

This PR fixes the missing `APIKey` authentication based on HTTP Cookies in Python clients.
Fixes #2075
I am using this change for quite some time in our local build and it works as expected.
When we receive the `Set-Cookie` header from the OpenAPI server, we update the configuration in the `ApiClient`.
Authentication works seamless from then on. There no need to set/add the `Cookie` header ourselves anymore.
There are some things related to the Cookie authentication which we might include here or add as separate BUG report or PR:
Please advise what to do with these pending changes.

Python apikey cookie

---

modules/openapi-generator/src/main/resources/r/api.mustache
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R

To fix issues when path parameters contain special characters that need to be url-encoded.

[R] url-encode path parameters

---

modules/openapi-generator/src/main/resources/go/client.mustache
samples/client/petstore/go/go-petstore/client.go

For the following spec:
``` yaml
responses:
"200":
description: Pong.
content:
text/plain:
schema:
type: string
```
The generated client currently fails with `undefined response type`.
In this scenario, `v interface{}` is a string pointer which can be populated regardless of the content-type.

[go] support decoding plain string responses

---

modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirequest.cpp.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirequest.h.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirouter.cpp.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirouter.h.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/main.cpp.mustache
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIApiRouter.cpp
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIApiRouter.h
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/main.cpp
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIPetApiRequest.cpp
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIPetApiRequest.h
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIStoreApiRequest.cpp
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIStoreApiRequest.h
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIUserApiRequest.cpp
samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIUserApiRequest.h

- The generated code allows setting a handler which is a derived class of the generated handler code
- using of `QSharedPointer` allows the old handler to be deallocated until all requests are served 
`cc:`
@stkrwork @MartinDelille @fvarose @ravinikam

[C++] [Qt5 Server] server allow api handler override of generated code

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5ClientCodegen.java

Fixes #2277 
`cc`
@stkrwork @ravinikam @fvarose @MartinDelille

[C++][Qt5] Fix generation of optional file when model name prefix is selected

---

docs/generators/php-laravel.md
docs/generators/php-lumen.md
docs/generators/php-slim.md
docs/generators/php-symfony.md
docs/generators/php-ze-ph.md
docs/generators/php.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/lumen/PhpLumenServerOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/PhpClientOptionsProvider.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/PhpLumenServerOptionsProvider.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/PhpSlimServerOptionsProvider.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpClientOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/slim/PhpSlimServerOptionsTest.java

These options are global so no need to be included in the PHP generators.
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

Remove global options from PHP generators

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
samples/client/petstore/ruby/docs/FakeApi.md
samples/openapi3/client/petstore/ruby/docs/FakeApi.md

A follow-up to https://github.com/OpenAPITools/openapi-generator/pull/2386#pullrequestreview-215337726

Fix boolean example value in ruby client generator

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java

Minor fix to docstring and code format
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

[Java] Fix Javadoc issue in the client

---

docs/customization.md
docs/usage.md
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
modules/openapi-generator-cli/src/test/java/org/openapitools/codegen/cmd/GenerateTest.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java

It implements #2425 support for yaml. It basically checks if the input file has `yaml` or `yml` extension, if so it uses the `Yaml.mapper()` for this. If any other extension, or empty (so no breaking change) it will use the old `Json.mapper()`.

[#2425] - implemented yaml parsing for config file.

---

.travis.yml
modules/openapi-generator-gradle-plugin/build.gradle

This is an attempt at publishing the gradle plugin to the gradle plugin portal.
I've attempted a publish locally, but it is pending approval: https://plugins.gradle.org/plugin/org.openapi.generator

Initial attempt at deploying to gradle plugin portal

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
modules/openapi-generator/src/main/resources/C-libcurl/README.md.mustache
modules/openapi-generator/src/main/resources/C-libcurl/object-body.mustache
modules/openapi-generator/src/main/resources/C-libcurl/object-header.mustache

- update handling of reserved keywords to make it same in all cases
- update README mustache to give info about how to compile the library and use the library
- add object header and body mustache to create object models
- set isEnum which is required for handling enum variables in C codegen in CLibCurlClientCodegen.java to avoid conflict with other codegen
cc
@wing328

[C] Update README and adding object.c/h files

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
modules/openapi-generator/src/main/resources/elixir/connection.ex.mustache
modules/openapi-generator/src/main/resources/elixir/request_builder.ex.mustache
samples/client/petstore/elixir/lib/openapi_petstore/connection.ex
samples/client/petstore/elixir/lib/openapi_petstore/request_builder.ex
samples/client/petstore/elixir/mix.exs

- Update Tesla dependency version
- ~Replace Poison with Jason (it is the new default JSON encoder)~ 
(Jason doesn't support `:as` option)
- Use new method to set the headers as per the [official migration guide](https://github.com/teamon/tesla/wiki/0.x-to-1.0-Migration-Guide).
closes #2325 
cc @mrmstn

[Elixir] Update Tesla dependency to version 1.0

---

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/Generator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/AbstractGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractApexCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptFlowtypedClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyOnRailsServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaClientCodegen.java

second part of fixing Sonar issues

---

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/OpenAPIGenerator.java
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ListGenerators.java
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Validate.java
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
pom.xml

fix `mvn verify -f modules/openapi-generator-cli/pom.xml` who failed locally (with jdk1.8.0_171) cause of javadoc warning with maven-javadoc-plugin 3.0.1 but not with 3.1.0 anymore (actually no error in circleci but probably cause of #705)
fix warning` line 2 column 2 - Error: <additionalproperties> is not recognized!` in circle-ci log in` openapi-generator-maven-plugin` module
fix some sonarlint issues in module `openapi-generator-cli`

[MAVEN PLUGIN] fix javadoc + sonarlint

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java

The unit tests skip all _media types_ which are not `application/json`.
In fact it should accept any _media type_ which uses `json` as underlying structure (`*/*+json`).
See also [RFC6838, section 4.2.8](https://tools.ietf.org/html/rfc6838#section-4.2) and [RFC6838, section 4.2.8](https://tools.ietf.org/html/rfc6838#section-4.2.8)) for more information.

[python-flask] Do not skip unit tests when underlying type defines json

---

modules/openapi-generator/src/main/resources/python/configuration.mustache
modules/openapi-generator/src/main/resources/python/rest.mustache
samples/client/petstore/python-asyncio/petstore_api/configuration.py
samples/client/petstore/python-tornado/petstore_api/configuration.py
samples/client/petstore/python/petstore_api/configuration.py
samples/client/petstore/python/petstore_api/rest.py
samples/client/petstore/ruby/docs/AdditionalPropertiesClass.md
samples/client/petstore/ruby/lib/petstore/models/additional_properties_any_type.rb
samples/client/petstore/ruby/lib/petstore/models/additional_properties_array.rb
samples/client/petstore/ruby/lib/petstore/models/additional_properties_boolean.rb
samples/client/petstore/ruby/lib/petstore/models/additional_properties_class.rb
samples/client/petstore/ruby/lib/petstore/models/additional_properties_integer.rb
samples/client/petstore/ruby/lib/petstore/models/additional_properties_number.rb
samples/client/petstore/ruby/lib/petstore/models/additional_properties_object.rb
samples/client/petstore/ruby/lib/petstore/models/additional_properties_string.rb
samples/openapi3/client/petstore/python/petstore_api/configuration.py
samples/openapi3/client/petstore/python/petstore_api/rest.py
samples/openapi3/client/petstore/ruby/docs/NullableClass.md
samples/openapi3/client/petstore/ruby/lib/petstore/models/nullable_class.rb

Adding retries option to override the default value of urllib which is 3. This will give option to control number of retries for any request.

Adding retries option to override default value 3 of urllib3

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts

[typescript-axios] Fix JSON serialization of falsy request bodies

---

modules/openapi-generator/src/main/resources/kotlin-client/api.mustache
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt

@jimschubert (2017/09), @dr4ke616 (2018/08)
fix #2462 
remove else in when clause cause all responseType values are covered

[Kotlin client] fix warning when else all covered

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/runtime.ts

Add return type declaration to typescript-fetch runtime

---

bin/ruby-client-petstore.sh
samples/client/petstore/ruby/spec/models/additional_properties_class_spec.rb

In order to guarantee update of sample for Ruby client (`samples/client/petstore/ruby`), `bin/ruby-client-petstore.sh` will purge `lib`, `doc`, `spec`.
Related PR: #2264

[Ruby] Auto recreate directories in Ruby samples

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache

- [ X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review …

[Java] Jersey2 - Always render setBearerToken no matter if OAuth2 is in use.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java
modules/openapi-generator/src/main/resources/python-aiohttp/__init__main.mustache
modules/openapi-generator/src/main/resources/python-aiohttp/conftest.mustache
modules/openapi-generator/src/main/resources/python-aiohttp/controller_test.mustache
modules/openapi-generator/src/main/resources/python-flask/__init__test.mustache
modules/openapi-generator/src/main/resources/python-flask/__main__.mustache
modules/openapi-generator/src/main/resources/python-flask/controller_test.mustache
modules/openapi-generator/src/test/resources/3_0/petstore.yaml
samples/server/openapi3/petstore/python-flask-python2/openapi_server/__main__.py
samples/server/openapi3/petstore/python-flask-python2/openapi_server/controllers/pet_controller.py
samples/server/openapi3/petstore/python-flask-python2/openapi_server/openapi/openapi.yaml
samples/server/openapi3/petstore/python-flask-python2/openapi_server/test/__init__.py
samples/server/openapi3/petstore/python-flask-python2/openapi_server/test/test_pet_controller.py
samples/server/openapi3/petstore/python-flask/openapi_server/__main__.py
samples/server/openapi3/petstore/python-flask/openapi_server/controllers/pet_controller.py
samples/server/openapi3/petstore/python-flask/openapi_server/openapi/openapi.yaml
samples/server/openapi3/petstore/python-flask/openapi_server/test/__init__.py
samples/server/openapi3/petstore/python-flask/openapi_server/test/test_pet_controller.py
samples/server/petstore/python-aiohttp/openapi_server/__init__.py
samples/server/petstore/python-aiohttp/openapi_server/openapi/openapi.yaml
samples/server/petstore/python-aiohttp/tests/conftest.py
samples/server/petstore/python-flask-python2/openapi_server/__main__.py
samples/server/petstore/python-flask-python2/openapi_server/openapi/openapi.yaml
samples/server/petstore/python-flask-python2/openapi_server/test/__init__.py
samples/server/petstore/python-flask/openapi_server/__main__.py
samples/server/petstore/python-flask/openapi_server/openapi/openapi.yaml
samples/server/petstore/python-flask/openapi_server/test/__init__.py

We have an OpenAPI spec file with `camelCase` (_query_ and _path_) parameters.
When generating a Python (`connexion`-based) server those parameters are converted to ("_pythonic_") `snake_case` parameters.
During generation of the supporting files there is also an OpenAPI spec file generated for use with `connexion`. This spec file does not match the original one regarding parameter names.
Especially when defining "_query_" parameters, the REST interface will be different than the one defined in the original OpenAPI spec file.
Such (_query_) parameters are incompatible with generated clients (and other server implementations)
Fixes #1671
We have been using this fix some time on a local checkout for generating `python-flask` server implementations without issues.
1. This PR also updates the …

Python flask pythonic params

---

.travis.yml

Publishing to the gradle plugin portal after Sonatype will fail on artifacts unsupported by the portal (asc, sources, etc). This attempts to publish to the portal first, to avoid needing to do a clean/publish after the Sonatype artifacts are published.

Publish to gradle plugin prior to sonatype

---

modules/openapi-generator/src/main/resources/php-symfony/Controller.mustache
modules/openapi-generator/src/main/resources/php-symfony/composer.mustache
modules/openapi-generator/src/main/resources/php-symfony/services.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/Controller.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/config/services.yml
samples/server/petstore/php-symfony/SymfonyBundle-php/composer.json

`Symfony\Bundle\FrameworkBundle\Controller\Controller` is deprecated and should be replaced with `Symfony\Bundle\FrameworkBundle\Controller\AbstractController`
cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon @Addvilz

[Symfony] Replace deprecated Controller with new one

---

docs/usage.md
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java

Added another option for the `config-help --format` called `yamlsample` that will basically outputs key value pairs with default values. Also comments with the description of the cli option. If the value doesn't have default value it is commented out and the user has the possibility to uncomment and set a value.

[#2442] - implement yamlsample config help output;

---

modules/openapi-generator/src/main/resources/Javascript-Flowtyped/api.mustache
samples/client/petstore/javascript-flowtyped/src/api.js

This fixes serialization of the request body in the javascript-flowtyped generator when the request body is falsy. Before this fix, some request bodies consisting of raw boolean/integer literals would be incorrectly serialized as `"{}"` (e.g. `false` is serialized as `"{}"`).

[JS][Flow] Fix body serialization when body is falsy

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaClientCodegen.java
modules/openapi-generator/src/main/resources/scala-akka-client/operationReturnType.mustache
modules/openapi-generator/src/main/resources/scala-akka-client/responseState.mustache
samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/api/PetApi.scala
samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/api/StoreApi.scala
samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/api/UserApi.scala

- remove `onlyOneSuccess` (hidden) option
- fix return type
cc @clasnake (2017/07), @jimschubert (2017/09), @shijinkui (2018/01), @ramzimaalej (2018/03)

Fix Scala client (Akka) return type

---

pom.xml

To be sure that we do not have any SNAPSHOT versions in our dependencies, this PR adds an enforcer rule to check this at build time.

Add rule to maven-enforcer-plugin to prevent usage of SNAPSHOT versions

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptFlowtypedClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptInversifyClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptJqueryClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypeScriptNodeClientCodegenTest.java

fix #803 - npm version generated when snapshot set to true and npmversion is in a snapshot format too in typescript clients  :
- javascript flowedtype
- angular
- axios
- fetch
- inversify
- jquery
- node
- rxjs
added some test case

[TypeScript Client] fix npm version when snapshot is true 

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
Currently the java-resttemplate mustache templates will create an ApiClient class which fails the validation done by the javadoc-maven-plugin. This PR fixes this issue.

Fix JavaDoc errors in ApiClient for resttemplate

---

modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_opt_var.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_req_var.mustache
modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/models/ApiResponse.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/models/Category.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/models/Order.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/models/Pet.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/models/Tag.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/models/User.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/models/ApiResponse.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/models/Category.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/models/Order.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/models/Pet.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/models/Tag.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/models/User.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/models/ApiResponse.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/models/Category.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/models/Order.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/models/Pet.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/models/Tag.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/models/User.kt

Generating from a json file, if an API uses anything other than camelCase, the property names are not generated with the proper Json name. The generated code does not serialize/deserialize properly.
Adding a `@Json` annotation on the properties fixes it.

[BUG][Kotlin Client] API using case other than camelCase not generated properly

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinClientCodegenModelTest.java
samples/client/petstore/kotlin-string/docs/PetApi.md
samples/client/petstore/kotlin-string/docs/StoreApi.md
samples/client/petstore/kotlin-string/docs/UserApi.md
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-threetenbp/docs/PetApi.md
samples/client/petstore/kotlin-threetenbp/docs/StoreApi.md
samples/client/petstore/kotlin-threetenbp/docs/UserApi.md
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin/docs/PetApi.md
samples/client/petstore/kotlin/docs/StoreApi.md
samples/client/petstore/kotlin/docs/UserApi.md
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/Paths.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApiService.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApiServiceImpl.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/UserApi.kt

Fix Kotlin default value "null" with `null`
cc @jimschubert (2017/09), @dr4ke616 (2018/08)

Fix Kotlin default value

---

modules/openapi-generator/src/main/resources/Java/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/play24/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey1/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/retrofit/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/retrofit2rx/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java

and add helper methods.
- [X ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technica …

[Java] Instantiate HttpBearerToken authentications if so declared 

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java

And stringify UUIDs. Fixes #2484.
* Add complex types dependencies in operations;
* Correctly stringify UUIDs.
cc @wing328

[elm] Import types in operations

---

bin/utils/ensure-up-to-date
bin/windows/kotlin-springboot-petstore-server.bat
modules/openapi-generator/src/main/resources/kotlin-spring/service.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/serviceImpl.mustache
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApiService.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApiServiceImpl.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/UserApiService.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/UserApiServiceImpl.kt

see https://github.com/OpenAPITools/openapi-generator/pull/2538

[Kotlin SpringBoot Server] alternative: fix optional parameter not correctly declared in service

---

docs/migration-from-swagger-codegen.md

This is a fix for a small spelling error in migration-from-swagger-codegen.md.

Fixed typo in migration-from-swagger-codegen.md

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
modules/openapi-generator/src/main/resources/csharp/api.mustache
modules/openapi-generator/src/main/resources/csharp/modelGeneric.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharp/CSharpModelTest.java
samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools.Test/Model/PetTests.cs

Followed a similar pattern to how the new csharp-netcore generator handles nullable support. I added an additional testcase as well. It verifies that a property marked as *not*-nullable will not generate the nullable form of it's type. Also, I verify that types that don't support the nullable type shorthand aren't affected, ie. a **string**.  Please let me know if this is sufficient or if there are other cases you'd like me to capture.
I did not provide any files for the CI because it appears only the *csharp-dotnet2* client has files committed to the project. Please let me know if you'd like me to run the *csharp-petstore-all* script and commit everything that's generated.
I think this can resolve the client-side request for issue #2269 (@wing328, hopefully this helps! I also have a PR …

Csharp nullable support

---

modules/openapi-generator/src/main/resources/elm/elm.mustache
samples/client/petstore/elm/elm.json

> I ran the files, and there we're changes, but formatting only. It looks like they we're formatted with elm-format before, but not correctly or with a different version, when I ran the script. I didn't commit them.
This updates works with ISO 8601 strings with missing ending "Z". This
is e.g. the default configuration used by spring boot in java.
See <https://github.com/rtfeldman/elm-iso8601-date-strings/pull/18>

[elm] Update ISO 8601 library (fixes missing time zone designator)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java
modules/openapi-generator/src/main/resources/Javascript/es6/travis.yml
modules/openapi-generator/src/main/resources/Javascript/travis.yml
samples/client/petstore/javascript-es6/.travis.yml
samples/client/petstore/javascript-promise-es6/.travis.yml
samples/client/petstore/javascript-promise/.travis.yml
samples/client/petstore/javascript/.travis.yml

- fix NPE for null string
- improve Travis config file

[JS] fix NPE for null string and improve Travis config file

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java

Add packageName configuration to maven for Kotlin client generation.
Must fix #2428
@jimschubert @dr4ke616

Add packageName configuration to maven

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
samples/server/petstore/rust-server/output/rust-server-test/src/client/mod.rs

Added API Key authentication in rust-server for both in header and query. Still missing in cookie.
For query, since we're not available to modify `hyper` request after creating it, I added it to the `uri` created. To do this I had to move `let query_string = ...` outside of the `queryParams` block which means it'll be present even if there aren't any queryParams or query API Key. I think we can change this by creating an additional property to check for both conditions.
For header it was easier since we can use `header_mut` on request to add any new headers to it. I only added the variable `x-keyVarName` to vendor extensions in order to camel case the header.
One other downside to this is that we may need to refactor it in case of multiple API Keys in headers.

[rust-server] Added API Key auth to rust-server

---

docs/generators/csharp-netcore.md
docs/generators/csharp.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
modules/openapi-generator/src/main/resources/csharp/modelGeneric.mustache

Remove emitDefaultValue option from C# generators as it should be replaced by the `nullable` attribute in the spec.

Remove emitDefaultValue option from C# generators

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java

fix out-of-memory issue with nested objects with arrays with maxItems set by limiting to max. 5 example items
fixes #2503

#2503: fix out-of-memory issue with nested objects with arrays with maxItems set

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/auth/OAuth.mustache
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/auth/OAuth.java
samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/auth/OAuth.java

If OAuth server doesn't provide time of token expiration with the attribute 'expires_in' a NPE append.
With this change the time of expiration is never set (because we don't know it) so for each request we ask again a new token.
Closes #2561

[Java][Feign] Support OAuth without 'expires_in' data

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java

Default name changed for more usable one. For #2516
@wing328
@jimschubert
@cbornet
@ackintosh
@jmini

Change default inline object name

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSCXFCDIServerCodegen.java

fix #2593 
there's no purpose to use File.separator for default Java libraries path as "/" separator work on all platforms

[JAVA] remove File.separator use for default project/Test/source Folder

---

docs/usage.md
modules/openapi-generator-gradle-plugin/README.adoc
modules/openapi-generator-maven-plugin/README.md

[Doc] Better highlight of generators docs page with generators specific parameters

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache

[typescript-axios] Fix Bearer authentication
It was generated the same as Basic authentication. Now we handle both cases differently.
Fix #1446

[typescript-axios] Fix Bearer authentication

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java

Add `configuration` to reserved words list for typescript-fetch. Fixes: https://github.com/OpenAPITools/openapi-generator/issues/2564

Add configuration to reserved words list for typescript-fetch

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java

The `removeModelSuffixIfNecessary` method of `TypeScriptAngularClientCodegen` has been reworked to also remove prefix/suffix defined using `--model-name-prefix|suffix` options.
I have added a test to document the new behaviour.
Fixes #2560.

[Typescript-angular] fix handling of --model-name-prefix|suffix options

---

website/static/css/custom.css

Change the width and add allow wrap to the member's page. #2554
@wing328
@jimschubert
@cbornet 
@ackintosh 
@jmini

Fix #2554 wrap members

---

bin/windows/typescript-axios-petstore-all.bat
docs/generators/typescript-axios.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-axios/modelGeneric.mustache
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/api-response.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/category.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/order.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/pet.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/tag.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/model/some/levels/deep/user.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
samples/client/petstore/typescript-axios/tests/default/test/PetApi.ts
samples/client/petstore/typescript-axios/tests/default/test/PetApiFactory.ts

Removing namespaces from typescript-axios, according to suggestions made in #1947. Added "withoutPrefixEnums" option for disabling class name prefixing for enums. Tested new option locally and it works, but I'm not sure how to add new testcase cause "petstore.json" has overlappping enum names

[typescript-axios] removing namespaces from enums

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache

To fix https://github.com/OpenAPITools/openapi-generator/issues/1877
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)

Add free-form object support to TS fetch client generator

---

modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php

If you pass a PHP boolean value as a parameter in the query/path/form, this will serialize it as "true" or "false" instead of "1" or "".
Fixes #2204.

Send "true" or "false" for boolean params.

---

docs/generators/php-symfony.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
samples/server/petstore/php-symfony/SymfonyBundle-php/DependencyInjection/Compiler/OpenAPIServerApiPass.php
samples/server/petstore/php-symfony/SymfonyBundle-php/DependencyInjection/OpenAPIServerExtension.php
samples/server/petstore/php-symfony/SymfonyBundle-php/README.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/config/routing.yml
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/config/services.yml
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/docs/Api/PetApiInterface.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/docs/Api/StoreApiInterface.md
samples/server/petstore/php-symfony/SymfonyBundle-php/Resources/docs/Api/UserApiInterface.md

The alias of the Symfony's Bundle who is generate by Openapi was open_apiserver. However, it doesn't work it missing an underscore between api and server. The good alias is open_api_server.

correction of alias to generate php-symfony

---

bin/java-jaxrs-petstore-server-all.sh
modules/openapi-generator/src/main/resources/JavaJaxRS/api.mustache
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/FakeClassnameTags123Api.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/UserApi.java

Remove specific File management from template to align it with the service. 
fix #2474

 Fix JaxRS-Jersey template for files upload

---

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

It looks like `skipValidSpec` try to do the same thing than `validateSpec` so I've removed it because I think it can create wired behavior if both are set. 
But maybe I've missed something and I can do another solution.
Must fix #2319 and #2577
@wing328
@jimschubert
@cbornet
@ackintosh
@jmini

Remove SkipValidSpec option

---

new.sh

- fix #1795 : test path/package name for generated test in case of composed generated name (i.e  java-newframework)
- use the camelized generated name everywhere in the generation script (remove blank and underscore)
- add an error if no generator type are in parameter (i.e. ./new.sh -n 'java-greatframework' -t)
here is some test done with the new version of the script : 
```
$ ./new.sh -n 'java-greatframework' -s -t
Creating modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaGreatframeworkServerCodegen.java
Creating modules/openapi-generator/src/main/resources/java-greatframework-server/README.mustache
Creating modules/openapi-generator/src/main/resources/java-greatframework-server/model.mustache
Creating …
```

[New Generator shell] improve gen_name parsing

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ProcessUtils.java

- [x ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
Replaced occurrences of if (cs.isXxx) by if (Boolean.TRUE.equals(cs.isXxx)) in DefaultGenerator and ProcessUtils.

Null-safe check of CodegenSecurity Booleans (#2608)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/URLPathUtilsTest.java

If the server url is null I use the default url like it's done if the url is malformed.
Fix #2625
@wing328
@jimschubert
@cbornet
@ackintosh
@jmini

Fix NPE when server url is null

---

docs/generators/ruby.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
modules/openapi-generator/src/main/resources/lumen/composer.mustache
modules/openapi-generator/src/main/resources/php-symfony/composer.mustache
modules/openapi-generator/src/main/resources/php/composer.mustache
modules/openapi-generator/src/main/resources/ze-ph/composer.json.mustache
samples/client/petstore/php/OpenAPIClient-php/composer.json
samples/openapi3/client/petstore/php/OpenAPIClient-php/composer.json
samples/server/openapi3/petstore/php-ze-ph/application/config/path_handler.yml
samples/server/openapi3/petstore/php-ze-ph/composer.json
samples/server/openapi3/petstore/php-ze-ph/src/App/DTO/EnumTest.php
samples/server/openapi3/petstore/php-ze-ph/src/App/DTO/HealthCheckResult.php
samples/server/openapi3/petstore/php-ze-ph/src/App/DTO/NullableClass.php
samples/server/openapi3/petstore/php-ze-ph/src/App/DTO/OuterEnumDefaultValue.php
samples/server/openapi3/petstore/php-ze-ph/src/App/DTO/OuterEnumInteger.php
samples/server/openapi3/petstore/php-ze-ph/src/App/DTO/OuterEnumIntegerDefaultValue.php
samples/server/openapi3/petstore/php-ze-ph/src/App/Handler/FakeHealth.php
samples/server/petstore/php-lumen/lib/composer.json
samples/server/petstore/php-symfony/SymfonyBundle-php/composer.json
samples/server/petstore/php-ze-ph/composer.json

Clean up the license field in various templates to ensure it's unlicense by default.
- [DONE] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [DONE] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [DONE] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
Changes based on the discussion contained in: …

Clean up the license field in various templates.

---

modules/openapi-generator-maven-plugin/README.md
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

Aligning the option with CLI and Gradle Plugin, this keeps
`skipValidateSpec` and removes the redundant `validateSpec`.

[maven] remove validateSpec

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/RubyClientOptionsProvider.java

Move module/gem to codegen constant to make it consistent with Python/PHP/Perl/etc module/package/etc

Move Ruby module/gem to codegen constant

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/models.mustache

- [ x ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
The petsore.yaml for openapi3 doesn't include oneOf so there are no updates. See example output below.
- [ x ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ x ] Copied the [technical …

[TypeScript-Fetch] Generate oneOf schemas as type unions

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlimServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/slim/PhpSlimServerCodegenTest.java

fixes https://github.com/OpenAPITools/openapi-generator/issues/2402

Fix regexp error on php-slim

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java

Better handling of undefined inner property in array/map by defaulting the inner property to string.
cc @OpenAPITools/openapi-generator-core-team

Better handling of undefined inner property in array/map

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
samples/client/petstore/cpp-qt5/client/OAIPetApi.cpp
samples/client/petstore/cpp-qt5/client/OAIStoreApi.cpp
samples/client/petstore/cpp-qt5/client/OAIUserApi.cpp

Fix missing percent encoding in the path param. 
@stkrwork @ravinikam @MartinDelille @fvarose

[C++] [Qt5] Use percent encoding for path parameters

---

modules/openapi-generator/src/main/resources/php-slim-server/SlimRouter.mustache
samples/server/petstore/php-slim/lib/SlimRouter.php

Current generator requires `AbstractAuthenticator` user implementation when schema contains security definitions. When implementation class is provided app throws TypeError.
```
[10-Apr-2019 17:42:41 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to OpenAPIServer\Auth\AbstractAuthenticator::__construct() 
must implement interface Psr\Container\ContainerInterface, array given, called in 
/Applications/MAMP/htdocs/openapi-generator/samples/server/petstore/php-slim/lib/SlimRouter.php on line 650 and defined in 
/Applications/MAMP/htdocs/openapi-generator/samples/server/petstore/php-slim/lib/Auth/AbstractAuthenticator.php:70
```
Fixes #2640 
cc @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @ybelenko, @renepardon

[Slim] Fix AbstractAuthenticator constructor TypeError

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java

- fixed default package name in Go server generator
- reviewed other options which do not have the same issue
Fix https://github.com/OpenAPITools/openapi-generator/issues/2661
cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09)

Fix default package name in Go server generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfigLoader.java

This PR fixes the service loader initializations for `CodegenConfig` so that the correct class loader is used, regardless of the thread's context class loader.
This essentially fixes an issue that occurs when calling `CodegenConfigurator.toClientOptInput` from a thread that doesn't use the same class loader which is used to load `openapi-generator` module (e.g. build tool plugins), and as a result, generator names cannot be specified.
There's still an issue with code generation itself but that is related to the `swagger-parser` module; I'll file another PR there to fix that as well.

Fix ServiceLoader initialization

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptFlowtypedClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java

- fix #514  (for all typescript generator)
- sonar fixes on AbstractTypeScriptClientCodeGen class
- remove some overrided impl on JavascriptFlotypedClientCodeGen/AxiosCodeGen Class because it's the same impl as parent

[TypeScript] fix single quote in enums not escaped

---

modules/openapi-generator/src/main/resources/typescript-rxjs/package.mustache
samples/client/petstore/typescript-rxjs/builds/es6-target/package.json
samples/client/petstore/typescript-rxjs/builds/with-npm-version/package.json

Fixes #2667 by increasing the min version of typescript to `^3.0.1` to be in sync with rxjs (https://github.com/ReactiveX/rxjs/blob/master/package.json#L241) and fixing invalid `package.json`.

[typescript-rxjs] fix samples and invalid package.json

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-angular/package.mustache
modules/openapi-generator/src/main/resources/typescript-axios/package.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/package.mustache
samples/client/petstore/typescript-angular-v2/npm/package.json
samples/client/petstore/typescript-angular-v4.3/npm/package.json
samples/client/petstore/typescript-angular-v4/npm/package.json
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/package.json
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/package.json
samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/package.json
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/package.json
samples/client/petstore/typescript-axios/builds/es6-target/package.json
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/package.json
samples/client/petstore/typescript-axios/builds/with-npm-version/package.json
samples/client/petstore/typescript-fetch/builds/es6-target/package.json
samples/client/petstore/typescript-fetch/builds/with-npm-version/package.json

- update ng-packagr for angular 7 who don't use node-sass anymore (dependency vulnerability issue)
```
=== npm audit security report ===                        
SEMVER WARNING: Recommended action is a potentially breaking change
High            Arbitrary File Overwrite                                      
Package         tar                                                           
Dependency of   ng-packagr [dev]                                              
Path            ng-packagr > node-sass > node-gyp > tar                       
More info       https://nodesecurity.io/advisories/803         
```
the install and build of …

[TypeScript Angular] update ngpackagr version

---

samples/client/petstore/scala-akka/src/test/scala/PetApiTest.scala

Add tests for scala-akka client. Tests are incomplete and more of them are still in error, but it's a first step.

Add scala-akka tests

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/runtime.ts

My previous pull request #2234 that introduced support for nested objects in query strings contains a bug where an empty nested object will lead to two ampersands (`&`) in a row.
This patch adds a filter to remove empty parts before joining them with ampersands.

[typescript-fetch] Double ampersand in query string with empty nested object

---

modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache

Hello.
I confirmed that if you perform nullable on array in Spring, it is syntax error.
I tried to fix it, so please take a look if you like.

Add nullable array support in spring

---

modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java

Minor change. [2685](https://github.com/OpenAPITools/openapi-generator/issues/2685)
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog

[JAVA][Webclient]fix select body for url encoded media type.

---

docs/generators/aspnetcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
modules/openapi-generator/src/main/resources/aspnetcore/2.1/Project.csproj.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/README.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/Startup.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/controller.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/model.mustache

Support for async and Task for both library and program
Support for Controller and Model namespaces.
Small fixes and code generation clean up

[aspnetcore] Support async tasks and some code cleanups

---

modules/openapi-generator/src/main/resources/JavaSpring/api.mustache

If for java spring-boot template generator we combine `reactive` and `interfaceOnly` properties then openapi generator generates incorrect code.
Example without fix:
```java
default Mono<ResponseEntity<ResponseWrapper>> _methodName(@ApiParam(value = ""  )  @Valid @RequestBody Mono<RequestWrapper> requestWrapper, ServerWebExchange exchange) {
return methodName(requestWrapper);
}
// Override this method
default Mono<ResponseEntity<ResponseWrapper>> methodName(RequestWrapper requestWrapper, ServerWebExchange exchange) {
Mono<Void> result = Mono.empty();
exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
result = …
```

[Java][Spring] Fix template for reactive implementation with `interfaceOnly` parameter

---

modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache

After running the generator for the Java-webclient target, I noticed a syntax error caused by a missing closing paren.

Add missing closing parenthesis

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/play24/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache

Fix missing parenthesis for Http Bearer authentication in Java clients

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache

Header parameters are broken in the `cpp-qt5-client` due to quotation of the `{{paramName}}` value -- the name of the parameter is used instead of the value. Remove quotation marks.
Fixes issue [2726](https://github.com/OpenAPITools/openapi-generator/issues/2726).

[BUG][cpp-qt5-client] Header params in api-body operations use param name instead of value

---

modules/openapi-generator/src/main/resources/python/rest.mustache
samples/client/petstore/python/petstore_api/rest.py
samples/openapi3/client/petstore/python/petstore_api/rest.py

fix #2623
Accept body as bytes to support binary content types like application/octet-stream

[Bug][Python]Support body as bytes when Content-Type is unknown

---

modules/openapi-generator/src/main/resources/ruby-client/api.mustache
samples/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/client/petstore/ruby/lib/petstore/api/user_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/default_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/user_api.rb

We want to change the option when debugging, changing timeout to specific api, etc...
So we want to merge and pass options to api client.

Pass opts argument to api client in ruby-client

---

modules/openapi-generator-core/src/main/java/org/openapitools/codegen/api/AbstractTemplatingEngineAdapter.java
modules/openapi-generator-core/src/main/java/org/openapitools/codegen/api/TemplatingEngineAdapter.java
modules/openapi-generator-core/src/main/java/org/openapitools/codegen/api/TemplatingGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/TemplatingEngineLoader.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/HandlebarsEngineAdapter.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/MustacheEngineAdapter.java
modules/openapi-generator/src/main/resources/META-INF/services/org.openapitools.codegen.api.TemplatingEngineAdapter

Allows for loading templating engine via ServiceLoader. Allows for user customization.

[templating] Load TemplatingEngineAdapter via Service Provider

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java

For python connexion servers:
This fixes adding supporting files to packages that have a '.'.
If the controllersPackage or modelsPackage has a '.' (eg to put the
controllers and/or models in a subpackage of the invokerPackage),
supporting controller and models were ending up in directories that
included the period instead of converting the periods to file
separators.

[Python Connexion Servers] BUGFIX: handle . in package names

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-angular/model.mustache
modules/openapi-generator/src/main/resources/typescript-angular/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-aurelia/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-aurelia/models.mustache
modules/openapi-generator/src/main/resources/typescript-axios/api.mustache
modules/openapi-generator/src/main/resources/typescript-axios/model.mustache
modules/openapi-generator/src/main/resources/typescript-axios/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-inversify/model.mustache
modules/openapi-generator/src/main/resources/typescript-inversify/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-jquery/model.mustache
modules/openapi-generator/src/main/resources/typescript-jquery/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/models.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/package.mustache
modules/openapi-generator/src/test/resources/3_0/oneOf.yaml
samples/client/petstore/typescript-aurelia/default/models.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/package.json
samples/client/petstore/typescript-rxjs/builds/with-npm-version/package.json

- as #2617 but for all other typescript generator 
- fix rxjs package.json (comma)
- fix oneOf.yaml not in yaml format

[TypeScript] Generate oneOf schemas as type unions

---

modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
modules/openapi-generator/src/main/resources/csharp/modelGeneric.mustache

@mandrean @jimschubert @wing328 
This PR is a reference to #2760. I did run the shell scripts locally, but I wasn't sure if I did it correctly. Therefore I first created the issue (#2760) and @wing328 suggested to open a PR to get additional help. 
Thanks!

[C#] Additional null check before doing SequenceEqual check

---

modules/openapi-generator/src/main/resources/cpp-pistache-server/main-api-server.mustache
samples/server/petstore/cpp-pistache/main-api-server.cpp

Fixes #2771
- Allow socket payload size override
- Set socket address reuse option
@stkrwork @MartinDelille @ravinikam @fvarose

[C++][Pistache] Allow socket address reuse option

---

modules/openapi-generator/src/main/resources/cpp-pistache-server/model-source.mustache
samples/server/petstore/cpp-pistache/model/ApiResponse.cpp
samples/server/petstore/cpp-pistache/model/Category.cpp
samples/server/petstore/cpp-pistache/model/Order.cpp
samples/server/petstore/cpp-pistache/model/Pet.cpp
samples/server/petstore/cpp-pistache/model/Tag.cpp
samples/server/petstore/cpp-pistache/model/User.cpp

@etherealjoy @stkrwork @ravinikam @MartinDelille @fvarose 
Fixed checking for optional properties when converting from json. Using 'at' on a key that doesn't exist throws an exception. Was replaced with 'contains'. This resolves issues #2734.
Fixes #2734

[C++][Pistache] Fixed checking for optional properties when converting from json.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java

Fixes #2759.
For arrays of enums, the elm prefix is added four times, instead of once.
cc @wing328

[elm] Fix repetitive enum prefixes

---

modules/openapi-generator/src/main/resources/dart2/class.mustache
samples/client/petstore/dart2/flutter_petstore/openapi/lib/api_client.dart
samples/client/petstore/dart2/flutter_petstore/openapi/lib/model/api_response.dart
samples/client/petstore/dart2/flutter_petstore/openapi/lib/model/category.dart
samples/client/petstore/dart2/flutter_petstore/openapi/lib/model/order.dart
samples/client/petstore/dart2/flutter_petstore/openapi/lib/model/pet.dart
samples/client/petstore/dart2/flutter_petstore/openapi/lib/model/tag.dart
samples/client/petstore/dart2/flutter_petstore/openapi/lib/model/user.dart
samples/client/petstore/dart2/openapi-browser-client/lib/api_client.dart
samples/client/petstore/dart2/openapi-browser-client/lib/model/api_response.dart
samples/client/petstore/dart2/openapi-browser-client/lib/model/category.dart
samples/client/petstore/dart2/openapi-browser-client/lib/model/order.dart
samples/client/petstore/dart2/openapi-browser-client/lib/model/pet.dart
samples/client/petstore/dart2/openapi-browser-client/lib/model/tag.dart
samples/client/petstore/dart2/openapi-browser-client/lib/model/user.dart
samples/client/petstore/dart2/openapi/lib/api_client.dart
samples/client/petstore/dart2/openapi/lib/model/api_response.dart
samples/client/petstore/dart2/openapi/lib/model/category.dart
samples/client/petstore/dart2/openapi/lib/model/order.dart
samples/client/petstore/dart2/openapi/lib/model/pet.dart
samples/client/petstore/dart2/openapi/lib/model/tag.dart
samples/client/petstore/dart2/openapi/lib/model/user.dart

This fix would avoid adding and sending fields that are not isNullable in the request.
This is the correct fix for the issue #2535 as discussed earlier. Self-explanatory in commit message.
@ircecho @swipesight  @jaumard  @wing328

dart2: Do not add non-nullable fields to model json

---

README.md
bin/openapi3/scala-akka-petstore.sh
bin/openapi3/scala-httpclient-petstore.sh
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/PhpSlimServerOptionsProvider.java
modules/openapi-generator/src/test/resources/integrationtests/scala/client/required-attributes.sh

For 4.0.0, we've removed the "lang" option. This removes any mappings
from swagger-codegen "lang" to openapi-generator "generator" options.

[general] Remove swagger-codegen "lang" mappings

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java

Fixes #2024
- Fixes import of model header due to rework (similar to #2168, #2750, #2744) 
- sanitizing the name is done in `AbstractCppCodegen` already so not needed twice
@stkrwork @ravinikam @MartinDelille @fvarose

[C++][Pistache]Fix import of model header

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5QHttpEngineServerCodegen.java
modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/README.md.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/main.cpp.mustache

Add listening of the socket on the server port defined in spec
`cc`
@stkrwork  @MartinDelille  @ravinikam  @fvarose

[C++][Qt5 Server] Process server port

---

modules/openapi-generator/src/main/resources/aspnetcore/2.0/Dockerfile.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/Dockerfile.mustache
samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Dockerfile

Switch dotnet image registry to MCR to pull latest sha for dotnet tags
Please see
https://github.com/dotnet/announcements/issues/101
https://devblogs.microsoft.com/dotnet/net-core-container-images-now-published-to-microsoft-container-registry/
@jimschubert @wing328

[ASP.NET Core]Switch registry to MCR for dotnet images

---

docs/generators/typescript-axios.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java

- fix using withSeparateModelsAndApi and withoutPrefixEnums in cli with additional-properties option reach a ClassCastException (fix #2709)
- fix typos in specific properties description

[TypeScript-axios] fix using withSeparateModelsAndApi and withoutPrefixEnums with additional-properties option

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelEnumTest.java

During Swagger-Parser Update #2775, I have noticed some regression.
This test ensure that we do not have any regression when we update Swagger-Parser. With version `2.0.12` this test is not green because of https://github.com/swagger-api/swagger-parser/issues/1090.

Add Enum_Test test

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpDotNet2ClientCodegen.java

Add warning about .net 2.0 framework reached EOL

Add warning about .net 2.0 framework reached EOL

---

README.md
docs/usage.md
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
modules/openapi-generator-cli/src/test/java/org/openapitools/codegen/cmd/GenerateTest.java
modules/openapi-generator-maven-plugin/README.md
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultGeneratorTest.java

Introduces an option to allow user customization of strict specification
behaviors. For instance, OpenAPI 3.x requires a path object name to be
prefixed with '/' so we append any missing '/', but this may not be
desirable to some users or generators. In this commit, this fix specifically is
the only modification affected.
Adds an option which allows users to disable any strict specification behaviors applied during generation. For example, #1034 introduces a modification which prefixes all paths missing a beginning slash to better fit "MUST" definitions in the OpenAPI Specification 3.x. Ideally, this behavior would be rolled up into the parser (i.e. if we've validated via the parser, we shouldn't need to fix the spec document).
Such a switch is necessary because, as discussed in #2702, …

[all] Adds strict spec option

---

modules/openapi-generator/src/main/resources/elm/modelTypeDiscriminator.mustache

The function is called `encode`. This fixed the call.
See https://github.com/OpenAPITools/openapi-generator/blob/dfa7e616c0f311f3ebf58c04287f200c8e491f08/modules/openapi-generator/src/main/resources/elm/modelTypeArray.mustache#L11
I have encountered this issue, and this is probably an easy fix.
@eriktim Can you have a short look?

[Elm] Bugfix .encode in modelTypeDiscriminator

---

.github/PULL_REQUEST_TEMPLATE.md

PR template seems to assume contributor is compiling the project, and would have had "latest" build completed locally. New contributors making template or documentation changes may not have built the project at all, and wouldn't know to do so based on previous PR template instructions.

Clarifies need to build project for sample output

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

- better form data detection
- better handling of content-type (show a warning message if content-type cannot be detected)
- minor code format

Better handling of form data

---

.travis.yml

Use mvn instead of run-in-docker to avoid timeout in Docker.

Use mvn instead of run-in-docker

---

modules/openapi-generator/src/main/resources/Javascript/es6/README.mustache
samples/client/petstore/javascript-es6/README.md
samples/client/petstore/javascript-promise-es6/README.md

I am not sure the unchecked box apply for documentation, please correct me if I am wrong.
This is a simple documentation PR to add the `npm run build` in the documentation (which was not required previously.

[Documentation] Add instructions to build the javascript client module

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java

@jimschubert (2017/09), @dr4ke616 (2018/08)  @Zomzog (2019/04)
a var with all upper case and numbers (e.g `USER123NAME`)  is incorrectly converted to (e.g `usER123NAME`) and the getter/setter generated is wrong (e.g `getUsER123NAME()`)
with the fix (following the all upper case var rule) :
`USER123NAME` stay `USER123NAME` and the getter is `getUSER123NAME()`
thanks to @JorgeMorata to detect this issue

[JAVA][KOTLIN] fix var Naming for all uppercase with Numbers

---

docs/templating.md
modules/openapi-generator-core/src/main/java/org/openapitools/codegen/api/TemplatingGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

Document new templating engine, adding the ability to reference templates by file to complete the example
Adds documentation around new templating engine support, and calls out that this support is consider experimental. This means we may modify the interfaces or remove support until we no longer consider it "experimental".

[docs] Document new templating engine, adding ability to reference templates

---

modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache

for typescript-angular client
https://swagger.io/docs/specification/describing-request-body/file-upload/
fix Multiple File Upload 
it was broken for typescript-angular  client 
from link above 
Use the multipart media type to define uploading an arbitrary number of files (an array of files):
requestBody:
content:
schema:
type: object
properties:
filename:
type: array
items:
type: string
format: binary
was broken 
did not generated proper HTTP request 

fix multiple file upload

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java

@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)
Escapes single quotes, so that the generated code does not break.

[Python][R] Escape single quotes in strings (#2808)

---

modules/openapi-generator/src/main/resources/go/client.mustache
samples/client/petstore/go/go-petstore/client.go

This changes go clients to append the multipart boundary parameter to the content type header independent of file content being present. This fixes #2772, which is an issue with pure multipart formdata.
1. I've ran `./bin/go-petstoresh` and updated the sample client. I'm not sure if I need ro run `./bin/go-petstore-withxml.sh` too?
2. How should I go about adding tests for this?
cc @antihax @bvwells @grokify @kemokemo

[go] fix multipart for non-file inputs

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java

cc. @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce
The TS generator prods you about setting `TS_POST_PROCESS_FILE` but when you set it, it doesn't have any effect, because you also need to include the `--enable-post-process-file` param in order for this to do anything.
This PR adds additional messages to make this requirement explicit.

[Typescript] Warn about unset post-processing param

---

samples/server/petstore/nodejs-express-server/.eslintrc
samples/server/petstore/nodejs-express-server/.openapi-generator/VERSION
samples/server/petstore/nodejs-express-server/config.js
samples/server/petstore/nodejs-express-server/config.json
samples/server/petstore/nodejs-express-server/expressServer.js
samples/server/petstore/nodejs-express-server/index.js
samples/server/petstore/nodejs-express-server/package.json
samples/server/petstore/nodejs-express-server/tests/serverTests.js

Created an expressServer.js file/class, which launches an express.js server, initializing some of the required middleware. At this point we have a server working and showing the swagger/openApi documentation when you go to http://localhost:3000/api-docs.

Express server working, api-docs loads properly. Routing not working yet

---

docs/generators/java-msf4j.md
docs/generators/jaxrs-cxf-cdi.md
docs/generators/jaxrs-cxf-extended.md
docs/generators/jaxrs-cxf.md
docs/generators/jaxrs-jersey.md
docs/generators/jaxrs-resteasy-eap.md
docs/generators/jaxrs-resteasy.md
docs/generators/jaxrs-spec.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaJAXRSServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaVertXServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
samples/server/petstore/jaxrs-spec-interface/src/main/openapi/openapi.yaml
samples/server/petstore/jaxrs-spec/src/main/openapi/openapi.yaml

when not provided by generator option
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @Zomzog (2019/04)
fix #1815 
fix #2033 PR feature :
- If no artifactVersion is provided in additional properties, version from API specification is used. If none of them is provided then fallbacks to default version (1.0.0)

[JAVA] fix artifactVersion is not taken from specification 

---

modules/openapi-generator/src/main/resources/typescript-rxjs/README.mustache

Fixed wrong reference to fetch instead of rxjs
- [] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
Fixed reference to wrong library in readme

Update typescript-rxjs readme to reference rxjs instead of fetch library

---

modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
samples/client/petstore/javascript-es6/src/ApiClient.js
samples/client/petstore/javascript-promise-es6/src/ApiClient.js
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript/src/ApiClient.js

The `enum_values` check only happens when `enum_values` exist.
Related issue: #2852 
Should I also add the modifications in resources/Javascript ?
@CodeNinjai
@frol
@cliffano

JS Client - Add support for empty enum in server object

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java

Disable jdk8 when using responseWrapper.
Fix #2872

Disable jdk8 when using responseWrapper

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/FsharpGiraffeServerCodegen.java

Tagging @nmfisher - autocomplete does not work, dunno if something is broke, sent him a mail though.
Error:(21, 46) java: package sun.reflect.generics.reflectiveObjects does not exist
This error happens on Manjaro Linux with JDK10, is this required on older JDKs?

[F#][Giraffe] Remove unused import

---

modules/openapi-generator/src/main/resources/dart/pubspec.mustache
modules/openapi-generator/src/main/resources/dart2/pubspec.mustache
samples/client/petstore/dart/flutter_petstore/openapi/pubspec.yaml
samples/client/petstore/dart/openapi-browser-client/pubspec.yaml
samples/client/petstore/dart/openapi/pubspec.yaml

@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09)
Dart 2.3.0 no longer works with http 0.11.+

dart2: update to work with dart 2.3.0

---

docs/generators/javascript-flowtyped.md
docs/generators/typescript-angular.md
docs/generators/typescript-aurelia.md
docs/generators/typescript-axios.md
docs/generators/typescript-fetch.md
docs/generators/typescript-inversify.md
docs/generators/typescript-jquery.md
docs/generators/typescript-node.md
docs/generators/typescript-rxjs.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptFlowtypedClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularJsClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAureliaClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptInversifyClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptJqueryClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAureliaClientOptionsProvider.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypeScriptNodeClientCodegenTest.java

cc @lalau
same as PR #2810 but for all typescript generator :  
- If no npmVersion is provided in additional properties, version from API specification is used. If none of them is provided then fallbacks to default version (1.0.0) 
- Refactoring npmName, npmVersion and Snapshot cliOptions (now defined in Abstract Class)

[Typescript] gets package npm version from API specification

---

docs/generators/groovy.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractApexCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GroovyClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
modules/openapi-generator/src/main/resources/Groovy/api.mustache
samples/client/petstore/groovy/src/main/groovy/org/openapitools/api/PetApi.groovy
samples/client/petstore/groovy/src/main/groovy/org/openapitools/api/StoreApi.groovy
samples/client/petstore/groovy/src/main/groovy/org/openapitools/api/UserApi.groovy

- improve code parsing body/form params
- add removeOption for CliOptions in DefaultCodeGen class 
- remove overrided method identical to parent (AbstractJavaCodeGen and AbstractApexCodeGen)

[Groovy] improve code parsing body/form params

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

a minor fix of PR #2798 :
when the artifactVersion is set (by additional properties or in spec files) , the snapshot parameter properties (set to true) is actually ignored

[JAVA] fix artifactVersion overriding snapshot parameter when set

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default/models/Category.ts
samples/client/petstore/typescript-fetch/builds/default/models/ModelApiResponse.ts
samples/client/petstore/typescript-fetch/builds/default/models/Order.ts
samples/client/petstore/typescript-fetch/builds/default/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/default/models/Tag.ts
samples/client/petstore/typescript-fetch/builds/default/models/User.ts
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/models/Category.ts
samples/client/petstore/typescript-fetch/builds/es6-target/models/ModelApiResponse.ts
samples/client/petstore/typescript-fetch/builds/es6-target/models/Order.ts
samples/client/petstore/typescript-fetch/builds/es6-target/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/es6-target/models/Tag.ts
samples/client/petstore/typescript-fetch/builds/es6-target/models/User.ts
samples/client/petstore/typescript-fetch/builds/es6-target/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/models/Category.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/models/ModelApiResponse.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/models/Order.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/models/Tag.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/models/User.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/models/Category.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/models/ModelApiResponse.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/models/Order.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/models/Tag.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/models/User.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/runtime.ts

cc. @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce
- Add support for openapi maps/dictionaries to be generated as typescript map.
- Fix is `.mustache` files only.
- Reason for PR: consumption of openapi api with [map collections](https://swagger.io/docs/specification/data-models/dictionaries/). The typescript-fetch generator failed to create working code by mapping it as an array.
- related previous issue: #1878

Feature/typescript fetch/map templating

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java

@asnelling It seems like you're the person to review this one.
This fixes #2904
The namedCredential property is intended to override the namedCredentials name, but it wasn't being used. Instead, the title from the openapi spec file was used in all cases, and the namedCredential property wasn't used anywhere.
If a namedCredential property is provided, it will be used instead of the default name. For backwards compatibility, the spec title is still used for the named credential by default.

[Apex] Set namedCredential file name from the property

---

.travis.yml

Limited reviewer request since this is a fairly simple change. #2388 introduced a somewhat cyclical dependency (`openapi-generator-cli` -> `openapi-generator` -> `openapi-generator-cli`). @jmini is working on an alternative method to enable better debugging during new generator development. As discussed in chat, we'd want this to fail in CI and the fix would be to avoid caching openapitools artifacts across builds.
This will likely fail until Jérémie's work is available and merged.

[build] Avoid caching openapitools* artifacts

---

modules/openapi-generator/src/main/resources/php/api.mustache
samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php

[PHP] Fix group parameters in WithHttpInfo method

---

bin/windows/csharp-petstore.bat
modules/openapi-generator/src/main/resources/csharp/Project.mustache
samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Org.OpenAPITools.csproj

[C#] Enabling XML documentation in the C# client

---

modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

To parse a model using custom fields, KotlinJsonAdapterFactory needs to be added to moshi's Adapter. 
- Fix parse error when using custom field names with @Json
- Fix to use isEmpty method for string length verification

[Kotlin] Fix parse error when using custom field names with @Json

---

modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

Some minor improvements to the kotlin-client template. Use `val` instead of `var` where possible. Use `.apply{}` combined with the builder pattern. Use `map[key] = value` instead of `map.put(key, value)`.
@jimschubert @dr4ke616 @karismann @Zomzog

improve Kotlin code quality

---

modules/openapi-generator/src/main/resources/typescript-axios/api.mustache
modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts

Sometime we have api params named url that will conflict with imported module url named url.

To fix conflict params name 'url'

---

modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/Serializer.kt.mustache
samples/client/petstore/kotlin-string/build.gradle
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin-threetenbp/build.gradle
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
samples/client/petstore/kotlin/build.gradle
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt

@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @Zomzog (2019/04)
cc @lemoinem 
- fix Moshi (Serializer/Deserializer)  duplicated  (fix #3004)
- update Moshi / okhttp version to latest

[KOTLIN client] fix Moshi (Serializer/Deserializer)  duplicated

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java
modules/openapi-generator/src/main/resources/elm/api.mustache
samples/client/petstore/elm/src/Request/Pet.elm

Enumerations are interpreted as strings in Elm operations. This PR fixes this.
Fixes #2585.

Add support for enums in Elm operations

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api_doc.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/AnotherFakeApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/PetApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/StoreApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/UserApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/okhttp-gson/docs/AnotherFakeApi.md
samples/client/petstore/java/okhttp-gson/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/okhttp-gson/docs/PetApi.md
samples/client/petstore/java/okhttp-gson/docs/StoreApi.md
samples/client/petstore/java/okhttp-gson/docs/UserApi.md
samples/client/petstore/java/okhttp-gson/pom.xml
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/UserApi.java

#2994 
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog

[java-okhttpgson]: Include API's Http response codes and their corresponding description and response headers in the documentation

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/README.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api_doc.mustache
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/AnotherFakeApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/PetApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/StoreApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/UserApi.md
samples/client/petstore/java/okhttp-gson/docs/AnotherFakeApi.md
samples/client/petstore/java/okhttp-gson/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/okhttp-gson/docs/PetApi.md
samples/client/petstore/java/okhttp-gson/docs/StoreApi.md
samples/client/petstore/java/okhttp-gson/docs/UserApi.md

#3017  
Make example snippets code compilable. Also, specify how to access response message and headers in case of request failure.

[java-okhttp]: Make example snippets code compilable

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java

#2991 
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess

[Python] ModuleNotFoundError when packagename contains dots

---

modules/openapi-generator/src/main/resources/aspnetcore/2.1/model.mustache

ASPNET Core uses the attribute RegularExpression to validate the model state. This is supported in OpenAPI spec with the 'pattern' property.
This PR adds the reg-ex attribute to the model codegen.

Added support for patterns on model properties

---

modules/openapi-generator-maven-plugin/README.md

Add new option to maven plugin's readme

Add new option to maven plugin's readme

---

modules/openapi-generator/src/main/resources/go-gin-server/routers.mustache
samples/server/petstore/go-gin-api-server/go/routers.go

This commit modifies the gin template for the router to leverage the http constants for method types as defined by RFC 7231 section 4.3. These are documented on:
https://golang.org/pkg/net/http/#pkg-constants
This removes the need for the `strings` dependency and does not require any new dependencies, as `net/http` is already imported.

Use golang's provided method names (gin)

---

modules/openapi-generator/src/main/resources/go/client.mustache
samples/client/petstore/go/go-petstore/client.go

@antihax @bvwells @grokify @kemokemo 
This checks the unhandled error returned from the xml Encoder. This will return an error if the user provides a `Content-Type` matching xml with an incorrect body
The method header is [here](https://golang.org/pkg/encoding/xml/#Encoder.Encode)
`func (enc *Encoder) Encode(v interface{}) error `

fix(golang): Check error of xml Encode

---

.travis.yml
modules/openapi-generator-gradle-plugin/build.gradle
modules/openapi-generator-gradle-plugin/pom.xml
modules/openapi-generator-gradle-plugin/settings.gradle

TravisCI proxies separate external requests with different orginating IP
addresses, while Sonatype associates artifacts for auto-generated
repositories by IP address. This leads to many gradle deploys from CI
resulting in "split" staging repositories with no way to combine in
Sonatype Nexus.
This introduces a workflow which should resolve this issue on the next
revision release. Specifically, nexus-publish-plugin is included to
create singular staging repositories from TravisCI and
gradle-nexus-staging-plugin is included to auto-release and promote
this repository.
NOTE:
We need to publish via `publishPluginMavenPublicationToNexusRepository`,
because `publishToNexus` will publish _all_ publish-related tasks,
including the one intended only for the Gradle Plugin Portal.
Tested in …

[gradle] Reworking publishing pipeline

---

README.md
modules/openapi-generator-cli/pom.xml
modules/openapi-generator-core/pom.xml
modules/openapi-generator-gradle-plugin/README.adoc
modules/openapi-generator-gradle-plugin/pom.xml
modules/openapi-generator-gradle-plugin/samples/local-spec/README.md
modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties
modules/openapi-generator-maven-plugin/README.md
modules/openapi-generator-maven-plugin/examples/java-client.xml
modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml
modules/openapi-generator-maven-plugin/examples/non-java.xml
modules/openapi-generator-maven-plugin/pom.xml
modules/openapi-generator-online/pom.xml
modules/openapi-generator/pom.xml
pom.xml
samples/meta-codegen/lib/pom.xml

Prepare 4.0.1 release

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5AbstractCodegen.java

Fixes #3037
`Changes:`
- Map `float` and `double` to `double` since `QJsonObject` always treat `float` and `double` as `double`
`cc:` @stkrwork @MartinDelille @ravinikam @wing328

[C++][Qt5]Map number to double since float is also parsed as double in Qt5

---

modules/openapi-generator/src/main/resources/ruby-client/api.mustache
samples/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/client/petstore/ruby/lib/petstore/api/user_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/default_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/user_api.rb

Path parameters should be escaped when encoded into the path.
In the path '/pet/{petId}' let's pretend petId is a string instead of a
number.
If the user uses "Bobby" as the petId then they correctly get the path
'/pet/Bobby'.
But if they put 'Bobby/Tables' as the petId then they used to get the
path '/pet/Bobby/Tables' which will be interpreted by the server as a
different route.
Using CGI::Escape they now get '/pet/Bobby%2FTables' which is correct.
Ruby technical committee:
See top

Ruby client: escape path parameters

---

README.md

Update CI badges to 4.1.x
Update CI badges to 4.1.x

Update CI badges to 4.1.x

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/api.mustache
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/api/UserApi.java

Closes:#3042
Fixing javadoc warnings.

fix(java-jersey2): Fixing javadocs warnings

---

modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
samples/client/petstore/javascript-promise/src/ApiClient.js
samples/client/petstore/javascript/src/ApiClient.js

This removes some syntax for "default parameters" from the JavaScript client. The reason is that it's a ES6 feature that [doesn't work on IE11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility)
cc @CodeNinjai @frol @cliffano

[JavaScript] Remove default parameters syntax, as it's an ES6 feature

---

modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/returnValue.mustache
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/UserApi.kt

Fixed consumes/produces comma placement.
Sometimes following happened: produces = ["application/json", ],
- a comma was placed after last element. I susupect that an empty consumes/produces element is somehow added to the list. 
Changed default response code in interface returnValue from HttpStatus.OK to first response code in definition. Allowing other responses, like created, accepted ...

Kotlin-Spring template fixes/improvements

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

Introduced with #2783, the `strictSpec` parameter causes the an error in the `4.0.1` maven plugin:
```
[ERROR] Failed to execute goal org.openapitools:openapi-generator-maven-plugin:4.0.1:generate (generate-client-code): Unable to parse configuration of mojo org.openapitools:openapi-generator-maven-plugin:4.0.1:generate for parameter strictSpec: Cannot find 'strictSpec' in class org.openapitools.codegen.plugin.CodeGenMojo -> [Help 1]
```
This PR is about to fix it.

[maven-plugin] fix strictSpec parameter

---

appveyor.yml
modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties

As discussed with @wing328  and @jimschubert during the `4.0.1` release, we would like to use SNAPSHOT version in the samples.
For the maven samples, this was solved with #3047. See [openapi-generator/modules/openapi-generator-maven-plugin/examples/
](https://github.com/OpenAPITools/openapi-generator/tree/dc81574f2b53e33fe7e8a5f93a5b79645424c3a0/modules/openapi-generator-maven-plugin/examples) folder.
For Gradle this PR is fixing this.
If the user do not have built the plugin locally, it will still work because of this section:
https://github.com/OpenAPITools/openapi-generator/blob/afcbab4d924a1ce740a4f833c8a1db20aa078ec8/modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle#L11-L13
Then gradle will download the SNAPSHOT version from the distant maven repository.

Use 4.0.2-SNAPSHOT version in gradle samples

---

.travis.yml
CI/circle_parallel.sh
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
shippable.yml

- Test maven plugin in Travis
- move jobs from Shippable to Circle CI

[CI] Test maven plugin in Travis, move jobs from Shippable to Circle CI

---

docs/generators/go.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
modules/openapi-generator/src/main/resources/go/go.mod.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/GoClientOptionsProvider.java

CC @antihax @bvwells @grokify @kemokemo
This allows generating the go client package as a submodule as requested in https://github.com/OpenAPITools/openapi-generator/issues/2940
I *think* the only template that needed to be fixed was `go.mod.mustache`, but I'll appreciate thorough review to find out if that's really correct.
Since I added this as an optional feature and turned it off by default, no files were touched by this change in the `samples` directory.

[Golang][client] Allow generating go client code as a submodule

---

modules/openapi-generator/src/main/resources/ruby-client/api.mustache
modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache
modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
samples/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/client/petstore/ruby/lib/petstore/api/user_api.rb
samples/client/petstore/ruby/lib/petstore/api_client.rb
samples/client/petstore/ruby/lib/petstore/configuration.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/default_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/pet_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/store_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api/user_api.rb
samples/openapi3/client/petstore/ruby/lib/petstore/api_client.rb
samples/openapi3/client/petstore/ruby/lib/petstore/configuration.rb

`URI.encode` is obsolete. `CGI.escape`, `URI.encode_www_form` or
`URI.encode_www_form_component` are recommended instead.
https://ruby-doc.org/stdlib-2.6/libdoc/uri/rdoc/URI/Escape.html#method-i-escape
URI.encode has different behaviour to CGI.escape:
```ruby
URI.encode('hello/world?test%string')
=> "hello/world?test%25string"
CGI.escape('hello/world?test%string')
=> "hello%2Fworld%3Ftest%25string"
```
I recently raised pull request #3039
201cbdce29cc6cdbbbe9efcb1afb250a05bc2ffd
That pull request escapes path items at insertion.
Before either pull request, the path item 'hello?world' would go into
the URL as 'hello?world'. That behaviour was insecure as if an attacker
could control the path item value, they could change the URL the
application connected to.
After #3039 'hello?world' would …

Ruby: Avoid double escaping path items

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

Introduced with #2783, the `strictSpec` parameter causes the an error in the `4.0.1` maven plugin:
```
[ERROR] Failed to execute goal org.openapitools:openapi-generator-maven-plugin:4.0.1:generate (generate-client-code): Unable to parse configuration of mojo org.openapitools:openapi-generator-maven-plugin:4.0.1:generate for parameter strictSpec: Cannot find 'strictSpec' in class org.openapitools.codegen.plugin.CodeGenMojo -> [Help 1]
```
This PR is about to fix it as discussed in https://github.com/OpenAPITools/openapi-generator/pull/3071#issuecomment-498772768

[maven-plugin] fix strictSpec parameter without alias

---

modules/openapi-generator/src/main/resources/scala-play-server/app/apiDocController.scala.mustache
samples/server/petstore/scala-play-server/app/api/ApiDocController.scala

A simple typo fix. When navigating to the API doc url (`/api`) the swagger-ui is supposed to show the OpenAPI spec that was used to generate the project, but it shows the generic petstore instead. This happens because the query parameter name is invalid - `/url` instead of `url`. When the slash is removed the API docs are shown as intended.

[scala-play-server] Fix API doc url

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaPlayFrameworkServerCodegen.java

This is a bugfix for the Scala-Play language.  
When an enum property's name is a reserved word in Scala, it is escaped with backticks (in `AbstractScalaCodegen`) so the generated code can compile. However, generating code with backticks is a bit tricky - the name must start and end with a backtick else the code doesn't compile.
In Scala-Play language, when enum properties are generated, the enum definition is contained inside the companion object of the model. The name of the enum is camelized (as per `toEnumName` method). To be able to serialize the enums, a corresponding JSON format must be introduced as well, named `<EnumName>JsonFormat`. If the enum name contains backticks (as is the case with a reserved word), the JSON format will contain backticks that are not properly terminated. …

[scala-play-server] Fix generated enums named after a reserved word

---

modules/openapi-generator-gradle-plugin/README.adoc

Add documentation notes for consuming via Gradle Plugin Portal
See #2505

[gradle] Document consuming via gradle plugin portal

---

README.md
pom.xml

Update core team in pom.xml

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/resources/2_0/mapArgs.yaml

Add import of inner type for map.
fix #3094
@bbdouglas
@sreeshas
@jfiala
@lukoyanov
@cbornet
@jeff9finger
@karismann

Import inner items for map

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.cpp.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.h.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache
samples/client/petstore/cpp-qt5/client/OAIHttpRequest.cpp
samples/client/petstore/cpp-qt5/client/OAIHttpRequest.h
samples/client/petstore/cpp-qt5/client/OAIPetApi.cpp
samples/client/petstore/cpp-qt5/client/OAIPetApi.h
samples/client/petstore/cpp-qt5/client/OAIStoreApi.cpp
samples/client/petstore/cpp-qt5/client/OAIStoreApi.h
samples/client/petstore/cpp-qt5/client/OAIUserApi.cpp
samples/client/petstore/cpp-qt5/client/OAIUserApi.h

Fixes #3064
- Add timeout specifier for api calls
- Default behaviour is unchanged, by default no timeout like before
- backwards compatible
`cc:`
@stkrwork @ravinikam @MartinDelille 
`cc:`
@luStopai

[C++] [Qt5] Add API timeout handling

---

modules/openapi-generator/src/main/resources/ruby-client/rubocop.mustache
samples/client/petstore/ruby/.rubocop.yml
samples/openapi3/client/petstore/ruby/.rubocop.yml

Rubocop gives an obsolescence error on linting the generated code
```
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in .rubocop.yml, please update it)
```
This PR fixes it.

Fix rubocop obsolescence

---

bin/utils/release_checkout.rb

Improve release checkout script due to change in DockerHub web page.

Improve release checkout script

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java
modules/openapi-generator/src/main/resources/perl/travis.mustache

render `.travis.yml` configuration for generated openapi perl client referring to the instructions https://docs.travis-ci.com/user/languages/perl/

Perl: Generate templated travis configuration

---

docs/generators/spring.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java

fix #3117
I have merged the two row and update the `default interface` part.
@bbdouglas
@sreeshas
@jfiala
@lukoyanov
@cbornet
@jeff9finger
@karismann

Merge java8 doc for spring

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java

Ruby clients call `self.send(:"#{key}=", value)`.  This breaks if a response entity exposes a 'send' attribute.
This change adds ruby's "#send" to the reserved word list for the ruby generator.

[Ruby][Client] Add "send" to ruby reserved word list

---

modules/openapi-generator/src/main/resources/csharp/README.mustache
modules/openapi-generator/src/main/resources/csharp/api_doc.mustache
samples/client/petstore/csharp/OpenAPIClient/README.md
samples/client/petstore/csharp/OpenAPIClient/docs/AnotherFakeApi.md
samples/client/petstore/csharp/OpenAPIClient/docs/FakeApi.md
samples/client/petstore/csharp/OpenAPIClient/docs/FakeClassnameTags123Api.md
samples/client/petstore/csharp/OpenAPIClient/docs/PetApi.md
samples/client/petstore/csharp/OpenAPIClient/docs/StoreApi.md
samples/client/petstore/csharp/OpenAPIClient/docs/UserApi.md

[csharp] Adding http response details on api_docs and making example snippet compilable

---

modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/AppMain.kt.mustache
samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/AppMain.kt

Move KtorExperimentalAPI import out of hasAuthMethods.
Fix #2967
@jimschubert
@dr4ke616
@karismann

Ktor Fix KtorExperimentalAPI import

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OpenAPIYamlGenerator.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/yaml/YamlGeneratorTest.java

openapi-yaml generator ignored `outputFile` config option and always wrote the output to `openapi/openapi.yaml` file. 
This PR takes `outputFile` into consideration and if not provided generator defaults output to `openapi/openapi.yaml` to preserve backwards compatibility. 
Fixes #3198

[openapi-yaml] Config option outputFile was ignored by the generator.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/resources/ruby-client/api.mustache

`--strict-spec false` solution to https://github.com/OpenAPITools/openapi-generator/issues/3119
URL-special characters such as /,?,% should be encoded when inside path
parameters. I changed the Ruby-client to do so.
https://github.com/OpenAPITools/openapi-generator/pull/3039
Unfortunately, some projects relied on slashes not being expanded within
path paramters:
https://github.com/OpenAPITools/openapi-generator/issues/3119
With this commit, these projects can now pass `--strict-spec false` to
not have / converted to %2F.
strict spec not specified: / -> %2F
--strict-spec true: / -> %2F
--strict-spec false: / -> /

Ruby-client: Don't encode slashes if strict-spec false

---

modules/openapi-generator/src/main/resources/typescript-rxjs/apis.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache
samples/client/petstore/typescript-rxjs/builds/default/apis/PetApi.ts
samples/client/petstore/typescript-rxjs/builds/default/apis/StoreApi.ts
samples/client/petstore/typescript-rxjs/builds/default/apis/UserApi.ts
samples/client/petstore/typescript-rxjs/builds/default/runtime.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/apis/PetApi.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/apis/StoreApi.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/apis/UserApi.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/apis/PetApi.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/apis/StoreApi.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/apis/UserApi.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/apis/PetApi.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/apis/StoreApi.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/apis/UserApi.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts

* refactor to arrow functions where possible
* abstract error throwing null checks into a function `throwIfRequired`
* remove unused parameter in `RequiredError` (this is a breaking change if people are using it outside the generated code)
* refactor `headers` and `query` objects to be created inline to be less verbose and skip redundant null checks
This all results in a noticeable code savings. 
In my current react project with CRA2 (9 controllers and 14 endpoints) I get a build with 4368 characters less which is about 4%, although file size after gzip it is only 230 Bytes which is about 1%.

[typescript-rxjs] refactor to arrow functions and short hand object creation

---

modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache
modules/openapi-generator/src/main/resources/python/configuration.mustache
samples/client/petstore/python-asyncio/petstore_api/configuration.py
samples/client/petstore/python-asyncio/petstore_api/rest.py

A current generated asyncio client limits number of simultaneous connections to 4 and this values is not configurable by the configuration object. In PR I use value from configuration and set default to 100 (it's default value recommended by the aiohttp library).
Thanks for reviewing and merging it :)
CC: @wing328 @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @Jyhess (2019/01)

feat: configurable limit of simultaneous connections (python/asyncio)

---

docs/generators/aspnetcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
modules/openapi-generator/src/main/resources/aspnetcore/2.1/Project.csproj.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/Startup.mustache

Preliminary support for ASP.NET Core 3.0 (preview 4). See issue #2350
No support for the new style routing or new Json library (still uses Newtonsoft).

[aspnetcore]: Preliminary support for ASP.NET 3.0 Core preview 5

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java

Check if inheritance parent exists with refName and not modelName. 
I've done it on DefaultCodegen so it will impact all generators.
Fix #3150
@wing328
@jimschubert
@cbornet
@ackintosh
@jmini
@etherealjoy

Fix inheritance with modelPrefix

---

CONTRIBUTING.md

Currently, there is no link to the [new-generator](https://openapi-generator.tech/docs/new-generator) guide in the `CONTRIBUTING.md`. This PR adds one.

add link to the "new-generator" guide

---

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache

Tech Committee: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)
For query parameters that are specified as `type: string` and `format: date`, the URL now contains the entire ISO-string while it should only include the date part in format `YYYY-MM-DD`. This distinction between `date` and `date-time` is already properly made in the models, but not in the client API generation.
In my project I cannot use the generated library for certain API calls that include something like `?date=` in their URL. The remote server may reject the request because it's not in the format `YYYY-MM-DD`.
I noticed that the sample Petstore does not include an example that uses `format: date`. There are …

[Typescript-Fetch] If a query parameter is a date, format it as YYYY-MM-DD

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/pingBearerAuth.yaml

See issue #457
Bearer support was missing in the Java client `okhttp-gson`.
This also add an example spec (ping spec modified to have bearer auth).

[java-client][okhttp-gson] support bearer authentication

---

modules/openapi-generator/src/main/resources/cpp-pistache-server/api-source.mustache
samples/server/petstore/cpp-pistache/api/PetApi.cpp
samples/server/petstore/cpp-pistache/api/StoreApi.cpp
samples/server/petstore/cpp-pistache/api/UserApi.cpp

@ravinikam @stkrwork @etherealjoy @MartinDelille 
GCC would complain about two warnings
```
(...)/api/(...)Api.cpp:24:92: warning: extra ‘;’ [-Wpedantic]
(...)Api::(...)Api(std::shared_ptr<Pistache::Rest::Router> rtr) { router = rtr; };
```
```
(..)/api/(...)Api.cpp: In member function ‘void org::openapitools::server::api::(...)Api::(...)_api_default_handler(const Pistache::Rest::Request&, Pistache::Http::ResponseWriter)’:
(...)/api/(...)Api.cpp:124:69: warning: unused parameter ‘request’ [-Wunused-parameter]
void (...)Api::(...)_api_default_handler(const Pistache::Rest::Request& request,
```

[C++][Pistache] Fix warnings

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ErlangClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ErlangProperCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java

Use escapeReservedWord on classVarName.
Must fix #1831 and #13
Also renamed snakeCase() to lowerCamelCase() to match with the method behavior. 
@bbdouglas 
@sreeshas 
@jfiala 
@lukoyanov 
@cbornet 
@jeff9finger 
@karismann

Check classVarName against reserved keywords, renamed snakeCase to lowerCamelCase

---

docs/generators/java-vertx.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaVertXServerCodegen.java
modules/openapi-generator/src/main/resources/JavaVertXServer/api.mustache

RxJava2 uses another base package. To support this package in java-vertx server codegen, a rxVersion2 boolean flag/option was added which defaults to false.
@wing328

Added RxJava2 to java-vertx server codegen

---

modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/configuration/OpenAPIDocumentationConfig.java

This sets "host" appropriately to the published host when GENERATOR_HOST
is configured.

[online] Honor GENERATOR_HOST env variable

---

modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/configuration/OpenAPIDocumentationConfig.java

Previously, this pulled from the GENERATOR_HOST system property. This
should have been an environment variable. Fallback is now generator.host
system property.

[online] Honor generator environment variable and system property

---

bin/windows/android-petstore-httpclient.bat
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java

If a string field is specified with a format which is also defined using --typeMappings, it will be treated as a primitive type
For example, if you run the following command:
`java -jar openapi-generator-cli.jar generate [options] --type-mappings dateorcutlabel=CutLabel`
The generated code will assume there is a class `CutLabel` and use it for any parameter which has a specific similiar to this:
> {
>   "name": "effectiveAt",
>   "in": "query",
>   "description": "Optional. The effective date of the data",
>   "required": false,
>   "type": "string",
>   "format": "**dateorcutlabel**"
> }

Update DefaultCodeGen to allow additional primitive types

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/allOf.yaml

The `mapping` property of the [Discriminator Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject) is "An object to hold mappings between payload values and schema names or references."  The subsequent examples in the spec have `mapping`s of both types.  The `mapping` support introduced in #536 only supports references.
This pull request updates the code to support names which are not references (identified by lack of `/`) in addition to references and changes a test mapping to cover this case.
Thanks for considering,
Kevin
CC:  @0v1se, @jmini (from #536)
CC technical committee:  @bbdouglas, @sreeshas, @jfiala, @lukoyanov, @cbornet, @jeff9finger, @karismann, @Zomzog

[Java] Handle discriminator mapping non-ref name

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_0/unusedSchemas.yaml

(https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
Introduced with #74 and updated with #1232 and #2138, the `ModelUtils.getUnusedSchemas(OpenAPI)` returns all schemas that are not used in an OpenAPI specification.
This PR fixes the case where a `Schema` is referenced in an `Content` of and `Header` or `Parameter`.
Original issue: #50

[core] consider content in parameters and headers when computing unused schemas

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache

Signed-off-by: Prateek Malhotra <someone1@gmail.com>
Attempt to address #2739 - In a [previous PR,](https://github.com/OpenAPITools/openapi-generator/pull/1545) I switched to `allVars` in the typescript model templates as `vars` only included the defined properties for that model, not any properties from any (at that time) inherited classes. Since then, the inheritance/composition models changed internally and `vars` includes all properties for the model as the model composition is now flattened and no longer inherits from any base class.
This gets the code in a compilable state but there are some worries here:
- Why is `allVars` blank?
- There are "*AllOf.ts" models generated that seem erroneous - these shouldn't be generated.
- Can we get better testing in place? I suggest using a yaml …

[Typescript][Fetch] switch to vars from allVars

---

docs/generators/spring.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
modules/openapi-generator/src/main/resources/JavaSpring/apiDelegate.mustache

Fixes #2984.
The documentation of the `java8` option describes it can be used to generate default interfaces. I therefore took the approach not to generate default interfaces when you don't explicitly set the `java8` option. To me this feels the most natural. Please let me know if you prefer to add an extra option for this.
cc @diyfr

Only enable Spring default interface for `java8`

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptJqueryClientCodegen.java

We decided to not use fields hiding other in child classes, because this is a bad practice in Java.
This PR fixes following error:
> The field TypeScriptJqueryClientCodegen.SNAPSHOT is hiding a field from type
AbstractTypeScriptClientCodegen

[typescript] remove duplicate TypeScriptJqueryClientCodegen.SNAPSHOT field

---

CI/circle_parallel.sh
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
modules/openapi-generator/src/main/resources/java-pkmst/config/appconfig.mustache
modules/openapi-generator/src/main/resources/java-pkmst/security/oAuth2SecurityConfiguration.mustache
modules/openapi-generator/src/main/resources/java-pkmst/security/resourceServerConfiguration.mustache
samples/client/petstore/java/jersey2-java6/pom.xml
samples/client/petstore/java/jersey2-java8/build.gradle
samples/client/petstore/java/jersey2-java8/pom.xml
samples/client/petstore/java/jersey2/build.gradle
samples/client/petstore/java/jersey2/pom.xml
samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/okhttp-gson/pom.xml
samples/server/petstore/java-pkmst/src/main/java/com/prokarma/pkmst/config/AppConfig.java
samples/server/petstore/java-pkmst/src/main/java/com/prokarma/pkmst/security/OAuth2SecurityConfiguration.java
samples/server/petstore/java-pkmst/src/main/java/com/prokarma/pkmst/security/ResourceServerConfiguration.java

Fixes #3299.
The special javadoc tag `@http.response.details` needs to be declared correctly, so that the javadoc can be built.
---
For maven, this PR changes where the `<configuration>` block is added.
It was inside the `<execution>` bloc, but the example in the documetation ([Configuring Custom Javadoc Tags](https://maven.apache.org/plugins/maven-javadoc-plugin/examples/tag-configuration.html)) adds it directly in the `<plugin>` bloc.
For gradle, the [javadoc](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html) page do not really mention the `tags` option, but 
[GRADLE-1563](https://issues.gradle.org/browse/GRADLE-1563) does. See also [this question](https://stackoverflow.com/a/35121736/91497) on stackoverflow.

[java] fix javadoc configuration

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Change-Id: Ic6e87bfdfa58a4a8f6f1f3aac043c57260ed873c
Referencing to issue #2923 
The change is in DefaultCodegen, so I haven't ran any language-specific script.
The referenced enum schema was missing both the type checking and the assignment of the variable `isEnum`. I moved the typechecking of the property to an external function which I then use for both the properties `p` and `referencedSchema`.
I have been using this fix for a personal project and it has been working well so far. I also tested the case in the issue request and it is solved. The library builds correctly with `mvn clean install`, but sadly I couldn't test through `mvn verify -Psamples` as it stops on language specific tests because I am missing the needed tools and running it in a protected environment.

Fixed type assignment for referenced enums

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/ClientOptInput.java

PR #2946 has deprecated some methods.
This PR adds a Javadoc note to indicate the replacement method.
cc @jimschubert

[core] indicate replacement methods in the javadoc

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

See issue #457
With #3236 I have added support for bearer authentication for `okhttp-gson` but I forgot to add the import line.
---
As comparison all other java client generators have those imports:
https://github.com/OpenAPITools/openapi-generator/blob/15f8c2c78b098ac6109adecf0048a538c071a3c7/modules/openapi-generator/src/main/resources/Java/ApiClient.mustache#L52-L55
https://github.com/OpenAPITools/openapi-generator/blob/15f8c2c78b098ac6109adecf0048a538c071a3c7/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache#L54-L57
https://github.com/OpenAPITools/openapi-generator/blob/15f8c2c78b098ac6109adecf0048a538c071a3c7/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L67-L70
...

[java-client][okhttp-gson] add missing import for bearer authentication

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaPlayFrameworkServerCodegen.java

The CLI option `routesFileName` is duplicated and the correct option name of later one ought to be `basePackage`.
[Doc of scala-play-server](https://github.com/openapitools/openapi-generator/blob/master/docs/generators/scala-play-server.md)

[scala-play-server] Correct CLI option name

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OpenAPIYamlGenerator.java

I am looking for a way to convert from Openapi 3 to Swagger 2 specification. I think `openapi-yaml` generator with custom template is a good starting point. 
In order to start, I needed to modify current generator to:
1. Group operations by resourcePath (they are grouped by tag currently) so that operations with same path are rendered one after the other:
Example:
```
/pet:
post:
.....
put:
.....
/pet/findByStatus:
get:
.....
```
And not (it might happen when grouped by a tag):
```
/pet:
post:
.....
/pet/findByStatus:
get:
.....
/pet: 
put:
.....
```
2. Created a Mustache lambda `OnChangeLambda` to return fragment only when current fragment is different than previous fragment. It will be used to render endpoint path only for a first operation in group.
3. Registered lambdas like …

[openapi-yaml] Prerequisities for Swagger 2 template.

---

modules/openapi-generator/src/main/resources/cpp-pistache-server/model-source.mustache
samples/server/petstore/cpp-pistache/model/ApiResponse.cpp
samples/server/petstore/cpp-pistache/model/Category.cpp
samples/server/petstore/cpp-pistache/model/Inline_object.cpp
samples/server/petstore/cpp-pistache/model/Inline_object_1.cpp
samples/server/petstore/cpp-pistache/model/Order.cpp
samples/server/petstore/cpp-pistache/model/Pet.cpp
samples/server/petstore/cpp-pistache/model/Tag.cpp
samples/server/petstore/cpp-pistache/model/User.cpp

@ravinikam @stkrwork @etherealjoy @MartinDelille 
While generated sample downloads nlohmann-json from GitHub, it could also be provided by operating system. Debian 10 Buster provides nlohmann-json3-dev package with 3.5.0 version [https://packages.debian.org/buster/nlohmann-json3-dev](https://packages.debian.org/buster/nlohmann-json3-dev).
`contains` was added in 3.6.0 [https://github.com/nlohmann/json/releases/tag/v3.6.0](https://github.com/nlohmann/json/releases/tag/v3.6.0)
This change makes generated code compatible with 3.5.0.
Here's the code I tested it with:
```c++
#include <nlohmann/json.hpp>
#include <iostream>
void check_with_find(char const * const key, nlohmann::json const &json)
{
if (json.find(key) != json.end())
std::cout << "find: " << key << " exists!\n";
else
std::cout << …
```

[C++][Pistache] Add compatibility for nlohmann-json 3.5.0

---

docs/generators/jaxrs-cxf-cdi.md
docs/generators/jaxrs-spec.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSSpecServerCodegenTest.java

Currently the OpenAPI Spec is generated to `src/main/openapi/openapi.yaml`. This is not conform with the [Eclipse MicroProfile OpenAPI](https://github.com/eclipse/microprofile-open-api/) which is the spec that defines how OpenAPI should be used on top of JAX-RS.
This PR introduces a new parameter `openApiSpecFileLocation` to be able to specify where the generated spec should be generated.
* Default value: `src/main/openapi/openapi.yaml` (no change for existing users)
* Possible value `src/main/resources/META-INF/openapi.yaml` to be conform with the MP-OpenAPI spec
* In order to not generate the spec, the value can be set to `null` or empty string `""`
Fixes #809

[JaxRS-Spec] add openApiSpecFileLocation parameter

---

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache

`COLLECTION_FORMATS` had a wrong reference, it is in the `runtime` file.

[typescript-fetch] Fix collection formats reference

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/runtime.ts

It would be helpful if the query string formatting could be configured.
Solution for example for the deep query string:
```
import { Configuration, PetApi } from './api'
import { stringify } from 'qs'
const config = new Configuration({ queryParamsStringify: stringify })
const api = new PetApi(config)
```

[typescript-fetch] support custom stringify for query string

---

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache

There was a typescript error, because only `this.configuration.accessToken` function takes two arguments,` this.configuration.apiKey` doesn't. Moreover, `apiKey` is unnecessary in bearer mode, and it is used a few lines below.

[typescript-fetch] Fix access token type

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractFSharpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OpenAPIYamlGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaPlayFrameworkServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/OnChangeLambda.java

Various generator used same Mustache lambdas over and over. In this PR, `DefaultCodegen` registers set of following Mustache lambdas:
```
.put("lowercase", new LowercaseLambda().generator(this))
.put("uppercase", new UppercaseLambda())
.put("titlecase", new TitlecaseLambda())
.put("camelcase", new CamelCaseLambda().generator(this))
.put("indented", new IndentedLambda())
.put("indented_8", new IndentedLambda(8, " "))
.put("indented_12", new IndentedLambda(12, " "))
.put("indented_16", new IndentedLambda(16, " "));
```
Extension is done in such a way that each generator can:
- extend the list with additional lambdas
```
@Override
protected Builder<String, Lambda> addMustacheLambdas() {
return super.addMustacheLambdas()
.put("multiline_comment_4", new IndentedLambda(4, " ", "///"));
}
```
- …

Include common lambdas in generators

---

docker-entrypoint.sh
modules/openapi-generator/src/main/resources/aspnetcore/2.0/model.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/model.mustache

* Addresses #3359 
* Also fixes a small syntax error in `docker-entrypoint.sh`.
* `./run-in-docker.sh mvn package` successfully builds & runs tests. 
*  `./run-in-docker.sh generate ...` produces the following.
```
openapi: '3.0.0'
info:
version: 1.0.0
title: API with Default Values
servers:
- url: http://localhost:8080
paths:
/test:
post:
operationId: testDefaults
requestBody:
required: true
content:
schema:
'$ref': '#/components/schemas/Payload'
responses:
'200':
description: Ok
components:
schemas:
Payload:
type: object
properties:
stringProp:
type: string
default: foo
intProp:
type: integer
default: 123
floatProp:
type: number
format: float
default: 1.23
doubleProp:
type: number
format: double
default: 1.234
decimalProp:
type: number
format: decimal
default: 1.2345 …
```

Adds default property values in ASP .NET Core models

---

modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/api.mustache
samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/api/UserApi.java

Java: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)
Fixes #3370
Tested with this spec:
```yaml
openapi: 3.0.1
info:
title: ping test
version: '1.0'
servers:
- url: 'http://localhost:8080/'
paths:
/ping:
get:
operationId: pingGet
tags:
- lorem
parameters:
- in: query
name: q
schema:
type: string
- in: query
name: r
schema:
type: string
responses:
'201':
description: Ok
```
With a this test using [MockServer](https://github.com/jamesdbloom/mockserver) (more on this to come in #689):
```java
public class LoremApiTest {
private ClientAndServer mockServer;
private LoremApi api;
@Before
public void createApi() {
mockServer = ClientAndServer.startClientAndServer();
String port =  "" …
```

[java rest-assured] prevent reqSpec reuse between requests

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/config/CodegenConfiguratorTest.java
samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
samples/server/petstore/php-symfony/SymfonyBundle-php/.gitignore

As part of settings refactor, I had missed assigning the value of templateDir to additional properties. This result in 4.1.0-SNAPSHOT branch with borked custom template support.
This PR makes that asignment, and fixes some other potential issues with internal state in CodegenConfigurator (`set*` methods).
Added a unit test which evaluates additional properties exist on a CodegenConfig instance after calling `processOpts()`. The test is limited to those properties known to be processed by DefaultCodegen.
fixes #3364

[fix] Assign template directory to additional properties

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-fetch/index.mustache
samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts

* use proper response for simple object return types
* exclude api and/or model support files and imports if none are generated
fixes #3167

typescript-fetch: fix basic type errors

---

README.md

Fix typo in `README.md` where there was a missing closing paren.

fix README.md missing paren typo

---

modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
modules/openapi-generator/src/main/resources/typescript-node/models.mustache
samples/client/petstore/typescript-node/default/api/petApi.ts
samples/client/petstore/typescript-node/default/api/storeApi.ts
samples/client/petstore/typescript-node/default/api/userApi.ts
samples/client/petstore/typescript-node/default/model/models.ts
samples/client/petstore/typescript-node/npm/api/petApi.ts
samples/client/petstore/typescript-node/npm/api/storeApi.ts
samples/client/petstore/typescript-node/npm/api/userApi.ts
samples/client/petstore/typescript-node/npm/model/models.ts

Example implementation for https://github.com/OpenAPITools/openapi-generator/issues/3407.
fixes #3407

[typescript-node] Promise-based Authentication interface

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny 
Fair warning that I tested this out more thoroughly using swagger-codegen for this PR - https://github.com/swagger-api/swagger-codegen/pull/9594 - but it looks like the same exact issue.
Related to this [issue](https://github.com/OpenAPITools/openapi-generator/issues/2745). When using TypeScript Fetch and passing parameters to a "Date" field, they expect a type of "string", but then `toISOString()` is called on it, which causes the function to fail. 
Example json swagger:
```json
"parameters": [
{
"name": "date",
"in": "query",
"type": "string",
"format": "date"
}
]
```
in In `AbstractTypeScriptClientCodegen.java the Typings map:
```
typeMapping.put("date", "string");
typeMapping.put("DateTime", "Date");
```
template issue: …

2745 typescript date format

---

modules/openapi-generator/src/main/resources/rust/api_doc.mustache
samples/client/petstore/rust-reqwest/docs/PetApi.md
samples/client/petstore/rust-reqwest/docs/StoreApi.md
samples/client/petstore/rust-reqwest/docs/UserApi.md
samples/client/petstore/rust/docs/PetApi.md
samples/client/petstore/rust/docs/StoreApi.md
samples/client/petstore/rust/docs/UserApi.md

/cc @frol @farcaller @bjgill 
Fixes #3418. Only generated API markdown files are impacted.

[Rust][Client] Correct the Rust client generated documentation

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/resources/Java/modelEnum.mustache
modules/openapi-generator/src/main/resources/Java/modelInnerEnum.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java

Fixes #447
The type `number` is mapped to java `BigDecimal`. This PR fixes the compilation issues that appears when `enum` values are defined.
Tested with:
```yaml
openapi: 3.0.1
info:
title: issue 447
version: '1.0'
servers:
- url: 'http://localhost:9999/'
paths:
/ping:
get:
operationId: pingGet
responses:
'201':
description: OK
components:
schemas:
NumberEnum:
type: number
enum:
- 1.0
- 2.5
- 3.0
SomeObject:
type: object
properties:
aNum:
type: number
enum:
- 5.0
- 6.5
- 7.0
```

[java] Support for number enum

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

…nerators are escaped now.
Somehow the generator started somewhen to generate broken java code if the fields in the openapi spec are staring with a number. Numbers are not allowed at the start of a word in java so they need to be escaped. This bugfix escapes all varNames which start with a number with an underscore like it was sometime before
- fixes https://github.com/OpenAPITools/openapi-generator/issues/3293

[Java] Fix numeric field names

---

docs/generators/cpp-qt5-client.md
docs/generators/cpp-qt5-qhttpengine-server.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5AbstractCodegen.java

This PR add the `modelNamePrefix` additional property to the Qt5 generator.
It also fix the double `cppNamespace` entry when running `openapi-generator config-help -g cpp-qt5-client`.
@ravinikam @stkrwork @etherealjoy

add modelNamePrefix option for qt5

---

modules/openapi-generator/src/main/resources/Javascript/es6/.babelrc.mustache
modules/openapi-generator/src/main/resources/Javascript/es6/package.mustache
samples/client/petstore/javascript-es6/.babelrc
samples/client/petstore/javascript-es6/package.json
samples/client/petstore/javascript-promise-es6/.babelrc
samples/client/petstore/javascript-promise-es6/package.json

This PR addresses the vulnerability described here: https://github.com/OpenAPITools/openapi-generator/issues/3393
I ran `npx babel-upgrade` within the generated package and copied the changes into the ES6 mustache templates.  I then ran the two relevant shell scripts: `javascript-es6-petstore.sh` and `javascript-promise-es6-petstore.sh`
Fixes #3393

Upgrade babel packages for Javascript ES6 generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-rxjs/apis.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache
samples/client/petstore/typescript-rxjs/builds/default/runtime.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts

The goal is to generate the correct `responseType` which is passed to `rxjs/ajax`. 
By default this is `json` as visible here: <https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/dom/AjaxObservable.ts#L167)> but it can be overriden.
I am not too sure about all the possible types but I found `json`, `text`, `blob` and `arraybuffer` to be supported by `rxjs/ajax` based on <https://github.com/Reactive-Extensions/RxJS-DOM/pull/121/files#diff-d3b897234759c07ed79441f35e56b67fR22>. Perhaps it's also possible to pass `document` and `ms-stream` as described there for completeness: <https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType>.
The one that I personally need for a project is `blob` in order to download an excel file.
The relevant lines for this in …

[typescript-rxjs]: support reponseType blob

---

modules/openapi-generator/src/main/resources/typescript-angular/package.mustache
samples/client/petstore/typescript-angular-v4.3/npm/package.json
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/package.json
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/package.json
samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/package.json
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/package.json

fix(typescript-angular): use correct package with http-client

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java

I just wanted to fix #3480 .
But I'm a newbie. 
I'm new to this. Is this correct?
Please review in your free time.
I ran following command and commit changed files.
- mvn verify
- bin/java-petstore-resttemplate.sh
- bin/java-petstore-resttemplate-withxml.sh

[Java][RestTemplate] remove wrong Null Check 

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-node/model.mustache
modules/openapi-generator/src/main/resources/typescript-node/models.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypeScriptNodeClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypeScriptNodeModelTest.java

This addresses an issue similar to Issue #3149 but for the TypeScript Node generator. This is a more general issue that could be implemented for all TypeScript generators, but I'm keeping the scope small initially.
The `importMapping` behavior described [here](https://openapi-generator.tech/docs/customization#bringing-your-own-models) and [here](https://openapi-generator.tech/docs/usage#target-external-models) in the usage docs, and supported [by the Maven plugin configuration](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin#general-configuration-parameters) does not currently work for TypeScript generation.
This change allows a user to define these mappings and produce valid TypeScript import statements when using the …

Support importMapping definitions for TypeScriptNodeClientCodegen

---

modules/openapi-generator/src/main/resources/aspnetcore/2.1/Startup.mustache

@mandrean , @jimschubert 
Fix the typo of commit 94c583b

Fix typo useDefaultRoutng to useDefaultRouting

---

modules/openapi-generator/src/main/resources/rust/model.mustache
samples/client/petstore/rust-reqwest/src/models/api_response.rs
samples/client/petstore/rust-reqwest/src/models/category.rs
samples/client/petstore/rust-reqwest/src/models/order.rs
samples/client/petstore/rust-reqwest/src/models/pet.rs
samples/client/petstore/rust-reqwest/src/models/tag.rs
samples/client/petstore/rust-reqwest/src/models/user.rs
samples/client/petstore/rust/src/models/api_response.rs
samples/client/petstore/rust/src/models/category.rs
samples/client/petstore/rust/src/models/order.rs
samples/client/petstore/rust/src/models/pet.rs
samples/client/petstore/rust/src/models/tag.rs
samples/client/petstore/rust/src/models/user.rs

It fails if the model contains a float, which don't implement Eq.
Fix for bug introduced in https://github.com/OpenAPITools/openapi-generator/pull/3309. 
We really need to improve the testing of the rust generator to catch this sort of mistake in future. I don't have time to do this now, though.

[rust] Stop deriving Eq for models

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java

Better handling of non-alphanumeric characters in inline model naming.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/3260
Tested locally with the spec provided by the user and the issue no longer exists.

Better handling of dot in inline model name

---

CI/samples.ci/client/petstore/java/test-manual/okhttp-gson/ApiClientTest.java
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/ApiClientTest.java

ApiClient for Okhttp3 must not copy the interceptors when setting the HttpClient.
fixes #3497

[java-client][okhttp-gson] fixes for interceptors in ApiClient.java

---

samples/client/petstore/cpp-qt5/PetStore/UserApiTests.cpp

Remove `QRandomGenerator` from the tests.
It adds unneeded dependency to `Qt 5.10` which can be done by a simple `rand()` function
`cc`
@MartinDelille

[C++][Qt5] Remove QRandomGenerator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
samples/server/petstore/php-symfony/SymfonyBundle-php/Api/PetApiInterface.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Api/StoreApiInterface.php
samples/server/petstore/php-symfony/SymfonyBundle-php/Api/UserApiInterface.php

Dear PHP technical committee, please review this PR
@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon
This PR attempts to fix #3514 
Short description: the return type of PHP Symfony actions is forced to be an array, while should be an object.

Fix PHP Symfony non-primitive return type being forced to be an array

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java

Fix DateTimeOffset part of issue https://github.com/OpenAPITools/openapi-generator/issues/3528
@wing328 
@mandrean 
@jimschubert

Fix DateTimeOffset nullable issue

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
modules/openapi-generator/src/main/resources/ruby-client/configuration_tls_faraday_partial.mustache
modules/openapi-generator/src/main/resources/ruby-client/configuration_tls_typhoeus_partial.mustache
modules/openapi-generator/src/main/resources/ruby-client/faraday_api_client.mustache
samples/openapi3/client/petstore/ruby-faraday/lib/petstore/api_client.rb
samples/openapi3/client/petstore/ruby-faraday/lib/petstore/configuration.rb
samples/openapi3/client/petstore/ruby-faraday/petstore.gemspec
samples/openapi3/client/petstore/ruby-faraday/spec/api_client_spec.rb

- bug fix: isFaraday
- use mustache partial for configuration.mustache

Use partial for Ruby HTTP libraries

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/clientConfiguration.mustache
samples/client/petstore/spring-cloud/src/main/java/org/openapitools/configuration/ClientConfiguration.java

fixes #3381
--
Fix invalid spring properties prefix

Add lowercase lamda

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java

typescript-angular fix string cast

---

modules/openapi-generator/src/main/resources/typescript-axios/configuration.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache
samples/client/petstore/typescript-axios/builds/default/configuration.ts
samples/client/petstore/typescript-axios/builds/es6-target/configuration.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/configuration.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/configuration.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/configuration.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/configuration.ts
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/runtime.ts
samples/client/petstore/typescript-rxjs/builds/default/runtime.ts
samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts
samples/client/petstore/typescript-rxjs/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts

fixes #2956
Iif you generate an axios API, you get a compilation error if tsconfig is set to 'strict' 
because `configuration.accessToken()` requires name as paramater (not optional) but here in the code generated  it calls `configuration.accessToken()` without passing any parameters.
I just made name an optional parameter.
I don't know if this is the right way to solve the issue, i would like to have some feedback about this. 

#2956 [typescript] change accessToken name parameter to optional

---

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache

Passing lists/containers to the body param as-is will send garbage via `fetch` - needed to stringify the contents first and only map over the items if it was a list of non-primitives.
fixes #3278 

typescript-fetch: Properly detect and encode container request body param

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/UserApi.java

This pr changes uri extension from static call of UriComponentsBuilder to more common way (via RestTemplate's UriTemplateHandler) and makes possible to natively handle templated path in metric collectors, etc
fixes #3499

Expand path templates via resttemplate's uriTemplateHandler

---

modules/openapi-generator/src/main/resources/rust-server/mimetypes.mustache
samples/server/petstore/rust-server/output/multipart-v3/src/mimetypes.rs
samples/server/petstore/rust-server/output/openapi-v3/src/mimetypes.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/mimetypes.rs
samples/server/petstore/rust-server/output/rust-server-test/src/mimetypes.rs

- @frol, @farcaller, @bjgill 
Generate valid Rustdocs for lazy_static items
Currently compiling a generated crate produced by rust-server produces warnings such as the follows:
```
warning: unused doc comment
--> output/rust-server-test/src/mimetypes.rs:15:5
|
15 |       /// Create Mime objects for the response content types for RawJsonGet
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16 | /     lazy_static! {
17 | |         pub static ref RAW_JSON_GET_SUCCESS: Mime = "*/*".parse().unwrap();
18 | |     }
| |_____- rustdoc does not generate documentation for macro expansions
|
= help: to document an item produced by a macro, the macro must produce the documentation as part of its expansion
```
This fixes that. This work was contributed by @mthebridge

 [Rust Server] Generate valid Rustdocs for lazy_static items

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts

I've change my mind on how to fix that "bug".  
In the bug itself, I was suggesting to do like in version 3.X.X and have an "option" parameter in each call but I realized that was no a very good design.
Once I understood how the code was refactored in 4.X.X, the only thing missing was to be able to provide additional `headers` with each Fetch query in the `Configuration` object. Also, the `credentials` option was missing, so I added it. Very simple PR with no breaking change and no risk :)
fixes #3402

typescript-fetch: allow configuration of headers and credentials

---

modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/IReadableConfiguration.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/IReadableConfiguration.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/IReadableConfiguration.cs

Fix #3561
Previously, the .NET Core SDK would not send configured default headers. This PR fixes this and also "fixes" the strange singular name of the property by marking it obsolete and redirecting to the new correctly-named plural form.
This second change is a separate commit and is less important so I'd drop it if need be.

[C#][client][csharp-netcore] Fix csharp netcore defaultheaders

---

modules/openapi-generator/src/test/resources/3_0/petstore.yaml

Removed `maxCount` added to `findPetsByTags`

Restore OpenAPI v3 petstore.yaml

---

README.md
modules/openapi-generator-cli/pom.xml
modules/openapi-generator-core/pom.xml
modules/openapi-generator-gradle-plugin/README.adoc
modules/openapi-generator-gradle-plugin/gradle.properties
modules/openapi-generator-gradle-plugin/pom.xml
modules/openapi-generator-gradle-plugin/samples/local-spec/README.md
modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties
modules/openapi-generator-maven-plugin/README.md
modules/openapi-generator-maven-plugin/examples/java-client.xml
modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml
modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml
modules/openapi-generator-maven-plugin/examples/non-java.xml
modules/openapi-generator-maven-plugin/pom.xml
modules/openapi-generator-online/pom.xml
modules/openapi-generator/pom.xml
pom.xml
samples/meta-codegen/lib/pom.xml

Prepare 4.1.0 release

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts

Fixes an issue where typescript-fetch in 4.1.0 generates Typescript code which doesn't compile.
```
src/api/petstore/src/runtime.ts:186:9 - error TS2322: Type 'HTTPHeaders | undefined' is not assignable to type 'HTTPHeaders'.
Type 'undefined' is not assignable to type 'HTTPHeaders'.
186         return this.configuration.headers;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/api/petstore/src/runtime.ts:190:9 - error TS2322: Type '"omit" | "same-origin" | "include" | undefined' is not assignable to type 'RequestCredentials'.
Type 'undefined' is not assignable to type 'RequestCredentials'.
190         return …
```

typescript-fetch: Fix type errors in generated code

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/README.mustache
modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_opt_var.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_req_var.mustache
modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ResponseExtensions.kt.mustache
modules/openapi-generator/src/main/resources/kotlin-client/model.mustache
samples/client/petstore/kotlin-string/README.md
samples/client/petstore/kotlin-string/build.gradle
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
samples/client/petstore/kotlin-threetenbp/README.md
samples/client/petstore/kotlin-threetenbp/build.gradle
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
samples/client/petstore/kotlin/README.md
samples/client/petstore/kotlin/build.gradle
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt

Fix escaping of dataType field.
Fix handling of arrays/lists of enums.
Update okhttp to 4.0.1
main issue was:
```val `data`: ApiResponseListString.`Data`? = null,
...
enum class `Data`(val value: kotlin.collection.List<kotlin.String>)```
instead of
```val `data`: kotlin.collection.List<ApiResponseListString.`Data`>? = null,`
`enum class `Data`(val value: kotlin.String)```

Fix kotlin templates

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

This should be merged after #3363, and after the core feature is published as a snapshot. There's an issue with consuming core changes in the maven plugin within the same build during a SNAPSHOT build, likely due to how we do the samples verification using a different profile from the original/cached build.

[maven] Support user overrides for serverVariables (carryover from #3363)

---

modules/openapi-generator/src/main/resources/typescript-inversify/HttpClient.mustache
samples/client/petstore/typescript-inversify/HttpClient.ts

Currently the typescript-inversify generator doesn't produce code that compiles, when using the “strict: true” compilerOptions in tsconfig.json - as the addJsonHeaders method requires a non-nullable instance of Headers, however the get/put/post etc. methods accept a nullable instance, this PR fixes this issue in the generator template

[Typescript] Fix typescript-inversify compiler errors

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts

@TiFu @taxpon @sebastianhaas  @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce @akehir
fix #2850
When the return type is not empty in swagger file, the corresponding axios method return type should be AxiosPromise<void> instead of AxiosPromise<Response>

typescript-axios: If the return type is empty, it should be void instead of Response

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/RubyClientCodegenTest.java

Fixes #3613 
When a model includes properties by composition (`allOf`, without a discriminator), these properties end up in the `vars` template variable but they are missing from the `allVars` variable.

Fix composed properties missing from allVars

---

modules/openapi-generator/src/main/resources/python/configuration.mustache
samples/client/petstore/python-asyncio/petstore_api/configuration.py
samples/client/petstore/python-tornado/petstore_api/configuration.py
samples/client/petstore/python/petstore_api/configuration.py
samples/openapi3/client/petstore/python/petstore_api/configuration.py

This PR optimizes get_api_key method for python client by removing redundant dictionary lookup.

[Python] avoid unnecessary dictionary lookup in get_api_key method

---

modules/openapi-generator/src/main/resources/kotlin-client/api.mustache
modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/bin/org/openapitools/client/apis/StoreApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

See #3529, this allows consumers of the client to better handle these unexpected conditions.
cc @dr4ke616 @karismann @Zomzog

[kotlin] Change Kotlin client exceptions to expose lack of support as UnsupportedOperationException rather than NotImplementedException.

---

modules/openapi-generator/src/main/resources/php-slim-server/SlimRouter.mustache
samples/server/petstore/php-slim/lib/SlimRouter.php

I changed the `SlimRouter.mustache` template to distinguish between basic and bearer authentications. Then I change the regex depending on that.

[Slim] Distinction between basicBasic and basicBearer authentication

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
modules/openapi-generator/src/main/resources/go/api.mustache

@antihax @bvwells @kemokemo 
This PR fixes parameters which use `collectionFormat=multi` so that duplicate keys (but different values) are sent in the query string instead of a single key with a single CSV concatenated value.
See description of bug here:
https://github.com/OpenAPITools/openapi-generator/issues/3386
This PR doesn't introduce any breaking changes and is built on the existing `antihax/optional.Interface` type for an optional `[]string`.
For a breaking change, it would be nice to implement an `[]string` in the optional structs and only use if the array has one or more elements.
For example, the following is currently generated:
```go
type APIOpts struct {
Name      optional.String
UserIds   optional.Interface
}
```
It may be better to generate:
```go
type APIOpts struct { …
```

[Golang][Client] Fix collectionFormat=multi request bug

---

modules/openapi-generator/src/main/resources/Java/libraries/native/generatedAnnotation.mustache

Before Java 9, the `Generated` annotation was part of JEE and in the
`javax.annotation` package. Starting with Java 9, it is now part
of the standard SDK, under the new `javax.annotation.processing`
package.
This change creates a custom Generated annotation template for the
native clientlib, since it is guaranteed to be run in Java 11+.
Adds a new custom `generatedAnnotation.mustache` template for the native HttpClient library with the correct `Generated` package name for Java 9+.
Fixes #3636

Use javax.annotation.processing.Generated for Java 11 native client

---

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache

Similar to #1730 and #1743 adding support for [nullable](https://swagger.io/docs/specification/data-models/data-types/#null) in the typescript-fetch client.
CC @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07)

[typescript-fetch] Add nullable support

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

Fixes #3647
Before this change the `trace` operation under all `PathItem` is just ignored by OpenAPI-
Generator.
With this change, the operation is considered. As written on the issue, the generator maintainers might need to do some changes to produce correct code for the `trace` operation.

[core] process TRACE operation

---

modules/openapi-generator/src/main/resources/python/configuration.mustache
samples/client/petstore/python-asyncio/petstore_api/configuration.py
samples/client/petstore/python-tornado/petstore_api/configuration.py
samples/client/petstore/python/petstore_api/configuration.py
samples/openapi3/client/petstore/python/petstore_api/configuration.py

This PR adds a function hook to support refreshing expired api key. It is part of the fix for kubernetes-client/python#741.

[Python] support api key refresh in configuration module

---

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
samples/openapi3/client/petstore/ruby-faraday/lib/petstore/api_client.rb

This seems to be the correct attribute based on the faraday ssl options here:
https://github.com/lostisland/faraday/blob/1c3bf50d8a28d71b11fca897ebdc71577c33ec6a/lib/faraday/options/ssl_options.rb#L15

[Ruby][faraday] Properly pass verify_mode to faraday

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiClient.java

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala  (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)  @karismann (2019/03) @Zomzog (2019/04)
See issue #3647
Follow up of #3648 for java client generators.

[java-client][jersey2][resteasy] add support for TRACE method

---

modules/openapi-generator/src/main/resources/go-experimental/api.mustache
modules/openapi-generator/src/main/resources/go/api.mustache
samples/client/petstore/go/go-petstore-withXml/api_pet.go
samples/client/petstore/go/go-petstore-withXml/api_store.go
samples/client/petstore/go/go-petstore-withXml/api_user.go
samples/client/petstore/go/go-petstore/api_pet.go
samples/client/petstore/go/go-petstore/api_store.go
samples/client/petstore/go/go-petstore/api_user.go

Proposed fix for https://github.com/OpenAPITools/openapi-generator/issues/3591
Simply wraps usage of path parameters with a call to url.QueryEscape().

[Go]URLEncode path parameters

---

bin/utils/openapi-generator-cli.sh

with this addition the script should be able to store the jars at a user-defined folder if desired

autoupdating generator script: userdef cache dir

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
samples/client/petstore/cpp-qt5/client/OAIPetApi.cpp
samples/client/petstore/cpp-qt5/client/OAIStoreApi.cpp
samples/client/petstore/cpp-qt5/client/OAIUserApi.cpp

I found a memory leak thanks to [valgrind](http://www.valgrind.org). Eventually it could be possible to use valgrind in the CI to make sure that the change doesn't bring more memory leaks.

cpp-qt5-client: fix memory leak in api-body

---

modules/openapi-generator/src/main/resources/csharp-netcore/Multimap.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/StoreApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/UserApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Multimap.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/StoreApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/UserApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Multimap.cs

Fixes #3673 
* Fix XML documentation warnings that are being shown while building the package.
* Fix the hard-coded `PetApi` class name in api.mustache.

[csharp-netcore] Fixing the XML documentation warnings.

---

modules/openapi-generator/src/main/resources/ruby-client/partial_model_generic.mustache

Fix #3670.
- Fix accessing to `openapi_one_of` and `openapi_any_of`
- Fix usage of `_one_of_found` and `_any_of_found`

Fix runtime error in the model's `valid?` of Ruby client (#3670)

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiClient.java

This PR add support for OPTIONS http-method to `jersey2` and `resteasy` java-clients.
This was not supported in following switches:
https://github.com/OpenAPITools/openapi-generator/blob/a5ab60bec8df9dfd7bfcba21fabd6fb710e990ff/samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/ApiClient.java#L696-L712
And:
https://github.com/OpenAPITools/openapi-generator/blob/a5ab60bec8df9dfd7bfcba21fabd6fb710e990ff/samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiClient.java#L648-L664
Before the change there was an exception like this (in the rest-easy case):
```
<package-name>.resteasy.ApiException: unknown method type OPTIONS
at <package-name>.resteasy.ApiClient.invokeAPI(ApiClient.java:648)
```

[java-client][jersey2][resteasy] add support for OPTIONS method

---

samples/client/petstore/cpp-qt5/PetStore/PetApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/PetApiTests.h
samples/client/petstore/cpp-qt5/PetStore/StoreApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/StoreApiTests.h
samples/client/petstore/cpp-qt5/PetStore/UserApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/UserApiTests.h
samples/client/petstore/cpp-qt5/PetStore/main.cpp
samples/client/petstore/cpp-qt5/build-and-test.bash

This PR refactor the Qt5 client Petstore tests:
- remove unnecessary headers
- remove unnecessary constructor/destructor for test classes
- avoid `QString` constructor when possible
- `PetStore` executable returns the number of failed tests
- Simplify test logic user `QTimer::singleShoot()` static method
- don't declare lambda if used only one time
- use simple connect to lambda form
- replace `QList<QString>` by `{..., ..., ...}`
The idea is to reduce the test code base without altering its readability. All the change are based on my opinions and I'll be totally ok to discard change that doesn't comply with good practice you'll oppose it to! 😃 

cpp-qt5-client: Improve tests

---

docs/generators/go-experimental.md
docs/generators/go.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
modules/openapi-generator/src/main/resources/go-experimental/model.mustache
modules/openapi-generator/src/main/resources/go/model.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/GoClientOptionsProvider.java
samples/client/petstore/go/go-petstore-withXml/model_enum_class.go
samples/client/petstore/go/go-petstore-withXml/model_outer_enum.go
samples/client/petstore/go/go-petstore/model_enum_class.go
samples/client/petstore/go/go-petstore/model_outer_enum.go

Add the option `enumClassPrefix` to determine the name of the enum class.
cc @antihax @bvwells @grokify @kemokemo @bkabrda

[Go] add option to use class as enum prefix

---

docs/generators/typescript-angular.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java

set angular 8 as the default version

typescript-angular: set angular version 8 as default for ngVersion

---

docs/generators/csharp-netcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/Multimap.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Multimap.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Multimap.cs

[csharp-netcore] Making HTTP response headers dictionary case-insensitive

---

modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiClient.java

Fixes #3702
See issue #457
And similar PR for `okhttp-gson`: #3236 + #3343

[java-client][resteasy] support bearer authentication

---

modules/openapi-generator/pom.xml
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java

[java] use [javaparser] library to detect syntax errors

---

modules/openapi-generator/src/main/resources/python-flask/util.mustache
samples/openapi3/server/petstore/python-flask/openapi_server/controllers/pet_controller.py
samples/openapi3/server/petstore/python-flask/openapi_server/openapi/openapi.yaml
samples/openapi3/server/petstore/python-flask/openapi_server/test/test_pet_controller.py
samples/openapi3/server/petstore/python-flask/openapi_server/util.py
samples/server/petstore/python-flask/openapi_server/util.py

- [X ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branch …

[BUG][Python-Flask] Primitive type bytearray deserialization missing in util.py. #2724

---

modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs

@mandrean , @jimschubert 
This is a simple change which adds the UserAgent to CallApiAsync method, just like it is set in the CallApi method.
This resolves #3595, but there still is some discussion which I'd like to have on the interaction and circular definition on the Configuration object and the RestClient.

[csharp] Update UserAgent in the async version of ClientAPI execute method.

---

.travis.yml
samples/client/petstore/cpp-qt5/PetStore/PetStore.pro
samples/client/petstore/cpp-qt5/build-and-test.bash

This PR perfoms valgrind test for Qt5 client test. https://github.com/OpenAPITools/openapi-generator/pull/3661 is not merge so it should fail (I'll rebase once it is merged).
What do you think of the way I handle valgrind result?

cpp-qt5-client: add valgrind memory test

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Better support for multipart (e.g. multipart/mixed)

Better support for multipart

---

modules/openapi-generator/src/main/resources/csharp-netcore/Multimap.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Multimap.cs

Dictioary -> Dictionary
- [ x ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ x ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
Just a simple spelling error fix.
CC/ @mandrean  @jimschubert

Simple spelling error in dotnet core comments

---

pom.xml
samples/client/petstore/go/go-petstore-withXml/api/openapi.yaml
samples/client/petstore/go/go-petstore/api/openapi.yaml
samples/client/petstore/haskell-http-client/openapi.yaml
samples/server/petstore/jaxrs-spec-interface/src/main/openapi/openapi.yaml
samples/server/petstore/jaxrs-spec/src/main/openapi/openapi.yaml
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/api/openapi.yaml
samples/server/petstore/springboot-reactive/src/main/resources/openapi.yaml

Update the Swagger-Parser version to `2.0.14-OpenAPITools.org-1`
Previous PR #3239

Update to swagger-parser to 2.0.14-OpenAPITools.org-1

---

pom.xml
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

cc @jimschubert (2017/09, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04)

Re-enable kotlin client tests in Shippable CI

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Fixes boolean evaluation following a null check in DefaultCodegen which could result in NPE.
Sets `op.isMultiPart` for a consumes string of starting with `multipart`. This affects all generators, but I think any generator that wants different behavior would be considered an exception.
Should fix #3748 
Changes to DefaultCodegen, so requesting feedback: @OpenAPITools/generator-core-team @OpenAPITools/openapi-generator-collaborators

[core] Set isMultipart=true for multipart operations, fix possible NPE

---

modules/openapi-generator/src/main/resources/r/api.mustache
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R

Handling exception and returning proper message for 3xx response status scenarios
@wing328, please look into this change as well.

[R] feat(r): handling error response for 3xx cases

---

modules/openapi-generator/src/main/resources/python/setup.mustache

Exclude "test" from packages so that it is not installed as top-level package when "pip installing" the generated sdk

[python] Exclude "test" from packages for pip

---

modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ApiClient.java

CC: @bbdouglas, @sreeshas, @jfiala, @lukoyanov, @cbornet, @jeff9finger, @karismann @Zomzog
1.) ApiClient already defines and configures an objectMapper to not fail on unknown properties, but it is not used when parsing the response. The fix uses the pre-configured object mapper instead of the vertx default one
2.) When an operation has no response (or just ones without content), the accept array passed to ApiClient is emtpy. This makes the null check in ApiClient useless, as it still tries to set a null Accept header, which is refused with an NPE. Amend the check with .length > 0 to catch this case.
This fix is for 4.1, which I believe is the version currently living on master, so filing the PR against this branch.

Two tiny fixes for Java Vertx client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OpenAPIGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/serializer/SerializerUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/serializer/SerializerUtilsTest.java

Similar to #233 but for JSON, solution for https://github.com/swagger-api/swagger-core/issues/2828 but in our project.

[core] change JSON serialisation to be deterministic

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

Fixes #3761
This PR fixes the `java.lang.ClassCastException`:
```
java.lang.ClassCastException: io.swagger.v3.oas.models.media.ObjectSchema cannot be cast to io.swagger.v3.oas.models.media.ArraySchema
at org.openapitools.codegen.languages.AbstractJavaCodegen.toDefaultValue(AbstractJavaCodegen.java:721)
at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2058)
at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2271)
at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3706)
at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3654)
at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1918)
at org.openapitools.codegen.languages.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:942) …
```

[java] fix ClassCastException in toDefaultValue()

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/pingSomeObj.yaml

This PR adds the test-case presented in https://github.com/OpenAPITools/openapi-generator/pull/3676#pullrequestreview-276936294 to ensure that valid java code is generated for Schema with similar names (`$_type` and `type`).

[ci][java] Add test case with 'type' and '$_type' properties

---

modules/openapi-generator-maven-plugin/README.md
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

Allow configuring User-Agent via maven plugin + update readme
Fixes #3775

Resolve #3775 - Allow configuring User-Agent via maven plugin + update readme

---

modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache

Have wrapped `JSON.stringify({{paramName}})` like this: `new Blob([JSON.stringify({{paramName}})], {type: 'application/json'})`
fixes #3776

typescript-angular: Set Content-Type for multipart requests in angular

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaInheritanceTest.java

Whilst the spec states that the 'allOf' relationship does not imply a hierarchy:
> While composition offers model extensibility, it does not imply a hierarchy between the models.
> To support polymorphism, the OpenAPI Specification adds the discriminator field.
Unfortunately this does not make sense for many existing use cases, that were supported by older
versions of the generator. Therefore, I've restored the older behavior, specifically
in the case that only a single possible parent schema is present.
I think a more complete solution would generate interfaces for the composed schemas,
and mark the generated class as implementing these.
@wing328 I guess you're probably the best person to review this, given that you overhauled the support for `anyOf`, `allOf`, `oneOf` originally. 
I'd be …

[core] [regression] set parentName when a single possible parent exists

---

modules/openapi-generator/src/main/resources/dart-jaguar/apilib.mustache
samples/client/petstore/dart-jaguar/flutter_petstore/openapi/lib/api.dart
samples/client/petstore/dart-jaguar/flutter_proto_petstore/openapi/lib/api.dart
samples/client/petstore/dart-jaguar/openapi/lib/api.dart
samples/client/petstore/dart-jaguar/openapi_proto/lib/api.dart

IOClient was for pure dart, now we need to use `Client` that will use either IOClient or Browserclient

Add flutter web support on jaguar dart

---

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

Current implementataion of maven plugin has the feature of skipping generation if no changes was detected in schema file. While the skipping itself is applied only when the **skipIfSpecIsUnchanged** option is present in the configuration file - hash calculation is calculated every time:
```
File storedInputSpecHashFile = getHashFile(inputSpecFile);
ByteSource inputSpecByteSource =
inputSpecFile.exists()
? Files.asByteSource(inputSpecFile)
: CharSource.wrap(ClasspathHelper.loadFileFromClasspath(inputSpecFile.toString().replaceAll("\\\\","/")))
.asByteSource(Charsets.UTF_8);
String  inputSpecHash =inputSpecByteSource.hash(Hashing.sha256()).toString();
```
This makes impossible to use remote spec files in pom configuration. FileNotFoundException is thrown at the end of generation phase …

1792 fix remote spec handling and hash calculation

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSSpecServerCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/issue_1347.yaml

Fixed bug where nullApi.java is generated instead of DefaultApi.java to match the default path /{pathParam}
To fix https://github.com/OpenAPITools/openapi-generator/issues/1347

Issue: 1347 Fixed bug where nullApi.java is generated instead of DefaultApi.java. 

---

modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Configuration.cs

- replace deprecated `AddBody` with `AddJsonBody`
- use DefaultHeaders to replace DefaultHeader (deprecated)
cc @mandrean (2017/08), @jimschubert (2017/09)

Fix warnings in the csharp-netcore client

---

modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/Api/PetApiTests.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs

`Changes`
- Add the missing file stream to the form request which is causing file uploads to fail
`cc:`
@mandrean @jimschubert

[C#] [netcore] Add missing files to the form request

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java

Fix #3835 by checking if the `reflect` package has already been imported to the file.
cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07) 
@wing328

[client][go] Avoid duplicated reflect imports

---

modules/openapi-generator-maven-plugin/examples/java-client.xml
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java

This is a following up PR of #3440 to fix the #1792 bug, supporting auth.
Before review & merging this PR, please have a look at and merge #3440.
We have #1792 bug since 3.x, but we had workround at that time.
However the workaround doesn't work well for 4.x, and it still prevents us from upgrading to 4.x.

Following up for #3440 (1792 fix remote spec handling and hash calculation)

---

modules/openapi-generator/src/main/resources/dart2/api.mustache
samples/client/petstore/dart2/openapi/lib/api/pet_api.dart
samples/client/petstore/dart2/openapi/lib/api/store_api.dart
samples/client/petstore/dart2/openapi/lib/api/user_api.dart

- [ X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branch …

Adds Http Info To Dart Api

---

modules/openapi-generator/src/main/resources/typescript-axios/configuration.mustache
samples/client/petstore/typescript-axios/builds/default/configuration.ts
samples/client/petstore/typescript-axios/builds/es6-target/configuration.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/configuration.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/configuration.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/configuration.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/configuration.ts

The typescript-axios template was missing the baseOptions setting when building an API Configuration. Set it.

typescript-axios: Fix baseoptions

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/resources/rust-server/models.mustache
samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs
samples/server/petstore/rust-server/output/rust-server-test/src/models.rs

- @frol, @farcaller, @bjgill 
This adds support for types which only contain additional properties, which is a common use case. It doesn't handle the thornier case of additional properties within a type with defined properties, which is allowed by the OpenAPI spec, but is more dubious API design in practice (as the API is mixing schema-ed and un-schema-ed data).
Note, this will also only fix the case where the type is defined (e.g. string) - if it's untyped, it remains unsupported.
This thus partially fixes https://github.com/OpenAPITools/openapi-generator/issues/318
An example of something this will support is already defined in the sample API:
```
additionalPropertiesObject:
description: An additionalPropertiesObject
type: object
type: string
```

[Rust Server] Support types with additional properties

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/asciidoc/AsciidocSampleGeneratorTest.java

This small PR fixes a javadoc bloc to fix following warning:
> Javadoc: Missing tag for declared exception: Exception

Fix javadoc error

---

.gitignore
modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default/src/apis/PetApi.ts
samples/client/petstore/typescript-fetch/builds/default/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/apis/PetApi.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/src/apis/PetApi.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/apis/PetApi.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/apis/PetApi.ts
samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/src/apis/PetApi.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/apis/PetApi.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts

Resolve an issue described in  https://github.com/OpenAPITools/openapi-generator/issues/3920 ([typescript-fetch] cannot handle with application/x-www-form-urlencoded content).
fixes  #3920 

typescript-fetch: Add application/x-www-form-urlencoded content support

---

README.md

As discussed via e-mail with @wing328 this PR adds the company I work for, Gantner, to the list of users of OpenAPI Generator. I'm raising this against `master` but I'm not sure so please correct if necessary.

Add Gantner (https://www.gantner.com) to the list of users

---

modules/openapi-generator/src/test/resources/3_0/scala_reserved_words.yaml
modules/openapi-generator/src/test/resources/codegen/scala/SomeObj.scala.txt

[scala] add [date-time] field to codegen unit test

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java

- Fix generateAliasAsModels in the default generator (line 496 - 498)
- minor code formatting

Fix generateAliasAsModels in the default generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

Java: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)
Currently it is not possible to use `setArtifactVersion(String)` when you use OpenAPI-Generator programmatically:
```java
JavaJAXRSSpecServerCodegen config = new JavaJAXRSSpecServerCodegen();
config.additionalProperties()
.put(JavaJAXRSSpecServerCodegen.USE_SWAGGER_ANNOTATIONS, "false");
config.setHideGenerationTimestamp(true);
config.setOutputDir(outputDirPath.toFile().getCanonicalPath());
config.setArtifactVersion("0.9.0-SNAPSHOT");
```
Prior to this PR, the code above had no effect, because the value was overridden.

[java] allow to use setArtifactVersion() programmatically

---

modules/openapi-generator-gradle-plugin/pom.xml

`org.gradle:gradle-tooling-api` is on Gradle Releases repository (cf. https://mvnrepository.com/artifact/org.gradle/gradle-tooling-api/4.10.2)
So, we need to add this repository to `pluginManagement`.
Without this setting, following error will occur in some environment.
```
[INFO] --- gradle-maven-plugin:1.0.8:invoke (default) @ openapi-generator-gradle-plugin-mvn-wrapper ---
[WARNING] The POM for org.gradle:gradle-tooling-api:jar:4.10.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] openapi-generator-project .......................... SUCCESS [  3.859 s]
[INFO] openapi-generator-core ............................. SUCCESS [  3.680 s]
[INFO] openapi-generator (core …
```

add gradle repository for using gralde dependency in plugin

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/EncodingUtils.mustache
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/EncodingUtils.java
samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/EncodingUtils.java

Fixes #3635
@bbdouglas
@sreeshas
@jfiala
@lukoyanov
@cbornet
@jeff9finger
@karismann
@Zomzog

Fix issue3635

---

modules/openapi-generator/src/main/resources/php-symfony/api_input_validation.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/StoreController.php

- [+] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [+] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [+] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches) …

Fix wrong variable name in LessThan and LessThanOrEqual asserts

---

docs/faq.md
website/core/Footer.js
website/pages/en/index.js

Replace gitter with Slack in the doc

Replace gitter with Slack in the doc

---

modules/openapi-generator/src/main/resources/cpp-pistache-server/main-api-server.mustache
samples/server/petstore/cpp-pistache/main-api-server.cpp

Remove warnings in pistache main.cpp
@ravinikam  @stkrwork @martindelille  @muttleyxd

[C++] [Pistache] Removed deprecated warnings

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5AbstractCodegen.java
modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/model-header.mustache
modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/model-source.mustache

Add missing enum processing in C++ codegen, already present for Qt5
- Applied changes from #2339 to Abstract Codegen instead of only Qt5
- Adapt the model mustache
Fixes #3970
@ravinikam @stkrwork @MartinDelille @muttleyxd

[C++] [rest-sdk] Add missing enum processing in C++Abstract codegen

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java

According to the last checkbox I think I should tag you, sorry if I'm wrong...
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04)
This PR fixes https://github.com/OpenAPITools/openapi-generator/issues/4002 because Parcelize is stable since Kotlin 1.3.41.

[kotlin] parcelize is now stable

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java

Fixes: #3976 
cc @antihax @bvwells @grokify @kemokemo @bkabrda since this is a Go related change.

go: add os import in case of File return type

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_opt_var.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_req_var.mustache

The Kotlin Multiplatform client introduced an bug that rendered variable names that were also Kotlin reserved words incorrectly. This change reverts the template to use the previous mechanism for rendering variable names.
https://github.com/OpenAPITools/openapi-generator/issues/3992

Fixes invalid Kotlin client variable names for reserved words

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/retrofit/src/main/java/org/openapitools/client/ApiClient.java

CC: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)
The Apache Oltu library is only needed when OAuth is used.
Currently a user is forced to add an Oltu dependency even though it is not used. This PR changes the template to only import Oltu when needed.

[java] Don't import oltu when not necessary

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java

@antihax @bvwells @grokify @kemokemo @bkabrda
Fixes #3972 by adding `import time` when a model has a property of type "array of `time.Time`". Tested against the input in #3972 description.

Import time when properties are slices of time.Time

---

modules/openapi-generator/src/main/resources/haskell-http-client/Core.mustache

This PR fix the issue #4012 4012

Fix trailing comma wrong in template for haskell-http-client

---

modules/openapi-generator/src/main/resources/haskell-http-client/Core.mustache
samples/client/petstore/haskell-http-client/lib/OpenAPIPetstore/Core.hs

[haskell-http-client] disable unused import warning in Core.hs

---

modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
samples/client/petstore/typescript-node/default/api/petApi.ts
samples/client/petstore/typescript-node/default/api/storeApi.ts
samples/client/petstore/typescript-node/default/api/userApi.ts
samples/client/petstore/typescript-node/npm/api/petApi.ts
samples/client/petstore/typescript-node/npm/api/storeApi.ts
samples/client/petstore/typescript-node/npm/api/userApi.ts

Uses the correct Accept media types as specified in the OpenApi
specifications.
relates to #3944
@akehir @macjohnny

[typescript][node]: Add accept header if produces is not empty

---

modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
samples/client/petstore/typescript-fetch/builds/default/src/apis/UserApi.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/apis/UserApi.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/src/apis/UserApi.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/apis/UserApi.ts
samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/apis/UserApi.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/src/apis/UserApi.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/apis/UserApi.ts

typescript-fetch: fix return type of primitive value

---

google_checkstyle.xml

LeftCurly had invalid attribute maxLineLength. Also removed the redundant RightCurly.

[FIX][CORE] Repaired Checkstyle

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-node/api-all.mustache
modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
samples/client/petstore/typescript-node/default/api/apis.ts
samples/client/petstore/typescript-node/default/api/petApi.ts
samples/client/petstore/typescript-node/default/api/storeApi.ts
samples/client/petstore/typescript-node/default/api/userApi.ts
samples/client/petstore/typescript-node/npm/api/apis.ts
samples/client/petstore/typescript-node/npm/api/petApi.ts
samples/client/petstore/typescript-node/npm/api/storeApi.ts
samples/client/petstore/typescript-node/npm/api/userApi.ts

@akehir @macjohnny
Add options to specify a from data file
Be able to specify file options as described on
https://github.com/request/request in the 'multipart/form-data
(Multipart Form Uploads)' section).
Related to #3944
I am new to the OpenApiGenerator and unsure if I did the java part correctly...

typescript-node: form data file

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts

Seralization check should be ensuring the param type is not a string, which matches that of the flow generator logic.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/4050
Fixes incorrect 'type checking' logic for serialisation in api requests.
Typescript technical committee:

[typescript-axios] Fix api generating incorrect seralization type check

---

modules/openapi-generator/src/main/resources/haskell-http-client/stack.mustache
samples/client/petstore/haskell-http-client/stack.yaml

Nobody is listed in the technical committee, but last few PRs were merged by @jonschoning, so cc'ing them.
As the title says, bumped stack.yaml to use lts-14.7. `katip` is already in the snapshot, so no need for `extra-deps`.
I re-generated the `petstore` example and ran the tests, they all passed.

[haskell-http-client] Bump deps to LTS 14.7

---

modules/openapi-generator/src/main/resources/confluenceWikiDocs/index.mustache

improved the Confluence wiki output to fix issues with tables, added information and improved readability within confluence

Fix for issue 4061

---

modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/model/GeneratorInput.java

Fix #4066
The field SecuritySchemeDefinition auth is deprecated and no more used in the generator.
I think we can just remove it.
@wing328 
@jimschubert 
@cbornet 
@ackintosh 
@jmini
@etherealjoy

Remove unused property

---

.travis.yml

Comment out qt5 installation to avoid build failure
```
8.02s$ sudo apt-get install valgrind
before_install.14
1.63s$ sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
13.70s$ sudo apt-get update -qq
W: The repository 'http://ppa.launchpad.net/beineri/opt-qt-5.10.1-trusty/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt-5.10.1-trusty/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update -qq" failed and exited with 100 during .
```

Comment out qt5 installation

---

docs/installation.md
website/pages/en/index.js

Problem:
```bash
cd ./modules/openapi-generator/src/test/resources/3_0/
docker run --rm \
> -v ${PWD}:/local openapitools/openapi-generator-cli generate \
> -i petstore.yaml \
> -g go \
> -o /local/out/go
[error] The spec file is not found: petstore.yaml
[error] Check the path of the OpenAPI spec and try again.
```
Solution: specify absolute path to input file

Fix example docker command line

---

modules/openapi-generator/src/main/resources/python/model_doc.mustache

Fixed Readonly Docs for python

---

bin/csharp-property-changed-petstore.sh
bin/openapi3/csharp-property-changed-petstore.sh
bin/windows/csharp-property-changed-petstore.bat
docs/generators/csharp.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
modules/openapi-generator/src/main/resources/csharp/modelGeneric.mustache

This commit addresses issue #3274 and adds the proposed ``optionalEmitDefaultValues`` flag.

[CSharp] add optional flag "optionalEmitDefaultValues" and update template

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
samples/client/petstore/typescript-fetch/tests/default/mocks.ts

This pull-request is correction patch for https://github.com/OpenAPITools/openapi-generator/pull/3934 . (related to https://github.com/OpenAPITools/openapi-generator/issues/3920 )
URLSearchParams body is converted empty JSON Object by `JSON.stringify` since missing check.

typescript-fetch: fix empty URLSearchParams request body

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java

when package name is changed api and model are still generated in the default folder the rest is generated in the specififed folder
fixes #4109

update api and model path when packagename is updated

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenDiscriminator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
modules/openapi-generator/src/main/resources/Java/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaInflector/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/eap/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/spec/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaPlayFramework/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/JavaSpring/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/java-pkmst/typeInfoAnnotation.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/typeInfoAnnotation.mustache
modules/openapi-generator/src/test/resources/2_0/swift4Test.json

For https://github.com/OpenAPITools/openapi-generator/pull/3320#discussion_r333520784

Rename property name from propertyRawName to propertyBaseName

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/serializer/SerializerUtils.java

- same as object mapper in `toJsonString`, we should copy object mapper when serializing the yaml, in order to avoid setting affects other serialization.
@wing328

serializer object mapper setting fix

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java

fixes #4097 
though the issue was about Angular the issue is a core issue

sanitizes model names so they're valid class/interface names fixes #4097

---

samples/client/petstore/python/tests/test_api_client.py
samples/client/petstore/python/tests/test_pet_api.py

Few test cases now run against localhost which causes the test cases to fail and we have to run petstore locally for that to pass

[Python] Run all test cases against petstore server

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java

This is a fix for a bug I've introduced with #3973 
Due to operator precedence, even if `addedTimeImport` is `true`, the if branch is executed and it results in duplicated `import time` statements in the generated code.
Use this definition (notice `User` has 2 date-time related fields, `joined` and `times`):
```
openapi: 3.0.0
info:
title: Sample OpenAPI Specification
version: 0.0.1
servers:
- url: http://localhost:8080/
description: Example API Service
components:
schemas:
'User':
type: object
required:
- display_name
- email
properties:
name:
type: string
readOnly: true
display_name:
type: string
maxLength: 20
minLength: 1
email:
type: string
format: email
joined:
type: string
format: date-time
times:
type: array
items:
type: string
format: date-time
#type: string
#format: date-time …
```

Fix boolean operators precedence

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5ClientCodegen.java
modules/openapi-generator/src/main/resources/cpp-qt5-client/CMakeLists.txt.mustache
samples/client/petstore/cpp-qt5/CMakeLists.txt
samples/client/petstore/cpp-qt5/client/CMakeLists.txt

Changes:
Add `CMakelists.txt` file for building with `cmake`
@stkrwork @ravinikam @muttleyxd @MartinDelille

[C++] [Qt5] Add generation of cmake files to qt5 client

---

modules/openapi-generator/src/main/resources/python/api.mustache
samples/client/petstore/python/petstore_api/api/fake_api.py
samples/client/petstore/python/petstore_api/api/pet_api.py
samples/client/petstore/python/petstore_api/api/user_api.py
samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py
samples/openapi3/client/petstore/python/petstore_api/api/user_api.py

If we send None for a non mandatory query parameter. OpenAPIGenerator now makes the URL something like `?query=None` this should not be passed as the string None rather should be ignored as None is a special keyword
If the user passes the query as "None" (Str) only then url should be considered as `?query=None`
fixes https://github.com/OpenAPITools/openapi-generator/issues/4151

[python] Skip adding None value in query parameters

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS
Options should not have body or post_params

[python] Remove post_params and body from OPTIONS request

---

.travis.yml
pom.xml
samples/client/petstore/cpp-qt5/PetStore/PetApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/PetApiTests.h
samples/client/petstore/cpp-qt5/PetStore/StoreApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/StoreApiTests.h
samples/client/petstore/cpp-qt5/PetStore/UserApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/UserApiTests.h
samples/client/petstore/cpp-qt5/build-and-test.bash

Fixes #4098
@stkrwork @MartinDelille @muttleyxd @ravinikam 
@wing328

[C++] Enable Qt5 Petstore tests

---

.github/.test/samples.json
.github/auto-labeler.yml

Per comment (https://github.com/OpenAPITools/openapi-generator/issues/802#issuecomment-543615003) from #802, this adds support for "generic" changes for all typescript generators.
Rather than `[typescript-angular]` or any other generator-specific tag, you can use just `[typescript]`.

Support labeling changes which affect all typescript generators with [typescript] (only) in title

---

modules/openapi-generator/src/main/resources/go/client.mustache
samples/client/petstore/go/go-petstore-withXml/client.go
samples/client/petstore/go/go-petstore/client.go
samples/openapi3/client/petstore/go/go-petstore/client.go

- Needed for dynamically changing the underlying implementations and for testing
- Fixes #1321, Fixes #3412
- FYI, I considered exporting the cfg variable instead, but thought this was a more backward compatible change.
- Travis build on my branch passed.
cc @antihax @bvwells @grokify @kemokemo @bkabrda since this is a Go related change.

[Golang] Allow retrieving the underlying configuration for APIClient

---

modules/openapi-generator/src/main/resources/kotlin-client/api.mustache
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt

Fixes OpenAPITools/openapi-generator#3880
For a more complex example than the one from the issue, the generated code looks like this:
```kotlin
fun getClients(withHostname: kotlin.String, page: kotlin.Int?, size: kotlin.Int?, withOrg: kotlin.String?) : Clients {
val localVariableBody: kotlin.Any? = null
val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
.apply {
if (page != null) {
put("page", listOf(page.toString()))
}
if (size != null) {
put("size", listOf(size.toString()))
}
put("withHostname", listOf(withHostname.toString()))
if (withOrg != null) {
put("withOrg", listOf(withOrg.toString()))
}
}
[...]
}
```
Reviewers: @jimschubert , @dr4ke616 , @karismann , @Zomzog

Fix generation of query parameters for optional/nullable function arguments

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/api.mustache

- add `isNullable` check in query parameter
- minor code format enhancement
@jimschubert (2017/09), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04)

[Kotlin][client] Add nullable query parameter support

---

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_store.go
samples/server/petstore/go-api-server/go/api_user.go

Update the go server api controller template to return the Router interface instead of the api specific router.
The Router interface type has the Routes function, which is what the generated `NewRouter` function needs. (not the api specific interface).
The change added in https://github.com/OpenAPITools/openapi-generator/pull/4038 would cause the following error since it was working with the wrong interface type 
```
./main.go:38:36: cannot use PetApiController (type petstoreserver.PetApiRouter) as type petstoreserver.Router in argument to petstoreserver.NewRouter:
petstoreserver.PetApiRouter does not implement petstoreserver.Router (missing Routes method)
```
@antihax @bvwells @grokify @kemokemo @bkabrda

[go-server] Return Router interface from controller constructor.

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm/infrastructure/ApiClient.kt.mustache
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

When using bearer authentication or oauth, the tokens are used even if they are null.
Here is the generated code:
```
protected fun updateAuthParams(requestConfig: RequestConfig) {
if (requestConfig.headers[Authorization].isNullOrEmpty()) {
requestConfig.headers[Authorization] = "Bearer " + accessToken
}
}
```
The problem is that if accessToken is null, the header "Authentication" will have the value "Bearer null" and the server will return Http Status Code 500 instead of 401.
Instead of the above code, I suggest generating something like this.
```
protected fun updateAuthParams(requestConfig: RequestConfig) {
if (requestConfig.headers[Authorization].isNullOrEmpty()) {
accessToken?.let { accessToken ->
requestConfig.headers[Authorization] = "Bearer " + accessToken
}
}
}
```
Fixes …

[kotlin][client] only use authentication tokens when they are not null

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/data_class_opt_var.mustache
modules/openapi-generator/src/main/resources/kotlin-client/data_class_req_var.mustache

Property names that include a dollar sign are being interpreted
by Kotlin as a string template. This fix escapes such instances.
https://github.com/OpenAPITools/openapi-generator/issues/4228

Fixes Kotlin client property names that include a dollar sign

---

docs/generators/csharp.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java

- Deprecated netstandard, uwp support in csharp generator and suggest `csharp-netcore` instead
- to close https://github.com/OpenAPITools/openapi-generator/issues/4202
cc @mandrean (2017/08) @jimschubert (2017/09) @frankyjuang (2019/09)

Deprecated netstandard, uwp support in csharp generator

---

modules/openapi-generator/src/main/resources/python/model.mustache
samples/client/petstore/python/petstore_api/models/enum_class.py
samples/client/petstore/python/petstore_api/models/outer_enum.py
samples/openapi3/client/petstore/python/petstore_api/models/enum_class.py
samples/openapi3/client/petstore/python/petstore_api/models/outer_enum.py
samples/openapi3/client/petstore/python/petstore_api/models/outer_enum_default_value.py
samples/openapi3/client/petstore/python/petstore_api/models/outer_enum_integer.py
samples/openapi3/client/petstore/python/petstore_api/models/outer_enum_integer_default_value.py

Currently, there is no way to get the list of allowed values for an enum. This PR adds a class variable to get all the allowed values
Why this is needed?
fixes https://github.com/OpenAPITools/openapi-generator/issues/4139

[python] Add ability to get allowed values

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

The old code boostrapping TLS settings used to work with older okhttp (< 3), but will throw NullPointerExceptions with okhttp3, which I noticed while working on kubernetes-client/java#709.
cc @wing328 @yue9944882 @brendandburns

okhttp-gson: fix SSL settings with okhttp3

---

CI/samples.ci/client/petstore/java/test-manual/okhttp-gson/api/PetApiTest.java
samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/api/PetApiTest.java

Test setVerifyingSsl to ensure it doesn't throw NPE
For #4226 

[Java][okhttp] Test setVerifyingSsl

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/resources/dart-dio/class.mustache
modules/openapi-generator/src/main/resources/dart-dio/enum.mustache

The `dart-dio` generator does not generate the `enum` class properly. The current implementation seems to be from an existing `dart` generator.
@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09)

fix(dart-dio): enum class generation is not implemented

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaUndertowServerCodegen.java

- There don't seem to be integration tests for `java-undertow-server`
- Added as reviewers 
------------------------------
When using the `java-undertow-server` generator, the location/package of  `PathHandlerProvider.java` isn't customizable, so this PR uses the `apiPackage` / `--api-package` option. 
Therefore when using this cli with these options `generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -g java-undertow-server --api-package com.github.loveisgrief.api  -o out/`
this is the output
```
/home/ubuntu/Programming/Projects/Java/openapi-generator/out
├── pom.xml
├── README.md
└── src
└── main
├── java
│   ├── com
│   │   └── github
│   │       └── loveisgrief
│   │           └── …
```

Place PathHandlerProvider.java of java-undertow-server in the apiPackage dir

---

bin/ci/php-slim-server-petstore.json
bin/openapi3/php-slim-server-petstore.sh
bin/php-slim-server-petstore.sh
bin/windows/php-slim-server-petstore.bat
docs/generators.md
docs/generators/php-slim-deprecated.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlim4ServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlimServerCodegen.java

Abandon Slim3 generator in favor of Slim4. #3658 
It doesn't make sense to enhance/support generator based on outdated framework.

Mark Slim3 server generator as deprecated

---

modules/openapi-generator/src/main/resources/dart-dio/api.mustache
samples/client/petstore/dart-dio/lib/api.dart
samples/client/petstore/dart-dio/lib/api/pet_api.dart
samples/client/petstore/dart-dio/lib/api/store_api.dart
samples/client/petstore/dart-dio/lib/api/user_api.dart
samples/client/petstore/dart-dio/lib/model/api_response.dart
samples/client/petstore/dart-dio/lib/model/category.dart
samples/client/petstore/dart-dio/lib/model/order.dart
samples/client/petstore/dart-dio/lib/model/pet.dart
samples/client/petstore/dart-dio/lib/model/tag.dart
samples/client/petstore/dart-dio/lib/model/user.dart
samples/client/petstore/dart-dio/lib/serializers.dart

If a the paramName inside a swagger doc is called data then the generated code does not compile.
- [ Y] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ Y] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ Y] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if …

Fix conflict if swagger paramName is data

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java

At the moment models starting with numbers generate invalid code. This PR makes a change to add model in such scenarios similar to other languages

[Dart] [Bug] Handle model names starting with number

---

README.md
docs/generators.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaVertXWebServerCodegen.java

Minor improvement to the Java vertx web server generator
- mark as beta
- minor change to default output directory
- update template creator
cc @lwlee2608

Minor improvement to the Java vertx web server generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java

Adds support for `kotlin.collections.Set` array types, when interpreting `ArraySchema.getUniqueItems()`
@jimschubert @dr4ke616 @karismann @Zomzog

[Kotlin] Add kotlin.collections.Set support for unique item arrays

---

modules/openapi-generator/src/main/resources/Java/README.mustache
modules/openapi-generator/src/main/resources/Java/api_doc.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/README.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api_doc.mustache
modules/openapi-generator/src/main/resources/htmlDocs2/sample_java.mustache

The Readme files generated  for java currently only adds HttpBasicAuth example. This update checks if the auth is a bearer auth and adds appropriate example for that. 
This fixes #4178

Add bearer token authentication documentation to template

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/petstore/python-asyncio/petstore_api/api_client.py
samples/client/petstore/python-tornado/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py

datetime is misspelled as datatime

[Python] [Bug] Correct typo in the word datetime

---

modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ApiAbstractions.kt.mustache
samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt
samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt
samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt
samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt
samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt
samples/openapi3/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt
samples/openapi3/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt

Fixes incorrect query header collection constants
The OpenAPI generator converts OpenAPI v2 documents into an OpenAPI v3
representation. The query parameter collection formats are squeezed
into different values from the raw OpenAPI 2 collection format values.
For example: csv -> space
See: DefaultCodegen#getCollectionFormat
To fix https://github.com/OpenAPITools/openapi-generator/issues/4285

Kotlin query collection format

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/petstore/python-asyncio/petstore_api/api_client.py
samples/client/petstore/python-tornado/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py

If statement has a return statement inside it. There is no need for having else and introducing indentation in the code.

[Python] Remove redundant else statement

---

modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache

fixes #4330, analogous to #3423.

fix(typescript-angular): do not call .toISOString() on a string (#4330)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-angular/model.mustache
modules/openapi-generator/src/main/resources/typescript-angular/models.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularModelTest.java

fixes https://github.com/openAPITools/openapi-generator/issues/4130
fixes https://github.com/openAPITools/openapi-generator/issues/3149

typescript-angular: fix oneOf and anyOf generates incorrect model for primitive types

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/feign/build.sbt.mustache
modules/openapi-generator/src/main/resources/Java/libraries/feign/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache
samples/client/petstore/java/feign/build.gradle
samples/client/petstore/java/feign/build.sbt
samples/client/petstore/java/feign/pom.xml
samples/client/petstore/java/feign10x/build.gradle
samples/client/petstore/java/feign10x/build.sbt
samples/client/petstore/java/feign10x/pom.xml
samples/client/petstore/java/webclient/pom.xml

- Fix security alerts due to com.fasterxml.jackson.core:jackson-databind
```
CVE-2019-16942 More information
moderate severity
Vulnerable versions: < 2.9.10.1
Patched version: 2.9.10.1
A Polymorphic Typing issue was discovered in FasterXML jackson-databind 2.0.0 through 2.9.10. When Default Typing is enabled (either globally or for a specific property) for an externally exposed JSON endpoint and the service has the commons-dbcp (1.4) jar in the classpath, and an attacker can find an RMI service endpoint to access, it is possible to make the service execute a malicious payload. This issue exists because of org.apache.commons.dbcp.datasources.SharedPoolDataSource and org.apache.commons.dbcp.datasources.PerUserPoolDataSource mishandling.
```
cc @bbdouglas (2017/07) @sreeshas (2017/08) …

[Java] Fix security alerts due to com.fasterxml.jackson.core:jackson-databind

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache

The typescript-fetch generator incorrectly using the `modelName` as the identifier for tagged unions (discriminators). This PR patches that by using the `mappingName` instead, as this may have been set to an arbitrary value.
cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce @akehir

[typescript-fetch] Fix discriminator mapping name

---

modules/openapi-generator/src/main/resources/Javascript/es6/package.mustache
samples/client/petstore/javascript-es6/package.json
samples/client/petstore/javascript-promise-es6/package.json
samples/openapi3/client/petstore/javascript-es6/package.json

Fixes #4258. Update package.json and package.mustache in some js packages. TypeScript files left unchanged.
openapi-generator version 4.1.3

[JS] Update package.json

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/petstore/python-asyncio/petstore_api/api_client.py
samples/client/petstore/python-tornado/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py

Current code violates pep8 rule
> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants
Ref: https://www.python.org/dev/peps/pep-0008/#imports

[Python] Avoid pep8 violation

---

modules/openapi-generator-gradle-plugin/build.gradle
modules/openapi-generator-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
modules/openapi-generator-gradle-plugin/pom.xml
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt

**Description**
```
A problem occurred evaluating project ':ua.aval.biz.client.android'.
> Failed to apply plugin [id 'org.openapi.generator']
> Could not create an instance of type org.openapitools.generator.gradle.plugin.extensions.OpenApiGeneratorGenerateExtension.
> Please use the ObjectFactory.mapProperty() method to create a property of type Map<K, V>.
```
There error was produced in Gradle 6.0-rc-2
**openapi-generator version**
4.2.0
**Related issues/PRs**
#2613

Remove deprecated API use of ObjectFactory.property() (#2613)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
modules/openapi-generator/src/test/resources/3_0/unusedSchemas.yaml

[core] consider polymorphism when computing unused schemas

---

modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs

Fixes #4343 
Same fix as applied to the csharp generator in #3537

csharp-netcore: Replace null literals with default

---

bin/utils/openapi-generator-cli.sh

Fixes a misspelling in the cache directory environment variable introduced in #3631, warning users that they need to migrate to the properly spelled variable.
Also creates the directory if it doesn't exist.

[cli][script] Fix misspelling in cli bootstrapping script

---

modules/openapi-generator/src/main/resources/Javascript-Flowtyped/modelGeneric.mustache

Issue: https://github.com/OpenAPITools/openapi-generator/issues/4262
Javascript Flowtyped generator does not add parent type to created types.
Example how it is now:
```
type ChildType = { ... }
type ParentType = { ... }
```
What's done:
```
type ChildType = { ... } & ParentType
type ParentType = { ... }
```
In this case Flow will not complain when client code will access fields from ParentType if object has ChildType.
What do you think?

[JavascriptFlowtyped] Adding parent flow type to child type using "& ParentType" to allow flow js access parent fields from child types

---

CI/samples.ci/client/petstore/java/test-manual/okhttp-gson/api/PetApiTest.java
samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/api/PetApiTest.java

Skip the getPetById result test as async call may have finished (to address the intermittent errors we're seeing with CircleCI build failure)

[Java] skip the test as async call may have finished

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
samples/client/petstore/python-asyncio/petstore_api/api_client.py
samples/client/petstore/python-tornado/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py

isinstance is not a very cheap operation and this check is being performed multiple times inside the for loop unnecessarily.

[Python] [Performance] Avoid unnecessary checks inside the loop

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java

This applies #4229, which fixes #4228 but on all vars, not only on `requiredVars` and `optionalVars`.
This allows template overrides relying on another set of `vars` to work properly.
(For example, our templates rely on `vars` so we don't need req_var and opt_var templates)

Fixes Kotlin client property names that include a dollar sign for template overrides

---

README.md

Add https://98elements.com/blog/generating-api-clients-based-on-openapi-v3-specifications/ to README.

Add a blog post tutorial about generating Java clients using OpenAPI v3

---

README.md
docs/integration.md

Add sbt, bazel to integration

---

.travis.yml
modules/openapi-generator-maven-plugin/examples/kotlin.xml
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java

This change will prevent a ClassCastException during execution of the generator maven plugin. 
When executed as maven plugin, boolean config options have the type java.lang.Boolean. When executed as CLI generator boolean config options have the type java.lang.String. Before this fix, only the latter case could be handled properly and the first case caused a ClassCastException.

[kotlin] [bugfix] [maven-plugin]: prevent ClassCastException with boolean config options

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelEnum.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
samples/client/petstore/typescript-fetch/builds/default/src/models/Order.ts
samples/client/petstore/typescript-fetch/builds/default/src/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/models/Order.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/src/models/Order.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/src/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/models/Order.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/models/Order.ts
samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/src/models/Order.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/src/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/models/Order.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/models/Pet.ts

The typescript-fetch generator can still generate code with type failures in the case of nullable enum values. This addresses this by applying a similar fix that was made to modelGenericMustache to modelEnumMustache.
In addition, tweak the previous fix to modelGenericMustache so that it handles null and undefined separately rather than using == to map them both to undefined. There is a difference between a key existing vs. a key existing with a null value.

[typescript-fetch] Fix for nullable enums + separate treatment of null and undefined

---

docs/generators/go-server.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
modules/openapi-generator/src/main/resources/go-server/routers.mustache

Add a Go server configuration option of "featureCORS" that defaults to false. When set to true the Go server routers will be generated with Cross-Origin Resource Sharing middleware through gorilla mux.
https://www.gorillatoolkit.org/pkg/handlers#CORS
Accepting cross origin requests is something that I needed in my project. I accomplished it with a custom template, but just in case anyone else would like this feature I put up this PR.

[go-server] Add featureCORS option

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
modules/openapi-generator/src/main/resources/go-server/routers.mustache
samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_store.go
samples/server/petstore/go-api-server/go/api_user.go
samples/server/petstore/go-api-server/go/routers.go

- minor enhancement to the template

[Go][Server] minor enhancement to the template

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.cpp.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.h.mustache
samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp
samples/client/petstore/cpp-qt5/client/PFXHttpRequest.h

This PR replace part of the job done here: #3688
The idea is to simplify the timer management by replacing the `QTimer` instance by a call to the `QTimer::singleShot()` static method`.
- x ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Simpler timeout with QTimer::singleShot

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.cpp.mustache
samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp

This fix the problem mentionned here: https://github.com/OpenAPITools/openapi-generator/pull/4430#issuecomment-552183699

fixup! Simpler timeout with QTimer::singleShot (#4430)

---

modules/openapi-generator/src/main/resources/typescript-rxjs/apis.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/modelGeneric.mustache

Support [nullable](https://swagger.io/docs/specification/data-models/data-types/#null) for typescript-rxjs same as #3645 #1730 #1743.
cc: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07)

[typescript-rxjs]: Add support for nullable

---

modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
modules/openapi-generator-core/src/test/java/org/openapitools/codegen/config/WorkflowSettingsTest.java
modules/openapi-generator-gradle-plugin/samples/local-spec/README.md
modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle

When WorkflowSettings was constructed from an existing instance, as is
the case when we deserialize from an external configuration file, it
would result in an error:
```
Caused by: java.lang.UnsupportedOperationException
at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:450)
at org.openapitools.codegen.config.WorkflowSettings$Builder.withSystemProperty(WorkflowSettings.java:465)
```
This was due to an error in `newBuilder(WorkflowSettings copy)` which
assigned builder.systemProperties with an immutable map. This is
incorrect because everything in the builder should be mutable until
.build() is invoked.
see #3815
I'm tagging with Gradle Plugin because this is where it was noticed. This likely affects CLI/Maven plugin as well for version 4.1.1 through 4.2.0.
cc …

[core] Fix system properties being immutable

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java

Addresses issue #4375 for java resttemplate and java webclient

[Java]: Client resttemplate and webclient: array parameters of type integer in path badly generated

---

modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache
samples/client/petstore/java/webclient/pom.xml
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/webclient/src/test/java/org/openapitools/client/api/PetApiTest.java

Spring supports [automatic instrumentation](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics-http-clients) of `WebClient` and `RestTemplate` to capture metrics when using injected clients. When instrumenting these HTTP clients, a URI template must be provided to properly group parameterized HTTP requests. For example, given a URI `/resources/{id}`, metrics should be captured under `/resources/{id}` instead of`/resources/1234`/`resources/4321`/etc.
Currently, the OpenAPI generated `RestTemplate` clients use [RestTemplate.getUriTemplateHandler](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html#getUriTemplateHandler--), which _can_ capture URI templates and …

[Java] Refactor webClient generator to use URI templates to capture correct metrics

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java
modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache
samples/client/petstore/cpp-qt5/PetStore/PetApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/PetApiTests.h
samples/client/petstore/cpp-qt5/PetStore/StoreApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/StoreApiTests.h
samples/client/petstore/cpp-qt5/PetStore/UserApiTests.cpp
samples/client/petstore/cpp-qt5/PetStore/UserApiTests.h
samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp
samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
samples/client/petstore/cpp-qt5/client/PFXPetApi.h
samples/client/petstore/cpp-qt5/client/PFXStoreApi.cpp
samples/client/petstore/cpp-qt5/client/PFXStoreApi.h
samples/client/petstore/cpp-qt5/client/PFXUserApi.cpp
samples/client/petstore/cpp-qt5/client/PFXUserApi.h

This PR replace part of the job done here: #3688 
Now that the base path is well handled, the API class can use the one provided in the API description.
There was previously a mismatch between host and base path as mentionned here: #3399

cpp-qt5-client: remove host since it is not well handled

---

modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/ApiResponse.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiResponse.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiResponse.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Configuration.cs

This PR resolves an issue with the ApiException error content described in #3473 .
The issue is linked to migration to the generic `IRestResponse<T>`. The deserialization happens before the exception is actually checked by `ExceptionFactory`.
Possible fix is to propagate both raw response content from `IRestResponse.Content` as well as `IRestResponse<T>.Data` to the `ApiResponse`.
But I think it makes sense to roll back to the older implementation, where deserialization happed if an exception hadn't been constructed.
Technical committee: @mandrean (2017/08), @jimschubert (2017/09) ❤️ @frankyjuang (2019/09)

[csharp-netcore] Propagate raw content to the ApiException error content.

---

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java

Otherwise the client has to check for the type (InterruptedException) of the cause of the thrown exception.
Fixes #4380 
Note that I didn't commit the output of running the ./bin/ scripts... it seemed to create a much larger diff than I expected, that I'm not sure it's doing the right thing. 
Tech-committee for java: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

Re-interrupt the thread in the generated code

---

bin/utils/ensure-up-to-date

bin/elm-petstore-all.sh invokes elm-petstore.sh and
elm-0.18-petstore.sh. Both of these define `ELM_POST_PROCESS_FILE` for
post-processing the generated files. If a user doesn't have elm-format
installed, they may not realize that ensure-up-to-date has failed which
causes CI to fail due to differences in the ELM generated outputs.
This confusion can lead to a lot of downtime for contributors. For
example, I encountered this while adding feature set information to all
generators. I thought I had introduced the error and spent too long
looking through my changeset and re-running `ensure-up-to-date`
in the background before noticing the failed output. I was able to
generate proper output by installing elm-format. With 80+ languages/frameworks
and a rule for contributors to unblock CI by …

[ci] Removes elm from ensure-up-to-date

---

modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ApiAbstractions.kt.mustache
samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiAbstractions.kt

When using non public api, there is one typealias in ApiAbstractions that is still public.
This PR fixes that https://github.com/OpenAPITools/openapi-generator/issues/4477.
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10)

[kotlin][client] improve nonpublic api

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache

Using `oneOf`s with `typescript-fetch` results in union types, but lacks decoders and encoders for them. This PR patches that. I've also added support for the discriminator (resulting in tagged unions).
@wing328 Is there already a YAML available for testing oneOfs/allOfs/discriminators? Otherwise I would like to add a generic one.
cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce @akehir

[typescript-fetch] Add (de)serializers for oneOfs

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java

#4449 introduced a dependency on to a relative file location and means that `./bin/run-all-petstore` produces error messages when used. I've switched this to load as a resource from the classpath instead.
@nickmeinhold, @wing328 were involved in the original MR and are probably best to review.

DartClientCodegen reads dart-keywords.txt as resource, not file

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/resources/dart-dio/serializers.mustache

https://github.com/google/built_value.dart/issues/134
`dart-dio` generator does not handle `Map<String, dynamic>` properly. This PR fixes this issue using `JsonObject`. 
- `Map<String, Object>` should be `BuiltMap<String,JsonObject>`
- `List<Object>` should be `BuiltList<JsonObject>`
```yaml
Test:
properties:
objectMap:
type: object
type: object
objectList:
type: array
items:
type: object
```
```dart
@nullable
@BuiltValueField(wireName: 'objectMap')
BuiltMap<String, JsonObject> get objectMap;
@nullable
@BuiltValueField(wireName: 'objectList')
BuiltList<JsonObject> get objectList;
```
CC: @ircecho @swipesight @jaumard @nickmeinhold @athornz

feat(dart-dio): correctly handle Map<String, Object>, List<Object> using JsonObject

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaInheritanceTest.java

Related to #4171.
When a composed schema has `required` attributes, it incorrectly adds duplicate `optionalVars` from the parent which should have been in the `requiredVars` and deduplicated.
For example:
```json
{
"Parent": {
"required": [
"a"
],
"type": "object",
"properties": {
"a": {
"type": "string"
}
}
},
"Child": {
"required": [
"a",
"c"
],
"type": "object",
"allOf": [
{
"$ref": "#/components/schemas/Parent"
},
{
"type": "object",
"properties": {
"c": {
"type": "string"
}
}
}
]
}
}
```
If a template loops required and optional properties separately it generates something like the following, where the property `c` is duplicated:
```kotlin
data class Child (
@Json(name = "a")
val a: kotlin.String,
@Json(name = "c")
val c: kotlin.String,
@Json(name = "c")
val c: kotlin.String? = null …
```

[default codegen] #4171 - Correct parent variables being duplicated in child

---

bin/cpp-qt5-petstore.json
bin/cpp-qt5-petstore.sh

This PR use the new ``--config`` option in the `bin/cpp-qt5-petstore.sh` script.
@ravinikam @stkrwork @etherealjoy @muttleyxd @jimschubert

Use bin/cpp-qt5-petstore.json

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java

when `--additional-properties unhandledException=false` is set, it does not take effect.
cc

[Java][Spring] minor bug fix on unhandledException flag

---

modules/openapi-generator/src/main/resources/haskell-servant/API.mustache
samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/API.hs

I messed up the Pull-Request https://github.com/OpenAPITools/openapi-generator/pull/4056 
Here is the fix containing three indentations.
@jonschoning could you please apply this fix?

[FIX][Haskell-servant] missing indent on the new feature pull request.

---

modules/openapi-generator/src/main/resources/dart/api_client.mustache
modules/openapi-generator/src/main/resources/dart2/api_client.mustache
samples/client/petstore/dart/flutter_petstore/openapi/lib/api_client.dart
samples/client/petstore/dart/openapi-browser-client/lib/api_client.dart
samples/client/petstore/dart/openapi/lib/api_client.dart
samples/client/petstore/dart2/openapi/lib/api_client.dart

Add HEAD method to ApiClient of dart codegen

---

modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
samples/client/petstore/php/OpenAPIClient-php/tests/DateTimeSerializerTest.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/tests/DateTimeSerializerTest.php

FYI @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @ybelenko, @renepardon

[PHP] Include microseconds in serialized date-time

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/AbstractGoCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

This is my attempt to fix #4362 for the two languages that I'm having this issue with.
What do you think ?
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608
@antihax @bvwells @grokify @kemokemo @bkabrda

[Java][Go] Unalias schema in getTypeDeclaration when not generating model for alias

---

docs/generators/go-experimental.md
docs/generators/go.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
modules/openapi-generator/src/main/resources/go-experimental/api.mustache
modules/openapi-generator/src/main/resources/go/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/GoClientOptionsProvider.java

Add an option whether to prefix struct with the class name. e.g. DeletePetOpts => PetApiDeletePetOpts"
Tested locally with Go Petstore client

Add an option to prefix Go struct with the classname

---

docs/usage.md
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/GenerateBatch.java

This documents the `batch` command introduced in 4.2.1 and currently executing CI sample regeneration.

[cli][doc] Document batch command

---

CI/circle_parallel.sh
samples/client/petstore/dart2/petstore_client_lib/lib/api_client.dart
samples/client/petstore/go-experimental/go-petstore/client.go
samples/openapi3/client/petstore/go/go-petstore/client.go

Use non-batch mode in ensure-up-to-date as batch mode doesn't cover everything in the non-batch mode.
cc @jimschubert

Use non-batch mode in ensure-up-to-date

---

.travis.yml
pom.xml

- elm 0.18 installation failed over the weekend and as a result we disable elm and TS Angular 4 tests for the time being.

Disable elm and TS Angular 4 tests

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/issue4584.yaml

See 
https://github.com/OpenAPITools/openapi-generator/issues/4584
```[INFO] Reactor Summary for openapi-generator-project 4.2.2-SNAPSHOT:
[INFO] 
[INFO] openapi-generator-project .......................... SUCCESS [  1.792 s]
[INFO] openapi-generator-core ............................. SUCCESS [  6.641 s]
[INFO] openapi-generator (core library) ................... SUCCESS [ 52.734 s]
[INFO] openapi-generator (executable) ..................... SUCCESS [ 19.343 s]
[INFO] openapi-generator (maven-plugin) ................... SUCCESS [  6.183 s]
[INFO] openapi-generator-gradle-plugin (maven wrapper) .... SUCCESS [ 19.095 s]
[INFO] openapi-generator-online ........................... SUCCESS [  5.514 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD …
```

Maintains state of hasMore when security is filtered

---

Dockerfile

In order to have `openapi-generator` in the path, I symlinked `docker-entrypoint.sh`.
@wing328

Add openapi-generator executable to docker container

---

modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache

Simple typo in Ruby client.
--

[Ruby] Fix typo in description

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/asciidoc/AsciidocSampleGeneratorTest.java

[asciidoctor] javadoc: add missing tag for declared exception

---

modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
modules/openapi-generator/src/main/resources/typescript-node/models.mustache
samples/client/petstore/typescript-node/default/api/petApi.ts
samples/client/petstore/typescript-node/default/api/storeApi.ts
samples/client/petstore/typescript-node/default/api/userApi.ts
samples/client/petstore/typescript-node/default/model/models.ts
samples/client/petstore/typescript-node/npm/api/petApi.ts
samples/client/petstore/typescript-node/npm/api/storeApi.ts
samples/client/petstore/typescript-node/npm/api/userApi.ts
samples/client/petstore/typescript-node/npm/model/models.ts

This PR adds support for bearer token authentication as well as adding a general interceptor pattern to allow for adding arbitrary headers etc.
Let me know if you prefer a PR against 4.3.x or 5.0.x instead.
Relates to #1133 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11)

typescript-node: support bearer token authentication

---

modules/openapi-generator/src/main/resources/typescript-rxjs/modelAllOf.mustache
modules/openapi-generator/src/main/resources/typescript-rxjs/models.mustache

fixes #4629
Hello.
When using rxjs, a warning occurred in unused import.
I tried to fix it, so please take a look if you like.
Before
```js
// tslint:disable
/**
* My application
* My application
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
import {
Box,
Response,
} from './';
/**
* @export
* @interface BoxResponse
*/
export interface BoxResponse extends Box, Response{
/**
* @type {string}
* @memberof BoxResponse
*/
status?: BoxResponseStatusEnum;
/**
* @type {number}
* @memberof BoxResponse
*/
id?: number;
/**
* @type {string}
* @memberof BoxResponse
*/
name?: string;
}
/**
* @export
* @enum {string}
*/
export enum …
```

[typescript-rxjs][client] Unnecessary imports occurs when using allOf

---

modules/openapi-generator/src/main/resources/go/client.mustache
modules/openapi-generator/src/main/resources/go/configuration.mustache
samples/client/petstore/go/go-petstore-withXml/client.go
samples/client/petstore/go/go-petstore-withXml/configuration.go
samples/client/petstore/go/go-petstore/client.go
samples/client/petstore/go/go-petstore/configuration.go

The following change adds a new configuration setting, which
controls whether clients want to dump the HTTP request and response.
Useful when debugging API calls and clients.

Add support for dumping request and response in Go generated clients

---

modules/openapi-generator/pom.xml

Fix the following errors in CI
```
WARN: Unable to load JNA library (OS: Linux 4.15.0-1037-gcp)
java.lang.NoClassDefFoundError: com/sun/jna/Native
at org.jetbrains.kotlin.com.intellij.jna.JnaLoader.load(JnaLoader.java:16)
at org.jetbrains.kotlin.com.intellij.jna.JnaLoader.isLoaded(JnaLoader.java:29)
at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:54)
at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:46)
at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.setFileAttributes(ZipHandler.java:62)
at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:44)
at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHand …
```

Add net.java.dev.jna to resolve "Unable to load JNA library"

---

modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/model.mustache
samples/client/petstore/R/R/pet.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R

Hi William,  @wing328 
This change makes use of `loadNamespace` instead of `package:{{packageName}}`.
The latter requires that the package be attached to the search path when using
`as.environment` (this can cause issues when it is not). The current change loads
the namespace before its use. 
cc: @Ramanth @saigiridhar21

[BUG][R] use loadNamespace instead of package:pkgName string

---

modules/openapi-generator/src/main/resources/typescript-node/model.mustache

Support nullable for typescript-node, same as #4438 #3645 #1730 #1743.
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11)

[typescript-node]: Add support for nullable

---

modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache

After I use c-libcurl generator to generate kubernetes API, the compiling fails due to the lost of apiClient->accessToken. I think below fix is right to guard free().
@PowerOfCreation @zhemant ❤️

[C-libcurl]Update the condition to free apiClient->apiKeys to avoid compilation error

---

modules/openapi-generator/src/main/resources/r/api_client.mustache
samples/client/petstore/R/R/api_client.R

This PR handles a missing case when deserializing empty json arrays of non-primitive types scenario.
cc @saigiridhar21
@wing328, please take a look at this and please run the required tests on other R clients (Namsor R SDK) as required.

fix(r): fixing serializatin bug in empty json array

---

modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/UserApi.java

Addresses issue #4687 for  java webclient

Error in the reactive client when the path variables are a list (#4687)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/RubyClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/oneOf.yaml

This PR fixes this issue:
https://github.com/OpenAPITools/openapi-generator/issues/4515
Currently, when we process composedSchemas, we are not including any properties that are described in the `properties` section of that model's schema. An example is the below fruit model, which leaves out the color property when we ingest it and make a model.
```
openapi: 3.0.1
info:
title: fruity
version: 0.0.1
paths:
/:
get:
responses:
'200':
description: desc
content:
schema:
$ref: '#/components/schemas/fruit'
components:
schemas:
fruit:
title: fruit
properties:
color:
type: string
oneOf:
- $ref: '#/components/schemas/apple'
- $ref: '#/components/schemas/banana'
resolved
apple:
title: apple
type: object
properties:
kind:
type: string
banana:
title: banana
type: object
properties: …
```

[Java/Core] Adds properties to ComposedSchema models when they exist

---

bin/openapi3/kotlin-client-petstore-nullable-required.sh
bin/openapi3/windows/kotlin-client-nullable-required.bat
modules/openapi-generator/src/main/resources/kotlin-client/data_class_req_var.mustache
modules/openapi-generator/src/test/resources/3_0/petstore-with-nullable-required.yaml

Fixes #4651.
- consumes the OpenApi 3.0 nullable field definition; if defined, even required fields will be nullable.
- required-nullable fields won't have a default value. The field is still required to exist - only it's value is null.
- added new kotlin-client sample to show the nullable-field changes
- in the model "Pet" the field "name" is now nullable. In the yaml it is defined as a required nullable field.
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10)

[Kotlin][Client] Added support for consuming OpenApi 3.0 nullable required fields

---

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Validate.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java

OAS 3.x specification isn't entirely clear on oneOf support. JSON Schema
defines oneOf in such a way that the Schema is only valid if it
validates against exactly one of the referenced Schemas. This suggests
that a Schema defined with oneOf can't include additional "dynamic"
properties. OpenAPI extends on this by adding the necessary
discriminator object, which allows tooling to decide the intended
Schema.
As tooling, openapi-generator may support loose or confusing definitions
in the Specification to better support our user's use cases. In this
case, we may warn that while this usage is technically valid the two
target specifications are unclear about the actual constraints regarding
oneOf.
This adds the warning and recommendation I proposed in review of #4482
cc @spacether …

[core] Provide User feedback on confusing use of oneOf

---

CONTRIBUTING.md
docs/contributing.md

From [PSR-2 Coding Style Guide](https://www.php-fig.org/psr/psr-2/):
> **Deprecated** - As of 2019-08-10 PSR-2 has been marked as deprecated. [PSR-12](http://www.php-fig.org/psr/psr-12/) is now recommended as an alternative.
Related to #4726

Update PHP coding style link

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/ClientOptInput.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultGeneratorTest.java
modules/openapi-generator/src/test/resources/2_0/refAliasedPrimitiveWithValidation.yml

Found during discussion of #4653 that `DefaultCodegen` has an `openApi` property that may remain unset in certain workflows.
This also adds a `pattern` property to `CodegenResponse` to demonstrate the concerns discussed in #4653. Rather than introduce all properties defined by OpenAPI Specification for Schema Validation Properties, I've added the single property for pattern. Adding all will change the contract of our response object for templates, and as I've proposed in the issue I think it would be best to rely on an interface which defines the Json Schema Validation Properties and includes getters/setters on targeted Codegen* models. 
Current master's state is this:
* CodegenParameter exposes Json Schema Validation properties as public fields
* CodegenProperty exposes Json Schema …

[core] Minor schema validations bug + add pattern property to CodegenResponse

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
modules/openapi-generator/src/main/resources/go-experimental/api.mustache
modules/openapi-generator/src/main/resources/go/api.mustache
samples/client/petstore/go-experimental/go-petstore/api_another_fake.go
samples/client/petstore/go-experimental/go-petstore/api_fake.go
samples/client/petstore/go-experimental/go-petstore/api_fake_classname_tags123.go
samples/client/petstore/go-experimental/go-petstore/api_pet.go
samples/client/petstore/go-experimental/go-petstore/api_store.go
samples/client/petstore/go-experimental/go-petstore/api_user.go
samples/client/petstore/go/go-petstore-withXml/api_another_fake.go
samples/client/petstore/go/go-petstore-withXml/api_fake.go
samples/client/petstore/go/go-petstore-withXml/api_fake_classname_tags123.go
samples/client/petstore/go/go-petstore-withXml/api_pet.go
samples/client/petstore/go/go-petstore-withXml/api_store.go
samples/client/petstore/go/go-petstore-withXml/api_user.go
samples/client/petstore/go/go-petstore/api_another_fake.go
samples/client/petstore/go/go-petstore/api_fake.go
samples/client/petstore/go/go-petstore/api_fake_classname_tags123.go
samples/client/petstore/go/go-petstore/api_pet.go
samples/client/petstore/go/go-petstore/api_store.go
samples/client/petstore/go/go-petstore/api_user.go
samples/openapi3/client/petstore/go/go-petstore/api_another_fake.go
samples/openapi3/client/petstore/go/go-petstore/api_default.go
samples/openapi3/client/petstore/go/go-petstore/api_fake.go
samples/openapi3/client/petstore/go/go-petstore/api_fake_classname_tags123.go
samples/openapi3/client/petstore/go/go-petstore/api_pet.go
samples/openapi3/client/petstore/go/go-petstore/api_store.go
samples/openapi3/client/petstore/go/go-petstore/api_user.go

Path parameters in go did not propery serialize multiple comma-separated values ( Values were serialised as a an array ). This change reuses the code from query param serialization for path parameters.
@antihax @bvwells @grokify

[go] Fix multi-value path params in go

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/recursion.yaml

As a preparation to a major refactoring of the Elm generator I would like to add the ability of detecting circular references. Support for _self_ referring types was already in place, but this PR also detects types that _indirectly_ refer back to themselves. Every property that indirectly refers back to itself gets marked with `isCircularReference`.
cc @wing328 @jimschubert @cbornet @ackintosh @jmini @etherealjoy

Add isCircularReference to properties

---

modules/openapi-generator/src/main/resources/r/NAMESPACE.mustache

Adding the missing export for `ApiException` class.
@Ramanth (2019/07)

[r] Adding export of ApiException class

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java

fixing an issue where serverPort from additional-properties is interpreted as a string... causing the default to always be used

[go-server] fix issue with serverPort configuration

---

modules/openapi-generator/src/main/resources/python/tox.mustache

Replaced petstore_api with the package name
To fix https://github.com/OpenAPITools/openapi-generator/issues/4766

[Python] Fix package name in tox.ini

---

modules/openapi-generator/src/main/resources/dart-dio/enum.mustache

CC @ircecho @swipesight @jaumard @nickmeinhold

[dart-dio] Fixes enum by setting the wireName to the correct value

---

modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache

[C-libcurl] Change "complexType" to "name" inner "isMapContainer" to fix building error when complexType is empty.
When generating k8s C-libcurl client,  there is a build error due to the duplicated List
They are generated by the below template code:
```
{{#isMapContainer}}
list_t *{{{complexType}}}List;
...
{{/isMapContainer}} 
```
But for my case,  complexType is empty, so there are some duplicated List
```
list_t *List;
...
list_t *List;
...
list_t *List;
```
They will cause building error.
I checked other parts inner the {{#isMapContainer}} and {{/isMapContainer}} in the same [file](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache), and found "complexType" should be changed to "name"
@wing328 …

[C-libcurl] fix building error when complexType is empty.

---

modules/openapi-generator/src/main/resources/typescript-redux-query/modelAllOf.mustache
modules/openapi-generator/src/main/resources/typescript-redux-query/modelOneOf.mustache
modules/openapi-generator/src/main/resources/typescript-redux-query/models.mustache

This adds explicit proper handling of `allOf` for the `typescript-redux-query` generator, generating an interface that extends all the `allOf` entries, and implements the necessary `ToJSON`/`FromJSON` functions as well.

[typescript-redux-query] Add proper modelling of allOf usage.

---

modules/openapi-generator/src/main/resources/php/HeaderSelector.mustache
samples/client/petstore/php/OpenAPIClient-php/lib/HeaderSelector.php
samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/HeaderSelector.php

fixes https://github.com/OpenAPITools/openapi-generator/issues/4636#issuecomment-560574254

[PHP] Preserve JSON accept header

---

docs/generators/dart-dio.md
modules/openapi-generator/pom.xml
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/resources/dart-dio/local_date_serializer.mustache
modules/openapi-generator/src/main/resources/dart-dio/pubspec.mustache
modules/openapi-generator/src/main/resources/dart-dio/serializers.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/dartdio/DartDioClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/dartdio/DartDioClientOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/dartdio/DartDioModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/DartDioClientOptionsProvider.java

This pr adds `dateLibrary` option and simple [test](https://github.com/amondnet/openapi-generator/blob/3c7889a9544d597c569b963b6ed72f9ae994ee6c/modules/openapi-generator/src/test/java/org/openapitools/codegen/dartdio/DartDioModelTest.java#L102) to `dart-dio` generator. 
`dateLibrary` has two options.
- core : `dart:core`, (default), not handled properly `date`, `date-time` format; https://github.com/OpenAPITools/openapi-generator/issues/2696  I will make a new PR on this. 
- timemachine: [time_machine](https://pub.dev/packages/time_machine)
If `dateLibrary` is `timemachine`,
**input**
```yaml
openapi: 3.0.0
info:
contact:
email: amond@amond.net
description: test
title: test
version: 1.0.0
paths:
/test:
get:
responses:
200:
content:
schema:
$ref: …
```

[dart][dio] add dateLibrary options ( core, timemachine )

---

modules/openapi-generator/src/main/resources/python/configuration.mustache
samples/client/petstore/python-asyncio/petstore_api/configuration.py
samples/client/petstore/python-experimental/petstore_api/configuration.py
samples/client/petstore/python-tornado/petstore_api/configuration.py
samples/client/petstore/python/petstore_api/configuration.py
samples/openapi3/client/petstore/python/petstore_api/configuration.py

Minimal change from https://github.com/OpenAPITools/openapi-generator/pull/4613 to avoid useless discussion about property docstrings.
---
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) ... @spacether (2019/11)

[Python] Removes mutable default argument

---

modules/openapi-generator/src/main/resources/go-experimental/README.mustache
modules/openapi-generator/src/main/resources/go-experimental/api.mustache
modules/openapi-generator/src/main/resources/go-experimental/client.mustache
modules/openapi-generator/src/main/resources/go-experimental/configuration.mustache
samples/client/petstore/go-experimental/go-petstore/README.md
samples/client/petstore/go-experimental/go-petstore/api_another_fake.go
samples/client/petstore/go-experimental/go-petstore/api_fake.go
samples/client/petstore/go-experimental/go-petstore/api_fake_classname_tags123.go
samples/client/petstore/go-experimental/go-petstore/api_pet.go
samples/client/petstore/go-experimental/go-petstore/api_store.go
samples/client/petstore/go-experimental/go-petstore/api_user.go
samples/client/petstore/go-experimental/go-petstore/client.go
samples/client/petstore/go-experimental/go-petstore/configuration.go
samples/openapi3/client/petstore/go-experimental/go-petstore/README.md
samples/openapi3/client/petstore/go-experimental/go-petstore/api_another_fake.go
samples/openapi3/client/petstore/go-experimental/go-petstore/api_default.go
samples/openapi3/client/petstore/go-experimental/go-petstore/api_fake.go
samples/openapi3/client/petstore/go-experimental/go-petstore/api_fake_classname_tags123.go
samples/openapi3/client/petstore/go-experimental/go-petstore/api_pet.go
samples/openapi3/client/petstore/go-experimental/go-petstore/api_store.go
samples/openapi3/client/petstore/go-experimental/go-petstore/api_user.go
samples/openapi3/client/petstore/go-experimental/go-petstore/client.go
samples/openapi3/client/petstore/go-experimental/go-petstore/configuration.go

Support selection and formatting of endpoint servers using context.
---

[go-experimental] Support selection and formatting of endpoint servers

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java

This should address #4653
The request was to add validation properties to CodegenModel, where CodegenModel may be used to represent reusable schemas which don't necessary result in a generated model (see `isString`, `isInteger`, etc).  Those use cases are legacy functionality from before there was a standardized structure in swagger-parser (now, `Schema`). I couldn't find any usages in template code, but that's not to say that users with customized templates aren't relying heavily on CodegenModel and legacy functionality.  I've added the set of validation properties to `CodegenModel` to address this issue, but I think we should work out a deprecation strategy if CodegenModel is no longer meant to be used for primitive schemas. That is, an OpenAPI Schema representing a primitive type …

[core] Validation properties standardization

---

modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker_interface.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker_test.mustache
samples/server/petstore/php-slim4/lib/Mock/OpenApiDataMocker.php
samples/server/petstore/php-slim4/lib/Mock/OpenApiDataMockerInterface.php
samples/server/petstore/php-slim4/test/Mock/OpenApiDataMockerTest.php

`mockArray` method added to interface and implemented class. Mocker creates smallest arrays(single item when possible) to avoid huge JSON responses.
Related to #3545
1. Checkout into feature branch
```shell
$ git checkout -b ybelenko-slim_data_mocker_array master
$ git pull https://github.com/ybelenko/openapi-generator.git slim_data_mocker_array
```
2. Generate new Slim4 samples and go to just created build
```shell
$ mvn clean package
$ bin/php-slim4-server-petstore.sh
$ cd samples/server/petstore/php-slim4
```
3. Start Composer installation and run unit tests
```shell
$ composer install
$ composer test
$ composer phpcs
```

[Slim4] Add array support to Data Mocker

---

modules/openapi-generator/src/main/resources/typescript-angular/api.module.mustache
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/api.module.ts
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/api.module.ts
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/default/api.module.ts
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/api.module.ts
samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/api.module.ts
samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-npm/api.module.ts
samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-prefixed-module-name/api.module.ts

Relates to https://github.com/OpenAPITools/openapi-generator/pull/120
This PR removes services from the `providers` array in `@NgModule`s when `providedInRoot` mode is on.
Listing the providers in the `providers` array is not required if using `providedIn: 'root'` syntax. By excluding the providers from this array, the ones that are not used can be tree shaken out and excluded from the final build.
More info here:
https://angular.io/guide/providers#providedin-and-ngmodules
Without this change, all services are bundled in a final production bundle, regardless of if they are injected or not.
cc @topce  @akehir

typescript-angular: optimize tree-shaking by disabling providers array when for providedIn: root is set

---

modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache

Fixes problems with truncating time in DateTime when converting to ISO format in typescript client for required method parameters. (This does not apply to dates without time).
Fixes #4623
See  #4763
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11)

fix(typescript-angular): Fix date-timing-parsing is truncating the time (#4623 #4763)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-axios/model.mustache
modules/openapi-generator/src/main/resources/typescript-axios/modelAllOf.mustache

fixes #4804
Hello.
When using typescript-axios, a warning occurred in unused import.
I tried to fix it, so please take a look if you like.
Before
```js
import { Box } from './box';
import { BoxInBox } from './box-in-box';
import { Response } from './response';
/**
* 
* @export
* @interface BoxesResponse
*/
export interface BoxesResponse {
/**
* 
* @type {string}
* @memberof BoxesResponse
*/
status: BoxesResponseStatusEnum;
/**
* 
* @type {number}
* @memberof BoxesResponse
*/
id?: number;
/**
* 
* @type {string}
* @memberof BoxesResponse
*/
name?: string;
/**
* 
* @type {BoxInBox}
* @memberof BoxesResponse
*/
box?: BoxInBox;
}
/**
* @export
* @enum {string}
*/
export enum BoxesResponseStatusEnum {
Success = 'success',
Error = 'error'
}
```
After
```
import { Box } from './box';
import { …
```

[typescript-axios][client] Unnecessary imports occurs when using nested model in allOf

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Add missing vendor extensions from security scheme.
https://openapi-generator.slack.com/archives/CLSB0U0R5/p1576666747065600
---
@jmini (2018/04) ❤️

Include vendor extensions from security scheme

---

modules/openapi-generator/src/main/resources/r/Rbuildignore.mustache
modules/openapi-generator/src/main/resources/r/description.mustache
samples/client/petstore/R/.Rbuildignore
samples/client/petstore/R/DESCRIPTION

* Fixing the CRAN submission issues that will be complained, while releasing the package on CRAN package manager.
Issue 1: Dependence on the R version should not specify the patch version.
Issue 2: Ignoring the unrequired files and directories from being added to the R package.
@Ramanth

[r] Fixing the CRAN submission issues

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartJaguarClientCodegen.java

DefaultCodegen#procesOpts sets up quite a bit which may be expected by
users (template directory overrides, git user/repo, etc). The way the
dart-dio and dart-jaguar processOpts methods were written, these things
did not work. This makes it work.
cc all dart contributors for awareness:
* Dart: @yissachar
* Dart (refactor): @joernahrens
* Dart 2: @swipesight
* Dart (Jaguar): @jaumard
* Dart (Dio): @athornz
To repro the bug, copy the dart `README.mustache` (for dart-dio or dart-jaguar) to some directory called `template`, make some changes to the README, for example add to the top:
```
```
Generate with:
```
openapi-generator generate --generator-name dart-dio -t $(pwd)/template --input-spec openapi.yaml --output client/
```
We'd expect this README to be generated, but as of current master …

[bug][dart] Allow derived generators to call DefaultCodegen#processOpts

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache

Using C libcurl generator to generate k8s c client,   when a parameter name of a function is a C keyword, ( e.g. continue),  the building will fail. 
But the request string cannot be escaped,  described in [issue #4782](https://github.com/OpenAPITools/openapi-generator/issues/4782),
@wing328 @PowerOfCreation @zhemant

[C-libcurl] Escape parameter name of function when it is the C keyword.

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java

Some of the java clients (jersey2 and resttemplate) were not sending the defaultCookies.
I added the defaultCookies implementation for jersey2 and validated that they are being included in the request in debugger (unfortunately it is hard to test outside of J2EE).
Resttemplate now adds the last cookie value (as per RFC) to the header instead of the toString value of the list. `Cookie: foo=bar` instead of `Cookie: foo=[bar]`.

[java] Jersey2 and resttemplate do not correctly send defaultCookies

---

modules/openapi-generator/src/main/resources/C-libcurl/model-header.mustache

[C-libcurl] Fix build error when a struct includes a pointer pointing to itself
After a C client is generated by the C-libcurl OpenAPI-generator,  a struct may include a pointer pointing to itself,  e.g.
```c
typedef struct v1_json_schema_props_t {
...
v1_json_schema_props_t *not;  
...
} v1_json_schema_props_t;
```  
C compiler cannot recoginze v1_json_schema_props_t *not; so the building will fail.
We need change the template code, let the generated code like below:
```c
typedef struct v1_json_schema_props_t {
...
struct v1_json_schema_props_t *not; //model
...
} v1_json_schema_props_t;
```
@wing328 @zhemant

[C-libcurl] Fix build error when a struct includes a pointer pointing to itself

---

modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker_interface.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker_test.mustache
samples/server/petstore/php-slim4/lib/Mock/OpenApiDataMocker.php
samples/server/petstore/php-slim4/lib/Mock/OpenApiDataMockerInterface.php
samples/server/petstore/php-slim4/test/Mock/OpenApiDataMockerTest.php

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use OpenAPIServer\Mock\OpenApiDataMocker as Mocker;
$mocker = new Mocker();
$data = [
'Integer from 1 to 100' => $mocker->mockInteger(null, 1, 100),
'Float from -3 to 3' =>  $mocker->mockNumber(null, -3, 3),
'String 10 chars' => $mocker->mockString(null, 10, 10),
'Boolean' =>  $mocker->mockBoolean(),
'Array of strings' => $mocker->mockArray(
[
'type' => 'string',
'maxLength' => 20,
]
),
'Object' => $mocker->mockObject([
'id' => [
'type' => 'integer',
'minimum' => 1,
'maximum' => 10
],
'username' => [
'type' => 'string',
'maxLength' => 10,
]
])
];
echo json_encode($data, JSON_PRETTY_PRINT);
```
output:
```json
{
"Integer from 1 to 100": 62,
"Float from -3 to 3": 2.9062,
"String 10 chars": "Lorem ipsu",
"Boolean": true,
"Array of …
```

[Slim4] Add object support to Data Mocker

---

docs/generators/mysql-schema.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/MysqlSchemaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/mysql/MysqlSchemaCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/mysql/MysqlSchemaOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/MysqlSchemaOptionsProvider.java

Output with `-p identifierNamingConvention=snake_case`
```sql
--
-- Table structure for table `file` generated from model 'File'
-- Must be named &#x60;File&#x60; for test.
--
CREATE TABLE IF NOT EXISTS `file` (
`source_uri` TEXT DEFAULT NULL COMMENT 'Test capitalization. Original param name - sourceURI.'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Must be named &#x60;File&#x60; for test.. Original model name - File.';
```
Closes #3503

[MySQL] snake_case table and column names

---

modules/openapi-generator/src/main/resources/Java/JSON.mustache
samples/client/petstore/python-experimental/tests/test_pet_api.py

This PR has a fix for #4671. The JSON.mustache template should use "propertyBaseName" tag instead of "propertyName". The "propertyBaseName" tag is the name of the serialized property, whereas "propertyName" is the Java variable name.

[Java] Fix serialized name of discriminator in JSON.mustache

---

modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache

If a request operation defined in OpenAPI spec has more than 1 parameter, the generated C-libcurl client code will lose a "+", this will cause building error.
e.g.
```
api/AppsV1API.c:2073:47: error: invalid suffix "strlen" on integer constant
long sizeOfPathParams_name = strlen(name)+3strlen(namespace)+3 + strlen("{ name }");
```
The root cause is the template code does not handle the case that more than 1 parameters.  
After I added below code:
```
{{#hasMore}} + {{/hasMore}}
``` 
The new generated code 
```
long sizeOfPathParams_name = strlen(name)+3 + strlen(namespace)+3 + strlen("{ name }");
```
will succeed to build.
@wing328 @zhemant

[C-libcurl] Fix build error when the request operation has more than 1 parameter

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
modules/openapi-generator/src/main/resources/dart2/pubspec.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/DartClientOptionsTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/options/DartClientOptionsProvider.java

@ircecho @swipesight @jaumard @nickmeinhold
Added three configuration values for Dart 2 to be able to publish the generated code to pub without changes:
pubAuthor - contains the name of the author
pubAuthorEmail - contains the email address of the author
pubHomepage - contain the homepage of the project
Changed the name of the output directory from docs to doc as this follows the dart [package layout](https://dart.dev/tools/pub/package-layout)

Added Dart config parameters to fulfill pubspec requirements for publishing to pub

---

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/apiClient.mustache

Because when we have tags on OpenAPI Specification, there can be more than 1 Feign Beans being generated and the title field is share by all the clients. This makes the code to stop working in runtime.
Here is a PR which uses the classVarName instead, which follows the standards and should be enough to solve this issue.
For more info please refer to: https://github.com/OpenAPITools/openapi-generator/issues/2205

Fix for Issue #2205

---

modules/openapi-generator/src/main/resources/r/Rbuildignore.mustache
samples/client/petstore/R/.Rbuildignore

* Fixing the below CRAN complaint.
* Ignoring README.md so that it will not get added to the generated R library(tar.gz file)
@Ramanth

[r] Ignoring README.md in Rbuildignore

---

modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache

When a struct field in the generated c client is a C key word (e.g. continue), it should be escaped.  This is implemented by the [PR #4735](https://github.com/OpenAPITools/openapi-generator/pull/4735).
But #4735 introduces an issue, that is the JSON key name in request/response body is also escaped.
e.g.
```
./model/v1_list_meta.c:    if(cJSON_AddStringToObject(item, "_continue", v1_list_meta->_continue) == NULL) {
./model/v1_list_meta.c:    cJSON *_continue = cJSON_GetObjectItemCaseSensitive(v1_list_metaJSON, "_continue");
```
This will cause logic error when API server processes the request/response body.
Actually the JOSN key name should not be escaped, e.g.
```
./model/v1_list_meta.c:    if(cJSON_AddStringToObject(item, "continue", v1_list_meta->_continue) == NULL) { …
```

[C-libcurl] The JSON key name in request/response body should not be escaped even though it is a C key word.

---

pom.xml

python-flask-python2 tests were previously failing and were disabled in https://github.com/OpenAPITools/openapi-generator/commit/62e5d1f43bfdf0c9298841b596e002cd9feab570
They were failing because the latest python connexion library was being installed, which was not python 2.7 compatible
This was fixed in https://github.com/OpenAPITools/openapi-generator/pull/4765
The only remaining step is to turn the CI tests back on and they should pass
That's what we're doing here
If merged, this PR will close https://github.com/OpenAPITools/openapi-generator/issues/4823
Python Technical Committee:
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) @spacether (2019/11)

[Python] Enables CI tests for python-flask-python2

---

modules/openapi-generator/src/main/resources/go-experimental/configuration.mustache
modules/openapi-generator/src/main/resources/go/configuration.mustache
samples/client/petstore/go-experimental/go-petstore/configuration.go
samples/client/petstore/go/go-petstore-withXml/configuration.go
samples/client/petstore/go/go-petstore/configuration.go
samples/openapi3/client/petstore/go-experimental/go-petstore/configuration.go
samples/openapi3/client/petstore/go/go-petstore/configuration.go

Fix `configuration.go` for schema with multiple servers (copy from go-experimental code)

[go][client] fix when schema have multiple servers

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/resources/dart-dio/api.mustache
modules/openapi-generator/src/main/resources/dart-dio/api_util.mustache

CC: @ircecho @swipesight @jaumard

[dart-dio] Adds support for multipart form data post body

---

modules/openapi-generator/src/main/resources/dart-dio/apilib.mustache
samples/client/petstore/dart-dio/README.md
samples/client/petstore/dart-dio/lib/api/pet_api.dart
samples/client/petstore/dart-dio/lib/api/store_api.dart
samples/client/petstore/dart-dio/lib/api/user_api.dart
samples/client/petstore/dart-dio/lib/api_util.dart

basePath is hard-encoded with petstore url
```dart
String basePath = "http://petstore.swagger.io/v2";
```
This PR replace with the right placeholder, same as [dart generator](https://github.com/ludoo0d0a/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart/api_client.mustache#L21)
@ircecho @swipesight @jaumard @nickmeinhold @athornz @amondnet

[dart-dio] Fix basepath

---

README.md

Add an link to Ada article

---

modules/openapi-generator/src/main/resources/python/setup_cfg.mustache

- replace petstore_api with packageName in setup_cfg.mustache
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) @spacether (2019/11)

[Python] replace petstore_api with packageName in setup_cfg.mustache

---

modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
samples/client/petstore/typescript-node/default/api/petApi.ts
samples/client/petstore/typescript-node/default/api/storeApi.ts
samples/client/petstore/typescript-node/default/api/userApi.ts
samples/client/petstore/typescript-node/npm/api/petApi.ts
samples/client/petstore/typescript-node/npm/api/storeApi.ts
samples/client/petstore/typescript-node/npm/api/userApi.ts

- added getter/setter for `defaultHeaders` property
- fixed authentication for clients that support several auth methods (use auth method only if auth credentials are set)
Issues fixed:
[[typescript-node][BUG] create getter/setter for `defaultHeaders` property #4894](https://github.com/OpenAPITools/openapi-generator/issues/4894)
[[typescript-node][BUG] all supported authentication method (not configured) applied to request #4895](https://github.com/OpenAPITools/openapi-generator/issues/4895)
- [+] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [+] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-pr …

Added ability to work with `defaultHeaders` and fixed authentication for code generated by openapi-generator for typescript-node

---

modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache
modules/openapi-generator/src/main/resources/rust-server/server-context.mustache
modules/openapi-generator/src/main/resources/rust-server/server-mod.mustache
samples/server/petstore/rust-server/output/multipart-v3/Cargo.toml
samples/server/petstore/rust-server/output/multipart-v3/src/client/mod.rs
samples/server/petstore/rust-server/output/multipart-v3/src/server/context.rs
samples/server/petstore/rust-server/output/multipart-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/openapi-v3/Cargo.toml
samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
samples/server/petstore/rust-server/output/openapi-v3/src/server/context.rs
samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/ops-v3/Cargo.toml
samples/server/petstore/rust-server/output/ops-v3/src/client/mod.rs
samples/server/petstore/rust-server/output/ops-v3/src/server/context.rs
samples/server/petstore/rust-server/output/ops-v3/src/server/mod.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/context.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
samples/server/petstore/rust-server/output/rust-server-test/Cargo.toml
samples/server/petstore/rust-server/output/rust-server-test/src/client/mod.rs
samples/server/petstore/rust-server/output/rust-server-test/src/server/context.rs
samples/server/petstore/rust-server/output/rust-server-test/src/server/mod.rs

If we have an API which has multiple auth types, we may panic. This is because
in Hyper 0.11, the following code will panic:
```rust
use hyper::header::{Authorization, Basic, Bearer, Headers};
fn main() {
let mut headers = Headers::default();
let basic = Basic { username: "richard".to_string(), password: None };
headers.set::<Authorization<Basic>>(Authorization(basic));
println!("Auth: {:?}", headers.get::<Authorization<Bearer>>());
}
```
as it mixes up an `Authorization<Basic>` and `Authorization<Bearer>` as both
have `Authorization:` as the header name.
This is fixed by using `swagger::SafeHeaders` added in
https://github.com/Metaswitch/swagger-rs/pull/90
This code is no longer relevant once the Hyper 0.12 work is merged, but that is a breaking change, so this is put in for the 4.x …

[Rust Server] Fix panic handling headers

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java

Most of the Kotlin generator templates loop `requiredVars` and `optionalVars` ([1](https://github.com/OpenAPITools/openapi-generator/blob/v4.1.3/modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache#L32-L36), [2](https://github.com/OpenAPITools/openapi-generator/blob/v4.1.3/modules/openapi-generator/src/main/resources/kotlin-spring/dataClass.mustache#L11-L13)) .  Unfortunately, it looks like during the [`CodegenModel.removeAllDuplicatedProperty`](https://github.com/OpenAPITools/openapi-generator/blob/v4.1.3/modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java#L527), the CodegenProperty's are all [cloned](https://github.com/OpenAPITools/openapi-generator/blob/v4.1.3/modules/openapi-generator/src/main/java/org/openapitools/codegen/Codege …

[Kotlin] Correct isInherited flag for Kotlin generators

---

docs/generators/aspnetcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharp/CsharpModelEnumTest.java

allows customization of enum suffixes for C#
addresses #4275 
```
{
"apiPackage": "RestApi.Controllers",
"modelPackage": "RestApi.Models",
"packageName": "RestApi",
"enumNameSuffix": "aaa",
"enumValueNameSuffix": "bbb"
}
```
generates stuff like (not that i would ever want 'aaa' or 'bbb' suffixes, but it's a fine example...)
```
/// <summary>
/// Gets or Sets Status
/// </summary>
[TypeConverter(typeof(CustomEnumConverter<Statusaaa>))]
[JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public enum Statusaaa
{
/// <summary>
/// Enum Activebbb for Active
/// </summary>
[EnumMember(Value = "Active")]
Activebbb = 1,
/// <summary>
/// Enum Disabledbbb for Disabled
/// </summary>
[EnumMember(Value = "Disabled")]
Disabledbbb = 2
}
```

[C#] allow customization of generated enum suffixes

---

modules/openapi-generator/src/main/resources/typescript-node/model.mustache
samples/client/petstore/typescript-node/default/model/apiResponse.ts
samples/client/petstore/typescript-node/default/model/category.ts
samples/client/petstore/typescript-node/default/model/order.ts
samples/client/petstore/typescript-node/default/model/pet.ts
samples/client/petstore/typescript-node/default/model/tag.ts
samples/client/petstore/typescript-node/default/model/user.ts
samples/client/petstore/typescript-node/npm/model/apiResponse.ts
samples/client/petstore/typescript-node/npm/model/category.ts
samples/client/petstore/typescript-node/npm/model/order.ts
samples/client/petstore/typescript-node/npm/model/pet.ts
samples/client/petstore/typescript-node/npm/model/tag.ts
samples/client/petstore/typescript-node/npm/model/user.ts

Fixes https://github.com/OpenAPITools/openapi-generator/issues/4902.
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11)

[typescript-node] Add RequestFile to typescript-node model template

---

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java

Extends the `config-help` command for formatted output of things like instantiation type mappings, import mappings, etc.  Not included here is supporting files because these are almost always set at `processOpts` time, meaning we'd need to have a dry-run option on the generate command for those outputs.
I haven't enabled the outputs by default. Looking for contributor feedback first. I think this would be an excellent addition to the generator docs that we auto-generate.
Adds boolean options for which output user is looking for, including a full-details option for all.
```
NAME
openapi-generator-cli config-help - Config help for chosen lang
SYNOPSIS
openapi-generator-cli config-help
[(-f <output format> | --format <output format>)] [--full-details]
[(-g <generator name> | --generator-name …
```

[cli] Full config help details

---

.github/auto-labeler.yml

It used to pick up `jax-rx` not `jax-rs` labels.

[fix] auto-labeler for jax-rs

---

docs/generators/javascript.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java
modules/openapi-generator/src/main/resources/Javascript/es6/package.mustache
modules/openapi-generator/src/main/resources/Javascript/package.mustache

Adds an `npmRepository` option to the javascript generators.
This functionality is in the flow typed client generator already, as well as the typescript client generators.

[javascript] Add npmRepository option to javascript generators

---

CONTRIBUTING.md
docs/contributing.md

Current scope (`--global`) of recommendation for **this** project can affect **all others** projects on user's machine.

Reduce scope of recommended git configuration

---

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Meta.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OpenAPIGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaGatlingCodegen.java

Using the `FilesUtils#writeStringToFile(File, String)` method leads to use of a user machine's default charset although the writing string has `UTF-8` charset.
This behavior will break file's charset for users which machine's default charset is not `UTF-8` - Windows users for example.
Furthermore the `FilesUtils#writeStringToFile(File, String)` method is deprecated after `commons-io` version `2.5` (2016-04-22) in favor of the `FilesUtils#writeStringToFile(File, String, Charset)` method.

Use UTF-8 charset on writing files

---

modules/openapi-generator/src/main/resources/r/Rbuildignore.mustache
samples/client/petstore/R/.Rbuildignore

`cran-comments.md` is the file where we address CRAN maintainer's comments/feedback. We need to add that file at the root location of the library's code repository and need to be ignored from the build.
@Ramanth

[r] Ignore cran-comments file from the build

---

modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache

After generating a C client,  user will use apiClient_create to create an apiClient to execute REST request operation.
But for now,  apiClient_create does not accept any parameter so apiClient cannot get any user setting. 
e.g.
```c
apiClient_t *apiClient_create() {
curl_global_init(CURL_GLOBAL_ALL);
apiClient_t *apiClient = malloc(sizeof(apiClient_t));
apiClient->basePath = "http://localhost";
apiClient->dataReceived = NULL;
apiClient->response_code = 0;
apiClient->apiKeys = NULL;
return apiClient;
}
```
I added a new function "apiClient_create_with_base_path" to get user settings:
```c
apiClient_t *apiClient_create_with_base_path(const char *basePath
, list_t *apiKeys
) {
curl_global_init(CURL_GLOBAL_ALL);
apiClient_t *apiClient = malloc(sizeof(apiClient_t));
if(basePath){ …
```

[C-libcurl] Support setting basePath and apiKeys when creating an apiClient

---

modules/openapi-generator/pom.xml
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/JsonCacheImpl.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/serializer/SerializerUtilsTest.java
pom.xml

notes: https://github.com/swagger-api/swagger-parser/releases

swagger-core 2.1.1 && swagger-parser 2.0.17

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
samples/server/petstore/php-symfony/SymfonyBundle-php/Api/PetApiInterface.php

Fix transient build issues with PHP symfony. The generated list of authMethods in codegen is not sorted because it is in a HashSet, hence the output is not deterministic. This means the generated code may potentially change when the code is executed or when the hash code changes.
I think codegen should return collections in a  deterministic order, such that when generating samples (in the bin directory), it does not keep swapping generated code around.

[PHP] fix php codegen ordering issue with CodegenSecurity

---

README.md

The current URLs return a 501 due to missing https and worng url

Fix Maven repo links (incl. https instead of http)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

This includes the missing property mapping from #2192. I testet the codegen with a custom template and it worked. But since this is my first PR in this repo, please review carefully if I managed to adhere to all standards and tell me if something is missing.

add multipleOf to CodegenProperty (#2192)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/resources/dart-dio/api.mustache
modules/openapi-generator/src/main/resources/dart-dio/api_util.mustache
samples/client/petstore/dart-dio/README.md
samples/client/petstore/dart-dio/lib/api/pet_api.dart
samples/client/petstore/dart-dio/lib/api/store_api.dart
samples/client/petstore/dart-dio/lib/api/user_api.dart
samples/client/petstore/dart-dio/lib/api_util.dart
samples/client/petstore/dart-dio/lib/model/order.dart

Fixes issues with DateTime import and form date paramaterToString function
- due to the addition of the timemachine library, models were importing ‘DateTime’ when using the core library, which is not a valid import.
- the parameterToString function was copied from the dart2 generator and had some errors when some enums were classes.
CC: @ircecho @swipesight @jaumard @nickmeinhold @amondnet

[dart-dio] Fixes issues with DateTime import and form date paramaterToString function

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache
modules/openapi-generator/src/main/resources/rust-server/server-mod.mustache
modules/openapi-generator/src/test/resources/2_0/rust-server/petstore-with-fake-endpoints-models-for-testing.yaml
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/README.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/api/openapi.yaml
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/fake_api.md
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/client.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/server_lib/server.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs

The rust server generator used the names of path parameters directly as the names of regex capture groups and format string substitutions. This is invalid when the path parameter is not a legal rust identifier. I couldn't find a specification of what characters OpenAPI permits in these names, and at least one other generator (python-flask, I think) was sanitizing path param names, so that's what I've done here.
Since I've changed the templates to use `{{paramName}}` instead of `{{baseName}}` this has the side effect of changing the previously working camel-case `petId` to `pet_id`. This seems desirable from a rust style perspective, but I'm not sure if it could be a backwards compatibility concern.

[Rust Server] fix handling of special characters in path param names

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/api/openapi.yaml

- minor code format change
- rename extension from pathFormatString to x-path-format-string
cc @frol (2017/07) @farcaller (2017/08) @bjgill (2017/12) @richardwhiuk (2019/07)

[rust] Minor improve to rust server

---

modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker_test.mustache
samples/server/petstore/php-slim4/lib/Mock/OpenApiDataMocker.php
samples/server/petstore/php-slim4/test/Mock/OpenApiDataMockerTest.php

Tiny PR to support `int32` and `int64` integer formats. Now `DataMocker` generates values in specific ranges for `int32` format.
```php
<?php
require __DIR__ . '/vendor/autoload.php';
use OpenAPIServer\Mock\OpenApiDataMocker as Mocker;
$mocker = new Mocker();
$data = $mocker->mockFromSchema([
'type' => 'object',
'properties' => [
'integer_from_1_to_100' => [
'type' => 'integer',
'minimum' => 1,
'maximum' => 100,
],
'float_from_minus3_to_3' => [
'type' => 'number',
'minimum' => -3,
'maximum' => 3,
],
'string_10chars' => [
'type' => 'string',
'minLength' => 10,
'maxLength' => 10,
],
'boolean' => [
'type' => 'boolean',
],
'array_of_strings' => [
'type' => 'array',
'items' => [
'type' => 'string',
'maxLength' => 20,
],
],
'Object' => [
'type' => 'object',
'properties' => [
'id' => [
'type' => …
```

[Slim4] Add integer formats support to Data Mocker

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/ApiClient.java

Quick PR to the Java templates to escape query parameters before sending them to the API. Currently query params aren't encoded and wind up causing issues if you're using non alphabetic characters. 
- [] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).

Escape query params before invoking api

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/api_doc.mustache
samples/client/petstore/java/jersey2-java6/docs/AnotherFakeApi.md
samples/client/petstore/java/jersey2-java6/docs/FakeApi.md
samples/client/petstore/java/jersey2-java6/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/jersey2-java6/docs/PetApi.md
samples/client/petstore/java/jersey2-java6/docs/StoreApi.md
samples/client/petstore/java/jersey2-java6/docs/UserApi.md
samples/client/petstore/java/jersey2-java8/docs/AnotherFakeApi.md
samples/client/petstore/java/jersey2-java8/docs/FakeApi.md
samples/client/petstore/java/jersey2-java8/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/jersey2-java8/docs/PetApi.md
samples/client/petstore/java/jersey2-java8/docs/StoreApi.md
samples/client/petstore/java/jersey2-java8/docs/UserApi.md
samples/client/petstore/java/jersey2/docs/AnotherFakeApi.md
samples/client/petstore/java/jersey2/docs/FakeApi.md
samples/client/petstore/java/jersey2/docs/FakeClassnameTags123Api.md
samples/client/petstore/java/jersey2/docs/PetApi.md
samples/client/petstore/java/jersey2/docs/StoreApi.md
samples/client/petstore/java/jersey2/docs/UserApi.md

- Better code format the auto-generated doc (removed empty line breaks, trailing spaces, etc)

[Java][Jersey] Better code format the auto-generated doc

---

bin/typescript.sh
bin/utils/ensure-up-to-date
docs/generators/typescript.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
modules/openapi-generator/src/main/resources/typescript/api/api.mustache
modules/openapi-generator/src/main/resources/typescript/http/http.mustache
modules/openapi-generator/src/main/resources/typescript/http/jquery.mustache
modules/openapi-generator/src/main/resources/typescript/package.mustache
samples/client/petstore/typescript/builds/default/.openapi-generator/VERSION
samples/client/petstore/typescript/builds/default/apis/PetApi.ts
samples/client/petstore/typescript/builds/default/package.json
samples/client/petstore/typescript/builds/jquery/.openapi-generator/VERSION
samples/client/petstore/typescript/builds/jquery/apis/PetApi.ts
samples/client/petstore/typescript/builds/jquery/apis/StoreApi.ts
samples/client/petstore/typescript/builds/jquery/apis/UserApi.ts
samples/client/petstore/typescript/builds/jquery/http/http.ts
samples/client/petstore/typescript/builds/jquery/http/jquery.ts
samples/client/petstore/typescript/builds/jquery/package-lock.json
samples/client/petstore/typescript/builds/jquery/package.json
samples/client/petstore/typescript/tests/jquery/package-lock.json
samples/client/petstore/typescript/tests/jquery/test/http/jquery.test.ts

This adds a new option to select the platform as node or browser.
When no platform is selected, a default is chosen by the framework option and likewise the file data type option is implied by the platform.
I did not have time to overhaul the tests, so I currently left the *default* sample build as node version and the *jquery* sample build as browser, as the latter uses proper e2e tests.
This PR assumes that my [previous PR](https://github.com/OpenAPITools/openapi-generator/pull/4424) is merged, so currently those commits are listed as well.
I also included some other minor improvements and fixes.
Cf. #802 
CC @TiFu

Typescript refactor: Platform select for browser and node

---

bin/utils/openapi-generator-cli.sh

closes #4357 
Option is `OPENAPI_GENERATOR_DOWNLOAD_CACHE_DIR`, not `OPENAPI_GENERATOR_DOWLOAD_CACHE_DIR` (with a missing N)

[scripts] Remove misspelled OPENAPI_GENERATOR_DOWLOAD_CACHE_DIR

---

modules/openapi-generator/src/main/resources/codegen/kotlin/build_gradle.mustache
samples/meta-codegen-kotlin/lib/build.gradle.kts

This continues on work in #5033 and #5034 which convert all http usage
to https to unblock CircleCI builds.
In #5034, mavenCentral() DSL was updated to explicitly target the https
maven repo because Gradle didn't force TLS 1.2 until v4.8.1 and many of
our examples use earlier versions of Gradle.  The Kotlin meta generator
was missed because it is a .kts build file rather than build.gradle, and
the mustache filename doesn't have kts in it; the file was updated as if
it was build.gradle (groovy syntax).

Use HTTPS Maven URL in Kotlin meta generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Adding code comments to explain apiTemplatesFiles vs supportingFiles, based on help from Jim Schubert.

[codegen] Add java code comments.

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/resources/dart-dio/api.mustache
modules/openapi-generator/src/main/resources/dart-dio/apilib.mustache
modules/openapi-generator/src/main/resources/dart-dio/class.mustache
modules/openapi-generator/src/main/resources/dart-dio/local_date_serializer.mustache
modules/openapi-generator/src/main/resources/dart-dio/serializers.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/dartdio/DartDioModelTest.java
samples/client/petstore/dart-dio/lib/api.dart
samples/client/petstore/dart-dio/lib/api/pet_api.dart
samples/client/petstore/dart-dio/lib/api/store_api.dart
samples/client/petstore/dart-dio/lib/api/user_api.dart
samples/client/petstore/dart-dio/lib/model/api_response.dart
samples/client/petstore/dart-dio/lib/model/api_response.g.dart
samples/client/petstore/dart-dio/lib/model/category.dart
samples/client/petstore/dart-dio/lib/model/category.g.dart
samples/client/petstore/dart-dio/lib/model/order.dart
samples/client/petstore/dart-dio/lib/model/order.g.dart
samples/client/petstore/dart-dio/lib/model/pet.dart
samples/client/petstore/dart-dio/lib/model/pet.g.dart
samples/client/petstore/dart-dio/lib/model/tag.dart
samples/client/petstore/dart-dio/lib/model/tag.g.dart
samples/client/petstore/dart-dio/lib/model/user.dart
samples/client/petstore/dart-dio/lib/model/user.g.dart
samples/client/petstore/dart-dio/lib/serializers.g.dart

This PR includes a few different fixes:
- Add missing import, serializer for `dateLibrary=timemachine`
- Remove bad import `package:http/io_client.dart`
- Use raw strings for those that contain variable name. This should eliminate potential issue with variables like `$ref`.
- Use `_path` instead of `path` to avoid potential conflict with op params.
These fixes are required when I try to generate for Kubernetes API ([example json here](https://gist.github.com/daohoangson/6431f46beb4c2d0d163f3a4791f518e8)).
Please note that this PR needs another PR to work properly (https://github.com/google/built_value.dart/pull/804).
CC @ircecho @swipesight @jaumard @nickmeinhold @athornz @amondnet

[dart-dio] Various fixes

---

modules/openapi-generator/src/main/resources/r/description.mustache
samples/client/petstore/R/DESCRIPTION

CRAN feedback :
-  Defining source code and it's issues URL.
This should be the last pull request to add package metadata for R package. 
@Ramanth

[r] Adding Git repository urls

---

modules/openapi-generator/src/main/resources/go-experimental/api.mustache
samples/client/petstore/go-experimental/go-petstore/api_fake.go

Currently, the generated go-experimental code has compilation errors and static analysis issues. This is because the block is repeated multiple times, depending on how many query parameters there are in the OAS.
It boils down to the fact that this line will be generated multiple times:
t:={{paramName}}
Hence the compiler will fail with the same variable being redefined multiple times.
I've opened a small, specific PR so hopefully it can be merged soon (compared to PR #4934 that has these changes plus other changes as well).

[go] fix compilation error in generated go code

---

modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/openapi_data_mocker_test.mustache
samples/server/petstore/php-slim4/lib/Mock/OpenApiDataMocker.php
samples/server/petstore/php-slim4/test/Mock/OpenApiDataMockerTest.php

```php
use OpenAPIServer\Mock\OpenApiDataMocker as Mocker;
$mocker = new Mocker();
$data = $mocker->mockFromSchema([
'type' => 'object',
'properties' => [
'byte' => [
'type' => 'string',
'format' => 'byte',
],
'binary' => [
'type' => 'string',
'format' => 'binary',
'minLength' => 16,
],
'date' => [
'type' => 'string',
'format' => 'date',
],
'datetime' => [
'type' => 'string',
'format' => 'date-time',
],
'password' => [
'type' => 'string',
'format' => 'password',
],
'email' => [
'type' => 'string',
'format' => 'email',
],
'uuid' => [
'type' => 'string',
'format' => 'uuid',
],
],
]);
echo json_encode($data, JSON_PRETTY_PRINT);
```
Output:
```json
{
"byte": "TA==",
"binary": "TG9yZW0gaXBzdQ==",
"date": "1975-10-19",
"datetime": "2006-08-03T00:43:34+00:00",
"password": "12345",
"email": …
```

[Slim4] Add string formats support to Data Mocker

---

modules/openapi-generator/src/main/resources/elm/Api.mustache
samples/openapi3/client/elm/src/Api.elm

Decoding fails if the return type is `()` if the body is empty.
This PR fixes that by using a default body of `{}`.

[elm] Fix decoding empty operation responses

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.cpp.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.h.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache
samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp
samples/client/petstore/cpp-qt5/client/PFXHttpRequest.h
samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
samples/client/petstore/cpp-qt5/client/PFXPetApi.h
samples/client/petstore/cpp-qt5/client/PFXStoreApi.cpp
samples/client/petstore/cpp-qt5/client/PFXStoreApi.h
samples/client/petstore/cpp-qt5/client/PFXUserApi.cpp
samples/client/petstore/cpp-qt5/client/PFXUserApi.h

**Summay**
Support request compression and improve response compression support in Qt5 client.
*Changes*
- Split response and request compression
- Add request compression 
- Add handling of *identity* *Content-Encoding*
- Default **gzip** for requests and response compression
*Sample Test spec*
```yaml
---
swagger: "2.0"
info:
description: Application Test Description
version: 1.0.0
title: ApplicationTemplate
host: 0.0.0.0:8080
basePath: /api
schemes:
- http
tags:
- name : CompressionTestServices
x-displayName : "CompressionTestServices"
description : |
"Test Services offered by the application"
paths:
/simpleEndpoint:
post:
tags:
- CompressionTestServices
summary: provide a list of Notifications
operationId: setGetCompressedData
consumes:
- application/json
produces:
- application/json …
```

[C++] [Qt5] Add request compression and handling identity

---

modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
modules/openapi-generator/src/main/resources/Javascript/README.mustache
modules/openapi-generator/src/main/resources/Javascript/api_doc.mustache
modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
modules/openapi-generator/src/main/resources/Javascript/es6/README.mustache
modules/openapi-generator/src/main/resources/Javascript/es6/api_doc.mustache
modules/openapi-generator/src/main/resources/asciidoc-documentation/index.mustache
modules/openapi-generator/src/main/resources/kotlin-client/api_doc.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
modules/openapi-generator/src/main/resources/perl/ApiClient.mustache
modules/openapi-generator/src/main/resources/perl/api_doc.mustache
modules/openapi-generator/src/main/resources/php/README.mustache
modules/openapi-generator/src/main/resources/php/api.mustache
modules/openapi-generator/src/main/resources/php/php_doc_auth_partial.mustache
modules/openapi-generator/src/main/resources/python/api_doc.mustache
modules/openapi-generator/src/main/resources/python/common_README.mustache
modules/openapi-generator/src/main/resources/python/configuration.mustache
modules/openapi-generator/src/main/resources/python/python-experimental/README_common.mustache
modules/openapi-generator/src/main/resources/python/python-experimental/api_doc.mustache
modules/openapi-generator/src/main/resources/python/python_doc_auth_partial.mustache
modules/openapi-generator/src/main/resources/ruby-client/README.mustache
modules/openapi-generator/src/main/resources/ruby-client/api_doc.mustache
modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache

For HTTP basic auth, many mustache templates use a convention to negate the isBasicBearer tag, i.e. the case for HTTP basic auth is the negation of isBasicBearer. The problem is this only works when there are two possible HTTP auth, 1) basic auth and 2) bearer token. To support more http auth methods, we should stop using the negation of "isBasicBearer".
```
...
{{^isBasicBearer}}
// do stuff for HTTP basic authentication
{{/isBasicBearer}}
{{#isBasicBearer}}
// do stuff for bearer authentication
{{/isBasicBearer}}
....
```
I am proposing that instead, we change the templates as follows:
```
{{#isBasicBasic}}
// do stuff for HTTP basic authentication
{{/isBasicBasic}}
{{#isBasicBearer}}
// do stuff for bearer authentication
{{/isBasicBearer}}
....
```
I started making the change for …

[HttpBasicAuth] Use positive isBasicBasic tag instead of negative isBasicBearer

---

pom.xml

This sets up jacoco instrumentation for code coverage. Preparing for
master and PR coverage reporting via sonarcloud.

Adds jacoco for code coverage

---

modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache

btoa (binary to ascii), is a javascript function to base64 encode a
string.
Axios is usable both from node and from the browser. But the btoa
function is available only in the browser.
This meant that any client that used basic auth was broken in node.
Axios has its own method of encoding basic auth credentials. This method
works in both the browser and node.
https://github.com/axios/axios/blame/v0.19.2/README.md#L318
By using this method, the generated client works in node and in the
browser.
This solves this comment on this issue.
https://github.com/OpenAPITools/openapi-generator/issues/3049#issuecomment-498278966
I have validated this change within a personal project:
https://github.com/ccouzens/create-vdc-with-edge-portal-api-demo/commit/df8b552f5f8b7528bd0b003b1c5b5558dd05eabf#diff-e9 …

Typescript axios: remove use of btoa

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/StringUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/StringUtilsTest.java

When using "kebab-case" file names, the typescript-angular client generator would create model files with repeating dashes in the filenames, but the import statements would have single dashes. This was caused by the Inline Model Resolver naming the resolved models by concatenating the parent name to the child model name with an underscore separator; if the child model name had a leading underscore, this would cause a double underscore in the new model name. When this model name was converted to kebab case for the file name, each individual underscore was converted to a dash, resulting in a filename with repeated dashes.
To address, updated the `dashize` method in StringUtils to collapse multiple consecutive whitespace and/or underscores to a single dash. This _shouldn't_ be a breaking …

[typescript-angular] Fix typescript model kebab-cased filenames

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java

This makes sure isReserverdWord check is run against the final (suffixed) model name.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/5104
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce @akehir @petejohansonxo

[typescript-angular] Sanitize/transform model name after appending modelSuffix

---

.github/workflows/sonar.yml
bin/ci/java-jaxrs-datelib-j8.json
bin/ci/java-jaxrs-resteasy-eap-java8-server.json
bin/ci/java-jaxrs-resteasy-eap-joda-server.json
bin/ci/java-jaxrs-resteasy-joda-server.json
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/GenerateBatch.java
modules/openapi-generator-cli/src/test/java/org/openapitools/codegen/cmd/GenerateBatchTest.java
modules/openapi-generator-cli/src/test/resources/batch/common/jaxrs-datelib-j8.json
modules/openapi-generator-cli/src/test/resources/batch/common/jaxrs-datelib-j8.yaml
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-json-include.yaml
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-yaml-include.json
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8.json
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8.yaml
modules/openapi-generator-cli/src/test/resources/batch/specs/petstore.yaml
modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFExtServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift4Codegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptReduxQueryClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java

After running Sonar on the master branch, some major analysis opportunities were displayed.
This fixes the use of SimpleDateFormat stored as static fields. SimpleDateFormat is not thread-safe, and may retain data across threads.
While there's no indicator that this has caused any issues (these are mostly used for example code), we should follow these best practices.
This also fixes a handful of NPE and other minor issues such as comparing Boolean.TRUE to strings and no wrapping some closeables in try-with-resources.

:bug: Fixing some issues with threading and NPE

---

.gitignore
README.md
modules/openapi-generator-cli/pom.xml
modules/openapi-generator-core/pom.xml
modules/openapi-generator-gradle-plugin/pom.xml
modules/openapi-generator-maven-plugin/pom.xml
modules/openapi-generator-online/pom.xml
modules/openapi-generator/pom.xml
pom.xml
spotbugs-exclude.xml

This extends on submission by @tomasbjerre in #5040 by moving the PMD and Spotbugs  plugin execution to a separate profile `static-analysis`. This keeps CheckStyle in the default build because it added a very minimal amount of time to execution.
Once merged, I'd like to extend the Sonar CI GitHub Action to be a static analysis action which caches the xml reports generated by these plugins as build artifacts.  This will give us SonarCloud as a means for evaluating the static analysis, and allow for contributors to download the `*.xml` reports from the action. Once the GitHub action is updated, we can also close #33 as well.
Core contributors may run static analysis with:
```
mvn -Pstatic-analysis install
```
The analysis is separated from default functionality to reduce impact to community …

[ci][test] Modifications to static analysis contribution via Tomasbjerre

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache
samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
samples/client/petstore/cpp-qt5/client/PFXPetApi.h
samples/client/petstore/cpp-qt5/client/PFXStoreApi.cpp
samples/client/petstore/cpp-qt5/client/PFXStoreApi.h
samples/client/petstore/cpp-qt5/client/PFXUserApi.cpp
samples/client/petstore/cpp-qt5/client/PFXUserApi.h

Add a method to abort operations after they have been invoked.
Fixes #3065
`cc`
@stkrwork @ravinikam @muttleyxd @MartinDelille

[C++] [Qt5] Support abort operation

---

modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache
samples/client/petstore/c/CMakeLists.txt

After the C client library is generated,  I try to link it to my program. 
```shell
gcc main.c -g -I../../c_k8s_api_client/include -I../../c_k8s_api_client/model -I../../c_k8s_api_client/api -L../../c_k8s_api_client/build -lkubernetes -lpthread -lssl -lz -lcurl -o lsecretOutCluster
```
But there are some link errors:
```shell
../../c_k8s_api_client/build/libk8s.a(CoreV1API.c.o): In function `CoreV1API_patchCoreV1Namespace':
/root/c_k8s_api_client/api/CoreV1API.c:19072: undefined reference to `object_convertToJSON'
../../c_k8s_api_client/build/libk8s.a(CoreV1API.c.o): In function `CoreV1API_patchCoreV1NamespaceStatus':
/root/c_k8s_api_client/api/CoreV1API.c:19219: undefined reference to `object_convertToJSON'
...
``` 
The reason is : The source code file "object.c" is not compiled into the …

[C-libcurl] Add object.c to CMakeLists to compile

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoGinServerCodegen.java

`go-gin-server` previously didn't allow users to configure apiPath, serverPort, or apiVersion. This change only overwrites those values if they don't exist.

[go] Allow user overrides for generated outputs

---

docs/generators/csharp-netcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
modules/openapi-generator/src/main/resources/csharp-netcore/TestProject.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/netcore_testproject.mustache

- Add `netstandard2.1` / `netcoreapp2.1` / `netcoreapp3.0` / `netcoreapp3.1` target
- Close #4818
- Introduce `testTargetFramework`
- Resolve mapping .NET Standard to .NET Core version
@mandrean @jimschubert @frankyjuang

[csharp-netcore] Support .NET Core 3.0/3.1 and .NET Standard 2.1

---

modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache

Support https/SSL for the C libcurl client
@wing328 @zhemant

[C-libcurl] Support HTTPS/SSL for the C client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

Support for `-DdebugOpenAPI` was accidentally removed in #3763 (since release 4.1.2).
Fixes #4654
cc/fyi @OpenAPITools/generator-core-team

[core] Add back functionality to debug openapi spec, accidentally removed in 4.1.2

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/StoreApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Animal.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Category.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/FormatTest.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Name.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Order.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Pet.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/TypeHolderDefault.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/TypeHolderExample.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/StoreApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Animal.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Category.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/FormatTest.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Name.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Order.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Pet.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/TypeHolderDefault.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/TypeHolderExample.cs

- Introduce `x-value-type` vendor extension
- This property represents a C# ValueType
- Make template null check decisions respect `x-value-type`
This PR is closes #4604, closes #3693
@mandrean @jimschubert @frankyjuang

[csharp-netcore] Fixed compiler null-check warning
