README.md
Included @gustavoapaz to founding members.
=> Included @gustavoapaz to founding members.

README.md
=> Included @ricardona to founding members.

README.md
=> Better badge description

.travis.yml, modules/openapi-generator-online/Dockerfile
For https://github.com/OpenAPITools/openapi-generator/pull/55#discussion_r188555959
=> Fix COPY in Dockerfile

README.md
=> Add links to blog posts

README.md
=> Revise the usage of OpenAPI Generator online (docker image)

modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/api/GenApi.java, modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/configuration/ParameterAllowableValuesPlugin.java
Set parameters allowableValues dynamically
=> Set parameters allowableValues dynamically

bin/windows/clojure-petstore.bat
=> Update clojure petstore batch file to use petstore.json

README.md
=> Add kenisteward to founding team

samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/AdditionalPropertiesClass.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Animal.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/ApiResponse.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/ArrayOfArrayOfNumberOnly.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/ArrayOfNumberOnly.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/ArrayTest.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Capitalization.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Cat.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Category.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/ClassModel.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Client.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Dog.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/EnumArrays.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/EnumTest.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/FormatTest.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/HasOnlyReadOnly.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/MapTest.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/MixedPropertiesAndAdditionalPropertiesClass.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Model200Response.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/ModelList.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/ModelReturn.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Name.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/NumberOnly.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Order.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/OuterComposite.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Pet.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/ReadOnlyFirst.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/SpecialModelName.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/Tag.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Model/User.php
Update PHP samples to resolve shippable CI failure
=> Update PHP samples

docs/migration-from-swagger-codegen.md
=> Add a section about body parameter name in the migration guide

CI/pom.xml.circleci
=> Re-enable go test in CircleCI

CI/pom.xml.bash, CI/pom.xml.circleci, CI/pom.xml.circleci.java7, CI/pom.xml.ios, CI/pom.xml.shippable, docs/3.0.0-release-note.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, shippable.yml
=> Release version 3.0.0

README.md
=> Add a remark about homebrew installation

README.md
=> add raiffeisen to company list

README.md
=> update company list

README.md
=> Put company list in alphabetical order

README.md
This is just an update to the README. No code was touched.
Adds two blogposts about swagger-codegen/openapi-generator to the list. Also adds our consulting/workshop company to the list of companies.
Thanks @wing328! 👍
=> Adds some links to the README

CI/pom.xml.bash, CI/pom.xml.circleci, CI/pom.xml.circleci.java7, CI/pom.xml.ios, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/Dockerfile, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, shippable.yml
=> Prepare release 3.0.2

docs/roadmap.adoc
=> Initial roadmap

README.md
=> Add wording to clarify the relationship with OAI

pom.xml
=> Disable Erlang server test due to dependency issue (Shippable CI)

pom.xml
=> Disable Rust server test due to lint error

README.md
=> Add link to presentation at JHipster conf 2008

README.md
Minor fixes for `README.md`:
* Spelling change for `beginners`
* Link update from 3.0.0 to 3.0.3
* Sorting and formatting for Members of Technical Committee table
* Addition of PowerShell to Members of Technical Committee table
=> [README.md] minor fixes incl. spelling, links, sorting, formatting

README.md
=> Add link to presentation

README.md
=> Add grokify to Go technical committee

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NodeJSServerCodegen.java
=> Show warning message for NodeJS server generator only

README.md
=> Fix broken link to openapi generator plugin README

CI/pom.xml.bash, CI/pom.xml.circleci, CI/pom.xml.circleci.java7, CI/pom.xml.ios, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/Dockerfile, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, shippable.yml
=> 3.1.0 release

bin/utils/ensure-up-to-date
=> Fix ensure-up-to-date

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pom.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/server/pom.mustache, samples/client/petstore/jaxrs-cxf-client/pom.xml, samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml, samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml, samples/server/petstore/jaxrs-cxf/pom.xml
@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
update CXF and Jackson to latest version
=> update CXF and Jackson to latest version

circle.yml
The caching does not work properly in CircleCI so this PR will fix it and improve the build time.
=> Improve CircleCI caching

docs/qna.md
=> Add an entry to clarify the Q&A page

README.md
@ybelenko
Welcome to the technical committee!  🎉
=> Add ybelenko to PHP technical committee

docs/migration-from-swagger-codegen.md
=> Mark rust-server as migrated in the migration guide

CI/pom.xml.bash, CI/pom.xml.circleci, CI/pom.xml.circleci.java7, CI/pom.xml.ios, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/Dockerfile, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, shippable.yml
=> Prepare release 3.1.1

modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache, samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiClient.java
Fixed header generation. Previously the key was used as value parameter.
=> [Java][RESTEasy] Fixed setting of custom headers

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java
Fix for Issue #[601](https://github.com/OpenAPITools/openapi-generator/issues/601)
=> Fix for Issue #601

CI/circle_parallel.sh, CI/pom.xml.circleci, CI/pom.xml.circleci.java7, circle.yml, samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/api/PetApi.scala
=> CircleCI: run Java8, Java7 tests in parallel

README.md
=> Add badges to maven store and Twitter

README.md
Add link to Go contribution quickstart article.
=> Add link to Go contribution quickstart article

CI/pom.xml.bash, CI/pom.xml.circleci, CI/pom.xml.circleci.java7, CI/pom.xml.ios, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/Dockerfile, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, shippable.yml
=> 3.1.2 patch release

README.md
=> Add template creator: C++ Qt5, PHP Laravel servers

CI/pom.xml.bash, CI/pom.xml.circleci, CI/pom.xml.circleci.java7, CI/pom.xml.ios, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/Dockerfile, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, shippable.yml
=> 3.2.0 release

CI/pom.xml.circleci, CI/pom.xml.circleci.java7, samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/PetApi.java
For https://github.com/OpenAPITools/openapi-generator/pull/755#discussion_r208143785
cc @fujigon
=> [JAX-RS][Spec] Add samples to CircleCI

modules/openapi-generator/src/main/resources/typescript-node/models.mustache, samples/client/petstore/typescript-node/default/model/models.ts, samples/client/petstore/typescript-node/npm/model/models.ts
Fixed formatting of dates for typescript node clients
https://github.com/OpenAPITools/openapi-generator/issues/785
@TiFu  @taxpon  @sebastianhaas  @kenisteward  @Vrolijkx  @macjohnny
=> Fixed date formatting in typescript node client

docs/customization.md
Fixes and improvement of the `docs/customization.md` page.
=> [documentation] improve section about usage of a generator from an other jar

README.md
=> Add https://www.suva.ch/ to the company list

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/857
=> Escape various descriptions in the spec

modules/openapi-generator/src/main/resources/typescript-angular/README.mustache, samples/client/petstore/typescript-angular-v2/default/README.md, samples/client/petstore/typescript-angular-v2/npm/README.md, samples/client/petstore/typescript-angular-v2/with-interfaces/README.md, samples/client/petstore/typescript-angular-v4.3/npm/README.md, samples/client/petstore/typescript-angular-v4/npm/README.md, samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/default/README.md, samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/README.md, samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/README.md, samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/README.md
=> Nit: Language fix in README.md

README.md
=> Add https://www.boxever.com/ to the company list

README.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java, modules/openapi-generator/src/main/resources/META-INF/services/org.openapitools.codegen.CodegenConfig
- minor enhancements (license, README)
- add Zalando to company list
- add @dr4ke616 to Kotlin tech committee
cc @jimschubert @dr4ke616
=> Minor improvements to Kotlin Spring Boot generator

README.md
Add @jaumard as the technical committee and template creator
cc  @ircecho (2017/07) @swipesight (2018/09)
=> Update Dart tech committee and template creator

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java
Fix postProcessFile log message by moving the "Successfully executed" message inside the try block.
=> Fix postProcessFile log message

README.md
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01)
=> Add nicokoenig to template creator list and TS tech committee

README.md
=> Update Usage instructions in README

modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache, modules/openapi-generator/src/main/resources/C-libcurl/api-header.mustache, modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache, modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache, samples/client/petstore/C/api/PetAPI.c, samples/client/petstore/C/api/StoreAPI.c, samples/client/petstore/C/api/StoreAPI.h, samples/client/petstore/C/api/UserAPI.c, samples/client/petstore/C/api/UserAPI.h, samples/client/petstore/C/include/apiClient.h, samples/client/petstore/C/src/apiClient.c
- added free functions
- addressed issue of if comparasions not working in apiClient.c for list.
- renamed imagecontainer struct to filestruct
- renamed variables by adding prefix / baseName.
- added updated sample
=> [C] Added free functions and addressed few issues

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
Rename C post-process file environment variable to C_POST_PROCESS_FILE, e.g. use te following to format C code:
```
export C_POST_PROCESS_FILE="/usr/local/bin/uncrustify --no-backup"
export UNCRUSTIFY_CONFIG=/Users/williamcheng/uncrustify-rules.cfg
```
=> Rename C post-process file environment variable to C_POST_PROCESS_FILE

README.md
=> Add Myworkout to the company list

modules/openapi-generator-cli/pom.xml
Update logback-classic to 1.2.3
=> Update openapi-generator-cli dependency

README.md
=> Add a link to an article about openapi-generator

pom.xml
A workaround for https://github.com/OpenAPITools/openapi-generator/issues/1138
=> Comment out TS node test in Travis CI

modules/openapi-generator/src/main/resources/C-libcurl/model-header.mustache, samples/client/petstore/c/model/order.h, samples/client/petstore/c/model/pet.h
- modified enum declaration in model header to match model body
=> [C] Fixed enum function declaration 

CI/pom.xml.bash, CI/pom.xml.circleci, CI/pom.xml.circleci.java7, CI/pom.xml.ios, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator/pom.xml, pom.xml
Update maven plugin version in various pom.xml
=> Update maven plugin version

modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache, modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache, modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache, modules/openapi-generator/src/main/resources/C-libcurl/api_pet_test.mustache, modules/openapi-generator/src/main/resources/C-libcurl/api_store_test.mustache, modules/openapi-generator/src/main/resources/C-libcurl/api_user_test.mustache, modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache, samples/client/petstore/c/api/PetAPI.c, samples/client/petstore/c/api/StoreAPI.c, samples/client/petstore/c/api/UserAPI.c, samples/client/petstore/c/include/apiClient.h, samples/client/petstore/c/model/api_response.c, samples/client/petstore/c/model/category.c, samples/client/petstore/c/model/order.c, samples/client/petstore/c/model/pet.c, samples/client/petstore/c/model/tag.c, samples/client/petstore/c/model/user.c, samples/client/petstore/c/src/apiClient.c, samples/client/petstore/c/unit-tests/manual-PetAPI.c, samples/client/petstore/c/unit-tests/manual-StoreAPI.c, samples/client/petstore/c/unit-tests/manual-UserAPI.c
- added variable for response code in apiClient struct
- added code to check response code and print in case of error
- removed commented code
- removed unnecessary print statements from test files
- set curl_verbose flag to 0 to disable curl header output
=> [C] minor fixes and additions

CONTRIBUTING.md, modules/openapi-generator/pom.xml
- update contributing guideline about adding new options
- fix the following error
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
-
=> Various improvements

CONTRIBUTING.md, modules/openapi-generator/pom.xml
Reverts OpenAPITools/openapi-generator#1213
=> Revert "Various improvements"

CI/circle_parallel.sh, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 3.3.1 patch release

docs/generators/groovy.md, docs/generators/java-inflector.md, docs/generators/java-msf4j.md, docs/generators/java-pkmst.md, docs/generators/java-play-framework.md, docs/generators/java-undertow-server.md, docs/generators/java-vertx.md, docs/generators/jaxrs-cxf-cdi.md, docs/generators/jaxrs-cxf-client.md, docs/generators/jaxrs-cxf.md, docs/generators/jaxrs-jersey.md, docs/generators/jaxrs-resteasy-eap.md, docs/generators/jaxrs-resteasy.md, docs/generators/jaxrs-spec.md, docs/generators/kotlin-server.md, docs/generators/kotlin-spring.md, docs/generators/kotlin.md, docs/generators/lua.md, docs/generators/rust-server.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/LuaClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
=> Update generator option

README.md
=> Add "tomplus" to Python technical committee

CONTRIBUTING.md, docs/generators/README.md
- update contributing guidelines
- update `docs`
=> Minor revision to the documentation

docs/migration-from-swagger-codegen.md
All generators have been migrated
=> Update migrated generators in the migration guide

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ClojureClientCodegen.java, pom.xml, samples/client/petstore/clojure/src/open_api_petstore/api/pet.clj, samples/client/petstore/clojure/src/open_api_petstore/api/store.clj, samples/client/petstore/clojure/src/open_api_petstore/specs/order.clj, samples/client/petstore/clojure/src/open_api_petstore/specs/pet.clj, samples/client/petstore/clojure/src/open_api_petstore/specs/user.clj
=> [Clojure] Fix tests: stop dashizing props names

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
Removed unused import to fix build
=> removed unused import to fix build

README.md
Update technical committee, template creator for Erlang, TS (Angular 7)
=> Update technical committee, template creator

README.md
=> Various updates in the README

README.md
This PR will add a link to my package, which will wrap the *.jar into an npm package
=> Added hint for npm package wrapper to README

CI/circle_parallel.sh, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 3.3.3 release

README.md
@wing328 as discussed
Add TUI InfoTec GmbH to the company list
=> add TUI InfoTec GmbH as company

README.md
=> Add C template creator to project's README

README.md
=> Fixed scripts list url in README.md

modules/openapi-generator/src/main/java/org/openapitools/codegen/AbstractGenerator.java
Updating previous PR with better comments
=> Add blank comment lines to satisfy PR feedback

README.md
=> Add a link to conference presentation

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- [X ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [N/A] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [N/A ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to …
=> Add option to skip maven execution if source is older than output

modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/GenApiService.java
=> Improve online gen resolution of host for the download link

.travis.yml, CI/circle_parallel.sh, README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 3.3.4 release

modules/openapi-generator-online/pom.xml, modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/GenApiService.java, modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/Generator.java, pom.xml
=> Add tests to online generator

README.md
=> Add GraphQL Server owner (renepardon) to the README

.gitignore, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java, modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache, modules/openapi-generator/src/main/resources/C-libcurl/README.md.mustache, modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache, modules/openapi-generator/src/main/resources/C-libcurl/api-header.mustache, modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache, modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache, modules/openapi-generator/src/main/resources/C-libcurl/apiKey.c.mustache, modules/openapi-generator/src/main/resources/C-libcurl/keyValuePair.h.mustache, modules/openapi-generator/src/main/resources/C-libcurl/list.c.mustache, modules/openapi-generator/src/main/resources/C-libcurl/list.h.mustache, modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache, modules/openapi-generator/src/main/resources/C-libcurl/model-header.mustache
- Changed curl version in CMakeLists
- Change CMakeLists to generate the library
- Updated README with how to compile and use generated library
- Modified import statements according to the directory structure
- Add a variable projectName to use in CMakeLists to differentiate generated packages
- updated .gitignore for C generator
=> [C] Resolve some issues from #1473

README.md
Thanks to help from @wing328 (and others), the rust-server generator for openapi-generator is now in a state where we can use it. We recently upgraded one of our projects to start using it (from swagger-codegen), switching to OpenAPI v3 at the same time.
=> @metaswitch is now using openapi-generator

.github/ISSUE_TEMPLATE/announcement.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This updates issue templates to support auto-labeling, and multiple issue formats.
=> Update issue templates

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
To fix #1627 
Tested with a few specs including the one provided in #1627
=> Fix alias to free form object & map

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/model.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/model.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pojo.mustache
proposed fix for: https://github.com/OpenAPITools/openapi-generator/issues/1654
=> Proposed fix for issues #1654. fix isSerializable for java jaxrs-cxf

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/OpenAPIGenerator.java
wrong description for `openapi-generator help`.
=> Fix CLI help description

pom.xml, shippable.yml
CI issues (e.g. build image change)
=> Fix various CI issues

appveyor.yml
Add C# client (refactor) to Appveyor CI
@mandrean (2017/08) @jimschubert (2017/09)
=> Add C# client (refactor) to Appveyor CI

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
=> Fix composed oneof type 1749

modules/openapi-generator-maven-plugin/pom.xml
To prevent shell command injection: https://snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSPLEXUS-31522
=> Maven dependencies version update

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Refactor getSchemaType, better handling of allOf
=> Better handling of allOf (composition)

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
The improvement that is suggested by @shiyumi-sarashino, who is author of [haskell-stab(on forked repo)](https://github.com/shiyumi-sarashino/openapi-generator/tree/haskell-stab) and [swagger-codegen-servant](https://github.com/shiyumi-sarashino/swagger-codegen-servant) . 👍
=> Resolve inline models before preprocess

modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java, modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml
This PR is a step to refactor InlineModelResolver, adds only test codes.
Previous PR: #1772
=> Add test case for InlineModelResolver: inline array request body

modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java, modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml
This PR is a step to refactor InlineModelResolver, adds only test codes.
Previous PR: #1778
=> Add test case for InlineModelResolver: inline object response with additionalProperties

modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java, modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml
This PR is a step to refactor InlineModelResolver, adds only test codes.
Previous PR: #1785
=> Add test case for InlineModelResolver: arbitrary models

modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java
This PR is a step to refactor InlineModelResolver, updates only test codes to address warnings by IntelliJ IDEA.
Previous PR: #1786
=> Improve test codes of InlineModelResolver

pom.xml, shippable.yml
- comment out apt-get update
- move php slim test to travis
=> Fix Shippable CI

README.md
=> Add GenFlow to the company/project list

README.md
I have a new username, @wing328
=> Change renamed user @trenneman to @eriktim

modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache, samples/client/petstore/javascript-promise-es6/README.md, samples/client/petstore/javascript-promise-es6/docs/AnotherFakeApi.md, samples/client/petstore/javascript-promise-es6/docs/FakeApi.md, samples/client/petstore/javascript-promise-es6/docs/FakeClassnameTags123Api.md, samples/client/petstore/javascript-promise-es6/docs/MapTest.md, samples/client/petstore/javascript-promise-es6/docs/PetApi.md, samples/client/petstore/javascript-promise-es6/docs/StoreApi.md, samples/client/petstore/javascript-promise-es6/docs/UserApi.md, samples/client/petstore/javascript-promise-es6/src/ApiClient.js, samples/client/petstore/javascript-promise-es6/src/api/AnotherFakeApi.js, samples/client/petstore/javascript-promise-es6/src/api/FakeApi.js, samples/client/petstore/javascript-promise-es6/src/api/FakeClassnameTags123Api.js, samples/client/petstore/javascript-promise-es6/src/api/PetApi.js, samples/client/petstore/javascript-promise-es6/src/api/StoreApi.js, samples/client/petstore/javascript-promise-es6/src/api/UserApi.js
Catching JS promise errors without having proper error details is a pain. This is a fine start to continue on.
Notice:
I've noticed the big change list when running the shell script.
=> [JavaScript][es6][promise] better error response

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
For https://github.com/OpenAPITools/openapi-generator/pull/1729#issuecomment-451991109
=> Add options to maven plugin

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
Fixes the first part of https://github.com/OpenAPITools/openapi-generator/pull/1729#issuecomment-451991109 (see https://github.com/OpenAPITools/openapi-generator/pull/1729#issuecomment-449937728). The second part was fixed by https://github.com/OpenAPITools/openapi-generator/pull/1845 (commit d65dd763d814fba356a61abeae6dd1dbc4193fd2).
=> Add additional properties to Java CodegenModel

.github/ISSUE_TEMPLATE/bug_report.md
=> Add a checklist to issue report

README.md
Add links to contributor's Patreon account so that the community can support the contributor's directly.
=> Add links to Patreon account

README.md
=> Add a link to  @ky-yk-d article

modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/README.md.mustache, samples/server/petstore/cpp-qt5-qhttpengine-server/server/README.MD, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIPetApiHandler.cpp, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIPetApiHandler.h, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIStoreApiHandler.cpp, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIStoreApiHandler.h, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIUserApiHandler.cpp, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIUserApiHandler.h, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIPetApiRequest.cpp, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIPetApiRequest.h, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIStoreApiRequest.cpp, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIStoreApiRequest.h, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIUserApiRequest.cpp, samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIUserApiRequest.h
- Small update in the readme for running the server
@stkrwork @MartinDelille @fvarose @ravinikam
=> [C++] [Qt5] Update Readme for qt5 server

modules/openapi-generator-maven-plugin/README.md
Update Maven plugin README with new options
=> Update Maven plugin README with new options

bin/typescript-node-petstore-npm.json, bin/typescript-node-petstore-with-npm.sh, bin/windows/typescript-node-petstore-with-npm.bat, modules/openapi-generator/src/main/resources/typescript-node/package.mustache, modules/openapi-generator/src/main/resources/typescript-node/tsconfig.mustache, samples/client/petstore/typescript-node/npm/package.json, samples/client/petstore/typescript-node/npm/tsconfig.json
https://github.com/OpenAPITools/openapi-generator/issues/1910
=> [BUG][typescript-node] Generated package causes compilation errors

README.md
We use openapi-generator to generate our API clients
=> Update README with FormAPI.io service

README.md
=> Add Prometheus/Alertmanager to README users list

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAiohttpConnexionServerCodegen.java, samples/server/petstore/python-aiohttp/openapi_server/__init__.py
Fix missing generated files reported in #1322
=> Fix missing __init__.py

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/StaticHtmlGenerator.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/html/StaticHtmlGeneratorTest.java
=> [html] Use ModelUtils to avoid NullPointerException

docs/generators/graphql-nodejs-express-server.md, docs/generators/python-aiohttp.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, samples/client/petstore/java/feign/pom.xml, samples/client/petstore/java/feign10x/pom.xml, samples/client/petstore/java/google-api-client/pom.xml, samples/client/petstore/java/jersey1/pom.xml, samples/client/petstore/java/jersey2-java6/pom.xml, samples/client/petstore/java/jersey2-java8/pom.xml, samples/client/petstore/java/jersey2/pom.xml, samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml, samples/client/petstore/java/okhttp-gson/pom.xml, samples/client/petstore/java/rest-assured/pom.xml, samples/client/petstore/java/resteasy/pom.xml, samples/client/petstore/java/resttemplate-withXml/pom.xml, samples/client/petstore/java/resttemplate/pom.xml, samples/client/petstore/java/retrofit/pom.xml, samples/client/petstore/java/retrofit2-play24/pom.xml, samples/client/petstore/java/retrofit2-play25/pom.xml, samples/client/petstore/java/retrofit2-play26/pom.xml, samples/client/petstore/java/retrofit2/pom.xml, samples/client/petstore/java/retrofit2rx/pom.xml, samples/client/petstore/java/retrofit2rx2/pom.xml, samples/client/petstore/java/vertx/pom.xml, samples/client/petstore/java/webclient/pom.xml
A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/1934
=> Update Java default value in pom.xml

website/i18n/en.json, website/pages/en/users.js
=> [website] Fix user link images

README.md
=> Add Xero to company list

README.md
=> fix link to online docs

README.md
=> update link to maven jar download to 3.3.4

modules/openapi-generator/src/main/resources/php-slim-server/README.mustache, samples/server/petstore-security-test/php-slim/README.md, samples/server/petstore/php-slim/README.md
This PR updates README to comply with requirements in #1857.
Link to OpenApi Generator website has been added.
Config example in README has been slightly changed.
=> [Slim] Update Readme

modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache, samples/client/petstore-security-test/typescript-angular/api/fake.service.ts, samples/client/petstore-security-test/typescript-angular/configuration.ts, samples/client/petstore-security-test/typescript-angular/model/return.ts
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to …
=> added bearer authentication to typescript-angular package

CI/circle_parallel.sh, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 4.0.0-beta2 release

docs/generators/groovy.md, docs/generators/java-inflector.md, docs/generators/java-msf4j.md, docs/generators/java-pkmst.md, docs/generators/java-play-framework.md, docs/generators/java-undertow-server.md, docs/generators/java-vertx.md, docs/generators/java.md, docs/generators/jaxrs-cxf-cdi.md, docs/generators/jaxrs-cxf-client.md, docs/generators/jaxrs-cxf.md, docs/generators/jaxrs-jersey.md, docs/generators/jaxrs-resteasy-eap.md, docs/generators/jaxrs-resteasy.md, docs/generators/jaxrs-spec.md, docs/generators/spring.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/UserApi.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/UserApi.java
To fix https://github.com/OpenAPITools/openapi-generator/issues/2043
=> Remove localVarPrefix from Java client

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java, samples/client/petstore/R/R/PetApi.r, samples/client/petstore/R/R/StoreApi.r, samples/client/petstore/R/R/UserApi.r
Use PascalCase for function naming
=> [R] Use PascalCase for function naming

modules/openapi-generator/src/main/resources/r/.travis.yml, modules/openapi-generator/src/main/resources/r/Rbuildignore.mustache, samples/client/petstore/R/.Rbuildignore, samples/client/petstore/R/.travis.yml, samples/client/petstore/R/R/PetApi.r, samples/client/petstore/R/R/StoreApi.r, samples/client/petstore/R/R/UserApi.r
Tested with https://github.com/wing328/petstore-r-client
=> [R] improve .travis.yml, .Rbuildignore

modules/openapi-generator/src/main/resources/r/api.mustache, modules/openapi-generator/src/main/resources/r/api_client.mustache, modules/openapi-generator/src/main/resources/r/model.mustache, samples/client/petstore/R/R/ApiClient.r, samples/client/petstore/R/R/ApiResponse.r, samples/client/petstore/R/R/Category.r, samples/client/petstore/R/R/Order.r, samples/client/petstore/R/R/PetApi.r, samples/client/petstore/R/R/StoreApi.r, samples/client/petstore/R/R/Tag.r, samples/client/petstore/R/R/User.r, samples/client/petstore/R/R/UserApi.r, samples/client/petstore/R/R/pet.R
=> [R] fix object serialization to JSON

modules/openapi-generator/src/main/resources/typescript-angular/encoder.mustache, samples/client/petstore/typescript-angular-v2/default/encoder.ts, samples/client/petstore/typescript-angular-v2/with-interfaces/encoder.ts, samples/client/petstore/typescript-angular-v4.3/npm/encoder.ts, samples/client/petstore/typescript-angular-v4/npm/encoder.ts, samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/default/encoder.ts, samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/encoder.ts, samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/encoder.ts, samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/encoder.ts, samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/default/encoder.ts, samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/encoder.ts, samples/client/petstore/typescript-angular-v7-provided-in-root/builds/default/encoder.ts, samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/encoder.ts
Reverts OpenAPITools/openapi-generator#2107
=> Revert "Don't escape [ and ] in query param keys"

modules/openapi-generator/src/main/resources/r/README.mustache, modules/openapi-generator/src/main/resources/r/api.mustache, modules/openapi-generator/src/main/resources/r/description.mustache, samples/client/petstore/R/DESCRIPTION, samples/client/petstore/R/R/pet_api.R, samples/client/petstore/R/R/store_api.R, samples/client/petstore/R/R/user_api.R, samples/client/petstore/R/README.md
Use `caTools::base64encode` to avoid line break
=> [R] fix base64 encode

modules/openapi-generator/src/main/resources/r/README.mustache, samples/client/petstore/R/README.md
- fix typo
- update installation procedure
=> [R] improvement to the documentation

modules/openapi-generator/src/main/resources/r/api_client.mustache, samples/client/petstore/R/R/api_client.R
=> [R] Fix query parameters in the API client

README.md
https://medium.com/google-cloud/building-api-services-a-beginners-guide-7274ae4c547f
=> Add link to Google Cloud Platform (GCP) article

README.md
=> Add a link to "Building APIs with OpenAPI: Continued"

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
To fix https://github.com/OpenAPITools/openapi-generator/issues/2051
=> Fix NPE when array item is undefined

README.md
Removed myself from the core team and java technical committee because I have no more time to work on the project. See you guys, it was awesome. Keep up the good work!
- [x ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
=> Removed JFCote from core team

README.md
=> Add a link to CSDN article

modules/openapi-generator/src/main/resources/Java/auth/HttpBearerAuth.mustache
Adds Javadocs per https://github.com/OpenAPITools/openapi-generator/pull/1930#issuecomment-471754689
=> [Java] Update Javadocs for HttpBearerAuth

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache, samples/client/petstore/typescript-fetch/builds/default/runtime.ts, samples/client/petstore/typescript-fetch/builds/es6-target/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/runtime.ts
fixes typescript fetch compilation error introduced in https://github.com/OpenAPITools/openapi-generator/pull/2234
=> fix typescript fetch compile issue

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache, samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle, samples/client/petstore/java/okhttp-gson-parcelableModel/build.sbt, samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml, samples/client/petstore/java/okhttp-gson/build.gradle, samples/client/petstore/java/okhttp-gson/build.sbt, samples/client/petstore/java/okhttp-gson/pom.xml
Update Java client (okhttp-gson) dependencies to the latest stable versions.
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
=> Update Java client (okhttp-gson) dependencies

bin/windows/go-gin-petstore-server.bat, bin/windows/go-petstore-server.bat, bin/windows/go-petstore-withxml.bat, bin/windows/go-petstore.bat
This PR applies the same process of the #2410 to the Windows batch files.
Thank you! 😃
@antihax (2017/11) @bvwells (2017/12) @grokify (2018/07)
=> [Go] Add a process to delete old files for the sample update Windows batch files

README.md
Thanks @GeneticGenesis for the blog post.
=> Add a link to "An adventure in OpenAPI V3 code generation"

bin/utils/detect_tab_in_java_class.sh
Detect tabs for all Java files under module
=> Detect tabs for all files under module

modules/openapi-generator/src/main/resources/ruby-client/Gemfile.mustache, samples/client/petstore/ruby/Gemfile, samples/client/petstore/ruby/docs/AdditionalPropertiesClass.md, samples/client/petstore/ruby/lib/petstore/models/additional_properties_any_type.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_array.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_boolean.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_class.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_integer.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_number.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_object.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_string.rb, samples/openapi3/client/petstore/ruby/Gemfile, samples/openapi3/client/petstore/ruby/docs/NullableClass.md, samples/openapi3/client/petstore/ruby/lib/petstore/models/nullable_class.rb
closes https://github.com/OpenAPITools/openapi-generator/issues/2444
=> Add RuboCop to Gemfile

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, samples/client/petstore/haskell-http-client/lib/OpenAPIPetstore/API/Fake.hs, samples/client/petstore/haskell-http-client/lib/OpenAPIPetstore/MimeTypes.hs, samples/client/petstore/javascript-es6/package.json, samples/client/petstore/javascript-es6/src/index.js, samples/client/petstore/javascript-promise-es6/package.json, samples/client/petstore/javascript-promise-es6/src/index.js, samples/client/petstore/javascript-promise/package.json, samples/client/petstore/javascript-promise/src/index.js, samples/client/petstore/javascript/package.json, samples/client/petstore/javascript/src/index.js, samples/client/petstore/ruby/docs/AdditionalPropertiesClass.md, samples/client/petstore/ruby/lib/petstore/models/additional_properties_any_type.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_array.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_boolean.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_class.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_integer.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_number.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_object.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_string.rb, samples/openapi3/client/petstore/ruby/docs/NullableClass.md, samples/openapi3/client/petstore/ruby/lib/petstore/models/nullable_class.rb
Convert slashes into underscore as part of `sanitizeName`
=> Better handling of operationId with slashes

modules/openapi-generator/src/main/resources/python/configuration.mustache, modules/openapi-generator/src/main/resources/python/rest.mustache, samples/client/petstore/python-asyncio/petstore_api/configuration.py, samples/client/petstore/python-tornado/petstore_api/configuration.py, samples/client/petstore/python/petstore_api/configuration.py, samples/client/petstore/python/petstore_api/rest.py, samples/client/petstore/ruby/docs/AdditionalPropertiesClass.md, samples/client/petstore/ruby/lib/petstore/models/additional_properties_any_type.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_array.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_boolean.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_class.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_integer.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_number.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_object.rb, samples/client/petstore/ruby/lib/petstore/models/additional_properties_string.rb, samples/openapi3/client/petstore/python/petstore_api/configuration.py, samples/openapi3/client/petstore/python/petstore_api/rest.py, samples/openapi3/client/petstore/ruby/docs/NullableClass.md, samples/openapi3/client/petstore/ruby/lib/petstore/models/nullable_class.rb
Added proxy headers option for urllib3. This will provide option to pass proxy headers if required.
=> Added proxy headers option for urllib3

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java
Better code format for Kotlin, Python generators (Java class) #2491
=> Better code format for Kotlin, Python generators (Java class)

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java, modules/openapi-generator/src/main/resources/r/api_doc.mustache, samples/client/petstore/R/docs/PetApi.md, samples/client/petstore/R/docs/StoreApi.md, samples/client/petstore/R/docs/UserApi.md
Provide better example code for R object in the auto-generated documentation.
=> Add better example code for R object

README.md
Add a link to Qitta blog post on OpenAPI Generator
=> Add a link to Qitta blog post on OpenAPI Generator

README.md
Add link to the article "OpenAPI generatorを試してみる"
=> Add link to the article "OpenAPI generatorを試してみる"

README.md
Add a link to the article "Access any REST service with the SAP S/4HANA Cloud SDK"
=> Add a link to the article "Access any REST service with the SAP S/4HANA Cloud SDK"

modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache, modules/openapi-generator/src/main/resources/Java/libraries/retrofit/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/pom.mustache, samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml, samples/client/petstore/java/okhttp-gson/pom.xml, samples/client/petstore/java/retrofit/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/retrofit2-play24/pom.xml, samples/client/petstore/java/retrofit2-play25/pom.xml, samples/client/petstore/java/retrofit2-play26/pom.xml, samples/client/petstore/java/retrofit2/pom.xml, samples/client/petstore/java/retrofit2rx/pom.xml, samples/client/petstore/java/retrofit2rx2/pom.xml
- improve code indentation
- update dependencies
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
=> Minor improvements to Java API clients (feign, okhttp, retrofit, retrofit2)

README.md
Add GoDaddy to the list of companies using OpenAPI Generator
cc @silasbw
=> Add GoDaddy to the list of companies using OpenAPI Generator

README.md
Add @karismann to Java and Kotlin technical committee
=> Add @karismann to Java and Kotlin technical committee

modules/openapi-generator/src/main/resources/aspnetcore/2.0/model.mustache, modules/openapi-generator/src/main/resources/aspnetcore/2.1/model.mustache, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Controllers/PetApi.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Controllers/StoreApi.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Controllers/UserApi.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/ApiResponse.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Category.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Order.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Pet.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Tag.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/User.cs
- fix "EmitDefaultValue" default value with false
=> [C#][ASP.NET] fix "EmitDefaultValue" default value with false

README.md
=> Add link to the article "OpenAPI3を使ってみよう！Go言語でクライアントとスタブの自動生成まで！"

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 4.0.0-beta3 release

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
Use 4.0.0-SNAPSHOT version in the master
=> Use 4.0.0-SNAPSHOT version in the master

docs/generators/spring.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
Elaborated the use of implicitHeaders option
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @wing328
=> [DOC] Elaborate usage of implicitHeader option

docs/customization.md, modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/build.sbt.mustache, modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/pom.mustache, samples/client/petstore/java/rest-assured/build.gradle, samples/client/petstore/java/rest-assured/build.sbt, samples/client/petstore/java/rest-assured/pom.xml
=> [Java][Rest-assured] Update dependencies for rest-assured client

README.md
Add @Zomzog (2019/04) to Java, Kotlin tech comm
=> Add @Zomzog (2019/04) to Java, Kotlin tech comm

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFExtServerCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptFlowtypedClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/JsonCacheImpl.java
Based on previous findings in this project we decided to apply certain code quality rules.
I have configured my local IDE to check for them (code analysis report).
This PR fixes some of them, the changes are really small.
=> Code review fixes

website/pages/en/index.js
Use the class "productShowcaseSection" instead.
=> Fix classname in the website

README.md
=> Add Namsor as the sponsor

docs/usage.md, website/sidebars.json
- usage : fix link to generator-specified parameters
- usage : fix next page link not found
=> [ONLINE] Minor links fix

modules/openapi-generator/src/main/resources/Javascript/api.mustache, modules/openapi-generator/src/main/resources/Javascript/es6/api.mustache, samples/client/petstore/javascript-es6/src/api/FakeApi.js, samples/client/petstore/javascript-es6/src/api/StoreApi.js, samples/client/petstore/javascript-promise-es6/src/api/FakeApi.js, samples/client/petstore/javascript-promise-es6/src/api/StoreApi.js, samples/client/petstore/javascript-promise/src/api/AnotherFakeApi.js, samples/client/petstore/javascript-promise/src/api/FakeApi.js, samples/client/petstore/javascript-promise/src/api/FakeClassnameTags123Api.js, samples/client/petstore/javascript-promise/src/api/PetApi.js, samples/client/petstore/javascript-promise/src/api/StoreApi.js, samples/client/petstore/javascript-promise/src/api/UserApi.js, samples/client/petstore/javascript/src/api/AnotherFakeApi.js, samples/client/petstore/javascript/src/api/FakeApi.js, samples/client/petstore/javascript/src/api/FakeClassnameTags123Api.js, samples/client/petstore/javascript/src/api/PetApi.js, samples/client/petstore/javascript/src/api/StoreApi.js, samples/client/petstore/javascript/src/api/UserApi.js
Unescape HTML characters in JS docstring
=> Unescape HTML characters in JS docstring

README.md
Add Camptocamp to company list
=> Add Camptocamp to company list

pom.xml, samples/client/petstore/typescript-rxjs/builds/with-npm-version/pom.xml
To cover https://github.com/OpenAPITools/openapi-generator/pull/2674
=> Add TypeScript-RxJS client to Travis CI

README.md
I talked "How to use OpenAPI3 for API developer" in RubyKaigi 2019
These are the topics of OpenAPI Generator
=> Add RubyKaigi 2019 presentation

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java, modules/openapi-generator/src/main/resources/cpp-pistache-server/main-api-server.mustache
Fixes #2732
@stkrwork @MartinDelille @ravinikam @fvarose
=> [C++][Pistache]Add server port processing

README.md
Add a link to OpenAPI Generator eBook
=> Add a link to OpenAPI Generator eBook

README.md
Add a link to the article on "Simply How"
=> Add a link to the article on "Simply How"

bin/aspnetcore-petstore-server.sh, docs/generators/aspnetcore.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java, modules/openapi-generator/src/main/resources/aspnetcore/2.0/controller.mustache, modules/openapi-generator/src/main/resources/aspnetcore/2.0/model.mustache, modules/openapi-generator/src/main/resources/aspnetcore/2.1/Startup.mustache, modules/openapi-generator/src/main/resources/aspnetcore/2.1/controller.mustache, modules/openapi-generator/src/main/resources/aspnetcore/2.1/model.mustache, samples/server/petstore/aspnetcore/README.md, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Controllers/PetApi.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Controllers/StoreApi.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Controllers/UserApi.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Pet.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/wwwroot/openapi-original.json
- minor format fix
- better null check (ref: https://github.com/OpenAPITools/openapi-generator/pull/2768)
cc @mandrean (2017/08), @jimschubert (2017/09)
=> [ASP.NET Core] minor format fix, better null check

modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
=> Apply strict spec option to CodegenConfig instance

README.md, website/dynamic/sponsors.yml
=> Add Lightbow as the Bronze sponsor

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java, modules/openapi-generator/src/main/resources/go/go.mod.mustache, modules/openapi-generator/src/main/resources/go/go.sum, samples/client/petstore/go/go-petstore/go.mod, samples/client/petstore/go/go-petstore/go.sum, samples/openapi3/client/petstore/go/go-petstore/go.mod, samples/openapi3/client/petstore/go/go-petstore/go.sum
@antihax @bvwells @grokify @kemokemo
Fixes #2796.
I didn't regenerate samples, since this is only triggered when moduleName is specified (either in config or on commandline). If you wish, I can definitely add this option to the scripts that generate samples and amend this PR.
I do have one question - it seems that the files under docs/generators are autogenerated, but I failed to find a script that generates them. Am I just looking wrong or are these handwritten? Thanks!
=> [Golang][client] Make it possible to generate go.mod and go.sum files

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Add support for models as query params for OAS3.
Sampleyaml : https://pastebin.com/MYk8nmdP
@wing328
=> [core] add support for model as query params

modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache, samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ApiClient.java
Fixed vertex ApiClient template because it has a bug. It not handling well the  exceptions from Json.mapper.readValue() function
Related issue
https://github.com/OpenAPITools/openapi-generator/issues/2842
=> Fixed vertex ApiClient template

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/RubyClientCodegenTest.java, modules/openapi-generator/src/test/resources/3_0/allOf_composition.yaml
- revert getContentType to return null to avoid too many warnings
- add tests for allOf composition
- better wording for skipFormModel
=> [Core] Minor enhancements

README.md
=>  Add CAM to company list

bin/groovy-petstore.sh, modules/openapi-generator/src/main/resources/Groovy/build.gradle.mustache, samples/client/petstore/groovy/build.gradle
=> Upgrade Groovy to 2.5.7

modules/openapi-generator/src/main/resources/Groovy/README.mustache, samples/client/petstore/groovy/README.md
=> Update Groovy readme

README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> 4.0.0 release

README.md
Removing myself from the technical committee, as I don't have any time to dedicate to this project anymore.
=> Remove @fvarose from technical committee

README.md
Add a link to the article published in 47northlabs.com: https://www.47northlabs.com/knowledge-base/generate-spring-boot-rest-api-using-swagger-openapi/
=> Add a link to the article published in 47northlabs.com

website/static/css/custom.css
This PR fixes https://github.com/OpenAPITools/openapi-generator/issues/2836
=> [Website] Fix css 

README.md
=> Add link to the article "OpenAPIによるスキーマファースト開発の実施サンプルとCloud Runについて"

website/static/css/custom.css
Reverts OpenAPITools/openapi-generator#2942
=> Revert "[Website] Fix css "

README.md
Add a link to Simplified Chinese eBook on OpenAPI Generator
=> Add a link to Simplified Chinese eBook on OpenAPI Generator

README.md
Add a link to OpenAPI Generator eBook (traditional chinese)
=> Add a link to OpenAPI Generator eBook (traditional chinese)

modules/openapi-generator/src/main/resources/python/api.mustache, samples/client/petstore/python-asyncio/petstore_api/api/another_fake_api.py, samples/client/petstore/python-asyncio/petstore_api/api/fake_api.py, samples/client/petstore/python-asyncio/petstore_api/api/fake_classname_tags_123_api.py, samples/client/petstore/python-asyncio/petstore_api/api/pet_api.py, samples/client/petstore/python-asyncio/petstore_api/api/store_api.py, samples/client/petstore/python-asyncio/petstore_api/api/user_api.py, samples/client/petstore/python-tornado/petstore_api/api/another_fake_api.py, samples/client/petstore/python-tornado/petstore_api/api/fake_api.py, samples/client/petstore/python-tornado/petstore_api/api/fake_classname_tags_123_api.py, samples/client/petstore/python-tornado/petstore_api/api/pet_api.py, samples/client/petstore/python-tornado/petstore_api/api/store_api.py, samples/client/petstore/python-tornado/petstore_api/api/user_api.py, samples/client/petstore/python/petstore_api/api/another_fake_api.py, samples/client/petstore/python/petstore_api/api/fake_api.py, samples/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py, samples/client/petstore/python/petstore_api/api/pet_api.py, samples/client/petstore/python/petstore_api/api/store_api.py, samples/client/petstore/python/petstore_api/api/user_api.py, samples/openapi3/client/petstore/python/petstore_api/api/another_fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/default_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py, samples/openapi3/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py, samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py, samples/openapi3/client/petstore/python/petstore_api/api/store_api.py, samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
Remove unnecessary if else.
Relate to #2977
=> [Python] Remove unnecessary if else.

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartJaguarClientCodegen.java
Fixes: 
```
data:
type: object
type: object
```
=> fix jaguar wrong import on object

modules/openapi-generator/src/main/resources/csharp/README.mustache, modules/openapi-generator/src/main/resources/csharp/api_doc.mustache, samples/client/petstore/csharp/OpenAPIClient/README.md, samples/client/petstore/csharp/OpenAPIClient/docs/AnotherFakeApi.md, samples/client/petstore/csharp/OpenAPIClient/docs/FakeApi.md, samples/client/petstore/csharp/OpenAPIClient/docs/FakeClassnameTags123Api.md, samples/client/petstore/csharp/OpenAPIClient/docs/PetApi.md, samples/client/petstore/csharp/OpenAPIClient/docs/StoreApi.md, samples/client/petstore/csharp/OpenAPIClient/docs/UserApi.md
Making example code snippet compilable for most of the use-cases.
=> [csharp] Making example code snippet compilable

modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- [-] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
Engine param for maven plugin.
=> Engine param in maven plugin.

samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/UserApi.md
Generates samples to match with code introduced in #2934.
Updated sample which caused master build to fail.
=> Updates sample generated content

README.md
Add @sunn to openapi generator core team
=> Add @sunn to openapi generator core team

README.md, website/dynamic/team.yml
=> Add/update new core team member: etherealjoy

README.md
Add Fuse to the company list
Add Fuse to the company list
=> Add Fuse to the company list

README.md, bin/utils/release_version_update_docs.sh, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> 4.0.2 release

README.md
Add "yue9944882" to Perl technical committee
=> Add "yue9944882" to Perl technical committee

README.md
Add a link to the speaker deck at Kubernetes Contributor Summit
=> Add a link to the speaker deck at Kubernetes Contributor Summit

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache, modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-mvc/pom.mustache, samples/client/petstore/spring-stubs/pom.xml, samples/server/petstore/spring-mvc-j8-async/pom.xml, samples/server/petstore/spring-mvc-j8-localdatetime/pom.xml, samples/server/petstore/spring-mvc/pom.xml, samples/server/petstore/springboot-beanvalidation/pom.xml, samples/server/petstore/springboot-delegate-j8/pom.xml, samples/server/petstore/springboot-delegate/pom.xml, samples/server/petstore/springboot-implicitHeaders/pom.xml, samples/server/petstore/springboot-useoptional/pom.xml, samples/server/petstore/springboot-virtualan/pom.xml, samples/server/petstore/springboot/pom.xml
=> Add missing javax dependencies for Java > 8

website/dynamic/team.yml
Remove Jean from the core team on the public website as he left the core team due to increased responsibility in his new role as a team leader. We appreciate all his contributions to the project.
=> Remove Jean from the core team in the public website

README.md
Add template creator - C# ASP.NET Core 3.0: @A-Joshi
=> Add template creator for C# ASP.NET Core 3.0

README.md
=> Fix release table in the project's README

README.md
Add a link to Japanese eBook (REST API のためのコード生成入門 (OpenAPI Generator))
=> Add a link to Japanese eBook (REST API のためのコード生成入門 (OpenAPI Generator))

README.md
Update R technical committee
cc @Ramanth  @saigiridhar21
=> Update R technical committee

README.md
As per the discussion with @macjohnny, I'm willing to join as a member of the typescript technical committee.
=> [typescript] added @akehir to the typescript technical committee

README.md
Add links to Codewind OpenAPI Tools
cc @keithchong
=>  Add links to Codewind OpenAPI Tools

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
The model interface has `additionalProperties` supports, but the `FromJSON` and `ToJSON` functions are not handling it.
=> [typescript-fetch] support additional properties

README.md
Added a link to the article "[OpenAPI Generator にコントリビュートしたら社名が載った話。(CAM) - CAM TECH BLOG](https://tech.cam-inc.co.jp/entry/2019/07/08/140000)"
=> Add a link to the article by CAM, Inc.

docs/debugging.md
closes https://github.com/OpenAPITools/openapi-generator/issues/3354
=> Add `Logs` section to the Debugging page.

pom.xml
fixes #3286
Flask v1.1.1 adds back support for Flask-Testing
=> [FIX] Add back Flask tests

README.md
Add GoDaddy as domain name sponsor
=> Add GoDaddy as domain name sponsor

README.md
Update brew instruction to install openjdk, maven
=> Update brew instruction to install openjdk, maven

README.md
Add @bkabrda to Go technical committee
cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09)
=> Add @bkabrda to Go technical committee

CI/.drone.yml, README.md, pom.xml, samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
Add drone.io CI for Java 11 test
=> Add drone.io CI for Java 11 test

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Add validation for primitive request bodies as desired in #3491. 
Fixes #3491
=> validation for primitive request bodies #3491

README.md
@frol @farcaller @bjgill
As discussed a while back, add myself to the Rust Technical Committee.
=> Add richardwhiuk to the Rust Technical Committee

README.md
Add @cgensoul to OCaml tech committee
=> Add @cgensoul to OCaml tech committee

README.md
Add @meganemura @dkliban as the template creator of Ruby Faraday client
=> Add @meganemura @dkliban as the template creator of Ruby Faraday client

README.md
=> Add a link to join the Slack workspace

README.md
Add build badges for 4.2.x branch
=> Add build badges for 4.2.x branch

docs/generators/dart-jaguar.md, docs/generators/dart.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
Better wordings
cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09)
=> Update CLI options in Dart

README.md
https://github.com/OpenAPITools/openapi-generator/pulls?q=is%3Apr+author%3Amuttleyxd+is%3Aclosed
Add @muttleyxd to C++ technical committee
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03)
=> Add @muttleyxd to C++ technical committee

modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java, modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml
related PR: https://github.com/OpenAPITools/openapi-generator/pull/3398
=> Add a test case for inline models within Callback Object

modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
=> fix typo in [TestUtils]

pom.xml
=> Swagger 2.0.8

docs/migration-from-swagger-codegen.md
Update Q&A with more info on nullable
=> Update Q&A with more info on nullable

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSSpecServerCodegenTest.java
=> [java] enhance JavaJAXRSSpecServerCodegenTest

README.md
Add a link to a Qiita blog post
=> Add a link to a Qiita blog post

modules/openapi-generator/pom.xml
=> Mockito 3.0.0

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
=> [java-client] add unit test for JDK 11 HttpClient

README.md
Add a link to Bitmovin blog post
=> Add a link to Bitmovin blog post

README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 4.1.1 release

README.md
=> Add a link to M3 Tech Blog

README.md
Add Pricefx to list of companies
=> Add Pricefx to list of companies

README.md
Add links to article and video
=> Add links to article and video

README.md
Add @nickmeinhold to Dart technical committee
cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09)
=> Add @nickmeinhold to Dart technical committee

README.md
=> Add Element AI to the list

modules/openapi-generator-maven-plugin/pom.xml
=> maven-plugin-plugin 3.6.0

modules/openapi-generator/src/main/resources/Java/libraries/google-api-client/pom.mustache, samples/client/petstore/java/google-api-client/pom.xml
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
=> updated google-api-client version from 1.23.0 to 1.30.2.  Bugfix #3625

docs/generators.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NimClientCodegen.java
- mark as "beta"
- reformat the code
- add copyright header
cc @hokamoto
=> Various minor improvements to the nim client generator

README.md
Add a link to a blog post (qiita)
=> Add a link to a blog post (qiita)

README.md
Add a link to Médiavision in the list of companies
cc @cgensoul
=> Add a link to Médiavision in the list of companies

README.md
Add a link to MasteCard tutorial
=> Add a link to MasteCard tutorial

modules/openapi-generator/pom.xml, modules/openapi-generator/src/main/resources/JavaVertXServer/pom.mustache, modules/openapi-generator/src/main/resources/android/libraries/volley/pom.mustache, modules/openapi-generator/src/main/resources/kotlin-vertx-server/pom.mustache, samples/client/petstore/android/volley/pom.xml, samples/server/petstore/java-vertx/async/pom.xml, samples/server/petstore/java-vertx/rx/pom.xml, samples/server/petstore/kotlin/vertx/pom.xml
=> [java] maven-compiler-plugin 3.8.1

README.md
Add a link to Japanese eBook
Add a link to Japanese eBook: https://booth.pm/ja/items/1571902
=> Add a link to Japanese eBook

README.md
Add a link to a blog post in Qiita
=> Add a link to a blog post in Qiita

modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml
- update maven-compiler-plugin version to 3.8.1
- minor formatting change
=> Update maven-compiler-plugin version

README.md
=> Add a link to a medium blog post

README.md
Add a link to DevRelCon SF 2019
=> Add a link to DevRelCon SF 2019

bin/utils/ensure-up-to-date
Add Go OAS3 petstore to ensure up-to-date
=> Add Go OAS3 petstore to ensure up-to-date

samples/client/petstore/go-experimental/go-petstore/api/openapi.yaml, samples/client/petstore/go-experimental/go-petstore/docs/FormatTest.md, samples/client/petstore/go-experimental/go-petstore/model_format_test_.go
Regenerate go samples again based on latest master
=> [golang ]Regenerate go samples on latest master

README.md
=> Add a link to IBM cloud docs

README.md
Add a link to the tutorial in http4k
=> Add a link to the tutorial in http4k

modules/openapi-generator/pom.xml
=> mockito 3.1.0

README.md
=> Add frankyjuang to the C# technical committee

modules/openapi-generator/src/main/resources/ruby-client/api_client_spec.mustache, samples/client/petstore/ruby/spec/api_client_spec.rb, samples/openapi3/client/petstore/ruby-faraday/spec/api_client_spec.rb, samples/openapi3/client/petstore/ruby/lib/petstore/api_client.rb, samples/openapi3/client/petstore/ruby/spec/api_client_spec.rb
- fix ruby test
- update error message
=> [Ruby] fix ruby test, update error message

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
Better wording for apiNameSuffix option description
=> Better wording for apiNameSuffix option description

README.md
Add a link to blog post on vertx and openapi
=> Add a link to blog post on vertx and openapi

README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 4.1.3 release

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/Dockerfile.jvm.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/Dockerfile.native.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/pom.mustache
Related PR: #3901
This PR is updating the Quarkus version in the OpenAPI-Generator template and doing some additional changes to the Docker templates.
The idea is that the code generated by the Quarkus tooling:
```
mvn io.quarkus:quarkus-maven-plugin:0.23.2:create \
-DprojectGroupId=org.openapitools \
-DprojectArtifactId=openapi-jaxrs-server \
-DclassName="org.openapi.openapitools.PingApi" \
-Dpath="/ping" \
-Dextensions="smallrye-openapi"
```
Must be similar to what is generated with OpenAPI generator:
```java
JavaJAXRSSpecServerCodegen config = new JavaJAXRSSpecServerCodegen();
config.setHideGenerationTimestamp(true);
config.setOutputDir(outputDirPath.toFile()
.getCanonicalPath());
config.setLibrary(JavaJAXRSSpecServerCodegen.QUARKUS_LIBRARY);
config.setArtifactVersion("1.0-SNAPSHOT"); …
```
=> [jaxrs-spec][quarkus] update to 0.23.2 and fixes for Dockerfile

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
@jimschubert @dr4ke616 @karismann @Zomzog
Closes #4046
=> Add DELETE with body to kotlin client

docs/generators/kotlin-server.md, docs/generators/kotlin-vertx.md, docs/generators/kotlin.md, modules/openapi-generator/src/main/resources/avro-schema/typeProperty.mustache, samples/openapi3/schema/petstore/avro-schema/InlineObject1.avsc
For https://github.com/OpenAPITools/openapi-generator/pull/4078#discussion_r332870678
=> Fix file type in avro template

pom.xml
Test Python aiohttp first in Travis to avoid failure
=> Test Python aiohttp first in Travis

README.md
https://github.com/banzaicloud/pipeline
=> Add Banzai Cloud to users list

README.md
Add California State University, Northridge to the list of users
=> Add California State University, Northridge to the list of users

README.md
Add a link to autopp's blog post
=> Add a link to autopp's blog post

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SwiftClientCodegen.java
Adds missing keywords for swift
=> [swift] Add missing keywords in swift

README.md
Add a link to blog post in csdn
=> Add a link to blog post in csdn

README.md
Add a link to a PoniCode blog post
=> Add a link to a PoniCode blog post

README.md
It was a conference talk about API First! development and a short introduction to OpenAPI and the OpenAPI Generator. It was held in German.
=> docs: add link to a slideshare presentation to readme.md

README.md
Add https://ponicode.dev/ to list of companies using OpenAPI Generator
=> Add https://ponicode.dev/ to list of companies using OpenAPI Generator

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/Dockerfile.jvm.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/pom.mustache
Similar to #4053 but to update to Quarkus `0.25.0`
=> [jaxrs-spec][quarkus] update to 0.25.0

README.md
Add https://vouchery.io to the company list cc @mszyndel
=> Add https://vouchery.io to the company list

modules/openapi-generator/src/main/resources/go-server/api.mustache, modules/openapi-generator/src/main/resources/go-server/controller-api.mustache, modules/openapi-generator/src/main/resources/go-server/routers.mustache, modules/openapi-generator/src/main/resources/go-server/service.mustache, samples/server/petstore/go-api-server/go/api.go, samples/server/petstore/go-api-server/go/api_pet.go, samples/server/petstore/go-api-server/go/api_pet_service.go, samples/server/petstore/go-api-server/go/api_store.go, samples/server/petstore/go-api-server/go/api_store_service.go, samples/server/petstore/go-api-server/go/api_user.go, samples/server/petstore/go-api-server/go/api_user_service.go, samples/server/petstore/go-api-server/go/routers.go
=> [Go][Server] Better code format

README.md
Add a link to meetup in Paris by Criteo
=> Add a link to meetup in Paris by Criteo

README.md
Add Fenergo in companies using OpenApi Generator
=> Add Fenergo in companies using OpenApi Generator

modules/openapi-generator/src/main/resources/typescript-rxjs/apis.mustache, modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache, samples/client/petstore/typescript-rxjs/builds/default/apis/PetApi.ts, samples/client/petstore/typescript-rxjs/builds/default/apis/UserApi.ts, samples/client/petstore/typescript-rxjs/builds/default/runtime.ts, samples/client/petstore/typescript-rxjs/builds/es6-target/apis/PetApi.ts, samples/client/petstore/typescript-rxjs/builds/es6-target/apis/UserApi.ts, samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts, samples/client/petstore/typescript-rxjs/builds/with-interfaces/apis/PetApi.ts, samples/client/petstore/typescript-rxjs/builds/with-interfaces/apis/UserApi.ts, samples/client/petstore/typescript-rxjs/builds/with-interfaces/runtime.ts, samples/client/petstore/typescript-rxjs/builds/with-npm-version/apis/PetApi.ts, samples/client/petstore/typescript-rxjs/builds/with-npm-version/apis/UserApi.ts, samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts
=> [typescript-rxjs] improve HttpQuery typing

README.md
Add Here to the company list
cc @gferon
=> Add Here to the company list

README.md
Add Edge Impulse to the list of users
cc @janjongboom
=> Add Edge Impulse to the list of users

README.md
Add a new section on IDE integration
=> Add a new section on IDE integration

README.md
Add a link to blog post in Qitta
=> Add a link to blog post in Qitta

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
Add missing reserved words
Reference: https://dart.dev/guides/language/language-tour
=> [Dart] Add missing reserved words

README.md
=> Add a link to presentation in eclipsecon Europe 2019

pom.xml
=> maven-enforcer-plugin: requireJavaVersion 1.8.0

modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/UserApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/AnotherFakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/StoreApi.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/UserApi.cs
=> [C#][NetCore] Rename local variables

README.md
Update technical committee (Java, Kotlin)
=> Update technical committee (Java, Kotlin)

modules/openapi-generator/src/main/resources/C-libcurl/README.md.mustache, samples/client/petstore/c/build-and-test.bash
=> [C] Update build-and-test.bash for CI errors

modules/openapi-generator/src/main/resources/csharp-netcore/model_doc.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/ClassModel.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/File.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/Model200Response.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/Name.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/Return.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/ClassModel.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/File.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/Model200Response.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/Name.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/Return.md
Adding model summary to model documentation files.
@mandrean (2017/08), @jimschubert (2017/09) ❤️ @frankyjuang (2019/09)
=> [csharp-netcore][documentation]: Adding model summary to model documentation files.

modules/openapi-generator/src/main/resources/python/model_doc.mustache, modules/openapi-generator/src/main/resources/python/python-experimental/model_doc.mustache, samples/client/petstore/python-asyncio/docs/ClassModel.md, samples/client/petstore/python-asyncio/docs/File.md, samples/client/petstore/python-asyncio/docs/Model200Response.md, samples/client/petstore/python-asyncio/docs/ModelReturn.md, samples/client/petstore/python-asyncio/docs/Name.md, samples/client/petstore/python-experimental/docs/ClassModel.md, samples/client/petstore/python-experimental/docs/File.md, samples/client/petstore/python-experimental/docs/Model200Response.md, samples/client/petstore/python-experimental/docs/ModelReturn.md, samples/client/petstore/python-experimental/docs/Name.md, samples/client/petstore/python-experimental/docs/TypeHolderDefault.md, samples/client/petstore/python-experimental/docs/TypeHolderExample.md, samples/client/petstore/python-tornado/docs/ClassModel.md, samples/client/petstore/python-tornado/docs/File.md, samples/client/petstore/python-tornado/docs/Model200Response.md, samples/client/petstore/python-tornado/docs/ModelReturn.md, samples/client/petstore/python-tornado/docs/Name.md, samples/client/petstore/python/docs/ClassModel.md, samples/client/petstore/python/docs/File.md, samples/client/petstore/python/docs/Model200Response.md, samples/client/petstore/python/docs/ModelReturn.md, samples/client/petstore/python/docs/Name.md, samples/openapi3/client/petstore/python/docs/ClassModel.md, samples/openapi3/client/petstore/python/docs/File.md, samples/openapi3/client/petstore/python/docs/HealthCheckResult.md, samples/openapi3/client/petstore/python/docs/Model200Response.md, samples/openapi3/client/petstore/python/docs/ModelReturn.md, samples/openapi3/client/petstore/python/docs/Name.md
Adding model summary to model documentation.
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)
=> [python][fix] Adding model summary to model documentation files

modules/openapi-generator/src/main/resources/r/description.mustache, samples/client/petstore/R/DESCRIPTION
* Using the license name specified on open api schema or else defaulting to Unlicense
* Using the contact information specified on open api schema or else defaulting to `open api generator community`.
@Ramanth (2019/07)
=> [r][license]: Fixing license and contact information

README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 4.2.0 release

README.md
Add slash-arun to Python technical committee
=> Add slash-arun to Python technical committee

modules/openapi-generator/src/main/resources/JavaSpring/api.mustache, modules/openapi-generator/src/main/resources/JavaSpring/apiDelegate.mustache
=> Fix issue 4326 forward throws for delegate to main method

CI/samples.ci/client/petstore/java/test-manual/okhttp-gson/api/PetApiTest.java, samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/api/PetApiTest.java
Smaller tests, better code format
=> [Java][okhttp-gson] Smaller tests, better code format

.github/PULL_REQUEST_TEMPLATE.md, README.md
Minor documentation update
- update badge for 4.3.x
- update pull request template to refer to 4.3.x
=> Minor documentation update

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/pom.mustache
Similar to #4185 but to update to Quarkus 0.27.0
=> [jaxrs-spec][quarkus] update to 0.27.0

README.md
Add https://qulix.com to the company list
=> Add https://qulix.com to list of companies using OpenAPI Generator

README.md
This PR is a small one just to add [QEDIT](https://qed-it.com/) to the [README](https://github.com/OpenAPITools/openapi-generator/blob/master/README.md) file under [Companies/Projects using OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator/blob/master/README.md#4---companiesprojects-using-openapi-generator)
=> Add QEDIT as a company that's using OpenAPI Generator

modules/openapi-generator/src/main/resources/kotlin-client/api.mustache, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/PetApi.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/UserApi.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/PetApi.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/UserApi.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/UserApi.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/UserApi.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
- Prefix local variable with localVar (response => localVarResponse)
cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10)
=> [Kotlin][Client] Prefix local variable with localVar

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-mvc/pom.mustache, modules/openapi-generator/src/main/resources/JavaSpring/model.mustache, modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
=> Replace the old ResourceSupport

README.md
=> Add a link to Sinatra article

bin/ci/php-symfony-petstore.json
=> Remove path relative to my home dir.

README.md
=> Add a link to TS article

modules/openapi-generator/src/main/resources/Java/pojo.mustache
This will fix #3182 thoroughly
@wing328
=> [Java] Recursive equal on reflection

README.md
We're using the OpenAPI generator for a few projects now.
=> README: Add GetYourGuide to company list

.travis.yml, CI/.travis.yml.ios, pom.xml, samples/client/petstore/swift4/default/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift4/promisekit/SwaggerClientTests/run_xcodebuild.sh, samples/client/petstore/swift4/rxswift/SwaggerClientTests/run_xcodebuild.sh
Minor enhancements to iOS tests
=> [Swift] Enhancements to iOS tests

README.md
Add a link to Devoxx Belgium 2019 presentation
=> Add a link to Devoxx Belgium 2019 presentation

README.md
Add a link to JHipster presentation
=> Add a link to JHipster presentation

README.md
=> Add a link to CodeTalks

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Better else clause to catch exception
=> Better else clause with warnings

README.md
Update Python, Kotlin technical committee
=> Update Python, Kotlin technical committee

CI/.drone.yml
=> Fix drone.io yaml file

modules/openapi-generator/src/main/resources/go-experimental/client.mustache, modules/openapi-generator/src/main/resources/go/client.mustache, samples/client/petstore/go/go-petstore-withXml/client.go, samples/client/petstore/go/go-petstore/client.go
=> [Go] Bypass object decode in case of empty body

pom.xml
Update swagger parser to the latest stable version
Ref: https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.16
=> Update swagger parser to the latest stable version

modules/openapi-generator/pom.xml, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinTestUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinTestUtilsTest.java, modules/openapi-generator/src/test/resources/org/openapitools/codegen/kotlin/KotlinTestUtilsTest/badPack/com/example/SimpleClass.kt, modules/openapi-generator/src/test/resources/org/openapitools/codegen/kotlin/KotlinTestUtilsTest/normalPack/com/example/SimpleClass.kt
Will used for [org.openapitools.codegen.kotlin.spring.KotlinSpringServerCodegenTest#embeddedEnumArrayTest](https://github.com/nekkiy/openapi-generator/blob/fix-kotlinArrayEnumEmbedded/modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/spring/KotlinSpringServerCodegenTest.java#L30)
=> [Kotlin-spring] add kotlin runtime compiler

bin/ci/php-slim4-server-petstore.json
Adds php-slim4 to bin/ci (for `batch` process) which is a newer generator.
=> Add php-slim4 config for batch/ci

bin/utils/ensure-up-to-date, samples/client/petstore/swift4/default/PetstoreClient/Classes/OpenAPIs/APIHelper.swift, samples/client/petstore/swift4/objcCompatible/PetstoreClient/Classes/OpenAPIs/APIHelper.swift, samples/client/petstore/swift4/promisekitLibrary/Package.swift, samples/client/petstore/swift4/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift, samples/client/petstore/swift4/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift, samples/client/petstore/swift4/unwrapRequired/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
=> [swift] update Swift4 samples

README.md
=> Add a link to the presentation by @t2y at JJUG CCC 2019 Fall

README.md
Add 4brunu to Swift technical committee
=> Add 4brunu to Swift technical committee

modules/openapi-generator/pom.xml
=> kotlin 1.3.60

README.md
Add a link to the YouTube playlist.
=> Add a link to the YouTube playlist.

README.md
=> Add a link to B9lab blog post

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/Dockerfile.native.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/pom.mustache
Similar to #4360 but to update to Quarkus `1.0.0.FINAL`
=> [jaxrs-spec][quarkus] update to 1.0.0.FINAL

README.md
- Add @petejohansonxo as the owner of TS redux-query generator
- Add @petejohansonxo to the TS technical committee
=> Add petejohansonxo as the owner of TS redux-query generator

README.md
Add a blog post by pochopocho13
=> Add a blog post by pochopocho13

README.md
Add a link to https://gotocph.com/2019/ presentation
=> Add a link to https://gotocph.com/2019/ presentation

README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Release 4.2.2

README.md
Add a link to blog post in dotnetthoughts
=> Add a link to blog post in dotnetthoughts

README.md, website/dynamic/sponsors.yml, website/dynamic/users.yml
=> Add DocSpring as the sponsor

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenCallback.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenDiscriminator.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenServer.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenServerVariable.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, samples/server/petstore/php-symfony/SymfonyBundle-php/Api/PetApiInterface.php
Regenerate hashCode, equals, toString in CodegenParameter, CodegenProperty, CodegenOperation, etc using Intellji IDE
=> Regenerate hashCode, equals, toString

README.md
=> Add a blog post to qiita

README.md
=> Fix sponsor image size

README.md
=> Add Embotics as a user of OpenAPI generator

modules/openapi-generator/pom.xml
=> mockito 3.2.0

README.md
- [ x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
=> Add Linode as a user of OpenAPI Generator

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/pom.mustache
Similar to #4609 but to update to Quarkus `1.0.1.FINAL`
=> [jaxrs-spec][quarkus] update to 1.0.1.FINAL

samples/client/petstore/javascript-flowtyped/lib/api.js, samples/client/petstore/javascript-flowtyped/lib/configuration.js
This PR fixes the paths in the files. There should not be these absolute (generated) paths.
=> Use correct relative paths

modules/openapi-generator/src/main/resources/php/api.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php, samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
fixes #4541
for reference https://github.com/guzzle/psr7/blob/19e510056d8d671d9d9e25dc16937b3dd3802ae6/src/Stream.php#L90-L109
=> [PHP] ensure rewound guzzle response body

shippable.yml
Fix shippable errors based on the discussion in https://github.com/Shippable/support/issues/5001
=> Fix shippable errors

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm/infrastructure/ApiClient.kt.mustache, samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
This adds a missing import that blocks the compilation (https://github.com/OpenAPITools/openapi-generator/issues/4771)
=> [Kotlin] fix basic authentication compilation issue

modules/openapi-generator/src/main/resources/dart-dio/gitignore.mustache, samples/client/petstore/dart-dio/.gitignore
update gitignore according to the [dart guide](https://dart.dev/guides/libraries/private-files
).
--
@ircecho @swipesight @jaumard @nickmeinhold (2019/09)
=> [dart-dio] fix(dart-dio): update gitignore according to the dart guide

README.md
Add @athornz, @amondnet to Dart technical committee
cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09)
=> Add @athornz, @amondnet to Dart technical committee

pom.xml, samples/server/petstore/php-slim4/php_syntax_checker.bash, samples/server/petstore/php-slim4/pom.xml
=> [Slim4] Add CI for PHP Slim4 Server

README.md
Add @ityuhui to C technical committee
cc @zhemant
=> Add @ityuhui to C technical committee

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/dartdio/DartDioClientOptionsTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/options/DartClientOptionsProvider.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/options/DartDioClientOptionsProvider.java
=> [Dart] fix option tests

modules/openapi-generator/src/main/resources/Java/libraries/feign/api.mustache, samples/client/petstore/java/feign/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/feign/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/feign/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/api/StoreApi.java
To fix https://github.com/OpenAPITools/openapi-generator/issues/3295
cherrypick https://github.com/OpenAPITools/openapi-generator/pull/3300
Credit: @stephanpelikan
=> Fix Java Feign client's parameter request name

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/Dockerfile.jvm.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/application.properties.mustache, modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/pom.mustache
Similar to #4725 but to update to Quarkus `1.1.0.Final`
=> [jaxrs-spec][quarkus] update to version 1.1.1.Final

pom.xml
Comment out python-flask (python 2.x) test as it fails itself since weekend.
=> Comment out python-flask (python 2.x) test

samples/client/petstore/swift4/rxswiftLibrary/SwaggerClientTests/SwaggerClientTests/UserAPITests.swift
- comment out broken tests for the time being due to bad data
=> [Swift] comment out broken tests due to bad data

modules/openapi-generator/src/main/resources/csharp-netcore/README.mustache, modules/openapi-generator/src/main/resources/csharp-netcore/api_doc.mustache, samples/client/petstore/csharp-netcore/OpenAPIClient/README.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/AnotherFakeApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/FakeApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/FakeClassnameTags123Api.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/PetApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/StoreApi.md, samples/client/petstore/csharp-netcore/OpenAPIClient/docs/UserApi.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/README.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/AnotherFakeApi.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/FakeApi.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/FakeClassnameTags123Api.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/PetApi.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/StoreApi.md, samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/UserApi.md
Fix incorrect configuration setup in csharp-netcore doc 
cc @mandrean (2017/08), @jimschubert (2017/09) @frankyjuang (2019/09)
=> [csharp-netcore] Fix csharp-netcore doc

README.md
=> Add a link to blog post in TECHSCORE

modules/openapi-generator/src/main/resources/Groovy/build.gradle.mustache, modules/openapi-generator/src/main/resources/java-pkmst/pom.mustache, samples/client/petstore/groovy/build.gradle, samples/server/petstore/java-pkmst/pom.xml
=> Updates maven urls, fix #5011

README.md
Add a link to a youtube video on Pulp and OpenAPI Generator
=> Add a link to a youtube video on Pulp and OpenAPI Generator

samples/openapi3/client/petstore/go-experimental/go-petstore/api/openapi.yaml
Somebody forgot to execute ./bin/openapi3/go-experimental-petstore.sh script.
checkout master and execute "mvn package" followed by ./bin/openapi3/go-experimental-petstore.sh.
=> Execute ./bin/openapi3/go-experimental-petstore.sh script

README.md
=> Add a link to a blog post in dev.to

modules/openapi-generator/src/main/resources/aspnetcore/2.0/model.mustache, modules/openapi-generator/src/main/resources/aspnetcore/2.1/model.mustache, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/ApiResponse.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Category.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Order.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Pet.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/Tag.cs, samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Models/User.cs
Fixes #5024. aspnetcore templates previously ignored the `complexType` property which indicates whether it's an inline enum or a reference to another type in the namespace.
Given `openapi.yaml` with enum as model:
```yaml
openapi: '3.0.0'
info:
version: 1.0.0
title: API with Default Values
servers:
- url: http://localhost:8080
paths:
/test:
post:
operationId: testDefaults
requestBody:
required: true
content:
schema:
'$ref': '#/components/schemas/Payload'
responses:
'200':
description: Ok
components:
schemas:
Payload:
type: object
properties:
stringProp:
type: string
default: foo
doubleProp:
type: number
format: double
default: 1.234
enumProp:
$ref: '#/components/schemas/EnumProp'
EnumProp:
type: string
enum: [One, Two, Three]
default: Two
```
This generates via …
=> [aspnetcore] Fix duplicate enums

README.md
=> Add company using generator

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
NPE from #4514 work. Attempted fix to avoid revert of that PR. See #5081 
cc @spacether @wing328
=> [python] Fix NPE in example generation

README.md
Add @bkabrda to Java technical committee
=> Add bkabrda to Java technical committee

README.md
=> Add a link to dev.to article

modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle
Provides an example for #4643
cc @wing328
=> [gradle] Clarify defining multiple tasks

README.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 4.2.3 release

README.md
I wrote about [this(#5090)](https://github.com/OpenAPITools/openapi-generator/pull/5090) PR!
=> Add a link to a ytaka0m blog post

README.md
cc @mandrean (2017/08), @jimschubert (2017/09) [:heart:](https://www.patreon.com/jimschubert) @frankyjuang (2019/09)
=> Add shibayan to C# technical committee

modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
This PR fixes https://github.com/OpenAPITools/openapi-generator/issues/2979
=> [kotlin] Fix non-compilable code

README.md
=> [typescript] Add amakhrov to Typescript tech committee

modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/kotlin.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml
Update pom version in maven plugin test to 4.3.0-SNAPSHOT
=> Update pom in maven plugin test

README.md
=> Add a link to youtube video

README.md
Add a link to simply-how article
=> Add a link to simply-how article

README.md
=> Add a link to article in GiFT, Inc

README.md
=> Add a link to vadosware.io

README.md
=> Add a link to LORNAJANE Blog

modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
Cleans up documentation for the -c option.
=> Edit documentation for -c

modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/helpers-body.mustache
=> [C++] [Qt5 Server] added implementation of declared function.

docs/customization.md, website/docusaurus.config.js, website/package.json, website/src/pages/styles.module.css, website/src/pages/team.js, website/yarn.lock
* Fixes h2 formatting on customization page
* Links to https://api.openapi-generator.tech rather than http
* Inverts github/twitter icons on team page in dark mode
=> [doc] Minor website fixes

README.md
Add checkly as the API monitoring sponsor
=> Add checkly as the API monitoring sponsor

.travis.yml
=> Use yarn for website builds

modules/openapi-generator-maven-plugin/examples/java-client.xml
=> fix typo in maven sample script comment

README.md
Add a link to brightfox blog post
=> Add a link to brightfox blog post

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
For https://github.com/OpenAPITools/openapi-generator/pull/5316/files#r381054386
cc @jimschubert @sebastien-rosset
=> Update the wording about "title" field

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NodeJSExpressServerCodegen.java
- Add post-processing to NodeJS express server generator
To close https://github.com/OpenAPITools/openapi-generator/issues/5323
=> Add post-processing to NodeJS express server generator

README.md
=> Add a link to Xero blog post

pom.xml, samples/client/petstore/kotlin-jackson/pom.xml
Include kotlin jackson petstore client in the CI tests
cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11)
=> Include Kotlin jackson petstore client in the CI tests

docs/usage.md
=> Update usage.md - Grammar

modules/openapi-generator-online/pom.xml, pom.xml
To fix https://github.com/OpenAPITools/openapi-generator/issues/5004
Tested locally and no longer got 500
=> Fix the issue with the online service

website/docusaurus.config.js
Enables Algolia search in the docs site. For example:
=> [docs] Enable Algolia search

README.md
=> Add a link to tech blog tech.medpeer.co.jp

README.md
=> Add links to blog posts about OpenAPI Generator

README.md
Add a link to the conference paper: https://link.springer.com/chapter/10.1007/978-3-030-41494-8_14
=> Add a link to the conference paper

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/clientConfiguration.mustache, samples/client/petstore/spring-cloud-async/src/main/java/org/openapitools/configuration/ClientConfiguration.java, samples/client/petstore/spring-cloud/src/main/java/org/openapitools/configuration/ClientConfiguration.java
Fixes https://github.com/OpenAPITools/openapi-generator/issues/5144 by conditional creation of imported package in `clientConfiguration.mustache`.
=> [Java][Spring][Spring-Cloud] Fix #5144 - Use conditional package declaration to avoid unnecessary dependencies

modules/openapi-generator/src/main/resources/python/python-experimental/api_client.mustache, samples/client/petstore/python-experimental/petstore_api/api_client.py, samples/openapi3/client/petstore/python-experimental/petstore_api/api_client.py
=> [Python-experimental] Fix UnboundLocalError: local variable 'obj_dict' referenced before assignment

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java, samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/package.json, samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-npm/package.json, samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-prefixed-module-name/package.json
=> typescript-angular: fix zone-js version for angular 8

README.md
=> Add a link to the slide

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NodeJSServerCodegen.java
=> NodeJS - Adds missing keyword

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalatraServerCodegen.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/scalahttpclient/ScalaHttpClientModelTest.java, samples/server/petstore/scalatra/src/main/scala/org/openapitools/server/api/PetApi.scala
https://github.com/OpenAPITools/openapi-generator/issues/5507
@clasnake @jimschubert @shijinkui @ramzimaalej
=> fix default value for abstract scala and scalatra server impl

README.md
Hi,
I've added a new blog post about [Load Testing Your API with Swagger/OpenAPI and k6](https://k6.io/blog/load-testing-your-api-with-swagger-openapi-and-k6) to show how the newly added k6 generator works.
=> [k6] Add blog post about using the k6 generator

pom.xml
=> [scala] scala-version 2.11.12

README.md
Fix founding member username rename in GitHub. see #5616
=> micheleISEP->michelealbano

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellExperimentalClientCodegen.java
Fixes minor typo in the powershell-experimental generator.
//cc @wing328
=> [powershell-experimental] Fixes typo

modules/openapi-generator/src/main/resources/C-libcurl/list.c.mustache, modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache, samples/client/petstore/c/model/api_response.c, samples/client/petstore/c/model/category.c, samples/client/petstore/c/model/order.c, samples/client/petstore/c/model/pet.c, samples/client/petstore/c/model/tag.c, samples/client/petstore/c/model/user.c, samples/client/petstore/c/src/list.c
The c client code snippet that I generate using OpenAPI c generator ( master branch ) is below:
```c
void v1_pod_spec_free(v1_pod_spec_t *v1_pod_spec) {
v1_affinity_free(v1_pod_spec->affinity); <-- If v1_pod_spec is null, program will coredump here
...
}
void list_free(list_t *list) {
list_iterateThroughListForward(list, listEntry_free, NULL);   <-- If list is null, program will coredump here.
free(list);
}
``` 
So I add some guard, now the code becomes:
```c
void v1_pod_spec_free(v1_pod_spec_t *v1_pod_spec) {
if(NULL == v1_pod_spec){  <-- now if v1_pod_spec is null, the function will return.
return ;
}    
v1_affinity_free(v1_pod_spec->affinity);
...
}
void list_free(list_t *list) {
if(list){   <-- now if list is null, the function will bypass this code. …
```
=> [C][Client] Check the pointer before deleting operation to avoid core dump label:"Client C"

modules/openapi-generator/src/main/resources/powershell-experimental/api_client.mustache, samples/client/petstore/powershell-experimental/src/PSPetstore/Private/PSApiClient.ps1
=> [PowerShell][Experimental] use basic parsing

README.md, docs/installation.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/README.md, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml, website/src/pages/index.js
=> 4.3.0 release

bin/utils/release/release_version_update_docs.sh
=> Fix file path in release_version_update_docs

modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache, samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb, samples/client/petstore/ruby/lib/petstore/api_client.rb, samples/openapi3/client/petstore/ruby-faraday/lib/petstore/api_client.rb, samples/openapi3/client/petstore/ruby/lib/petstore/api_client.rb
=> fix request.on_complete message when tempfile is nil

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellExperimentalClientCodegen.java
=> [PS][Experimental] Add map example

README.md
please add openVALIDATION Project to the readme.
This open source project includes the integration of openVALIDATION into OpenAPI. It enables the specification of complex validation rules within a service contract using natural language. Thus, both the service stubs and the client proxies including validation logic can be generated automatically. [ read more...](https://docs.openvalidation.io/openapi/openapi-specification)
validation rules can also be generated separately.
sample:
```yaml
info:
version: 1.0.0
title: sample
paths:
/:
post:
requestBody:
content:
schema:
properties:
name:
type: string
mail:
type: number
x-ov-rules:
culture: en
rule: |  
the name of applicant has to be Alex
and his mail must not be alex@yahoo.com
responses:
'200': …
```
=> please add openVALIDATION Project to readme

modules/openapi-generator/src/main/resources/powershell-experimental/api.mustache
=> [PS][Experimental] minor fix to http basic auth

modules/openapi-generator/src/main/resources/powershell-experimental/configuration.mustache, samples/client/petstore/powershell-experimental/src/PSPetstore/Client/PSConfiguration.ps1, samples/client/petstore/powershell-experimental/tests/Petstore.Tests.ps1
- various enhancements, bug fixes
=> [PS] various enhancements, bug fixes

README.md
- [ x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc). …
=> docs: removes Nico from technical committee

modules/openapi-generator/src/main/resources/dart2/enum.mustache
To fix https://github.com/OpenAPITools/openapi-generator/issues/5792
=> Update enum.mustache to fix #5792

README.md
=> Add a link to optim blog post

samples/server/petstore/python-aiohttp-srclayout/Makefile, samples/server/petstore/python-aiohttp/Makefile
proposal fix for https://github.com/OpenAPITools/openapi-generator/issues/5912
=> [Python][aiohttp] create venv as rule

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache, modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache, samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle, samples/client/petstore/java/okhttp-gson-parcelableModel/build.sbt, samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml, samples/client/petstore/java/okhttp-gson/build.gradle, samples/client/petstore/java/okhttp-gson/build.sbt, samples/client/petstore/java/okhttp-gson/pom.xml
- update dependency for java client (okhttp-gson)
=> [Java] update dependency

modules/openapi-generator/src/main/resources/csharp/README.mustache, modules/openapi-generator/src/main/resources/csharp/api.mustache, modules/openapi-generator/src/main/resources/csharp/api_doc.mustache, samples/client/petstore/csharp/OpenAPIClientNet40/src/Org.OpenAPITools/Model/FormatTest.cs, samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/src/Org.OpenAPITools/Model/FormatTest.cs
- Add bearer support to C# client
cc @mandrean (2017/08), @jimschubert (2017/09) @frankyjuang (2019/09) @shibayan (2020/02)
=> [C#] Add bearer support to C# client

modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
Fixes https://github.com/OpenAPITools/openapi-generator/issues/5935
=> [gradle] Print value of outputDir correctly in gradle plugin

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
When an inline schema in allOf is defined without "type: object", then the inline schema will be handled differently.
This PR will fix the incorrect behavior and generate the inline schema as a separate model (the same as how an inline scheme in allOf with "type: object" is defined.
=> Fix inline schema in allOf without object type

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache, samples/client/petstore/typescript-fetch/builds/default/runtime.ts, samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts, samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts, samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
closes #2935
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, …
=> [typescript-fetch] support http HEAD

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/pom.mustache
update version to 3.1.2 
(samples already updated)
=> [JAX-RS] Update cxf version

README.md
- Add a link to the blog post in Nordic APIs
=> Add a link to the blog post in Nordic APIs

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientExperimentalCodegen.java, modules/openapi-generator/src/main/resources/go-experimental/api_doc.mustache, samples/client/petstore/go-experimental/go-petstore/docs/AnotherFakeApi.md, samples/client/petstore/go-experimental/go-petstore/docs/FakeApi.md, samples/client/petstore/go-experimental/go-petstore/docs/FakeClassnameTags123Api.md, samples/client/petstore/go-experimental/go-petstore/docs/PetApi.md, samples/client/petstore/go-experimental/go-petstore/docs/StoreApi.md, samples/client/petstore/go-experimental/go-petstore/docs/UserApi.md, samples/openapi3/client/petstore/go-experimental/go-petstore/docs/AnotherFakeApi.md, samples/openapi3/client/petstore/go-experimental/go-petstore/docs/DefaultApi.md, samples/openapi3/client/petstore/go-experimental/go-petstore/docs/FakeApi.md, samples/openapi3/client/petstore/go-experimental/go-petstore/docs/FakeClassnameTags123Api.md, samples/openapi3/client/petstore/go-experimental/go-petstore/docs/PetApi.md, samples/openapi3/client/petstore/go-experimental/go-petstore/docs/StoreApi.md, samples/openapi3/client/petstore/go-experimental/go-petstore/docs/UserApi.md
- [Go][experimental] provide code samples in the API doc
=> [Go][experimental] provide code samples in the API doc

CI/.drone.yml, samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
Test java 11 native client in drone.ci
=> Test java 11 native client in drone.ci

modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
To fix https://github.com/OpenAPITools/openapi-generator/issues/5915
cc @mandrean (2017/08), @jimschubert (2017/09)  @frankyjuang (2019/09) @shibayan (2020/02)
=> Fix bearer authentication in c# netcore client (async call)

README.md, docs/installation.md, modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, website/src/pages/index.js
=> Prepare 4.3.1 release

modules/openapi-generator-gradle-plugin/README.adoc, modules/openapi-generator-gradle-plugin/build.gradle, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties, modules/openapi-generator-gradle-plugin/samples/local-spec/gradle/wrapper/gradle-wrapper.properties, pom.xml
=> Minor fixes post-release

modules/openapi-generator-maven-plugin/README.md, modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
=> [maven] Introduce addTestCompileSourceRoot

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
https://github.com/OpenAPITools/openapi-generator/issues/6215
cc @mandrean,  @jimschubert, @frankyjuang, @shibayan, @wing328
=> [aspnetcore] Do not reset templateDir in setAspnetCoreVersion

pom.xml
=> scala-maven-plugin 4.3.1

pom.xml
=> testng 7.1.0

modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- Add cookie authentication support to csharp-netcore
- Tested locally and the code compiles without issues.
cc @mandrean (2017/08), @jimschubert (2017/09) @frankyjuang (2019/09) @shibayan (2020/02)
=> Add cookie authentication support to csharp-netcore

samples/client/petstore/python-asyncio/test_python3.sh, samples/client/petstore/python-experimental/test_python2.sh, samples/client/petstore/python-experimental/test_python2_and_3.sh, samples/client/petstore/python-tornado/test_python2_and_3.sh, samples/client/petstore/python/test_python2.sh, samples/client/petstore/python/test_python2_and_3.sh, samples/openapi3/client/petstore/python-experimental/test_python2.sh, samples/openapi3/client/petstore/python-experimental/test_python2_and_3.sh, samples/openapi3/client/petstore/python/test_python2.sh, samples/server/petstore/python-flask-python2/test_python2.sh, samples/server/petstore/python-flask/test_python3.sh
- Fix build failure due to flake8
=> Fix build failure due to flake8

samples/client/petstore/javascript-flowtyped/package-lock.json
- Update JS Flow dependencies to address security alerts
=> Update JS Flow dependencies to address security alerts

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ProcessUtils.java
=> [Java] Fix repeated OAuth files being generated

README.md
Add a link to android blog post
=> Add a link to Android blog post

modules/openapi-generator/src/main/resources/dart2/api.mustache
=> Improve parameter documentation

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java, modules/openapi-generator/src/main/resources/go-experimental/model_enum.mustache, samples/client/petstore/go-experimental/go-petstore/model_enum_class.go, samples/client/petstore/go-experimental/go-petstore/model_outer_enum.go, samples/openapi3/client/petstore/go-experimental/go-petstore/model_enum_class.go, samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum.go, samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_default_value.go, samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer.go, samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer_default_value.go
- Avoid duplicated import in enum model
- Convert spaces to tabs
=> [Go][Experimental] Avoid duplicated import in enum model

pom.xml
Update swagger parser to 2.0.20
Ref: https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.20
Previous update PR: https://github.com/OpenAPITools/openapi-generator/pull/5413
=> Update swagger parser to 2.0.20

modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/AnotherFakeApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/PetApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/StoreApi.java, samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/UserApi.java
Possible fix for:
https://github.com/OpenAPITools/openapi-generator/issues/6301
@bbdouglas  (2017/07) @sreeshas  (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)
=> Use webclient exceptions in java webclient client

README.md
Add @wing328 as the creater of PowerShell client generator, which has been rewritten/refactored in 5.0.0 release
=> Add @wing328 as the creater of PowerShell client generator (refactored)

README.md
Add links to blog post, youtube video
=> Add links to blog post, youtube video

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ProcessUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
Remove `System.out.println` from tests
=> Clean up debug in test

README.md
Add a link to medium blog post
=> Add a link to medium blog post

README.md
Add a link to the article in dev.to
=> Add a link to the article in dev.to

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/anyof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey2/oneof_model.mustache
- minor bug fixes (exception message)
- port https://github.com/OpenAPITools/openapi-generator/pull/6323 enhancement to anyOf
=> [Java][jersey2] enhance anyOf

samples/client/petstore/javascript-es6/package-lock.json
- update package-json.lock to fix security alerts.
=> [JS] update package-json.lock

pom.xml, samples/client/petstore/rust/reqwest/petstore/pom.xml, samples/client/petstore/rust/reqwest/petstore/tests/pet_tests.rs
- add tests to Travis CI
cc @frol (2017/07) @farcaller (2017/08) @bjgill (2017/12) @richardwhiuk (2019/07) @paladinzh (2020/05)
=> [Rust][reqwest] add tests to CI

pom.xml
Comment out erlang server test as it's failing due to change in dependencies
=> [Shippable CI] comment out erlang server test

bin/openapi3/elm.sh, modules/openapi-generator/src/test/resources/3_0/elm.yaml
Mark path parameters as required.
FYI @eriktim
=> Fix Elm test spec

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java, modules/openapi-generator/src/main/resources/powershell/model_oneof.mustache, modules/openapi-generator/src/main/resources/powershell/model_simple.mustache, samples/client/petstore/powershell/src/PSPetstore/Model/Pet.ps1
- better discriminator mapping (same as go-experimental, python-experimental)
=> [PS] better discriminator mapping

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/anyof_model.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey2/oneof_model.mustache
=> [java][jersey2] Fix import of JSON class

README.md
Closes #6628 
Documentation referenced for this PR: https://github.com/AdoptOpenJDK/homebrew-openjdk#other-versions
=> Add missing brew tap command to README instructions

bin/configs/other/openapi3/typescript-angularjs.yaml, bin/configs/typescript-angularjs.yaml, docs/generators.md, docs/generators/typescript-angularjs-deprecated.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularJsClientCodegen.java, pom.xml
Mark `typescript-angularjs` as deprecated since it's no longer supported
=> Mark `typescript-angularjs` as deprecated

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
=> [maven] Avoid "Schema unaliasing" INFO-spam on the Maven console

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, modules/openapi-generator/src/main/resources/Java/libraries/jersey2/auth/OAuth.mustache, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/OAuth.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/OAuth.java
- setting debugging in service
- more logging
To close https://github.com/OpenAPITools/openapi-generator/issues/6461
=> [Java][jersey2] Add debugging to OAuth

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
See https://github.com/OpenAPITools/openapi-generator/issues/6765 for more details.
=> Copy vendor extensions from request body

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 5.0.0-beta release

modules/openapi-generator-cli/pom.xml, modules/openapi-generator-core/pom.xml, modules/openapi-generator-gradle-plugin/gradle.properties, modules/openapi-generator-gradle-plugin/pom.xml, modules/openapi-generator-maven-plugin/examples/java-client.xml, modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml, modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml, modules/openapi-generator-maven-plugin/examples/non-java.xml, modules/openapi-generator-maven-plugin/pom.xml, modules/openapi-generator-online/pom.xml, modules/openapi-generator/pom.xml, pom.xml, samples/meta-codegen/lib/pom.xml
=> Prepare 5.0.0-SNAPSHOT

README.md
Add links to tech blog, youtube video
=> Add links to tech blog, youtube video

README.md
Add a link to DreamFactory blog
=> Add a link to DreamFactory blog

README.md
Add a link to Go article in Qiita Blog
=> Add a link to Go article in Qiita Blog

docs/integration.md
Add cake addin to the integration documentation
=> Add cake addin to the integration documentation

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache, samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
=> [java][jersey2] Fix typo in javadoc

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/auth/HttpSignatureAuth.mustache, samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/HttpSignatureAuth.java
=> [Java][jersey2] Fix format of Date header in HTTP signature

CI/circle_parallel.sh, pom.xml
Rebalance tests to shorten the overall job runtime from 48 minutes to 32 minutes.
FYI. @OpenAPITools/generator-core-team
=> [CircleCI] rebalance tests

samples/client/petstore/scala-akka/pom.xml, samples/client/petstore/scala-httpclient/pom.xml, samples/client/petstore/scala-sttp/pom.xml, samples/client/petstore/scalaz/pom.xml, samples/server/petstore/scala-akka-http-server/pom.xml, samples/server/petstore/scala-finch/pom.xml, samples/server/petstore/scala-lagom-server/pom.xml, samples/server/petstore/scala-play-server/pom.xml, samples/server/petstore/scalatra/pom.xml
replace ~ with $user.home in pom.xml
=> [Scala] replace ~ with $user.home in pom.xml

circle.yml
Add `~/.sbt` to circleci cache
cc @clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)
=> Add ~/.sbt to circleci cache

README.md
=> Add a link to Datadog blog

README.md
Add a link to the dev.to article
=> Add a link to the dev.to article

website/src/dynamic/team.yml
Add "spacether" to the core team in https://openapi-generator.tech/team/
FYI. @OpenAPITools/generator-core-team
=> Add "spacether" to the core team

modules/openapi-generator/src/main/resources/go/client.mustache, samples/client/petstore/go/go-petstore-withXml/client.go, samples/client/petstore/go/go-petstore/client.go, samples/openapi3/client/petstore/go/go-petstore/client.go
Based on https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00, the content-type would be `application/problem+json`
=> [Go] support problem details HTTP API

README.md
Add a link to Laracon EU presentation
=> Add a link to Laracon EU presentation

modules/openapi-generator/src/main/resources/php/api.mustache, samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php, samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
Cherrypick #6265 and update samples
credit: @atanasiuk-hubspot
=> [PHP] Fix sending array of files with multipart/form-data in PHP template

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PlantumlDocumentationCodegen.java
=> Surpress warnings in the plantuml generator

README.md
Add a link to the blog post at qiita
=> Add a link to the blog post at qiita

.travis.yml, shippable.yml
=> Move maven,gradle tests to Shippable CI

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.sbt.mustache, samples/client/petstore/java/jersey2-java8/build.sbt, samples/openapi3/client/petstore/java/jersey2-java8/build.sbt
- Fix http signature auth in build.sbt 
=> [Java][jersey2] Fix http signature authentication in build.sbt

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache, samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java, samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
=> [BUG][JAVA] Fix error handling in okhttp-gson async api client

modules/openapi-generator/src/main/resources/powershell/appveyor.mustache, samples/client/petstore/powershell/appveyor.yml
- Update appveyor image to Visual Studio 2019
=> [PowerShell] Update appveyor image to Visual Studio 2019

README.md
Add a link to https://medium.com/@everisBrasil blog post
=> Add a link to https://medium.com/@everisBrasil blog post

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pojo.mustache
fix following issue: https://github.com/OpenAPITools/openapi-generator/issues/7128
- [+ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [+] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [+] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [+] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator …
=> [jaxrs-spec] Fix JaxRS Spec generator additional model types

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/cmake-lists.mustache, samples/client/petstore/cpp-restsdk/client/CMakeLists.txt
- update cmakelist to fix the issue on Linux (failed to find the cpprest cmake file)
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)
=> [C++][Cpprest] update cmakelist to fix issue on Linux

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/StringUtils.java
Reverts OpenAPITools/openapi-generator#7220
=> Revert "[codegen][Python] Add model cache to speed up code generation"

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- minor code format change
- fix typo
- undo changes to play default version (now set to Play 2.6)
=> Minor enhancements to Java client generator

README.md
* Add Apache 2.0 and OpenCollective badges
* Update bitrise and github workflow badges to use shields and better match other badges
Just an FYI @OpenAPITools/generator-core-team 
Before:
After:
=> [docs] Update README badges

modules/openapi-generator/src/main/resources/scala-play-server/app/apiTrait.scala.mustache
Fix for https://github.com/OpenAPITools/openapi-generator/issues/6889
=> [scala][play] Update apiTrait.scala.mustache

README.md
Add a link to Think IT（シンクイット）blog post
=> Add a link to Think IT（シンクイット）blog post

docs/generators/go-gin-server.md, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoGinServerCodegen.java
Added missing parameter info to go-gin-server documentation.
The actual code.
* apiPath
https://github.com/OpenAPITools/openapi-generator/blob/b48112d9419b3187be9e5b31c0ff47f819668198/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoGinServerCodegen.java#L153-L157
* serverPort
https://github.com/OpenAPITools/openapi-generator/blob/b48112d9419b3187be9e5b31c0ff47f819668198/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoGinServerCodegen.java#L147-L151
=> [docs] Fix go-gin-server additional property docs.

README.md
=> Add wbt-solutions as using company

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java, modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Cat.cs, samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Dog.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Cat.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Dog.cs, samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ParentPet.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Model/Cat.cs, samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Model/Dog.cs
Cherry-pick #6232
Credit @thommy101 
=> [c-sharp] Fix default values with discriminator 

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java, modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaInheritanceTest.java
Reverts OpenAPITools/openapi-generator#6901
=> Revert "Correct allOf with only one child schema (no discriminator)"

README.md
Add a link to SmartHR Tech Blog
=> Add a link to SmartHR Tech Blog

modules/openapi-generator/src/main/resources/go-experimental/client.mustache, modules/openapi-generator/src/main/resources/go-experimental/configuration.mustache, modules/openapi-generator/src/main/resources/go-experimental/go.mod.mustache, modules/openapi-generator/src/main/resources/go/go.mod.mustache, samples/client/petstore/go-experimental/go-petstore/client.go, samples/client/petstore/go/go-petstore-withXml/go.mod, samples/client/petstore/go/go-petstore/go.mod, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/api_usage.go, samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go, samples/openapi3/client/petstore/go-experimental/go-petstore/client.go, samples/openapi3/client/petstore/go/go-petstore/go.mod
Add AWS v4 signature support to `go-experimental` client generator
Ref: https://github.com/OpenAPITools/openapi-generator/pull/4784
=> Add AWS v4 signature support to go-experimental client generator

docs/new-generator.md, modules/openapi-generator/src/main/resources/META-INF/services/org.openapitools.codegen.CodegenConfig, new.sh
This reverts commit 151752aa9d6be346e8750fe14ade592ab3178826.
=> Revert "[doc] Update new-generator steps (new.sh) (#7334)"

docs/new-generator.md, modules/openapi-generator/src/main/resources/META-INF/services/org.openapitools.codegen.CodegenConfig, new.sh
Resubmitted  #7334 without the change to org.openapitools.codegen.CodegenConfig
cc @jimschubert
=> [doc] Update new-generator steps (new.sh)

modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache, samples/client/petstore/c/api/PetAPI.c
These problems are found by code static check tool (Clang Static Analyzer)
and same with PR https://github.com/OpenAPITools/openapi-generator/pull/7305
=> [C][Client][Clang Static Analyzer] Fix uninitialized argument value (Part-2)

pom.xml
Add spacether to pom.xml's developer section
=> Add spacether to pom.xml's developer section
