- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java
- modules/openapi-generator/src/main/resources/elm/Api.mustache
- modules/openapi-generator/src/main/resources/elm/operation.mustache
- modules/openapi-generator/src/test/resources/3_0/elm.yaml
- samples/openapi3/client/elm/src/Api.elm
- samples/openapi3/client/elm/src/Api/Request/Default.elm
Add support for:
* bearer tokens;
* sending `Request`s as `Task`;
* mapping `Http.Error`s to custom errors.
> [elm] Add bearer, task, and sendWithCustomError

- modules/openapi-generator-gradle-plugin/build.gradle
This shuffles around the repositories in the gradle plugin's build file to see if it will help unblock Shippable build failures.
> [gradle] Reorganize build repositories

- docs/generators/javascript-flowtyped.md
- docs/generators/typescript-angular.md
- docs/generators/typescript-angularjs.md
- docs/generators/typescript-aurelia.md
- docs/generators/typescript-axios.md
- docs/generators/typescript-fetch.md
- docs/generators/typescript-inversify.md
- docs/generators/typescript-jquery.md
- docs/generators/typescript-node.md
- docs/generators/typescript-redux-query.md
- docs/generators/typescript-rxjs.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAngularClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAngularJsClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAureliaClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptFetchClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptNodeClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java
This works similar to the existing "modelPropertyNaming", but applies to enum var names instead of model properties.
Default value is "PascalCase", which reflects the way it works currently.
Personally, I only need this configurable in the typescript-angular generator now. However, since the enum var name transformation is implemented in the abstract typescript class, I thought it would be beneficial to keep consistency across multiple typescript generators. After all, this is quite a generic setting, not specific to a particular framework.
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce @akehir @petejohansonxo
> [typescript] Introduce "enumPropertyNaming" option

- docs/generators/javascript-flowtyped.md
- docs/generators/typescript-angular.md
- docs/generators/typescript-angularjs.md
- docs/generators/typescript-aurelia.md
- docs/generators/typescript-axios.md
- docs/generators/typescript-fetch.md
- docs/generators/typescript-inversify.md
- docs/generators/typescript-jquery.md
- docs/generators/typescript-node.md
- docs/generators/typescript-redux-query.md
- docs/generators/typescript-rxjs.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAngularClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAngularJsClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAureliaClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptFetchClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptNodeClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchModelTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java
- samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/model/order.ts
- samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/model/pet.ts
Fixes https://github.com/OpenAPITools/openapi-generator/issues/5135
~I was not able to approach this problem without introducing backward-incompatible changes.
A new `enumSuffix` option is introduced to minimize migration efforts, though.~
**UPDATE**: actually, backward compatibility is now ensured by having `v4-compat` value by default for the newly introduced option
- (**breaking change**) With modelNameSuffix, only append "Enum" suffix but not model suffix. So instead of `ResponseModelPropNameModelEnum` we now get `ResponseModelPropNameEnum`.
- Without modelNameSuffix, all typescript generators except typescript-angular keep the existing behavior (emit smth like `ResponsePropNameEnum`)
- (**breaking change**) typescript-angular now follows the same enum naming rules as other TS …
> [typescript] Append enum suffix without model suffix

- docs/templating.md
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
- modules/openapi-generator-maven-plugin/README.md
- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/AbstractGenerator.java
At one point, we supported loading templates via class path, but there were a few conditions in code which removed this behavior.
You can test with https://github.com/jimschubert/template-classpath-example, which uses [Bangers](https://fonts.google.com/specimen/Bangers?selection.family=Bangers) rather than the font used in the built-in template. The example demonstrates mustache templates loading relative template files rather than falling back to the embedded templates. In that repo:
```
gradle build publishToMavenLocal
```
In this repo:
```
mvn install
java -cp ~/.m2/repository/org/openapitools/samples/template-classpath-example/1.0-SNAPSHOT/template-classpath-example-1.0-SNAPSHOT.jar:modules/openapi-generator-cli/target/openapi-generator-cli.jar \ …
```
> [bug] Templates via classpath

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
When the OAS spec has paths with multiple content types, the following obscure warning is logged:
o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
I have added code comments and better log message.
o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS content section, returning only the first one (‘application/json’)
As a possible enhancement, I suggest supporting a configuration property to specify the desired content type. Sometimes it’s not possible to reorder the OAS spec because you are the consumer of the spec, not the author.
> [codegen] Add code comments and improve "first content" warning

- modules/openapi-generator/src/main/resources/csharp-dotnet2/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/ClientUtils.mustache
- modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
- samples/client/petstore/csharp-dotnet2/OpenAPIClientTest/Lib/OpenAPIClient/src/main/CsharpDotNet2/Org/OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientNet35/README.md
- samples/client/petstore/csharp/OpenAPIClientNet35/docs/FakeApi.md
- samples/client/petstore/csharp/OpenAPIClientNet35/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientNet35/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientNet40/README.md
- samples/client/petstore/csharp/OpenAPIClientNet40/docs/FakeApi.md
- samples/client/petstore/csharp/OpenAPIClientNet40/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientNet40/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientNetStandard/README.md
- samples/client/petstore/csharp/OpenAPIClientNetStandard/docs/FakeApi.md
- samples/client/petstore/csharp/OpenAPIClientNetStandard/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientNetStandard/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/README.md
- samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/docs/FakeApi.md
- samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/src/Org.OpenAPITools/Client/ApiClient.cs
C# bool is upper cased when doing `ToString()`, like `True` or `False`.
OAI defines it as `true` or `false`, so fix it.
@mandrean @jimschubert @frankyjuang
> [csharp][csharp-netcore][csharp-dotnet2] Convert bool value to string in lower case

- modules/openapi-generator-cli/pom.xml
- modules/openapi-generator-cli/src/main/resources/logback.xml
Requested by @ybelenko in #4615
Trying this out: set `-Dcolor`
> [cli] Optional colorized outputs

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/ApiClient.java
Fixes #4866.
PR #3703 introduced a change to the Java `jersey2` generator that dealt with errors that were occurring in the case where no body is supplied. It short-circuits with the empty JSON object as the body:
```diff
-    Entity<?> entity = serialize(body, formParams, contentType);
+    Entity<?> entity = (body == null) ? Entity.json("") : serialize(body, formParams, contentType);
```
- As #4866 discovered, when there is no body supplied but there are form parameters (it's `multipart/form-data` or `application/x-www-form-urlencoded`), the above logic skips the creation of a body from the form parts. This pull request changes the logic to not miss the form parameter body construction.
- I suspect from the commentary on the previous pull request and issue that `Entity.json("")` was not …
> [java-jersey2] Fix empty body when form parameters supplied

- docs/customization.md
Replaced `-D` with `-p` since `-D` arguments after `generate` subcommand are deprecated now.
https://github.com/OpenAPITools/openapi-generator/blob/ac528aaf07978ac722c6da5435cbda16aba9115f/modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java#L403
> [doc] Replace `-D` with `-p`

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OpenApiEvaluator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OpenApiParameterValidations.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OpenApiSchemaValidations.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OpenApiSecuritySchemeValidations.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OperationWrapper.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/ParameterWrapper.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/SchemaWrapper.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/SecuritySchemeWrapper.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/validations/oas/OpenApiOperationValidationsTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/validations/oas/OpenApiParameterValidationsTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/validations/oas/OpenApiSchemaValidationsTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/validations/oas/OpenApiSecuritySchemeValidationsTest.java
* Add "OpenAPI" attribute such that validators can access the OpenAPI specification. For example, this is useful to determine the version of the OpenAPI spec, but this could also be useful potentially to perform cross attribute validation.
For example, I would like to be able to do something like this: https://github.com/CiscoM31/openapi-generator/pull/16/files#diff-74008c7d7a3f7e768ea177ffd70c334dR91
* Add code comments to existing method.
> [codegen] Add openAPI attribute to validation and recommendation

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/2_0/composed-allof.yaml
Fixes https://github.com/OpenAPITools/openapi-generator/issues/4770
Turned out that generator still supports a deprecated inheritance case with a single oneOf ref without a discriminator. The behavior in this case is to treat it as inheritance rather than composition.
Now, the problem is that even though `model.parent` is properly populated with the referenced model in this situation, `model.allParents` (**used with multiple inheritance**) stays empty. It looks like a bug in the implementation rather than intended behavior - but of course correct me if I'm wrong.
This PR makes sure the same logic supporting the deprecated inheritance case applies both to `parent` and `allParents`.
I also cleaned up a few tests for DefaultCodegen that are related to `allOf` composition - just to give me a …
> [core][typescript][perl] Ensure model.parent is also added to model.allParents with multiple inheritance

- modules/openapi-generator/src/main/resources/JavaSpring/typeInfoAnnotation.mustache
- samples/server/petstore/spring-mvc-j8-async/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/spring-mvc-j8-localdatetime/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/spring-mvc/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/springboot-beanvalidation/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/springboot-delegate/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/Animal.java
- samples/server/petstore/springboot-virtualan/src/main/java/org/openapitools/virtualan/model/Animal.java
- samples/server/petstore/springboot/src/main/java/org/openapitools/model/Animal.java
This fixes issue #3796 for JavaSpring. It's a very straightfoward extension
of #5120 for the JavaSpring generator (that PR was just for the Java generator).
> Use EXISTING_PROPERTY for JavaSpring as well

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
* Add enableEnumPrefixRemoval option to toggle whether enum prefixes are stripped. Currently the prefixes are stripped so I have this option set to true by default.
* Close #2624
* Add tests to `DefaultCodegenTest` to test functionality and verify default behavior has not changed.
- [ x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ …
> [feature] Add option to disable stripping of common prefix enum

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientExperimentalCodegen.java
Currently an openapi model called e.g. `EntityURL` would have a structure generated with name `EntityUrl`. I think this is both against the intention of the spec author and it is also against [Go naming recommendations](https://github.com/golang/go/wiki/CodeReviewComments#initialisms). This PR fixes that to preserve the capitalized acronyms.
> [go-experimental] Preserve capitalized acronyms in structure names

- modules/openapi-generator-maven-plugin/README.md
- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
The maven documentation was missing a few option, a couple of option
properties, and was inconsistent regarding selective generation for apis
an models. This adds properties and options where appropriate and
updates the docs. All options in the README have been reordered to match
property declaration order in CodegenMojo, hopefully making it easier
for maintainers to recognized when there are docs missing or out of
date.
This also slightly refactors the code in CodegenMojo to reduce the
cyclomatic complexity of the `execute` method.
cc @OpenAPITools/generator-core-team @shybovycha 
closes #4938 
closes #4937
@shybovycha I hope this documentation update helps make it more clear how to use these properties without potential breaking changes and without using `additionalProperties` as a …
> [maven]:memo: Docs and minor refactoring

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java
Some operational messages are iterated multiple times during some generations and should only be logged once.
This uses the cache I recently added to debounce some log messages. By default the messages `once`'d here will only display a most once per 2 seconds, and is configurable (see OnceLogger for details).
@OpenAPITools/generator-core-team fyi
> [core] Log some things in model/url utils once

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientExperimentalCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/OneOfImplementorAdditionalData.java
- modules/openapi-generator/src/main/resources/Java/model.mustache
- modules/openapi-generator/src/main/resources/Java/model_test.mustache
- modules/openapi-generator/src/main/resources/Java/pojo_doc.mustache
- modules/openapi-generator/src/main/resources/go-experimental/model.mustache
- modules/openapi-generator/src/main/resources/go-experimental/model_doc.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/OneOfImplementorAdditionalDataTest.java
- modules/openapi-generator/src/test/resources/3_0/composed-oneof.yaml
This PR adds `oneOf` support in the same way it was added for Java clients recently in #5120. It contains a lot of refactoring to be able to use the same mechanisms as were used to implement this feature for Java. Also see https://github.com/OpenAPITools/openapi-generator/pull/4785 for discussion on semantics of `oneOf` and thoughts on why it was implemented that way for Java.
Note that this PR doesn't contain any tests right now. I do want to add tests, but would like to do that after the general direction of this PR and the related refactoring is approved.
> [go-experimental] Add oneOf support

- README.md
Per request from William Cheng, we added our company to the README. We have used OpenAPI Generator to build out our whole API successfully.
> Added Logicdrop to the README

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularJsClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAureliaClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptInversifyClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptJqueryClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptReduxQueryClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchModelTest.java
If the user has set --type-mappings Date=foo, respect this setting
instead of hardcoding the date type.
> [typescript] Don't hardcode the date type if user has mapped it

- modules/openapi-generator/src/main/resources/typescript-rxjs/apis.mustache
This PR fixes the wrong formatting of format 'date' for the typescript rxjs generator. It was falsely converted to 'date-time' (e.g. '2019-12-10T17:56:56.999Z') but should look like '2019-12-10'.
Fix #4763
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)
> [BUG][TYPESCRIPT-RXJS] Format Date is converted to Date-Time

- website/src/pages/users.html.js
Our Docusaurus 1.x site had a users.html page. This adds a redirect from
that location to /users
see also #5271
cc @wing328
> [docs] Support old site's users.html

- docs/generators/go-experimental.md
- docs/generators/go.md
- docs/usage.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
This passage confused me when I was reading [this page](https://openapi-generator.tech/docs/usage/):
>whether to include Go codegen comment to disable Go Lint and collapse by default GitHub in PRs and diffs (Default: false)
I'm not entirely sure, but I think this PR proposes the intended formulation.
I'm not a Java expert, but I'm also wondering why [`GoClientCodegen.java`](/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java#L86) has said string hardcoded instead of using `WITH_GO_CODEGEN_COMMENT_DESC` from [`CodegenConstants.java`](/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java#L70), but I guess that's a separate issue …
> [go] Fix typo: "default GitHub in PRs"

- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
This was previously erroneously pointing at the wrong constant.
> Fix docs for --enable-post-process-file

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
> Add missing keywords in rust

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
FYI @mvniekerk 
CC @frol @farcaller @bjgill @richardwhiuk
> Fix NPE in rust server generator

- modules/openapi-generator/src/main/resources/Javascript-Flowtyped/babelrc
change `absoluteRuntime` to false which is the usual default. 
fixes issues brought up here #4677 
the imports in `lib/api.js` and `lib/configuration.js` are now relative. 
> [javascript-flowtyped] Update babelrc

- modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/models/Pet.kt
https://github.com/OpenAPITools/openapi-generator/pull/4707 introduced a flag `sortModelPropertiesByRequiredFlag` to control how the model orders the properties to fix https://github.com/OpenAPITools/openapi-generator/issues/4705.
By default the model properties already are sorted by the required here
https://github.com/OpenAPITools/openapi-generator/blob/4fa096f604bfe138a7ea6d3a426cfd3caed473ad/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java#L76
And the user can choose if he wants to sort the model properties already by the required or not here
https://github.com/OpenAPITools/openapi-generator/blob/4fa096f604bfe138a7ea6d3a426cfd3caed473ad/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.j …
> [kotlin][client] respect sortModelPropertiesByRequiredFlag

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
Fix Issue #3432
Changed the template for generating the ApiClient.java class for Java with okhttp-gson library so that the GzipRequestInterceptor and the RetryingOauth interceptors are added to the OkHttpClient builder before building it. This avoids modifying the immutable list of interceptors which caused the UnsupportedOperationException before.
> [Java][okhttp-gson] Use builder api of OkHttpClient to avoid UnsupportedOperationEx

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
fixes #5282, allows developer to set base_path to an empty string.
The code check the `this.configuration.basePath`, if it's **NOT A NULL OR UNDEFINED**,  then use `this.configuration.basePath`, otherwise use the `BASE_PATH`
> typescript-fetch: Base Path can't be set to empty string

- modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/api/pet.service.ts
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/api/store.service.ts
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/api/user.service.ts
Fixes #5307 
If useSingleRequestParameter is activated for the Angular generator, a JSDoc comment is added to the generated request parameter interface members (if a description is given in the spec).
_Previously:_
```
export interface ExampleRequestParams {
test: string;
}
```
_With this PR:_
```
export interface ExampleRequestParams {
/** An example documentation of the request parameter test. */
test: string;
}
```
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)
> typescript-angular: single request parameter documentation

- docs/usage.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
Add code comments in ModelUtils and documentation for the --generate-alias-as-model argument.
> [codegen] Improve java code comments and argument documentation; Fix issue with ComposedSchema that has undeclared properties

- modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
- samples/client/petstore/javascript-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise/src/ApiClient.js
- samples/client/petstore/javascript/src/ApiClient.js
- samples/openapi3/client/petstore/javascript-es6/src/ApiClient.js
Avoid setting `Content-Type` header if body is not used. Currently, it's set to `application/json` by default even if no body is used.
This is important in that it makes request [simple](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests) to avoid triggerring a CORS preflight, which may not be supported by server since the sever does not expect it.
> [JavaScript] Avoid setting Content-Type header if body is not used

- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
After generating a C-libcurl client for kubernetes and linking with my program,  a coredump will happen due to deleting an un-allocated memory
```
Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x3000000030) at malloc.c:2951
2951    malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x3000000030) at malloc.c:2951
#1  0x00000000004290a0 in CoreV1API_listCoreV1NamespacedSecret (apiClient=0x6b4570, namespace=0x488489 "default", 
pretty=0x0, allowWatchBookmarks=0, _continue=0x0, fieldSelector=0x0, labelSelector=0x0, limit=0, 
resourceVersion=0x0, timeoutSeconds=1000, watch=0) at /root/c_k8s_api_client/api/CoreV1API.c:16598
#2  0x0000000000401532 in listSecret () at main.c:77
#3  0x000000000040179f in main (argc=2, argv=0x7fffffffe0a8) at …
```
> [C-libcurl] Guard memory free for query parameters to avoid coredump

- docs/plugins.md
While working with a OpenAPI with Maven plugin had some trouble with the dependencies for the generated Models.
Updating the docs to help others that may face the same issues in the future.
> [maven] improve documentation regarding depedencies issues

- modules/openapi-generator/src/main/resources/r/api.mustache
- samples/client/petstore/R/R/pet_api.R
- samples/client/petstore/R/R/store_api.R
- samples/client/petstore/R/R/user_api.R
CRAN committee recommended using `dontrun` instead of `donttest`. The reason is that the generated OpenAPI client library uses some sort of authentication and `dontrun` specifies that the example snippets can't be run without defining some additional configuration like API keys/username-password etc. whereas `donttest` specifies that examples can be run without any additional configurations manually.
@Ramanth
> [r] Handling CRAN feedback for example snippets

- modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache
- samples/client/petstore/typescript-rxjs/builds/default/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts
With Typescript 3.7.5 the `runtime.ts` template output produces the following error:
```ts
(50,9): Type ‘“” | ((name: string) => string) | undefined’ is not assignable to type ‘((name: string) => string) | undefined’.
Type ‘“”’ is not assignable to type ‘((name: string) => string) | undefined’.
```
referring to the coalescing of the null `""` JS value in the following lines:
https://github.com/OpenAPITools/openapi-generator/blob/118b5e77473c80eb0e3cbea1413ecf27075c19e3/modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache#L39
https://github.com/OpenAPITools/openapi-generator/blob/118b5e77473c80eb0e3cbea1413ecf27075c19e3/modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache#L44
Additionally, the `typeof accessToken === 'function'` check opens …
> [BUG][typescript-rxjs] Fix nully type coalescing in Configuration getters

- docs/debugging.md
- docs/usage.md
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/AbstractGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DryRunStatus.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
CLI now supports `--dry-run`, which will output a file change status similar to git status --porcelain. This option aligns with #1811 for providing users and template authors more details about targeted outputs. This `--dry-run` option will be necessary in order to present users with vendor extensions which heavily rely on the generator inputs and often on logic defined by some generator implementations which is only evaluated during generation.
The user may also specify `--verbose` for a one-liner below each file explaining why the change operation might take place.
This PR also cleans up some lint warnings and improves general code cleanliness
of DefaultGenerator.
Specifically:
* logger strings are now using the built-in log formatter rather than
constructing new strings regardless of …
> [cli][core] Add support for dry-run and display

- modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache
I have noticed that in certain cases, the enum usage for path parameter and url query parameter is incorrectly implemented. 
In the case I have an enum with MY_ENUM("MyEnum") and I am using the enum as a path parameter. The path would look like that "myPath/.../MY_ENUM/...". This request would always fail. That is due to the different enum value than the server would expect.
To fix this issue, I suggest we add a custom toString to every enum class so that we will not use the enum var name but the value. That way the path would look like this "myPath/.../MyEnum/...".
Changes made with this PR:
- Added custom toString to the enum class script.
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11)
> [Kotlin][Client] Enum toString handling

- modules/openapi-generator/src/main/resources/python/gitlab-ci.mustache
- modules/openapi-generator/src/main/resources/python/travis.mustache
- samples/client/petstore/python-asyncio/.gitlab-ci.yml
- samples/client/petstore/python-asyncio/.travis.yml
- samples/client/petstore/python-experimental/.gitlab-ci.yml
- samples/client/petstore/python-experimental/.travis.yml
- samples/client/petstore/python-tornado/.gitlab-ci.yml
- samples/client/petstore/python-tornado/.travis.yml
- samples/client/petstore/python/.gitlab-ci.yml
- samples/client/petstore/python/.travis.yml
- samples/openapi3/client/petstore/python-experimental/.gitlab-ci.yml
- samples/openapi3/client/petstore/python-experimental/.travis.yml
- samples/openapi3/client/petstore/python/.gitlab-ci.yml
- samples/openapi3/client/petstore/python/.travis.yml
As requested in [this comment](https://github.com/OpenAPITools/openapi-generator/pull/5342#issuecomment-587074732) of #5342 , this PR makes sure that the generated `.travis.yml` and `.gitlab-ci.yml` for python projects respect the "useNose" option passed to them from the CLI. The will switch to using either `nosetests` or `pytest`.
----------------------
Adding Python technical committee: @taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess @slash-arun @spacether
> Respect usenose for Python CI

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
Avoid using filename with sufixes with valid `$GOOS` or `$GOARCH` to avoid surprises.
❗️ **Huge thanks to @zippolyte for identifying this issue.** ❗️ 
--
> [go] Fix filenames with $GOOS and $GOARCH sufixes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
This resolves issue #4403.
On a model `Foo` with an inline enum `Bar` which has a possible string
value `baz`. we should generate a `FooDTO::BAR_BAZ` constant, not
`FooDTO::BAR_DTO_BAZ`.
> [PHP] Remove model prefix/suffix from inline enum var names

- modules/openapi-generator/src/main/resources/python/api_client.mustache
- modules/openapi-generator/src/main/resources/python/configuration.mustache
- samples/client/petstore/python-asyncio/petstore_api/api_client.py
- samples/client/petstore/python-asyncio/petstore_api/configuration.py
- samples/client/petstore/python-experimental/petstore_api/configuration.py
- samples/client/petstore/python-tornado/petstore_api/api_client.py
- samples/client/petstore/python-tornado/petstore_api/configuration.py
- samples/client/petstore/python/petstore_api/api_client.py
- samples/client/petstore/python/petstore_api/configuration.py
- samples/client/petstore/python/tests/test_configuration.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/configuration.py
- samples/openapi3/client/petstore/python/petstore_api/api_client.py
- samples/openapi3/client/petstore/python/petstore_api/configuration.py
As a follow up the discussion https://github.com/OpenAPITools/openapi-generator/pull/4485#issuecomment-584915749 I'd like to recovery an option to set default configuration. I prepared very simple solution which provides the same API as we had before.
Thanks for reviewing it.
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) @spacether (2019/11)
> [python] add method to set/get default configuration

- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/api/TemplatingEngineAdapter.java
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/api/TemplatingGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/HandlebarsEngineAdapter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/MustacheEngineAdapter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/TemplateNotFoundException.java
Experimental handlebars template engine wasn't applying data bundle to supporting files. This fixes that.
Because this changes how default mustache supporting files are handled, and our samples directory overwrites existing files, I'd like someone to double-check generation of mustache. I'd deleted the whole `samples` directory before regeneration, but this results in ~1200 lines of git status. I switched over to master and had the same results
closes #5320
> [hb] Honor supporting files when applying bundles

- modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/AppMain.kt.mustache
make the import conditional, and add a few that were missing
without this, setting `featureCORS` or `featureConditionalHeaders` to true produces invalid code
> kotlin-server: fix features' imports

- docs/generators/typescript-angular.md
- docs/generators/typescript-angularjs.md
- docs/generators/typescript-aurelia.md
- docs/generators/typescript-axios.md
- docs/generators/typescript-fetch.md
- docs/generators/typescript-inversify.md
- docs/generators/typescript-jquery.md
- docs/generators/typescript-node.md
- docs/generators/typescript-redux-query.md
- docs/generators/typescript-rxjs.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
This allows mapping the array type to TypeScript's ReadonlyArray. If ReadonlyArray is not a native type, using --type-mappings array=ReadonlyArray causes erroneous attempts at importing ReadonlyArray from the generated code.
> [typescript] Add ReadonlyArray to native types

- docs/generators/cpp-pistache-server.md
- docs/generators/cpp-restbed-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestbedServerCodegen.java
Completes a leftover task for #5269. That PR fixed issue #5268, but did not propagate the fix into all code generators, since some of them clear the base class's CLI options. This ensures that the added CLI option in the linked PR also appears in the Restbed and Pistache C++ generators.
> Add reserved word option to Pistache and Restbed generators

- modules/openapi-generator/src/main/resources/erlang-server/logic_handler.mustache
Logic added to logic_handler.mustache so that it does not export authorize_api_key/3 when the function is not defined, leading to compilation error of *_logic_handler.erl, where * is openapi by default. 
```rebar3 shell``` under the root directory of the code stub can be run to compile.
> [erlang] Do not export function if not defined.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/petstore.yaml
-  handling examples of type date for openAPI 3 as localdate
- created test
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01) @wing328  @jmini
> [Java] Error generating java due to a default for a date  #5086

- modules/openapi-generator/src/main/resources/php-symfony/model_generic.mustache
- samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Order.php
- samples/server/petstore/php-symfony/SymfonyBundle-php/Model/Pet.php
As it is possible to add types to the generated code (method argument types), it seems it is also wise to add types at the return value. This is wat this MR does.
> Add return types to getter and fluent setter

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java
Related issue: https://github.com/OpenAPITools/openapi-generator/issues/5417
Add error output to the log so that we can make sure why the error occured, when the command passed via RUBY_POST_PROCESS_FILE failed.
```sh
$ which rubocop
/usr/local/bin/rubocop
$ rubocop -v
0.80.0
$ env RUBY_POST_PROCESS_FILE="/usr/local/bin/rubocop -a" \
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar \
generate \
-g ruby \
-o /tmp/issue/5417 \
-i http://petstore.swagger.io:8080/api/v3/openapi.json \
--enable-post-process-file
```
Before:
```
[main] ERROR o.o.c.languages.AbstractRubyCodegen - Error running the command (/usr/local/bin/rubocop -a /tmp/issue/5417/lib/openapi_client/models/address.rb). Exit value: 2
```
After:
the error output shows why rubocop resulted in error
``` …
```
> [Ruby] Add error output

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Fix NPE when enum contains `null`
> Fix NPE for enum

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/UserApi.java
- better code format for Java (WebClient) client
- prefix some local variables with an underscore 
> [Java][WebClient] better code format

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
Small, but so important fix. Configuration class has baseOptions key, this is object for set any axios options, but headers from this object was ignored because they shadowing, I fixed this.
> Fix #5420 add headers from configuration object

- docs/generators/javascript-flowtyped.md
- docs/generators/typescript-angular.md
- docs/generators/typescript-angularjs.md
- docs/generators/typescript-aurelia.md
- docs/generators/typescript-axios.md
- docs/generators/typescript-inversify.md
- docs/generators/typescript-jquery.md
- docs/generators/typescript-rxjs.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptInversifyClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptReduxQueryClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java
Fixes #2976
**Summary**
- Generators without runtime models conversion use "original" property naming by default. It's still possible to change it via cli options - might be helpful when used together with customized templates. The cli option description has been modified to provide some more context.
- Generators with runtime conversion (typescript-fetch, typescript-node, typescript-reduxquery) keep using "camelCase"
**Implementation notes**
- I decoupled `toVarName` from `toParamName`. Former respects the `modelPropertyNaming`, while latter keeps always using camelCase.
- Refactoring: use an enum instead of string for `modelPropertyNaming`. It now better resembles `enumPropertyNaming`.
- No samples have changed. It's because `petstore.yaml` has all model vars defined in camelCase - …
> [typescript] Clean up modelPropertyNaming across generators 

- modules/openapi-generator/src/main/resources/cpp-qt5-client/CMakeLists.txt.mustache
Moved GCC-specific compile flags to non msvc builds, and added equivalent flags for msvc.
Copying the c++ technical committee @ravinikam @stkrwork @etherealjoy @martindelille @muttleyxd
> Added support for msvc builds in cpp-qt5-client generator

- modules/openapi-generator/src/main/resources/ruby-client/api_client_spec.mustache
- modules/openapi-generator/src/main/resources/ruby-client/rubocop.mustache
- samples/client/petstore/ruby-faraday/.rubocop.yml
- samples/client/petstore/ruby/.rubocop.yml
- samples/client/petstore/ruby/spec/api_client_spec.rb
- samples/openapi3/client/petstore/ruby-faraday/.rubocop.yml
- samples/openapi3/client/petstore/ruby-faraday/spec/api_client_spec.rb
- samples/openapi3/client/petstore/ruby/.rubocop.yml
- samples/openapi3/client/petstore/ruby/spec/api_client_spec.rb
Fix #5417
- Fix renamed Cop and its settings in generated `.rubocop.yml`
- Remove obsolete cop `Style/BracesAroundHashParameters` from generated `.rubocop.yml` (this has been removed from Rubocop v0.80.0)
- Fix rubocop's warns in generated Ruby client code
> [Ruby] Fix obsolete configuration of Rubocop and Rubocop's warns (#5417)

- modules/openapi-generator/src/main/resources/ruby-client/Gemfile.mustache
- samples/client/petstore/ruby-faraday/Gemfile
- samples/client/petstore/ruby/Gemfile
- samples/openapi3/client/petstore/ruby-faraday/Gemfile
- samples/openapi3/client/petstore/ruby/Gemfile
```
CVE-2020-8130
moderate severity
Vulnerable versions: <= 12.3.2
Patched version: 12.3.3
There is an OS command injection vulnerability in Ruby Rake before 12.3.3 in Rake::FileList when supplying a filename that begins with the pipe character |.
```
> [Ruby] Fix CVE-2020-8130

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/main/resources/rust-server/models.mustache
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/multipart-v3/src/models.rs
- samples/server/petstore/rust-server/output/openapi-v3/README.md
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/docs/NullableTest.md
- samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/NullableTest.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs
- samples/server/petstore/rust-server/output/rust-server-test/src/models.rs
This fixes a number of bugs when nullable was used alongside optional or array types - primarily around either generating invalid default values or rendering them to string parameters incorrectly.  I've added tests for these and fixed the bugs.
This fix was contributed by @mirw and reviewed by myself, on behalf of of @Metaswitch.
- @frol
- @farcaller 
- @bjgill
> [Rust Server] Nullable fixes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/test/resources/2_0/rust-server/petstore-with-fake-endpoints-models-for-testing.yaml
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/README.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/api/openapi.yaml
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/fake_api.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/client.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/server_lib/mod.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
Handle response descriptions which start with a number.
- @frol
- @farcaller 
- @bjgill
> [Rust Server] Handle numeric response description

- modules/openapi-generator/src/main/resources/go-experimental/model.mustache
- samples/client/petstore/go-experimental/go-petstore/model_enum_class.go
- samples/client/petstore/go-experimental/go-petstore/model_outer_enum.go
- samples/client/petstore/scala-gatling/bin/gatling/loginUser-queryParams.csv
- samples/client/petstore/scala-gatling/bin/gatling/org/openapitools/client/api/UserApiSimulation.scala
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_enum_class.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_default_value.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer_default_value.go
Adds `Ptr` method that returns a reference to the constant enum value.
---
> [go] Add Ptr method to const enum values

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/test/resources/2_0/rust-server/petstore-with-fake-endpoints-models-for-testing.yaml
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/README.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/api/openapi.yaml
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/fake_api.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/client.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/server_lib/mod.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
Support operation IDs which begin with a number
- @frol
- @farcaller 
- @bjgill
> [Rust Server] Support numeric operation IDs

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/openapi-v3/README.md
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/docs/default_api.md
- samples/server/petstore/rust-server/output/openapi-v3/examples/client.rs
- samples/server/petstore/rust-server/output/openapi-v3/examples/server_lib/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/mimetypes.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
Support application/merge-patch+json as defined by RFC 7386 -
https://tools.ietf.org/html/rfc7386
Handle exactly the same as application/json - similarly to https://github.com/OpenAPITools/openapi-generator/pull/5407
- @frol
- @farcaller 
- @bjgill
> [Rust Server] Support RFC 7386

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/ApiResponse.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/List.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/ModelReturn.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/docs/Name.md
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs
Currently a field which matches a Rust keyword e.g. `type` is rendered as the Rust variable `_type` in order to produce valid Rust. This is confusing, because a leading underscore indicated an unused variable in Rust code.
Instead we match convention in the Rust community and suffix variables with an `_` instead. For fields which begin with a number (e.g. `1234word`), we prefix them with `param_` to avoid this problem, and avoid being unable to to start with a number.
- @frol
- @farcaller 
- @bjgill
> [Rust Server] Suffix reserved words with _

- samples/openapi3/client/petstore/ruby/spec/custom/pet_spec.rb
- samples/openapi3/client/petstore/ruby/spec/petstore_helper.rb
This PR fixes Rubocop warnings in `samples/openapi3/client/petstore/ruby`.
Before:
```
$ (cd samples/openapi3/client/petstore/ruby && rubocop -c .rubocop.yml)
Inspecting 129 files
............................................................................C..................................................C.
Offenses:
spec/custom/pet_spec.rb:82:9: C: Layout/LeadingCommentSpace: Missing space after #.
#expect(e.message).to eq("Error message: the server returns an error\nHTTP status code: 404\nResponse headers: {\"Date\"=>\"Tue, 26 Feb 2019 04:35:40 GMT\", \"Access-Control-Allow-Origin\"=>\"*\", \"Access-Control-Allow-Methods\"=>\"GET, POST, DELETE, PUT\", \"Access-Control-Allow-Headers\"=>\"Content-Type, api_key, Authorization\", \"Content-Type\"=>\"application/json\", …
```
> Fix rubocop warnings in Ruby client's custom spec

- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
To fix the issue [#5101](https://github.com/OpenAPITools/openapi-generator/issues/5101)
The name "x-api-token" in API spec includes the c keyword "-",  and it is escaped:
```
if (x_api_token) {
keyHeader_x_api_token = strdup("x_api_token");  <--should not be escaped here
valueHeader_x_api_token = strdup((x_api_token));
```
Now the fix will not escape:
```
if (x_api_token) {
keyHeader_x_api_token = strdup("x-api-token");  <--It is right now
valueHeader_x_api_token = strdup((x_api_token));
```
@wing328 @zhemant
> [C-libcurl] The name in API parameter should not be escaped

- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Validate.java
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/ValidateTask.kt
The validate command now uses ParseOptions#setResolve(true) to match how
we parse in CodegenConfigurator and online's Generate. Without this
option, the OpenAPI 3 parser skips the "resolve" block, which made lead
to validations in the command not matching validations during
generation.
I found this difference while stepping through #5413 
This will now match: https://github.com/OpenAPITools/openapi-generator/blob/b0b46d57e07696932038122aec569905c5ed5a22/modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java#L453-L455
and:
https://github.com/OpenAPITools/openapi-generator/blob/b0b46d57e07696932038122aec569905c5ed5a22/modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/Generator.java#L95-L105
cc …
> [cli][gradle] Validate now uses parseOptions w/setResolve

- modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/Paths.kt.mustache
- samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/Paths.kt
fixes #5198
Optional parameters have to annotated as nullable
I can't find `./bin/openapi3/kotlin-server-petstore.sh`:cry:
> [kotlin]Fix ktor doesn't generate nullable types

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
- modules/openapi-generator/src/main/resources/rust-server/lib.mustache
Don't change the API version which is exposed in `crate::API_VERSION`.
This is useful, because often the API version needs to be passed on the API (e.g. as a query parameter), at which point it's useful if you can use the API version which the library itself is exposing.
As such, we change the logic such that:
- If the API version isn't set, we don't expose it.
- If it is set, we leave it well alone.
- Always pass a package version:
- Pass in the passed package version by preference
- Pass in the API version if it's not.
- If the API version isn't set, we use 1.0.0
- If it is set, and isn't a valid semver, we append .0 such that we have
something with three digits (so that an API version of 1 works).
This is obviously breaking, as we are changing the exposed API version for a bunch of …
> [Rust Server] Don't change the API version

- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pojo.mustache
The annotation is present on other generated files when using jaxrs-spec, but is missing on model classes.
This PR doens't change any samples, because the samples are built with `hideGenerationTimestamp=true`.
> Add missing `@Generated` annotation.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchClientCodegenTest.java
This fixes https://github.com/OpenAPITools/openapi-generator/issues/4968 as well the related case for mapAlias.
Hope the bit of refactoring is ok.
All existing and new tests pass and no samples where changed.
CC @TiFu (2017/07) @taxpon (2017/07)  @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09)  @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir  (2019/07) @petejohansonxo (2019/11)
> Typescript array alias array

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- modules/openapi-generator/src/main/resources/php/api.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
Fixes #2292, Guzzle seems to handle collections and manual serialization breaks that functionality.
> fix(php): no need to serialize collections, Guzzle does that, fix #2292

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlim4ServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlimServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpZendExpressivePathHandlerServerCodegen.java
- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
- replace $collectionFormat with $style
- minor code format enhancement
> [php] replace $collectionFormat with $style

- docs/generators/scala-akka.md
- docs/generators/scala-gatling.md
- docs/generators/scala-httpclient-deprecated.md
- docs/generators/scala-lagom-server.md
- docs/generators/scala-play-server.md
- docs/generators/scala-sttp.md
- docs/generators/scalaz.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/scala/AbstractScalaCodegenTest.java
With option `--type-mappings=number=BigDecimal` generators produce models with imported `java.math.BigDecimal` type instead of `scala.math.BigDecimal` which is not required any import as has public alias `BigDecimal` 
This PR is to replace import from DefaultCodegen with proper scala related types import
@clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03)
> [BUG][scala][template] scala generate java.math.BigDecimal instead of scala type

- modules/openapi-generator/src/main/resources/php/api.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
Current code for the PHP generator doesn't properly support the 'form' style. If we look at other implementations (such as the Javascript one), when _explode_ is **true** and _style_ equals to **form**, the parameter should be expanded so that each key inside the parameter (which should then be an array) would result in a new query parameter. There is a very nice example of this in the accepted answer for [this thread at stackoverflow](https://stackoverflow.com/questions/49582559/how-to-document-dynamic-query-parameter-names-in-openapi-swagger).
So, to make this work, in my humble opinion this code might be changed to:
```
if (${{paramName}} !== null) {
{{#style}}
if('form' === '{{style}}' && is_array(${{paramName}})) {
foreach(${{paramName}} as $key => $value) {
$queryParams[$key] = …
```
> [PHP] complete support for form style

- samples/client/petstore/swift4/default/SwaggerClientTests/SwaggerClientTests/StoreAPITests.swift
- samples/client/petstore/swift4/promisekitLibrary/SwaggerClientTests/SwaggerClientTests/StoreAPITests.swift
- samples/client/petstore/swift4/rxswiftLibrary/SwaggerClientTests/SwaggerClientTests/StoreAPITests.swift
- Commented out Swift 4 tests that failed due to bad data in the public petstore server
cc @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)
> Fix Swift4 CI tests

- CI/.drone.yml
- CI/circle_parallel.sh
- pom.xml
Test dart petstore client in CircleCI instead (using local petstore server to avoid bad data in the public server)
cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09) @athornz (2019/12) @amondnet (2019/12)
> Test Dart petstore client in CircleCI

- modules/openapi-generator/src/main/resources/python/api.mustache
- samples/client/petstore/python-asyncio/petstore_api/api/another_fake_api.py
- samples/client/petstore/python-asyncio/petstore_api/api/fake_api.py
- samples/client/petstore/python-asyncio/petstore_api/api/fake_classname_tags_123_api.py
- samples/client/petstore/python-asyncio/petstore_api/api/pet_api.py
- samples/client/petstore/python-asyncio/petstore_api/api/store_api.py
- samples/client/petstore/python-asyncio/petstore_api/api/user_api.py
- samples/client/petstore/python-tornado/petstore_api/api/another_fake_api.py
- samples/client/petstore/python-tornado/petstore_api/api/fake_api.py
- samples/client/petstore/python-tornado/petstore_api/api/fake_classname_tags_123_api.py
- samples/client/petstore/python-tornado/petstore_api/api/pet_api.py
- samples/client/petstore/python-tornado/petstore_api/api/store_api.py
- samples/client/petstore/python-tornado/petstore_api/api/user_api.py
- samples/client/petstore/python/petstore_api/api/another_fake_api.py
- samples/client/petstore/python/petstore_api/api/fake_api.py
- samples/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py
- samples/client/petstore/python/petstore_api/api/pet_api.py
- samples/client/petstore/python/petstore_api/api/store_api.py
- samples/client/petstore/python/petstore_api/api/user_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/another_fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/default_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/store_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
Fixes kwargs typos, removes E501s
Python Technical Committee
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) @spacether (2019/11)
> [Python] Fixes kwargs typos, removes E501s

- modules/openapi-generator/src/main/resources/typescript-inversify/modelGeneric.mustache
Added `| null` to model field where the swagger schema has the field marked as nullable
The samples were regenerated, but were not different as the petstore schema doesn't have any nullable fields
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)
> [typescript-inversify] Support nullable properties #5543

- CONTRIBUTING.md
Adding a link to the integration test page in the wiki.
> [DOC] Add link to integration test wiki in CONTRIBUTING.md

- modules/openapi-generator/src/main/resources/kotlin-client/api.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
The current kotlin client implementation was failing to upload files to the server.
This PR fixes that.
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11)
> [Kotlin][client] fix file upload

- modules/openapi-generator/src/main/resources/markdown-documentation/README.mustache
- modules/openapi-generator/src/main/resources/markdown-documentation/api.mustache
- modules/openapi-generator/src/main/resources/markdown-documentation/model.mustache
- samples/documentation/markdown/Apis/PetApi.md
- samples/documentation/markdown/Models/ApiResponse.md
- samples/documentation/markdown/Models/Category.md
- samples/documentation/markdown/Models/Order.md
- samples/documentation/markdown/Models/Pet.md
- samples/documentation/markdown/Models/Tag.md
- samples/documentation/markdown/Models/User.md
- samples/documentation/markdown/README.md
The `api.mustache` file generates links to the markdown model files.
These links were previously brokeen.
Additionally, the defaultPackage for markdown is "/Models", so this
looked pretty in the heading for model files. So this prefix has been
stripped from the header in `model.mustache`.
> [markdown] Fix broken links when generating markdown

- docs/generators/swift5.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/Swift5OptionsProvider.java
In my current project, I need to consume two different swagger servers.
The problem is that both of them generate an api class that have the same name.
Example: Both generator PetAPI.Swift
This is a problem because Swift doesn't have built in namespaces or packages, so it fails to compile if it has the came class defined more than once, and the same to the file name.
This also happen with same model objects, but with modelNamePrefix, I added a different prefix to the models of each server, and in that way the collisions would be avoided.
I propose to use the same solution that I used for models, but for the api classes, by adding apiNamePrefix.
This PR fixes https://github.com/OpenAPITools/openapi-generator/issues/5566.
@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah …
> [swift] add option for API prefix

- modules/openapi-generator/src/main/resources/scala-akka-client/apiInvoker.mustache
- samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/core/ApiInvoker.scala
Client code generated from scala-akka template does not attach specified body to PATCH requests.
This PR addresses the issue.
@clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03)
> Scala-Akka: Add missing body to PATCH requests

- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/api.mustache
- samples/server/petstore/jaxrs-cxf-cdi/pom.xml
- samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/PetApi.java
- samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/StoreApi.java
- samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/org/openapitools/api/UserApi.java
Add the cxf PATCH annotation to the imports so that the generated code
when defining a PATCH api compiles.
When using "patch" as verb in an openapi specification and the jaxrs-cxf-cdi generator, the generated code do not compile, as it is missing the PATCH annotation that is provided by cxf.
I added the required import, and now the generated code compiles and works fine.
> [jaxrs-cxf-cdi] Support PATCH httpMethod

- modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
Added Response interceptor for various reasons:
- logging
- extraction of header variables
to close #5501 
- [ x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, …
> Adding Response Interceptor

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
- samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/StoreApi.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/UserApi.ts
Implements interfaces for typescript-fetch, closes https://github.com/OpenAPITools/openapi-generator/issues/3478
The style from typescript-axios is followed
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)
> [typescript-fetch] add interfaces, withInterfaces

- samples/client/petstore/scala-akka/README.md
- samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/api/PetApi.scala
- samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/api/StoreApi.scala
- samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/api/UserApi.scala
Regenerated samples for completeness after contrib from #5605
> [scala] Regenerate akka sample

- samples/client/petstore/cpp-qt5/PetStore/PetApiTests.cpp
- samples/client/petstore/cpp-qt5/PetStore/StoreApiTests.cpp
- samples/client/petstore/cpp-qt5/PetStore/UserApiTests.cpp
Handle negative response from the server for the tests to avoid timeout errors
`cc`
@wing328 
@stkrwork @muttleyxd @MartinDelille @ravinikam
> [C++] [Qt5] CI Tests Handle negative response from the server

- samples/client/petstore/clojure/test/open_api_petstore/api/user_test.clj
- samples/client/petstore/go-experimental/user_api_test.go
- samples/client/petstore/go/user_api_test.go
- samples/client/petstore/php/OpenAPIClient-php/tests/UserApiTest.php
- samples/client/petstore/scala-httpclient/bin/UserApiTest.scala
- samples/client/petstore/scala-httpclient/src/test/scala/UserApiTest.scala
- samples/client/petstore/spring-cloud/src/test/java/org/openapitools/api/UserApiTest.java
- samples/client/petstore/typescript-angular-v6-provided-in-root/tests/default/src/test/api.spec.ts
- samples/client/petstore/typescript-angular-v7-provided-in-root/tests/default/src/test/api.spec.ts
- samples/openapi3/client/petstore/go-experimental/user_api_test.go
- samples/openapi3/client/petstore/go/user_api_test.go
- samples/openapi3/client/petstore/php/OpenAPIClient-php/tests/UserApiTest.php
Fix integration tests (Travis, CircleCI) due to change in the petstore server (updated a few days ago).
There are issues with the delete user operation. In the short/medium term, we'll switch to our own test servers instead.
> Fix integration tests (Travis, CircleCI)

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellExperimentalClientCodegen.java
fixes #5663 
The powershell-experimental generator runs into the below stackoverflow when the OAS spec has circular references. This happens while generating example strings.
```
[main] INFO  o.o.codegen.AbstractGenerator - writing file /home/vvb/sdk/powershell/src/PSOpenAPITools/Api/AaaApi.ps1
[main] INFO  o.o.codegen.AbstractGenerator - writing file /home/vvb/sdk/powershell/tests/AaaApi.Tests.ps1
[main] INFO  o.o.codegen.AbstractGenerator - writing file /home/vvb/sdk/powershell/docs/AaaApi.md
Exception in thread "main" java.lang.StackOverflowError
at java.lang.StringBuilder.append(StringBuilder.java:136)
at org.openapitools.codegen.languages.PowerShellExperimentalClientCodegen.constructExampleCode(PowerShellExperimentalClientCodegen.java:760)
at …
```
> [powershell-experimental] Protects against stackoverflow when OAS spec has circular references

- modules/openapi-generator/src/main/resources/powershell-experimental/api_client.mustache
- modules/openapi-generator/src/main/resources/powershell-experimental/configuration.mustache
This PR has the following changes,
1. Adds support for `SkipCertificateCheck` in Get/Set-Configuration. It is set to `$false` by default. It can be enabled to allow connection to a server with self-signed certificate.
2. Fixes an issue where cookie from configuration was not get consumed in ApiClient. 
3. Fix a minor typo.
/cc @wing328
> [powershell-experimental] Adds configuration option to skip certificate check

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/K6ClientCodegen.java
- modules/openapi-generator/src/main/resources/k6/licenseInfo.mustache
- samples/client/petstore/k6/script.js
A strange case appeared while testing the generator (when writing the blog post #5608) in variable conversion, so here's the fix.
> [k6] bugfixes to improve the output script

- pom.xml
Remove scala version in parent pom as seems like it's not used in the project.
Related: https://github.com/OpenAPITools/openapi-generator/pull/5618
cc @clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03)
> Remove scala version in parent pom

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientExperimentalCodegen.java
- modules/openapi-generator/src/main/resources/go-experimental/model.mustache
- modules/openapi-generator/src/main/resources/go-experimental/model_doc.mustache
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Apple.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/AppleReq.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Banana.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/BananaReq.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/GmFruit.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Whale.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Zebra.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_apple.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_apple_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_banana.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_banana_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_gm_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_mammal.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_whale.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_zebra.go
Rename from `x-basetype` to `x-go-base-type`
Also update Go (experimental) petstore samples (OAS3) 
> [Go][Experimental] Rename extensions from x-basetype to x-go-base-type

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientExperimentalCodegen.java
The http_signature_test.go is now manually generated. I missed removing http_signature_test.mustache from GoClientExperimentalCodegen.java in #5588.
> [Go][Experimental] Remove processing of http_signature_test.mustache

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
This extends the recently added oneOf support to also respect oneOf in properties, as reported at https://github.com/OpenAPITools/openapi-generator/issues/5382
CC @jimschubert who reviewed the original oneOf PR and this is a followup further improving that functionality (I tested this for both Java and go-experimental and both seem to work fine with this).
> Fix generation of oneOf interfaces for oneOf usage in properties

- modules/openapi-generator/src/main/resources/python/api_client.mustache
- modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache
- samples/client/petstore/python-asyncio/petstore_api/api_client.py
- samples/client/petstore/python-asyncio/petstore_api/rest.py
- samples/client/petstore/python-asyncio/tests/test_api_client.py
- samples/client/petstore/python-asyncio/tests/test_pet_api.py
- samples/client/petstore/python-asyncio/tests/util.py
From https://github.com/OpenAPITools/openapi-generator/pull/5094/ python clients expose api-client.close() method and the context manager. In this PR I added closing aiohttp.ClientSession there to allow users clean up objects in a more predictive way.
cc: @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) @spacether (2019/11)
Thank you reviewing and merging.
> [python/asyncio] explicitly close client session and asynchronous context manager

- modules/openapi-generator-gradle-plugin/README.adoc
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
Gradle Plugin was missing the option for the template engine to support handlebars. This adds the option and a unit test for validation.
Fixes #5685
> [gradle] Include engine option for handlebars generation

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/docs/default_api.md
- samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/mimetypes.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
Treat application/xml the same as text/xml as per RFC 7303 - https://tools.ietf.org/html/rfc7303
This fixes #5594 
- @frol
- @farcaller 
- @bjgill
> [Rust Server] Handle text/xml correctly

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
This changes the Kotlin Client to use `allVars` instead of `vars` for the data class properties.  `vars` only contains the immediate child properties, but `allVars` contains both inherited and child properties.
Related to #5211, #4707, #4705, #4453
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11)
To fix #5211
> [kotlin][client] Use allVars instead of vars for Kotlin client

- bin/utils/release_checkout.rb
> Fix SSL setting in checkout script

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
This PR includes:
- correct the function names to correct one as defined in model-body
- reformat base64decode function to avoid unnecessary malloc and assigning of the wrong length.
> [C] fix decode funtion

- bin/utils/release/bump.sh
This updates the release script to go from `-SNAPSHOT` to its next version automatically.
From 4.3.0-SNAPSHOT:
Then, from 4.3.0 to 4.3.1-SNAPSHOT:
When I (or anyone else) gets time, maybe we could add some bats tests for `bump.sh`.
cc @OpenAPITools/build
> Update bump.sh to go SNAPSHOT to version

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5AbstractCodegen.java
Removed unused vendor extension and warning
@wing328
> [C++] [Qt5] Remove warning for unused camel case vendor extension for Qt5 client

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache
- samples/client/petstore/c/include/apiClient.h
- samples/client/petstore/c/src/apiClient.c
The PR https://github.com/OpenAPITools/openapi-generator/pull/5140 has supported SSL server authentication, now this PR will support SSL client authentication.
> [C][Client] Support SSL client authentication for the c client

- modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
Attempt to fix #5247. The fix is applied by using the same logic as used in the Swift5 generator, which has been working correctly for us for these kinds of enums.
After testing on the example provided in issue #5247, the correct output is now a `String` instead of an invalid dataType for the enum.
Since I have very limited experience with the structure for templating, it would be good if the Kotlin technical committee could verify the assumptions that the templating used for Swift here is also relevant for Kotlin.
@jimschubert @dr4ke616 @Zomzog @andrewemery @4brunu
> [kotlin] Fix #5247 incorrect enum parameter type for arrays

- pom.xml
- samples/server/petstore/kotlin/vertx/pom.xml
Test failures in the CircleCI CI due to the following:
```
[ERROR] Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/verticle/PetApiVertxProxyHandler.kt: (12, 27) Class 'kotlinx.coroutines.GlobalScope' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/verticle/PetApiVertxProxyHandler.kt: (66, 13) Class 'kotlinx.coroutines.DisposableHandle' is compiled by a pre-release version of Kotlin …
```
> Comment out kotlin vertx server test to fix CI failure

- .travis.yml
- docs/usage.md
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/Constants.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/OpenAPIGenerator.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/BuildInfo.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/CompletionCommand.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/GenerateBatch.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/GlobalOptions.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/HelpCommand.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ListGenerators.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Meta.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/OpenApiGeneratorCommand.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Validate.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Version.java
- modules/openapi-generator/pom.xml
- pom.xml
* Introduce --version 
* Introduce --help ![image](https://user-images.githubusercontent.com/109659/77824664-bc25d980-70da-11ea-8f5c-b48ac15f209a.png)
* Add --sha to version command for short SHA display 
* Output Version and SHA details
* In new --version output, display repo and doc site
This adds image labels to store metadata on the online and cli docker
images, using standard labels:
* org.opencontainers.image.created
* org.opencontainers.image.revision
* org.opencontainers.image.title
* org.opencontainers.image.version
These can be inspected via 'docker inspect IMAGE_NAME' and may be useful
in tooling/automation or bug reports submitted by users.
For more details on these labels, see:
https://github.com/opencontainers/image-spec/blob/master/annotations.md
Useful pattern for …
> [cli][docker] Better expose version/sha information of builds

- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfiguratorUtils.java
-D option has been deprecated as it was previously used to:
* Pass "system properties"
* Pass additional properties
This was confusing because we already have --additional-properties and
because Java System Properties are passed as -D before program
arguments.
Confusion around the -D option had existed for some time, but when we
introduced the thread-safe GlobalSettings to avoid overwriting Java
System Properties, we created a hard break from Java System Properties
in the generator. This also disconnected the previous "system
properties" from accepting additional properties.
Once these newly deprecated methods are removed, we will have a clear
separation of concerns between:
* Java System Properties
* Global generator properties (used as workflow context)
* Additional properties (used as …
> [cli] Add --global-property for -D replacement

- modules/openapi-generator/src/main/resources/scala-akka-client/serializers.mustache
- samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/core/Serializers.scala
- samples/openapi3/client/petstore/scala-akka/src/main/scala/org/openapitools/client/core/Serializers.scala
scala-akka with default `java8` serializers won't compile due missed argument in match case 
@clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03)
> fix scala-akka java8 serializers

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
fixes #5796
Hello.
When using typescript-axios, a warning occurred in unused import.
I tried to fix it, so please take a look if you like.
<details><summary>Before/After</summary>
<p>
```typescript
// tslint:disable
/**
* My application
* My application
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { …
```
> [typescript-axios][client] Unnecessary imports occurs when using withSeparateModelsAndApi

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
Small enhancement to reduce the amount of logging when there is a large number of warning messages.
> [codegen] Use once(LOGGER) to reduce amount of identical warning messages

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/StringUtils.java
This is a follow-up to Jim's PR #5484. The cache parameters are configurable using system properties.
> [codegen] Make name cache configurable using system properties

- modules/openapi-generator/src/main/resources/python/python-experimental/model_utils.mustache
- samples/client/petstore/python-experimental/petstore_api/model_utils.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model_utils.py
* Improve documentation.
* Improve error message.
> [Python-experimental] Documentation enhancement for oneOf schema and minor err msg improvement

- modules/openapi-generator/src/main/resources/powershell-experimental/configuration.mustache
- Fix array return in Get-PSHostSetting
> [PS][Experimental] Fix array return

- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/pojo.mustache
When generating model that use allOf, the equals and hashCode methods
must take the parent class into account.
Current equals check will fail to detect a change in the inherited properties.
> [jaxrs-cxf-cdi] fix allOf equals and hashCode

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellExperimentalClientCodegen.java
- modules/openapi-generator/src/main/resources/powershell-experimental/model.mustache
- samples/client/petstore/powershell-experimental/src/PSPetstore/Client/PSConfiguration.ps1
> [PS][Experimental] use allVars to cover all properties

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/javascript/JavascriptClientCodegenTest.java
- Add default case to handle response code by throwing runtime exception as it shouldn't happen https://github.com/OpenAPITools/openapi-generator/compare/response_default?expand=1#diff-7cb46fa53f89a458a7b7cb201d2214a8R3322
- bug fix with "defaultResponse" (new value from parser)
> Add default case to handle response code

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Add `parent` for `allOf` only.
Otherwise, oneOf/anyOf class will also inherit from the class with a discriminator set in the spec.
> Add parent for allOf only

- modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-header.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/helpers-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/helpers-header.mustache
- samples/client/petstore/cpp-qt5/PetStore/main.cpp
- samples/client/petstore/cpp-qt5/client/PFXHelpers.cpp
- samples/client/petstore/cpp-qt5/client/PFXHelpers.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIHelpers.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIHelpers.h
Fixes #5708
`cc`
@DevASG
@stkrwork @MartinDelille @muttleyxd @ravinikam
> [C++] [Qt5] Updates to allow the setting of the dateTime format string

- modules/openapi-generator/src/main/resources/csharp/api.mustache
- samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientNetStandard/Org.OpenAPITools.sln
- samples/client/petstore/csharp/OpenAPIClientNetStandard/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientNetStandard/src/Org.OpenAPITools/Org.OpenAPITools.csproj
- samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/src/Org.OpenAPITools/Api/FakeApi.cs
Complex form parameters should be serialized as application/json
Reference: http://spec.openapis.org/oas/v3.0.3#special-considerations-for-multipart-content
In the last PR, there was another place to fix. 
https://github.com/OpenAPITools/openapi-generator/pull/5787
cc @mandrean @jimschubert @frankyjuang @shibayan
> [Csharp-client] Complex form parameters are not serialized as application/json

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellExperimentalClientCodegen.java
- add file post-processing to the PowerShell generator
> [PS] add file post-processing to the PowerShell generator

- modules/openapi-generator/src/main/resources/Java/JSON.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
- modules/openapi-generator/src/main/resources/Java/pom.mustache
- samples/client/petstore/java/jersey1/pom.xml
- samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/okhttp-gson/pom.xml
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/JSON.java
1. Add maven-compiler-plugin plugin to the pom.mustache template. This makes it possible to configure arguments for the compilation phase.
1. Set `-Xlint:all` argument by default in the pom.xml. This is used to identify linter warnings. These warnings should be fixed.
1. Fix warnings identified by linter in step 2.
1. Configure pom.xml to fork the java compiler and specify memory parameters. This helps to compile the generated code when the input OAS document is a big file.
> [Java-client] Add maven-compiler-plugin in pom.xml and enable linter checks by default

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
- modules/openapi-generator/src/main/resources/scala-sttp/apiInvoker.mustache
@clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)
> Fix Scala sttp generator packages

- modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
- modules/openapi-generator/src/main/resources/rust-server/client-operation.mustache
- modules/openapi-generator/src/main/resources/rust-server/lib.mustache
- modules/openapi-generator/src/main/resources/rust-server/models.mustache
- modules/openapi-generator/src/main/resources/rust-server/server-operation.mustache
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/multipart-v3/Cargo.toml
- samples/server/petstore/rust-server/output/multipart-v3/src/lib.rs
- samples/server/petstore/rust-server/output/no-example-v3/Cargo.toml
- samples/server/petstore/rust-server/output/no-example-v3/src/lib.rs
- samples/server/petstore/rust-server/output/openapi-v3/Cargo.toml
- samples/server/petstore/rust-server/output/openapi-v3/README.md
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/docs/default_api.md
- samples/server/petstore/rust-server/output/openapi-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/openapi-v3/examples/server/server.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
- samples/server/petstore/rust-server/output/ops-v3/Cargo.toml
- samples/server/petstore/rust-server/output/ops-v3/src/lib.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/models.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
- samples/server/petstore/rust-server/output/rust-server-test/Cargo.toml
- samples/server/petstore/rust-server/output/rust-server-test/src/lib.rs
Support complex query parameters by using the correct FromStr implementation and using ToString at all.
This enables support for definitions such as:
```
parameters:
- name: list-of-strings
in: query
schema:
type: array
items:
$ref: '#/components/schemas/StringObject'
```
This fix was contributed by @mirw and reviewed by myself on behalf of @Metaswitch.
- @frol
- @farcaller 
- @bjgill
> [Rust Server] Support complex query parameters

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
- modules/openapi-generator/src/main/resources/Java/pom.mustache
- samples/client/petstore/java/jersey1/pom.xml
- samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
- samples/client/petstore/java/okhttp-gson/pom.xml
When the input OAS document is large, the generated JSON.java file is large. The default javac stack size may not be sufficient, increasing to 4MiB.
> [Java] Increase java compiler stack size to handle large files

- CI/bitrise.yml
Update bitwise config (comment out run all script as it's causing timeout)
> Update bitwise config

- modules/openapi-generator/src/main/resources/Java/beanValidationCore.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/beanValidationCore.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/beanValidationCore.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/beanValidationCore.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/beanValidationCore.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/eap/beanValidationCore.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/beanValidationCore.mustache
- modules/openapi-generator/src/main/resources/JavaSpring/beanValidationCore.mustache
If using the property "exclusiveMaximum" on a decimal value in a spec, the java generators incorrectly generate the java bean validation annotation using the value for "exclusiveMinimum" instead. This should fix that issue.
- [] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`. 
> [Java] Fix inclusive maximum validation

- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
Add bearer auth support to csharp netcore client generator
To fix https://github.com/OpenAPITools/openapi-generator/issues/5915
cc @mandrean (2017/08), @jimschubert (2017/09) ❤️ @frankyjuang (2019/09) @shibayan (2020/02)
(no changes to the samples as fake petstore.yaml doesn't use bearer auth, will need to update it to cover bearer auth later)
> Add bearer auth support to csharp netcore client generator

- modules/openapi-generator/src/main/resources/dart2/api.mustache
- modules/openapi-generator/src/main/resources/dart2/api_client.mustache
- samples/client/petstore/dart2/petstore/test/fake_client.dart
- samples/client/petstore/dart2/petstore/test/pet_faked_client_test.dart
- samples/client/petstore/dart2/petstore/test/store_faked_client_test.dart
- samples/client/petstore/dart2/petstore/test/store_test.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/user_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api_client.dart
The current `Dart Client` does not require `ContentType` to specify `Content-type: application/json`, which is incorrect.  
There are two reasons.  
1. Specifying `Content-type: application/json` in `header` without declaration can be confusing.
2. There may be no RequestBody at all. In such case, I don't think `Content-type: application/json` is correct.
Therefore, if `ContentType` is not specified, `header` should not add `Content-type: application/json`  
@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09) @athornz (2019/12) @amondnet (2019/12)
> [Dart] Remove content type from header when content type is not specified

- modules/openapi-generator/src/main/resources/typescript-axios/package.mustache
- samples/client/petstore/typescript-axios/builds/es6-target/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version/package.json
Axios (version 0.18.0) used by typescript-axios generator is more than two years old (released in Feb 2018). Axios 0.19.2 released earlier this year contains a lot of fixes and functionality, I recommend updating to 0.19.x. Using an old axios version causes multiple axios versions to be installed - axios 0.18.0 used by typescript-axios client and a newer 0.19.x version used by other packages. 
@amakhrov, @petejohansonxo
> Update axios dependency to the new minor version 0.19.0

- modules/openapi-generator/src/main/resources/csharp-netcore/README.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/api_doc.mustache
Fixed README/doc generation after bearer support added by @wing328 #5921 for issue #5915
@mandrean (2017/08), @jimschubert (2017/09) heart @frankyjuang (2019/09) @shibayan (2020/02)
> fixed README/doc of bearer auth support for csharp-netcore

- modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Animal.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Category.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/FormatTest.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Pet.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/TypeHolderDefault.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/TypeHolderExample.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Animal.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Category.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/FormatTest.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Pet.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/TypeHolderDefault.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/TypeHolderExample.cs
Remove duplicated semi-colon in c# netcore models
To fix https://github.com/OpenAPITools/openapi-generator/issues/5927
cc @mandrean (2017/08), @jimschubert (2017/09) ❤️ @frankyjuang (2019/09) @shibayan (2020/02)
> Remove duplicated semi-colon in c# netcore models

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/main/resources/rust-server/example-client-main.mustache
- modules/openapi-generator/src/main/resources/rust-server/example-server-operation.mustache
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/multipart-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/multipart-v3/examples/server/main.rs
- samples/server/petstore/rust-server/output/multipart-v3/examples/server/server.rs
- samples/server/petstore/rust-server/output/no-example-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/no-example-v3/examples/server/main.rs
- samples/server/petstore/rust-server/output/no-example-v3/examples/server/server.rs
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/openapi-v3/examples/client/server.rs
- samples/server/petstore/rust-server/output/openapi-v3/examples/server/main.rs
- samples/server/petstore/rust-server/output/openapi-v3/examples/server/server.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
- samples/server/petstore/rust-server/output/ops-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/ops-v3/examples/server/main.rs
- samples/server/petstore/rust-server/output/ops-v3/examples/server/server.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/client/main.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/server/server.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
- samples/server/petstore/rust-server/output/rust-server-test/examples/client/main.rs
- samples/server/petstore/rust-server/output/rust-server-test/examples/server/main.rs
- samples/server/petstore/rust-server/output/rust-server-test/examples/server/server.rs
https://github.com/OpenAPITools/openapi-generator/issues/5906
Modification list
1. Fix generated code with Rust 1.39+ issue
```
help: use dyn: dyn Future<Item=CallbackWithHeaderPostResponse, Error=ApiError> + Send
error: trait objects without an explicit dyn are deprecated
--> output/openapi-v3/examples/server/server.rs:137:29
|
137 | context: &C) -> Box<Future<Item=CallbackWithHeaderPostResponse, Error=ApiError> + Send>
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use dyn: dyn Future<Item=CallbackWithHeaderPostResponse, Error=ApiError> + Send
|
= note: -D bare-trait-objects implied by -D warnings
error: trait objects without an explicit dyn are deprecated
--> output/openapi-v3/examples/server/server.rs:147:29
|
147 | context: &C) -> …
```
> [Rust Server] Fix #5906 (yaml with path parameter error)

- modules/openapi-generator/src/main/resources/python/python-experimental/signing.mustache
- samples/openapi3/client/petstore/python-experimental/petstore_api/signing.py
- samples/openapi3/client/petstore/python-experimental/tests/test_http_signature.py
ECDSA signatures can be encoded using raw binary or ASN.1 encoding. This PR uses the same ASN1 encoding as the go-experimental implementation.
Add hash algorithm parameter in the configuration.py for HTTP signatures.
The IETF is still actively working on the draft and I opened an issue with the IETF HTTP working group to clarify the encoding of ECDSA signatures.
> [Python-experimental] Use DER encoding for ECDSA signatures, add parameter to configure hash algorithm

- modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache
- samples/client/petstore/python-asyncio/petstore_api/rest.py
- samples/client/petstore/python-asyncio/tests/test_pet_api.py
API Client will fail if proxy parameters are passed. `aiohttp` raises `unexpected keyword argument 'proxy'` - `query()` method accepts them instead of the constructor.
Please review: @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) @spacether (2019/11)
> [python/asyncio] fix passing proxy parameters to aiohttp

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- modules/openapi-generator/src/main/resources/typescript-axios/configuration.mustache
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/default/configuration.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/configuration.ts
fixes #5952
Hello.
When I used cognito(authenticate server), I found it difficult to use typescript-client.
Therefore, I suggest the code.
> [typescript-axios][client] Allow apiKey type Promise.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaHttpServerCodegen.java
- modules/openapi-generator/src/main/resources/scala-akka-http-server/api.mustache
- samples/server/petstore/scala-akka-http-server/src/main/scala/org/openapitools/server/api/PetApi.scala
- samples/server/petstore/scala-akka-http-server/src/main/scala/org/openapitools/server/api/StoreApi.scala
- samples/server/petstore/scala-akka-http-server/src/main/scala/org/openapitools/server/api/UserApi.scala
Operations that should provide empty responses actually provided a response with an empty text/plain content. It's not the case anymore.
cc @clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)
> [scala-akka-http-server] Fix a generation problem on operations with empty responses

- modules/openapi-generator/src/main/resources/csharp-netcore/ClientUtils.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ClientUtils.cs
For GET-methods no Content-Type is required, since there is no body. This has been requested and discussed already at #476 and #1061. This is the dotnet-core implementation of it, since I only have the capabilities to do it for that right now. I came across an API that reacts differently depending on the content type, thats why I fixed this here.
@mandrean (2017/08), @jimschubert (2017/09) heart @frankyjuang (2019/09) @shibayan (2020/02)
> return a null instead of application/json when no content types are set

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
Fixes a regression reported here https://github.com/OpenAPITools/openapi-generator/issues/927 (although originally that was a broader issue, not just typescript-specific)
`allParents` is used by generators with multiple inheritance, e.g typescript and perl.
Earlier there was an attempt to bring `parent` and `allParents` in sync: https://github.com/OpenAPITools/openapi-generator/pull/5182
Turned out it's not a robust approach, as it had duplicated logic in two methods. And a later change un-synced the two methods again (https://github.com/OpenAPITools/openapi-generator/pull/5526/files#diff-57d7532cf464a8d7c24aab4b22ceb993R1138)
This PR eliminates logic duplication (well, to some degree) and simply appends `parent` to the list of `allParents` if it was not there yet.
Note that there is no …
> [typescript] Ensure `model.allParents` always includes `model.parent`.

- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
Fixes #5862.
---
The change to `CodegenConfigurator` looks more than it really is. I just pulled out everything that is related to actually _parse_ the file into a `synchronized` method to resolve the following concurrency issue: https://github.com/OpenAPITools/openapi-generator/issues/5862#issuecomment-611023874
I must say though, that the existing approach to mutate a singleton `ObjectMapper` seems rather dodgy.
Before my change, I was able to provoke the issue in my current project (which I am not allowed to share) after max. 30 mins via:
```
time while mvn -T2 …
```
> [maven] mark Mojo threadSafe=true + fix concurrency issue in CodegenConfigurator

- bin/csharp-dotnet2-petstore.sh
- bin/windows/csharp-dotnet2-petstore.bat
- modules/openapi-generator/src/main/resources/csharp-dotnet2/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-dotnet2/Configuration.mustache
- modules/openapi-generator/src/main/resources/csharp-dotnet2/README.mustache
- modules/openapi-generator/src/main/resources/csharp-dotnet2/api_doc.mustache
- samples/client/petstore/csharp-dotnet2/OpenAPIClientTest/Lib/OpenAPIClient/README.md
- samples/client/petstore/csharp-dotnet2/OpenAPIClientTest/Lib/OpenAPIClient/docs/PetApi.md
- samples/client/petstore/csharp-dotnet2/OpenAPIClientTest/Lib/OpenAPIClient/docs/StoreApi.md
- samples/client/petstore/csharp-dotnet2/OpenAPIClientTest/Lib/OpenAPIClient/docs/UserApi.md
- samples/client/petstore/csharp-dotnet2/OpenAPIClientTest/Lib/OpenAPIClient/src/main/CsharpDotNet2/Org/OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-dotnet2/OpenAPIClientTest/Lib/OpenAPIClient/src/main/CsharpDotNet2/Org/OpenAPITools/Client/Configuration.cs
- add bearer auth support to C# 2.0 client
@mandrean (2017/08), @jimschubert (2017/09) @frankyjuang (2019/09) @shibayan (2020/02)
> [C#][2.0] add bearer auth support to C# 2.0 client

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript-axios/gitignore
- modules/openapi-generator/src/main/resources/typescript-axios/npmignore
- samples/client/petstore/typescript-axios/builds/default/.gitignore
- samples/client/petstore/typescript-axios/builds/default/.npmignore
- samples/client/petstore/typescript-axios/builds/es6-target/.gitignore
- samples/client/petstore/typescript-axios/builds/es6-target/.npmignore
- samples/client/petstore/typescript-axios/builds/with-complex-headers/.gitignore
- samples/client/petstore/typescript-axios/builds/with-complex-headers/.npmignore
- samples/client/petstore/typescript-axios/builds/with-interfaces/.gitignore
- samples/client/petstore/typescript-axios/builds/with-interfaces/.npmignore
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/.gitignore
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/.npmignore
- samples/client/petstore/typescript-axios/builds/with-npm-version/.gitignore
- samples/client/petstore/typescript-axios/builds/with-npm-version/.npmignore
This pull requests fixes the issue described in https://github.com/OpenAPITools/openapi-generator/issues/3224 where the dist folder is not published when the ```npm publish``` command is run. This appears to be because the dist folder is included in the ```.gitignore```. This PR removes the ```dist``` entry from gitignore which ensures that the dist folder is included and that generated libraries can be safely published to npm etc.
fixes #3224
Without this fix, the generated library works when linked locally but not when published, ensuing in much confusion.
- Copying technical committee
CC @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo …
> [BUG] [TYPESCRIPT-AXIOS] Fixing issue where dist folder is not published when publishing typescript-axios generated client with npm publish

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- samples/client/petstore/python-experimental/docs/Child.md
- samples/client/petstore/python-experimental/docs/Parent.md
- samples/client/petstore/python-experimental/petstore_api/models/child.py
- samples/client/petstore/python-experimental/petstore_api/models/parent.py
This PR fixes [issue 5876](https://github.com/OpenAPITools/openapi-generator/issues/5876)
We are reverting the code back to the prior state to make it so
codegenModel.parentSchema, .parent, and parentModel return back to previous behavior for composed schemas.
@amakhrov this update changes result for the test testAllOfSingleRefWithOwnPropsNoDiscriminator which you added in https://github.com/OpenAPITools/openapi-generator/pull/5738
> Fixes issue 5876

- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/allOf_composition.yaml
Add more tests for parents, allParents
> Add tests for parents, allParents

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/component-deprecated.yml
We're using openapi-generator to generate models but we want to mark the deprecated ones as such. I realized that the `deprecated` attribute was not available for a model, so I'm adding that with this pull-request. This PR (https://github.com/OpenAPITools/openapi-generator/pull/5090) made it pretty easy but please let me know if I forgot something.
This is the follow-up of https://github.com/OpenAPITools/openapi-generator/issues/3358 which makes the deprecated attribute available to a model template.
> Expose `isDeprecated` variable to model template

- modules/openapi-generator/src/main/resources/mysql-schema/mysql_schema.mustache
- samples/schema/petstore/mysql/mysql_schema.sql
Database schema copied from [oauth2-server-php-mysql](https://github.com/dsquier/oauth2-server-php-mysql/) repo.
I can't say that I'm fully satisfied with mentioned schema. My complaints are:
* ~`oauth_users`.`password` column limited to 80 characters which can be not enough for future password encryption algorithms. In PHP docs [`password_hash`](https://www.php.net/manual/en/function.password-hash.php) recommended length is 255.~
* Schema doesn't set column collations. It's important for case-sensitive tokens(base64 e.g.). More info in submitted [issue](https://github.com/dsquier/oauth2-server-php-mysql/issues/12)
* It's not obvious that `oauth_users`.`username` is `user_id` mentioned in other tables. Maybe column comment can make it more clear.
Tables structure described in related …
> [mysql] Add OAuth2 framework tables

- README.md
Adding Allianz Technology, the service provider subsidiary of Allianz SE, as company who is using OpenAPI generator.
> Added Allianz Technolgy

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
A model import might clash with an operation when badly named. Append a "Operation" to the name to disambiguate and make the code compil.e
Closes #6002
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run …
> typescript-fetch: Escape operation-id if clashing with model names

- docs/generators/typescript-fetch.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
Some APIs have a model called "Index" which would create a file
"Index.ts" which would override "index.ts" on case-insensitive file
systems (e.g. macOS, some Windows versions). Make "Index" a reserved
word to prevent this clash.
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must …
> typescript-fetch: Make "Index" a reserved word

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
Fix APIs that return a map.
given the following schema (yaml) as the `application/json` body of an API:
```yaml
Foo:
type: object
$ref: '#/components/schemas/Bar'
```
The generator generated the wrong code that wouldn't transpile. This PR fixes that by handling maps the same way as we handle maps in other places.
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your …
> [typescript-fetch] Fix map API return type

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/docs/info_api.md
- samples/server/petstore/rust-server/output/openapi-v3/docs/repo_api.md
#5947  [BUG] [Rust Server] Generated code with yaml multi tag compile error.
- @frol
- @farcaller 
- @bjgill
> [Rust Server] Bugfix #5947 multi tag generate multi method issue.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GroovyClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaInflectorServerCodegen.java
Fix #6010
@bkabrda @Zomzog @lwlee2608 @karismann
> fix generate java-inflector crash issue on windows

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
So that it can be overridden with a custom behaviour.
> [Java][RestTempalte] Change access updateParamsForAuth to protected

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/main/resources/rust-server/example-client-main.mustache
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/multipart-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/no-example-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/openapi-v3/README.md
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/docs/info_api.md
- samples/server/petstore/rust-server/output/openapi-v3/docs/repo_api.md
- samples/server/petstore/rust-server/output/openapi-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/openapi-v3/examples/server/server.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
- samples/server/petstore/rust-server/output/ops-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/examples/client/main.rs
- samples/server/petstore/rust-server/output/rust-server-test/examples/client/main.rs
Fix #5948 (Generated client code "Disabled because there's no example")
> [Rust Server] Bugfix #5948 (Generated client code "Disabled because there's no example")

- modules/openapi-generator/src/main/resources/python/configuration.mustache
- samples/client/petstore/python-asyncio/petstore_api/configuration.py
- samples/client/petstore/python-experimental/petstore_api/configuration.py
- samples/client/petstore/python-tornado/petstore_api/configuration.py
- samples/client/petstore/python/petstore_api/configuration.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/configuration.py
- samples/openapi3/client/petstore/python/petstore_api/configuration.py
To initialize the configuration, developers can write the following code:
```python
configuration = Configuration(
host = "http://example.com",
configuration.signing_info = openapi.HttpSigningConfiguration(
signing_scheme = intersight.signing.SCHEME_RSA_SHA256,
...
)
)
```
Or, for whatever reason, they can first create the config object, then assign the signing info:
```python
configuration = Configuration(
host = "http://example.com"
)
...
configuration.signing_info = openapi.HttpSigningConfiguration(
signing_scheme = intersight.signing.SCHEME_RSA_SHA256,
...
)
```
In the first case, the host parameter is automatically passed from the Configuration object to the HttpSigningConfiguration. In the second case, the HttpSigningConfiguration.host was None. This PR fixes the problem for the …
> [Python experimental] Add __setattr__ function to ensure signing_info.host is the same as configuration.host when the user assigns signing info

- modules/openapi-generator/src/main/resources/cpp-qt5-client/model-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/model-header.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/model-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/model-header.mustache
- samples/client/petstore/cpp-qt5/client/PFXApiResponse.cpp
- samples/client/petstore/cpp-qt5/client/PFXApiResponse.h
- samples/client/petstore/cpp-qt5/client/PFXCategory.cpp
- samples/client/petstore/cpp-qt5/client/PFXCategory.h
- samples/client/petstore/cpp-qt5/client/PFXOrder.cpp
- samples/client/petstore/cpp-qt5/client/PFXOrder.h
- samples/client/petstore/cpp-qt5/client/PFXPet.cpp
- samples/client/petstore/cpp-qt5/client/PFXPet.h
- samples/client/petstore/cpp-qt5/client/PFXTag.cpp
- samples/client/petstore/cpp-qt5/client/PFXTag.h
- samples/client/petstore/cpp-qt5/client/PFXUser.cpp
- samples/client/petstore/cpp-qt5/client/PFXUser.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIApiResponse.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIApiResponse.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAICategory.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAICategory.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIOrder.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIOrder.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIPet.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIPet.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAITag.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAITag.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIUser.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/models/OAIUser.h
Fixes #6014
@stkrwork @ravinikam @MartinDelille @muttleyxd
> [C++] [Qt5] Export valid and set status of properties

- modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.cpp.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.h.mustache
- samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp
- samples/client/petstore/cpp-qt5/client/PFXHttpRequest.h
Fixes #6018
@ravinikam @stkrwork @MartinDelille @muttleyxd
> [C++] [Qt5] Export response code to worker

- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/allOf_composition.yaml
Add tests for allOf without object type in line schema to ensure there's no inheritance.
> Add test for allOf without object type

- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
> Add input flag for Gradle openApiGenerate task

- modules/openapi-generator-maven-plugin/examples/spring.xml
- modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
- samples/openapi3/client/petstore/go/go-petstore/README.md
- samples/openapi3/client/petstore/go/go-petstore/api/openapi.yaml
- samples/openapi3/client/petstore/go/go-petstore/api_fake.go
- samples/openapi3/client/petstore/go/go-petstore/docs/FakeApi.md
- samples/openapi3/client/petstore/php/OpenAPIClient-php/README.md
- samples/openapi3/client/petstore/php/OpenAPIClient-php/docs/Api/FakeApi.md
- samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/openapi3/client/petstore/php/OpenAPIClient-php/test/Api/FakeApiTest.php
- samples/openapi3/client/petstore/python/README.md
- samples/openapi3/client/petstore/python/docs/FakeApi.md
- samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/configuration.py
- samples/openapi3/client/petstore/ruby-faraday/README.md
- samples/openapi3/client/petstore/ruby-faraday/docs/FakeApi.md
- samples/openapi3/client/petstore/ruby-faraday/lib/petstore/api/fake_api.rb
- samples/openapi3/client/petstore/ruby-faraday/spec/api/fake_api_spec.rb
- samples/openapi3/client/petstore/ruby/README.md
- samples/openapi3/client/petstore/ruby/docs/FakeApi.md
- samples/openapi3/client/petstore/ruby/lib/petstore/api/fake_api.rb
- samples/openapi3/client/petstore/ruby/spec/api/fake_api_spec.rb
- samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/FakeApi.java
- samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/FakeApiService.java
- samples/server/petstore/jaxrs-jersey/src/main/java/org/openapitools/api/impl/FakeApiServiceImpl.java
- Add Http signature authentication test to fake petstore spec
- fix plugin version in modules/openapi-generator-maven-plugin/examples/spring.xml
> Add Http signature authentication test to fake petstore spec

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
deepObject query parameters need to be specially marshalled.
Unfortunately, they're quite tricky to distinguish in mustache because
there's no boolean property for deepObject, so add a vendorExtension
property to ease the mustache template.
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and …
> [typescript-fetch] Support deepObject query params

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
Check "typeof FormData" first. This allows the code to also work in
nodejs with isomorphic-fetch.
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, …
> [typescript-fetch] Make FormData optional

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/serializer/SerializerUtils.java
There are cases where minimizing quotes results in invalid YAML. For example, an input YAML with string "1234_1234" will be converted to YAML value 1234_1234 which is an int in YAML 1.1 (https://yaml.org/type/int.html)
The only option in these cases is to either:
* Revert the option completely to always quote values
* Provide a user-customization to disable quotes minimization
This applies the latter with the assumption that this is an edge case and users who are unaffected will default to the "prettier" version.
An alternative would be to write a custom serializer for strings, and if they are in the format of of any of the valid formats defined in YAML:
```
[-+]?0b[0-1_]+ # (base 2)
|[-+]?0[0-7_]+ # (base 8)
|[-+]?(0|[1-9][0-9_]*) # (base 10)
|[-+]?0x[0-9a-fA-F_]+ # (base 16) …
```
> [feat] Allow configuration of yaml minimize quotes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
- modules/openapi-generator/src/main/resources/typescript-fetch/modelEnum.mustache
- modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
- modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache
- samples/client/petstore/typescript-fetch/builds/default/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/default/apis/StoreApi.ts
- samples/client/petstore/typescript-fetch/builds/default/apis/UserApi.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/apis/StoreApi.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/apis/UserApi.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/StoreApi.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/UserApi.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/apis/StoreApi.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/apis/UserApi.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/apis/StoreApi.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/apis/UserApi.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/StoreApi.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/UserApi.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/apis/StoreApi.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/apis/UserApi.ts
Add a lambda that formats the documentation correctly even if it
contains newlines. The generated docs with typedoc looks a lot better
and also renders Markdown correctly.
Also remove the "no description" fallback for APIs because we don't have
it anywhere else, other generators don't generate a default fallback and
I'd rather have no documentation than a "no description" string.
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts …
> [typescript-fetch] Allow multiline documentation

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
While generating a **typescript-axios** client, **pattern** property gets improperly escaped, resulting in a non-valid regular expression. This seems to be caused by `toRegularExpression(String pattern)`method calling `escapeText(String input)`: overriding the method for `TypeScriptAxiosClientCodegen` and removing _escapeText()_ call fixes it.
- Fixes #5973
> [typescript-axios] fixed pattern data integrity

- modules/openapi-generator/src/main/resources/typescript-angular/README.mustache
- samples/client/petstore/typescript-angular-v2/default/README.md
- samples/client/petstore/typescript-angular-v2/npm/README.md
- samples/client/petstore/typescript-angular-v2/with-interfaces/README.md
- samples/client/petstore/typescript-angular-v4.3/npm/README.md
- samples/client/petstore/typescript-angular-v4/npm/README.md
- samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v7-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/README.md
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-prefixed-module-name/README.md
> [TypeScript-Angular] Add AuthService example to  README.md

- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OpenApiEvaluator.java
The specification requires that tags are unique. This isn't caught by swagger-parser, so we will issue a warning if duplicate tag names are found.
Example:
```
openapi-generator validate -i .bak/petstore.yaml
Validating spec (.bak/petstore.yaml)
Warnings:
- Duplicated tags: user
[info] Spec has 1 recommendation(s).
```
> [validation] Warn on duplicate tags

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/AbstractOpenApiSchema.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/ApiResponse.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/JSON.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/apiException.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/oneof_model.mustache
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/ApiResponse.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/api/DefaultApi.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- better docstring for Java jersey2-experimental client
> [Java][jersey2-experimental] better docstring for Java jersey2-experimental client

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/any_type.yaml
- modules/openapi-generator/src/test/resources/3_0/issue796.yaml
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/User.md
- Better "Any Type" support by introducing "AnyType", which is mapped to "oas_any_type_not_mapped" by default.
- minor fix to isFreeFormObject check
- removed commented code
> Better "Any Type" support

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/model-deprecated.yaml
As $ref is supposed to completely replace the definition of a property,
make sure we also include the 'deprecated' property when generating the
type of a $ref property.
This makes a property $ref'ing a deprecated schema also become deprecated.
> Propagate deprecated property through $ref's

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- modules/openapi-generator/src/main/resources/dart-dio/apilib.mustache
- modules/openapi-generator/src/main/resources/dart-dio/auth/api_key_auth.mustache
- modules/openapi-generator/src/main/resources/dart-dio/auth/auth.mustache
- modules/openapi-generator/src/main/resources/dart-dio/auth/basic_auth.mustache
- modules/openapi-generator/src/main/resources/dart-dio/auth/oauth.mustache
- modules/openapi-generator/src/main/resources/dart-dio/pubspec.mustache
- modules/openapi-generator/src/main/resources/dart-dio/serializers.mustache
- samples/client/petstore/dart-dio/lib/api.dart
- samples/client/petstore/dart-dio/lib/api/pet_api.dart
- samples/client/petstore/dart-dio/lib/api/store_api.dart
- samples/client/petstore/dart-dio/lib/api/user_api.dart
- samples/client/petstore/dart-dio/lib/auth/api_key_auth.dart
- samples/client/petstore/dart-dio/lib/auth/auth.dart
- samples/client/petstore/dart-dio/lib/auth/basic_auth.dart
- samples/client/petstore/dart-dio/lib/auth/oauth.dart
- samples/client/petstore/dart-dio/lib/serializers.dart
- samples/client/petstore/dart-dio/pubspec.yaml
fix https://github.com/OpenAPITools/openapi-generator/issues/6044
fix https://github.com/OpenAPITools/openapi-generator/issues/6026
cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09) @athornz (2019/12) @amondnet (2019/12)
> dart-dio improvements 

- modules/openapi-generator/src/main/resources/dart2/enum.mustache
> Add listFromJson method to fix #4887

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp/OpenAPIClientNet35/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientNet40/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientNet40/src/Org.OpenAPITools/Model/FormatTest.cs
- samples/client/petstore/csharp/OpenAPIClientNetCoreProject/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientNetCoreProject/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientNetStandard/Org.OpenAPITools.sln
- samples/client/petstore/csharp/OpenAPIClientNetStandard/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientNetStandard/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientNetStandard/src/Org.OpenAPITools/Org.OpenAPITools.csproj
- samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientWithPropertyChanged/src/Org.OpenAPITools/Model/FormatTest.cs
Fixes an issue where the enum type is not properly treated as nullable.
Fixed #5442
> [csharp-netcore] Fixed handling of nullable enum values

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaClientCodegen.java
- modules/openapi-generator/src/main/resources/scala-akka-client/api.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/apiInvoker.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/apiRequest.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/apiSettings.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/model.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/requests.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/api.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/apiInvoker.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/model.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/requests.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/scalaakka/ScalaAkkaClientCodegenTest.java
Default setting for mainPackage is `org.openapitools.client`  and it will be always next values for:
`api = mainPackage + .api`
`invoker = mainPackage + .invoker`
`model = mainPackage + .model`
There is a cases when i want to define all of 3 properties explicitly ( sbt-plugin / gradle-plugin ) or to have custom values. 
This fix allows to apply explicitly every property and combine with `mainPackage` when applicable
https://github.com/OpenAPITools/openapi-generator/issues/6128
@clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)
> [scala][akka-http] fix non-default packages for api, model and invoker

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
> [codegen] Improve documentation, fix typos

- modules/openapi-generator/src/main/resources/go/client.mustache
Fixed parsing for file return type in golang
> File return type fix

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
A follow-up PR for https://github.com/OpenAPITools/openapi-generator/pull/6025#discussion_r416632520
cc @jimschubert, @frankyjuang, @shibayan
> Skip web.config generation for aspnetcore 3.x

- docs/generators.md
- docs/generators/typescript.md
- modules/openapi-generator/src/main/resources/typescript/generators/fetch-api.mustache
- modules/openapi-generator/src/main/resources/typescript/generators/jquery.mustache
- samples/client/petstore/typescript/builds/default/index.ts
- samples/client/petstore/typescript/builds/jquery/index.ts
- samples/client/petstore/typescript/tests/default/test/api/PetApi.test.ts
- samples/client/petstore/typescript/tests/default/test/auth/auth.test.ts
- samples/client/petstore/typescript/tests/default/test/http/isomorphic-fetch.test.ts
- samples/client/petstore/typescript/tests/default/test/models/ObjectSerializer.test.ts
- samples/client/petstore/typescript/tests/jquery/test/api/PetApi.test.ts
- samples/client/petstore/typescript/tests/jquery/test/http/jquery.test.ts
As discussed in #802, this PR moves all exported classes and objects of the refactored ts-generator to the top-level.
@bodograumann Did I miss anything?
> [TS-Refactor] Top-level exports for fetch & jquery

- modules/openapi-generator/src/main/resources/markdown-documentation/README.mustache
Shows operation `description` when `summary` is missing.
Closes #6103 
cc @jimschubert
> [markdown] Show description when summary is missing

- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
Fixes issue: https://github.com/OpenAPITools/openapi-generator/issues/6157
@wing328 @UkonnRa @joerg-wille
> Fix #6157: Updated native template to fix null async return

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
With the recent changes for AnyType, there are cases where csharp-netcore generates AnyType but does not define it. This PR adds a typeMapping for `AnyType` to `Object` type.
/cc @wing328 @jimschubert
> [csharp-netcore] adds the missing typeMapping for AnyType

- modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.cpp.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.h.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache
- samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp
- samples/client/petstore/cpp-qt5/client/PFXHttpRequest.h
- samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXPetApi.h
- samples/client/petstore/cpp-qt5/client/PFXStoreApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXStoreApi.h
- samples/client/petstore/cpp-qt5/client/PFXUserApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXUserApi.h
Problem:
Every api call created new connection to server. It happens because _OAIHttpRequestWorker_ creates new _QNetworkAccessManager_ every time.
Solution:
Passing _QNetworkAccessManager_ as parameter. It allows QT reusing an opened early connection if it possible (if server support keep alive connections and if there is no active request).
This change is optional and should not affect existing code.
Also I change connect to signal _QNetworkReply::finished_ instead of _QNetworkAccessManager::finished_. 
@ravinikam  @stkrwork @etherealjoy  @martindelille  @muttleyxd
> [cpp][Qt5] Add the ability to pass QNetworkAccessManager as a parameter 

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
Without the AnyType type mapping, the generated dart code uses `AnyType` instead of  `Object`, which does not compile. I based this on changes to other languages I saw in the PR for #6091 by @wing328  .
@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09) @athornz (2019/12) @amondnet (2019/12)
> [dart-dio] Add missing AnyType type mapping

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- pom.xml
- samples/server/petstore/rust-server/output/openapi-v3/docs/ObjectUntypedProps.md
- samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
- Map "AnyType" in rust server generator
cc @richardwhiuk
> Map "AnyType" in rust server generator

- docker-entrypoint.sh
PR to go with issue https://github.com/OpenAPITools/openapi-generator/issues/6206 to stop `unbound variable` errors when running docker-entrypoint.sh without an argument.
> [Docker] Added a check to make sure an argument is passed

- bin/ci/php-silex-petstore-server.json
- bin/openapi3/php-silex-petstore-server.sh
- bin/php-silex-petstore-server.sh
- bin/windows/php-silex-petstore-server.bat
- docs/generators.md
- docs/generators/php-silex-deprecated.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSilexServerCodegen.java
[Silex](https://packagist.org/packages/silex/silex) package has been abandoned:
> This package is **abandoned** and no longer maintained. The author suggests using the [symfony/flex](https://packagist.org/packages/symfony/flex) package instead.
> **WARNING**: Silex is in maintenance mode only. Ends of life is set to June 2018. Read more on [Symfony's blog](https://symfony.com/blog/the-end-of-silex).
Closes #6203 
cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @renepardon
> Mark Silex server generator as deprecated

- modules/openapi-generator/src/main/resources/JavaInflector/inflector.mustache
java-inflector references wrong openapi file (swagger.yaml)
> Fix java-inflector to reference the correct openapi.yaml file

- modules/openapi-generator/src/main/resources/csharp-netcore/ClientUtils.mustache
Using a generated .NET Core client from an application with a locale that formats numbers with a comma as a decimal separator will make the client send invalid numeric parameters to the API. Any numeric parameter with decimals will added to the URL with a comma ('0,15' instead of '0.15'), potentially breaking the API integration.
In my specific use case, the API interpreted '0,15' as '15', resulting in pretty funky errors.
This commit ensures that parameters are parsed with the invariant culture, fixing the mentioned error.
> Fix locale issue for numeric string conversions

- docs/usage.md
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java
- modules/openapi-generator-gradle-plugin/README.adoc
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
fix #6210
Remove an extra closing curly bracket in the example of the `--http-user-agent` generate option.
I updated the files manually, none of them seemed to be auto-generated.
This is my first contribution so let me know if I missed something. I didn't update any Petstore samples because I don't think they are affected.
> Remove extra bracket in --http-user-agent example.

- modules/openapi-generator/src/main/resources/Java/StringUtil.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/auth/OAuth.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2-experimental/pom.mustache
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/feign10x/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/google-api-client/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/jersey1/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/jersey2-experimental/pom.xml
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/jersey2-experimental/src/main/java/org/openapitools/client/auth/OAuth.java
- samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/retrofit/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/retrofit2-play24/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/retrofit2-play25/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/retrofit2rx/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/StringUtil.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/StringUtil.java
Add full OAuth2 support to jersey2-experimental codegen.
The scribejava lib is used (instead of OLTU for other generators which is deprecated)
Features:
- Client Credentials, Authorization code, Password flows
- Automatic refresh using the refresh token if possible
- Automatic renewal of access token
- Helper methods to configure the client
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)
> Add full OAuth2 support to jersey2-experimental codegen

- modules/openapi-generator/src/main/resources/python/python-experimental/model_utils.mustache
- modules/openapi-generator/src/test/resources/3_0/python-experimental/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
- samples/client/petstore/python-experimental/petstore_api/model_utils.py
- samples/openapi3/client/petstore/python-experimental/docs/Apple.md
- samples/openapi3/client/petstore/python-experimental/docs/Fruit.md
- samples/openapi3/client/petstore/python-experimental/docs/GmFruit.md
- samples/openapi3/client/petstore/python-experimental/petstore_api/model_utils.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/models/apple.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/models/fruit.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/models/gm_fruit.py
- samples/openapi3/client/petstore/python-experimental/test/test_fruit.py
- samples/openapi3/client/petstore/python-experimental/test/test_gm_fruit.py
- samples/openapi3/client/petstore/python-experimental/tests/test_deserialization.py
1. Add unit tests for regex pattern and regex flags.
1. Improve error message when payload does not match regex pattern from OAS document.
> [python-experimental] Improve error message for regex matching, add unit tests.

- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
- samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
Fixes #6218
`Changes`
- Handle all types inserted in the header generically. 
- Remove pointer checks which is invalid as all types are passed are never passed as pointers anymore since 4.0
`cc`
@ravinikam @stkrwork @MartinDelille @muttleyxd 
@wunt
> [C++] [Qt5] Fix datatypes in headers other than strings

- docs/generators/README.md
Tiny change. There are no deprecated generators in that doc. I've deleted Silex too.
> Remove Silex link from doc

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/AbstractOpenApiSchema.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/anyof_model.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/oneof_model.mustache
- samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-java6/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- Add null type support to oneOf/anyOf
- tested locally with a spec using oneOf and "type: null"
To fix https://github.com/OpenAPITools/openapi-generator/issues/6257
> [Java][jersey2] Add null type support to oneOf/anyOf

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/AbstractOpenApiSchema.mustache
Simple fix to use the proper tag in a mustache template. The package name of the ApiException class should not be hard-coded.
> [Java jersey2] Mustache template should use invokerPackage tag to generate import

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
- modules/openapi-generator/src/main/resources/go-experimental/model_anyof.mustache
- modules/openapi-generator/src/main/resources/go-experimental/model_oneof.mustache
- Add null type support to Go (experimental) oneOf/anyOf schemas
- Tested locally and no issue found so far
> Add null type support to Go (experimental) oneOf/anyOf schemas

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
> [Java] Add composed schema check when constructing the default value

- modules/openapi-generator/src/main/resources/dart2/enum.mustache
Just create a toJson method for enum serialization. As you can see on: https://github.com/OpenAPITools/openapi-generator/issues/4157#issuecomment-621370059 :
On the version 4.3.1 the serialize function delegate on dart convert library json.encode(). It return an error because serializing this enums because the enum is not "encodable" (is not a number, boolean, string, null, list or a map), so the encode() method looks for a toJson() on the Object passed:
```dart
/// If [toEncodable] is omitted, it defaults to a function that returns the
/// result of calling `.toJson()` on the unencodable object.
```
So I implemented this method on the template.
> Fix  #4157 dart enum toJson method 

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- samples/client/petstore/dart-dio/lib/api/pet_api.dart
- samples/client/petstore/dart-dio/lib/api/store_api.dart
- samples/client/petstore/dart-dio/lib/api/user_api.dart
Dio supports using callbacks to report send/recv progress. This PR adds the ability to pass those callbacks as parameters to api method.
@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09) @athornz (2019/12) @amondnet (2019/12)
> [dart-dio][client] Allow passing progress callbacks through client methods.

- modules/openapi-generator/src/test/resources/3_0/petstore.yaml
- samples/client/petstore/lua/petstore/api/user_api.lua
- samples/openapi3/client/petstore/scala-sttp/README.md
- samples/openapi3/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/UserApi.scala
Remove cookie authentication from petstore.yaml (oas3.0) as it's for testing purposes only.
> Remove cookie authentication from petstore.yaml (oas3.0)

- docs/generators/typescript.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript/README.mustache
- modules/openapi-generator/src/main/resources/typescript/package.mustache
- samples/client/petstore/typescript/builds/default/README.md
- samples/client/petstore/typescript/builds/jquery/README.md
- Added basic README
- Added NPM Version, Repository and Name switch
CC @bodograumann
> [TS-Refactor] Added options for npm version, repository, name and updated readme

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.sbt.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pom.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/vertx/build.gradle.mustache
- samples/client/petstore/java/jersey2-java7/build.gradle
- samples/client/petstore/java/jersey2-java7/build.sbt
- samples/client/petstore/java/jersey2-java7/pom.xml
- samples/client/petstore/java/jersey2-java8/build.gradle
- samples/client/petstore/java/jersey2-java8/build.sbt
- samples/client/petstore/java/jersey2-java8/pom.xml
- samples/client/petstore/java/vertx/build.gradle
Fix build.gradle in some Java clients due to missing dependencies.
Tested locally. I'll update the CI to catch these issues moving forward.
> Fix build.gradle in some Java clients

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java7/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
Make it possible to set `serverIndex` to `null`. This is useful when one wants to use the `ApiClient` to send a custom request with URL that doesn't map to generated operation URLs. This was possible in 4.3.1, but regressed in 5.0 snapshot - this PR fixes it.
> [Java][jersey2] Allow setting serverIndex to null

- modules/openapi-generator/src/main/resources/swift5/api.mustache
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
With the PR https://github.com/OpenAPITools/openapi-generator/pull/6336 the openapi3 deprecated attribute was introduced.
This PR improved the openapi3 deprecated attribute when used together with the Combine framework.
> [swift] improve deprecated APIs when using the Combine framework

- modules/openapi-generator/src/main/resources/go-experimental/model_oneof.mustache
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_mammal.go
This PR adds a convenience wrapper function to make it easier to work with oneOf members.
> [go-experimental] Add convenience wrapper function for oneOf members

- modules/openapi-generator/src/main/resources/go-experimental/model_enum.mustache
- samples/client/petstore/go-experimental/go-petstore/model_enum_class.go
- samples/client/petstore/go-experimental/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_enum_class.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_default_value.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer_default_value.go
This new unmarshalling method for enums ensures that unmarshalling fails if the value is not in the enumeration choices. As the enum type is just a type alias in go, technically any value of the base type can actually be assigned to it - this patch prevents that at least on unmarshalling.
This allows to properly deserialize `oneOf` members that have a common field that has specific distinct choices for each of the members. For example:
* `A` and `B` are members of `oneOf` and both have a `foo`
* For `A`, `foo` is an enum with allowed choices `a`, `A`
* For `B`, `foo` is an enum with allowed choices `b`, `B`
* The rest of the fields is potentially the same.
Having this new unmarshalling method ensures that entity with `foo: b` can't get deserialized as `A`, but only as `B`, hence the …
> [go-experimental] Ensure enum deserialization checks enum values

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
Array of objects translate to **map[string,object][]** and they fail to deserialize. This is because the deserialization does not parse the mapping string correctly. A quick fix is moving array deserialization before object deserialization.
```
ObjectExample:
type: object
properties:
data:
type: array
items:
type: object
additionalProperties: true
```
@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon
> [PHP] ObjectSerializer fix for array of objects

- modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirouter.h.mustache
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/handlers/OAIApiRouter.h
[C++] [Qt5] [Server] [Bug] fixed Incomplete Read JSON #6342
Emit signal ```requestReceived``` only after request content is entirely received.
Fixes #6342
cc
> [C++] [Qt5] [Server] read json

- modules/openapi-generator/src/main/resources/go-experimental/model_enum.mustache
- modules/openapi-generator/src/main/resources/go-experimental/model_oneof.mustache
- samples/client/petstore/go-experimental/go-petstore/model_enum_class.go
- samples/client/petstore/go-experimental/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_enum_class.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_mammal.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_default_value.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer_default_value.go
- Reset to nil with multiple matches in oneOf
- replace 4-spaces with tabs
> [Go][Experimental] Reset to nil with multiple matches in oneOf

- modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache
- samples/client/petstore/typescript-rxjs/builds/default/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts
This reverts (by improving) a change by @denyo in #4250, which I spoke to him in [the review comment](https://github.com/OpenAPITools/openapi-generator/pull/4250#pullrequestreview-395647328). In my opinion, if this change is accepted, it should be adopted by the rest of typescript templates.
- previously clone() and its clients in the BaseAPI class were generic
- with removal of the generic argument, these methods became unavailable
to the API classes inheriting from BaseAPI
- original generic was imprecise, as these are not statics
- return type of `this` is the correct notation
Additionally, @denyo [requested](https://github.com/OpenAPITools/openapi-generator/pull/6001#discussion_r412200918) I add some of the changes he has PRed in #5465 to avoid future conflict. I agree with the …
> [typescript-rxjs] restore prototype inheritance for clone & its clients

- modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirequest.cpp.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-qhttpengine-server/apirequest.h.mustache
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIPetApiRequest.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIPetApiRequest.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIStoreApiRequest.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIStoreApiRequest.h
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIUserApiRequest.cpp
- samples/server/petstore/cpp-qt5-qhttpengine-server/server/src/requests/OAIUserApiRequest.h
Change helper method ```writeResponseHeaders``` implementation to just set the headers, instead of write them, and also rename the method to ```setSocketResponseHeaders```, to maintain the new semantic.
The implementation of ```QHttpEngine::Socket::write``` or ```QHttpEngine::Socket::writeJson``` implementations will call ```Socket::writeData``` that writes the Headers and Status Code before write the content if they are not already written.
If these methods are not called (e.g.: empty reply), we could set the headers just before close the socket.
Fixes #6344
cc
> [C++] [Qt5] Fixed missing headers and wrong status code

- modules/openapi-generator/src/main/resources/go-experimental/model_anyof.mustache
- modules/openapi-generator/src/main/resources/go-experimental/model_oneof.mustache
- modules/openapi-generator/src/main/resources/go-experimental/model_simple.mustache
- modules/openapi-generator/src/main/resources/go-experimental/nullable_model.mustache
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_gm_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_mammal.go
This change ensures that `oneOf` and `anyOf` have their respective `Nullable<Model>` structures defined. These are necessary when the model is used as nullable.
> [go-experimental] Ensure that all oneOf/anyOf models have their Nullable<Model> defined

- modules/openapi-generator/src/main/resources/r/README.mustache
- modules/openapi-generator/src/main/resources/r/api.mustache
- modules/openapi-generator/src/main/resources/r/description.mustache
- samples/client/petstore/R/DESCRIPTION
- samples/client/petstore/R/R/pet_api.R
- samples/client/petstore/R/R/store_api.R
- samples/client/petstore/R/R/user_api.R
- samples/client/petstore/R/README.md
- samples/client/petstore/R/test_petstore.bash
Replacing caTools with base64enc library
As the caTools has recently upgraded to new version and it is now not available for R versions less than 3.6.1, which is causing installation errors of the R generator on lower R versions.
@wing328  @saigiridhar21
> replacing caTools dependency with base64enc

- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
- Add pub to struct when using the single parameter option
cc @frol (2017/07) @farcaller (2017/08) @bjgill (2017/12) @richardwhiuk (2019/07) @paladinzh (2020/05)
> [rust][reqwest] Add pub to struct when using the single parameter option

- modules/openapi-generator/src/main/resources/go-experimental/model_oneof.mustache
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_mammal.go
The `MarshalJSON` method has to be defined on a non-pointer receiver, otherwise serializing non-pointer oneOf structures wouldn't work properly.
> [go-experimental] Fix marshalling of of go oneOf structures to work on non-pointer receivers

- modules/openapi-generator/src/main/resources/typescript/api/api.mustache
- modules/openapi-generator/src/main/resources/typescript/http/http.mustache
- modules/openapi-generator/src/main/resources/typescript/http/isomorphic-fetch.mustache
- modules/openapi-generator/src/main/resources/typescript/http/jquery.mustache
- modules/openapi-generator/src/main/resources/typescript/index.mustache
- modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache
- modules/openapi-generator/src/main/resources/typescript/package.mustache
- modules/openapi-generator/src/main/resources/typescript/tsconfig.mustache
- samples/client/petstore/typescript/builds/default/apis/PetApi.ts
- samples/client/petstore/typescript/builds/default/apis/StoreApi.ts
- samples/client/petstore/typescript/builds/default/apis/UserApi.ts
- samples/client/petstore/typescript/builds/default/http/http.ts
- samples/client/petstore/typescript/builds/default/http/isomorphic-fetch.ts
- samples/client/petstore/typescript/builds/default/index.ts
- samples/client/petstore/typescript/builds/default/models/ObjectSerializer.ts
- samples/client/petstore/typescript/builds/default/package-lock.json
- samples/client/petstore/typescript/builds/default/package.json
- samples/client/petstore/typescript/builds/default/tsconfig.json
- samples/client/petstore/typescript/builds/jquery/apis/PetApi.ts
- samples/client/petstore/typescript/builds/jquery/apis/StoreApi.ts
- samples/client/petstore/typescript/builds/jquery/apis/UserApi.ts
- samples/client/petstore/typescript/builds/jquery/http/http.ts
- samples/client/petstore/typescript/builds/jquery/http/jquery.ts
- samples/client/petstore/typescript/builds/jquery/index.ts
- samples/client/petstore/typescript/builds/jquery/models/ObjectSerializer.ts
- samples/client/petstore/typescript/builds/jquery/package-lock.json
- samples/client/petstore/typescript/tests/default/package-lock.json
- samples/client/petstore/typescript/tests/default/test/http/isomorphic-fetch.test.ts
- samples/client/petstore/typescript/tests/jquery/package-lock.json
Currently the new typescript generator only supports receiving http responses with `Content-Type: application/json`. This is an approach to support other media types as well.
In particular the first goal is to allow parsing arbitrary binary files as `HttpFile`.
Later other media types, like xml could be added (possibly togglable with an config option to not always pull in the relevant parser library)
Please have a look, when you find the time @TiFu. The file download is not quite finished though.
Cf. #802
> Support media types other than json

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/AbstractOpenApiSchema.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/oneof_model.mustache
- samples/client/petstore/java/jersey2-java7/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
This PR makes `oneOf` (de)serialization actually work properly, also adds some convenience constructors for the `oneOf` models and equals/toString/hashcode for proper comparison and debugging.
> [Java][jersey2] Make (de)serialization work for oneOf models

- .travis.yml
- CI/.travis.yml.bash
- CI/.travis.yml.ios
- CI/bitrise.yml
- CI/circle_parallel.sh
- appveyor.yml
- bin/utils/ensure-up-to-date
- circle.yml
- pom.xml
- shippable.yml
Explicitly set Maven's `--no-snapshot-updates` option in CI. Although certain providers may configure snapshot updates, it's unclear across our providers what would occur if we run `mvn install` in one command, followed by `mvn verify` in another during which time a SNAPSHOT release was published on master. Declaring this option provides some certainty across all providers where we follow this approach.  Because we also run with `--quiet`, we reduce our visibility into whether CI is downloading the SNAPSHOT or using the locally cached version.
Gradle doesn't require such an option because it caches snapshot dependencies for 24 hours by default and requires either manual updates or reconfiguration to change that behavior (see https://docs.gradle.org/current/userguide/dynamic_versions.html). …
> [ci] Execute maven and verify with no-snapshot-updates

- modules/openapi-generator/src/main/resources/powershell/configuration.mustache
- modules/openapi-generator/src/main/resources/powershell/model_anyof.mustache
- modules/openapi-generator/src/main/resources/powershell/model_oneof.mustache
- samples/client/petstore/powershell/src/PSPetstore/Client/PSConfiguration.ps1
Minor code style change based on reports by https://github.com/PowerShell/Psscriptanalyzer
> [PS] minor code style change

- modules/openapi-generator/src/main/resources/powershell/model_anyof.mustache
- modules/openapi-generator/src/main/resources/powershell/model_oneof.mustache
- Fix hardcoded match type in oneOf, anyOf
> [PS] Fix hardcoded match type

- appveyor.yml
Fixed pester version to fix the following errors due to recent release of pester 5.0:
```
Starting discovery in 12 files.
Discovery finished in 658ms.
[-] Integration Tests.Pet.CRUD tests 688ms (481ms|207ms)
ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to …
```
> [PS] Set pester version to v4.3.1

- modules/openapi-generator/src/main/resources/ruby-client/rubocop.mustache
- samples/client/petstore/ruby-faraday/.rubocop.yml
- samples/client/petstore/ruby/.rubocop.yml
> Fix ruby deprecation error

- docs/templating.md
- docs/usage.md
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/OpenAPIGenerator.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/AuthorTemplate.java
- modules/openapi-generator-cli/src/test/java/org/openapitools/codegen/cmd/AuthorTemplateTest.java
This new command allows users to extract templates for authoring (customization) without the complexity of finding and downloading a specific directory for their versioned artifact.
Example usage:
```
openapi-generator author template -g java --library webclient
```
This will write all templates with library-specific templates to the './out' directory relative to the current directory. The user can specify an alternative directory as well. See the doc changes in this PR for more details.
CLI will refer the user to https://openapi-generator.tech/docs/templating after generation.
This PR is supplemental to the template quality PR #6357
This PR provides the start of authoring commands detailed in #1811
> [cli] new 'author template' command

- modules/openapi-generator/src/main/resources/typescript-axios/modelGeneric.mustache
Add `@deprecated` to JSDoc for a parameter when it is marked as deprecated
fixes #6474 
> typescript-axios: Support deprecated parameters

- bin/csharp-petstore-all.sh
- bin/csharp-petstore-net-standard.json
- bin/windows/csharp-petstore-all.bat
- bin/windows/csharp-petstore-netcore-project.bat
- bin/windows/csharp-petstore-netstandard.bat
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
The `netstandard1.3` was originally presented to users as `v5.0`. This was deprecated throughout 4.x, and is now renamed as a hard breaking change. The original implementation was from pre-fork in swagger-codegen. I never understood why `v5.0` was chosen because it's not even a [documented mapping](https://github.com/dotnet/standard/blob/master/docs/versions.md#mapping-pcl-profiles-to-net-standard).
Up for discussion: I'd be happy to fully delete this option and uwp from the csharp generator instead.
Whatever route we take, this v5.0 needs to be removed before the actual .NET 5.0 exits preview.
> [csharp] Rename v5.0 to netstandard1.3

- bin/rust-petstore.sh
- docs/generators/rust.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
- set supportAsync to true as the default
> [Rust] set supportAsync to true as the default

- modules/openapi-generator/src/main/resources/typescript/api/api.mustache
- modules/openapi-generator/src/main/resources/typescript/auth/auth.mustache
- modules/openapi-generator/src/main/resources/typescript/http/http.mustache
- modules/openapi-generator/src/main/resources/typescript/http/servers.mustache
- modules/openapi-generator/src/main/resources/typescript/package.mustache
- modules/openapi-generator/src/main/resources/typescript/types/ObservableAPI.mustache
- samples/openapi3/client/petstore/typescript/builds/default/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/auth/auth.ts
- samples/openapi3/client/petstore/typescript/builds/default/package-lock.json
- samples/openapi3/client/petstore/typescript/builds/default/package.json
- samples/openapi3/client/petstore/typescript/builds/default/servers.ts
- samples/openapi3/client/petstore/typescript/builds/default/types/ObservableAPI.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/auth/auth.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/http/http.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/package-lock.json
- samples/openapi3/client/petstore/typescript/builds/jquery/package.json
- samples/openapi3/client/petstore/typescript/builds/jquery/servers.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/types/ObservableAPI.ts
- samples/openapi3/client/petstore/typescript/tests/default/package-lock.json
Previously I defined my own SecurityAuthentication class. This PR adds support for bearer token authentication directly to the typescript generator.
The configuration requires a (possibly asynchronous) token provider class. This is so that the token can be refreshed if necessary. Also the token provider can later be injected with inversifyjs.
Would it be useful, to also use credential providers in the other security types? Maybe a more generic solution could be used?
In our use case the bearer token changes frequently, but I'm not sure what the common api token or basic auth use cases need.
I also updated typescript to 3.9 which hopefully avoids some issues with the ancient version we where using before.
Some commits are cherry-picked from typescript-refactor-master-oaiv3 to make the …
> [Typescript] Support http bearer authentication with token provider

- bin/apex-petstore.sh
- samples/client/petstore/apex/README.md
- samples/client/petstore/apex/force-app/main/default/classes/OASPetApi.cls
- samples/client/petstore/apex/force-app/main/default/classes/OASStoreApi.cls
- samples/client/petstore/apex/force-app/main/default/classes/OASUserApi.cls
> [Apex] migrate samples to use OAS v3 spec

- README.md
When you run this command in a directory that contains spaces, it will not execute correctly. Sample result.
```
docker: invalid reference format: repository name must be lowercase.
```
> Improve handling spaces in example command

- docs/faq-contributing.md
- docs/installation.md
- docs/integration.md
- website/src/pages/index.js
Just a couple of minor spelling/capitalization fixes in the docs:
- `Github` -> `GitHub`
- `NPM` -> `npm`
> Fix docs typos

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientExperimentalTest.java
Minor enhancement to Python client  and experimental client generator's code format
> Minor enhancement to Python client generator's code format

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientExperimentalTest.java
Undo PR #6451 (and https://github.com/OpenAPITools/openapi-generator/pull/6510, which is a follow-up PR to #6451) due to CI failure (outdated samples and changes to enum example values): https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/3043/workflows/2c13f8cb-583f-401a-b865-e5184d035f35/jobs/16404
> Undo PR #6451

- modules/openapi-generator/src/main/resources/powershell/model_anyof.mustache
Add discriminator support to anyOf to speed up the lookup process with the mapping
> [PowerShell] Add discriminator support to anyOf 

- docs/generators/go-experimental.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientExperimentalCodegen.java
- modules/openapi-generator/src/main/resources/go-experimental/model_oneof.mustache
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_mammal.go
Add oneOf discriminator lookup with the option "useOneOfDiscriminatorLookup"
> [Go][Experimental] add oneOf discrimistrator lookup

- modules/openapi-generator/src/main/resources/go-experimental/model_oneof.mustache
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_fruit_req.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_mammal.go
- Minor fix to discriminator lookup
- Tested locally and confirm the discriminator is used in lookup
> [Go][Experimental] Fix discriminator lookup

- modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/clientConfiguration.mustache
- samples/client/petstore/spring-cloud-async/src/main/java/org/openapitools/configuration/ClientConfiguration.java
- samples/client/petstore/spring-cloud/src/main/java/org/openapitools/configuration/ClientConfiguration.java
> Register OAuth2ClientContext as bean

- docs/installation.md
The current `npx ` command says to use:
```
npx openapi-generator generate -i petstore.yaml -g ruby -o /tmp/test/
```
This however, pulls a similarly-named but different project: [zhang740/openapi-generator](https://www.npmjs.com/package/openapi-generator).
This commit fixes this, by using the appropriate package `@openapitools/openapi-generator-cli`
> Fix incorrect npx command

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppUE4ClientCodegen.java
- modules/openapi-generator/src/main/resources/cpp-ue4/Build.cs.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/api-operations-header.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/helpers-header.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/helpers-source.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/model-base-header.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/model-header.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/model-source.mustache
- samples/client/petstore/cpp-ue4/OpenAPI.Build.cs
- samples/client/petstore/cpp-ue4/Private/OpenAPIApiResponse.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPICategory.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIHelpers.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIOrder.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIPet.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPITag.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIUser.cpp
- samples/client/petstore/cpp-ue4/Public/OpenAPIApiResponse.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIBaseModel.h
- samples/client/petstore/cpp-ue4/Public/OpenAPICategory.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIHelpers.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIOrder.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIPet.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIPetApiOperations.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIStoreApiOperations.h
- samples/client/petstore/cpp-ue4/Public/OpenAPITag.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIUser.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIUserApiOperations.h
More fixes to UE4 code generator. Tested compilation under various project setups, including linux compilation. Added support for string and enum type definitions. Better handling of variable names in edge cases, should no longer produce empty variable names.
> [C++][Ue4] various bus fixes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
- modules/openapi-generator/src/main/resources/powershell/model_anyof.mustache
- modules/openapi-generator/src/main/resources/powershell/model_oneof.mustache
- samples/client/petstore/powershell/.openapi-generator/FILES
- automatically derive discriminator mapping for oneOf/anyOf if the discriminator mapping is not defined in the spec
> [PS] automatically derive discriminator mapping for oneOf/anyOf 

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
Whitelist AdditionalProperties in the field name with `AdditionalPropertiesField` instead as it can be used when `additionalProperties` is set to true
> [Go] whitelist AdditionalProperties in the field name

- modules/openapi-generator/src/main/resources/kotlin-spring/apiUtil.mustache
- samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/ApiUtil.kt
- samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/ApiUtil.kt
fixes #5476 The kotlin-spring generator ApiUtil object doesn't compile, by adding null safe accessor
> [kotlin][spring] Fix ApiUtil compilation

- pom.xml
Move Ruby tests to Travis from CircleCI to address the failure due to requirement of a newer version of Ruby
> Move Ruby tests to Travis CI

- pom.xml
Remove scala-related profile from the pom as this project is no longer written in scala.
> Remove scala-related profile from the pom

- bin/rust-petstore-reqwest-async.sh
- modules/openapi-generator/src/main/resources/rust/reqwest/api_mod.mustache
- pom.xml
- samples/client/petstore/rust/reqwest/petstore-async/pom.xml
For https://github.com/OpenAPITools/openapi-generator/issues/6178#issuecomment-640270765
> [rust][reqwest] fix broken export

- README.md
- `N/A` If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- `N/A` Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- `N/A` File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): …
> Add Instana to the list of users

- modules/openapi-generator/src/main/resources/ruby-client/gemspec.mustache
- samples/client/petstore/ruby-faraday/petstore.gemspec
- samples/client/petstore/ruby/petstore.gemspec
JSON has been included in ruby since 1.9:
```ruby
$ irb -f
irb(main):001:0> RUBY_VERSION
irb(main):002:0> require "json"
irb(main):003:0> JSON
```
Forcing everyone to use a recent version like 2.1+ is a good thing but sometimes it may be detrimental: some older apps may still be stuck on 1.x for some reason and currently they wouldn't be able to use generated clients because of the 2.1+ requirement.
Unless there's a specific reason to use 2.1+ in the clients, listing (or not) json as a dependency should be up to the user of the generated clients.
For example, rails dropped the explicit dependency a long time ago ([PR](https://github.com/rails/rails/pull/23453)).
@cliffano @zlx @autopp @wing328
> Remove the json dependency

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFExtServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/K6ClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/api.mustache
- modules/openapi-generator/src/test/resources/2_0/templates/Java/libraries/jersey2/api.mustache
- modules/openapi-generator/src/test/resources/sampleConfig.json
Remove `localVariablePrefix` in Java files and templates as the local variable has been prefixed correctly to avoid naming collision with parameter names.
> Remove localVariablePrefix

- modules/openapi-generator/src/main/resources/Java/libraries/native/README.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/api_doc.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/api_test.mustache
- samples/client/petstore/java/native/docs/AnotherFakeApi.md
- samples/client/petstore/java/native/docs/FakeApi.md
- samples/client/petstore/java/native/docs/FakeClassnameTags123Api.md
- samples/client/petstore/java/native/docs/PetApi.md
- samples/client/petstore/java/native/docs/StoreApi.md
- samples/client/petstore/java/native/docs/UserApi.md
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/native/src/test/java/org/openapitools/client/api/FakeApiTest.java
Ths PR added the option to build API requests using builder pattern for Client-Java-Native based on the [request](https://github.com/OpenAPITools/openapi-generator/issues/5451)
It includes the changes below:
- update the template of API
- update the template of README
- add modified template of api test under native
- add modified template of api doc under native
- update Petstore samples for native
- fixed [build error with null async return](https://github.com/OpenAPITools/openapi-generator/issues/6550)
@wing328 @cbornet @jeff9finger @bbdouglas @sreeshas @jfiala @lukoyanov @karismann @Zomzog @lwlee2608  @bkabrda @jfeltesse-mdsol @jcarres-mdsol
> [Java][Native]Add option to use the builder pattern for API parameters

- modules/openapi-generator/src/main/resources/go-experimental/api.mustache
- modules/openapi-generator/src/main/resources/go/api.mustache
- samples/client/petstore/go-experimental/go-petstore/api_pet.go
- samples/client/petstore/go-experimental/go-petstore/api_store.go
- samples/client/petstore/go-experimental/go-petstore/api_user.go
- samples/client/petstore/go/go-petstore-withXml/api_pet.go
- samples/client/petstore/go/go-petstore-withXml/api_store.go
- samples/client/petstore/go/go-petstore-withXml/api_user.go
- samples/client/petstore/go/go-petstore/api_pet.go
- samples/client/petstore/go/go-petstore/api_store.go
- samples/client/petstore/go/go-petstore/api_user.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_pet.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_store.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_user.go
- samples/openapi3/client/petstore/go/go-petstore/api_pet.go
- samples/openapi3/client/petstore/go/go-petstore/api_store.go
- samples/openapi3/client/petstore/go/go-petstore/api_user.go
This PR uses [`url.PathEscape`](https://golang.org/pkg/net/url/#PathEscape) instead of [`url.QueryEscape`](https://golang.org/pkg/net/url/#QueryEscape) to escape path parameters. `PathEscape` performs what would typically be called "URL encoding" with percents. PathEscape replaces spaces with pluses among other encoding that's suitable for query parameters.
```go
package main
import (
"fmt"
"net/url"
)
func main() {
input := "foo bar"
fmt.Println("QueryEscape:", url.QueryEscape(input))
fmt.Println("PathEscape:", url.PathEscape(input))
}
```
```
QueryEscape: foo+bar
PathEscape: foo%20bar
```
https://play.golang.org/p/3gWzjBhMR9C
Escaping was originally added in #3643.
> go: use PathEscape instead of QueryEscape to escape path params

- bin/generate-samples.sh
- bin/utils/ensure-up-to-date
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
Based on some feedback in #6509, this PR allows users to run `./bin/generate-samples.sh` with a single config and additional arguments similar to how individual bash scripts previously worked.
See also #6608 which updates docs for Windows users to execute through GitBash or equivalent.
Examples are embedded in the script as a header/preamble so users will always be presented these options without the need to `--help`.
For example:
```
IMPORTANT: this script should be run by the CI (e.g. Shippable) to ensure that the 'samples/' folder is up to date.
This script generates all configs under bin/configs by default.
You may generate a targeted script or set of scripts using glob patterns.
For example:
/Users/jim/projects/openapi-generator/bin/generate-samples.sh bin/configs/java-*
You may …
```
> [ci][cli] Allow invoking generate-samples.sh with single file + args

- modules/openapi-generator/src/main/resources/objc/DefaultConfiguration-body.mustache
Referred to the OpenAPI Spec https://swagger.io/docs/specification/authentication/bearer-authentication/ it is able to add bearer authentication to OpenAPI.
The Basic Bearer was ignored in OBJC Template.
> Added basic bearer authentication to objc template

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/auth/HttpSignatureAuth.mustache
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/HttpSignatureAuth.java
Fix problem with HTTP signatures when the URL path and/or query include characters that need to be encoded. For example, `/api/v1/Request?$orderby=-CreateTime&$top=10` may be encoded to `/api/v1/Request?%24orderby=-CreateTime&%24top=10` on the wire. When the HTTP signature includes the `(request-target)` field, the path and query must be written exactly as it is on the wire.
> [java][jersey2] Fix URL encoding problem for HTTP signatures

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
This PR adds a new method that can be overridden to customize the SSL context, trust store, host verifier and keystore.
For example, this may be needed to disable certificate validation when the server is deployed in a development environment with a self-signed certificate, or when the key store needs to be customized.
> [java][jersey2] Add hook to customize SSL context, trust manager and host verifier

- modules/openapi-generator/src/main/resources/php-slim4-server/SlimRouter.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/api.mustache
- samples/server/petstore/php-slim4/lib/Api/AbstractAnotherFakeApi.php
- samples/server/petstore/php-slim4/lib/Api/AbstractFakeApi.php
- samples/server/petstore/php-slim4/lib/Api/AbstractFakeClassnameTags123Api.php
- samples/server/petstore/php-slim4/lib/Api/AbstractPetApi.php
- samples/server/petstore/php-slim4/lib/Api/AbstractStoreApi.php
- samples/server/petstore/php-slim4/lib/Api/AbstractUserApi.php
- samples/server/petstore/php-slim4/lib/SlimRouter.php
It's a bad practice to use general PHP `Exception` because it makes difficult to catch specific cases. Slim framework contains [Slim\Exception\HttpNotImplementedException](https://github.com/slimphp/Slim/blob/4.x/Slim/Exception/HttpNotImplementedException.php) class which looks better than unknown `Exception`.
Result of API call with header `Accept: application/json` and `displayErrorDetails: false` option:
`HTTP/1.1 501 Not Implemented`
```json
{
"message": "501 Not Implemented"
}
```
and with `displayErrorDetails: true` option:
`HTTP/1.1 501 Not Implemented`
```json
{
"message": "501 Not Implemented",
"exception": [
{
"type": "Slim\\Exception\\HttpNotImplementedException",
"code": 501,
"message": "How about extending AbstractUserApi by OpenAPIServer\\Api\\UserApi class implementing …
```
> [php-slim4] Throw specialized HttpNotImplementedException

- modules/openapi-generator/src/main/resources/erlang-server/auth.mustache
Hardcoding open_api_utils there breaks this package if packageName option is used for generating the server code.
Use the provided {{packageName}} template variable the same as it is used in the rest of the file.
The samples do not change when using the default packageName.
CC erlang technical committe
@tsloughter @jfacorro @robertoaloi
> Use supplied packageName instead of hardcoded

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AsciidocDocumentationCodegen.java
- modules/openapi-generator/src/main/resources/asciidoc-documentation/index.mustache
- modules/openapi-generator/src/main/resources/asciidoc-documentation/params.mustache
- samples/documentation/asciidoc/index.adoc
* Allow to use an introduction section instead of abstract
* Allow to use table titles rather than wrapping with sections
* Allow to use HTTP method and path as operation title
* Allow to skip examples sections
> Add some AsciiDoc tweaks

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
The intention of this change is to allow someone to supply their own `OkHttpClient` to the `ApiClient` in the event that they don't want to pay the price for creating a new client even when if they're going to `setHttpClient`. 
A specific example of this is if you have multiple `ApiClients` (e.g. imagine a user service and an avatar service) which have different API contracts but could share the same DNS/caching/resiliency settings etc...  
I appreciate that this could be solved with a custom template but this felt useful enough to contribute.
> [Java] Add add constructor to BYO OkHttpClient

- CI/bitrise.yml
Update bitrise.io config to keep it in sync with the one used in https://bitrise.io
> Update bitrise.io config

- modules/openapi-generator/src/main/resources/go-experimental/model_enum.mustache
- samples/client/petstore/go-experimental/go-petstore/model_enum_class.go
- samples/client/petstore/go-experimental/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_enum_class.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_default_value.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_outer_enum_integer_default_value.go
The error message uses the unmarshaled struct, but it is empty since the unmarshal failed. This fixes it to have a proper error message.
> [go-experimental] Fix error message when unmarshaling wrong enum value

- modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/model_simple.mustache
- samples/client/petstore/python-experimental/petstore_api/model/animal_farm.py
- samples/client/petstore/python-experimental/petstore_api/model/enum_class.py
- samples/client/petstore/python-experimental/petstore_api/model/outer_enum.py
- samples/client/petstore/python-experimental/petstore_api/model/outer_number.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model/animal_farm.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model/array_of_enums.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model/enum_class.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model/outer_enum.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model/outer_enum_default_value.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model/outer_enum_integer.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model/outer_enum_integer_default_value.py
The `__init__` method expects the `attribute_map` to be present.
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)
> [Python] Add attribute_map to simple model

- modules/openapi-generator/src/main/resources/rust-server/client-imports.mustache
- modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache
- modules/openapi-generator/src/main/resources/rust-server/client-operation.mustache
- modules/openapi-generator/src/main/resources/rust-server/server-callbacks.mustache
- samples/server/petstore/rust-server/output/multipart-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/multipart-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/no-example-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/no-example-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/server/callbacks.rs
- samples/server/petstore/rust-server/output/ops-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/ops-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
- samples/server/petstore/rust-server/output/rust-server-test/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/rust-server-test/src/client/mod.rs
When creating a client with middleware, pass the context.
This allows users to pass contextual data about the requests through to the
client middleware.
Note, this is breaking, because:
a) middleware now needs to pass in a `DropContextService` wrapper when calling `Client::try_new_with_client_service()` if it's not expecting to use the context.
b) the type of a client has changed (as the Service is now wrapped in a `DropContextService`).
- @frol
- @farcaller
- @bjgill
- @paladinzh
> [Rust Server] Pass context to client middleware

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/resources/rust-server/client-operation.mustache
- modules/openapi-generator/src/main/resources/rust-server/response.mustache
- modules/openapi-generator/src/main/resources/rust-server/server-operation.mustache
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/multipart-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/no-example-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/openapi-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
- samples/server/petstore/rust-server/output/ops-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
- samples/server/petstore/rust-server/output/rust-server-test/.openapi-generator/FILES
Rust Server currently treats all headers declared in the OpenAPI file as mandatory, when actually they default to optional.
Furthermore, the core code doesn't pass through whether a header is mandatory or optional.
This makes a small change to the DefaultCodgen to pass this data through, defaulting correctly.
The Rust change is then fairly straightforward - we enhance Rust Server, using `Option` to represent non-required headers.
This is breaking, because we'll treat headers which were treated as required before as optional, and we'll provide them as an Option instead.
- @frol
- @farcaller
- @bjgill
- @paladinzh
> [Core, Rust Server] Support optional headers

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/multipart-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/no-example-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/openapi-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/openapi-v3/README.md
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/docs/AdditionalPropertiesWithList.md
- samples/server/petstore/rust-server/output/openapi-v3/src/models.rs
- samples/server/petstore/rust-server/output/ops-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/rust-server-test/.openapi-generator/FILES
Support models which contain an array directly within additional properties - e.g.
```
AdditionalPropertiesWithList:
type: object
type: list
items:
type: string
```
- @frol
- @farcaller
- @bjgill
- @paladinzh
> [Rust Server] Support arrays within additional properties

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/main/resources/rust-server/client-operation.mustache
- modules/openapi-generator/src/main/resources/rust-server/server-operation.mustache
- modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
- samples/server/petstore/rust-server/output/multipart-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/multipart-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/no-example-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/openapi-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/openapi-v3/README.md
- samples/server/petstore/rust-server/output/openapi-v3/api/openapi.yaml
- samples/server/petstore/rust-server/output/openapi-v3/docs/default_api.md
- samples/server/petstore/rust-server/output/openapi-v3/examples/client/main.rs
- samples/server/petstore/rust-server/output/openapi-v3/examples/server/server.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/client/mod.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
- samples/server/petstore/rust-server/output/openapi-v3/src/server/mod.rs
- samples/server/petstore/rust-server/output/ops-v3/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/.openapi-generator/FILES
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/client/mod.rs
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
- samples/server/petstore/rust-server/output/rust-server-test/.openapi-generator/FILES
This adds support to Rust Server for query parameters encoded in JSON - e.g.
```yaml
- name: list-of-strings
in: query
content:
schema:
type: array
items:
$ref: '#/components/schemas/StringObject'
```
There's a small change to the core code to record the content type, and then there's an update to the Rust Server code to support JSON decoding.
Note, no attempt is made to support anything other than JSON query parameters - you can in theory specify an arbitrary mime type here.
This change was contributed by @mirw and reviewed by myself.
- @frol
- @farcaller
- @bjgill
- @paladinzh
> [Core, Rust Server] Support JSON query parameters

- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumClass.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pojo.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom.mustache
- samples/client/petstore/java/microprofile-rest-client/pom.xml
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/model/Category.java
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/model/ModelApiResponse.java
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/model/Order.java
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/model/Pet.java
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/model/Tag.java
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/model/User.java
Fixes the issue no: 2 reported in the issue https://github.com/OpenAPITools/openapi-generator/issues/6028
The pull request removes all jaxb (xml) imports when withXml=false also it uses JsonbTypeSerializer & JsonbTypeDeserializer to deal with enum data types.
> [Java][MicroProfile] Use jsonb imports for serializing  and deserializing enum

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
This fixes the issue reported here https://github.com/OpenAPITools/openapi-generator/issues/6028
setting dateLibrary to java8 is generating joda time library imports.
> Fix issue: Microprofile dateLibrary java8 not working

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/AbstractOpenApiSchema.mustache
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/model/MammalTest.java
- Add getActualInstanceRecursively helper method to get the actual instance recursively.
> [java][jersey2] Add getActualInstanceRecursively

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
Remove incorrect type mapping
```
typeMapping.put("interface{}", "interface{}");
```
> [Go] Remove incorrect type mapping

- docs/generators/typescript-angular.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/TypeScriptAngularClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientOptionsTest.java
fixes: #5781
Extend support to include an option to configure how objects are encoded in query parameters. To include options for nested keys and JSON string.
@TiFu @taxpon  @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce @akehir @petejohansonxo @amakhrov
> [typescript-angular] support for object query parameters as nested key/json string

- bin/configs/rust-reqwest-petstore-async.yaml
- docs/generators/rust.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
- samples/client/petstore/rust/reqwest/fileResponseTest/src/apis/default_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/store_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/user_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/tests/pet_tests.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/pet_api.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/store_api.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/user_api.rs
- samples/client/petstore/rust/reqwest/petstore/tests/pet_tests.rs
- samples/client/petstore/rust/reqwest/rust-test/src/apis/default_api.rs
By default, rust client (using Reqwest) returns a simple return type. Handling multiple returns (several 2xx codes is optional).
cc @frol (2017/07) @farcaller (2017/08) @bjgill (2017/12) @richardwhiuk (2019/07) @paladinzh (2020/05) @wing328
> [Rust][Client] Multiple returns becomes optional (fixes #6650).

- modules/openapi-generator/src/main/resources/go-experimental/model_oneof.mustache
cherry-pick the enhancement from https://github.com/OpenAPITools/openapi-generator/pull/6672
credits: @bkabrda 
> [Go][Experimental] Better logic when using useOneOfDiscriminatorLookup

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
To fix https://github.com/OpenAPITools/openapi-generator/issues/6668
> [PHP] map AnyType to mixed

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
- modules/openapi-generator/src/main/resources/aspnetcore/3.0/Filters/BasePathFilter.mustache
- modules/openapi-generator/src/main/resources/aspnetcore/3.0/Startup.mustache
- samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Filters/BasePathFilter.cs
- samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj
- samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Startup.cs
- samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Filters/BasePathFilter.cs
- samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Org.OpenAPITools.csproj
- samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Startup.cs
Fixes #6466
Fix Issue
Template Directory for .NET 3.1/3.0 is not updated and therefore wrong mustache files were used.
Removed obseleted call from Swashbuckle
@mandrean @jimschubert @frankyjuang @shibayan @wing328
> [ASP.NET] The templateDir for aspnet is not set correctly

- modules/openapi-generator/src/main/resources/objc/Object-body.mustache
- samples/client/petstore/objc/core-data/SwaggerClient/Core/SWGObject.m
- samples/client/petstore/objc/default/SwaggerClient/Core/SWGObject.m
- A static set needs a static lock or we get multiple locks if the class is inherited
- If this fix is not included and SWGObject is accessed from a second thread then we get EXC_BAD_ACCESS error (crash)
Example crash: 
```
Crashed: asyncRealm
0  libobjc.A.dylib                0x180f82088 objc_msgSend + 8
1  CoreFoundation                 0x1811e400c -[__NSSetM containsObject:] + 180
2  MyApp                          0x10094fc28 -[SWGObject initWithDictionary:error:] + 20 (SWGObject.m:20)
3  MyApp                          0x100e019e4 -[JSONModel __importDictionary:withKeyMapper:validation:error:] + 4310850020
4  MyApp                          0x100e00a28 -[JSONModel initWithDictionary:error:] + 4310845992
5  MyApp                          0x10094fcac -[SWGObject initWithDictionary:error:] …
```
> [Objective-C] Fix thread-safety in template

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java
- modules/openapi-generator/src/main/resources/cpp-qt5-client/model-header.mustache
Fixes #6377
@muttleyxd @MartinDelille @stkrwork @ravinikam 
@wing328 
**Fixes this spec below**
```yaml
openapi: 3.0.0
info:
version: 0.0.1
title: Test
paths:
/endpoint:
get:
operationId: getOptions
description: "-"
parameters:
- name: OptionA
in: header
schema:
$ref: '#/components/schemas/OptionA'
responses:
200:
description: Success
content:
schema:
type: array
items:
$ref: '#/components/schemas/OptionA'
components:
schemas:
OptionA:
type: object
description: 'OptionA'
properties:
suboptions:
type: array
description: 'Suboptions of OptionA'
items:
$ref: '#/components/schemas/OptionB'
OptionB:
type: object
description: 'OptionB'
properties:
suboptions1:
type: array
description: 'Suboptions 1 of OptionB'
items:
$ref: '#/components/schemas/OptionA'
suboptions2:
type: …
```
> [C++]Enable forward declaration for C++

- modules/openapi-generator/src/main/resources/go-experimental/model_doc.mustache
- samples/client/petstore/go-experimental/go-petstore/docs/Animal.md
- samples/client/petstore/go-experimental/go-petstore/docs/Category.md
- samples/client/petstore/go-experimental/go-petstore/docs/EnumTest.md
- samples/client/petstore/go-experimental/go-petstore/docs/FormatTest.md
- samples/client/petstore/go-experimental/go-petstore/docs/Name.md
- samples/client/petstore/go-experimental/go-petstore/docs/Pet.md
- samples/client/petstore/go-experimental/go-petstore/docs/TypeHolderDefault.md
- samples/client/petstore/go-experimental/go-petstore/docs/TypeHolderExample.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Animal.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/AppleReq.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/BananaReq.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Category.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/EnumTest.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/FormatTest.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/FruitReq.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/InlineObject3.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/InlineObject4.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/InlineObject5.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Mammal.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Name.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Pet.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Whale.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/docs/Zebra.md
Fixes model documentation: required fields are not pointers.
---
> [go] Required fields are not pointers

- modules/openapi-generator/src/main/resources/typescript-jquery/api.mustache
> typescript-jquery: create empty array to prevent pushing to undefined

- modules/openapi-generator/src/main/resources/python/python-experimental/model_utils.mustache
- samples/client/petstore/python-experimental/petstore_api/model_utils.py
- samples/client/petstore/python-experimental/tests/test_serialization.py
- samples/openapi3/client/extensions/x-auth-id-alias/python-experimental/x_auth_id_alias/model_utils.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model_utils.py
Serialization for nested enums is adding extra `value` key.
`{"foo": EnumValue("bar")}` is serialized as `{"foo": {"value": "bar"}}` instead of `{"foo": "bar"}`.
---
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)
> [Python] enum serialization

- .travis.yml
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
- modules/openapi-generator/src/main/resources/powershell/model_simple.mustache
- samples/client/petstore/powershell/src/PSPetstore/Model/ApiResponse.ps1
- samples/client/petstore/powershell/src/PSPetstore/Model/Category.ps1
- samples/client/petstore/powershell/src/PSPetstore/Model/InlineObject.ps1
- samples/client/petstore/powershell/src/PSPetstore/Model/InlineObject1.ps1
- samples/client/petstore/powershell/src/PSPetstore/Model/Order.ps1
- samples/client/petstore/powershell/src/PSPetstore/Model/Pet.ps1
- samples/client/petstore/powershell/src/PSPetstore/Model/Tag.ps1
- samples/client/petstore/powershell/src/PSPetstore/Model/User.ps1
- vendor extension naming
cc @Ghufz
> [PS] better code format, vendor extension naming

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
Add the ability to turn uniqueItems array into Set in swift.
CC Swift5 technical committee @jgavris (@ehyche @Edubits @jaz-ah @4brunu
> [SWIFT5] Add the ability to turn uniqueItems array into Set in swift.

- modules/openapi-generator/src/main/resources/powershell/api.mustache
- samples/client/petstore/powershell/src/PSPetstore/Api/PSPetApi.ps1
- samples/client/petstore/powershell/src/PSPetstore/Api/PSStoreApi.ps1
- samples/client/petstore/powershell/src/PSPetstore/Api/PSUserApi.ps1
ConvertTo-Josn unable to process the nested objects which are more than two level inside, it treats the whole object as string. Parameter Depth is used to control the nested element processing.
Problem :-
```
PS C:> $response.ActualInstance.Results[0].Organization.GetType().Name
String
```
Correct One:
```
PS C:> $response.ActualInstance.Results[0].Organization.GetType()
PSCustomObject
```
@wing328
> Response was unable to process nested json object more than 2 level 

- modules/openapi-generator/src/main/resources/dart2/class.mustache
- samples/client/petstore/dart2/petstore/test/pet_test.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/api_response.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/category.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/order.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/pet.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/tag.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/user.dart
@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12)
> Dart - generate constructor with named params

- modules/openapi-generator/src/main/resources/powershell/api_test.mustache
- samples/client/petstore/powershell/.openapi-generator/FILES
- samples/client/petstore/powershell/tests/Api/PSPetApi.Tests.ps1
- samples/client/petstore/powershell/tests/Api/PSStoreApi.Tests.ps1
- samples/client/petstore/powershell/tests/Api/PSUserApi.Tests.ps1
- fix the hardcode test with the correct method names
> [PowerShell] fix hardcode method name in test files

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/auth/HttpSignatureAuth.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pom.mustache
- samples/openapi3/client/petstore/java/jersey2-java8/pom.xml
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/HttpSignatureAuth.java
This pull request has a dependency on https://github.com/tomitribe/http-signatures-java/pull/39. The dependent PR needs to be merged before this one, and the pom.mustache template will need to be updated when the tomitribe PR has been merged.
> [java][jersey2] Add support for (expires) and (created) fields in HTTP signature

- .github/workflows/docker-tag-latest-release.yml
Our `latest` tags track master. We don't currently have a stable tracking tag.
This github workflow runs every couple of days, gets the last known tagged release from git metadata, pulls that image from dockerhub if it exists, and creates/updates a tag which represents the latest release.
* `openapitools/openapi-generator-online:latest-release`
* `openapitools/openapi-generator:cli-latest-release`
* `openapitools/openapi-generator:online-latest-release`
Review [github workflow docs](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow) for details on secrets usage.
Secrets are already setup and ready for this to be merged.
fixes #3840
> [docker] Tag latest-release for stable latest tagging

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
fix for the issue https://github.com/OpenAPITools/openapi-generator/issues/6484
PR is against the master branch.
> fix for operation defination containing ref schema

- modules/openapi-generator/src/main/resources/swift5/modelObject.mustache
[SWIFT] - The idea is to manage In a more efficiently way the creation of init methods of model objects providing a default nil value for optional parameters.
This is a trivial change to modelObject.mustache template and could be helpful to create Model objects more simply, in particular when they have many parameters. 
In addition we could avoid possible compilation error for projects that are switching from swagger-codegen tool which provided an init with empty parameters.
With this change we simply provide the '= nil' default value for all params that are optionals
@jgavris  @ehyche  @Edubits  @jaz-ah  @4brunu
> Fix - Provides a default value for optional init parameters

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
Add a getter to the ApiClient class for the User-Agent header value.
Useful for customization of the header agent, when the client is used by a wrapper library for instance. The wrapper can get this value and add its own identifying parts.
> [Java][jersey2] Add a getter for the User-Agent header value

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
If the $data is an invalid Json (for example, add an extra comma after the last property) or if data is not an array, php gives error:
Invalid argument supplied for foreach() at line 257 (Now line is 262)
This is my fist git pull request so please pardon me if I did something wrong.
Best Regards
> [PHP] Better handling of invalid data (array)

- modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
- samples/client/petstore/kotlin-gson/build.gradle
- samples/client/petstore/kotlin-jackson/build.gradle
- samples/client/petstore/kotlin-json-request-string/build.gradle
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/build.gradle
- samples/client/petstore/kotlin-moshi-codegen/build.gradle
- samples/client/petstore/kotlin-nonpublic/build.gradle
- samples/client/petstore/kotlin-nullable/build.gradle
- samples/client/petstore/kotlin-okhttp3/build.gradle
- samples/client/petstore/kotlin-retrofit2/build.gradle
- samples/client/petstore/kotlin-string/build.gradle
- samples/client/petstore/kotlin-threetenbp/build.gradle
- samples/client/petstore/kotlin/build.gradle
There were some dependencies introduced in https://github.com/OpenAPITools/openapi-generator/pull/6585 when using the retrofit library, that accidentally were added also when using the okhttp library.
This PR fixes that, by attributing the right dependencies to the right libraries.
> [kotlin][client] fix retrofit dependencies

- README.md
Fixes #6845 
- [y] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [y] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
> fix erronous cmd arg example for docker in readme

- modules/openapi-generator/src/main/resources/python/configuration.mustache
- samples/client/petstore/python/petstore_api/configuration.py
- samples/openapi3/client/petstore/python/petstore_api/configuration.py
Fixes #6847 
Note I have not built the repo after this change. I manually changed the petstore examples.
I tried to build before making my change. I installed Java 8 (to replace 7). Then I installed Maven, but that then installed Java 7 again and made 7 the default. So I can't build on my machine.
Anyway, it's a trivial change, and CICD should pick up if I somehow forgot to change an example file.
> clarify direction of py client side validation flag

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchModelTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularModelTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangularjs/TypeScriptAngularJsModelTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypeScriptNodeModelTest.java
I was building my own mustache template for typescript client generation and ran into the issue of all boolean and date property defaultValue fields always beeing set to undefined. This PR adds the missing defaultValue handling for typescript generators.
* Added default values for DateTimeSchema, DateSchema and BooleanSchema.
* Added simple tests for default value parsing
> [typescript] Add default values for typescript types

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
This reverts commit 354f195ec09293cfd731b72e67c3cc977b8c0894.
It became superfluous due to some other changes in runtime and changing
of the queryParameters in d9a6f4d
> [typescript-fetch]: Revert "[typescript-fetch] Support deepObject query params (#6075)"

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientExperimentalCodegen.java
- modules/openapi-generator/src/main/resources/go-experimental/model_simple.mustache
- samples/client/petstore/go-experimental/go-petstore/model_additional_properties_any_type.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/model_nullable_class.go
- Added isAdditionalPropertiesTrue to indicate whether `additionalProperties` in the spec is set to true
- Updated go-experimental template to use isAdditionalPropertiesTrue
> Add isAdditionalPropertiesTrue

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
- modules/openapi-generator/src/main/resources/powershell/model_simple.mustache
Replace x-additional-properties with isAdditionalPropertiesTrue
Tested locally to confirm the change.
> [PS] Replace x-additional-properties with isAdditionalPropertiesTrue

- CI/circle_parallel.sh
- pom.xml
Remove JDK7 tests in CircleCI as JDK7 support has been dropped in 5.x release.
> Remove JDK7 tests in CircleCI

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/api_doc.mustache
- samples/client/petstore/java/jersey2-java8/docs/AnotherFakeApi.md
- samples/client/petstore/java/jersey2-java8/docs/FakeApi.md
- samples/client/petstore/java/jersey2-java8/docs/FakeClassnameTags123Api.md
- samples/client/petstore/java/jersey2-java8/docs/PetApi.md
- samples/client/petstore/java/jersey2-java8/docs/StoreApi.md
- samples/client/petstore/java/jersey2-java8/docs/UserApi.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/AnotherFakeApi.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/DefaultApi.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/FakeApi.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/FakeClassnameTags123Api.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/PetApi.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/StoreApi.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/UserApi.md
minor fix to code samples in the doc by replacing `models` with `model`
> [Java][jersey2] minor fix to code samples in the doc

- modules/openapi-generator/src/main/resources/powershell/api.mustache
- modules/openapi-generator/src/main/resources/powershell/api_client.mustache
- samples/client/petstore/powershell/Test1.ps1
- samples/client/petstore/powershell/src/PSPetstore/Api/PSPetApi.ps1
- samples/client/petstore/powershell/src/PSPetstore/Api/PSStoreApi.ps1
- samples/client/petstore/powershell/src/PSPetstore/Api/PSUserApi.ps1
- samples/client/petstore/powershell/src/PSPetstore/Private/PSApiClient.ps1
- added nullable body support
- tested locally to confirm "null" in the HTTP request body
> [PS] add nullable body support

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
Fix null payload
- when body (non-nullable) is null, send empty string
- when body is nullable and null, send "null"
- tested locally with tcpdump to verify the HTTP request
> [Java][jersey2] Fix null payload

- modules/openapi-generator/src/main/resources/r/README.mustache
- modules/openapi-generator/src/main/resources/r/model_test.mustache
- samples/client/petstore/R/README.md
- skip test for enum model to avoid build failure
- update readme
> [R] skip test for enum model

- .gitignore
- modules/openapi-generator/src/main/resources/typescript-axios/api.mustache
- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
- samples/client/petstore/typescript-axios/tests/default/package-lock.json
- samples/client/petstore/typescript-axios/tests/default/package.json
- samples/client/petstore/typescript-axios/tests/default/test/PetApi.ts
- samples/client/petstore/typescript-axios/tests/default/test/PetApiFactory.ts
- samples/client/petstore/typescript-axios/tests/default/test/StoreApi.ts
- samples/client/petstore/typescript-axios/tests/default/test/StoreApiFactory.ts
Switched to new URL API since Node.js legacy URL API is deprecated.
This will drop support Node.js below v6.0.0 (which was released Apr. 2016).
close #6859
> [typescript-axios] switched to new URL API

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/TypeScriptClientCodegenTest.java
- samples/openapi3/client/petstore/typescript/builds/default/http/http.ts
- samples/openapi3/client/petstore/typescript/builds/deno/http/http.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/http/http.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/http/http.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/http/http.ts
This applies the bug fix #4981 to the refactored typescript generator.
CC @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)
> [Typescript] Fix array model of alias to array

- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/UserApi.cs
Make the accept and content-type header consistent with the sync version
This should fix issue OpenAPITools#6821
> fix: make accept header consistent with sync vers.

- modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/model-header.mustache
Enabling forward class declarations also for cpp-restsdk generator as introduced in #6654 
This PR modifies only the templates used for cpp-restsdk and is a simple copy&paste from #6654. The petstore sample client does not change since it does not contain circular references.
> [cpp-restsdk] Enabling forward declarations also for cpp-restsdk generator

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java
> [Java][jersey2] Fix `serializeToString`

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFExtServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
This allows turning on the generate-alias-as-model option per schema with an `x-generate-alias-as-model` extension.
Since this is not a language-specific change, but rather a core change, I'm not sure who to CC... So hopefully CCing @wing328 and @jimschubert is ok.
> Add 'x-generate-alias-as-model' extension to allow enabling generating alias as model per-schema

- modules/openapi-generator-maven-plugin/examples/java-client.xml
- modules/openapi-generator-maven-plugin/examples/kotlin.xml
- modules/openapi-generator-maven-plugin/examples/multi-module/pom.xml
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/JSON.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/oneof_model.mustache
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Fruit.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/FruitReq.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Mammal.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/NullableShape.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Pig.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Quadrilateral.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Shape.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/ShapeOrNull.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Triangle.java
I have a schema that has a `oneOf` with two choices, one is an alias for string and the other for int:
```yaml
components:
schemas:
Something:
type: object
oneOf:
- $ref: '#/components/schemas/One'
- $ref: '#/components/schemas/Two'
One:
type: string
Two:
type: integer
```
The problem is that when the API returns a string that has integer in it, e.g. `"1234"`, the Jackson library (which has coercion of scalars turned on by default) fails to deserialize the `Something` object, as `"1234"` deserializes successfully as both `Integer` and `String`. This PR disables scalar coercion to prevent this, thus making the above example work. (As an additional note, I think we want to have this feature disabled since it is something that other clients don't do) 
@bbdouglas (2017/07) @sreeshas (2017/08) …
> [java][jersey2-client] Disable coercion of scalars

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
Fix string comparison using `.equals` instead of `!=`
> [TS] Fix string comparison

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAiohttpConnexionServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonBluePlanetServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFlaskConnexionServerCodegen.java
- Fix string comparison
- rename PythonAbstractConnexionServerCodegen.java to AbstractPythonConnexionServerCodegen.java
> Fix string comparison in Python generator's abstract class

- modules/openapi-generator/src/main/resources/python-flask/controller_test.mustache
Fixes #6712 
I tried regenerating the petstore examples. The flask one didn't change, but many others did. I didn't commit those changes.
> [fix][python-flask] add missing space for flask basic auth header

- samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java
Follow up to #7028
Tests that `HttpSignatureAuth` headers can be verified after signing.
> [Java][jersey2] Test HttpSignature verification

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Made changes to resolve the issue I raised here - https://github.com/OpenAPITools/openapi-generator/issues/6982
There are quite a few issues with the kotlin multiplatform library currently, but this should at least resolve issues caused by generating a client from a spec which all endpoints require no authorization.
Main changes were to the `ApiClient.kt` - simply adding the appropriate `{{#hasAuthMethods}}` checks as well as the safe access modifier `?.` for the private `authentications` property.
> Add empty checks using hasAuthMethods

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java
- modules/openapi-generator/src/main/resources/protobuf-schema/api.mustache
- modules/openapi-generator/src/main/resources/protobuf-schema/model.mustache
As described in issue https://github.com/OpenAPITools/openapi-generator/issues/6756 .
Cc: @dobl1 .
The protobuf generator currently does not guarantee that generated field numbers are preserved across multiple generations: it always generates them as a sequence from 0 to `n` (through the `x-index` vendor extension). If fields are re-ordered, added, or deleted, field numbers will almost always shift. This is a big deal, as field numbers are part of the binary interface of protobuf serialization format.
This change is making it possible to specify protobuf field numbers using the vendor extension `x-protobuf-index`. This is an opt-in feature at field level: if `x-protobuf-index` is not specified, then the current behavior based on `x-index` still applies. In other words: this is backward …
> [Protobuf] Make it possible to override field numbers using x-protobuf-index

- modules/openapi-generator/src/main/resources/java-pkmst/logging/httpLoggingFilter.mustache
- samples/server/petstore/java-pkmst/src/main/java/com/prokarma/pkmst/logging/HttpLoggingFilter.java
Fix string comparison using `.equals()`
> [Java][pkmst] Fix string comparison

- modules/openapi-generator/src/test/java/org/openapitools/codegen/fsharp/FSharpServerCodegenTest.java
Fix string comparison in fsharp generator tests by using `.equals()`
FYI @nmfisher
> Fix string comparison in fsharp generator tests

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
fix https://github.com/OpenAPITools/openapi-generator/issues/6934
The previously generated code tried to remove loggingInterceptor from an immutable list.
Unfortunately OkHttpClient.Builder is not symmetrical and thus does not contain a method removeInterceptor which would allow for the much cleaner line 
`httpClient = httpClient.newBuilder().removeInterceptor(loggingInterceptor).build();`
> [Java][okhttp-gson] prevent UnsupportedOperationException by removal from ImmutableList on setDebugging(false)

- CONTRIBUTING.md
Add "Allow edits from maintainers" tips to the doc
> Add "Allow edits from maintainers" tips to the doc

- modules/openapi-generator/src/main/resources/dart2/class.mustache
This PR fixes the `fromJson` method for classes with nested lists like `List<List<>>`.  Thus it fixes #2567.
I know the fix is not perfect. The generation will probably break with `List<List<List<>>>` and more dimensions. For fixing this I don't see any easy solution. Feel free to comment ideas into this direction.
@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12)
> [DART] Fix 2d list generated deserilization

- modules/openapi-generator/src/main/resources/protobuf-schema/model.mustache
An example will best illustrate the point of this pull-request. Take the following OpenAPI definition:
```yaml
swagger: "2.0"
info:
title: MyModel
version: "1.0"
paths: {}
definitions:
MyModel:
type: object
properties:
color:
type: string
enum:
- RED
- BLUE
- GREEN
```
**Without** this pull-request, the generated protobuf file looks like:
```protobuf
message MyModel {
enum ColorEnum {
RED = 0;
BLUE = 1;
GREEN = 2;
}
}
```
**With** this pull-request, the generated protobuf file looks like:
```protobuf
message MyModel {
enum ColorEnum {
RED = 0;
BLUE = 1;
GREEN = 2;
}
ColorEnum color = 1;
}
```
> [Protobuf] Generate enum fields

- modules/openapi-generator/src/main/resources/go-experimental/api.mustache
- modules/openapi-generator/src/main/resources/go-experimental/model_anyof.mustache
- modules/openapi-generator/src/main/resources/go-experimental/signing.mustache
- samples/client/petstore/go-experimental/go-petstore/api_another_fake.go
- samples/client/petstore/go-experimental/go-petstore/api_fake.go
- samples/client/petstore/go-experimental/go-petstore/api_fake_classname_tags123.go
- samples/client/petstore/go-experimental/go-petstore/api_pet.go
- samples/client/petstore/go-experimental/go-petstore/api_store.go
- samples/client/petstore/go-experimental/go-petstore/api_user.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_another_fake.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_default.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_fake.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_fake_classname_tags123.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_pet.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_store.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_user.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/signing.go
> [Go][Exp] better code format

- modules/openapi-generator-online/pom.xml
- modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/OpenAPI2SpringBoot.java
- modules/openapi-generator-online/src/test/java/org/openapitools/codegen/online/api/GenApiControllerTest.java
From [slack](https://openapi-generator.slack.com/archives/CLSB0U0R5/p1595950538195500)… generation via online is broken due to errors.
For example:
```
curl -X POST "https://api-latest-master.openapi-generator.tech/api/gen/clients/csharp" -H "Accept: */*" -H "Content-Type: application/json" -d "{ \"openAPIUrl\": \"https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml\"}"
```
Results in an error:
```
{"timestamp":"2020-07-31T13:05:33.674Z","status":500,"error":"Internal Server Error","message":"Could not initialize class io.swagger.v3.parser.OpenAPIV3Parser","path":"/api/gen/clients/csharp"}
```
The online project was pulling in Jackson 2.9 deps which are not all ABI compatible with the 2.10 version we pull in …
> [online] Fix for version conflicts with springfox/boot

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
Fixed issue #6070 - [BUG][All Languages] Multi-Part content type in respons…e ignores properties of composed schema (allOf/oneOf)
https://github.com/OpenAPITools/openapi-generator/issues/6070
This change uses the existing addProperties() method to combine properties of composed schemas.
Before the change, the generated file looked like:
https://gist.github.com/vvalchev/54a935c0f93c06a184a9eeb1640f96e6#file-usersapi-java
After the change, the fist method is properly generated and includes all inherited properties:
https://gist.github.com/vvalchev/54a935c0f93c06a184a9eeb1640f96e6#file-usersapi-java-fixed
CC: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) …
> [BUG] Multi-Part content type in response ignores properties of composed schema (allOf/oneOf)

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
- samples/client/petstore/java/jersey2-java8/build.gradle
- samples/openapi3/client/petstore/java/jersey2-java8/build.gradle
* Corrects tag for including HttpSignatureAuth in gradle builds
* Updates version of org.tomitribe:tomitribe-http-signatures in
gradle template to match version from maven template
* Updates samples
> [Java][jersey2]Fix gradle HttpSignatureAuth dependencies

- modules/openapi-generator/src/main/resources/powershell/Org.OpenAPITools.psm1.mustache
- modules/openapi-generator/src/main/resources/powershell/about_Org.OpenAPITools.help.txt.mustache
- modules/openapi-generator/src/main/resources/powershell/appveyor.mustache
- modules/openapi-generator/src/main/resources/powershell/configuration.mustache
- modules/openapi-generator/src/main/resources/powershell/http_signature_auth.mustache
- modules/openapi-generator/src/main/resources/powershell/rsa_provider.mustache
- samples/client/petstore/powershell/appveyor.yml
- samples/client/petstore/powershell/src/PSPetstore/Client/PSConfiguration.ps1
- samples/client/petstore/powershell/src/PSPetstore/PSPetstore.psm1
- samples/client/petstore/powershell/src/PSPetstore/Private/PSHttpSignatureAuth.ps1
- samples/client/petstore/powershell/src/PSPetstore/Private/PSRSAEncryptionProvider.cs
- samples/client/petstore/powershell/src/PSPetstore/en-US/about_PSPetstore.help.txt
- Allow Appveyor CI to publish the module if the API key is defined and the build is tagged
> [PS] Allow CI to publish the module

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/IAsynchronousClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/Org.OpenAPITools.sln
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/IAsynchronousClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/IAsynchronousClient.cs
Adds optional cancellation tokens to async calls.  This closes #7048. 
> [csharp-netcore] added cancellation tokens to async calls

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
fix for the issue https://github.com/OpenAPITools/openapi-generator/issues/6267
PR is against the master branch.
> fix for the issue, with the spec invlolving arrayschema structure with reference of another schema  for java code generation

- docs/generators/aspnetcore.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
- modules/openapi-generator/src/main/resources/aspnetcore/3.0/Program.mustache
- samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Program.cs
- samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Program.cs
There are two small typo fixes in this issue:
- a doc typo #4829
- a method typo #7093
@mandrean 
@frankyjuang 
@shibayan
> [aspnetcore] Typo issues in docs and generated code

- modules/openapi-generator/src/main/resources/powershell/appveyor.mustache
- samples/client/petstore/powershell/appveyor.yml
- better error handling
- only publish when running on windows images
> [PowerShell] better publishing workflow

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/UserApi.java
fix #4222 
(see #4222  for simple example and steps to reproduce.)
- Changed Java/resttemplate/api.mustache local variables from accept(s) to localVarAccept(s) to avoid collisions with API contract accept(s) parameters.
- Built openapi-generator-maven-plugin and successfully used it to generate client for current development project with an API contract that includes operations with "Accept" header parameters.  (Also verified template changes using o-g-m-p v4.3.1 using templateDirectory override.)
- Ran openapi-generator integration tests against newly generated samples.
- [ X] If contributing template-only or documentation-only changes which will change sample output, …
> ISSUE-4222: Prevent conflicts with accept(s) local variables in generated Java RestTemplate ApiClient

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This adds some caveats that title/descriptions lacking enough detail may result in delays. Also changes generation steps from requiring command line as it doesn't make sense to require command line repro for bugs related to plugin generation; suggests providing config based inputs so we can test across those entrypoints.
> [contrib][docs] Assert importance of title/description/repro steps

- modules/openapi-generator/src/main/resources/go/api.mustache
- samples/client/petstore/go/go-petstore-withXml/api_another_fake.go
- samples/client/petstore/go/go-petstore-withXml/api_fake.go
- samples/client/petstore/go/go-petstore-withXml/api_fake_classname_tags123.go
- samples/client/petstore/go/go-petstore-withXml/api_pet.go
- samples/client/petstore/go/go-petstore-withXml/api_store.go
- samples/client/petstore/go/go-petstore-withXml/api_user.go
- samples/client/petstore/go/go-petstore/api_another_fake.go
- samples/client/petstore/go/go-petstore/api_fake.go
- samples/client/petstore/go/go-petstore/api_fake_classname_tags123.go
- samples/client/petstore/go/go-petstore/api_pet.go
- samples/client/petstore/go/go-petstore/api_store.go
- samples/client/petstore/go/go-petstore/api_user.go
- samples/openapi3/client/petstore/go/go-petstore/api_another_fake.go
- samples/openapi3/client/petstore/go/go-petstore/api_default.go
- samples/openapi3/client/petstore/go/go-petstore/api_fake.go
- samples/openapi3/client/petstore/go/go-petstore/api_fake_classname_tags123.go
- samples/openapi3/client/petstore/go/go-petstore/api_pet.go
- samples/openapi3/client/petstore/go/go-petstore/api_store.go
- samples/openapi3/client/petstore/go/go-petstore/api_user.go
… such that is available to client consumers via the returned httpResponse variable.
Addresses https://github.com/OpenAPITools/openapi-generator/issues/4799
> Update to reset httpRepsonse.Body

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/oneof_model.mustache
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Fruit.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/FruitReq.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Mammal.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/NullableShape.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Pig.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Quadrilateral.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Shape.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/ShapeOrNull.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Triangle.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/JSONComposedSchemaTest.java
Add helper methods for oneOf Java classes
For https://github.com/OpenAPITools/openapi-generator/issues/6892
Will submit another another one for anyOf if this one is accepted.
> [Java][jersey2] Add helper methods for oneOf Java classes

- docs/generators/go-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
- modules/openapi-generator/src/main/resources/go-server/model.mustache
Added "enumClassPrefix" option for Go server generation. Ported existing functionality already made available in the Go client generation so that the constant terms for enum values can be prefixed with the enum name itself. This is useful when you have multiple enum definitions that have some values that are shared between the enum sets.
Fix #6907 
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07)
> [REQ] Added enumClassPrefix option to Go server generation

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- modules/openapi-generator/src/main/resources/typescript-axios/configuration.mustache
- samples/client/petstore/typescript-axios/builds/composed-schemas/configuration.ts
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/default/configuration.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/configuration.ts
This PR enables to resolve access tokens (bearer and OAuth) asynchronously, similar to API keys.
Closes #7105.
@TiFu @taxpon @sebastianhaas @kenisteward  @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov
> [typescript-axios] add promise to bearer and oauth tokens

- modules/openapi-generator/src/main/resources/powershell/appveyor.mustache
- samples/client/petstore/powershell/appveyor.yml
- Better error handling when publishing module by reporting a build failure
- skip NuGet.CommandLine installation which is not needed
> [PS] Better error handling when publishing module

- docs/generators/go-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
- fix boolean options
- minor code format
- add cli option for enum prefix in go server generator
> [Go] minor improvements

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/anyof_model.mustache
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/GmFruit.java
- Add helper methods to "anyOf" Java models
A follow-up PR to #7115
> Add helper methods to "anyOf" Java models

- modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
- modules/openapi-generator/src/main/resources/go-server/routers.mustache
- samples/server/petstore/go-api-server/README.md
- samples/server/petstore/go-api-server/go/api_pet.go
- samples/server/petstore/go-api-server/go/api_store.go
- samples/server/petstore/go-api-server/go/routers.go
> added int32 type support for go-server

- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/UserApi.cs
- Remove duplicated cancellationToken in comment 
e.g. https://github.com/OpenAPITools/openapi-generator/pull/7148/files#diff-7e23c3337402ba4f60a5f2f37efb5613L273
> [c#][netcore] Remove duplicated cancellationToken in comment

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
- Escape double quotes in regular expression by replacing `"` with `""`
- Tested locally to confirm the fix.
> [C#][netcore] fix regular expression when it contains double quotes

- modules/openapi-generator/src/main/resources/scala-sttp/api.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/paramQueryCreation.mustache
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/PetApi.scala
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/UserApi.scala
This fixes #6883 
Provided solution generates additional spaces around `paramName`.
Alternative solution to fix this would be to create a custom lambda to wrap arbitrary expression in curly braces in sttp generator and register it within `additionalProperties`.
@clasnake (2017/07), @jimschubert (2017/09) , @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)
> Sttp - wrap query params

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-retrofit2/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
> [Kotlin] Make ApiClient in jvm-retrofit2 be able to use own OkHttpClient

- modules/openapi-generator/src/main/resources/JavaJaxRS/ApiException.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/ApiException.mustache
- modules/openapi-generator/src/main/resources/JavaSpring/apiException.mustache
- modules/openapi-generator/src/main/resources/java-msf4j-server/ApiException.mustache
- samples/server/petstore/java-msf4j/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs/jersey1-useTags/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs/jersey1/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/ApiException.java
Fixes #6830 
Basically a few `ApiException` templates for Java servers were missing a getter for the `code` field.  
Before the fix the generated class was:
```java
package org.openapitools.api;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaResteasyServerCodegen", date = "2020-07-01T16:12:55.083+02:00[Europe/Paris]")
public class ApiException extends Exception{
private int code;
public ApiException (int code, String msg) {
super(msg);
this.code = code;
}
}
```
With the fix it becomes:
```java
package org.openapitools.api;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaResteasyServerCodegen", date = "2020-08-06T22:46:58.073+02:00[Europe/Paris]")
public class ApiException extends Exception {
private int code;
public ApiException(int …
```
> [Java][jaxrs] Add getter to ApiException templates

- .github/workflows/check-supported-versions.yaml
- README.md
This sets up a GitHub Workflow to verify JDK 8 (Linux, Windows), 11 (Linux), and 13 (Linux) on pushes to master. It also verifies that the ensure-up-to-date script works in both Linux and Windows.
This is applied to pushes to master only, because GitHub Workflows currently don't support run cancellation.
JDK 13 skips building the Maven and Gradle plugins for simplicity since the version of Gradle we use to build the Gradle plugin does not support JDK 13 and the Maven plugin is compiled and released using JDK 8. This supported version check is provided for those contributing generators and other functionality aside from plugins. we may add back in plugin checks to JDK 13 once our Gradle dependency is updated.
> [ci] Verify supported JDK versions on master push

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiException.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiException.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiException.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Configuration.cs
* Adding HTTP response headers to the ApiException.
> [csharp-netcore] Adding response headers to the ApiException

- appveyor.yml
- modules/openapi-generator-gradle-plugin/README.adoc
- modules/openapi-generator-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
- modules/openapi-generator-gradle-plugin/samples/local-spec/README.md
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/MetaTask.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/ValidateTask.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
Fixes #6472 
Enhance current Gradle plugin to support Caching and Up-To-Date checks by declaring @input and @OutputDirectory annotations. This can speed up build times.
- replaced @Internal with @Optional annoations
- added @InputFile and @OutputDirectory to file inputs
- added @Input to all configuration inputs
- added @CacheableTask to all task except GeneratorsTask
- Added notes to README
- Updated Gradle Wrapper to 5.6.4 in accordance to pom.xml
cc @OpenAPITools/build
> [gradle] Enabling up-to-date checks and gradle caching for openapigenerator tasks

- modules/openapi-generator/src/main/resources/typescript-node/api-all.mustache
- modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
- modules/openapi-generator/src/test/resources/integrationtests/typescript/node-es5-expected/api.ts
- modules/openapi-generator/src/test/resources/integrationtests/typescript/objectsWithEnums-expected/api/defaultApi.ts
- samples/client/petstore/typescript-node/default/api/apis.ts
- samples/client/petstore/typescript-node/default/api/petApi.ts
- samples/client/petstore/typescript-node/default/api/storeApi.ts
- samples/client/petstore/typescript-node/default/api/userApi.ts
- samples/client/petstore/typescript-node/npm/api/apis.ts
- samples/client/petstore/typescript-node/npm/api/petApi.ts
- samples/client/petstore/typescript-node/npm/api/storeApi.ts
- samples/client/petstore/typescript-node/npm/api/userApi.ts
Hello developers.
Thank you for maintaining the OpenAPI Generator!!
I have a suggestion for you today.
I have been using "typescript-node" recently, and I noticed a problem.
Even though I use node @ 10, es5, and Typescript 3.7 in my development, the correct type will not be generated unless I include the "--additional-properties supportsES6 = true" flag when generating the "typescript-node" code!
If this flag is not set, a "http.IncomingMessage" type should be created, but a "http: ClientResponse" type will be created.
So I did some research and found that the version of node, not the ECMA Proposal, should determine whether the "http.IncomingMessage" or "http: ClientResponse" type should be used.
As you know, the ECMA Proposal is just a proposal for a language specification and makes no …
> [typescript-node] Fix invalid type when using node@10 and ES5

- modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
- samples/client/petstore/javascript-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise-es6/src/ApiClient.js
Fixing the handling of non primitive types in paramToString (#7171)
Small change adding a helper method that checks if a parameter could be JSON-ified then modified paramToString to use JSON.stringify if the helper returns true.
cc @CodeNinjai @frol @cliffano @wing328
> [JS] Fix paramToString handling for non primitive types

- modules/openapi-generator/src/main/resources/python/python-experimental/rest.mustache
- modules/openapi-generator/src/main/resources/python/rest.mustache
- samples/client/petstore/python-experimental/petstore_api/rest.py
- samples/client/petstore/python/petstore_api/rest.py
- samples/openapi3/client/extensions/x-auth-id-alias/python-experimental/x_auth_id_alias/rest.py
- samples/openapi3/client/features/dynamic-servers/python-experimental/dynamic_servers/rest.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/rest.py
- samples/openapi3/client/petstore/python/petstore_api/rest.py
This PR allows passing of a fractional number of seconds as a timeout when making network requests through the `RESTClientObject`. Currently timeout durations provided as a `float` are silently ignored instead of being enforced:
<details>
<summary> RESTClientObject timeout behavior</summary>
```python
>>> # Google uses the OpenAPI generator for their Python client
>>> from kubernetes.client.configuration import Configuration
>>> from kubernetes.client.rest import RESTClientObject
>>> rest_client_object = RESTClientObject(Configuration())
>>>
>>> # unexpectedly returns a response
>>> rest_client_object.request('GET', 'http://neverssl.com', _request_timeout=1e-9)
<kubernetes.client.rest.RESTResponse object at 0x7fd6a968cbd0>
>>>
>>> # fails with a timeout error, as we'd expect
>>> …
```
> [python{,-experimental}] Obey floating point timeouts provided to RESTClientObject.request(...)

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
Fixes #7174. Please review.
Use `/` instead of `File.Separator`. `File.Separator` is `/` in Windows.
A target method is `postProcessOperationsWithModels` of openapi-generator\modules\openapi-generator\src\main\java\org\openapitools\codegen\languages\TypeScriptClientCodegen.java.
Before
```java
im.put("filename", ((String) im.get("import")).replace(".", File.Separator));
```
After
```java
im.put("filename", ((String) im.get("import")).replace(".", "/"));
```
By this, OpenAPI generator generated valid import path in typescript.
Expected Code
```typescript
import { Pet } from '../models/Pet';
```
Actual Code
```typescript
import { Pet } from '..\models\Pet';
```
> [Typescript] Import path is invalid in windows.

- modules/openapi-generator/src/main/resources/typescript-redux-query/apis.mustache
- modules/openapi-generator/src/main/resources/typescript-redux-query/runtime.mustache
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/apis/PetApi.ts
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/apis/StoreApi.ts
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/apis/UserApi.ts
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/runtime.ts
Added a new Configuration object that has attributes that can be used to alter the behaviour of the query config generators.  In particular, added a basePath field which can be used to prepend to the urls in the query configs.  The old behaviour only used relative paths for the urls which means cross domain support was not possible.
Left the default basePath as an empty string to keep existing behaviour the same.
> Fixes #6942: Added ability to prepend a basePath to typescript-redux-query generators

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientExperimentalTest.java
* Forces formatting of import classnames to handle edge case schemas
If merged this will resolve:
https://github.com/OpenAPITools/openapi-generator/issues/7187
> [WIP][python-exp] Force camelization of imports

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
- modules/openapi-generator/src/main/resources/csharp-netcore/IAsynchronousClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/IAsynchronousClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/IAsynchronousClient.cs
If `supportsAsync` is set to false, generate better code and remove unnecessary files.
Tested locally with `supportsAsync` set to false
> [C#][netcore] Better sync only client support

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache
- remove `supportsUWP` from template as it's not supported in csharp-netcore.
- users are advised to use `csharp` generator instead.
> [C#][netcore] remove supportsUWP from template

- modules/openapi-generator/src/main/resources/go-server/api.mustache
- modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
- modules/openapi-generator/src/main/resources/go-server/service.mustache
- samples/server/petstore/go-api-server/go/api.go
- samples/server/petstore/go-api-server/go/api_pet.go
- samples/server/petstore/go-api-server/go/api_pet_service.go
- samples/server/petstore/go-api-server/go/api_store.go
- samples/server/petstore/go-api-server/go/api_store_service.go
- samples/server/petstore/go-api-server/go/api_user.go
- samples/server/petstore/go-api-server/go/api_user_service.go
Modifiled go-server templates.
close #6657 
- Added `context.Context` arguments to below templates
- api.mustache
- controller-api.mustache
- service.mustache
- Updated `go-api-server` sample by running `./bin/generate-samples.sh`
> [go-server] Modified go-server templates to allow services to receive http request's context.

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- samples/client/petstore/c/src/apiClient.c
Fixes a missing return in the sslConfig_create function in the C client templates.
cc @zhemant @ityuhui @michelealbano
> Fix a missing return in the C client sslConfig_create function.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java
fixes #6837 
avoid 'servers not defined in the spec' warn-spam on maven console
> avoid 'servers not defined in the spec' warn-spam on maven console (#6837)

- .gitignore
- modules/openapi-generator/src/main/resources/php-laravel/gitignore
- modules/openapi-generator/src/main/resources/php-slim4-server/gitignore
- modules/openapi-generator/src/main/resources/php-symfony/gitignore
- modules/openapi-generator/src/main/resources/php/gitignore
- samples/client/petstore/php/OpenAPIClient-php/.gitignore
- samples/server/petstore/php-laravel/lib/.gitignore
- samples/server/petstore/php-slim4/.gitignore
- samples/server/petstore/php-symfony/SymfonyBundle-php/.gitignore
`composer.lock` may produce CI errors when you need to test build against different PHP versions. However users most likely want to commit this file, so I think it's better to exclude it only in root `.gitignore`.
@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @renepardon
> [php] Exclude composer.lock in root gitignore

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
Completes commit fc9d4584ca1144532c0b86db958d7f782098253d
The "..._parseFromJSON" template was buggy because the name of the _e type used was not the same than the generated.
See the first argument of "..._convertToJSON" to see that the _e type used there was not the same
About #5477 (#5091 and #4293)
> C-Libcurl client: fix enum model generation

- modules/openapi-generator/src/main/resources/typescript-redux-query/apis.mustache
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/apis/PetApi.ts
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/apis/UserApi.ts
When we have requests that have an array, we get the following error with typescript
```
Object is possibly 'undefined'.  TS2532
261 |             headers: headerParameters,
262 |         },
> 263 |         body: queryParameters || requestParameters.theArrayParam.map(theArrayParamToJSON),
|                                  ^
264 |     };
265 | 
266 |     const { transform: requestTransform } = requestConfig;
```
there are two ways to fix it, and I don't know which is better. Either the one on the PR or adding a ? to every call of the array to have something like this:
`body: queryParameters || requestParameters.theArrayParam?.map(theArrayParamToJSON),`
by the way, regenerating the samples didn't change the output. I guess this case isn't covered by the petstore example
@TiFu (2017/07) …
> [typescript-redux-query]fixed array requests

- modules/openapi-generator/src/main/resources/typescript-redux-query/apis.mustache
- modules/openapi-generator/src/main/resources/typescript-redux-query/runtime.mustache
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/apis/PetApi.ts
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/apis/StoreApi.ts
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/apis/UserApi.ts
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/src/runtime.ts
Hi, 
When we generate the code with typescript-redux-query template the code has an issue when we have anything in the header with this error : 
> Element implicitly has an 'any' type because expression of type '"Content-Type"' can't be used to index type '{}'.
>   Property 'Content-Type' does not exist on type '{}'
to fix this i just added a httpheader type on the object headerParameters
> [Typescript-redux-query] Fix issue on api template when we have non empty header

- docs/generators/aspnetcore.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
- Better wordings for 'classModifier' option based on feedback from the community.
> [ASP.Net Core] Better wordings for 'classModifier' option

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/DefaultApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/DefaultApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
Follow the general guidance and add a call to `ConfigureAwait(false)` to the `await`.
>This leads to the general guidance of: if you’re writing general-purpose library code, use ConfigureAwait(false).
https://devblogs.microsoft.com/dotnet/configureawait-faq/
> [csharp-netcore] Adding ConfigureAwait(false) using async methods call

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- samples/client/petstore/c/src/apiClient.c
@wing328  @zhemant @michelealbano
This problem is found by code static check tool (Clang Static Analyzer)
Bug Group | Bug Type ▾ | File | Function/Method | Line | Path Length |  
-- | -- | -- | -- | -- | -- | --
Dead store | Dead assignment | src/apiClient.c | assembleTargetUrl | 146 | 1 | 
The root cause is:
The variable ```slashNeedsToBeAppendedToBasePath``` is not used.
So I removed the variable ```slashNeedsToBeAppendedToBasePath``` and releated code.
> [C][Client][Clang Static Analyzer] Remove the useless variable when assembling URL

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.sbt.mustache
- samples/client/petstore/java/jersey2-java8/build.gradle
- samples/client/petstore/java/jersey2-java8/build.sbt
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/build.gradle
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/build.sbt
- samples/openapi3/client/petstore/java/jersey2-java8/build.gradle
- samples/openapi3/client/petstore/java/jersey2-java8/build.sbt
Adds the jersey injection dependency to gradle and sbt to match
the maven dependency.
> [Java][jersey2] Add jersey injection dependencies

- .hub.cli.dockerfile
- .hub.online.dockerfile
- Dockerfile
Switch base image from jimschubert/8-jdk-alpine-mvn:1.0 to
maven:3.6.3-jdk-11-openj9.
The jimschubert/8-jdk-alpine-mvn:1.0 is not managed by
any project, it has a very old (alpine 3.4) base image
with many CVE security flaw.
Swap to the image managed by the Maven apache project.
> fix: update base image to maven supported

- modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache
- samples/client/petstore/typescript-rxjs/builds/default/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts
`runtime.ts` is always importing `Subscriber`, even though it's not necessary. It causes linter error like this: 
`'Subscriber' is defined but never used  @typescript-eslint/no-unused-vars`
Changes:
- Added a conditional for the importing on `runtime.mustache`
- Updated samples
Technical committee:
> [typescript-rxjs] Added conditional for `Subscriber` importing

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Remove redundant warning, when type imported via `--import-mapping` param
- [+] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [+] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [+] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [+] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of …
> Remove warning when type imported manually

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/list.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/list.h.mustache
- samples/client/petstore/c/include/list.h
- samples/client/petstore/c/src/apiClient.c
- samples/client/petstore/c/src/list.c
The 2 problems are found by code static check tool (Clang Static Analyzer)
Bug Group | Bug Type ▾ | File | Function/Method | Line | Path Length |  
-- | -- | -- | -- | -- | -- | --
API | Argument with 'nonnull' attribute passed null | src/apiClient.c | apiClient_invoke | 275 | 12 | 
Memory error | Memory leak | src/apiClient.c | apiClient_invoke | 257 | 18 | 
```c
list_ForEach(listEntry, contentType) {
if(strstr((char *) listEntry->data,
"xml") == NULL)
{   
buffContent =     //<==== The pointer pointing the previous bufContnet memory is lost 
malloc(strlen(
"Content-Type: ") + strlen(
(char *)
listEntry->data) +
1);     
sprintf(buffContent, "%s%s",
"Content-Type: ",
(char *) listEntry->data);
headers = curl_slist_append(headers,
buffContent);
// need to free the memory of bufContnet …
```
> [C][Client][Clang Static Analyzer] Fix memory leak in apiClient_invoke

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellHttpClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/resources/csharp/api.mustache
Using `x-is-json` as an alternative solution/implementation to https://github.com/OpenAPITools/openapi-generator/pull/5217
cc @milesressler
> Add x-is-json to csharp generators

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ResponseExtensions.kt.mustache
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ResponseExtensions.kt
Currently the kotlin client generator `ResponseExtensions.kt` shows the following warning.
`infrastructure/ResponseExtensions.kt: (13, 23): Extension is shadowed by a member: public final val isRedirect: Boolean`
This PR silents this warning.
> [kotlin][client] fix warning Extension is shadowed by a member

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/main/resources/swift5/modelObject.mustache
- modules/openapi-generator/src/test/resources/2_0/swift/petstore-with-fake-endpoints-models-for-testing.yaml
- samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/ClassModel.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/File.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/Model200Response.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/Name.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/Return.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/urlsessionLibrary/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- Add extension for hashable
To close https://github.com/OpenAPITools/openapi-generator/issues/7281
cc @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)
> [swift5] Add extension for hashable

- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
- samples/client/petstore/c/api/PetAPI.c
- samples/client/petstore/c/api/StoreAPI.c
- samples/client/petstore/c/api/UserAPI.c
The problem is found by code static check tool (Clang Static Analyzer)
Bug Group | Bug Type ▾ | File | Function/Method | Line | Path Length |  
-- | -- | -- | -- | -- | -- | --
Memory error | Memory leak | api/PetAPI.c | PetAPI_uploadFile | 705 | 5 |
```c
long sizeOfPath = strlen("/pet/{petId}/uploadImage")+1;
char *localVarPath = malloc(sizeOfPath);
if(petId == 0){
goto end;
}
...
free(localVarPath);
...
return elementToReturn;
end:
return NULL;  // <-- The localVarPath is not freed, so memory will leak if the function returns from here
```
> [C][Client][Clang Static Analyzer] Fix memory leak before function returns

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pojo.mustache
- modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/ChildCat.md
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/ChildCatAllOf.md
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ChildCat.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ChildCatAllOf.cs
- samples/openapi3/client/petstore/java/jersey2-java8/api/openapi.yaml
- samples/openapi3/client/petstore/java/jersey2-java8/docs/ChildCat.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/ChildCatAllOf.md
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/ChildCat.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/ChildCatAllOf.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/JSONComposedSchemaTest.java
> [Java][jersey2]Support enum discriminator value in child objects

- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
- samples/client/petstore/c/api/PetAPI.c
- samples/client/petstore/c/api/StoreAPI.c
- samples/client/petstore/c/api/UserAPI.c
These problems are found by code static check tool (Clang Static Analyzer)
Take example:
```c
char *keyForm_status; //<-- keyForm_status is uninitialized
...
free(keyForm_status);  //<-- if the memory of keyForm_status is not allocated by malloc/calloc, it will coredump here. 
```
> [C][Client][Clang Static Analyzer] Fix uninitialized argument value

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- samples/client/petstore/c/src/apiClient.c
This is a defect introduced by my PR https://github.com/OpenAPITools/openapi-generator/pull/7285
```c
list_ForEach(listEntry, contentType) {
if(strstr((char *) listEntry->data,
"xml") == NULL)
{
buffContent =
malloc(strlen(
"Content-Type: ") + strlen(
(char *)
listEntry->data) +
1);
...
free(buffContent);  // <-- I add code to free "buffContent" in PR 7285
buffContent = NULL;
}
...
if(contentType != NULL) {.   // <-- but I forgot to remove this code, so it will coredump here because buffContent is freed before.	
free(buffContent);	
}
```
> [C][Client][Clang Static Analyzer] Remove the useless free operation for buffContent

- modules/openapi-generator/src/main/resources/go-experimental/README.mustache
- modules/openapi-generator/src/main/resources/go/README.mustache
- samples/client/petstore/go/go-petstore-withXml/README.md
- samples/client/petstore/go/go-petstore/README.md
- samples/openapi3/client/petstore/go-experimental/go-petstore/README.md
- samples/openapi3/client/petstore/go/go-petstore/README.md
Auth documentation for the following config is not generated correctly for go clients:
```yaml
GoogleOpenIdAuth:
type: http
scheme: bearer
bearerFormat: JWT
```
It should use AccessToken as the auth config, but what we have right now is BasicAuth.
Also properly document http_signature scheme as unsupported.
> fix http bear auth documentation for go clinets

- docs/file-post-processing.md
- docs/usage.md
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OCamlClientCodegen.java
- website/sidebars.js
Adds user-facing documentation around file post-processing. Previously this was presented ad hoc to unblock users, but the lack of documentation appears to have caused confusion and frustration (see #5301).
Closes #5301
> [doc] Document usage of post-process file feature

- modules/openapi-generator/src/main/resources/go-server/model.mustache
- samples/server/petstore/go-api-server/go.sum
Hello, in the golang server, the model template seems to be broken when we use dot in openapi tags.
For example, for this Openapi input : https://forge.etsi.org/rep/mec/gs011-app-enablement-api/blob/master/MecAppSupportApi.yaml 
The current output is : 
```
package openapi
// DestinationInterfaceInterfaceType : Type of the interface
type DestinationInterface.InterfaceType string
// List of DestinationInterface.InterfaceType
const (
DESTINATIONINTERFACEINTERFACETYPE_TUNNEL DestinationInterfaceInterfaceType = "TUNNEL"
DESTINATIONINTERFACEINTERFACETYPE_MAC DestinationInterfaceInterfaceType = "MAC"
DESTINATIONINTERFACEINTERFACETYPE_IP DestinationInterfaceInterfaceType = "IP"
)
```
I change from {{{name}}} to {{{classname}}}, to have the enum matching the declaration ( i.e, removing the dot) …
> Remove dot in golang type

- modules/openapi-generator/src/main/resources/go-experimental/api.mustache
- samples/client/petstore/go-experimental/go-petstore/api_another_fake.go
- samples/client/petstore/go-experimental/go-petstore/api_fake.go
- samples/client/petstore/go-experimental/go-petstore/api_fake_classname_tags123.go
- samples/client/petstore/go-experimental/go-petstore/api_pet.go
- samples/client/petstore/go-experimental/go-petstore/api_store.go
- samples/client/petstore/go-experimental/go-petstore/api_user.go
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/api_usage.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_another_fake.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_default.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_fake.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_fake_classname_tags123.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_pet.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_store.go
- samples/openapi3/client/petstore/go-experimental/go-petstore/api_user.go
- Add `structPrefix` support to go-experimental
> Add structPrefix support to go-experimental

- docs/new-generator.md
- modules/openapi-generator/src/main/resources/META-INF/services/org.openapitools.codegen.CodegenConfig
- new.sh
We've moved away from script based iterative generation to config based generation. This allowed us to move away from the "ensure script" process taking 30+ minutes for contributors to taking as few as 1-2 minutes. It also allows us to reuse the configurations for golden samples in the plugins for easier testing of outputs.
cc @OpenAPITools/openapi-generator-core-team
> [doc] Update new-generator steps (new.sh)

- modules/openapi-generator/src/main/resources/cpp-ue4/api-source.mustache
Very simple change to the api template for cpp-ue4 to handle an API that respond without any content (for instance if it responds with a single 200 to indicate success).
Sadly, there are no test config for cpp-ue4 (yet?). I tested the change directly inside the UE4 project we have in which we are using openapi-generator (as it's a proprietary game I cannot share it obviously, but the resulting code did compîle well).
@ravinikam @etherealjoy @martindelille @muttleyxd @Kahncode
> [cpp-ue4] add support for empty response

- modules/openapi-generator/src/main/resources/Java/libraries/resteasy/pom.mustache
The jackson-datatype-jsr310 dependency is imported twice when the java8 option is enabled. As the dependency is also imported unconditionally I removed the conditional one.
- [ x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x ] Run the shell script `./bin/generate-samples.sh`to update all …
> [Java][Resteasy] Remove duplicate jackson-datatype-jsr310 dependency

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue7262.yaml
We have an open issue where an allOf composed schema with an inline definition makes the openapi codegen throw an exception.
This PR updates our code to skip over those inline schemas
So now the exception is not thrown
Fixes https://github.com/OpenAPITools/openapi-generator/issues/7262
Core Team:
@wing328 (2015/07)
@jimschubert (2016/05)
@ackintosh (2018/02)
@jmini (2018/04)
@spacether (2020/05)
> Adds fix for issue7262 and a test of it

- modules/openapi-generator/src/main/resources/python/exceptions.mustache
- modules/openapi-generator/src/main/resources/python/rest.mustache
- samples/client/petstore/python-asyncio/petstore_api/exceptions.py
- samples/client/petstore/python-tornado/petstore_api/exceptions.py
- samples/client/petstore/python/petstore_api/exceptions.py
- samples/client/petstore/python/petstore_api/rest.py
- samples/openapi3/client/petstore/python/petstore_api/exceptions.py
- samples/openapi3/client/petstore/python/petstore_api/rest.py
Subclasses Python exceptions as outlined in #2151:
- `UnauthorizedException` (401)
- `ForbiddenException` (403)
- `NotFoundException` (404)
- `ServiceException` [500 - 599]
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)
> Subclass Python exceptions

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue7356.yaml
- Adds validation properties for array models
- Fixes #7356
- Adds a test which verifies that a validation on an array schema is present in the array model
> Syncs validation properties for arraymodels

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/swift5/Swift5ClientCodegenTest.java
- modules/openapi-generator/src/test/resources/bugs/Swift5CodeGenerationStackOverflow#2966.yaml
To fix #2966.
The Crash occurs in Swift5 and Swift4 CodeGeneration. 
swift4 has been marked as deprecated, so I only fixed the Swift5CodeGeneration.
UnitTest: crashSwift5ExampleCodeGenerationStackOverflowTest()
> Bugfix swift5 code generation 2966

- modules/openapi-generator/src/main/resources/dart2/api_client.mustache
- modules/openapi-generator/src/main/resources/dart2/auth/api_key_auth.mustache
- samples/client/petstore/dart2/petstore_client_lib/lib/auth/api_key_auth.dart
Issue #7344
This modifies `api_client.mustache` and `api_key_auth.mustache` to allow an option of `cookie` for location of apiKey.  To test, you can create a security schema such as:
```yaml
securitySchemes:
ExampleCookieAuth:
type: apiKey
in: cookie
name: session
```
This should send a `Cookie` header up to server with semi-colon separated auth keys/values e.g.:
`Cookie: session=12345; otherAuthKey=abcdef`
> Adds cookie auth support to ApiKeyAuth in dart2 templates

- modules/openapi-generator/src/main/resources/powershell/http_signature_auth.mustache
- samples/client/petstore/powershell/src/PSPetstore/Private/PSHttpSignatureAuth.ps1
for HTTPSigning  [System.Security.Cryptography.RSACng]::new() is not supported on linux and mac os so replacing it with [System.Security.Cryptography.RSA]::Create()  
@wing328
> RSACng class is not supported on linux replacing it by RSA

- modules/openapi-generator/src/main/resources/r/api_client.mustache
- samples/client/petstore/R/R/api_client.R
Adding retry configuration that can be set on ApiClient.
CC @wing328 , @saigiridhar21
> feat(r): retry configuration for status codes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
> Properly decode $ref

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/TypeScriptAxiosClientCodegenTestTest.java
fixes #7369
Enum values are generated incorrectly for PascalCase enum property naming type when the source enum values are in uppercase with underscores.
> [typescript] Fix incorrect enum literal case

- docs/customization.md
- docs/templating.md
closes #4909
cc @OpenAPITools/generator-core-team just an fyi
> [docs] Add notes on Windows classpath modification

- modules/openapi-generator/src/main/resources/cpp-ue4/api-source.mustache
Change to the api template for cpp-ue4 to handle a composite Content-Type (for instance application/json; charset=utf-8) by comparing the start of the string instead of looking for a perfect match.
Sadly, there are no test config for cpp-ue4 (yet?). I tested the change directly inside the UE4 project we have in which we are using openapi-generator (as it's a proprietary game I cannot share it obviously, but the resulting code did compile well).
@ravinikam @etherealjoy @MartinDelille @muttleyxd @Kahncode
> [cpp-ue4] add support for Content-Type containing charset

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientExperimentalTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7372.yaml
We have a bug in master branch where this schema:
```
A:
type: object
$ref: '#/components/schemas/B'
```
Is incorrectly interpreted as FreeFormObject when it should be a MapSchema
Per our java documentation a schema is FreeForm if:
```
A free form object is an object (i.e. 'type: object' in a OAS document) that:
1) Does not define properties, and
2) Is not a composed schema (no anyOf, oneOf, allOf), and
3) additionalproperties is not defined, or additionalproperties: true, or additionalproperties: {}.
```
Schema A does not satisfy requirement 3. Requirement 3 only allows additionalproperties  values of null, true, and empty object {}. We have {$ref: '#/components/schemas/B'} which is different.
This PR fixes that bug by making sure that when we are in …
> Fixes isFreeFormObject detection

- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/config/DynamicSettingsTest.java
Use the canonical path of `templateDir` instead of absolute path in order to get rid of `..` when specifying a relative templateDir like `-t ../../templates` in the command line, and avoid raising the new exception introduced in #6598: `IllegalArgumentException("Template location must be constrained to template directory.")`
> [core] Use canonical path for template dir

- modules/openapi-generator/src/main/resources/ruby-client/api.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api/another_fake_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/default_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/fake_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/fake_classname_tags123_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/pet_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/store_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/user_api.rb
- samples/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
- samples/client/petstore/ruby/lib/petstore/api/default_api.rb
- samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
- samples/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
- samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
- samples/client/petstore/ruby/lib/petstore/api/store_api.rb
- samples/client/petstore/ruby/lib/petstore/api/user_api.rb
- rename debugging variables by adding the `debug_` prefix
- minor formatting fix to avoid trailing spaces
> [Ruby] rename debugging variables

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
This change adjusts the kotlin openhttp api template to ignore null headers when building the request rather than convert them to "null" string
> [kotlin] Fix optional header params in openhttp client

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript-node/api-single.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypeScriptNodeClientCodegenTest.java
Issue: Resolves https://github.com/OpenAPITools/openapi-generator/issues/7385
> For mapping such as:
> ```
>   "importMappings": {
>     "Pet": "../dataModel/petModel"
>   }
> ```
> **Actual**
> ```
> import { AModelPetModel } from '../../dataModel/petModel';
> ```
> **Expected**
> ```
> import { Pet } from '../dataModel/petModel';
> ```
> 
> For a mapping such as:
> ```
>   "importMappings": {
>     "Pet": "@company/prefix-zoo-store"
>   }
> ```
> 
> **Actual**
> ```
> import { NyPrefixZooStore } from '../@company/prefix-zoo-store';
> ```
> **Expected**
> ```
> import { Pet } from '@company/prefix-zoo-store';
> ```
Below is the map in `operations.get("imports")` based on the import location:
_Model is created by generator_
```
[{import=model/pet, classname=Pet}]
```
_BYOModel_
``` …
```
> [bug][typescript] Fix node client generator import file paths

- modules/openapi-generator/src/main/resources/php/Configuration.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Configuration.php
When spec server doesn't contain variables I got error in php client:
> Notice: Undefined index: variables in /Users/ybelenko/Sites/php-client/api-client/php/Configuration.php on line 473
cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @renepardon
> [php] Fix bug undefined index: variables

- .github/workflows/sonar.yml
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
- modules/openapi-generator-maven-plugin/pom.xml
- modules/openapi-generator-online/pom.xml
Minor adjustments to sonar scanning…
* Exclude maven plugin from test coverage reporting
* Exclude online project from test coverage reporting
* Use `-nsu` to prevent scanner from pulling the `-SNAPSHOT` artifact from last master build, and use jars published locally
* Update to use Java 11 as Sonar will stop supporting publishing reports built via Java 8 soon
cc @OpenAPITools/generator-core-team as fyi
> [sonar] Java 11, use -nsu, exclude maven/online projects

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/ChildCat.md
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ChildCat.cs
- samples/openapi3/client/petstore/java/jersey2-java8/docs/ChildCat.md
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/ChildCat.java
- fix port in the Ruby client (e.g. https://localhost:3000 will result in the `:3000` omitted in the host in the Ruby client)
> [Ruby] fix port in the Ruby client

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
Simply adds a type for AnyType for Rust codegen. I can see that this is present for other languages, so is really just filling a missing piece:
```
$ rg '"AnyType"'
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
1451:        typeMapping.put("AnyType", "oas_any_type_not_mapped");
2082:            return "AnyType";
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
130:        typeMapping.put("AnyType", "mixed");
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
178:        typeMapping.put("AnyType", "Object");
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
173: …
```
> Fix Rust codegen for AnyType

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaVertXWebServerCodegen.java
- Use typeMapping instead of postProcessParameter to map UUID, Date, DateTime into String
> [Java][vertx] Use typeMapping instead of postProcessParameter

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- modules/openapi-generator/src/main/resources/typescript-axios/configuration.mustache
- samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
- samples/client/petstore/typescript-axios/builds/composed-schemas/configuration.ts
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/default/configuration.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/configuration.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/configuration.ts
Signed-off-by: Peter Somogyvari <peter.metz@unarin.com>
Added an optional parameter to the constructor parameters of the `Configuration` class so that a user defind `FormData` constructor can be injected in execution environments where `FormData` is not supported by default (e.g. NodeJS).
This issue is tracking the same problem which I also had and thus this PR was born:
https://github.com/OpenAPITools/openapi-generator/issues/2939 
I tested it by using the generator on a [project](https://github.com/hyperledger/cactus) I'm a maintainer of where we use the tool (thank you very much for the all your work)
What this enables is code like this in my NodeJS test cases:
```typescript
import FormData from "form-data";
const configuration: Configuration = new Configuration({
formDataCtor: …
```
> feat(typescript-axios): injectable FormData

- modules/openapi-generator/src/main/resources/typescript-axios/modelEnum.mustache
- modules/openapi-generator/src/main/resources/typescript-axios/modelGeneric.mustache
`x-enum-varnames` was already supported but `x-enum-descriptions` was not.
refs #1693 #1752
https://github.com/OpenAPITools/openapi-generator/blob/master/docs/templating.md#enum
> [typescript-axios] support "x-enum-descriptions"

- modules/openapi-generator/src/main/resources/python/python-experimental/__init__api.mustache
- modules/openapi-generator/src/main/resources/python/python-experimental/__init__apis.mustache
- modules/openapi-generator/src/main/resources/python/python-experimental/api_client.mustache
- samples/client/petstore/python-experimental/petstore_api/api/__init__.py
- samples/client/petstore/python-experimental/petstore_api/api_client.py
- samples/client/petstore/python-experimental/petstore_api/apis/__init__.py
- samples/openapi3/client/extensions/x-auth-id-alias/python-experimental/x_auth_id_alias/api/__init__.py
- samples/openapi3/client/extensions/x-auth-id-alias/python-experimental/x_auth_id_alias/api_client.py
- samples/openapi3/client/extensions/x-auth-id-alias/python-experimental/x_auth_id_alias/apis/__init__.py
- samples/openapi3/client/features/dynamic-servers/python-experimental/dynamic_servers/api/__init__.py
- samples/openapi3/client/features/dynamic-servers/python-experimental/dynamic_servers/api_client.py
- samples/openapi3/client/features/dynamic-servers/python-experimental/dynamic_servers/apis/__init__.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/api/__init__.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/api_client.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/apis/__init__.py
- replaced hardcoded PetApi with actual values from the OpenAPI spec.
> [python][experimental] remove hardcoded PetApi

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GroovyClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
Fixes #7434 
When generating on Windows, some outputs may look like:
```
main.java.srcDirs = ['src/main\java']
```
That's wrong and this fixes the issue. Common strings like `src/main/java` shouldn't be treated like a path; if it's used to write files then it's the responsibility of the template manager, if it's used in Gradle outputs then it's Gradle's responsibility to normalize the path for the given OS.
cc java technical committee
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda
> [java][groovy] Fix mangled src paths in some outputs on Windows

- bin/generate-samples.sh
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/GenerateBatch.java
This provides a means to fully remove files which were previously generated. This adds a `--clean` option to the CLI's batch command. This is not done by default in the ensures script, but can be enabled via:
```
export BATCH_OPTS="--clean"
```
Functionally, this loops over each line in the target directory's `.openapi-generator/FILES` file, verifies that the file is below the target directory, and deletes it.
This is implemented only in the `batch` command for now, and we can include elsewhere if people would like.
This will allow closing out PR #3479 
> [batch] Option to clean files before generation

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
PowerShell does not treat \(backslash) as escape character. hence no need to replace \\ to \\\\
@wing328
> [PowerShell] fixed the backslash issue

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/FsharpGiraffeServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellHttpClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFExtServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaHttpServerCodegen.java
This fixes a handful of potential bugs as documented [in sonar](https://sonarcloud.io/project/issues?id=OpenAPITools_openapi-generator&resolved=false&types=BUG).
> [ci] Sonar bug fixes

- modules/openapi-generator/src/main/resources/objc/model-body.mustache
This fixes https://github.com/OpenAPITools/openapi-generator/issues/6587.
--> `openapi-generator-gradle-plugin (maven wrapper) .... FAILURE` on Mac OS, is this supposed to work from Maven? Surely this is not related to the changes made.
--> Did not cause any changes.
--> There is no technical committee responsible for Objective-C.
> Update of Objective-C model-body.mustache to support discriminator.mappedModels

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFExtServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api/usage_api.rb
Wraps a couple potential NPEs in null checks.
> [sonar][ci] Fixes some new recommended "bug" fixes found via Sonar

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- minor formatting change
cc @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)
> [Rust][Server] minor formatting change

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Fixes #4069
The jira openapi spec includes "~=" as a value of an enum. This change ensures it gets stringified correctly.
You can see the problem by performing Rust codegen on https://developer.atlassian.com/cloud/jira/platform/swagger.v3.json:
```
$ java -jar openapi-generator-cli.jar generate -i $jiraspecpath -o jira-openapi -g rust --library reqwest --additional-properties packageName=jira-openapi
$ grep -A100 'pub enum Operator' jira-openapi/src/models/field_value_clause.rs
pub enum Operator {
#[serde(rename = "=")]
Equal,
#[serde(rename = "!=")]
Not_Equal,
#[serde(rename = ">")]
Greater_Than,
#[serde(rename = "<")]
Less_Than,
#[serde(rename = ">=")]
Greater_Than_Or_Equal_To,
#[serde(rename = "<=")]
Less_Than_Or_Equal_To,
#[serde(rename = "in")]
_In,
#[serde(rename = "not in")] …
```
> Fix stringifying of ~= in enums

- modules/openapi-generator/src/main/resources/powershell/README.mustache
- modules/openapi-generator/src/main/resources/powershell/api_doc.mustache
- modules/openapi-generator/src/main/resources/powershell/model_doc.mustache
- samples/client/petstore/powershell/README.md
- samples/client/petstore/powershell/docs/ApiResponse.md
- samples/client/petstore/powershell/docs/Category.md
- samples/client/petstore/powershell/docs/InlineObject.md
- samples/client/petstore/powershell/docs/InlineObject1.md
- samples/client/petstore/powershell/docs/Order.md
- samples/client/petstore/powershell/docs/PSPetApi.md
- samples/client/petstore/powershell/docs/PSStoreApi.md
- samples/client/petstore/powershell/docs/PSUserApi.md
- samples/client/petstore/powershell/docs/Pet.md
- samples/client/petstore/powershell/docs/Tag.md
- samples/client/petstore/powershell/docs/User.md
- samples/client/petstore/powershell/src/PSPetstore/Model/Category.ps1
This PR has following changes 
- Added the httpsigning code snippet for api doc
- Fix the typos Invoker-Pester  , Convert-ToJson
- Update the model doc.
@wing328
> [powershell] Updated the Api doc with httpsiging script snippet.

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/list.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/list.h.mustache
- samples/client/petstore/c/include/apiClient.h
- samples/client/petstore/c/include/list.h
- samples/client/petstore/c/src/apiClient.c
- samples/client/petstore/c/src/list.c
There is a special API design: 
When the client issues a http request, http server will block the request ( does not return to client ), and write some data to stream to client continuously. 
e.g. 
In kubernetes, when client issues a ```watch``` request, kube-apiserver will block this request, but write the watch event data to the stream to client once there is new event such as pod creation/deletion. Client needs to read and handle these event data.
But for now, c generator does not support this mode because ```apiClient_invoke``` and ```writeDataCallback``` have no chance to access the raw data if the request is blocking.
This PR adds a ```data_callback_func``` to ```writeDataCallback```, if it is not NULL, it will be called to access the data received. By this means, user can inject a …
> [C][Client]Support data callback function

- modules/openapi-generator/src/main/resources/swift5/api.mustache
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/AnotherFakeAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeClassnameTags123API.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/StoreAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/UserAPI.swift
@jgavris @ehyche @Edubits @jaz-ah @4brunu
> [Swift5] Fixed spelling for `promise` in the generated code.

- modules/openapi-generator/src/main/resources/apex/OAS.cls
- samples/client/petstore/apex/force-app/main/default/classes/OAS.cls
openapi-generator/modules/openapi-generator/src/main/resources/apex/OAS.cls
If you send a response that contains anything in addition to "application/json" nothing is returned.
Set the toReturnValue to validate for more than just application/json e.g. UTF-8 within the Content Type.
To fix #7500
> [Apex] better handling of different content-type in the response

- samples/client/petstore/php/OpenAPIClient-php/tests/PetApiTest.php
Fix PHP test using a proper getter: `$pet->getStatus()`
> Fix PHP test using a proper getter

- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/urlsessionLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
While trying to implement @4brunu suggestion for token refresh ( https://github.com/OpenAPITools/openapi-generator/issues/5462#issuecomment-592417371 ), with an access token configured in customHeaders with key "Authorization", I noticed that after changing the value in the customHeaders in the TokenRefresher, and then calling `shouldRetry(true)`, the following call would still use the old access token value. 
Looking into the issue I noticed that the new value (set via `MyAPI.customHeaders.updateValue(accessToken, forKey: "Authorization")` before calling `shouldRetry(true)` was being overwritten with the old one stored in self.headers in the `createURLRequest` function defined in URLSessionImplementations.swift.
The proposed change creates the new headers for the modifiedRequest by …
> [Swift5][URLSession] Fix handling of customHeaders between retries

- modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
- modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
- modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Configuration.cs
- samples/client/petstore/javascript-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise-es6/src/ApiClient.js
- samples/client/petstore/php/OpenAPIClient-php/lib/Configuration.php
- samples/client/petstore/php/OpenAPIClient-php/tests/ConfigurationTest.php
- samples/client/petstore/ruby-faraday/lib/petstore/configuration.rb
- samples/client/petstore/ruby/lib/petstore/configuration.rb
- samples/openapi3/client/petstore/go/go-petstore/api/openapi.yaml
- samples/openapi3/client/petstore/go/go-petstore/configuration.go
- samples/openapi3/client/petstore/java/jersey2-java8/api/openapi.yaml
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/python/petstore_api/configuration.py
- Add server URL without variables to the test spec to ensure the code works without variables defined.
FYI. @OpenAPITools/generator-core-team
> Add server URL without variables to the test spec

- modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache
- modules/openapi-generator/src/main/resources/typescript/model/model.mustache
- samples/openapi3/client/petstore/typescript/builds/default/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/deno/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/models/ObjectSerializer.ts
Due to the fact that the consolidated typescript template was forked from master so long ago, there are still some bugs left that where fixed for other typescript generators in the meantime. This is one of them.
This fixes #665 for the consolidated typescript generator. (With [sample definition](https://github.com/OpenAPITools/openapi-generator/issues/665#issuecomment-408769117))
The issue there is, that top-level enum schemas, which are not nested as attributes of other schemas are just generated as normal object schemas, which is not suited to represent the different allowed values.
Original fix for typescript-node was in PR #2266, merged as 8417c5bed0e23764dc841816c2322cf7dc4e9b0d in version 4.1.0.
CC: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) …
> [typescript] Fix generation of enum models

- modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
- samples/client/petstore/javascript-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise-es6/src/ApiClient.js
I am using "custom" auth method (basically I need to generate new JWT every request). The easiest way to do it is to use custom accessToken function instead of string. My idea for solving this problem came from similiar code in typescript-axios client:
https://github.com/OpenAPITools/openapi-generator/blob/8c78f13a4180d7e49b63afe61bb35627260bee4e/samples/client/petstore/typescript-axios/builds/es6-target/api.ts#L281-L286
> [JS] Allow auth.accessToken to be either function or string

- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
swagger-parser has the potential to return null
for messages which will throw NPE on
initialization of the  validationMessages hashset.
rather that allow this to happen we will assume
that a null message collection represents an empty
collection and continue.
Fixes #7453
This prevents a null pointer exception when the swagger-parser library returns a null on `getMessages()`. Rather than instantiate the validation HashSet with null, we will pass an empty list.
In my case I was experiencing this null pointer exception because swagger-parser has a bug which returns null for all fields when parameters are not passed in.
While this does not fix that issue, it allows a much more friendly run time exception to be thrown that states 
`Exception in thread "main" java.lang.RuntimeException: missing …
> [FIX][CLI] handle null result messages

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7193.yaml
This PR fixes #7193 generation of multiple oauth flows as it should be possible to do so by [specification](https://swagger.io/docs/specification/authentication/oauth2/)  
cc: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)
> [core] Enable multiple oauth2 flows

- modules/openapi-generator-maven-plugin/README.md
- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
The global properties option replaced system properties in 4.x. Maven has always had the incorrectly named `environmentVariables`.  This updates the maven plugin to align with the proper naming by issuing a warning for removal in 5.1.0
> [maven] environmentVariables ->  globalProperties

- bin/utils/ensure-up-to-date
Based on discussions in slack, this clarifies in the script echo that we run against merge commits.
cc @spacether
> [ci] Clarify wording in ensure script output

- modules/openapi-generator/src/main/resources/ruby-client/gemspec.mustache
- samples/client/petstore/ruby-faraday/petstore.gemspec
- samples/client/petstore/ruby/petstore.gemspec
- samples/openapi3/client/features/dynamic-servers/ruby/dynamic_servers.gemspec
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/petstore.gemspec
- Set default Ruby version to 2.4
- Set faraday version to 1.0.1
> Update default ruby, faraday versions

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartJaguarClientCodegen.java
- modules/openapi-generator/src/main/resources/dart/api_client.mustache
Leftover after removal of dart1, it's always set to false, can be removed.
> [Dart] Remove redundant browserClient

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
Map `AnyType` to `Object` in C# generators
> Add AnyType support to C# generators

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java
fixes #7322
Kotlin escaping should follow similar pattern to other generators, by escaping the regex sanitization before language-specific sanitize.
cc @agilob 
cc @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m
> [bug][kotlin] Better escaping of var names

- docker-entrypoint.sh
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/GenerateBatch.java
When you use the very usefull `batch` subcommand you can't use docker on npm wrapper.
https://openapi-generator.tech/docs/usage/#batch
NPM CLI Wrapper use `help` subcommand to validate possibles arguments https://github.com/OpenAPITools/openapi-generator-cli/blob/master/apps/generator-cli/src/app/services/pass-trough.service.ts#L21 so you get an error `error: unknown command 'batch'` when you use it.
In some cases, Docker image also could forbid usage of `batch`.
I will open a PR in https://github.com/OpenAPITools/openapi-generator-cli to propose usage of `completion` in place of `help` to check possible commands, but I think `batch` should no be hidden in help.
> Expose batch subcommand

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java
- samples/client/petstore/ruby-faraday/docs/EnumTest.md
- samples/client/petstore/ruby-faraday/lib/petstore/models/enum_test.rb
- samples/client/petstore/ruby/docs/EnumTest.md
- samples/client/petstore/ruby/lib/petstore/models/enum_test.rb
Default values for referenced schemas weren't being set. This fixes it. Also uses the constant definition for enum default values instead of the plain value
cc @cliffano (2017/07) @zlx (2017/09) @autopp (2019/02) @jimschubert @wing328
> [ruby] fix default value for referenced schemas and enums

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- modules/openapi-generator/src/main/resources/php/api.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
Continuation on #7376, fixes two small code issues and a single code style issue.
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) heart, @ybelenko (2018/07), @renepardon (2018/12)
> [PHP] Small tweaks for php generator, PHPStan level 1

- modules/openapi-generator/src/main/resources/csharp-netcore/HTTPSigningConfiguration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/HTTPSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/HTTPSigningConfiguration.cs
Fix warnings in HTTPSigningConfiguration class
FYI. @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02)
> [C#][netcore] Fix warnings in HTTPSigningConfiguration

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7613.yaml
- samples/openapi3/client/petstore/python-experimental/.openapi-generator/VERSION
Right now the master branch does not store the validations for array schema items for some classes
This PR fixes that issue, validations in items are now accessible on the CodegenProperty items instance.
This PR
- adds an items property to Java classes which store Schema info
- the items property stores a CodegenProperty of the items of the current type Array schema
- adds an isModel property so the generator can tell if the schema is a model or not
- the intention is to have isModel be true for codegenModels or Schemas that ref codegenModels
- that way generators will know to stop moving through schemas and use that one if it is a refed model
If merged, this will be a partial fix for https://github.com/OpenAPITools/openapi-generator/issues/7613
- it is up to the generators to set this …
> Adds missing items property to Java classes which store Schema info

- modules/openapi-generator/src/main/resources/elixir/api.mustache
- samples/client/petstore/elixir/lib/openapi_petstore/api/fake.ex
Closes #5234 
This PR will map an optional body param, given by the static key `body` to the request body. This makes it relatively transparent to read what actually happens, instead of "mapping the title" in the optional param. This is also the default behavior for primitiv types.
cc: @wing328 I'm sorry it's you again :see_no_evil:
> [Elixir] Fixes optional body mapping

- modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_setattr_getattr_composed.mustache
- modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_setattr_getattr_normal.mustache
- samples/client/petstore/python-experimental/petstore_api/model_utils.py
- samples/openapi3/client/extensions/x-auth-id-alias/python-experimental/x_auth_id_alias/model_utils.py
- samples/openapi3/client/features/dynamic-servers/python-experimental/dynamic_servers/model_utils.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model_utils.py
Allow to check for attribute presence in model using `in` operator.
Unless I'm missing something, right now the only way to correctly get an attribute which may not be present is this:
try:
attr_value = instance.attr_name
except ApiAttributeError:
attr_value = None
which is quite cumbersome.
@spacether
> [python-experimental] implement `in` operator for model classes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java
Resolves problems related to '....Module not found: Error: Can't resolve './AnyType' in...' errors when attempting to use generated Javascript code. Original regression at #6091
CC: @CodeNinjai @frol @cliffano
> Add AnyType mapping of Object to Javascript codegen

- modules/openapi-generator/src/main/resources/Javascript-Apollo/model_test.mustache
- modules/openapi-generator/src/main/resources/Javascript/es6/model_test.mustache
Looks like this did not get propagated to these other JS clients from the original at 90859575ebfea800dde93a498e1439011963d6cf
CC: @CodeNinjai @frol  @cliffano
> Fix typos in Javascript test clients 'instane' to 'instance'

- modules/openapi-generator/src/main/resources/powershell/api_client.mustache
- samples/client/petstore/powershell/src/PSPetstore/Private/PSApiClient.ps1
When the server send null in response PowerShell cmdlet return as Empty string not the $null which was misleading. 
Example before fix
```powershell
PS C:\> $result = Remove-NtpPolicy  -id xxxxxxxxxxxxxx  # the cmdlet removed the resource based on id and does not return anything
#$result is string.empty not null which is not as per the value returned from the server.
PS C:\> $result -eq $null
False
$result -eq ""
True
```
Example after fix
```powershell
PS C:\> $result = Remove-NtpPolicy  -id xxxxxxxxxxxxxx  # the cmdlet removed the resource based on id and does not return anything
PS C:\> $result -eq $null
True
```
@wing328
> [PowerShell] Fixed the empty string issue when server returns null

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java
- samples/client/petstore/elixir/lib/openapi_petstore/api/pet.ex
- samples/client/petstore/elixir/lib/openapi_petstore/api/store.ex
- samples/client/petstore/elixir/lib/openapi_petstore/api/user.ex
This PR fixes the wrong typespec for mutiple return types. (Closes #3958)
It does first building and generating a list for every return type defined. Those are saved in a HashList to ensures that every defintion will only be present once.
After that, the list will be added to the existing StringBuffer and adding the `{:error, Tesla.Env.t}` at the end of the typespec.
@wing328 Since you're the only one I know here, could you do me the favor and review my changes :)?
> [Elixir] Fixes Typespec for multiple return definitions

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7651.yaml
This PR:
- Adds isDate to CodegenModel
- adds isDate getter and setter to IJsonSchemaValidationProperties
- Adds a test to ensure that isDate has the correct values on on implementing java classes
- is a feature break out for https://github.com/OpenAPITools/openapi-generator/issues/7651
Note: this is potentially a breaking change because if one is generating a model for a date schema, the current master branch sets isString in that CodegenModel to true. After this PR, isString will be False and isDate will be true, which is consistent with how date schemas are handled in these classes:
- CodegenProperty
- CodegenParameter
- CodegenResponse
Setting isString and isDate for date schemas should be consistent in these 4 classes.
Checklist
Core Team Members
@jimschubert …
> Adds isDate to CodegenModel

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7651.yaml
This PR:
Adds isDateTme to CodegenModel
adds isDateTime getter and setter to IJsonSchemaValidationProperties
Adds a test to ensure that isDateTime has the correct values on on implementing java classes
is a feature break out for #7651
Note: this is potentially a breaking change because if one is generating a model for a date-time schema, the current master branch sets isString in that CodegenModel to true. After this PR, isString will be False and isDateTime will be true, which is consistent with how date schemas are handled in these classes:
CodegenProperty
CodegenParameter
CodegenResponse
Setting isString and isDateTime for date schemas should be consistent in these 4 classes.
Core Team Members …
> Adds isDateTime to CodegenModel

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift4Codegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
Map AnyType to `Any` in Swift 4,5 generators
To close https://github.com/OpenAPITools/openapi-generator/pull/7644
cc @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)
> Add AnyType support to Swift generators

- modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
Provide array as json encoded string if argument --additional-properties=queryParamObjectFormat=json is provided to typescript-angular generator.
fixes #7620
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov, please have a look. Thanks!
> [typescript-angular] pass array as a single JSON string to url query when queryParamObjectFormat=json (fix #7620)

- modules/openapi-generator/src/main/resources/go/go.sum
- samples/client/petstore/go/go-petstore/go.sum
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/go.sum
- samples/openapi3/client/petstore/go/go-petstore/go.sum
Remove github.com/antihax/optional from go.sum as it's no longer being used in the Go (refactored) client.
> [Go] Remove github.com/antihax/optional from go.sum

- README.md
- docs/building.md
- docs/customization.md
- docs/faq-generators.md
- docs/file-post-processing.md
- docs/installation.md
- docs/integration.md
- docs/new-generator.md
- docs/online.md
- docs/templating.md
- docs/usage.md
- new.sh
- website/src/pages/index.js
- Use 3.0 spec in documentations
- update docs (how to set version)
> Use 3.0 spec in documentations, update docs 

- modules/openapi-generator/src/main/resources/csharp-netcore/api_test.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/model_test.mustache
- proper namespaces for API and model tests
- comment out model import as not all APIs have models.
> [C#][netcore] better csharp tests

- modules/openapi-generator/src/main/resources/typescript-angular/README.mustache
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-prefixed-module-name/README.md
> [Typescript][Angular] Fix generated README when using apiModulePrefix

- modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/Generator.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultGeneratorTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/haskellservant/HaskellServantCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSCXFExtServerCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
replace setConfig and setOpenApi with the
non-deprecated config / openAPI methods
Fixes N/A
Replace usages of `setOpenAPI` and `setConfig` with non-deprecated usages `config` / `openAPI`.
There also seem to be a bunch of unused deprecated methods in this package. Are these used by some third party or can these be pruned if unused?
> CHORE[CORE]: replace deprecated methods

- modules/openapi-generator/src/main/resources/Java/libraries/native/pojo.mustache
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesClass.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/MapTest.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/MixedPropertiesAndAdditionalPropertiesClass.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesClass.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/MapTest.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/MixedPropertiesAndAdditionalPropertiesClass.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesClass.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/MapTest.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/MixedPropertiesAndAdditionalPropertiesClass.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/NullableClass.java
This PR
- changes isMapContainer to isMap.
- is a feature break out for #7651
Note: This file was not updated or was added after https://github.com/OpenAPITools/openapi-generator/issues/7651
Core Team Members
@jmini (2018/04) ❤️
@spacether (2020/05)
> Changes lingering isMapContainer to isMap

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/IReadableConfiguration.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/README.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/README.md
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/ConfigurationTests.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/IReadableConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/README.md
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Configuration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/IReadableConfiguration.cs
- add proxy support to the C# NetCore clients
> [c#][netcore] add proxy support

- .github/workflows/check-supported-versions.yaml
This adds the Maven integration tests to the Check Supported Java
Versions job which runs on master.
Maven on Windows was previously broken with templateDirectory. This was
fixed previously in a pull request, but the Maven plugin integration
testing did not work in our other CI vendors. This was tested and
verified in a private repo. The difference is likely due to vCPUs
available in GitHub Workflows differing from other free CI we use
elsewhere.
> [maven] Run integration on master checks

- modules/openapi-generator/src/main/resources/ocaml/model.mustache
It's not covered by generated tests. Maybe I can add one?
fix #7738
ping @cgensoul
> [Ocaml] Fix missing space on models

- modules/openapi-generator/src/main/resources/csharp-netcore/HttpSigningConfiguration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
Fixed the HTTPSigning to calculate the request body digest without CamelCase.
This fix is done in context to the PR  
https://github.com/OpenAPITools/openapi-generator/pull/7583
@wing328
> [C#][netcore]Fixed the HTTPSigning to calculate the body diegest without CamelCase

- modules/openapi-generator/src/main/resources/csharp-netcore/AbstractOpenAPISchema.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/modelOneOf.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/JSONComposedSchemaTests.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/AbstractOpenAPISchema.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Fruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/FruitReq.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Mammal.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/NullableShape.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Pig.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Quadrilateral.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Shape.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/ShapeOrNull.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Triangle.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/AbstractOpenAPISchema.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Fruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/FruitReq.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Mammal.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/NullableShape.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Pig.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Quadrilateral.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Shape.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ShapeOrNull.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Triangle.cs
- Add nullable support to oneOf models
> [C#][netcore] Add nullable support to oneOf models

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppTizenClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7613.yaml
Adds additional properties to core schema classes
This is a feature break out for additionalProperties for https://github.com/OpenAPITools/openapi-generator/issues/7613
Core Team:
@jmini (2018/04) ❤️
@spacether (2020/05)
> Adds additionalProperties to core schema classes

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
This is a followup to #7376, #7528, trying to get the generated code quality up to a standard where strong static analysis tools like PHPStan, Psalm can be used to verify the generated output in CI.
This reaches level 3 for PHPStan (0 is most lax, 8 is most strict), level 7 for Psalm (8 is most lax, 1 is most strict).
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) heart, @ybelenko (2018/07), @renepardon (2018/12)
> Small tweaks for php generator, PHPStan level 3, Psalm level 7

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OCamlClientCodegen.java
This PR replaces '.' characters by '_' ones in generated type names. More precisely this only affects types generated in the support/Enums.ml file.
It brings us one step closer to being able to generated compilable code for https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.yaml
Fixes #7757.
> Replace '.' characters by '_' in enum type names since OCaml doesn't allow to use '.' in any kind of identifiers.

- docs/generators/android.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AndroidClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GroovyClientCodegen.java
Builds on work done in #7569, this removes JVM imports from DefaultCodegen and puts them in JVM classes where they should be. Removes unused loads introduced in #7569 for generators which populate a new map later in constructors.
cc @OpenAPITools/generator-core-team as there aren't substantial changes in any specific generators
> [core] Remove java specific imports from DefaultCodegen

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript-rxjs/index.mustache
- modules/openapi-generator/src/main/resources/typescript-rxjs/runtime.mustache
- modules/openapi-generator/src/main/resources/typescript-rxjs/servers.mustache
- samples/client/petstore/typescript-rxjs/builds/default/.openapi-generator/FILES
- samples/client/petstore/typescript-rxjs/builds/default/index.ts
- samples/client/petstore/typescript-rxjs/builds/default/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/default/servers.ts
- samples/client/petstore/typescript-rxjs/builds/es6-target/.openapi-generator/FILES
- samples/client/petstore/typescript-rxjs/builds/es6-target/index.ts
- samples/client/petstore/typescript-rxjs/builds/es6-target/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/es6-target/servers.ts
- samples/client/petstore/typescript-rxjs/builds/with-npm-version/.openapi-generator/FILES
- samples/client/petstore/typescript-rxjs/builds/with-npm-version/index.ts
- samples/client/petstore/typescript-rxjs/builds/with-npm-version/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/with-npm-version/servers.ts
- samples/client/petstore/typescript-rxjs/builds/with-progress-subscriber/.openapi-generator/FILES
- samples/client/petstore/typescript-rxjs/builds/with-progress-subscriber/index.ts
- samples/client/petstore/typescript-rxjs/builds/with-progress-subscriber/runtime.ts
- samples/client/petstore/typescript-rxjs/builds/with-progress-subscriber/servers.ts
Description of the PR
- allows the typescript-rxjs client to retrieve all server URLs defined in the spec (based on #1361)
- based on the main typescript project
_(if somebody could tell me, if typescript-rxjs is still a good idea to use or if the main typescript generator would be a better option (as it seems to use rxjs as well), I would highly appreciate it)_
> [typescript-rxjs] Added support for servers

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
Complex types need to be serialized as JSON to avoid FormData.append()
from converting them into strings through .toString().
Fixes #7658
Tested locally by running the generator against the following schema:
```
---
info:
title: Bug test case
version: "1.0"
paths:
/example:
post:
operationId: exampleOperation
requestBody:
content:
schema:
properties:
simpleValue:
type: string
fileValue:
format: binary
type: string
complexvalue:
properties:
value1:
type: number
value2:
type: string
type: object
complexvalue_with_underscores:
properties:
value_1:
type: string
value_2:
type: number
type: object
type: object
responses:
"201":
description: Created
```
This resulted in the following serialization code:
```
export interface ExampleOperationRequest { …
```
> [typescript-fetch] serialize complex type in multipart/form-data as JSON

- modules/openapi-generator/src/main/resources/php/api.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
See https://github.com/OpenAPITools/openapi-generator/issues/7563
> changed request method from protected to public

- modules/openapi-generator/src/main/resources/rust/reqwest/api_mod.mustache
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/mod.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/mod.rs
Adds Error trait impls for the common error types so that they can be chained via normal rust error handling libraries.
cc @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)
> Add impls for Error trait for Rust reqwest 

- docs/generators/python-experimental.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java
- modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_setattr_getattr_composed.mustache
- modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_setattr_getattr_normal.mustache
- modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_shared.mustache
- samples/client/petstore/python-experimental/petstore_api/model_utils.py
- samples/openapi3/client/extensions/x-auth-id-alias/python-experimental/x_auth_id_alias/model_utils.py
- samples/openapi3/client/features/dynamic-servers/python-experimental/dynamic_servers/model_utils.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model_utils.py
- samples/openapi3/client/petstore/python-experimental/tests_manual/test_fruit.py
See #7781
Add option to return None instead of raising exception when accessing unset attribute.
cc @spacether
> [python] Add option to return None instead of raising exception when accessing unset attribute

- modules/openapi-generator/src/main/resources/haskell-http-client/API.mustache
- modules/openapi-generator/src/main/resources/haskell-http-client/Core.mustache
- samples/client/petstore/haskell-http-client/lib/OpenAPIPetstore/API/Fake.hs
- samples/client/petstore/haskell-http-client/lib/OpenAPIPetstore/API/Pet.hs
- samples/client/petstore/haskell-http-client/lib/OpenAPIPetstore/API/User.hs
- samples/client/petstore/haskell-http-client/lib/OpenAPIPetstore/Core.hs
> [haskell-http-client] have applyOptionalParemeter (-&-) append values in headers or querystrings instead of replacing values

- modules/openapi-generator/src/main/resources/csharp-netcore/modelAnyOf.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/modelOneOf.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Fruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/FruitReq.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/GmFruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Mammal.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/NullableShape.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Pig.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Quadrilateral.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Shape.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/ShapeOrNull.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Triangle.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Fruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/FruitReq.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/GmFruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Mammal.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/NullableShape.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Pig.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Quadrilateral.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Shape.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ShapeOrNull.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Triangle.cs
- Use WriteRawValue instead of WriteRaw to fix serialization for nested oneOf property.
- Tested locally to confirm the bug fix.
> [C#][netcore] use WriteRawValue instead of WriteRaw

- modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs
- Use System.Environment.OSVersion in .NET standard
> [C#][netcore] Use System.Environment.OSVersion in .NET standard

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache
- samples/client/petstore/c/include/apiClient.h
- samples/client/petstore/c/src/apiClient.c
- samples/client/petstore/c/unit-tests/manual-PetAPI.c
- samples/client/petstore/c/unit-tests/manual-StoreAPI.c
- samples/client/petstore/c/unit-tests/manual-UserAPI.c
Described in libcurl official document https://curl.haxx.se/libcurl/c/libcurl.html, the functions ```curl_global_init``` and ```curl_global_cleanup``` cannot be called in multiple thread environment, or it will cause a coredump.
Following by the guide, this PR removes the 2 function calls from ```apiClient_create*``` and ```apiClient_free```,  and adds 2 new functions for user to call:
```c
/*
* In single thread program, the function apiClient_setupGlobalEnv is not needed.
* But in multi-thread program, apiClient_setupGlobalEnv must be called before any worker thread is created
*/
void apiClient_setupGlobalEnv()
{
curl_global_init(CURL_GLOBAL_ALL);
}
/*
* This function apiClient_unsetupGlobalEnv must be called whether single or multiple program.
* In …
```
> [C][Client]Fix coredump in multi-thread environment

- modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache
- modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
fixes: #7734
`download_file` doesn't work.
> [Ruby][faraday] fix download_file

- modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache
- samples/client/petstore/spring-stubs/pom.xml
- samples/server/petstore/springboot-beanvalidation-no-nullable/pom.xml
- samples/server/petstore/springboot-beanvalidation/pom.xml
- samples/server/petstore/springboot-delegate-j8/pom.xml
- samples/server/petstore/springboot-delegate/pom.xml
- samples/server/petstore/springboot-implicitHeaders/pom.xml
- samples/server/petstore/springboot-reactive/pom.xml
- samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8/pom.xml
- samples/server/petstore/springboot-spring-pageable-delegatePattern/pom.xml
- samples/server/petstore/springboot-spring-pageable-without-j8/pom.xml
- samples/server/petstore/springboot-spring-pageable/pom.xml
- samples/server/petstore/springboot-useoptional/pom.xml
- samples/server/petstore/springboot-virtualan/pom.xml
- samples/server/petstore/springboot/pom.xml
Use default jackson will fix #7743
> [Spring] Use default jackson-databind 

- docs/generators/kotlin-server.md
- docs/generators/kotlin-spring.md
- docs/generators/kotlin-vertx.md
- docs/generators/kotlin.md
- docs/generators/typescript-rxjs.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
- modules/openapi-generator/src/main/resources/kotlin-spring/dataClass.mustache
- modules/openapi-generator/src/main/resources/kotlin-spring/generatedAnnotation.mustache
* Fix generation of nested map/arrays and map/array models (code taken from AbstractJavaCodegen)
* Fix data class extension constructor (there's still an issue when parent has attributes and mutableModels is false that will need to be fixed in another PR)
* Fix generation of `@Generated` annotation
@jimschubert (2017/09) heart, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)
> [Kotlin] Fix Spring Kotlin generation of array/map models

- modules/openapi-generator/src/main/resources/csharp-netcore/HttpSigningConfiguration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
Fixed the query string issue in HttpSigning .
@wing328
> Fixed the HttpSigning issue for query string

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
Complex types need to be serialized as JSON to avoid FormData.append() from converting them into strings through .toString().
Fixes #7658 for typescript-axios
> [typescript-axios] Serialize complex type in multipart/form-data as JSON (#7658)

- modules/openapi-generator/src/main/resources/python/api_client.mustache
- samples/client/petstore/python-asyncio/petstore_api/api_client.py
- samples/client/petstore/python-tornado/petstore_api/api_client.py
- samples/client/petstore/python/petstore_api/api_client.py
- samples/openapi3/client/petstore/python/petstore_api/api_client.py
In the Python client generator we have code to detect output encoding (https://github.com/OpenAPITools/openapi-generator/pull/5679). This code checks received headers but it doesn't work if preloading content is disabled. In such situation raw response is returned (from native client library like aiohttp) and method getheader() doesn't exist. In this PR I rearrange code a little bit to work in such cases.
CC: @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)
> [python] check output content-type only if preload_content is set

- modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/HasOnlyReadOnly.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/Name.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/ReadOnlyFirst.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/JSONComposedSchemaTests.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/HasOnlyReadOnly.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Name.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/ReadOnlyFirst.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/HasOnlyReadOnly.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Name.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ReadOnlyFirst.cs
- Skip readonly properties in serialization
> [c#][netcore] Skip readonly properties in serialization

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7613.yaml
This PR adds vars and requiredVars as a feature addition for https://github.com/OpenAPITools/openapi-generator/issues/7613
We need to store vars and requiredVars to support use cases where our users include inline schema definitions.
> Adds vars and requiredVars to Schema classes

- modules/openapi-generator/src/main/resources/python/python-experimental/model_utils.mustache
- samples/client/petstore/python-experimental/petstore_api/model_utils.py
- samples/openapi3/client/extensions/x-auth-id-alias/python-experimental/x_auth_id_alias/model_utils.py
- samples/openapi3/client/features/dynamic-servers/python-experimental/dynamic_servers/model_utils.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/model_utils.py
This PR adds a check in the model_utils of the python client. This is to fix #7797 
The explicit check for None is to make sure zero value things like an empty list still get validated against something like minLength. 
Previously this check validation would fail when processing a response into a schema item that was `nullable` but also had any validation component like minItem, minLength, etc. 
- [] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
> [Python][Experimental] Skip validation if input_value is None

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov
> [typescript-axios]: Check configuration is defined in `api.ts` so it compiles with `strict` flag

- modules/openapi-generator/src/main/java/org/openapitools/codegen/ignore/CodegenIgnoreProcessor.java
There is a NullPointerException thrown when using an override ignore file with no parent.
This is not specific to a particular language; it impacts all generators.
See https://github.com/OpenAPITools/openapi-generator/issues/3356
> Fix NPE in CodegenIgnoreProcessor.java (fixes #3356)

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
A closing parenthesis was missing in apiInner.mustache, causing invalid generated api.ts in rare cases.
> [typescript-axios] Fix missing parenthesis in apiInner.mustache

- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools.Test/Model/CatTests.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/JSONComposedSchemaTests.cs
- Add test for AdditionalProperties in both child and parent
> [C#][netcore] Add test for AdditionalProperties in both child and parent

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/form-duplicated-parameter.yaml
If a form-parameter had the same name as another (header-, query-,
path-, or cookie-)parameter, a conflict could be caused (for example
in the typescript generator). This fix executes the same uniqueness-
check and renaming for form- and body-parameters as it is done for
all other parameters.
Fixes #7575
This fix has influence on all generators, however I was working with the TypeScript generator:
> Fix parameter uniqueness for form- and body-params

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- samples/client/petstore/typescript-fetch/builds/default-v3.0/models/EnumArrays.ts
- samples/client/petstore/typescript-fetch/builds/default-v3.0/models/EnumTest.ts
- samples/client/petstore/typescript-fetch/builds/default-v3.0/models/InlineObject2.ts
- samples/client/petstore/typescript-fetch/builds/default-v3.0/models/MapTest.ts
- samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Order.ts
- samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Pet.ts
- samples/client/petstore/typescript-fetch/builds/enum/models/InlineObject.ts
- samples/client/petstore/typescript-fetch/builds/enum/models/InlineResponse200.ts
Do not use cached properties for additionalProperties
This should fix the bug where additionalProperties tests are intermittently failing
Core Team Members
@jmini (2018/04) ❤️
@spacether (2020/05)
> Do not use cached properties for additionalProperties

- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- Set generateAliasAsModel to false in tests to fix github action's failure
> Set generateAliasAsModel to false in tests

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
Throw RuntimeException when the library option is not set to `urllib3` in the refactored python client generator.
```
Exception in thread "main" java.lang.RuntimeException: Only the `urllib3` library is supported in the refactored `python` client generator at the moment. Please fall back to `python-legacy` client generator for the time being. We welcome contributions to add back `asyncio`, `tornado` support to the `pyhton` client generator.
at org.openapitools.codegen.languages.PythonClientCodegen.processOpts(PythonClientCodegen.java:156)
at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:250)
at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:862)
at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
at …
```
> [python] Add warning about unsupported libraries 

- modules/openapi-generator/src/main/resources/dart2/api.mustache
- modules/openapi-generator/src/main/resources/dart2/class.mustache
- modules/openapi-generator/src/main/resources/dart2/enum.mustache
- modules/openapi-generator/src/main/resources/dart2/enum_inline.mustache
- samples/client/petstore/dart2/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/user_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/api_response.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/category.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/order.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/pet.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/tag.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/user.dart
The current implementation has a couple of problems and this pr addresses them:
1) Change `fromJson(value)` to accept a `dynamic value`.
2) Encode non-String header values using `parameterToString()` method.
3) Changed `fromJson()` to a static function, will not instantiate a new object when json == null.
@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12) @wing328 @sbu-WBT @agilob
> [DART2] A couple of bug fixes

- modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
- samples/client/petstore/javascript-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise-es6/src/ApiClient.js
PR for issue: [7910](https://github.com/OpenAPITools/openapi-generator/issues/7910)
This change modifies the mustache files to generate 
```
switch (collectionFormat) {
case 'csv':
return param.map(this.paramToString, this).join(',');
case 'ssv':
return param.map(this.paramToString, this).join(' ');
case 'tsv':
return param.map(this.paramToString, this).join('\t');
case 'pipes':
return param.map(this.paramToString, this).join('|');
case 'multi':
// return the array directly as SuperAgent will handle it as expected
return param.map(this.paramToString, this);
default:
throw new Error('Unknown collection format: ' + collectionFormat);
```
CC: @CodeNinjai @frol @cliffano @wing328
> [JS] (#7910) Fixing undefined error caused by no `this` instances

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaInheritanceTest.java
> Correct allOf with only one child schema (no discriminator)

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
Closes #7942
@jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @ybelenko, @renepardon
- [Y] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
> [php][bug] Fixes exceptions with API's with too high date-time nanosecond precision

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
As lorenzleutgeb reported in #476 two years ago, GET requests get a Content-Type header by default, which is wrong. And while it shouldn't, it can actually lead to issues with some servers. This PR changes that for java webclient. 
I only changed it for webclient as that is what I use and I was hoping that keeping the PR small would result in a faster merge. If needed for consistency I could also fix the other java clients.
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala  (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)  @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda  (2020/01)
> [java][webclient] remove default Content-Type

- modules/openapi-generator/src/main/resources/rust-server/context.mustache
Instead of using `keyParamName` of `CodegenSecurity`, a hard coded token name of "api_key_query" was used to parse API tokens in query strings.
This PR changes this string to the template value `{{{keyParamName}}}`.
Closes #7904
Technical committee: @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)
> [rust-server] Fix keyParamName not  used for query API token

- modules/openapi-generator/src/main/resources/dart2/class.mustache
Before:
```yml
schemas:
Order:
type: object
required: ["status"]
properties:
status:
type: string
enum:
- placed
- approved
- delivered
```
Would produce the following Dart code which would fail to compile (because of a missing required parameter):
```dart
OrderEnum order = OrderEnum._();
```
This PR skips the enum initialization when no default value is provided.
Also, when a minimum value was specified for a property, I think there was a comment expected to display but wasn't (because it was in a wrong section). If fixed the comment value and put it in the proper section so that it shows.
> [Dart2] Fix compile errors for required enums without default value.

- modules/openapi-generator/src/main/resources/typescript/package.mustache
- samples/openapi3/client/petstore/typescript/builds/default/package.json
- samples/openapi3/client/petstore/typescript/builds/inversify/package.json
- samples/openapi3/client/petstore/typescript/builds/jquery/package.json
- samples/openapi3/client/petstore/typescript/builds/object_params/package.json
'prepublishOnly' is run before the package is published. 'prepack' is run before the package is published and after local installation eg. via Git.
> Allows install typescript client via npm from Git

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java
- modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/javascript/JavascriptClientCodegenTest.java
- samples/client/petstore/javascript-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise-es6/src/ApiClient.js
To fix https://github.com/OpenAPITools/openapi-generator/issues/7913
Adding support for multi file upload. Also adding the option for individual CodeGens to specify a collectionFormat for CodegenParameters
* updated samples as well
See the issue for details on the implementation.
CC: @CodeNinjai @frol @cliffano @wing328
> [JS] (#7913) Adding support for multi file upload.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
This PR fixes the incompatible types error for `numberSchema` which has a default value but no `format` or the `format` is not `double` or `float`.
About issue detail, please see https://github.com/OpenAPITools/openapi-generator/issues/4612 
@wing328 @sebastien-rosset @cbornet @jeff9finger @bbdouglas @sreeshas @jfiala @lukoyanov @karismann @Zomzog @lwlee2608 @bkabrda @jfeltesse-mdsol @jcarres-mdsol @ykitamura-mdsol
> [java]Fix incompatible types error for number

- modules/openapi-generator/src/main/resources/ruby-client/model_test.mustache
The spec wrongly assumed the items in the oneOf schema were all models.
Solves the issue described in https://github.com/OpenAPITools/openapi-generator/pull/5706#issuecomment-732983709
@cliffano (2017/07) @zlx (2017/09) @autopp (2019/02) @zippolyte @wing328
> [ruby] make the generated ruby oneOf specs pass

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache
- samples/client/petstore/c/include/apiClient.h
- samples/client/petstore/c/src/apiClient.c
Hi @wing328 @zhemant @michelealbano
This is a feature enhancement.
libcurl has a mechanism of progress callback function. 
https://curl.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html
That can be used to do some operation ( e.g. display download/upload progress information ) when the transfer is in progress. 
This PR introduces this feature into c client.
It also can be used to stop an endless http(s) request. The detail can be found at https://github.com/kubernetes-client/c/pull/39
> [C][Client] Support progress function of libcurl

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/ApiClientTests.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp/OpenAPIClientNetStandard/src/Org.OpenAPITools/Client/ApiClient.cs
In this PR, I expose the JsonSerializerSettings in the ApiClient so that serialization customizations can be done. For example, in my specific use-case, I wanted to add additional Converters to change the way JSON was being deserialized back into the csharp classes.
Fixes #4241
I reviewed the comments made on this related PR #4466 and incorporated the feedback into this PR.
> Expose JsonSerializerSettings in ApiClient

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
When a model has an example in an array, it wrongly wraps it again in a list
instead of returning the list examples. This fixes it.
> Fix list examples in python

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/api_doc.mustache
- samples/client/petstore/java/google-api-client/docs/FakeApi.md
- samples/client/petstore/java/jersey1/docs/FakeApi.md
- samples/client/petstore/java/jersey2-java8/docs/FakeApi.md
- samples/client/petstore/java/jersey2-java8/docs/PetApi.md
- samples/client/petstore/java/native-async/docs/FakeApi.md
- samples/client/petstore/java/native/docs/FakeApi.md
- samples/client/petstore/java/okhttp-gson-parcelableModel/docs/FakeApi.md
- samples/client/petstore/java/okhttp-gson/docs/FakeApi.md
- samples/client/petstore/java/resteasy/docs/FakeApi.md
- samples/client/petstore/java/resttemplate-withXml/docs/FakeApi.md
- samples/client/petstore/java/resttemplate/docs/FakeApi.md
- samples/client/petstore/java/retrofit2-play26/docs/FakeApi.md
- samples/client/petstore/java/retrofit2/docs/FakeApi.md
- samples/client/petstore/java/retrofit2rx2/docs/FakeApi.md
- samples/client/petstore/java/retrofit2rx3/docs/FakeApi.md
- samples/client/petstore/java/vertx-no-nullable/docs/FakeApi.md
- samples/client/petstore/java/vertx/docs/FakeApi.md
- samples/client/petstore/java/webclient/docs/FakeApi.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/FakeApi.md
- samples/openapi3/client/petstore/java/jersey2-java8/docs/PetApi.md
- samples/openapi3/client/petstore/java/native/docs/FakeApi.md
This fixes a bunch of issues with Java examples, including:
* Adds imports to basic types
* Generate proper example for enums
* Generate useful default for OffsetDatetime
* Wrap schema examples when necessary (quotes, longs, etc).
> Improve generated Java examples

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
- samples/openapi3/client/petstore/python/docs/PetApi.md
The patch in #7967 forgot the prefix, this fixes it, and change the samples so
that we can see the effect this time.
> Fix list examples in Python (for real)

- modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/api-source.mustache
- modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/modelbase-header.mustache
- modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/modelbase-source.mustache
- samples/client/petstore/cpp-restsdk/client/ModelBase.cpp
- samples/client/petstore/cpp-restsdk/client/ModelBase.h
- samples/client/petstore/cpp-restsdk/client/api/PetApi.cpp
- samples/client/petstore/cpp-restsdk/client/api/StoreApi.cpp
- samples/client/petstore/cpp-restsdk/client/api/UserApi.cpp
- Expected Float/Double types will be deserialized even if missing the decimal point
- Add the case for application/x-www-form-urlencoded
Fixes #6994
Fixes #7751
`cc`
@MartinDelille @ravinikam @stkrwork @muttleyxd
> [cpprest] Deserialize Float without decimal point

- modules/openapi-generator/src/main/resources/php/model_generic.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/EnumArrays.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/EnumTest.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/InlineObject2.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/Order.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/Pet.php
- samples/client/petstore/php/OpenAPIClient-php/tests/EnumTestTest.php
Purpose is simple: if the property is an enum and the value in the response doesn't match the enum, print the received value in the exception, allowing spec designers to easily fix the spec.
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) heart, @ybelenko (2018/07), @renepardon (2018/12)
> feature(PHP): include the current value with enum failure

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/configuration.rb
To fix https://github.com/OpenAPITools/openapi-generator/issues/8047
TODO: will add a test case shortly
> Fix port when the URL doesn't have port specified

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- samples/openapi3/client/petstore/python/docs/FakeApi.md
When generation examples of objects with additional properties, we use the map
syntax inside a model instantiation, which is incorrect. This fixes it by
checking for model at the right place.
> Fix generation of map model examples in Python

- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
This defect is introduced by my previous PR https://github.com/OpenAPITools/openapi-generator/pull/6652.
At that PR, I converted the integer/boolean query parameter to a string, but forgot to free the memory of this string before the function returns, this will cause memory leak. 
> [C][Client] Fix memory leak when the type of query parameter in request url is integer or boolean

- modules/openapi-generator/src/main/resources/go/client.mustache
- samples/client/petstore/go/go-petstore/client.go
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go
- samples/openapi3/client/petstore/go/go-petstore/client.go
Added missing return statement to client.mustache.
To fix #8072
> [Go] Fixes missing return statement 

- modules/openapi-generator/src/main/resources/python/exceptions.mustache
- modules/openapi-generator/src/main/resources/python/rest.mustache
- samples/client/petstore/python/petstore_api/exceptions.py
- samples/client/petstore/python/petstore_api/rest.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/exceptions.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/rest.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/exceptions.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/rest.py
- samples/openapi3/client/petstore/python/petstore_api/exceptions.py
- samples/openapi3/client/petstore/python/petstore_api/rest.py
Re-merging lost commit of "Subclassing python exceptions" (#7321) by @ryanrishi after "Renames python generators" (#7965) by @wing328.
https://github.com/OpenAPITools/openapi-generator/pull/7965/files#diff-54adab86675d7379d0ce4f680369a8a1161fb5427d5dc3f58e97e06d84040f52
> [python] Re-merge Subclass Python exceptions (#7321)

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
When deleting a map in the ```*_free()``` function of a model, the original codes only free the memory for key and value of the map, but forget to free the memory of map (```keyValuePair_t```) itself. 
```list_free({{classname}}->{{name}})```  only frees the memory of each ```listEntry_t *listEntry```, does not free the map itself too.
> [C][Client] Fix memory leak when deleting a map

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
fixes https://github.com/OpenAPITools/openapi-generator/issues/8065
A user must be able to simply define the basePath as they are constructing the Service.
**Current:**
```
const healthCheckService = new HealthcheckApi({}, process.env.REACT_APP_API_ENDPOINT)
```
**Once this PR is approved:**
```
const healthCheckService = new HealthcheckApi({ basePath: process.env.REACT_APP_API_ENDPOINT })
```
> feat(config): pull the basePath from config is exists

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
Fixes #8104
The logic to update the flag was moved to `postProcessParameter`, as `op.allParams` contains a copy of the parameter, and not the reference.  
Therefore, `op.formParams` was still returning the parameters with the 'isCollectionFormatMulti' flag set to false.
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov
> [BUG][typescript-axios] Sets 'isCollectionFormatMulti' flag to true on multiple file uploads

- modules/openapi-generator/src/main/resources/python/api_client.mustache
- samples/client/petstore/python/petstore_api/api_client.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/api_client.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api_client.py
- samples/openapi3/client/petstore/python/petstore_api/api_client.py
as described in #8068 , encode object to json and add 'content-type:application/json' for sending multipart/form-data.
and checked if the request is sent to server with collect format described in #8068.
fix #8068 
@taxpon  @frol @mbohlool  @cbornet  @kenjones-cisco  @tomplus  @Jyhess @arun-nalla @spacether @wing328  @jimschubert
> Fix bug [python][client] generated python client code cannot POST object in multipart/form-data

- modules/openapi-generator/src/main/resources/python/model_utils.mustache
- samples/client/petstore/python/petstore_api/model_utils.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/model_utils.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/model_utils.py
- samples/openapi3/client/petstore/python/petstore_api/model_utils.py
Updated model_utils.mustache to pass the check_type flag into attempt_convert_item(). Failure to do so
results in type validation errors occurring when the user has specifically requested that they be disabled.
@spacether if this is not the 'right' way to fix this, then I may need some assistance with my model.  This fix works for my code.
Fixes:
https://github.com/OpenAPITools/openapi-generator/issues/8014
-  @[x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
> Fixes issue #8014, _check_type flag not being honored.

- circle.yml
- add default cache for PR as currently PR cannot recover any cache to start with
> [CircleCI] add default cache

- modules/openapi-generator/src/main/resources/swift5/modelObject.mustache
PR #6827 introduced nil values in initialisers for non-required parameters, however this behaviour overrides the default values provided to the struct. For instance, this kind of struct would be generated:
```swift
public struct ModelObject: Codable {
public var nonRequiredAttribute: String? = "defaultValue"
public init(nonRequiredAttribute: String? = nil) {
self.nonRequiredAttribute = nonRequiredAttribute
}
}
```
which would yield:
```swift
let model = ModelObject()
print(model.nonRequiredAttribute) // prints "nil" when "defaultValue" is expected
```
- Returned: `[SUCCESS] Batch generation finished 217 generators successfully.`
- @jgavris @ehyche @Edubits @jaz-ah @4brunu
> [Swift] Use default values in modelObject initializers

- modules/openapi-generator/src/main/resources/dart-dio/class.mustache
- modules/openapi-generator/src/main/resources/dart-dio/enum.mustache
- modules/openapi-generator/src/main/resources/dart-dio/enum_inline.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/model/order.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/model/pet.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/model/order.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/model/pet.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/enum_arrays.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/enum_test.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/inline_object2.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/map_test.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/model200_response.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/model_enum_class.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/model_return.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/order.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/pet.dart
* fix wrong escaped built_value serializer names
* prevent enum name collisions in inlined enums by prefixing the private built_value instances with the enum class name. This prevents clashes when multiple inline enums contain the same value - for example `EnumTest`.  No breaking changes here as all the changed fields/references are private and automatically re-generated with built_value.
There is still a lot wrong with enums but this is a small step.
> [dart][dart-dio] Enum fixes specific to Dart DIO

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
Discussed in PR https://github.com/OpenAPITools/openapi-generator/pull/8107,  this PR replaces ```free()``` with the function ```keyValuePair_free()``` to free the map itself.
> [C][Client] Update the function of releasing memory when a map is deleted

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
Fix IndexOutOfBoundsException when the spec doesn't contain any model definitions.
> Fix IndexOutOfBoundsException with no model definition

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/DartModelTest.java
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/enum_test.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/enum_test.dart
Correctly name enum variables for numeric values, e.g. `[1, -1]`.
CC @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @josh-burton  (2019/12) @amondnet (2019/12)
FYI @agilob
> [dart] Handle enumVarNames for negative names

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
* only use `FormData.fromMap()` for multipart content, `FormData` does not work with `x-www-form-urlencoded`
* use a basic map for `x-www-form-urlencoded` content
* fix formatting
--
> [dart-dio] Fix x-www-form-urlencoded body not working

- modules/openapi-generator/src/main/resources/kotlin-spring/beanValidation.mustache
- modules/openapi-generator/src/main/resources/kotlin-spring/beanValidationModel.mustache
- modules/openapi-generator/src/main/resources/kotlin-spring/dataClassOptVar.mustache
- modules/openapi-generator/src/main/resources/kotlin-spring/dataClassReqVar.mustache
- modules/openapi-generator/src/main/resources/kotlin-spring/model.mustache
- samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/model/Category.kt
- samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/model/ModelApiResponse.kt
- samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/model/Order.kt
- samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/model/Pet.kt
- samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/model/Tag.kt
- samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/model/User.kt
- samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/model/Category.kt
- samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/model/ModelApiResponse.kt
- samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/model/Order.kt
- samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/model/Pet.kt
- samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/model/Tag.kt
- samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/model/User.kt
- I do not understend how add to copy committee!! :(
To close https://github.com/OpenAPITools/openapi-generator/issues/8036
- [x ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): …
> Fix missing @Valid annotation in the nested classes

- modules/openapi-generator/src/main/resources/kotlin-spring/apiController.mustache
If the delegate is optional, put it as optional in constructor
> [kotlin-spring] Optional delegate in ApiController constructor

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
- modules/openapi-generator/src/main/resources/dart-dio/class.mustache
- modules/openapi-generator/src/main/resources/dart-dio/enum_inline.mustache
- modules/openapi-generator/src/main/resources/dart2/class.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/DartModelTest.java
- samples/client/petstore/dart-dio/petstore_client_lib/lib/model/order.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/model/pet.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/model/order.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/model/pet.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/enum_arrays.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/enum_test.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/inline_object2.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/map_test.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/order.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/pet.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/enum_arrays.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/inline_object2.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/map_test.dart
> [dart][dart-dio] More enum fixes for inner types

- modules/openapi-generator/src/main/resources/dart2/class.mustache
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/inline_object2.dart
* fix enum property with default value not being correctly generated
* simplify template expression (I know its now more complex due to the enum handling but there is only one branch for `@required` and `this.name`)
> [bug][dart] Fix enums with default value

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
fixes https://github.com/OpenAPITools/openapi-generator/issues/8176
> fix: use config basePath instead of the class context basePath

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
- modules/openapi-generator/src/main/resources/ruby-client/README.mustache
- modules/openapi-generator/src/main/resources/ruby-client/api_doc.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/RubyClientCodegenTest.java
- samples/client/petstore/ruby-faraday/docs/AnotherFakeApi.md
- samples/client/petstore/ruby-faraday/docs/DefaultApi.md
- samples/client/petstore/ruby-faraday/docs/FakeApi.md
- samples/client/petstore/ruby-faraday/docs/FakeClassnameTags123Api.md
- samples/client/petstore/ruby-faraday/docs/PetApi.md
- samples/client/petstore/ruby-faraday/docs/StoreApi.md
- samples/client/petstore/ruby-faraday/docs/UserApi.md
- samples/client/petstore/ruby/docs/AnotherFakeApi.md
- samples/client/petstore/ruby/docs/DefaultApi.md
- samples/client/petstore/ruby/docs/FakeApi.md
- samples/client/petstore/ruby/docs/FakeClassnameTags123Api.md
- samples/client/petstore/ruby/docs/PetApi.md
- samples/client/petstore/ruby/docs/StoreApi.md
- samples/client/petstore/ruby/docs/UserApi.md
- samples/openapi3/client/features/dynamic-servers/ruby/docs/UsageApi.md
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/docs/UsageApi.md
Improve ruby client examples for models, by building models with required properties set.
Goal is to have examples a bit more copy/pastable directly
Adds `constructExampleCode` methods, similarly to a few other clients like go, or powershell
> [ruby] Improve ruby client examples

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
Process all files with dart extension. Fixes https://github.com/OpenAPITools/openapi-generator/issues/6963
`"supporting-mustache"` and `"supporting-common"` no longer exists, only `"supporting-file"`. This is why some supporting files did not get post processed. But we can actually juts skip the type check and format all dart files. 
> [dart] Fix some dart files not being post processed

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- modules/openapi-generator/src/main/resources/dart2/api.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/default_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/user_api.dart
* don't rely on implicit dynamics
* add space between return type and some method names
Note: `http.Response` is not generically typed for dart but `dio.Response<Type>` is.
> [dart][dart-dio] Correctly type responses and futures

- modules/openapi-generator/src/main/resources/python/api.mustache
- modules/openapi-generator/src/main/resources/python/model_templates/method_init_shared.mustache
- modules/openapi-generator/src/main/resources/python/model_templates/method_init_simple.mustache
- samples/openapi3/client/petstore/python/petstore_api/model/additional_properties_class.py
- samples/openapi3/client/petstore/python/petstore_api/model/format_test.py
- samples/openapi3/client/petstore/python/petstore_api/model/user.py
mustache escaping the description make them render weirdly, including sometimes
unsupported characters in python.
> Include description directly in python docstrings

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
- samples/client/petstore/c/model/api_response.c
- samples/client/petstore/c/model/category.c
- samples/client/petstore/c/model/order.c
- samples/client/petstore/c/model/pet.c
- samples/client/petstore/c/model/tag.c
- samples/client/petstore/c/model/user.c
Sometimes, the model is not created completely due to some error (e.g. JSON string of a data field of the model cannot be parsed). Only a part of model is created.
At this time, we need check whether the pointer pointing to the data field is valid to avoid core-dump before releasing its memory.
> [C][Client] Fix coredump when releasing the memory of an incompleted model

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
The `additionalPropertiesType` is correctly typed as `BuiltMap<String, Type>` in all examples, with or without this change and the import is correct. 
The `jsonFormat` is unused for dart-dio.
> [dart-dio] Remove code fo additionalPropertiesType

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/default_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart
* fixes some compile errors due to header params not being of type `String`
* add optional `extra` and `validateStatus` parameters from dio to API calls
Contains the same changes as https://github.com/OpenAPITools/openapi-generator/pull/6915 and fixes compile issues for dart-dio mentioned in https://github.com/OpenAPITools/openapi-generator/issues/8179.
Regarding the concerns in #6915 about missing changes to the dart generator: 
- dart generator does not expose the header map
- the `http.Client` only handles `String` headers where as `dio` can handle `dynamic` headers and does its own serialization of headers
> [dart-dio] Allow dynamic headers and add additional dio parameters

- pom.xml
dart-dio now compiles with the OAS3 fake petstore, integration test should now be enabled to ensure this doesn't break again.
> [dart][dart-dio] Add fake petstore integration tests to master POM

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
This previous PR https://github.com/OpenAPITools/openapi-generator/pull/5255 removed not only the double url encoding, but
all url encoding. So I put back a single url encoding feature.
@bbdouglas, @sreeshas, @jfiala, @lukoyanov, @cbornet, @jeff9finger, @karismann, @Zomzog, @lwlee2608, @bkabrda
> Add previously removed url encode feature to WebClient

- modules/openapi-generator/src/main/resources/csharp-netcore/HttpSigningConfiguration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
Query string for HttpSigning has issue due peculiar behavior of HttpUtility ParseQueryString for dotnet core and dotnet47. 
- [] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
@wing328
> Fixed the query string for HttpSigning core vs dotnet47

- modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/HandlebarsEngineAdapter.java
This exposes a setting value for Handlebars' `infiniteLoops` setting value, which allows for recursive partials usage. I implemented this using the builder patter to be able to easily do something like this in a Codegen class:
```
private TemplatingEngineAdapter templatingEngine = new HandlebarsEngineAdapter().infiniteLoops(true);
```
> Expose Handlebars infiniteLoops setting

- modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
- samples/server/petstore/go-api-server/go/api_pet.go
- samples/server/petstore/go-api-server/go/api_store.go
- samples/server/petstore/go-api-server/go/api_user.go
Implementing two minor changes:
1. When extracting the parameter value use `baseName` instead of `paramName`. The two variables usually are not different, but there is a difference in case the path parameter name includes a special character like a `-`. For example in:
`/api/resource/{resource-id}`
`baseName` is equal to `resource-id`, while `paramName` is eqaul to `resourceId`. Using the latter is incorrect.
2. When failing to parse a parameter, like for example when the code expects an integer and parsing the integer fails, I would think it is more appropriate to return StatusBadParam isntead of StatusServerInternalError, because the failure was caused by the client sending invalid data and not because of an issue on the server.
> [Go][Server] Use the correct parameter name

- .travis.yml
- modules/openapi-generator/src/main/resources/typescript/index.mustache
- samples/openapi3/client/petstore/typescript/builds/default/index.ts
- samples/openapi3/client/petstore/typescript/builds/deno/index.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/index.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/index.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/index.ts
- samples/openapi3/client/petstore/typescript/tests/deno/test/api/PetApi_test.ts
> [typescript(experimental)] fix for Deno v1.6

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_8052_recursive_model.yaml
- modules/openapi-generator/src/test/resources/3_0/issue_8052_recursive_model_expected_value.txt
Added a Set<String> to the toExampleValueRecursive() method to detect circular references.
Added a watered down GeoJson API that, prior to this commit, would have thrown a StackOverflowException
Added a unit test (testRecursiveToExample()) and expected output confirming that the fix works.
@spacether this solution may be a little heavy handed.  I tried not to introduce another parameter to the toExampleValueRecursive(), but this seemed like the cleanest way to do it.
> Fixes issue 8052: Stackoverflow in toExampleValue() for python client

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
This is a very small change and not at all important: there are two spaces after `get header():` instead of just the normal one. 😄 
@leonyu
> typescript-fetch: Fix two spaces after get headers()

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
The code generated will fail to build if the default value (default is Model) is overridden using the modelPackage setting.
> [csharp-netcore] Fixed ApiClient code generation not respecting modelPackage settings

- modules/openapi-generator/src/main/resources/swift5/Cartfile.mustache
- modules/openapi-generator/src/main/resources/swift5/Podspec.mustache
- samples/client/petstore/swift5/promisekitLibrary/Cartfile
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient.podspec
- samples/client/petstore/swift5/promisekitLibrary/SwaggerClientTests/Podfile.lock
- samples/client/petstore/swift5/rxswiftLibrary/Cartfile
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient.podspec
- samples/client/petstore/swift5/rxswiftLibrary/SwaggerClientTests/Podfile.lock
This PR updates the dependencies (RxSwift and PromiseKit) in the Swift 5 generator
> [swift 5] update dependencies

- modules/openapi-generator/src/main/resources/swift5/XcodeGen.mustache
- samples/client/petstore/swift5/alamofireLibrary/project.yml
- samples/client/petstore/swift5/combineLibrary/project.yml
- samples/client/petstore/swift5/default/project.yml
- samples/client/petstore/swift5/deprecated/project.yml
- samples/client/petstore/swift5/nonPublicApi/project.yml
- samples/client/petstore/swift5/objcCompatible/project.yml
- samples/client/petstore/swift5/promisekitLibrary/project.yml
- samples/client/petstore/swift5/readonlyProperties/project.yml
- samples/client/petstore/swift5/resultLibrary/project.yml
- samples/client/petstore/swift5/rxswiftLibrary/project.yml
- samples/client/petstore/swift5/urlsessionLibrary/project.yml
Currently the Swift 5 generator supports iOS 9 as minimum supported version, but in XcodeGen the minimum iOS version supported is 10.
This PR fixes that.
> [Swift 5] fix XcodeGen deploy target to match cocoapods

- modules/openapi-generator/src/main/resources/kotlin-spring/apiDelegate.mustache
If the requestBody is not required, the current code with delegate fails because the type used in the delegate signature is non-nullable.
@jimschubert (2017/09) heart, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)
> [Kotlin-Spring] Fix optional requestBody with delegate

- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
When the path parameter name is a C/C++ keyword, e.g. ```namespace```, the generated code will escape the parameter name, e.g. ```_namespace```:
```c
snprintf(localVarPath, sizeOfPath, "/apis/apps/v1/namespaces/{namespace}/controllerrevisions");
// Path Params
long sizeOfPathParams__namespace = strlen(_namespace)+3 + strlen("{ _namespace }");
...
char* localVarToReplace__namespace = malloc(sizeOfPathParams__namespace);
sprintf(localVarToReplace__namespace, "{%s}", "_namespace");   //<--- This is not right, {_namespace} cannot replace namespace in localVarPath "/apis/apps/v1/namespaces/{namespace}/controllerrevisions"
localVarPath = strReplace(localVarPath, localVarToReplace__namespace, _namespace);
```
The ```{_namespace}``` in ```localVarToReplace__namespace``` should not be escaped, it …
> [C][Client] Disable escaping the parameter name in URL path string

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpNetCoreClientCodegenTest.java
Fixes #8212 
It seems I do not have the required permissions to perform the last step in the checklist.
> Fix csharp-netcore enum var name underscore and space handling

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
Use `Map` instead of `HashMap` for the configureApiKeys method in the Java client. This allows users to pass in whatever implementation of Map they'd like. This pattern is used elsewhere throughout the java client currently. 
This addresses an issue raised here - https://github.com/DataDog/datadog-api-client-java/issues/513
> [Java/Jersey2] Use Map interface for configureApiKeys

- .travis.yml
To fix the following:
```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
The command "docker pull swaggerapi/petstore" failed and exited with 1 during .
```
> Login dockerhub before docker pull

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/DartModelTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/dartdio/DartDioModelTest.java
* empty array dafault values are now correctly generated for dart-dio
* default arrays with values are generated empty for now, supporting arrays with values requires much more work
* date/dateTime defaults are now always null in order to prevent compile errors, this also requires much more work
Fixes https://github.com/OpenAPITools/openapi-generator/issues/8285
> [dart][dart-dio] Fix collection and date default values not compiling

- modules/openapi-generator/src/main/resources/powershell/model_simple.mustache
- samples/client/petstore/powershell/src/PSPetstore/Model/Pet.ps1
If field is boolean, the value might be $False.
The current null checking does not allow $False to be set.
@wing328
> [powershell] Fix fields null check in powershell model template

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- pom.xml
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart
This happened due to the merge of #6384 where implicit-dynamics were still allowed.
> [dart-dio] Fix failing integration tests

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/StringUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/StringUtilsTest.java
The rule to split a capitalized word with plural didn't work properly, leading
to weird name generation in a few languages. This is an attempt at fixing it.
> Tweak regexp in underscore method

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ConfluenceWikiCodegen.java
- modules/openapi-generator/src/main/resources/confluenceWikiDocs/index.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/confluencewiki/ConfluenceWikiTest.java
I recognized that enums are not documented well in confluence wiki markup. Therefore I created this PR which renders the enum values as a table in the model section. Additionaly I removed the escaping of values to make sure the text is displayed correctly in wiki (i. e. " instead of \" or with multiline comments).
Input:
```yaml
FooType:
description: >
A simple enum with:
* Multiline description
* Enum value
* Enum description
type: string
enum:
- "F-Code"
x-enum-varnames:
- FOO
x-enum-descriptions:
- The amazing foo enum
```
Output:
```md
h3. FooType
A simple enum with:
* Multiline description
* Enum value
* Enum description
||Name||Value||Description||
|FOO |"F-Code" |The amazing foo enum |
```
> [cwiki] Added Enum documentation and fix newline problem for description

- modules/openapi-generator/src/main/resources/powershell/model_simple.mustache
- samples/client/petstore/powershell/src/PSPetstore/Model/Pet.ps1
some fields may start with a "u" character which causes
Powershell to think it is a unicode escape sequence.
Fields such as `updatedAt` for example causes errors on build:
``` 
The Unicode escape sequence is not valid. A valid sequence is `u{ followed by one to six hex digits and a closing '}'.
```
@wing328
> [powershell] Fix error message templates for some field names

- docs/generators/powershell.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
> Implement optional powershell verb parsing

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
This adds missing imports for operations that have container type parameters.
Also remove redundant needToImport check.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/8273
> [dart][dart-dio] Add missing imports for container parameters

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
- modules/openapi-generator/src/main/resources/dart-dio/serializers.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/serializers.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/serializers.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/serializers.dart
* only generate actually used serializers (anything used in body or response)
* generate previously missing serializers for collection types
* improve formatting
Fixes https://github.com/OpenAPITools/openapi-generator/issues/8270
> [dart][dart-dio] Generate the correct serializers

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
Fixes cases where the request body is a map.
> [bug][dart][dart-dio] Fix serialization of map body params

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
Similar problem as with typescript-axios in https://github.com/OpenAPITools/openapi-generator/issues/8104, where `isCollectionFormatMulti` was not set properly for arrays with binary items.
Sample request body:
```yaml
requestBody:
content:
schema:
type: object
properties:
files:
type: array
items:
type: string
format: binary
```
Incorrect handling before PR:
```js
if (requestParameters.files) {
formParams.append('files', requestParameters.files.join(runtime.COLLECTION_FORMATS["csv"]));
}
```
Correct handling after PR:
```js
if (requestParameters.files) {
requestParameters.files.forEach((element) => {
formParams.append('files', element as any);
})
}
```
> typescript-fetch: fix isCollectionFormatMulti for arrays of files

- modules/openapi-generator-gradle-plugin/README.adoc
Updated the gradle example to exclude the modelFilesConstrainedTo parameter. 
I didn't do any testing beyond using this same configuration when trying out the openapi-generator project. The parameter is optional, and ommitting it should not cause any negative behaviors for new users.
> Remove modelFilesConstrainedTo from gradle example

- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfiguratorUtils.java
1. unable to use --global-property models="User,Pet" as this creates only User model.
2. to solve the issue, instead of "," separator used ":" separator
3. made some changes with that
4. need to refresh the documentation
To fix #7358
> To fix model selection

- modules/openapi-generator/src/main/resources/scala-sttp/api.mustache
Fixed https://github.com/OpenAPITools/openapi-generator/issues/8395 replacing `withCredentials` with `basic`. 
Please see more details in official sttp client documentation
https://sttp.softwaremill.com/en/latest/requests/authentication.html.
Thanks.
@clasnake @jimschubert @shijinkui @ramzimaalej @chameleon82 @Bouillie
> Renamed basic authentication function in sttp client 

- modules/openapi-generator/src/main/resources/typescript-angular/apiInterface.mustache
Adjusted the configuration import in the ApiInterface, so it imports the correct class name (including the configurationPrefix), instead of statically importing 'Configuration'.
Fixes #8415 
```
``` 
> [typescript-angular] Fix configuration import in apiInterface.mustache when the configurationPrefix option is used

- modules/openapi-generator/src/main/resources/python/api.mustache
- samples/client/petstore/python/petstore_api/api/another_fake_api.py
- samples/client/petstore/python/petstore_api/api/fake_api.py
- samples/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py
- samples/client/petstore/python/petstore_api/api/pet_api.py
- samples/client/petstore/python/petstore_api/api/store_api.py
- samples/client/petstore/python/petstore_api/api/user_api.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/api/usage_api.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api/usage_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/another_fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/default_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/store_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
> [PYTHON] fix #8404: use_Endoint to allow apis to have Endpoint

- modules/openapi-generator/src/main/resources/go/api.mustache
- samples/client/petstore/go/go-petstore/api_another_fake.go
- samples/client/petstore/go/go-petstore/api_fake.go
- samples/client/petstore/go/go-petstore/api_fake_classname_tags123.go
- samples/client/petstore/go/go-petstore/api_pet.go
- samples/client/petstore/go/go-petstore/api_store.go
- samples/client/petstore/go/go-petstore/api_user.go
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/api_usage.go
- samples/openapi3/client/petstore/go/go-petstore/api_another_fake.go
- samples/openapi3/client/petstore/go/go-petstore/api_default.go
- samples/openapi3/client/petstore/go/go-petstore/api_fake.go
- samples/openapi3/client/petstore/go/go-petstore/api_fake_classname_tags123.go
- samples/openapi3/client/petstore/go/go-petstore/api_pet.go
- samples/openapi3/client/petstore/go/go-petstore/api_store.go
- samples/openapi3/client/petstore/go/go-petstore/api_user.go
As discussed in https://github.com/OpenAPITools/openapi-generator/pull/8427/files#r556504630
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01)
```
``` 
> [Go] Fix response body

- modules/openapi-generator/src/main/resources/typescript-axios/package.mustache
- samples/client/petstore/typescript-axios/builds/es6-target/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version/package.json
I've updated the axios version to one that includes vulnerability fix as described [here](https://github.com/OpenAPITools/openapi-generator/issues/8432).
This PR does not implement any new features.
fixes https://github.com/OpenAPITools/openapi-generator/issues/8432
```
```  …
> [typescript-axios] bump axios version to 0.21.1 to fix vulnerability

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7651.yaml
- samples/openapi3/client/petstore/python/.openapi-generator/VERSION
Adds isNull to codegenModel codegenParameter codegenProperty codegenResponse
This is different than nullable: True
isNull should be set to true for schemas of type null like:
```
schema:
type: 'null'
```
Note: this is a v3.1 feature
Adding this property and these getIsNull setIsNull methods is a feature break out for https://github.com/OpenAPITools/openapi-generator/issues/7651
```
```  …
> Adds isNull to codegenX java core classes that represent schemas

- modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpNetCoreClientCodegenTest.java
Corrects package name in tests (copy-paste mistake), as pointed out here https://github.com/OpenAPITools/openapi-generator/commit/ee2f0e04a95e8b0eb6cec07b77515369bd062585#r45960427
```
``` 
> Style fix: use correct package name in tests

- modules/openapi-generator/src/main/resources/nim-client/api.mustache
If REST end-point has a path with multiple parameters current `api.mustache` generates a broken Nim-code by repeating path string multiple times, for example:
```nim
proc getCompanyUser*(httpClient: HttpClient, companyId: string, userId: string): (Option[User], Response) =
let response = httpClient.get(basepath & fmt"/companies/{companyId}/users/{userId}"fmt"/companies/{companyId}/users/{userId}")
constructResult[User](response)
```
after this fix is applied the result will be as is was designed by original author:
```nim
proc getCompanyUser*(httpClient: HttpClient, companyId: string, userId: string): (Option[User], Response) =
let response = httpClient.get(basepath & fmt"/companies/{companyId}/users/{userId}")
constructResult[User](response)
```
**Note:** unfortunately Petstore example …
> Nim client template bugfix for the case when path contains multiple parameters

- modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
- modules/openapi-generator/src/main/resources/rust-server/server-operation.mustache
- pom.xml
- samples/server/petstore/rust-server/output/multipart-v3/Cargo.toml
- samples/server/petstore/rust-server/output/multipart-v3/src/server/mod.rs
- samples/server/petstore/rust-server/output/no-example-v3/Cargo.toml
- samples/server/petstore/rust-server/output/openapi-v3/Cargo.toml
- samples/server/petstore/rust-server/output/ops-v3/Cargo.toml
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/server/mod.rs
- samples/server/petstore/rust-server/output/rust-server-test/Cargo.toml
This reverts https://github.com/OpenAPITools/openapi-generator/pull/8440 and updates swagger-rs to fix the tests - I'm surprised this wasn't picked up by CI automatically.
@frol @farcaller @paladinzh
```
``` 
> [Rust Server] Reinstate tests

- docs/plugins.md
1. Updated gradle plugin version to 5.0.0 (the latest stable release)
2. Removed modelFilesConstrainedTo  in the gradle sample to generate code for dummies who are pasting and running.
```
``` 
> [ plugin docs ] Update gradle plugin version to 5.0.0

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
* simplify template
* respect required flag (only null check when not required)
* minor formatting
> [dart][dart-dio] Improve form param handling, respect required flag

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- modules/openapi-generator/src/main/resources/dart/api_client.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/default_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart
It basically add a `User-Agent` header as it's missing in dart generator templates
```
``` 
> --http-user-agent arg support in dart generator

- modules/openapi-generator-gradle-plugin/samples/local-spec/gradle.properties
Fix the Gradle test in AppVeyor due to incorrect version of openapi-generator
```
``` 
> Fix the Gradle test in AppVeyor

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
Collection related refactorings:
- replaces for/foreach loops to use Collections.addAll() where
possible,
- replaces for/foreach loops to use Collection.addAll() where possible,
- replaces for/foreach loops to use Collection.removeAll() where
possible.
AddAllRatherThanLoopCleanUp from AutoRefactor applied by erefactor.
For AutoRefactor see https://github.com/JnRouvignac/AutoRefactor .
```
```  …
> erefactor - AutoRefactor - Collections.addAll() rather than loop

- modules/openapi-generator/src/main/resources/jmeter-client/api.mustache
- samples/client/petstore/jmeter/PetApi.jmx
- samples/client/petstore/jmeter/StoreApi.jmx
- samples/client/petstore/jmeter/UserApi.jmx
> [JMeter] Support json data in csv

- docs/generators/cpp-qt5-client.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5ClientCodegen.java
Added missing security feature support in the documentation
Added missing security feature support for the cpp-qt5-generator.
PING @wing328  @etherealjoy
> [Qt][C++] Updated cpp-qt5-client doc

- modules/openapi-generator/src/main/resources/dart2/enum.mustache
- modules/openapi-generator/src/main/resources/dart2/enum_inline.mustache
- samples/client/petstore/dart2/petstore_client_lib/lib/model/order.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/model/pet.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/model/order.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/model/pet.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/enum_arrays.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/enum_class.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/enum_test.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/map_test.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/order.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_enum.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_enum_default_value.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_enum_integer.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/outer_enum_integer_default_value.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/pet.dart
All enum instances are `const` so `equals/hashCode` is not needed.
Removing this allows to `switch/case` on enum instances.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/8307
```
``` 
CC @swipesight (2018/09) @jaumard (2018/09) …
> [dart] Fix switch on enums not possible

- docs/generators/java.md
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/api_test.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
This pull-request extends https://github.com/OpenAPITools/openapi-generator/pull/6912 by providing an implementation of the new `useAbstractionForFiles` flag for the webclient library.
The original issue was https://github.com/OpenAPITools/openapi-generator/issues/6715 . I left a comment on that ticket mentioning that the functionality would be nice to have for the webclient as well.
In this PR I mostly just adapted the changes that were necessary for the resttemplate to work for the webclient.
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda
> Implement useAbstractionForFiles for webclient library

- modules/openapi-generator/src/main/resources/swift5/api.mustache
- modules/openapi-generator/src/main/resources/swift5/modelObject.mustache
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/Category.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/Pet.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Models/Tag.swift
The objc integration in the is broken, which was making CI to fail.
This PR fixes that.
```
``` 
> [swift 5] fix objc integration

- modules/openapi-generator/src/main/resources/Javascript-Apollo/api.mustache
- modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
- samples/client/petstore/javascript-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise-es6/src/ApiClient.js
It adds a `User-Agent` header in javascript and javascript-apollo generators allowing usage of `--http-user-agent` argument.
```
``` 
> --http-user-agent arg support in javascript generator

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
- modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
- samples/server/petstore/spring-mvc-j8-async/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-j8-localdatetime/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-no-nullable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-spring-pageable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-beanvalidation-no-nullable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-beanvalidation/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-delegate/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-delegatePattern/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-without-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-virtualan/src/main/java/org/openapitools/virtualan/model/FormatTest.java
- samples/server/petstore/springboot/src/main/java/org/openapitools/model/FormatTest.java
Fixes #1448
Binary and Byte Arrays
* should be compared using Arrays.equals(...)
* their hash code generated using Arrays.hashCode(...)
Spring codegen has been updated and the Tests updated.
> Spring codegen - fix equals and hashCode methods for byte array and binary

- modules/openapi-generator/src/main/resources/Java/libraries/vertx/ApiClient.mustache
- samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ApiClient.java
> [Java][Client][Vertx] Use Vertx reference instead of static class in ApiImpl template

- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/urlsessionLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
`cleanupRequest()` is only called on error for now. So `sessionDelegate` doesn't get deallocated after request.
I think it's okay to call `cleanupRequest()` directly after the processing of the response, instead of putting it in the completion closure, since it will only deallocate when not in use anymore. What do you guys think?
```
```  …
> [swift5] URLSession: Fix memory leak of SessionDelegate

- bin/utils/export_docs_generators.sh
- bin/utils/export_generator.sh
change the shebangs for the scripts that generate samples to locate bash via `/usr/bin/env`
Some systems, like nixOS, don't use the linux filesystem hierarchy standard and/or have a bash binary in that path. `/usr/bin/env` is available on most systems even that don't go with the regular FHS and will locate the interpreter using the user's $PATH instead. for more info: https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my
> make shebangs portable

- bin/configs/rust-server-petstore-with-fake-endpoints-models-for-testing.yaml
- modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
- samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml
Allow configuration of various pieces of Cargo metadata:
- Rust Registry to publish to
- Repository URL
- Documentation URL
- Homepage
This work was developed on behalf of @Metaswitch
@frol @farcaller @paladinzh
```
``` 
> [Rust Server] Cargo Metadata Configuration

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
Fix https://github.com/OpenAPITools/openapi-generator/issues/7991
```
``` 
> Added 'hash' to objcReservedWords

- bin/utils/test_file_list.yaml
- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/Api/PetApiTests.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
To fix https://github.com/OpenAPITools/openapi-generator/issues/8524 by supporting binary responses.
```
``` 
> [C#][netcore] fix binary response

- docs/configuration.md
The link to the Gradle plugin linked to the Maven plugin. I've pointed the link in the right direction.
> Fixed incorrect link in configuration.md

- modules/openapi-generator/src/main/resources/python/configuration.mustache
- samples/client/petstore/python-asyncio/petstore_api/configuration.py
- samples/client/petstore/python-tornado/petstore_api/configuration.py
- samples/client/petstore/python/petstore_api/configuration.py
- samples/openapi3/client/petstore/python/petstore_api/configuration.py
Generating Python client for my OpenAPI and it is outputting invalid Python code, it generates a Configuration class, which is trying to use self.access_token which is not initialised to any default value.
closes #7468 
@spacether  @arun-nalla @taxpon @cbornet
> [BUG][Python] init access token for python client configuration

- modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
- samples/client/petstore/javascript-es6/src/ApiClient.js
- samples/client/petstore/javascript-promise-es6/src/ApiClient.js
Fix for #8632
* updated the regex used in the String.replace for parseDate() to more precisely target ISO-8601
* added the replace function call to the ES6 mustache file
```
```  …
> [JS] the replace statement in parseDate is too greedy (#8632)

- docs/generators/cpp-qt5-client.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5ClientCodegen.java
- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache
- samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXPetApi.h
- samples/client/petstore/cpp-qt5/client/PFXStoreApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXStoreApi.h
- samples/client/petstore/cpp-qt5/client/PFXUserApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXUserApi.h
```
``` 
NOTE:  all changes are from #8565. I did a fresh PR because the rebase on the old PR was a bad idea.
This PR will enable parameter styling support following the [OpenAPI Specification 3.0.3](https://github.com/OAI/OpenAPI-Specification/blob/master …
> [Qt5][C++] Adding Parameter Styling Support for Qt5

- docs/contributing.md
The link to Swift style guide (called API design guidelines in Swift) is not the right one. It is a link to old language guide.
Mentioning the Swift commitee here: @jgavris @ehyche @Edubits @jaz-ah @4brunu
```
``` 
> Update Swift styleguide link in contribution guidelines

- modules/openapi-generator/src/main/resources/ruby-client/partial_model_generic.mustache
- modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
- samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Model/ArrayTest.cs
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/ArrayTest.php
- samples/client/petstore/ruby-faraday/lib/petstore/models/array_test.rb
- samples/client/petstore/ruby/lib/petstore/models/array_test.rb
- samples/openapi3/client/petstore/python-legacy/petstore_api/models/array_test.py
- samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/model/ArrayTest.java
Added missing closing brace in list_invalid_properties model method.
```
``` 
> [ruby] Fix syntax error
