modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java

[kotlin] Fix imports of generated class

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/TypeScriptClientCodegenTest.java

Fix package declaration #7122

---

README.md

Add a link to Instana Blog

---

modules/openapi-generator/src/main/resources/go-server/service.mustache
samples/server/petstore/go-api-server/go/api_pet_service.go
samples/server/petstore/go-api-server/go/api_store_service.go
samples/server/petstore/go-api-server/go/api_user_service.go

[Go][Server] replace spaces with tabs

---

docs/usage.md
modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/GenerateBatch.java
modules/openapi-generator-cli/src/test/java/org/openapitools/codegen/cmd/GenerateBatchTest.java
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-double.json
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-double.yaml
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-nested-include-property-merge.yaml
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-nested-include.json
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-nested-include.yaml
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-nested-property-merge.yaml
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-nested.json
modules/openapi-generator-cli/src/test/resources/batch/jaxrs-datelib-j8-nested.yaml

**Issue 7311**
This change updates the '!include' directive available in the 'batch' CLI command to handle multiple includes as well as nested includes.
Instead of parsing the files into a tree, parsing them via the streaming API allows multiple and nested includes. 
The appropriate test case (GenerateBatchTest) has been updated to test nested and multiple includes for both JSON and YAML.
The file usage.md has been updated to explain the change. It mentions version 5.0.0 as the affected version - that may have to change.

[cli] Batch: support multiple/nested !include directive

---

README.md

Add a link to PS blog post

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/axios/TypeScriptAxiosClientCodegenTest.java

Rename TS Axios tests to TypeScriptAxiosClientCodegenTest.java with better package name

[TS] rename TS Axios tests

---

modules/openapi-generator/src/main/resources/scala-sttp/model.mustache

To fix #7431 
cc @clasnake @jimschubert @shijinkui @ramzimaalej @chameleon82 @Bouillie

Fix scala-sttp enum generation

---

README.md

Add a link to a post about angular reactiveforms

Add a link to a post about angular reactiveforms

---

shippable.yml

- Remove Haskell stack installation in the Shippable CI

Remove Haskell stack installation in the Shippable CI

---

modules/openapi-generator/src/main/resources/powershell/model_simple.mustache

Fixed the maximum minimum range check condition
@wing328

[PowerShell] Fixed the maximum minimum range check condition

---

README.md

Add a link to react native tutorial

Add a link to react native tutorial

---

modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/IReadableConfiguration.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/Configuration.cs

- fix issues related to HTTP signature authentication by not including related code when the spec doesn't contain HTTP signature authentication.
- local test results with petstore.yaml was good.

[C#][NetCore] fix issues related to HTTP signature authentication

---

samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api/usage_api.rb
samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb
samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/configuration.rb

Fixes ruby samples changed by outdated PR merge

[ci][test] Fix samples

---

modules/openapi-generator/src/main/resources/go/api_doc.mustache
samples/client/petstore/go/go-petstore/docs/AnotherFakeApi.md
samples/client/petstore/go/go-petstore/docs/FakeApi.md
samples/client/petstore/go/go-petstore/docs/FakeClassnameTags123Api.md
samples/client/petstore/go/go-petstore/docs/PetApi.md
samples/client/petstore/go/go-petstore/docs/StoreApi.md
samples/client/petstore/go/go-petstore/docs/UserApi.md
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/docs/UsageApi.md
samples/openapi3/client/petstore/go/go-petstore/docs/AnotherFakeApi.md
samples/openapi3/client/petstore/go/go-petstore/docs/DefaultApi.md
samples/openapi3/client/petstore/go/go-petstore/docs/FakeApi.md
samples/openapi3/client/petstore/go/go-petstore/docs/FakeClassnameTags123Api.md
samples/openapi3/client/petstore/go/go-petstore/docs/PetApi.md
samples/openapi3/client/petstore/go/go-petstore/docs/StoreApi.md
samples/openapi3/client/petstore/go/go-petstore/docs/UserApi.md

Fix the example in the API docs to use the proper signature

[go][client] Fix API docs example generation

---

README.md

- Add PLAID, Inc. to the user list

Add PLAID, Inc. to the user list

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

Skip 443 for port mustache tag

[core] Skip 443 for port mustache tag

---

samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/Model/SpecialModelNameTests.cs

Add tests for serialization of special property names using `SpecialModelName`

Add tests for serialization of special property names

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/FsharpFunctionsServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinVertxServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NimClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PlantumlDocumentationCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaHttpServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaPlayFrameworkServerCodegen.java
new.sh

[core] Make loggers static final where possible

---

README.md

Add a link to a blog post on generating Angular client

Add a link to a blog post on generating Angular client

---

bin/utils/export_docs_generators.sh

Just trying things out to speed up circle ci

Generate docs on 4 threads

---

modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs

- Default OverrideSpecifiedNames to false
To close https://github.com/OpenAPITools/openapi-generator/issues/7541

[C#][netcore] Default OverrideSpecifiedNames to false

---

samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/models/array_alias.rb
samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/models/map_alias.rb

Runs ensure up to date

---

modules/openapi-generator/src/main/resources/go/utils.mustache

I found the typo, here is the fix.

Fix golang comment typo

---

docs/templating.md

Fix typos in templating.md

---

README.md

- Use 3.0 Petstore spec
- Update npm wrapper installation

Update the website/README

---

modules/openapi-generator/src/main/resources/csharp-netcore/AbstractOpenAPISchema.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/modelOneOf.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/JSONComposedSchemaTests.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/AbstractOpenAPISchema.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Fruit.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/FruitReq.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Mammal.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/NullableShape.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Pig.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Quadrilateral.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Shape.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/ShapeOrNull.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Triangle.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/AbstractOpenAPISchema.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Fruit.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/FruitReq.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Mammal.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/NullableShape.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Pig.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Quadrilateral.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Shape.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ShapeOrNull.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Triangle.cs

Convert `FromJson` to a static method (similar to `FromJson` method in other C# libs) 

[C#][netcore] convert FromJson to static method

---

website/src/pages/index.js

[Website] add cake, sbt integration

---

modules/openapi-generator/src/main/resources/powershell/api_client.mustache
modules/openapi-generator/src/main/resources/powershell/configuration.mustache
samples/client/petstore/powershell/src/PSPetstore/Client/PSConfiguration.ps1
samples/client/petstore/powershell/src/PSPetstore/Private/PSApiClient.ps1
samples/client/petstore/powershell/tests/Petstore.Tests.ps1

-  Add `Proxy` to the configuration so that users can set the proxy setting when making the HTTP requests

[PS] Add proxy support

---

modules/openapi-generator/src/main/resources/powershell/Org.OpenAPITools.psm1.mustache
samples/client/petstore/powershell/src/PSPetstore/PSPetstore.psm1

Auto load System.Web and System.Net when importing the module.

[PowerShell] Auto load System.Web and System.Net

---

modules/openapi-generator/src/main/resources/go/README.mustache
samples/client/petstore/go/go-petstore/README.md
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/README.md
samples/openapi3/client/petstore/go/go-petstore/README.md

- Update README to show how to set proxy

[Go] Update doc to show how to set proxy

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/main/resources/Java/README.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.sbt.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pom.mustache
samples/client/petstore/java/jersey2-java8/README.md
samples/client/petstore/java/jersey2-java8/build.gradle
samples/client/petstore/java/jersey2-java8/build.sbt
samples/client/petstore/java/jersey2-java8/pom.xml
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/README.md
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/build.gradle
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/build.sbt
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/pom.xml
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/README.md
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/build.gradle
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/build.sbt
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/pom.xml
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8/README.md
samples/openapi3/client/petstore/java/jersey2-java8/build.gradle
samples/openapi3/client/petstore/java/jersey2-java8/build.sbt
samples/openapi3/client/petstore/java/jersey2-java8/pom.xml
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java

- add ClientConfig getter, setter
- remove performAdditionalClientConfiguration (breaking changes)

[java][jersey2] add proxy support

---

modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/model.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/modelOneOf.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/JSONComposedSchemaTests.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Fruit.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/FruitReq.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Mammal.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/NullableShape.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Pig.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Quadrilateral.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Shape.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/ShapeOrNull.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/Triangle.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Fruit.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/FruitReq.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Mammal.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/NullableShape.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Pig.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Quadrilateral.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Shape.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/ShapeOrNull.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/Triangle.cs

- add custom converters for oneOf models
- add tests

[C#][netcore] Add custom converters for oneOf models

---

docs/generators.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GraphQLSchemaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java

Change codegen type to schema in the Protobuf, GraphQL schema generators

[Protobuf][GraphQL] Change codegen type to schema

---

modules/openapi-generator/src/main/resources/Java/libraries/webclient/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache
modules/openapi-generator/src/main/resources/Java/pom.mustache
samples/client/petstore/java/jersey1/pom.xml
samples/client/petstore/java/webclient/pom.xml

- fix missing dependencies in build.gradle
- update jersey1 junit to a newer version
For https://github.com/OpenAPITools/openapi-generator/issues/5690#issuecomment-697300565

[Java][webclient] fix missing dependencies in build.gradle

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/issue_7791.yaml

To fix #7791 
Update to `JavaClientCodeGen#postProcessOperationsWithModels` for the Feign library to be aware of a custom method if one exists at the end of the path. A custom method is removed for the path parameters to be "camelized" and then replaced afterwards.
Added a sample yaml to demonstrate a custom method and a test case in `JavaClientCodegenTest`. 
I have not yet placed a sample custom method path into the Fake Petstore Spec and tested that all of the other generators are compatible. 

Sample fix for Feign client support for custom method syntax #7791

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAxiosClientCodegen.java
modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts

Fix #7247
Ping @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov

[typescript-axios] Fix multipart with file array

---

modules/openapi-generator/src/main/resources/elixir/api.mustache
modules/openapi-generator/src/main/resources/elixir/model.mustache
samples/client/petstore/elixir/lib/openapi_petstore/api/fake.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/class_model.ex
samples/client/petstore/elixir/lib/openapi_petstore/model/file.ex

Do not use HTML-escaped values in comments.
cc @mrmstn (2018/12)

[Elixir] use original value in comments

---

CONTRIBUTING.md
docs/contributing.md
docs/generators/typescript-rxjs.md

There were line breaks within words and a `you've` where have was no auxiliary verb -> `you have`

Update CONTRIBUTING.md with typo corrections - no semantic changes

---

README.md

adesso is using openapi tools as well.

Added adesso as users

---

README.md

Add link to React Native Client article

Add link to React Native Client article

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java

- map AnyType to Object
To fix https://github.com/OpenAPITools/openapi-generator/issues/7819
cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12)

[Dart] map AnyType to Object

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/protobuf/ProtobufSchemaCodegenTest.java
samples/config/petstore/protobuf-schema/models/api_response.proto
samples/config/petstore/protobuf-schema/models/category.proto
samples/config/petstore/protobuf-schema/models/inline_object.proto
samples/config/petstore/protobuf-schema/models/inline_object1.proto
samples/config/petstore/protobuf-schema/models/order.proto
samples/config/petstore/protobuf-schema/models/pet.proto
samples/config/petstore/protobuf-schema/models/tag.proto
samples/config/petstore/protobuf-schema/models/user.proto

- Better code format (Java files)
- Remove some commented code
- update samples

[Protobuf] Better code format (Java files)

---

modules/openapi-generator/src/main/resources/nodejs-express-server/eslintrc.mustache

CC-ing Node/JavaScript technical committee: @CodeNinjai, @frol, @cliffano.
Closes #7843.
To validate, please see the steps to reproduce in #7843.
I believe re-generating Petstore samples isn't needed for this change — no results with `grep -R airbnb samples/client/petstore/*` — but I'm not sure I understand this correctly. I ran `./bin/generate-samples.sh bin/configs/typescript-node*` and `./bin/generate-samples.sh bin/configs/javascript*` just to be sure and got "success" messages.

[node-express-server] template-only change to fix use of 'airbnb-base' ESLint plugin

---

README.md

Add a link to presentation at FEConf 2020 (Korea)

Add a link to presentation at FEConf 2020

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java

- throw exception for invalid framework (instead of silently defaulting to .net standard 2.0)
- tested locally to confirm an exception is thrown when the targetFramework is invalid.

[C#][netcore] throw exception for invalid framework

---

samples/openapi3/client/petstore/python-experimental/tests_manual/test_fake_api.py

Adds tests case showing not sending optional params

[python] Adds tests case showing omitting optional props when tx and rxing

---

shippable.yml

Fix shippable issue
ref: https://github.com/Shippable/support/issues/5170#issuecomment-726550397

Fix shippable issue

---

samples/client/petstore/typescript-fetch/builds/default-v3.0/models/FormatTest.ts

update typescript-fetch samples

---

README.md

Add "LVM Versicherungen" to list of companies

Add "LVM Versicherungen" to list of companies

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/EnumArrays.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/EnumTest.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/InlineObject2.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/MapTest.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Order.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Pet.ts
samples/client/petstore/typescript-fetch/builds/enum/models/InlineObject.ts
samples/client/petstore/typescript-fetch/builds/enum/models/InlineResponse200.ts

Reverts OpenAPITools/openapi-generator#7955
Reverting this because it did not fix the problem

Revert "Do not use cached properties for additionalProperties"

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pojo.mustache

- fixed additional properties without variables
- tested locally to ensure the output compiles

[Java][jersey2] fix additional properties without variables

---

README.md

Add contact about security vulnerabilities in the project's readme.

Add contact about security vulnerabilities

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java

- fix string comparison in the generator

[Go] fix string comparison in the generator

---

CI/.drone.yml

Test OAS v3 Java native client in drone.ci

 Test OAS v3 Java native client in drone.ci

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java

Fix "pyhton" typo in error message
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess @arun-nalla @spacether

[python] Fix pyhton typo

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java

Those are not primitive types, but not model either, they need to be
handled explicitely.

Properly generate email examples in go

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/swift5/Swift5ClientCodegenTest.java
samples/client/petstore/swift5/alamofireLibrary/docs/FakeAPI.md
samples/client/petstore/swift5/alamofireLibrary/docs/PetAPI.md
samples/client/petstore/swift5/combineLibrary/docs/FakeAPI.md
samples/client/petstore/swift5/combineLibrary/docs/PetAPI.md
samples/client/petstore/swift5/default/docs/FakeAPI.md
samples/client/petstore/swift5/default/docs/PetAPI.md
samples/client/petstore/swift5/deprecated/docs/PetAPI.md
samples/client/petstore/swift5/nonPublicApi/docs/FakeAPI.md
samples/client/petstore/swift5/nonPublicApi/docs/PetAPI.md
samples/client/petstore/swift5/objcCompatible/docs/FakeAPI.md
samples/client/petstore/swift5/objcCompatible/docs/PetAPI.md
samples/client/petstore/swift5/promisekitLibrary/docs/FakeAPI.md
samples/client/petstore/swift5/promisekitLibrary/docs/PetAPI.md
samples/client/petstore/swift5/readonlyProperties/docs/FakeAPI.md
samples/client/petstore/swift5/readonlyProperties/docs/PetAPI.md
samples/client/petstore/swift5/resultLibrary/docs/FakeAPI.md
samples/client/petstore/swift5/resultLibrary/docs/PetAPI.md
samples/client/petstore/swift5/rxswiftLibrary/docs/FakeAPI.md
samples/client/petstore/swift5/rxswiftLibrary/docs/PetAPI.md
samples/client/petstore/swift5/urlsessionLibrary/docs/FakeAPI.md
samples/client/petstore/swift5/urlsessionLibrary/docs/PetAPI.md

- Revert "Bugfix swift5 code generation 2966 (#7301)"
- provide a better fix for the stackoverflow issue using HashSet
(the test added by #7301 has NOT been deleted so stackoverflow issue is covered moving forward)
cc @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

[Swift5] improve code sample generation

---

README.md

Add a link to saki-engineering blog post

Add a link to saki-engineering blog post

---

README.md

Add a link to massive art blog

Add a link to massive art blog

---

modules/openapi-generator/src/main/resources/jmeter-client/api.mustache
samples/client/petstore/jmeter/PetApi.csv
samples/client/petstore/jmeter/PetApi.jmx
samples/client/petstore/jmeter/StoreApi.csv
samples/client/petstore/jmeter/StoreApi.jmx
samples/client/petstore/jmeter/UserApi.csv
samples/client/petstore/jmeter/UserApi.jmx

[JMeter] Support body params for jmeter

---

pom.xml

mockito 3.6.28

---

modules/openapi-generator/src/main/resources/jmeter-client/api.mustache
samples/client/petstore/jmeter/PetApi.csv
samples/client/petstore/jmeter/PetApi.jmx
samples/client/petstore/jmeter/StoreApi.csv
samples/client/petstore/jmeter/StoreApi.jmx
samples/client/petstore/jmeter/UserApi.csv
samples/client/petstore/jmeter/UserApi.jmx

[Jmeter] Support media type of consumes and produces for jmeter

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java

To close https://github.com/OpenAPITools/openapi-generator/issues/8070
cc @eriktim

Better handling of operationId in the Elm client generator

---

.travis.yml
CI/deno_install.sh

Install deno from local shell script to avoid issues below:
```
$ curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.1.2
curl: (22) The requested URL returned error: 429 too many requests
The command "curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.1.2" failed and exited with 22 during .
```
cc @TiFu

Use local deno installation shell script

---

pom.xml

Update swagger parser to 2.0.23.
Reviewed the release note and the changes are pretty minor: https://github.com/swagger-api/swagger-parser/releases

Update swagger parser to 2.0.23

---

.travis.yml
pom.xml
samples/client/petstore/typescript-axios/tests/default/package-lock.json
samples/client/petstore/typescript-axios/tests/default/package.json
samples/client/petstore/typescript-axios/tests/default/test/PetApi.ts
samples/client/petstore/typescript-axios/tests/default/test/PetApiFactory.ts
samples/client/petstore/typescript-axios/tests/default/test/StoreApi.ts
samples/client/petstore/typescript-axios/tests/default/test/StoreApiFactory.ts

Hi everyone!
I want to enable Typescript-Axios integration test to check if generated files works well.
So I have modified some files including package.json and broken package-lock.json.
Please check the detail I wrote below.
- (TravisCI) update nodejs from @8 to @12 since node@10 becomes EOL at 2021/04
- delete unused dependency and regenerate broken package-lock.json
- update outdated Typescript from v2.4.1 to v4.1.2(LTS)
- turn on typescript-axios integration test

test: enable typescript-axios integration test

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java

Add postProcess method to show donation message, e.g.
```
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/client/petstore/java/vertx/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/client/petstore/java/vertx/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file samples/client/petstore/java/vertx/.openapi-generator/FILES
################################################################################
################################################################################
```
Generators can override this method to show tips (e.g. using code formatter to format the output), etc.

Add postProcess method to show donation message

---

modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/api-source.mustache

Fixes #7898
@stkrwork @ravinikam @MartinDelille @muttleyxd

[cpp-rest]Allocate httpcontent

---

README.md

Add a link to qiita blog post

---

README.md

Add a link to Yahoo! Tech blog

Add a link to Yahoo! Tech blog

---

.travis.yml

Ignore docker login error for PR. Tested via https://github.com/OpenAPITools/openapi-generator/commit/ce17593d2835e1c940e11dbe6df8f88d7c82e5c1

Ignore docker login error for PR

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellHttpClientCodegen.java

[haskell-http-client] regard mime type as json if "json" appears anywhere in the mimetype

---

modules/openapi-generator/src/main/resources/kotlin-spring/dataClassOptVar.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/dataClassReqVar.mustache
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/model/Pet.kt
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/model/Pet.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/model/Pet.kt

* Remove useless `NotNull` annotation : Kotlin has built-in null-checking
* Add `required=true` in `JsonProperty` to reject null values
@jimschubert (2017/09), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

[Kotlin-Spring] Fix required model property deserialization

---

.github/PULL_REQUEST_TEMPLATE.md

include build command before updating samples

docs: improve pull request checklist

---

docs/customization.md

Update doc to use colon as the separator in model selection
e.g. models=Pet:Tag:Category
```
``` 

Update doc to use colon as the separator in model selection

---

.github/PULL_REQUEST_TEMPLATE.md

Consolidate the 3rd item into the 4th item in the PR template as they are very similar
cc @macjohnny @OpenAPITools/generator-core-team 
```
``` 

Consolidate 3rd item into the 4th item in PR template

---

README.md

Add a link to the blog post in nginx blog
```
``` 

Add a link to the blog post in nginx blog

---

pom.xml

Comment out the rust server test since it fails on itself in Travis CI at the moment.
cc @richardwhiuk 
```
``` 

Comment out rust server tests

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java

Minor Fix: typo

---

modules/openapi-generator/src/main/resources/python/README_common.mustache
samples/client/petstore/python/README.md
samples/openapi3/client/extensions/x-auth-id-alias/python/README.md
samples/openapi3/client/features/dynamic-servers/python/README.md
samples/openapi3/client/petstore/python/README.md

Let 2 follow 1.
```
``` 
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)

Fix counting for large API solutions in generated Python README

---

CI/.drone.yml
samples/client/petstore/nim/petstore/models/model_order.nim

- tested the petstore client in drone.io
- triggered a build failure to confirm the test is working as expected
```
``` 
cc @hokamoto - the creator of the Nim client generator

[Nim] test the petstore client in drone.io

---

modules/openapi-generator/src/main/resources/crystal/README.mustache
samples/client/petstore/crystal/README.md

Fix README typo for Crystal

---

docs/generators/csharp-netcore.md
docs/generators/go.md
docs/generators/powershell.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java

Fix typo in useOneOfDiscriminatorLookup

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
modules/openapi-generator/src/main/resources/powershell/api_doc.mustache
samples/client/petstore/powershell/docs/PSPetApi.md
samples/client/petstore/powershell/docs/PSStoreApi.md
samples/client/petstore/powershell/docs/PSUserApi.md

minor fix to API doc:
- fix configuration
- fix model Initialize cmdlet
```
``` 

[PowerShell] minor fix to API doc

---

modules/openapi-generator-gradle-plugin/gradlew
modules/openapi-generator-gradle-plugin/gradlew.bat

- Update gradlew, gradlew.bat to the one in v6.8.0: https://github.com/gradle/gradle/tree/v6.8.0
```
``` 

[Gradle Plugin] Update gradlew, gradlew.bat

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
pom.xml

update parser to 2.0.24
```
``` 

Update parser to newer version 2.0.24

---

modules/openapi-generator/src/main/resources/jmeter-client/api.mustache
samples/client/petstore/jmeter/PetApi.jmx
samples/client/petstore/jmeter/StoreApi.jmx

[Jmeter] Support securityDefinitions

---

README.md

viadee as using company added

---

modules/openapi-generator/src/main/resources/dart2/api_client.mustache
samples/client/petstore/dart2/petstore_client_lib/lib/api_client.dart
samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api_client.dart
samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api_client.dart

[dart] Fix typo added in 57126a19

---

modules/openapi-generator/src/main/resources/rust-server/lib.mustache
modules/openapi-generator/src/main/resources/rust-server/response.mustache
samples/server/petstore/rust-server/output/multipart-v3/src/lib.rs
samples/server/petstore/rust-server/output/no-example-v3/src/lib.rs
samples/server/petstore/rust-server/output/openapi-v3/src/lib.rs
samples/server/petstore/rust-server/output/ops-v3/src/lib.rs
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs
samples/server/petstore/rust-server/output/rust-server-test/src/lib.rs

This makes response models generated by the generator serializable.
This allows them to be serialized, which makes it easier to write tests.
This work was done and reviewed by @Metaswitch
@frol @farcaller @paladinzh
```
``` 

[Rust Server] Serializable responses

---

modules/openapi-generator/src/main/resources/dart-dio/api.mustache
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/default_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart

[dart][dart-dio] Add missing isRedirect parameter to response

---

README.md

Remove old script reference in readme
```
``` 

Remove old script reference in readme

---

modules/openapi-generator/src/main/resources/dart-dio/api.mustache
modules/openapi-generator/src/main/resources/dart-dio/apilib.mustache
modules/openapi-generator/src/main/resources/dart-dio/local_date_serializer.mustache
modules/openapi-generator/src/main/resources/dart-dio/serializers.mustache
samples/client/petstore/dart-dio/petstore_client_lib/lib/api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/default_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart

General field initialization improvements for API classes.
```
``` 

[dart][dart-dio] Improve API & API-Client field initialization

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/petstore/java/okhttp-gson-dynamicOperations/pom.xml
samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
samples/client/petstore/java/okhttp-gson/pom.xml

Upgraded dependency versions in okhttp generator, closes #8425 
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch
```
``` 

Upgraded dependency versions in okhttp generator.

---

modules/openapi-generator/src/main/resources/powershell/api_doc.mustache
samples/client/petstore/powershell/docs/PSPetApi.md
samples/client/petstore/powershell/docs/PSStoreApi.md
samples/client/petstore/powershell/docs/PSUserApi.md

Remove import in code samples as already stated in the installation instruction
```
``` 

Remove import in code samples as already stated in the installation instruction

---

bin/configs/typescript-nestjs-v6-provided-in-root.yaml
modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts

Minor fixes to typescript-nestjs client generator
```
``` 
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov …

Minor fixes to typescript-nestjs client generator

---

modules/openapi-generator/src/main/resources/Java/libraries/native/AbstractOpenApiSchema.mustache

Fixed package declaration in AbstractOpenApiSchema.mustache template
```
``` 
@bbdouglas, @sreeshas, @jfiala, @lukoyanov, @cbornet, @jeff9finger, @karismann, @Zomzog, @lwlee2608, @nmuesch
To fix #8583

[BUG][JAVA] fix AbstractOpenApiSchema package

---

modules/openapi-generator-core/src/main/java/org/openapitools/codegen/api/TemplatingGenerator.java
modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/configuration/HomeController.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/FsharpFunctionsServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/FsharpGiraffeServerCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSCXFExtServerCodegenTest.java

AutoRefactor cleanup 'AnnotationCleanUp' applied by erefactor:
Simplifies annotation uses:
- empty parentheses will be removed from annotations,
- single members named "value" will be removed from annotations and
only the value will be left.
For AutoRefactor see https://github.com/JnRouvignac/AutoRefactor
```
```  …

refactor: erefactor/AutoRefactor - Annotation

---

modules/openapi-generator/src/main/resources/crystal/api.mustache
modules/openapi-generator/src/main/resources/crystal/api_client.mustache
modules/openapi-generator/src/main/resources/crystal/api_client_faraday_partial.mustache
modules/openapi-generator/src/main/resources/crystal/api_client_typhoeus_partial.mustache
modules/openapi-generator/src/main/resources/crystal/base_object.mustache
modules/openapi-generator/src/main/resources/crystal/configuration.mustache
modules/openapi-generator/src/main/resources/crystal/partial_model_generic.mustache
modules/openapi-generator/src/main/resources/crystal/partial_oneof_module.mustache
samples/client/petstore/crystal/src/petstore/api_client.cr
samples/client/petstore/crystal/src/petstore/configuration.cr
samples/client/petstore/crystal/src/petstore/models/api_response.cr
samples/client/petstore/crystal/src/petstore/models/category.cr
samples/client/petstore/crystal/src/petstore/models/order.cr
samples/client/petstore/crystal/src/petstore/models/pet.cr
samples/client/petstore/crystal/src/petstore/models/tag.cr
samples/client/petstore/crystal/src/petstore/models/user.cr

Thank you so much for adding a Crystal client generator! I got a little ambitious and attempted to generate a Stripe API client from [their OAS3 definition](https://github.com/stripe/openapi). From inside that repo, I ran the following:
```
openapi-generator generate -i openapi/spec3.yaml -g crystal -p shardName=stripe -p moduleName=Stripe -o ../stripe
```
Then I spun up a new Crystal app:
- `crystal init app test_stripe`
- Added the generated Crystal shard as a dependency in `shard.yml` with `path: ../stripe`
- In my new app's `src/test_stripe.cr`:
```crystal
require "stripe"
Stripe.configure do |c|
c.api_key = ENV["STRIPE_API_KEY"]
end
pp Stripe.get_customers
```
- `crystal src/test_stripe.cr`
There were a few compiler errors for a Crystal project I spun up to test-drive it and I've …

Fix syntax errors and method calls in code generated by Crystal client generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java

```
[main] INFO  o.o.codegen.TemplateManager - writing file samples/client/petstore/swift5/default/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file samples/client/petstore/swift5/default/.openapi-generator/FILES
################################################################################
################################################################################
```
```
```  …

Add sponsorship message in swift5 generator

---

modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java

Keep timezone for OffsetDateTime in responses
https://github.com/OpenAPITools/openapi-generator/issues/8611
```
```  …

[Java][native] Do not use context timezone.

---

modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java

Fixed date-time query parameter handling for java native java8 and typescript-fetch.
https://github.com/OpenAPITools/openapi-generator/issues/8615
```
``` 
These …

Fixed serialization of date-time query parameters.

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api.module.ts

Minor fix for typescript-nestjs

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/LuaClientCodegen.java

Add sponsorship message to the lua generator
cc @daurnimator
```
``` 

Add sponsorship message to the lua generator

---

modules/openapi-generator/src/main/resources/dart-dio/auth/api_key_auth.mustache
samples/client/petstore/dart-dio/petstore_client_lib/lib/auth/api_key_auth.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/auth/api_key_auth.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/auth/api_key_auth.dart

Remove the break stopping after the first key.
Fixes #8254
```
``` 

[dart][dart-dio] Allow API key authentication with multiple API keys

---

modules/openapi-generator/src/main/resources/powershell/Build.ps1.mustache
samples/client/petstore/powershell/Build.ps1

- replace tabs with 4-space to make the code format consistent with the rest of the powershell client
```
``` 

[PowreShell] replace tabs with 4-space

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/ignore/CodegenIgnoreProcessor.java

Change warning message to info.
Add name of directory checked to message.
Resolves #4627
```
``` 

Fix misleading warning message for missing output directory.

---

modules/openapi-generator/src/main/resources/dart-dio/api_util.mustache
modules/openapi-generator/src/main/resources/dart/auth/authentication.mustache
modules/openapi-generator/src/main/resources/dart2/class.mustache
samples/client/petstore/dart-dio/petstore_client_lib/lib/api_util.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api_util.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api_util.dart

- replace tabs with 4-space in the templates to make it consistent with the rest of the code base
cc @swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)
```
``` 

[Dart] replace tabs with 4-space in the templates

---

modules/openapi-generator/src/main/resources/aspnetcore/2.1/Startup.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/controller.mustache
modules/openapi-generator/src/main/resources/aspnetcore/3.0/Startup.mustache
modules/openapi-generator/src/main/resources/aspnetcore/3.0/controller.mustache
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Startup.cs

replace tabs with 4-space to make it consistent with the rest of the code base.
```
``` 

[aspnetcore] replace tabs with 4-space

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api.module.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts

[TypeScript][nestJS] Fix missing "=" and unused/undefined import

---

modules/openapi-generator/src/main/resources/Java/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/google-api-client/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/google-api-client/build.sbt.mustache
modules/openapi-generator/src/main/resources/Java/libraries/google-api-client/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/pom.mustache
modules/openapi-generator/src/main/resources/Java/pom.mustache
samples/client/petstore/java/google-api-client/build.gradle
samples/client/petstore/java/google-api-client/build.sbt
samples/client/petstore/java/google-api-client/pom.xml
samples/client/petstore/java/jersey1/build.gradle
samples/client/petstore/java/jersey1/pom.xml
samples/client/petstore/java/retrofit2-play26/pom.xml

Update jackson to 2.12.1 for `jersey`, `google-api-client`, `retrofit2` to address security issues
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) …

[Java][client] Update jackson to 2.12.1

---

README.md

Add a link to the blog post by cloud-viadee
```
``` 

Add a link to the blog post by cloud-viadee

---

modules/openapi-generator/src/main/resources/kotlin-server/data_class.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradleKts.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/pom.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/settingsGradle.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/service.mustache
samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/models/ApiResponse.kt
samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/models/Category.kt
samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/models/Order.kt
samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/models/Pet.kt
samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/models/Tag.kt
samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/models/User.kt
samples/server/petstore/kotlin-springboot-delegate/build.gradle.kts
samples/server/petstore/kotlin-springboot-delegate/pom.xml
samples/server/petstore/kotlin-springboot-delegate/settings.gradle
samples/server/petstore/kotlin-springboot-reactive/build.gradle.kts
samples/server/petstore/kotlin-springboot-reactive/pom.xml
samples/server/petstore/kotlin-springboot-reactive/settings.gradle
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/PetApiService.kt
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/StoreApiService.kt
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/UserApiService.kt
samples/server/petstore/kotlin-springboot/build.gradle.kts
samples/server/petstore/kotlin-springboot/pom.xml
samples/server/petstore/kotlin-springboot/settings.gradle
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApiService.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/StoreApiService.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/UserApiService.kt

- replace tabs with spaces
- minor code format change
```
``` 

[Kotlin] replace tab with spaces, minor code format change

---

modules/openapi-generator/src/main/resources/scala-finch/api.mustache
samples/server/petstore/scala-finch/src/main/scala/org/openapitools/apis/PetApi.scala
samples/server/petstore/scala-finch/src/main/scala/org/openapitools/apis/StoreApi.scala
samples/server/petstore/scala-finch/src/main/scala/org/openapitools/apis/UserApi.scala

- use Files.createTempFile to avoid potential security issues
```
``` 
cc @clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)

[Scala][Finch] use Files.createTempFile to avoid potential security issues

---

modules/openapi-generator/src/main/resources/typescript-nestjs/README.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/README.md

Revert changes in the readme
For https://github.com/OpenAPITools/openapi-generator/pull/8775/files#r580041567
```
``` 

[TS] Revert changes in nestjs readme

---

docs/generators/python-aiohttp.md
docs/generators/python-blueplanet.md
docs/generators/python-flask.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonLegacyClientCodegen.java
samples/server/petstore/python-aiohttp-srclayout/src/openapi_server/openapi/openapi.yaml
samples/server/petstore/python-aiohttp/openapi_server/openapi/openapi.yaml
samples/server/petstore/python-flask/openapi_server/openapi/openapi.yaml

- create Python abstract class
- minor code format change (Java files)
- only change in the samples (output) is the addition of `title` in the model's properties
```
``` 
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) …

[Refactor] create Python abstract class

---

modules/openapi-generator/src/main/resources/dart-dio/api.mustache
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/default_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/pet_api_test.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/store_api_test.dart

* first construct a `RequestOptions` instance with all parameters etc. inline
* then construct and serialize the body data
* then send the request and await the response
* then deserialize the response
* always use the `specifiedType` for built_value (de)serialization instead of a mix of ways (this does the same as finding the serializer directly)
* use indent of 2 spaces (as per Dart convention)
* prefix all local variables to prevent name clashes with parameters 
* add 2 tests that (de)serialize collections and add API key header
```
```  …

[dart][dart-dio] API class/template refactoring

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/api.mustache

When a GET/PUT/POST operations includes queryParams, then the feign generator wrongly generates the Basename instead of the paramName. That leads to
a java.illegalstateException ("Body parameters cannot be used with form parameters") in Feign Contract when attempting to invoke the Method.
i.e: a generated feign client:
public interface PersonClientTest extends RestApi {
@RequestLine("GET /personen/{kundenNummer}?mitUnterstruktur={mitUnterstruktur}")
@Headers({
"Accept: application/json",
"If-None-Match: {ifNoneMatch}"
})
PersonOut getPersonByKundenNummer(@Param(value="kundenNummer", expander=ParamExpander.class) String kundenNummer, @Param(value="If-None-Match", expander=ParamExpander.class) String ifNoneMatch, @Param(value="mitUnterstruktur", expander=ParamExpander.class) Boolean …

FIX: [Java Feign Generator]- Error in api.mustache template

---

docs/generators/java.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/main/resources/Java/model.mustache
modules/openapi-generator/src/main/resources/Java/modelEnum.mustache
modules/openapi-generator/src/main/resources/Java/modelInnerEnum.mustache
modules/openapi-generator/src/main/resources/Java/pojo.mustache
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/BigCat.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/BigCatAllOf.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/EnumArrays.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/EnumClass.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/EnumTest.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/MapTest.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/Order.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/OuterEnum.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/model/Pet.java

This PR adds JSON-B as a serialization option in the Java client. It is based on the work done in the Microprofile library with the goal of eventually replacing the library-specific templates created there. This is the JSON-B changes from #8716.
```
```  …

[Java][Client] JSON-B serialization support

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
samples/openapi3/client/petstore/go/go-petstore/api/openapi.yaml
samples/openapi3/client/petstore/go/go-petstore/docs/NullableClass.md
samples/openapi3/client/petstore/go/go-petstore/model_nullable_class.go

This applies the Nullable change to all variables on the model, instead of just
the ones in vars.
```
``` 

Make nullable fix on all vars in Go

---

samples/server/petstore/go-api-server/pom.xml

Run `go test` in the CI to catch issues instead
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01)
```
``` 

Better test for go-server

---

modules/openapi-generator/src/main/resources/go-gin-server/main.mustache
samples/server/petstore/go-gin-api-server/main.go
samples/server/petstore/go-gin-api-server/pom.xml

- Test go-gin-server sample with `go test -v
Similar to https://github.com/OpenAPITools/openapi-generator/pull/8852
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01)
```
``` 

Test go-gin-server sample with `go test -v`

---

modules/openapi-generator/src/main/resources/dart-dio/api.mustache
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/default_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart

* add null check for non-required/nullable parameters
Related to https://github.com/OpenAPITools/openapi-generator/issues/8271

[dart][dart-dio] Handle nullable/required header/query parameters

---

samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/fake_api_test.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/pet_api_test.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/store_api_test.dart

* replace branch ref with commit ref (new release of http_mock_adapter coming soon)
```
``` 

[dart][dart-dio] Fix failing master due to unstable test dependency

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-header.mustache
samples/client/petstore/cpp-qt5/client/PFXHelpers.h

Add `QSet` to the header file
```
``` 

[C++][Qt5]Add QSet Header to the Helper

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
samples/client/petstore/cpp-qt5/client/PFXStoreApi.cpp
samples/client/petstore/cpp-qt5/client/PFXUserApi.cpp

Minor change in Indentation and readability to keep same style as the rest of the files
```
``` 
@ravinikam @stkrwork @MartinDelille @muttleyxd

[C++][QT]Minor change in Indentation and readability 

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.cpp.mustache
samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp

Fixes #8823
```
``` 
@ravinikam @stkrwork   @MartinDelille @muttleyxd

[C++][Qt]Make header checks case insensitive as described in RFC

---

README.md

Simple readme update to add Plaid.com to the docs.

Add Plaid to companies using the generator.

---

bin/utils/test_file_list.yaml
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools.Test/Api/PetApiTests.cs

- Add tests for array of string serialization
```
``` 

Add tests for array of string serialization

---

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/pom.mustache
samples/server/petstore/jaxrs-cxf-cdi/pom.xml

To fix https://github.com/OpenAPITools/openapi-generator/issues/8922
Fix dependency version to avoid [jaxrs-cxf-cdi](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/jaxrs-cxf-cdi) compilation error
Please take a look
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01) @wing328
```
```  …

[JaxRS] Fix ambiguous dependency (#8922)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java

Add messages about powershell ebook after generating a PowerShell client
```
################################################################################
################################################################################
```
```
``` 

Add messages about powershell ebook after generating a PowerShell client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
modules/openapi-generator/src/main/resources/aspnetcore/2.0/Project.csproj.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/Project.csproj.mustache
modules/openapi-generator/src/main/resources/aspnetcore/3.0/Project.csproj.mustache
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Org.OpenAPITools.csproj

Fixes aspnetcore generator not adding version to project file. On a side note also fixes the wrong target framework for non net5.0 targets.
```
``` 

[csharp][aspnetcore] Fix ASPNetCore not adding version to csproj

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java

An additional **reserved words** list is added for parameter name in **PowerShell**. The initial **reserved words** list contains all reserved words provided by **PowerShell**. However for the parameter name, only the **variables** extracted in the new list can't be passed as names of a **PowerShell Advanced** function parameter. With the additional **reserved words** list, keywords like **Filter** don't receive the additional prefix **Var** when they're parameter names.
Closes #8805
@wing328
```
```  …

[REQ][PowerShell] Add additional reserved words list for parameter name in PowerShell

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
samples/openapi3/client/petstore/java/jersey2-java8/api/openapi.yaml
samples/openapi3/client/petstore/java/native/api/openapi.yaml

This removes complex examples in Java which would not result in valid
code.
```
``` 

Skip examples on complex body in Java

---

modules/openapi-generator/src/main/resources/dart-dio/api.mustache

There doesn't seem to be an example for this.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/8878
```
``` 
CC @agilob

[dart][dart-dio] Fix missing byte response cast

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java

- Update sponsorship message in the R generator
```
``` 

Update sponsorship message in the R generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java

Update post code generation message in the Perl client generator
```
``` 
cc @wing328 (2017/07)  @yue9944882 (2019/06)

Update post code generation message in the Perl client generator

---

docs/customization.md

Update docs of skipFormModel default value

---

modules/openapi-generator/src/main/resources/android/libraries/volley/build.mustache
modules/openapi-generator/src/main/resources/android/libraries/volley/pom.mustache
samples/client/petstore/android/volley/build.gradle
samples/client/petstore/android/volley/pom.xml

- Remove unnecessary dependencies
```
implementation "org.apache.httpcomponents:httpcore:$httpcore_version"
implementation "org.apache.httpcomponents:httpclient-android:$httpclient_version"
```
```
``` 
cc @jaz-ah (2017/09)

[Android][Volley] Remove unnecessary dependencies

---

docs/generators/dart-dio.md
docs/generators/dart-jaguar.md
docs/generators/dart.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartJaguarClientCodegen.java
modules/openapi-generator/src/main/resources/dart-dio/auth/auth.mustache
samples/client/petstore/dart-dio/petstore_client_lib/lib/auth/auth.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/auth/auth.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/auth/auth.dart

* none of the dart generators supports XML
* jaguar is no longer maintained
* dart and dart-dio support bearer token
* none of the dart generators supports composition atm.
```
``` 
CC @swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) …

[dart] Generic docs update and fixes

---

docs/generators/aspnetcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
modules/openapi-generator/src/main/resources/aspnetcore/2.0/Project.csproj.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/Project.csproj.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/Project.nuspec.mustache
modules/openapi-generator/src/main/resources/aspnetcore/3.0/Project.csproj.mustache
modules/openapi-generator/src/main/resources/aspnetcore/3.0/Project.nuspec.mustache
samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/spring-mvc-default-value/src/main/java/org/openapitools/api/TestHeadersApi.java
samples/server/petstore/spring-mvc-default-value/src/main/java/org/openapitools/api/TestQueryParamsApi.java

Update aspnetcore nuspec and csproj with authors and description
```
``` 

[csharp][aspnetcore] Update aspnetcore nuspec and csproj with authors and description

---

docs/generators/csharp-netcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java

- mark httpclient support as experimental
```
``` 

[c#][netcore] mark httpclient support as experimental

---

modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools.Test/Api/PetApiTests.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/server/petstore/spring-mvc-default-value/src/main/java/org/openapitools/api/TestHeadersApi.java
samples/server/petstore/spring-mvc-default-value/src/main/java/org/openapitools/api/TestQueryParamsApi.java

[csharp][csharp-netcore] Fix Fileupload for Request Bodies for RestSharp and HttpClient libraries

---

modules/openapi-generator/src/main/resources/Java/libraries/webclient/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache
samples/client/petstore/java/webclient/build.gradle
samples/client/petstore/java/webclient/pom.xml

- update WebClient dependencies to newer versions
- use `spring-boot-starter-webflux` instead of `spring-webflux` (as my local tests failed with  `spring-webflux` and `spring-boot-starter-webflux` fixed the issue
```
``` 
cc @bbdouglas (2017/07) @sreeshas …

[Java] Update WebClient dependencies

---

bin/configs/csharp-netcore-OpenAPIClient-httpclient.yaml
modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Org.OpenAPITools.csproj

[csharp][httpclient] Fix accidental use of c# 8 language feature

---

pom.xml

maven-jar-plugin 3.2.0

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java

Reverts OpenAPITools/openapi-generator#8061

Revert "Enable useOneOfInterfaces for the ruby generator"

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java

minor code improvement based on https://sonarcloud.io/dashboard?id=OpenAPITools_openapi-generator
```
``` 
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) …

[python]] minor code improvement

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
samples/client/petstore/ruby-faraday/.openapi-generator/FILES
samples/client/petstore/ruby/.openapi-generator/FILES
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/.openapi-generator/FILES
samples/openapi3/client/features/dynamic-servers/ruby/.openapi-generator/FILES
samples/openapi3/client/features/generate-alias-as-model/ruby-client/.openapi-generator/FILES

- remove duplicated declaration
- `supportingFiles.add(new SupportingFile("configuration.mustache", gemFolder, "configuration.rb"));`
※ Before correction
After generation, in `.openapi-generator/FILES`
```
.gitignore
.openapi-generator-ignore
.rspec
.rubocop.yml
.travis.yml
Gemfile
README.md
Rakefile
docs/ApiResponse.md
docs/Category.md
docs/Order.md
docs/Pet.md
docs/PetApi.md
docs/StoreApi.md
docs/Tag.md
docs/User.md
docs/UserApi.md
git_push.sh
lib/openapi_client.rb
lib/openapi_client/api/pet_api.rb
lib/openapi_client/api/store_api.rb
lib/openapi_client/api/user_api.rb
lib/openapi_client/api_client.rb
lib/openapi_client/api_error.rb
lib/openapi_client/configuration.rb
lib/openapi_client/configuration.rb
lib/openapi_client/models/api_response.rb
lib/openapi_client/models/category.rb …
```

[Ruby] remove duplicated supportingFiles.add

---

docs/generators/rust.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java

Add enum suffix support. The default is an empty string for backward compatibility.
```
```  …

[Rust] Add enum suffix support

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/LuaClientCodegen.java

EclipseJdt cleanup 'ConvertForLoopToEnhanced' applied by erefactor.

[cleanup] erefactor/EclipseJdt - Convert 'for' loops to enhanced

---

modules/openapi-generator/src/main/resources/dart-dio/pubspec.mustache
modules/openapi-generator/src/main/resources/dart/libraries/dio/pubspec.mustache
samples/client/petstore/dart-dio/petstore_client_lib/pubspec.yaml
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/pubspec.yaml
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake_tests/pubspec.yaml
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake_tests/test/api/pet_api_test.dart
samples/openapi3/client/petstore/dart-dio/petstore_client_lib/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/pet_api_test.dart

* update dio for dart-dio-next
* fix build problems with analyzer & Dart 2.12 for dart-dio
```
``` 

[dart][dart-dio] Update dependencies

---

README.md

Add links to blog posts about openapi-generator
```
``` 

Add links to blog posts about openapi-generator

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-header.mustache
samples/client/petstore/cpp-qt5/client/PFXHelpers.h

```
``` 
Quick fix to include `<QVariant>` and fix a compilation error on MacOS. I didn't dig more why it doesn't fails on Linux.

Include QVariant helpers header

---

modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
modules/openapi-generator/src/main/resources/go-server/helpers.mustache
modules/openapi-generator/src/main/resources/go-server/impl.mustache
modules/openapi-generator/src/main/resources/go-server/routers.mustache
samples/server/petstore/go-api-server/go/api_pet.go
samples/server/petstore/go-api-server/go/api_store.go
samples/server/petstore/go-api-server/go/api_user.go
samples/server/petstore/go-api-server/go/helpers.go
samples/server/petstore/go-api-server/go/impl.go
samples/server/petstore/go-api-server/go/routers.go

This pull request is intended to provide the capability to specify headers to include in the response.
This is needed, for example, to allow a REST API to redirect the client to a new URL (using the Location header).
This pull request includes also the changes in the pull request https://github.com/OpenAPITools/openapi-generator/pull/8144

goserver - Allow to specify headers to add to the response

---

modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java

Use StandartCharsets.UTF_8 instead of Charset.forName("utf-8") in generated java api clients

---

modules/openapi-generator/src/main/resources/dart/libraries/dio/pubspec.mustache
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/pubspec.yaml
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake_tests/pubspec.yaml
samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml

* required built_value update
* finally use released versions for http mocking
```
``` 

[dart][dart-dio] Minor dependency update

---

modules/openapi-generator/src/main/resources/go/client.mustache
modules/openapi-generator/src/main/resources/go/response.mustache
samples/client/petstore/go/go-petstore/client.go
samples/client/petstore/go/go-petstore/response.go
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/response.go
samples/openapi3/client/petstore/go/go-petstore/client.go
samples/openapi3/client/petstore/go/go-petstore/response.go

I found the typos.Here is fix.
```
``` 

[Go] Fix golang comment typos

---

.travis.yml
modules/openapi-generator-cli/Dockerfile

To support different CPU architectures (e.g. arm64)
```
``` 

[Docker] support multi-arch build

---

modules/openapi-generator/src/main/resources/typescript-angular/configuration.mustache
samples/client/petstore/typescript-angular-v10-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-angular-v10-provided-in-root/builds/with-npm/configuration.ts
samples/client/petstore/typescript-angular-v11-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-angular-v11-provided-in-root/builds/with-npm/configuration.ts
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/configuration.ts
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/configuration.ts
samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/configuration.ts
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/configuration.ts
samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/configuration.ts
samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-npm/configuration.ts
samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-prefixed-module-name/configuration.ts
samples/client/petstore/typescript-angular-v9-provided-in-any/builds/default/configuration.ts
samples/client/petstore/typescript-angular-v9-provided-in-root/builds/default/configuration.ts
samples/client/petstore/typescript-angular-v9-provided-in-root/builds/with-npm/configuration.ts

This fixes #9259 and may possibly fix #8980 and fix #8983
```
``` 

typescript-angular: Fix Cannot read property 'apiKey' of undefined

---

modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-body.mustache
modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-header.mustache
samples/client/petstore/cpp-qt5/client/PFXHelpers.cpp
samples/client/petstore/cpp-qt5/client/PFXHelpers.h

fixes #9279
```
``` 
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @MartinDelille (2018/03) @muttleyxd (2019/08)

Qt5 support date format enum

---

modules/openapi-generator/src/main/resources/powershell/api_doc.mustache
samples/client/petstore/powershell/docs/PSPetApi.md
samples/client/petstore/powershell/docs/PSStoreApi.md
samples/client/petstore/powershell/docs/PSUserApi.md

- improve return type documentation
```
``` 

[PowerShell] improve return type documentation

---

modules/openapi-generator/src/main/resources/powershell/appveyor.mustache
samples/client/petstore/powershell/appveyor.yml

minor improvements to the auto-generated appveyor.yml
```
``` 

[PS] minor improvements to the auto-generated appveyor.yml

---

README.md

Add a link to blog post in unibuddy tech blog
```
``` 

Add a link to blog post in unibuddy tech blog

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/AbstractOpenApiSchema.mustache

* Fixing package name in `AbstractOpenApiSchema.mustache`
```
```  …

[Java][Jersey2]: Fixing package name in AbstractOpenApiSchema.java

---

modules/openapi-generator/src/main/resources/python/api.mustache
modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py

Cherrypick #9254
Credit @jirikuncar
Fix `inclusive_maximum`
```
``` 

[Python] Fix exclusive min and max

---

CI/.drone.yml
CI/circle_parallel.sh
bin/meta-codegen.sh
bin/utils/test-fake-petstore-for-all.sh
samples/meta-codegen/usage/src/org/openapitools/api/PetApi.sample
samples/meta-codegen/usage/src/org/openapitools/api/StoreApi.sample
samples/meta-codegen/usage/src/org/openapitools/api/UserApi.sample

Move ensure up-to-date script to drone.io

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.sbt
samples/client/petstore/java/okhttp-gson-parcelableModel/build.sbt
samples/client/petstore/java/okhttp-gson/build.sbt

Bump OkHTTP dependency to latest in build.sbt: `3.14.7` to `4.9.1`
Tested locally and the output compiles.
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann …

[Java][okhttp] Bump OkHTTP dependency to latest in build.sbt

---

CI/.drone.yml

- Migrate CI to drone.io as shippable CI is no longer available to this project.
```
``` 

[Erlang] migrate CI to drone.io

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache

Fixes https://github.com/OpenAPITools/openapi-generator/issues/8600
```
``` 

[kotlin][client] fix warning for non optional header parameter

---

docs/generators/kotlin.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java

This PR supersedes https://github.com/OpenAPITools/openapi-generator/pull/8471 and fixes 
```
``` 

[kotlin][client] improve moshi code gen docs

---

docs/generators/scala-sttp.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
modules/openapi-generator/src/main/resources/scala-sttp/build.sbt.mustache
modules/openapi-generator/src/main/resources/scala-sttp/project/build.properties.mustache
samples/client/petstore/scala-sttp/build.sbt
samples/client/petstore/scala-sttp/project/build.properties

Bump minor versions of libraries, SBT and Scala.
cc @clasnake (2017/07), @jimschubert (2017/09) heart, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)

[scala-sttp] Bump minor versions of libraries, SBT and Scala

---

modules/openapi-generator/src/main/resources/scala-sttp/api.mustache
modules/openapi-generator/src/main/resources/scala-sttp/project/build.properties.mustache
samples/client/petstore/scala-sttp/project/build.properties
samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/PetApi.scala

- remove trailing spaces
- remove blank lines
```
``` 
cc @clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)

[Scala] better code format

---

.travis.yml
samples/client/petstore/crystal/pom.xml
samples/client/petstore/crystal/shard.lock

Update crystal version to 1.0.0 (from 0.35.1).
ref: 
- https://crystal-lang.org/install/on_ubuntu/
- https://software.opensuse.org/download.html?project=devel%3Alanguages%3Acrystal&package=crystal
```
``` 
@wing328

[crystal] Update crystal version 1.0.0 (from 0.35.1)

---

README.md

Add a link to powershell devops conf presentation
```
``` 

Add a link to powershell devops conf presentation

---

pom.xml

Reduce Travis CI job runtime
- comment out C test (not functioning as intented)
- comment out php server tests (will be moved to Gtihub action). will be tested manually for the time being.
```
``` 

Reduce Travis CI job runtime

---

modules/openapi-generator/src/main/resources/typescript/auth/auth.mustache

https://github.com/OpenAPITools/openapi-generator/issues/9475
```
``` 

fix api key in query 

---

modules/openapi-generator/src/main/resources/JavaSpring/beanValidationPathParams.mustache
modules/openapi-generator/src/main/resources/JavaSpring/beanValidationQueryParams.mustache
modules/openapi-generator/src/main/resources/JavaSpring/optionalDataType.mustache

#8690
```
``` 
@bbdouglas
@sreeshas 
@jfiala 
@lukoyanov 
@cbornet 
@jeff9finger 
@karismann 
@Zomzog 
@lwlee2608 
@nmuesch

Fix bean validation for type Optional

---

.github/actions/run-samples/action.yaml
.github/workflows/samples-dart.yaml
CI/circle_parallel.sh
pom.xml
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/pom.xml
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake_tests/test/model/date_serializer_test.dart

**Suggestions/Assumptions**
* future release branches (`5.2.x`) should be named `release/5.2.x` or some use different pattern that can be globbed in the workflow files
* there should be a separate workflow for Samples of each platform/language
```
``` 

[dart][ci] Move Dart samples from CircleCI to Github actions

---

modules/openapi-generator/src/main/resources/cpp-ue4/api-operations-header.mustache
modules/openapi-generator/src/main/resources/cpp-ue4/api-operations-source.mustache
modules/openapi-generator/src/main/resources/cpp-ue4/model-header.mustache
modules/openapi-generator/src/main/resources/cpp-ue4/model-source.mustache

Added public methods to process enums in string form as it may be useful for the user code
```
``` 
- @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08) @wing328

[cpp-ue4] Added public methods to process enums in string form

---

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/application.mustache
modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache
samples/server/petstore/springboot-virtualan/pom.xml

Upgrade Virtualan version with 2.2.1 -> Open API Mock service

---

modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
samples/client/petstore/javascript-es6/src/api/FakeApi.js
samples/client/petstore/javascript-promise-es6/src/api/FakeApi.js
samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
samples/client/petstore/ruby-faraday/lib/petstore/api/fake_api.rb
samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/FakeApi.ts
samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/fake_api.dart
samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api/fake_api.dart
samples/openapi3/client/petstore/python-legacy/petstore_api/api/fake_api.py

Update query parameter sample to include pipe delimiter

---

modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/auth/OAuthOkHttpClient.kt.mustache
samples/client/petstore/kotlin-gson/build.gradle
samples/client/petstore/kotlin-jackson/build.gradle
samples/client/petstore/kotlin-json-request-string/build.gradle
samples/client/petstore/kotlin-jvm-okhttp4-coroutines/build.gradle
samples/client/petstore/kotlin-moshi-codegen/build.gradle
samples/client/petstore/kotlin-nonpublic/build.gradle
samples/client/petstore/kotlin-nullable/build.gradle
samples/client/petstore/kotlin-okhttp3/build.gradle
samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/build.gradle
samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/auth/OAuthOkHttpClient.kt
samples/client/petstore/kotlin-retrofit2-rx3/build.gradle
samples/client/petstore/kotlin-retrofit2-rx3/src/main/kotlin/org/openapitools/client/auth/OAuthOkHttpClient.kt
samples/client/petstore/kotlin-retrofit2/build.gradle
samples/client/petstore/kotlin-retrofit2/src/main/kotlin/org/openapitools/client/auth/OAuthOkHttpClient.kt
samples/client/petstore/kotlin-string/build.gradle
samples/client/petstore/kotlin-threetenbp/build.gradle
samples/client/petstore/kotlin-uppercase-enum/build.gradle
samples/client/petstore/kotlin/build.gradle

This PR updates the kotlin client dependencies and make gradle compatible with version 7.X
```
``` 

[kotlin][client] update dependencies

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java

Add sponsor message to python-fastapi generator
```
``` 

Add sponsor message to python-fastapi generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java

I think it's time to declare swift 5 generator as stable.
It's been out for a year and half, without major issues, so I think it's time now.
This PR should only be merged after https://github.com/OpenAPITools/openapi-generator/pull/9625
```
``` 
@jgavris …

[swift][client] make swift 5 generator stable

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java
modules/openapi-generator/src/main/resources/python-fastapi/README.mustache
modules/openapi-generator/src/main/resources/python-fastapi/api_test.mustache
pom.xml
samples/server/petstore/python-fastapi/.openapi-generator/FILES
samples/server/petstore/python-fastapi/README.md
samples/server/petstore/python-fastapi/pom.xml
samples/server/petstore/python-fastapi/test_python3.sh
samples/server/petstore/python-fastapi/tests/test_pet_api.py
samples/server/petstore/python-fastapi/tests/test_store_api.py
samples/server/petstore/python-fastapi/tests/test_user_api.py

- better tests to avoid status code comparison
- better readme 
- add CI tests
- fix paypal link
```
```  …

[python][fastapi] various minor improvements

---

modules/openapi-generator/src/main/resources/python-fastapi/model.mustache
modules/openapi-generator/src/main/resources/python-fastapi/model_field_type.mustache
samples/server/petstore/python-fastapi/src/openapi_server/models/api_response.py
samples/server/petstore/python-fastapi/src/openapi_server/models/category.py
samples/server/petstore/python-fastapi/src/openapi_server/models/order.py
samples/server/petstore/python-fastapi/src/openapi_server/models/pet.py
samples/server/petstore/python-fastapi/src/openapi_server/models/tag.py
samples/server/petstore/python-fastapi/src/openapi_server/models/user.py

Generate validators for the models fields
```
``` 

Add validators to models fields

---

docs/generators.md
modules/openapi-generator-maven-plugin/examples/kotlin.xml

- Fix kotlin client issue in maven plugin tests:
```
[ERROR] /Users/williamcheng/Code/openapi-generator/modules/openapi-generator-maven-plugin/examples/target/generated-sources/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (183, 81) Unresolved reference: lowercase
[ERROR] /Users/williamcheng/Code/openapi-generator/modules/openapi-generator-maven-plugin/examples/target/generated-sources/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (198, 74) Unresolved reference: lowercase
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.5.10:compile (compile) on project sample-project: Compilation failure: Compilation failure: 
[ERROR] /Users/williamcheng/Code/openapi-generator/modules/openapi-generator-maven-plugin/exampl …
```

Fix kotlin client issue in maven plugin tests

---

modules/openapi-generator/src/main/resources/powershell/api.mustache
samples/client/petstore/powershell/src/PSPetstore/Api/PSPetApi.ps1
samples/client/petstore/powershell/src/PSPetstore/Api/PSStoreApi.ps1
samples/client/petstore/powershell/src/PSPetstore/Api/PSUserApi.ps1

To properly encode URL parameters
To closes https://github.com/OpenAPITools/openapi-generator/issues/8364
Credits: @EngineerCoding 
```
``` 

[PowerShell] properly encode URL parameters

---

README.md

Add a link to flutter blog post
```
``` 

Add a link to flutter blog post

---

appveyor.yml

- sleep 15s after starting the web server
- set clone depth
```
``` 

Fix Appveyor CI issues 

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/JSON.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/build.sbt.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/pom.mustache
samples/client/petstore/java/resteasy/README.md
samples/client/petstore/java/resteasy/build.gradle
samples/client/petstore/java/resteasy/build.sbt
samples/client/petstore/java/resteasy/pom.xml
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/AdditionalPropertiesClass.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/ArrayOfArrayOfNumberOnly.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/ArrayOfNumberOnly.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/ArrayTest.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/EnumArrays.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/FileSchemaTestClass.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/MapTest.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/MixedPropertiesAndAdditionalPropertiesClass.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/Pet.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/TypeHolderDefault.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/TypeHolderExample.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/XmlItem.java

- Update resteasy dependencies
- Remove jdk7 support
- Add help method `setJava8ModeAndAdditionalProperties`
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann …

[Java] Update resteasy dependencies

---

.github/workflows/samples-dart.yaml
.github/workflows/samples-kotlin.yaml
samples/client/petstore/kotlin-nullable/settings.gradle

* in pull requests only run the samples that matter
* if a sample is outdated it will still fail in the build pipeline
* all checks will still run on push/merge in master
```
``` 

[ci] Only run samples when they actually changed

---

modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/date.mustache
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/date.dart

This is a minor fix for converting a Date to DateTime with the utc option set to true

[dart] fix Date.toDateTime utc

---

README.md

Thanks to Julian(@jfastnacht) for Slim3 generator.
Since Slim4 codegen is based on deprecated Slim3 I greatly appreciate your commitment.
I hope you don't mind if I declare myself as current Slim4 templates author.
@wing328 I didn't find any places beside `README` where you show template creators and it's weird. Not even on the website.
```
```  …

Add ybelenko as php-slim4 template creator

---

modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache

Hide buildOauthRequestInterceptor under isOAuth section (#9147)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache

- Skip oauth-related files when the spec has no oauth defined
```
```  …

[Java][Feign] Skip oauth-related files when the spec has no oauth defined

---

README.md

Update readme with travis-ci.com 
```
``` 

Update readme with travis-ci.com

---

modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache
modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift

Fix typo (Unsuported -> Unsupported)

---

modules/openapi-generator/src/main/resources/go/client.mustache
samples/client/petstore/go/go-petstore/client.go
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go
samples/openapi3/client/petstore/go/go-petstore/client.go

Cherry-pick #9714
Credits: @icubbon
```
``` 

[Go-client] Fix inability to download files

---

README.md

Add a link to blog post about openapi-generator
```
``` 

Add a link to blog post about openapi-generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java

([link on the issue](https://github.com/OpenAPITools/openapi-generator/issues/8927))
```
``` 
Fixes
https://github.com/OpenAPITools/openapi-generator/issues/8927
(where there is all other information helping to reproduce the issue)
It could probably be …

Typescript angular discriminator mapping

---

.github/workflows/check-supported-versions.yaml

Fix GitHub action due to missing JAR
```
``` 

Fix GitHub action

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/android/AndroidClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharp/CSharpClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/csharp/CSharpModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/DartClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/dio/DartDioClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/dio/DartDioNextClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/eiffel/AbstractEiffelCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/eiffel/EiffelClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/fsharp/FSharpServerCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/AbstractGoCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/haskellhttpclient/HaskellHttpClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/haskellservant/HaskellModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaCXFClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelEnumTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/AbstractJavaJAXRSServerCodegenTest.java

AutoRefactor cleanup 'TestNGAssert' applied by erefactor:
Refactors to a proper use of TestNG assertions.
For AutoRefactor see https://github.com/JnRouvignac/AutoRefactor
--------
Dear Project Team!
This pull request is provided in the hope that it will be useful.
Changes are manually reviewed after they passed the test suite of
your project. Only successful reviews become project PRs.
Errors found are reported upstream to support the cleanup providers.
But please do a careful review of your own as usual because tools
have bugs and bugs in the changes may have been overlooked.
For scalability and out of fun and laziness, the creation of commits
and PRs and parts of the change handling are automated.
If you are not interested or want to …

[cleanup] erefactor/AutoRefactor - TestNG asserts

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

Better null check to surpress SonarCloud warning: https://sonarcloud.io/project/issues?id=OpenAPITools_openapi-generator&open=AXjJ4PVyUt4sElJCkJBz&resolved=false&types=BUG
```
``` 

Better null check to surpress SonarCloud warning

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

The bug described in #8064 has been fixed. Can I ask for your confirmation? @ph4r5h4d 
```
``` 

[go-server] Fix missing vendor extensions in inlined objects #8064

---

modules/openapi-generator/src/main/resources/ruby-client/travis.mustache
samples/client/petstore/ruby-faraday/.travis.yml
samples/client/petstore/ruby/.travis.yml
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/.travis.yml
samples/openapi3/client/features/dynamic-servers/ruby/.travis.yml
samples/openapi3/client/features/generate-alias-as-model/ruby-client/.travis.yml

Related issue: https://github.com/OpenAPITools/openapi-generator/issues/9970
```
``` 
Tagging the Ruby technical committee members: @cliffano @zlx @autopp

[Ruby] Add new Ruby versions to the Travis CI build matrix configuration

---

bin/configs/rust-hyper-petstore.yaml
bin/configs/rust-reqwest-petstore-async.yaml
bin/configs/rust-reqwest-petstore.yaml
samples/client/petstore/rust/hyper/petstore/docs/PetApi.md
samples/client/petstore/rust/hyper/petstore/docs/StoreApi.md
samples/client/petstore/rust/hyper/petstore/docs/UserApi.md
samples/client/petstore/rust/hyper/petstore/src/apis/pet_api.rs
samples/client/petstore/rust/hyper/petstore/src/apis/store_api.rs
samples/client/petstore/rust/hyper/petstore/src/apis/user_api.rs
samples/client/petstore/rust/reqwest/petstore-async/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-async/docs/StoreApi.md
samples/client/petstore/rust/reqwest/petstore-async/docs/UserApi.md
samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-async/src/apis/store_api.rs
samples/client/petstore/rust/reqwest/petstore-async/src/apis/user_api.rs
samples/client/petstore/rust/reqwest/petstore/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore/docs/StoreApi.md
samples/client/petstore/rust/reqwest/petstore/docs/UserApi.md
samples/client/petstore/rust/reqwest/petstore/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore/src/apis/store_api.rs
samples/client/petstore/rust/reqwest/petstore/src/apis/user_api.rs

FYI. @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)
```
``` 

Migrate Rust client samples to 3.0 spec

---

README.md

Add a link to Line engineering video
```
``` 

Add a link to LINE engineering video

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/UserApi.java

```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

[Java][resttemplate] better code format

---

modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pojo.mustache

This small change addresses this issue
https://github.com/OpenAPITools/openapi-generator/issues/8056
```
``` 

Move the JsonbProperty annotation from the getter to the field declaration

---

docs/generators/aspnetcore.md
docs/generators/csharp-dotnet2.md
docs/generators/csharp-netcore.md
docs/generators/csharp.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
modules/openapi-generator/src/main/resources/csharp-netcore/modelEnum.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/modelInnerEnum.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Model/EnumArrays.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Model/EnumArrays.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/EnumArrays.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/EnumArrays.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/EnumArrays.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/EnumArrays.cs

- fix property names
- fix enum XML comments
```
``` 

[C#][netcore] minor bug fixes

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.gradle
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.sbt
samples/client/petstore/java/okhttp-gson-dynamicOperations/pom.xml
samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
samples/client/petstore/java/okhttp-gson-parcelableModel/build.sbt
samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/okhttp-gson/build.sbt
samples/client/petstore/java/okhttp-gson/pom.xml

Fix missing jackson-databind-nullable in okhttp java client
```
```  …

[Java][okhttp] Fix missing jackson-databind-nullable dependency

---

modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache

Fixes typo in csharp-netcore generated code comment

[csharp-netcore] Fixed typo in httpclient generated code comment

---

README.md

Add Inquisico to list of generator users

---

bin/configs/java-micronaut-client.yaml
docs/generators.md
docs/generators/java-micronaut-client.md
docs/generators/php-dt.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautClientCodegen.java

- marked the generator as "beta"
- minor code format change
- renamed the generator to "java-micronaut-client"
cc @andriy-dmytruk 
cc Java Technical committee: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)
```
```  …

[java][micronaut] minor improvements

---

.github/PULL_REQUEST_TEMPLATE.md
bin/utils/release/release_version_update.sh
modules/openapi-generator-maven-plugin/examples/kotlin.xml
modules/openapi-generator-maven-plugin/examples/spring.xml

Minor update to use 5.3.0 in documentations and test files
```
``` 

Minor update to use 5.3.0 in documentations and test files

---

modules/openapi-generator/src/main/resources/python/api_doc.mustache
samples/client/petstore/python/docs/AnotherFakeApi.md
samples/client/petstore/python/docs/FakeApi.md
samples/client/petstore/python/docs/FakeClassnameTags123Api.md
samples/client/petstore/python/docs/PetApi.md
samples/client/petstore/python/docs/StoreApi.md
samples/client/petstore/python/docs/UserApi.md
samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/docs/AnotherFakeApi.md
samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/docs/FakeApi.md
samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/docs/FakeClassnameTags123Api.md
samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/docs/PetApi.md
samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/docs/StoreApi.md
samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/docs/UserApi.md
samples/openapi3/client/extensions/x-auth-id-alias/python/docs/UsageApi.md
samples/openapi3/client/features/dynamic-servers/python/docs/UsageApi.md
samples/openapi3/client/petstore/python/docs/AnotherFakeApi.md
samples/openapi3/client/petstore/python/docs/DefaultApi.md
samples/openapi3/client/petstore/python/docs/FakeApi.md
samples/openapi3/client/petstore/python/docs/FakeClassnameTags123Api.md
samples/openapi3/client/petstore/python/docs/PetApi.md
samples/openapi3/client/petstore/python/docs/StoreApi.md
samples/openapi3/client/petstore/python/docs/UserApi.md

Fix python generated markdown documentation for Jekyll 

---

modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache

[php][symfony] Use correct JMS/Serializer annotation for Date-Fields

---

pom.xml
samples/openapi3/client/petstore/typescript/tests/default/test/http/isomorphic-fetch.test.ts

enable typescript unit tests

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java

Fixes #10251 // This commit tries to improve the documentation on the relationship between the two configuration options library and serializationLibrary.
```
``` 

[#10251] Improve the documentation of the option serializationLibrary

---

docs/generators/scala-play-server.md
docs/generators/scala-sttp.md
docs/generators/scalatra.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java

This PR fixes the compilation error when a property is named as `clone`, please refer to [issue#10291 ](https://github.com/OpenAPITools/openapi-generator/issues/10291)
**Note:** by default, openapi-generator for scala-sttp escapes the reserved-keyword via ' -> see [this](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java#L291), `sbt compiler` works for most cases, but not for `clone`. Instead of hard-coded word-mapping, we can use the option `--reserved-words-mappings` to specified the mapping word as needed, for example
```
openapi-generator-cli generate \
-g scala-sttp \
-i name_of_file.yaml \
-p mainPackage=myPackage \
-o myApi \
--reserved-words-mappings=clone=cloning
``` …

[sala-sttp]Add 'clone' in reservedWords list

---

modules/openapi-generator/src/main/resources/JavaSpring/apiController.mustache

Used the useOptional flag in the ApiController template generator.
I run the TravisCI in my own git fork, build succeed
@bkabrda
fix #6728

Adding the useOptional in the ApiController

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pojo.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/pojo.mustache
modules/openapi-generator/src/main/resources/Java/pojo.mustache
modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/model/EnumTest.java
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/model/HealthCheckResult.java
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/model/NullableClass.java
samples/client/petstore/java/webclient-nulable-arrays/src/main/java/org/openapitools/client/model/ByteArrayObject.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/model/EnumTest.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/model/HealthCheckResult.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/model/NullableClass.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/AdditionalPropertiesClass.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Drawing.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/EnumTest.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/HealthCheckResult.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/NullableClass.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/User.java

issue: https://github.com/OpenAPITools/openapi-generator/issues/10213
```
``` 

[Java][Spring] fix imports for nullable helpers

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenExampleValuesTest.java
samples/client/petstore/java/apache-httpclient/docs/FakeApi.md
samples/client/petstore/java/google-api-client/docs/FakeApi.md
samples/client/petstore/java/jersey1/docs/FakeApi.md
samples/client/petstore/java/jersey2-java8-localdatetime/docs/FakeApi.md
samples/client/petstore/java/jersey2-java8/docs/FakeApi.md
samples/client/petstore/java/native-async/docs/FakeApi.md
samples/client/petstore/java/native/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson-dynamicOperations/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson-parcelableModel/docs/FakeApi.md
samples/client/petstore/java/okhttp-gson/docs/FakeApi.md
samples/client/petstore/java/resteasy/docs/FakeApi.md
samples/client/petstore/java/resttemplate-withXml/docs/FakeApi.md
samples/client/petstore/java/resttemplate/docs/FakeApi.md
samples/client/petstore/java/retrofit2-play26/docs/FakeApi.md
samples/client/petstore/java/retrofit2/docs/FakeApi.md
samples/client/petstore/java/retrofit2rx2/docs/FakeApi.md
samples/client/petstore/java/retrofit2rx3/docs/FakeApi.md
samples/client/petstore/java/vertx-no-nullable/docs/FakeApi.md
samples/client/petstore/java/vertx/docs/FakeApi.md
samples/client/petstore/java/webclient/docs/FakeApi.md
samples/openapi3/client/petstore/java/jersey2-java8/docs/FakeApi.md

Fixes #10256 
This fixes Java codegen. I introduced correct default values and examples for LocalDate, OffsetDateTime, BigDecimal, UUID.
Also here it is the support for inline enums: take the first value from availables as example. Works both for inline enums, and enums defined in schema components.
Created unit test to cover the changes.
to mention:
```
``` 
These …

Fix java examples

---

modules/openapi-generator/src/main/resources/dart/libraries/dio/auth/oauth.mustache
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/README.md
samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/auth/oauth.dart

There was a bug in OAuthInterceptor of dart-dio-next where it would never handle any request because of a condition that could never be true.
```
``` 
@jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela

[bugfix][dart-dio-next] Fix condition bug in dart-dio-next OauthInterceptor

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppTinyClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java

Code improvement based on https://sonarcloud.io/project/issues?id=OpenAPITools_openapi-generator&branch=master&resolved=false&types=BUG
```
``` 

Minor code improvement based on sonarcloud reports

---

README.md

Add a link to AWS ParallelCluster  API documentation
```
``` 

Add a link to AWS ParallelCluster  API documentation

---

modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache

Fix installation bug reported here https://github.com/kubernetes-client/c/pull/80#discussion_r706273123
```
``` 
@zhemant @ityuhui @michelealbano

Fix installation script

---

modules/openapi-generator-gradle-plugin/build.gradle

Addresses CVE described in this issue:
https://github.com/OpenAPITools/openapi-generator/issues/10377
```
``` 
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m …

Updates kotlin to v1.3.30

---

modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache

```
``` 
Fix for: https://github.com/OpenAPITools/openapi-generator/issues/10408
@mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti

[csharp-netcore] made Validate public.

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
modules/openapi-generator/src/test/resources/2_0/templates/Java/libraries/jersey2/ApiClient.mustache
samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java

[java][jersey2] Use 'this' to assign to class field.

---

modules/openapi-generator/src/main/resources/go/model_enum.mustache
samples/client/petstore/go/go-petstore/model_enum_class.go
samples/client/petstore/go/go-petstore/model_outer_enum.go
samples/openapi3/client/petstore/go/go-petstore/model_enum_class.go
samples/openapi3/client/petstore/go/go-petstore/model_outer_enum.go
samples/openapi3/client/petstore/go/go-petstore/model_outer_enum_default_value.go
samples/openapi3/client/petstore/go/go-petstore/model_outer_enum_integer.go
samples/openapi3/client/petstore/go/go-petstore/model_outer_enum_integer_default_value.go

fix: expose allowed values of the enum

---

modules/openapi-generator/src/main/resources/Java/model.mustache

Attempt to fix #8157
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch

Fix missing import for JsonTypeName

---

modules/openapi-generator/src/main/resources/php/phpunit.xml.mustache
samples/client/petstore/php/OpenAPIClient-php/phpunit.xml.dist

Update phpunit xml to newer format
```
``` 

Update phpunit xml to newer format

---

pom.xml

Addresses https://github.com/OpenAPITools/openapi-generator/issues/10375
```
```  …

update to handlebars.java 4.2.1

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java

Add decimal support to R client generator
```
``` 

Add decimal support to R client generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java

Use array examples when available.
```
``` 

Use array examples in Ruby

---

.travis.yml
CI/circle_parallel.sh
pom.xml

Move TypeScript, JavaScript tests to CircleCI
```
``` 
cc
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov …

Move TypeScript, JavaScript tests to CircleCI

---

README.md

Add a link to hackernoon article
```
``` 

Add a link to hackernoon article

---

samples/client/petstore/typescript-axios/builds/with-npm-version/package-lock.json
samples/client/petstore/typescript-axios/tests/default/package-lock.json

Regenerate package-lock.json so that the CI can test with the latest dependencies.
```
``` 
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) …

[TS][axios] Regenreate package-lock.json

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.sbt.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pom.mustache
samples/client/petstore/java/jersey2-java8-localdatetime/build.gradle
samples/client/petstore/java/jersey2-java8-localdatetime/build.sbt
samples/client/petstore/java/jersey2-java8-localdatetime/pom.xml
samples/client/petstore/java/jersey2-java8/build.gradle
samples/client/petstore/java/jersey2-java8/build.sbt
samples/client/petstore/java/jersey2-java8/pom.xml
samples/openapi3/client/petstore/java/jersey2-java8/build.gradle
samples/openapi3/client/petstore/java/jersey2-java8/build.sbt
samples/openapi3/client/petstore/java/jersey2-java8/pom.xml

update scribejava to 8.x (latest stable version)
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch …

[java][jersey2] update scribejava to 8.x

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiResponse.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/apiException.mustache
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiException.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiResponse.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiResponse.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiResponse.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiResponse.java

Better docstring in api client, exception, response class
```
``` 

[Java][okhttp] better docstring

---

pom.xml

Disable groovy test due to the following errors in the server side:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'groovy'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not resolve org.jfrog.buildinfo:build-info-extractor-gradle:2.0.16.
Required by:
project :
> Could not resolve org.jfrog.buildinfo:build-info-extractor-gradle:2.0.16.
> Could not get resource 'https://repo.jfrog.org/artifactory/gradle-plugins/org/jfrog/buildinfo/build-info-extractor-gradle/2.0.16/build-info-extractor-gradle-2.0.16.pom'.
> Could not GET 'https://www.jfrog.com/error?from=repo.jfrog.org&by=nginx-dedicated2e'. Received status code 403 from server: Forbidden
* Try:
Run with --stacktrace option to get the stack trace. Run …
```

Disable groovy client tests

---

modules/openapi-generator-maven-plugin/examples/java-client.xml
modules/openapi-generator-maven-plugin/examples/multi-module/pom.xml

Update maven plugin test dependencies to CI failure

---

modules/openapi-generator/src/main/resources/csharp-netcore/nuspec.mustache

Tested locally and the result is good:
```
Time Elapsed 00:00:05.57
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
Build: 0 errors, 8 warnings
```
```
```  …

Fix nuspec in csharp-netcore template

---

modules/openapi-generator/src/main/resources/csharp-netcore/netcore_project.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/nuspec.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Org.OpenAPITools.csproj

Update C# dependencies (Newtonsoft.Json, Polly) to newer version
```
``` 

[C#] Update C# dependencies to newer version

---

modules/openapi-generator/src/main/resources/kotlin-spring/api_test.mustache

Change test parameters. Should fix #10704
```
``` 
@jimschubert @dr4ke616 @karismann @andrewemery @4brunu @yutaka0m

[Kotlin][Spring] Fix required parameter in tests

---

README.md

Added Bunker Holding Group to companies list

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/others/java/okhttp-gson-streaming/build.gradle
samples/client/others/java/okhttp-gson-streaming/pom.xml
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.gradle
samples/client/petstore/java/okhttp-gson-dynamicOperations/pom.xml
samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/okhttp-gson/pom.xml

```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

[java][okhttp] Skip spotless as part of the check task

---

README.md

Add Qavar to the user list.
```
``` 

Add Qavar to the user list

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/apiException.mustache
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiException.java

- fix warnings using `@SuppressWarnings("serial")`
- better docstrings for constructors
```
```  …

[Okhttp] fix warnings and better docstrings for constructors

---

modules/openapi-generator/src/main/resources/Java/JSON.mustache
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/JSON.java

- fix outdated link in the comment
- improve the docstring of `setLenientOnJson`
```
```  …

[java][okhttp] fix outdated link, improve docstring

---

modules/openapi-generator/src/main/resources/JavaSpring/apiController.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/service.mustache
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/PetApiService.kt
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/StoreApiService.kt
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/UserApiService.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApiService.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/StoreApiService.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/UserApiService.kt

add comments to kotlin-spring's api method 
fix #8424
- [v] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [v] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [v] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
```  …

[kotlin-spring] add comment to api method

---

modules/openapi-generator/src/main/resources/codegen/pom.mustache
samples/meta-codegen/lib/pom.xml

Update meta codegen template junit to latest version 4.13.2
```
``` 

Update meta codegen template junit to latest version

---

README.md

README update: Add Airthings to list of generator users

---

docs/generators/crystal.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java

`annotation` is also reserved by crystal lang. Documentation is [here](https://crystal-lang.org/reference/syntax_and_semantics/annotations/index.html).
```
``` 

[crystal] Add annotation to reserved key word list of crystal lang

---

modules/openapi-generator/src/main/resources/swift5/APIHelper.mustache
modules/openapi-generator/src/main/resources/swift5/Extensions.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/Extensions.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/APIHelper.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/Extensions.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/Extensions.swift

Refactor some swift5 codes
- Use compactMap: ed52f324c6be6a55bb925400e28a00104550603d
- Remove as Any cast: a0980635c1e3485c014ee2d79d12a4a8d6980d72
- Remove unused array: a62aa84b348078bf0c2cbb61fde7bcc43644a33c
```
``` 

[swift5] Refactor some codes

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate-withXml/src/test/java/org/openapitools/client/ApiClientTest.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/test/java/org/openapitools/client/ApiClientTest.java

fix #10499 
Based on the description of the issue, Java resttemplate URL queryParams don't encode UTF-8 correctly.
For example,
```
https://localhost/v1/pets/v1.0/infos?code=1234&languages=fr%2Cen
https://localhost/v1/pets/v1.0/infos?code=1234&languages=fr,en
```
Add `URLEncoder` support to fix the issue with a unit test.
```
``` 
For …

[Java][resttemplate] Support URL queryParams Comma encoding

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
samples/client/petstore/haskell-http-client/.openapi-generator/VERSION

Adds codegenParameter.schema to allow referenced schemas in parameters
This allows referenced schemas in request parameters as https://github.com/OpenAPITools/openapi-generator/issues/10927 requests.
In the future whole parameters may be referenced, so adding a class property which stores a schema codegenProperty allows us to:
- store when there is a schema for a Parameter
- tell when that schema is referenced to a component
- will allow us to tell the difference in the future between a referenced Parameter and a referenced parameter schema
- right now for a single schema or content schema, those schema's properties like isMap are stored on codegenParameter. 
- that is an unclear way to do it because let's say the parameter references parameter definition in components/parameters as a ref …

Adds codegenParameter.schema to allow referenced schemas in parameters

---

.github/workflows/check-supported-versions.yaml
.github/workflows/gradle-test.yaml
.github/workflows/openapi-generator.yaml
.github/workflows/samples-dart.yaml
.github/workflows/samples-kotlin.yaml
.github/workflows/sonar.yml

- use setup-java v2 everywhere
- use Temurin JDK everywhere
https://github.com/actions/setup-java/blob/main/README.md
```
NOTE: Adopt OpenJDK got moved to Eclipse Temurin and 
won't be updated anymore. It is highly recommended to 
migrate workflows from adopt to temurin to keep receiving 
software and security updates.
```
```
``` 
For …

update GitHub Actions

---

docs/generators/kotlin.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache

It is currently not possible to use the Kotlin Multiplatform generator template to generate a Gradle child module. This is a problem for projects that wish to do that.
I created an example project that demonstrates the issue as well as how this change resolves the problem: https://github.com/Airthings/openapi-multiplatform-multi-module
The demo project uses the existing Kotlin Multiplatform Petstore API sample. If you check out the project and try to build it you get the following error:
```
$ ./gradlew
> Configure project :shared
[ omitted ]
FAILURE: Build failed with an exception.
* Where:
Build file './openapi-multiplatform-multi-module/openapi-generator/samples/client/petstore/kotlin-multiplatform/build.gradle.kts' line: 3
* What went wrong:
Error resolving plugin [id: …
```

[Kotlin][Multiplatform] Support generating gradle module as child module

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenEncoding.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenMediaType.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/content-data.yaml
samples/server/petstore/python-aiohttp-srclayout/src/openapi_server/openapi/openapi.yaml
samples/server/petstore/python-aiohttp/openapi_server/openapi/openapi.yaml
samples/server/petstore/python-fastapi/openapi.yaml
samples/server/petstore/python-flask/openapi_server/openapi/openapi.yaml

Adds CodegenMediaType and CodegenEncoding
These are needed to allow request bodies to contain multiple content types and encoding definitions which are openapi 3.0.0+ features
One can read about these features in the openapi spec here https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-10
in the content section.
This PR sets codegenParameter.content for:
- fromParameter (query, header, cookie, path parameters)
- fromRequestBody (request body params)
Not covered:
- form parameters because this code assumes that there is one codegenParameter to set content on. For that to work for form parameters, only one type object form parameter must exist. In the shared code today, the object is exploded into multiple form parameters, each which were properties of the …

Adds request body content data to allow multiple content types to be sent to servers

---

modules/openapi-generator/src/main/resources/swift5/modelOneOf.mustache
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/Models/Fruit.swift

Fixes #10970.
@4brunu if you find the time to look at this PR, I'd highly appreciate it.

[swift5] Add Hashable to oneOf enums

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonLegacyClientCodegen.java

[python] fix file path

---

modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/enum.mustache
modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/enum_inline.mustache

Fix https://github.com/OpenAPITools/openapi-generator/issues/10410
```
``` 
CC @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

[dart][dio] Fix int64 based enums not correctly generated

---

README.md

Add links to blog posts, remove nmuesch remove java tech comm

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/anyof_model.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/oneof_model.mustache
modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-with-http-signature-okhttp-gson.yaml
samples/client/petstore/java/okhttp-gson-nextgen/.openapi-generator/FILES
samples/client/petstore/java/okhttp-gson-nextgen/README.md
samples/client/petstore/java/okhttp-gson-nextgen/api/openapi.yaml
samples/client/petstore/java/okhttp-gson-nextgen/docs/GmFruit.md
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Fruit.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/FruitReq.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/GmFruit.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Mammal.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/NullableShape.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Pig.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Quadrilateral.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Shape.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/ShapeOrNull.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Triangle.java
samples/client/petstore/java/okhttp-gson-nextgen/src/test/java/org/openapitools/client/JSONTest.java

- better error message in oneOf/anyOf
- add tests
```
``` 

[java][okhttp-gson-next-gen] better error message in oneOf/anyOf

---

samples/client/petstore/java/okhttp-gson-nextgen/src/test/java/org/openapitools/client/JSONTest.java

- add more tests for oneOf (serialization)
```
``` 

[java][okhttp-gson-next-gen] add more tests for oneOf

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java

resolve #11072 
- Adds **optional** to the nullable fields.

[Protobuf-Schema] Added field presence tracking

---

modules/openapi-generator/src/main/resources/Java/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/google-api-client/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/google-api-client/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resteasy/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache
modules/openapi-generator/src/main/resources/Java/pom.mustache
samples/client/petstore/java/google-api-client/build.gradle
samples/client/petstore/java/google-api-client/pom.xml
samples/client/petstore/java/jersey1/build.gradle
samples/client/petstore/java/jersey1/pom.xml
samples/client/petstore/java/resteasy/build.gradle
samples/client/petstore/java/resteasy/pom.xml
samples/client/petstore/java/retrofit2-play26/build.gradle
samples/client/petstore/java/retrofit2-play26/pom.xml
samples/client/petstore/java/retrofit2/pom.xml
samples/client/petstore/java/retrofit2rx2/pom.xml
samples/client/petstore/java/retrofit2rx3/pom.xml
samples/client/petstore/java/webclient-nulable-arrays/build.gradle
samples/client/petstore/java/webclient-nulable-arrays/pom.xml
samples/client/petstore/java/webclient/build.gradle
samples/client/petstore/java/webclient/pom.xml

- update Java client dependencies to newer versions
```
``` 

[java][client] update dependencies to newer versions

---

.github/workflows/samples-kotlin.yaml
README.md
samples/client/petstore/kotlin-jvm-volley/gradle.properties

Test kotlin volley sample in the CI

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/auth/RetryingOAuth.mustache
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/auth/RetryingOAuth.java
samples/client/petstore/java/okhttp-gson-nextgen/src/test/java/org/openapitools/client/auth/RetryingOAuthTest.java

- Fix OAuth enum name
```
``` 

[java][okhttp-gson-nextgen] Fix OAuth enum name

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppTizenClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/K6ClientCodegen.java

Various minor bug fixes based on sonar report: https://sonarcloud.io/project/issues?id=OpenAPITools_openapi-generator&resolved=false
```
``` 

Various minor bug fixes based on sonar report

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/scala/ScalaGatlingCodegenTest.java

[scala-gatling] add ScalaGatlingCodegenTest

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java

- fix import mapping for JsonValue
```
``` 

[kotlin][spring] fix import mapping for JsonValue

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java

Minor bug fixes: https://sonarcloud.io/project/issues?id=OpenAPITools_openapi-generator&open=AX4a21mv1B2j6S6yzy0m&resolved=false&types=BUG
```
``` 
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) …

[TS][fetch] Minor bug fixes

---

README.md

update in readme: Manticore Search uses the generator too

---

modules/openapi-generator/src/main/resources/python-legacy/asyncio/rest.mustache
modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache
samples/client/petstore/python-asyncio/petstore_api/rest.py

- [X ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
```
```  …

feat(python-asyncio): add support for proxy config using system env vars

---

README.md

Adds spacether sponsorship link and python-experimental item
```
``` 

Adds spacether sponsorship link and python-experimental item

---

modules/openapi-generator/src/main/resources/python-experimental/README_common.handlebars
modules/openapi-generator/src/main/resources/python-experimental/__init__apis.handlebars
modules/openapi-generator/src/main/resources/python-experimental/api_doc_example.handlebars
modules/openapi-generator/src/main/resources/python-legacy/__init__api.mustache
modules/openapi-generator/src/main/resources/python-legacy/__init__package.mustache
modules/openapi-generator/src/main/resources/python-legacy/api_test.mustache
modules/openapi-generator/src/main/resources/python/README_common.mustache
modules/openapi-generator/src/main/resources/python/__init__apis.mustache
modules/openapi-generator/src/main/resources/python/api_doc_example.mustache
modules/openapi-generator/src/main/resources/python/api_test.mustache

[python] modify python import classVarName to classFileName

---

CI/circle_parallel.sh
pom.xml
samples/openapi3/client/petstore/python-legacy/test/test_fake_api.py
samples/openapi3/client/petstore/python-legacy/test_python2.sh

Turns python-legacy CI back on in circle, fixes python-legacy test
python-legacy testing was no longer active on PR circleCI
It is on on master branch CI and we saw a master branch failure at: https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds/244792765
@Amelia0193 @wing328 
This PR is a fix for a test failure introduced in: https://github.com/OpenAPITools/openapi-generator/pull/11140
```
```  …

Turns python-legacy CI back on in circle, fixes python-legacy test

---

modules/openapi-generator/src/main/resources/csharp-netcore/HttpSigningConfiguration.mustache
samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs

- remove duplicated condition in `HttpSigningConfiguration.cs`
```
``` 

[csharp][netcore] remove duplicated condition

---

modules/openapi-generator/src/main/resources/csharp-netcore/api_test.mustache

- update API tests to work with nonPublicApi option when set to true
- tested locally to confirm no compilation errors
```
``` 

[csharp][netcore] update API tests to work with nonPublicApi option

---

modules/openapi-generator/pom.xml
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java

[java] javaparser 3.24.0

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java

[java] JavaClientCodegenTest validateJavaSourceFiles

---

pom.xml

mockito 4.2.0

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/auth/RetryingOAuth.mustache
samples/client/petstore/java/okhttp-gson-nextgen/pom.xml
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/auth/RetryingOAuth.java

Update docstring in ApiClient, RetryingOAuth to fix the warnings reported by Javadoc
```
```  …

[java][okttp-gson-nextgen] update docstring in ApiClient, RetryingOAuth

---

docs/installation.md

Fix typo in script name in docs/installation.md

---

modules/openapi-generator/src/main/resources/java-undertow-server/pom.mustache
samples/server/petstore/java-undertow/pom.xml

Update dependencies to newer versions
```
``` 

[java][undertwo] update junit dependencies

---

modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/server/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/eap/gradle.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/gradle.mustache
samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml
samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml
samples/server/petstore/jaxrs-cxf-test-data/.openapi-generator/FILES
samples/server/petstore/jaxrs-cxf/pom.xml
samples/server/petstore/jaxrs-resteasy/default-value/build.gradle
samples/server/petstore/jaxrs-resteasy/default/build.gradle
samples/server/petstore/jaxrs-resteasy/eap-java8/build.gradle
samples/server/petstore/jaxrs-resteasy/eap-joda/build.gradle
samples/server/petstore/jaxrs-resteasy/eap/build.gradle
samples/server/petstore/jaxrs-resteasy/java8/build.gradle
samples/server/petstore/jaxrs-resteasy/joda/build.gradle

- update junit dependencies to 4.13.1
```
``` 

[jaxrs][cxf][resteasy] update junit dependencies to 4.13.1

---

modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts

fix isListContainer with isArray in the templates
```
``` 
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov …

[TS][nestjs] fix isListContainer with isArray

---

modules/openapi-generator/src/main/resources/python/__init__model.mustache

fix a error in the template
```
``` 

[Python] add missing } in __init__model.mustache

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache
samples/client/others/java/okhttp-gson-streaming/build.gradle
samples/client/others/java/okhttp-gson-streaming/build.sbt
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.gradle
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.sbt
samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
samples/client/petstore/java/okhttp-gson-parcelableModel/build.sbt
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/okhttp-gson/build.sbt

Update build.gradle, build.sbt with javax.ws.rs dependencies
```
``` 

[java][okhttp-gson] Update build.gradle, build.sbt

---

pom.xml

mockito 4.3.1

---

modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache

Replace tabs with spaces in JavaScript templates
```
``` 

Replace tabs with spaces in JavaScript templates

---

modules/openapi-generator/src/main/resources/JavaVertXServer/pom.mustache
modules/openapi-generator/src/main/resources/JavaVertXWebServer/apiImpl.mustache
samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/PetApiImpl.java
samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/StoreApiImpl.java
samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/UserApiImpl.java

Vertx has moved HttpStatusException (vertx internal) to HttpException (public)
https://github.com/vert-x3/wiki/wiki/4.1.0-Deprecations-and-breaking-changes#iovertxextwebhandlerimplhttpstatusexception
This is a breaking change in vertx, so this is a priority fix. The changes can be tested by adding the plugin to a Java project and building with vertx-core and vertx-web on the current version, 4.2.4.
NOTE: A similar PR is at https://github.com/OpenAPITools/openapi-generator/pull/10299, but author has been inactive and has not addressed issues with the PR mentioned by @wing328 .
``` …
```

[java][vertx] moved HttpStatusException (vertx internal) to HttpException (public)

---

.github/workflows/samples-groovy.yaml
.github/workflows/samples-spring.yaml
samples/client/petstore/groovy/README.md

- add Groovy client tests to Github workflow
```
``` 

[Groovy] add Groovy client tests to Github workflow

---

.github/workflows/samples-java-play-framework.yaml
pom.xml
samples/server/petstore/java-play-framework-async/pom.xml
samples/server/petstore/java-play-framework-fake-endpoints-with-security/pom.xml
samples/server/petstore/java-play-framework-no-nullable/pom.xml
samples/server/petstore/java-play-framework/README

Migrate Java Play framework tests from CircleCI to Github action
```
```  …

Test Java Play framework in Github action

---

modules/openapi-generator/src/main/resources/JavaVertXWebServer/queryParams.mustache

See issue: https://github.com/OpenAPITools/openapi-generator/issues/11597
```
``` 

[JAVA] [Vertx/Web] Add default value to query parameters

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaModelTest.java

Better code format for various java files
```
``` 

[General] Better code format

---

modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/beanValidationModel.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/beanValidationPath.mustache
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApi.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/model/Category.kt
samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/PetApiController.kt
samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/StoreApiController.kt
samples/server/petstore/kotlin-springboot-modelMutable/src/main/kotlin/org/openapitools/api/UserApiController.kt
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/PetApiController.kt
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/StoreApiController.kt
samples/server/petstore/kotlin-springboot-reactive/src/main/kotlin/org/openapitools/api/UserApiController.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApiController.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/StoreApiController.kt
samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/UserApiController.kt

Add `@Email` validation annotation for kotlin-spring
```
``` 
- @jimschubert @dr4ke616 @karismann  @Zomzog  @andrewemery  @4brunu @yutaka0m

Support email validation in kotlin-spring

---

.github/workflows/samples-jaxrs.yaml
pom.xml
samples/server/petstore/jaxrs/jersey2/README.md

Migrate JAX-RS server tests to Github action
```
``` 

Migrate JAX-RS server tests to Github action

---

.github/workflows/samples-java-client-jdk11.yaml
pom.xml
samples/client/petstore/java/feign/README.md

move some client tests to Github actions
```
``` 

[Java] move some client tests to Github actions 

---

modules/openapi-generator/src/main/resources/kotlin-vertx-server/pom.mustache
samples/server/petstore/kotlin-vertx-modelMutable/pom.xml
samples/server/petstore/kotlin/vertx/pom.xml

Update kotlin vertx server dependencies
```
``` 

Update kotlin vertx server dependencies

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJerseyServerCodegenTest.java

[java] enhance unit tests for JavaJerseyServerCodegen

---

pom.xml

https://github.com/apache/maven-compiler-plugin/releases/tag/maven-compiler-plugin-3.10.0
```
``` 

maven-compiler-plugin 3.10.0

---

modules/openapi-generator-cli/pom.xml
modules/openapi-generator/src/main/resources/Java/libraries/feign/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom.mustache
modules/openapi-generator/src/main/resources/JavaInflector/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/server/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/pom.mustache
modules/openapi-generator/src/main/resources/java-pkmst/pom.mustache
samples/client/petstore/java/feign-no-nullable/pom.xml
samples/client/petstore/java/feign/pom.xml
samples/client/petstore/java/microprofile-rest-client/pom.xml
samples/client/petstore/jaxrs-cxf-client-jackson/pom.xml
samples/client/petstore/jaxrs-cxf-client/pom.xml
samples/openapi3/client/petstore/jaxrs-cxf-client-jackson-nullable/pom.xml
samples/server/petstore/java-inflector/pom.xml
samples/server/petstore/java-pkmst/pom.xml
samples/server/petstore/jaxrs-cxf-annotated-base-path/pom.xml
samples/server/petstore/jaxrs-cxf-non-spring-app/pom.xml
samples/server/petstore/jaxrs-cxf/pom.xml
samples/server/petstore/jaxrs-datelib-j8/pom.xml
samples/server/petstore/jaxrs-jersey/pom.xml
samples/server/petstore/jaxrs/jersey2-useTags/pom.xml
samples/server/petstore/jaxrs/jersey2/pom.xml

Latest version of logback
https://logback.qos.ch/news.html
```
``` 

[java] logback 1.2.10

---

README.md

👋 Thank you for all of the hard work maintaining this project! I use openapi-generator extensively over at [print-nanny.com](https://www.print-nanny.com/) to generate API clients in Python, Rust, and Typescript. 
```
``` 

Add print-nanny.com to project list

---

pom.xml

jackson 2.13.1

---

modules/openapi-generator/src/main/resources/JavaJaxRS/pom.mustache
samples/server/petstore/jaxrs-datelib-j8/pom.xml
samples/server/petstore/jaxrs-jersey/pom.xml
samples/server/petstore/jaxrs/jersey2-useTags/pom.xml
samples/server/petstore/jaxrs/jersey2/pom.xml

[java] jaxrs swagger-core 1.6.5

---

modules/openapi-generator/pom.xml
pom.xml

https://github.com/TNG/ArchUnit/releases/tag/v0.23.0
```
``` 

archunit 0.23.0

---

modules/openapi-generator/src/test/java/org/openapitools/codegen/ArchUnitRulesTest.java

update ArchUnit rules

---

pom.xml

kotlin 1.6.10

---

modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/JSON.mustache
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/JSON.java

- fix build warning in javadoc
```
``` 

[java][native] fix build warning in javadoc

---

modules/openapi-generator/pom.xml
modules/openapi-generator/src/test/java/org/openapitools/codegen/TestUtils.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJerseyServerCodegenTest.java
pom.xml

use the [OpenRewrite](https://github.com/openrewrite) Maven parser to verify that the pom.xml is valid.
```
``` 

validate pom.xml files

---

modules/openapi-generator/src/main/resources/JavaPlayFramework/securityApiUtils.mustache
samples/server/petstore/java-play-framework-api-package-override/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-async/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-controller-only/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-fake-endpoints-with-security/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-fake-endpoints/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-no-bean-validation/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-no-exception-handling/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-no-interface/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-no-nullable/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-no-swagger-ui/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework-no-wrap-calls/app/openapitools/SecurityAPIUtils.java
samples/server/petstore/java-play-framework/app/openapitools/SecurityAPIUtils.java

Nothing risky here. Just removed warnings / code smells that were consistently pop in my generated projects that are scanned by SonarQube.
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) …

[Play Framework] Fix sonarqube warnings / code smells from the generated code.

---

modules/openapi-generator/src/main/resources/Java/RFC3339DateFormat.mustache
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/feign/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/google-api-client/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/jersey1/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/rest-assured-jackson/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/webclient-nulable-arrays/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/RFC3339DateFormat.java
samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/RFC3339DateFormat.java

Updated RFC3339DateFormat java mustache template to correctly initialize numberFormat field

Fixed RFC3999DateFormat clone NPE

---

samples/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java

A follow-up PR for https://github.com/OpenAPITools/openapi-generator/pull/11705
```
``` 

Add test for RFC3999DateFormat clone method

---

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
modules/openapi-generator/src/main/resources/ruby-client/configuration_tls_faraday_partial.mustache

Expose [Faraday Proxy Settings](https://lostisland.github.io/faraday/usage/customize#proxy).
```
``` 

Expose proxy settings for Ruby Faraday

---

docs/generators/java.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java

- Add useOneOfDiscriminatorLookup option so that it's shown in the `java` generator doc properly
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) …

[Java] Add useOneOfDiscriminatorLookup option

---

pom.xml

archunit 0.23.1

---

pom.xml

openrewrite 7.19.0

---

docs/faq.md
website/docusaurus.config.js
website/src/pages/index.js

Small change to update slack join links in documentation see: https://github.com/OpenAPITools/openapi-generator/issues/11716
```
``` 

Fix slack join links in documentation

---

modules/openapi-generator/src/main/resources/csharp-netcore-functions/Configuration.mustache
modules/openapi-generator/src/main/resources/csharp-netcore/Configuration.mustache

Fixes the injection of ClientCertificates in Configuration.mustache for csharp netcore and netcore-functions.
ClientCertificates was not being configured properly as part of the csharp client generation. These changes have been tested locally. Original issue link: https://github.com/OpenAPITools/openapi-generator/issues/6940
```
``` 
For …

Fix ClientCertificates in csharp configuration for client generation.

---

modules/openapi-generator/src/main/resources/php-slim4-server/config_dev_default.mustache
modules/openapi-generator/src/main/resources/php-slim4-server/config_prod_default.mustache
samples/server/petstore/php-slim4/config/dev/default.inc.php
samples/server/petstore/php-slim4/config/prod/default.inc.php

Just found more descriptive config declaration. Makes source code more readable.
```
``` 

[php-slim4] Tiny config comments

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/scala/AbstractScalaCodegenTest.java

This PR fixes the issue [#11721](https://github.com/OpenAPITools/openapi-generator/issues/11721)
Here is the openapi spec that can be used to reproduce the issue and verify the fix.
```yaml
openapi: 3.0.0
info:
title: stringToModelMapping
version: "1.0.0"
paths:
/:
get:
summary: Empty Route
responses:
"200":
description: Good Request.
content:
schema:
type: array
items:
$ref: '#/components/schemas/FreeformObjectTypes'
"400":
description: Bad Request.
"403":
description: Forbidden. Access denied.
components:
schemas:
SimpleModel:
type: object
properties:
name:
type: string
ArrayModel:
type: array
items:
$ref: '#/components/schemas/SimpleModel'
FreeformObjectTypes:
type: object
properties:
stringToModelMapping:
type: object
$ref: …
```

[scala-client]fix missing type in StringToArrayModelMapping

---

modules/openapi-generator/src/main/resources/typescript/api/api.mustache
samples/openapi3/client/petstore/typescript/builds/deno/apis/PetApi.ts
samples/openapi3/client/petstore/typescript/builds/deno/apis/StoreApi.ts
samples/openapi3/client/petstore/typescript/builds/deno/apis/UserApi.ts

Code generated with v5.4.0 does not work with typescript deno.
```
$ wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.4.0/openapi-generator-cli-5.4.0.jar -O openapi-generator-cli.jar
$ java -jar openapi-generator-cli.jar generate -i https://petstore.swagger.io/v2/swagger.json -g typescript --additional-properties=platform=deno -o generated-src
$ deno
Deno 1.19.3
exit using ctrl+d or close()
> import * as petstore from "./generated-src/index.ts";
const configuration = petstore.createConfiguration();
const petApi = new petstore.PetApi(configuration);
const pets = await petApi.findPetsByStatus(["available"]); 
console.log(pets.slice(0, 5));
Uncaught TypeError: Module not found "file:///home/chiba/data/work/oag/generated-src/auth/auth".
at …
```

[typescript(experimental)] fix for Deno

---

modules/openapi-generator/src/main/resources/csharp/api.mustache

- [✅  ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ✅ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ✅ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
```
- [ ✅ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [✅ ] If your PR is targeting a particular programming language, …

MustacheTemplateUpdate csharp

---

docs/generators/groovy.md
docs/generators/java-camel.md
docs/generators/java-inflector.md
docs/generators/java-micronaut-client.md
docs/generators/java-micronaut-server.md
docs/generators/java-msf4j.md
docs/generators/java-pkmst.md
docs/generators/java-play-framework.md
docs/generators/java-undertow-server.md
docs/generators/java-vertx-web.md
docs/generators/java-vertx.md
docs/generators/java.md
docs/generators/jaxrs-cxf-cdi.md
docs/generators/jaxrs-cxf-client.md
docs/generators/jaxrs-cxf-extended.md
docs/generators/jaxrs-cxf.md
docs/generators/jaxrs-jersey.md
docs/generators/jaxrs-resteasy-eap.md
docs/generators/jaxrs-resteasy.md
docs/generators/jaxrs-spec.md
docs/generators/spring.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/VendorExtension.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java

Add few more vendor extensions to docs
```
``` 

[Java] update list of vendor extensions

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.sbt.mustache
samples/client/others/java/okhttp-gson-streaming/build.gradle
samples/client/others/java/okhttp-gson-streaming/build.sbt
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.gradle
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.sbt
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
samples/client/petstore/java/okhttp-gson-parcelableModel/build.sbt
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/build.gradle
samples/client/petstore/java/okhttp-gson/build.sbt
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

- fix uncheck type cast waning
- update build.gradle, buld.sbt to junit 5.x
```
```  …

[java][okhttp-gson] Fix warning, update build.gradle, build.sbt

---

modules/openapi-generator/src/main/resources/java-msf4j-server/pom.mustache
samples/server/petstore/java-msf4j/pom.xml

- use JDK8 in msf4j code
```
``` 

[java][msf4j] use JDK8 in msf4j code

---

README.md

I'm no more developing on this technology.
I will focus on other fields, and let other community members manage this part.

Remove myself from Python community

---

docs/generators/csharp-netcore-functions.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CsharpNetcoreFunctionsServerCodegen.java

This issue appears while running `export_generator.sh csharp-netcore-functions`
```
Error: Exception in thread "main" java.lang.IllegalStateException: Duplicated options! generateBody and generateBody
at org.openapitools.codegen.cmd.ConfigHelp.lambda$generateMdConfigOptions$0(ConfigHelp.java:174)
at java.util.Map.merge(Map.java:1175)
at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at …
```

[C#/.NET] remove duplicate CLI option

---

README.md
docs/core-team.md
pom.xml
website/src/dynamic/team.yml

Removed myself from the core team and php technical committee because I have no more time to work on the project.
It has been my pleasure to contribute to this project. I wish you all the best!
```
``` 

Remove ackintosh from core team and technical committee

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
modules/openapi-generator/src/test/resources/bugs/issue_11897.yaml

Fix for https://github.com/OpenAPITools/openapi-generator/issues/11897
```
``` 
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02)

[Java][Spring] Fix Array response

---

modules/openapi-generator/src/main/resources/python-legacy/api.mustache
samples/client/petstore/python-asyncio/petstore_api/api/another_fake_api.py
samples/client/petstore/python-asyncio/petstore_api/api/fake_api.py
samples/client/petstore/python-asyncio/petstore_api/api/fake_classname_tags123_api.py
samples/client/petstore/python-asyncio/petstore_api/api/pet_api.py
samples/client/petstore/python-asyncio/petstore_api/api/store_api.py
samples/client/petstore/python-asyncio/petstore_api/api/user_api.py
samples/client/petstore/python-legacy/petstore_api/api/another_fake_api.py
samples/client/petstore/python-legacy/petstore_api/api/fake_api.py
samples/client/petstore/python-legacy/petstore_api/api/fake_classname_tags123_api.py
samples/client/petstore/python-legacy/petstore_api/api/pet_api.py
samples/client/petstore/python-legacy/petstore_api/api/store_api.py
samples/client/petstore/python-legacy/petstore_api/api/user_api.py
samples/client/petstore/python-tornado/petstore_api/api/another_fake_api.py
samples/client/petstore/python-tornado/petstore_api/api/fake_api.py
samples/client/petstore/python-tornado/petstore_api/api/fake_classname_tags123_api.py
samples/client/petstore/python-tornado/petstore_api/api/pet_api.py
samples/client/petstore/python-tornado/petstore_api/api/store_api.py
samples/client/petstore/python-tornado/petstore_api/api/user_api.py
samples/openapi3/client/petstore/python-legacy/petstore_api/api/another_fake_api.py
samples/openapi3/client/petstore/python-legacy/petstore_api/api/fake_api.py
samples/openapi3/client/petstore/python-legacy/petstore_api/api/fake_classname_tags123_api.py
samples/openapi3/client/petstore/python-legacy/petstore_api/api/pet_api.py
samples/openapi3/client/petstore/python-legacy/petstore_api/api/store_api.py
samples/openapi3/client/petstore/python-legacy/petstore_api/api/user_api.py

This is a more brief and efficient way of accomplishing the same thing.
```
``` 
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess @arun-nalla @spacether

[Python] abbreviate dictionary membership testing idiom

---

modules/openapi-generator/src/main/resources/Java/api_doc.mustache
modules/openapi-generator/src/main/resources/Java/libraries/jersey2/api_doc.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/api_doc.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api_doc.mustache
modules/openapi-generator/src/main/resources/Java/libraries/rest-assured/api_doc.mustache
modules/openapi-generator/src/main/resources/Java/pojo_doc.mustache
modules/openapi-generator/src/main/resources/java-micronaut/client/doc/api_doc.mustache
modules/openapi-generator/src/main/resources/markdown-documentation/README.mustache
modules/openapi-generator/src/main/resources/markdown-documentation/api.mustache
modules/openapi-generator/src/main/resources/markdown-documentation/model.mustache

origin:
```
Name | Value
-----|------
foo  | bar
```
after:
```
| Name | Value |
|------|-------|
|  foo |  bar  |
```
```
``` 

fix markdown table format

---

docs/installation.md

Add documentation for scoop installation

---

README.md
docs/building.md

Fixed the following error when executing the command written in docs.
```bash
❯ ./run-in-docker.sh generate -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
-g go -o /gen/out/go-petstore --packageName=petstore
++ dirname ./run-in-docker.sh
+ cd .
+ maven_cache_repo=/Users/tim/.m2/repository
+ mkdir -p /Users/tim/.m2/repository
++ id -u
++ id -g
+ docker run --rm -it -w /gen -e GEN_DIR=/gen -e MAVEN_CONFIG=/var/maven/.m2 -e 'MAVEN_OPTS=-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=/var/maven/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Djacoco.skip=true' -u 502:20 -v /Users/tim/src/github.com/mkusaka/openapi-generator:/gen -v …
```

Fixed commands written in docs.

---

README.md
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/pom.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/pom.mustache
samples/server/petstore/jaxrs-cxf-cdi/pom.xml
samples/server/petstore/jaxrs-resteasy/default/pom.xml
samples/server/petstore/jaxrs-resteasy/java8/pom.xml
samples/server/petstore/jaxrs-resteasy/joda/pom.xml

fix #11342 Use https://search.maven.org/ for Maven Central links
```
``` 

fix #11342 Use https://search.maven.org/ for Maven Central links

---

.circleci/config.yml
CI/circle_parallel.sh
pom.xml
samples/client/petstore/scala-httpclient/build.sbt

[CircleCI] update image

---

.circleci/config.yml
.travis.yml
CI/circle_parallel.sh
pom.xml

Test PHP client with PHP 8.1.4 in Travis CI
```
``` 
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

Test PHP client in Travis CI

---

modules/openapi-generator/src/main/resources/Java/libraries/native/additional_properties.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java

Remove Javadoc warnings. fix #8692. 
```
``` 

[Java][Native] Remove Javadoc warnings. fix #8692

---

docs/installation.md

scoop install openapi-generator-cli
Installing 'openapi-generator-cli' (5.4.0) [64bit]
openapi-generator-cli-5.4.0.jar (24.1 MB) [===================================================================] 100%
Checking hash of openapi-generator-cli-5.4.0.jar ... ok.
Linking ~\scoop\apps\openapi-generator-cli\current => ~\scoop\apps\openapi-generator-cli\5.4.0
Creating shim for 'openapi-generator-cli'.
'openapi-generator-cli' (5.4.0) was installed successfully!
```
```  …

Correct scoop install command

---

pom.xml

surefire plugin 3.0.0-M6

---

modules/openapi-generator/src/main/resources/python-experimental/README_common.handlebars
modules/openapi-generator/src/main/resources/python-experimental/api_doc.handlebars
modules/openapi-generator/src/main/resources/python-experimental/api_doc_schema_type_hint.handlebars
modules/openapi-generator/src/main/resources/python-experimental/configuration.handlebars
modules/openapi-generator/src/main/resources/python-experimental/endpoint.handlebars
modules/openapi-generator/src/main/resources/python-experimental/schema_doc.handlebars
modules/openapi-generator/src/main/resources/python-experimental/setup.handlebars
samples/openapi3/client/petstore/python-experimental/docs/AnotherFakeApi.md
samples/openapi3/client/petstore/python-experimental/docs/DefaultApi.md
samples/openapi3/client/petstore/python-experimental/docs/FakeApi.md
samples/openapi3/client/petstore/python-experimental/docs/FakeClassnameTags123Api.md
samples/openapi3/client/petstore/python-experimental/docs/PetApi.md
samples/openapi3/client/petstore/python-experimental/docs/StoreApi.md
samples/openapi3/client/petstore/python-experimental/docs/UserApi.md

[python-experimental] Eliminates handlebars helper warnings
```
``` 

[python-experimental] Eliminates handlebars helper warnings

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java

Adds postProcess method to python-experimental
```
``` 

Adds postProcess method to python-experimental

---

README.md

Added [Brevy](https://www.brevy.com) to the list of companies using OpenAPI Generator.
Thank you for your amazing work!

Add Brevy to the list of companies

---

modules/openapi-generator/src/main/resources/haskell-servant/stack.mustache
samples/server/petstore/haskell-servant/stack.yaml

- Use the latest LTS in the stack.yaml configuration.
- Remove the previously introduced extra-deps that are not needed anymore.
- Update the petstore sample
```
``` 

Upgrade haskell-servant to latest LTS

---

bin/configs/cpp-qt-client.yaml
modules/openapi-generator/src/test/resources/3_0/cpp-qt/petstore.yaml
pom.xml
samples/client/petstore/cpp-qt/README.md
samples/client/petstore/cpp-qt/client/PFXPet.h
samples/client/petstore/cpp-qt/client/PFXPetApi.cpp
samples/client/petstore/cpp-qt/client/PFXPetApi.h
samples/client/petstore/cpp-qt/client/PFXStoreApi.cpp
samples/client/petstore/cpp-qt/client/PFXStoreApi.h
samples/client/petstore/cpp-qt/client/PFXUserApi.cpp
samples/client/petstore/cpp-qt/client/PFXUserApi.h

- update petstore to 3.0 spec
FYI. @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)
```
``` 

[C++][Qt] update petstore to 3.0 spec

---

README.md

FYI. @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03)
```
``` 

Add @mkusaka to TS technical committee

---

modules/openapi-generator/src/main/resources/ruby-client/api_client_typhoeus_partial.mustache
samples/client/petstore/ruby/lib/petstore/api_client.rb
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_client.rb
samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_client.rb
samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb

* implementation of https://github.com/OpenAPITools/openapi-generator/issues/10028
```
``` 

[REQ][Ruby] Ruby Allow Follow Redirect

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java

Fix for https://github.com/OpenAPITools/openapi-generator/issues/12143
```
```  …

[Java][OkHTTP] fix empty request body handling

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java

- renamed `openapi` (member) to `openAPI` to make it consistent with the code base overall.
- removed passing openAPI around different functions, use the member instead
This PR doesn't change the functionality of the resolver itself.
```
```  …

[Inline model resolver] minor enhancements/refactoring

---

modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Models/ApiResponse.cs
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Models/Category.cs
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Models/Order.cs
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Models/Pet.cs
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Models/Tag.cs
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Models/User.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Models/ApiResponse.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Models/Category.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Models/Order.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Models/Pet.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Models/Tag.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Models/User.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Models/ApiResponse.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Models/Category.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Models/Order.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Models/Pet.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Models/Tag.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Models/User.cs

Fixes #10772 for aspnetcore 3+, possibly #9071 as well (since the initial issue was about non-nullable numeric values)
This allows numbers to be set to zero, and booleans to be set to false.
It may make sense to port this fix to the other C# generators,
though it was partially fixed (for booleans only) in the netcore client in PR9042.
```
```  …

[AspNetCore] Emit default values for aspnetcore 3 value types

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
samples/server/petstore/aspnetcore-3.0/.openapi-generator/FILES
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/appsettings.Development.json
samples/server/petstore/aspnetcore-3.1/.openapi-generator/FILES
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/appsettings.Development.json
samples/server/petstore/aspnetcore-5.0/.openapi-generator/FILES
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/appsettings.Development.json
samples/server/petstore/aspnetcore-6.0/.openapi-generator/FILES
samples/server/petstore/aspnetcore-6.0/src/Org.OpenAPITools/appsettings.Development.json
samples/server/petstore/aspnetcore/.openapi-generator/FILES
samples/server/petstore/aspnetcore/src/Org.OpenAPITools/appsettings.Development.json

Previously the file was not used and not part of the output although it already exists as template
```
``` 

[aspnetcore] Include appsettings.Development.json

---

modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
samples/client/petstore/javascript-es6/src/ApiClient.js
samples/client/petstore/javascript-promise-es6/src/ApiClient.js

To close #10833
Based on https://github.com/OpenAPITools/openapi-generator/pull/10916
credit: @code1x1
```
``` 

Fix response type string in javascript mustache template

---

modules/openapi-generator/src/main/resources/python/api_client.mustache
modules/openapi-generator/src/main/resources/python/configuration.mustache
modules/openapi-generator/src/main/resources/python/rest.mustache
samples/client/petstore/python/petstore_api/api_client.py
samples/client/petstore/python/petstore_api/rest.py
samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api_client.py
samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/rest.py
samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/api_client.py
samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/configuration.py
samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/rest.py
samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api_client.py
samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/configuration.py
samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/rest.py
samples/openapi3/client/petstore/python/petstore_api/api_client.py
samples/openapi3/client/petstore/python/petstore_api/configuration.py
samples/openapi3/client/petstore/python/petstore_api/rest.py

- no functionality change
```
``` 
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @spacether (2019/11) ❤️

[python] Better code format

---

pom.xml

maven-compiler-plugin 3.10.1

---

pom.xml

rewrite 7.22.0

---

pom.xml

slf4j 1.7.36

---

pom.xml

scala maven plugin 4.6.1

---

.circleci/config.yml
CI/circle_parallel.sh

[CircleCI] improve execution time

---

modules/openapi-generator/src/main/resources/python-flask/base_model_.mustache

```
``` 
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @spacether (2019/11)

[python-flask] Fix mypy error type annotation needed

---

pom.xml

maven-jar-plugin 3.2.2

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
modules/openapi-generator/src/main/resources/kotlin-spring/generatedAnnotation.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/buildGradleKts.mustache
modules/openapi-generator/src/main/resources/kotlin-spring/libraries/spring-boot/pom.mustache
samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/ModelBase.h
samples/client/petstore/cpp-restsdk/client/src/ModelBase.cpp
samples/server/petstore/kotlin-springboot-delegate/build.gradle.kts
samples/server/petstore/kotlin-springboot-delegate/pom.xml
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApiController.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/PetApiDelegate.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApiController.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/StoreApiDelegate.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApiController.kt
samples/server/petstore/kotlin-springboot-delegate/src/main/kotlin/org/openapitools/api/UserApiDelegate.kt
samples/server/petstore/kotlin-springboot-modelMutable/build.gradle.kts
samples/server/petstore/kotlin-springboot-modelMutable/pom.xml
samples/server/petstore/kotlin-springboot-reactive/build.gradle.kts
samples/server/petstore/kotlin-springboot-reactive/pom.xml
samples/server/petstore/kotlin-springboot-source-swagger1/build.gradle.kts
samples/server/petstore/kotlin-springboot-source-swagger1/pom.xml
samples/server/petstore/kotlin-springboot-source-swagger2/build.gradle.kts
samples/server/petstore/kotlin-springboot-source-swagger2/pom.xml
samples/server/petstore/kotlin-springboot-springfox/build.gradle.kts
samples/server/petstore/kotlin-springboot-springfox/pom.xml
samples/server/petstore/kotlin-springboot-springfox/src/main/kotlin/org/openapitools/SpringFoxConfiguration.kt
samples/server/petstore/kotlin-springboot/build.gradle.kts
samples/server/petstore/kotlin-springboot/pom.xml

Updating Spring version and dependency versions in Kotlin Spring generated code
```
``` 
@jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @wing328

Kotlin spring version bump

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonExperimentalClientTest.java
modules/openapi-generator/src/test/resources/3_0/issue_12196.yaml

Adds fix and test for spec version detection
```
``` 

[python-experimental] Fixes spec version detection

---

pom.xml

mockito 4.5.1

---

pom.xml

maven-javadoc-plugin 3.4.0

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml
samples/client/petstore/java/okhttp-gson/.openapi-generator/FILES
samples/client/petstore/java/okhttp-gson/README.md
samples/client/petstore/java/okhttp-gson/api/openapi.yaml
samples/client/petstore/java/okhttp-gson/docs/ArrayOfInlineAllOf.md
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/JSON.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ArrayOfInlineAllOf.java
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ArrayOfInlineAllOfArrayAllofDogPropertyInner.java
samples/openapi3/client/petstore/go/go-petstore/api/openapi.yaml

- Fix inline allOf in request body
- Add tests
To fix https://github.com/OpenAPITools/openapi-generator/issues/8892
```
``` 

Fix inline allOf in request body

---

README.md

Hi!
Added 3DS Outscale in companies/projects using OpenAPI Generator.
Thanks for this awesome project ❤️

[README] Add Outscale to companies using OpenAPI Generator

---

README.md

Signed-off-by: zhucan <zhucan.k8s@gmail.com>
```
``` 

[README] add deeproute to company list

---

modules/openapi-generator/src/main/resources/cpp-qt-client/CMakeLists.txt.mustache
samples/client/petstore/cpp-qt/client/CMakeLists.txt

Note replacement of : #11950
Changed: Always add Qt5::Gui to build, needed because {{prefix}}Oauth.h is always part of the build
Added: find_package for OpenSSL, should be done prior target_link_libraries
(ubuntu) 
install deps (reference #11371 ): 
sudo apt install -y --no-install-recommends qt5-default 
run code generator:
java -jar openapi-generator-cli-5.4.0.jar generate -t cpp-qt-templates -i petstore.json -g cpp-qt-client -o petstore
run cmake:
cmake -S petstore -B petstore/build
(windows)
run code generator:
java -jar openapi-generator-cli-5.4.0.jar generate -t cpp-qt-templates -i petstore.json -g cpp-qt-client -o petstore
run cmake:
cmake -S petstore -B petstore/build
fixes #11371 
@wing328 
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @MartinDelille …

[Cpp][Qt][Client] Fix CMakeLists.txt, Qt::Gui, Find_Package(OpenSSL)

---

modules/openapi-generator/src/main/resources/r/Rbuildignore.mustache
samples/client/petstore/R/.Rbuildignore

update .Rbuildignore to include more files (e.g. ..RCheck) to fix the following during build:
```
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
.Rhistory
.gitignore
.openapi-generator-ignore
.travis.yml
..Rcheck
.Rproj.user
.openapi-generator
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
* checking for portable file names ... OK
```
```
```  …

[R] update .Rbuildignore with more files/directories

---

modules/openapi-generator/src/main/resources/JavaJaxRS/spec/api.mustache
modules/openapi-generator/src/main/resources/kotlin-server/libraries/jaxrs-spec/api.mustache
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/AnotherFakeApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/FakeApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/PetApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/StoreApi.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/UserApi.java
samples/server/petstore/kotlin-server/jaxrs-spec/src/main/kotlin/org/openapitools/server/apis/PetApi.kt
samples/server/petstore/kotlin-server/jaxrs-spec/src/main/kotlin/org/openapitools/server/apis/StoreApi.kt
samples/server/petstore/kotlin-server/jaxrs-spec/src/main/kotlin/org/openapitools/server/apis/UserApi.kt

Pure formatting, no functional changes. fixes #10746
```
```

[jaxrs-spec] Added linefeed between @Generated-annotation and class declaration

---

modules/openapi-generator/src/main/resources/android/libraries/volley/build.mustache
modules/openapi-generator/src/main/resources/android/libraries/volley/pom.mustache
samples/client/petstore/android/volley/build.gradle
samples/client/petstore/android/volley/pom.xml

Update Android dependencies to newer versions
```
``` 

Update Android dependencies to newer versions

---

modules/openapi-generator/src/main/resources/android/build.mustache
modules/openapi-generator/src/main/resources/android/pom.mustache
samples/client/petstore/android/httpclient/build.gradle
samples/client/petstore/android/httpclient/pom.xml

- update gson to 2.8.9
```
``` 

[android][httpclient] update gson to 2.8.9

---

modules/openapi-generator/src/main/resources/kotlin-vertx-server/pom.mustache
samples/server/petstore/kotlin-vertx-modelMutable/pom.xml
samples/server/petstore/kotlin/vertx/pom.xml

Update gson to newer version v2.8.9
```
``` 
--

[kotlin] Update gson to newer version

---

modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache

OkHttpClient - fix enum properties in requests #12450

---

README.md

Add Qovery to list of companies using the project

---

bin/configs/r-client.yaml
modules/openapi-generator/src/main/resources/r/api_doc.mustache
samples/client/petstore/R/.openapi-generator/FILES
samples/client/petstore/R/DESCRIPTION
samples/client/petstore/R/NAMESPACE
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/R/api_exception.R
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/docs/FakeApi.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/docs/StoreApi.md
samples/client/petstore/R/docs/UserApi.md
samples/client/petstore/R/test_petstore.R

Update R auto-generated doc to use snake_case instead of dot.case
Update tests to use rlang exception object instead
```
``` 

Update R auto-generated doc

---

modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
modules/openapi-generator/src/test/resources/bugs/issue_12494.yaml

[Java/Spring] Fix of issue #12494: call to superclass method is done with correct arguments

---

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom-sb3.mustache
modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/pom-sb3.mustache
samples/openapi3/client/petstore/spring-cloud-3/pom.xml
samples/openapi3/server/petstore/springboot-3/pom.xml

[BUG] Use https URL for Spring milestone repository
- Also set version for spring maven plugin as it does _not_ work with the milestone version
- Compiled samples (`samples/openapi3/client/petstore/spring-cloud-3` and `samples/openapi3/server/petstore/springboot-3`) using Java 17 to valiate
```
```  …

[BUG] Use https URL for Spring milestone repository

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/apiException.mustache
modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
samples/client/others/java/okhttp-gson-streaming/pom.xml
samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson-dynamicOperations/pom.xml
samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiException.java
samples/client/petstore/java/okhttp-gson/pom.xml
samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiException.java

Fix NPE in the response header
Fix junit5 issue in surefire plugin 
```
```  …

[java][okhttp-gson] Fix NPE in the response header, junit5 issue in surefire plugin 

---

.github/workflows/samples-php.yaml
.github/workflows/samples-php7.yaml
.github/workflows/samples-php8.yaml
bin/configs/php-laravel.yaml
bin/configs/php-symfony-SymfonyBundle-php.yaml
samples/server/petstore/php-laravel/lib/composer.json
samples/server/petstore/php-symfony/SymfonyBundle-php/README.md
samples/server/petstore/php-symfony/SymfonyBundle-php/composer.json
samples/server/petstore/php-symfony/SymfonyBundle-php/git_push.sh

```
``` 
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

Test PHP Symfony server sample in github action

---

modules/openapi-generator/src/main/resources/php-symfony/serialization/StrictJsonDeserializationVisitor.mustache
samples/server/petstore/php-symfony/SymfonyBundle-php/Service/StrictJsonDeserializationVisitor.php

-> https://www.php.net/manual/en/language.oop5.properties.php
```
``` 
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) [❤️](https://www.patreon.com/ackintosh/overview), @ybelenko (2018/07), …

[BUG] [PHP] [SYMFONY] Fix syntax error for $jsonDeserializationVisitor

---

modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
samples/client/others/java/okhttp-gson-streaming/build.gradle
samples/client/petstore/java/okhttp-gson-dynamicOperations/build.gradle
samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
samples/client/petstore/java/okhttp-gson/build.gradle

update build.gradle to work with junit5
```
``` 

[java][okhttp-gson] update build.gradle to work with junit5

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java

Skip generate operation examples when corresponding flag is set to true
```
``` 

[crystal][client] Skip generating operation examples when flag is set

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pojo.mustache
samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/FormatTest.java
samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/FormatTest.java

[jaxrs-spec] Use Arrays.equals and Arrays.hashCode by built-in array types

---

docs/generators/spring.md

Clarify inverted skipDefaultInterface configuration description
```
``` 

Clarify spring generator documentation

---

modules/openapi-generator/src/main/resources/r/modelOneOf.mustache
samples/client/petstore/R/R/pig.R
samples/client/petstore/R/test_petstore.R
samples/client/petstore/R/tests/testthat/test_petstore.R

- Fix toJSON in oneOf models
- add tests
```
``` 
cc@Ramanth (2019/07) @saigiridhar21 (2019/07)

[R] Fix toJSON in oneOf models, add tests

---

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom-sb3.mustache
modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/pom-sb3.mustache
samples/openapi3/client/petstore/spring-cloud-3/pom.xml
samples/openapi3/server/petstore/springboot-3/pom.xml

Add milestone repository for Spring maven plugin
Using java 17 to validate
`<checkoutroot>/openapi-generator/samples/openapi3/server/petstore/springboot-3$ mvn clean package`
```
``` 

Add milestone repository for Spring maven plugin

---

modules/openapi-generator/src/main/resources/go/client.mustache
samples/client/petstore/go/go-petstore/client.go
samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go
samples/openapi3/client/petstore/go/go-petstore/client.go

@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d 
Updated Go client mustache template to address gosec warnings, updated the samples too
```
``` 

[Go] Address Gosec vulnerabilities in Go client mustache template

---

modules/openapi-generator/src/main/resources/Java/libraries/jersey3/auth/OAuth.mustache
samples/client/petstore/java/jersey3/src/main/java/org/openapitools/client/auth/OAuth.java

- throw exception instead of logging a warning when failed to refresh token
```
```  …

[java][jersey3] throw exception when failed to refresh token #12431

---

docs/plugins.md

Updated maven plugin to the latest released version 6.0.0
```
``` 

Update plugins.md Maven Version

---

modules/openapi-generator/src/main/resources/r/description.mustache
samples/client/petstore/R/DESCRIPTION

Update RoxygenNote to newer version 7.2.0
```
``` 

[R] Update RoxygenNote to newer version

---

modules/openapi-generator/src/main/resources/r/api.mustache
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R

- update API methods doc to suppress warnings
```
``` 

[R] Update API doc

---

modules/openapi-generator/src/main/resources/Java/libraries/resteasy/pom.mustache
samples/client/petstore/java/resteasy/pom.xml

- RESTEasy to 4.7.6.Final
```
``` 

[Java] Update RESTEasy lib to newer version

---

modules/openapi-generator/src/main/resources/r/modelGeneric.mustache
samples/client/petstore/R/R/allof_tag_api_response.R
samples/client/petstore/R/R/animal.R
samples/client/petstore/R/R/basque_pig.R
samples/client/petstore/R/R/cat.R
samples/client/petstore/R/R/cat_all_of.R
samples/client/petstore/R/R/category.R
samples/client/petstore/R/R/danish_pig.R
samples/client/petstore/R/R/dog.R
samples/client/petstore/R/R/dog_all_of.R
samples/client/petstore/R/R/model_api_response.R
samples/client/petstore/R/R/order.R
samples/client/petstore/R/R/pet.R
samples/client/petstore/R/R/special.R
samples/client/petstore/R/R/tag.R
samples/client/petstore/R/R/update_pet_request.R
samples/client/petstore/R/R/user.R
samples/client/petstore/R/test_petstore.R
samples/client/petstore/R/tests/testthat/test_petstore.R

- minify json in toJSON to reduce payload size
- better variable naming in fromJSON, fromJSONString
```
``` 

[R] minify json in toJSON

---

modules/openapi-generator/src/main/resources/r/README.mustache
modules/openapi-generator/src/main/resources/r/api_doc.mustache
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/FakeApi.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/docs/StoreApi.md
samples/client/petstore/R/docs/UserApi.md

- installation procedure
- code sample
- [xx] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
```
``` 

[R] Improve documentation, readme, code sample

---

README.md

Update README to add Adyen to the list of companies using OpenAPI Generator

README: add Adyen

---

modules/openapi-generator/src/main/resources/r/modelGeneric.mustache
samples/client/petstore/R/R/allof_tag_api_response.R
samples/client/petstore/R/R/animal.R
samples/client/petstore/R/R/basque_pig.R
samples/client/petstore/R/R/cat.R
samples/client/petstore/R/R/cat_all_of.R
samples/client/petstore/R/R/category.R
samples/client/petstore/R/R/danish_pig.R
samples/client/petstore/R/R/dog.R
samples/client/petstore/R/R/dog_all_of.R
samples/client/petstore/R/R/model_api_response.R
samples/client/petstore/R/R/order.R
samples/client/petstore/R/R/pet.R
samples/client/petstore/R/R/special.R
samples/client/petstore/R/R/tag.R
samples/client/petstore/R/R/update_pet_request.R
samples/client/petstore/R/R/user.R
samples/client/petstore/R/test_petstore.R

- added toString method to easily print out the object
```
``` 

[R[ Add toString method in models

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R/R/special.R
samples/client/petstore/R/docs/Special.md

- Fix empty variable name 
- fix post process model incorrectly skipping postProcessModelsEnum 
```
``` 
cc @Ramanth (2019/07) @saigiridhar21 (2019/07)\

[R] Fix empty variable name, fix post process model

---

docs/generators/cpp-ue4.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppUE4ClientCodegen.java

Added support for unique items lists for UE4 code generator.
@wing328 @Kahncode
Testcase for testing: https://gist.github.com/madrazzl3/e9333e9404ac48467bac142388b0b05d
Fix #12742
```
``` 

[BUG] [CPP-UE4] Fix unique items list codegen

---

modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R/R/special.R
samples/client/petstore/R/docs/Special.md

add tests for item with special characters, numbers
```
``` 

[R] add tests for item with special characters

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
modules/openapi-generator/src/main/resources/ruby-client/gitlab-ci.mustache
samples/client/petstore/ruby-faraday/.gitlab-ci.yml
samples/client/petstore/ruby-faraday/.openapi-generator/FILES
samples/client/petstore/ruby/.gitlab-ci.yml
samples/client/petstore/ruby/.openapi-generator/FILES
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/.gitlab-ci.yml
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/.openapi-generator/FILES
samples/openapi3/client/features/dynamic-servers/ruby/.gitlab-ci.yml
samples/openapi3/client/features/dynamic-servers/ruby/.openapi-generator/FILES
samples/openapi3/client/features/generate-alias-as-model/ruby-client/.gitlab-ci.yml
samples/openapi3/client/features/generate-alias-as-model/ruby-client/.openapi-generator/FILES

Generate .gitlab-ci.yml files for Ruby template

---

modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/json_serializable/deserialize.mustache

Fixes https://github.com/OpenAPITools/openapi-generator/issues/12613
cc @jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela
```
``` 

[dart-dio] Fix model package name import in Dart json_serializable

---

samples/client/petstore/rust/hyper/petstore/docs/PetApi.md
samples/client/petstore/rust/hyper/petstore/docs/StoreApi.md
samples/client/petstore/rust/hyper/petstore/src/apis/pet_api.rs
samples/client/petstore/rust/hyper/petstore/src/apis/request.rs
samples/client/petstore/rust/hyper/petstore/src/apis/store_api.rs
samples/client/petstore/rust/reqwest/petstore-async/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-async/docs/StoreApi.md
samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-async/src/apis/store_api.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore-awsv4signature/docs/StoreApi.md
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/apis/store_api.rs
samples/client/petstore/rust/reqwest/petstore/docs/PetApi.md
samples/client/petstore/rust/reqwest/petstore/docs/StoreApi.md
samples/client/petstore/rust/reqwest/petstore/src/apis/pet_api.rs
samples/client/petstore/rust/reqwest/petstore/src/apis/store_api.rs

Regenerates rust sample so CI test will pass
```
``` 

Regenerates rust sample so CI test will pass

---

docs/generators/r.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/api_client.mustache
modules/openapi-generator/src/main/resources/r/api_doc.mustache
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/test_petstore.R
samples/client/petstore/R/tests/testthat/test_petstore.R

Add streaming support for `x-streaming` tag in the spec
```
``` 

[R] add streaming support

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java

Add schema mapping support in typescript client codegen (TypeScriptClientCodegen)
```
``` 
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) …

Add schema mapping support in typescript client codegen

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java

Fix https://github.com/OpenAPITools/openapi-generator/issues/12835
```
``` 
@wing328

[csharp-netcore] fix NPE when handling custom Content-type

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java
modules/openapi-generator/src/test/resources/3_0/csharp/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/docs/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/docs/apis/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/docs/apis/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/docs/apis/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net47/docs/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/docs/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/docs/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/PetApi.md
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs

Custom Content type: better message and added tests
```
``` 

Custom Content type: better message and added tests

---

modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java

 Copy skipOperationExample from builder to WorkflowSettings

---

modules/openapi-generator/src/main/resources/typescript-angular/modelEnum.mustache
modules/openapi-generator/src/main/resources/typescript-nestjs/modelEnum.mustache

Removed unnecessary semicolon from `typescript-angular` and `typescript-nestjs` generators.
```typescript
export interface MyObject { 
statusCodes?: MyObjectStatusCodesEnum;
}
export enum MyObjectStatusCodesEnum {
Ok = 'OK',
BadRequest = 'BAD_REQUEST',
NotFound = 'NOT_FOUND'
}    //  <--- Unnecessary semicolon removed
```
Sonar was picking on it and raising a **Code Smell**:
[https://rules.sonarsource.com/typescript/RSPEC-1116](https://rules.sonarsource.com/typescript/RSPEC-1116)
[https://github.com/OpenAPITools/openapi-generator/issues/12862](https://github.com/OpenAPITools/openapi-generator/issues/12862)
```
```  …

[BUG][typescript] Unnecessary semicolon [sonar(typescript:S1116)]

---

modules/openapi-generator/src/main/resources/r/r-client.mustache
samples/client/petstore/R/.github/workflows/r-client.yaml

Add roxygen2 to Github workflow
```
``` 

[R] Add roxygen2 to Github workflow

---

docs/customization.md

Add documentations for schema mapping and inline schema naming

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestSdkClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java

- Fix parameter schema mapping
- Refactor unaliasSchema
```
``` 

Fix parameter schema mapping

---

.travis.yml
pom.xml

Test perl petstore in Travis CI.
```
``` 

Test Perl client in Travis CI

---

docs/generators/aspnetcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
modules/openapi-generator/src/main/resources/aspnetcore/2.0/model.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/model.mustache
modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache

```
``` 
FYI: @mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti 
Added a new parameter for the C# ASPNETCORE generators.
So that you generate POCO Models -- aka. models that don't include IEquatable methods and the operators.
This is highly …

Aspnetcore Generator - New pocoModels parameter for POCO models

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/main/resources/r/lintr.mustache
modules/openapi-generator/src/main/resources/r/r-client.mustache
samples/client/petstore/R/.github/workflows/r-client.yaml
samples/client/petstore/R/.lintr
samples/client/petstore/R/.openapi-generator/FILES

- add .lintr
- update workflow to install lintr
```
``` 

[R] Add lintr

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java

Add decimal support to Crystal client
```
``` 
cc @cyangle (2021/01)

Add decimal support to Crystal client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java

cache model name for faster lookup to reduce code generation time.
this is helpful when the spec is very large.
```
``` 

[powershell] cache model name for faster lookup

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java

[R] cache model name for faster lookup

---

samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift

Update Swift samples after merging https://github.com/OpenAPITools/openapi-generator/pull/12882
```
``` 

[Swift][client] update samples

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java

Add schema mapping support to R client generator
```
``` 

Add schema mapping support to R client generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java

Add schema mapping support to PowerShell client generator
```
``` 

Add schema mapping support to PowerShell client generator

---

modules/openapi-generator/src/main/resources/aspnetcore/3.0/Startup.mustache
modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-6.0/src/Org.OpenAPITools/Startup.cs

```
``` 
FYI: @mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti @wing328 
Added the support for polymorphism in models to ASP.NET Core generator.
So that Swashbuckle SwaggerGen re-outputs a correct swagger schema with ALLOF.

Added support for inheritance in Swashbuckle in ASP.NET Core

---

modules/openapi-generator/src/main/resources/cpp-qt-client/HttpRequest.cpp.mustache
modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache
modules/openapi-generator/src/main/resources/cpp-qt-client/oauth.cpp.mustache
samples/client/petstore/cpp-qt/PetStore/PetStore.pro
samples/client/petstore/cpp-qt/client/PFXHttpRequest.cpp
samples/client/petstore/cpp-qt/client/PFXOauth.cpp
samples/client/petstore/cpp-qt/client/PFXPetApi.cpp
samples/client/petstore/cpp-qt/client/PFXPrimitivesApi.cpp
samples/client/petstore/cpp-qt/client/PFXStoreApi.cpp
samples/client/petstore/cpp-qt/client/PFXUserApi.cpp

Minor fixes:
- foreach => for
- Fix PetStore.pro
- Whitespace formatting
```
``` 
cc @ravinikam @stkrwork @etherealjoy @muttleyxd

[cpp-qt-client] Minor fixes

---

docs/generators/aspnetcore.md
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-6.0-pocoModels/src/Org.OpenAPITools/Org.OpenAPITools.csproj
samples/server/petstore/aspnetcore-6.0-pocoModels/src/Org.OpenAPITools/Startup.cs
samples/server/petstore/aspnetcore-6.0/src/Org.OpenAPITools/Org.OpenAPITools.csproj

Update swashbuckle version to 6.4.0 (latest stable version)
```
``` 

Update swashbuckle version to 6.4.0

---

modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ApiClient.cs
samples/server/petstore/aspnetcore-6.0-pocoModels/src/Org.OpenAPITools/Startup.cs

Add support for string response deserialization
(redo #12910)
```
``` 

[csharp-netcore] Add support for string response deserialization

---

modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/api_client.mustache
modules/openapi-generator/src/main/resources/r/api_doc.mustache
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/PetApi.md

- Add HTTP bearer auth support
- Add tests
- Update doc
```
``` 

[R] Add HTTP bearer auth support

---

modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/tests/testthat/test_petstore.R

Add HTTP basic test in R client
```
``` 

Add HTTP basic test in R client

---

README.md

I tried to write a minimal example of java client and server based on openapi-generator-maven-plugin.
[project](https://github.com/Lincest/openapi-generator-maven-plugin-demo) and [blog](https://blog.roccoshi.top/2022/java/openapi-generator%E7%9A%84%E4%BD%BF%E7%94%A8/)
```
```  …

add a link to blog post

---

modules/openapi-generator/src/main/resources/aspnetcore/2.0/README.mustache
modules/openapi-generator/src/main/resources/aspnetcore/2.1/README.mustache
modules/openapi-generator/src/main/resources/aspnetcore/3.0/README.mustache
samples/server/petstore/aspnetcore-3.0/README.md
samples/server/petstore/aspnetcore-3.1/README.md
samples/server/petstore/aspnetcore-5.0/README.md
samples/server/petstore/aspnetcore-6.0-pocoModels/README.md
samples/server/petstore/aspnetcore-6.0/README.md
samples/server/petstore/aspnetcore/README.md

@wing328 - I've added instructions for Nuget updating into the README for aspnetcore
```
``` 

[aspnetcore] Added dotnet outdated to READMEs

---

samples/client/petstore/perl/test.pl

This fixes a small bug in a perl test script, as mentioned in PR #12871...
```
``` 
@wing328 @yue9944882

[PERL] Fix bug on test script

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java

Add schema mapping support to Perl
```
``` 
cc @wing328 (2017/07)  @yue9944882 (2019/06)

Add schema mapping support to Perl

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java

Add model caching to Kotlin generators to speed up the codegen process. Useful when the spec is huge.
```
``` 
cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m …

Add model caching to Kotlin generators

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts
samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts

Fixing FetchError to be compatible with esnext

---

modules/openapi-generator/src/main/resources/r/api.mustache
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/test_petstore.R
samples/client/petstore/R/tests/testthat/test_petstore.R

- fix query, header params
- add tests
```
``` 

[R] fix query, header params

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
samples/client/petstore/typescript-aurelia/default/PetApi.ts
samples/client/petstore/typescript-axios/builds/default/api.ts
samples/client/petstore/typescript-axios/builds/es6-target/api.ts
samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
samples/client/petstore/typescript-axios/builds/with-node-imports/api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
samples/client/petstore/typescript-axios/builds/with-string-enums/api.ts
samples/client/petstore/typescript-jquery/default/api/PetApi.ts
samples/client/petstore/typescript-jquery/npm/api/PetApi.ts

description problem in: https://github.com/OpenAPITools/openapi-generator/issues/12744

[Typescript] Fix generated type for files

---

modules/openapi-generator/src/main/resources/r/ApiResponse.mustache
modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/api_client.mustache
modules/openapi-generator/src/main/resources/r/api_exception.mustache
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/R/api_exception.R
samples/client/petstore/R/R/api_response.R
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R

- refactor the client to prepare additional HTTP library support
```
``` 
FYI. @Ramanth (2019/07) @saigiridhar21 (2019/07)

[R] refactor the client to prepare additional HTTP library support

---

modules/openapi-generator/src/main/resources/r/api_doc.mustache
modules/openapi-generator/src/main/resources/r/api_exception.mustache
samples/client/petstore/R/R/api_exception.R
samples/client/petstore/R/docs/FakeApi.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/docs/StoreApi.md
samples/client/petstore/R/docs/UserApi.md
samples/client/petstore/R/test_petstore.R
samples/client/petstore/R/tests/testthat/test_petstore.R

- Enhance API exception in code sample
- Add tests
```
``` 

[R] Enhance API exception

---

modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/api_client.mustache
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R-httr2/R/fake_api.R
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R-httr2/R/store_api.R
samples/client/petstore/R-httr2/R/user_api.R
samples/client/petstore/R-httr2/README.md
samples/client/petstore/R-httr2/docs/PetApi.md
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/PetApi.md

- fix query param using list
- fix spec (rearrange)
```
``` 

[R][httr] fix query param, fix spec

---

modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache
samples/client/petstore/R-httr2/R/api_client.R
samples/client/petstore/R-httr2/tests/testthat/test_petstore.R

- fix assignment,
- clean up tests
- use !!! operator
```
``` 
FYI. cc @Ramanth (2019/07) @saigiridhar21 (2019/07)

[R][httr2] fix assignment, clean up tests

---

modules/openapi-generator/src/main/resources/r/README.mustache
modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/api_doc.mustache
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R-httr2/README.md
samples/client/petstore/R-httr2/docs/FakeApi.md
samples/client/petstore/R-httr2/docs/PetApi.md
samples/client/petstore/R-httr2/docs/StoreApi.md
samples/client/petstore/R-httr2/docs/UserApi.md
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/FakeApi.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/docs/StoreApi.md
samples/client/petstore/R/docs/UserApi.md

- fix auto-generated doc
- use Sys.getenv to obtain token/key, etc
- add null checks for bearer/access token (to prevent null values overriding previously set token)
```
``` 

[R] fix auto-generated doc, add checks for bearer/access token

---

bin/configs/r-httr2-client.yaml
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/main/resources/r/README.mustache
modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/api_client.mustache
modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R-httr2/R/api_client.R
samples/client/petstore/R-httr2/R/fake_api.R
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R-httr2/R/store_api.R
samples/client/petstore/R-httr2/R/user_api.R
samples/client/petstore/R-httr2/docs/PetApi.md
samples/client/petstore/R-httr2/tests/testthat/test_petstore.R
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/tests/testthat/test_petstore.R

- better support for OAuth authorisation flows
```
``` 

[R][httr2] better support for OAuth authoriziation flows

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R-httr2/R/fake_api.R
samples/client/petstore/R-httr2/R/user_api.R
samples/client/petstore/R-httr2/README.md
samples/client/petstore/R-httr2/docs/FakeApi.md
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/FakeApi.md

- Improve regular expression handling by removing trailing/leading backslash
```
``` 

[R] Improve regular expression handling

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java

Update samples and resolved merge conflicts for https://github.com/OpenAPITools/openapi-generator/pull/12516
```
``` 

[Java] enum space value must not be generated as underscore

---

modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache
modules/openapi-generator/src/main/resources/r/modelEnum.mustache
samples/client/petstore/R-httr2/R/api_client.R

Fix doc issues reported by roxygen
```
``` 

[R] Fix doc issues reported by roxygen

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java
modules/openapi-generator/src/test/resources/3_0/inline_model_resolver.yaml

Fix null ref on invalid requestBody reference (fixes #13197)

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/main/resources/r/.travis.yml.mustache
modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/modelGeneric.mustache
samples/client/petstore/R-httr2-wrapper/.travis.yml
samples/client/petstore/R-httr2-wrapper/R/animal.R
samples/client/petstore/R-httr2-wrapper/R/basque_pig.R
samples/client/petstore/R-httr2-wrapper/R/cat.R
samples/client/petstore/R-httr2-wrapper/R/category.R
samples/client/petstore/R-httr2-wrapper/R/danish_pig.R
samples/client/petstore/R-httr2-wrapper/R/dog.R
samples/client/petstore/R-httr2-wrapper/R/pet.R
samples/client/petstore/R-httr2/.travis.yml
samples/client/petstore/R-httr2/R/animal.R
samples/client/petstore/R-httr2/R/basque_pig.R
samples/client/petstore/R-httr2/R/cat.R
samples/client/petstore/R-httr2/R/category.R
samples/client/petstore/R-httr2/R/danish_pig.R
samples/client/petstore/R-httr2/R/dog.R
samples/client/petstore/R-httr2/R/pet.R
samples/client/petstore/R/R/animal.R
samples/client/petstore/R/R/basque_pig.R
samples/client/petstore/R/R/cat.R
samples/client/petstore/R/R/category.R
samples/client/petstore/R/R/danish_pig.R
samples/client/petstore/R/R/dog.R
samples/client/petstore/R/R/pet.R

- Fix warnings reported by r cmd check so that the package can be published to R cran
- Minor fix in .travis.yml to use httr2 when using httr2
- Fix assignment with `<-`
```
``` 

[R] Fix warnings reported by r cmd check

---

modules/openapi-generator/src/main/resources/python-experimental/README.handlebars
modules/openapi-generator/src/main/resources/python-experimental/model_templates/schema.handlebars
samples/openapi3/client/3_0_3_unit_test/python-experimental/README.md
samples/openapi3/client/3_0_3_unit_test/python-experimental/unit_test_api/model/properties_with_escaped_characters.py
samples/openapi3/client/3_0_3_unit_test/python-experimental/unit_test_api/model/property_named_ref_that_is_not_a_reference.py
samples/openapi3/client/petstore/python-experimental/README.md
samples/openapi3/client/petstore/python-experimental/petstore_api/model/format_test.py
samples/openapi3/client/petstore/python-experimental/petstore_api/model/model200_response.py
samples/openapi3/client/petstore/python-experimental/petstore_api/model/model_return.py
samples/openapi3/client/petstore/python-experimental/petstore_api/model/name.py
samples/openapi3/client/petstore/python-experimental/petstore_api/model/object_with_difficultly_named_props.py
samples/openapi3/client/petstore/python-experimental/petstore_api/paths/fake_1/post.py

[python-experimental] improves docs
Adds migration guide
Adds comment explaining the locals code
```
``` 

[python-experimental] improves docs, add migration guide

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
modules/openapi-generator/src/main/resources/r/modelGeneric.mustache
samples/client/petstore/R-httr2-wrapper/R/pet.R
samples/client/petstore/R-httr2/R/pet.R
samples/client/petstore/R/R/pet.R

- Fix R doc type to address the warning reported by R CMD check, e.g.
```
Warning: Missing link or links in documentation object 'InvalidRequestProblemAllOfErrors.Rd':
‘array[character]’
```
- fix map type example code
```
``` 
cc @Ramanth (2019/07) …

[R] Fix R doc type

---

modules/openapi-generator/src/main/resources/r/README.mustache
modules/openapi-generator/src/main/resources/r/api_doc.mustache
samples/client/petstore/R-httr2-wrapper/README.md
samples/client/petstore/R-httr2-wrapper/docs/FakeApi.md
samples/client/petstore/R-httr2-wrapper/docs/PetApi.md
samples/client/petstore/R-httr2-wrapper/docs/StoreApi.md
samples/client/petstore/R-httr2-wrapper/docs/UserApi.md
samples/client/petstore/R-httr2/README.md
samples/client/petstore/R-httr2/docs/FakeApi.md
samples/client/petstore/R-httr2/docs/PetApi.md
samples/client/petstore/R-httr2/docs/StoreApi.md
samples/client/petstore/R-httr2/docs/UserApi.md
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/FakeApi.md
samples/client/petstore/R/docs/PetApi.md
samples/client/petstore/R/docs/StoreApi.md
samples/client/petstore/R/docs/UserApi.md

- skip author section if not defined
- highlight scope
- fix sample code for saving data, streaming when enabling wrapper
```
``` 

[R] Minor improvements to the documentation

---

modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
samples/client/petstore/typescript-fetch/builds/default-v3.0/models/Pet.ts

Serialize Set of primitives as array
Fixes #10770
```
``` 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov …

[typescript-fetch] Serialize Set of primitives as array

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java

Fix string comparison in Scala sttp client
```
``` 
cc @clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)

Fix string comparison in Scala sttp client

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/K6ClientCodegen.java

- Better handling of NPE in k6 client generator
```
``` 
FYI @mostafa

Better handling of NPE in k6 client generator

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java

- remove duplicated logic
- no functionality change
```
``` 

Minor code improvement in model utils

---

modules/openapi-generator/src/main/resources/java-undertow-server/pom.mustache
samples/server/petstore/java-undertow/dependency-reduced-pom.xml
samples/server/petstore/java-undertow/pom.xml

Update undertow to newer version to address security issues.
```
``` 

Update undertow to newer version

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java

- Better null check in default codegen according to https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=OpenAPITools_openapi-generator&open=AYK4fffSE526gXJ5Emq5
```
``` 

Better null check in default codegen

---

modules/openapi-generator/src/main/resources/go/README.mustache

Add missing golang tag in code markdown

---

.github/workflows/openapi-generator.yaml
modules/openapi-generator-gradle-plugin/samples/local-spec/README.md
modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle
modules/openapi-generator-gradle-plugin/samples/local-spec/gradle/wrapper/gradle-wrapper.properties
modules/openapi-generator-gradle-plugin/samples/local-spec/gradlew
modules/openapi-generator-gradle-plugin/samples/local-spec/gradlew.bat

- Add more tests for Gradle plugin in Github workflows
- Update gradlew to use v6.8.3 (dropping v5.x support)
```
``` 

Add more tests for Gradle plugin in Github workflows

---

bin/configs/unmaintained/javascript-apollo.yaml
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java

- remove config as it's deprecated.
```
``` 

Minor enhancements to the JS apollo generator

---

modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache
modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift

For an API POST request with content type `"multipart/form-data"` and an parameter of `format": "uuid",`,
openapi-generator correctly generates an API function with UUID as parameter, but crashes when calling it, because FormDataEncoding does not support UUID types.
This PR adds support for UUID in FormDataEncoding for Alamofire and URLSession.
I have no idea if, how or where to add tests for this.
```
```  …

[swift5] Add UUID support in FormDataEncoding

---

modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache
samples/client/petstore/R-httr2-wrapper/R/api_client.R
samples/client/petstore/R-httr2-wrapper/R/pet_api.R
samples/client/petstore/R-httr2-wrapper/test_petstore.R
samples/client/petstore/R-httr2/R/api_client.R
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R/R/pet_api.R

Fix query parameters (array) in R client
```
``` 

Fix query parameters (array) in R client

---

modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R-httr2-wrapper/R/api_client.R
samples/client/petstore/R-httr2-wrapper/R/pet_api.R
samples/client/petstore/R-httr2-wrapper/R/user_api.R
samples/client/petstore/R-httr2-wrapper/docs/PetApi.md
samples/client/petstore/R-httr2-wrapper/test_petstore.R
samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R
samples/client/petstore/R-httr2/R/api_client.R
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R-httr2/R/user_api.R
samples/client/petstore/R-httr2/docs/PetApi.md
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/docs/PetApi.md

- support explode (true/false) in query array parameters
- add tests to ensure both list and vector can be used as the input
```
``` 

[R] support explode (true/false) in query array parameters

---

modules/openapi-generator/src/main/resources/r/api.mustache
samples/client/petstore/R-httr2-wrapper/R/pet_api.R
samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R/R/pet_api.R

Add validation for query enum parameters in R client
Add tests
```
``` 

Add validation for query enum parameters in R client

---

modules/openapi-generator/src/main/resources/python-experimental/schemas.handlebars
samples/openapi3/client/3_0_3_unit_test/python-experimental/unit_test_api/schemas.py
samples/openapi3/client/petstore/python-experimental/.openapi-generator/VERSION
samples/openapi3/client/petstore/python-experimental/petstore_api/schemas.py

[python-experimental] adds more base classes, preparation for v3.1.0 type arrays
```
``` 

[python-experimental] adds more base class mixins, preparation for v3.1.0 type arrays

---

modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R-httr2-wrapper/R/fake_api.R
samples/client/petstore/R-httr2-wrapper/R/pet_api.R
samples/client/petstore/R-httr2-wrapper/R/store_api.R
samples/client/petstore/R-httr2-wrapper/R/user_api.R
samples/client/petstore/R-httr2-wrapper/README.md
samples/client/petstore/R-httr2-wrapper/docs/FakeApi.md
samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R
samples/client/petstore/R-httr2/R/fake_api.R
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R-httr2/R/store_api.R
samples/client/petstore/R-httr2/R/user_api.R
samples/client/petstore/R-httr2/README.md
samples/client/petstore/R-httr2/docs/FakeApi.md
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/FakeApi.md

- Add array support to path parameters
- Add tests
- minor refactoring of mustache templates (code more readable)
```
``` 

[R] Add array support to path parameters

---

modules/openapi-generator/src/main/resources/python-experimental/api_client.handlebars
samples/openapi3/client/3_0_3_unit_test/python-experimental/unit_test_api/api_client.py
samples/openapi3/client/petstore/python-experimental/petstore_api/api_client.py

[python-experimental] Fix error message

---

modules/openapi-generator/src/main/resources/ruby-client/partial_model_enum_class.mustache
modules/openapi-generator/src/main/resources/ruby-client/partial_oneof_module_doc.mustache
samples/client/petstore/ruby-autoload/lib/petstore/models/enum_class.rb
samples/client/petstore/ruby-autoload/lib/petstore/models/outer_enum.rb
samples/client/petstore/ruby-autoload/lib/petstore/models/outer_enum_default_value.rb
samples/client/petstore/ruby-autoload/lib/petstore/models/outer_enum_integer.rb
samples/client/petstore/ruby-autoload/lib/petstore/models/outer_enum_integer_default_value.rb
samples/client/petstore/ruby-autoload/lib/petstore/models/single_ref_type.rb
samples/client/petstore/ruby-faraday/lib/petstore/models/enum_class.rb
samples/client/petstore/ruby-faraday/lib/petstore/models/outer_enum.rb
samples/client/petstore/ruby-faraday/lib/petstore/models/outer_enum_default_value.rb
samples/client/petstore/ruby-faraday/lib/petstore/models/outer_enum_integer.rb
samples/client/petstore/ruby-faraday/lib/petstore/models/outer_enum_integer_default_value.rb
samples/client/petstore/ruby-faraday/lib/petstore/models/single_ref_type.rb
samples/client/petstore/ruby/lib/petstore/models/enum_class.rb
samples/client/petstore/ruby/lib/petstore/models/outer_enum.rb
samples/client/petstore/ruby/lib/petstore/models/outer_enum_default_value.rb
samples/client/petstore/ruby/lib/petstore/models/outer_enum_integer.rb
samples/client/petstore/ruby/lib/petstore/models/outer_enum_integer_default_value.rb
samples/client/petstore/ruby/lib/petstore/models/single_ref_type.rb

`Module.constants` and `Module.const_get` combination is slow.
See below benchmark:
```ruby
class Sample
CONST_0 = "0"
CONST_1 = "1"
CONST_2 = "2"
CONST_3 = "3"
CONST_4 = "4"
CONST_5 = "5"
CONST_6 = "6"
CONST_7 = "7"
CONST_8 = "8"
CONST_9 = "9"
def self.all_vars
@all_vars ||= %w[0 1 2 3 4 5 6 7 8 9].freeze
end
def build_from_hash(value)
constantValues = Sample.constants.select { |c| Sample::const_get(c) == value }
raise "Invalid ENUM value #{value} for class Sample" if constantValues.empty?
value
end
def new_build_from_hash(value)
return value if Sample.all_vars.include?(value)
raise "Invalid ENUM value #{value} for class Sample"
end
end
require "benchmark/ips"
sample = Sample.new
values = %w[0 1 2 3 4 5 6 7 8 9].cycle
Benchmark.ips do |x|
x.report("old build_from_hash") { …
```

[Ruby] Change constants lookup methods in enum class

---

modules/openapi-generator/src/main/resources/r/api.mustache
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R-httr2-wrapper/R/fake_api.R
samples/client/petstore/R-httr2-wrapper/R/pet_api.R
samples/client/petstore/R-httr2-wrapper/R/store_api.R
samples/client/petstore/R-httr2-wrapper/R/user_api.R
samples/client/petstore/R-httr2-wrapper/README.md
samples/client/petstore/R-httr2-wrapper/docs/FakeApi.md
samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R
samples/client/petstore/R-httr2/R/fake_api.R
samples/client/petstore/R-httr2/R/pet_api.R
samples/client/petstore/R-httr2/R/store_api.R
samples/client/petstore/R-httr2/R/user_api.R
samples/client/petstore/R-httr2/README.md
samples/client/petstore/R-httr2/docs/FakeApi.md
samples/client/petstore/R/R/fake_api.R
samples/client/petstore/R/R/pet_api.R
samples/client/petstore/R/R/store_api.R
samples/client/petstore/R/R/user_api.R
samples/client/petstore/R/README.md
samples/client/petstore/R/docs/FakeApi.md

- Fix optional body parameter
- Add tests
To close https://github.com/OpenAPITools/openapi-generator/issues/13468
```
``` 

[R] Fix optional body parameter

---

modules/openapi-generator/src/main/resources/r/modelGeneric.mustache
samples/client/petstore/R-httr2-wrapper/R/order.R
samples/client/petstore/R-httr2-wrapper/R/pet.R
samples/client/petstore/R-httr2-wrapper/R/zebra.R
samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R
samples/client/petstore/R-httr2/R/order.R
samples/client/petstore/R-httr2/R/pet.R
samples/client/petstore/R-httr2/R/zebra.R
samples/client/petstore/R/R/order.R
samples/client/petstore/R/R/pet.R
samples/client/petstore/R/R/zebra.R

- Better enum status validation
- Add tests
```
``` 

[R] Better enum status validation

---

README.md

Add OpenAPI Generator design philosophy to the readme
```
``` 

Add OpenAPI Generator design philosophy to the readme

---

modules/openapi-generator/src/main/resources/r/api_client.mustache
modules/openapi-generator/src/main/resources/r/libraries/httr2/api_client.mustache
modules/openapi-generator/src/main/resources/r/modelGeneric.mustache
samples/client/petstore/R-httr2-wrapper/R/animal.R
samples/client/petstore/R-httr2-wrapper/R/api_client.R
samples/client/petstore/R-httr2-wrapper/test_petstore.R
samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R
samples/client/petstore/R-httr2/R/animal.R
samples/client/petstore/R-httr2/R/api_client.R
samples/client/petstore/R/R/animal.R
samples/client/petstore/R/R/api_client.R
samples/client/petstore/R/tests/testthat/test_petstore.R

- add discriminator and mappings support
- add tests
```
``` 

[R] add discriminator and mappings support

---

README.md

Removes inactive python reviewers from the tech committee list:
@taxpon (2017/07)  Last commit 2017
@frol (2017/07) No activity in the last year
@mbohlool (2017/07) No activity in the last year
@cbornet (2017/09) member of core team, no python commits in the last 3 years
@kenjones-cisco (2017/11) No activity in the last year
@tomplus (2018/10) Last python commit 2021
@arun-nalla (2019/11) No github profile
```
```  …

Updates readme active python reviewers

---

modules/openapi-generator/src/main/resources/r/modelGeneric.mustache
modules/openapi-generator/src/test/resources/3_0/r/petstore.yaml
samples/client/petstore/R-httr2-wrapper/R/date.R
samples/client/petstore/R-httr2-wrapper/docs/Date.md
samples/client/petstore/R-httr2-wrapper/tests/testthat/test_petstore.R
samples/client/petstore/R-httr2/R/date.R
samples/client/petstore/R-httr2/docs/Date.md
samples/client/petstore/R/R/date.R
samples/client/petstore/R/docs/Date.md

[R] add URL validation

---

modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
samples/client/petstore/typescript-fetch/builds/allOf-readonly/runtime.ts
samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
samples/client/petstore/typescript-fetch/builds/default/runtime.ts
samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts
samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts

[typescript-fetch] fix #13853 add semi colon

---

modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
samples/server/petstore/rust-server/output/openapi-v3/Cargo.toml
samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing/Cargo.toml

See https://github.blog/2021-09-01-improving-git-protocol-security-github/
```
``` 

[Rust] Remove decommissioned git://

---

modules/openapi-generator/pom.xml
pom.xml

Update project dependencies (pom.xml) - root, openapi-generator
No change in samples
```
``` 

Update project dependencies - root, openapi-generator

---

modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb

fix #13891
```
```
cc @cliffano, @zlx, @autopp

[RUBY] handle Faraday::ConnectionFailed api error

---

modules/openapi-generator-maven-plugin/pom.xml
modules/openapi-generator-online/pom.xml

Update maven plugin, online generator dependencies
```
``` 

Update maven plugin, online generator dependencies

---

bin/utils/test_file_list.yaml
samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/ClientTest.java
samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/JSONTest.java
samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/StringUtilTest.java

Add array test to java okhttp-gson client in a new file named "ClientTest.java"
```
```  …

Add array tests to java okhttp-gson client

---

.github/PULL_REQUEST_TEMPLATE.md

The latest release is 6.2.X so updating the template to correct the version
```
``` 

[DOCS] Update PR template branch

---

modules/openapi-generator/src/main/resources/ruby-client/gemspec.mustache
modules/openapi-generator/src/main/resources/ruby-client/gitlab-ci.mustache
modules/openapi-generator/src/main/resources/ruby-client/travis.mustache
pom.xml
samples/client/petstore/ruby-autoload/.gitlab-ci.yml
samples/client/petstore/ruby-autoload/.travis.yml
samples/client/petstore/ruby-autoload/petstore.gemspec
samples/client/petstore/ruby-faraday/.gitlab-ci.yml
samples/client/petstore/ruby-faraday/.travis.yml
samples/client/petstore/ruby-faraday/petstore.gemspec
samples/client/petstore/ruby/.gitlab-ci.yml
samples/client/petstore/ruby/.travis.yml
samples/client/petstore/ruby/petstore.gemspec
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/.gitlab-ci.yml
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/.travis.yml
samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/x_auth_id_alias.gemspec
samples/openapi3/client/features/dynamic-servers/ruby/.gitlab-ci.yml
samples/openapi3/client/features/dynamic-servers/ruby/.travis.yml
samples/openapi3/client/features/dynamic-servers/ruby/dynamic_servers.gemspec
samples/openapi3/client/features/generate-alias-as-model/ruby-client/.gitlab-ci.yml
samples/openapi3/client/features/generate-alias-as-model/ruby-client/.travis.yml
samples/openapi3/client/features/generate-alias-as-model/ruby-client/petstore.gemspec

- update Ruby minimum version to 2.7
- move tests to circleci
- add ruby 3.1 to CI configs
to close https://github.com/OpenAPITools/openapi-generator/issues/13986
```
``` 

Update Ruby minimum version to 2.7

---

modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java

Fix for https://github.com/OpenAPITools/openapi-generator/issues/13968
```
``` 

[Java][Native] handle empty response body

---

modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java

Mitigates https://github.com/OpenAPITools/openapi-generator/issues/13709
```
``` 

[csharp-netcore] Fixed circular references in composed properties

---

modules/openapi-generator/src/main/resources/cpp-qt-client/oauth.cpp.mustache
samples/client/petstore/cpp-qt/client/PFXOauth.cpp

```
``` 
cc @ravinikam @stkrwork @etherealjoy @muttleyxd

[cpp-qt-client] Fix warnings

---

modules/openapi-generator-gradle-plugin/README.adoc
modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt

- display a message about output directory being cleaned up
- update the test with better wording
```
``` 

Minor improvements to Gradle plugin

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/apachehttpclient/ApacheHttpClientCodegenTest.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java

- Update test
- suppress warnings and better docstring
```
``` 

Update test, suppress warnings in Java apache-httpclient

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/pom.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/native/pom.mustache
samples/client/petstore/java/apache-httpclient/build.gradle
samples/client/petstore/java/apache-httpclient/pom.xml
samples/client/petstore/java/native-async/build.gradle
samples/client/petstore/java/native-async/pom.xml
samples/client/petstore/java/native/build.gradle
samples/client/petstore/java/native/pom.xml

- update dependencies to newer versions
```
``` 

[Java][native][apache-httpclient] update dependencies to newer versions

---

docs/customization.md

Update customization doc with better example on using the inline schema name mapping option
```
``` 

Update customization doc with better example on using the inline schema name mapping option

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache
modules/openapi-generator/src/main/resources/JavaVertXWebServer/supportFiles/pom.mustache
modules/openapi-generator/src/main/resources/java-undertow-server/pom.mustache
samples/client/petstore/java/resttemplate-swagger1/build.gradle
samples/client/petstore/java/resttemplate-swagger1/pom.xml
samples/client/petstore/java/resttemplate-withXml/build.gradle
samples/client/petstore/java/resttemplate-withXml/pom.xml
samples/client/petstore/java/resttemplate/build.gradle
samples/client/petstore/java/resttemplate/pom.xml
samples/server/petstore/java-undertow/pom.xml
samples/server/petstore/java-vertx-web/pom.xml

Update jackson databind to newer versions 2.14.1
```
``` 

[java] Update jackson databind to newer versions

---

modules/openapi-generator/src/main/resources/swift5/APIHelper.mustache
samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/APIHelper.swift
samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/APIHelper.swift
samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/APIHelper.swift

@4brunu
- Modified Swift 5 template `APIHelper.mustache` to handle `RawRepresentable` enums with a new method `convertAnyToString`.
- This handles a case where parameter casing/spelling doesn't match, i.e.:
```
public enum Facets_productsRequest: String, CaseIterable {
case offers = "OFFERS"
case images = "IMAGES"
}
```
```
``` 
For …

Support RawRepresentable enums

---

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache

A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/14183
```
``` 

Update python-fastapi dependeny to newer version

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/api.mustache
modules/openapi-generator/src/test/java/org/openapitools/codegen/java/apachehttpclient/ApacheHttpClientCodegenTest.java
samples/client/petstore/rust/reqwest/petstore-async-middleware/src/apis/mod.rs

Fix apache http client query parameters

---

modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
samples/client/echo_api/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
samples/client/echo_api/java/apache-httpclient/src/test/java/org/openapitools/client/CustomTest.java
samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java

- fix optional body (when it's not provided)
- add tests
```
``` 

[Java apache-http client] fix optional body, add tests

---

modules/openapi-generator/src/main/resources/python-fastapi/requirements.mustache
samples/server/petstore/python-fastapi/requirements.txt

Bump certifi from 2020.12.5 to 2022.12.7
```
``` 
cc @spacether @krjakbrjak

[python-fastapi] Bump certifi from 2020.12.5 to 2022.12.7

---

modules/openapi-generator-gradle-plugin/build.gradle

For https://github.com/OpenAPITools/openapi-generator/pull/13860/files#r1049878211
```
``` 

Add back mavenLocal in Gradle plugin build

---

modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache
modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache
samples/client/petstore/java/resttemplate-swagger1/build.gradle
samples/client/petstore/java/resttemplate-swagger1/pom.xml
samples/client/petstore/java/resttemplate-withXml/build.gradle
samples/client/petstore/java/resttemplate-withXml/pom.xml
samples/client/petstore/java/resttemplate/build.gradle
samples/client/petstore/java/resttemplate/pom.xml

Update spring web to latest 5.x (5.3.24 released in Nov 2022)
```
``` 

[Java][resttemplate] Update spring web to latest 5.x

---

modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom-sb3.mustache
modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-boot/pom.mustache
samples/openapi3/client/petstore/spring-stubs-skip-default-interface/pom.xml
samples/openapi3/client/petstore/spring-stubs/pom.xml
samples/openapi3/server/petstore/spring-boot-oneof/pom.xml
samples/openapi3/server/petstore/spring-boot-springdoc/pom.xml
samples/openapi3/server/petstore/springboot-3/pom.xml
samples/openapi3/server/petstore/springboot-beanvalidation-no-nullable/pom.xml
samples/openapi3/server/petstore/springboot-delegate/pom.xml
samples/openapi3/server/petstore/springboot-implicitHeaders/pom.xml
samples/openapi3/server/petstore/springboot-reactive/pom.xml
samples/openapi3/server/petstore/springboot-source/pom.xml
samples/openapi3/server/petstore/springboot-useoptional/pom.xml
samples/openapi3/server/petstore/springboot/pom.xml
samples/server/petstore/spring-boot-defaultInterface-unhandledException/pom.xml
samples/server/petstore/spring-boot-nullable-set/pom.xml
samples/server/petstore/spring-stubs/pom.xml
samples/server/petstore/springboot-beanvalidation-no-nullable/pom.xml
samples/server/petstore/springboot-delegate-j8/pom.xml
samples/server/petstore/springboot-delegate/pom.xml
samples/server/petstore/springboot-implicitHeaders-annotationLibrary/pom.xml
samples/server/petstore/springboot-implicitHeaders/pom.xml
samples/server/petstore/springboot-reactive/pom.xml
samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8/pom.xml
samples/server/petstore/springboot-spring-pageable-delegatePattern/pom.xml
samples/server/petstore/springboot-spring-pageable-without-j8/pom.xml
samples/server/petstore/springboot-spring-pageable/pom.xml
samples/server/petstore/springboot-useoptional/pom.xml
samples/server/petstore/springboot-virtualan/pom.xml
samples/server/petstore/springboot/pom.xml

- Upgrade Spring Boot to 2.7.6 / 3.0.0
- Upgrade Springdoc to 1.6.14 / 2.0.2
- Upgrade Swagger-Ui web jar to 4.15.5
```
```  …

[Java][Spring] Upgrade Dependencies (2022-12)
