- modules/openapi-generator/src/main/resources/rust/Cargo.mustache
- samples/client/petstore/rust/reqwest/petstore-async/Cargo.toml
This p-r upgrades the reqwest crate to 0.11.
reqwest 0.11 uses tokio 1.0 and it should be totally preferable for most of tokio users.
Also, since 0.11 make multipart support optional, I added it to the features list.
```
``` 
> [rust client] upgrade reqwest crate to 0.11

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenParameter.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpNetCoreClientDeepObjectTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientDeepObjectTest.java
- modules/openapi-generator/src/test/resources/3_0/deepobject.yaml
[java native][dotnetcore] Implement QueryParameter deepObject style for client generators java native and dotnetcore.
https://github.com/OpenAPITools/openapi-generator/issues/469
Please have a look at the new tests:
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientDeepObjectTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcore/CSharpNetCoreClientDeepObjectTest.java
with the test document modules/openapi-generator/src/test/resources/3_0/deepobject.yaml
The urls …
> [java native][dotnetcore] Implement QueryParameter deepObject style

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
- modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/PetApi.ts
uniqueItems produces Set instead of Array as type, but the corresponding code did not treat Set correctly
use `Array.from` and `new Set` to convert from Set to Array and vice versa, if uniqueItems is true.
related to https://github.com/OpenAPITools/openapi-generator/issues/8258, but only fixes typescript-fetch
> [typescript-fetch] handle uniqueItems correctly in model and api

- modules/openapi-generator/src/main/resources/go/client.mustache
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go
- samples/openapi3/client/petstore/go/go-petstore/client.go
Fixes #8392 with the naive approach of checking if the body type is `**os.File` , so it can read its content and avoid the bug of not reading the bytes and having content-length 0.
Tested the fixed code on a separate branch in the same repo used to reproduce the issue : https://github.com/dhontecillas/openapi-generator-go-upload-bug/tree/test_fix (the updated line can be found in https://github.com/dhontecillas/openapi-generator-go-upload-bug/blob/test_fix/pkg/bug/client.go#L415 ). When running the `go run . ` command in that branch, the bug is not reproduced anymore. We get an output of : 
```
The request failed for a different reason: Post "http://127.0.0.1:8000/upload": dial tcp 127.0.0.1:8000: connect: connection refused
```
That is the expected result as we do not have any server …
> Fix generated go client cannot upload file

- modules/openapi-generator/src/main/resources/aspnetcore/3.0/Project.csproj.mustache
- modules/openapi-generator/src/main/resources/aspnetcore/3.0/model.mustache
Generator `aspnetcore` mustache templates is missing a mechanism that can support polymorphism(inheritance). 
Serializing child types will end up as their base class without indicating known types to the base class. 
This pull request will also be a fix for #7377 
- add package reference on JsonSubTypes in `Project.csproj.mustache
- apply usage by including `KnownSubTypes` and discriminator in `model.mustache`
> [aspnetcore] Improve model inheritance support by including JsonSubTypes to properly handle serialization

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
- modules/openapi-generator/src/main/resources/dart-dio/class.mustache
- modules/openapi-generator/src/main/resources/dart-dio/enum_inline.mustache
- modules/openapi-generator/src/main/resources/dart2/class.mustache
- modules/openapi-generator/src/main/resources/dart2/enum_inline.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/test/api_response_test.dart
- samples/client/petstore/dart-dio/petstore_client_lib/test/category_test.dart
- samples/client/petstore/dart-dio/petstore_client_lib/test/order_test.dart
- samples/client/petstore/dart-dio/petstore_client_lib/test/pet_test.dart
- samples/client/petstore/dart-dio/petstore_client_lib/test/tag_test.dart
- samples/client/petstore/dart-dio/petstore_client_lib/test/user_test.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/model/map_test.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/map_test.dart
* prevent further name conflicts by correctly naming the enum, until now there could potentially occur conflicts e.g. 2x `MapTestInnerEnum` by renaming the `items` child property
* correctly set `enumName` to match `datatypeWithEnum`
Follow-up for https://github.com/OpenAPITools/openapi-generator/pull/8220
```
```  …
> [dart][dart-dio] Improve prefixing of inner enums with classname

- modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
Issue https://github.com/OpenAPITools/openapi-generator/issues/8541
Give ability to extend `ApiClient` for `java-native` library
```
``` 
> [Java][native] extend native ApiClient

- modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpFileElement.cpp.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.cpp.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/HttpRequest.h.mustache
- samples/client/petstore/cpp-qt5/client/PFXHttpFileElement.cpp
- samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp
- samples/client/petstore/cpp-qt5/client/PFXHttpRequest.h
The Qt 5.15 check doesn't works: it checked again Qt 5.21.0 (my mistake by the way). This PR fix it.
```
``` 
> [cpp-qt5-client] Fix qt5.15 check

- modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache
- modules/openapi-generator/src/main/resources/ruby-client/api_client_typhoeus_partial.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
- samples/client/petstore/ruby/lib/petstore/api_client.rb
- samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_client.rb
- samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_client.rb
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb
- force users to specify the temp folder path to address security concerns as the default location of the temp folder can be read by any users.
- if the temp folder path is not set, an exception will be thrown
```
``` 
cc @cliffano (2017/07) @zlx …
> [Ruby] force users to specify the temp folder path to address security concerns

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
Better invalid spec error message
```
Issues with the OpenAPI input. Possible causes: invalid/missing spec, malformed JSON/YAML files, etc.
```
```
``` 
> Better invalid spec error message

- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
- modules/openapi-generator-gradle-plugin/README.adoc
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-maven-plugin/README.md
- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
Add an option to skip operation examples to avoid potential JVM out of memory errors
Closes https://github.com/OpenAPITools/openapi-generator/issues/6597
Closes https://github.com/OpenAPITools/openapi-generator/issues/8682
Closes https://github.com/OpenAPITools/openapi-generator/issues/4398
```
```  …
> Add an option to skip operation examples

- modules/openapi-generator/src/main/resources/go/client.mustache
- modules/openapi-generator/src/main/resources/go/configuration.mustache
Golang client generator allows to include the AWS v4 signature. However, It's not possible to provide AWS session token (required when we use temporary credentials) and some configuration parameters like region and service name are hardcoded.
This PR adds additional configuration options: SessionToken, Region and Service to the existing sigv4 implementation.
This change maintain backward compatibility. Old, hardcoded values for region and service name are used as a default ones.
```
``` 
You may …
> [GO] Add additional AWS v4 signature config options to go client generator

- modules/openapi-generator/src/main/resources/typescript-axios/common.mustache
- samples/client/petstore/typescript-axios/builds/composed-schemas/common.ts
- samples/client/petstore/typescript-axios/builds/default/common.ts
- samples/client/petstore/typescript-axios/builds/es6-target/common.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/common.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/common.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/common.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/common.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/common.ts
typescript-axios does not correctly output query arguments when you use `explode: true` for a parameter.
```
``` 
- CC: @TiFu @taxpon  @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov 
fixes #7966
fixes #7973
> [typescript-axios] Support array query arguments

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/play26/ApiClient.mustache
- samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- use Files.createTempFile instead to avoid potential security issues.
```
```  …
> [Java] use Files.createTempFile instead

- modules/openapi-generator/src/test/java/org/openapitools/codegen/asciidoc/IncludeMarkupFilterTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/asciidoc/LinkMarkupFilterTest.java
Use Files.createTempFile in asciidoc generator tests if possible to avoid potential security issues.
```
``` 
> Use Files.createTempFile in asciidoc generator tests if possible

- modules/openapi-generator/src/main/resources/python/model_templates/method_init_simple.mustache
- samples/client/petstore/python/petstore_api/model/animal_farm.py
- samples/client/petstore/python/petstore_api/model/enum_class.py
- samples/client/petstore/python/petstore_api/model/number_with_validations.py
- samples/client/petstore/python/petstore_api/model/string_enum.py
- samples/openapi3/client/petstore/python/petstore_api/model/animal_farm.py
- samples/openapi3/client/petstore/python/petstore_api/model/array_of_enums.py
- samples/openapi3/client/petstore/python/petstore_api/model/enum_class.py
- samples/openapi3/client/petstore/python/petstore_api/model/integer_enum.py
- samples/openapi3/client/petstore/python/petstore_api/model/integer_enum_one_value.py
- samples/openapi3/client/petstore/python/petstore_api/model/integer_enum_with_default_value.py
- samples/openapi3/client/petstore/python/petstore_api/model/number_with_validations.py
- samples/openapi3/client/petstore/python/petstore_api/model/string_enum.py
- samples/openapi3/client/petstore/python/petstore_api/model/string_enum_with_default_value.py
> [python][template] move _path_to_item of simple init to avoid name error

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/conflictingParameter.yaml
- Fix bugs to ensure unique parameter names
- Add tests
Related: https://github.com/OpenAPITools/openapi-generator/pull/5963
Credit: @thiagoarrais for creating the test spec.
```
``` 
> Fix bugs to ensure unique parameter names

- modules/openapi-generator/src/main/resources/JavaVertXWebServer/apiHandler.mustache
- modules/openapi-generator/src/main/resources/JavaVertXWebServer/supportFiles/HttpServerVerticle.mustache
- samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/HttpServerVerticle.java
- samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/PetApiHandler.java
- samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/StoreApiHandler.java
- samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/UserApiHandler.java
Fix #8710
This PR deprecates the default no-args constructor for `ApiHandler` and replaces it with a constructor requiring to provide the implementation, in order to make easier to use the generated code without modifying it
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
```
```  …
> [Java][Vert.x] Make ApiHandler reusable

- modules/openapi-generator/src/main/resources/rust/model.mustache
For a field described like:
```yaml
matrixAttributes:
type: array
uniqueItems: true
items:
type: string
enum: ["travelTimes", "distances"]
default: ["travelTimes"]
```
the generated field in Rust would not be correct and was:
```rust
#[serde(rename = "matrixAttributes", skip_serializing_if = "Option::is_none")]
pub matrix_attributes: Option<MatrixAttributes>,
```
with this patch, it is now correctly wrapped in a collection, depending on whether `uniqueItems` is set or not:
For a list:
```rust
#[serde(rename = "matrixAttributes", skip_serializing_if = "Option::is_none")]
pub matrix_attributes: Option<Vec<MatrixAttributes>>,
```
For a set:
```rust
#[serde(rename = "matrixAttributes", skip_serializing_if = "Option::is_none")]
pub matrix_attributes: …
```
> Rust: Add support for lists (and sets) of enum values

- modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache
- modules/openapi-generator/src/main/resources/ruby-client/api_client_typhoeus_partial.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
- samples/client/petstore/ruby/lib/petstore/api_client.rb
- samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_client.rb
- samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_client.rb
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb
… security concerns (#8730)"
This reverts commit 18a6f5a941f3b5777977693f3b59ac5d200928a8.
```
``` 
> Revert "[Ruby] force users to specify the temp folder path to address security concerns (#8730)"

- modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/Generator.java
In the online generator, use Files.createTempFile to address security concerns
```
``` 
> [online] use Files.createTempFile to address security concerns

- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- Use Files.createTempFile instead
```
``` 
> [maven plugin] fix security issues

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- modules/openapi-generator/src/main/resources/dart-dio/pubspec.mustache
- modules/openapi-generator/src/main/resources/dart2/pubspec.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/pubspec.yaml
- samples/client/petstore/dart2/petstore_client_lib/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/another_fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/default_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/pom.xml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/README.md
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/analysis_options.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/pet_api_test.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/pubspec.yaml
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/pubspec.yaml
Dio automatically adds a default transformer which does call `json.encode` and `json.decode` when the content-type is `application/json`. When the content-type is different, then it  is up to the consumer to configure the Dio instance correctly to support custom content-types.
Also tests!!!
```
```  …
> [dart][dart-dio] Remove manual json encode/decode calls in API classes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
- samples/openapi3/client/petstore/go/go-petstore/docs/DefaultApi.md
Go generation didn't properly named base type in `getSchemaType`, which ends up
breaking some doc generation.
```
``` 
> Fix base type naming in Go

- modules/openapi-generator/src/main/resources/go/go.mod.mustache
- samples/client/petstore/go/go-petstore/go.mod
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/go.mod
- samples/openapi3/client/petstore/go/go-petstore/go.mod
Temporary fix for #8763 till an official release of oauth2 package is actually made
Using the latest available version of this package at the time of writing https://pkg.go.dev/golang.org/x/oauth2?tab=versions
> [GO] use latest available oauth2 version

- modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
- modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
- samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api.module.ts
- samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/store.service.ts
- samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/api/user.service.ts
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/8810
```
``` 
> typescript-nestjs: removed unused basePath from api.service template

- modules/openapi-generator/src/main/resources/dart2/api.mustache
- samples/client/petstore/dart2/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/store_api.dart
- samples/client/petstore/dart2/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/another_fake_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/default_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/fake_classname_tags123_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api/user_api.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api/another_fake_api.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api/default_api.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api/fake_classname_tags123_api.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api/store_api.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api/user_api.dart
> [dart] Remove old leftover format parameter from path

- modules/openapi-generator/src/main/resources/go-server/routers.mustache
- samples/server/petstore/go-api-server/go/routers.go
Fork of https://github.com/OpenAPITools/openapi-generator/pull/8683 with the samples regenerated
This is a similar fix to the other PR but I was able to regenerate the samples.
This adds a missing import into the routers from go server
> [Fix GO Server] Add mime/multipart missing import in go server

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ErlangClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFExtServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/K6ClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KtormSchemaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/MysqlSchemaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlim4ServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/mysql/MysqlSchemaCodegenTest.java
EclipseJdt cleanup 'RemoveUnnecessaryCast' applied by erefactor.
For EclipseJdt see https://www.eclipse.org/eclipse/news/4.18/jdt.php
```
``` 
> [cleanup] erefactor/EclipseJdt - Remove unnecessary casts

- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/api/TemplateProcessor.java
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/JsonCache.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
EclipseJdt cleanup 'RemoveRedundantSemicolons' applied by erefactor.
For EclipseJdt see https://www.eclipse.org/eclipse/news/4.18/jdt.php
```
``` 
> [cleanup] erefactor/EclipseJdt - Remove redundant semicolons

- .github/workflows/sonar.yml
The CI fails every time in a fork because it can't get uploaded to sonar (obviously). This PR fixes this
Taken from https://github.community/t/how-to-detect-a-pull-request-from-a-fork/18363/3
```
``` 
> Don't deploy to sonar in forks

- modules/openapi-generator/src/main/resources/cpp-qt5-client/ServerConfiguration.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache
- samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXPetApi.h
- samples/client/petstore/cpp-qt5/client/PFXServerConfiguration.h
- samples/client/petstore/cpp-qt5/client/PFXStoreApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXStoreApi.h
- samples/client/petstore/cpp-qt5/client/PFXUserApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXUserApi.h
The issue #8694 pointed out that there are some unused variables and that it would be handy to be able to add new servers that are not provided in the OpenAPI file. The variables `host`, `port`, `scheme` and `basePath` have been removed since the servers are handled by the `ServerConfiguration` class.  Furthermore one can add a new `ServerConfiguration` for an Operation: 
```
[...]
API api;
//add a new server with port and server variables
int newDefaultServerIndex =  api.addServerConfiguration("defaultServer","{server}:{port}","newly added default server", 
QMap<QString, PFXServerVariable>{ 
{"server", PFXServerVariable("No description provided","custom-petstore",
QSet<QString>{ {"custom-petstore"},{"custom-qa-petstore"},{"custom-dev-petstore"} })}, 
{"port", PFXServerVariable("No …
```
> [C++][Qt5] Added function to add a new Server. Removed unused variables

- modules/openapi-generator/src/main/resources/dart-dio/api.mustache
- modules/openapi-generator/src/main/resources/dart-dio/api_util.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/client/petstore/dart-dio/petstore_client_lib/lib/api_util.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/api_util.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/api_util.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api/fake_api_test.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/test/api_util_test.dart
* handle all primitives correctly
* use specific serializer for non-primitives
Related to https://github.com/OpenAPITools/openapi-generator/issues/8271
> [bug][dart][dart-dio] Improve parameterToString handling

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5AbstractCodegen.java
- modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-header.mustache
- samples/client/petstore/cpp-qt5/client/PFXHelpers.h
This PR will add support for QSet as a datatype when using unique items. QSet is added to the `typeMapping` in the `CppQt5AbstractCodegen` and the all helper functions are implemented in the `helpers-header.mustache` template.
```
``` 
PING @wing328 …
> [C++][Qt5] added QSet as datatype for unique items

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/resources/csharp-netcore/ClientUtils.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ClientUtils.cs
This was triggered by this issue which it should close https://github.com/OpenAPITools/openapi-generator/issues/8798
Looking into the issue I found that indeed SwaggerUI and the csharp-netcore client libraries were generating different queries. Neither of which was getting read by the newly updated aspnetcore generator (https://github.com/OpenAPITools/openapi-generator/pull/8826). It appears that neither format was acceptable there and this is also something Swashbuckle needs to fix (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2034) as their generated spec does not actually work with the controller its supposed to query.
This pull request does two things:
- Fix default handling so that it corresponds to what SwaggerUI is doing for Dictionaries
- Fix deepObject …
> [csharp-netcore] Fix handling of Dictionary query parameters and fix deepObject style parameter handling

- samples/client/petstore/cpp-qt5/PetStore/PetApiTests.cpp
- samples/client/petstore/cpp-qt5/PetStore/PetApiTests.h
- samples/client/petstore/cpp-qt5/PetStore/StoreApiTests.cpp
- samples/client/petstore/cpp-qt5/PetStore/UserApiTests.cpp
- samples/client/petstore/cpp-qt5/PetStore/UserApiTests.h
Updated and reenabled the test cases
```
``` 
@ravinikam @stkrwork @MartinDelille @muttleyxd
> [C++][Qt]Updated test and fix/workaround failed tests

- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ClientUtils.cs
This is a first step that in general makes the API Client compatible with Blazor Webassembly applications. I'll add some more detailed instructions later but it does work already out of the box. Performance improvements as well as size improvements are something that is definitely desirable in that scenario but that can come later.
```
```  …
> [csharp-netcore] Make Blazor Webassembly compatible

- modules/openapi-generator-gradle-plugin/README.adoc
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
Gradle Plugin's `additionalProperties` are of type Map<String, String>. When a project tries to set a `Boolean` property it needs to put it as a String (i.e. "true") which is not evaluated as proper `Boolean` value by mustache template.
This PR update `additionalProperties` to `Map<String, Any>`.
Use case comes from `moko-network` library: https://github.com/icerockdev/moko-network/issues/59
```
```  …
> [Gradle Plugin] Allow to set additional property of any type. Useful for Boolean values.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
See #8896 . The Go client was failing when a schema looked like:
```json
"schema": {
"type": "string",
"format": "date-time",
"default": "2000-01-01T00:00:00Z"
}
```
This fixes that! Not sure who to tag in this... @wing328 ?
> Fix String cast error on default object

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
- Call static method without creating instance as the class may not have the default constructor.
```
``` 
> [C#][netcore] Call static method without creating instance

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
Remove deprecated restsharp parameter class to address the warning shown in the building process.
```
``` 
> Remove deprecated restsharp parameter class

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java
- modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
This fixes python list examples on models by not generating the example when we have model objects, and adding the missing closing character when we don't.
```
``` 
> Fix python example list

- modules/openapi-generator/src/main/resources/dart-dio/pubspec.mustache
- samples/client/petstore/dart-dio/petstore_client_lib/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml
The `8.x` versions are no longer compatible with the current generated code. An update is also not possible without breaking change and null-safety support.
```
``` 
> [dart][dart-dio] Lower upper bound for built_value

- modules/openapi-generator/src/main/resources/typescript-angular/README.mustache
- samples/client/petstore/typescript-angular-v10-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v10-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v11-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v11-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v7-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/README.md
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-npm/README.md
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-prefixed-module-name/README.md
- samples/client/petstore/typescript-angular-v9-provided-in-any/builds/default/README.md
- samples/client/petstore/typescript-angular-v9-provided-in-root/builds/default/README.md
- samples/client/petstore/typescript-angular-v9-provided-in-root/builds/with-npm/README.md
> Arrow function removed

- modules/openapi-generator/src/main/resources/csharp-netcore/HttpSigningConfiguration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- better code format 
FYI. @Ghufz
```
``` 
> [C#][netcore] better code format 

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
In an effort to make `kotlin-spring` behave the same as `spring` (java), I disabled generation of the `Application.kt` when `interfaceOnly=true`. This is similar to what `spring` does: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L368
Fixes #5165
```
```  …
> Do not generate Application.kt when interfaceOnly=true

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache
- samples/client/petstore/java/webclient/build.gradle
- samples/client/petstore/java/webclient/pom.xml
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
See #8553 fro more information.
To validate this run the java generator with the webclient library no deprecation warning should be displayed anymore
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet …
> [Java][webclient] Fix deprecation warning: BodyInserters.fromObject

- modules/openapi-generator/src/main/resources/Java/JSON.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/OAuthOkHttpClient.mustache
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/auth/OAuthOkHttpClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/auth/OAuthOkHttpClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/auth/OAuthOkHttpClient.java
- samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/JSON.java
- Fix deprecation warnings for `RequestBody.create()`
- Fix deprecation warnings in JSON.java
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) …
> [java] fix deprecation warnings

- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/bodyParams.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/bodyParams.mustache
- samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/org/openapitools/api/PetApi.java
- samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/org/openapitools/api/StoreApi.java
- samples/server/petstore/jaxrs-cxf-annotated-base-path/src/gen/java/org/openapitools/api/UserApi.java
- samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/org/openapitools/api/PetApi.java
- samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/org/openapitools/api/StoreApi.java
- samples/server/petstore/jaxrs-cxf-non-spring-app/src/gen/java/org/openapitools/api/UserApi.java
- samples/server/petstore/jaxrs-cxf/src/gen/java/org/openapitools/api/AnotherFakeApi.java
- samples/server/petstore/jaxrs-cxf/src/gen/java/org/openapitools/api/FakeApi.java
- samples/server/petstore/jaxrs-cxf/src/gen/java/org/openapitools/api/FakeClassnameTags123Api.java
- samples/server/petstore/jaxrs-cxf/src/gen/java/org/openapitools/api/PetApi.java
- samples/server/petstore/jaxrs-cxf/src/gen/java/org/openapitools/api/StoreApi.java
- samples/server/petstore/jaxrs-cxf/src/gen/java/org/openapitools/api/UserApi.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/AnotherFakeApi.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/FakeApi.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/PetApi.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/StoreApi.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/api/UserApi.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/AnotherFakeApi.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/FakeApi.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/FakeClassnameTestApi.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/PetApi.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/StoreApi.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/api/UserApi.java
This PR adds missing @NotNull annotations for required body parameters when using BeanValidation and fixes #4280.
I fixed all jaxrs generators which use identical bodyParams.mustache files (my company is affected by this bug in the jaxrs-spec generator):
- jaxrs-cxf
- jaxrs-cxf-extended
- jaxrs-spec
Please review by Java technical committee: 
> [jaxrs-cxf][jaxrs-spec] Add missing @NotNull annotation for required body parameters when using BeanValidation, fixes #4280

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/swift5/Swift5ClientCodegenTest.java
- modules/openapi-generator/src/test/resources/bugs/Swift5CodeGenarationBug2.yaml
- samples/client/petstore/swift5/alamofireLibrary/docs/FakeAPI.md
- samples/client/petstore/swift5/combineLibrary/docs/FakeAPI.md
- samples/client/petstore/swift5/default/docs/FakeAPI.md
- samples/client/petstore/swift5/nonPublicApi/docs/FakeAPI.md
- samples/client/petstore/swift5/objcCompatible/docs/FakeAPI.md
- samples/client/petstore/swift5/promisekitLibrary/docs/FakeAPI.md
- samples/client/petstore/swift5/readonlyProperties/docs/FakeAPI.md
- samples/client/petstore/swift5/resultLibrary/docs/FakeAPI.md
- samples/client/petstore/swift5/rxswiftLibrary/docs/FakeAPI.md
- samples/client/petstore/swift5/urlsessionLibrary/docs/FakeAPI.md
This is my  fix for issue  #8671. 
As mentioned in the ticket, there may be even better solutions. 
- [C] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
``` 
> Fix for StackOverflow in Swift5 CodeGeneration Issue #8671

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
DefaultWebClient() already encodes URL query parameters.
Without this PR, I have a request with title=foo bar which gets converted to title=foo%25%20bar.
With this PR, the request becomes title=foo%20bar
This fixes #8171
> fix: remove double URL encoding

- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache
- modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-header.mustache
- samples/client/petstore/cpp-qt5/PetStore/PetApiTests.cpp
- samples/client/petstore/cpp-qt5/client/PFXHelpers.h
- samples/client/petstore/cpp-qt5/client/PFXPetApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXPetApi.h
- samples/client/petstore/cpp-qt5/client/PFXStoreApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXStoreApi.h
- samples/client/petstore/cpp-qt5/client/PFXUserApi.cpp
- samples/client/petstore/cpp-qt5/client/PFXUserApi.h
Fixes #8934
Issue was due to `Optional` support with `QVariant` here #8733
```
``` 
**Changes**
- **QVariant cannot construct user types hence it is not suitable for all cases**
- A more intuitive approach is provided, which also shows the type of …
> [C++][Qt]Replace usage of QVariant with a more intuitive optional wrapper 

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
- modules/openapi-generator/src/main/resources/C-libcurl/README.md.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/api_doc.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/model_doc.mustache
- samples/client/petstore/c/.openapi-generator/FILES
- samples/client/petstore/c/README.md
- samples/client/petstore/c/docs/PetAPI.md
- samples/client/petstore/c/docs/StoreAPI.md
- samples/client/petstore/c/docs/UserAPI.md
- samples/client/petstore/c/docs/api_response.md
- samples/client/petstore/c/docs/category.md
- samples/client/petstore/c/docs/order.md
- samples/client/petstore/c/docs/pet.md
- samples/client/petstore/c/docs/tag.md
- samples/client/petstore/c/docs/user.md
Hi @wing328 @zhemant @michelealbano
This PR will add the feature of generating API and module documents automatically.
To fix https://github.com/OpenAPITools/openapi-generator/issues/8426
```
``` 
> [C][Client] Generate API and module documents automatically

- modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/Serializer.kt.mustache
- samples/client/petstore/kotlin-jackson/build.gradle
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/Serializer.kt
To fix #8688 
```
``` 
Suggested reviewers: @jimschubert  @dr4ke616  @karismann @Zomzog @andrewemery @4brunu @yutaka0m
> [Kotlin] Upgrade jackson version used in the Kotlin client

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java
A friend create a specification with a model named `ApiClient` which resulted for me in two classes with the same name which doesn't compile. So I thought it might be handy to mark the default included classes also as reserved.
```
``` 
@swipesight …
> [DART] Add standard generated classes as reserved

- CI/circle_parallel.sh
- pom.xml
- move dart tests to node 2 to balance the run time
- remove Dart petstore (OASv2) tests as there are already OAS v3 tests
```
``` 
> [Dart] move dart tests to node 2, remove oas v2 dart tests

- appveyor.yml
- fix build error with `-name` in Install-Module in the master (due to changes in appveyor side)
```
``` 
> [PS] fix build error with `-name` in Install-Module

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Drawing.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/Drawing.java
When using composed schemas, `null` is generated as a default value, even if no default value is given. This bug is resides in `AbstractJavaCodegen` and is thus present in many generators extending the `AbstractJavaCodegen`.
Samples showing the buggy behavior already exist in `bin/configs/java-native-openapi3.yaml` and `bin/configs/java-jersey2-8.yaml` using `modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml`. Below is an excerpt of this yaml, showing the definition of the composed schemas. 
```yaml
Drawing:
type: object
properties:
mainShape:
$ref: '#/components/schemas/Shape'
shapeOrNull:
$ref: '#/components/schemas/ShapeOrNull'
nullableShape:
$ref: '#/components/schemas/NullableShape'
shapes:
type: array …
```
> Fix default value generation for composed schemas in AbstractJavaCodegen

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
- samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Controllers/PetApi.cs
- samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Controllers/PetApi.cs
- samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Controllers/PetApi.cs
- samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Controllers/StoreApi.cs
- samples/server/petstore/aspnetcore-5.0/src/Org.OpenAPITools/Controllers/UserApi.cs
- samples/server/petstore/aspnetcore/src/Org.OpenAPITools/Controllers/PetApi.cs
An error in the handling of the for loops caused it to early exit in case the spec contained entries without consuming properties.
```
``` 
> [csharp][aspnetcore] Enable Consumes Tag for Specs where not every operation consumes

- docs/generators/scala-akka-http-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaHttpServerCodegen.java
When the official OpenAPITools / sbt-openapi-generator sbt plugin is used to generate a scala-akka-http-server stub, the resulting files are a project in their own right, including:
- a build file
- a README.md file
- a default controller (controller.scala)
The problem is that it can be interesting not to generate a project, but just the source files needed to compile a project.
By generating just scala files, which are placed in the managedSources of sbt, one can automate the generation of models and APIs within a project, without having to filter unnecessary files that prevent compilation.
This is what this modification allows.
By adding the **asManagedSources** parameter in the additional properties of the generator, the build.sbt, README.md and controller.scala files will be ignored. …
> [scala-akka-http-server] allows generation of managed sources only

- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/ktorm/KtormSchemaCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/objc/ObjcModelTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/BashClientOptionsProvider.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/serializer/SerializerUtilsTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/JsonCacheTest.java
EclipseJdt cleanup 'RemoveAllTrailingWhitespace' applied by erefactor.
> [cleanup] erefactor/EclipseJdt - Remove trailing whitespace - All lines

- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/meta/GeneratorMetadata.java
- modules/openapi-generator-maven-plugin/src/test/java/org/openapitools/codegen/plugin/CodeGenMojoTest.java
- modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/configuration/OpenAPIDocumentationConfig.java
- modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/Generator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenDiscriminator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractApexCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractEiffelCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Apache2ConfigCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AvroSchemaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ClojureClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
EclipseJdt cleanup 'RemoveUnusedImport' applied by erefactor.
> [cleanup] erefactor/EclipseJdt - Remove unused imports - 1

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5AbstractCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestbedServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartJaguarClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/FsharpFunctionsServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMSF4JServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaPlayFrameworkCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaResteasyEapServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptApolloClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptFlowtypedClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NimClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OCamlClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ObjcClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonLegacyClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyOnRailsServerCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/asciidoc/AsciidocGeneratorTest.java
EclipseJdt cleanup 'RemoveUnusedImport' applied by erefactor.
> [cleanup] erefactor/EclipseJdt - Remove unused imports - 2

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractFSharpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptApolloClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/scalahttpclient/ScalaHttpClientModelTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/swift5/Swift5ClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/swift5/Swift5OptionsTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptnode/TypescriptNodeEnumIntegrationTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/OnceLoggerTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/URLPathUtilsTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/validations/oas/OpenApiSchemaTypeTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/yaml/YamlGeneratorTest.java
EclipseJdt cleanup 'RemoveUnusedImport' applied by erefactor.
Currently the last one of this kind!
> [cleanup] erefactor/EclipseJdt - Remove unused imports

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift4Codegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/features/LoggingFeatures.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/Markdown.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/OptionUtils.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/StringUtils.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OpenApiSchemaValidations.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/RuleConfiguration.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/asciidoc/AsciidocGeneratorTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/bash/BashTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/confluencewiki/ConfluenceWikiTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/dio/DartDioClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/dart/dio/DartDioNextClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/fsharp/FSharpServerCodegenTest.java
EclipseJdt cleanup 'RemoveUnusedImport' applied by erefactor.
Currently the last one!
> [cleanup] erefactor/EclipseJdt - Remove trailing whitespace - All lines - 2

- modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/service/ZipUtil.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CliOption.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfiguratorUtils.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/GlobalSettings.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractEiffelCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ConfluenceWikiCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5ClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppUE4ClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpLumenServerCodegen.java
EclipseJdt cleanup 'RemoveAllTrailingWhitespace' applied by erefactor.
> [cleanup] erefactor/EclipseJdt - Remove trailing whitespace - All lines - 1

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractFSharpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellHttpClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptApolloClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NodeJSExpressServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/OCamlClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift4Codegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- Restore interrupted state when InterruptedException occurs by calling `Thread.currentThread().interrupt()`
```
``` 
> Restore interrupted state when InterruptedException occurs

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
Better logging to avoid string concatenation 
```
``` 
cc @swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)
> [Dart] Better logging

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
Use interrupted exception instead of just exception
cc @swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)
```
``` 
> [Dart] Use interrupted exception instead of just exception

- modules/openapi-generator/src/main/resources/aspnetcore/3.0/controller.mustache
- samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Controllers/PetApi.cs
- samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Controllers/StoreApi.cs
- samples/server/petstore/aspnetcore-3.0/src/Org.OpenAPITools/Controllers/UserApi.cs
- samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Controllers/PetApi.cs
- samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Controllers/StoreApi.cs
- samples/server/petstore/aspnetcore-3.1/src/Org.OpenAPITools/Controllers/UserApi.cs
Moved using directive for Microsoft.AspNetCore.Authorization outside of the useSwashbuckle template tag. 
This prevents compilation errors involving a missing Authorize attribute for the generated ASP.NET Core 3.x controllers if Swashbuckle generation is disabled. (See issue #8341)
(Template for 2.0 and 2.1 is unchanged since the issue does not occur there)
> [ASPNETCORE 3.x] Microsoft.AspNetCore.Authorization directive no longer requires useSwashbuckle condition

- modules/openapi-generator/src/main/resources/bash/client.mustache
Bash Client Escapes parameters with a 't' to %09 and leaves tabs unescaped
Fixes https://github.com/OpenAPITools/openapi-generator/issues/7303
Bash Client Escapes parameters with a 't' to %09 and leaves tabs unescaped
openapitools/openapi-generator-cli Version 5.0.0-SNAPSHOT
Command used to generate:
```bash
docker run --rm -v $(git rev-parse --show-toplevel)/lt-frontend/:/local openapitools/openapi-generator-cli generate \
-i /local/spec/frontend-api.yml \
-g bash \
--enable-post-process-file  -o /local/clients/cli/ -p apiKeyAuthEnvironmentVariable=API_KEY,generateBashCompletion=true,hostEnvironmentVariable=API_HOST,scriptName=api,generateZshCompletion=true
```
Example:
```bash
API_HOST=https://load-test-int.test.ops.company.se ./api --dry-run getTestJobByName job=systest-stress-pc
curl …
```
> [Bash] Update client.mustache

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
> fix #8755 [BUG] Java (jersey2) ApiClient debug cannot be enabled

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
Tested against https://ftc-events.firstinspires.org/swagger/v2.0/swagger.json
Used to generate un-runnable code, now it works.  Try running against any openapi
spec with oneof.
> Enable useOneOfInterfaces for the ruby generator

- modules/openapi-generator/src/main/resources/Javascript/es6/package.mustache
Including the generated JS client library code as a git repository did not work when executing npm install. It complained about not being able to find 'babel'. Apparently when referencing a dependency from git, both prepare and prepack are executing to build the 'dist' directory, but prepack does will not include any devDependencies. Therefore we need to switch this to prepare instead.
- [ x Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
CC @CodeNinjai @frol @cliffano
> Use prepare script instead of prepack in Javascript package.json

- modules/openapi-generator/src/main/resources/go/client.mustache
- modules/openapi-generator/src/main/resources/go/configuration.mustache
This is a PR in response to my issue #7390. I need a way to create a custom authentication method (which is specific to a single cloud provider), however current code seems to make modifications to auth methods pretty hard (at least I did not find a way to provide custom header with dynamic value).
In this PR I allowed to do pretty much everything with http request, since I considered it an easy way to provide as many integrations as possible.
Since I am not sure if it's the expected way to fix these issues and I ran into some problems compiling this library I did not run all required scripts, but I am willing to once somebody approves the direction of proposed changes.
> [Go] Allow to use custom middleware

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Better null check for response when using `useOneOfInterfaces`
cherry-pick from https://github.com/OpenAPITools/openapi-generator/pull/6253/files#diff-3a138675e8cb40943bcb00feb46edd6f6ee5c5306c29cc19f02c845a299c8658R780
Credit @tuxBurner 
```
```  …
> Better null check for response

- modules/openapi-generator-core/src/test/java/org/openapitools/codegen/validation/ValidationRuleTest.java
- modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/OpenAPI2SpringBoot.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNancyFXServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaPKMSTServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KtormSchemaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/JsonCache.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java
EclipseJdt cleanup 'MakeInnerClassStatic' applied by erefactor.
> [cleanup] erefactor/EclipseJdt - Make inner class static

- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
This allows for config files of this sort:
```yaml
globalProperties:
skipFormModel: true
apiTests: false
modelTests: false
supportingFiles: ''
models:
- Pet
- Dog
- User
apis:
- UserApi
```
This is much easier to use than comma separated strings, especially for large lists (I have 50+ models out of 100+)
> [core] Allow using lists as globalProperty in config files

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaPKMSTServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonLegacyClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNestjsClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/swift5/Swift5OptionsTest.java
EclipseJdt cleanup 'ParsePrimitive' applied by erefactor.
> [cleanup] erefactor/EclipseJdt - Use primitive parse methods instead of wrapper

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
Similar to https://github.com/OpenAPITools/openapi-generator/pull/5516 but using unaliasSchema instead.
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01)
```
``` 
> Better default value handling in Go generators

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonLegacyClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_8052_recursive_model_expected_value.txt
- samples/client/petstore/python/docs/FakeApi.md
- samples/openapi3/client/petstore/python/docs/FakeApi.md
Fixes type null not handled properly in [python] toExampleValue
Improves regex example setting in the python client generator
```
``` 
> Fixes type null not handled properly in [python] toExampleValue

- modules/openapi-generator/src/main/resources/csharp-netcore/README.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/README.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/DefaultApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/README.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/README.md
- samples/client/petstore/csharp-netcore/OpenAPIClient/README.md
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/README.md
Fixed an existing issue that made the HttpClient open new sockets for each connection. 
Also makes HttpClient settable from external.
Fixes: #9060
Patches: #9085
Updated constructors to be more explicit in the usage.
Updated documentation to underline the use cases and the issue.
```
```  …
> [csharp][netcore-httpclient] Reuse HttpClient, Allow use of external HttpClient. Patch to previous PR.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift4Codegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptInversifyClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNestjsClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
EclipseJdt cleanup 'EvaluateNullable' applied by erefactor.
> [cleanup] erefactor/EclipseJdt - Evaluate without null check

- docs/usage.md
```
``` 
- Update `usage.md` (and therefore hopefully the website as well) with the current output of the CLI; it looks like this was forgotten when new features were added in the past
- Change syntax highlighting for CLI output in `usage.md` from `bash` …
> Update usage.md with current CLI output

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java
quoting for default values is already done in:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java#L533
```
``` 
> [php-symfony] fix double quoting string defaults values

- modules/openapi-generator/src/main/resources/go/model_enum.mustache
- samples/client/petstore/go/go-petstore/model_enum_class.go
- samples/client/petstore/go/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go/go-petstore/model_enum_class.go
- samples/openapi3/client/petstore/go/go-petstore/model_outer_enum.go
- samples/openapi3/client/petstore/go/go-petstore/model_outer_enum_default_value.go
- samples/openapi3/client/petstore/go/go-petstore/model_outer_enum_integer.go
- samples/openapi3/client/petstore/go/go-petstore/model_outer_enum_integer_default_value.go
Add constructor and IsValid method to enum types.
This allows users of library to make they have valid value when not using the constants directly
> [go] Add constructor and IsValid method to enum types

- docs/templating.md
I spotted a way to control the enum variants in rust-server for the responses in the docs, tried it out and discovered it doesn't work. Further digging found that the property was simply mislabelled in the docs and works as expected when using the correct property name.
> [rust-server] Update templating docs to correct the name of x-response-id

- bin/configs/go-server-go-api-server.yaml
- docs/generators/go-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
- modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
- modules/openapi-generator/src/main/resources/go-server/helpers.mustache
- modules/openapi-generator/src/main/resources/go-server/impl.mustache
- modules/openapi-generator/src/main/resources/go-server/routers.mustache
- samples/server/petstore/go-api-server/go/api_pet.go
- samples/server/petstore/go-api-server/go/api_store.go
- samples/server/petstore/go-api-server/go/api_user.go
- samples/server/petstore/go-api-server/go/helpers.go
- samples/server/petstore/go-api-server/go/impl.go
- samples/server/petstore/go-api-server/go/routers.go
This pull request is intended to provide the capability to specify headers to include in the response.
This is needed, for example, to allow a REST API to redirect the client to a new URL (using the Location header).
This pull request includes also the changes in the pull request #8144
credits: @randomswdev 
Also added an option "addResponseHeaders" to make this change backward-compatible.
Tests also passed without the option enabled: https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/10088/workflows/40c945db-9fbc-47e3-a330-e0cfae82cc2f/jobs/23700
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would …
> Allow to specify response headers (needed for redirecting clients)

- modules/openapi-generator/src/main/resources/typescript-angular/configuration.mustache
In order to avoid a compiler error when using `noImplicitReturns `, we
change the mustache template to use provide a return value for the if-
and else branch.
Fixes #9174.
---- 
```
```
> [typescript-angular] Provide return value for all code paths (#9174)

- modules/openapi-generator/src/main/resources/scala-akka-client/requests.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/serializers.mustache
- samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/core/Serializers.scala
- samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/core/requests.scala
Add support for the `java.util.UUID` type in parameter serialization and response deserialization.
This additionally adds support for `java.net.URI`, `java.net.URL` for response deserialization.
The UUID types are already generated, when using a schema using uuid formatted strings in the openapi schema.
@cchafer
```
``` 
For Windows …
> Support UUID types in scala-akka-client

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
Currently, showing warnings instead of throwing exceptions in case the spec is not perfect.
We're already doing something similar in other part of the codegen, e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2025
```
``` 
For Windows …
> Use warning instead of throwing exceptions

- modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache
Recursive validate non primitive objects
> [php-symfony] Update model_variables.mustache

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/NimClientCodegen.java
- samples/client/petstore/nim/petstore/apis/api_pet.nim
camelize names (e.g. api_key => apiKey)
To fix https://github.com/OpenAPITools/openapi-generator/issues/9250
Ref: https://nim-lang.org/docs/nep1.html
cc @hokamoto
```
``` 
> [nim] camelize names

- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
Motivation:
In Gradle 7.0 apply @Input and @Internal on property is forbidden.
Before Gradle 7.0 applying both on the same property is confusing. According to the documentation:
* @Input: Attached to a task property to indicate that the property specifies some input value for the task.
* @Internal: Attached to a task property to indicate that the property is not to be taken into account for up-to-date checking
Note: Gradle 7.0 is not release yet 2021-03-24
build.gradle.kts
```
plugins {
id("org.openapi.generator") version ("5.1.0")
}
```
with the command line `./gradlew openApiGenerate` will cause
```
Type 'GenerateTask' property 'input' annotated with @Internal should not be also annotated with @Input.
Reason: A property is ignored but also has input annotations.
Possible solutions:
1. …
```
> Gradle - @Input and @Internal should not be apply on the same property

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache
This is a fix for #9238
```
``` 
@jimschubert (2017/09), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)
> Kotlin jvm-retrofit2: Add missing ResponseBody import for binary responses

- modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
- samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/build.gradle
- samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/models/Order.kt
- samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/models/Pet.kt
Enum class which are inside the dataClass.mustache file are missing the `Serializable` annotation. This leads to a wrong behavior of the serializer where the names instead of the the SerialName values are used. 
You can reproduce this issue if you run the `kotlin-retrofit2-kotlinx_serialization` sample project. A warning like `Explicit @Serializable annotation on enum class is required when @SerialName or @SerialInfo annotations are used on its members.` will be thrown. 
The changeset also adds the Xopt-in compiler flags for the `ExperimentalSerializationApi` which also leads to compiler warnings.
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of …
> [Kotlin] Fix (de)serialization of enum classes (kotlinx serialization)

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
- modules/openapi-generator/src/main/resources/kotlin-spring/enumClass.mustache
While inner enum classes from dataClass.mustache work fine, standalone enum classes lack `@JsonProperty` annotations so that Jackson uses names instead of values.
> [Kotlin] Fix (de)serialization of enum classes

- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/DefaultApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
It tries to reduce the number of constructors introduced in previous PR.
Related to: #9060, #9085
In the previous PM I created too much constructors.
This is an emprovement to reduce them:
1. I kept the HttpClient service as first parameter when available in signature
2. Then the configurations
3. Then the optional HttpClientHandler
With this PM we have in ApliClient:
1. ctor()
2. ctor(string basePath)
3. **ctor(HttpClient client, HttpClientHandler handler = null)**
4. **ctor(HttpClient client, string basePath, HttpClientHandler handler = null)**
(point 1-2 marked as obsolete)
and in ApiClass:
1. ctor()
2. ctor(string basePath)
3. ctor(Configuration configuration)
3. **ctor(HttpClient client, HttpClientHandler handler = null)**
4. **ctor(HttpClient client, string basePath, …
> [csharp][netcore-httpclient] Refactor of constructors

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
typescript-axios was missing `baseName` when applying params where the value is an array.
For example it will generate the following:
```
if (tags) {
localVarFormParams.append(tags.join(COLLECTION_FORMATS.csv));
}
```
But it should be:
```
if (tags) {
localVarFormParams.append("tags", tags.join(COLLECTION_FORMATS.csv));
}
```
The FormData `append` and `set` should have at least two parameters `name` and `value`, as seen here
https://developer.mozilla.org/en-US/docs/Web/API/FormData/append
https://developer.mozilla.org/en-US/docs/Web/API/FormData/set
This bug has also been raised by somebody else: fixes #9036
```
```  …
> [typescript-axios] add missing baseName for array params

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/ruby/RubyClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/type_mapping_test.yaml
Based on  #4931 (credits: @ShoeBoom) but use `+` as the separator
=========================
Makes it possible to map format.
For example these args can be used to properly map the following:
```
"foo": {
"enum": [
"0",
"1",
"2"
],
"type": "integer",
"format": "byte"
}
```
`generate -i openapi.json -o out -g kotlin --type-mappings integer_byte=kotlin.Byte`
By default it would map `foo` to `Int`
this is similar to #2730
```
```  …
> [Enhancement] added support for custom type & format mapping

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
To fix https://github.com/OpenAPITools/openapi-generator/issues/9191
```
``` 
> [Ruby] prevent NPE in constructing oneOf example

- modules/openapi-generator/src/main/resources/cpp-ue4/helpers-header.mustache
If the API we're generating for uses UUID, which is appropriately mapped to FGuid for UE4, we get compiler errors because the default templated c++ methods get called with FGuid, which doesn't support those standard operations.
Here I've added FGuid specializations akin to how FDateTime is handled, which resolves the compiler errors and adds FGuid support.
```
```  …
> UE4 - Support FGuid with in/out Helpers

- README.md
Add a link to twilio blog
```
``` 
> Add a link to twilio blog

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
[Kotlin][#9317] @Path must be before @Query
(See the bug ticket)
The sorting code is taken from the Java code generator.
```
``` 
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu …
> [Kotlin][#9317] Add parameter sorting to Kotlin client generator

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-retrofit2-rx3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-retrofit2/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
[Kotlin][#7925] Make ApiClient in jvm-retrofit2 be able to add additional retrofit Converter.Factory
The serializer option is not enough, we need an additional Converter.Factory for date serialization in query params (not body). 
```
``` 
@jimschubert …
> [Kotlin][#7925] Make ApiClient in jvm-retrofit2 be able to add additional retrofit Converter.Factory

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api_test.mustache
- modules/openapi-generator/src/main/resources/JavaSpring/homeController.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- samples/server/petstore/spring-mvc-j8-async/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-j8-localdatetime/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-no-nullable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-spring-pageable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-beanvalidation-no-nullable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-beanvalidation/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-delegate/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/configuration/HomeController.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-delegatePattern/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-without-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-virtualan/src/main/java/org/openapitools/virtualan/model/FormatTest.java
- samples/server/petstore/springboot/src/main/java/org/openapitools/model/FormatTest.java
Related to #8659 
Actual api endpoint is using `org.springframework.core.io.Resource` but delegatee is using `org.springframework.web.multipart.MultipartFile`
Now both are using the second one, which is recommended by Spring (according to my latest knowledge)
Tests are passing and also generation of the following endpoint works (it does not work on plain 5.1.0)
```
post:
operationId: setClientFile
tags:
- clients
parameters:
- $ref: '#/components/parameters/clientId'
requestBody:
required: true
content:
application/octet-stream:
schema:
type: string
format: binary
responses:
204:
description: No records found
415:
description: Invalid image type
200:
description: Upload successful
```
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch
``` …
```
> [Java][Spring] Fix for #8659 Different in-parameter types generated for api and delegate for binary (application/octet-stream)

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Add `refreshUrl` to CodegenSecurity
Ref: [OAS3 - OAuth Flow Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oauth-flow-object)
Closes #9209 
```
``` 
> [core] Add refreshUrl to CodegenSecurity

- docs/plugins.md
The snippet for openapi-generator-maven-plugin ist updated with the latest version (5.1.0) und now similar to https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-maven-plugin/README.md. 
Since it's a very simple doc-only change, I didn't run tests etc. 🙈
> [DOCS] Updated pom.xml snippet with latest version

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
- samples/client/petstore/java/okhttp-gson-dynamicOperations/build.gradle
- samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
- samples/client/petstore/java/okhttp-gson/build.gradle
My understanding of the version 5 release of OpenAPI generator was that Java 7 support was dropped. Currently the Java client defaults to Java 7, Java 8 can be opted in with the `java8` config option. This removes the conditional logic in `build.gradle` around that config option and defaults to Java 8. This is to support #9151, up-to-date dependency versions rely on Java 8 and it's easier if that is the default.
To be clear, this changes behavior - previous default version was Java 7, this changes it to Java 8.
```
```  …
> [java][okhttp] Default Java client to Java 8 instead of Java 7

- modules/openapi-generator/src/main/resources/php/model_generic.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/NullableClass.php
we cannot call `parent::` if parent isn't present. Everywhere else in the schema we're checking for `{{parentSchema}}` but here we're checking for `{{parent}}` which is causing errors when parent is not present
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) ❤️, @ybelenko (2018/07), @renepardon (2018/12)
```
```  …
> [PHP] Fix parentSchema conditional causing parent call when parent isn't present

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache
- samples/client/petstore/java/okhttp-gson-dynamicOperations/build.gradle
- samples/client/petstore/java/okhttp-gson-parcelableModel/build.gradle
- samples/client/petstore/java/okhttp-gson/build.gradle
In 5.0.1 the generated line in `ApiClient` was:
```
return RequestBody.create(MediaType.parse(contentType), (byte[]) obj);
```
in 5.1.0 it is:
```
return RequestBody.create((byte[]) obj, MediaType.parse(contentType));
```
Looks like this change was introduced in #8969, and requires a more recent version of OkHttp to compile in some (all?) circumstances.
I tested out the failing spec that was mentioned in the linked ticket, and it compiles now.
```
```  …
> [java][okhttp] Fixes #9151: Bump OkHTTP dependency to latest

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java
Check if there's a default response in specs
```
``` 
> [Codegen] Add hasDefaultResponse property

- new.sh
This is a small fix, for generating a new template. It helps getting started.
I found the issue today, as I was making a new generator.
I've made a Issue, describing the problem #9320 
```
``` 
> [BUG] new.sh fix generator type , issue #9320

- modules/openapi-generator/src/main/resources/csharp-netcore/README.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/api_doc.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/README.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/AnotherFakeApi.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/DefaultApi.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/FakeApi.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/FakeClassnameTags123Api.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/PetApi.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/StoreApi.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/UserApi.md
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools.Test/Api/PetApiTests.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/AnotherFakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/DefaultApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/FakeClassnameTags123Api.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/StoreApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/UserApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
Removed the obsolete attribute on constructors without the HttpClient parameter.
See last comments in PR #9145.
```
``` 
> [csharp][netcore-httpclient] Refactor of constructors: removed obsolete attribute

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
- [ X ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ X ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
``` 
You …
> [aspnetcore] Fix incorrect logging messages

- docs/generators/aspnetcore.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
To fix #9398
- [ X ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ X ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
```  …
> [aspnetcore] Fix config enum documentation

- CONTRIBUTING.md
- modules/openapi-generator/src/main/resources/cpp-ue4/api-header.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/api-source.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/model-base-header.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/model-base-source.mustache
- samples/client/petstore/cpp-ue4/Private/OpenAPIBaseModel.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIPetApi.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIStoreApi.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIUserApi.cpp
- samples/client/petstore/cpp-ue4/Public/OpenAPIBaseModel.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIPetApi.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIStoreApi.h
- samples/client/petstore/cpp-ue4/Public/OpenAPIUserApi.h
Hello, I have improved the retry system of the generator as per Epic's suggestion. The new Http retry system allows timeouts and exponential backoff (technically unreal's implementation is arithmetic not exponential).
```
``` 
@ravinikam (2017/07) …
> [cpp-ue4] Improved retry system to use Unreal's FHttpRetrySystem

- modules/openapi-generator/src/main/resources/dart2/api_client.mustache
- modules/openapi-generator/src/main/resources/dart2/build.yaml.mustache
- modules/openapi-generator/src/main/resources/dart2/pubspec.mustache
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api_client.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/pubspec.yaml
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api_client.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/pubspec.yaml
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/build.yaml
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api_client.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/pubspec.yaml
upgrade dart generator dependencies
> upgrade dart generator dependencies

- modules/openapi-generator/src/main/resources/Javascript-Flowtyped/api.mustache
Without these changes, openapi-generator will create `Set()` objects for swagger parameters with `"uniqueItems": true`.  This wraps those `Set`s in `Array.from()` so they can be properly joined. When debugging this in our setup, I found  #8695 which fixes this issue for `typescript-fetch` in the same way.
Also replaced some mixed-indent with spaces in the relevant file.
> [Javascript-Flowtyped] Handle joining uniqueItems in api template

- modules/openapi-generator/src/main/resources/bash/client.mustache
- samples/client/petstore/bash/petstore-cli
Currently a generated bash client will not append headers as documented:
```
bash samples/client/petstore/bash/petstore-cli --dry-run --host localhost getPetById a:b
curl  -sS --tlsv1.2   -X GET "localhost/v2/pet/"
```
This PR fixes the generated client to match `Header-Name: Header-Value` parameters and add them to the request:
```
bash samples/client/petstore/bash/petstore-cli --dry-run --host localhost getPetById a:b
curl  -sS --tlsv1.2 -H "a: b"   -X GET "localhost/v2/pet/"
```
@frol @bkryza @kenjones-cisco
> [Bash] Fix matching of header parameters

- modules/openapi-generator/src/main/resources/crystal/configuration.mustache
- modules/openapi-generator/src/main/resources/crystal/model.mustache
- modules/openapi-generator/src/main/resources/crystal/partial_model_generic.mustache
- modules/openapi-generator/src/main/resources/crystal/shard.mustache
- samples/client/petstore/crystal/shard.yml
- samples/client/petstore/crystal/src/petstore/configuration.cr
- samples/client/petstore/crystal/src/petstore/models/api_response.cr
- samples/client/petstore/crystal/src/petstore/models/category.cr
- samples/client/petstore/crystal/src/petstore/models/order.cr
- samples/client/petstore/crystal/src/petstore/models/pet.cr
- samples/client/petstore/crystal/src/petstore/models/tag.cr
- samples/client/petstore/crystal/src/petstore/models/user.cr
This PR fix follows.
```
``` 
@wing328
> [crystal][client] some fix and minor improvement

- modules/openapi-generator/src/main/resources/typescript/api/api.mustache
- modules/openapi-generator/src/main/resources/typescript/types/ObservableAPI.mustache
- modules/openapi-generator/src/main/resources/typescript/types/PromiseAPI.mustache
- samples/openapi3/client/petstore/typescript/builds/default/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/types/ObservableAPI.ts
- samples/openapi3/client/petstore/typescript/builds/default/types/PromiseAPI.ts
- samples/openapi3/client/petstore/typescript/builds/deno/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/deno/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/deno/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/deno/types/ObservableAPI.ts
- samples/openapi3/client/petstore/typescript/builds/deno/types/PromiseAPI.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/types/ObservableAPI.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/types/PromiseAPI.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/types/ObservableAPI.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/types/PromiseAPI.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/types/ObservableAPI.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/types/PromiseAPI.ts
fixes https://github.com/OpenAPITools/openapi-generator/issues/9425
```
``` 
> [BUG] [typescript] Duplicate parameter's names (rename options to _options and config to _config)

- bin/configs/kotlin-json-request-string.yaml
- modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache
- samples/client/petstore/kotlin-json-request-string/build.gradle
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/ApiResponse.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/Category.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/Order.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/Pet.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/Tag.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/User.kt
This PR adds a sample project to ensure that the parcelizeModels option continues to work as expected.
```
``` 
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m …
> [kotlin][client] add sample for parcelizeModels

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/scala/SttpCodegenTest.java
scala-sttp generators would not compile when URI parameter names were not camelCase.  Fixed by substituting the names in the URI with values from encodePath.
Test case added.
Fixes #9345
cc @clasnake (2017/07), @jimschubert (2017/09) heart, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)
>  [scala-sttp] Compilation failure URI parameter not camelCase, fixes #9345

- modules/openapi-generator/src/main/resources/python-flask/requirements.mustache
- samples/server/petstore/python-flask/requirements.txt
As a result of the release of [Flask 2.0](https://github.com/pallets/flask/releases), the python-flask tests in TravisCI seem to be failing.
[For example](https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/770872412):
```
==================================== ERRORS ====================================
_________ ERROR collecting openapi_server/test/test_pet_controller.py __________
ImportError while importing test module '/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask/openapi_server/test/test_pet_controller.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
openapi_server/test/__init__.py:4: in <module>
from flask_testing import TestCase
.tox/py3/lib/python3.6/site-packages/flask_testing/__init__.py:13: …
```
> [python][flask] Fix to failed tests on TravisCI

- modules/openapi-generator/src/main/resources/crystal/api.mustache
- modules/openapi-generator/src/main/resources/crystal/api_client.mustache
- modules/openapi-generator/src/main/resources/crystal/configuration.mustache
- samples/client/petstore/crystal/spec/api/pet_api_spec.cr
- samples/client/petstore/crystal/spec/api_client_spec.cr
- samples/client/petstore/crystal/src/petstore/api/pet_api.cr
- samples/client/petstore/crystal/src/petstore/api/store_api.cr
- samples/client/petstore/crystal/src/petstore/api/user_api.cr
- samples/client/petstore/crystal/src/petstore/api_client.cr
- samples/client/petstore/crystal/src/petstore/configuration.cr
Support authorization headers `oauth2` and `api_key`.
Note: Probably not the best, but I tried to make it work anyway.
```
``` 
@wing328
> [crystal][client] Support authorization

- docs/generators/aspnetcore.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
partially revert #9404 to fix Travis CI failure in the master.
```
``` 
> [aspnetcore] avoid empty string enum value in the option

- modules/openapi-generator/src/main/resources/typescript/auth/auth.mustache
- samples/openapi3/client/petstore/typescript/builds/default/auth/auth.ts
- samples/openapi3/client/petstore/typescript/builds/deno/auth/auth.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/auth/auth.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/auth/auth.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/auth/auth.ts
Fixes https://github.com/OpenAPITools/openapi-generator/issues/9465
```
``` 
> add OAuth2 to typescript template

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
> [typescript-axios] fix: properly mark 'deprecated' routes in

- modules/openapi-generator/src/main/resources/crystal/configuration.mustache
- modules/openapi-generator/src/main/resources/crystal/shard_name.mustache
- samples/client/petstore/crystal/spec/configuration_spec.cr
- samples/client/petstore/crystal/spec/petstore_spec.cr
- samples/client/petstore/crystal/src/petstore.cr
- samples/client/petstore/crystal/src/petstore/configuration.cr
Support `configure` method with block that looks like:
```crystal
Petstore.configure do |config|
config.username = "xxx"
config.password = "xxx"
end
Petstore::Configuration.new do |config|
...
end
config = Petstore::Configuration.new
config.configure do |config|
...
end
```
Note:
`block_given?` is not supported in Crystal currently.
https://github.com/crystal-lang/crystal/issues/1013
```
```  …
> [crystal][client] support configure method with block

- modules/openapi-generator/src/main/resources/typescript-node/package.mustache
- samples/client/petstore/typescript-node/npm/package.json
Fix typescript-node installation due to @types/bluebird 3.5.35 (latest release) as reported by the CI:
```
> @openapitools/node-typescript-petstore@0.0.1 build
> tsc
node_modules/@types/bluebird/index.d.ts(42,47): error TS1005: '?' expected.
node_modules/@types/bluebird/index.d.ts(42,59): error TS1005: ';' expected.
node_modules/@types/bluebird/index.d.ts(43,34): error TS1110: Type expected.
node_modules/@types/bluebird/index.d.ts(44,27): error TS1110: Type expected.
node_modules/@types/bluebird/index.d.ts(54,17): error TS1005: ']' expected.
node_modules/@types/bluebird/index.d.ts(54,20): error TS1005: ';' expected.
node_modules/@types/bluebird/index.d.ts(54,39): error TS1005: '(' expected.
node_modules/@types/bluebird/index.d.ts(54,40): error TS1135: Argument expression expected. …
```
> Fix typescript-node installation due to @types/bluebird 3.5.35

- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
Removes noncompliant merging of post query parameters, which makes more sense but is not exactly to spec
```
``` 
> [csharp][httpclient] Remove noncompliant post behaviour

- modules/openapi-generator/src/main/resources/dart-dio/gitignore.mustache
- modules/openapi-generator/src/main/resources/dart/libraries/dio/gitignore.mustache
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/.gitignore
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/.gitignore
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/.gitignore
Fixes the invalid gitignore comment style present in the templates of dart-dio and dart-dio-next generators
Fixes #9553
CC(Dart): @swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)
```
```  …
> [dart][dart-dio] Fix gitignore comment style

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api_test.mustache
- modules/openapi-generator/src/main/resources/JavaSpring/homeController.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- samples/server/petstore/spring-mvc-j8-async/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-j8-localdatetime/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-no-nullable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc-spring-pageable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/spring-mvc/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-beanvalidation-no-nullable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-beanvalidation/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-delegate/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/configuration/HomeController.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-delegatePattern/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable-without-j8/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-spring-pageable/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-useoptional/src/main/java/org/openapitools/model/FormatTest.java
- samples/server/petstore/springboot-virtualan/src/main/java/org/openapitools/virtualan/model/FormatTest.java
- samples/server/petstore/springboot/src/main/java/org/openapitools/model/FormatTest.java
This reverts commit b9a1c8f016711307b9c718dbbdf60a137372c7af.
Reverts of PR #9331 to fix #9462
>However, the newly generated interface contract cannot be satisfied in a clean way, as MultipartFile is not supposed to be a return value. See Spring documentation of MultipartFile
>    A representation of an uploaded file received in a multipart request.
>    The file contents are either stored in memory or temporarily on disk. In either case, the user is responsible for copying file contents to a session-level or persistent store as and if desired. The temporary storage will be cleared at the end of request processing.
```
```  …
> Revert "[Java][Spring] Fix for #8659 - Different in-parameter types  - fix for #9462

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
The current generated codes for the C++ pistache server does not pass the correct default value for strings (and thus enums) to the templates. This PR just fixes that.
That way, non-required enum values are not set to an empty string in the constructor of a model, if a corresponding default value is specified.
yaml example
```yaml
Pet:
type: object
required:
- someEnum
- someOtherEnum
- someString
- someOtherString
properties:
someEnum:
type: string
enum: [EnumVal1, EnumVal2, EnumVal3]
default: EnumVal1
someOtherEnum:
type: string
enum: [OtherEnumVal1, OtherEnumVal2, OtherEnumVal3]
someString:
type: string
default: "hello world"
someOtherString:
type: string
```
generated constructor:
```cpp
Pet::Pet()
{
m_SomeEnum = "EnumVal1";
m_SomeOtherEnum = "";
m_SomeString = "hello world"; …
```
> [C++][Pistache] fix missing default values for string and enum types

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlim4ServerCodegen.java
It was a mistake to extend Slim4 from Slim3 codegen. When I need to fix something in Slim4 I have to overwrite code from Slim3 somehow and it's not always possible. It's even more important that Slim3 codegen shouldn't be touched as soon as it's deprecated long time ago.
Refresh samples didn't change which is main goal of this PR.
**Guys, please merge this PR asap, I need to rebase on this all other php-slim4 PRs.**
```
``` 
You may regenerate an individual generator by passing the relevant config(s) …
> [php-slim4] Decouple Slim4 codegen from Slim3

- modules/openapi-generator/src/main/resources/dart/libraries/dio/api.mustache
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/api/another_fake_api.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/api/default_api.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/api/fake_api.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/api/fake_classname_tags123_api.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/api/pet_api.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/api/store_api.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/api/user_api.dart
Add stacktraces to DioErrors that are manually wrapped.
```
``` 
> [dart][dart-dio-next] Add stacktraces to manual DioError instances

- .github/workflows/openapi-generator-test-results.yaml
- .github/workflows/openapi-generator.yaml
- CI/.drone.yml
- CI/circle_parallel.sh
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioNextClientCodegen.java
- shippable.yml
I think this should be the next step for migration to Github actions.
This will give faster and explicit feedback on
* build failures related to generator/plugins
* failing unit tests related to generator/plugins
* outdated docs
* outdated samples
```
```  …
> [ci] Move openapi-generator build/docs/samples to github actions

- modules/openapi-generator/src/main/resources/dart2/api_exception.mustache
- modules/openapi-generator/src/main/resources/dart2/api_helper.mustache
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api_exception.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api_helper.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api_exception.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api_helper.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api_exception.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api_helper.dart
Fixes two nits in `dart2` mustache templates that should satisfy linter:
- add `@override` toString (rule `annotate_overrides`)
- use String's `isNotEmpty` instead of `!isEmpty`  (rule `prefer_is_not_emty`)
@kuhnroyal
```
``` 
> fix: dart2 mustache templates minor improvements

- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
Gets rid of non async pathways that were in the middle of async pathways.
```
``` 
> [csharp][netcore] Handle Deserialization Asynchronously

- docs/generators/swift5.md
- docs/generators/tiny-cpp.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/Swift5OptionsProvider.java
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/9308
```
``` 
> [swift5] Map file and binary to Data

- docs/generators/swift5.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
This PR adds a warning on a temporary flag.
```
``` 
> [swift5] update docs

- modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache
- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
- samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
- samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
This PR fixes the download of binary response and is related to https://github.com/OpenAPITools/openapi-generator/issues/9308 
```
``` 
> [swift5][client] fix binary response

- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
enumvalue is being modified to replace all "-" with "_". This is changing the original enum values.
E.g. If an enum is defined as follows:
enum:
- a-test
- b-rest
- c-best
The values are changed to a_test, b_rest, c_best. This should not happen as it results in issues if the same spec is referenced by different people with different code-gen. 
The enumvalue is still required to replace all "-" with "_" as this is used in typedef.
```
```  …
> [C]: Fix enum values

- docs/generators/tiny-cpp.md
- modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/modelbase-source.mustache
- samples/client/petstore/cpp-restsdk/client/ModelBase.cpp
Fix cpp-restsdk double and float parse.
double.NaN was parsed when server doesn't ensure the floating point value has decimal point in in.
Fixed incorrect server response json parsing. For example the following json:
```json
{
"double_value": 42
}
```
As of now, the value 42 is parsed as NaN, because json library returns false on is_double().
Additional condition ensures NaN is not returned when not needed.
Implemented for both float & double data types.
> [cpp-restsdk] Update json double/float parse.

- .github/workflows/samples-kotlin.yaml
First try to run Kotlin samples via Github.
```
``` 
> [ci] Build kotlin samples via github

- docs/generators/swift5.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/Swift5OptionsProvider.java
> [Swift5] Add useClasses cli option

- docs/generators/aspnetcore.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
- modules/openapi-generator/src/main/resources/aspnetcore/3.0/Project.csproj.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/csharp/CSharpModelTest.java
Since c# 8 / .net core 3.0 it is possible to add a nullable annotation to a project file. 
This allows to use the ? annotation not only on non-nullable types but on all types. 
Using this annotations can improve the readability within the code and also improves API behavior in regards to optional (nullable) properties.
The default behavior is not altered, it should stay compatible with everything.
Tests were added to ensure correct behavior.
This PR is a possible solution for:
#9190 
#9022
@shibayan @Blackclaws @lucamazzanti 
```
```  …
> Add nullable annotation support to AspNetCoreServer

- docs/generators/python-aiohttp.md
- docs/generators/python-blueplanet.md
- docs/generators/python-flask.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/AbstractPythonConnexionServerCodegenTest.java
(#9558) This PR adds a new `usePythonSrcRootInImports` flag to allow a user of the generator to specify that they want the `pythonSrcRoot` value included in the namespaces generated. The default value of false leaves the output as is today. I added this change into the AbstractPythonConnexionServerCodegen so all the extending generators can benefit from it. 
I've added a new unit test suite against the AbstractPythonConnexionServerCodegen since one didn't exist. In there I use a dataProvider to test that with the new flag off that there are no changes to what is generated now and that with the flag on the appropriate paths for file generation and import namespaces are changed.
```
```  …
> Adding usePythonSrcRootInImports logic to AbstractPythonConnexionServerCodegen. (#9558)

- docs/generators/tiny-cpp.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultGeneratorTest.java
> Fix python generation when custom files and templates are specified

- modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
This fixes #9586 . We do not wish to validate enum type parameters further as they are already constrained by their possible values so any validation is superfluous.
```
``` 
@mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws …
> [csharp][netcore] Do not validate enum parameters

- modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
query.Get() must use {{baseName}} instead of {{paramName}} on boolean and default query parameters
> Fix module "go-server" - template "controller-api.mustache"

- modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
Fixes #7619 
Attempting to pass an object as a query parameter while queryParamObjectFormat=json currently results in the key being set to undefined. This PR ensures the key is always provided when the JSON object format is used.
```
``` 
**Technical …
> [typescript-angular] Fix undefined query param when queryParamObjectFormat=json

- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/ValidateTask.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/ValidateTaskDslTest.kt
This fixes #9328, which prevents from using the OpenAPI Generator Gradle Plugin with the latest Gradle 7.0.
As of Gradle 7.0, an error is returned at configuration time if a plugin task declares a property of "mutable" type with a setter.
See https://docs.gradle.org/7.0/userguide/validation_problems.html#mutable_type_with_setter for further details.
This PR fixes this issue by declaring such properties as Kotlin `val` members instead, so they do not have setters.
To validate that the fix works, this PR also adds the capability to run the same set of tests in `ValidateTaskDslTest` using different instances of `GradleRunner`, configured with different versions of Gradle. 
@agilob and @jimschubert I'm mentioning the two of you since you reviewed a similar PR (#9059 ) about `GenerateTask`. …
> fix(#9328): Gradle Plugin ValidateTask does not work under Gradle 7.0

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/SharedTypeScriptTest.java
Fixes #8000 
When using `allOf`, or `oneOf` with an inline schema, a Union/Intersection type is generated with the primitive `object`. This results in an invalid import because the composed type of the schema is ignored.
```js
import { BaseObject &amp; object }
```
To fix this I used  `needToImport` to removes the language primitives from being imported. This same check already happens in `addImport`, but not in `toModelImportMap`.
`toModelImportMap` splits union types but not intersection types, so I've combined those cases into `splitComposedType`. For `splitComposedType` I combined `replace(" ","").split("\\|")` and `split("( [|&] )|[<>]")` into `replace(" ","").split("[|&<>]")`. These should be equivilant regex, and I think stripping the whitespace is good here.
I added the warning in …
> [typescript] Fix uncompilable output when using allOf (#8000)

- modules/openapi-generator/src/test/java/org/openapitools/codegen/yaml/YamlGeneratorTest.java
- modules/openapi-generator/src/test/resources/2_0/issue_9086.yaml
- modules/openapi-generator/src/test/resources/2_0/issue_9086_expected.yaml
- pom.xml
A bug in the upstream schema parser was causing generation issues for swagger v2.0 #9086 
This PR updates the upstream version and adds a test for this issue
```
``` 
> bump swagger-parser-version to v2.0.26 to close #9086

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/FakeApi.ts
- samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
Fixes #9658 @amakhrov
This request will allow to configure APIs with async functions for access tokens.
```
``` 
> [typescript-fetch] Support for async accessToken

- modules/openapi-generator/src/main/resources/powershell/api_client.mustache
- samples/client/petstore/powershell/src/PSPetstore/Private/PSApiClient.ps1
Add null check on $ContentTypes when deserializing the response
To close https://github.com/OpenAPITools/openapi-generator/issues/8329
credits: @EngineerCoding 
```
``` 
> [PowerShell] add null check on $ContentTypes

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
Silence deprecated warning when used internally
```
``` 
> [kotlin][client] silence deprecation warning

- modules/openapi-generator/src/main/resources/cpp-ue4/api-header.mustache
- modules/openapi-generator/src/main/resources/cpp-ue4/api-source.mustache
This is better than returning a bool and allows the request to be canceled or inspected while in flight
```
``` 
@wing328
> [cpp-ue4] API calls not return the http request for further manipulation

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConstants.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/bugs/issue_9719.yaml
This PR adds the functionality I requested in #9719 
Add new configuration flags: REMOVE_OPERATION_ID_PREFIX_DELIMITER and REMOVE_OPERATION_ID_PREFIX_COUNT
Add the corresponding fields in the DefaultCodegen
Sanitize the operationId according to the new fields
Add delimiter to list of nonNameElementPattern
Add unit test for different cases (different delimiters and counts)
```
```  …
> operationId: Allow getting only the method name (#9719)

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
Same issue and fix as https://github.com/OpenAPITools/openapi-generator/pull/7976, but for the webclient generator. Issue I created: https://github.com/OpenAPITools/openapi-generator/issues/9543
```
``` 
> [Java][webclient] Filter out problem+json mime type from JSON mime types

- bin/configs/typescript-consolidated-deno.yaml
- bin/configs/typescript-consolidated-inversify.yaml
- bin/configs/typescript-consolidated-jquery.yaml
- bin/configs/typescript-consolidated-node-object-parameters.yaml
- bin/configs/typescript-consolidated-node.yaml
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript/api_doc.mustache
- samples/openapi3/client/petstore/typescript/builds/default/.openapi-generator/FILES
- samples/openapi3/client/petstore/typescript/builds/default/PetApi.md
- samples/openapi3/client/petstore/typescript/builds/default/StoreApi.md
- samples/openapi3/client/petstore/typescript/builds/default/UserApi.md
- samples/openapi3/client/petstore/typescript/builds/deno/.openapi-generator/FILES
- samples/openapi3/client/petstore/typescript/builds/deno/PetApi.md
- samples/openapi3/client/petstore/typescript/builds/deno/StoreApi.md
- samples/openapi3/client/petstore/typescript/builds/deno/UserApi.md
- samples/openapi3/client/petstore/typescript/builds/inversify/.openapi-generator/FILES
- samples/openapi3/client/petstore/typescript/builds/inversify/PetApi.md
- samples/openapi3/client/petstore/typescript/builds/inversify/StoreApi.md
- samples/openapi3/client/petstore/typescript/builds/inversify/UserApi.md
- samples/openapi3/client/petstore/typescript/builds/jquery/.openapi-generator/FILES
- samples/openapi3/client/petstore/typescript/builds/jquery/PetApi.md
- samples/openapi3/client/petstore/typescript/builds/jquery/StoreApi.md
- samples/openapi3/client/petstore/typescript/builds/jquery/UserApi.md
- samples/openapi3/client/petstore/typescript/builds/object_params/.openapi-generator/FILES
- samples/openapi3/client/petstore/typescript/builds/object_params/PetApi.md
- samples/openapi3/client/petstore/typescript/builds/object_params/StoreApi.md
- samples/openapi3/client/petstore/typescript/builds/object_params/UserApi.md
> [typescript] Generate documentation and examples

- README.md
The latest version of homebrew has changed usesage of  `cask`, as follows.
```bash
$ brew install --cask firefox
```
https://brew.sh/
```
``` 
> fix(readme): update brew cask usage

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
- modules/openapi-generator/src/main/resources/haskell-servant/API.mustache
`AnyType` would not be translated to the json value type.
This fixes that.
```
``` 
> [haskell][server]: Set "AnyType" to `Aeson.Value`

- modules/openapi-generator/src/main/resources/go-gin-server/routers.mustache
[go-gin-server] add PATCH method support.
```
``` 
> [go-gin-server] add PATCH method support 

- modules/openapi-generator/src/main/resources/go-server/model.mustache
This pull request is intended to fix an issue introduced with https://github.com/OpenAPITools/openapi-generator/pull/4934.
The line `supportsInheritance = true` has been included in the cosntructor of `AbstractGoCodegen`, which is also the parent class of the go server code generator. The pull request implements changes in the go client's and go deprecated's  `model.mustache`, but not in the go server, even if the change in `AbstractGoCodegen` affects also this generator.
This PR addresses this.
@wing328 possibly this should be included also in `5.1.x`.
> [goserver] Fix single inheritance code generation for goserver

- modules/openapi-generator/src/main/resources/cpp-pistache-server/api-header.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/api-source.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/model-header.mustache
- samples/server/petstore/cpp-pistache/api/PetApi.cpp
- samples/server/petstore/cpp-pistache/api/PetApi.h
- samples/server/petstore/cpp-pistache/api/StoreApi.cpp
- samples/server/petstore/cpp-pistache/api/StoreApi.h
- samples/server/petstore/cpp-pistache/api/UserApi.cpp
- samples/server/petstore/cpp-pistache/api/UserApi.h
- samples/server/petstore/cpp-pistache/model/ApiResponse.h
- samples/server/petstore/cpp-pistache/model/Category.h
- samples/server/petstore/cpp-pistache/model/Order.h
- samples/server/petstore/cpp-pistache/model/Pet.h
- samples/server/petstore/cpp-pistache/model/Tag.h
- samples/server/petstore/cpp-pistache/model/User.h
Here I am fixing bugs I myself have created.
The overload for the models `validate(std::stringstream&, const std::string&)` was marked as private, which lead to model classes being unable to use the helper when validating other classes. The function was made public, with a summary comment noting that it is not of much use for the user.
The defaultl implementation of `handleParsingException` handles exceptions based on their type. In order to check the type, the caught exception is rethrown in a `try` block. However, it is important to rethrow using `throw;` and not with `throw exVariable;`.
The latter does not preserve derived class information (See https://stackoverflow.com/questions/2360597/c-exceptions-questions-on-rethrow-of-original-exception). This lead to all runtime exceptions …
> [C++][Pistache] Fix compile break, error handling

- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/GlobalSettings.java
This PR fixes #7601 by working around https://github.com/gradle/gradle/issues/17344. It does not change generator output.
```
``` 
> Avoid using Properties.clone() which is broken in Gradle

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
- samples/client/petstore/rust/reqwest/petstore-async/README.md
- samples/client/petstore/rust/reqwest/petstore-async/docs/PetApi.md
- samples/client/petstore/rust/reqwest/petstore-async/docs/StoreApi.md
- samples/client/petstore/rust/reqwest/petstore-async/docs/UserApi.md
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/store_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/user_api.rs
- samples/client/petstore/rust/reqwest/petstore/README.md
- samples/client/petstore/rust/reqwest/petstore/docs/PetApi.md
- samples/client/petstore/rust/reqwest/petstore/docs/StoreApi.md
- samples/client/petstore/rust/reqwest/petstore/docs/UserApi.md
- samples/client/petstore/rust/reqwest/petstore/src/apis/pet_api.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/store_api.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/user_api.rs
```
``` 
fix: https://github.com/OpenAPITools/openapi-generator/issues/9743
> [rust-client]: fix reqwest not support client::options

- modules/openapi-generator/src/main/resources/Java/libraries/native/AbstractOpenApiSchema.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/JSON.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/anyof_model.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/oneof_model.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/pom.mustache
- samples/client/petstore/java/native-async/build.gradle
- samples/client/petstore/java/native-async/pom.xml
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- samples/client/petstore/java/native/build.gradle
- samples/client/petstore/java/native/pom.xml
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- samples/openapi3/client/petstore/java/native/build.gradle
- samples/openapi3/client/petstore/java/native/pom.xml
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/JSON.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/Fruit.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/FruitReq.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/GmFruit.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/Mammal.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/NullableShape.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/Pig.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/Quadrilateral.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/Shape.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/ShapeOrNull.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/model/Triangle.java
This removes the dependency on JAX-RS from the Java native client template by making the following changes:
1) Remove use of GenericType
This was originally introduced in #7263 by presumably copy pasting a piece of code for OneOf/AnyOf support from the Jersey client. It was using `GenericType` from JAX-RS, which seems unnecessary since it doesn't seem to generate generic type instantiations (the anyOf/oneOf deserializer will also use `{{.}}.class`, and not GenericType or similar type tokens).
2) Remove ContextResolver implementation
The `JSON` class implements the JAX-RS ContextResolver interface, which seems unnecessary for a native Java client in a non JAX-RS environment  (probably copy paste)
3) Removed the respective dependencies from build.gradle/pom.xml.
4) [OPTIONAL] Set source …
> [java][native] Remove JAX-RS dependency from generated java-native client.

- modules/openapi-generator/src/main/resources/python/api.mustache
- modules/openapi-generator/src/main/resources/python/api_client.mustache
- samples/client/petstore/python/petstore_api/api/another_fake_api.py
- samples/client/petstore/python/petstore_api/api/fake_api.py
- samples/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py
- samples/client/petstore/python/petstore_api/api/pet_api.py
- samples/client/petstore/python/petstore_api/api/store_api.py
- samples/client/petstore/python/petstore_api/api/user_api.py
- samples/client/petstore/python/petstore_api/api_client.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/another_fake_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/fake_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/fake_classname_tags_123_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/pet_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/store_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/user_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api_client.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/api/usage_api.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/api_client.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api/usage_api.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api_client.py
- samples/openapi3/client/petstore/python/petstore_api/api/another_fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/default_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/store_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
- samples/openapi3/client/petstore/python/petstore_api/api_client.py
While several method docstrings suggested that you could pass floats for _request_timeout and the underlying [urllib3.Timeout](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.Timeout) can deal with them, the code only allowed integer values so far when passed as a single number.
```py
>>> # everything alright
>>> api.my_endpoint(_request_timeout=2)
>>>
>>> api.my_endpoint(_request_timeout=1.2)
Traceback (most recent call last):
File "<console>", line 1, in <module>
File ".../client/api_client.py", line 763, in __call__
return self.callable(self, *args, **kwargs)
File ".../client/api/my_api.py", line 344, in __list_appliances
return self.call_with_http_info(**kwargs)
File ".../client/api_client.py", line 810, in call_with_http_info …
```
> [python][client] allow passing floats for _request_timeout

- .gitattributes
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/UserApi.java
```
``` 
For now we done it by overriding templates but as I have a bit of time and I found that there is already an issue about that, I propose this PR
fix: #5599
For review (java) :
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov …
> [Java][WebClient] add ResponseEntity return for webclient

- modules/openapi-generator/src/main/resources/erlang-server/logic_handler.mustache
- modules/openapi-generator/src/main/resources/erlang-server/server.mustache
dialyzer fixes for erlang-server
ping @tsloughter (2017/11) @jfacorro (2018/10) @robertoaloi (2018/10)
solves two dialyzer problems.
First one is this issue #6354 and the corresponding dialyzer output
```
X_server.erl
Line 54 Column 66: The call X_server:store_key('env', NewEnv::[any()], Opts::#{'env':=#{'dispatch':=cowboy_router:dispatch_rules()}}) will never return since it differs in the 3rd argument from the success typing arguments: (any(), any(), [tuple()])
Line 57 Column 65: The call X_server:store_key(Key::any(), Value::any(), Opts::#{'env':=#{'dispatch':=cowboy_router:dispatch_rules()}}) will never return since it differs in the 3rd argument from the success typing arguments: (any(), any(), [tuple()])
Line 66 Column 1: Function store_key/3 has no local return
Line 67 Column 28: …
```
> [erlang-server] minor bug fixes

- modules/openapi-generator/src/main/resources/erlang-server/handler.mustache
Similar to https://github.com/OpenAPITools/openapi-generator/pull/9512. This PR just adds 304 to the condition that should return an empty body to cowboy, as it has the same validation as 204: https://github.com/ninenines/cowboy/blob/2a082504996afccf78185182cd168123800bd4f0/src/cowboy_req.erl#L807-L824
@tsloughter (2017/11) @jfacorro (2018/10) @robertoaloi (2018/10)
```
```  …
> [Erlang] Return empty body for 304

- modules/openapi-generator/src/main/resources/go-server/routers.mustache
- samples/server/petstore/go-api-server/go/routers.go
- samples/server/petstore/go-chi-server/go/routers.go
According to the [documentation](https://openapi-generator.tech/docs/generators/go-server) the go-server generator should support an `addResponseHeaders` option but a template uses an `addResponseHeader` option in some places which this PR fixes.
Closes #9795
@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d
```
```  …
> [go-server] fix addResponseHeaders tpl option typo

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
```
``` 
@Ramanth @saigiridhar21
Fix #9821.
To validate, repeat the steps outlined in #9821. 
The StackOverflowError is fixed and instead of recursing infinitely deep, we stop generating example code after 10 levels.
> [R] Limit depth of example code generation in RClientCodegen

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
Verbs with no content returned are now shown as having return type of `()`. This makes `servant` to try to parse resulting object.
Thus replacement with `NoContent` type fixes the issue.
Fixes: #9829
@wing328 @jimschubert @burberius
> [BUG][Haskell]Fix returning NoContent

- modules/openapi-generator-gradle-plugin/README.adoc
Updated docs to reference latest gradle plugin version 5.1.1 with important support for gradle 7.
```
``` 
> Updated openapi-generator-gradle-plugin/README.adoc to latest plugin version

- CONTRIBUTING.md
- docs/contributing.md
The line break in the Contribution guidelines for the `generate-samples` statement added a space in the statement when copy & pasting it:
`./bin/generate-samples.sh . /bin/configs/python*`
This resulted in errors when executing for the `.` as well as `/bin/configs/python*`.
```
```  …
> Fixes line break Contribution guidelines code sample

- modules/openapi-generator/src/main/resources/python/model_utils.mustache
- samples/client/petstore/python/petstore_api/model_utils.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/model_utils.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/model_utils.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/model_utils.py
- samples/openapi3/client/petstore/python/petstore_api/model_utils.py
Very minor contribution but I noticed 1 typo in the docstring of @cached_property 
```
``` 
@arun-nalla @spacether
> Fix minor typo in @cached_property python docstring

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/TemplateManager.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractAdaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractApexCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGraphQLCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaJAXRSServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AsciidocDocumentationCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/BashClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestSdkClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestbedServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppTinyClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppTizenClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppUE4ClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java
EclipseJdt cleanup 'AddMissingOverrideAnnotation' applied by erefactor.
For EclipseJdt see https://www.eclipse.org/eclipse/news/4.20/jdt.php
--------
Dear Project Team!
This pull request is provided in the hope that it will be useful.
Changes are manually reviewed after they passed the test suite of
your project. Only successful reviews become project PRs.
Errors found are reported upstream to support the cleanup providers.
But please do a careful review of your own as usual because tools
have bugs and bugs in the changes may have been overlooked.
For scalability and out of fun and laziness, the creation of commits
and PRs and parts of the change handling are automated.
If you are not interested or want to discuss issues just comment …
> [cleanup] erefactor/EclipseJdt - Add missing @Override annotation - include interface implementations

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaHttpServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaPlayFrameworkServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/StaticHtml2Generator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift4Codegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/JsonCacheImpl.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/asciidoc/AsciidocGeneratorTest.java
Please note that the changes are technically as correct as the code was before but that
for example the log message in RustServerCodegen.java and other files is (and was)
printing wrong or incomplete information.
I don't have the time to fix this but the PR may be useful nevertheless.
Please note that this is the last PR that addresses LogParametersRatherThanLogMessage.
All log calls erefactor found are done with this PR.
I saw that a lot of test asserttions have wrong argument order. I plan to provide PRs for
that when I find some time.
Best regards,
Cal
AutoRefactor cleanup 'LogParametersRatherThanLogMessage' applied by erefactor:
Replaces a string concatenation as parameter of a logger method by a
string template followed by objects.
For AutoRefactor …
> [cleanup] erefactor/AutoRefactor - Log parameters rather than log message

- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/api/DefaultApi.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/openapi3/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
The template has two methods for creating API exceptions, and the enhancements from #9169 didn't make it to the async version.
- unify the signatures of the two methods (name, arguments)
- make sure the sync version is not generated with asyncNative
- extract the formatting logic into a common formatExceptionMessage() method
- add the status code to the exception message as well, not just the body
- shortened "call received non-success response" to a more concise "call failed with"
```
``` 
You may …
> [Java] [Native] Unify exception messages for async, add the status code

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ApiClient.cs
```
``` 
@mandrean @frankyjuang @shibayan @Blackclaws  @lucamazzanti
> [csharp][netcore]Fix cancellation token usage for async calls in csharp-netcore.

- modules/openapi-generator/src/main/resources/python/rest.mustache
- samples/client/petstore/python/petstore_api/rest.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/rest.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/rest.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/rest.py
- samples/openapi3/client/petstore/python/petstore_api/rest.py
This commit ensures that the Python generator no longer sets a default 
`Content-Type` of`application/json` for `GET`, `HEAD` and `DELETE` 
requests.
Fixes #9831
Related issues/PRs: #476, #1061, #5941, #6167
Having the `Content-Type` set for these requests was causing issues with
other tools which insist that GET, HEAD and DELETE requests do not have
a Content-Type (as per the OpenAPI 3 specification).
An example of the problem that this commit fixes is when using
[Prism][1] as a [validation proxy][2].
[Prism rejects any GET request that has a Content-Type][3].
Here is [an example of the problem manifesting itself][4].
To validate the fix in this commit:
1. Start with any OpenAPI3 spec e.g. the Petstore example at
https://editor.swagger.io/
2. Generate Python client code for the spec
3. …
> [BUG][PYTHON] Do not set Content-Type for GET, HEAD or DELETE requests

- modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/build.gradle
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
Initially when kotlin coroutines support was introduced in https://github.com/OpenAPITools/openapi-generator/pull/6362, there was no coroutines context defined, this PR fixes that.
```
``` 
@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah …
> [kotlin][client] define kotlin coroutines context

- modules/openapi-generator/src/main/resources/haskell-servant/API.mustache
For tests it’s useful to have direct access to the Wai `Application`,
which is the plain function from `Request` to `Response`.
Then you don’t need to use a full-blown http server to run requests.
```
``` 
> [haskell][server] Export the Wai Application for the server

- modules/openapi-generator/src/main/resources/elixir/mix.exs.mustache
- samples/client/petstore/elixir/mix.exs
Closes #9944 
Adds additional values to `mix.exs` to enable publishing generated packges to Hex.
```
``` 
> [Elixir] Adding :package and :description to mix.exs template

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
- samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/API.hs
- Remove redundant logic in adding ICollection in CSharpClientCodegen and CSharpNetCoreClientCodegen as these logics already present in the abstract C# codegen class.
- No change to the samples.
```
``` 
cc @mandrean (2017/08) @frankyjuang (2019/09) …
> [C#][netcore] Remove redundant logic in adding ICollection

- modules/openapi-generator/src/main/resources/erlang-server/handler.mustache
- modules/openapi-generator/src/main/resources/erlang-server/router.mustache
- samples/server/petstore/erlang-server/src/openapi_pet_handler.erl
- samples/server/petstore/erlang-server/src/openapi_router.erl
- samples/server/petstore/erlang-server/src/openapi_store_handler.erl
- samples/server/petstore/erlang-server/src/openapi_user_handler.erl
When using the the generated code with many paths we could sometimes end up using 50MB memory per request.
This is since the process will use the complete dispatch rule including one validator state per path. 
This removes that and instead we fetch the state after we found the match in cowboy.
This way we will only have seen one jesse ValidatorState
https://github.com/ninenines/cowboy/blob/master/src/cowboy_router.erl#L163
@tsloughter  @jfacorro @robertoaloi 
```
```  …
> [Erlang] decrease memory usage

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioNextClientCodegen.java
This PR closes #9955 by only removing the import for `dart:typed_data` if there are no parameters AND no responses of type `UInt8List`.
Previously only parameters were being checked, meaning invalid dart code would be generated if there was a `UInt8List` response, because the import would have been removed.
Have tested against the example I provided in the bug report, as well as our own codebase where the error was first identified.
Have run `./bin/generate-samples.sh`, but as the Petstore API does not have any file responses, there were no changes to the generated code.
@swipesight @jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob (2020/12)
```
``` 
This is …
> [dart-dio-next] only remove typed_data import if safe

- modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache
- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
- samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
- samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
When a file download is handled within URLSessionImplementations,
the filename is retrieved via the header _Content-Disposition_ part of the response.
The header is looked for an entry starting with _filename=_. 
But the search is skipped too early, since the loop is exited if the first iteration does not match.
Try to download a file with a swift5 client for a spec like this:
```
/PublicDocument/Download:
get:
tags:
- Public Area
description: 'Document Download for Public Documents. Login not Required'
parameters:
- $ref: '#/components/parameters/queryId'
responses:
'200':
description: 'OK'
content:
application/pdf:
schema:
type: string
format: binary
```
When downloading from a server, the response header could have an answer like so:
```
Content-Disposition: attachment; …
```
> [swift5 client] fix filename for binary downloads

- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
- modules/openapi-generator/src/main/resources/php/composer.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/php/AbstractPhpCodegenTest.java
- samples/client/petstore/php/OpenAPIClient-php/composer.json
I've added small method to AbstractPhpGenerator to validate Composer package name(against `^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$`).
PHP client `composer.json` template slightly changed. Now it contains package name only when it pass validation.
Closes #9998 
```
```  …
> [php] Fix Composer 2 name error

- modules/openapi-generator/src/main/resources/erlang-server/router.mustache
- samples/server/petstore/erlang-server/src/openapi_router.erl
Dialyzer fails with success typing after #9946 
`Line 29 Column 2: Invalid type specification for function .._handler:init/2. The success typing is ...`
@tsloughter @jfacorro @robertoaloi
```
``` 
> [erlang-server] Dialyzer spec

- modules/openapi-generator-maven-plugin/examples/kotlin.xml
- modules/openapi-generator/src/main/resources/kotlin-client/build.gradle.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-json-request-string/build.gradle
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-moshi-codegen/build.gradle
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nonpublic/build.gradle
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nullable/build.gradle
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-okhttp3/build.gradle
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-retrofit2-rx3/build.gradle
- samples/client/petstore/kotlin-retrofit2/build.gradle
- samples/client/petstore/kotlin-string/build.gradle
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-threetenbp/build.gradle
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-uppercase-enum/build.gradle
- samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin/build.gradle
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Added support for collecting lists of objects for Jackson, Gson, and Moshi. Support for Moshi added by @adamsz-lume, included in this PR, due to cherry picking, commits are unfortunately not by @adamsz-lume.
[[BUG][Kotlin] Generated clients cannot serialize into `List<T>`](https://github.com/OpenAPITools/openapi-generator/issues/8560)
```
```  …
> [BUG][Kotlin] Add support for collection of generic classes (Jackson / Gson / Moshi)

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/UserApi.java
URI Template attribute is used by spring-boot-actuator to put proper uri template tags in metrics in [WebClientExchangeTags.java](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/reactive/client/WebClientExchangeTags.java#L69)
E.g. when the attribute is set, the `uri ` metric tag will be `/pets/{petId}/children` instead of `/pets/666/children?gender=male&name=Tom` and will prevent flooding of monitoring systems with all path params/query params combinations.
The logic is the same as in DefaultWebClient's `uri()` method [implementation](https://github.com/spring-projects/spring-framework/blob/main/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/DefaultWeb …
> Store uri template attribute for webclient to store in metrics

- modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
- samples/client/petstore/spring-cloud-spring-pageable/src/main/java/org/openapitools/api/PetApi.java
- samples/server/petstore/spring-mvc-spring-pageable/src/main/java/org/openapitools/api/PetApi.java
- samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8/src/main/java/org/openapitools/api/PetApi.java
- samples/server/petstore/springboot-spring-pageable-delegatePattern/src/main/java/org/openapitools/api/PetApi.java
- samples/server/petstore/springboot-spring-pageable-without-j8/src/main/java/org/openapitools/api/PetApi.java
- samples/server/petstore/springboot-spring-pageable/src/main/java/org/openapitools/api/PetApi.java
Use fully qualified name for Pageable to avoid missing import error
```
``` 
cc @mwatel42, @billbarni @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog …
> [Spring] Use fully qualified name for Pageable

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache
- samples/client/petstore/kotlin-multiplatform/build.gradle.kts
This dependency was accidentally removed in PR #9755 where we switched
from `build.gradle` to `build.gradle.kts`.
Symptom of this dependency missing (not making this change):
```
12:28:25.021 [DefaultDispatcher-worker-6] ERROR Application - Unhandled: GET - <redacted>
java.lang.ExceptionInInitializerError: null
at com.dynatrace.teamsmanager.infrastructure.ApiClient$client$2.invoke(ApiClient.kt:38)
...
Caused by: java.lang.IllegalStateException: Failed to find HTTP client engine implementation in the classpath: consider adding client engine dependency. See https://ktor.io/clients/http-client/engines.html
at io.ktor.client.HttpClientJvmKt.<clinit>(HttpClientJvm.kt:42)
```
which contains a clear message hinting what's wrong.
----
``` …
```
> [Kotlin][Multiplatform] Add missing JVM dependency

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
Add AnyType support to Kotlin server.
```diff
@@ -11,7 +11,6 @@
*/
package org.openapitools.client.models
-import org.openapitools.client.models.AnyType
import com.squareup.moshi.Json
@@ -31,6 +30,6 @@ data class ApiResponse (
@Json(name = "message")
val message: kotlin.String? = null,
@Json(name = "any_test")
-    val anyTest: AnyType? = null
+    val anyTest: kotlin.Any? = null
)
```
To fix https://github.com/OpenAPITools/openapi-generator/issues/10036
```
```  …
> Add AnyType support to Kotlin generators

- modules/openapi-generator/src/main/resources/kotlin-spring/api_test.mustache
The default output will result in the following when running tests:
```
[INFO] Running org.openapitools.api.TestApiTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.openapitools.api.TestApiTest
[ERROR] org.openapitools.api.TestApiTest.testTest()  Time elapsed: 0.001 s  <<< FAILURE!
kotlin.KotlinNullPointerException
at org.openapitools.api.TestApiTest.testTest(TestApiTest.kt:25)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   org.openapitools.api.TestApiTest#testTest KotlinNullPointerException
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```
This [fix](https://github.com/OpenAPITools/openapi-generator/pull/10058/files#diff-e7f2ed728494af823c8be1952a27a79db580904855d436035b7046ccbdcd1e06R32) will make …
> Update kotlin-spring auto-generated test to avoid NPE

- modules/openapi-generator/src/main/resources/csharp-netcore/WebRequestPathBuilder.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/WebRequestPathBuilder.cs
To fix https://github.com/OpenAPITools/openapi-generator/issues/10018
Local test result is good:
```
/v2/pet/34?test_query=%3chello%26world%3e&test_query3=12
```
as `<hello&world>` is encoded correctly above.
```
``` 
> [C#][netcore] fix path and query parameters encoding

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
This is a follow-up of PR https://github.com/OpenAPITools/openapi-generator/pull/10034.
This PR will free the variable with the data type "byteArray" same as "string" in the function `*_free()` .
Hi @zhemant @wing328 @michelealbano
Could you please review this PR ? Thanks.
```
```  …
> [C][Client] Free the variable with the data type "byteArray" same as "string"

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/RetryingOAuth.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/pom.xml
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/auth/RetryingOAuth.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/pom.xml
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/auth/RetryingOAuth.java
- samples/client/petstore/java/okhttp-gson/.openapi-generator-ignore
- samples/client/petstore/java/okhttp-gson/pom.xml
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/auth/RetryingOAuth.java
- samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/auth/RetryingOAuthTest.java
If there were multiple concurrent requests at a time at which the OAuth token had expired, only a single request would be retried. The other requests would fail because of the expired token, but not be retried and so the failures would be propagated to the caller.
```
```  …
> [BUG]Java] Fix a race condition in RetryingOAuth.mustache

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioNextClientCodegen.java
- modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/serialize.mustache
- modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/serializers.mustache
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/serializers.dart
* fix parameter with list of `MultipartFile` being generated as single `MultipartFile`
* generate serializer factories for all container params, not only body params
* fix compilation errors when `skipFormModel=false`   
* fixes #10032
* fixes #10031
* fixes #9968
We have nothing in the samples for these things so we need some people to test this.
@ahmednfwela maybe you can try?
```
```  …
> [dart-dio] Fix parameter generation problems

- modules/openapi-generator/src/main/resources/php-laravel/api.mustache
- modules/openapi-generator/src/main/resources/php-laravel/model.mustache
- modules/openapi-generator/src/main/resources/php-lumen/api.mustache
- modules/openapi-generator/src/main/resources/php-mezzio-ph/api.mustache
- modules/openapi-generator/src/main/resources/php-slim-server/api.mustache
- modules/openapi-generator/src/main/resources/php-slim-server/model.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/api.mustache
- modules/openapi-generator/src/main/resources/php-symfony/api.mustache
- modules/openapi-generator/src/main/resources/php-symfony/api_controller.mustache
- modules/openapi-generator/src/main/resources/php/api.mustache
- modules/openapi-generator/src/main/resources/php/model_generic.mustache
- modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
- samples/client/petstore/java/feign/api/openapi.yaml
- samples/client/petstore/java/webclient/api/openapi.yaml
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/ObjectWithDeprecatedFields.php
- samples/server/petstore/php-laravel/lib/app/Http/Controllers/PetController.php
- samples/server/petstore/php-laravel/lib/app/Models/ObjectWithDeprecatedFields.php
- samples/server/petstore/php-lumen/lib/app/Http/Controllers/PetApi.php
- samples/server/petstore/php-mezzio-ph/src/App/Handler/PetFindByTags.php
- samples/server/petstore/php-slim4/lib/Api/AbstractPetApi.php
- samples/server/petstore/php-symfony/SymfonyBundle-php/Api/PetApiInterface.php
- samples/server/petstore/php-symfony/SymfonyBundle-php/Api/StoreApiInterface.php
- samples/server/petstore/php-symfony/SymfonyBundle-php/Api/UserApiInterface.php
- samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/PetController.php
Apply the `@deprecated` annotation to deprecated functions and properties.
@jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @ybelenko, @renepardon
```
```
> [php] Deprecated annotation on operations and fields

- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake_tests/test/api_util_test.dart
Added tests for enum encoding in query parameters.
Fixes #9905
Fixes #9854
@tfbsza @bmxbandita I have added new tests for encoding enum values in query parameters but I can't find anything fundamentally wrong with it. The tests succeed and seem to encode the correct values.
```
```  …
> Add tests for enum query encoding

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
`window` should not be used in typescript-fetch because `window` does not exist under node js environment.
According to https://github.com/OpenAPITools/openapi-generator/pull/3326, `fetch` is globally defined in both browser and nodejs.
So we just need to simply use `fetch`.
Also I found out why the `fetch` function need to bind `window` again in the old code.
Because when the `fetch` function passed by the `fetchApi` getter, the `fetch` function will lose its context(window) and cause an error 'Fetch TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation'.
So, **DO NOT** pass the `fetch` function by the `fetchApi` getter, call `fetch` directly wherever it needs to be executed.
```
``` …
> make typescript-fetch code compatiable with nodejs environment

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptInversifyClientCodegen.java
```
``` 
Pinging TypeScript technical committee members: @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov
Resolves the same issue for ts-inversify that was fixed in #8105, #8376 for ts-axios and …
> [BUG][typescript-inversify] Sets `isCollectionFormatMulti` flag to true on multi-file uploads

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/UserApi.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/apis/PetApi.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/apis/PetPartApi.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/apis/UserApi.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/apis/index.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/index.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/models/index.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/package-lock.json
Refs #10050
This is a follow up PR for #10050 to fix incorrect arguments names.
I've removed `{{^-last}}, {{/-last}}` and replaced it with `,` as there will always be another argument (the initOverrides argument). 
I've done a global search for `, ,` and can't find this issue anywhere so i think this fix is good.
Note after generating the samples i see the following files have changed but I have not commited them:
```console
modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Api/PetApi.cs
modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/PetApi.cs
modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Api/PetApi.cs
modified: …
```
> [typescript-fetch] Fix double comma arguments due to initOverrides

- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
```
``` 
@paladinzh there is a typo in rust-client template that make generated client library which have nullable text field unable to compile (with reqwest)
> [rust-client] Fix typo

- docs/customization.md
This PR is so simple that I don't know what more details I could possibly give here.
> [documentation] Fix typo (preffer → prefer)

- docs/generators/php-laravel.md
- docs/generators/php-lumen.md
- docs/generators/php-mezzio-ph.md
- docs/generators/php-slim-deprecated.md
- docs/generators/php-slim4.md
- docs/generators/php.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/php/AbstractPhpCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_8945.yaml
- samples/client/petstore/php/OpenAPIClient-php/docs/Model/AdditionalPropertiesClass.md
- samples/client/petstore/php/OpenAPIClient-php/docs/Model/ArrayOfArrayOfNumberOnly.md
- samples/client/petstore/php/OpenAPIClient-php/docs/Model/ArrayTest.md
- samples/client/petstore/php/OpenAPIClient-php/docs/Model/MapTest.md
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
Fixes a bug where code generation would sometimes treat arrays as objects and break serialization and code documentation.
Fixes #8945 
```
``` 
> Make php's array primitive

- modules/openapi-generator/src/main/resources/dart2/api_client.mustache
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api_client.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api_client.dart
- samples/openapi3/client/petstore/dart2/petstore_json_serializable_client_lib_fake/lib/api_client.dart
This change updates the generated `ApiClient` to include the request body on DELETE calls. [Per the RFC on page 2](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.5), DELETE calls are allowed to have a request body, even though the behavior may be undefined. I've not come across many APIs that use this behavior but there are a few, in particular the [Ory Kratos API](https://www.ory.sh/kratos/docs/reference/api/#operation/submitSelfServiceLogoutFlowWithoutBrowser) does so, not forwarding the body prevents such an API from being used. An API method that does not define a request body should continue to function as expected as the body would be null in that scenario.
```
```  …
> [dart2] Include request body on DELETE call

- modules/openapi-generator/src/main/resources/typescript-angular/apis.mustache
Fixes https://github.com/OpenAPITools/openapi-generator/issues/10120
Added missing semi colon to interface export in api.ts template file (typescript-angular).
```
``` 
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir …
> Typescript-angular: Added missing semi colon to interface file

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
If the type of element of an array is number, e.g. 
```yaml
"supplementalGroups": {
"description": "A list of groups applied to the first process run in each container, in addition to the container's primary GID.  If unspecified, no groups will be added to any container.",
"items": {
"format": "int64",
"type": "integer"
},
"type": "array"
},
```
The current template code of CLibcurl will not allocate memory for the element before adding it to a list:
```c
list_addElement(supplemental_groupsList , &supplemental_groups_local->valuedouble);
```
`supplemental_groups_local` is a local variable, it will be released soon. And then the pointer pointing to `supplemental_groups_local->valuedouble` will be invalid.
This PR allocates memory for the element:
```c
double …
```
> [C][Client] Allocate memory for the element of array when the type is number

- modules/openapi-generator/src/main/resources/csharp-netcore/HttpSigningConfiguration.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/HttpSigningConfiguration.cs
Fixed the utc time issue which leads to expired httpSignature. 
```
``` 
@wing328
> [csharp-netcore]Fixed the utc time issue for httpSigning auth.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
- modules/openapi-generator/src/main/resources/cpp-pistache-server/api-source.mustache
- samples/server/petstore/cpp-pistache/api/PetApi.cpp
- samples/server/petstore/cpp-pistache/api/StoreApi.cpp
- samples/server/petstore/cpp-pistache/api/UserApi.cpp
fix OpenAPITools#10134
fix OpenAPITools#10135
```
``` 
@ravinikam @stkrwork @etherealjoy @MartinDelille @muttleyxd
> [cpp-pistache-server] Fix missing semicolon in template and missing code to set default values of model schema

- modules/openapi-generator/src/main/resources/python-flask/util.mustache
- samples/server/petstore/python-flask/openapi_server/util.py
As "deserialize_date" and "deserialize_datetime" are used outside of "deserialize_model", we should check 'None' value before parsing string.
```
``` 
1. Generate a server : (Yaml file below)
`java -jar …
> [python-flask] Fix NoneType when deserialize optional date (See #5813)

- modules/openapi-generator/src/main/resources/dart/libraries/dio/api.mustache
- modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/serialize.mustache
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/api/fake_api.dart
* respect the nullable flag for all parameters (except path params where this is not allowed)
* generate default values for header and query parameters that are not collections
* we can not handle default values for collection with built_value atm. (not const)
* we can not handle default values for form/body parameters atm. as those can be enums which we can not construct easily
```
```  …
> [dart][dio] Nullable parameters & defaults for header/query parameters

- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- modules/openapi-generator-maven-plugin/src/test/java/org/openapitools/codegen/plugin/CodeGenMojoTest.java
- modules/openapi-generator-maven-plugin/src/test/resources/classpath/pom.xml
- modules/openapi-generator-maven-plugin/src/test/resources/petstore-on-classpath.yaml
The `skipIfSpecIsUnchanged` configuration setting to the maven plugin did not work when the input spec came from a classpath resource, which could lead to infinite build loops when the plugin was used in eclipse.
Fix #5805
The `CodeGenMojo` appears to have already had support for creating hashes of input specs from different locations, but an incorrect `if` check was preventing these non-filesystem locations having hashes created. 
Two additional test methods have been added to test that a spec from the classpath can respect the `skipIfSpecIsUnchanged` setting. 
```
```  …
> Fix issue where skipIfSpecIsUnchanged was ignored when using a classpath input spec

- docs/generators/groovy.md
- docs/generators/java-inflector.md
- docs/generators/java-micronaut-client.md
- docs/generators/java-msf4j.md
- docs/generators/java-pkmst.md
- docs/generators/java-play-framework.md
- docs/generators/java-undertow-server.md
- docs/generators/java-vertx-web.md
- docs/generators/java-vertx.md
- docs/generators/java.md
- docs/generators/jaxrs-cxf-cdi.md
- docs/generators/jaxrs-cxf-client.md
- docs/generators/jaxrs-cxf-extended.md
- docs/generators/jaxrs-cxf.md
- docs/generators/jaxrs-jersey.md
- docs/generators/jaxrs-resteasy-eap.md
- docs/generators/jaxrs-resteasy.md
- docs/generators/jaxrs-spec.md
- docs/generators/spring.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
Split by ';' and/or newline
Trim value
fix: #7032
> [Java] refactor: improve additionalModelTypeAnnotations generation

- modules/openapi-generator/src/main/resources/dart/libraries/dio/api.mustache
Fixes a bug introduced in #10147
```
``` 
CC: @jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob
> [dart][dio] Parameter with default value must not be required

- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api_test.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/api_test.mustache
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/microprofile-rest-client/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
In case of array properties declared with uniqueItems: true, the
generated Java code uses Sets but imports are not present for them in
the Api and Test classes.
Maybe this can be considered for a bugfix release also for older releases?
CC @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch
```
```  …
> [Java] Add missing imports for Set in java clients

- docs/generators/markdown.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/MarkdownDocumentationCodegen.java
- modules/openapi-generator/src/main/resources/markdown-documentation/README.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/markdown/MarkdownSampleGeneratorTest.java
- modules/openapi-generator/src/test/resources/3_0/markdown/expected/Models/Object.md
- modules/openapi-generator/src/test/resources/3_0/markdown/expected/Models/Object_InlinedObject.md
- modules/openapi-generator/src/test/resources/3_0/markdown/expected/Models/ReferencedObject.md
- modules/openapi-generator/src/test/resources/3_0/markdown/expected/Models/String.md
- modules/openapi-generator/src/test/resources/3_0/markdown/expected/README.md
- modules/openapi-generator/src/test/resources/3_0/markdown/issue_6096.yaml
Adds primitive types to the Markdown generator to resolve #5449, which also resolves #6096. Adds a new OpenAPI spec (`issue_6096.yaml`) with many primitive types and tests that show that the primitive types are no longer linked to in the generated Markdown.
```
```  …
> [markdown] Add primitive types to Markdown generator (#5449)

- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/server/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/server/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/libraries/jersey1/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/eap/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/helidon/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/kumuluzee/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/openliberty/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/quarkus/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/libraries/thorntail/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pom.mustache
Fix #8890 (only part 2 of the issue)
- At first glance : I apply the change only in Jaxrs-Jersey pom.mustache template
- After a closer look : I apply the change to every JaxRS pom.mustache templates
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet  @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch
> Fix #8890 (part 2) in every JaxRS pom.mustache templates

- modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
Prior to this change, clients generated with asyncNative=true
could not intercept the responses using the existing repsonse
interceptor. This adds another response interceptor solely for
asyncNative=true clients.
Integration tests pass for both java/native and native-async.
```
```  …
> [Java][Native] Add an async response interceptor in ApiClient

- modules/openapi-generator/src/main/resources/cpp-ue4/api-operations-source.mustache
Issue 10175 describes a potential bug and potential remedy.  This pull request is the basic fix I referenced in the issue.
https://github.com/OpenAPITools/openapi-generator/issues/10175
Simply put:  if there is no body parameter defined, it tries to generate a json body from formParams.  If a formParam isn't required, it uses IsSet from TOptional<> before writing the parameter.
See the referenced issue for the example schema that seems to require this template fix.
To be clear, this isn't really tested against a wide array of OpenAPI schemas.  And there are further issues with the generator.  But as a first pass, this at least gets a standard Django api-token-auth to be accepted by a Django server, and doesn't ruin other end points in my sample schema.
tagging @Kahncode as requested.
I'd …
> [cpp-ue4] fix for generating formParams in json requests

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java
Resolves https://github.com/OpenAPITools/openapi-generator/issues/10190
Adds a mapping for `AnyType` to ruby's `Object`.
Basically the same as https://github.com/OpenAPITools/openapi-generator/pull/10070 but for ruby.
```
``` 
@cliffano @zlx @autopp
> AnyType support for ruby generator

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
This change fixes a bug introduced in https://github.com/OpenAPITools/openapi-generator/pull/10072
Here's the type error:
With this change the return type now matches the config fetchApi type. 
It would be great to get this bugfix released asap.
```
``` 
> [typescript-fetch] Fix config getter type issue

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellHttpClientCodegen.java
While the fix in #9916 correctly made endpoint types which did not produce content return the `NoContent` type, those endpoint still generated `Produces` instances with the wrong mime types due to not resetting the `hasProduces` variable. This corrects that fix so that the `Produces` instance for `MimeNoContent` is generated instead of any other instance.
```
```  …
> [Haskell-http-client] Correct fix of no-content endpoints

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/feign/auth/ApiErrorDecoder.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/feign/auth/OAuth.mustache
- samples/client/petstore/java/feign-no-nullable/.openapi-generator/FILES
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/auth/ApiErrorDecoder.java
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/auth/OAuth.java
- samples/client/petstore/java/feign/.openapi-generator/FILES
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/auth/ApiErrorDecoder.java
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/auth/OAuth.java
- samples/client/petstore/java/feign/src/test/java/org/openapitools/client/api/ApiKeyAuthTest.java
- samples/client/petstore/java/feign/src/test/java/org/openapitools/client/api/HttpBasicAuthTest.java
- samples/client/petstore/java/feign/src/test/java/org/openapitools/client/api/HttpBearerAuthTest.java
- samples/client/petstore/java/feign/src/test/java/org/openapitools/client/api/OauthClientCredentialsGrantTest.java
- samples/client/petstore/java/feign/src/test/java/org/openapitools/client/api/OauthPasswordGrantTest.java
- samples/client/petstore/java/feign/src/test/java/org/openapitools/client/api/OauthRetryAuthErrorsTest.java
- samples/client/petstore/java/feign/src/test/java/org/openapitools/client/auth/ApiErrorDecoderTest.java
Hello
This PR adds the capability of automatically retry the requests that fail due to a 401 or 403. Sometimes these errors indicate that the token has expired.
This may happen if we have a valid token in memory, but it expires before the request is sent. After reaching the server the request will fail either with a 401 or 403.
For this case the Feign client will renew the token and retry to send the request one more time. If it fails on the second attempt it thrown an exception as before.
```
```  …
> [JAVA][FEIGN] Automatically retry request that fail due to a 401 or 403

- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pom.mustache
- samples/client/petstore/java/microprofile-rest-client/pom.xml
Quarkus, as one potential target for using the Java microprofile client
generator, requires a Jandex index to be present in library jars for
discovering beans inside these jars. Therefore, include Jandex index
generation in the pom.xml for microprofile clients as explained here:
https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index
Generating and shipping the index is only a small overhead that is
probably not worth an additional client option.
Considering a backport to 5.2 or 5.1 would be great.
CC @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch
```
```  …
> [Java] Add a Jandex index to microprofile client packages

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Add oneOfProps, allOfProps, anyOfProps to Codegen model instead of using vendor extensions. 
A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/9977
```
``` 
> Add oneOfProps, allOfProps, anyOfProps to Codegen model

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient-nulable-arrays/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
Update restttemplate and webclient templates to use <>-operator.
Also update samples.
```
``` 
> Fix unchecked conversion

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/resources/go/api.mustache
- modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
- samples/openapi3/client/petstore/go/go-petstore/api/openapi.yaml
- samples/openapi3/client/petstore/go/go-petstore/api_default.go
This PR adds support for response ranges in Go clients, as defined in [section 4.8.16.2](https://spec.openapis.org/oas/latest.html#patterned-fields-0) of the spec.
This includes a simple response sorting change in `DefaultCodegen.java` (originally introduced by @thiagoarrais) that should make this feature easier to support in all languages.
```
```
> [go] Support for response status code ranges

- modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache
I forgot to add the extension to the optional scripts in my previous PR.
```
``` 
@zhemant  @ityuhui  @michelealbano
> Fix names of pre- and post- scripts for building libcurl

- modules/openapi-generator/src/main/resources/typescript/api/api.mustache
- samples/openapi3/client/petstore/typescript/builds/default/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/deno/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/apis/PetApi.ts
fixes a regression introduced by https://github.com/OpenAPITools/openapi-generator/pull/9960
```
``` 
> [typescript] fix compilation error for file upload

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
If no version number is provided as property then it will try identify the version number automatically from the OpenAPI specification. If no version exist there either then it will still fallback to "1.0.0". This code is taken [from the typescript generator](https://github.com/OpenAPITools/openapi-generator/blob/5.2.x/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java#L279), is very short and is severely tested. This mirrors behavior in e.g. typescript.
@frol @farcaller @richardwhiuk @paladinzh
> [Rust][Client] Default version to spec version if not provided as property

- modules/openapi-generator/src/main/resources/typescript-axios/tsconfig.mustache
- samples/client/petstore/typescript-axios/builds/es6-target/tsconfig.json
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/tsconfig.json
- samples/client/petstore/typescript-axios/builds/with-npm-version/tsconfig.json
- samples/client/petstore/typescript-axios/tests/default/tsconfig.json
When using ES6 in the generator, the generated sources are indeed ES6. However, when building the package (and publishing to npm or other registries, as that's done automatically), TypeScript compiler builds a commonJS version of the code, which goes against the desire of the user's desire to build ES6.
```
``` 
For Windows users, please …
> [typescript-axios] Properly emit module as ES6 instead of commonJS when using ES6

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/php/AbstractPhpCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/php/issue_10244.yaml
Fix https://github.com/OpenAPITools/openapi-generator/issues/10244
I manually tested the output of generation but was'nt able to validate it against the petstore sample. I did not find any enum with a default value used as a model property in the petstore.
generate-samples.sh and export_docs_generators.sh did not produce any code diff.
> Fix php enum default value initialization

- modules/openapi-generator/src/main/resources/JavaSpring/apiUtil.mustache
- modules/openapi-generator/src/main/resources/JavaSpring/methodBody.mustache
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/AnotherFakeApiDelegate.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/ApiUtil.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/FakeApiDelegate.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/FakeClassnameTestApiDelegate.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/PetApiDelegate.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/StoreApiDelegate.java
- samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/UserApiDelegate.java
Previously the default responses in a reactive spring project were sent without a `Content-Type` header, so added the header to the default utility.
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet …
> [Java] Return content type on default spring reactive responses

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient-nulable-arrays/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
Fix `generateQueryUri` method param `queryParams` mistype as  `queryParam` in the comments. Previously IDE will have a "Cannot resolve symbol 'queryParam'" notification and red line on the typo.
```
``` 
> [Java][RestTemplate][WebClient] Fix typo in comments

- modules/openapi-generator/src/main/resources/typescript-axios/tsconfig.mustache
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/tsconfig.json
- samples/client/petstore/typescript-axios/builds/with-npm-version/tsconfig.json
- samples/client/petstore/typescript-axios/tests/default/tsconfig.json
Fixes failing tests in #10308 by fixing a mistake from myself according to [TypeScript docs](https://www.typescriptlang.org/tsconfig#module)
```
``` 
> [typescript-axios] Use CommonJS when using ES5 as target as per Typescript docs

- modules/openapi-generator/src/main/resources/r/git_push.sh.mustache
- samples/client/petstore/R/git_push.sh
To test:
```sh
openapi-generator generate --config bin/configs/r-client.yaml
```
To validate fix:
```sh
✗ which shellcheck
/usr/local/bin/shellcheck
✗ shellcheck samples/client/petstore/R/git_push.sh
```
https://github.com/OpenAPITools/openapi-generator/issues/10343
```
```  …
> [R] Fix shellcheck violations in git_push.sh.template

- modules/openapi-generator/src/main/resources/elm/fieldDecoder.mustache
- modules/openapi-generator/src/main/resources/elm/fieldEncoder.mustache
Elm code generator produces invalid elm code if there are enums in the OpenAPI specification. As described in #8343 the problem is the missing encoder/decoder for the enum field in the encoder/decoder of the structure. With this patch the encoders/decoders are added as required.
@eriktim 
```
``` 
For Windows users, please run the script …
> [elm] fix for invalid code being generated for enums

- modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt-client/api-header.mustache
- samples/client/petstore/cpp-qt/client/PFXPetApi.cpp
- samples/client/petstore/cpp-qt/client/PFXPetApi.h
- samples/client/petstore/cpp-qt/client/PFXStoreApi.cpp
- samples/client/petstore/cpp-qt/client/PFXStoreApi.h
- samples/client/petstore/cpp-qt/client/PFXUserApi.cpp
- samples/client/petstore/cpp-qt/client/PFXUserApi.h
Here is a list of improvement to fix most of the cppcheck and clazy warning by a generated code:
- Remove unsused variable
- Don't create temporary item when iterating
- Pass QString parameter by const reference
- Pass a context object as 3rd connect parameter (https://github.com/KDE/clazy/blob/master/docs/checks/README-connect-3arg-lambda.md)
The second commit improve the coding style.
```
```  …
> cpp-qt-client: Fix cppcheck warnings

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Show an error instead of NPE when schema is not defined in oneOf/anyOf
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Problem'.Please make sure that your schema is correct!
at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:499)
at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:899)
at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
at org.openapitools.codegen.DefaultCodegen.getOneOfAnyOfDescendants(DefaultCodegen.java:3019)
at …
```
> Show an error instead of NPE when schema is not defined

- modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache
- modules/openapi-generator/src/main/resources/htmlDocs2/sample_curl.mustache
Addressed the issue in #9384 where query strings in curl examples were not displaying their example values.
I also refactored the code out so that the curl example into its own mustache file, and provided the request body examples as well.
```
./mvn clean package 
``` 
> Updated the HTML2 Doc Curl Examples to provide sample Request Body & Query Param examples.

- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pojo.mustache
For setters the Jackson based property name conversion  (e. g.  from _-separated to CamelCase) is missing. So I propose this.
```
``` 
> Update pojo.mustache for property name conversion

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
Make  method updateParamsForAuth protected (not private) for java webclient
rationale: so that it can be overridden
the equivalent method in RestTemplate is currently also protected
protected void updateParamsForAuth(String[] authNames, MultiValueMap<String, String> queryParams, HttpHeaders headerParams, MultiValueMap<String, String> cookieParams)
> make  method updateParamsForAuth protected for java webclient

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
- samples/openapi3/client/petstore/go/go-petstore/docs/NullableClass.md
- samples/openapi3/client/petstore/go/go-petstore/model_nullable_class.go
If an item in a go array is nullable, we want to represent it as a pointer,
otherwise it will be deserialized with a default value and it will be
impossible to differentiate it from null.
```
``` 
> Handle nullable items in Go arrays

- .circleci/config.yml
- CI/circle_parallel.sh
- pom.xml
Move `python` client tests to CircleCI due to low credits in other CI.
cc @spacether 
```
``` 
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) …
> Test Python clients in CircleCI

- modules/openapi-generator/src/main/resources/python/model_templates/methods_shared.mustache
- modules/openapi-generator/src/main/resources/python/model_utils.mustache
- samples/client/petstore/python/petstore_api/model_utils.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/model_utils.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/model_utils.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/model_utils.py
- samples/openapi3/client/petstore/python/petstore_api/model_utils.py
- samples/openapi3/client/petstore/python/tests_manual/test_copy.py
- addresses issue #9669
- Add __deepcopy__ and __copy__ to OpenApiModel
- pass discriminator inside deepcopy if exists
- add test cases for deepcopy of models
```
``` 
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) …
> fix: handle deepcopy of openapi objects

- modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache
- samples/client/petstore/cpp-qt/client/PFXPetApi.cpp
- samples/client/petstore/cpp-qt/client/PFXStoreApi.cpp
- samples/client/petstore/cpp-qt/client/PFXUserApi.cpp
Fix issue raised here: https://github.com/OpenAPITools/openapi-generator/pull/10322#issuecomment-915677613
```
``` 
> cpp-qt-client: Fix CI

- .gitignore
- modules/openapi-generator/src/main/resources/cpp-qt-client/ServerConfiguration.mustache
- modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache
- samples/client/petstore/cpp-qt/.gitignore
- samples/client/petstore/cpp-qt/PetStore/PetStore.pro
- samples/client/petstore/cpp-qt/client/PFXPetApi.cpp
- samples/client/petstore/cpp-qt/client/PFXServerConfiguration.h
- samples/client/petstore/cpp-qt/client/PFXStoreApi.cpp
- samples/client/petstore/cpp-qt/client/PFXUserApi.cpp
> Fix ci again

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Currently the okhttp requests don't support empty body, this PR fixes that.
```
``` 
> [kotlin][client] add support for okhttp requests with empty body

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
Fixes the following warning
`The corresponding parameter in the supertype 'Callback' is named 'call'. This may cause problems when calling this function with named arguments.`
```
``` 
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) …
> [kotlin][client] fix warning in coroutines implementation

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/scala/SttpCodegenTest.java
This PR fixes the compilation error for a property which is defined as `format = byte` and `type = string`. 
- Fixed by typeMapping ByteArray -> Array([Byte])
- Test case added.
- Fixed [issue #10150](https://github.com/OpenAPITools/openapi-generator/issues/10150)
```
```  …
> [scala-sttp] Fix Compilation failure - not found type ByteArray

- modules/openapi-generator/src/main/resources/typescript-axios/package.mustache
- samples/client/petstore/typescript-axios/builds/es6-target/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version/package.json
This is to fix a security vuln in 0.21.1, and to stop GitHub dependency check from complaining. 🙂 
```
``` 
@nicokoenig
>  [typescript-axios] Upgrade axios from 0.21.1 to 0.21.4

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
This PR fixes the issue [#8827](https://github.com/OpenAPITools/openapi-generator/issues/8827)
Here is the openapi spec that can be used to reproduce the issue and verify the fix. This spec includes the both inline and stand-alone Enum schemas. 
```yaml
openapi: 3.0.3
info:
title: standalone or inline enums
version: '1.0'
paths:
/state:
get:
operationId: getUsers
responses:
'200':
description: get Users
content:
schema:
$ref: '#/components/schemas/Users'
components:
schemas:
Users:
properties:
emails:
items:
type: string
type: array
search:
enum:
- email
- full_name
type: string
standAloneEnum:
$ref: '#/components/schemas/StandAloneEnum'
StandAloneEnum:
enum:
- first_name
- last_name
- email
type: string
```
``` …
```
> [scala-sttp] Fix enum is not imported correctly

- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/store_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/user_api.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/pet_api.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/store_api.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/user_api.rs
- Tracking issue: #10421
The Rust reqwest client code breaks due to a variable name conflict when the model has a parameter named `configuration`.
This happens with several [twilio-oai](https://github.com/twilio/twilio-oai) specs.
This PR works around it by adding a local `local_var` prefix to `configuration` and referencing that (similar to the other local variables), which solves the issue when using `useSingleRequestParameter`, at least.
```
```  …
> fix(rust,client): use local_var prefix for configuration

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
This corrects the `"{} (reserved word) cannot be used as model name. Renamed to {}"` logging message to refer to right names before and after the rename.
```
``` 
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)
> fix(rust,server): fix reserved word model rename log message

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
> [core][general] added opportunity to configure names of metadata files

- CI/.drone.yml
Docs: https://docs.drone.io/pipeline/configuration/#multiple-pipelines
This should reduce the Drone CI build time substantially: instead of testing all the languages sequentially, the build should only take as long as the language with the longest test time. (Currently, that's java11-test, which takes less than half the time of the sequential total.)
```
```  …
> ci(drone): use parallel pipelines

- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
- Tracking issue: #10421
The Rust reqwest client's form handling fails to call `to_string` on array params, which fails to compile for arrays of values other than `String`.
This adds the missing `to_string` calls (similar to what's done with `queryParams` earlier in the function).
```
```  …
> fix(rust,client): convert form isArray values to string

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue8352.yaml
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient-nulable-arrays/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
> Fix issue 8352: [Java][RestTemplate][WebClient] Incorrect handling of free form query parameters 

- modules/openapi-generator/src/main/resources/go/model_anyof.mustache
> [go]: fix anyOf compilation error

- modules/openapi-generator/src/main/resources/go/client.mustache
- samples/client/petstore/go/go-petstore/client.go
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go
- samples/openapi3/client/petstore/go/go-petstore/client.go
https://github.com/OpenAPITools/openapi-generator/issues/10340
When API returns mixed content - 200 returns File/Binary and 500 returns JSON which is typical for error handling.
Generated code will include two accept headers. Problem is that selectHeaderAccept function that builds headers always forces accept headers to be JSON. This will crash as the server only knows how to return zip content type.
Example:
https://github.com/redhat-developer/app-services-sdk-go/blob/main/registryinstance/apiv1internal/client/api_admin.go#L1004-L1007
Request is mixed with zip and json on 500:
```
],
"responses": {
"200": {
"content": {
"application/zip": {
"schema": {
"$ref": "#/components/schemas/FileContent"
}
}
},
"description": "Response when the export is successful."
},
"500": {
"$ref": …
```
> Accept header forces application/json type even if server 

- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
The openapi-gradle generator plugin has a strict check on the `engine` param to only set the parameter if `handlebars` is set as value. Otherwise the parameter is ignored. This is currently blocking anyone from specifiying custom template engines (https://openapi-generator.tech/docs/templating/#custom-engines) when using the official gradle plugin.
This change will set the `engine` param to the user-provided value, even if it's not `handlebars`.
The engine param was initially added in: https://github.com/OpenAPITools/openapi-generator/pull/5686
```
``` 
These …
> [gradle]: allow setting custom engines other than handlebars

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/WsdlSchemaCodegen.java
- string comparison bug fix
- minor format change
cc @adessoDpd
```
``` 
> [wsdl] string comparison bug fix, minor format change

- CI/.drone.yml
Drone requires unique pipeline names, which PR #10423 (5c45465) missed.
```
``` 
> ci(drone): fix duplicate pipeline names

- modules/openapi-generator/src/main/resources/rust/Cargo.mustache
- samples/client/petstore/rust/reqwest/petstore-async/Cargo.toml
The existing reqwest codegen disables the default reqwest crate features when `supportAsync=true`: this inadvertently has the effect of disabling reqwest's TLS support entirely.
This PR keeps the default features, which matches the behaviour of `supportAsync=false`, and keeps the default TLS support enabled.
- Tracking issue: #10421
```
```  …
> fix(rust,client): re-enable TLS support for reqwest with supportAsync

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Please could you also add `;` as a special case in enums?
```
``` 
> [Java] Add semicolon as a special case

- modules/openapi-generator/src/main/resources/rust/model.mustache
- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
- samples/client/petstore/rust/hyper/petstore/src/models/api_response.rs
- samples/client/petstore/rust/hyper/petstore/src/models/category.rs
- samples/client/petstore/rust/hyper/petstore/src/models/order.rs
- samples/client/petstore/rust/hyper/petstore/src/models/pet.rs
- samples/client/petstore/rust/hyper/petstore/src/models/tag.rs
- samples/client/petstore/rust/hyper/petstore/src/models/user.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/pet_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/store_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/apis/user_api.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/models/api_response.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/models/category.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/models/order.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/models/pet.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/models/tag.rs
- samples/client/petstore/rust/reqwest/petstore-async/src/models/user.rs
- samples/client/petstore/rust/reqwest/petstore/src/models/api_response.rs
- samples/client/petstore/rust/reqwest/petstore/src/models/category.rs
- samples/client/petstore/rust/reqwest/petstore/src/models/order.rs
- samples/client/petstore/rust/reqwest/petstore/src/models/pet.rs
- samples/client/petstore/rust/reqwest/petstore/src/models/tag.rs
- samples/client/petstore/rust/reqwest/petstore/src/models/user.rs
This makes operations with many parameters easier to work with.
- Relevant for: #10421
```
``` 
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)
> feat(rust,client): derive Default for operation parameter structs

- modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache
Solves #9179
Allows overwriting the basePath, this useful when the base url cannot always be known beforehand.
@CodeNinjai @frol @cliffano This is an update to only the ApiClient constructor
```
``` 
> fix: :bug: Added ability to override basePath while creating ApiClient instance

- modules/openapi-generator/src/main/resources/bash/client.mustache
- samples/client/petstore/bash/petstore-cli
In the case where we are making empty posts, use -d '' to force curl to set the Content-Length header to 0. Some backends (among which Microsoft Kestrel) are sensitive about POST without a Content-Length set.
This pull request adds a `-d ''` option to curl's command-line in such a situation
I don't have an extensive test setup to provide, for a simple change like this I'm not sure it's necessary. Please let me know if I should add things.
As this is bash: CC @frol, @bkryza, @kenjones-cisco
> [bash] force content length in empty post

- modules/openapi-generator/src/main/resources/ruby-client/api.mustache
- modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api/another_fake_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/fake_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/fake_classname_tags123_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/pet_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/store_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api/user_api.rb
- samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
- samples/client/petstore/ruby/lib/petstore/api/another_fake_api.rb
- samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
- samples/client/petstore/ruby/lib/petstore/api/fake_classname_tags123_api.rb
- samples/client/petstore/ruby/lib/petstore/api/pet_api.rb
- samples/client/petstore/ruby/lib/petstore/api/store_api.rb
- samples/client/petstore/ruby/lib/petstore/api/user_api.rb
- samples/client/petstore/ruby/lib/petstore/api_client.rb
- samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_client.rb
- samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_client.rb
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api/usage_api.rb
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb
Addresses the same issue (#8116) as the PR (#9766), but in the ruby client.
> Define content type if and only if the body is not empty

- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/FileParameter.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/FileParameter.cs
The changes allow to specify content-type for files sent using csharp-netcore client. If content-type is not set explicitly it will be set to `application/octet-stream` as it is currently set fo all files.
To close #10472
```
``` 
> [csharp-netcore] allow to specify content-type for files

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
- modules/openapi-generator/src/main/resources/php/model_enum.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/php/AbstractPhpCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpModelTest.java
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/EnumClass.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/OuterEnum.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/OuterEnumDefaultValue.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/OuterEnumInteger.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/OuterEnumIntegerDefaultValue.php
- fix numeric value in model enum by using the "NUMBER_" prefix
```
``` 
> [PHP] fix numeric value in model enum

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java
- samples/client/petstore/ruby-faraday/docs/FormatTest.md
- samples/client/petstore/ruby-faraday/lib/petstore/models/format_test.rb
- samples/client/petstore/ruby/docs/FormatTest.md
- samples/client/petstore/ruby/lib/petstore/models/format_test.rb
Add decimal support to ruby generators
```
``` 
> Add decimal support to ruby generators

- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
This PR fixes some potential flaky tests in `org.openapitools.codegen.java.AbstractJavaCodegenTest` file. 
In these tests, we assigned some hardcoded elements into the `codegen`'s `AdditionalModelTypeAnnotations`. 
However, according to the code where we set this value, we split the input string by a regex, convert it to a `HashSet`, and store in an `ArrayList`:
```java
// org/openapitools/codegen/languages/AbstractJavaCodegen.java:347
if (additionalProperties.containsKey(ADDITIONAL_MODEL_TYPE_ANNOTATIONS)) {
String additionalAnnotationsList = additionalProperties.get(ADDITIONAL_MODEL_TYPE_ANNOTATIONS).toString();
this.setAdditionalModelTypeAnnotations(new ArrayList<>(Sets.newHashSet(additionalAnnotationsList.trim().split("\\s*(;|\\r?\\n)\\s*"))));
}
```
The problem is that HashSet is not …
> [Java] Fix Potential Flaky Tests

- modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
- modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
- samples/client/petstore/ruby-faraday/lib/petstore/configuration.rb
> [Ruby][Faraday][#10137] Fix config request options and timeout

- .travis.yml
- pom.xml
Skip Crystal tests to shorten build time (based on free credits)
We'll test it locally for the time being before moving the tests to other CIs
```
``` 
> Skip Crystal tests

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- samples/client/petstore/typescript-axios/builds/composed-schemas/api.ts
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/store-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/user-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
Everything from options is already passed to Axios in https://github.com/OpenAPITools/openapi-generator/blob/c2c4ba5b06c2107ad466c20dfee7a8f191a25139/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L57 and later in https://github.com/OpenAPITools/openapi-generator/blob/c2c4ba5b06c2107ad466c20dfee7a8f191a25139/modules/openapi-generator/src/main/resources/typescript-axios/common.mustache#L124 so removing `options.query` from being passed to `setSearchParams` is fine because Axios can merge query params from `path` (where `setSearchParams` result ends up in) and from `options` (where all othed params end up in). This also fixes the issue that `options.query` does not actually exists and the correct parameter is `options.params` which is now typed correctly …
> [typescript-axios] Fix invalid query params usage

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/package.json
Fixes: #10523
NB: `tsickle: 0.43` requires `typescript: 4.3.x` so increased minimum version too.
```
``` 
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce (@akehir @petejohansonxo @amakhrov
> Correct a dependency resolution failure in generated angular typescript packages for Angular 12

- modules/openapi-generator/src/main/resources/typescript/api/api.mustache
- modules/openapi-generator/src/main/resources/typescript/api/baseapi.mustache
- samples/openapi3/client/petstore/typescript/builds/composed-schemas/apis/baseapi.ts
- samples/openapi3/client/petstore/typescript/builds/default/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/default/apis/baseapi.ts
- samples/openapi3/client/petstore/typescript/builds/deno/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/deno/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/deno/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/deno/apis/baseapi.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/apis/baseapi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/apis/baseapi.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/apis/PetApi.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/apis/StoreApi.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/apis/UserApi.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/apis/baseapi.ts
- samples/openapi3/client/petstore/typescript/tests/default/test/api/PetApi.test.ts
Changes the `RequiredError` exceptions class to retain the api class, method and field names as context.
Most importantly the actual error message is now in the `message` field, where it belongs.
Added an integration test to check it works. Verify with:
```
mvn integration-test -f samples/openapi3/client/petstore/typescript/tests/default/pom.xml
```
Fixes #10459 
```
./mvn clean package 
```  …
> Add message and more context to RequiredError

- docs/generators.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartJaguarClientCodegen.java
Dart jaguar doesn't work with newer versions of Dart, there are no contributors to this generator, and it doesn't even generate correct code #5583.
I suggest marking it as deprecated and removing in the future, only changes in last 12 months were forced maintenance changes to keep it in sync with other Dart generators.
```
``` 
For …
> Dart: mark jaguar for deprecation

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/JSON.mustache
- samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/JSON.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/JSON.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java
- remove warning using JsonMapper.builder
```
[WARNING] /Users/williamcheng/Code/openapi-generator/samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/JSON.java:[24,10] [deprecation] configure(MapperFeature,boolean) in ObjectMapper has been deprecated
```
```
```  …
> [java][jersey2] remove warning using JsonMapper.builder

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/IJsonSchemaValidationProperties.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_10725.yaml
Fixes #10725 
Hi @wing328  @spacether @agilob @therve 
This PR tries to fix #10725.  The detail can be found at the page of the issue. 
In a word, "ByteArray" should not be recognized as "String".
Thanks.
```
``` 
> [Core] Does not recognize the type "ByteArray" as "String"

- modules/openapi-generator/src/main/resources/Java/ServerConfiguration.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/google-api-client/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/jersey1/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/rest-assured-jackson/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/rest-assured/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/retrofit2/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/retrofit2rx2/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/retrofit2rx3/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/vertx-no-nullable/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/webclient-nulable-arrays/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ServerConfiguration.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ServerConfiguration.java
- use IllegalArgumentException instead of RuntimeException as suggested by code review
```
``` 
> [java] use IllegalArgumentException instead of RuntimeException

- pom.xml
- samples/client/petstore/groovy/build.gradle
- Fix build-info-extractor-gradle in groovy build.gradle
- Update to the latest version
```
``` 
> Fix build-info-extractor-gradle in groovy build.gradle

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinClientCodegen.java
Fixes #10679 by generating `ApiKeyAuth` when an "apiKey" security scheme is present in the spec.
```
``` 
> Allow ApiKeyAuth generation when an "apiKey" security scheme is present in the spec

- docs/generators/typescript-angular.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/google-api-client/api.mustache
- modules/openapi-generator/src/main/resources/erlang-proper/api.mustache
- modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
- modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
fix
https://github.com/OpenAPITools/openapi-generator/issues/7557
https://github.com/OpenAPITools/openapi-generator/issues/10448
fix isBodyAllow to return true in case of DELETE method
add new method isMethodPutOrPatchOrPost
fix angular typescript client to allow delete with body
if angular version  allow it use isBodyAllow in template 
otherwise use isMethodPutOrPatchOrPost
angular fix client in version12.1
change default angular version to be latest 
in this moment 12.2.12 
```
``` 
You may …
> Delete body angular

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
-Fix bug (authentication setting) in query collection parameters. Before the fix, collectionQueryParams were not updated with authentication settings.
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet …
> [java][okhttp] Fix authentication bug in query collection parameters

- appveyor.yml
Update Maven to 3.8.3 in Appveyor CI to fix CI failure (invalid download URL)
```
``` 
> Update Maven to 3.8.3 in Appveyor CI

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/api/PingApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/ApiClientTest.java
Before this fix, the content-type of the request defaults to "application/json".
With this fix, we no longer set such default.
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger …
> [Java][okhttp] remove default content-type in the request

- modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
- samples/client/petstore/typescript-angular-v10-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v10-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v11-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v11-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v6-not-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v6-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v6-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v7-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v7-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/single-request-parameter/api/pet.service.ts
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-prefixed-module-name/api/pet.service.ts
- samples/client/petstore/typescript-angular-v9-provided-in-any/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v9-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v9-provided-in-root/builds/with-npm/api/pet.service.ts
Fixes #10776 the broken form params for typescript angular client introduced by search&replace refactoring in #10020. 
```
``` 
For …
> Fixed broken form params in typescript-angular client (#10776)

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
- samples/client/petstore/c/model/pet.c
In the functions  `*_parseFromJSON` of the generated C-libcurl client code, when an error occurs, all the non-primitive variables will be freed before the function exits.
e.g.
```c
pet_t *pet_parseFromJSON(cJSON *petJSON){
...
// pet->id
cJSON *id = cJSON_GetObjectItemCaseSensitive(petJSON, "id");
if (id) { 
if(!cJSON_IsNumber(id))
{
goto end; //Numeric
}
}
// pet->category
cJSON *category = cJSON_GetObjectItemCaseSensitive(petJSON, "category");
category_t *category_local_nonprim = NULL;
...
end:
if (category_local_nonprim) {
category_free(category_local_nonprim);
category_local_nonprim = NULL;
}
return NULL;
}
```
But sometimes, the variables are not defined and initialized at this time. e.g. `category_local_nonprim` is not defined if `id` is invalid. Freeing `category_local_nonprim` …
> [C][Client] Define and initialize non-primitive variables at the beginning of function

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultGeneratorTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_10056.yaml
fixes #2731
fixes #8576
fixes #10697
fixes #10056
```
``` 
> #10056 Fix relative url as basePath

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient-nulable-arrays/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java
Motivation:
Remove useless warnings for webclient and resttemplate
See https://github.com/OpenAPITools/openapi-generator/issues/10788
> [Java][resttemplate][webclient] ApiClient should not produce warning

- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
Fixed a typo in description for **full-details** shown by cli command "**help config-help**"
```
``` 
> fix typo (--supporting-files > --feature-set)

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
Hi all!
This issue is regarding the `csharp-netcore` generator. There is a bit of an inconsistency in how the test folders are generated when the `sourceFolder` property is provided. For example: 
- Set the option `sourceFolder` to anything other than `src`. 
- In this case, I left it empty:  `--additional-properties=sourceFolder=""`
- Generate the client
- See that the client was generated in the provided `sourceFolder`... but the tests where generated in `src`:
In the `AbstractCSharpCodegen.java`, there is a TODO a few years old saying that a separate option for `testFolder` could be added: 
https://github.com/OpenAPITools/openapi-generator/blob/8551b0af492286a431c95ce3a37d7edf1ef4870a/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java#L …
> [csharp] Use the provided 'sourceFolder' property to generate the test folder

- modules/openapi-generator/src/main/resources/rust/model.mustache
#10432
This change forgot enum structures, which causes the compiler to throw errors for "the trait `Default` is not implemented for MyEnum". This change implements the Default trait to the enum template.
This has been tested to work and fixes the problem.
```
```  …
> fix(rust, client): fix breaking regression introduced by #10432

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
- modules/openapi-generator/src/main/resources/cpp-pistache-server/api-header.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/api-impl-header.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/api-source.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/cmake.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-header.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-source.mustache
- samples/server/petstore/cpp-pistache/CMakeLists.txt
- samples/server/petstore/cpp-pistache/api/PetApi.cpp
- samples/server/petstore/cpp-pistache/api/PetApi.h
- samples/server/petstore/cpp-pistache/api/StoreApi.h
- samples/server/petstore/cpp-pistache/api/UserApi.cpp
- samples/server/petstore/cpp-pistache/api/UserApi.h
- samples/server/petstore/cpp-pistache/impl/PetApiImpl.cpp
- samples/server/petstore/cpp-pistache/impl/PetApiImpl.h
- samples/server/petstore/cpp-pistache/impl/StoreApiImpl.h
- samples/server/petstore/cpp-pistache/impl/UserApiImpl.cpp
- samples/server/petstore/cpp-pistache/impl/UserApiImpl.h
- Fixes #9148
- Integrate pistache's meson build system into existing cmake build
- Upgrade build to C++17
- Replace `Pistache::Optional` with `std::optional` from C++17
- Disable running tests during build of nlohmann/json dependency
- Update petstore sample
CC: @ravinikam @stkrwork @etherealjoy @martindelille @muttleyxd
```
``` 
For …
> [cpp-pistache-server]: Fix build with pistache master branch

- pom.xml
I played a bit with surefire config locally. `mvn test` with config from master branch runs in 418 seconds on my laptop so this was my baseline. I tried a few different things, experimented with configuration on parallel classes, methods etc. and got to this point where `mvn test ` now completes in 280 seconds
From surefire doesn't really encourage to use fork parallelism:
>forkCount=1/reuseForks=false executes each test class in its own JVM process, one after another. It creates the highest level of separation for the test execution, but it would probably also give you the longest execution time of all the available options. Consider it as a last resort.
testng had to be downgraded to support `parallel` flag in surefire, but that will be fixed in the next version of surefire: …
> Use parallel classes test over reusing forks

- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
- samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
resolve #8562
Creating new URLSession for every request isn't optimal and it is not recommended by Apple.
Also, `NSPOSIXErrorDomain Code=28 "No space left on device"` will get thrown after too many URLSessions get created. 
> https://developer.apple.com/videos/play/wwdc2018/714/?time=1646
> https://developer.apple.com/videos/play/wwdc2017/709/
> https://developer.apple.com/forums/thread/84663
> https://stackoverflow.com/questions/67318867/error-domain-nsposixerrordomain-code-28-no-space-left-on-device-userinfo-kcf/67507327#67507327
I've hashed the session's configuration, credentials and sessionDelegate with Hasher so we can reuse URLSessions with the same settings.
```
```  …
> [swift5] Reuse URLSessions

- modules/openapi-generator/src/main/resources/go/client.mustache
- samples/client/petstore/go/auth_test.go
- samples/client/petstore/go/go-petstore/client.go
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go
- samples/openapi3/client/petstore/go/auth_test.go
- samples/openapi3/client/petstore/go/go-petstore/client.go
Golang be default canonizes header names for example `content-type` will be converted to `Content-Type`, this PR allows to opt out this behaviour by setting additional property dontCanonizeHeaders=true.
```
``` 
> [GO] dont canonize headers 

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/pom.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/settings.gradle.kts.mustache
- samples/client/petstore/kotlin-multiplatform/build.gradle.kts
- samples/client/petstore/kotlin-multiplatform/pom.xml
- samples/client/petstore/kotlin-multiplatform/settings.gradle.kts
Fixes #10898 
- Remove [obsolete](https://github.com/gradle/gradle/issues/15993) `GRADLE_METADATA` Gradle preview flag from Kotlin Multiplatform `settings.gradle.kts.mustache` template file.
- Update Kotlin Version to 1.5.31.
- Update `coroutines`, `serialization` and `ktor` versions to the versions recommended for usage with Kotlin 1.5.31 (see https://kotlinlang.org/docs/releases.html#release-details).
- Add a `clean` task to the Kotlin Multiplatform template `pom.xml` file to allow to easily clean the samples folder from previous build outputs.
- Update the Kotlin Multiplatform sample to reflect the changes to the template.
To validate that this PR fixes the issue, run the Kotlin Multiplatform test from the project's root folder and see that the test completes successfully.
```
./mvnw …
```
> [Kotlin][Multiplatform] Fix Kotlin Multiplatform Test

- modules/openapi-generator/src/main/resources/powershell/api_client.mustache
- modules/openapi-generator/src/main/resources/powershell/appveyor.mustache
- modules/openapi-generator/src/main/resources/powershell/configuration.mustache
- modules/openapi-generator/src/main/resources/powershell/model_simple.mustache
- samples/client/petstore/powershell/appveyor.yml
- samples/client/petstore/powershell/src/PSPetstore/Client/PSConfiguration.ps1
- samples/client/petstore/powershell/src/PSPetstore/Model/Pet.ps1
- samples/client/petstore/powershell/src/PSPetstore/Private/PSApiClient.ps1
better `$null` comparison by putting $null on the LHS
```
``` 
> [powershell] better null comparison

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java
- modules/openapi-generator/src/main/resources/protobuf-schema/enum.mustache
- modules/openapi-generator/src/main/resources/protobuf-schema/model.mustache
resolves #10867 
- Added enum.mustache
- Partial render to model.mustache.
- Add "protobuf-enum-index" to enumVars in model aswell (needed for field numbers)
- ~Set ClassName to match the enumName when used as CodegenProperty~
> [Protobuf-Schema] Add enum as model support

- modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache
Fixes #10902 
- Fix broken generation of enum classes by removing unnecessary template code that broke the compilation of the generated code.
To validate that this PR fixes the issue you should first reproduce the issue. This can be done on the `master` branch by generating the `kotlin-multiplatform` template code with the `petstore-with-fake-endpoints-models-for-testing.yaml` API spec, and then trying to compile the generated code:
```
./bin/generate-samples.sh bin/configs/kotlin-multiplatform.yaml -- -i modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
./mvnw integration-test -f samples/client/petstore/kotlin-multiplatform/pom.xml
```
The test fails due to several compilation errors. The errors that are relevant for the purpose of this …
> [Kotlin][Multiplatform] Fix Enum Generation 

- modules/openapi-generator/src/main/resources/python-legacy/test-requirements.mustache
- samples/client/petstore/python-legacy/test-requirements.txt
- samples/client/petstore/python-legacy/tests/test_pet_api.py
- samples/openapi3/client/petstore/python-legacy/test-requirements.txt
It fixes build problems introduced in this PR https://github.com/OpenAPITools/openapi-generator/pull/10686
```
``` 
cc: @wing328 @spacether
> [Python] Add missing Mock library for Python 2.7.

- modules/openapi-generator/src/main/resources/typescript-axios/package.mustache
- samples/client/petstore/typescript-axios/builds/es6-target/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version/package.json
This updates the typescript-axios template to use `prepare` instead of `prepublishOnly` in the same manner that the typescript generator was updated in [#7878](https://github.com/OpenAPITools/openapi-generator/pull/7878)
```
``` 
@amakhrov
> Allows install typescript-axios client via npm from Git

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/api/PingApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/UserApi.java
Add operation level server support for Java okhttp-gson http client 
Closes #10847 
At the API level - user can specify a custom base URL. If no custom base url is specified, the API selects the 1st path level server (if any), unless a different host index is specified. If no operation level servers are defined, the http request is built using the spec default server url. 
```
```  …
> Add operation level servers support for java okhttp-gson client

- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
The [docs for ofInputStream](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpResponse.BodySubscribers.html#ofInputStream()) say:
> To ensure that all resources associated with the corresponding exchange are properly released the caller must ensure to either read all lines until the stream is exhausted, or call BaseStream.close() if it is unable or unwilling to do so. Calling close before exhausting the stream may cause the underlying HTTP connection to be closed and prevent it from being reused for subsequent operations.
When ObjectMapper.readValue is called with an InputStream it implicitly closes it, but when the library is not expecting a return type it's not passing the InputStream to Jackson, so the stream needs to be manually drained and closed as …
> [Java][Native] Drain InputStream when no response is being read

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/ApiClientTest.java
fix #9734
Before this PR, okhttp-gson client cannot send text/plain body.
After the PR, okhttp-gson client support text/plain body.
In addition, I add tests for Serialize method.
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) …
> [Java][okhttp-gson] Support text/plain body

- docs/generators/ruby.md
Current generated ruby client library's default option is different what documentation says. This PR updates some options to latest.
See also: https://github.com/OpenAPITools/openapi-generator/blob/c13067d100c43cfbedea205df37f365014cbdb2f/modules/openapi-generator/src/main/resources/ruby-client/gemspec.mustache
```
``` 
For Windows …
> Update ruby's default options on document

- modules/openapi-generator/src/main/resources/kotlin-client/enum_class.mustache
- samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/models/PetEnum.kt
For the case, an enum value is named Any, the parameter in encode and decode should be fully qualified.
I have not created an issue, because these change is not worth the time.
@jimschubert, @dr4ke616, @karismann, @Zomzog, @andrewemery, @4brunu, @yutaka0m
```
```  …
> [Kotlin] Fully qualified "Any" for enums in encode and decode function

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache
- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/StoreApi.kt
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/UserApi.kt
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
It is currently not possible to configure the Ktor HTTP client when using generated Kotlin Multiplatform code.
Configuring the HTTP client can be useful for logging or customising request headers, to name a few use cases.
This issue has been raised in #10130 .
This PR makes it possible to configure the Ktor HTTP client by allowing to pass an optional `httpClientConfig` parameter to the generated API classes.
An example of how the new `httpClientConfig` parameter can be used can be seen [here](https://github.com/Airthings/openapi-multiplatform-multi-module/compare/configurable-http-client#diff-04d693ee26583a89dce08ae4bcb2f5120653955239bf92713a883afe481742c5R12):
```kotlin
private val petApi = PetApi(httpClientConfig = createHttpClientConfig())
private fun createHttpClientConfig(): …
```
> [Kotlin][Multiplatform] Support custom Ktor HTTP client configuration

- openapi-generator.code-workspace
Adds visual studio code structured configuration with modules separated for easier navigation:
Config contains IntelliJ-like configuration for VSC with features like autosave, autorefresh dependencies.
A few plugins are recommended for use like mustache highlighter, java for vcs, and openapi spec linter.
> Add vscode openapi workspace configuration

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
Fixes CodegenMediaType schema baseName
Every schema should have a different baseName depending upon its contentType
```
``` 
> Fixes CodegenMediaType schema baseName

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
This PR updates the Kotlin Multiplatform library templates with the following:
- Fix an object freezing related issue that occurs on iOS when configuring the HTTP client. In the current version of the template, the entire `ApiClient` instance is captured when configuring the HTTP client. This does not work on iOS and throws an exception. The fix is implemented by capturing only the `serializer` instance.
- Always use the HTTP client config that is defined in the API client class and extend it with the optional constructor provided configuration. Without this change, the client of the generated `ApiClient` class must also configure JSON serialization in order for the generated code to work. 
These changes were tested and validated in a demo project: …
> [Kotlin][Multiplatform] Fix and improve HTTP client configuration

- .github/workflows/samples-kotlin.yaml
- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache
- samples/client/petstore/kotlin-multiplatform/build.gradle.kts
This PR adds building and testing the Kotlin Multiplatform samples in the project's CI.
Kotlin technical committee:
```
``` 
> [Kotlin][Multiplatform] Build and test Kotlin Multiplatform samples in CI

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
According to RFC 7235 (HTTP/1.1: Authentication), schema tokens are
handled case-insensitive (Section 2.1: Challenge and Response). This
change compares the known token values basic, bearer, and signature
case-insensitive.
- https://datatracker.ietf.org/doc/html/rfc7235#section-2.1
```
```  …
> Compare HTTP auth security schema names case-insensitive

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/allOf_composition_discriminator_recursive.yaml
This boils down to preserving the import from the child to the parent schema if the parent is directly referenced in the child.
I added a test with an example yaml spec that features such recursively defined schemas. Basically,
```
Token: ExpressionToken | StringToken
ExpressionToken:
tokens: Array<Token>
```
```
```  …
> [typescript-angular] taggedUnions=true: Support recursive schemas

- modules/openapi-generator/src/main/resources/php-slim4-server/README.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/composer.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/licenseInfo.mustache
- samples/server/petstore/php-slim4/README.md
- samples/server/petstore/php-slim4/composer.json
- samples/server/petstore/php-slim4/config/dev/example.inc.php
- samples/server/petstore/php-slim4/config/prod/example.inc.php
- samples/server/petstore/php-slim4/lib/Api/AbstractPetApi.php
- samples/server/petstore/php-slim4/lib/Api/AbstractStoreApi.php
- samples/server/petstore/php-slim4/lib/Api/AbstractUserApi.php
- samples/server/petstore/php-slim4/lib/Auth/AbstractAuthenticator.php
- samples/server/petstore/php-slim4/lib/BaseModel.php
- samples/server/petstore/php-slim4/lib/Middleware/JsonBodyParserMiddleware.php
- samples/server/petstore/php-slim4/lib/Model/ApiResponse.php
- samples/server/petstore/php-slim4/lib/Model/Category.php
- samples/server/petstore/php-slim4/lib/Model/Order.php
- samples/server/petstore/php-slim4/lib/Model/Pet.php
- samples/server/petstore/php-slim4/lib/Model/Tag.php
- samples/server/petstore/php-slim4/lib/Model/User.php
- samples/server/petstore/php-slim4/lib/SlimRouter.php
- samples/server/petstore/php-slim4/public/index.php
- samples/server/petstore/php-slim4/tests/BaseModelTest.php
Related #11038
Since latest Slim(4.9.0) requires PHP ^7.3, then I don't see any reason to test updated samples. Everything should work.
cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @renepardon
```
``` 
> [php-slim4] Bump required PHP version to 7.4

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/anyof_model.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/oneof_model.mustache
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Fruit.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/FruitReq.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/GmFruit.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Mammal.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/NullableShape.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Pig.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Quadrilateral.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Shape.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/ShapeOrNull.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/model/Triangle.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/test/java/org/openapitools/client/JSONTest.java
- better null handling in oneOf, anyOf model
- add more tests
```
``` 
> [java][okhttp-gson-nextgen] Better null handling in oneOf, anyOf model

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/resources/3_0/oneOfArrayMapImport.yaml
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIs.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIs/AnotherFakeAPI.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIs/FakeClassnameTags123API.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIs/StoreAPI.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/APIs/UserAPI.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/Models.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/typescript-angular-v11-oneOf/builds/default/.openapi-generator/VERSION
- samples/client/petstore/typescript-angular-v11-oneOf/builds/default/api/default.service.ts
Fixes paramName and dataType for request body anyType parameters
The earlier PR https://github.com/OpenAPITools/openapi-generator/pull/10334 created a regression for AnyType request bodies where their paramName and dataTypes went from having values to being null or incorrect.
This PR fixes that bug.
```
``` 
For Windows users, please run …
> Fixes paramName and dataType for request body anyType parameters

- modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache
- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
- samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
- samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
> [swift5] Fix missing case for FormDataEncoding#encode

- modules/openapi-generator/src/main/resources/swift5/api.mustache
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/AnotherFakeAPI.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeClassnameTags123API.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/StoreAPI.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/UserAPI.swift
With the release of Xcode 13.2, async/await is not available on macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0.
Previously it was only available in macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0.
This fixes that.
```
``` 
@jgavris (2017/07) @ehyche (2017/08) …
> [swift5][client] add support for async/await in iOS 13 and above

- modules/openapi-generator/src/main/resources/cpp-qt-client/CMakeLists.txt.mustache
- modules/openapi-generator/src/main/resources/cpp-qt-client/oauth.cpp.mustache
- modules/openapi-generator/src/main/resources/cpp-qt-client/oauth.h.mustache
- samples/client/petstore/cpp-qt/CMakeLists.txt
- samples/client/petstore/cpp-qt/client/CMakeLists.txt
- samples/client/petstore/cpp-qt/client/PFXOauth.cpp
- samples/client/petstore/cpp-qt/client/PFXOauth.h
Fix for the PR that broke the integration test. #10183
I had to modify the CMakeLists.txt in the Petstore example project and add Qt5::Gui package. 
@wing328 
```
``` 
> [QT][C++]fixed integration test for Oauth

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Show error when schema in discriminator mapping in oneOf/anyOf is undefined, e.g.
```sh
[main] INFO  o.o.c.languages.AbstractJavaCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Processing operation getState
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Processing operation createState
[main] ERROR o.o.codegen.DefaultCodegen - Failed to lookup the schema 'ObjC' when processing the discriminator mapping of oneOf/anyOf. Please check to ensure it's defined properly.
[main] ERROR o.o.codegen.DefaultCodegen - Failed to lookup the schema 'ObjC' when processing the discriminator mapping of oneOf/anyOf. Please check to ensure it's defined properly.
[main] WARN …
```
> Show an error when the schema in discriminator mapping is undefined

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioNextClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/ArchUnitRulesTest.java
- modules/openapi-generator/src/test/resources/archunit_ignore_patterns.txt
new archunit test check for not allowing to use standard streams like System.out and System.err, this PR replaces https://github.com/OpenAPITools/openapi-generator/pull/11128
@wing328 @jimschubert
> Forbid using standard streams in archunit

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java
- modules/openapi-generator/src/main/resources/protobuf-schema/api.mustache
- modules/openapi-generator/src/main/resources/protobuf-schema/model.mustache
- modules/openapi-generator/src/test/resources/3_0/protobuf-schema/pet.proto
- samples/config/petstore/protobuf-schema/services/pet_service.proto
- samples/config/petstore/protobuf-schema/services/store_service.proto
- samples/config/petstore/protobuf-schema/services/user_service.proto
resolve #11114 
- fixed default packageName to **openapitools**
- api mustache packageName changed to {**{packageName}}.{{apiPackage}}.{{classname}}**
- package name changed to lowercase following the protobuf convention
> [Protobuf-Schema] Namespace updates

- modules/openapi-generator/src/main/resources/scala-akka-client/apiInvoker.mustache
- samples/client/petstore/scala-akka/src/main/scala/org/openapitools/client/core/ApiInvoker.scala
Fixes a deprecation issue in the Akka HTTP client generator for Scala. The `ActorMaterializer` type and constructor have been deprecated since Akka HTTP 2.6.0 and are throwing a warning.
```
ApiInvoker.scala:94:58
[E]      method apply in object ActorMaterializer is deprecated (since 2.6.0): Use the system wide materializer with stream attributes or configuration settings to change defaults
[E]      L94:   private implicit val materializer: ActorMaterializer = ActorMaterializer()
ApiInvoker.scala:94:38
[E]      class ActorMaterializer in package stream is deprecated (since 2.6.0): The Materializer now has all methods the ActorMaterializer used to have
[E]      L94:   private implicit val materializer: ActorMaterializer = ActorMaterializer()
```
``` …
```
> [Scala-Akka-Http] Fix deprecated `ActorMaterializer` since akka-http 2.6

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/api.mustache
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/PetApi.kt
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/StoreApi.kt
- samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/apis/UserApi.kt
This PR changes the Kotlin multiplatform templates so that:
- API classes can be subclassed.
- API methods can be overridden.
The motivation for this change is to make it easier to use API classes in tests. By making the class and methods `open`, it is possible to override the API class behavior and provide stubs.
An example of how this is useful in a test scenario can be seen [here](https://github.com/Airthings/openapi-multiplatform-multi-module/blob/subclass-pet-api/shared/src/commonTest/kotlin/com.airthings.openapi.test/GreeterTest.kt#L38).
```kotlin
private class PetApiStub(private val findPetsByStatusResponse: List<Pet>) : PetApi() {
override suspend fun findPetsByStatus(status: List<String>): HttpResponse<List<Pet>> =
HttpResponseStub(responseStub = findPetsByStatusResponse)
}
``` …
> [Kotlin][Multiplatform] Declare API classes and methods as open

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/apis/FakeApi.ts
- samples/client/petstore/typescript-fetch/builds/enum/apis/DefaultApi.ts
This PR uses a default value to requestParameters (= {}) if all the parameters are optional.
Fixes #11112
```
``` 
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov
> useSingleRequestParameter should mark parameter optional if all properties are optional

- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
Previously, rust-client generator disregarded collectionFormat property of multi-value parameters. Now we support following values in collectionFormat: `""`, `"csv"`, `"multi"`.
You can review changes this PR yield for fairly sizeable  project at https://github.com/CrowdStrike/rusty-falcon/pull/33/files
```
``` 
For Windows users, please …
> Rust Client: Add support for collectionFormat="multi"

- modules/openapi-generator/src/main/resources/scala-gatling/build.gradle
This plugin is no longer supported:
https://github.com/lkishalmi/gradle-gatling-plugin
It has been replaced by this plugin:
https://github.com/gatling/gatling-gradle-plugin
﻿
```
``` 
> [scala-gatling] use the official Gradle plugin

- modules/openapi-generator/src/main/resources/Java/Pair.mustache
…client.
The java client doesn't allow query parameters that have a value of just "%20"
or "%0A". Those can now be values with this commit.
To close #11032
```
``` 
> Bug fix - Allow query parameters than contain spaces for Java client

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
The content type being null leads to an empty content type header. The resteasy server cannot process an empty content type:
```
java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType string: 
at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.internalParse(MediaTypeHeaderDelegate.java:96) ~[org.jboss.resteasy.core_4.7.1.Final.jar:?]
at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.parse(MediaTypeHeaderDelegate.java:69) ~[org.jboss.resteasy.core_4.7.1.Final.jar:?]
at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:33) ~[org.jboss.resteasy.core_4.7.1.Final.jar:?]
at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:19) …
```
> [Java-OKHTTP-GSON] Do not set content-type if content type is null

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Add isSkipOperationExample check before generating op.requestBodyExamples in the DefaultCodeGe. This avoids the running out of heap space error you can get when generating a large spec file, even with the skipOperationExample flag is set to true under additional properties. 
Example command:
java -jar ./openapi-generator-cli.jar generate -i http://localhost:5000/swagger/v1/swagger.json --additional-properties=skipOperationExample=true -g dart -o ../server-api -c ./openapi-gen-config.yaml
Now skips example code generation in the body as well when the flag is set to true. Before this would only skip op.examples but generate would still run for op.requestBodyExamples which would blow up the heap stack with no way to disable it.
> Add isSkipOperationExample check before generating op.requestBodyExamples

- docs/generators/jaxrs-cxf-cdi.md
- docs/generators/jaxrs-spec.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/api.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/apiInterface.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/apiMethod.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pom.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/returnAsyncTypeInterface.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/jaxrs/JavaJAXRSSpecServerCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_4832.yaml
resolves #4832
This PR is an attempt at addressing https://github.com/OpenAPITools/openapi-generator/issues/4832
Since version 2.1, JAX-RS server side component has support for returning a `CompletionStage` to mark the request as eligible for asynchronous processing. The advantage this approach has over the AsyncResponse based API is that it is richer and allows you to create asynchronous pipelines. 
It is also extended by 3rd party libraries such as [Reactor](https://github.com/reactor/reactor-core), [RxJava](https://github.com/ReactiveX/RxJava) or [Mutiny](https://github.com/smallrye/smallrye-mutiny). All of those allow to convert from/to `CompletionStage`, examples:
* Reactor:
```java
CompletionStage<String> single = Mono.just("something").toFuture();
CompletionStage<List<String>> many …
```
> Add support for asynchronous API for JavaJaxRsSpec

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
- samples/client/petstore/php/OpenAPIClient-php/tests/ObjectSerializerTest.php
That's enhanced version of #11003 PR(thanks to original author @carmenquan). Please, let me know if my fix solves your problem.
Closes #10548
```console
vendor/bin/phpunit tests/ObjectSerializerTest.php
Xdebug requires Zend Engine API version 320160303.
The Zend Engine API version 320190902 which is installed, is newer.
Contact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.
...................                                               19 / 19 (100%)
Time: 00:00.009, Memory: 6.00 MB
OK (19 tests, 29 assertions)
```
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09), @renepardon (2018/12), @carmenquan
``` …
```
> [php][bug] Fix DateTime microseconds bug in ObjectSerializer

- modules/openapi-generator/src/main/resources/avro-schema/typeProperty.mustache
Changing the mustache template to generate correct type for properties with ref as enum. 
Fixes #11200
> Avro schema generation fix for properties with type ref to an enum

- modules/openapi-generator/src/main/resources/cpp-qt-qhttpengine-server/apirouter.h.mustache
> Bugfix of #11176 and related #10706 CPP-QT-QHTTPENGINE Server 

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
Before the fix, if using Jersey2 as generator and including DELETE operations that don't "accept" any body, the generated code executes HTTP requests with header "Accept:null", which is not a valid header.
After the fix, it will not create "Accept:null" as the header.
This is to fix issue #6882
```
```  …
> Not creating "Accept:null" header for Java-Jersey2 generator

- modules/openapi-generator/src/main/resources/go-server/api.mustache
- modules/openapi-generator/src/main/resources/go-server/controller-api.mustache
- modules/openapi-generator/src/main/resources/go-server/helpers.mustache
- modules/openapi-generator/src/main/resources/go-server/impl.mustache
- samples/server/petstore/go-api-server/go/api.go
- samples/server/petstore/go-api-server/go/api_pet.go
- samples/server/petstore/go-api-server/go/api_store.go
- samples/server/petstore/go-api-server/go/api_user.go
- samples/server/petstore/go-api-server/go/helpers.go
- samples/server/petstore/go-api-server/go/impl.go
- samples/server/petstore/go-chi-server/go/api.go
- samples/server/petstore/go-chi-server/go/api_pet.go
- samples/server/petstore/go-chi-server/go/api_store.go
- samples/server/petstore/go-chi-server/go/api_user.go
- samples/server/petstore/go-chi-server/go/helpers.go
- samples/server/petstore/go-chi-server/go/impl.go
- samples/server/petstore/go-server-required/go/api.go
- samples/server/petstore/go-server-required/go/api_pet.go
- samples/server/petstore/go-server-required/go/api_store.go
- samples/server/petstore/go-server-required/go/api_user.go
- samples/server/petstore/go-server-required/go/helpers.go
- samples/server/petstore/go-server-required/go/impl.go
_*Affects the Go-server only._
Adds a code generation to parse query parameter fields of `int32 array` and `int64 array` types. Assumes that `style: form` and `explode: false` are used as serialization method.
```yaml
info:
description: Example API
version: 1.0.0
title: "Example API"
servers:
- url: http://localhost:8080/api/v1
description: development server
paths:
/companies:
get:
summary: Filter companies by specified criteria
operationId: find
parameters:
- name: ids
in: query
example: "500, 501"
schema:
type: array
items:
type: integer
format: int64
tags:
- Company
responses:
200:
description: Successful operation
```
Before:
```go
parentIDsParam := strings.Split(query.Get("ids"), ",")
```
After:
```go
mtinfoIDsParam, err := parseInt64ArrayParameter(query.Get("ids"), …
```
> [Go] Parse integer array query parameters. Fix typos

- modules/openapi-generator/src/main/resources/python/api.mustache
- modules/openapi-generator/src/main/resources/python/api_client.mustache
- samples/client/petstore/python/petstore_api/api/another_fake_api.py
- samples/client/petstore/python/petstore_api/api/fake_api.py
- samples/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py
- samples/client/petstore/python/petstore_api/api/pet_api.py
- samples/client/petstore/python/petstore_api/api/store_api.py
- samples/client/petstore/python/petstore_api/api/user_api.py
- samples/client/petstore/python/petstore_api/api_client.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/another_fake_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/fake_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/fake_classname_tags_123_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/pet_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/store_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api/user_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api_client.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/api/usage_api.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/api_client.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api/usage_api.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api_client.py
- samples/openapi3/client/petstore/python/petstore_api/api/another_fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/default_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/fake_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/fake_classname_tags_123_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/pet_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/store_api.py
- samples/openapi3/client/petstore/python/petstore_api/api/user_api.py
- samples/openapi3/client/petstore/python/petstore_api/api_client.py
> [Python] add '_spec_property_naming' param 

- modules/openapi-generator/src/main/resources/php/composer.mustache
- samples/client/petstore/php/OpenAPIClient-php/composer.json
Fix [#11152](https://github.com/OpenAPITools/openapi-generator/issues/11152)
Allows the use of guzzlehttp/psr7 in versions 1.8.x and v2.0.x
This ensures that the created package can be used in combination with libraries that still require 1.x of guzzlehttp/psr7 and as all the necessary functions of 2.x already exists in 1.8.x, it requires only a composer.json change.
Furthermore, it is also what is required by guzzlehttp itself in 7.3.0 or higher itself: https://github.com/guzzle/guzzle/blob/7.3.0/composer.json
```
```  …
> [PHP] Allow guzzlehttp/psr7 ^1.7 or ^2.0

- samples/client/petstore/python/test/test_fake_api.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/test/test_fake_api.py
Adds fix for broken python test
@JoeCqupt
It looks like https://github.com/OpenAPITools/openapi-generator/pull/11226 broke a test
```
``` 
> Adds fix for broken python test

- modules/openapi-generator/src/main/resources/python/api_client.mustache
- samples/client/petstore/python/petstore_api/api_client.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/api_client.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/api_client.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/api_client.py
- samples/openapi3/client/petstore/python/petstore_api/api_client.py
Closes #10773
Example case that caused issue:
API spec
```
post:
parameters:
- in: formData
name: file-en
type: file
required: false
```
Uploading a file resulted in `name` being `file_en` rather than `file-en`.
Changing `param_name` to `base_name` resolves that issue.
```
```  …
> [python] Fix 10773 - Use base_name for file uploads in form data

- modules/openapi-generator/src/main/resources/python-legacy/setup.mustache
- samples/client/petstore/python-asyncio/setup.py
- samples/client/petstore/python-legacy/setup.py
- samples/client/petstore/python-tornado/setup.py
- samples/openapi3/client/petstore/python-legacy/setup.py
https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/
Since our `long_description` includes markdown, we now need to explicitly declare the content type by setting `long_description_content_type='text/markdown'`
```
``` 
> Making PyPi markdown friendly requires additional property

- modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue11242.yaml
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
Fixes #11242 white space encoding in path parameters
```
``` 
> ISSUE-11242: Fix Java native path param encoding

- bin/configs/python-experimental.yaml
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java
- samples/openapi3/client/petstore/python-experimental/.openapi-generator/VERSION
Allows generators to set defaultTemplateEngine
python-experimental needs to use handlebars as its default template engine
If we don't allow this then when devs use generator that need to use handlebars by default the devs must always pass in the -e or templatingEngineName yaml input; even though all the template files are handlebars files for python-experimental.
For context the python-experimental generator only works with handlebars templates.
That template engine allows any depth of indented partials and python-experimental uses it to render inline schemas.
```
```  …
> Has generators set default template engine

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/RequestOptions.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/RequestOptions.mustache
- samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Client/RequestOptions.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/RequestOptions.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/RequestOptions.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/RequestOptions.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/RequestOptions.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/RequestOptions.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/RequestOptions.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/RequestOptions.cs
Fix issue #11132
FileParameters at Request Options is a Dictionary so we weren't able to send more than one file with the same key.
Refactor FileParamerts to Multimap to enable sending more than one file with the same key.
I did the development only for csharp-netcore but it has no impacts and can be made to the others generators.
If you find it useful say it at the review.
@mandrean 
@shibayan 
@Blackclaws 
@lucamazzanti 
```
```  …
> [BUG][csharp-netcore] Fix Multi Files for the same FormField  (#11132)

- modules/openapi-generator/src/main/resources/csharp-netcore/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Api/PetApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Api/PetApi.cs
This PR fix problem in `csharp-netcore` client with invalid(multiple) authorization header if more than one security present in spec file.
Steps to reproduce:
1. Create new C# web project with bearer auth scheme which consumes `access_token` and put `Authorize` attribute on test controller
2. Install Swashbuckle to project
3. Add Bearer and OAuth schemes to swagger via `AddSecurityRequirement`
4. Generate `csharp-netcore` client against spec
5. Put `AccessToken` in `Configuration` for generated client
6. Call request on generated client <-- 401 here
Solution:
Pass only one `Authorization` header. Which one will be chosen from first met scheme.
```
``` 
This is important, as CI …
> [csharp-netcore] Fix: Add only first Authorization header

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-retrofit2-kotlinx_serialization/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-retrofit2-rx3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-retrofit2/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- https://github.com/OpenAPITools/openapi-generator/issues/10008
- https://github.com/OpenAPITools/openapi-generator/pull/10708
```
``` 
/cc @jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m
> Fix missing ApiKeyAuth import in 'jvm-retrofit2' Kotlin client template

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CLibcurlClientCodegen.java
- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/api_pet_test.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/api_store_test.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/list.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/list.h.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
- modules/openapi-generator/src/main/resources/cpp-tizen-client/api-body.mustache
- modules/openapi-generator/src/main/resources/cpp-tizen-client/requestinfo.mustache
- samples/client/petstore/c/api/PetAPI.c
- samples/client/petstore/c/api/StoreAPI.c
- samples/client/petstore/c/api/UserAPI.c
- samples/client/petstore/c/include/list.h
- samples/client/petstore/c/model/pet.c
- samples/client/petstore/c/src/apiClient.c
- samples/client/petstore/c/src/list.c
- samples/client/petstore/c/unit-test/test_pet.c
- samples/client/petstore/c/unit-tests/manual-PetAPI.c
- samples/client/petstore/c/unit-tests/manual-StoreAPI.c
- samples/client/petstore/cpp-tizen/src/PetManager.cpp
- samples/client/petstore/cpp-tizen/src/RequestInfo.h
- samples/client/petstore/cpp-tizen/src/StoreManager.cpp
- samples/client/petstore/cpp-tizen/src/UserManager.cpp
```
#define list_ForEach(element, list) for(element = (list != NULL) ? (list)->firstEntry : NULL; element != NULL; element = element->nextListEntry)
list_t* list_create();
void list_free(list_t* listToFree);
void list_addElement(list_t* list, void* dataToAddInList);
listEntry_t* list_getElementAt(list_t *list, long indexOfElement);
```
Key work "list_create()" and "list_free()" Conflict with Zebos "llist_create()" and "list_free()"
https://github.com/kubernetes-client/c/issues/90#issue-1039058417
change to
```
#define list_ForEach(element, list) for(element = (list != NULL) ? (list)->firstEntry : NULL; element != NULL; element = element->nextListEntry)
list_t* __list_create();
void __list_free(list_t* listToFree);
void list_addElement(list_t* list, void* dataToAddInList);
listEntry_t* …
```
> keyword conflict with zebos list_creat(), list_free()

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
resolve #7199
The Kotlin client codegen currently cannot handle path params of type array. The code being generated for the path is currently this: `path = "/stuff/{ids}".replace("{"+"ids"+"}", "$ids")`. This works fine, but not if `ids` is a list or an array, since the `toString()` method is used to create the string.
With the current code, if `ids` contains 123 and 456, then `path` would be set to:
* `/stuff/[123,456]` if `collectionType` is list.
* `/stuff/[Ljava.lang.String;@6a98f353` if `collectionType` is array.
In both cases, `/stuff/123,456` is the expected result.
If we change the code from
`path = "/stuff/{ids}".replace("{"+"ids"+"}", "$ids")`
to 
`path = "/stuff/{ids}".replace("{"+"ids"+"}", ids.joinToString(","))`,
we get the expected result.
OpenAPI Spec demonstrating this: …
> [BUG][kotlin] Make Kotlin client generate comma separated list for array path params

- bin/configs/python-experimental.yaml
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java
This reverts commit dd3bba8c9442f2ee40d6ea8f0872ab0be43714b9.
Because it broke peoples builds per this issue https://github.com/OpenAPITools/openapi-generator/issues/11276
```
``` 
> Revert "Has generators set default template engine (#11245)"

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/KotlinReservedWordsTest.java
- modules/openapi-generator/src/test/resources/3_0/kotlin/reserved_words.yaml
- modules/openapi-generator/src/test/resources/bugs/issue_11304_kotlin_backticks_reserved_words.yaml
Added fix for wrongly encoded backticks for reserved words when generating kotlin client using reserved words as part of the parameters. Wrote a test verifying that the method signatures is without html encoding for backticks
This fixes issue #11304
```
```  …
> [kotlin] Added fix for wrongly encoded backticks for reserved words when generating kotlin client

- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/api.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/FakeApi.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Api/PetApi.cs
Apply fix from https://github.com/OpenAPITools/openapi-generator/pull/11272 to httpclient library
```
``` 
> [csharp-netcore] Fix: Add only first Authorization header 

- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
This PR intends to fix #6779. There's a bug in the native Java generator that forces the _Content-Type_ and _Accept_ headers of every endpoint of the generated client to `application/json`, even though a different media-type is specified in the spec.
I have let `application/json` as a default value in case no media-type is found for a given endpoint. I made sur the _Accept_ header contains all possible values referenced in the responses in the spec, as opposed to the _Content-Type_ header where I only selected the first media-type found in the _consumes_ array variable since this header only accepts one value, as per the HTTP standard.
I have tested this fix on a company project by using a template with `api.mustache`, which has proven to give the expected results. We are using this …
> [Java][Native] Fix the Content-Type and Accept headers that were forced to application/json

- modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache
- samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiClient.java
when i use java-sdk  generated by  openapi-generater (library:apache-httpclient). 
below code is not work
```
apiClient.setBasePath("https://{host}:{port}");
```
the reason is  method: ApiClient#buildUrl()
```
private String buildUrl(String path, List<Pair> queryParams, List<Pair> collectionQueryParams) {
String baseURL;
if (serverIndex != null) {
if (serverIndex < 0 || serverIndex >= servers.size()) {
throw new ArrayIndexOutOfBoundsException(String.format(
"Invalid index %d when selecting the host settings. Must be less than %d", serverIndex, servers.size()
));
}
baseURL = servers.get(serverIndex).URL(serverVariables);
} else {
baseURL = basePath;
}
....
```
the variable serverIndex default is 0.  so the baseUrl always is  the serverIndex  of servers 
if we don't  serverIndex = null . …
> [Java] fix java apache-httpclient set basePath

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/api/PingApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/api/DefaultApi.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-nextgen/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/UserApi.java
```
``` 
If an API does not define a custom ContentType, an empty …
> [Java-okhttp-gson] Do not set content-type if content type is null #2

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerDeprecatedCodegen.java
Bugfix for #11327.
It happens because there is no action to process the `library` additional properties. In this PR, I propose to add that logic based on [this code](https://github.com/OpenAPITools/openapi-generator/blob/5bccbf6734e82184e8a4aba0d2bb46a28bfb7276/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L421-L423). I have checked to re-generate kotlin client from the specification yaml. Now It works as expected.
cc @jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m
```
``` 
These must …
> [KOTLIN][CLIENT] fix unused `library` additional properties on kotlin generator

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Clean up default type mapping (invalid entries)
```
``` 
> Clean up default type mapping

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
Better checking for security definitions
- incorrect `http` schema type
- incorrect flow definition
- unknown type
```
``` 
> Better checking for security definitions

- modules/openapi-generator/src/main/resources/go/model_oneof.mustache
Trying to address issue  https://github.com/OpenAPITools/openapi-generator/issues/7961 
The idea of the fix is we use the same code of useOneOfDiscriminatorLookup(false) of the condition useOneOfDiscriminatorLookup(true) and  discriminator is not defined.
Validation:
1. Have oneOf without discriminator in the openapi spec
2. Use `useOneOfDiscriminatorLookup: true` to generate golang client
3. Generated code can be compiled and the code will unmarshal each struct
```
```  …
> Handling golang client generation for oneOf with no discriminator and useOneOfDiscriminatorLookup is true

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
- samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/model/Category.kt
- samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/model/ModelApiResponse.kt
- samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/model/Order.kt
- samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/model/Pet.kt
- samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/model/Tag.kt
- samples/server/petstore/kotlin/vertx/src/main/kotlin/org/openapitools/server/api/model/User.kt
Bugfix for #9175
It occurred because there is no `modelMutable` boolean parser. So the value will be treated as a string instead of a boolean.
cc @jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m
```
``` 
> [KOTLIN] add `modelMutable` additional properties parser

- modules/openapi-generator/src/main/resources/Java/RFC3339DateFormat.mustache
The implementation of clone method has been fixed to call `super.clone()` instead just `return this`.
The opened issue related is #11311 
```
``` 
> [JAVA] Fix clone method in RFC3339DateFormat template class

- modules/openapi-generator/src/main/resources/csharp-netcore/GlobalConfiguration.mustache
[csharp-netcore] corrected visibility of GlobalConfiguration mustache
The visibility of the `modules/openapi-generator/src/main/resources/csharp-netcore/GlobalConfiguration.mustache` is currently `public partial class GlobalConfiguration`. This should be defined as `{{>visibility}} partial class GlobalConfiguration`.
Otherwise you will get a compile error when parameter `nonPublicApi=true` is set.
```
```  …
> [csharp-netcore] Update GlobalConfiguration.mustache visibility definiton

- docs/configuration.md
- modules/openapi-generator-gradle-plugin/README.adoc
- modules/openapi-generator-maven-plugin/README.md
fix: #11375
Update docs to show the necessary usage of colons to separate **apis**, **models** and **supportingFiles**
```
``` 
> [docs] use correct separator

- .circleci/config.yml
- CI/circle_parallel.sh
- modules/openapi-generator/src/main/resources/python-experimental/tox.handlebars
- pom.xml
- samples/openapi3/client/petstore/python-experimental/pom.xml
- samples/openapi3/client/petstore/python-experimental/tox.ini
Turns on python-experimental CI tests
- v3 python and python-experimental tests are now running in a new node4 which is based upon a docker image
- all other nodes (0-3) will continue running on the defined machine. Previously they were parallel runs. They can be switched back to parallel if needed in the future.
```
``` 
For Windows …
> Turns on python-experimental CI tests

- modules/openapi-generator/src/main/resources/csharp-netcore-functions/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore-functions/libraries/httpclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
Tidy to remove redundant `useWebRequest` tag from template.  Does not appear to be used anywhere.
```
``` 
> tidy: [csharp-netcore] Remove redundant useWebRequest tag from templates

- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pojo.mustache
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/AdditionalPropertiesClass.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/ArrayOfArrayOfNumberOnly.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/ArrayOfNumberOnly.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/ArrayTest.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/EnumArrays.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/FileSchemaTestClass.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/MapTest.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/MixedPropertiesAndAdditionalPropertiesClass.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/Pet.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/TypeHolderDefault.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/TypeHolderExample.java
- samples/server/petstore/jaxrs-spec-interface/src/gen/java/org/openapitools/model/XmlItem.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/AdditionalPropertiesClass.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/ArrayOfArrayOfNumberOnly.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/ArrayOfNumberOnly.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/ArrayTest.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/EnumArrays.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/FileSchemaTestClass.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/MapTest.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/MixedPropertiesAndAdditionalPropertiesClass.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/Pet.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/TypeHolderDefault.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/TypeHolderExample.java
- samples/server/petstore/jaxrs-spec/src/gen/java/org/openapitools/model/XmlItem.java
- fix isArray, isMap tag in jaxrs spec templates
```
``` 
> [jaxrs][spec] fix isArray, isMap tags

- modules/openapi-generator/src/main/resources/crystal/partial_model_generic.mustache
- modules/openapi-generator/src/main/resources/crystal/spec_helper.mustache
- samples/client/petstore/crystal/pet_compilation_error_spec.cr
- samples/client/petstore/crystal/spec/api/pet_api_spec.cr
- samples/client/petstore/crystal/spec/models/pet_spec.cr
- samples/client/petstore/crystal/spec/models/tag_spec.cr
- samples/client/petstore/crystal/spec/spec_helper.cr
- samples/client/petstore/crystal/src/petstore/models/api_response.cr
- samples/client/petstore/crystal/src/petstore/models/category.cr
- samples/client/petstore/crystal/src/petstore/models/order.cr
- samples/client/petstore/crystal/src/petstore/models/pet.cr
- samples/client/petstore/crystal/src/petstore/models/tag.cr
- samples/client/petstore/crystal/src/petstore/models/user.cr
Closes #10721
Mark model properties as nillable when applicable, and also handle property serialization correctly.
@wing328 The model initializers are already using nillable types for parameters, this PR allows setting legitimate nil values to model properties
```
```  …
> [crystal][client] Make optional properties nillable in models

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CrystalClientCodegen.java
Checks if codegenParameter.items is null in constructExampleCode
Fix NullPointerException in constructExampleCode
Spec file to reproduce the issue: https://github.com/stripe/openapi/raw/master/openapi/spec3.json
```
``` 
> [crystal][client] Fix crystal code gen null pointer exception error in constructExampleCode

- docs/generators/java.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/build.sbt.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/play26/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/pom.mustache
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/api/UserApi.java
Remove options that have been marked as deprecated: `useRxJava`, `playVersion`
`useRxJava2`, `useRxJava3` have been marked as deprecated and will be removed in 6.x version (default to RxJava3 after that)
```
``` 
cc @bbdouglas (2017/07) @sreeshas …
> Remove deprecated options in Java client generator

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/fetch/TypeScriptFetchModelTest.java
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/models/index.ts
This make sure that date/datetime types are only typed as javascript date types with runtime checks are enabled. Otherwise it will be a string (the default).
WIP: Not much java experience, if someone with more experience could check this, would be greatly appreciated.
```
```  …
> Typescript-fetch: date is only converted to javascript date with runtime checks enabled

- modules/openapi-generator/src/main/resources/Java/libraries/feign/auth/OAuth.mustache
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/auth/OAuth.java
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/auth/OAuth.java
Fix duplicated Authorization headers when renewing a token on a retry
Add a leeway time to avoid a skew in the local clock
```
``` 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) …
> [Java] [Feign] Fix duplicated Authorization headers when renewing a token on a retry

- modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiResponseDecoder.mustache
The currently generated code will throw a `ClassCastException` if `type` is `Object`. I'm not quite sure why `isAssignableFrom` is used here but I tried to keep the change minimal - in my understanding, the result would be the same if the line was 
```
if(Types.getRawType(type).equals(ApiResponse.class)) {
``` 
because the `ApiResponse` only extends `Object` and implements no interfaces. Maybe it was meant to be `ApiResponse.class.isAssignableFrom(Types.getRawType(type))`? This would also permit subclasses of `ApiResponse`, but then it would be more complicated to determine the actual type parameter (because `type` itself may not be parameterized) and to create the object to return (because it would have to be an instance of the subclass).
Fixes #11509
``` …
```
> Fix ClassCastException if expected type is Object

- modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java
> [java][feign] fix javadoc warnings

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
Small fix that ensures the float literals (written for default values) in the generated C++ code are suffixed with an `f`. 
Before, this could cause a compile break because the literal would be interpreted as for example an integer before.
_Note: this might be different for certain C++ compilers, I've encountered this with GCC 10.2.1._
It's a bit of a hack but hey it works.
Also: I ran the generate-samples script and did not encounter any changed files, so maybe this is an edge case not caught by the examples.
```
```  …
> [C++][Pistache] fix float literals in C++ Pistache codegen

- modules/openapi-generator/src/main/resources/csharp-netcore/ClientUtils.mustache
- samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ClientUtils.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ClientUtils.cs
🐉 Possible breaking change: Method is public so upstream consumer *may* of used it, but library does not require it.
*  ClientUtils.UrlEncode method removed.
```
``` 
@mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) …
> tidy [csharp-netcore]: Remove unused UrlEncode method from csharp-netcore template.

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
- modules/openapi-generator/src/main/resources/scala-sttp/api.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/build.sbt.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/jsonSupport.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/project/build.properties.mustache
- samples/client/petstore/scala-sttp/build.sbt
- samples/client/petstore/scala-sttp/project/build.properties
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/PetApi.scala
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/StoreApi.scala
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/UserApi.scala
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/core/JsonSupport.scala
The sttp generator is out of date by atleast a year, sttp2 has been deprecated and i have updated the generator to now support sttp3.
```
``` 
- [  ] 
@chameleon82
> Upgrade Scala sttp client generator to sttp3

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-volley/build.mustache
Remove JDK 6, 7 supports in kotlin templates
```
``` 
> Remove JDK 6, 7 supports in kotlin templates

- modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
- modules/openapi-generator/src/test/resources/bugs/issue_11464.yaml
This PR fixed #11464.
If multble tags are defined the spring generator (with swagger2 annotations) insert a tag attribute for each tag which is defined in the spec.
```
```  …
> Fix for multible tags in @Operation annotation

- modules/openapi-generator/src/main/resources/php/api.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
`Configuration::getAccessToken()` returns an empty string, but API classes currently do a `null` check:
```php
if ($this->config->getAccessToken() !== null)
```
This will always be `true` whenever an endpoint allows access token auth.
```
``` 
> [PHP] Fix checking value of `Configuration::getAccessToken()`

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/multiplatform/build.gradle.kts.mustache
- samples/client/petstore/kotlin-multiplatform/build.gradle.kts
- The PR upgrades the Kotlin version used by the Kotlin Multiplatform template to version 1.6.0.
- Ktor is upgraded to version 1.6.4, the [the recommended version to use](https://kotlinlang.org/docs/releases.html#release-details) with Kotlin 1.6.0. 
Upgrading to 1.6.0 was [deliberately avoided](https://github.com/OpenAPITools/openapi-generator/pull/10900#discussion_r753263348) in #10900 because Jetpack Compose was not compatible with Kotlin 1.6.0. This issue is now resolved because Jetpack Compose can be used with Kotlin 1.6.0 when using [Compose compiler version 1.1.0-beta04](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.1.0-beta04).  
This change was validated in KMM demo project that uses this branch to generate the petstore sample code and Jetpack Compose: …
> [Kotlin][Multiplatform] Upgrade Kotlin to version 1.6.0

- modules/openapi-generator/src/main/resources/go/model_simple.mustache
The commit https://github.com/aeneasr/openapi-generator/commit/0c5e5aeccc9fa2ef392c8fd0a3dd0b219665ec5d in the PR :  https://github.com/OpenAPITools/openapi-generator/pull/8491 resolves the pointer issue, missed the logic to perform similar operation in case of Unmarshalling of the JSON.
Due to this, there is a mismatch between the data type(This issue is seen for array of object type property) between Dog type and DogWithoutEmbeddedStruct type(Present inside Unmarshalling method).
Applying the same logic mentioned in the above commit in UnmarshalJSON method.
```
```  …
> [GO] Fix for Pass by value/Pass by Reference changes which is breaking the go client

- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/enumClass.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/enumOuterClass.mustache
I'd like to fix issue #3995 with this PR (see my comments there). 
The fix creates an additional static method `fromString()` as required by the JAX RS spec, so that compliant implementations can correctly parse enum arguments whoose wire string representation differs from the Java enum field name (e.g. MyEnum.FOO vs. "foo"). As it stands right now, a JAX RS implementation would expect "FOO" as a value passed as parameter, so parsing "foo" will fail.
I've coded this fix against v4.3.1, as I ran into other issues with 5.0.0 in my project and did use 4.3.1 there; however I assume this can be merged into both the 4.3.x and 5.0.x lines. I couldn't find a release branch for 4.3.x, so this PR is made against `master` in the hope that it will also be patched into the 4.3.x line if accepted.
> [Java][jaxrs-spec] add fromString() method to generated enums as required by JAX RS spec

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/UserApi.java
Renaming local variable names.
fixes #11579: Java RestTemplate Mustache template doesn't use reserved words for local variables
```
``` 
> fixes #11579: Java RestTemplate Mustache template doesn't use reserved words for local variables

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
- samples/client/petstore/php/OpenAPIClient-php/tests/ObjectSerializerTest.php
Currently the `ObjectSerializer::deserialize()` does not work when passing a filename string for a `SplFileObject` type.
The `\GuzzleHttp\Psr7\Utils::streamFor()` has support for a wide-range of data, including strings, and converts them to a stream resource.
```
```  …
> [PHP] Allows passing filename to deserialize

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
fixes #6134
The method buildRequestBodyMultipart in ApiClient.java now recognizes if an input parameter is an instance of List. So it is possible for clients so send multiple files in one request. 
Tested by using the generated code in one of our webservices.
Since the existing Pull-Request [8197](https://github.com/OpenAPITools/openapi-generator/pull/8197) seems to be stuck, we made this one to apply the workaround (fixing the generated code) we are using for more than two years now.
```
``` 
You may …
> fix #6134 for okhttp-gson by considering the input type "List<File>" in ApiClient.mustache

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautAbstractCodegen.java
avoid Double Brace Initialization (DBI)
Ref: https://sonarcloud.io/project/issues?id=OpenAPITools_openapi-generator&open=AX6U-J6KoKSjET3uZBKf&resolved=false&types=BUG
cc @andriy-dmytruk
```
``` 
> [java][Micronaut] avoid Double Brace Initialization (DBI)

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
- samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
Moved static logic to initialization method for when no RestTemplate is provided.
Otherwise, use the settings from the RestTemplate that was provided. (Wired by spring)
```
``` 
**Help me on this one: this needs to go into 5.3.2, 5.4.1 and 6.0.x** …
> [Java][RestTemplate] Use class level RestTemplate for uri encoding

- modules/openapi-generator/src/main/resources/Java/beanValidation.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/beanValidation.mustache
- modules/openapi-generator/src/main/resources/JavaSpring/beanValidation.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/spring/issue_5026-b.yaml
- modules/openapi-generator/src/test/resources/3_0/spring/issue_5026.yaml
fixes #5026
This duplicates #5960 (which was stale because of missing feedback/updates from creator).
@bbdouglas  @sreeshas @jfiala  @lukoyanov @cbornet @jeff9finger @karismann  @Zomzog  @lwlee2608 @nmuesch 
```
``` 
> [java] No @NotNull annotation for readOnly (required) attributes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ProtobufSchemaCodegen.java
- samples/config/petstore/protobuf-schema/models/order.proto
- samples/config/petstore/protobuf-schema/models/pet.proto
possible fix for #11484
Adds prefix based on enum name to all enum values.
> [Protobuf-Schema] Add enum prefix

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
- modules/openapi-generator/src/main/resources/typescript-fetch/modelGenericInterfaces.mustache
Fixes https://github.com/OpenAPITools/openapi-generator/issues/11522
Similar to the `axios` and `angular` versions:
https://github.com/OpenAPITools/openapi-generator/pull/9505
https://github.com/OpenAPITools/openapi-generator/pull/6973
> typescript-fetch: Support deprecated parameters, operations

- docs/generators/java.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
Fix the typo error "proeprties" to properties inside the gradleProperties config for java generator
```
``` 
> :pencil2: Fixed typo error on java generator config-help command

- modules/openapi-generator/src/main/resources/go/api.mustache
- samples/client/petstore/go/go-petstore/api_another_fake.go
- samples/client/petstore/go/go-petstore/api_fake.go
- samples/client/petstore/go/go-petstore/api_fake_classname_tags123.go
- samples/client/petstore/go/go-petstore/api_pet.go
- samples/client/petstore/go/go-petstore/api_store.go
- samples/client/petstore/go/go-petstore/api_user.go
- samples/client/petstore/go/go.mod
- samples/client/petstore/go/go.sum
- samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/api_usage.go
- samples/openapi3/client/petstore/go/go-petstore/api_another_fake.go
- samples/openapi3/client/petstore/go/go-petstore/api_default.go
- samples/openapi3/client/petstore/go/go-petstore/api_fake.go
- samples/openapi3/client/petstore/go/go-petstore/api_fake_classname_tags123.go
- samples/openapi3/client/petstore/go/go-petstore/api_pet.go
- samples/openapi3/client/petstore/go/go-petstore/api_store.go
- samples/openapi3/client/petstore/go/go-petstore/api_user.go
Originally, this dummy declaration was needed because there was the possibility of the generated code doesn't use `context.Context` and then if it imported that package, go compiler complains that and makes an error.
ref: https://github.com/OpenAPITools/openapi-generator/blob/3ed1aa8e79687bed63dfa064de27317273080471/modules/swagger-codegen/src/main/resources/go/api.mustache#L30
However, now this dummy placement is no longer needed because the generated code always uses `context.Context`.
So this pull request removes that dummy declaration.
cc. @antihax @grokify @kemokemo @jirikuncar @ph4r5h4d
```
```  …
> Remove dummy variable declaration for context.Context from generated go code

- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
This PR intends to fix #11638. There's a bug in the native Java generator that alters a request if the request body of an endpoint is a formatted String like XML.
By using a method specific for Strings in the request builder, I've found that it fixes the problem. The body parameter is no longer altered with surrounding double quotes and escape characters.
For further information on how to validate my work, please refer to the linked issue.
```
``` 
I'm tagging the technical committee responsible for the Java generator: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608
> [Java][Native] Fix an issue leading to an altered String parameter when consuming formatted strings like XML

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonLegacyClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonLegacyClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_11521.yaml
This removes some code that was not correctly generating regex validation patterns. It's basically a revert of #10920 and fixes #11521.
Technical team: 
@taxpon 
@frol
@mbohlool 
@cbornet
@kenjones-cisco 
@tomplus 
@Jyhess 
@arun-nalla 
@spacether
```
```  …
> [Python] python regex validation generation

- docs/generators/aspnetcore.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
Aspnet 6.0 is almost upon us. This pull request introduces basic generation capabilities. The generated code won't run until the 6.0.0 packages are published, so maybe we delay the merge until 10.11. 
In general we might want to think about getting rid of the support for aspnet 2.1 and below, would simplify a lot of the code and its out of support anyway.
```
```  …
> [Csharp][aspnet] Aspnet 6.0 Support

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java
> Better code format in c#, aspnet generators

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/spring/issue_11323.yml
A CodegenModel's hasEnum property is set in addVars:
cm.hasEnums = true;
This state was cleared afterwards again.
As one of its results the import for @JsonValue was not added for the model class in the Spring code generator, where 'model.hasEnums' was evaluated to false where it should be true.
Added a test case with the model provided in the issue that reproduces the problem.
> [#11323] Fixed wrong clearing of CodegenModel#hasEnum field

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/cpp-tizen-client/api-body.mustache
- modules/openapi-generator/src/main/resources/cpp-tizen-client/requestinfo.mustache
- samples/client/petstore/c/src/apiClient.c
- samples/client/petstore/cpp-tizen/src/PetManager.cpp
- samples/client/petstore/cpp-tizen/src/RequestInfo.h
- samples/client/petstore/cpp-tizen/src/StoreManager.cpp
- samples/client/petstore/cpp-tizen/src/UserManager.cpp
`{{/isOAuth}}
{{/authMethods}}
{{/hasAuthMethods}}
if(bodyParameters != NULL) {
postData(handle, bodyParameters);
}
res = curl_easy_perform(handle);
curl_slist_free_all(headers);   // curl_slist_freeList_all -> curl_slist_free_all
free(targetUrl);
if(res == CURLE_OK) {
curl_easy_getinfo(handle, CURLINFO_RESPONSE_CODE, &apiClient->response_code);
} ``
```  …
```
> rollback curl_list_free keyword

- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue4808.yaml
Fixes #4808 by properly setting exploded query params
```
``` 
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @wing328
> [Java][native] Properly encode exploded query params in url

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaClientCodegen.java
- modules/openapi-generator/src/main/resources/scala-akka-client/class_doc.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/enum_doc.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/model_doc.mustache
- samples/client/petstore/scala-akka/.openapi-generator/FILES
- samples/client/petstore/scala-akka/README.md
- samples/client/petstore/scala-akka/docs/ApiResponse.md
- samples/client/petstore/scala-akka/docs/Category.md
- samples/client/petstore/scala-akka/docs/Order.md
- samples/client/petstore/scala-akka/docs/Pet.md
- samples/client/petstore/scala-akka/docs/Tag.md
- samples/client/petstore/scala-akka/docs/User.md
Scala Akka Client contains references to Model Docs that aren't present in the generated source code. This PR fixes that by adding those docs, resolving this issue #10242
```
``` 
> Add Model Docs to scala-akka generator as defined in its README

- modules/openapi-generator/src/main/resources/swift5/api.mustache
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/AnotherFakeAPI.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeClassnameTags123API.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/StoreAPI.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/UserAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/AnotherFakeAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeClassnameTags123API.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/StoreAPI.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/APIs/UserAPI.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/AnotherFakeAPI.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeAPI.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/FakeClassnameTags123API.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/PetAPI.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/StoreAPI.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/APIs/UserAPI.swift
The parameter `apiResponseQueue` doesn't have any impact in Async/Await, Combine and PromiseKit, so I removed it in that configuration.
```
``` 
> [swift5][client] remove apiResponseQueue in the clients that don't have any impact

- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientDeepObjectTest.java
- modules/openapi-generator/src/test/resources/3_0/deepobject.yaml
This PR extends src/main/resources/Java/libraries/native/api.mustache to handle arrays within deepObject
#11697
Please have a look at the extended test class and test document:
* modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientDeepObjectTest.java
* modules/openapi-generator/src/test/resources/3_0/deepobject.yaml
```
```  …
> [java native] Support arrays in QueryParameters deepObject style

- modules/openapi-generator/src/main/resources/kotlin-spring/apiDelegate.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/spring/KotlinSpringServerCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/kotlin/issue7325-use-delegate-reactive-tags-kotlin.yaml
This PR fixes the problem described in issue [#9902](https://github.com/OpenAPITools/openapi-generator/issues/9902), which I'll summarize here:
* For the `kotlin-spring` generator, with `delegatePattern` and `reactive` set to true, the generated API file should use a Kotlin coroutine-type `Flow` when dealing with an OpenAPI `array` data type.
* For a `requestBody` parameter, it does this for a generated API class, but _not_ for a generated Delegate class. In generated Delegate classes, an array type that is the request body is generated as a `kotlin.collections.List` instead of a `Flow`.
* This is not only incorrect, it also means the generated code does not compile, as the API class is attempting to pass a `Flow` to a Delegate that is expecting a `kotlin.collections.List`.
To fix this, I …
> [kotlin-spring] fix #9902 use coroutine Flow for arrays in delegate when reactive=true

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java
- samples/client/petstore/cpp-qt/client/PFXPet.h
- samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/model/Pet.h
This makes sure all model classes are added to the forward declarations which makes it possible to create templates without any model includes.
This helps to resolve circular inclusion issues.
This adds more forward declarations of which a lot are not strictly needed by the current templates, but they don't harm either. Trying to detect in which case declarations are needed or not or making it configurable does not seem to be worth the effort and would add a lot of complexity.
If you have a spec like this:
``` 
openapi: 3.0.1
info:
title: Libre Graph API
version: v0.9.0
license:
name: Apache 2.0
url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://ocis.ocis-traefik.latest.owncloud.works/
description: ownCloud Infinite Scale Latest
paths: {}
components:
schemas: …
```
> [C++] Simplify forward declaration detection

- modules/openapi-generator/src/main/resources/cpp-qt-client/ServerConfiguration.mustache
I am compiling this on a sligthtly older Qt version (Qt 5.6) with a slightly older compiler and I encounter the following error:
```
error: no matching conversion for functional-style cast from 'QByteArray' to 'std::runtime_error'
```
This is easily mitigated and the solution is forward-compatible. The problem is simply because of mising cast operator from `QByteArray` to `std::string` on older Qt version. This solution should support all Qt versions.
```
```  …
> Bug Fix: Cast from QByteArray to std::runtime_error

- bin/configs/java-okhttp-gson.yaml
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/oneof_model.mustache
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Mammal.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/NullableShape.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Pig.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Quadrilateral.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Shape.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ShapeOrNull.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Triangle.java
- samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/JSONTest.java
- Fix oneOf discriminator lookup in java okhttp-gson client
- Add tests
```
```  …
> Fix oneOf discriminator lookup in java okhttp-gson client

- modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/feign/auth/OAuth.mustache
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/feign-no-nullable/src/main/java/org/openapitools/client/auth/OAuth.java
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/feign/src/main/java/org/openapitools/client/auth/OAuth.java
Fix typo in Java Feign client
```
``` 
> Fix typo in Java Feign client

- modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache
- samples/client/petstore/cpp-qt/client/PFXPetApi.cpp
- samples/client/petstore/cpp-qt/client/PFXStoreApi.cpp
- samples/client/petstore/cpp-qt/client/PFXUserApi.cpp
Fix typo in C++ QT client
```
``` 
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)
> Fix typo in C++ QT client

- modules/openapi-generator/src/main/resources/Java/libraries/webclient/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache
- samples/client/petstore/java/webclient-nulable-arrays/build.gradle
- samples/client/petstore/java/webclient-nulable-arrays/pom.xml
- samples/client/petstore/java/webclient/build.gradle
- samples/client/petstore/java/webclient/pom.xml
The spring-boot-starter-webflux uses
io.projectreactor.netty:reactor-netty-http
dependency so the io.projectreactor.ipc:reactor-netty
is actually not used at all
```
```  …
> [Java] Fix reactor-netty dependency

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
I have encountered this issues when I want to pass an api key in the request but the endpoint support multiple header api key. 
So I use a fonction to set the right api key and set the other api key to `undefined`.
With this code : 
```
function getFirstApiKey(keyName) {
if (keyName === 'first-api-key') {
return "my-key-value";
}
return undefined;
};
```
The generated code for api key in the api endpoint : 
```
if (this.configuration && this.configuration.apiKey) {
headerParameters["first-api-key"] = this.configuration.apiKey("first-api-key"); // first-api-key authentication
}
if (this.configuration && this.configuration.apiKey) {
headerParameters["second-api-key"] = this.configuration.apiKey("second-api-key"); // second-api-key authentication
}
```
The generated `apiKey` function : 
``` …
```
> [typescript-fetch] Remove undefined headers

- modules/openapi-generator/src/main/resources/ruby-client/partial_oneof_module.mustache
This must be a very rare case but we are using a boolean property as discriminator:
```yaml
CarOrCustomCar:
oneOf:
- $ref: '#/components/schemas/Car'
- $ref: '#/components/schemas/CustomCar'
discriminator:
propertyName: custom_flag
mapping:
true: '#/components/schemas/CustomCar'
false: '#/components/schemas/Car'
CustomCar:
properties:
:
custom_flag:
type: boolean
Car:
properties:
:
custom_flag:
type: boolean
```
The [OpenAPI specification](https://swagger.io/specification/#discriminator-object) says:
> Mapping keys MUST be string values, but tooling MAY convert response values to strings for comparison.
So I think we can modify to handle boolean values property for discriminator.
```
``` 
Commit all …
> [ruby] Allow boolean for discriminator value in oneOf handling

- docs/generators/kotlin-spring.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java
- modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache
- modules/openapi-generator/src/main/resources/kotlin-spring/apiController.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/spring/KotlinSpringServerCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/kotlin/bean-qualifiers.yaml
```
``` 
-  @jimschubert , @dr4ke616 , @karismann , @Zomzog , @andrewemery , @4brunu , @yutaka0m
P.S.: Yes, i do understand that indented behaviour can be archived using customized templates (and we are using them right now). But i feel that this setting …
> [kotlin-spring] Add beanQualifiers switch to populate RestController / Controller annotations with FQCN

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultGeneratorTest.java
- modules/openapi-generator/src/test/resources/bugs/recursion-bug-4650.yaml
The generator ran into a loop when a composite schema recursively added itself. This change provides a reproducing example and fixes the issue by extending DefaultCodegen#addProperties() by an additional circuit breaker parameter.
When additionalProperties() is called with a schema instance for which the properties have already been added, the method directly returns and does not run into the loop.
To fix #4650
> [#4650] Fix StackOverflowError for recursive composite schemas

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/content-data.yaml
In #11046 a bug was introduced regarding the fetching of reference headers.
As ModelUtils.getReferencedHeader wasn't called in all cases before headerToCodegenParameter was.
So now it's called inside headerToCodegenParameter as the first thing after null checking the header.
```
```  …
> [DefaultCodegen] GetReferenceHeader for both calls of headerToCodegenParameter

- modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
Modifying the JavaSpring/api.mustache template to insert description value in @Operation annotation (related to issue #11779)
```
``` 
> Fix for issue #11779

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ConfluenceWikiCodegen.java
The Confluence Markup needs to escape some characters.
```
``` 
> Confluence Wiki - Escape special characters

- modules/openapi-generator/src/main/resources/JavaJaxRS/pom.mustache
- samples/server/petstore/jaxrs-datelib-j8/pom.xml
- samples/server/petstore/jaxrs-jersey/pom.xml
- samples/server/petstore/jaxrs/jersey2-useTags/pom.xml
- samples/server/petstore/jaxrs/jersey2/pom.xml
JDK17 is missing class `javax.annotation.Generated`.
Add javax.annotation:javax.annotation-api 1.3.2
Fixes https://github.com/OpenAPITools/openapi-generator/issues/11795
```
``` 
> Fix jaxrs-spec to run with JDK 17

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
For some buggy configurations, a warning is emitted indicating that for a given request body the corresponding `CodegenModel` could not be found. When this happens, some generators produce NPEs when writing out example code. This change avoids the NPEs by providing a stub value instead.
This is similar in spirit to #11170, and addresses the same set of generators.
```
```  …
> [Go][Ruby][PowerShell] Fix example generation when missing models

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaInflector/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/eap/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/spec/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaPlayFramework/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaVertXServer/pojo.mustache
- modules/openapi-generator/src/main/resources/JavaVertXWebServer/pojo.mustache
- modules/openapi-generator/src/main/resources/java-msf4j-server/pojo.mustache
- modules/openapi-generator/src/main/resources/java-pkmst/pojo.mustache
- modules/openapi-generator/src/main/resources/java-undertow-server/pojo.mustache
Fix for https://github.com/OpenAPITools/openapi-generator/issues/11636
```
``` 
> [Java] support x-implements

- modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
Using the conditional serialization flag with the csharp-netcore generator each of the properties has a correspondent flag property that determines if it has or not to be serialized when the method toJson gets called.
Using the setters of the properties it works as expected, the flags are set as they have to and the serialized json is alright, but if we set the class properties with the constructor, none of the flags gets set to true, so using the toJson method we get an empty json. This solution checks in the constructor if each property is null or not, if it isn’t, the according flag gets set to true.
``` …
```
> [csharp-netcore] Fixed csharp netcore conditional serialization

- modules/openapi-generator/src/main/resources/C-libcurl/list.h.mustache
Fix Wrong keyword to list_createList and list_freeList keyword. 
"before"
`list_t* List();
void list_freeListList(list_t* listToFree);`
"after"
`list_t* list_createList();
void list_freeList(list_t* listToFree);`
```
``` 
> Fix list keyword

- docs/generators/groovy.md
- docs/generators/java-camel.md
- docs/generators/java-inflector.md
- docs/generators/java-micronaut-client.md
- docs/generators/java-micronaut-server.md
- docs/generators/java-msf4j.md
- docs/generators/java-pkmst.md
- docs/generators/java-play-framework.md
- docs/generators/java-undertow-server.md
- docs/generators/java-vertx-web.md
- docs/generators/java-vertx.md
- docs/generators/java.md
- docs/generators/jaxrs-cxf-cdi.md
- docs/generators/jaxrs-cxf-client.md
- docs/generators/jaxrs-cxf-extended.md
- docs/generators/jaxrs-cxf.md
- docs/generators/jaxrs-jersey.md
- docs/generators/jaxrs-resteasy-eap.md
- docs/generators/jaxrs-resteasy.md
- docs/generators/jaxrs-spec.md
- docs/generators/spring.md
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/VendorExtension.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
Describe vendor extensions used by specific generator
```
``` 
> Document all used vendor extensions in specific generator

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
Fix warnings due to incorrect docstring
- warning - Tag @link: reference not found: org.openapitools.client.ApiClient
- warning - Tag @link: reference not found: org.threeten.bp.format.DateTimeFormatter
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) …
> [java][okhttp-gson] Fix warnings due to incorrect docstring

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-array-simple-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
When using kotlin client in Android, we should warn the users about the flag `supportAndroidApiLevel25AndBelow` to that they make an informed decision
```
``` 
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) …
> [kotlin][client] create comment to warn about android api version

- modules/openapi-generator/src/main/resources/ruby-client/api.mustache
- modules/openapi-generator/src/main/resources/ruby-client/api_doc.mustache
- samples/client/petstore/ruby-faraday/docs/FakeApi.md
- samples/client/petstore/ruby-faraday/lib/petstore/api/fake_api.rb
- samples/client/petstore/ruby/docs/FakeApi.md
- samples/client/petstore/ruby/lib/petstore/api/fake_api.rb
This PR introduces support for `x-group-parameters` in the `ruby-client` templates, similar to how it has been added to PHP (#1337) and others in the past.
This helps prevent breakage if the order of parameter documentation changes, and at Fastly helped us in writing data-driven tests. (Other use cases #641 #5451)
Support for grouped parameters already exists in the Codegen, so these changes are completely self-contained in template files only. Unfortunately it seems tests for the API files in the Ruby client file have not existed, and for now I didn't have the time to draft them from scratch.
I'm branching from 6.0.x as I believe this can be considered breaking. The existence of `x-group-parameters` is automatically picked up from input files, and the updated generated client will break …
> [Ruby] Add x-group-parameters support to Ruby client

- docs/generators/go-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoServerCodegen.java
In response to the ongoing conversation in https://github.com/OpenAPITools/openapi-generator/issues/3547, I added two flags to the `go-server` generator.
`outputAsLibrary` generates output intended to be included in a larger go project. It removes the `Dockerfile`, `main.go`, and `go.mod` from the rendered output.
`onlyInterfaces` removes the factory functions `New{{classname}}Service`, which expects implementations to be added to the generated templates, and those templates to be added to `.openapi-generator-ignore`.
Using both flags together will create a package that can be incorporated in an existing project, and whose service must be implemented in the composition root of the larger project, rather than in the generated output files.
This is a small step towards the larger goal of …
> Optional outputAsLibrary, onlyInterfaces parameters

- modules/openapi-generator/src/main/resources/go/model_oneof.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/oneOf_primitive.yaml
A recent enhancement to the template made these primitive types usable as property names, but a small section of the template wasn't updated, leading to compilation problems.
See the added test case for an example.
```
``` 
For Go, @antihax @grokify …
> [Go] Fix template for oneOfs with primitive types

- modules/openapi-generator/src/main/resources/python/README_common.mustache
- samples/openapi3/client/extensions/x-auth-id-alias/python/README.md
- samples/openapi3/client/features/dynamic-servers/python/README.md
Added a newline in the README_common.mustache to fix the wrong indentation in the generated README.md file:
Example openapi.yaml: https://github.com/bundesAPI/weiterbildungssuche-api/blob/main/openapi.yaml
Problematic Section before change:
```python
with openapi_client.ApiClient(configuration) as api_client:
api_instance = default_api.DefaultApi(api_client)
sw = "IT-Security%2520-%2520allgemein" # str | Suchwort (optional)
ort = "Feucht_90537_11.224918_49.376701" # str | Ortsangabe nebst Postleitzahl und Koordinaten (optional)
page = 1 # int | Ergebnissseite (optional)
size = 50 # int | Anzahl von Ergebnissen (optional)
re = "BW" # str | Region/Bundesland - BW=Baden-Württemberg, BY=Bayern, BE=Berlin, BB=Brandenburg, HB=Bremen, HH=Hamburg, HE=Hessen, MV=Mecklenburg-Vorpommern, …
```
> [Python] Fix to remove wrong intendation in generated README.md

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaClientCodegen.java
- modules/openapi-generator/src/main/resources/scala-akka-client/README.mustache
- modules/openapi-generator/src/main/resources/scala-akka-client/api_doc.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/scalaakka/ScalaAkkaClientCodegenTest.java
- samples/client/petstore/scala-akka/.openapi-generator/FILES
- samples/client/petstore/scala-akka/README.md
- samples/client/petstore/scala-akka/docs/PetApi.md
- samples/client/petstore/scala-akka/docs/StoreApi.md
- samples/client/petstore/scala-akka/docs/UserApi.md
Adds API Docs to the scala-akka client, as requested in #5795
```
``` 
> Add auto-generated doc to scala-akka client

- modules/openapi-generator/src/main/resources/csharp-netcore-functions/libraries/httpclient/ApiClient.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Client/ApiClient.cs
Fixes #10588.
OpenAPI responses with binary content have a method generated that returns a `FileParameter` with the csharp-netcore generator, but this type can't actually be deserialized properly when the call is made, resulting in an error. The type is simply a wrapper for a stream, so reading the stream and creating the `FileParameter` is sufficient to fix the problem.
Testing done is that we've tried this fix proposed in #10588 successfully and are using it in production with an OpenAPI that has the following 200 response definition for a GET request that downloads a file:
```json
{
"description": "The call was successful.",
"content": {
"image/png": {
"schema": { "type": "string", "format": "binary" }
}
}
}
```
``` …
```
> [csharp-netcore] Fix incorrect FileParameter deserialization

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
- modules/openapi-generator/src/main/resources/go/model_oneof.mustache
- modules/openapi-generator/src/test/resources/3_0/go/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
- samples/openapi3/client/petstore/go/go-petstore/api/openapi.yaml
- samples/openapi3/client/petstore/go/go-petstore/model_one_of_primitive_type.go
- fix oneOf naming by using a lambda in the template to handle more cases (e.g.  array of string: []string)
- add tests
To fix https://github.com/OpenAPITools/openapi-generator/issues/11842
```
``` 
cc @antihax @grokify @kemokemo @jirikuncar @ph4r5h4d
> [Go] fix oneOf naming

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlim4ServerCodegen.java
- modules/openapi-generator/src/main/resources/php-slim4-server/github_action.yml.mustache
- samples/server/petstore/php-slim4/.github/workflows/main.yml
- samples/server/petstore/php-slim4/.openapi-generator/FILES
I used that [example](https://github.com/shivammathur/setup-php/blob/master/examples/slim-framework.yml) as reference.
The most interesting part is that I've checked it with a fresh repo, output:
[First run without coding style check](https://github.com/ybelenko/petstore-server-slim4/actions/runs/1983790520)
[Second run, coding style check on](https://github.com/ybelenko/petstore-server-slim4/actions/runs/1983804159)
I think that failed CI(links above) is absolutely normal regarding this PR, since coding style fix should be added in next PRs. The purpose of this change is to generate CI config which launches GitHub runners without errors(correct syntax).
Relative issue #11858 
``` …
```
> [php-slim4] Add minimal GitHub Action config

- docs/generators/java-micronaut-client.md
- docs/generators/java-micronaut-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautAbstractCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautServerCodegen.java
- modules/openapi-generator/src/main/resources/java-micronaut/client/params/type.mustache
- modules/openapi-generator/src/main/resources/java-micronaut/common/model/jackson_annotations.mustache
- modules/openapi-generator/src/main/resources/java-micronaut/server/params/type.mustache
- samples/client/petstore/java-micronaut-client/docs/apis/FakeApi.md
- samples/client/petstore/java-micronaut-client/docs/models/FormatTest.md
- samples/client/petstore/java-micronaut-client/docs/models/MixedPropertiesAndAdditionalPropertiesClass.md
- samples/client/petstore/java-micronaut-client/docs/models/Order.md
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/api/FakeApi.java
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/api/UserApi.java
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/model/FormatTest.java
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/model/MixedPropertiesAndAdditionalPropertiesClass.java
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/model/Order.java
- samples/server/petstore/java-micronaut-server/docs/models/Order.md
- samples/server/petstore/java-micronaut-server/src/main/java/org/openapitools/controller/UserController.java
- samples/server/petstore/java-micronaut-server/src/main/java/org/openapitools/model/Order.java
(Rebased version of the https://github.com/OpenAPITools/openapi-generator/pull/11778 to exclude lots of previous commits)
This change is made based on this issue: https://github.com/OpenAPITools/openapi-generator/issues/11694
Additional fix for error of target files generated outside output directory in the maven plugin.
I ran the following to build and test the project:
```
./bin/meta-codegen.sh
./mvnw integration-test -P java-micronaut-client -P java-micronaut-server
```
@wing328 @pfyod
Java technical committee (not sure if required):
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608
> [Micronaut] Add support for OffsetDateTime for Micronaut generators

- modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/pom.mustache
- samples/client/petstore/java/native-async/build.gradle
- samples/client/petstore/java/native-async/pom.xml
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/native/build.gradle
- samples/client/petstore/java/native/pom.xml
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/ApiClient.java
This PR includes the updates below:
- Add set/get for connection timeout
- bump jackson version to 2.13.0
- updated the samples via ./bin/generate-samples.sh;
```
``` 
@wing328 @sebastien-rosset @cbornet @jeff9finger @bbdouglas @sreeshas @jfiala …
> [java][native] add connection timeout

- modules/openapi-generator/src/main/resources/kotlin-spring/api.mustache
- modules/openapi-generator/src/main/resources/kotlin-spring/apiInterface.mustache
Rename extension to conform to kebab-case: x-contentType => x-content-type
```
``` 
> [kotlin][spring] Rename extension to conform to kebab-case

- modules/openapi-generator/src/main/resources/swift5/Models.mustache
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/Models.swift
When the `NullEncodable` the public vs non public visibility modifier was forgotten.
This PR fixes that.
```
``` 
> [swift5][client] fix non public visibility modifier for NullEncodable

- samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/JSONComposedSchemaTest.java
Fix test failure due to different error message based on JDK version
```
``` 
> Fix test failure due to different error message based on JDK version

- modules/openapi-generator/src/main/resources/python/model_templates/methods_shared.mustache
- samples/client/petstore/python/petstore_api/model_utils.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/model_utils.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/model_utils.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/model_utils.py
- samples/openapi3/client/petstore/python/petstore_api/model_utils.py
Implements the recommended fix for issue #10856, a Python client bug in the mustache template that causes model copies to fail due to trying to return an undefined object.
Changes the template for the `__copy__` method to return `cls.__new__(cls, **self.__dict__)` instead of `new_cls.__new__(cls, **self.__dict__)`
Tagging Python committee:
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess @arun-nalla @spacether
```
```  …
> Fix undefined object in Python model __copy__ template

- modules/openapi-generator/src/main/resources/Ada/server.mustache
"Connect you browser" -> "Connect your browser"
```
``` 
@stcarrez
> [Ada] Fix typo in final Info message

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java
Fix the exception in python flask generator's option handling (boolean vs string)
To fix https://github.com/OpenAPITools/openapi-generator/issues/11854
```
``` 
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco …
> Fix the exception in python flask generator's option handling

- modules/openapi-generator/src/main/resources/kotlin-server/libraries/jaxrs-spec/api.mustache
- samples/server/petstore/kotlin-server/jaxrs-spec/src/main/kotlin/org/openapitools/server/apis/PetApi.kt
- samples/server/petstore/kotlin-server/jaxrs-spec/src/main/kotlin/org/openapitools/server/apis/StoreApi.kt
- samples/server/petstore/kotlin-server/jaxrs-spec/src/main/kotlin/org/openapitools/server/apis/UserApi.kt
Remove obsolete imports from `kotlin-server/libraries/jaxrs-spec/api.mustache`. These two removed Java imports are not used but trigger warnings by the Kolin compiler.
```
[WARNING] This class shouldn't be used in Kotlin. Use kotlin.collections.Map or kotlin.collections.MutableMap instead.
[WARNING] This class shouldn't be used in Kotlin. Use kotlin.collections.List or kotlin.collections.MutableList instead.
```
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as …
> [kotlin-server][jaxrs-spec] Remove obsolete imports from API template

- docs/generators/python-experimental.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java
- Only allow v3 input specs into python-experimental
- Removes library options that python-experimental does not support
```
``` 
> Only allow v3 input specs into python-experimental

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- modules/openapi-generator/src/main/resources/php/api.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
- samples/client/petstore/php/OpenAPIClient-php/tests/ObjectSerializerTest.php
- samples/client/petstore/php/OpenAPIClient-php/tests/ParametersTest.php
- samples/client/petstore/php/OpenAPIClient-php/tests/RequestTest.php
This fixes #11222 
The [Query::build()](https://github.com/guzzle/psr7/blob/master/src/Query.php#L71) function does not support deepObjects in query params, but the [OpenAPI defintion](https://swagger.io/docs/specification/serialization/) does. 
> `/users?id[role]=admin&id[firstName]=Alex` an example from the docs.
I have replaced the `Query::build()` function with PHP's internal [http_build_query](https://www.php.net/http_build_query) function. I have adjust PHP default encoding to match the default encoding from `Query::build()` which is `PHP_QUERY_RFC3986`.
This change will only have an effect for the query string of the URL, encoding POST bodys is still done by `Query::build()`.
> [php] use http_build_query for deepObject support

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
- samples/client/petstore/c/model/pet.c
When a list or map JSON cannot to be parsed successfully,  the original code will goto the end of function `*_parseFromJSON` without freeing the memory of the list or map.
This PR fixes this memory leak.
```
``` 
> [C][Client] Free list or map memory when json parsing fails

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/petstore-multiple-required-properties-has-same-oneOf-object.yaml
Go client generator will hit  StringIndexOutOfBoundsException when the object (petPreference) has multiple (2+) required fields (pet1, pet2, pet3) that pointing to the same object (pet).
The code triggering the error coming from the `processedMap` that checks if the same model is in an infinite loop, and returns an empty string when more than two stimes cause this error.
The fix introduces the depth of the recursion to the function and the `processedMap`, so the processedMap tracks the depth of the model wherever it processes
Example
```
pet:
oneOf:
- $ref: '#/components/schemas/dog'
- $ref: '#/components/schemas/cat'
discriminator:
propertyName: attr
mapping:
DOG: '#/components/schemas/dog'
CAT: '#/components/schemas/cat'
petPreference:
type: object
required:
- pet1
- pet2
- pet3 …
```
> [GoClient] Fixed StringIndexOutOfBoundsException when multiple properties has the same required $ref oneOf objects

- pom.xml
> Update parser to 2.0.31

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautServerCodegen.java
- modules/openapi-generator/src/main/resources/java-micronaut/server/controller.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/micronaut/MicronautServerCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/micronaut/roles-extension-test.yaml
Added ability to apply security roles on operations with the `x-roles` extension as in this example:
```yaml
post:
tags: [books]
summary: Create a new book
operationId: createBook
parameters:
- {name: bookName, in: path, required: true, schema: {type: string}}
requestBody:
content:
application/json: { schema: { $ref: "#/components/schemas/Book" } }
responses:
'200':
description: success
x-roles: ["admin"]
```
It will be added with Micronaut's `@Secured` annotation. Also supports `isAuthorized()`, `isAnonymous()` and `denyAll()` values that will be converted to Micronaut constants.
I ran the following to validate build:
```
./bin/meta-codegen.sh
./mvnw integration-test -P …
```
> [Micronaut] [Server] Add support for security roles with extension

- modules/openapi-generator/src/main/resources/php/api.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/DefaultApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeClassnameTags123Api.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/StoreApi.php
- samples/client/petstore/php/OpenAPIClient-php/lib/Api/UserApi.php
Should fix failed tests from #11225. I missed that one, sorry, PR was really huge.
@nadar 
```
``` 
> [php] Fix form serialization typo from #11225

- samples/client/petstore/php/OpenAPIClient-php/tests/DateTimeSerializerTest.php
- samples/client/petstore/php/OpenAPIClient-php/tests/PetApiTest.php
Noticed that `$expected` and `$actual` params are misplaced in static tests of PHP client. Correct order of arguments gives more readable output when test fails.
cc @jebentier, @dkarlovi, @mandrean, @jfastnacht, @renepardon
```
``` 
> [php] Switch expected and actual params in tests

- modules/openapi-generator/src/main/resources/scala-sttp/paramCreation.mustache
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/PetApi.scala
This PR fixes the issue [#11942](https://github.com/OpenAPITools/openapi-generator/issues/11942)
Here is the openapi spec for reproduce the issue and verify the fix.
```ymal
openapi: 3.0.0
info:
title: Request Header
version: "1.0.0"
paths:
/test:
get:
summary: Empty Route
parameters:
- description: Gets user info.
explode: false
in: header
name: user_uuid
required: true
schema:
format: uuid
type: string
style: simple
responses:
"200":
description: Good Request.
content:
schema:
$ref: '#/components/schemas/ReturnValue'
"400":
description: Bad Request.
components:
schemas:
ReturnValue:
properties:
name:
type: string
``` 
```
```  …
> [scala][sttp]convert header parameter to string

- modules/openapi-generator/src/main/resources/python/exceptions.mustache
- samples/client/petstore/python/petstore_api/exceptions.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/exceptions.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/exceptions.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/exceptions.py
- samples/openapi3/client/petstore/python/petstore_api/exceptions.py
This PR changes the \_\_str\_\_ function for the APIException class to print `Status Code: ` before printing the status code. This is just to remain consistent with the other output in the custom error message.
```
``` 
@taxpon (2017/07) @frol (2017/07) …
> [Python] Update APIException Output

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/webclient/pom.mustache
- samples/client/petstore/java/resttemplate-withXml/build.gradle
- samples/client/petstore/java/resttemplate-withXml/pom.xml
- samples/client/petstore/java/resttemplate/build.gradle
- samples/client/petstore/java/resttemplate/pom.xml
- samples/client/petstore/java/webclient-nulable-arrays/build.gradle
- samples/client/petstore/java/webclient-nulable-arrays/pom.xml
- samples/client/petstore/java/webclient/build.gradle
- samples/client/petstore/java/webclient/pom.xml
[CVE-2022-22965: Spring Framework RCE via Data Binding on JDK 9+](https://tanzu.vmware.com/security/cve-2022-22965)
[Spring Boot 2.6.6 available now](https://spring.io/blog/2022/03/31/spring-boot-2-6-6-available-now)
[Spring Framework RCE, Early Announcement](https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement)
```
```  …
> Update Spring dependencies to address CVE-2022-22965

- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api.mustache
In case 'useBeanValidation' is enabled the relevant annotation classes should be imported on the API as well.
In the current version (5.4.0) the resource methods parameters are annotated with @Valid but without importing them.
> Conditionally import the java validation API in the resource interface definition

- modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache
- samples/client/others/typescript/builds/with-unique-items/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/composed-schemas/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/default/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/deno/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/inversify/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/jquery/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/builds/object_params/models/ObjectSerializer.ts
- samples/openapi3/client/petstore/typescript/tests/default/test/api/PetApi.test.ts
- samples/openapi3/client/petstore/typescript/tests/deno/test/api/PetApi_test.ts
- samples/openapi3/client/petstore/typescript/tests/jquery/test/api/PetApi.test.ts
- samples/openapi3/client/petstore/typescript/tests/object_params/test/api/PetApi.test.ts
Currently the deserializer fills all fields which are missing in the payload with the value `undefined`. Usually the difference between a missing field and a field which is set to `undefined` is not important. In some cases the behaviour is different however. For example when using `Object.keys`, the `in` operator or a strict recursive comparison like lodash’s `isEqual`.
This PR changes the behaviour, so that the missing fields are skipped and the deserialized objects do not have them set to `undefined` anymore.
I feel this is the correct approach, because this is the most strict meaning for optional properties in typescript. (Even though [the flag](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) that checks strictly is not enabled by default, for backward …
> [typescript] Skip missing fields during deserialization

- .travis.yml
Conditionally install `phpenv` based on whether the cache is currently empty.
```
``` 
> Conditionally install phpenv based on cache

- modules/openapi-generator/src/main/resources/JavaPlayFramework/newApiController.mustache
- samples/server/petstore/java-play-framework-api-package-override/app/com/puppies/store/apis/PetApiController.java
- samples/server/petstore/java-play-framework-async/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework-controller-only/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework-fake-endpoints/app/controllers/FakeApiController.java
- samples/server/petstore/java-play-framework-fake-endpoints/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework-no-bean-validation/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework-no-exception-handling/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework-no-interface/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework-no-nullable/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework-no-swagger-ui/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework-no-wrap-calls/app/controllers/PetApiController.java
- samples/server/petstore/java-play-framework/app/controllers/PetApiController.java
This change is to prevent a NPE when the field in a formData is "not required" and that we pass null.
```
```  …
> [Java Play Framework Generator] Fix NPE when passing null in a formData that is not required.

- modules/openapi-generator/src/main/resources/java-micronaut/common/model/typeInfoAnnotation.mustache
In some cases, where the openapi file uses a discriminator, `@JsonTypeName` will appear twice - causing an error. This PR removes it from `typeInfoAnnotation.mustache` since it will always be included in `pojo.mustache`
```
``` 
Java technical committee …
> [Micronaut] remove duplicate JsonTypeName

- modules/openapi-generator/src/main/resources/Java/beanValidationQueryParams.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue-11340.yaml
Added space between @NotNull-annotation and Java type to produce code  that compiles. fix #11340
```
```  …
> Added space between @NotNull-annotation and Type

- modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache
- modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
- samples/client/petstore/ruby-faraday/lib/petstore/configuration.rb
- samples/client/petstore/ruby/lib/petstore/api_client.rb
- samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/api_client.rb
- samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/api_client.rb
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/api_client.rb
Support binary return format only  in Ruby faraday client via the config option `return_binary_data`
```
``` 
> Support binary return format only  in Ruby faraday client

- modules/openapi-generator/src/main/resources/cpp-qt-client/oauth.h.mustache
- samples/client/petstore/cpp-qt/client/PFXOauth.h
This fix the "zero as null pointer constant" warning
```
``` 
@ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)
> [cpp-qt-client] Fix c++ warning

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
```
``` 
@TiFu @taxpon @sebastianhaas  @kenisteward  @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov
> [typescript-fetch]: use ReponseError instead of throwing a response (#10477)

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
Add response headers to API exception when streaming
```
``` 
> [java][okhttp-gson] Add response headers to API exception when streaming

- modules/openapi-generator/src/main/resources/python-experimental/__init__apis.handlebars
- modules/openapi-generator/src/main/resources/python/__init__apis.mustache
- samples/client/petstore/python/petstore_api/apis/__init__.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/apis/__init__.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/apis/__init__.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/apis/__init__.py
- samples/openapi3/client/petstore/python-experimental/petstore_api/apis/__init__.py
- samples/openapi3/client/petstore/python/petstore_api/apis/__init__.py
This tiny PR fixes the spelling of an identifier that was incorrectly cased in a mustache template. The fix only affects a comment in the output, so it will make no runtime difference when consuming a generated client.
In the Ruby generator, the package name is available as `{{packageName}}`, but in `src/main/resources/python/__init__apis.mustache`, it was being referenced as `{{packagename}}`.
This produced incorrect output such as:
```ruby
#
```
(note the missing package name)
The corrected output:
```ruby
#
```
cc @cliffano @zlx @autopp
```
``` 
These must …
> [Python] Fix incorrectly capitalized mustache identifier in apis template

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/build.sbt.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pom.mustache
- samples/client/petstore/java/jersey2-java8-localdatetime/build.gradle
- samples/client/petstore/java/jersey2-java8-localdatetime/build.sbt
- samples/client/petstore/java/jersey2-java8-localdatetime/pom.xml
- samples/client/petstore/java/jersey2-java8/build.gradle
- samples/client/petstore/java/jersey2-java8/build.sbt
- samples/client/petstore/java/jersey2-java8/pom.xml
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/build.gradle
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/build.sbt
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/pom.xml
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/build.gradle
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/build.sbt
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/pom.xml
- samples/openapi3/client/petstore/java/jersey2-java8/build.gradle
- samples/openapi3/client/petstore/java/jersey2-java8/build.sbt
- samples/openapi3/client/petstore/java/jersey2-java8/pom.xml
Update jackson databind to newer version (v2.13.2.2) to address security concerns.
```
```  …
> [java][jersey2] Update jackson databind to newer version (v2.13.2.2)

- modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache
- samples/client/petstore/c/api/PetAPI.c
- samples/client/petstore/c/api/StoreAPI.c
- samples/client/petstore/c/api/UserAPI.c
Comment out error message debug
```
``` 
cc @zhemant (2018/11) @ityuhui (2019/12) @michelealbano (2020/03)
> [C] Comment out error message debug

- pom.xml
> testng 7.5

- modules/openapi-generator/src/main/resources/openapi-yaml/README.md
- modules/openapi-generator/src/main/resources/openapi/README.md
Fixed a typo README file, which caused the project link to be broken
```
``` 
> Fixed typo in readme which caused the project link to be broken

- modules/openapi-generator-gradle-plugin/README.adoc
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
- modules/openapi-generator-maven-plugin/README.md
- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- modules/openapi-generator-maven-plugin/src/test/java/org/openapitools/codegen/plugin/CodeGenMojoTest.java
- modules/openapi-generator-maven-plugin/src/test/resources/default/pom.xml
Add `apiNameSuffix` parameter to maven & gradle plugins. Fix for https://github.com/OpenAPITools/openapi-generator/issues/12055
```
``` 
> Configure apiNameSuffix via plugins

- bin/configs/dart-dio-next-petstore-client-lib-fake.yaml
- bin/configs/dart-dio-petstore-client-lib.yaml
- modules/openapi-generator/src/main/resources/dart-dio/enum.mustache
- modules/openapi-generator/src/main/resources/dart-dio/enum_inline.mustache
- modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/enum.mustache
- modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/enum_inline.mustache
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/enum_arrays.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/enum_test.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/map_test.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/model_enum_class.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/order.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/outer_enum.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/outer_enum_default_value.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/outer_enum_integer.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/outer_enum_integer_default_value.dart
- samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/lib/src/model/pet.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/model/order.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib/lib/model/pet.dart
Adds support to dart-dio and built value for the new enumUnknownDefaultCase flag. When this flag is enabled, a default enum value is created.
With this change, that value is now set as the fallback value when deserializing unknown enums. This prevents runtime errors when the deserializer encounters an unknown enum.
- [x ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update …
> [dart-dio] Adds support for enumUnknownDefaultCase to BuiltValue enums

- modules/openapi-generator/src/main/resources/php-slim4-server/README.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/composer.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/config_dev_default.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/register_dependencies.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/register_routes.mustache
- samples/server/petstore/php-slim4/README.md
- samples/server/petstore/php-slim4/composer.json
- samples/server/petstore/php-slim4/config/dev/default.inc.php
- samples/server/petstore/php-slim4/lib/App/RegisterDependencies.php
- samples/server/petstore/php-slim4/lib/App/RegisterRoutes.php
Added Mock Server as fully pre-configured dev only feature.
UPD: how it looks like from the CURL
with `production` env:
```console
$ curl --request GET \
>   --url 'http://phpslim4.test/v2/pet/findByStatus?status=available' \
>   --header 'accept: application/json' \
>   --header 'x-openapiserver-mock: ping'
{
"message": "501 Not Implemented"
}
```
with `development` env:
```console
$  curl --request GET \
>   --url 'http://phpslim4.test/v2/pet/findByStatus?status=available' \
>   --header 'accept: application/json' \
>   --header 'x-openapiserver-mock: ping'
[{"id":-8738629417578509312,"category":{"id":-4162503862215270400,"name":"Lorem ipsum dol"},"name":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem i","photoUrls":["Lor"],"tags":[{"id":-3506202845849391104,"name":"Lorem …
```
> [php-slim4] Add Mock Server

- modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
- modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
- modules/openapi-generator/src/main/resources/ruby-client/configuration_faraday_partial.mustache
- modules/openapi-generator/src/main/resources/ruby-client/configuration_typhoeus_partial.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
- samples/client/petstore/ruby-faraday/lib/petstore/configuration.rb
- samples/client/petstore/ruby/lib/petstore/configuration.rb
- samples/openapi3/client/extensions/x-auth-id-alias/ruby-client/lib/x_auth_id_alias/configuration.rb
- samples/openapi3/client/features/dynamic-servers/ruby/lib/dynamic_servers/configuration.rb
- samples/openapi3/client/features/generate-alias-as-model/ruby-client/lib/petstore/configuration.rb
The partial templates were renamed because they no longer hold tls
settings exclusively.
fixes: #9838
> [Ruby] [Faraday] Adds 'params_encoder' config option for clients

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/main/resources/typescript-axios/modelGeneric.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/go/AbstractGoCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_9282.yaml
- samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
- samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
When a schema specifies `additionalProperties: true`, we need not restrict those properties to a particular type. This change sets the schemas for them to `AnyType` instead of `object`.
From a generation perspective, this only changes the output for generators that differentiate between `AnyType` and `object` in their type mappings; most do not. This fixes at least one bug in the Go and TypeScript generators.
* Fixes #9282
* Fixes #3277 (Go-specific)
New tests for the Go generator and `DefaultCodegen` demonstrate the intent of this change.
```
``` 
These must …
> Process additionalProperties: true as arbitrary type instead of object

- modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/pom.mustache
- modules/openapi-generator/src/main/resources/Java/pom.mustache
- samples/client/petstore/java/apache-httpclient/pom.xml
- samples/client/petstore/java/jersey1/pom.xml
Plugins must be unique. Formerly maven-compiler-plugin was configured twice. That produces warnings with following:
`mvn clean install -f samples/client/petstore/java/jersey1/pom.xml `
(similar for `mvn clean install -f samples/client/petstore/java/apache-httpclient/pom.xml`)
> [WARNING] Some problems were encountered while building the effective model for org.openapitools:petstore-java-client-jersey1:jar:1.0.0
> [WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-compiler-plugin @ line 150, column 21
> [WARNING] 
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING] 
> [WARNING] For this reason, future Maven versions might no longer …
> [Java] maven-compiler-plugin only once, because duplicates cause warnings

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
- modules/openapi-generator/src/main/resources/csharp-netcore/modelAnyOf.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/modelOneOf.mustache
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/PolymorphicProperty.cs
Fix warning in cref for list
ref: https://stackoverflow.com/questions/532166/how-to-reference-generic-classes-and-methods-in-xml-documentation
```
``` 
cc @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti …
> [C#][netcore] Fix warning in cref for list

- modules/openapi-generator/src/main/resources/Java/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/build.gradle.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/pom.mustache
- modules/openapi-generator/src/main/resources/Java/pom.mustache
- samples/client/petstore/java/apache-httpclient/build.gradle
- samples/client/petstore/java/apache-httpclient/pom.xml
- samples/client/petstore/java/jersey1/build.gradle
- samples/client/petstore/java/jersey1/pom.xml
Update jackson databind to newer version for jersey1 and apache-httpclient
```
```  …
> [Java] Update jackson databind to newer version

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/typescript-three-plus/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
This PR allows we to write global settings for api clients.
Prior to this, we had to write the following for each api client (tag), which is a bit verbose.
```ts
import {
Configuration,
ClientAApi,
ClientBApi,
ClientCApi,
} from "./generated";
// custom config
const config = new Configuration({
credentials: "include",
});
export const clientA = new ClientAApi(config);
export const clientB = new ClientBApi(config);
export const clientC = new ClientCApi(config);
```
After this change, it can be written simply as follows.
```ts
import {
Configuration,
ClientAApi,
ClientBApi,
ClientCApi,
DefaultConfig,
} from "./generated";
// custom config
DefaultConfig.config = new Configuration({
credentials: "include",
});
export const clientA = new ClientAApi();
export const clientB = new ClientBApi(); …
```
> [typescript-fetch] add default config feature

- modules/openapi-generator-online/src/main/java/org/openapitools/codegen/online/configuration/OpenAPIDocumentationConfig.java
The generated OpenAPI spec does not reflect the GENERATOR_HOST which causes wrong generated code and non-functional snippets in the UI.
This PR improves that by adding the relevant parts to the spec.
```
``` 
🛠 with ❤ at …
> fix: respect configured generator URL in swagger config

- modules/openapi-generator/src/main/resources/typescript-aurelia/package.json.mustache
- modules/openapi-generator/src/main/resources/typescript-axios/package.mustache
- modules/openapi-generator/src/main/resources/typescript-jquery/package.mustache
- modules/openapi-generator/src/main/resources/typescript-nestjs/package.mustache
- modules/openapi-generator/src/main/resources/typescript-node/package.mustache
- modules/openapi-generator/src/main/resources/typescript-redux-query/package.mustache
- modules/openapi-generator/src/main/resources/typescript/package.mustache
- modules/openapi-generator/src/test/resources/integrationtests/typescript/additional-properties-expected/package.json
- modules/openapi-generator/src/test/resources/integrationtests/typescript/array-and-object-expected/package.json
- modules/openapi-generator/src/test/resources/integrationtests/typescript/node-es5-expected/package.json
- modules/openapi-generator/src/test/resources/integrationtests/typescript/objectsWithEnums-expected/package.json
- modules/openapi-generator/src/test/resources/integrationtests/typescript/petstore-expected/package.json
- samples/client/others/typescript/builds/with-unique-items/package.json
- samples/client/petstore/typescript-aurelia/default/package.json
- samples/client/petstore/typescript-axios/builds/es6-target/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/package.json
- samples/client/petstore/typescript-axios/builds/with-npm-version/package-lock.json
- samples/client/petstore/typescript-axios/builds/with-npm-version/package.json
- samples/client/petstore/typescript-axios/tests/default/package-lock.json
- samples/client/petstore/typescript-axios/tests/default/package.json
- samples/client/petstore/typescript-jquery/npm/package.json
- samples/client/petstore/typescript-nestjs-v6-provided-in-root/builds/default/package.json
- samples/client/petstore/typescript-node/npm/package.json
- samples/client/petstore/typescript-redux-query/builds/with-npm-version/package.json
- samples/openapi3/client/petstore/typescript/builds/browser/package.json
- samples/openapi3/client/petstore/typescript/builds/composed-schemas/package.json
- samples/openapi3/client/petstore/typescript/builds/default/package.json
- samples/openapi3/client/petstore/typescript/builds/inversify/package.json
- samples/openapi3/client/petstore/typescript/builds/jquery/package.json
- samples/openapi3/client/petstore/typescript/builds/object_params/package.json
Changed the lower limit of typescript version generated by the typescirpt-related generator to 4.0 as well as https://github.com/OpenAPITools/openapi-generator/pull/12102
See https://github.com/OpenAPITools/openapi-generator/pull/12102 for motivation and benefits.
```
```  …
> [typescript*] drop support typescript below 4.0

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
Changed to remove the `exist` and `mapValue` functions from runtime.ts when withoutRuntimeChecks is true.
This is because these functions are not used when this option is true.
```
``` 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) …
> [typescript-fetch] Removed functions that are unused when withoutRuntime is true.

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/apiException.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiException.java
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/api/PingApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/DefaultApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/UserApi.java
Improve errorObjectType to avoid regression
To fix https://github.com/OpenAPITools/openapi-generator/pull/11538#issuecomment-1090226625
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) …
> [java][okhttp-gson] Improve errorObjectType to avoid regression

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSlim4ServerCodegen.java
- modules/openapi-generator/src/main/resources/php-slim4-server/README.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/composer.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/config_dev_default.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/config_prod_default.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/gitignore
- modules/openapi-generator/src/main/resources/php-slim4-server/phpcs.xml.mustache
- modules/openapi-generator/src/main/resources/php-slim4-server/register_dependencies.mustache
- samples/server/petstore/php-slim4/.gitignore
- samples/server/petstore/php-slim4/.openapi-generator/FILES
- samples/server/petstore/php-slim4/README.md
- samples/server/petstore/php-slim4/composer.json
- samples/server/petstore/php-slim4/config/dev/default.inc.php
- samples/server/petstore/php-slim4/config/prod/default.inc.php
- samples/server/petstore/php-slim4/lib/App/RegisterDependencies.php
- samples/server/petstore/php-slim4/logs/.htaccess
- samples/server/petstore/php-slim4/phpcs.xml.dist
I've added pre-configured [Monolog](https://github.com/Seldaek/monolog) logger. Big projects might need logger factory to use different logger instances in each micro service, but current implementation should cover MVP.
This code enables logger with production mode only, it's based on my personal job experience because I don't read log files during development. From my point of view enabled logger at the dev server just pollutes system with temp files which I won't read anyway, in rare cases when I do need logs(CRON task) I turn them on manually.
@wing328 if you know how to change folder permissions from the Java code let me know. It would be great to make `logs` folder writable(like from command line `sudo chmod a+w logs`)
cc @jebentier @dkarlovi @mandrean @jfastnacht @renepardon
``` …
```
> [php-slim4] Add monolog package as default logger

- modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
- samples/client/petstore/c/model/api_response.c
- samples/client/petstore/c/model/category.c
- samples/client/petstore/c/model/order.c
- samples/client/petstore/c/model/pet.c
- samples/client/petstore/c/model/tag.c
- samples/client/petstore/c/model/user.c
The PR https://github.com/OpenAPITools/openapi-generator/pull/5477 supports the data type `enum` e.g.
```c
typedef enum  { 
kubernetes_v1_container_IMAGEPULLPOLICY_NULL = 0, 
kubernetes_v1_container_IMAGEPULLPOLICY_Always, 
kubernetes_v1_container_IMAGEPULLPOLICY_IfNotPresent, 
kubernetes_v1_container_IMAGEPULLPOLICY_Never 
} kubernetes_v1_container_IMAGEPULLPOLICY_e;
```
And the default value is `kubernetes_v1_container_IMAGEPULLPOLICY_NULL` if the enum data does not appear in json string at all. 
Actually `kubernetes_v1_container_IMAGEPULLPOLICY_NULL` is invalid to API server because it is not defined in OpenAPI Spec. So it should not be passed to API server.
But in the function `*_convertToJSON`, the current code puts the value to the JSON structure (which will be passed to the API …
> [C][Client] Do not put the invalid value of the enum to a JSON structure

- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/AbstractAnnotationAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/JavaFileAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/MethodAnnotationAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/MethodAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/ParameterAnnotationAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/ParameterAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/PropertyAnnotationAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/PropertyAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/TypeAnnotationAssert.java
Small improvement to reduce warnings from JavaFileAssert unit
```
``` 
> [Java] Ignore return value for Java file assert classes

- docs/generators/java-msf4j.md
- docs/generators/jaxrs-cxf-extended.md
- docs/generators/jaxrs-cxf.md
- docs/generators/jaxrs-jersey.md
- docs/generators/jaxrs-resteasy-eap.md
- docs/generators/jaxrs-resteasy.md
- docs/generators/jaxrs-spec.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaJAXRSServerCodegen.java
The default for `sourceFolder` in the documentation was wrong.
```
``` 
The first two fail at the moment because of some unrelated python-experimental stuff, but I did run
```
mvn clean package -DskipTests
./bin/generate-samples.sh ./bin/configs/java*
```
successfully and added the changed files.
Please review
@bbdouglas
@sreeshas 
@jfiala 
@lukoyanov 
@cbornet
@jeff9finger 
@karismann 
@Zomzog 
@lwlee2608
> Fix documentation/config-help for users of AbstractJavaJAXRSServerCodegen, sourceFolder was wrong

- modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache
- modules/openapi-generator/src/main/resources/ruby-client/api_client_faraday_partial.mustache
- modules/openapi-generator/src/main/resources/ruby-client/gemspec.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/api_client.rb
- samples/client/petstore/ruby-faraday/petstore.gemspec
Closes #12074
To support Faraday 2.x, we only need the changes in dfa16a68fb7417259d38c11d05a2a2147764ec22
I also did a little refactoring mainly to memoize Faraday connections in 1594f4eb5e346e6002982f66dc6c882d2719bdf9.
If it doesn't look good, I can take it out so let me know.
Additionally, since the `params_encoder` option seems to be configured twice, modified in f8d4cff2a3c94a4f580fa7fd38d2ca6caf7f245d to remove redundancy.
```
```  …
> [Ruby] Add support for faraday 2.x

- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
- samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
Added abstraction of URLSession in swift5 template
> [swift5] Abstract away URLSession (#11651)

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/.openapi-generator/FILES
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
- samples/client/petstore/php/OpenAPIClient-php/tests/ObjectSerializerTest.php
In our project, we use a CS tool that adds `declare(strict_types=1)` everywhere. [`ObjectSerializer::toPathValue`](https://github.com/OpenAPITools/openapi-generator/blob/v5.4.0/modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache#L147) then throws a type error, if you for example have a field in your API that is an integer, as `rawurlencode` only accepts `string`s.
Make [`ObjectSerializer::toString`](https://github.com/OpenAPITools/openapi-generator/blob/4a36be70025e9c0d3ff61731618b7fc2d942c4b6/modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache#L216) actually return a string:
* Less surprises due to inconsistent types
* The function does what it promises
@jebentier , @dkarlovi, @mandrean, @jfastnacht, @ybelenko, @renepardon
> [php] make ObjectSerializer::toString actually return a string

- docs/generators/csharp-netcore-functions.md
- modules/openapi-generator/src/main/resources/csharp-netcore-functions/function.mustache
Change to Azure functions code gen which gives the functions an explicit return type instead of IActionResult.
```
``` 
> Return type for Azure funcs

- docs/generators/java-micronaut-client.md
- docs/generators/java-micronaut-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautAbstractCodegen.java
- modules/openapi-generator/src/main/resources/java-micronaut/common/model/beanValidation.mustache
- modules/openapi-generator/src/main/resources/java-micronaut/common/model/model.mustache
- modules/openapi-generator/src/main/resources/java-micronaut/common/model/pojo.mustache
The Micronaut generator by default adds the `@Nullable` annotation to
non-required properties and allows using the Jackson JsonNullable
wrapper but it is not possible to use java.util.Optional as a wrapper
for optional properties.
This change adds support for using the Optional wrapper for non-required
properties.
```
``` 
For Windows …
> [java-micronaut] Support Optional for non-required properties

- modules/openapi-generator/src/main/resources/python-flask/controller.mustache
Flask (and connexion by extension) allows the return type to be either
just the body, or the body & status code, or the body & status code &
headers.
This commit fixes the stated `rtype` to allow the latter two cases.
```
``` 
@taxpon (2017/07) @frol …
> [python-flask] Fix return type too strict

- modules/openapi-generator/src/main/resources/go/api.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java
In generated API requests/responses, this fixes a minor duplication of the word "Api", which is already part of the `classname` template parameter and doesn't need to be repeated when `structPrefix` is set.
For example, previously a generated name might be `PetApiApiAddPetRequest`, and with this change it is simplified to `PetApiAddPetRequest`.
```
```  …
> [Go] Fix duplication of "Api" in generated code when structPrefix is set

- bin/configs/java-micronaut-client.yaml
- docs/generators/java-micronaut-client.md
- docs/generators/java-micronaut-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautAbstractCodegen.java
- modules/openapi-generator/src/main/resources/java-micronaut/common/model/pojo.mustache
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/model/Animal.java
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/model/BigCat.java
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/model/Cat.java
- samples/client/petstore/java-micronaut-client/src/main/java/org/openapitools/model/Dog.java
When types which extend a common type and are distinguished based on a
discriminator are consumed they are often cast to their specific Java
type which results in error prone boilerplate code.
By generating a visitor for those kind of types the various subtypes can
be consumed in a type safe manner.
This change is based on the same implementation I made for the [Kokuwa.io](https://github.com/kokuwaio/micronaut-openapi-codegen/pull/66)
version of the micronaut openapi plugin.
Note that there is also a pull request for the [typescript-angular](https://github.com/OpenAPITools/openapi-generator/pull/9278) implementation.
```
```  …
> [java-micronaut] Generate visitor for subtypes with a discriminator

- modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache
- samples/client/others/csharp-netcore-complex-files/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Client/ApiClient.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCoreAndNet47/src/Org.OpenAPITools/Client/ApiClient.cs
Add support for `byte[]` response type deserialization
```
``` 
@mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti
> [csharp-netcore] Add support for `byte[]` response deserialization

- modules/openapi-generator/src/main/resources/python/rest.mustache
- samples/client/petstore/python/petstore_api/rest.py
- samples/client/petstore/python_disallowAdditionalPropertiesIfNotPresent/petstore_api/rest.py
- samples/openapi3/client/extensions/x-auth-id-alias/python/x_auth_id_alias/rest.py
- samples/openapi3/client/features/dynamic-servers/python/dynamic_servers/rest.py
- samples/openapi3/client/petstore/python/petstore_api/rest.py
Hello! I fixed PEP8 E111 issue in [rest.mustache](https://github.com/OpenAPITools/openapi-generator/blob/85df431ebf7b2fbdb8fa95ba90d153df8a4ef98c/modules/openapi-generator/src/main/resources/python/rest.mustache).
```
``` 
@taxpon (2017/07) @frol …
> [BUG][python] Fix PEP8 E111 issue in rest.mustache

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/apiException.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/api/PetApiTest.java
> [Java][OkHTTP] Include HTTP response data in ApiException getMessage()

- samples/openapi3/client/petstore/python-experimental/tests_manual/test_fake_api.py
Enables test_inline_composition
```
``` 
> Enables test_inline_composition [python-experimental]

- modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/PetApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/StoreApi.java
- samples/client/petstore/java/native/src/main/java/org/openapitools/client/api/UserApi.java
```
``` 
Closes #9928
- Solved the problem with an enabled config option 'fullJavaUtil'
- Fixed compilation error for 'fullJavaUtil' - true
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger …
> [Java][Native] Reference to Consumer is ambiguous

- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.c.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache
- samples/client/petstore/c/include/apiClient.h
- samples/client/petstore/c/src/apiClient.c
If we call `apiClient_invoke` with some `const char *` as parameters of the function, ( the complete source code is https://github.com/kubernetes-client/c/blob/master/kubernetes/src/generic.c)  then there are some warnings while compiling the C client library.
```bash
src/generic.c:57:38: warning: passing argument 2 of ‘apiClient_invoke’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
apiClient_invoke(client->client, path, queryParameters, headerParameters, formParameters, headerType, contentType, body, method);
^~~~
In file included from src/generic.c:1:0:
src/../include/apiClient.h:43:6: note: expected ‘char *’ but argument is of type ‘const char *’
void apiClient_invoke(apiClient_t *apiClient,char* operationParameter, list_t *queryParameters, list_t …
```
> [C][Client] Eliminate compiler warnings

- modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/modelbase-header.mustache
- modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/modelbase-source.mustache
A specialization for the `shared_ptr<datetime>` data type was added to
ModelBase member functions fromString, fromJson, toJson and
toHttpContent.
This should fix compilation errors on generated source code.
See https://github.com/coinapi/coinapi-sdk/pull/130
@muttleyxd
> [cpp-rest-sdk-client] handling datetime type

- modules/openapi-generator/src/test/java/org/openapitools/codegen/csharpnetcorefunctions/CsharpNetcoreFunctionsServerCodegenTest.java
I'm not sure how this ever compiled, but it causes a build failure for me and the fix is easy and non-invasive.
> Fix directory name to match package

- modules/openapi-generator/src/main/resources/elixir/README.md.mustache
- modules/openapi-generator/src/main/resources/elixir/config.exs.mustache
- modules/openapi-generator/src/main/resources/elixir/connection.ex.mustache
- samples/client/petstore/elixir/README.md
- samples/client/petstore/elixir/config/config.exs
- samples/client/petstore/elixir/lib/openapi_petstore/connection.ex
Elixir uses `config.exs` files to store most configuration values. This change allows the baseURL to be overridden with `dev.exs` and `prod.exs` in a project using the generated code.
```
``` 
@mrmstn
> Allow the baseUrl of elixir APIs to be overridden

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java
- modules/openapi-generator/src/main/resources/rust/Cargo.mustache
Fix version with leading v in rust client.
It does not cover all edge cases though so we may need to improve it over time.
Tested locally to confirm the fix. Will add a test later when revising the spec with more test cases.
Another way is to set the packageVersion directly via an option.
To fix https://github.com/OpenAPITools/openapi-generator/issues/12271
```
```  …
> Better handling of version in Rust client

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java
- modules/openapi-generator/src/main/resources/cpp-pistache-server/api-source.mustache
- samples/server/petstore/cpp-pistache/api/UserApi.cpp
- samples/server/petstore/cpp-pistache/api/UserApi.h
- samples/server/petstore/cpp-pistache/impl/UserApiImpl.cpp
- samples/server/petstore/cpp-pistache/impl/UserApiImpl.h
- samples/server/petstore/cpp-pistache/model/Pet.cpp
- samples/server/petstore/cpp-pistache/model/Pet.h
fixes #11246
```
``` 
@ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03)
> [C++][Pistache] Add support for validating arrays, use full namespace type with custom types

- modules/openapi-generator/src/main/resources/cpp-pistache-server/helpers-source.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-header.mustache
- modules/openapi-generator/src/main/resources/cpp-pistache-server/model-struct-source.mustache
- samples/server/petstore/cpp-pistache/model/Helpers.cpp
Hi, I have tried to use struct models with newest Pistache version but it does not compile:
- bunch of conversion warnings (truncating from 32-bit int to 16-bit uint)
- Pistache::Optional was used but it got removed from Pistache some time ago
- validation was missing, I have ported the validation to struct model, I think it looks okay - I have generated samples with `useStructModel: "true"` and the part related to validation did not change in PetStore sample
I have run `bin/generate-samples.sh` and it modified a bunch of files in .NET Core generator, but I didn't commit these files, apart from that everything else is committed.
```
$ git status
On branch pistache-fix-struct-model
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore …
```
> [C++][Pistache] Fixes for struct model

- modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/model-source.mustache
https://github.com/OpenAPITools/openapi-generator/issues/12289
Fix for cpp-rest-sdk-client generator producing uncompilable code if there is a "-" (or other characters like a space etc.) in a property name of an object.
@ravinikam, @stkrwork, @etherealjoy, @martindelille, @muttleyxd
> Fix for cpp-rest-sdk-client generator producing uncompilable code

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaSttpClientCodegen.java
- modules/openapi-generator/src/main/resources/scala-sttp/additionalTypeSerializers.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/dateSerializers.mustache
- modules/openapi-generator/src/main/resources/scala-sttp/jsonSupport.mustache
- samples/client/petstore/scala-sttp/.openapi-generator/FILES
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/core/AdditionalTypeSerializers.scala
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/core/DateSerializers.scala
- samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/core/JsonSupport.scala
There are a couple of issues with the sttp codegen support.
1. `enum` should not be used as it will be a reserved keyword -> changed this in JsonSupport
2. Enums were completely missed and not generated at all -> Fixed 
3. AnyType was added as value type for maps where the schema type is object. These should be encoded as a json library specific json value (personal opinion)
4. URI serializer is added to support URI as well.
```
```  …
> [Scala][sttp] various bug fixes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/schema-unalias-test.yml
- Add new method to detect self-refernecing in ModelUtils
- Add tests
(self referencing is already tested by crashSwift5ExampleCodeGenerationStackOverflowTest and crashSwift5ExampleCodeGenerationStackOverflowBug_2Test)
```
``` 
FYI …
> Add new method to detect self-referencing in ModelUtils

- modules/openapi-generator/src/main/resources/python-fastapi/api.mustache
- modules/openapi-generator/src/main/resources/python-fastapi/model.mustache
- samples/server/petstore/python-fastapi/src/openapi_server/apis/pet_api.py
- samples/server/petstore/python-fastapi/src/openapi_server/apis/store_api.py
- samples/server/petstore/python-fastapi/src/openapi_server/apis/user_api.py
- samples/server/petstore/python-fastapi/src/openapi_server/models/api_response.py
- samples/server/petstore/python-fastapi/src/openapi_server/models/category.py
- samples/server/petstore/python-fastapi/src/openapi_server/models/order.py
- samples/server/petstore/python-fastapi/src/openapi_server/models/pet.py
- samples/server/petstore/python-fastapi/src/openapi_server/models/tag.py
- samples/server/petstore/python-fastapi/src/openapi_server/models/user.py
I noticed that the Python-FastAPI generator converts all model field names to snake_case to match Python convention. While this is desireable from a code-style perspective, it breaks any API using a different convention for field names since it also affects the names of fields that get serialised to JSON. 
FastAPI uses Pydantic for its model classes, which supports setting an [alias](https://pydantic-docs.helpmanual.io/usage/models/#model-signature) value in order to deserialise a different name to what is used for the Python class, so I modified the generator to use this. Be default it will always be used during deserialisation but only during serialisation if the `by_alias=True` option is specified. Luckily, FastAPI includes an option we can set on endpoints that will use this for data …
> Fix issue with fastapi generator converting all fields to snake_case

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/oneof_model.mustache
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Fruit.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/FruitReq.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Mammal.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/NullableShape.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Pig.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Quadrilateral.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Shape.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/ShapeOrNull.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/Triangle.java
- samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/JSONTest.java
- Better error messages for oneOf
```
``` 
> [java][okhttp-gson] Better error messages for oneOf

- bin/configs/r-client.yaml
- samples/client/petstore/R/R/api_client.R
Add a test to set the httpUserAgent in r client
```
``` 
> Add a test to set the httpUserAgent in R client

- .github/CODEOWNERS
I discovered the [github code owner](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) feature that could be useful to improve the review process which is currently done by manually pinging the language team.
If I understand correctly, this changes should automatically ping me when the path mentioned in the CODEOWNERS file are modified in a PR.
I of course don't claim any ownership here but just want to improve the review process. If it seems suitable we could extends this to other contributors.
It would close a preview try to simplify review project (close #10623).
```
``` 
This is important, …
> Add martindelille to code owners

- modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
Fix for https://github.com/OpenAPITools/openapi-generator/issues/12319
> [java][resttemplate] avoid StringIndexOutOfBoundsException on empty HttpHeaders

- modules/openapi-generator/src/main/resources/dart/libraries/dio/pubspec.mustache
- modules/openapi-generator/src/main/resources/dart/libraries/dio/serialization/built_value/api_util.mustache
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake-json_serializable/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/lib/src/api_util.dart
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake/pubspec.yaml
- samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml
Just a minor bump to prevent some import warnings.
```
``` 
CC @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)
> [dart] Bump min dio version to prevent unused import

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/apiException.mustache
Remove errorObjectType as it's not used
```
``` 
> [java][okhttp-gson] Remove errorObjectType as it's not used

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java
close (#12357)
- [] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
```
``` 
@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d
> [GO] Fix exception in constructExampleCode with oneOf primitive type

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
Support Sets in query parameters (happens when uniqueItems=true).
Resolves #12317
```
``` 
> [typescript-fetch] Support Sets in query parameters (when uniqueItems=true)

- modules/openapi-generator/src/main/resources/r/api.mustache
- modules/openapi-generator/src/main/resources/r/testthat.mustache
- samples/client/petstore/R/R/pet_api.R
- samples/client/petstore/R/R/store_api.R
- samples/client/petstore/R/R/user_api.R
- samples/client/petstore/R/test_petstore.bash
- samples/client/petstore/R/tests/testthat.R
- samples/client/petstore/R/tests/testthat/test_petstore.R
- Added optional method argument "data_file" to methods that return data in order to support downloading the response body as files.
- Added test cases and tested locally.
```
``` 
> [R] Add support to download response as files

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java
- modules/openapi-generator/src/main/resources/r/description.mustache
- modules/openapi-generator/src/main/resources/r/testthat.mustache
- samples/client/petstore/R/DESCRIPTION
- samples/client/petstore/R/tests/testthat.R
- samples/client/petstore/R/tests/testthat/test_petstore.R
fix the following warnings:
```
* using R version 4.2.0 (2022-04-22)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘./DESCRIPTION’ ... ERROR
Required fields missing or empty:
‘Author’ ‘Maintainer’
* DONE
Status: 1 ERROR
```
```
* checking DESCRIPTION meta-information ... WARNING
Non-standard license specification:
Apache-2.0
Standardizable: FALSE
```
```
```  …
> [R] fix warnings in DESCRIPTION

- docs/generators/spring.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java
- modules/openapi-generator/src/main/resources/JavaSpring/springdocDocumentationConfig.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/spring/SpringCodegenTest.java
- samples/openapi3/server/petstore/spring-boot-oneof/.openapi-generator/FILES
- samples/openapi3/server/petstore/spring-boot-oneof/src/main/java/org/openapitools/configuration/SpringDocConfiguration.java
- samples/openapi3/server/petstore/spring-boot-springdoc/.openapi-generator/FILES
- samples/openapi3/server/petstore/spring-boot-springdoc/src/main/java/org/openapitools/configuration/SpringDocConfiguration.java
- samples/openapi3/server/petstore/springboot-beanvalidation-no-nullable/.openapi-generator/FILES
- samples/openapi3/server/petstore/springboot-beanvalidation-no-nullable/src/main/java/org/openapitools/configuration/SpringDocConfiguration.java
- samples/openapi3/server/petstore/springboot-delegate/.openapi-generator/FILES
- samples/openapi3/server/petstore/springboot-delegate/src/main/java/org/openapitools/configuration/SpringDocConfiguration.java
- samples/openapi3/server/petstore/springboot-implicitHeaders/.openapi-generator/FILES
- samples/openapi3/server/petstore/springboot-implicitHeaders/src/main/java/org/openapitools/configuration/SpringDocConfiguration.java
- samples/openapi3/server/petstore/springboot-useoptional/.openapi-generator/FILES
- samples/openapi3/server/petstore/springboot-useoptional/src/main/java/org/openapitools/configuration/SpringDocConfiguration.java
- samples/openapi3/server/petstore/springboot/.openapi-generator/FILES
- samples/openapi3/server/petstore/springboot/src/main/java/org/openapitools/configuration/SpringDocConfiguration.java
- Added the auto-generated OpenAPI 3 support for service metadata and security, using springdoc.
- Changes made to `SpringCodegen` to add the new documentation config file (`SpringDocConfiguration.java`) to the list of auto-generated files
- Added new template file: `springdocDocumentationProvider.mustache` for the Spring generator which builds `SpringDocConfiguration.java`
- This can be validated by generating a java spring API using the default documentation provider, and examining `target/generated-sources/openapi/src/main/java/org/openapitools/configuration/SpringDocConfiguration.java` in the resulting API.
- Updated spring samples in this PR can also be checked to see some examples of the new springdoc configuration files.
- `CodegenSecurityTest` was updated to test the new addition …
> [java][spring] added springdoc support for service metadata and security

- bin/configs/java-micronaut-server.yaml
- docs/generators/java-micronaut-server.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautServerCodegen.java
- modules/openapi-generator/src/main/resources/java-micronaut/server/controller.mustache
- modules/openapi-generator/src/main/resources/java-micronaut/server/controllerOperationBody.mustache
- samples/server/petstore/java-micronaut-server/src/main/java/org/openapitools/controller/PetController.java
- samples/server/petstore/java-micronaut-server/src/main/java/org/openapitools/controller/StoreController.java
- samples/server/petstore/java-micronaut-server/src/main/java/org/openapitools/controller/UserController.java
The default controller implementation returns an empty response. While
this might be an expected default for some users we want the default
implementation to return HTTP 501 Not Implemented instead. This will
support rapid development when the specs aren't finalized yet and thus
change often while preventing the methods from being unimplemented by
accident without the user of the API noticing it.
By adding a property which allows the generation of default methods
which return HTTP 501 developers can opt-in for this behavior.
```
```  …
> [java-micronaut] Allow default implementation to return HTTP 501

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/content-data.yaml
This PR adds support for the `style` and `explode` values on the `encoding` object onto request body parameters that are submitted as `application/x-www-form-urlencoded` or `multipart`.
The [Encoding Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#encodingObject) allows the specification of `style` and `explode` similar to how they can be applied to operation `parameter`s.
There has already existed code that would apply `contentType` from this Encoding Object, but this was the only value that was being applied. This PR renames that function from `setParameterContentType` to `setParameterEncodingValues`, and now also applies `style` and `explode` as appropriate.
I've added tests to `DefaultCodegenTest.testRequestBodyContent()` against some new definitions …
> Apply style and explode values from encoding for form-encoded request body parameters

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- remove errorObjectSubtype from Java client generator
```
``` 
> [Java] remove errorObjectSubtype from Java client generator

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/auth/RetryingOAuth.mustache
> Remove Javadoc comment for unthrown IOException

- modules/openapi-generator/src/main/resources/confluenceWikiDocs/index.mustache
This are small (but visually nice) improvements:
- Add colors: 200 = green, 300 = blue, 400 = red
- Add an example per parameter for better understanding
```
``` 
> Add - Status colors in Wiki, Example per parameter

- modules/openapi-generator/src/main/resources/python-experimental/schemas.handlebars
- samples/openapi3/client/petstore/python-experimental/petstore_api/schemas.py
- samples/openapi3/client/petstore/python-experimental/tests_manual/test_boolean_enum.py
- samples/openapi3/client/petstore/python-experimental/tests_manual/test_composed_bool.py
- samples/openapi3/client/petstore/python-experimental/tests_manual/test_nullable_string.py
- Fixes https://github.com/OpenAPITools/openapi-generator/issues/12388
- is_none moved from NoneClass into NoneBase so now it is visible as a method in pycharm, + docstring added
- is_true moved from BoolClass into BoolBase so now it is visible as a method in pycharm, + docstring added
- is_false moved from BoolClass into BoolBase so now it is visible as a method in pycharm, + docstring added
- Values for is_false fixed
- tests updated to test is_none, is_true, and is_false
If I don't hear back from @meawoppl in a day or two I will merge this in
```
``` 
These …
> [python-experimental] BoolSchema + NoneSchema improvements

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/auth/OAuth.mustache
- samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/auth/OAuth.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/OAuth.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/auth/OAuth.java
- throw exception instead of logging a warning when failed to refresh token
```
```  …
> [java][jersey2] throw exception when failed to refresh token

- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_12445.yaml
- samples/client/petstore/typescript-fetch/builds/enum/apis/DefaultApi.ts
- samples/client/petstore/typescript-fetch/builds/with-string-enums/apis/DefaultApi.ts
When "useInlineModelResolver" is true, avoid resolving ref schema of an enum to the actual schema for parameter of an operation, when we do resolve the enum will not be added to the imports.
```
``` 
> #12445 - avoid resolving ref schema to the actual schema for enum

- modules/openapi-generator/src/main/resources/dart2/serialization/native/native_class.mustache
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/mixed_properties_and_additional_properties_class.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/model/nullable_class.dart
fixes #12165 
This PR includes a patch to the `modules/openapi-generator/src/main/resources/dart2/serialization/native/native_class.mustache` file which previously wasn't handling the deserialiation of `Map<String, Object>` types correctly.
Previously, the deserialization of such fields was being generated as `mapValueOfType<Map<String, Object>>(json, key)`,  but due to Dart using different internal map representations, this would always fail at runtime, meaning that such objects were not able to be generated by this project.
This change adjusts the mustache file to detect when a field is a complex map and uses `mapCastOfType<String, Object>(json[key])` instead, which does not crash at runtime.
The correctness of the change can be confirmed using the following test files:
spec.yaml: …
> [Dart] Fix incorrect generation of additionalProperties:true (#12165)

- modules/openapi-generator/src/main/resources/graphql-nodejs-express-server/model.mustache
This PR fixes the missing enums values generation for **GraphQL NodeJS Express Server** as described in https://github.com/OpenAPITools/openapi-generator/issues/5815 .
Previous output:
```json
enum MyEnum {
}
```
Fixed output:
```json
enum MyEnum {
OPTION_1
OPTION_2
}
```
> Fixed enum values generation fo 'GraphQL NodeJS Express Server' generator.

- docs/generators/haskell.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
- modules/openapi-generator/src/main/resources/haskell-servant/API.mustache
- modules/openapi-generator/src/main/resources/haskell-servant/README.mustache
- modules/openapi-generator/src/main/resources/haskell-servant/haskell-servant-codegen.mustache
- samples/server/petstore/haskell-servant/README.md
- samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/API.hs
- samples/server/petstore/haskell-servant/openapi-petstore.cabal
Adds support for API key, basic and bearer authentication in the OpenAPI specification. OAuth and multiple authentication schemes simultaneously are not implemented. The implementation uses servants [generalized authentication](https://docs.servant.dev/en/stable/tutorial/Authentication.html#generalized-authentication).
If the OpenAPI specification does not specify an authentication mechanism it is compatible with the existing implementation. I added examples without authentication and for the different schemes [here](https://github.com/7omb/openapi-generator-haskell-auth-examples). The command:
```
./mvnw integration-test -f ./samples/server/petstore/haskell-servant/pom.xml
```
passes on my machine with `BUILD SUCCESS`.
``` …
```
> Add authentication for haskell-servant

- samples/client/petstore/javascript-closure-angular/compile.py
The current code is a syntax error in Python 3.
The proposed code works as expected in both Python 2 and Python 3.
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example, `./bin/generate-samples.sh bin/configs/java*`. 
@spacether
> Use print() function in both Python 2 and Python 3

- modules/openapi-generator/src/main/resources/Java/modelEnum.mustache
- modules/openapi-generator/src/main/resources/Java/modelInnerEnum.mustache
Fixes the issue https://github.com/OpenAPITools/openapi-generator/issues/11886 
Basically the suggested fix is applied in this branch which succesfully handles the `enumUnknownDefaultCase=true` option for the Java generator during the deserialization process.
```
```  …
> fix #11886 unhandled default enum case

- modules/openapi-generator/src/main/resources/php-symfony/serialization/JmsSerializer.mustache
- samples/server/petstore/php-symfony/SymfonyBundle-php/Service/JmsSerializer.php
Hello,
We have an issue when a parameter is not set in a get query.
In file Service/JmsSerializer.php, the `deserializeArrayString` method does not check for null value.
If value is null, the returned data is an array with 1 element:
```
array(1) {
[0]=>
string(0) ""
}
```
This value the fails validation.
Returning null for a null input corrects the issue.
Mentionning contributors as requested:
@jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @ybelenko, @renepardon
> [php-symfony] Allow non mandatory array value in Symfony

- modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
- samples/client/petstore/kotlin-array-simple-string-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-array-simple-string-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-bigdecimal-default-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-default-values-jvm-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-default-values-jvm-okhttp4/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-enum-default-value/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-gson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jackson/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-modelMutable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-moshi-codegen/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nonpublic/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-nullable/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-threetenbp/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin-uppercase-enum/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
- samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
https://github.com/OpenAPITools/openapi-generator/pull/11911 introduced some usages of `java.nio.*` which is not supported on Android API 25 and bellow.
This PR uses alternative API's, to avoid crashing on Android API 25 and bellow.
```
``` 
@jimschubert …
> [Kotlin][Client] replace java.nio.* to avoid crash on Android API 25 and bellow

- modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache
- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
There is a typo in generated code for `typescript-fetch`: `InitOverideFunction` (note a single `r`). This PR fixes it.
CC @mkusaka as member of Typescript Technical Committee
> Fixing typo in InitOverideFunction [typescript-fetch]

- modules/openapi-generator/src/main/resources/dart2/api_client.mustache
- samples/openapi3/client/petstore/dart2/petstore_client_lib/lib/api_client.dart
- samples/openapi3/client/petstore/dart2/petstore_client_lib_fake/lib/api_client.dart
I've got an issue while parsing an Array of Strings in date-time format
```yaml
content:
schema:
type: array
items:
type: string
format: date-time
```
which the generator translates into a `List<DateTime>`. 
When the List is unwrapped and then it tries to _deserialize the `DateTime` it does not find any suitable parser.
This just fixes it
@ahmednfwela
- [v] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [v] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
``` …
```
> [Dart][Client] Support parsing DateTime 

- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/resources/swift5/api.mustache
- modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache
- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
- samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/AlamofireImplementations.swift
- samples/client/petstore/swift5/asyncAwaitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/combineLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/default/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/deprecated/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/frozenEnums/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/nonPublicApi/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/objcCompatible/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/oneOf/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/promisekitLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/readonlyProperties/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/resultLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/rxswiftLibrary/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
- samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift
- samples/client/petstore/swift5/x-swift-hashable/PetstoreClient/Classes/OpenAPIs/URLSessionImplementations.swift
I've come across a problem implementing an API for Swift5 with an operation that could both answer a 200 response with a result body and an empty 202 response, so without any response body.
The problem concerns the Swift language, and most likely any other language that gracefully handles nulls, like Kotlin.
When generating the API for such an operation, the result, while using RxSwift, is an `Observable<ResponseObject>` and not an `Observable<ResponseObject?>` _(note the `?` that specifies that the response object can be null)_. This and the fact that the implementation of the class `URLSessionImplementations` [line 355-358](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.musta …
> [Feature] Handle optional operation responses

- modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache
Added recursive check for the references ($ref)
Now we should support nested objects.
[x ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
[ x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
[ x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
This is important, as CI jobs will verify all generator outputs of your HEAD commit as it would merge with master. …
> Fixes #9923 - added recursion for nested objects

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpModelTest.java
When using a Hydra schema, where you can have @id and id property in the model, the generated PHP code included duplicate id properties, getter and setter methods. The result was thus an invalid class. The Hydra schema is extensively used in the PHP Api Platform codebase. 
This change replaces the @ with at characters, just like it does in the Java generator and Rust generator. 
@jebentier  @dkarlovi @mandrean @jfastnacht @ybelenko @renepardon
> [PHP] Replace @ character so we can use Hydra Jsonld models.

- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- samples/client/petstore/java/jersey2-java8-localdatetime/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/extensions/x-auth-id-alias/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8-special-characters/src/main/java/org/openapitools/client/ApiClient.java
- samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/ApiClient.java
Here is the problem:
* When uploading a file with "multipart/form-data" and the jersey2 client, we receive this error:
`multipart/form-data not yet supported for serializeToString (http signature authentication)`
This error doesn't make sense since we do not use http signature authentication in our project. After some digging, I discovered that since the OAuth has been added, the method `serializeToString` was added to support http signature authentication and this method do not support "multipart/form-data". To fix it, I just added the `serializeToString` call when we support http signature authentication.
```
```  …
> Fix problem when uploading file using form-data in jersey2 client

- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfiguratorUtils.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/InlineModelResolverTest.java
- Add new option to customize inline model naming convention
e.g. ` --inline-schema-name-defaults arrayItemSuffix=_array_item` (the default is `_inner`)
Only arrayItemSuffix, mapItemSuffix are supported at the moment.
```
```  …
> Add new option to customize inline model naming convention

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- fix bugs when property name, datatype are the same
- test locally to confirm the fix
```
```  …
> [Java] fix bugs when property name, datatype are the same

- modules/openapi-generator/src/main/resources/C-libcurl/object-body.mustache
- modules/openapi-generator/src/main/resources/C-libcurl/object-header.mustache
- samples/client/petstore/c/model/object.c
- samples/client/petstore/c/model/object.h
The PR https://github.com/OpenAPITools/openapi-generator/pull/12069 adds the support for free-form objects. That is a very useful feature.
I'd like to submit the code on behalf of the author @harlequin-tech. So I picked up the two files and updated them according to my thoughts. 
```
``` 
For Windows …
> [C][Client] Support free-form objects

- modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache
- samples/client/petstore/typescript-angular-v12-oneOf/builds/default/api/default.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api/store.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-any/builds/default/api/user.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api/store.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default/api/user.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api/store.service.ts
- samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm/api/user.service.ts
- samples/client/petstore/typescript-angular-v13-oneOf/builds/default/api/default.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api/store.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default/api/user.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api/pet.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api/store.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default/api/user.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api/pet.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api/store.service.ts
- samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm/api/user.service.ts
The unused method doesn't pass stricter TS compiler settings (`noUnusedLocals`).
Tested by using the modified template as an override in project.
A similar change was made in #10713
```
``` 
> [ts-angular]: added ts-ignore directive to `addToHttpParams` to avoid compilation errors

- modules/openapi-generator/src/main/resources/Java/libraries/feign/api.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/resources/3_0/issue_7791.yaml
This change fixes the feign api template for form parameters.
These parameters should not use the `paramName` but rather the `baseName` as this is the name that will be used to create the fields in the form-data encoded body and therefore should match exactly the name declared in the specification.
```
``` 
For Windows users, please run …
> [JAVA][Feign] Remove camelCase naming for form parameters

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache
- modules/openapi-generator/src/test/resources/3_0/streaming.yaml
- samples/client/others/java/okhttp-gson-streaming/README.md
- samples/client/others/java/okhttp-gson-streaming/api/openapi.yaml
- samples/client/others/java/okhttp-gson-streaming/docs/PingApi.md
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/api/PingApi.java
Add streaming support in group parameters (useSingleRequestParameter=true to enable `x-group-parameters` in the operations)
```
``` 
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger …
> [java][okhttp-gson] Add streaming support in group parameters

- modules/openapi-generator/src/main/resources/C-libcurl/object-body.mustache
- samples/client/petstore/c/model/object.c
The PR https://github.com/OpenAPITools/openapi-generator/pull/12557 adds the support for the free-form object. When it is merged to the downstream project https://github.com/kubernetes-client/c, I received a comment https://github.com/kubernetes-client/c/pull/128#discussion_r898144002 that the default value for the null json should be `"null"` other than `"{}"`
cc  @harlequin-tech
```
``` 
You may regenerate an individual generator by passing the relevant config(s) as …
> [C][Client] Set the default value for the null json

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java
- modules/openapi-generator/src/main/resources/typescript-node/model.mustache
- Default enum value and type are seperated by .
- classname is added to enum default property
This is a fix for the bug mentioned here #12634.
I changed the default enum value to be <datatype>.<value>, and edited model.mustache template accordingly.
For testing I used the following yaml schema and generation command. I made sure that before the fix the client wasn't generated correctly and that the problem was solved after the fix.
Fixes #12634
Opeanapi schema:
```yaml
info:
version: "1.0.0"
title: "Test default enum value"
paths:
/eat:
post:
requestBody:
content:
schema:
$ref: "#/components/schemas/Fruit"
responses:
200:
description: "Yummy"
components:
schemas:
Fruit:
type: "object"
properties:
fruit:
type: "string"
enum: [
"melon",
"apple"
]
default: …
```
> fix typescript node default enum

- modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/mustache/CamelCaseLambda.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/mustache/CamelCaseLambdaTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/mustache/PascalCaseLambdaTest.java
- fix bugs (not handling spaces correctly) in camelcase lambda
- add tests for pascalcase
```
``` 
> Fix bugs in camelcase lambda, add tests for pascalcase

- modules/openapi-generator/src/main/resources/r/modelGeneric.mustache
- samples/client/petstore/R/R/special.R
- samples/client/petstore/R/tests/testthat/test_petstore.R
- fix deserialization for models with special item names: private, self, super
```
``` 
> [R] fix deserialization for models with special item names

- docs/generators/swift5.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift5ClientCodegen.java
- modules/openapi-generator/src/main/resources/swift5/modelObject.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/Swift5OptionsProvider.java
Fixes #12130
JSONEncodable is not a native type and does not exist if only models are generated. We use OpenAPI to generate only the models and none of the utils or other parts, so we need the generated models to be valid and able to compile as a stand-alone package.
```
```  …
> [swift5] Make it possible to opt out of JSONEncodable conformance

- docs/generators/cpp-qt-client.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQtClientCodegen.java
- modules/openapi-generator/src/main/resources/cpp-qt-client/helpers-body.mustache
- modules/openapi-generator/src/main/resources/cpp-qt-client/helpers-header.mustache
- samples/client/petstore/cpp-qt/client/PFXHelpers.cpp
- samples/client/petstore/cpp-qt/client/PFXHelpers.h
Fix #12641
The cpp-qt-client generator generates invalid code when the OpenAPI document contains AnyType objects (example: `type: {}`).
I have replaced `AnyType` with `QJsonValue`, so that the correct type can be manually unpacked later.
```
``` 
For Windows users, please run …
> [cpp-qt-client] Add support for AnyType objects

- modules/openapi-generator/src/main/resources/Java/libraries/feign/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit/ApiClient.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/ApiClient.mustache
Use triple curly braces to avoid URLs getting HTML-escaped in Java Code.
Fixed Java code generation, so this might be interesting for you: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)
To fix #12656 
```
```  …
> Fix HTML-escaped token and authorization URLs in Java libraries

- modules/openapi-generator/src/main/resources/r/modelAnyOf.mustache
- modules/openapi-generator/src/main/resources/r/modelOneOf.mustache
- samples/client/petstore/R/R/any_of_pig.R
- samples/client/petstore/R/R/pig.R
- samples/client/petstore/R/tests/testthat/test_petstore.R
- Add toString method to oneOf/anyOf objects for easier debugging.
- Fix toJSONString to return characters instead of json object
```
``` 
> [R] Add toString method to oneOf/anyOf objects

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
`typescript-fetch` provides support for two types of interceptors: to pre-process the request and post-process the response. However, there is one more case which is not handled - network or similar error when response is not received.
This PR suggests an additional interceptor hook `onError` that covers the missing piece. It is called in case of exception during request processing and allows to, for instance, re-try the request, replace it with alternative route, etc.
```
```  …
> [typescript-fetch] Support error handler in middleware

- samples/client/petstore/R/tests/testthat/test_petstore.R
- add tests for nested oneOf's fromJSONString method
```
``` 
> [R] add tests for nested oneOf's fromJSONString method

- modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/model.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/model.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/modelAnyOf.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/modelEnum.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
- modules/openapi-generator/src/main/resources/csharp-netcore/modelOneOf.mustache
- modules/openapi-generator/src/test/resources/3_0/csharp/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Model/GmFruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/src/Org.OpenAPITools/Model/NumberOnly.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Model/GmFruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/src/Org.OpenAPITools/Model/NumberOnly.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/GmFruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net47/src/Org.OpenAPITools/Model/NumberOnly.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/GmFruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/src/Org.OpenAPITools/Model/NumberOnly.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/GmFruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClient/src/Org.OpenAPITools/Model/NumberOnly.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/GmFruit.cs
- samples/client/petstore/csharp-netcore/OpenAPIClientCore/src/Org.OpenAPITools/Model/NumberOnly.cs
- add support for ComVisible `x-com-visible`, CLSCompliant `x-cls-compliant` attributes
- fix incorrect anyOf mustache tag
```
``` 
> [csharp-netcore] Add support for ComVisible, CLSCompliant attributes

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppUE4ClientCodegen.java
Fixed code generation for nested container type (list of lists / map of lists) for UE4.
@wing328 @Kahncode
Testcase for testing:
https://gist.github.com/madrazzl3/b2d9ab436b16fa82151816d31f73468b
Fix https://github.com/OpenAPITools/openapi-generator/issues/12746
```
```  …
> [BUG] [CPP-UE4] Fix codegen for nested container types

- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/ConfigHelp.java
- modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Generate.java
- modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenConfig.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfiguratorUtils.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCSharpCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractDartCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractEiffelCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractScalaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppRestSdkClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonExperimentalClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/AbstractKotlinCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/utils/ModelUtilsTest.java
Add schema mappings
To fix https://github.com/OpenAPITools/openapi-generator/issues/11506
```
``` 
> Add schema mappings

- modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pojo.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/resources/bugs/issue_12622.json
Fix for https://github.com/OpenAPITools/openapi-generator/issues/12622
```
```  …
> [Java][microprofile] fix constructor creation with readOnly & not required args

- modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache
- samples/client/petstore/typescript-fetch/builds/default-v3.0/runtime.ts
- samples/client/petstore/typescript-fetch/builds/default/runtime.ts
- samples/client/petstore/typescript-fetch/builds/enum/runtime.ts
- samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/multiple-parameters/runtime.ts
- samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/sagas-and-records/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-interfaces/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-npm-version/src/runtime.ts
- samples/client/petstore/typescript-fetch/builds/with-string-enums/runtime.ts
- samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/runtime.ts
We made a mistake in #12716 when implementing error handling interceptors - we fail in case of an error if interceptor returned an alternative response, although should have failed in the opposite case, when none of the interceptors could process the error.
This PR fixes the bug.
```
```  …
> [typescript-fetch] Fixing error handler in middleware

- modules/openapi-generator/src/main/resources/rust/reqwest/api.mustache
When a parameter is both required and nullable the code generate an `Option<&str>` parameters and then try to do a `to_string()` on this paramter which failed due to lack of to_string() implementation for `Option<&str>`.
An example of such issue can be found in https://developers.scaleway.com/static/c78c1fb6947abf78efab65d4acc6dacd/scaleway.baremetal.v1.Api.yml in function list-settings
@frol
@farcaller
@richardwhiuk
@paladinzh
```
``` 
Commit all changed files. 2484 …
> [Rust] fix for required nullable input generating invalid code

- docs/generators/haskell.md
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
- modules/openapi-generator/src/main/resources/haskell-servant/API.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/options/HaskellServantOptionsProvider.java
- samples/server/petstore/haskell-servant/lib/OpenAPIPetstore/API.hs
This PR makes it possible to use a [custom monad](https://docs.servant.dev/en/stable/tutorial/Server.html#using-another-monad-for-your-handlers) in the haskell-servant generator. Two examples that use 1) a custom monad and 2) a custom monad together with apikey auth are [here](https://github.com/7omb/openapi-generator-haskell-auth-examples). The separate option has the benefit that it is backwards compatible and easier to use when the option is disabled.
```
```  …
> Add option to use custom a monad

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/HaskellServantCodegen.java
This PR attempts to solve #9828. It should be in line with the OpenAPI specification:
> The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call.
and exclude the 2XX range response itself.
```
```  …
> Use the first status code in 2XX range, fallback to 200

- modules/openapi-generator/src/main/resources/php/model_generic.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/Model/FormatTest.php
model_generic.mustache: Display property name instead of its value,  when throwing InvalidArgumentException() for values not respecting a given pattern.
This is an old annoying bug: in 2016 the error message for this InvalidArgumentException() mas changed from single to double quotes, to allow patterns containing single quotes. This caused the "$" sign (plus the following property name) to be parsed, making the error message display its content, instead of its name (like in all other exception messages in this file). This PR fixes that by escaping the "$" sign.
```
```  …
> [PHP] Fix message for InvalidArgumentException(), when failing to test pattern

- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGenerateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorGeneratorsExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/extensions/OpenApiGeneratorValidateExtension.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GeneratorsTask.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/MetaTask.kt
- modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/ValidateTask.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/GenerateTaskDslTest.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/GeneratorsTaskDslTest.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/MetaTaskDslTest.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/TestBase.kt
- modules/openapi-generator-gradle-plugin/src/test/kotlin/ValidateTaskDslTest.kt
Fix typos, unused imports and formatting issues. Remove @Supress
annotations that are no longer necessary
Related to https://github.com/OpenAPITools/openapi-generator/pull/12719
```
``` 
> Gradle Plugin: Clean up Kotlin code

- modules/openapi-generator-maven-plugin/README.md
- modules/openapi-generator-maven-plugin/examples/kotlin.xml
- modules/openapi-generator-maven-plugin/examples/spring.xml
Fixed some types and copy&paste errors in the readme and some example pom.xml files. No code changes.
```
``` 
> Fix small documentation errors

- modules/openapi-generator-maven-plugin/README.md
The name of the configuration option "logToStderr" and parts of the description ("not just errors") imply that the messages are written into STDERR, not STDOUT, like the description tells. Therefore the description is fixed (no code changes).
```
``` 
> correct description for logToStderr configuration

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
The current implementation of the PHP client doesn't allow strings containing only white spaces (like `' '`) as values for enum, despite they being valid in OpenAPI specification (or, at least not forbidden). This is a fragment of Microsoft Business Central API for reading/posting a Journal Entry (I'm only showing the relevant field):
```
components:
schemas:
JournalEntry:
- type: object
properties:
'Document_Type':
type: string
enum:
- ' '
- 'Payment'
- 'Invoice'
- 'Credit Memo'
- 'Finance Charge Memo'
- 'Reminder'
- 'Refund'
default: ' '
```
Microsoft Business Central API **demands** the default value to be a string with exactly one space character inside it, otherwise it fails.
The current PHP generator sanitizes the enum options, removing all white spaces - even if the option contain …
> [PHP] Allow strings with only whitespaces in enums

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
@mkusaka 
Add support for schemaMappings to typescript client generator. See issue: https://github.com/OpenAPITools/openapi-generator/issues/12802
```
``` 
> [Typescript] support schemaMapping

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaCXFClientCodegen.java
- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java
- modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pojo.mustache
- modules/openapi-generator/src/main/resources/Java/libraries/native/pojo.mustache
- modules/openapi-generator/src/main/resources/Java/pojo.mustache
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/ConstructorAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/JavaFileAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/MethodAnnotationAssert.java
- modules/openapi-generator/src/test/java/org/openapitools/codegen/java/assertions/ParameterAssert.java
- modules/openapi-generator/src/test/resources/bugs/issue_12790.yaml
Fix for https://github.com/OpenAPITools/openapi-generator/issues/12790
```
```  …
> [Java] fix JsonCreator with JsonNullable

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java
Add schema mapping support to Go generators by adding schemaMapping in unaliasSchema calls
```
``` 
> Add schema mapping support to Go generators

- modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache
- samples/client/others/java/okhttp-gson-streaming/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-dynamicOperations/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-group-parameter/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/ApiClient.java
- samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/ApiClient.java
In the current generator for Java with okhttp-gson only `File` and `List<File>` parts were supported for `multipart/form-data` values. All other types were serialized to `String`. With the changes in this PR also `Object` and `List<Object>` types will be supported and serialized as JSON.
- #11289
```
``` 
For Windows users, please run …
> [java][okhttp-gson] Complex values in form data get serialized as JSON instead of String

- modules/openapi-generator/src/main/resources/r/api_client.mustache
- samples/client/petstore/R/R/api_client.R
Fix warning in roxygen2 due to missing @param
```
Warning: [api_client.R:38] Must use one @param for each argument
✖ $CallApi(stream_callback) is not documented
```
```
``` 
> Fix warning in roxygen2 due to missing @param

- modules/openapi-generator/src/main/resources/r/api_doc.mustache
- samples/client/petstore/R/docs/PetApi.md
Fix documentation on using stream_callback to stream data 
```
``` 
> [R] Fix stream_callback doc

- modules/openapi-generator/src/main/resources/Java/apiException.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/ApiException.mustache
- modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/ApiException.mustache
- modules/openapi-generator/src/main/resources/JavaSpring/apiException.mustache
- modules/openapi-generator/src/main/resources/android/apiException.mustache
- modules/openapi-generator/src/main/resources/android/libraries/volley/apiException.mustache
- modules/openapi-generator/src/main/resources/java-msf4j-server/ApiException.mustache
- samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/jersey1/src/main/java/org/openapitools/client/ApiException.java
- samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/ApiException.java
- samples/server/petstore/java-msf4j/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-datelib-j8/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-jersey/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-resteasy/java8/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs-resteasy/joda/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs/jersey1-useTags/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs/jersey1/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs/jersey2-useTags/src/gen/java/org/openapitools/api/ApiException.java
- samples/server/petstore/jaxrs/jersey2/src/gen/java/org/openapitools/api/ApiException.java
Previously, only the class name appeared in stacktrace whereas now
relevant details are added. This applies to most Java-related
generators.
```
``` 
> Java: Add `toString` method to ApiException

- modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
- samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php
This comes from a bug we found while dealing with the Tripletex API.
ObjectSerializer::deserialize()'s last `else` block instantiates an object of type `$class` and tries to populate it with the contents of `$data`. From this point on, `$data` is always handled as an object, as we check for its properties (`$data->{$discriminator}` or $data->{$instance::attributeMap()[$property]}.
But while working with Tripletex (and after a lot of debugging), we figured out that in some very specific cases the received `$data` parameter was an associative array, which then caused all properties from the instance to become empty.
This PR casts `$data` to object, in case it is an array. It is absolutely harmless, since it happens in the last `else` block (where we only care for an object anyway). It's …
> [PHP] ObjectSerializer::deserialize() associative arrays bugfix

- modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java
Fix circular reference in inline schema causing stack overflow error.
```
``` 
> Fix circular reference in inline schema

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PerlClientCodegen.java
- samples/client/petstore/perl/docs/FormatTest.md
- samples/client/petstore/perl/lib/WWW/OpenAPIClient/Object/FormatTest.pm
- Add decimal mapping in Perl client generator.
all tests passed locally:
```
ok 32 - accept_tokens() correctly set api_key
ok 33 - accept_tokens() correctly set api_key_prefix
ok 34 - accept_tokens() correctly set api_key_in
ok 35 - clear_tokens() returns the correct data structure
ok 36 - bad token causes exception
ok 37 - no (unexpected) warnings (via END block)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.460 s
[INFO] Finished at: 2022-07-17T13:01:51+08:00
[INFO] ------------------------------------------------------------------------
```
``` …
```
> Add decimal mapping in Perl client generator

- modules/openapi-generator/src/main/resources/cpp-ue4/api-operations-source.mustache
- samples/client/petstore/cpp-ue4/Private/OpenAPIPetApiOperations.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIStoreApiOperations.cpp
- samples/client/petstore/cpp-ue4/Private/OpenAPIUserApiOperations.cpp
Modify cpp-ue4 generator template to stop generating body writes for methods that are not PUT / POST / PATCH (using isBodyAllowed).
Fixes #12833 
@Kahncode
```
``` 
> [cpp-ue4] Fix GET request writes body

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
This PR adds memoization to Java **toModelName()** method.
```
```
This PR greatly reduces the time taken for Java code generation.
**toModelName()** method is invoked numerous times and it was accumulating a lot of time.
This has reduced the Java SDK …
> [JAVA] Optimize time taken to generate Java code

- modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
- modules/openapi-generator/src/test/resources/3_0/petstore-with-complex-headers.yaml
- samples/client/petstore/typescript-axios/builds/default/api.ts
- samples/client/petstore/typescript-axios/builds/es6-target/api.ts
- samples/client/petstore/typescript-axios/builds/test-petstore/api.ts
- samples/client/petstore/typescript-axios/builds/with-complex-headers/api.ts
- samples/client/petstore/typescript-axios/builds/with-fake-endpoints-models-for-testing-with-http-signature/api.ts
- samples/client/petstore/typescript-axios/builds/with-interfaces/api.ts
- samples/client/petstore/typescript-axios/builds/with-node-imports/api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api/api/another/level/pet-api.ts
- samples/client/petstore/typescript-axios/builds/with-npm-version/api.ts
- samples/client/petstore/typescript-axios/builds/with-single-request-parameters/api.ts
- samples/client/petstore/typescript-axios/builds/with-string-enums/api.ts
Serialization of complex headers was introduced in https://github.com/OpenAPITools/openapi-generator/pull/1874 .
However, a header value of type string/enum defined via `$ref` is serialized as well.
```js
JSON.stringify('foo') === '"foo"' // note the problematic extra quotes
```
The only (known to me) workaround is to use the last parameter of generated methods: `options: AxiosRequestConfig` where we can override all headers. A cumbersome solution.
This PR solves the problem of stringifying values that are already string.
Fixes https://github.com/OpenAPITools/openapi-generator/issues/10840
```
``` 
This is important, as CI jobs will verify _all_ generator outputs of your HEAD …
> [typescript-axios] avoid stringifying header string values

- modules/openapi-generator/src/main/resources/swift5/libraries/urlsession/URLSessionImplementations.mustache
When calling an api that returns an optional result, the generated swift 5 client with url session implementation tries to unwrap nil and crashes, in cases where the called endpoint actually returns no data. I think that this is due to the fact that it is never possible to cast Optional < T >.none to T. The solution implemented here is stolen from https://stackoverflow.com/questions/41492153/how-to-produce-a-nil-of-a-generic-type and it works for me.
You can reproduce this, for example, using the MoWeSta Api (https://www.mowesta.com/api/mowesta.json) using the api call that returns the nearest weather station for a city (/cities/{id}/station). If you call this with a city id that does not lie near Germany (e.g. Essen in Belgium, id: 81211), the api responds with 201 (success, no data) and …
> Fix npe when unwrapping optional in swift 5 client, if web server returns no data and client should return nil

- modules/openapi-generator/src/main/resources/JavaSpring/api.mustache
Fix erroneous code generation when `implicitHeaders=true` and `annotationLibrary=none`
Technical committee: @cachescrubber, @welshm, @MelleD, @atextor, @manedev79, @javisst, @borsch, @banlevente
```
``` 
> Fix spring implicitHeaders w/o annotationLibrary

- modules/openapi-generator/src/main/resources/typescript-nestjs/api.service.mustache
Check if `queryParameters` didn't get initialized, because `hasQueryParams` is false and if so initialize it when an apikey is used as a query parameter.
Fixes: #12938
```
``` 
> fix(typescript-nestjs): initialize `queryParameters` when needed

- modules/openapi-generator/src/main/resources/ruby-client/configuration.mustache
- samples/client/petstore/ruby-faraday/lib/petstore/configuration.rb
Thanks to @johngallagher Faraday middlewares are configurable now:
- #10495
In this PR, I'd like to enhance the Faraday middleware support to be able to call the [methods to push onto the various positions in the stack](https://github.com/lostisland/faraday/blob/v2.3.0/lib/faraday/rack_builder.rb#L117-L143) (`insert`, `insert_before`, `insert_after`, `swap`, and `delete`) and also to be able to pass a block to the methods.
```ruby
PetstoreAPI.configure do |config|
config.set_faraday_middleware(:request, :retry, max: 3, methods: [:get, :post], retry_statuses: [503])
config.set_faraday_middleware(:response, :logger, nil, { bodies: true, log_level: :debug })
config.set_faraday_middleware(:use, Faraday::HttpCache, store: Rails.cache, shared_cache: false)
config.set_faraday_middleware(:insert, …
```
> [Ruby] Enhance Faraday middleware support

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
Add model caching to Ruby client generator to improve execution time. This is useful when the spec is huge.
```
``` 
> Add model caching to Ruby client generator

- modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java
Add schema mapping support to ruby client generator. The feature is already supported by some other generators.
```
``` 
> Add schema mapping support to ruby client generator
